### ISSUE TITLE
escapeshellarg removes exclamation marks on Windows (native SSH)

### ISSUE THREAD

**Issue by ju5tify** [deployphp/deployer#1001]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | Windows 10
| Remote Machine OS | Ubuntu

### Description 
_escapeshellarg_ removes exclamation marks on Windows when using native ssh.
deploy:prepare and all other commands with `!` like `run('if [ ! -d {{deploy_path}} ]; then mkdir -p {{deploy_path}}; fi');` return invalid results.

**Comment by elfet** [comment]
So its bug with escapeshellarg func?

**Comment by ju5tify** [comment]
I dont' think so. Looks like it is [documented and expected](http://php.net/manual/ru/function.escapeshellarg.php) behavior for Windows

**Comment by elfet** [comment]
This is really strange. We need to find some solution for this.

**Comment by ju5tify** [comment]
It seems that escapeshellarg for *nix does only following:
- wraps string with single quotes
- escapes single quotes

I presume it can be done manually

**Comment by elfet** [comment]
It's have very strange behaviour on windows: https://github.com/php/php-src/blob/master/ext/standard/exec.c#L390

**Comment by elfet** [comment]
WTF? https://github.com/php/php-src/commit/a621781fdb733167f37027f02bf612696f892d07

> When delayed variable substitution is enabled (can be set in the
Registry, for instance), !ENV! works similar to %ENV%, and so ! should
be escaped like %.

**Comment by elfet** [comment]
Will not work with `SETLOCAL ENABLEDELAYEDEXPANSION` on windows. So we need to find another solution for this. Maybe use tmp files and cat script or write directly to stdin of ssh.

**Comment by ju5tify** [comment]
И все-таки.
Зачем тебе конкретно эта убогая функция? Весь смысл ее существования заключается в экранировании кавычек и оборачивании строки в другие кавычки. 
Мне кажется ее проще заменить на что-то вроде `return '"' . addcslashes($string, '"') . '"';`

**Comment by staabm** [comment]
@weltling any known workarround for escapeshellarg on windows when `!` should not be escaped?

**Comment by weltling** [comment]
@staabm that makes no sense, actually. These shell functions target different shells on different OSes. The command needs to be processed on the target system.

Thanks.

**Comment by elfet** [comment]
Found solution for windows. See #1092

**Comment by MrAidynShorts** [comment]
I know I'm a bit late on this, but depending on whether you need to include the exclamation mark, within the escapeshellarg function or not, I've simply been concatenating the exclamation mark to the escapeshellarg output, as follows.

`<?php`
`$a = Hello World";`
`$cmd = "tclsh C:/path/to/apache/htdocs/file.tcl " . escapeshellarg($a) . "!";`
`$output = shell_exec($cmd);`
`echo $output;`
`?>`

This obviously may not be valid, in many cases. 
However, I hope it helps a few others.
