### ISSUE TITLE
Failing upload with native SSH, from Windows to Windows.

### ISSUE THREAD

**Issue by ArminVieweg** [deployphp/deployer#1002]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | Windows 8
| Remote Machine OS | Windows Server 2013

### Description 
Uploading files does not work, with SSH native mode.

### Steps to reproduce
```
$local = 'C:\path\to\file.pdf';
$remote = '/c:/path/to/file.pdf';
\Deployer\upload($local, $remote);
```

### Output log
This will throw this exception:

```
[Symfony\Component\Process\Exception\ProcessFailedException]
  The command "scp -P "22" "C:\path\to\file.pdf" "admin@srv-hostname:/c:/path/to/file.pdf"" failed.
  Exit Code: 1(General error)
  Working directory: C:\path\to\
  Output:
  ================
  Error Output:
  ================
  ssh: Could not resolve hostname C: hostname nor servname provided, or not known
```

So the ssh command thinks "C:" would be a host. I can change the local path, with prepending a slash. SSH would work... but your local `is_file` and `is_dir` checks (in `\Deployer\upload`) will fail then.

When I change `ssh_type` to something else, which triggers PhpSecLib, it works.

**Comment by elfet** [comment]
So what is correct sap command for copy?

**Comment by ArminVieweg** [comment]
Padon? Is this question for me?

**Comment by elfet** [comment]
sorry, autocorrecting. What is correct scp command for Windows? `scp -P "22" "C:\path\to\file.pdf" "admin@srv-hostname:/c:/path/to/file.pdf"` or scp -P "22" "C:\path\to\file.pdf" "admin@srv-hostname:c:/path/to/file.pdf"

**Comment by ArminVieweg** [comment]
This works:
```
scp -P "22" "\Path\To\file.txt" "admin@srv-hostname:/C:/Path/To/file.txt"
```
So just get rid of the drive letter in windows. I guess it uses the current set drive letter.

**Comment by ArminVieweg** [comment]
Ah. I should mention, that I get this warning then:

```
cygwin warning:
  MS-DOS style path detected: \Dev\Iwm\mitarbeiterportal-relaunch\test.txt
  Preferred POSIX equivalent is: /cygdrive/c/Dev/Iwm/mitarbeiterportal-relaunch/test.txt
```
But it works.
With slashes instead of backslashes, no warning appears.

**Comment by antonmedv** [comment]
Fixed in master.
