### ISSUE TITLE
phar-update not a dev-dependency

### ISSUE THREAD

**Issue by KingCrunch** [deployphp/deployer#1005]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | Linux DELL-E5540-SEKR 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux
| Remote Machine OS | N/A

### Description 
`deployer/phar-updater` is a `require-dev`. I'd expect, that a development requirement is only required für development, but once I installed deployer with `composer --no-dev` deployer fails to do _anything_ at all.

Expectation: Deployer works even when installed with `composer --no-dev`.

### Steps to reproduce

```
~$ dep -vvv
```

### Content of `deploy.php`

N/A

### Output log

```
PHP Fatal error:  Uncaught Error: Class 'Deployer\Component\PharUpdate\Console\Helper' not found in phar:///usr/bin/dep/src/Console/Application.php:72
Stack trace:
#0 phar:///usr/bin/dep/vendor/symfony/console/Application.php(83): Deployer\Console\Application->getDefaultHelperSet()
#1 phar:///usr/bin/dep/bin/dep(99): Symfony\Component\Console\Application->__construct('Deployer', '4.2.1')
#2 /usr/bin/dep(4): require('phar:///usr/bin...')
#3 {main}
  thrown in phar:///usr/bin/dep/src/Console/Application.php on line 72
```

**Comment by elfet** [comment]
You are running phar version of deployer, not composer installed?

**Comment by KingCrunch** [comment]
@elfet Exactly. I find it ugly to mix tools with dependencies

**Comment by elfet** [comment]
Phar from deployer.org site contains this deps.

**Comment by KingCrunch** [comment]
@elfet Don't get my wrong, I simply want to understand

So it is intended, that a Phar created without _development_ dependencies is actually broken?

**Comment by elfet** [comment]
No, dev contains this package. What we can do is to check if class exists before adding it.

**Comment by KingCrunch** [comment]
I've seen your comment after I've created the pull request #1006 (which I've created, because I didn't want to complain only ;)). Sure, you can close it, but I'd still disagree. The package is used during production. This makes it a concrete requirement and not something to enhance development.

Additionally fetching _all_ the dev dependencies means many unused files in the phar. There are 29 packages in prod-setup, but 53 for development and only phpunit and phpspec are excluded from the phar. This makes the resulting phar 570kB bigger than necessary (still 3.3MB fell big somehow ...)

This said I'll leave it to you. No complains from me anymore :)
