### ISSUE TITLE
Call to undefined function set()

### ISSUE THREAD

**Issue by cpnadal** [deployphp/deployer#1006]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | Windows 10
| Remote Machine OS | Debian 8

### Description 
When sending command bin/dep deploy production2 with deployer version 4.2.1, I get this error "Call to undefined function set()". The same command is working on version 3.3.0.

### Steps to reproduce
Just launch the bin/dep command

### Content of `deploy.php`
```php
<?php
require 'recipe/symfony.php';

set('bin_dir', 'bin');

serverList('app/config/servers.yml');

set('repository', 'git@xxx');
set('shared_files', []);
set('shared_dirs', ['var/logs', 'var/cache', 'var/sessions', 'var/spool', 'web/uploads']);
set('clear_use_sudo', false);
set('clear_paths', ['current/update_apache', 'current/app/config/parameters.yml.dist', 'current/app/config/parameters_*.yml', 'current/app/config/servers.yml', 'current/app/config/config_*.yml', 'current/app/config/routing_*.yml']);
set('keep_releases', 3);
set('writable_dirs', [
    'var/cache',
    'var/logs',
    'web/uploads',
]);

```

### Output log
$ bin/dep -vvv deploy production2

Fatal error: Uncaught Error: Call to undefined function set() in C:\wamp\www\tpsonlinev2\deploy.php:4
Stack trace:
#0 C:\wamp\www\tpsonlinev2\vendor\deployer\deployer\bin\dep(109): require()
#1 C:\wamp\www\tpsonlinev2\vendor\deployer\deployer\bin\dep(110): {closure}()
#2 {main}
  thrown in C:\wamp\www\tpsonlinev2\deploy.php on line 4

**Comment by elfet** [comment]
https://github.com/deployphp/deployer/blob/master/UPGRADE.md
