### ISSUE TITLE
How to configure git repository to other port ?

### ISSUE THREAD

**Issue by Hesiode** [deployphp/deployer#1009]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
How to configure git repository to other port ?

Something like :
set('repository', 'git@domain.com:user/path.git:28');

thank you

**Comment by pluseg** [comment]
@Hesiode hi! Try to use repo link in format `ssh://user@domain.com:28/path/to/repo.git`.

**Comment by pluseg** [comment]
@Hesiode did it help?

**Comment by Hesiode** [comment]
Perfect :  git+ssh://xxx@xxx.xxxxxx.xx:28/xxxx/xxxx/xxxxxx
Thank you !
