### ISSUE TITLE
NativeSsh should allow HostKeyCheck

### ISSUE THREAD

**Issue by pniederlag** [deployphp/deployer#1011]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | 4.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*Native SSHImplementation (shell out to ssh command) shall be the default starting from deployer 5.1, as per #980 *

Currently NativeSsh-Connection has hardcoded the flag "StrictHostKeyChecking=no". This disables a useful security feature. (https://github.com/deployphp/deployer/blob/master/src/Server/Remote/NativeSsh.php#L54)

There should be an option to make this feature configurable.

**Comment by elfet** [comment]
Done in #1092 
```php
host('198.168.10.01')
    ->options([
        'StrictHostKeyChecking=no'
    ]);
```
