### ISSUE TITLE
NativeSsh, improve user experience for connection failures

### ISSUE THREAD

**Issue by pniederlag** [deployphp/deployer#1012]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.2.1
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*As suggested I switched to the native ssh connection via set('ssh_type', 'native')*

When I do have an error in the setup that prevents a succesfull (ssh-)connection the error shown for the native-ssh implementation is very irritating. 

### Steps to reproduce

* add some invalid server configuration
* try to run an arbitrary task on this server
* EXCEPTION  [RuntimeException]                              
  Unable to login with the provided credentials is clear to me.
* switch to native ssh implementation as the warning suggests
* EXCEPTION: [Symfony\Component\Process\Exception\ProcessFailedException] is irritating for me

### Content of `deploy.php`
```php
// compat with php < 5.6
namespace Deployer;

use Symfony\Component\Console\Input\InputArgument;

//
require 'recipes/rsync.php';

argument('stage', InputArgument::OPTIONAL, 'Run tasks only on this server or group of servers');

//set('ssh_type', 'native');
//set('ssh_multiplexing', true);

// Configuration
serverList('servers.yml');

desc('Say Hello');
task('say_hello', function () {
     writeln('Hello');
     run("pwd");
});%  
```

**Comment by elfet** [comment]
Done.
