### ISSUE TITLE
Implement task ssh for connecting to server

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1013]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next

Implement task `dep ssh [server]` for opening ssh shell to remote server and cd to `deploy_path`.

**Comment by pluseg** [comment]
@elfet as I know you are going to support only Native SSH in the nearest future, right? I have a good solution for Native SSH and I'm not sure do we need to implement same functionality for other ssh connection methods if they will be cut? What do you think?

**Comment by elfet** [comment]
Only for native ssh is okay. in v5 two other will be droped.

**Comment by antonmedv** [comment]
📦 Done in #1092
