### ISSUE TITLE
Add option to use `sudo` when cleaning up old releases

### ISSUE THREAD

**Issue by gwagroves** [deployphp/deployer#1014]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Add an option to use `sudo` when cleaning up old releases.

Clean up fails if the deployment user does not have the appropriate permissions to remove files created, for example, by Apache.

**Comment by elfet** [comment]
Can you use `deploy:writable` task for correcting permissions on folder while deploying?

**Comment by snowiow** [comment]
I needed exactly the same feature, because runtime files were written by the webserver and clean as the normal ssh user didn't work because I had not enough rights. So I've rewritten the original clean task and added a sudo option like in the writable task:
```php
task('cleanup:custom_project', function () {
    $releases = get('releases_list');
    $sudo = get('cleanup_use_sudo') ? 'sudo' : '';
    $keep = get('keep_releases');
    if ($keep === -1) {
        // Keep unlimited releases.
        return;
    }
    while ($keep - 1 > 0) {
        array_shift($releases);
        --$keep;
    }
    foreach ($releases as $release) {
        run(sprintf('%s rm -rf {{deploy_path}}/releases/%s', $sudo, $release));
    }
    run('cd {{deploy_path}} && if [ -e release ]; then rm release; fi');
    run('cd {{deploy_path}} && if [ -h release ]; then rm release; fi');
})->desc('Cleanup of older releases with sudo option');
```
Hope it's of any help. Maybe it can be added to the real cleanup task?

**Comment by kslimani** [comment]
👍 same issue here, a sudo flag may be usefull.

**Comment by antonmedv** [comment]
Done!

**Comment by afilina** [comment]
For those unsure about what "done" means here, you can now specify this option to use sudo during the cleanup task:
`set('cleanup_use_sudo', true);`
