### ISSUE TITLE
Deploying from root user, as another user

### ISSUE THREAD

**Issue by krve** [deployphp/deployer#1018]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

Is it possible to deploy to a server, as another user then the one you SSH in as? The reason I'm asking is because in my current setup, it would be easier if I could use one user for the SSH, and then just `su - deployuser` and then deploy. 

This means I don't have to add my SSH-key to every single user I want to deploy as.

I've tried to create a task and run `su - deployuser` but that doesn't seem to work.

**Comment by elfet** [comment]
That's not possible for now, but definitely will be in next Deployer v5.

**Comment by antonmedv** [comment]
Done in 5 beta

**Comment by ivoba** [comment]
How does this work?

**Comment by antonmedv** [comment]
https://deployer.org/docs/hosts#become

**Comment by alek-s-andr** [comment]
@antonmedv How can do it in version 7? Is it possible now?

**Comment by antonmedv** [comment]
Set become on host.

**Comment by alek-s-andr** [comment]
I have tried specify the param **become**
`host('staging')->set('become', 'user_name')`
and it is working, thank you!
