### ISSUE TITLE
Decouple SSH forwarding and authentication type

### ISSUE THREAD

**Issue by msbit** [deployphp/deployer#1023]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | v4.2.1
| Local Machine OS  | macOS 10.12.3
| Remote Machine OS | Ubuntu 16.04.2 LTS

I have a situation where I am deploying to a server that I authenticate with via PEM file, but the repository is accessed via a different SSH key. It would be nice to decouple the authentication method from the forwarding setting, right now calling:

```
server(...)
  ->pemFile(...)
  ->forwardAgent()
```

would result in the PEM file being ignored, and:

```
server(...)
  ->forwardAgent()
  ->pemFile(...)
```

would result in forwarding not being enabled.

**Comment by elfet** [comment]
Yes, this is known issue with phpseclib. I'm definitely planning to fix it in next Deployer v5 with migration on only native ssh.

**Comment by msbit** [comment]
@elfet okay cool

**Comment by elfet** [comment]
Done in #1092
