### ISSUE TITLE
Native SSH with password auth

### ISSUE THREAD

**Issue by adminDev361** [deployphp/deployer#1024]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question

### Description 
Hello,
I had this message recently after update my deployer file:

```
Warning: ssh type `phpseclib` will be deprecated in Deployer 5.
Add this lines to your deploy.php file:
    set('ssh_type', 'native');
    set('ssh_multiplexing', true);
```

So I did it, I added these two line and stop use phpseclib.
But now authentification with password doesn't work:
```
server-name:
    host: ****
    user: ****
    password: ********
```
At deploy, it ask me password.
When I put "set('ssh_type', 'phpseclib');" it work again fine

**Comment by elfet** [comment]
Looks like a bug. Will fix it in next v5. Try to use identity key files.

**Comment by mbardelmeijer** [comment]
Got the same issue, but unable to move to identify key files at the moment due to backend infra. Any idea when a fix for this will be released?

**Comment by elfet** [comment]
Passwords for what? Please show full example of deploy.php and dep deploy -vvv

**Comment by adminDev361** [comment]
Sorry, It is the password for ssh access, dep deploy -vvv show only this sentense:
****SSHP@***.***.***.***'s password:
And wait for me to enter password, but I repeat, I fill password yaml line and it work when "set('ssh_type', 'phpseclib');" is set.

**Comment by elfet** [comment]
Please, show content of your `deploy.php` file.

**Comment by mbardelmeijer** [comment]
Debugged the issue a bit further, when password authentication is used the password isn't send to the multiplexing 'ssh' call, which prompts for a password because it cannot authenticate without one.

Only solution that i know of is to use 'sshpass' here, but that's a system dependency. Perhaps prompt the user if password authentication is used and 'sshpass' isn't installed to install it?

Hereby my (simplified) deploy file. Tested it with this, issue remained the same.

```
<?php

namespace Deployer;

require_once 'recipe/common.php';

set('ssh_type', 'native');
set('ssh_multiplexing', true);

server('production', 'hostname', 2222) // custom port
   ->user('USER')
   ->password('PASSWORD')
   ->stage('production')
   ->set('deploy_path', '/home/USER/domains/domain.com');

set('repository', 'REPO');
set('keep_releases', 2);

task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'cleanup',
]);
```

**Comment by elfet** [comment]
> password isn't send to the multiplexing 'ssh' call

Maybe send password on that call?

**Comment by mbardelmeijer** [comment]
It isn't possible to send the password to the `ssh` command, you must use a utility like `sshpass` for that, but a user needs to install that.

To clearify, it isn't just with multiplexing. If multiplexing is disabled the same issue is there, due to the `ssh` call at https://github.com/deployphp/deployer/blob/master/src/Server/Remote/NativeSsh.php#L86

**Comment by elfet** [comment]
I see. Well, sshpass does not seems good solution. Maybe write from php to stdin of ssh?

**Comment by mbardelmeijer** [comment]
Isn't possible to pass the password trough stdin unfortuality due to the way this interactive prompt works.

However, found another solution, but i don't think should be implemented due to the security implications: https://www.linkedin.com/pulse/youre-doing-wrong-ssh-plain-text-credentials-robert-mccurdy?trk=mp-reader-card

What do you think? @elfet

**Comment by reissr** [comment]
Same issue for me as well.. I'm unable to log into our server with username and password (which I prefer at the moment, instead of ssh keys..).
Any workaround? (e.g. use another ssh_type?)

**Comment by elfet** [comment]
I found solution for using ssh with password. It will be next deployer release, for more info #1092

**Comment by houstona** [comment]
`Host('host')->password('password')`

Does not work. I get the following message:

>  [Error] Call to undefined method Deployer\Host\Host::password()

**Comment by antonmedv** [comment]
host haven't password method.

**Comment by pulselife** [comment]
What can I use instead of **->password('password')** ?

**Comment by antonmedv** [comment]
@pulselife deployer will ask you about password on deploy.

**Comment by apopescu-im** [comment]
@antonmedv That does not seem to be the case (v 5.1.3).  This is what I get.  It apparently tries a couple times (perhaps using my `%USERDATA%/.ssh/id_rsa` which would not work for this user/server) but it never prompts for password

```
λ dep deploy ****
➤ Executing task deploy:prepare
✔ Executing task deploy:failed
➤ Executing task deploy:unlock


  [Deployer\Exception\RuntimeException]
  The command "rm -f /opt/****/.dep/deploy.lock" failed.
  Exit Code: -1 (Unknown error)
  Host Name: ****
  ================
  Permission denied, please try again.
  Permission denied, please try again.
  Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).


deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]
```

**Comment by Erim32** [comment]
Any update ?

**Comment by antonmedv** [comment]
Please reopen issues.

**Comment by jan-wilhelm** [comment]
What happened here? I am getting the same error!

**Comment by antonmedv** [comment]
Can’t tell with out more info

**Comment by antonmedv** [comment]
Use ssh-agent

**Comment by fnkr** [comment]
Here is my solution using sshpass, works fine:

`deploy.php`:
```php
putenv('PATH=' . __dir__ . '/.ci/deployment/bin:' . getenv('PATH'));
```

`.ci/deployment/bin/ssh` (must be executable, `chmod a+x .ci/deployment/bin/ssh`):
```bash
#!/usr/bin/env bash
set -e -u -o pipefail
# shellcheck disable=SC2230
ssh="$(which -a ssh | grep -Fxv -m 1 -- "$(dirname -- "$0")/ssh")"
sshpass -p "$SSH_PASSWORD" "$ssh" -o PubkeyAuthentication=no "$@"
```

```
SSH_PASSWORD='<password>' ./deployer.phar ...
```
