### ISSUE TITLE
Cannot deploy on WIN10 - SSH error

### ISSUE THREAD

**Issue by ladislavsulc** [deployphp/deployer#1030]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug / Question
| Deployer Version  | Latest stable via Composer Require
| Local Machine OS  | WIN10
| Remote Machine OS | Linux (Debian)

### Description 
Hi, I am a newbie with Deployer and so with DevOps/PHP so please keep that in mind :) I have a fully working Open SSH on WIN 10 with CMDer. I can easily SSH to any server with my SSH keys from my "terminal". No matter what I try to put in the deploy.php I always get this error. I also have a working ssh agent.

I tried:
* regular password + username
* SSH config
* IdentityFile
* a different server
* adjusting the path to SSH keys

Every time I get the error down in the screenshot:
**Shell on your server is not POSIX-compliant. Please change to sh, bash or similar.
  Usually, you can change your shell to bash by running: chsh -s /bin/bash**

### Steps to reproduce
My command: `.\vendor\bin\dep deploy staging`

Error screen: http://i.imgur.com/EHFZGDD.png

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/common.php';

// Configuration

$branch = 'master';

set('ssh_type', 'native');
set('ssh_multiplexing', true);

set('shared_files', ['wp-config.php']);
set('shared_dirs', ['wp-content/uploads']);
set('writable_dirs', ['wp-content/uploads']);

// Servers

server('staging', 'xxx', '22')
    ->user('xxx')
    ->identityFile('~/.ssh/id_rsa', '~/.ssh/id_rsa', 'xxxx')
    ->forwardAgent()
    ->set('deploy_path', '/home/master/applications/wordmove/public_html');

set('repository', 'xxx.git'); // Repository to deploy.
set('branch', $branch);

// Tasks

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
*With enabled option for verbose output `-vvv`.*
http://i.imgur.com/EHFZGDD.png

Any kind of help is highly appreciated. I am trying to deploy a simple Wordpress installation on Cloudways before learning more advanced stuff (Composer install, atomic deployment). Guess I haven't gone so far .)

Thanks!

**Comment by elfet** [comment]
Hi, looks like when you connect to server via ssh its logon not bash. Try to run this command on server via ssh: echo $0

**Comment by ladislavsulc** [comment]
@elfet Hi, thanks for the reply. No, on the server there is bash. I tried what you said: /bin/bash is the result.

Any other idea? Regular ssh from terminal works (using open ssh).

Thank you.

**Comment by AnatolyRugalev** [comment]
Same problem here.

**Comment by antonmedv** [comment]
Fixed in master.
