### ISSUE TITLE
Git clone fails with ssh multiplexing

### ISSUE THREAD

**Issue by sanderfreshheads** [deployphp/deployer#1031]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1
| Local Machine OS  | OSX Sierra
| Remote Machine OS | Ubuntu 16.04

### Description 
When I run the deploy.php script it fails on the git clone command. If I run the command that you get from the error output the command is successful.

### Steps to reproduce

1. run: php vendor/bin/dep install:production -vvv
2. copy failed command from error output
3. past en run command in terminal

example command:
ssh -A -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/deployer_mux_s
  ander@37.97.xxx.xx:22' -p '22' -i '/Users/sander/.ssh/sanderlissenburg@gmail.com' 'sander@37.97.xxx.xx' 'cd www && (git clone git@github.com:sanderlissenburg/movi
  es-api.git)'

### Content of `deploy.php`
```php
<?php

namespace Deployer;

require 'recipe/common.php';

set('ssh_type', 'native');
set('ssh_multiplexing', true);
set('default_stage', 'production');

// I anonymised my ip adress
server('production', '37.97.xxx.xx')
    ->user('sander')
    ->identityFileAndPassword('~/.ssh/sanderlissenburg@gmail.com.pub', '~/.ssh/sanderlissenburg@gmail.com', null, null)
    ->stage('production')
;


task('install:production', function() {
    writeln('<info>Deploying...</info>');
    cd('www');
    $response = run('pwd');
    writeln($response);

    // I know this is not the best way to do a clone with deployer
    $response = run('git clone git@github.com:sanderlissenburg/movies-api.git');
});

```

### Output log
```
[production] < /home/sander/www
/home/sander/www

[production] > cd www && (git clone git@github.com:sanderlissenburg/movies-api.git)
  SSH multiplexing initialization


  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "ssh -A -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/deployer_mux_s
  ander@37.97.xxx.xx:22' -p '22' -i '/Users/sander/.ssh/sanderlissenburg@gmail.com' 'sander@37.97.xxx.xx' 'cd www && (git clone git@github.com:sanderlissenburg/movi
  es-api.git)'" failed.
  Exit Code: 128(Invalid exit argument)
  Working directory: /Users/sander/docker/www/movies-api
  Output:
  ================
  Error Output:
  ================
  Cloning into 'movies-api'...
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.


Exception trace:
 () at /Users/sander/docker/www/movies-api/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:233
 Symfony\Component\Process\Process->mustRun() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/Server/Remote/NativeSsh.php:87
 Deployer\Server\Remote\NativeSsh->run() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/functions.php:310
 Deployer\run() at /Users/sander/docker/www/movies-api/deploy.php:25
 Deployer\{closure}() at n/a:n/a
 call_user_func() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/Task/Task.php:85
 Deployer\Task\Task->run() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/Console/TaskCommand.php:95
 Deployer\Console\TaskCommand->execute() at /Users/sander/docker/www/movies-api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /Users/sander/docker/www/movies-api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at /Users/sander/docker/www/movies-api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /Users/sander/docker/www/movies-api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/src/Deployer.php:186
 Deployer\Deployer->run() at /Users/sander/docker/www/movies-api/vendor/deployer/deployer/bin/dep:114

install:production [-p|--parallel]
```

**Comment by sanderfreshheads** [comment]
I managed to get it working. I removed **set('ssh_multiplexing', true);**. Although when you omit set('ssh_type', 'native'); you get a warning that says add **set('ssh_type', 'native');** and **set('ssh_multiplexing', true);**

```
Warning: ssh type `phpseclib` will be deprecated in Deployer 5.
Add this lines to your deploy.php file:

    set('ssh_type', 'native');
    set('ssh_multiplexing', true);

More info here: https://goo.gl/ya8rKW
```

Can someone explain why removing this fixes the problem?

**Comment by elfet** [comment]
Try to clone your repo via ssh on server. Check what forward agent is confgured.

**Comment by sanderfreshheads** [comment]
Cloning via ssh on the remote server is succesfull and yes its using my forwarded ssh keys. The only problem I have now is that **ssh_multiplexing** is not working. For now I can disable it.

**Comment by j3j5** [comment]
I have the same problem. When I am logged in on a server with a forwarded key, I can't deploy from there, but I can clone all my repos with no problem.

Only removing `set('ssh_multiplexing', true);` works with no problem.

**Comment by elfet** [comment]
@j3j5 so in native ssh but without multiplexing all works? 

Maybe a bug with forwarding and multiplexing.

**Comment by j3j5** [comment]
It looks like it. Let me know if I can help debugging it or provide with any more info!

**Comment by elfet** [comment]
Please, show full log of `dep deploy -vvv`

**Comment by j3j5** [comment]
Here it is:
[deploy.txt](https://github.com/deployphp/deployer/files/816951/deploy.txt)

**Comment by mathieu-gilloots** [comment]
Same Here :(

**Comment by elfet** [comment]
> Permission denied (publickey).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.

Please check what ssh agent is working, or use deploy keys.

**Comment by j3j5** [comment]
What do you mean with _what ssh agent is working_? 

Where can I read a bit more about what enabling multiplexing does? I'm willing to help fixing this issue (if possible), otherwise, you may want to add some extra text on the warning for deployer5, since adding `set('ssh_multiplexing', true);` breaks an existing workflow that used to work with phpseclib.

**Comment by elfet** [comment]
Does ssh agent working locally? Try run it:ssh server git clone http...

**Comment by j3j5** [comment]
Running `ssh -A server 'git clone...'` works just fine.

**Comment by elfet** [comment]
Can you activate multiplexing by hands and run this command again.

**Comment by j3j5** [comment]
I'm trying the command as seen on the error message, this seems to work as well:

`ssh -A -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/deployer_mux_deploy@web03.myserver.com:22' -p '22' 'deploy@web03.myserver.com' '/usr/bin/git clone  --recursive -q git@gitlab.myserver.com:projects/myproject.git ~/myproject-testing'`

**Comment by elfet** [comment]
What is strange, because dep only run this command. Nothing more.

**Comment by j3j5** [comment]
So I've been debugging and it seems that using `exec()` instead of Symfony's `Process` class [here](https://github.com/deployphp/deployer/blob/v4.2.1/src/Server/Remote/NativeSsh.php#L83) seems to fix it, so it has something to do with the way that class executes the command. I'm not really familiar with the class so I can say much more for now.

**Comment by elfet** [comment]
There is simple git proc_open call.

**Comment by j3j5** [comment]
Is there anything else I can do to help fixing this before the next release? 

Do you think the bug comes from upstream? 

My guess is that the `SSH_AUTH_SOCK` variable isn't being shared when the `proc_open` call is made but I'd have to debug to be sure.

**Comment by elfet** [comment]
@j3j5 do you use agent forwarding or deploy keys? If deploy keys do you have passphrase on it?

**Comment by j3j5** [comment]
I'm using agent forwarding, the setup is somewhat as follows:

[Keys are here]                        [Agent Forward]
|Local machine| ---`SSH`----> |Dev       Server| ---`dep deploy`---> |Prod Server|

**Comment by elfet** [comment]
>| Dev   Server | ---dep deploy---> |Prod Server|

Here also agent forwarding?

**Comment by j3j5** [comment]
Yes, also agent forwarding, my `deploy.php` would look something like
```
server('production', 'web01.myserver.com')
    ->user('deploy')
    ->forwardAgent()
```
And as mentioned above, `ssh -A [...] 'git clone ...` works as expected from dev to prod.

**Comment by elfet** [comment]
Can tell why this is does now working. Will try to implement same env by myself. You can use deploy keys for now.

**Comment by j3j5** [comment]
The odd thing is, when I'm not using `ssh_multiplexing` everything works fine (albeit a little slower). It's what I'm using now, but it's pretty weird. Let me know if I can help with anything, I've tried to debug it but so far didn't really get anything.

**Comment by elfet** [comment]
It should work with multiplexing, probably a bug

**Comment by pryley** [comment]
I have the same issue. Everytime it happens I have to do the following to temporarily fix it

`Permission denied (publickey).`

1. Run the command from the error in a new terminal (using -vvv):
```sh
ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/deployer_mux_user@domain.com:1234' -p '1234' -i '/Users/me/.ssh/domain_rsa' 'user@domain.com'
```
When running the command, I get the following warning: 

`Warning: Permanently added '[domain.com]:1234,[11.22.33.225]:1234' (ECDSA) to the list of known hosts.`

I am then logged in to the server.

2. Go back to the previous Terminal and re-run deployer.

This time it works, however if I logout of the server and try to run deployer again a short time later, the problem repeats itself and I have to repeat the steps above.

My `server.yml` looks something like this:
```yml
staging:
    host: domain.com
    port: 1234
    user: user
    identity_file:
        public_key: ~/.ssh/domain_rsa.pub
        private_key: ~/.ssh/domain_rsa
        password: mysshkeypassword
    forward_agent: true
    stage: staging
    branch: master
...
```

My `config.yml` looks something like this (see: #1108):
```yml
composer_action: update
default_stage: staging
keep_releases: 5
public_dir: public
repository: git@bitbucket.org:myapps/myapp.git
shared_dirs:
    - app/uploads
shared_files:
    - public/.htaccess
    - public/robots.txt
ssh_multiplexing: true
ssh_type: native
uploads_dir: shared/app/uploads
writable_dirs:
    - app/uploads
writable_mode: chmod
...
```

**Comment by barryvdh** [comment]
I might be off here, but I had similar problems. But I think they were related to a different command failing, and the `ssh UserKnownHostsFile` error was not actually the problem. (But I could be wrong)

I also tried starting ssh-agent manually + adding the key

```
eval "$(ssh-agent -s)"
ssh-add
```

**Comment by antonmedv** [comment]
Now deployer supports tty. Add this `set('git_tty', true);`

**Comment by antonmedv** [comment]
@vasilvestre working for me with 5.1.3

**Comment by vasilvestre** [comment]
@antonmedv not for me, with that :

**Comment by dimkasta** [comment]
For host(), it worked for me only with IP being the only param in the function.
and I am passing only the private key
Passphrase is sent through ssh-add in bash
