### ISSUE TITLE
Failed opening built-in recipe from phar archive

### ISSUE THREAD

**Issue by andrespoder** [deployphp/deployer#1032]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| PHP Version | PHP 7.0.15 (cli)
| Local Machine OS  | Linux
| Remote Machine OS | Linux

### Description 

Getting fatal error when running deployer phar. See details below.

Probably because `phar://`contains a colon and include path separator is also a colon.

### Steps to reproduce

```
$ dep
```

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/common.php';
```

### Output log
```
Fatal error: require(): Failed opening required 'recipe/common.php' (include_path='phar:///data01/virt62570/bin/dep/bin/../:.:/opt/zone/lib64/php70/php-pear') in /data01/virt62570/deploy/cdn/deploy.php on line 4
```

**Comment by andrespoder** [comment]
```
$ php -r "echo PATH_SEPARATOR;"
:
```

```
$ php -r "echo get_include_path();"
.:/opt/zone/lib64/php70/php-pear
```

**Comment by elfet** [comment]
I'm also have `:` as path separator, phar works fine. Can you try to include recipe via full path?

**Comment by andrespoder** [comment]
This works:
`
require 'phar:///data01/virt62570/bin/dep/recipe/common.php';
`
instead of 
`require 'recipe/common.php';`

But such deploy.php is not usable when deployer is installed with composer.

**Comment by elfet** [comment]
This is really strange, how to specify phar schema in not with ://?

**Comment by andrespoder** [comment]
I haven't found any such bug reports except this:

https://bugs.php.net/bug.php?id=61317

I guess it's something environment specific. Solution could be using full paths everywhere and not include_path.

E.g require DEPLOYER_DIR . '/recipe/common.php';

**Comment by pluseg** [comment]
@elfet I guess the ticket is done.

**Comment by kanevbg** [comment]
Experiencing this same issue. Installed deployer with
```
curl -LO https://deployer.org/deployer.phar
mv deployer.phar /usr/local/bin/dep
chmod +x /usr/local/bin/dep
```

![image](https://user-images.githubusercontent.com/11477130/53298799-9117e900-383b-11e9-82f7-c2a75b6ea631.png)

I have checked the "dep" binary file permission and even tried with root user so it seems to be not related to permissions.

In my environment /usr/bin/php is symlink to needed PHP binary if that can be anyhow related.

**Comment by kanevbg** [comment]
changing
```require 'recipe/common.php';```
to
```require 'phar:///usr/local/bin/dep/recipe/common.php';```
fixes the issue

**Comment by antonmedv** [comment]
I have plans to fix and simplify recipes for next LTS v7. Will much simplier.

**Comment by Guave-Mattias** [comment]
I my case I used:
```
require 'phar://' . __DIR__ . '/deployer.phar/recipe/symfony4.php';
```
My deployer.phar is in the same directory as my deploy.php recipe. If that is the case for you as well, this will fix the problem.

**Comment by Aquive** [comment]
For future Googlers: weird enough changing

`require`

to 

`require_once`

Fixed it for me.
