### ISSUE TITLE
FR: log full debug output to file

### ISSUE THREAD

**Issue by karakum** [deployphp/deployer#1039]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
It would be better if command `dep deploy production` write full debug output to file like `dev -vvv deploy production` does on stdout. 
For daily usage i don't want call with `-vvv`, but it need on errors. You say 'There are full exception output!'. Yes, but I wanna have all comand history from deploy start, not only last one failed.

Thanks for deployer!

**Comment by pluseg** [comment]
@karakum Hi! What's about using shell redirection of standard streams? E.g. `dep task > log.txt 2>&1`. By same way you can separate common logs and errors. Does it work for you?

**Comment by elfet** [comment]
> By same way you can separate common logs and errors.

This is only redirection for stdout. I'm think it will be cool to have `--log` option:

```
dep deploy --log deploy.log
```

In stdout – normal output, in deploy.log – debug output (same as with -vvv).

**Comment by antonmedv** [comment]
Done in v5 `--log`
