### ISSUE TITLE
Bad return code for failed deployements

### ISSUE THREAD

**Issue by GaryPEGEOT** [deployphp/deployer#1045]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | Ubuntu Linux
| Remote Machine OS | Debian

### Description 
When deployement fail, deployer return a 0 code. To be used by continuous integration tools, the return code should be != from 0 when something went wrong. 

### Steps to reproduce
* Deploy a project
* Trigger any failure
* Check status code (`echo $?` on UNIX systems)
### Content of `deploy.php`
*Not relevant* 

### Output log
*Not relevant*

**Comment by bacbos** [comment]
👍

**Comment by mbrodala** [comment]
I cannot confirm this. If an error occurs in any task, the deployment stops and deployer exits with a non-zero code. Can you post your `deploy.php` and a deploy log with `-vvv` which shows an error followed by `echo $?`?

**Comment by GaryPEGEOT** [comment]
My mistake, after update return code is fine !

Sorry for false alert.

**Comment by bacbos** [comment]
Same here, sorry for that, I realized I wasn't using the latest version.
I guess the issue can be closed.
