### ISSUE TITLE
File watcher for Deployer

### ISSUE THREAD

**Issue by ArminVieweg** [deployphp/deployer#1046]
Hey Folks,

I've experimented a little bit with Deployer and a composer package called [jasonlewis/resource-watcher](https://packagist.org/packages/jasonlewis/resource-watcher).

I did a demo video gif:
![Deployer File Watcher](https://i.imgur.com/sWOZndn.gif)

And [here you find the deploy.php file](https://bitbucket.org/ArminVieweg/dce/src/d8bd0fe7d0df9d8ad28dcdcd6e936f23c300f03e/deploy.php?at=master&fileviewer=file-view-default) with all necessary contents.

Have fun! 😎

**Comment by elfet** [comment]
Really cool. This is very interesting way of using deployer? Why don't you write a post about this? For example on medium? Will be interesting to read.

**Comment by ArminVieweg** [comment]
I've seen many workflows which include uploading files to a remote (dev-)server. This makes it a lot easier for developers to step into an existing project. 

Like take this TYPO3 CMS extension I've written for example. Check it out. Run `vagrant up`, start `dep watch` and happy developing :)

**Comment by pluseg** [comment]
Looks interesting, but I don't know real use cases for this functionality... For example `gulp` has `watch` command already.

Events `modify`, `create`, and `delete` aren't applicable for uploading as for me. Usually you want to sync only concrete state of a file, not each modification.

**Comment by tuupola** [comment]
FWIW I have good experiences with [entr](http://entrproject.org/) which is a unixy approach for the same task. To watch local files and upload them to remote server if anything changes you could do something like:

```
$ ls -d * | entr rsync -a . username@example.com:/tmp
```
