### ISSUE TITLE
Broken Scrutinizer tests

### ISSUE THREAD

**Issue by pluseg** [deployphp/deployer#1048]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Need to configure Scrutinizer phpunit properly (check Scrutinizer's recommendation).

### Examples
* https://scrutinizer-ci.com/g/deployphp/deployer/inspections/f6fb6889-6726-4b81-b7df-2f12be6924c9
* https://scrutinizer-ci.com/g/deployphp/deployer/inspections/4eca1b94-31e1-4933-a3f9-00570925a398

**Comment by elfet** [comment]
Lately, there are a lot of issues with Scrutinizer's tests. I think to moving to another tool. Do you know some alternatives?

**Comment by pluseg** [comment]
I've used only Scrutinizer, Travis and self-hosted Jenkins. I hope that these issues are only temporary. Meanwhile it doesn't seem to be fixed hardly. Let's give Scrutinizer one more chance ;)

**Comment by elfet** [comment]
Fixed.

Code coverage down 56%
