### ISSUE TITLE
Need help: multiple problems after upgrade to 4.2 (Windows 10)

### ISSUE THREAD

**Issue by frutality** [deployphp/deployer#1060]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1
| Local Machine OS  | Windows 10
| Remote Machine OS | Ubuntu 16.04

### Description 
This is probably not a bug, just I am misunderstanding something. Upgraded Deployer from 3 to 4.2.1, did everything mentioned here: https://github.com/deployphp/deployer/blob/master/UPGRADE.md

When I try to deploy with `phpseclib`, everything seems fine except `upload()` not working anymore. It says `Ok` in the output, but files aren't really uploaded.

Then I tried `native` ssh_type, and error happened:

> [RuntimeException]
  There already is a directory (not symlink) named "current" in ~/www/project. Remove this directory so it can be replaced with a symlink for atomic deployments.

I checked: there is symlink "current", it's not a directory. Anyway, I removed it. Next error I saw was

> mkdir: cannot create directory ‘.dep’: File exists.

I deleted it. Next errors were:

> mkdir: cannot create directory ‘releases’: File exists
mkdir: cannot create directory ‘shared’: File exists

Deleted both. Next error:

> touch: cannot touch '/deploy_path_here/.dep/deploy.lock': No such file or directory

And I am really don't know what to do. Already digging there for 2 hours with no luck. I wish if `upload()` just worked as with v3.

**Comment by frutality** [comment]
Found why `upload()` didn't work. The same problem as in https://github.com/deployphp/deployer/issues/907: if deploy_path is started with `~`, no files were uploaded. I changed it to absolute path and everything works now.

Probably issue can be closed, but I'm still a bit curious why there were errors with `native`.

**Comment by antonmedv** [comment]
Fixed in master
