### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by herloct** [deployphp/deployer#1062]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Would you interested in docker image for Deployer?

I've been building it here [herloct/docker-deployer](https://github.com/herloct/docker-deployer) to help me on my CI/CD workflow, but i would love to have official docker image for our Deployer.

**Comment by antonmedv** [comment]
Will do official docker image

**Comment by mmenozzi** [comment]
@antonmedv has ever been done an official Docker image of Deployer?

**Comment by antonmedv** [comment]
I think to do it. But what's best practice of doing it? How to do autoupdates?

**Comment by mmenozzi** [comment]
I think the the best thing is to have a "build proccess" integrated with the Travis CI build. One of the step of this build should create a Docker image and push it to Docker Hub.
