### ISSUE TITLE
use `getenv('_')` instead of `php`

### ISSUE THREAD

**Issue by leo108** [deployphp/deployer#1063]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1

### Description 

`https://github.com/deployphp/deployer/blob/master/src/Executor/ParallelExecutor.php#L235`

In some servers, `php` is not installed globally or not set in Env, so we should use `getenv('_')` to get the correct php bin path. (or other suitable ways)

**Comment by mbrodala** [comment]
Read [Usage of `_` as an environment variable passed to a command](https://unix.stackexchange.com/questions/292991/usage-of-as-an-environment-variable-passed-to-a-command) for an explanation.

**Comment by antonmedv** [comment]
Now using dep bin which uses env php shabang.

**Comment by antonmedv** [comment]
See #1092
