### ISSUE TITLE
Useless code in ParallelExecutor

### ISSUE THREAD

**Issue by leo108** [deployphp/deployer#1065]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1

### Description 

https://github.com/deployphp/deployer/blob/master/src/Executor/ParallelExecutor.php#L210

and

https://github.com/deployphp/deployer/blob/master/src/Executor/ParallelExecutor.php#L236

the `$input` variable already contains the `--file` option

**Comment by elfet** [comment]
Thanks. Please send PR with fixes.

**Comment by antonmedv** [comment]
It does not contains it. Fixed in #1092
