### ISSUE TITLE
Add Builder(Interface)::add()

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#1069]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.1.2
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Since there is a helper `add()` which extends compared to `set()` the same should be available in the server builder.

### Content of `deploy.php`
```php
server('foo', 'example.org')
  ->set('deploy_path', ...)
  ->add('shared_dirs', ['only-on-foo']);
```

Thus the example given should only extend `shared_dirs` in the environment of a single server.

Since this would be added to the `BuilderInterface` and `Builder` this would be a backward incompatible change requiring a major version bump.

**Comment by elfet** [comment]
I think this can be implemented in v5.

**Comment by elfet** [comment]
Done.

**Comment by mbrodala** [comment]
Nice, thanks. :-)
