### ISSUE TITLE
How multi server deployment works

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#1070]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.2.1
| Local Machine OS  | N/A
| Remote Machine OS | N/A

I just wondering it does start with server1 and then executes all tasks and after that will start with second server? or it does task1 on server 1 and server2 then task2 on server1 and server2..

I understand that updates will come almost with no downtime but in my case I am doing long upgrades and want to put whole server under maintenance(because I know other server will take care of requests) and after is up to date I would like to bring it up and do updates with second server

**Comment by neikei** [comment]
Some useful information are available at the end of the following webpage: https://deployer.org/docs/tasks

**Comment by svycka** [comment]
oh I see now :)

but it looks it does one task in all servers and only starts second when all servers finish with first one :(
maybe there is some way to do all tasks to first server and then start second and so on?

**Comment by neikei** [comment]
I haven't seen this feature, but you can create stages and run the deployer for them one after another.

Assign server to stage: https://deployer.org/docs/servers

Run Deployer for the assigned stage: php vendor/bin/dep deploy <your_stage>

**Comment by svycka** [comment]
ok this answers my question just don't like idea to run deploy command for each server of course i could create a bash script for this but would be more happy with built in feature :D

**Comment by elfet** [comment]
@svycka you can do this by bash script:
```sh
dep deploy servers_a &
dep deploy servers_b &
dep deploy servers_c &
```
This does not included in code, i try to keep code simple. I think adding this to docs.

**Comment by svycka** [comment]
@elfet yes I can, just would like to have more control how to run tasks
