### ISSUE TITLE
Parse hyphens in environment setting names

### ISSUE THREAD

**Issue by MrHash** [deployphp/deployer#1073]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
```
set('hyphenated-var', 'value');
parse('{{hyphenated-var}}'); 
```
Result is `{{hyphenated-var}}` when expected is `value`.

**Comment by elfet** [comment]
Let's leave only PR.
