### ISSUE TITLE
Support for multiple choice questions

### ISSUE THREAD

**Issue by MrHash** [deployphp/deployer#1075]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Support for `ChoiceQuestion` as part of the function set as `askChoice()` would be a nice feature. Instead of using `ask()` with invisible options, choice displays all options and also supports multiple choice selection. Have an implementation available if interested.

**Comment by elfet** [comment]
Will be cool if you can make pr with docs for it.

**Comment by elfet** [comment]
Done in v4.3.0
