### ISSUE TITLE
Laravel overriding public folder not symlinking properly

### ISSUE THREAD

**Issue by garygreen** [deployphp/deployer#1086]
If you've overridden the public path in laravel from the standard `public` to e.g. `public_html` -- the symlinking for the public storage won't work.

Laravel actually provides a command `php artisan storage:link` that can link public to the storage folder (it will know that you've overriden the path) -- maybe that should be used rather than [hardcoding it](https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L117) ?

**Comment by elfet** [comment]
What will be cool. Can you make a PR with this?

**Comment by barryvdh** [comment]
Would be just 
```php
desc('Execute artisan optimize');
task('artisan:storage:link', function () {
    run('{{bin/php}} {{release_path}}/artisan storage:link');
});
```

But it does have different checks: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Console/StorageLinkCommand.php

**Comment by barryvdh** [comment]
See https://github.com/deployphp/deployer/pull/1152
