### ISSUE TITLE
Deployer stuck on "echo $0"

### ISSUE THREAD

**Issue by pzaj2** [deployphp/deployer#1102]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.3.0
| Local Machine OS  | Ubuntu 16.04.2 LTS (Desktop)
| Remote Machine OS | Ubuntu 16.04.2 LTS (Server)

### Description 
I'm starting to play with deployer and wanted to see how it's gonna work. Unfortunately it does not, getting stuck on "echo $0".

Just a small update, when I comment out "->pty(true)" line from server configuration (it was there by default). It works until ssh login (but this is something I can manage myself). So the question is what pty is there for? (no documentation on that)

### Steps to reproduce
-

### Content of `deploy.php`
I use standard symfony recipe with following configuration
``
namespace Deployer;

require 'recipe/symfony.php';

// Configuration

set('ssh_type', 'native');
set('ssh_multiplexing', true);
set('keep_releases', 3);
set('default_stage', 'staging');

set('repository', '<GITLAB REPOSITORY URL>');
server('staging', '<HOST>')
    ->user('<USER>')
    ->identityFile()
    ->stage('staging')
    ->set('env', 'dev')
    ->set('branch', 'develop')
    ->set('clear_paths', ['web/config.php'])
    ->set('deploy_path', '<PATH>')
    ->pty(true);
``

### Output log
*With enabled option for verbose output `-vvv`.*
 Executing task deploy:prepare
[staging] > echo $0

**Comment by elfet** [comment]
Try remove `->pty(true);`

**Comment by cronfy** [comment]
@antonmedv I have same problem and same question.

What pty is there for? (no documentation on that)

**Comment by antonmedv** [comment]
Pty deprecated in 5.x.  Use tty.

**Comment by loganstellway** [comment]
I am experiencing the described issue above. 

Environment:
```
Deployer 6.0.3 (Latest version at time of writing)
Deploying from CentOS 7 > CentOS 7
```

Initially, I would see:
```
# dep -vvv deploy staging
[xx.xxx.xxx.xx] > echo $0
[xx.xxx.xxx.xx] < ssh multiplexing initialization
```

After disabling multiplexing:
```
# dep -vvv deploy staging
[xx.xxx.xxx.xx] > echo $0
```

My deployment process works flawlessly with production
```
# dep -vvv deploy production
```

**Note:**
  - This issue occurs with any command - even a simple `run('pwd')`.
  - I can create an SSH connection to the `staging` server without issue

Any ideas what could be happening?

**Comment by antonmedv** [comment]
Try this: `ssh stage bash -c`

**Comment by loganstellway** [comment]
@antonmedv Thank you for the reply

I receive the following error when running the command
```
# ssh user@xx.xxx.xxx.xx bash -c
bash: -c: option requires an argument
```

Omitting the `-c` argument successfully establishes an `ssh` session
```
# ssh user@xx.xxx.xxx.xx bash
```

**Comment by loganstellway** [comment]
Ahh .. the issue was my `hostname` setting in my `inventory.yml` - changing the value to the IP address did the trick.

Thanks for the help!
