### ISSUE TITLE
Pseudo-terminal will not be allocated because stdin is not a terminal.

### ISSUE THREAD

**Issue by improvethings** [deployphp/deployer#1106]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.30
| Remote Machine OS | Linux 4.4.0-57-generic x86_64

### Description 
terminal issue upon deployment

### Output log
*With enabled option for verbose output `-vvv`.*
➤ Executing task deploy:unlock
• done on [production]
✔ Ok [348ms]

                                                                          
  [RuntimeException]                                                      
  Pseudo-terminal will not be allocated because stdin is not a terminal.  
                                                                          

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/NativeSsh.php:103
 Deployer\Server\Remote\NativeSsh->run() at phar:///usr/local/bin/dep/src/functions.php:318
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/update_code.php:59
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:85
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:103
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:123
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:190
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

**Comment by elfet** [comment]
Fixed in v5 #1092

**Comment by FredoVelcro** [comment]
same issue on Windows

**Comment by FredoVelcro** [comment]
why could not be fixed in v 4.3 ?

**Comment by antonmedv** [comment]
Install in from master branch. (Note: API BC in v5)
Will release v5 after finishing docs.

**Comment by borNfreee** [comment]
> Install in from master branch. (Note: API BC in v5)

It does not work from `master`. Fails with such error "https://github.com/deployphp/deployer/issues/888"

4.3.0 fails with error `Pseudo-terminal will not be allocated because stdin is not a terminal`.

It's impossible to use deployer at the moment...

**Comment by antonmedv** [comment]
```
dep deploy
➤ Executing task deploy:prepare
anton@deployer.org's password:
```
In v5 it should work

**Comment by Kolyunya** [comment]
I don't feel like deploying to production via an unstable deployer. Looking forward for a release.

**Comment by micbenner** [comment]
Unfortunately this stops my venture into the deployer world if this is only going to be fixed on a PHP7 release.

**Comment by antonmedv** [comment]
Yes, only php7.
