### ISSUE TITLE
can't get a config param from yml file

### ISSUE THREAD

**Issue by makogons** [deployphp/deployer#1113]
| Q                 | A
| ----------------- | ---
| Issue Type | Question        
| Deployer Version   |  4.3.0
| Local Machine OS  | Windows 10 x64
| Remote Machine OS  |  Ubuntu 16,04

### Description
why i can't get a config param from yml file?

### Steps to reproduce
 ./deployer.phar deploy development

### Content of `deploy.php`
```php
<?php
use function Deployer\{task, run, set, get, serverList};

require 'recipe/common.php';

serverList('servers.yml');

set('keep_releases', 10);
set('branch', get('stage') == 'production' ? 'master' : 'develop'); //here get('stage') returns NULL

set('repository', 'myrepo');

set('ssh_type', 'native');
set('ssh_multiplexing', true);

task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:symlink',
    'cleanup',
    'deploy:unlock',
    'success',
]);

```

### Output log
all ok

### Content of servers.yml
```php
development:
  host: dev.domain.com
  port: 22
  user: deployer
  identity_file:
    public_key:  ~/.ssh/id_rsa.pub
    private_key: ~/.ssh/id_rsa
    password:    ''
  stage: development
  deploy_path: /var/www/_config

```

**Comment by elfet** [comment]
`get('deploy_path')`

**Comment by makogons** [comment]
set('branch', get('stage') == 'production' ? 'master' : 'develop'); //here get('stage') returns NULL

**Comment by antonmedv** [comment]
Yes, on init state there is no stage, only in tasks.

**Comment by postfriday** [comment]
Got the same issue. What is the right way to change branch depending on stage?

**Comment by makogons** [comment]
use function Deployer\{task, run, set, get, serverList};

require 'recipe/common.php';

serverList('servers.yml');

set('keep_releases', 10);
set('branch', get('stage') == 'production' ? 'master' : 'develop');

set('config_path', '{{deploy_path}}/current/' . (get('stage') == 'production' ? 'production' : 'stage') . '/');

set('repository', 'git@bitbucket.org:pushworld/push.world-deploy.git');

set('ssh_type', 'native');
set('ssh_multiplexing', true);

task('deploy:init_config', function() {
    get('stage');
    return;
});

task('deploy', [
    'deploy:init_config',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:symlink',
    'cleanup',
    'deploy:unlock',
    'success',
]);



**Output**

./deployer.phar deploy local -vvv
➤ Executing task deploy:init_config
➤ Executing task deploy:failed
• done on [local]
✔ Ok [0ms]


  [RuntimeException]
  Configuration parameter `stage` does not exists.


Exception trace:
 () at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Server/Environment.php:131
 Deployer\Server\Environment->get() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/functions.php:535
 Deployer\get() at /mnt/c/work/push.world-deploy/deploy.php:19
 {closure}() at n/a:n/a
 call_user_func() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Task/Task.php:85
 Deployer\Task\Task->run() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Console/TaskCommand.php:103
 Deployer\Console\TaskCommand->execute() at phar:///mnt/c/work/push.world-deploy/deployer.phar/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at phar:///mnt/c/work/push.world-deploy/deployer.phar/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Console/Application.php:123
 Deployer\Console\Application->doRunCommand() at phar:///mnt/c/work/push.world-deploy/deployer.phar/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///mnt/c/work/push.world-deploy/deployer.phar/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///mnt/c/work/push.world-deploy/deployer.phar/src/Deployer.php:190
 Deployer\Deployer->run() at phar:///mnt/c/work/push.world-deploy/deployer.phar/bin/dep:119
 require() at /mnt/c/work/push.world-deploy/deployer.phar:4

deploy [-p|--parallel] [--no-hooks]

**Comment by makogons** [comment]
no, we are found another way to determinate which branch we want to deploy
