### ISSUE TITLE
Installation problems : No command 'dep' found

### ISSUE THREAD

**Issue by callard** [deployphp/deployer#112]
Hello there,

I've downloaded deployer.phar and then followed the instructions but if I run the dep command, I get an error message 'No command 'dep' found'

I've added /usr/local/bin/dep to the path but it didn't change anything.

Do you know what I've missed please ?

**Comment by bali182** [comment]
My first try at `go`. After

`go get -u github.com/golang/dep/cmd/dep`

There is no output on the terminal. Also the `/usr/local/bin/` folder doesn't have a `dep` folder in it. Did the installation path change?

**Comment by antonmedv** [comment]
@bali182 try to install php first =)))

**Comment by bali182** [comment]
@antonmedv are you serious?

**Comment by bali182** [comment]
Sorry wrong issue... Thought I'm at the `dep` repo.

**Comment by antonmedv** [comment]
Well, it's dep repo, but not for go. 😄
