### ISSUE TITLE
Command arguments/options signature

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1125]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.x (Next)
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Laravel has a nice feature to describe the commands with a signature, including the options/arguments. It also provides closure based commands, with some additions to bind the arguments and the command itself. See https://laravel.com/docs/5.4/artisan#defining-input-expectations for the signature, and the bit above for closure based commands.
This would make it easier to have specific flags for certain commands.

```php
task('deploy:cache {type=all}', function ($type) {
    run("bin/console clear $type");
})->describe('Clear the cache');
```

Binding the TaskCommand to the closure would allow the TaskCommand to have some helper functions, instead of the global helpers (eg. `$this->write('output')` instead of `output()->write()`)

See the Parser code here: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Console/Parser.php

**Comment by antonmedv** [comment]
I have plans for adding opts and rags to task:
```php
task('deploy', function () {
    // ...
})->option(...);

**Comment by antonmedv** [comment]
> $this->write('output')

**Comment by barryvdh** [comment]
Okay nice, then this syntax would just be some syntaxic sugar, but it does work nicely for most features/flags and is very understandable when reading.

**Comment by antonmedv** [comment]
> $this->write('output')

I don't like this as there no benefits of this approach. You will not get autocomplete in IDE, but you need to write more ~$this->~ 

```
write('this is better ❤️ ');
```

**Comment by antonmedv** [comment]
After trying to implement this, end up what this is become really complicated in parallel executor. So no solution for now. Closing it, maybe some one will find better way and we bring back this issue.
