### ISSUE TITLE
Relative symlinks strategy should not rely on man-db

### ISSUE THREAD

**Issue by sourcerer-mike** [deployphp/deployer#1128]
As in #503 you introduced relative symlinks relying on `man ln` .
This is a command of the `man-db` package which is not always installed. Never if you look in docker php container.
So please make this `if [[ "$(ln --help)" =~ "--relative" ]]; then echo "true"; fi` .
Or is there something, that breaks when using the usual help option?

**Comment by antonmedv** [comment]
This is possible to use. Does all nix system supports help option? For temp this you can set config use relative symlinks to true.

**Comment by sourcerer-mike** [comment]
That was my question, too. Seeing this close I guess you've implemented it already.
Both check might help to answer our question - like a fallback ;-)

**Comment by antonmedv** [comment]
There is a PR #1132
