### ISSUE TITLE
[question] Use deployer with nodejs

### ISSUE THREAD

**Issue by flashios09** [deployphp/deployer#1129]
Hi,
I have a cakephp application that i want to deploy, i have also a `server.js` file that i need to run with nodejs. 
Is it possible to create a task that run this command `npm install`(to install node modules) then `node server.js` with deployer ?
thanks

**Comment by antonmedv** [comment]
```php
task('deploy:build', function () {
    run('cd {{release_path}} && npm install');
});
```

For running node, you need some king of demonize, you can take a look on forever or on pm2 (recomended)
