### ISSUE TITLE
Migrate to deployphp/deployer

### ISSUE THREAD

**Issue by gordalina** [deployphp/deployer#113]
This should happen sometime in the future.
Documentation here: https://help.github.com/articles/transferring-a-repository/

**Comment by elfet** [comment]
Well, 652 :star: will be enough. Will migrate on this week. :laughing: 

What we need to do?

* [ ] Transfer repository
* [ ] Edit `composer.json` and publish on packagist
* [ ] Fork on `elfet/deployer` and edit `composer.json`

What else @gordalina?

**Comment by gordalina** [comment]
looks good to me

**Comment by gordalina** [comment]
:+1:
