### ISSUE TITLE
Yii2 Advanced task order

### ISSUE THREAD

**Issue by vinpel** [deployphp/deployer#1135]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

the Yii2 receipe have an order of task problem :
  * create shared file
  * do the init

The shared file are created in the init in the first deployment.

### Content of `deploy.php`
```php
task('deploy', [
  'deploy:prepare',
  'deploy:lock',
  'deploy:release',
  'deploy:update_code',
  'deploy:vendors',
  'deploy:init',
  'deploy:shared',  
  'deploy:run_migrations',
  'deploy:symlink',
  'deploy:unlock',
  'cleanup',
  ])->desc('Deploy your project');
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by antonmedv** [comment]
Please send PR.

**Comment by vinpel** [comment]
done
