### ISSUE TITLE
Add tests for HostSelector and ScriptManager

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1137]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | v5.x

### Description 
Add tests for [HostSelector](https://github.com/deployphp/deployer/blob/master/src/Host/HostSelector.php) and [ScriptManager](https://github.com/deployphp/deployer/blob/master/src/Task/ScriptManager.php).

**Comment by douria** [comment]
hello , I want to contribute to this project and make the test for HostSelector, but i don't understand clearly how it works. so i believe that there is an array or a list that contains the hosts and each host has a role and a stage. but could you please specify the structure of this list/array? for example is it 

column1                 column2          column3 
hostName              role                  list of stages 
?
thank you in advance.

**Comment by antonmedv** [comment]
@douria host contains fields for filtering, `HostSelector` gathers hosts. 
```php
interface Host 
{
    stage: string
    roles: string[]
    hostname: string
}
```

**Comment by dudu84** [comment]
Hi! I would like to do this!!

**Comment by antonmedv** [comment]
I can assign only deployer organization members, sorry. But you can do it, i think everybody else will see your comment.

**Comment by dudu84** [comment]
No problem!

**Comment by dudu84** [comment]
Hey Anton! I finished writing some tests.
All green. 
What should I do now?
