### ISSUE TITLE
Parse also the vars with `:` like the task names `deploy:prepare`, `deploy:lock` 

### ISSUE THREAD

**Issue by flashios09** [deployphp/deployer#1138]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I want to do `run({{nginx:restart}})` inside a task like this:
```php
task('predeploy:nginx', function () {
    if(!commandExist('nginx')) {
        // ...
       
        // restart nginx
        run('{{nginx:restart}}');
    }

    return get('bin/nginx');
});
```
i set the `nginx:restart` var like this:
```php
// Closures
$nginxRestart = function () {
    return run('sudo systemctl restart nginx');
};
set('nginx:restart', $nginxRestart);
```
I use a closure because i have also an `nginx:restart` task:
```php
task('nginx:restart', $nginxRestart);
```

If i replace `{{nginx:restart}}` by `{{nginx-restart}}` it works but not with the `:` char.
I take a look at the parse function used, the regex doesn't accept the `:` char.
The same pattern `task:subtask` is used in the task name, is it possible to update the parse regex for var names from this `/\{\{\s*([\w\.\/-]+)\s*\}\}/` to this `\{\{\s*([\w\:\.\/-]+)\s*\}\}` ?

I can create a PR.

Thanks

**Comment by antonmedv** [comment]
Why not `run('{{nginx:restart}}');` to `nginxRestart();`?
In v5 there is `invoke('task')` func.

**Comment by flashios09** [comment]
> In v5 there is invoke('task') func.
Do you mean that in v5 it will not be possible to use *mustache* syntax `{{var}}` inside the run function ?

**Comment by antonmedv** [comment]
No

**Comment by antonmedv** [comment]
For know i think to close this issue. If there will be need or real use case lets talk about it again.
