### ISSUE TITLE
Accept functions inside `onlyOn`

### ISSUE THREAD

**Issue by hstandaert** [deployphp/deployer#1139]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.3.0
| Local Machine OS  | macOS Sierra

### Description 
Would be nice to be able to do this: 

```
desc('Some task')
task('example:some_task', function() {
    ...
})->onlyOn(function(){
    return has('variable');
});
```

**Comment by antonmedv** [comment]
What about this?
```php
desc('Some task')
task('example:some_task', function() {
    if (has('variable')) {
        //...
    } else {
        writeln('Skipping example:some_task');
    }
});
```

**Comment by mbrodala** [comment]
Maybe something like `->onlyOn('{{option_value}}');` or `->onlyOn(get('option_value'))` would make sense? (The former would be evaluated upon task collection, the latter upon definition) In this case `set('option_value', ...);` could be defined as desired.

**Comment by antonmedv** [comment]
When to run code then?
```php
set('option_value', function () {
    return run('pwd');
});
```

**Comment by mbrodala** [comment]
@antonmedv Depends on when the evaluation occurs. For the former as soon as the task collection is prepared for a host, the latter as soon as `deploy.php` is included.

**Comment by antonmedv** [comment]
* Run task `example:some_task`
* Check cond
* > pwd
* End task

What different from this? 
```php
desc('Some task')
task('example:some_task', function() {
    if (has('variable')) {
        //...
    } else {
        writeln('Skipping example:some_task');
    }
});
```

**Comment by hstandaert** [comment]
The function inside the `onlyOn()` is supposed to be executed on task execution.  Essentially, I'd like to determine whether or not a task should be executed on the specified server without putting the server name in there. 

I suppose it's possible to place an `if`-statement inside the task, but the task will still appear to be executed upon deploy in the console. It's seems bit redundant to have something like this in your console:

```
> Executing task 'example:some_task 
Not executed
```

I think #851 has the same intention as this, but just implemented in a different way.

**Comment by antonmedv** [comment]
@hstandaert i think we can combine our efforts and found a solution for the problem. 
Let's continue disqus in here  #1140
