### ISSUE TITLE
"Known hosts" error message

### ISSUE THREAD

**Issue by benrolfe** [deployphp/deployer#1141]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | master
| Local Machine OS  | Mac
| Remote Machine OS | Ubuntu

### Description 
Every time I deploy I get the error message shown below. How can this be removed?
I've checked the "~/.ssh/known_hosts" file already.

### Output log
Warning: Permanently added '***.***.***.***' (ECDSA) to the list of known hosts.

**Comment by antonmedv** [comment]
```php
host('domain.com')
    ->options([
        'UserKnownHostsFile=/dev/null',
        'StrictHostKeyChecking=no',
    ])
```

**Comment by benrolfe** [comment]
Thanks antonmedv. How would this fit with my current code?

```
server('production', '***.***.***.***')
    ->user('root')
    ->password('*****')
    ->identityFile()
    ->set('deploy_path', '/var/www/example.co.uk');
```

**Comment by antonmedv** [comment]
This solution for v5 (master branch)

**Comment by benrolfe** [comment]
Great, do you know when the composer package will switch to v5 as standard?

**Comment by antonmedv** [comment]
After release, or use can install in with `@dev`, or via https://deployer.org/download

**Comment by antonmedv** [comment]
https://getcomposer.org/doc/articles/versions.md#stability-constraints

**Comment by Sobak** [comment]
Tip for anyone using Deployer from the Windows on local machine. You can specify `NUL` as Windows' counterpart of `/dev/null` from unix-like systems.

```php
->addSshOption('UserKnownHostsFile', 'NUL')
```

That should silence the warning.

PS: Theoretically, if you're running it from PowerShell `$null` should do the trick but I haven't checked it personally.
