### ISSUE TITLE
Copy file when shared

### ISSUE THREAD

**Issue by picks44** [deployphp/deployer#1142]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.3
| Local Machine OS  | Windows
| Remote Machine OS | Debian

When you set up some shared files (like `add('shared_files', ['app/config/parameters.yml']);`  for Symfony for instance), is there a way to copy the file in the shared folder before creating the symlink and all?

Apparently today, the file is created but it's empty. Or am I missing something?

**Comment by vinpel** [comment]
it's exactly my proposed PR, i've got the same problem

**Comment by stevenklar** [comment]
Should be fixed when #1143 got merged.

**Comment by antonmedv** [comment]
Fixed
