### ISSUE TITLE
Unable to deploy the repository.

### ISSUE THREAD

**Issue by shankhadevpadam** [deployphp/deployer#1148]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 4.3.0
| Local Machine OS  | Ubuntu 16.04.2 LTS
| Remote Machine OS | Ubuntu 16.04.2 LTS

### Description 
I have the following deploy.php file and following configuration file generated by deployer and when i am trying to deploy the repository the follwing error is occur

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/common.php';

// Configuration

set('ssh_type', 'native');
set('ssh_multiplexing', true);

set('repository', 'git@github.com:shankhadevpadam/padamshankhadevtk.git');
set('shared_files', []);
set('shared_dirs', []);
set('writable_dirs', []);

// Servers

server('padamshankhadev', 'xxx.xx.xx.xxx', 22)
    ->user('root')
    ->identityFile()
    ->set('deploy_path', '/home/admin/web/padamshankhadev.tk/public_html');


// Tasks

desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
after('deploy:symlink', 'php-fpm:restart');

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
✔ Executing task deploy:failed
✔ Executing task deploy:unlock

                      
  [RuntimeException]  
                      

deploy [-p|--parallel] [--no-hooks]

**Comment by antonmedv** [comment]
Run dep with `-vvv` option.

**Comment by shankhadevpadam** [comment]
[RuntimeException]                                                           
  The command "ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyCheckin  
  g=no -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/deplo  
  yer_mux_root@139.59.72.150:22' -p '22' -i '/home/padam/.ssh/id_rsa' 'root@1  
  39.59.72.150' bash -s" failed.                                               
  Exit Code: 128(Invalid exit argument)                                        
  Working directory: /home/padam/html/git_test/deployer                        
  Output:                                                                      
  ================                                                             
  Host key verification failed.                                                
  fatal: Could not read from remote repository.                                
  Please make sure you have the correct access rights                          
  and the repository exists.                                                   
  Error Output:                                                                
  ================

**Comment by antonmedv** [comment]
> Host key verification failed.
> fatal: Could not read from remote repository.

Try use agent forwarding or deploy keys.
