### ISSUE TITLE
Get stuck when using multiplexing

### ISSUE THREAD

**Issue by leo108** [deployphp/deployer#1155]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | master cdac931
| Local Machine OS  | Ubuntu 16.04.1 LTS/ homestead
| Remote Machine OS | Ubuntu 16.04.2 LTS

### Description 
See deploy file and output log

### Content of `deploy.php`
```php
<?php
namespace Deployer;

host('xxx.com')
    ->user('root')
    ->multiplexing(true)  // it works as expected if set this to false
    ->identityFile('/home/vagrant/.ssh/id_rsa');

task('test', function () {
    run('echo 123;');
});
```

### Output log

```
➤ Executing task test
[xxx.com] > echo 123;
[xxx.com] < ssh multiplexing initialization
[xxx.com] < 123        # output 123 within 1s
• done on [xxx.com] # output this line after 1min
✔ Ok [60s 804ms]
```

**Comment by antonmedv** [comment]
So what is the problem?

**Comment by leo108** [comment]
@antonmedv it takes 60 seconds to finish the `test` task when enabling the multiplexing, but it only takes 800ms when disabling the multiplexing.

**Comment by leo108** [comment]
I changed the test task to this:

```
task('test', function () {
    run('echo 123;');
    run('echo 321;');
});
```

the output is:

```
➤ Executing task test
[xxx.com] > echo 123;
[xxx.com] < ssh multiplexing initialization
[xxx.com] < 123
[xxx.com] > echo 321;
[xxx.com] < ssh multiplexing initialization
[xxx.com] < 321
• done on [xxx.com]
✔ Ok [121s 522ms]
```

It takes 2 min to finish this simple task, don't you think there is something wrong?

**Comment by antonmedv** [comment]
Looks like multiplexing isn't initialized correctly. Please chech if it's working on your local machine.

**Comment by leo108** [comment]
I did some tests and find something strange

```
$cmd = 'ssh -i /home/vagrant/.ssh/id_rsa -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_root@xxx.com root@xxx.com echo 1;';
$p = new Symfony\Component\Process\Process($cmd);
$p->run(function() {var_dump(func_get_args());});
```

it outputs

```
array:2 [
  0 => "out"
  1 => "1\n"
]
```

and then stuck there for 1min, then outputs error message:

```
Symfony\Component\Process\Exception\ProcessTimedOutException with message 'The process "ssh -i /home/vagrant/.ssh/id_rsa -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_root@xxx.com root@xxx.com echo 1;" exceeded the timeout of 60 seconds.'
```

I have tried to run `$cmd` in terminal directly, it outputs `1` and exits immediately. Do you know what's the problem? (although it's not related with deployer). Thanks.

**Comment by staabm** [comment]
Sounds like the Symfony Prorcess is waiting for a timeout

**Comment by antonmedv** [comment]
Try realtime output with tty mode. Maybe remote host prompt for some input.

**Comment by leo108** [comment]
@antonmedv 

```
$cmd = 'ssh -i /home/vagrant/.ssh/id_rsa -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_root@xxx.com root@xxx.com echo 1;';
$p = new Symfony\Component\Process\Process($cmd);
$p->setTty(true);
$p->run(function() {var_dump(func_get_args());});
```

it responses `1` immediately and return `0`, I think there is no remote host prompt

![image](https://cloud.githubusercontent.com/assets/1551716/24826504/1fe097b2-1c6a-11e7-9051-fe871e37fc1f.png)

**Comment by leo108** [comment]
I think it maybe a bug belongs to symfony/process, I have submitted an issue https://github.com/symfony/symfony/issues/22346

**Comment by antonmedv** [comment]
Well, i don't know that else can it be. Maybe some bug in ssh multiplexing?

**Comment by mikeymike** [comment]
hey @leo108 I might have run into the same issue that you have here... Turns out the reason it was hanging for me was because of a [bug in OpenSSH](https://bugzilla.mindrot.org/show_bug.cgi?id=1988).

I resolved it by moving my build/deploy process into docker and using a newer version of OpenSSH. 

I believe MacOS comes with a relatively new version of OpenSSH with the bug resolved while a lot of Linux distros still ship with older versions. 

Hope this helps 👍

**Comment by leo108** [comment]
@mikeymike that makes sense, all my servers are using openssh 7.2, according to your link is should be fixed after 7.3p1

**Comment by staabm** [comment]
is there anything we can do to warn the user about this openssh bug in outdated openssh versions?

**Comment by mikeymike** [comment]
I think you could parse the output of `ssh -V` and disable multiplexing because from what I can see it simply won't work.
