### ISSUE TITLE
Can't set server IP

### ISSUE THREAD

**Issue by dima-stefantsov** [deployphp/deployer#1157]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | dev-master @ 210b899928c723cf5507638a3e9545021f5cdba4
| Local Machine OS  | Win10
| Remote Machine OS | Ubuntu 16

### Description 
*Can not specify server IP address!*

### Steps to reproduce
1. have a sitename.com and example.com
2. have them run behind Cooudflare CDN. It means their DNS IP is not what real server IP is.
3. update from 3.x to 5.x to find out there is no longer way to specify IP address separately from deploy name.

Here is my workflow:
I have many sites with same codebase. Their names represent what they really are, eg. sitename.com
There are also names like sitename.com-virtual = will deploy this site to a VMware.
sitename.com-root = will use different login options, used to update server files with root.

etc.

It is essential for me to be able to have different server()'s with different names, point to the same IP.

While I technically can create a lot of DNS records for every workflow, or can do some other crazy things, this is highly undesirable. This is  totally not how flexible deploy should look like.

Server system you had in 3.x ($name, $ip)->stage() was perfect. Why would you break this great flexible functionality? How do I achieve what was easily possible in 3.x now in 5.x?

### Expected outcome
Please make it possible to specify multiple server names with different workflows for a single IP, without a need to make DNS records for every single workflow.

**Comment by dima-stefantsov** [comment]
I technically could move unique server names to call them with - as one of it's stages.
But it currently seems declaring second host() with same ip as hostname, overwrites first host().
And even if it would be possible, it would not be intuitive and easy to read, as it was in 3.x.

**Comment by antonmedv** [comment]
Servers with server names deprecated, instead there are hosts. Think of host separately of your deploy targets.
Also in v5 comes roles, you can group hosts into different roles. Also there are a [host aliases](https://github.com/deployphp/docs/blob/master/hosts.md#host-aliases). You can use them:
```php
host('sitename.com/virtual')
    ->...
host('sitename.com/root')
    ->...
```

**Comment by dima-stefantsov** [comment]
Я перейду на русский, на английском у вас получаются более-менее стандартные отписки из мануала.

У меня есть 500 серверов, мне нужно сгруппировать их в пересекающиеся группы. Некоторые из них находятся на одном и том же сервере (группа "сервер1", "сервер2", ...), некоторые находятся на одной и той же БД (группа "БД1", "БД2", ...).

На деплоере v3 это было реализовано через ->stage([]), теперь же stage не может принимать массив, только строку. Массив теперь принимают только roles(), но из командной строки я не нашёл способа запустить команду именно на конфигурациях, принадлежащих к группе/роли "БД2". Раньше это просто была команда dep cmd servername или dep cmd stagename, а теперь изменения пошли в каком-то инопланетном направлении, и вместо того, чтобы стать лучше - стало хуже.

На самом деле мне всего хватало в v3.3, только https://github.com/deployphp/deployer/issues/924 резко портит жизнь. Сейчас попробую где-нибудь в исходниках это захардкодить, я как-то отчаялся заставить v5 работать.

Раньше было просто и мощно. Теперь сложно, глючит (both v.4 and v.5), и ограничено узкими workflow.

**Comment by antonmedv** [comment]
You can use option --roles: `dep deploy --roles app`.

You can fork 3.x branch and continue to develop it as you see. It is open source and ships *as is*.

**Comment by dima-stefantsov** [comment]
Thank you, I have tried that, got error http://4.stefantsov.com/s/2017.04.12_20.45.29_mv9u1j07.png [Deployer\Exception\Exception] No host selected
Now that you said it should work, I found what my problem was: roles()  takes not array of strings, but ...$strings, it works now.

Before you tell me it's "as is" and send me to fork it, would you maybe consider a feedback of deployer active user, me? With roles now working, you have just made deployer syntax harder to use: instead of `dep task stagename`, now it must be used as `dep task --roles rolename`
Would you maybe consider allowing, like it used to be, many stages per host? That would solve my current issue, and should not make it any harder for everyone else.

Either that, or `dep task rolename`, that would work too. That would require support for --stage option. That would make roles and stages interchangeable.

**Comment by dima-stefantsov** [comment]
By the way, array syntax is superior to ...$variable, because using arrays allows me to write
[
value1,
value2,
]
and have that comma in the end, and it will compile and work. Easy to add more values later.

With your syntax it gives compiler error every time I leave comma there. And it doesn't even give the line where it was broken, just http://4.stefantsov.com/s/2017.04.13_12.03.03_9b03zkog.png

**Comment by antonmedv** [comment]
It's possible to add array syntax in deployer. I'm trying to keep Deployer API simple as possible but not simpler.
