### ISSUE TITLE
Is it possible to create task for server

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#1159]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question, Feature Request

### Description 
I know that it is possible to set task for environment but I want to execute on one server and just one task.
```
task(...)->onlyForStage('db');
```
would be ok, but I can't tell deployer that it should not execute other tasks on this server.
basically I want to initiate database backup on database server with does not have any code. maybe would be useful to have some flag to set that deployer could skip all tasks except they are specifically defined for this server or something..

Maybe I can do this in current version just don't know how?

**Comment by antonmedv** [comment]
Just call it directly: `dep db:dump db`

**Comment by svycka** [comment]
@antonmedv I know I could do this, but then I have to create bash script to run deployment and I am using deployer just because I don't want this. And this was just and example I have more servers like images, cache also I run tasks before and after new release like sending newsletters about new release, running tests.. And if I have to find other tool to do this whats the point using deployer?

**Comment by antonmedv** [comment]
You can use new Deployer v5, there are `onHosts` `onRoles` `onStages` filtering for tasks.
