### ISSUE TITLE
Using password

### ISSUE THREAD

**Issue by dima-stefantsov** [deployphp/deployer#1162]
Why are you making it harder?

It was pretty simple,
server
user
password

Deployer was easy to use.
Now it's some weird "host" (wth is 'host' I'm connecting to a server, by an ip!), etc. And now, there's no -> password() at all!

How do I deploy using password?

Me having to ask this trivial question means there is something hugely wrong with the way deployer is going.

**Comment by antonmedv** [comment]
OpenSSH uses **host** naming. AS deployer rely on OpenSSH i've decided to use host too. Also a lot of other tools uses **host** too: capistrano, fabfile, ansible, terraform.

**Comment by dima-stefantsov** [comment]
So my question was "how to use password to connect to server?", and your answer is "host naming is good, [Closed]"?

How do I use password to connect to remote host, @antonmedv ?
I have found no ->password() function.

**Comment by antonmedv** [comment]
There is no password func. Deployer will ask you about it:
<img width="828" alt="2017-04-14 16 38 53" src="https://cloud.githubusercontent.com/assets/141232/25040027/358450a6-2131-11e7-8331-0c7c5f222e98.png">

**Comment by antonmedv** [comment]
Passprase with git_tty:
```
➤ Executing task deploy:update_code
[beta] > which git
[beta] < /usr/bin/git
[beta] > /usr/bin/git version
[beta] < git version 2.1.4
[beta] > if [ -h ~/beta/release ]; then echo 'true'; fi
[beta] < true
[beta] > readlink ~/beta/release
[beta] < releases/14
[beta] > /usr/bin/git clone -b master --depth 1 --recursive -q git@gitlab.com:medv/pro.git ~/beta/releases/14 2>&1
medv@**********'s password:
Connection to ********** closed.
• done on [beta]
✔ Ok [10s 651ms]
```

**Comment by ivangretsky** [comment]
@antonmedv, I think @dima-stefantsov 's question was about connecting to SSH with a login/password and being able to define the password in deploy.php. The password() function is gone. Please consider putting it back, please.

**Comment by antonmedv** [comment]
Make a pr.

**Comment by npotier** [comment]
Hello @antonmedv,

I'm having the same problem than @ivangretsky. Using SSH user and password in deploy.php file was useful to deployer using CI tools, such as Gitlab CI.

I would like to contribute in order to restore the ```password()```method.

I've tried to compare ```server``` (deployer v4) and ```host``` (deployer v5) and I'm confused about what to do, because it seems like a lot of things changed.

Any help would be appreciated.

**Comment by antonmedv** [comment]
@npotier you still can you password (but i don't recommend that), take a look at sshpass tool.

**Comment by dima-stefantsov** [comment]
>  I'm confused about what to do, because it seems like a lot of things changed.
>
> Any help would be appreciated.

Hi @npotier, what I'm about to propose may not sound good, but given the circumstances I found it to be the best solution: continue using old deployer that works for you. For me it is dep v3.3, it works really well.

Newer versions do not.

**Comment by antonmedv** [comment]
Better to use modern version of any software — bug got fixes, performance improved, and so on.

**Comment by dima-stefantsov** [comment]
> Better to use modern version of any software — bug got fixes, performance improved, and so on.

That's the general understanding. it sadly does not apply to `deployer` at all.
I've lost few full days trying to make v5 work for my workflow, back to v3.
Maybe my experience will be useful to you, Reader.

**Comment by npotier** [comment]
Thank you for your answers.

@antonmedv : I looked at sshpass, it sounds interesting. Do you have an example of how to use sshpass in a ```deploy.php``` file ? Should I override ```ssh``` commands ?

@dima-stefantsov : I would prefer to use latest version of deployer, but you are right, for now i'll use deployer 4.3

**Comment by ivangretsky** [comment]
Have to partly agree with @dima-stefantsov. The new version might be easier to maintain and maybe even market (the stars count goes up after all), but it is harder to get started with comparing to 3.x. Especially for windows users. Just maybe we falling out of the target audience))

I decided not to fight but to conform) Installed bash on windows, started to use ssh key authentication. But it is not getting more friendly on an average user.

**Comment by antonmedv** [comment]
@ivangretsky i think better docs will help here. So this is what i'm working on now. Also i think 5.x is much friendly to users, we put a lot of work into this piece of software :)

**Comment by npotier** [comment]
@antonmedv Thank you very much. And thanks again for Deployer, which is very cool 👍
