### ISSUE TITLE
[QUESTION] Is Deployer 5.x compatible with PHP 5.6.x ?

### ISSUE THREAD

**Issue by kslimani** [deployphp/deployer#1163]
Does Deployer 5.x works only with PHP 7 or does it also support PHP 5.6.x ?

**Comment by barryvdh** [comment]
According to the composer.json it isn't, but you would only need php7 on the deployment machine

**Comment by kslimani** [comment]
Allright, this explains the error with PHP 5.6 😃 
Thank you @barryvdh .
