### ISSUE TITLE
Allow to configure multiplexing

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1165]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.x

### Description 

Allow to configure multiplexing with host options.

```php
host(...)
    ->options(['ControlPersist=360'])
```

**Comment by mikeymike** [comment]
@antonmedv are you open to PRs on this ? (just wanted to make sure you wasn't working on it atm)

**Comment by antonmedv** [comment]
No, i don't working on this right now.
