### ISSUE TITLE
RunLocally no longer parses the command

### ISSUE THREAD

**Issue by mikeymike** [deployphp/deployer#1169]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
As of [this change](https://github.com/deployphp/deployer/commit/df21fa16ea0afeeb5220aaad92a164f742c8263d#diff-84b928a9905378810b602c8a740b4cbaL262) we're no longer parsing locally run commands which caues failures in the recipes such as rsync. 

I believe this was likely a regression as it doesn't make sense to be different to how the `run` function handles commands.

**Comment by antonmedv** [comment]
Thanks! You are right. Fixed.

**Comment by antonmedv** [comment]
26cfd93cbf37336285b6909f51eb92a329ae8ef8
