### ISSUE TITLE
Do I have to install "git" on my production servers?

### ISSUE THREAD

**Issue by cartmanchen** [deployphp/deployer#1170]
I want to fetch code on local server, and then upload them to my production servers

**Comment by antonmedv** [comment]
This is possible. For 4.x there was https://github.com/deployphp/recipes/blob/4.x/docs/local.md recipe.

For new Deployer 5.x there will be possibility to do it with standard common recipe (docs are coming (more info here https://github.com/deployphp/recipes/issues/125#issuecomment-292707050))

**Comment by cartmanchen** [comment]
Thanks.
