### ISSUE TITLE
Documentation not up to date on site / v3 -> v4 migration instructions

### ISSUE THREAD

**Issue by khromov** [deployphp/deployer#1173]
### Description 

While https://deployer.org/ now links to version 4.3, the documentation on the same site site still uses `set()` / `get()` which are deprecated, for example here: https://deployer.org/docs/configuration

It's **very** confusing for newcomers and I know several people that gave up on using Deployer because they just couldn't get it to work due to incorrect documentation. Would like to see it get fixed.

I also suggest adding migration instructions for existing recipes, similar to what I have written here:
https://snippets.khromov.se/upgrading-from-deployer-3-to-deployer-4/

Lastly, running `deployer self-update` does not update version 3 to version 4, furthering the confusion even more.

**Comment by antonmedv** [comment]
>  the documentation on the same site site still uses set() / get() which are deprecated, for example here: 

They aren't deprecated.

> It's very confusing for newcomers and I know several people that gave up on using Deployer because they just couldn't get it to work due to incorrect documentation. Would like to see it get fixed.

I agree. Better docs required. I have plans on improving it a lot. 

> Lastly, running deployer self-update does not update version 3 to version 4, furthering the confusion even more.

I think docs required here too. You need to add `--upgrade` or `-u` option to migrate major versions. See `dep help self-update`

**Comment by khromov** [comment]
@antonmedv `env()` **is** deprecated in the `4.3` branch:
https://github.com/deployphp/deployer/blob/4.x/src/functions.php#L729

Maybe you reverted this change, but the currently latest version does not work with `env()` and throws an error for recipes.

**Comment by antonmedv** [comment]
> https://deployer.org/docs/configuration

Couldn't find any `env` calls.

**Comment by xdemoor** [comment]
https://deployer.org/docs/servers

Stages

You can define every server with a stage, or list of stages:

server(...)
    ->env('stages', ['stage']);
