### ISSUE TITLE
Cleanup task not keeping releases correctly

### ISSUE THREAD

**Issue by mikeymike** [deployphp/deployer#1175]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | master
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Example of the bug can be seen on https://3v4l.org/cXYMq

When you only want to keep 1 release it deletes it, whilst keeping more releases it seems to keep 1 less than required

**Comment by mikeymike** [comment]
As mentioned in the PR #1176 my use case separates code deployment and release symlink into two separate commands because our `release` could be a DB upgrade release or may just be an atomic release, so a deploy may look something like below

```
vendor/bin/dep deploy production
vendor/bin/dep release:upgrade production
```

With this in mind the second command includes the new release in the release list while common deploys with one command will use the cache from a `get('release_list')` call from earlier in the task list. 

In my opinion this caching is causing unexpected behaviour ... what do you think ?

**Comment by antonmedv** [comment]
I agree. I think we need to update releases list cache after new release and use your pr.

**Comment by mikeymike** [comment]
What are your thoughts on defining if it's cachable on the `set` method .. so it's signature would change to `set(name, value, cacheable = true)` 

This way there are things that never change during deployment that can be cached, e.g. binary locations etc while other closures can be set to run each time they are called by setting cacheable to false

**Comment by antonmedv** [comment]
No, i think it will make stuff more complicated. I just was thinking about adding this to `deployer:release`:
```php
add('releases_list', $new_release);
```

**Comment by mikeymike** [comment]
Ahh yeah that makes sense, I'm still learning the codebase so was unaware of that function 😄 , I'll update and reopen that PR with this change later today 👍

**Comment by antonmedv** [comment]
Fixed.
