### ISSUE TITLE
Exclude certain repo files from deployment to server

### ISSUE THREAD

**Issue by malamoet** [deployphp/deployer#1183]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description

Is it possible to exclude certain repo files (e.g. Grunt/Gulp file, package.json, yarn.lock, .gitgnore, ...) so they don't end up on the server?

**Comment by antonmedv** [comment]
Use clear_paths.
