### ISSUE TITLE
Failure on Windows 10 local server

### ISSUE THREAD

**Issue by salarmehr** [deployphp/deployer#1188]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | master
| Local Machine OS  | win 10
| Remote Machine OS | win 10

 Here is my dep.php file:

```
<?php

namespace Deployer;
require 'recipe/common.php';

localServer('dd')
//    ->stage('local')
    ->set('deploy_path', 'D:\www\www\lab\dep\path');
```

trying to to `dep deploy:prepare` task I got the following error:

```
Warning: ssh type `phpseclib` will be deprecated in Deployer 5.
Add this lines to your deploy.php file:

    set('ssh_type', 'native');
    set('ssh_multiplexing', true);

More info here: https://goo.gl/ya8rKW
ظئج Executing task deploy:prepare


  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "if [ ! -d D:\www\www\lab\dep\path ]; then mkdir -p D:\www\www\lab\dep\path; fi" failed.
  Exit Code: 1(General error)
  Working directory: D:\www\www\lab\dep
  Output:
  ================
  Error Output:
  ================


deploy:prepare [-p|--parallel] [--no-hooks]
```

Is deployer compatible with windows? I'm trying to use my local machine to test deployer features.

**Comment by salarmehr** [comment]
The issue sources from `deployer/deployer/recipe/deploy/prepare.php:33` :
````
      run('if [ ! -d {{deploy_path}} ]; then mkdir -p {{deploy_path}}; fi');
````
That command is not cross platform. It can be simply resolved by using php `mkdir()` (http://php.net/manual/en/function.mkdir.php) function or checking the OS and using appropriate command. 

I can send a PR for that if you are open to merge it. There may be other places to modify. 

I did not use laravel Envy because it does not support Windows currently and I hope I can employ deployer instead.

**Comment by antonmedv** [comment]
Try 5.0.0.-beta.2
