### ISSUE TITLE
Latest version points to wrong .phar

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1190]
At https://deployer.org/download it says the latest version is 5.0-beta2, but after downloading, it actually is 4.3. 
The 'other versions' links do work, but this is confusing as it leads to errors when upgrading (eg. undefined functions).

**Comment by antonmedv** [comment]
Oh, will fix it.

**Comment by antonmedv** [comment]
fixed

**Comment by barryvdh** [comment]
Btw, you can also upload binaries to your Github releases page if you want, you could even link them from there :)

**Comment by antonmedv** [comment]
No, its builded on server automatically. Also manifest update and so on. I'm only adding tags)
