### ISSUE TITLE
Auto unlock on failure 

### ISSUE THREAD

**Issue by salarmehr** [deployphp/deployer#1193]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4

### Description 
Consider this laravel deploy script as an example:

```
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
    'artisan:view:clear',
    'artisan:cache:clear',
    'artisan:config:cache',
    'artisan:optimize',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])
```
If any of these step fails we need to manually unlock deployment. I believe logically when script exits ether with failure or success the unblock recipe should be executed.

**Comment by antonmedv** [comment]
This is possible to do in Deployer v5:
```php
after('deploy:failed', 'deploy:unlock');
```

**Comment by salarmehr** [comment]
@antonmedv Thanks for your reply. How can I access v5 docs? and when will the stable version release?

**Comment by salarmehr** [comment]
BTW, I think `after('deploy:failed', 'deploy:unlock');` should be done in `deploy:failed` by default.

**Comment by antonmedv** [comment]
It done in temple by default :) 
I hope release will be soon. If you can join test it will help.

**Comment by salarmehr** [comment]
@antonmedv doc need a new page upgrade guid == https://github.com/deployphp/deployer/blob/master/UPGRADE.md

**Comment by antonmedv** [comment]
Feel free to add)
