### ISSUE TITLE
Selecting server on cmd? v5

### ISSUE THREAD

**Issue by salarmehr** [deployphp/deployer#1194]
I have just upgraded to master. How can I selectively deploy on one server. I see the server name on `server` function is not available on `host` function. Some hose name are really long and hostname cannot act as server's name.

**Comment by antonmedv** [comment]
Use full hostname or stage.

**Comment by salarmehr** [comment]
@antonmedv How can I use them?
There is no switch for selecting them in cmd

```
Usage:
  command [options] [arguments]

Options:
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
  -f, --file[=FILE]          Specify Deployer file
      --tag[=TAG]            Tag to deploy
      --revision[=REVISION]  Revision to deploy
      --branch[=BRANCH]      Branch to deploy
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by salarmehr** [comment]
‌Please keep the ability to assign a name to a host (alias). It can as a shorthand or mnemonic for hostname. It has no downside.

**Comment by antonmedv** [comment]
You can use ssh config for aliasing:
```
Host alias
   ...
~~~

**Comment by salarmehr** [comment]
Oh, never used that file before. Seems cool. Thanks. 

http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by antonmedv** [comment]
So now deployer trying not to duplicate functionality what goes with ssh itself.
