### ISSUE TITLE
  The command "echo $0" failed.

### ISSUE THREAD

**Issue by salarmehr** [deployphp/deployer#1195]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | master
| Local Machine OS  | win 10
| Remote Machine OS | centos

```
  [Deployer\Exception\RuntimeException (-1)]
  The command "echo $0" failed.
  Exit Code: -1 (Unknown error)
  Host Name: ec2-54-213-43-192.us-west-2.compute.amazonaws.com
  ================
  mm_receive_fd: no message header
  process_mux_new_session: failed to receive fd 0 from slave
  mux_client_request_session: read from master failed: Connection reset by peer
  Failed to connect to new control master
```

It get this error some times (a lot) and rerunning code for several time it works.

**Comment by antonmedv** [comment]
http://gcc.gnu.org/wiki/SSH_connection_caching "Unfortunately if you are using OpenSSH on Cygwin you will not be able to take advantage of connection caching because Cygwin does not currently support file descriptor passing via unix-domain sockets."

try bash on windows

**Comment by salarmehr** [comment]
I was using cmd and gitbash in version 4 without any issue. Should I downgrade? It seems the ssh_type config is removed in new version. May you please provide some details regarding this change. 

BTW, using windows bash is not so comfortable, it need its own set of programs to be installed.

**Comment by antonmedv** [comment]
v5 does only with native ssh implementation. This restriction really helps in maintaining deployer and refactoring codebase also moving forward and implementing new useful features.

**Comment by salarmehr** [comment]
I could connect to CentOS from Windows again by setting `set('ssh_multiplexing', false);` :) 

@antonmedv

**Comment by antonmedv** [comment]
Well, this looks like openssh multiplexing does not working in your case. Will be cool if you can debug it and find why.

**Comment by ivangretsky** [comment]
Nobody I know is using bash on windows yet. It is gitbash in most cases and cygwin time to time. I think there should be at least a clear explanation on why the previously working features are being removed and how to deal with the situation.

**Comment by antonmedv** [comment]
I'll weite docs for window guys) but i think it will be bash anyway))

**Comment by salarmehr** [comment]
@ivangretsky 👍 100% correct.

According to https://insights.stackoverflow.com/survey/2017 Windows is the most popular OS among developers. I hope to see better deployer support in future.

**Comment by antonmedv** [comment]
@salarmehr most users of Deployer use linux, rest – macos, only a fraction use windows.

**Comment by ivangretsky** [comment]
...and that is what you should try to change, @antonmedv, to make Deployer more successful)

By the way, how do you know? Is there some kinв of tracking?

**Comment by antonmedv** [comment]
@ivangretsky yes, anonymous stats, see #1196
