### ISSUE TITLE
SSH/Deployer problem

### ISSUE THREAD

**Issue by cbuchler** [deployphp/deployer#1197]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.1.0
| Local Machine OS  | MacOSX
| Remote Machine OS | Debian 9

### Description 
I've been checking my configurations for the past two hours and it seems there is something missing. 
We use Public/Private Key authentication for ssh logins.
We use Gitlab deploy keys.

Can someone point me in a new direction? 

### Steps to reproduce
Run the deploy command to deploy to **production** 
### Content of `deploy.php`
```php
<?php
/*
 * This file has been generated automatically.
 * Please change the configuration for correct use deploy.
 */

namespace Deployer;
require 'recipe/common.php';

// Set configurations
set('repository', 'git@git.code.int:dev/pwp.git');
set('shared_files', []);
set('shared_dirs', []);
set('writable_dirs', []);

set('keep_releases', 0);

server('staging', 'staging.host.xxx')
    ->user('deploy')
    ->forwardAgent()
    ->stage('staging')
    ->set('branch', 'develop')
    ->set('deploy_path', '/var/www/host.xxx/staging/site/wp-content/themes/');

server('production', 'prod.host.xxx') 
    ->forwardAgent()
    ->user('deploy')
    ->stage('production')
    ->set('branch', 'develop')
    ->set('deploy_path', '/home/deploy/theme');



task('extract_wp', function () {
    run('cp -R  {{deploy_path}}/current/* {{deploy_path}}/pirate/');
})->desc('Extracting Wordpress theme');

task('compile_assets', function () {
    run('cd {{deploy_path}}pirate/ && gulp  --production');
})->desc('Compiling assets');
/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
    'extract_wp',
    'compile_assets',
    'cleanup',
])->desc('<info>Successfully deployed!</info>');

after('deploy', 'success');

```

### Contents of SSH Debug
deploy@crm:~$ ssh -vT git@git.cwc.lu
OpenSSH_7.4p1 Debian-10, OpenSSL 1.0.2k  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to git.cwc.lu [163.172.188.133] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deploy/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to git.cwc.lu:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:9PbX9nir6s1jiCmqGJrPXiMCjR5gefTqOhSpmbB1Ze4
debug1: Host 'git.cwc.lu' is known and matches the ECDSA host key.
debug1: Found key in /home/deploy/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/deploy/.ssh/deploy_key
debug1: Server accepts key: pkalg rsa-sha2-512 blen 535
debug1: Authentication succeeded (publickey).
Authenticated to git.cwc.lu ([163.172.188.133]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: PTY allocation disabled.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
Welcome to GitLab, Charles Büchler!
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3536, received 3576 bytes, in 0.7 seconds
Bytes per second: sent 4821.1, received 4875.6
debug1: Exit status 0

### Contents of SSH Config
```
#	$OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin


Port 22
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
SyslogFacility AUTH
LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2

AuthorizedPrincipalsFile none

AuthorizedKeysCommand none
AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

AllowAgentForwarding yes
AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#UsePrivilegeSeparation sandbox
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem	sftp	/usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server
```
### Output log
dep deploy production -vvv
➤ Executing task deploy:prepare
[production] > echo $0
[production] < bash
[production] > if [ ! -d /home/deploy/pirate-theme ]; then mkdir -p /home/deploy/pirate-theme; fi
[production] > if [ ! -L /home/deploy/pirate-theme/current ] && [ -d /home/deploy/pirate-theme/current ]; then echo true; fi
[production] > cd /home/deploy/pirate-theme && if [ ! -d .dep ]; then mkdir .dep; fi
[production] > cd /home/deploy/pirate-theme && if [ ! -d releases ]; then mkdir releases; fi
[production] > cd /home/deploy/pirate-theme && if [ ! -d shared ]; then mkdir shared; fi
• done on [production]
✔ Ok [610ms]
➤ Executing task deploy:release
[production] > cd /home/deploy/pirate-theme && (if [ -h release ]; then echo 'true'; fi)
[production] < true
[production] > cd /home/deploy/pirate-theme && (rm -rf "$(readlink release)")
[production] > cd /home/deploy/pirate-theme && (rm release)
[production] > cd /home/deploy/pirate-theme && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[production] < true
[production] > cd /home/deploy/pirate-theme && (cd releases && ls -t -d */)
[production] < 1.3/
[production] < 1.2/
[production] < 2/
[production] < 1/
[production] > cd /home/deploy/pirate-theme && (if [ -f .dep/releases ]; then echo "true"; fi)
[production] < true
[production] > cd /home/deploy/pirate-theme && (tail -n 5 .dep/releases)
[production] < 20170505175904,1.1
[production] < 20170505180931,1.1
[production] < 20170508090059,1.1
[production] < 20170508091433,1.1
[production] < 20170508093315,1.1
[production] > cd /home/deploy/pirate-theme && (if [ -d /home/deploy/pirate-theme/releases/1 ]; then echo 'true'; fi)
[production] < true
[production] > cd /home/deploy/pirate-theme && (if [ -d /home/deploy/pirate-theme/releases/1.1 ]; then echo 'true'; fi)
[production] > cd /home/deploy/pirate-theme && (date +"%Y%m%d%H%M%S")
[production] < 20170508104559
[production] > cd /home/deploy/pirate-theme && (echo '20170508104559,1.1' >> .dep/releases)
[production] > cd /home/deploy/pirate-theme && (mkdir /home/deploy/pirate-theme/releases/1.1)
[production] > cd /home/deploy/pirate-theme && (if [[ "$(man ln)" =~ "--relative" ]]; then echo "true"; fi)
[production] < true
[production] > cd /home/deploy/pirate-theme && (ln -nfs --relative /home/deploy/pirate-theme/releases/1.1 /home/deploy/pirate-theme/release)
• done on [production]
✔ Ok [898ms]
➤ Executing task deploy:update_code
[production] > which git
[production] < /usr/bin/git
[production] > /usr/bin/git version
[production] < git version 2.11.0
[production] > if [ -h /home/deploy/pirate-theme/release ]; then echo 'true'; fi
[production] < true
[production] > readlink /home/deploy/pirate-theme/release
[production] < releases/1.1
[production] > /usr/bin/git clone -b develop  --recursive -q git@git.cwc.lu:piraten/piraten-wp.git /home/deploy/pirate-theme/releases/1.1 2>&1
➤ Executing task deploy:failed
• done on [production]
✔ Ok [0ms]

  [RuntimeException]
  Permission denied, please try again.
  Permission denied, please try again.
  Permission denied (publickey,password).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:124
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:310
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/update_code.php:59
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:91
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:80
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:186
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:110
 require() at /usr/local/bin/dep:4
*

**Comment by antonmedv** [comment]
If you have deploy keys, where no need for `forwardAgent()`, use `identityFile(...)` instead. 

Also i really recommend you to take a look at next Deployer v5. It still in beta, but release will be soon. It fully uses your ssh config file.

**Comment by cbuchler** [comment]
@antonmedv thank you for your comment. I've tried it, however now I can't even login onto the production server. 

I should also note that, if the deployment user logs-in, via the .bash_login file the deploy key will be added to the SSH-Agent automatically. 

If I clone the repository manually using the key it works. :/

**Comment by antonmedv** [comment]
Hard to tell what going on there. phpseclib used by v4.1 is unpredictable =)
try to upgrade to 5.0.0-beta.3 or to 4.3.0 (this version has native ssh client)

**Comment by cbuchler** [comment]
Will do and let you know afterwards!

**Comment by cbuchler** [comment]
@antonmedv wohoo 4.3.0 works like a charm. Thank you very much!
