### ISSUE TITLE
Define multiple localhosts no longer possible with v5

### ISSUE THREAD

**Issue by stucki** [deployphp/deployer#1199]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0-beta3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description
I have a server where deployer is run locally at various locations.
In previous versions (v4.3.0), it was possible to define multiple `localServer` entries with different names for this.
In the latest beta (v5.0-beta3) I can only define one `localhost` entry.
There can be multiple `host` entries but this will always involve SSH (see #138), so it's not an option for me.

### Proposed solution
It should be possible (again) to set an optional name for `localhost` entries like it was possible with `localServer`.

**Comment by antonmedv** [comment]
This is possible through _alias_ hosts:

~~~php
host('localhost/foo');
host('localhost/bar');
host('localhost/baz');
~~~

https://github.com/deployphp/docs/blob/master/hosts.md#host-aliases

**Comment by mickaeltardy** [comment]
Unfortunately that didn't work out for me. Using aliases makes deployer use ssh connection. However, I'm running deploy inside a docker container and wish not to install ssh service in the container.

**Comment by antonmedv** [comment]
@mickaeltardy what about this?
```php
```

**Comment by mickaeltardy** [comment]
@antonmedv 
Works well. Thank you! My bad, should have checked the API 
https://github.com/deployphp/docs/blob/master/api.md

### localhost

* `localhost(string ...$alias = 'localhost'): Host`
