### ISSUE TITLE
Is it possible to deploy a specific tag instead of lastest on a branch ?

### ISSUE THREAD

**Issue by faboo03** [deployphp/deployer#120]
Is it possible to deploy a specific tag, instead of the last commit on master ?? Would be useful to make rollback...

**Comment by elfet** [comment]
Done! :beers: 
To deploy specific branch:
```php
set('branch', 'master');
```

To deploy specific tag:
```
dep deploy --tag="v3.0.0"
```

And even more. To deploy production stage:
```
dep deploy production
```

:gem: :gem: :gem:
