### ISSUE TITLE
set() callback functions broken

### ISSUE THREAD

**Issue by FlorianMoser** [deployphp/deployer#1200]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.3.0
| Local Machine OS  | OSX
| Remote Machine OS | Ubuntu

### Description 
Dynamic values using callback function in set() does not work.

Take this configuration and task:

```php
set('var', 'original');
set('dynamic', function() {
	return get('var');
});

task('test', function() {
	writeln(get('dynamic'));
	set('var', 'changed');
	writeln(get('dynamic'));
});
```

Expected output:

```
➤ Executing task test
original
changed
✔ Ok
```

Real output:

```
➤ Executing task test
original
original
✔ Ok
```

This also seems to apply to master version.

I think the error is in Deployer\Server\Environment::get() on line 112:

```php
    public function get($name, $default = null)
    {
        if ($this->values->has($name)) {
            if ($this->isClosure($this->values[$name])) {
                $value = $this->values[$name] = call_user_func($this->values[$name]);
            } else {
                $value = $this->values[$name];
            }
        } else {
            $config = Deployer::get()->config;

            if (isset($config[$name])) {
                if ($this->isClosure($config[$name])) {
                    $value = $this->values[$name] = call_user_func($config[$name]);
                } else {
                    $value = $this->values[$name] = $config[$name];
                }
            } else {
                if (null === $default) {
                    throw new \RuntimeException("Configuration parameter `$name` does not exists.");
                } else {
                    $value = $default;
                }
            }
        }

        return $this->parse($value);
    }
```

A closure is never cached, only the output of the closure. I suggest the following changes:

```php
    public function get($name, $default = null)
    {
        if ($this->values->has($name)) {
            if ($this->isClosure($this->values[$name])) {
                $value = call_user_func($this->values[$name]);
            } else {
                $value = $this->values[$name];
            }
        } else {
            $config = Deployer::get()->config;

            if (isset($config[$name])) {
                if ($this->isClosure($config[$name])) {
                    $value = call_user_func($config[$name]);
                } else {
                    $value = $config[$name];
                }
	            $this->values[$name] = $config[$name];
            } else {
                if (null === $default) {
                    throw new \RuntimeException("Configuration parameter `$name` does not exists.");
                } else {
                    $value = $default;
                }
            }
        }

        return $this->parse($value);
    }
```

Note the changes on line 116 and 125, 127, 129.

**Comment by antonmedv** [comment]
This is done on purpose, it's not a bug. First value returned from callback cached. This is some sort of lazy evaluation (not dynamic). 
I think better docs needed here.

**Comment by FlorianMoser** [comment]
I re-read the docs:

> Configuration parameters also can be specified as callback function, which will be executed on remote server on **first** get call

Seems clear. But can you still call it a "callback function", when it is only executed on first call? Wouldn't it make sense to have real callbacks? Why the caching, for performance?

For example I currently have the problem, that I need to change the release symlink during deployment. This could easily be done with a callback function. Without callback I'll have to write my own release.php and symlink.php recipes.

**Comment by antonmedv** [comment]
> Why the caching, for performance?
Yes.

If you need to change it, use `set` or `add` function.
