### ISSUE TITLE
How to configure an SSH gateway for servers

### ISSUE THREAD

**Issue by jojonaloha** [deployphp/deployer#1202]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Is there a way to setup server environments to use an SSH gateway? I've used capistrano in the past and you just need to `set :gateway, "gateway.example.com"` for each stage. I would expect this to look something like:
```
server('production', 'domain.com')
    ->user('username')
    ->identityFile()
    ->set('gateway', 'gateway.example.com');
```

I can't find any documentation on this though, so am curious how this is/could be done https://deployer.org/docs/servers

**Comment by antonmedv** [comment]
What is gateway?

**Comment by jojonaloha** [comment]
Gateway is an intermediate server that you need to ssh into because SSH directly to the actual production server is restricted or is within a private network.

**Comment by antonmedv** [comment]
Please, show what ssh command or ssh config you are using.

**Comment by sbacelic** [comment]
You can use something like this in your ~/.ssh/config
```
Host gw
   User username
   Hostname gateway.example.com
   Port 22
Host domain.com
   User username
   Hostname domain.com
   ProxyCommand ssh -q gw -x -W %h:22
```
