### ISSUE TITLE
Changing current symlink name to custom one

### ISSUE THREAD

**Issue by ivangretsky** [deployphp/deployer#1203]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5 beta
| Local Machine OS  | Windows 10
| Remote Machine OS | Linux

### Description 
The name of the symlink produced by the `deploy:symlink` task of the common recipe is hard coded to `current `. In the environments where you cannot configure the web root name (shared hosting) it would be useful to be able to change that to a custom name (like public_html or www) via simple config option.

**Comment by antonmedv** [comment]
See #1107

**Comment by vkryukov76** [comment]
@ivangretsky 
You could make a symlink to `current` or any other dir  from your webroot on target server.

In my case root of repository is not a contents of public_html dir, so my first pre-deployment action is something like

```
ln -s /home/username/project/current/public /home/username/public_html
```
