### ISSUE TITLE
Incorrect symlinks

### ISSUE THREAD

**Issue by salarmehr** [deployphp/deployer#1214]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug,
| Deployer Version  | Dev master
| Local Machine OS  | centos
| Remote Machine OS | windows

### Description 
Consider you have folder in `/foo/bar/files/image/` that contains images of the sites and you refer to that folder as `files/image/` in the scr attributes of `img` tags. So we need a symlink to `/foo/bar/files` and logically add `/foo/bar/files/` to shared dirs config. Unexpectedly, deployer create a symlink to `/foo/` in the release folder in stead of `files/image`

**Comment by antonmedv** [comment]
Please, read this: https://github.com/deployphp/deployer/blob/master/CONTRIBUTING.md
