### ISSUE TITLE
Error when executing deployer.phar

### ISSUE THREAD

**Issue by adrorocker** [deployphp/deployer#1216]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.0
| Local Machine OS  | macOS sierra
| Remote Machine OS | N/A

### Description 

When trying to run `dep init` or `deployer.phar init` I get this error:

```
Parse error: parse error in phar:///usr/local/bin/dep/src/Deployer.php on line 351
```

I did install it as suggested in https://deployer.org/docs/installation and I even build it myself

**Comment by antonmedv** [comment]
Upgrade to php7.
