### ISSUE TITLE
Symfony recipe doesn't ask for parameters it just fails

### ISSUE THREAD

**Issue by moralesfelipe** [deployphp/deployer#1217]
It doesn't ask for parameters

**Comment by antonmedv** [comment]
Yes, you should create parameters.yml your self before continue (in shared)

**Comment by moralesfelipe** [comment]
Can I create in a diferent file and upload to parameters.yml so I don't share my dev credentials to production?

**Comment by moralesfelipe** [comment]
The shared option doesn't work neither 

...
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
add('shared_files', ['app/config/parameters.yml']);
add('shared_dirs', []);
add('writable_dirs', []);
set('allow_anonymous_stats', false);
