### ISSUE TITLE
Tracking deployed versions

### ISSUE THREAD

**Issue by talisman-innovations** [deployphp/deployer#1223]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question / Feature Request
| Deployer Version  | 4.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Hi

First off, we are using deployer for all of our projects and loving it - big thanks to all involved.

I'd like to be able to know definitively what "version" of an application has been deployed onto a server.  I've put "version" as git doesn't really do versions, but there are a few ways to identify the code.

* The branch name and commit
* MD5 signature of the code
* any other ideas

Currently deployer add some information into the .dep folder on the server.  Could this be augmented with some additional version information.  I seem to remember that a previous version of deployer did this, so maybe it's been removed for a good reason.

Thanks

Steve

**Comment by antonmedv** [comment]
Hi,

> The branch name and commit

This is good idea. 

> with some additional version information. I seem to remember that a previous version of deployer did this, so maybe it's been removed for a good reason.

Now i.m working on system where you can easily track all of your deployments: https://deployer.org/pro/continuous-integration
