### ISSUE TITLE
List copied file types in `copy_dirs`

### ISSUE THREAD

**Issue by dakur** [deployphp/deployer#1230]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | -
| Local Machine OS  | -
| Remote Machine OS | -

### Description 
It would be nice to have an option to set just some file types to copy in `copy_dirs` directive. For example:
```
set('copy_dirs', [
    'dist/*.js',
    'dist/*.css'
]);
```
Don't know, maybe `copy_files` would be better with allowing concrete files as well (eg `dist/abcd.css`).

**Comment by antonmedv** [comment]
I think `copy_files` is better here:
```php
set('copy_files', [
    'dist/*.js',
    'dist/*.css'
]);
```

**Comment by fabkow** [comment]
PR (#1392) added with copying file by file: 
```php
set('copy_files', [
     'dist/file1.txt',
     'dist/file2.txt',
     'dist/css/main.css'
]);
```

**Comment by dakur** [comment]
@fabkow It is slightly different than what this issue is about as it does not support `*` syntax, but at least good basement for future resolve. :-)

**Comment by antonmedv** [comment]
Can you add support for `*`?

**Comment by dakur** [comment]
If I could, I would. I use deployer at work, so from time to time there is a time gap to help improving underlying open-source libraries, but the time is not now. :-)

**Comment by antonmedv** [comment]
Closing as looks like nobody really interesting in such feature.
