### ISSUE TITLE
Input in declaration context

### ISSUE THREAD

**Issue by gulios** [deployphp/deployer#1233]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 5.0.1
| Local Machine OS  | macOS

### Description 
In 4.3 version i'm checing input parameters in recipie for run different set of tasks depends on context(running manually or from CI).

### Content of `deploy.php`
```php
if (!empty(Deployer::get()->getInput()->getParameterOption('prepared_release'))) {
    $tasks = [
        'some_task',
    ];
} else {
    $tasks = [
        'some_different_task',
    ];
}
task('deploy', $tasks);
```

In new version 5.0.1 i see it stopped working.
Ho can i check input parameters in new version ?

I need to check it outside tasks because i don't want to put condition(hasoption ...) in every task so it's much better to do this once. 

### Output log
*[InvalidArgumentException] Identifier "input" is not defined.

 #0 /data/www/deployment/deployer/vendor/deployer/deployer/src/Deployer.php(264): Pimple\Container->offsetGet('input')
 #1 /data/www/deployment/deployer/deployment/ci-test.php(57): Deployer\Deployer->getInput()
 #2 /data/www/deployment/deployer/vendor/deployer/deployer/src/Deployer.php(309): require('/data/www/deplo...')
 #3 [internal function]: Deployer\Deployer::Deployer\{closure}()
 #4 /data/www/deployment/deployer/vendor/deployer/deployer/src/Deployer.php(310): call_user_func(Object(Closure))
 #5 /data/www/deployment/deployer/vendor/deployer/deployer/bin/dep(120): Deployer\Deployer::run('master',
 '/data/www/deplo...')
 #6 {main}*

### getOutput
SImilar problem with code.

```php
Deployer::get()->getOutput()->writeln("some text");
```
getting "[InvalidArgumentException] Identifier "output" is not defined."

Thx

**Comment by antonmedv** [comment]
Now getting input possible only in task context. You can use task filtering: https://deployer.org/docs/tasks#filtering

**Comment by gulios** [comment]
filtering it's not the same tool and it's hard to achive the same functionalilty.
We're useing recipies in different modes(running manually from CLI by developer) and CI flow so we pass input options to command ex:
running from CI
```
../vendor/bin/dep -frecipe.php deploy production prepared_release=RELEASE  user=SOMEUSER
```
or from CLI by developer:
```
../vendor/bin/dep -frecipe.php deploy production
```

and now we're checking input options `prepared_release` or 'user' to run different set of tasks depends on mode or we want to set user name(for notifications etc) and now we check 'user' option or check 'whoami' and next we can(4.3) 
```
if (!empty(Deployer::get()->getInput()->getParameterOption('user'))) {
    $deployUser = Deployer::get()->getInput()->getParameterOption('user');
} else {
    $deployUser = CommonHelper::getSshUser();
}

set('user', $deployUser);
```
It would be very helpufl to have ability to check input's/argument's values before we run tasks. 
In 4.3 it's great because we have one recipe for different modes and we don;t have to put conditions in all tasks we want to run.

Maybe there is other resolution for that flow? or maybe you can add this functionality to check inputs outside task for recipe.

Thank you.

**Comment by antonmedv** [comment]
You can use env for that.
```php
set('param', getenv('PARAM'));
```

Run: `PARAM=value dep deploy`

**Comment by gulios** [comment]
Ok, thank you it works ;)
