### ISSUE TITLE
Additional options to pass when executing writable job

### ISSUE THREAD

**Issue by milosmiric** [deployphp/deployer#1234]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.0.1
| Local Machine OS  | MacOS Sierra
| Remote Machine OS | Ubuntu 16.04

### Description 
When setting writable on directories on remote server i used chmod/chgrp but i was getting following error:

 chgrp: cannot dereference 'sugar-deployment/vendor/bin/phpunit': No such file or directory

I solved it by adding additional option to chmod or chgrp
-h   affect  each  symbolic link instead of any referenced file
      (useful only on systems that can change the ownership of a symlink)

run("$sudo chown -RLh $httpUser $dirs");

Which resulted in link to shared as well as shared content to be properly set.

Maybe there should be an easy way to add additional options to pass when executing writable commands ?

**Comment by antonmedv** [comment]
Maybe it's better to include this option to main code? Is it supported on debian, centos, macos?

**Comment by eitrix** [comment]
It could be, -h option is part of chmod and chown command on all unix like systems. To me it does make sense to have writable job change ownership of the link itself and the linked files.

**Comment by eitrix** [comment]
I was thinking about this today and decided locally for myself to convert set('writable_mode', into an array of parameters and just iterate over array in already existing writable job logic.

Let me know if you want me to submit a pull request for this.

Thanks!

**Comment by antonmedv** [comment]
@eitrix i was thinking of splitting task into few: #1237
