### ISSUE TITLE
Splitting writable into 2 separate jobs

### ISSUE THREAD

**Issue by milosmiric** [deployphp/deployer#1237]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.0.1
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Writable settings don't really make much sense for a bit more complex scenario. I believe this needs to be broken down into 2 different jobs.

writable-owner
writable-permissions

and 2 different set of settings for those jobs.

I don't have an easy way now to say:

1. I want to chgrp on X directories to www-data
2. I want to chmod 775 on X directories

Because writable job relies on writable_mode and we only can pick 1.

Thoughts?

**Comment by antonmedv** [comment]
I agree. Maybe we should implement some think like cap: https://github.com/capistrano/file-permissions
