### ISSUE TITLE
Separate SSH connection for each step in Deployer 4

### ISSUE THREAD

**Issue by jdavidbakr** [deployphp/deployer#1241]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.3.0
| Local Machine OS  | MacOS 10.11.6
| Remote Machine OS | Linux

### Description 
In version 3.X of deployer, it would connect to each server individually and keep each connection throughout the entire process.  I have recently started using version 4, but have been running into problems because my server is using multi-factor authentication.  This means that I cannot make a new connection to my server more than once every 20 seconds, making deployer 4 unusable, so I'm stuck with deployer 3 right now.

**Comment by antonmedv** [comment]
@jdavidbakr try to use Deployer 5. I has ssh multiplexing.

**Comment by jdavidbakr** [comment]
Thanks @antonmedv - I was going to step my way up to 5 through 4 but 5 does appear to work.
