### ISSUE TITLE
Add a signal handler

### ISSUE THREAD

**Issue by 1ed** [deployphp/deployer#1242]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.0.1
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description 
When I want to abort a deploy and press CTRL-C it stays locked and I have to manually unlock it. It would be great to handle this by adding a signal handler to remove the lock and maybe cleanup before abort.

**Comment by eitrix** [comment]
I do not agree with auto unlocking, if you want that to happen why not just add unlock as your first step in the build ?

**Comment by ryancastle** [comment]
I don't think deployer can presume that unlocking is the best option in the case of an aborted deploy. Is there some sort of `finally` mechanism which might be used if users want to add auto-unlock?

**Comment by antonmedv** [comment]
```php
// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

**Comment by barryvdh** [comment]
I think that's not run when you ctrl+c it, right?

**Comment by antonmedv** [comment]
Right

**Comment by lsv** [comment]
That requires that PHP is build with pcntl - Which is not enabled by default.

Otherwise if you @1ed have it in your PHP installation, you can create do it in your configuration file.

```
pcntl_signal(SIGTERM, function() {
   `dep deploy:unlock`
});
```

**Comment by antonmedv** [comment]
So this feature will be available only for those who have pcntl installed.

**Comment by lsv** [comment]
Thats the only way you can catch CTRL+C commandline command

**Comment by antonmedv** [comment]
> And will never be available on windows 

What about Bash on Windows?

**Comment by antonmedv** [comment]
Will be cool if someone can implement this feature.

**Comment by lsv** [comment]
Good question, if you can install php with pcntl extension, then maybe :)

**Comment by lsv** [comment]
Maybe this could be a inspiration
https://github.com/chEbba/ConsoleSignals
