### ISSUE TITLE
Why does it needs to be so strict?

### ISSUE THREAD

**Issue by jens1o** [deployphp/deployer#1244]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | latest
| Local Machine OS  | Windows 10
| Remote Machine OS | no

Personally, I liked the approach of having some file I can create tasks and these will be updated, for example when I update the scss file. Something like gulp:watch, but in php. I thought this is the perfect library for my approach. But as deeper as I digged in, the more I'm shocked. I can only define deploy tasks, and define just some tasks is pretty hard. 😢 

Do you have any library which fits my needs better?

**Comment by antonmedv** [comment]
What do you mean strict? It's deploy tool. Task can be really easy described.

**Comment by jens1o** [comment]
Well, I feel a bit uncomfortable with it, because everything is related for deployment, but I want to improve development using some tasks...

**Comment by antonmedv** [comment]
If you uncomfortable with it, don't use it. Deployer is a deployment tool.

**Comment by jens1o** [comment]
Okay. Thanks. Do you have any other tool?

**Comment by antonmedv** [comment]
Yes, I have https://monkberry.js.org

**Comment by jens1o** [comment]
Well, I would like to have it in php. But after some points, it fits my needs more or less.
