### ISSUE TITLE
Repeats itself

### ISSUE THREAD

**Issue by jens1o** [deployphp/deployer#1245]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | latest 5.x
| Local Machine OS  | Windows 10 Home
| Remote Machine OS | N/A

### Description 
In the output pane, I get each line-end with the same 2 letters:
![image](https://cloud.githubusercontent.com/assets/11234139/26524546/9d829bbe-4336-11e7-8779-73d3637ee97b.png)

### Steps to reproduce
Create any `deploy.php` .

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require_once 'vendor/autoload.php';

// Configuration
task('minify', function () {

});
```

### Output log
![image](https://cloud.githubusercontent.com/assets/11234139/26524551/c0c4a162-4336-11e7-808b-fa247e10793f.png)
*

**Comment by antonmedv** [comment]
Try use bash on windows.

**Comment by jens1o** [comment]
Why do yo close it so fast? That's not even slightly helpful. Maybe you have problems with control character? Why should it be prohibited for developers to use the Power Shell? Actually, when you want to reach developers, you should make it as easy as possible for **them**, not for you. I'm disappointed.

**Comment by antonmedv** [comment]
I don't support power shell, sorry. Only bash.

**Comment by jens1o** [comment]
But we can do support it?

**Comment by antonmedv** [comment]
Yes, will free to submit a pull request.

**Comment by jens1o** [comment]
Thanks. 😃
