### ISSUE TITLE
Cant use upload function from windows

### ISSUE THREAD

**Issue by egolife** [deployphp/deployer#1247]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  |  5.0
| Local Machine OS  | win10
| Remote Machine OS | centOS

### Description 
Hello, as a part of my deploy process I need to upload some local files.
In version 4 of deployer it works fine (because scp used under the hood).
But in version 5 I get an error (see log below).

So what can I do to actually use deployer 5 from windows?
Can't find anything in docs or issues.
Is there a way to switch upload driver from rsync to scp?

### Steps to reproduce
Just run any task with upload function as it's part from windows machine

### Output log
[Symfony\Component\Process\Exception\ProcessFailedException]
  The command "rsync -azP  public/mix-manifest.json alena2090@remontim.egodev.ru:/home/a/alena2090/remontim/releases/3/public/mix-manifest.json" failed.
  Exit Code: 1(General error)
  Working directory: F:\openserver7\OpenServer\domains\remontim.dev
  Output:
  ================
  Error Output:
  ================
  'rsync' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by antonmedv** [comment]
> 'rsync' is not recognized as an internal or external command,
operable program or batch file.

Install rsync locally. Deployer doesn't offer scp as driver anymore, because rsync is mach more powerful and widely used.
