### ISSUE TITLE
Globally installed deployer "collide" with the one in the vendor folder

### ISSUE THREAD

**Issue by LucaGallinari** [deployphp/deployer#1248]
Hi, i just installed the version 5.0.1 by entering the following commands:
>curl -LO https://deployer.org/releases/v5.0.1/deployer.phar
mv deployer.phar /usr/local/bin/dep501
chmod +x /usr/local/bin/dep501

When i am in a generic folder i can launch "dep501" on the terminal and it works properly. Instead, when i am in folder with a previous version of deployer in "vendor" (4.3.0), if i run "dep501" it shows me this:

> You need to update Deployer to the latest version:
  dep self-update
Or use composer installed version:
  php vendor/bin/dep
 
Can you help me?

**Comment by antonmedv** [comment]
This is feature of deployer. Global Deployer 5 can properly run local Deployer 4 code. So...

You need to update Deployer to the latest version:
```
dep self-update
```
Or use composer installed version:
```
php vendor/bin/dep
```

**Comment by indapublic** [comment]
> ➜  api git:(release) ✗ dep self-update
> You need to update Deployer to the latest version:
> 
>   dep self-update
> 
> Or use composer installed version:
> 
>   php vendor/bin/dep

Just downloaded deployer, but received this error. Tried to update - same error
