### ISSUE TITLE
Option --revision not working

### ISSUE THREAD

**Issue by iluxaar** [deployphp/deployer#1249]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0

### Description 
Option --revision ignored, becouse this code return true:
https://github.com/deployphp/deployer/blob/v3.3.0/recipe/common.php#L180 

This code only return true:
`input()->hasOption('tag')`

### Steps to reproduce
`run $ vendor/bin/dep deploy production --revision="5665737"`

**Comment by antonmedv** [comment]
Fixed in 4.x and 5.x vhttps://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L46
