### ISSUE TITLE
Make task always verbose

### ISSUE THREAD

**Issue by cronfy** [deployphp/deployer#1259]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 5.0.3
| Local Machine OS  | Linux Mint 17.3
| Remote Machine OS | N/A

I have a task that I want to be always verbose, like in `-vvv` mode. 

Currently I achieve it like this:

```
task('yii:migrate', function() {
    $verbosity = output()->getVerbosity();
    output()->setVerbosity(OutputInterface::VERBOSITY_DEBUG);
    run('cd {{ deploy_path }}/release && ./yii migrate --interactive=0');
    output()->setVerbosity($verbosity);
})->desc('apply yii migrations');
```

Is there any simpler way to do it?

**Comment by antonmedv** [comment]
What about this?

```php
desc('apply yii migrations');
task('yii:migrate', function() {
    $output = run('cd {{ deploy_path }}/release && ./yii migrate --interactive=0');
    write($output);
});
```

**Comment by cronfy** [comment]
It's better. 

But maybe we can introduce something like this?

```
task('yii:migrate','
    cd {{ deploy_path }}/release && ./yii migrate --interactive=0
')->verbose();
```
To make it compatible with [Simple tasks](https://deployer.org/docs/tasks#simple-tasks).

**Comment by antonmedv** [comment]
Done in #1904

**Comment by neochief** [comment]
Hi, @antonmedv! Could you please advise how was it done (if it is)? It seems the verbose() method is not present yet, as per @cronfy suggestion.

**Comment by antonmedv** [comment]
Sorry, it's still in separate brunch what wasn't merged to master. I will reopen this branch to not forget.

**Comment by antonmedv** [comment]
Done in 04c2a406e39e9cb0c4fa1047442f942fc5eb4b5b
