### ISSUE TITLE
Run deploy causes InitializationException: Failed to initialize ssh multiplexing

### ISSUE THREAD

**Issue by secretwz** [deployphp/deployer#1266]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 14.04
| Recipe | Symfony (3.3.2)

### Description 

I get an _InitializationException_ if i run "dep deploy", since i updated to version 5.0.3 in my Symfony project.

### Steps to reproduce

1. Deployer 4.0 with a functional deploy.php config in a symfony project
2. Update to Deployer 5.0.3
3. Change "server" to "host" in deploy.php
4. Run "dep deploy test"

### Content of `deploy.php`

```php
namespace Deployer;
require 'recipe/symfony.php';

// Configuration

set('repository', 'git@[...].git');
set('ssh_type', 'native');
set('ssh_multiplexing', true);

add('shared_files', ['web/.htaccess', 'app/config/configuration.yml', 'web/robots.txt']);
add('shared_dirs', ['app/Resources/uploads']);
add('writable_dirs', ['app/Resources/uploads']);

// Hosts

host('test', '88.[...]', '53546')
    ->user('user')
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/test');

host('master', '88.[...]', '53546')
    ->user('user')
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/main');

// Tasks

desc('Compile main sass file');
task('custom:sass', function () {
    run('sass {{release_path}}/web/styles/scss/main.scss {{release_path}}/web/styles/css/main.css -E "UTF-8"');
});

desc('Clear cache');
task('custom:clear_cache', function () {
    run('{{env_vars}} {{bin/php}} {{release_path}}/app/console cache:clear --env=prod --no-debug');
});

desc('Dump assetics');
task('custom:assetic_dump', function () {
    run('{{env_vars}} {{bin/php}} {{release_path}}/app/console assetic:dump --env=prod --no-debug');
});

desc('Dump Composer Classmap (for performance)');
task('custom:classmap_dump', function () {
    run('{{env_vars}} composer --working-dir={{release_path}} dump-autoload --optimize --no-dev --classmap-authoritative');
});

task('first_deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:clear_paths',
    'deploy:create_cache_dir',
    'deploy:shared',
    'deploy:assets',
    'custom:sass',
    'deploy:writable',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])->desc('Deploy project first time');

task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:clear_paths',
    'deploy:create_cache_dir',
    'deploy:shared',
    'deploy:assets',
    'deploy:vendors',
    'custom:sass',
    'custom:clear_cache',
    'custom:assetic_dump',
    'custom:classmap_dump',
    'deploy:writable',
    'deploy:unlock',
])->desc('Deploy new version of project');

task('migrate', [
    'deploy:lock',
    'database:migrate',
    'deploy:unlock'
])->desc('Migrate database');

task('release', [
    'deploy:lock',
    'deploy:symlink',
    'cleanup',
    'deploy:unlock'
])->desc('Release new version');
```

### Output log
➤ Executing task deploy:prepare
[test] > echo $0
[test] < ssh multiplexing initialization
                                                
  [Deployer\Exception\InitializationException]  
  Failed to initialize ssh multiplexing         
                                                
Exception trace:
 () at /var/www/symfony-project/vendor/deployer/deployer/src/Ssh/Client.php:142
 Deployer\Ssh\Client->initMultiplexing() at /var/www/symfony-project/vendor/deployer/deployer/src/Ssh/Client.php:80
 Deployer\Ssh\Client->run() at /var/www/symfony-project/vendor/deployer/deployer/src/functions.php:297
 Deployer\run() at /var/www/symfony-project/vendor/deployer/deployer/recipe/deploy/prepare.php:15
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /var/www/symfony-project/vendor/deployer/deployer/src/Task/Task.php:82
 Deployer\Task\Task->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Console/TaskCommand.php:135
 Deployer\Console\TaskCommand->execute() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at /var/www/symfony-project/vendor/deployer/deployer/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Deployer.php:315
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

**Comment by antonmedv** [comment]
Try run this from terminal:
```
ssh -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=./dep_mux hostname
```

**Comment by secretwz** [comment]
This command connects me without problems to remote.

**Comment by antonmedv** [comment]
Okay, I'll create a script for testing ssh multiplexing connection

**Comment by antonmedv** [comment]
Please, run this script locally https://gist.github.com/antonmedv/53181dce02a876872e74cb56c9090c62
```
php check.php
```

**Comment by secretwz** [comment]
Output (i have add the port):

```
1:ssh -p 53546 -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_user@88.[...] user@88.[...] 'bash -s'
1:run 'pwd'
1:/home/user
1:command returned 0
2:ssh -O check -p 53546 -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_user@88.[...] user@88.[...] 2>&1
2:run ''
2:Master running (pid=1681)
2:command returned 0
```

**Comment by antonmedv** [comment]
Okay, let me try to change something in kernal.

**Comment by antonmedv** [comment]
Try this: add to host declaration:
```
host()
    ->sshOptions(['ControlPath', '/dev/shm/deployer'])
```

**Comment by antonmedv** [comment]
And also please check with master branch. Just added a fix: https://github.com/deployphp/deployer/pull/1268

**Comment by secretwz** [comment]
The sshOptions have no effect. If i update deployer to master, i get the following exception:

```
➤ Executing task deploy:prepare
[test] > echo $0
[test] < ssh multiplexing initialization
[test] < ssh: Could not resolve hostname test: Name or service not known
➤ Executing task deploy:failed
• done on [test]
✔ Ok [0ms]

                                                                   
  [Deployer\Exception\RuntimeException (-1)]                       
  The command "echo $0" failed.                                    
  Exit Code: -1 (Unknown error)                                    
  Host Name: test                                                  
  ================                                                 
  ssh: Could not resolve hostname test: Name or service not known  
                                                                   

Exception trace:
 () at /var/www/symfony-project/vendor/deployer/deployer/src/Ssh/Client.php:95
 Deployer\Ssh\Client->run() at /var/www/symfony-project/vendor/deployer/deployer/src/functions.php:297
 Deployer\run() at /var/www/symfony-projects/vendor/deployer/deployer/recipe/deploy/prepare.php:15
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /var/www/symfony-project/vendor/deployer/deployer/src/Task/Task.php:82
 Deployer\Task\Task->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Console/TaskCommand.php:135
 Deployer\Console\TaskCommand->execute() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at /var/www/symfony-project/vendor/deployer/deployer/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /var/www/symfony-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/symfony-project/vendor/deployer/deployer/src/Deployer.php:315
 Deployer\Deployer::run() at /var/www/symfony-project/vendor/deployer/deployer/bin/dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [--] [<stage>]

```

**Comment by antonmedv** [comment]
Please, test with master version more, should be fixed there.

**Comment by secretwz** [comment]
I found the problem:

if i define stage and port with object operator it runs fine. 

```
host('88.[...]')
    ->stage('test')
    ->user('user')
    ->port(53546)
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/test');
```

But if i add a second host (the same ip, but different stage and deploy-path), it throws the Exception "Hostname or stage `test` was not found.":

```
host('88.[...]')
    ->stage('prod')
    ->user('user')
    ->port(53546)
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/main');
```

Is there a way to define one host with different stages and different deploy_path on each stage?

**Comment by antonmedv** [comment]
Yes, use it: https://deployer.org/docs/hosts#host-aliases
Also soon will be fixes for better host management.

**Comment by antonmedv** [comment]
Does ssh multiplexing working now?

**Comment by secretwz** [comment]
Yes, ssh multiplexing working with new host-configuration, also with version 5.0.3. 

My final hosts:

```
host('88.[...]/test')
    ->stage('test')
    ->user('user')
    ->port(53546)
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/test');

host('88.[...]/prod')
    ->stage('prod')
    ->user('user')
    ->port(53546)
    ->forwardAgent()
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/html/main');
```

Thanks for your help and for the wonderful deployer tool :)
