### ISSUE TITLE
Only use two directories for releases

### ISSUE THREAD

**Issue by lbausch** [deployphp/deployer#1274]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | 5.0.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
As Rasmus Lerdorf pointed out in his talk about deploying PHP 7 it makes sense to only have two release directories: https://www.youtube.com/watch?v=MT4rRWKygq0&feature=youtu.be&t=54m24s

By only using two directories you may benefit more from caching.
The way Deployer works right now caching is more or less inefficient since a new release will be in a completely new directory and therefore will lead to 100% cache misses.

Is it possible to have Deployer use only two directories like "A" and "B"?

**Comment by matthew-muscat** [comment]
@lbausch - you could also possibly pre-warm / cache the release directory prior to deploy...

ie: https://github.com/jderusse/composer-warmup

**Some other concerns..**
- Using only A / B folders may cause some issues with rollback history, limiting rollbacks to the 1 single previous release.
- This assumes OP Cache setting has low TTL, or opcache flush is managed by the deployment system (if cache flush is required in deployments, then might as well handle cache warmup instead, as deployments is when we touch this)

**Comment by antonmedv** [comment]
@lbausch are you really suffer from lack of cache warmup? Because you can warmup cache as @matthew-muscat says. Even without of cache warmup it's pretty fast. 

I you really want to do this anyway, it's simple to implement yourself. Just override `deploy:release` and `deploy:symlink` to use only A and B dirs.

**Comment by lbausch** [comment]
@matthew-muscat thanks for pointing out the composer-warmup plugin. Will try this 👍 
@antonmedv Thanks for the explanation :)
