### ISSUE TITLE
Simplify upload method usage

### ISSUE THREAD

**Issue by fnagel** [deployphp/deployer#1277]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | most likely any
| Local Machine OS  | Linux
| Remote Machine OS | Linux

### Description 
Each `upload()` call needs me to enter my key passphrase as each call is actually an rsync call. Any idea how to improve this? Or is there no other way? Or am I doing something wrong?

Any feedback or hint is appreciated. 

Thanks a lot for this awesome piece of software and your hard work.

**Comment by johannesschobel** [comment]
Same here.. When i try to deploy it, i need to enter my password for every command (e.g., when creating the folders, i need to enter my password about 8 times).. Maybe i am doing something wrong?!

**Comment by antonmedv** [comment]
Use ssh agent. That's is what they designed to.

**Comment by fnagel** [comment]
> Use ssh agent.

🤦of course! Took 1min, works as expected. Thanks for pointing out the obvious...

@johannesschobel Close ticket? Or any more questions?

**Comment by johannesschobel** [comment]
@fnagel actually, i don't know how to do this. Maybe you can explain, how to set up ssh-agent and forwarding? That would be nice ;)

**Comment by fnagel** [comment]
Github has some pretty good tutorials on stuff like this: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by johannesschobel** [comment]
ok, so basically just create a SSH key? and add it to the GitHub account?

**Comment by fnagel** [comment]
No, this has nothing to do with GH, expect they have good tutorials.

In short: create a key, add it to your ssh agent, add the key to your servers `authorized_keys`, use it with deployer.

https://www.google.com/search?q=Public+Key+Auth

**Comment by johannesschobel** [comment]
hmmm.. i will try at the weekend.. can i contact you if i have any questions regarding this?

**Comment by johannesschobel** [comment]
hey @fnagel ,
i have created an SSH key (actually i already had one) and changed my `deploy.php` file to the following:

```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Configuration

set('ssh_type', 'native');
set('ssh_multiplexing', false);
set('repository', 'MY/PROJECT');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Hosts

host('api')
    ->hostname('HOSTNAME')
    ->stage('production')
    ->user('SSH-USERNAME')
    ->set('deploy_path', 'PAHT/TO/DEPLOYMENT')
    ->forwardAgent()
    ->identityFile('PATH/TO/SSH/.ssh/id_rsa');
```

But now it asks me several times for my password for the SSH key file (yes, i am pretty sure the password is correct!). Am i missing something?!

**Comment by antonmedv** [comment]
@johannesschobel run before deploy `ssh-add PATH/TO/SSH/.ssh/id_rsa`
