### ISSUE TITLE
default_stage does not support callable as all set() do

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#1278]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.3.0 / 5.x
| Local Machine OS  | Mac Sierra
| Remote Machine OS | Debian 8

### Description 
When I set default_stage as callable there is error because it does not expect callable.

```
set('default_stage', function () {
    return 'local';
});
```

### Steps to reproduce
1. Set:
```
set('default_stage', function () {
    return 'local';
});
```
2. Make
`dep deploy`

3. Output is:
`PHP Catchable fatal error:  Object of class Closure could not be converted to string in /Volumes/Data/www/workspace-typo3/projects/t3base8/vendor/deployer/deployer/src/Stage/StageStrategy.php on line 67
`
4. When you set:
`set('default_stage', 'local');`
then everything is working as expected.

**Comment by kszymukowicz** [comment]
@antonmedv 
If you accept its a bug I can prepare PR.

**Comment by antonmedv** [comment]
This is a tricky one. You can't run anything inside  this cb, because there is no context yet.
So this is doesn't correct:
```js
set('default_stage', function () {
    return run('echo local');
});
```

**Comment by kszymukowicz** [comment]
In my case I do not need context but only callable. 

Having callable allows me to not set the value at once when declared but later when used. This maybe has no difference when we assign simple string but when we assign value of function then this function must be called at once if not used as callable. With callable it can be called when used so function can be overwritten. This is the great power of having callable in set().

So to solve my case its enough to change:
File: src/Deployer.php
```
$this['stageStrategy'] = function ($c) {
            return new StageStrategy($c['servers'], $c['environments'], $c['config']['default_stage']);
        };
```
to
```
$this['stageStrategy'] = function ($c) {
           $default_stage = $c['config']['default_stage'];
           if(is_object($default_stage) && ($default_stage instanceof \Closure)) {
               $default_stage = call_user_func($default_stage);
           }
           return new StageStrategy($c['servers'], $c['environments'], $default_stage);
        };
```

I think it can not break anything and give more possibilities to have dynamic value of default_stage.

What do you think?
Can I prepare PR with this change ?

**Comment by antonmedv** [comment]
Yes, open PR, but please add tests and docs for this feature.

**Comment by kszymukowicz** [comment]
I added the docs in https://github.com/deployphp/docs/pull/94 but I need your help on writing test for this. Should I create separate test/recipe/DeployTest.php ?

**Comment by antonmedv** [comment]
I think no test for needed here
