### ISSUE TITLE
Don't download composer.phar for every release if it is globally available

### ISSUE THREAD

**Issue by Flyingmana** [deployphp/deployer#128]

**Comment by elfet** [comment]
Yes, it better to check it first.

**Comment by elfet** [comment]
But how to tets it?

**Comment by Flyingmana** [comment]
first solution which comes into my mind, test what the command ```composer.phar --version``` returns, maybe also allow to configure how the executable is named, and where it should be (I always install it as part of my environment directly after php gets installed)

**Comment by elfet** [comment]
Done.
