### ISSUE TITLE
Allow http_user to contain multiple values

### ISSUE THREAD

**Issue by KingCrunch** [deployphp/deployer#1280]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.0.3
| Local Machine OS  | Linux DELL-E5540-SEKR 4.11.6-3-ARCH \#1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux
| Remote Machine OS | Linux orocrmphptuv01 3.16.0-4-amd64 \#1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

### Description 

I have some cases, where multiple different users needs write access to the shared folders. Right now it is only possible to set a single username to `http_user`. 

```php
set('http_user', ["application_user", "web_user", "cron-user"]);
```

**Comment by antonmedv** [comment]
I think this isn't common case and i think this should not be in common recipe as it brings complicity. 

You can easily define your own task to fulfil your needs.

**Comment by KingCrunch** [comment]
Alright then. Tbh I don't know, how common, or uncommon this case is.

Now it would be nice to have an easy way to extend recipes :) Most of this recipe is already pretty nice.

Thank you for your comment.

**Comment by antonmedv** [comment]
Overriding is pretty  simple:
```js
task('deploy:writable', ...);
```
