### ISSUE TITLE
ssh_type=native throws Exception when using upload() if file name containing brackets

### ISSUE THREAD

**Issue by jzdunek** [deployphp/deployer#1281]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v4.3.0 (installed via composer)
| Local Machine OS  | MacOS 10.12.5
| Remote Machine OS | Ubuntu 14.04 LTS

### Description 
When using the upload() function with a file name that contains opening brackets '(', deployer stops with an error message regarding the bracket and throws an exception (see below).

When using ssh_type phpseclib (just commenting out the two `set` calls under Configuration) the upload works fine.

### Steps to reproduce
Run the script (you need a file named `yet(another)test.txt` in the same folder :wink:).

### Content of `deploy.php`
Minimal deploy.php to reproduce the bug.
```php
<?php
namespace Deployer;
require 'recipe/common.php';

// Configuration
set('ssh_type', 'native');
set('ssh_multiplexing', true);

// Servers
//server( -- redacted --);


// Tasks
desc('Upload some files');
task('deploy:upload', function () {
    upload('yet(another)test.txt', "/tmp/yet(another)test.txt");
});

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:upload',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
```
  [RuntimeException]
  sh: 1: Syntax error: "(" unexpected
  lost connection


Exception trace:
 () at /Users/test/deployer_test/vendor/deployer/deployer/src/Server/Remote/NativeSsh.php:185
 Deployer\Server\Remote\NativeSsh->scpCopy() at /Users/test/deployer_test/vendor/deployer/deployer/src/Server/Remote/NativeSsh.php:128
 Deployer\Server\Remote\NativeSsh->upload() at /Users/test/deployer_test/vendor/deployer/deployer/src/functions.php:418
 Deployer\upload() at /Users/test/deployer_test/deploy.php:19
 Deployer\{closure}() at n/a:n/a
 call_user_func() at /Users/test/deployer_test/vendor/deployer/deployer/src/Task/Task.php:85
 Deployer\Task\Task->run() at /Users/test/deployer_test/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at /Users/test/deployer_test/vendor/deployer/deployer/src/Console/TaskCommand.php:103
 Deployer\Console\TaskCommand->execute() at /Users/test/deployer_test/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /Users/test/deployer_test/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at /Users/test/deployer_test/vendor/deployer/deployer/src/Console/Application.php:123
 Deployer\Console\Application->doRunCommand() at /Users/test/deployer_test/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /Users/test/deployer_test/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /Users/test/deployer_test/vendor/deployer/deployer/src/Deployer.php:190
 Deployer\Deployer->run() at /Users/test/deployer_test/vendor/deployer/deployer/bin/dep:120

deploy [-p|--parallel] [--no-hooks]
```

**Comment by antonmedv** [comment]
Escape `( )`

**Comment by jzdunek** [comment]
Escaping within `deploy.php` works in the provided (artifical) example, but...
1. it makes the script depending on the chosen transfer lib, because when choosing phpseclib the target file name will be `yet\(another\)test.txt`.
2. the problem occurs even with files nested deep inside some folder structure when uploading the root folder. One might not be aware that the problem exists and one might not be able to influence file naming there (actually some symfony package creates this problem for me).

**Comment by jzdunek** [comment]
Regarding bullet point 2 from above:
`upload('folder_containing_file_with_brackets', "/tmp/folder_containing_file_with_brackets");` will break in the same way.

**Comment by jzdunek** [comment]
I dug a little deeper into the problem and found a *potential* solution: In function `NativeSsh:upload($local, $remote)` replacing the first line
- `$remote = str_replace(' ', '\ ', $remote);`
by this line
- `$remote = escapeshellcmd($remote);`

It worked with my little examples but I'm not sure about all the implication this change might have...

@antonmedv What do you think?

**Comment by antonmedv** [comment]
This is unnecessary as in Deployer 5 for upload func used rsync.

**Comment by jzdunek** [comment]
Fair point - will switch to Deployer 5.
