### ISSUE TITLE
changes to allow non-standard port for uploads and downloads seems to overwrite any custom rsync options

### ISSUE THREAD

**Issue by mtoothaker-links** [deployphp/deployer#1282]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.1+
| Local Machine OS  | Tested on Ubuntu and Mac
| Remote Machine OS | Linux

### Description 

As of 5.0.3(but I believe as early as 5.0.1) the code added to allow upload and download from non-standard port overwrites our custom options passed in. 

`if ($port !== 22) {
    $config['options'] = ["-e 'ssh -p $port'"];
}`

Unless I am missing something, the above code replaces any other options with only the option for non-standard port. It should instead add the non-standard port to any existing options already in config.

### Steps to reproduce
We have the following task:
`task('upload_code', function(){
    $ssh_port = get('ssh_port');
    if( empty($ssh_port) ){
        $ssh_port = '22';
    }
    $exclude = get('exclude_files');
    if(!empty($exclude))
        $exclude =  '--exclude="' . implode('" --exclude="', $exclude) . '"';
    upload( '{{repo_tree}}/', '{{release_path}}', array( 'options' => array($exclude, '-e "ssh -p ' . $ssh_port . '"', '--delete')));
});`

### Content of `deploy.php`
N/A

### Output log
We deploy to a remote server and any version higher than 5.0.0 doesn't exclude the files that we told it to, the only difference seems to be the above mentioned code in upload/download.

**Comment by antonmedv** [comment]
Fixed in 5.1: https://github.com/deployphp/deployer/blob/master/src/functions.php#L435

**Comment by mtoothaker-links** [comment]
Thanks. Sorry I missed that.
