### ISSUE TITLE
Add information about deploy

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1288]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5.x

### Description 
Now what you deploy you see this:
```
✔︎ Executing task deploy:prepare
✔︎ Executing task deploy:release
✔︎ Executing task deploy:update_code
✔︎ Executing task deploy:shared
✔︎ Executing task deploy:vendors
✔︎ Executing task deploy:migrate
✔︎ Executing task deploy:warmup
✔︎ Executing task deploy:symlink
✔︎ Executing task cleanup
Successfully deployed!
```
I want to add some info about deploy:

```
> Deploying master to production
✔︎ Executing task deploy:prepare
✔︎ Executing task deploy:release
...
```

**Comment by antonmedv** [comment]
But format need to be discuss

**Comment by staabm** [comment]
in case source control information is available it would also be cool to have something like `deploy master  ade4ac0 to production` or similar

**Comment by antonmedv** [comment]
Yes, format is discussable

Information we have on deploy:

* Deployer Version
* List of hosts
* Command name
* User name
* Stage (_optional_)
* Roles (_optional_)
* Git Branch (_optional_)
* Git Revision (_optional_)
* Git Tag (_optional_)
* Git Diff (_optional_) – list of changes since last release

**Comment by antonmedv** [comment]
Done in master. Will be in v6.

**Comment by alterphp** [comment]
Hi,

If I don't pass the revision option, can I see the revision that is being deployed ?

Regards,

**Comment by antonmedv** [comment]
@alterphp working on it in form of https://deployer.org/pro/continuous-integration
