### ISSUE TITLE
Set branch on host basis

### ISSUE THREAD

**Issue by martijn94** [deployphp/deployer#1292]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 5.3.1
| Local Machine OS  | Ubuntu Server 16.04
| Remote Machine OS | N/A

### Description 
I'm not sure if i'm missing something here but I would love to be able to set the git branch to use on host basis instead of project basis. This way we can have a staging and production server from a different branch. I saw some options for this in older versions I think but I was not able to find it for 5.x. Maybe this can be added or someone can point me in the right direction?

Thanks in advance!

**Comment by antonmedv** [comment]
https://deployer.org/docs/hosts#overriding-config-per-host

**Comment by martijn94** [comment]
Great work, thanks!
