### ISSUE TITLE
symfony/console version to high for Magento 2

### ISSUE THREAD

**Issue by TKlement** [deployphp/deployer#1293]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | ~5.1
| Local Machine OS  | Ubuntu
| Remote Machine OS | N/A

### Description 
We would like to use deployer for Magento 2.
Now the problem starts with installing deployer via composer.
It seems that deployer needs a minimum version for symfony/console that starts at ~2.7.
Even the latest RC 2.2 from Magento 2 requires
"symfony/console": "~2.3, !=2.7.0"
At the moment we are working with Magento 2.1.7 which requires
"symfony/console": "~2.3 <2.7"

Is there perhaps still a possibility to use deployer?

### Steps to reproduce
composer require deployer/deployer

### Content of `deploy.php`
```php
CONTENT
```

### Output log
Problem 1
    - Conclusion: don't install deployer/deployer v5.1.3
    - Conclusion: don't install deployer/deployer v5.1.2
    - Conclusion: don't install deployer/deployer v5.1.1
    - Conclusion: remove symfony/console v2.6.13
    - Installation request for deployer/deployer ^5.1 -> satisfiable by deployer/deployer[v5.1.0, v5.1.1, v5.1.2, v5.1.3].
    - Conclusion: don't install symfony/console v2.6.13
    - deployer/deployer v5.1.0 requires symfony/console ~2.7|~3.0 -> satisfiable by symfony/console[v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2, v3.3.3, v3.3.4].
    - Can only install one of: symfony/console[v2.7.0, v2.6.13].
    - Can only install one of: symfony/console[v2.7.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v2.7.0-BETA2, v2.6.13].
    - Can only install one of: symfony/console[v2.7.1, v2.6.13].
    - Can only install one of: symfony/console[v2.7.10, v2.6.13].
    - Can only install one of: symfony/console[v2.7.11, v2.6.13].
    - Can only install one of: symfony/console[v2.7.12, v2.6.13].
    - Can only install one of: symfony/console[v2.7.13, v2.6.13].
    - Can only install one of: symfony/console[v2.7.14, v2.6.13].
    - Can only install one of: symfony/console[v2.7.15, v2.6.13].
    - Can only install one of: symfony/console[v2.7.16, v2.6.13].
    - Can only install one of: symfony/console[v2.7.17, v2.6.13].
    - Can only install one of: symfony/console[v2.7.18, v2.6.13].
    - Can only install one of: symfony/console[v2.7.19, v2.6.13].
    - Can only install one of: symfony/console[v2.7.2, v2.6.13].
    - Can only install one of: symfony/console[v2.7.20, v2.6.13].
    - Can only install one of: symfony/console[v2.7.21, v2.6.13].
    - Can only install one of: symfony/console[v2.7.22, v2.6.13].
    - Can only install one of: symfony/console[v2.7.23, v2.6.13].
    - Can only install one of: symfony/console[v2.7.24, v2.6.13].
    - Can only install one of: symfony/console[v2.7.25, v2.6.13].
    - Can only install one of: symfony/console[v2.7.26, v2.6.13].
    - Can only install one of: symfony/console[v2.7.27, v2.6.13].
    - Can only install one of: symfony/console[v2.7.28, v2.6.13].
    - Can only install one of: symfony/console[v2.7.29, v2.6.13].
    - Can only install one of: symfony/console[v2.7.3, v2.6.13].
    - Can only install one of: symfony/console[v2.7.30, v2.6.13].
    - Can only install one of: symfony/console[v2.7.31, v2.6.13].
    - Can only install one of: symfony/console[v2.7.4, v2.6.13].
    - Can only install one of: symfony/console[v2.7.5, v2.6.13].
    - Can only install one of: symfony/console[v2.7.6, v2.6.13].
    - Can only install one of: symfony/console[v2.7.7, v2.6.13].
    - Can only install one of: symfony/console[v2.7.8, v2.6.13].
    - Can only install one of: symfony/console[v2.7.9, v2.6.13].
    - Can only install one of: symfony/console[v2.8.0, v2.6.13].
    - Can only install one of: symfony/console[v2.8.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v2.8.1, v2.6.13].
    - Can only install one of: symfony/console[v2.8.10, v2.6.13].
    - Can only install one of: symfony/console[v2.8.11, v2.6.13].
    - Can only install one of: symfony/console[v2.8.12, v2.6.13].
    - Can only install one of: symfony/console[v2.8.13, v2.6.13].
    - Can only install one of: symfony/console[v2.8.14, v2.6.13].
    - Can only install one of: symfony/console[v2.8.15, v2.6.13].
    - Can only install one of: symfony/console[v2.8.16, v2.6.13].
    - Can only install one of: symfony/console[v2.8.17, v2.6.13].
    - Can only install one of: symfony/console[v2.8.18, v2.6.13].
    - Can only install one of: symfony/console[v2.8.19, v2.6.13].
    - Can only install one of: symfony/console[v2.8.2, v2.6.13].
    - Can only install one of: symfony/console[v2.8.20, v2.6.13].
    - Can only install one of: symfony/console[v2.8.21, v2.6.13].
    - Can only install one of: symfony/console[v2.8.22, v2.6.13].
    - Can only install one of: symfony/console[v2.8.23, v2.6.13].
    - Can only install one of: symfony/console[v2.8.24, v2.6.13].
    - Can only install one of: symfony/console[v2.8.3, v2.6.13].
    - Can only install one of: symfony/console[v2.8.4, v2.6.13].
    - Can only install one of: symfony/console[v2.8.5, v2.6.13].
    - Can only install one of: symfony/console[v2.8.6, v2.6.13].
    - Can only install one of: symfony/console[v2.8.7, v2.6.13].
    - Can only install one of: symfony/console[v2.8.8, v2.6.13].
    - Can only install one of: symfony/console[v2.8.9, v2.6.13].
    - Can only install one of: symfony/console[v3.0.0, v2.6.13].
    - Can only install one of: symfony/console[v3.0.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v3.0.1, v2.6.13].
    - Can only install one of: symfony/console[v3.0.2, v2.6.13].
    - Can only install one of: symfony/console[v3.0.3, v2.6.13].
    - Can only install one of: symfony/console[v3.0.4, v2.6.13].
    - Can only install one of: symfony/console[v3.0.5, v2.6.13].
    - Can only install one of: symfony/console[v3.0.6, v2.6.13].
    - Can only install one of: symfony/console[v3.0.7, v2.6.13].
    - Can only install one of: symfony/console[v3.0.8, v2.6.13].
    - Can only install one of: symfony/console[v3.0.9, v2.6.13].
    - Can only install one of: symfony/console[v3.1.0, v2.6.13].
    - Can only install one of: symfony/console[v3.1.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v3.1.0-RC1, v2.6.13].
    - Can only install one of: symfony/console[v3.1.1, v2.6.13].
    - Can only install one of: symfony/console[v3.1.10, v2.6.13].
    - Can only install one of: symfony/console[v3.1.2, v2.6.13].
    - Can only install one of: symfony/console[v3.1.3, v2.6.13].
    - Can only install one of: symfony/console[v3.1.4, v2.6.13].
    - Can only install one of: symfony/console[v3.1.5, v2.6.13].
    - Can only install one of: symfony/console[v3.1.6, v2.6.13].
    - Can only install one of: symfony/console[v3.1.7, v2.6.13].
    - Can only install one of: symfony/console[v3.1.8, v2.6.13].
    - Can only install one of: symfony/console[v3.1.9, v2.6.13].
    - Can only install one of: symfony/console[v3.2.0, v2.6.13].
    - Can only install one of: symfony/console[v3.2.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v3.2.0-RC1, v2.6.13].
    - Can only install one of: symfony/console[v3.2.0-RC2, v2.6.13].
    - Can only install one of: symfony/console[v3.2.1, v2.6.13].
    - Can only install one of: symfony/console[v3.2.10, v2.6.13].
    - Can only install one of: symfony/console[v3.2.11, v2.6.13].
    - Can only install one of: symfony/console[v3.2.2, v2.6.13].
    - Can only install one of: symfony/console[v3.2.3, v2.6.13].
    - Can only install one of: symfony/console[v3.2.4, v2.6.13].
    - Can only install one of: symfony/console[v3.2.5, v2.6.13].
    - Can only install one of: symfony/console[v3.2.6, v2.6.13].
    - Can only install one of: symfony/console[v3.2.7, v2.6.13].
    - Can only install one of: symfony/console[v3.2.8, v2.6.13].
    - Can only install one of: symfony/console[v3.2.9, v2.6.13].
    - Can only install one of: symfony/console[v3.3.0, v2.6.13].
    - Can only install one of: symfony/console[v3.3.0-BETA1, v2.6.13].
    - Can only install one of: symfony/console[v3.3.0-RC1, v2.6.13].
    - Can only install one of: symfony/console[v3.3.1, v2.6.13].
    - Can only install one of: symfony/console[v3.3.2, v2.6.13].
    - Can only install one of: symfony/console[v3.3.3, v2.6.13].
    - Can only install one of: symfony/console[v3.3.4, v2.6.13].
    - Installation request for symfony/console (locked at v2.6.13) -> satisfiable by symfony/console[v2.6.13].

**Comment by martijn94** [comment]
Don't know about the dependencies but I have been deploying Magento 2 with deployer just fine yesterday. The big difference is however is that I installed the PHAR system wide instead of via composer in the project.

Maybe this can be a workaround for you as well?

**Comment by TKlement** [comment]
@martijn94 
Thanks for the tipp. I will give it a try.
Now that the newest version won't work with composer I also tried to install 4.3.
But again ... now there is a problem with monolog/monolog.
Magento needs 1.16.0 and deployer 1.21.0.
Great!

The problem with the phar file is, that we have some more developers working and deploying that project. And the best way is to include deployer with composer so that everyone has the same version.
With that phar file I have to tell everyone to install it. :-(
But anyway ... if there is no other way I will try it.

**Comment by antonmedv** [comment]
@TKlement it's common problem with composer :( I'm trying to use as little as possible dependencies for deployer. For your case only possible solution is to use phar version right now.

Maybe in future, I'll try to move away from any deps at all, but it's not easy.

**Comment by kszymukowicz** [comment]
@martijn94 
My solution for magento2 and deployer 4.3.0 is:

`"monolog/monolog": "1.16.0 as 1.21.0",`

**Comment by kszymukowicz** [comment]
FYI: having https://github.com/deployphp/deployer/issues/1308 could solve all problems in this issue :)

**Comment by antonmedv** [comment]
Fixed in #1308
