### ISSUE TITLE
Unable to deploy with composer with dev-master

### ISSUE THREAD

**Issue by TKlement** [deployphp/deployer#1298]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 5.1.3
| Local Machine OS  | Ubuntu
| Remote Machine OS | N/A

### Description 
I want to deploy magento 2 to our staging server. So I don't need stable modules.
Some of the magento 2 modules have the flag "dev-master".
All of these modules are ignored by composer.
The minimum stability in magento 2 main composer file is alpha. And that is as far as I know correct.
Is there a possibility with deployer also to deploy modules with dev-master stability?
How can I test my modules that haven't reached a stable status?

### Steps to reproduce
deployer deploy staging

### Content of `deploy.php`
require 'recipe/magento2.php'

### Output log
Deployer ignore every module that isn't tagged as stable.

**Comment by antonmedv** [comment]
Run `dep deploy -vvv` 
Check called composer command

**Comment by TKlement** [comment]
The command is the default:
`/usr/bin/php /usr/local/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader`
There is no hint or error.
I guess the problem is that every module that is listed there has a version like:
```
magento/magento-composer-installer:0.1.12
composer/semver:1.4.2
```
But my modules in the main composer.json are listed like that:
```
"require": {
        "magento/product-community-edition": "2.1.7",
        "composer/composer": "@alpha",
        "company/magento2-mymodule-name": "dev-master",
        "company/magento2-mytheme-name": "dev-master",
...
```
But I don't want to tag my modules until I know they are tested on the staging system.
Therefor must be a way to get those modules on a staging system.

**Comment by antonmedv** [comment]
`--no-dev` - remove this

**Comment by TKlement** [comment]
Ok, tried. But as expected now the list for installed modules now contains also the require-dev modules but without my modules.

**Comment by antonmedv** [comment]
Hmm, can't tell what is wrong then. Try to run it (composer) command manually on server. Maybe it's but in composer.
