### ISSUE TITLE
is there a migration documentation from v4 to v5?

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#1304]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4,5
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
is there a migration documentation from v4 to v5? can't find any

**Comment by antonmedv** [comment]
Yes: https://github.com/deployphp/deployer/blob/master/UPGRADE.md
