### ISSUE TITLE
Autocomplete install does not work in zsh

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#1305]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.1.3
| Local Machine OS  | Ubuntu 14.04.5 LTS
| Remote Machine OS | N/A

### Description 
autocomplete install does not work. I guess I am missing some package, but maybe script should give me some clue what I am missing?

### Steps to reproduce
$ dep autocomplete --install > ~/.deployer_completion && echo "source ~/.deployer_completion" >> ~/.zshrc
$ source ~/.zshrc

### Output log
/home/vytautas/.deployer_completion:47: command not found: complete

**Comment by antonmedv** [comment]
```
autoload bashcompinit
bashcompinit
```

**Comment by svycka** [comment]
> autoload bashcompinit
> bashcompinit
> source ~/.zshrc

after:
```
_deployer:4: command not found: _get_comp_words_by_ref
_deployer:7: bad option: -t
_deployer:38: command not found: __ltrim_colon_completions
```

**Comment by antonmedv** [comment]
I think it's a bug then. Please check this project to https://github.com/bamarni/symfony-console-autocomplete
Deployer's autocomplete based on it.

**Comment by svycka** [comment]
looks like its working just had to add to .zshrc
```
eval "$(/home/vytautas/.composer/vendor/bin/symfony-autocomplete)"
```
instead of
```
eval "$(symfony-autocomplete)"

but not sure this is related

**Comment by svycka** [comment]
okay added  composer bin path to $PATH and now works eval "$(symfony-autocomplete)" but deployer still does not

**Comment by svycka** [comment]
also symfony-autocomplete works without
```
autoload bashcompinit
bashcompinit
```

**Comment by antonmedv** [comment]
Really strange, because they are really same. Try this:
```
eval "$(cat  ~/.deployer_completion)"
```

**Comment by svycka** [comment]
no, does not help same output

**Comment by antonmedv** [comment]
Can't tell what's wrong then)

**Comment by svycka** [comment]
by quick look at bash scripts they are different maybe they updated something? also symfony-autocomplete has different templates for bash and zsh but deployer has just one template? no?

**Comment by svycka** [comment]
okay now I see deployer uses bash template from that project even I am using zsh I guess that's the problem

**Comment by antonmedv** [comment]
>  also symfony-autocomplete has different templates for bash and zsh
No, only bash impl

**Comment by svycka** [comment]
@antonmedv when Iinstalled symfony-autocomplete it created with this https://github.com/bamarni/symfony-console-autocomplete/blob/master/resources/zsh/default.php
and when I installed deployer it used this:
https://github.com/bamarni/symfony-console-autocomplete/blob/master/resources/bash/default.php

from my error you can see deployer version tries to use `_get_comp_words_by_ref` this only exists in bash template
_deployer:4: command not found: _get_comp_words_by_ref

also I don't need 
```
autoload bashcompinit
bashcompinit
```
because https://github.com/bamarni/symfony-console-autocomplete/blob/master/resources/zsh/default.php does not have this line https://github.com/bamarni/symfony-console-autocomplete/blob/master/resources/bash/default.php#L46

**Comment by antonmedv** [comment]
Ok, thanks. I see. Well) I think it's a time for PR? Maybe optional param to install? `--install zsh`

**Comment by skarnl** [comment]
What's the outcome of this issue? It's still open, but the problem still exists.

**Comment by antonmedv** [comment]
Yes, this issue still present. Can you make PR to fix it?

**Comment by igloocube** [comment]
Is there any known workaround for this? I've tried things mentioned here and nothing actually fixes it. Also tried upgrading bash to v4 (MacOS) and no luck. Ref: https://github.com/dsifford/yarn-completion/issues/4

Thanks

**Comment by njpanderson** [comment]
Hey all — still getting this issue today. Clean install of deployer with recent zsh:

Used this to install: 

```
dep autocomplete --install > ~/.deployer_completion && echo "source ~/.deployer_completion" >> ~/.zshrc
```

Completely closed CLI session then tried `dep <tab>`:

```
» dep …_deployer:4: command not found: _get_comp_words_by_ref "source ~/.deployer_completion"_deployer:type:7: bad option: -t
_deployer:38: command not found: __ltrim_colon_completions
```

**Comment by svycka** [comment]
I guess this was not fixed I forgot to create PR at the time. And I guess no one fixed this if it does not work. Not sure why @antonmedv closed if it's not fixed or maybe you just ran into a different issue.

**Comment by antonmedv** [comment]
It was completely redesigned in v7. Please, take a look there.

**Comment by svycka** [comment]
@njpanderson what version you use? I see docs changed since then https://github.com/deployphp/deployer/blob/57dea072e68979d79e43351a0a39931333e7fff2/docs/installation.md#autocomplete

**Comment by njpanderson** [comment]
Interesting. I'm just getting 6 from the phar, which seems to be the first method of installation as per the docs?

@svycka:

```
--- ~ » dep --version
Deployer 6.8.0
```

I see v7 is still in beta, any plans to release it this coming year?

**Comment by svycka** [comment]
@njpanderson I hope so because stable release didn't have any releases for almost  about one year I guess you can use v7 but maybe @antonmedv can say more about his plans

**Comment by antonmedv** [comment]
I have plans to release v7 as soon as I find some time)

**Comment by campaignupgrade** [comment]
MacOS 11.6
`eval "$(dep autocomplete --shell bash)` fails in .bashrc
`dep autocomplete --shell bash` fail on command line

Same error 
```
The "--shell" option does not exist.

autocomplete [--install]
```

**Comment by campaignupgrade** [comment]
Ah I see. The docs are wrong at https://deployer.org/docs/7.x/installation 

`dep autocomplete --install | sudo tee /etc/bash_completion.d/deployer` works as expected.

**Comment by campaignupgrade** [comment]
If I run `dep autocomplete` I get the following output:
```
dep autocomplete
To install Deployer autocomplete run one of the following commands:

# Bash (Ubuntu/Debian)

  dep autocomplete --install | sudo tee /etc/bash_completion.d/deployer

# Bash (Mac OSX with Homebrew "bash-completion")

  dep autocomplete --install > $(brew --prefix)/etc/bash_completion.d/deployer

# Zsh

  dep autocomplete --install > ~/.deployer_completion && echo "source ~/.deployer_completion" >> ~/.zshrc

# Fish

  dep autocomplete --install > ~/.config/fish/completions/deployer.fish
  ```
  
  This is where I found the working command to add to bash.

**Comment by antonmedv** [comment]
I think this should be deleted and replaced as it is not really accurate and prevents the newer version from automatically poping in.
