### ISSUE TITLE
Download phar based deployer into vendor/bin/dep

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#1308]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | All
| Local Machine OS  | All
| Remote Machine OS | All

### Description 
I am not sure if something like that is already possible but IMO it would be good to have ability to require as composer package a phar based version of deployer which would be downloaded into ./vendor/bin. 

I know I can do "composer require deployer/deployer" and it will do symlink to ./vendor/bin/dep but "deployer/deployer" depends on lot of packages and I do not want to include them in main project.

So having smth like "composer require deployer/deployer-bin" which will not depend on anything and make ./vendor/bin/dep would be the best option.

This solves at least few problems people face today:

1) If the deployer is installed globally then if I use deployer in versions 3,4,5 then I need to create 3 different symlinks and use it like for example "dep4 deploy live" on one project and  "dep3 deploy live" on second. Additionally I need to remember which deployer version is used in project I work in.  

2) If I want to use "deployer/deployer" as composer package then it loads lot of dependencies into project which can bring conflicts.

What do you think ?

I know I can make myself smth like below in my composer.json:
```
"scripts": {
    "post-autoload-dump": [
       "curl -LO https://deployer.org/releases/v5.1.3/deployer.phar && mv deployer.phar ./vendor/bin/dep && chmod +x ./vendor/bin/dep"
    ]
}
```
but this will not update on "composer update" and other packages can not set dependency on strict version of deployer also.

**Comment by antonmedv** [comment]
I like your idea, really cool. I tried t configure composer to download phar but unsuccesful.
What about having something like `deployer/deployer-phar` or `deployer/dist`

> If the deployer is installed globally then if I use deployer in versions 3,4,5 then I need to create 3 different symlinks and use it like for example "dep4 deploy live" on one project and "dep3 deploy live" on second. Additionally I need to remember which deployer version is used in project I work in.

If you have installed deployer globally and locally with composer, `dep` command will run locally installed version.

**Comment by antonmedv** [comment]
Created https://github.com/deployphp/distribution

**Comment by antonmedv** [comment]
Only auto update system left.

**Comment by kszymukowicz** [comment]
Great!!! 
Installed / tested / works perfectly !!! 

:smile: :smile:

I can take care of docs. Give me a notice if I should so we do not double the work.

**Comment by antonmedv** [comment]
@kszymukowicz ok, take care of docs (add section into installation.md) also if you can think about autoupdate system will be cool.

**Comment by kszymukowicz** [comment]
What do you mean exactly by autoupdate ?

**Comment by antonmedv** [comment]
After release of deployer. To don't run manually `php update`.

**Comment by antonmedv** [comment]
Auto update will implement myself.
