### ISSUE TITLE
Where can I find recipe/laravel.php to edit?

### ISSUE THREAD

**Issue by arnasfomenko** [deployphp/deployer#1310]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | Newest
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

### Description 

I'd like to know where can I find recipe/laravel.php file to edit, because everytime I begin the deployment deployer automatically does config:cache, which is really bad for me and makes some issues.

**Comment by dimkasta** [comment]
It's inside the recipe folder.

https://github.com/deployphp/deployer/blob/master/recipe/laravel.php

I 'd leave this alone and just bypass the action that causes the problem in deploy.php
