### ISSUE TITLE
Execute a task only on first node from a pull

### ISSUE THREAD

**Issue by alinalexandru** [deployphp/deployer#1311]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
For example you have to execute a command only once. I don't like a idea of hardcode o server name when defining a task.

Instead of doing 
```php
task('only:once', function (){
....
})->onHosts('frist.node')
```

I propose to have a method *onFirstHost* for example, that will limit the task execution to the first node from available.
```php
task('only:once', function (){
....
})->onFirstHost()
```

If you consider that is an good idea, I can propose a PR with the implementation.

**Comment by richsage** [comment]
+1, I've used some variation of this before:

```
task('only:once', function () {
    static $runOnce = false;
    if ($runOnce) {
        return;
    }

    $runOnce = true;
    // ...
});
```

but would be good to make this a bit cleaner.

**Comment by antonmedv** [comment]
But I think good naming required here. Maybe `once`?
```php
task('only:once', function () {
....
})->once()
```

**Comment by alinalexandru** [comment]
@antonmedv what do you think about this PR.
I am open to any feedback

**Comment by antonmedv** [comment]
Merged!
