### ISSUE TITLE
How to insert password for host?

### ISSUE THREAD

**Issue by pulselife** [deployphp/deployer#1312]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by antonmedv** [comment]
Deployer asks about password on deploy.
