### ISSUE TITLE
add option to copy shared_files instead of creating symlink

### ISSUE THREAD

**Issue by insekticid** [deployphp/deployer#1317]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
e.g. define shared_files: app/config/parameters.yml and setup basic config. 
In Symfony setup will composer run post-install command: Incenteev\\ParameterHandler\\ScriptHandler::buildParameters and it will add other non defined variables from parameters.yml.dist to parameters.yml.

It is good habbit, to define only non changing variables in parameters.yml.

It is impossible now, because you are creating symlink to this file. Add option to simply copy files instead of symlinking.

This behaviour is used in capistrano deploy tool. I am switching from this tool

**Comment by antonmedv** [comment]
We have task called copy_dirs https://github.com/deployphp/deployer/blob/7dea6107c3958e2b84b4263173cd157856c9f9c7/recipe/deploy/copy_dirs.php#L11

Maybe it's time for copy_files option.

**Comment by antonmedv** [comment]
Or simple create task for it:
```php
task('deploy:copy_parameters', 'cp shared/... {{release_path}}/...');
```

**Comment by gpietoso** [comment]
@antonmedv Would Would like to implement the copy_files option. Would it be useful?

**Comment by antonmedv** [comment]
Yes, you can create PR for it.
