### ISSUE TITLE
Task run commands asynchronously

### ISSUE THREAD

**Issue by ouhman** [deployphp/deployer#1321]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | v5.1.3
| Local Machine OS | Ubuntu 16.04

I currently have a task which publishes assets to multiple CDNs. In order to speed up the process it would be great to be able to trigger these commands within a task in parallel.

**Comment by antonmedv** [comment]
Show example php code.

**Comment by ouhman** [comment]
The task is pretty straight forward. It runs some PHP scripts to upload new assets.
It would be great to have an option on a task to allow these commands to be run asynchronously.

```
$options = [
    'tty' => true,
    'timeout' => 1200
];
$commands = [
    'asset:publish-site1' => '{{bin/php}} {{release_path}}publish-assets/site1 --interactive=0',
    'asset:publish-site2' => '{{bin/php}} {{release_path}}publish-assets/site2 --interactive=0',
    'asset:publish-site3' => '{{bin/php}} {{release_path}}publish-assets/site3 --interactive=0',
    'asset:publish-site4' => '{{bin/php}} {{release_path}}publish-assets/site4 --interactive=0',
];
foreach ($commands as $type => $command) {
    \Deployer\task($type, function() use ($command, $options) {
        \Deployer\run($command, $options);
    })->onRoles('migration');
}
```

**Comment by antonmedv** [comment]
What about using this:
```php
runLocally('dep async_task &');
```
