### ISSUE TITLE
Load/source .env

### ISSUE THREAD

**Issue by jverdeyen** [deployphp/deployer#1322]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
What is the best practice to load a .env file with environment variables to use during a deploy.
Which can be use by by composer install (for example).

Defining them as `set('env_vars',  ...` doesn't make it portable for the application.

Thanks!

**Comment by antonmedv** [comment]
Please, explain what are you trying to do? Some example?

**Comment by jverdeyen** [comment]
When deploying a Symfony application and all the env vars are defined in a .env file.
This .env file should always be the endpoint to load environment vars from.

But when deploying I need to load this .env vars into the current deploy shell.

**Comment by antonmedv** [comment]
Local .env file, or remote (shared)?

**Comment by jverdeyen** [comment]
A shared .env on the target server itself.

**Comment by antonmedv** [comment]
Maybe a task with reading it will be ok.

**Comment by jverdeyen** [comment]
I've already created an extra task to preload the env vars.

```
task('deploy:env',  function() {
   run('env $(cat {{ release_path }}/app/config/.env | xargs)') ;
   run('export') ;
});
```

The export is showing the correct output. But the vendors install task doesn't seem to have these exports anymore.

**Comment by antonmedv** [comment]
Try setting `set` _env_vars_ option.

**Comment by jverdeyen** [comment]
Is it possible to set the env_vars from a remote executed command?

**Comment by antonmedv** [comment]
`set('env_vars', '...');`

**Comment by antonmedv** [comment]
Done! Now you can do this stuff:

```php
set('env', [
    'FOO' => 'bar',
]);

add('env', [
    'BAZ' => 'some value',
]);

host(...)->set('env', [...]);

run('...', ['env' => [
    'SOME' => 'value',
]]);
```
