### ISSUE TITLE
Hardcoded password is ignored and the command asks for password again

### ISSUE THREAD

**Issue by acelaya** [deployphp/deployer#1324]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.3.1
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description 
It seems the server password is being ignored. When `dep` is run, it asks for server password even if it was provided in the `deploy.php` file

### Steps to reproduce
Define one server with hardcoded password like this

```php
server('web-server', '1.2.3.4')
    ->user('my-user')
    ->password('my-password')
    ->stage('production');
```

Then run `vendor/bin/dep deploy production` and it will ask you for the password as if you passed null.

I'm not sure if it affects the execution, but I use native SSH

```php
set('ssh_type', 'native');
set('ssh_multiplexing', true);
```

**Comment by antonmedv** [comment]
Password doesn't work with native ssh type (will ask anyway)

**Comment by staabm** [comment]
So whats the use case of the password function/method then?

**Comment by antonmedv** [comment]
For example with phpseclib.
