### ISSUE TITLE
ⅆⅇ𝕡│Name of get/set: config/parameters/options/variable

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1325]
Now terminology for this in Deployer a little bit confusing. I'm talking about these:
```php
set('name', 'value');
get('name');
```

All this stuff together called configuration: https://deployer.org/docs/configuration
But how to call individual elements?

**Comment by kszymukowicz** [comment]
I can see you already use "configuration parameter" and "variable" for that.
IMO "configuration parameter" is quite ok.

But I can imagine yet "configuration item".

**Comment by antonmedv** [comment]
_configuration parameter_ is ok, but tooo long. Maybe vars?

**Comment by kszymukowicz** [comment]
Could be also :)

**Comment by antonmedv** [comment]
Or params.

**Comment by antonmedv** [comment]
Parameters

**Comment by staabm** [comment]
setting

**Comment by antonmedv** [comment]
Okay, params is ok)
