### ISSUE TITLE
 [Error] Call to undefined function Deployer\server()

### ISSUE THREAD

**Issue by badalsurana** [deployphp/deployer#1337]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.1.3
| Local Machine OS  | MacOs Sierra
| Remote Machine OS | N/A

### Description 
After installing deployer i am getting this error.

### Steps to reproduce
Just install Deployer 5.1.3 and run `dep -V`

### Output log
*With enabled option for verbose output `-vvv`.*
#0 /Users/badalsurana/.composer/vendor/deployer/deployer/src/Deployer.php(314): require()                              
 #1 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #2 /Users/badalsurana/.composer/vendor/deployer/deployer/src/Deployer.php(315): call_user_func(Object(Closure))        
 #3 /Users/badalsurana/.composer/vendor/deployer/deployer/bin/dep(120): Deployer\Deployer::run('master',                
 '/Users/badalsur...')                                                                                                  
 #4 {main}

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/blob/master/UPGRADE.md#upgrade-from-4x-to-5x
