### ISSUE TITLE
How to get config variable from query database

### ISSUE THREAD

**Issue by muswanto** [deployphp/deployer#1338]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | Latest
| Local Machine OS  | Linux Ubuntu 16.04
| Remote Machine OS | Docker Container

Hello bro.. I just want to ask here. How can i set configuration variable such as host IP, url git repo, username & password, etc from database. I want to store everything in database.
Example : 
`set('repository', <value from database>);`

Thank very much to help me.. ;)

**Comment by antonmedv** [comment]
Yes. Use php for it)
```
set('repository', getValue());
```

**Comment by muswanto** [comment]
@antonmedv Do you have an example to achive that? Thank you
Where to create db connection? in deployer.php?

**Comment by antonmedv** [comment]
It's depends on what you need.

**Comment by muswanto** [comment]
@antonmedv I need to get repository url from database

**Comment by antonmedv** [comment]
You can do it, it's just PHP – do what ever you want to. That's a point!

**Comment by jverdeyen** [comment]
@muswanto 

```
task('deploy:fetchrepo', function() {
   set('repository', function() {
       return 'github.com';
   });
   run('echo {{ repository }}');
});
```

The `set` function accepts any kind of callable.
Instead of returning `github.com`, you can connect to a db and retrieve the repo from a query result.
