### ISSUE TITLE
SSH Agent Forwarding Feature

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#134]
Now PHP's ext ssh2 does not support ssh agent forwarding. And i'm thinking it will be good to implement it in pure PHP inside Deployer.

![a3d175c2172bf9469483602e552e0a11 media 600x424](https://cloud.githubusercontent.com/assets/141232/5721404/645023fa-9b42-11e4-90f9-2a198e5cfd3f.png)

Is there anyone willing to take for implementation of?

**Comment by tomzx** [comment]
Reference: phpseclib/phpseclib#592

**Comment by elfet** [comment]
Done in #175
