### ISSUE TITLE
Allow extending init templates

### ISSUE THREAD

**Issue by jedateach** [deployphp/deployer#1340]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request

### Description 

I deploy multiple websites using the same host and website framework.

I want to be able to do the least amount of work possible when setting up a new website.
It would be useful if I could write my own init template so that I can just fill out the specific details for a recipe that is specific to my environment.

`composer require myvendor/my-deployer-template`

e.g.  `dep init --template=MyTemplate`

**Comment by jedateach** [comment]
Has making this project use more of an extensible architecture been considered?

**Comment by antonmedv** [comment]
I think this is cool feature to have. Will be cool to create some API/Interface for extending init system. 
For example i think it should allow for arbitrary questions.

**Comment by jedateach** [comment]
Yes, if you could have deployer ask for required details on init - that would be very useful.

**Comment by kl3sk** [comment]
Any way to add custom template ?

**Comment by antonmedv** [comment]
Possible to do via extending deployer class.
