### ISSUE TITLE
Access hostname during local task

### ISSUE THREAD

**Issue by jedateach** [deployphp/deployer#1342]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5
| Local Machine OS  | osx
| Remote Machine OS | linux

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce

I would like to do the following

### Content of `deploy.php`
```php
desc('Perform a deploy locally for upload to server.');
task('localbuild', function () {
	set('deploy_path', '~/.mydeploys/{{hostname}}');
       // ...
})->local();
```
However, 'hostname' is set to 'localhost'

**Comment by antonmedv** [comment]
This is correct behavior. You mark task as `->local();`.

**Comment by jedateach** [comment]
@antonmedv - yes I understand, but say you want to reference the hostname that you are going to release your local deploy to? See my example.

**Comment by antonmedv** [comment]
What output should be here?

```php
host('prod_a');
host('prod_b');

task('localbuild', function () {
	writeln('~/.mydeploys/{{hostname}}');
})->local();
```

prod_a or prod_b?

**Comment by jedateach** [comment]
Thats a good point.
Is there a way to set a global variable from another task that isn't local?

**Comment by antonmedv** [comment]
You can use env for it: 
```php
set('branch', function () {
    return getenv('BRANCH');
});
task('localbuild', function () {
	writeln(getenv('BRANCH'));
})->local();
```

```
BRANCH=feature-branch dep deploy
```
