### ISSUE TITLE
RunLocally has a operand issue for env

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#1345]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.0
| Local Machine OS  | Mac
| Remote Machine OS | Ubuntu16

### Description 
A merge in runLocally function is perhaps wrong written?

### Steps to reproduce
1. Create a task with a runLocally command.
2. Call for the task.

### Content of `deploy.php`
```php
task('example', function() {
    runLocally("echo \$PWD");
});
```

### Output log
[Error] Unsupported operand types

and what causes this is src/functions.php row 311:
```
    $env = get('env', []) + ($options['env'] ?? []);
```
You can't assign arrays with + in PHP. Or what is intended in this row?

**Comment by antonmedv** [comment]
What's your 'env' variable is?

**Comment by ekandreas** [comment]
`set('env', '/usr/bin/env');`

**Comment by antonmedv** [comment]
This is incorrect. See https://deployer.org/docs/configuration#env
It must be an array:
```php
set('env', [
    'VARIABLE' => 'value',
]);
```
Also you CAN merge arrays in php with `+` – http://php.net/manual/en/language.operators.array.php

Maybe warning will be good here.

**Comment by ekandreas** [comment]
Ok, then I have some old v3 settings left in my deploy.php.
I will start using arrays instead.
And great the the operand + is ok to use to merge arrays in PHP.

**Comment by antonmedv** [comment]
Take a look at migration guide: https://github.com/deployphp/deployer/blob/master/UPGRADE.md

**Comment by abiodunjames** [comment]
@antonmedv  Is it fine if I send in a PR for this ?

**Comment by antonmedv** [comment]
@abiodunjames what kind of PR? :)

**Comment by abiodunjames** [comment]
Warn users that `env ` must be an array and then default to empty array

**Comment by antonmedv** [comment]
Actually now it's not possible to do. I'm going to add API in v7 for it:
```php
set('env', [])
    ->validate(function ($value) {});
```
