### ISSUE TITLE
Git branch override issue.

### ISSUE THREAD

**Issue by Streid** [deployphp/deployer#1347]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.0

### Description 
Hi! I can't override the git branch specified in inventory('servers.yml') via CLI.
Command:
`php deployer.phar deploy streid --branch=test -vv`
Result:
`[streid] > /usr/bin/git clone -b master --recursive -q --reference /home/streid/deployer/code/releases/2 --dissociate git@bitbucket.org:example.git  /home/streid/deployer/code/releases/3 2>&1`

In previous versions it worked =\

**Comment by antonmedv** [comment]
Yes, it is BC in v6. New priority of branch. If you set branch to host directly, Deployer treats this as mandatory. Read more about upgrading from v5 here – [UPGRADE.md](https://github.com/deployphp/deployer/blob/master/UPGRADE.md).

## First solution

One of solution with using inventory is to override `branch` param like this:

```php
set('branch', function () {
    return input()->getOption('branch') ?: get('default_branch');
});
```
In _inventory.yml_:

```yaml
host.com:
    default_branch: production
```

But take a look at implementation of `branch` param in Deployer v6 – https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L15
It's mush advance, and have cool feature of automatically deploying current HEAD branch.

## Second solution

Use default `branch` implementation and override only needed hosts:

```yaml
production:
    hostname: domain.com
    branch: production

staging:
    hostname: staging.domain.com
```

**Comment by Streid** [comment]
Thx ;) It works.
