### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by martijn94** [deployphp/deployer#1349]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | 6.0.2
| Local Machine OS  | Does not apply
| Remote Machine OS | Does not apply

### Description 

I am trying to run commands programmatically from PHP. Now the output of informational commands like "dep config:dump staging" is in a table like terminal format. Would be awesome if it would be possible to specify a format to receive the output in JSON for instance to read it easily in code.

If any more information or testing is needed, please let me know!

**Comment by antonmedv** [comment]
What kind of information you want to see?

**Comment by antonmedv** [comment]
Can you an example of expected json file?

**Comment by martijn94** [comment]
Now when doing a config dump I end up with this array, it's really hard to extract values from here.

![configdump](https://user-images.githubusercontent.com/1652861/29872867-94c92bb4-8d91-11e7-949d-8d3572f238e9.jpg)

Would be awesome to do something like "dep config:dump staging --format=json

Which would result in something like 

`{"stage":"staging","branch":"staging","shared_files":["staging_config.php"],"deploy_path":"\/path\/to\/deploy","releases_list":[1,2,3,4,5], "etc": "etc"}`

I you see a better way of solving this that would be an solution for me as well. But this would awesome in my opinion for automating stuff and any future informational commands.

Thanks!

**Comment by antonmedv** [comment]
Yes, this will be cool to have.

**Comment by martijn94** [comment]
Cool, will also looking into adding this myself. Not sure if my skills will manage.

For anyone else trying to add support for this, I know WP CLI supports different formats for an example: https://github.com/wp-cli/wp-cli
