### ISSUE TITLE
--version option is not working properly

### ISSUE THREAD

**Issue by matyx** [deployphp/deployer#1351]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | ^4, ^5 and ^6 (composer notation)
| Local Machine OS  | Linux
| Remote Machine OS | N/A

### Description 
`dep --version` always returns master only, and it should returns version of installed deployer

### Steps to reproduce
```bash
composer require deployer/deployer:^5
vendor/bin/dep --version #outputs Deployer master, should be v5.1.3

composer require deployer/deployer:^6
vendor/bin/dep --version #outputs Deployer master, be v6.0.2

composer require deployer/deployer:^4
vendor/bin/dep --version #outputs Deployer master, should be v4.3.1
```

**Comment by antonmedv** [comment]
Actually it should. Take a look at https://github.com/deployphp/deployer/blob/master/bin/dep#L91
Maybe a bug there.

**Comment by matyx** [comment]
I think that it would be better to hardcode version into deployer files, because now I am not able to check version from source, and deployer could be used without composer. I can send PRs, if you agree with this.

**Comment by antonmedv** [comment]
I don't think what hardcoded version will be good. Maintaining versions will be harder as we need to create separate commits with version for releases in order to save master varsion for master branch.

**Comment by chellem** [comment]
The problem is that when installing deployer globally, the version is found in ~/composer.lock but `dep` is trying the read composer.lock from inside the deployer vendor directory which does not contains deployer/deployer version as it is found.
