### ISSUE TITLE
deploy:release requires shell date function?!

### ISSUE THREAD

**Issue by tinogo** [deployphp/deployer#1359]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.3.1
| Local Machine OS  | Docker PHP Image, PHP 7.1
| Remote Machine OS | Hosteurope Webpack Premium (Linux)

### Description 
I'm currently trying to deploy my application using Gitlab to a Webpack (normal webspace with SSH access) of the german hoster "Hosteurope".
When running the various deployment tasks, the `deploy:release`-task from the `common.php` recipe fails, because the shell for this webhosting package forbids the usage of the function `date`.

Is there any way for me to prevent this error?

### Output log
```sh
$ php deployer.phar --file=./ci/deploy/deploy.php -vvv deploy production --branch ${CI_JOB_REF_NAME}
➤ Executing task deploy:prepare
[production] > echo $0
[production] < bash
[production] > if [ ! -d ~/www/ ]; then mkdir -p ~/www/; fi
[production] > if [ ! -L ~/www//current ] && [ -d ~/www//current ]; then echo true; fi
[production] > cd ~/www/ && if [ ! -d .dep ]; then mkdir .dep; fi
[production] > cd ~/www/ && if [ ! -d releases ]; then mkdir releases; fi
[production] > cd ~/www/ && if [ ! -d shared ]; then mkdir shared; fi
• done on [production]
✔ Ok [3s 655ms]
➤ Executing task deploy:release
[production] > cd ~/www/ && (if [ -h release ]; then echo 'true'; fi)
[production] > cd ~/www/ && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[production] < false
[production] > cd ~/www/ && (if [ -d ~/www//releases/1 ]; then echo 'true'; fi)
[production] > cd ~/www/ && (date +"%Y%m%d%H%M%S")
➤ Executing task deploy:failed
• done on [production]
✔ Ok [0ms]

                                 
  [RuntimeException]             
  bash: date: command not found  
```

**Comment by antonmedv** [comment]
Is it possible to install date utility there?

**Comment by tinogo** [comment]
Nope - the shell access for the webspace offerings of Hosteurope are really restricted in this regard.
And to change the hoster is currently not an option for my customer... :(

**Comment by antonmedv** [comment]
You can override this task and trim date

**Comment by tinogo** [comment]
Okay - thanks.
This was the only solution, which was coming in my mind, too.
But this would result in that the deployer meta-information is not being written, right?!

**Comment by antonmedv** [comment]
No, actually you can change `run('date')` to php call `date()` or similar.

**Comment by tinogo** [comment]
Hi Anton,
thanks for your help - this solution resolved my problem! :)
I'll close this issue now. :)
