### ISSUE TITLE
Reach 99% code coverage

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#136]
I think it well be cool to have in next v3.1 release. 

If some one take it, i'll will give free PhpStorm license. :moneybag:

**Comment by elfet** [comment]
![2015-02-20 18 00 23](https://cloud.githubusercontent.com/assets/141232/6288486/6f6e116a-b92a-11e4-907e-8f23c89bb178.png)
I am good :smile:

**Comment by dirkluijk** [comment]
Is the PhpStorm license still available? :smirk:
I need some practice on unit testing, so...

**Comment by elfet** [comment]
@dirkluijk yes, but only for Core Developers or some one who reach this feature goal :)
