### ISSUE TITLE
dep deploy {branchname}

### ISSUE THREAD

**Issue by johnrobertporter** [deployphp/deployer#1360]
I would love to be able to deploy a specific branch by typing it in the command line.

There may already be a way to do this using a default host or something, but I am unsure if I can.

Is this possible?

**Comment by grohiro** [comment]
@johnrobertporter I use `--branch` option in the command line.

**Comment by antonmedv** [comment]
Btw, In Deployer v6 if you type `dep deploy` it automatically will deploy current git branch.

**Comment by johnrobertporter** [comment]
Thanks for the pointers guys!
