### ISSUE TITLE
shared_dirs keep permissions as set locally?

### ISSUE THREAD

**Issue by jasperf** [deployphp/deployer#1362]
Just a quick general question which I did not see answered at [Deployer Documentation on Configuration](https://deployer.org/docs/configuration). Are the `shared_dirs` always going to keep the permissions as set locally? I mean we currently have:
```
// Make sure uploads & published aren't overwritten by deploying
set('shared_dirs', [
    'public/uploads',
    'public/published'
]);
```
in deploy.php and on the server they are now chmod 777 while others are 775 on the server.

**Comment by antonmedv** [comment]
Hi,

No, deployer does not copy any local permissions as it doesnt transfer anything. You need to setup correct permissions yourself.

**Comment by jasperf** [comment]
@antonmedv OK, understood. Thanks!
