### ISSUE TITLE
PHP7.0 requirement

### ISSUE THREAD

**Issue by nvaken** [deployphp/deployer#1366]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Deployer seems to implement some PHP 7.0 only code, which crashes our < 7.0 environment. 

### Steps to reproduce
Use older PHP version, for example 5.6. Note that it crashes. 
```
Parse error: syntax error, unexpected ':', expecting '{' in /path/to/project/vendor/deployer/deployer/src/Support/helpers.php on line 82
```

### Suggestion
I only noticed 3 small implementations of PHP7.0 dependent code and two of those were shorthands. I think those are easily replaced by non PHP7.0 dependent code and one implementation of return type declaration. If there are no other (heavier) implementations, I'd suggest making those compatible with older version. 

If not, then define that PHP 7.0 is required for running Deployer.

The implementations I found:
#### functions.php:283:
```
    $env = get('env', []) + ($options['env'] ?? []);
```
#### functions.php:311:
```
    $env = get('env', []) + ($options['env'] ?? []);
```
#### helpers.php:82
```
function array_to_string(array $array): string
```

**Comment by antonmedv** [comment]
Actually I'm looking forward to push more php7 related stuff. 😃

For php5 there is an older version for deployer.

And deployer can detect php5 and notify user about it.

**Comment by nvaken** [comment]
Alright, well, I didn't notice the problems about PHP 7 untill I opened my Drupal 8 project with Deployer installed into the `vendor/` folder. It crashed our Drupal 8 install since deployer is autoloaded into the project. Maybe it's still a wise decision to add a "requirements" section into the readme or anything? Or shouldn't I have required the package at all into the project? I was planning to use the `vendor/bin/dep` binary to execute deployer.

**Comment by antonmedv** [comment]
Platform requirement sounds good. Also install it as dev dependency.

**Comment by kszymukowicz** [comment]
@nvaken

Did you try to use deployer/dist?
You will have binary in vendor/bin/dep and no dependencies to all other packages.

**Comment by nvaken** [comment]
Hi @kszymukowicz, not sure what you mean with `deployer/dist`? I'm using `vendor/bin/dep`. I think I'm all good. Though, I do think that a few things could be done to prevent confusion in the future by:
1. Adding platform package requirements to `composer.json` for PHP 7.0
2. Adding a 'requirements' chapter to README.md
3. Change the https://deployer.org/ instructions about composer installation and add a `--dev` flag.

**Comment by kszymukowicz** [comment]
You install deployer with composer, right ?
So why do not you install https://github.com/deployphp/distribution with composer ?

**Comment by nvaken** [comment]
Because the website instructs me otherwise :-)

![image](https://user-images.githubusercontent.com/503360/30633281-5ae597ce-9deb-11e7-84e0-8d649a8f9607.png)

So, this should be the preferred way of installing Deployer? If so, shouldn't the documentation be changed accordingly? 

Thanks, I'll be trying out this method later. 👍

**Comment by kszymukowicz** [comment]
@nvaken 

Its there later in docs:
https://deployer.org/docs/installation

But you right that on homepage its deployer/deployer. IMO preferred could be deployer/dist as I suppose nobody wants to pollute project with not needed dependencies.
