### ISSUE TITLE
Canceling deployment with CTRL+C, task still locked.

### ISSUE THREAD

**Issue by jiisuominen** [deployphp/deployer#1368]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug / Question
| Deployer Version  | v6.0.3
| Local Machine OS  | Ubuntu VM
| Remote Machine OS | N/A

### Description 
I canceled deployment with CTRL+C, and now I can't unlock said deployment. When I run deploy:unlock, I get message suggesting that deploy.lock file has been deleted. But when I try and run deployment again, still get message about concurrent deployment.

So I can't get that canceled deployment run again.

When I run deploy:unlock with -vvv I can see that Deployer is trying to delete lock file, but when I go to check deployment path, I can't see lock file anywhere. I searched my whole target server and my VM, and no deploy.lock file anywhere to be found.

Cheers,
Janne

**Comment by mikemix** [comment]
`dep unlock host/stage` ?

**Comment by jiisuominen** [comment]
Yeah, got this working.
