### ISSUE TITLE
Alternative to rsync

### ISSUE THREAD

**Issue by garhbod** [deployphp/deployer#1369]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 5
| Local Machine OS  | linux
| Remote Machine OS | linux

### Description 
Rsync isn't available on our share remote so having an SFTP or SCP option to upload would be nice

**Comment by antonmedv** [comment]
For upload/download?

**Comment by garhbod** [comment]
The upload is all I was concerned about

**Comment by antonmedv** [comment]
But rsync really fast.

**Comment by garhbod** [comment]
I'm sure it is. But what do I do when rsync isn't available

**Comment by antonmedv** [comment]
I see. What about implementing separate recipe with scp?

**Comment by garhbod** [comment]
With 2 new functions like uploadWithSCP or something?

**Comment by antonmedv** [comment]
Or with task `upload:scp`.

**Comment by garhbod** [comment]
Why not just a new function added to `src/functions.php` called `uploadWithSCP` or `uploadWithSFTP`.
Take the first 2 arguments of upload

**Comment by garhbod** [comment]
I was able to replace
```
upload($source, "{{deploy_path}}/{$destination}");
```
With
```
runLocally("scp -rC -P {{port}} {$source} {{user}}@{{hostname}}:{{deploy_path}}/{$destination}");
```

Is there a way I can make a class for scp that can be used to replace the Rsync class

**Comment by antonmedv** [comment]
Just create composer package.

**Comment by antonmedv** [comment]
I'm closing this issues as inactive. Please, feel free to open new issues.
