### ISSUE TITLE
Deployer throws a general error when executing a server command

### ISSUE THREAD

**Issue by aMerovingian** [deployphp/deployer#1374]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug/ Feature Request
| Deployer Version  | 5.1.3
| Local Machine OS  | Linux version 4.4.0-79-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )
| Remote Machine OS | Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )  

### Description 
 In the last step in my deploy process I have a task that kills some cron jobs on the target server
  First part of the executed command (this is with the problem) : "ps axf  | grep target_cron_script"  
 If there is no active process at that moment with that name, deployer stops the entire process; he interprets it as an error. (i'm not sure what he receives at php level that he interprets it like that)

 Now, this might not be a bug...but at least I should be able to catch that error...because sometimes the script is active and sometimes..it's not...and I can't have that affecting the deploy process.
Is there a workaround for this problem? Or a different approach?
 
### Steps to reproduce
Execute command: dep test-process my.server.com -vvv
### Content of `deploy.php`  (the task)
```php
task('test-process', function () { 
       $res=run("ps axf  | grep target_cron_script");
        writeln("result: $res");   
});
```

### Output log
 Warning: Permanently added 'my.server.com,xxx.xxx.xxx.xxx' (ECDSA) to the list of known hosts.

                                                                                          
  [Deployer\Exception\RuntimeException (1)]                                               
  The command "ps axf  | grep target_cron_script" failed.                                      
  Exit Code: 1 (General error)                                                            
  Host Name:  my.server.com                                                           
  ================                                                                        
  Warning: Permanently added ' my.server.com ,xxx.xxx.xxx.xxx' (ECDSA) to the list of  
   known hosts.                                                                           
                                                              

Exception trace: 
 () at phar:///usr/local/bin/dep/src/Ssh/Client.php:95
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:297
 Deployer\run() at /home/alex/project/project-app/deploy.php:197
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:82
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:142
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:320
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

Thanks

**Comment by antonmedv** [comment]
It's php =) 
```js
task('test-process', function () { 
   try {
       $res=run("ps axf  | grep target_cron_script");
        writeln("result: $res");   
   } catch (\Deployer\Exception\RuntimeException $e) {
        writeln("no process");   
   }
});
```

**Comment by aMerovingian** [comment]
Hello,
True, it was an inattention on my part.
I did try to catch that exception, but silly me, it was without the backslash symbol at the beginning 
 : " catch (Deployer\Exception\RuntimeException $e) " and this, of course, didn't work 

Thank you
