### ISSUE TITLE
How to update hosts with a dynamic IP

### ISSUE THREAD

**Issue by hailwood** [deployphp/deployer#1375]
* Deployer version: v6.0.3
* PHP version: 7.1
* Deployment target(s) OS: Ubuntu 17.04

---

I have a similar issue to #1320 with the one difference being I only need a single host, 

I need the identityFile, hostname, ssh user to be passed in via options and In the linked issue @antonmedv commented that

> You can create a local task where you can get IPs and update hosts info

But I cannot find any docs on how to update the host info via a task. 
Can you please provide an example of what this task would look like?

For simplicities sake let's say the options are

```php
option('user', null, InputOption::VALUE_REQUIRED, 'SSH User.');
option('identity', null, InputOption::VALUE_REQUIRED, 'SSH Identity File Path.');
option('hostname', null, InputOption::VALUE_REQUIRED, 'SSH Hostname.');
```

and the script is invoked as 

```sh
dep deploy --user=matthew --identity=./deploy-matthew.pem --hostname=matthew.example.com
```

**Comment by antonmedv** [comment]
Hi, for now the easiest solution is to use env params:
```js
host(getenv('hostname'))
    ->user(getenv('user'))
    ->identityFile(getenv('identity'));
```

And call it with proper env:
```
$ dep deploy user=matthew identity=./deploy-matthew.pem hostname=matthew.example.com
```
