### ISSUE TITLE
[Magento2] Disable maintenance only when previously disabled

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1379]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question/ Feature Request

Is it possible to only disable maintenance mode, when it was previously also disabled.

So situation 1, site is live, maintenance is disabled

 - enable maintenance
 - upgrade DB
 - disable maintenance

Situation 2, maintenance is enabled because of development / IP filter

 - skip maintenance enable, already enabled.
 - db upgrade
 - skip maintenance disable.

In our case we use the maintenance mode to prevent users from seeing pre-production versions for only certain IPs, as this is a standard Magento2 feature.

**Comment by antonmedv** [comment]
So you want smarter maintains mode?

**Comment by barryvdh** [comment]
Yeah indeed, by setting a flag or runtime variable when the maintenance file exists.

**Comment by antonmedv** [comment]
Can you create pr for this feature?
