### ISSUE TITLE
Deploy 2 projects to one host from one deploy file

### ISSUE THREAD

**Issue by denrolya** [deployphp/deployer#1383]
Given:

* Single-page frontend application(angularJS) & API backend service(Symfony3)
* One host for one stage which hosts both the front- & the backend
* Deployer version: 6.0.3

The question is: how to be able to deploy both of them using the following format of command: `dep deploy [frontend|backend]`.
The problem now is: you have to describe them as 2 separate hosts, as they use different parameters, `repository` & `deploy_path` at least. Then if you keep them in one file you can't just have 2 tasks for backend & frontend described as so:

    task('deploy', [
        'deploy:info',
        .
        .
        .
    ])->onHosts(['[frontend|backend]']);
I mean you can, but then in command line you gonna write `dep deploy stage --hosts frontend` & `dep deploy stage --hosts backend` either one of them will fail with error:

      No task will be executed, because the selected hosts do not meet the conditions of the tasks.

My guess is that it overrides the task itself & will execute the one that stands last.

----

AND OK. I can be have a workaround for that too

    task('deploy:frontend', [
        'deploy:info',
        .
        .
        .
    ]);
    task('deploy:backend', [
        'deploy:info',
        .
        .
        .
    ]);

This way, will be logical to run it with `dep deploy:[frontend|backend] stage`, BUT since both frontend & backend live on the same server & they both have `deploy_path` parameters for instance, it just overrides the deploy parameters with the last host's configuration in the file.

----

For that matter what I've used is `onHosts()` function with some tweaking on hosts declarations;

    host('backend')
        ->hostname('host.com')
    host('frontend')
        ->hostname('host.com')
& 2 tasks defined:

    task('deploy:[frontend|backend]', [
        'deploy:info',
        .
        .
        .
    ])->onHosts(['[frontend|backend]']);

this way you'll have to deploy as so: `dep deploy:[frontend|backend] stage --hosts [frontend|backend]` which you all agree is nonsensical.

My further guess is to separate deploys into 2 files as `backend.php` & `frontend.php`. `dep deploy stage -f [frontend|backend].php`, but for everyday operations it is inconvenient, like database import/export...

**Please share your opinion or solution to this problem**

**Comment by antonmedv** [comment]
A few questions:
Do you have different repos for front/back?
Do you need one command to deploy it together?

Maybe something like this:
```php
host('front.stageing')
    ->hostname('staging.project.com')
    ->set('deploy_path', '~/front')
    ->roles(['front'])
    ->stage('staging');

host('back.stageing')
    ->hostname('staging.project.com')
    ->set('deploy_path', '~/back')
    ->roles(['back'])
    ->stage('staging');

host('front.prod')
    ->hostname('front.project.com')
    ->set('deploy_path', '~/front')
    ->roles(['front'])
    ->stage('production');

host('back.prod')
    ->hostname('back.project.com')
    ->set('deploy_path', '~/back')
    ->roles(['back'])
    ->stage('production');

task('forntend', [...])->onRoles('front'); // How to deploy frontend
task('backend', [...])->onRoles('back'); // How to deploy backend

task('deploy', ['frontend', 'backend']); // Deploy together
```

Usage:
```
dep frontend staging
dep backend staging

dep frontend production
dep backend production
```

And default usage:
```
dep deploy staging
dep deploy production
```

**Comment by denrolya** [comment]
Nope, repos are different. And having one command to deploy them together is not a must. Your approach looks like something I could use now. However it would be still nice to be able to have multiple task definitions and have them polymorphic.
Thank you for you fast response!

**Comment by antonmedv** [comment]
> Nope, repos are different

Set repos in host:

```php
host('back.prod')
    ...
    ->set('repository', '...')
    ...
``` 

Or set in in task:

```php
task('repos:front', function () {
    set('repository', '...');
});

task('forntend', ['repos:front'...])->onRoles('front'); // How to deploy frontend
```

> However it would be still nice to be able to have multiple task definitions and have them polymorphic.

What do you mean by polymorphic?

**Comment by denrolya** [comment]
Copying your approach and using it with `dep frontend staging` I get the following error:

     No task will be executed, because the selected hosts do not meet the conditions of the tasks 

By polymorphic I mean having multiple tasks with same name but different scenarios based on hosts|roles

**Comment by antonmedv** [comment]
Show full deploy.php

**Comment by denrolya** [comment]
<?php
    namespace Deployer;
    
    require __DIR__ . '/vendor/deployer/deployer/recipe/symfony3.php';
    require __DIR__ . '/vendor/deployer/recipes/recipe/slack.php';
    
    set('application', '-CHANGE_ME-'); // Project name
    set('http_user', '-CHANGE_ME-');
    set('db', [
        'local' => [
            'name' => '-CHANGE_ME-',
            'username' => '-CHANGE_ME-'
        ],
        'staging' => [
            'host' => '-CHANGE_ME-',
            'port' => -CHANGE_ME-,
            'name' => '-CHANGE_ME-',
            'username' => '-CHANGE_ME-'
        ]
    ]);
    set('slack_webhook', '-CHANGE_ME-');
    
    // Hosts
    host('backend.staging')
        ->hostname('-CHANGE_ME-')
        ->stage('staging')
        ->roles(['backend'])
        ->user('-CHANGE_ME-')
        ->identityFile('~/.ssh/id_rsa')
        ->multiplexing(true)
        ->set('repository', '-CHANGE_ME-')
        ->set('branch', 'develop')
        ->set('clear_paths', [])
        ->set('symfony_env', 'dev')
        ->set('composer_options', 'install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader')
        ->set('deploy_path', '/path/to/api.{{application}}.staging')
        ->set('shared_dirs', ['var/logs', 'var/jwt', 'var/sessions'])
        ->set('slack_success_text', 'Deploy to backend *{{target}}* successful');
    
    host('frontend.staging')
        ->hostname('-CHANGE_ME-')
        ->stage('staging')
        ->roles(['frontend'])
        ->user('-CHANGE_ME-')
        ->identityFile('~/.ssh/id_rsa')
        ->multiplexing(true)
        ->set('repository', '-CHANGE_ME-')
        ->set('branch', 'develop')
        ->set('dist_folder', 'dist')
        ->set('clear_paths', ['.git*', '.sass*', '.tmp'])
        ->set('deploy_path', '/path/to/{{application}}.staging')
        ->set('shard_files', 'env.js')
        ->set('slack_success_text', 'Deploy to frontend *{{target}}* successful');
    
    task('database:copy:to_local', function() {
        $dumpFilename = 'dump-' . time() . '.sql';
        $remoteDb = get('db')[input()->getArgument('stage')];
        $localDb = get('db')['local'];
    
        writeln('<info>Dumping database from remote host.</info>');
    runLocally("pg_dump --host={$remoteDb['host']} --port={$remoteDb['port']} --username={$remoteDb['username']} --dbname={$remoteDb['name']} > ./    $dumpFilename");
    
        writeln('<info>Dump success. Exporting dump into local database.</info>');
        runLocally("psql --username={$localDb['username']} --dbname={$localDb['name']} < ./$dumpFilename");
        writeln('<info>Successfully exported! Removing leftover files...</info>');
    
        runLocally("rm ./$dumpFilename");
        writeln('<info>Finish!</info>');
    })->desc('Copy database from remote stage to local environment');
    
    task('database:copy:to_remote', function() {
        if (!askConfirmation('You sure you want to upload your local DB to a ' . get('db')['host'] . ' host?')) {
            writeln('<info>Aborted by user!</info>'); die;
        }
    
        $dumpFilename = 'dump-' . time() . '.sql';
        $remoteDb = get('db')[input()->getArgument('stage')];
        $localDb = get('db')['local'];
    
        writeln('<info>Dumping database locally.</info>');
        runLocally("pg_dump --username={$localDb['username']} --dbname={$localDb['name']} > ./$dumpFilename");
    
        writeln('<info>Dump complete. Exporting dump into remote database.</info>');
    runLocally("psql --host={$remoteDb['host']} --port={$remoteDb['port']} --username={$remoteDb['username']} --dbname={$remoteDb['name']} < ./$    dumpFilename");
        writeln('<info>Successfully exported! Removing leftover files...</info>');
    
        runLocally("rm ./$dumpFilename");
        writeln('<info>Finish!</info>');
    })->desc('Copy local database to remote stage');
    
    task('backend', [
        'deploy:info',
        'deploy:prepare',
        'deploy:lock',
        'deploy:release',
        'deploy:update_code',
        'deploy:clear_paths',
        'deploy:create_cache_dir',
        'deploy:shared',
        'deploy:assets',
        'deploy:vendors',
        'deploy:assets:install',
        'deploy:assetic:dump',
        'deploy:cache:clear',
        'deploy:cache:warmup',
        'deploy:writable',
        'deploy:symlink',
        'deploy:unlock',
        'cleanup',
    ])->onRoles('backend')
        ->desc('Deploy backend application');
    
    task('frontend', [
        'deploy:info',
        'deploy:prepare',
        'deploy:lock',
        'deploy:release',
        'deploy:update_code',
        'deploy:frontend:vendors',
        'deploy:frontend:build',
        'deploy:frontend:clear_paths',
        'deploy:symlink',
        'deploy:unlock',
        'cleanup'
    ])->onRoles('frontend')
        ->desc('Deploy frontend application');
    
    task('deploy', ['frontend', 'backend']);
    
    task('deploy:frontend:clear_paths', function() {
        run("cd {{release_path}} && ls | grep -v {{dist_folder}} | xargs rm -rf");
    
        $paths = get('clear_paths');
        $sudo  = get('clear_use_sudo') ? 'sudo' : '';
    
        foreach ($paths as $path) {
            run("$sudo rm -rf {{release_path}}/$path");
        }
    })->desc('Cleaning up files and/or directories');
    
    task('deploy:frontend:vendors','
        npm install;
        bower install
    ')->desc('Install frontend dependencies');
    
    task('deploy:frontend:build', 'grunt build')->desc('Build frontend application');
    
    after('deploy:failed', 'deploy:unlock');
    after('frontend', 'success');
    after('backend', 'success');
    after('deploy', 'success');
    after('success', 'slack:notify:success');

**Comment by antonmedv** [comment]
Error: `->roles(['front'])` to `->roles('front')`

**Comment by denrolya** [comment]
`dep frontend staging` for instance gives me the following.
✈︎ Deploying develop on backend.staging
✈︎ Deploying develop on frontend.staging
...

Sees it as the same host I suppose, and hence overriding parameters with the other's host config and then fails

**Comment by denrolya** [comment]
Task polymorphism could come really handy in situations like this. Something to keep deployer aware that 2 tasks with same names are different conditionally or by definition

**Comment by antonmedv** [comment]
I'll think about polymorphism for tasks in deployer

**Comment by denrolya** [comment]
Would love to help. Just write

**Comment by renatop7** [comment]
Hi @denrolya 
I'm basically in the same situation as you, but using Anguar 6 + Laravel 5.4.

Did you manage to workaround the limitations to deploy your projects?

**Comment by denrolya** [comment]
Well, I'm using it as `dep frontend staging --hosts frontend.staging` with the configuration above

**Comment by lucasmezencio** [comment]
I'm trying to do basically the same, but I'm facing some issues.

Here's my `deploy.php`:
```php
<?php

namespace Deployer;

require 'recipe/common.php';

// Project name
set('application', 'API');

// Project repository
set('api_repo', 'git@__/api.git');
set('cron_repo', 'git@__/cron.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);
set('allow_anonymous_stats', false);
set('identity_file', '/root/.ssh/__');
set('branch', 'master');
set('deploy_path', null);
set('flow', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success',
]);
set('bin/php', static function () {
    $binary = locateBinaryPath('php');

    return "{$binary} -d disable_functions= ";
});

// Hosts
host('__')
    ->stage('staging')
    ->user('root')
    ->roles(['cron', 'api'])
    ->identityFile('{{identity_file}}');

// Tasks
desc('Prepare API deployment');
task('prep:api', static function () {
    set('repository', get('api_repo'));
    set('deploy_path', '/var/www/html');
});

desc('Prepare CRON deployment');
task('prep:cron', static function () {
    set('repository', get('cron_repo'));
    set('deploy_path', '/var/www/cron');
});

desc('Prepare Configs deployment');
task('prep:config', static function () {
    $stage = get('stage');

    set('deploy_path', '/etc/configs');

    switch ($stage) {
        case 'production':
            set('repository', 'git@__/configs.prod.git');

            break;
        case 'staging':
        default:
            set('repository', 'git@__/configs.stg.git');

            break;
    }
});

desc('Set release path for configs');
task('config:set_release_path', static function () {
    set('config_release_path', get('release_path'));
});

desc('Symlink configs');
task('symlink:config', static function () {
    $target = parse('{{config_release_path}}');
    $link = parse('{{release_path}}/_config');

    symlink($target, $link);
});

desc('Deploy Configs');
task('config', [
    'prep:config',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])
    ->onRoles(['api', 'cron'])
    ->addAfter('config:set_release_path');

desc('Deploy API');
task('api', get('flow'))->onRoles(['api']);

desc('Deploy CRON');
task('cron', get('flow'))->onRoles(['cron']);

desc('Deploy your project');
task('deploy', [
    'config',
    'api',
    'cron',
]);

// [Optional] If deploy fails automatically unlock.
before('api', 'prep:api');
before('cron', 'prep:api');

after('deploy:failed', 'deploy:unlock');

after('api', 'symlink:config');
after('api', 'success');

after('cron', 'symlink:config');
after('cron', 'success');
```

When I run `dep deploy staging`, I realised that Deployer is trying to clone the second project (`api`) in the same folder as the first `config`:

```
cd /var/www/api && (/usr/bin/git clone -b master --recursive git@__/api.git /etc/configs/releases/1 2>&1)
```

> I omitted repositories by purpose.

Am I doing something wrong?

**Comment by antonmedv** [comment]
I'm closing this issues as inactive. Please, feel free to open new issues.
