### ISSUE TITLE
Check for opcache.enable_cli and apc.enable_cli

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1385]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next

### Description 
Check for enabled opcache.enable_cli and apc.enable_cli. Inform user to disable these config.

**Comment by petrenkorf** [comment]
Can I take this issue?

**Comment by antonmedv** [comment]
Yes. Will be perfect.
