### ISSUE TITLE
SSH authentication with password protected key

### ISSUE THREAD

**Issue by michalsvec** [deployphp/deployer#1388]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3

### Description 
In previous version, there was a possibility to authenticate with key that had password. I can't find such option any more. 
There was something like this: ```->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'pass')```. Is it still possible or not?

Thank you.

**Comment by antonmedv** [comment]
Hi, it still possible. If your key has passphrase it Deployer will automatically ask you about you passphrase on deploy. No need to specify it in deploy.php file.

**Comment by michalsvec** [comment]
Yeah, but I have an automated deploy which deploys new version after successful build.

**Comment by antonmedv** [comment]
Use key without password.

**Comment by spidgorny** [comment]
```
> ssh-agent bash
> ssh-add ~/.ssh/aws.pem
Enter passphrase for ~/.ssh/aws.pem:
Identity added: ~/.ssh/aws.pem
> dep deploy
```
It works!
