### ISSUE TITLE
Local deployment with multiple folders and one command

### ISSUE THREAD

**Issue by 3579km** [deployphp/deployer#1396]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.3
| Local Machine OS  | Windows 10, Xshell SSH client
| Remote Machine OS | Ubuntu Server 16.04

### Description 
How can i locally deploy php application on the one server with multiple folders (same code) by one command?
I need to do same action for /var/www/public/localhost2 and /var/www/public/localhost3... folders
Maybe how I can group stages or something like that?

### Steps to reproduce
cd /path/to/deploy.php
dep deploy dev -vvv

### Content of `deploy.php`
```php
<?php
namespace Deployer;

//require 'recipe/yii2-app-advanced.php';

// Project name
set('application', 'app');

// Hosts
localhost()
->stage('dev')
->set('deploy_path', '/var/www/public/localhost1');

localhost()
->stage('dev')
->set('deploy_path', '/var/www/public/localhost2');

localhost()
->stage('dev')
->set('deploy_path', '/var/www/public/localhost1');

// Project repository
set('repository', 'git@bitbucket.org:project/repo.git');

/*
// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);
*/

// Deploying confirmation

/*task('ask', function() {
    if(!askConfirmation('Do you really want to deploy app?')) {
        die('Ok, no deploy then.');
    }
});

before('deploy', 'ask');*/

// Deploy tasks
task('deploy:git', function () {
    run('cd /var/www/public/localhost1 && git pull');
});

task('deploy:migration', function () {
    run('cd /var/www/public/localhost1 && php yii migrate');
});

task('deploy:composer', function () {
    run('cd /var/www/public/localhost1 && composer install');
});

task('deploy:npm', function () {
    run('cd /var/www/public/localhost1/client-apps && npm install');
});

task('deploy:ng build', function () {
    run('cd /var/www/public/localhost1/client-apps && ng build --prod');
});

// Tasks group
task('deploy', [
    'deploy:git',
    'deploy:migration',
    'deploy:composer',
    'deploy:npm',
    'deploy:ng build',
    ]);

// [Optional] if deploy fails automatically unlock.
//after('deploy:failed', 'deploy:unlock');
?>


```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by antonmedv** [comment]
```php
localhost('localhost1')
->stage('dev')
->set('deploy_path', '/var/www/public/localhost1');

localhost('localhost2')
->stage('dev')
->set('deploy_path', '/var/www/public/localhost2');

localhost('localhost3')
->stage('dev')
->set('deploy_path', '/var/www/public/localhost3');
```

Or more simple
```php
localhost('localhost1')
->stage('dev');

localhost('localhost2')
->stage('dev');

localhost('localhost3')
->stage('dev');

set('deploy_path', '/var/www/public/{{hostname}}');
```

**Comment by 3579km** [comment]
Edited
`// Hosts
localhost('localhost1')
->stage('dev')
->set('deploy_path', '/var/www/public/education.vm');

localhost('localhost2')
->stage('dev')
->set('deploy_path', '/var/www/public/en.education.vm');

localhost('localhost3')
->stage('dev')
->set('deploy_path', '/var/www/public/asia.education.vm');`

But deploying in one path
`user@ubuntu:/var/www/public/education.vm$ dep deploy dev -vvv

➤ Executing task deploy:git
[localhost1] > cd /var/www/public/education.vm && git pull
[localhost1] < Already up-to-date.
• done on [localhost1]
[localhost2] > cd /var/www/public/education.vm && git pull
[localhost2] < Already up-to-date.
• done on [localhost2]
[localhost3] > cd /var/www/public/education.vm && git pull
[localhost3] < Already up-to-date.
• done on [localhost3]
✔ Ok [7s 139ms]
➤ Executing task deploy:migration
[localhost1] > cd /var/www/public/education.vm && php yii migrate
[localhost1] < Yii Migration Tool (based on Yii v2.0.12)
[localhost1] < No new migrations found. Your system is up-to-date.
• done on [localhost1]
[localhost2] > cd /var/www/public/education.vm && php yii migrate
[localhost2] < Yii Migration Tool (based on Yii v2.0.12)
[localhost2] < No new migrations found. Your system is up-to-date.
• done on [localhost2]
[localhost3] > cd /var/www/public/education.vm && php yii migrate
[localhost3] < Yii Migration Tool (based on Yii v2.0.12)
[localhost3] < No new migrations found. Your system is up-to-date.
• done on [localhost3]
✔ Ok [133ms]
`

**Comment by antonmedv** [comment]
Really strange, maybe a bug. Will check tomorrow.

**Comment by antonmedv** [comment]
It does working. Here an example:
```php
<?php

namespace Deployer;

require 'recipe/common.php';

localhost('local_1');
localhost('local_2');

set('deploy_path', __DIR__ . '/.tmp/{{hostname}}');

task('test', function () {
    writeln(get('deploy_path'));
});

```

**Comment by antonmedv** [comment]
Please provide a minimal, self-contained, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by 3579km** [comment]
@antonmedv thank you for reply
I tested, i think problem in tasks group - it just make every tasks for each host
Please, help me group tasks
Here is code

`...
// Deploy tasks for education.vm
task('deploy:git', function () {
    run('cd /var/www/public/education.vm && git pull');
});

task('deploy:migration', function () {
    run('cd /var/www/public/education.vm && php yii migrate');
});

task('deploy:composer', function () {
    run('cd /var/www/public/education.vm && composer install');
});

task('deploy:npm', function () {
    run('cd /var/www/public/education.vm/client-apps && npm install');
});

task('deploy:ng build', function () {
    run('cd /var/www/public/education.vm/client-apps && ng build --prod');
});

// Deploy tasks for en.education.vm
task('deploy:en-git', function () {
    run('cd /var/www/public/en.education.vm && git pull');
});

task('deploy:en-migration', function () {
    run('cd /var/www/public/en.education.vm && php yii migrate');
});

task('deploy:en-composer', function () {
    run('cd /var/www/public/en.education.vm && composer install');
});

task('deploy:en-npm', function () {
    run('cd /var/www/public/en.education.vm/client-apps && npm install');
});

task('deploy:en-ng build', function () {
    run('cd /var/www/public/en.education.vm/client-apps && ng build --prod');
});

// Deploy tasks for asia.education.vm
task('deploy:asia-git', function () {
    run('cd /var/www/public/asia.education.vm && git pull');
});

task('deploy:asia-migration', function () {
    run('cd /var/www/public/asia.education.vm && php yii migrate');
});

task('deploy:asia-composer', function () {
    run('cd /var/www/public/asia.education.vm && composer install');
});

task('deploy:asia-npm', function () {
    run('cd /var/www/public/asia.education.vm/client-apps && npm install');
});

task('deploy:asia-ng build', function () {
    run('cd /var/www/public/asia.education.vm/client-apps && ng build --prod');
});

// Tasks group
task('deploy', [
    'deploy:git',
    'deploy:migration',
    'deploy:composer',
    'deploy:npm',
    'deploy:ng build',
    'deploy:en-git',
    'deploy:en-migration',
    'deploy:en-composer',
    'deploy:en-npm',
    'deploy:en-ng build',
    'deploy:asia-git',
    'deploy:asia-migration',
    'deploy:asia-composer',
    'deploy:asia-npm',
    'deploy:asia-ng build',
    ]);
?>`

**Comment by antonmedv** [comment]
Please provide a full example of deploy.php

**Comment by antonmedv** [comment]
Add restrictions to tasks: `->onHosts('education.vm')`
