### ISSUE TITLE
Rsync and recursive directories creation

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1397]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Check it

> I guess it is a limitation of rsync that it does not want to recursively create directories.

See #1395

**Comment by oanhnn** [comment]
I see output when upload files by rsync, it fire but with out compress. 
And try with option `-zz`, it was fire success.

I think you should replace this option in https://github.com/deployphp/deployer/blob/master/src/Utility/Rsync.php#L40

```
$ rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, no xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

$ rsync -azP -e 'ssh -A -p 22' public/fonts/ oanhnn@host:/apps/app_name/releases/2/public/fonts/
This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.

$ rsync -azz -e 'ssh -A -p 22' public/fonts/ oanhnn@host:/apps/app_name/releases/2/public/fonts/
```

**Comment by kinoute** [comment]
Any news on this? For the moment if I want to upload a single file into a new directory, I have to use `run('mkdir folder'); `before using `upload() `.  Otherwise it fails with the rsync error explained in #1395.

**Comment by antonmedv** [comment]
Nope, still no solution to this. I'll look to this later.
