### ISSUE TITLE
Could not connect to remote machine.

### ISSUE THREAD

**Issue by akoSalman** [deployphp/deployer#1398]
| Q                 | A
| ----------------- | ---
| Issue Type        |Question
| Deployer Version  |  v6.0.3
| Local Machine OS  | Windows 10
| Remote Machine OS | CentOS release 6.8 

### Description 
I can make ssh connection to the remote_machine from my local windows.10 machine using a passphrase.
But when trying to connect to remote machine using deployer i got below error.
how can i fix it?
thanks.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', 'karabama');

// Project repository
set('repository', 'ssh://root@remote_machine_ip/home/projects/project.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);


// Hosts

host('remote_machine_ip')
    ->set('deploy_path', '/var/www/project/');    
    
// Tasks

task('build', function () {
    run('ls');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'artisan:migrate');


```

### Output log
*dep deploy -vvv
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < master
ظ£êي╕ Deploying master on remote_machine_ip
ظت done on [remote_machine_ip]
ظئج Executing task deploy:prepare
[remote_machine_ip] > echo $0
[remote_machine_ip] < ssh multiplexing initialization
[remote_machine_ip] < Permission denied, please try again.
[remote_machine_ip] < Permission denied, please try again.
[remote_machine_ip] < Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
ظئج Executing task deploy:failed
ظت done on [remote_machine_ip]
ظ£¤ Ok [3ms]
ظئج Executing task deploy:unlock
[remote_machine_ip] > rm -f /var/www/project//.dep/deploy.lock
[remote_machine_ip] < ssh multiplexing initialization
[remote_machine_ip] < Permission denied, please try again.
[remote_machine_ip] < Permission denied, please try again.
[remote_machine_ip] < Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

  [Deployer\Exception\RuntimeException (-1)]
  The command "rm -f /var/www/project//.dep/deploy.lock" failed.
  Exit Code: -1 (Unknown error)
  Host Name: remote_machine_ip
  ================
  Permission denied, please try again.
  Permission denied, please try again.
  Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

Exception trace:
 () at E:\Projects\project\vendor\deployer\deployer\src\Ssh\Client.php:96
 Deployer\Ssh\Client->run() at E:\Projects\project\vendor\deployer\deployer\src\functions.php:292
 Deployer\run() at E:\Projects\project\vendor\deployer\deployer\recipe\deploy\lock.php:30
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at E:\Projects\project\vendor\deployer\deployer\src\Task\Task.php:104
 Deployer\Task\Task->run() at E:\Projects\project\vendor\deployer\deployer\src\Executor\SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at E:\Projects\project\vendor\deployer\deployer\src\Console\TaskCommand.php:152
 Deployer\Console\TaskCommand->execute() at E:\Projects\project\vendor\symfony\console\Command\Command.php:264
 Symfony\Component\Console\Command\Command->run() at E:\Projects\project\vendor\symfony\console\Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at E:\Projects\project\vendor\deployer\deployer\src\Console\Application.php:132
 Deployer\Console\Application->doRunCommand() at E:\Projects\project\vendor\symfony\console\Application.php:228
 Symfony\Component\Console\Application->doRun() at E:\Projects\project\vendor\symfony\console\Application.php:130
 Symfony\Component\Console\Application->run() at E:\Projects\project\vendor\deployer\deployer\src\Deployer.php:324
 Deployer\Deployer::run() at C:\Users\pc\AppData\Roaming\Composer\vendor\deployer\deployer\bin\dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]*

**Comment by antonmedv** [comment]
Can you connect directly using `ssh ...`? Can you use key without passhrase?

**Comment by akoSalman** [comment]
@antonmedv Yes i can connect directly using `ssh`.
What do u mean of key?
I have added my local machine's public key to to the server(remote_machine) and could connect just using a passphrase.
Here is prompt when i connect through `ssh` from git bash : `Enter passphrase for key '/c/Users/pc/.ssh/id_rsa': `
I wonder who to set this passphrase in deployer?

**Comment by antonmedv** [comment]
Deployer should ask for passphrase it it persist. Maybe it's a bug during to different behavior of pipes on windows. Do you use _Bash for windows_?

**Comment by akoSalman** [comment]
@antonmedv No i use windows CMD.
I'll try it on git bash now.

**Comment by akoSalman** [comment]
@antonmedv Now i tried to connect(`dep deploy`) on git bash, it asks for passphrase, when i enter it, it prompt and prompt again for passphrase.
:(
I'm sure that passphrase is correct, because i can make `ssh` connection using `ssh root@remote_machine_ip` and it prompts for passphrase, and then when passphrase entered connection is established.

**Comment by antonmedv** [comment]
> mux_client_request_session: read from master failed: Connection reset by peer
Authentication failed.

Try to disable ssh_multiplexing:

```php
set('ssh_multiplexing', false);
```

**Comment by akoSalman** [comment]
@antonmedv I deactived passphrase on ssh and above issue solved.
Now i got this error (I googled below issue and could not solve it):
$ dep deploy
✈︎ Deploying master on 46.105.235.153
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
✔ Executing task deploy:failed
✔ Executing task deploy:unlock


  [Symfony\Component\Process\Exception\RuntimeException]
  TTY mode is not supported on Windows platform.

I want to deploy a `Laravel` project

**Comment by antonmedv** [comment]
Add github to list of known hosts on server.

**Comment by akoSalman** [comment]
@antonmedv Not wokred.

**Comment by antonmedv** [comment]
> TTY mode is not supported on Windows platform.

And of cause disable tty for git:
```php
set('git_tty', false); 
```

**Comment by Kaos-Industries** [comment]
> 

What's the YAML equivalent to this? Couldn't find it anywhere in the documentation.

**Comment by Kaos-Industries** [comment]
> > TTY mode is not supported on Windows platform.
> 
> And of cause disable tty for git:
> 
> ```
> set('git_tty', false); 
> ```

What's the YAML equivalent to this? Couldn't find it anywhere in the documentation.
