### ISSUE TITLE
Deployer not installing

### ISSUE THREAD

**Issue by reginaldojunior** [deployphp/deployer#1404]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v4.3.1
| Local Machine OS  | Fedora
| Remote Machine OS | Debian

### Description 
When try install deployer composer return error.

![captura de tela de 2017-11-01 11-56-26](https://user-images.githubusercontent.com/7466894/32278106-5a0b212e-bef3-11e7-8c6b-60efeb4e1725.png)

composer.json

```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"phpunit/phpunit": "4.1.0"
	},
	"require-dev": {
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

### Steps to reproduce

Nothing

### Content of `deploy.php`

Nothing

### Output log

Nothing

**Comment by antonmedv** [comment]
Looks like deps conflict. Try to use dep as phar archive or upgrade to newer version.
Related to #1371
