### ISSUE TITLE
Initial shared file not created

### ISSUE THREAD

**Issue by kviolka** [deployphp/deployer#1406]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug,
| Deployer Version  | 6.0.3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | FreeBSD 11.1

### Description 
#1142 is not fixed for me, the initial file is not created. Instead empty files are symlinked.

### Steps to reproduce
Have a shared file configured, I use the Drupal 8 recipe. 

In a debugger, i noticed that both of the tests in the if clause in shared.php result to "false" so the file is not copied.

**Comment by kviolka** [comment]
my fault, sorry.

**Comment by matheusdallrosa** [comment]
Hi, i'm having the same problem, but with Symfony 3.3, would you mind to share your solution?
