### ISSUE TITLE
[Idea] Container at hypervisor creation before deploy

### ISSUE THREAD

**Issue by razseo** [deployphp/deployer#1407]
| Q                 | A
| ----------------- | ---
| Issue Type        | New idea
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Hello, at another project i works under integration with proxmox and LXC creation.
If it will be useful - i can create recipe for create virtual machine, start up some installation staff and deploy after it. For example it can be used for scale project with single code base.

**Comment by antonmedv** [comment]
@razseo what's be awesome! Maybe lets start some new repo under deployer organization?

**Comment by razseo** [comment]
As you wish. As i read in issues - somebody wants to create UI for deploy. Any progress?

**Comment by antonmedv** [comment]
I'm working on UI right now.

**Comment by razseo** [comment]
LXC container management tool based on ProxMox VE under development :)
