### ISSUE TITLE
Running tasks on certain roles

### ISSUE THREAD

**Issue by chrisramakers** [deployphp/deployer#1409]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.3
| Local Machine OS  | OSX
| Remote Machine OS | CentOS

### Description 
I'm trying to figure out how to handle the following scenario, it seem that it's not possible with Deployer right now due to how hosts are configured and how tasks are not possible to be limited to certain hosts.

### Scenario

I've got a webserver, a database server and a worker server. Deploying should go as follows

1. Stop all workers on the worker server 
2. Deploy code from git repo to our webserver
3. Run migration scripts on Database server
4. Start all workers on the worker server

The problem is right now i'm defining all 3 hosts in my hosts.yml file and I wanted to limit tasks to certain hosts. So for example have one deploy task that executes other tasks but on their respective machines.

Is this possible with Deployer and if so, how do you configure your tasks and hosts to limit certain tasks to execute on certain hosts? 

(eg: I only want to run the migration task on my database server, but at a specific point in my deploy process for the webserver, after updating my webserver dependencies but before updating the symlink of my ~/current folder)

**Comment by antonmedv** [comment]
Hi, what's certainly possible. Take a look at [roles](https://deployer.org/docs/tasks#by-roles).

Example with migration:
```php
host('db.domain.com')
    ->roles(['db']);

desc('Migrate database');
task('migrate', function () {
    ...
})->onRoles('db');
```

Then add task to your deploy flow:
```php
task('deploy', [
    ...
    'migrate',
    ...
]);
```

Think of task and hosts as matrix:

| task⤵ host → |Worker|Database|Webserver|
|---|---|---|---|
| stop worker | x | | |
| deploy from git | | | x |
| migrate db | | x | |
| start worker | x | | |
