### ISSUE TITLE
shell_exec('dep deploy') no execute when i use web client

### ISSUE THREAD

**Issue by veekend** [deployphp/deployer#1410]
a.php：
shell_exec('dep deploy');

b.php:
shell_exec('mkdir b');

my deploy's version is 6.0.3.

when i use php cli mode to execute command "php a.php", it works.
but when i want to use webhook to send a request to http://xxx.com/a.php
it doesn't work,
but when i send request to http://xxx.com/b.php,
it works,
the permissions of nginx and php-fpm's user is the same as snapshot
use linux centos 6.8

<img width="814" alt="2017-11-08 12 06 29" src="https://user-images.githubusercontent.com/11720015/32503664-6b28e856-c3a3-11e7-8abd-51351365ec09.png">
<img width="868" alt="2017-11-08 12 06 42" src="https://user-images.githubusercontent.com/11720015/32503683-7a0b336a-c3a3-11e7-9ad1-ad8abe6485c3.png">
<img width="211" alt="2017-11-08 12 06 56" src="https://user-images.githubusercontent.com/11720015/32503712-8cda63d0-c3a3-11e7-94aa-6e75b990369b.png">
<img width="441" alt="2017-11-08 12 10 48" src="https://user-images.githubusercontent.com/11720015/32503866-f412e09a-c3a3-11e7-9182-a95fb39f7f0f.png">

help me please

**Comment by razseo** [comment]
Try to use full path to dep.
exec which "dep" and copy full path and try again.

**Comment by veekend** [comment]
just nothing.
i edited a.php with full path like this:
shell_exec('/home/gosuncn/hook/dep deploy');
but it doesn't work also.

and i try to edit deploy.php to generate a task A
and then edited a.php：
shell_exec('/home/gosuncn/hook/dep A');
it doesn't work.

i find php-fpm's error.log and nginx's error.log,
and there are no errors in these logs.

Is deployer the problem？

**Comment by razseo** [comment]
Try php -f "/home/gosuncn/hook/deploy.php"

**Comment by veekend** [comment]
is not tried php -f  "/home/gosuncn/hook/a.php"？

if i try php -f "/home/gosuncn/hook/deploy.php",
output error:
PHP Warning:  require(recipe/yii2-app-advanced.php): failed to open stream: No such file or directory in /home/gosuncn/hook/deployer/deploy.php on line 4
PHP Fatal error:  require(): Failed opening required 'recipe/yii2-app-advanced.php' (include_path='.:/usr/local/php/lib/php') in /home/gosuncn/hook/deployer/deploy.php on line 4

and now 
a.php
shell_exec('/home/gosuncn/hook/dep deploy');
shell_exec('mkdir e');

b.php
shell_exec('php a.php');
shell_exec('mkdir d');

i send a request to b.php
it generates e and d directory
but dep not works.  = =||

**Comment by antonmedv** [comment]
Try this: php -r ‘/home/gosuncn/hook/dep’
