### ISSUE TITLE
Move or copy last release to a current dir instead make a symlink

### ISSUE THREAD

**Issue by nonDeath** [deployphp/deployer#1411]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | Current
| Local Machine OS  | Ubuntu 16.04 (LAMP)
| Remote Machine OS | CentOS (httpd instead apache2)

### Description 

I'm deploying my project on shared hosting, every thing its all right but, after deployment is success, the new version of the files isn't served by the web server, just i see the previous version, but checking the current symlink and the new files, they are deployed fine.

My problem is: may be that the symlink destination is being cached by the httpd demon (googleing it i follow this http://www.mikebrittain.com/blog/2009/05/12/case-against-using-symlinks-for-code-promotion/)? in this case need restart the httpd, but i can't.

My workaround is make a task thah move the current vesion to a current directory, without make a symlink. In this case, the question is: There is already a recipe to do it?

Is a good idea for this?

Thanks in advance!

**Comment by razseo** [comment]
Which hosting you use? Maybe it have some control panel for restart your vhost?

**Comment by antonmedv** [comment]
It is bad idea, but you can do it anyway with custom recipe. Or you can find how to clear cache or restart server.

**Comment by nonDeath** [comment]
May be restarting the vhost, but i don't direct access to do that. And is some extra administrative task to do, 
is supposed to minimize that kind of things.

**Comment by antonmedv** [comment]
Then write copy task instead of symlink task. It's easy:
```php
task('deploy:copy', 'cp -R {{release_path}} {{deploy_path}}/current');
```

**Comment by nonDeath** [comment]
I digging into the code and found this

```
<?php
/* (c) Anton Medvedev <anton@medv.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Deployer;
desc('Creating symlink to release');
task('deploy:symlink', function () {
    if (get('use_atomic_symlink')) {
        run("mv -T {{deploy_path}}/release {{deploy_path}}/current");
    } else {
        // Atomic symlink does not supported.
        // Will use simple≤ two steps switch.
        run("cd {{deploy_path}} && {{bin/symlink}} {{release_path}} current"); // Atomic override symlink.
        run("cd {{deploy_path}} && rm release"); // Remove release link.
    }
});
```

If you see if use_atomic_symlink is seted then, the release is moved to the current. My assumption is true?

**Comment by antonmedv** [comment]
`{{deploy_path}}/release` is also symlink.

**Comment by nonDeath** [comment]
Ok thanks!! I try do a copy task

**Comment by nonDeath** [comment]
Me again!

I think that is a not very good idea, because the task deploy:prepare verify the symlik existence, and if it found a directory throw an exception and stop the entire deployment process.

What I see that you try to do, is an atomic deploy, but: could I rewrite the deploy `task:prepare` to prevent that exception? checking for the directory instead use the readlink command.

 I know it's still a not so good idea, but I'm trying to find an alternative to restarting the httpd

**Comment by antonmedv** [comment]
>  alternative to restarting the httpd

Try to clear cache: https://deployer.org/recipes/cachetool

**Comment by nonDeath** [comment]
Thanks! i try whit this
