### ISSUE TITLE
Removing a task from a recipe ?

### ISSUE THREAD

**Issue by metfan** [deployphp/deployer#1415]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.x

### Description 
Hello, 
I'm setting deployement for a symfony project. This project only contains command line and is built using Flex. So I don't have web/ folder.
I'm using symfony3 recipe and I had an errror when trying to install assets, because I don't have web/ folder.

I found 2 ways to fix this, override task: deploy:assets to do nothing or task deploy skipping deploy:asset.

I'd like to know if there is a function to remove a task from a recipe.

I think it could be a good feature to have `remove('deploy:asset');`.
What do you think?

**Comment by antonmedv** [comment]
Or you can simple override deploy task. I think it is the best solution. Support for symfony flex will defenetly come in next deployer version.

**Comment by nvahalik** [comment]
Is there a way to do this per-host? e.g. can I define what deploy looks like for host A and B individually?

**Comment by antonmedv** [comment]
Yes, you can filter task and hosts:
```
task('...')
     ->onHosts(...)
```
See https://deployer.org/docs/tasks#by-hosts

**Comment by nvahalik** [comment]
Ah. I see—somehow I was using 4.x of deployer—not sure how that 
happened. A quick update fixed my issue.
