### ISSUE TITLE
Same IP but different ports

### ISSUE THREAD

**Issue by superbot-qumo** [deployphp/deployer#1418]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.3
| Local Machine OS  | Windows 7
| Remote Machine OS | Ubuntu

Hello, Anton. 

I need to deploy to several VMs running on same IP but different ports, say

1.1.1.1:2222, 1.1.1.1:2223, 1.1.1.1:2224

If I use
  host('1.1.1.1') -> port(2222) ...
  host('1.1.1.1') -> port(2223) ...
  host('1.1.1.1') -> port(2224) ...

then it will deploy only once (per IP).

What should I do? I wonder if there is some config for that?

**Comment by antonmedv** [comment]
host('1.1.1.1/2222') -> port(2222) ...
host('1.1.1.1/2223') -> port(2223) ...
host('1.1.1.1/2224') -> port(2224) ...

**Comment by superbot-qumo** [comment]
host('1.1.1.1/222x')
              ->user('user')
              ->port(222x)
              ->set('branch', 'dev')
              ->identityFile('~/.ssh/id_rsa')
              ->set('deploy_path', '{{application}}')
              ->set('repository', 'ssh://user@ip:port/hub.git')
              ->forwardAgent(true)
...
Still have 1 output string per IP:
  remote: ✈︎ Deploying  dev on 1.1.1.1
  remote: ✈︎ Deploying dev on 2.2.2.2

**Comment by antonmedv** [comment]
host('a')  -> hostname('1.1.1.1') -> port(2222) ...
host('b') -> hostname('1.1.1.1') -> port(2223) ...
host('c') -> hostname('1.1.1.1') -> port(2224) ...

**Comment by superbot-qumo** [comment]
The problem was due to incorrect rights to the repository. Thank you.
