### ISSUE TITLE
task(...)->once() doesn't work on a parallel deployment

### ISSUE THREAD

**Issue by hyde1** [deployphp/deployer#1419]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | Deployer 6.0.3
| Local Machine OS  | Ubuntu 16.04.3 LTS
| Remote Machine OS | Ubuntu 16.04.3 LTS

### Description 
Hi,

It seams that `task(...)->once()` doesn't work when I used with the `--parallel` flag

### Steps to reproduce

Create a simple recipe with a "once" task like:
```
task('deploy:migratedb', function() {
	run('cd {{release_path}} && php migrate.php');
})->once();
```
Deploy on 2 hosts with the `--parallel` flag and the task is executed twice

### Output log
```
$ dep deploy production --parallel -vvv
➤ Executing task deploy:migratedb
[host1] > cd /var/www/application/releases/76 && php migrate.php
[host2] > cd /var/www/application/releases/76 && php migrate.php
[host1] < Migrated 0 migrations in 0
• done on [host1]
[host1] < Migrated 0 migrations in 0
• done on [host2]
✔ Ok [963ms]
```

Is seams that the task is flagged to "hasRun" at the end of it's execution, so in a parallel deployment the task is executed on every host whereas it works fin on a simple deployment.

Thanks for your help

**Comment by antonmedv** [comment]
Yes, it's looks like a bug. Try to fix it on weekends.

**Comment by mikkelle** [comment]
Hi,
When this bug will be fixed - I need it so much?:)

Thanks

**Comment by staabm** [comment]
feel free to provide a PR.

**Comment by ged15** [comment]
Hello!

Any plans on getting this fixed?

**Comment by antonmedv** [comment]
Does any body wants to fix it?

**Comment by antonmedv** [comment]
Everything working in v7). Added test for once().

**Comment by kanevbg** [comment]
Can this be merged to v6?

**Comment by antonmedv** [comment]
Sorry but no. This too much work.
