### ISSUE TITLE
Local task getting wrong parameter

### ISSUE THREAD

**Issue by jackd248** [deployphp/deployer#1421]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.3
| Local Machine OS  | OSX
| Remote Machine OS | N/A

I'm using a task to clone the git repository locally. 
```php
desc('Clone code locally');
task('deploy:prepare_code', function() {
    $repository = trim(get('repository'));
    $branch = get('branch');
    $git = get('bin/git');

    $at = '';
    if (!empty($branch)) {
        $at = "-b $branch";
    }

    // If option `tag` is set
    if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
        if (!empty($tag)) {
            $at = "-b $tag";
        }
    }
    ...
    run("$git clone $at -q $repository _{{application}}");
})->local();
```

The problem for me is that I got the wrong branch parameter. I'm trying to fetch the _dev_ branch, but I get the _master_ branch when running the `dep deploy develop`. It's interesting, because the **deploy:info** task is showing the correct branch. 

```
host-name:
  stage: develop
  ...
  branch: dev
```

I tried to rewrite the task to use the `runLocally` command and don't run the whole task local. This works for me so far. 

Do you have any idea, why I didn't get the correct parameter?

**Comment by antonmedv** [comment]
Yes, I know. This is common pitfall. Will be solved in next version. And for now, please show we your full setup. 

I think problem with choosing server and branch.

**Comment by antonmedv** [comment]
|Default localhost for `local()`|host-name (stage: develop)|prod-host (stage: prod)|
|---|---|---|
|branch: unset(master)|branch: dev|branch: prod|
|Run task deploy:prepare_code (which branch? master)|---|---|
|---|Run task deploy (dev)|Run task deploy (prod)|

**Comment by jackd248** [comment]
The task ``deploy:prepare_code`` runs after the info task. The task ``deploy:update_code`` copies the code to the target server. I got several servers in the _hosts.yml_:
````
internal-dev-host
  stage: dev
  branch: dev
  ...
dev-host
  stage: develop
  branch: dev
  ...
test-host
  stage: test
  branch: test
  ...
production-host
  stage: production
  branch: master
  ...
````
What else do you need?

**Comment by antonmedv** [comment]
As I said try to use same host info for building , try with runLocally.

**Comment by fnagel** [comment]
Maybe related to #1387

**Comment by antonmedv** [comment]
Yes, related. Now working on this to fix. :)

**Comment by fnagel** [comment]
Any news on this?

**Comment by antonmedv** [comment]
Nope, sorry. Haven't time for this bug.

**Comment by antonmedv** [comment]
Fixed in master. Please verify.

**Comment by mbrodala** [comment]
@antonmedv Can you link the commit/PR which fixed this?

**Comment by antonmedv** [comment]
This fix was squashed with other in master branch. Please, take a look it 👀 
If it now fixed feel free to open new issue.

**Comment by antonmedv** [comment]
@mbrodala it finally got fixed. See https://github.com/deployphp/deployer/pull/2457
