### ISSUE TITLE
rsync should sync to copy of last release dir 

### ISSUE THREAD

**Issue by yehosef** [deployphp/deployer#1422]
If I am doing an upload/rsync - it creates a new directory in the releases dir and then starts an rsync to the empty dir.  It seems it would be better to copy the last release dir to the new one, and do an rsync to that.  Then you are only updating the files that changed, which more often than not is a small set.

**Comment by antonmedv** [comment]
Use copy_dir param or create task for the it: cp -R {{previos_release}} release

**Comment by yehosef** [comment]
this should happen just before the upload?

I need the curly brackets on both like this?  (I'm new to deployer..)
`cp -R {{previous_release}} {{release}}`

**Comment by antonmedv** [comment]
Yes, like this

**Comment by yehosef** [comment]
It was supposed to be like your first version 
`cp -R {{previos_release}} release` because the `release` is the dirname - not a config option.

**Comment by antonmedv** [comment]
Try release-path
