### ISSUE TITLE
Update application

### ISSUE THREAD

**Issue by clieee** [deployphp/deployer#1423]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | Latest
| Local Machine OS  | Mac OS X
| Remote Machine OS | Ubuntu

### Description 
Is it possible to update an existing release, without doing a new deploy?

**Comment by antonmedv** [comment]
How?) what are you trying to do?

**Comment by clieee** [comment]
Lets say I have just done a really small adjustment, for example changing a text color, is it then possible to make an update on a current release instead of making a completely new release?

**Comment by antonmedv** [comment]
No, you need to perform full release. Note, what deploy:update_code very optimized to fetch only new data from git remote.

**Comment by clieee** [comment]
Okay, but if I make a new release, then I guess it will clone the whole repository? So, for my small adjustment like a text color means the whole repository will be fetched, right?

**Comment by antonmedv** [comment]
No, it uses shallow copy and previous release file used , only text color will be fetched

**Comment by clieee** [comment]
Thank you for clarifying!

**Comment by antonmedv** [comment]
But you can create task which will be performing a git patch of current release.

**Comment by clieee** [comment]
Okay, how would that look?

**Comment by antonmedv** [comment]
1. create patch `git format-patch master --stdout > mypatch.patch`
2. upload to server
3. apply patch

**Comment by vkryukov76** [comment]
If you don't need any other deployment steps (composer, npm, etc.) you could try this simple task.

```php
task('git:pull', function () {
    cd('{{release_path}}');
    $output = run('{{bin/git}} pull');
    writeln('<info>' . $output . '</info>');
});

```

**Comment by clieee** [comment]
thank you, will try that too
