### ISSUE TITLE
Create laravel deploy

### ISSUE THREAD

**Issue by hoangnguyenba** [deployphp/deployer#1425]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.3
| Local Machine OS  | MacOS
| Remote Machine OS | centos-release-7-3.1611.el7.centos.x86_64

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
1. Create a laravel deploy
2. Config host
// Hosts
host('52.198.155.95')
    ->stage('test')
    ->set('deploy_path', '~/{{application}}')
    ->set('branch', 'develop')
    ->user('tavidev')
    ->port(22)
    ->identityFile('~/.ssh/TaviBSVServer')
    ->forwardAgent(true)
    ->multiplexing(true)
    ->addSshOption('UserKnownHostsFile', '/dev/null')
    ->addSshOption('StrictHostKeyChecking', 'no');

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', 'TaviWeb');

// Project repository
set('repository', 'bsv@bsv.git.backlog.jp:/TAVI/web.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);
set('allow_anonymous_stats', false);

// Hosts
host('52.198.155.95')
    ->stage('test')
    ->set('deploy_path', '~/{{application}}')
    ->set('branch', 'develop')
    ->user('tavidev')
    ->port(22)
    ->identityFile('~/.ssh/TaviBSVServer')
    ->forwardAgent(true)
    ->multiplexing(true)
    ->addSshOption('UserKnownHostsFile', '/dev/null')
    ->addSshOption('StrictHostKeyChecking', 'no');
    
// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'artisan:migrate');


```

### Output log
*With enabled option for verbose output `-vvv`.*
✈︎ Deploying develop on 52.198.155.95
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
Warning: Permanently added '52.198.155.95' (ECDSA) to the list of known hosts.
Connection to 52.198.155.95 closed.
✔ Ok
✔ Executing task deploy:shared
✔ Executing task deploy:vendors
➤ Executing task deploy:writable
✔ Executing task deploy:failed
✔ Executing task deploy:unlock

  [Deployer\Exception\RuntimeException]
  The command "cd ~/TaviWeb/releases/1 && (setfacl -RL -m u:"gitlab-+":rwX -m u:`whoami`:rwX bootstrap/cache)" failed.
  Exit Code: 2 (Misuse of shell builtins)
  Host Name: 52.198.155.95
  ================
  setfacl: Option -m: Invalid argument near character 3

**Comment by antonmedv** [comment]
setfacl version?

**Comment by hoangnguyenba** [comment]
2.2.51-12.el7

**Comment by antonmedv** [comment]
Try run this command manually on server

**Comment by hoangnguyenba** [comment]
Yeah, I did. Same result.

**Comment by hoangnguyenba** [comment]
I fixed problem by run this on my server:
echo  `ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`

**Comment by antonmedv** [comment]
Did you solve this issue?

**Comment by hoangnguyenba** [comment]
I change from:
setfacl -RL -m u:"gitlab-+":rwX -m u:`whoami`:rwX bootstrap/cache
to
setfacl -RL -m u:`whoami`:rwX bootstrap/cache
Then it's working.

My server does not have user "gitlab-+", right ?

**Comment by antonmedv** [comment]
Yes, probably it's http user detection error. Try set `http_user` your self

**Comment by hoangnguyenba** [comment]
Yes, working now :)

added this: ->set('http_user', 'tavidev')
