### ISSUE TITLE
Deployment on a server without Node.js

### ISSUE THREAD

**Issue by KriBetko** [deployphp/deployer#1428]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | ^6.0
| Local Machine OS  | Unix-like with Node.js
| Remote Machine OS | Unix-like without Node.js

### Question 
What is the way to deploy a webpack bundle assembled to a build machine with Node.js on a server without Node.js?

**Comment by antonmedv** [comment]
Use local build:
https://deployer.org/docs/advanced/deploy-strategies

**Comment by KriBetko** [comment]
Thank you!
This works for me:
```
task('build', function () {
    run('cd {{release_path}} && build');
});

task('build', function () {
    run('npm install');
    run('npm run build');
})->local();

after('deploy:symlink', 'upload');

task('upload', function () {
    upload(__DIR__ . '/web/build', '{{release_path}}/web/build');
});
```
