### ISSUE TITLE
Add support for Symfony 4.0

### ISSUE THREAD

**Issue by tehplague** [deployphp/deployer#1437]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Now that Symfony 4.0 is released, let's try to make Deployer compatible with its Console component.

**Comment by Cryde** [comment]
We could already do some research like : 

```
// Clear paths
set('clear_paths', ['web/app_*.php', 'web/config.php']); // <= no needed anymore

// Symfony shared files
set('shared_files', ['app/config/parameters.yml']); // <= no needed anymore / .env now !

// Assets
set('assets', ['web/css', 'web/images', 'web/js']); // <= old
set('assets', ['public/css', 'public/images', 'public/js']); // <= new 
```

For me the https://github.com/deployphp/deployer/blob/master/recipe/symfony3.php is ok ! :)
Some stuff to adjust about symfony env variable I guess in : https://github.com/deployphp/deployer/blob/master/recipe/symfony.php

**Comment by antonmedv** [comment]
#1420

**Comment by zorn-v** [comment]
@Cryde 
`deploy:assets:install` task not compatible with flex, as here https://github.com/deployphp/deployer/blob/6708d2640f9d8b68b539b3929d9b09cf0d4fec1e/recipe/symfony.php#L95 `web` is hardcoded

**Comment by erik-ropez** [comment]
Larave 5.6 is out and it depends on Symfony 4.

**Comment by solofeed** [comment]
We have the problem with Symfony 4 support.

**Comment by antonmedv** [comment]
Done! 🎉

**Comment by Shaked** [comment]
@antonmedv is this really done? 

AFAIK symfony now uses `public/` instead of `web/` and `app/console` is `bin/console`.

**Comment by zorn-v** [comment]
Use `require/symfony4.php`
