### ISSUE TITLE
New proposal for recipes loading

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1438]
As an alternative:

```php
\Deployer\Deployer\Common::register();
\Deployer\Recipes\Slack::register();
\ThirdParty\Recipes\Stuff::register();
```

**Comment by antonmedv** [comment]
OR stay with same old way:
```php
require 'common.php';
require 'slack.php';
require 'third-party.php';
```

**Comment by barryvdh** [comment]
Both would be fine if it's possible to load them without requiring them with composer. Is that already possible? Eg. slack, using just the binary install?

**Comment by antonmedv** [comment]
Not in master, I'm working on it in next v7.
