### ISSUE TITLE
New stage() func proposal

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1441]
What about adding a new function for manipulating stages?

```php
stage('production', function () {
    set('deploy_path', '...');
    host('domain.com')
        ->roles(['app']);
});
```

```php
stage('staging', function () {
    set('deploy_path', '...');
    inventory('./inventory/staging.yml');
});
```

**Comment by mathieuimbert** [comment]
I think it's a great idea. It actually makes more sense to make the stage / environment a root element. You could do many things such as:

- associate a specific branch to a stage
- add custom tasks for a stage (deployment notification only for production for example)
- have different variables set for each environment
- a lot more I cannot think of right now

It is how [PM2 Deployment](http://pm2.keymetrics.io/docs/usage/deployment/#getting-started) works, and I believe it has only advantages. It is a great feature! Let me know if you need any help with implementation or tests, I'll be happy to help.

**Comment by antonmedv** [comment]
What about having separate file for each stage?

```
| deploy.php
|- app
    |- deploy
        |- staging.php
        |- production.php
```

#### deploy.php
```php
set('stages', __DIR__ . '/app/deploy');
set('default_stage', 'staging');
```

#### production.php
```php
set('branch', 'master');
host('production.com');
```

**Comment by mathieuimbert** [comment]
Personally I like to have all my deployment configuration in a single file. Since I have other config files (ex: phpunit, CI script, Dockerfile, Composer, gulp, npm, ...), I find it easier to have one file per tool. But my deployment scripts are usually quite simple, maybe this would be a good idea for projects with more complex scripts?

**Comment by antonmedv** [comment]
Do you like it?

```php
stage('production', function () {
    set('branch', 'production');
    host('ec2-32-47-157-121.eu-west-1.compute.amazonaws.com');
    host('ec2-52-37-137-111.ap-southeast-1.compute.amazonaws.com');
});

stage('staging', function () {
    set('branch', 'development');
    host('beta.project.com');
});
```

**Comment by staabm** [comment]
I would prefer something like

```
stage('production')
    ->set('branch', 'production')
    ->host('ec2-32-47-157-121.eu-west-1.compute.amazonaws.com')
    ->host('ec2-52-37-137-111.ap-southeast-1.compute.amazonaws.com');
});

stage('development')
    ->set('branch', 'development')
    ->host('beta.project.com');
});
```

to have it like the `host()` api which is also IDE friendly and allows autocompletion etc.

**Comment by antonmedv** [comment]
@staabm okay, how to do it:
```haskell
stage('production', function () {
    set('branch', 'production');
    host('ec2-32-47-157-121.eu-west-1.compute.amazonaws.com')
        ->set('param', 'value');
    host('ec2-52-37-137-111.ap-southeast-1.compute.amazonaws.com');
});
```

**Comment by staabm** [comment]
ok, I see.

**Comment by antonmedv** [comment]
I decided to remove the stage in the flavor of roles which eventually the same, but more functional. See #1904 for progress.
