### ISSUE TITLE
DX: implicit api makes it really hard to navigate codebase/recipies

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1444]
let me describe my feelings which I had today when working a few ours with deployer.

I read some docs, some 3rd party and also builtin recipies. when trying to understand the code I need to search the deployer codebase for keywords/symbols/functions like `deploy_path`, `upload`, `deploy:prepare` etc.

my IDE is not able to help me in any way, because of this "string-based api".

I would love a recipe (or api style) which allows me to use the regular IDE features, which work on most php codebases, like "navigate to function", "show inline phpdocs of func declaration" or similar.

because of the mentioned problems the library is rather hard to use DX wise.

please dont be angry, the lib itself is still a very usefull tool, but IMO there is some room for improvements as far as developer experience is a concern.

thank you

**Comment by antonmedv** [comment]
Agree. But take a look at Symfony which also has a lot of strings in DI and services. But has a great plugins for IDE. 
We can do same thing and create same plugin for IDE. 

Also I'm going to improve DX with helpful error messages, better recipe validation and better recipes importing and location.

**Comment by staabm** [comment]
I am fine with whatever way we can implement as long as DX inprove with it
