### ISSUE TITLE
commandSupportsOption: `[[: not found`

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1445]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.3
| Local Machine OS  | Ubuntu16 lts
| Remote Machine OS | N/A

### Description 
when running my recipe I can see a `[[: not found` error, which is triggered by a call to `commandSupportsOption()`. I guess there is some kind of incompatibility with bash or similar, which makes this simple command trigger this error

### Output log
```sh
[localhost] > cd /cluster/www/www/www/xxx_relaunch/.build && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[localhost] < sh: 1: [[: not found
```

### Env
```
php -v
PHP 7.0.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 29 2017 09:51:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.26-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.0~linux-x64-non_zts70, https://blackfire.io, by SensioLabs
```

**Comment by antonmedv** [comment]
Yes, maybe we should use `test` here as well.

**Comment by JavierPons** [comment]
Hi there!
I would like to contribute in this project. What I can do? It will be my first contributing place.

**Comment by antonmedv** [comment]
Yes we need! You can start fron any issue with label good for beginners

**Comment by JavierPons** [comment]
@antonmedv thanks. I going to looking for something. Do you recommend any special?

**Comment by JavierPons** [comment]
@antonmedv I have notice that good for beginners there are quite old issues. (correct me if I'm wrong). How can I go forward?

**Comment by staabm** [comment]
You can start with this issue. Provide a PR and note the change in the Changelog

**Comment by JavierPons** [comment]
@staabm hi! do you mean with PR (private repository) Im quite new in this .... :p Can you explain if I'm wrong?

**Comment by JavierPons** [comment]
@staabm ok I will try

**Comment by staabm** [comment]
PR = Pull Request. Github itself provides some great tutorials on howto provide a patch toma codebase, see https://help.github.com/

**Comment by staabm** [comment]
@antonmedv do you have a suggestion how this problem needs to be fixed?

**Comment by antonmedv** [comment]
Use `[` instead of `[[`. 

As `[` - POSIX, `[[`  - bash only (but much better and easier to use)

**Comment by antonmedv** [comment]
Actually deployer really relies on bash. So `[[` should be available.
