### ISSUE TITLE
Support .env files (dotenv)

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1446]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3
| Local Machine OS  | Ubuntu16 lts
| Remote Machine OS | Ubuntu16 lts

### Description 
recipes tend to duplicate config settings which are sometimes already defined elsewhere in the project.
this might be e.g. a url to the repository, usernames, passwords etc.

there is some kind of standard which solves such problems. usually you use a dotenv file, 
see e.g. https://symfony.com/components/Dotenv

that way you have a config file in a format consumable by the application itself, its clitools or other related parties. the files are technologie and programming language/framework agnostic so information placed there can be used in a lot of places, without duplication.

would be great to get some kind of out-of-the-box support for dotenv files.

**Comment by Blizzke** [comment]
If all you want is the values from your `.env` available in templates (eg `{{APP_NAME]}`) etc, that is something you can solve quickly in about 3 lines of text.

First of all: add Symfony's dotenv as a requirement: 
`composer require symfony/dotenv:"^3"` (Deployer is still on 3.x so I'll use that)

When that is done, add these 2 somewhere in your deploy script (I usually do it right after the namespace):
```php
(new \Symfony\Component\Dotenv\Dotenv())->load('.env');
array_map(function ($var) { set($var, getenv($var)); }, explode(',', $_SERVER['SYMFONY_DOTENV_VARS']));
```
That's it. All variables from your `.env` are now available as Deployer variables.

**Comment by leeuwd** [comment]
For Laravel:

`composer require vlucas/phpdotenv`

And put this in the top of your `deploy.php`:

```php
// Load .env
with(new \Dotenv\Dotenv(__DIR__))->load();
```

**Comment by Blizzke** [comment]
If you are running deployer from within a laravel project, you don't need to run the require, it's there already.  

I did realise, hence the second part of my message, during a deploy you'd probably want the settings from the remote server, not the local one. Unfortunately phpdotenv doesn't seem to support loading from a string, it needs a file as source. So even for a laraval project you'd have to include Symfony's dotenv if you want to load from remote.

**Comment by cilefen** [comment]
Here is a simple way, building on what @Blizzke wrote above (which is good stuff, thank you!):

```php
task('deploy:dotenv', function() {
    $environment = run('cat {{deploy_path}}/shared/.env');
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $dotenv->populate($dotenv->parse($environment));
})->desc('Load DotEnv values');
after('deploy:shared', 'deploy:dotenv');
```

**Comment by cilefen** [comment]
Also, to anyone using Symfony with DotEnv, it will pay to scrutinize the bin/console command:

```php
if (!isset($_SERVER['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
    }
    (new Dotenv())->load(__DIR__.'/../.env');
}
```

Remove the outer conditional if you plan on using DotEnv in production while calling bin/console. With that done, what I wrote in the comment above is unnecessary.

**Comment by antonmedv** [comment]
Yes, actually this is correct solution.

**Comment by staabm** [comment]
Great to see this examples. I guess we could close this issue and the people who need .env can use those snippets posted above.

@antonmedv do you agree that we _dont_ need a more deployer-core like approach for this?

**Comment by antonmedv** [comment]
What is deployer-core like approach ?

**Comment by cafferata** [comment]
I think @staabm mean including the above code snippet as a standard task in the deployer codebase. As a result, other people do not have to duplicate this task code on the various projects.

**Comment by antonmedv** [comment]
This can be done. Can anyone create PR?

**Comment by inverse** [comment]
Thanks @Blizzke + @cilefen. Reworked what you guys did to load the environment for deployment and came up with this.

```
task('load:env-vars', function() {
    $environment = run('cat {{deploy_path}}/.env');
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $data = $dotenv->parse($environment);
    set('env', $data);
});
```
Which hooks in before deploy and post rollback.

**Comment by chapterjason** [comment]
With Symfony recipe the .env is always empty and not working like expected.

I'm expecting something like this
```php
$new_variables = run('cat {{release_path}}/.env.dist');
$old_enviroment = run('cat {{deploy_path}}/shared/.env');
array_merge($dotenv->parse($new_variables), $dotenv->parse($old_enviroment), get('env'));
```

And then the output will be save to `{{deploy_path}}/shared/.env` to take effect of the changes from host.

**Comment by cilefen** [comment]
@chapterjason That is an interesting idea. I think that this issue is focused on getting .env files parsed and read in the first place. What you are proposing could be a good follow-up. As far as I know Symfony via DotEnv outside of the Deployer context no longer updates the .env file when .env.dist changes so this would be an added feature.

**Comment by chapterjason** [comment]
Yeah thats are right, that was a good side-effect of my idea. 

The env variables are changing in my workflow by host, so that I can specify them there an they will get overriden and taken care of old and new env.

But what is with a rollback? Then the .env, shouldn't be shared, cause of different used `.env`, some of them could be someday be deprecated, get noticed by the system and it will throw everytime a warning.

With a new release, it should take work *like* this.
```
array_merge("{{previous_release}}/.env.dist", "{{current_release}}/.env.dist", "{{previous_release}}/.env", "get('env')");
````

**Comment by simioluwatomi** [comment]
> For others struggling with this:
> 
> For Laravel:
> 
> `composer require vlucas/phpdotenv`
> 
> And put this in the top of your `deploy.php`:
> 
> ```
> // Load .env
> with(new \Dotenv\Dotenv(__DIR__))->load();
> ```

This fails in new ```Dotenv``` versions. This works for me though

```
namespace Deployer;

\Dotenv\Dotenv::create(__DIR__)->load();
```

**Comment by ryancwalsh** [comment]
I had to run this instead: `require __DIR__ . '/bootstrap/autoload.php'; \Dotenv\Dotenv::create(__DIR__)->load();`

**Comment by bretvanhorn** [comment]
> For others struggling with this:
> 
> For Laravel:
> 
> `composer require vlucas/phpdotenv`
> 
> And put this in the top of your `deploy.php`:
> 
> ```
> // Load .env
> with(new \Dotenv\Dotenv(__DIR__))->load();
> ```

This worked well for me—note that you simply use the env('VAR_NAME') function to get your variable.

**Comment by ludo237** [comment]
Heads up for Laravel users.

If you are on Laravel 7.x you can't create a new instance of Dotenv like 

> > For others struggling with this:
> > For Laravel:
> > `composer require vlucas/phpdotenv`
> > And put this in the top of your `deploy.php`:
> > ```
> > // Load .env
> > with(new \Dotenv\Dotenv(__DIR__))->load();
> > ```
> 
> This fails in new `Dotenv` versions. This works for me though
> 
> ```
> namespace Deployer;
> 
> \Dotenv\Dotenv::create(__DIR__)->load();
> ```

I suggest `createImmutable` instead. Both work fine tho

**Comment by antonmedv** [comment]
Support added in 36596a618e73af764cbc93fa913a960115bac6c3
 ```php
 set('dotenv', '{{current_path}}/.env');
 ```

**Comment by loevgaard** [comment]
For people finding this on Google and wanted a solution to update your environment variables on your remote server I created a library for that: https://github.com/Setono/deployer-dotenv

**Comment by vuletuanbt** [comment]
> Support added in [36596a6](https://github.com/deployphp/deployer/commit/36596a618e73af764cbc93fa913a960115bac6c3)
> 
> ```
> set('dotenv', '{{current_path}}/.env');
> ```

So, how can we get env on that? I didn't find the answer on the docs

**Comment by antonmedv** [comment]
Yes

**Comment by vuletuanbt** [comment]
> Yes

I mean how could we get env value?
```php
DEPLOYER_HOSTNAME=myhost
```
how can i get `myhost`

**Comment by Schrank** [comment]
Sitting in s car, so didn’t check code, but I would guess `env('DEPLOYER_HOSTNAME')`

**Comment by vuletuanbt** [comment]
> Sitting in s car, so didn’t check code, but I would guess `env('DEPLOYER_HOSTNAME')`

I tried on my laravel project but there's no hope 
```php
set('dotenv', '{{current_path}}/.env');

$hostName = env('DEPLOYER_HOSTNAME');
$hostName = get('DEPLOYER_HOSTNAME');
$hostName = getenv('DEPLOYER_HOSTNAME');
```
Then I try and it works
```php
use Dotenv\Dotenv;
with(Dotenv::createMutable(__DIR__)->load());
// ....
$hostName = env('DEPLOYER_HOSTNAME');
```

**Comment by cerw** [comment]
> ```
> env
> ```

```

  Call to undefined function Deployer\with()
```

What version of deployer?

**Comment by pafernandez-oesia** [comment]
If you want to load all environment vars from the shell into PHP, including `.env` ones, you can use this recipe:

```
task('dotenv:load', function () {
    $shellEnvs = run('set');
    $shellEnvs = (array) preg_split("/(\n|\r\n|\r)/", $shellEnvs);
    $shellEnvs = array_filter(array_map('trim', $shellEnvs));

    foreach ($shellEnvs as $env) {
        list($key, $value) = explode('=', $env, 2);

        $_ENV[$key] = $value;
    }
});
```

Usage:
```
set('dotenv', '{{deploy_path}}/.env');

task('test', function () {
    invoke('dotenv:load');
    info($_ENV['APP_NAME']);
});
```
