### ISSUE TITLE
DX: us long option names

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1447]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
when reading the codebase there are a lot of bash commands which use short option names, e.g. `mkdir -p` or `rsync -av` or similar. 

using long option names for this scripts would greatly improve the developer experience.
instead of `mkdir -p` we should e.g. write `mkdir --parents`.

short option names are mostly intended for typing to save keystrokes.
when reading bash sources the long option names help in understanding whats going on.

changes welcome?

**Comment by antonmedv** [comment]
Agree. But we need to be really carefully, as different operation systems may have different long names and same short. 
Also for well known commands as `mkdir -p` I think to better stay with sort name, as more developers familiar with it. 
So it's sense of meaning.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
