### ISSUE TITLE
Better Error Feedback

### ISSUE THREAD

**Issue by AlexStansfield** [deployphp/deployer#145]
Been trying to run deployment scripts on a new host. Some failed at installing vendors and some at dumping assets. The errors returned didn't give me any help. 

It wasn't until I sshed in and trying to install manually that I found one of the problems was because I was missing php-intl (composer told me but this message wasn't relayed back through deployer) and the other was php5-apcu (I got the message when doing it manually, but it wasn't relayed through deployer).

I was thinking that when deploying to a brand new host then missing libraries could be a common issue. So perhaps there is a way to improve the feedback when these processes fail.

**Comment by elfet** [comment]
Yes, this is good enhancement. And i already implemented it in Deployer 3. Now hard working on release of it.

**Comment by AlexStansfield** [comment]
Ahh great. Will make a note of the changes in V3 so I can mention them at the end of my talk. At the moment I'm not sure how long I have, it's meant to be a 3 min jam session but so far not many have signed up so I might beg for more time.

**Comment by elfet** [comment]
Good luck! :dart:

**Comment by elfet** [comment]
Done.
