### ISSUE TITLE
Document root does not point to the current release 

### ISSUE THREAD

**Issue by nazmulislam** [deployphp/deployer#1451]
| Q                 
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0
| Local Machine OS  | Mac OSX
| Remote Machine OS | Vagrant Unbuntu

### Description 

I am trying deploying to a vagrant machine, the deployment appears to working correctly, all folders are created and git repo is pulled correctly.
However, the symlink does not appear to be pointing to the current folder it displays file not found and it trying to load the files from the document root /var/www/html. The deploy path is /var/www
I can confirm that there is no error messages in deploy.

I am relative new to the world of devOps and currently going through a steep learning curve and i will be grateful if someone could point me in the direction as to what i am doing wrong.

### Content of `deploy.php`
set('default_stage', 'staging');
set('deploy_path', '/var/www');
set('http_user', 'www-data');

host( '192.168.10.5' )
    ->user( 'vagrant', 'vagrant' )
    ->stage('staging');
    

// Tasks

desc('Deploy your project');
task('deploy:staging', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

**Comment by antonmedv** [comment]
Take a look at deploy_path
What files created there?

**Comment by nazmulislam** [comment]
so the following folders and files are created
current
.dep
releases
       - 1
             - index.php
shared

**Comment by nazmulislam** [comment]
I have made some progress, after googling around. 
in my 000-default file i have added now set the document root /var/www/current, previously this was set to /var/www/html
`DocumentRoot /var/www/current
        <Directory />
            Options FollowSymLinks
            AllowOverride All
        </Directory>

        <Directory /var/www/current>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>`

is this correct because now the the webserver is pointing to the current folder and is now display the file from the current directory.

However, i then made a change to the file committed and then run deploy:staging, the release 2 folder is created and the current folder shows the correct file, the server is referring to release 1 files and not current.

**Comment by antonmedv** [comment]
Reastart server, or clear opcache.

**Comment by nazmulislam** [comment]
is there a way to set sudo for mkdir .dep in deployer

**Comment by antonmedv** [comment]
No, use proper permissions on dirs.

**Comment by nazmulislam** [comment]
I have managed to get it all working. I test it on digital ocean machine, and the were no issues of permissions, its on only on vagrant machine which in any case is my test environment, so i can live with that. 

Now i need to start exploring in how to use deployer with my custom tasks etc.

Thanks for you help.
