### ISSUE TITLE
Set custom timeouts for Server::run()

### ISSUE THREAD

**Issue by mabrahamde** [deployphp/deployer#146]
Deploying using `Deployer\Server\Local` Server i am running into a timeout.

Tasks like composer install can take really long. However in `Symfony\Component\Process` the method `run()` uses a default timeout of 60 seconds. Sometimes 60s is too short. I suggest two solutions for this:

a) set higher default values `Deployer\Server\Local`:

```
    const TIMEOUT = 300;
```

b) extend `Deployer\Server\ServerInterface` and add a new parameter to the `run()` method inside `functions.php`:

```
    public function run($command, $timeout = 60)
```

**Comment by elfet** [comment]
I think `a` is better.

**Comment by EkAndreas** [comment]
Please add this option for runLocally...

**Comment by maximTarleckiy** [comment]
If you want run deployment task for local server which already used run() function, turns out that you should change task to use runLocally('command...', 0) to disable timeout for command. Maybe make sense to set timeout option for particular server?

**Comment by peterjaap** [comment]
+1 to add custom timeouts to `run()` as well, just like `runLocally()`. We pretty often need to import database into our staging environment, which we control through Deployer.

**Comment by pluseg** [comment]
@elfet please stick it with https://github.com/deployphp/deployer/issues/924 (seems as full duplicate) and https://github.com/deployphp/deployer/pull/974.

**Comment by elfet** [comment]
Command (remote/locale) timeout refactoring is planned for v5. Have some ideas implement to.

**Comment by elfet** [comment]
Done in #1092
