### ISSUE TITLE
Proposal: parameter validator

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1460]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 7.x

### Description 
Add validator for parameters.

```php
set('shared_files')
    ->validate(function ($value) {
        return is_array($value);
    });

set('shared_files', 'string'); // throws error
add('shared_files', 'string'); // throws error
```

**Comment by staabm** [comment]
as described in https://github.com/deployphp/deployer/issues/1459#issuecomment-353001781, in case you add a more explicit api, you can just leaverage phps' builtin typehints and you are good to go.

no need to re-implement such types in the app-layer.

**Comment by antonmedv** [comment]
So what’s your proposal? How to do it? Please, show an example.

**Comment by staabm** [comment]
for the above mentioned case it would be

```
function set_shared_files(string $files) {
  // ....
}

set_shared_files("myvalue")
```

while activating php strict types.

**Comment by antonmedv** [comment]
What about it:
```php
use Deployer\Set as set;

set\shared_files('myvalue');
```

**Comment by staabm** [comment]
you can do this kind of "subnamespacing" but IMO the `\` is a lot harder to type then the `_` for functions you need a lot

**Comment by antonmedv** [comment]
But funcs will require a lot of `use` statements.

**Comment by staabm** [comment]
in case we put those funtions into the "Deployer" namespace, no `use` will be required.

**Comment by antonmedv** [comment]
But not all use `namespace Deployer`. Some use `use`.

**Comment by staabm** [comment]
this new functions we are going to introduce could still all live in the `Deployer` namespace, no?

**Comment by antonmedv** [comment]
I think no for first . It should be separate package first .
