### ISSUE TITLE
Support after/before/fail($it, callable);

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1475]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
with the current version I need to define a private task which then need to be wired with after/before/fail.
it would be easier if I could just register a callable, like already possible with `task()`, e.g.

```php
after('success', function() {
  $chatBot->msg('successfully deployed... yay');
});
fail('deploy', function() {
  $chatBot->msg('deploy task fu**ed up');
});
```

**Comment by antonmedv** [comment]
Added support in master!
