### ISSUE TITLE
anonymous usage stats

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1477]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
deployer per default sends anonymous usage statistics. such a feature should be opt-in and not enabled by default. I discovered it by accident...

In case this data is important for you/development of the tool and you need as much as possible of it, you should ask the user while installation or similar. just collecting the data and sending it away is very bad practice for privacy reasons.

I guess this kind of behaviour might even be considered illegal in the EU.

**Comment by antonmedv** [comment]
But we have opt-in. try run dep init - it will ask you about it.

**Comment by staabm** [comment]
I installed deployer and started with a recipe not created via `dep init`.
I was never asked this question and the data are still collected/send

**Comment by antonmedv** [comment]
Yes, it’s work only in interactive mode.

**Comment by staabm** [comment]
> Yes, it’s work only in interactive mode.

wdyt about changing the hardcoded default to be "disabled" (in case someone doesnt invoke `dep init`?)

**Comment by antonmedv** [comment]
Well, I thinking of creating separate config file for it, so you can disable it for all projects on machine.

File `~/.deployer/config.php` will be required in all dep runs.

```php
<?php
// config goes here
```

**Comment by staabm** [comment]
I dont think about my concrete problem, but about the general handling of tihs privacy problem.

I will disable it in my recipe for sure, but IMO enabling it by default (even in only some use-cases) is not a good idea.

feel free to ingore my opinion.

**Comment by dasuchin** [comment]
Is there no way to turn this off? I keep getting a 500 error at the end of my deploy now. 

`PHP Warning:  file_get_contents(https://deployer.org/api/stats): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error`
