### ISSUE TITLE
Submodule init problem

### ISSUE THREAD

**Issue by tomaj** [deployphp/deployer#148]
Hi

I have problem in task deploy:update_code when my repo is using some submodules.
Deploy skript is trying to run something like this:
```
cd /home/user/mytest && git clone --recursive -q git@bitbucket.org:owner/repo.git /home/user/mytest/releases/2015012324229
```
But it fails :-(
```
[RuntimeException]
  Cloning into 'htdocs/somefolder1'...
  Cloning into 'htdocs/somefolder2'...
  Cloning into 'htdocs/somefolder3'...
  Cloning into 'htdocs/somefolder4'...
```

I am using *php ssh2* lib. I have tried to debug this issue and it fails in ```vendor/elfet/php-ssh/src/Ssh/Exec.php:30``` when command returns something to output it will consider it as fail and. git command outputs information with "Cloning into" for submodules (event you pass -q variable). There is no permission problem, I can run command that I mentioned on the top and it runs ok (but output information about initialising submodules)

Anyone have any ideas how to fix this?

**Comment by elfet** [comment]
Please, run deploy with -vvv attr and show output.

**Comment by tomaj** [comment]
Here it is:

```
$php vendor/bin/dep deploy:update_code -vvv

Updating code
Run task deploy:update_code on server main
[mytest.sk] cd /home/forge/mytest && git clone --recursive -q git@bitbucket.org:owner/streamapp.git /home/forge/mytest/releases/2015012329915
Run task deploy:rollback on server main
Rolling back to previous release on server main
[mytest.sk] cd /home/forge/mytest && rm -rf /home/forge/mytest/releases/2015012329915
[mytest.sk] ::



  [RuntimeException]
  Cloning into 'htdocs/somefolder1'...
  Cloning into 'htdocs/somefolder2'...
  Cloning into 'htdocs/somefolder3'...
  Cloning into 'htdocs/somefolder4'...



Exception trace:
 () at /var/www/streamapp/htdocs/Nette/libs/vendor/elfet/php-ssh/src/Ssh/Exec.php:28
 Ssh\Exec->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/Server/Ssh2.php:94
 Deployer\Server\Ssh2->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/functions.php:115
 run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/recipe/common.php:64
 {closure}() at n/a:n/a
 call_user_func() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/Task/Runner.php:45
 Deployer\Task\Runner->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/Console/RunTaskCommand.php:168
 Deployer\Console\RunTaskCommand->runSeries() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/Console/RunTaskCommand.php:118
 Deployer\Console\RunTaskCommand->execute() at /var/www/streamapp/htdocs/Nette/libs/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/symfony/console/Symfony/Component/Console/Application.php:887
 Symfony\Component\Console\Application->doRunCommand() at /var/www/streamapp/htdocs/Nette/libs/vendor/symfony/console/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /var/www/streamapp/htdocs/Nette/libs/vendor/symfony/console/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/src/Deployer.php:114
 Deployer\Deployer->run() at /var/www/streamapp/htdocs/Nette/libs/vendor/deployer/deployer/bin/dep:52


deploy:update_code [--dry-run] [--server[="..."]] [stage]
```

I think it will always fail when you use git command with submodules, because he send output even if you use --quiet option.

**Comment by elfet** [comment]
Can you try to update recipe and run git clone task with `2>&1` at the end?

**Comment by tomaj** [comment]
Sorry for late answer. When I modified recipe/common.php

```
run("git clone --recursive -q $repository $releasePath 2>&1");
```

it is working.

**Comment by tomaj** [comment]
Right now i have few deployments with this change and it is looking stable for me. Shoud i create pull request for using it with default recipe?

**Comment by elfet** [comment]
Yes, please!

**Comment by itelmenko** [comment]
What about deployer v7 ? I don't see -- recursive in this version

**Comment by itelmenko** [comment]
I have add own task as temporary solution

```
desc('Updates submodules');
task('deploy:update_submodules', function () {
    $git = get('bin/git');
    cd('{{release_path}}');
    run("$git submodule update --init --recursive");
});
```

**Comment by Schrank** [comment]
I would assume, because nowadays "we all use composer", there is no need for submodules anymore. Fun storey: A colleague suggested today to use them and all others here were like "What is that?"

So having your own task is imho the right take on that, because I don't see it needed.

**Comment by itelmenko** [comment]
If I have own classes?

**Comment by Schrank** [comment]
I don't understand your question, what do you mean?

**Comment by itelmenko** [comment]
I have 2 repositories. I need some php classes in both of they. But I need not composer package.

**Comment by Schrank** [comment]
composer solves exactly this problem :-) It is totally fine for me to not use composer, use submodules if it makes you happy :) But imho this is not "best practice" anymore and therefore I would not implement it in deployer :-)

**Comment by itelmenko** [comment]
It is very difficult for debug and work

**Comment by Schrank** [comment]
Composer? I disagree, but don’t want to join this discussion 🙃
As I said, have your own task, use submodules!

**Comment by itelmenko** [comment]
If you can attache some links how to do it easy than submodules, you will make a lot of people happy. Sorry I spend your time. I had a lot of pain with composer packages when  code has many changes in short time.

**Comment by Schrank** [comment]
@itelmenko Happy to help - I just don't want a "but submodules are better" discussion :) I'm happy with composer, if you are with submodules, great!

That said, depending on the situation I have two ways to make quick and easy fixes to dependencies while managing these with composer:

1. [Adding a path-repository, git clone the dependency into it](https://alanastorm.com/composer-path-repositories/) and then "overwrite" the remote version with the local one. So you can add changes to it, have a second branch, etc. and once it is done push it, open pr, merge it, etc.
    The cool thing about this way is, that your path repository will not be deleted accidentaly, as in the second way:
3. The alternative is to run `composer install --prefer-install=source`, so the vendor directory contains mostly git/vcs clones/checkouts if possible. So you can change anything, change branches and push the changes as well. Depending on the situation the cool/horrible situation is, that the next `composer install` or `update` deletes all your changes (although composer is complaining about changes in `vendor/` before simply deleting/updating it.
Hope that helps!

**Comment by itelmenko** [comment]
@Schrank Thank you for such detailed answer!

**Comment by chaikivskyi** [comment]
@Schrank What about the case where we have the frontend in a separate repository but want to deploy it together with the backend? I believe submodules are a good option for this. Do you know any approach for that in Deployer?
