### ISSUE TITLE
Catch exceptions inside «cd» func

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1480]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

With a task like

```php
task('clx:remote_dirty', function() {
    cd('{{current_path}}');
    $output = run('svn status');

    if (!empty($output)) {
        throw new \Exception("Remote working copy contains uncommitted changes!\n". $output);
    }
});
``` 

you can run into errors like

```
 [Deployer\Exception\RuntimeException (1)]
  The command "readlink /www/apps/relaunch/current" failed.
  Exit Code: 1 (General error)
  Host Name: ci16
  ================
```

in the error message it mentions a path, which was not mentioned in the recipe.
IMO the error message should also contain a hint to the line of the recipe, in this case `cd('{{current_path}}');`. otherwise the user of deployer needs to know the internals of deployer to find the actual line throwing/generating the error

**Comment by staabm** [comment]
also a visual hint inside the stacktrace would be helpfull:

![grafik](https://user-images.githubusercontent.com/120441/34386168-a47e0900-eb27-11e7-9c71-3f88cc8024d3.png)

as a user you get a rather large stacktrace, but most of the time the offending line from your recipe is hidden in between

**Comment by antonmedv** [comment]
Reading stack trace is difficult for users. It's try. My be it's better to handle error inside `cd` and re throw errors.
