### ISSUE TITLE
use current process for runLocally

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1484]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.5
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
measuering my deployment process shows that `runLocally` consumes a lot of time (30% of overall time).

wdyt about using the current process instead of forking a local subprocess which adds overhead like local process communication etc?

do you think this makes sense and is feasible?

**Comment by antonmedv** [comment]
How do you imagine this? Try
```
runLocally('whoami');
```

**Comment by staabm** [comment]
hmm I guess what I could imagine is something very similar to the batching you already proposed in https://github.com/deployphp/deployer/pull/1483#issuecomment-354403293
