### ISSUE TITLE
ssh command wants to cd into not existing current directory

### ISSUE THREAD

**Issue by FabianSchmick** [deployphp/deployer#1486]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | bento/ubuntu-14.04
| Remote Machine OS | Debian GNU/Linux 8 (jessie)

### Description 
If I run `dep ssh` on my local machine, deployers ssh command wants to change directory into a `/current` directory on my remote machines project root, but this does not exist. Do I have to create it in my project root or why does it want to go there? The connection established after the warning, but I am in my home directory and not in the project root. Look at the end of my issue for the output log, I think this is more clear.

### Content of `deploy.php`
```php
<?php

namespace Deployer;

require 'recipe/symfony3.php';

// Project name
set('application', 'domain.de');

// Project repository
set('repository', 'myProject.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server
add('writable_dirs', []);

// Default Stage
set('default_stage', 'production');

// Default branch
set('branch', 'master');

// Hosts

host('domain.de')
    ->configFile('/vagrant/.ssh/config')
    ->stage('production')
    ->roles('app')
    ->set('assets', ['web/bundles/app'])
    ->set('deploy_path', '/var/www/{{application}}');

// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'database:migrate');

```

### Output log
```
$ dep ssh
Enter passphrase for key '/vagrant/.ssh/id_rsa':
bash: Line 0: cd: /var/www/domain.de/current: File or directory not found
fabian@v18645 ~ $
```

**Comment by staabm** [comment]
try `dep ssh -vvv`

**Comment by FabianSchmick** [comment]
I tried, but I unfortunately don't get any further information.

**Comment by antonmedv** [comment]
Please, show content of `/var/www/domain.de`
Did you deploy successfully?

**Comment by FabianSchmick** [comment]
Content of `/var/www/domain.de`
```
domain.de
 +-- .git/
 +-- ansible/
 +-- app/
 +-- bin/
 +-- node_modules/
 +-- src/
 +-- tests/
 +-- var/
 +-- vendor/
 +-- web/
 +-- .gitignore
 +-- composer.json
 +-- composer.lock
 +-- gulpfile.js
 +-- package.json
 +-- package-lock.json
 +-- phpunit.xml.dist
 +-- README.md
 +-- rev-manifest.json
 +-- Vagrantfile
```

Note: I deployed earlier per hand (login to remote machine, git pull, exec composer install, gulp and so on) but recently I decided to test this deployer tool.

If I run `dep deploy` I get some errors to:
```
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
✔ Executing task deploy:failed
✔ Executing task deploy:unlock


  [Deployer\Exception\RuntimeException]
  The command "export SYMFONY_ENV='prod'; cd /var/www/domain.de &
  & (/usr/bin/git clone -b master --depth 1 --recursive -q https://fschmick@bitbucke
  t.org/fschmick/domain.git /var/www/domain.de/releases/1 2>&
  1)" failed.
  Exit Code: 128 (Invalid exit argument)
  Host Name: domain.de
  ================
```

**Comment by antonmedv** [comment]
This is correct. You need to finish deployment. After that, dep ssh command will work. See `git_tty` param or manually add  bitbucket.org to known host.

**Comment by staabm** [comment]
DX wise, `dep ssh` should error with a message that it requires a successfull deployment beforehand
