### ISSUE TITLE
Feature request: option to keep a deploy-log on the server

### ISSUE THREAD

**Issue by skarnl** [deployphp/deployer#1489]
In the `.dep` folder now only the releases are stored. It would be nice to have some kind of deployment log there, just an actual `deploy.log` would be great.
It could contain:

author
date
repository / branch / tag
and in what release-version it resulted

Would be happy to help with this

**Comment by staabm** [comment]
I usually use `dep --log deployer.log` and copy it to the server with the source

**Comment by skarnl** [comment]
Mmm, didn't know that was possible. You copy that in an `after('deploy', ...)` task then?

**Comment by staabm** [comment]
yeah, you need to make sure you are before cleanup and after most deployment steps are finished.

**Comment by skarnl** [comment]
But still some of the basic information (date, username) are missing

I would like to see who deployed when from what branch
So for now I think I will make my own task that writes that to the .dep folder and maybe PR that

**Comment by antonmedv** [comment]
> I would like to see who deployed when from what branch

I'm actually working on this feature right now. Really want it myself.
