### ISSUE TITLE
Error thrown in TaskFactory.php, array_map()

### ISSUE THREAD

**Issue by robinwo** [deployphp/deployer#149]
I downloaded & installed the phar file (2.0.1, via https://github.com/deployphp/deployer/releases) using
     
    mv deployer.phar /usr/local/bin/dep
    chmod +x /usr/local/bin/dep

Now I'm getting these errors:

    PHP Warning:  array_map(): An error occurred while invoking the map callback in     phar:///usr/local/bin/dep/src/Task/TaskFactory.php on line 35

    Warning: array_map(): An error occurred while invoking the map callback in     phar:///usr/local/bin/dep/src/Task/TaskFactory.php on line 35
    PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Task "deploy:start" does not     defined.' in phar:///usr/local/bin/dep/src/Deployer.php:309 

With tasks:

    task('deploy', [
     	'deploy:start',
     	'deploy:prepare',
     	'deploy:update_code',
     	'deploy:vendors',
     	'deploy:symlink',
    	'cleanup',
     	'deploy:end'
    ]);

In deploy.php, I also configured env, shared_dirs, writable_dirs, assets, auto_migrate, servers, stages and repository.

Any idea how to fix this?

**Comment by robinwo** [comment]
Okay just found out that I need to define all tasks manually (also the tasks in recipes/common.php). So to install, you not only need to copy the phar file to /usr/local/bin/dep, but you also need to clone this repo (for the recipes). Correct?

>> https://github.com/deployphp/deployer/tree/master/recipe

**Comment by elfet** [comment]
You can simple include recipes from you `deploy.php`.
```php
require 'recipe/common.php';
```

**Comment by robinwo** [comment]
Ok! Think it's good to add this to the docs. Installation focuses only on the phar file, cloning the git repo (for including recipes) is not mentioned yet.
