### ISSUE TITLE
global error handler

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1493]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I want to define a "global error handler" or similar in my recipe which gets fired when a exception is thrown while deployer runs and the script ends unexpectedly.

As far as I can see right now, the only way I can define error handling is via `fail('a-task-name', 'a-error-handling-task');`. I would rather want some kind of global error handler which is fired no matter which task errored.
I would use this error handler to sent a message in our chatroom so someone is aware that the build errored.
I could also do this via the exit-code of the `dep` command call, but at the calling level I need to duplicate my notification api (which is already available for other notifications in my recipe).

**Comment by antonmedv** [comment]
Do you have lots of first level tasks?

**Comment by staabm** [comment]
5-6. maybe it doesnt work as expected because I use invoke() inside first level task.. didnt investigate, but I have situations in which tasks dont run the fail handler even if exceptions are thrown.

**Comment by antonmedv** [comment]
What about useing set_error_handler?

**Comment by staabm** [comment]
I tried using set_error_handler and also set_exception_handler but both do not get fired.

the exception handler is not called, because the deployer internal exception handler exit()`s without invoking a maybe existing previous handler.

and the error_handler isnt invoked because no error happened, but a exception I guess.
