### ISSUE TITLE
Separate deploy task from framework recipe

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1494]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next
| Breaking Changes | **yes** |

Now framework recipes contains `deploy` tasks with definition of deploy process. 

https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L160-L176

```php
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
    'artisan:storage:link',
    'artisan:view:clear',
    'artisan:cache:clear',
    'artisan:config:cache',
    'artisan:optimize',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
]);
```

What about removing this `deploy` tasks from all recipes? And instead put it in template created with `dep init` command? 

So users can see what exactly going on and can modify deployment more easily. 

Framework recipes become sets of useful tasks instead.

**Comment by staabm** [comment]
I like the idea as it unveils those hidden framework things and makes them more explicit in the actual recipe! 👍
