### ISSUE TITLE
Feature request: prevent deploy when no changes

### ISSUE THREAD

**Issue by skarnl** [deployphp/deployer#1497]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question / Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
This question is kinda related to issue #1489 

I would like to have the sha of each deployed release. Not sure if this is already being implemented ([see this comment by antonmedv](https://github.com/deployphp/deployer/issues/1489#issuecomment-354965421)).
But it would be nice if the sha is stored there.

The reason why we need this is that we can check if the new release is actually different compared with the previous release.
Now when someone runs `dep deploy <environment>` multiple times in a row, you'll get multiple releases on the server - but they are all the same. This kinda screws up the `rollback` mechanism and everything (especially since you have no way to track what sha/branch something is based on)

So it would be better if - before doing the release - a check will be done, checking the last version (sha) and the sha of the HEAD. If they are the same, we can opt to bail or to ask a confirmation to make sure someone wants to deploy the same version again.

This feature does depends on the logging of the sha for each release.
Other benefits of storing the sha:

- we can display it in the `config:current` overview, so we can easily see the different sha's
- we can create a `dep env:version <environment>` command that displays the version what is deployed (or show a log)
  
---

@antonmedv : since you are already working on the logging, can I help at any way with the pre-release-checking or other commands? Or should I be patient and way until your logging-feature is finished? :)

**Comment by staabm** [comment]
the sha of your repos alone does not represent the "uniqueness" of your project.
projects can be different even when the sha is the same, e.g. when composer installs vendors in different folders

**Comment by skarnl** [comment]
I don't understand what you mean. Maybe the projects I've done were just simple deploys - no idea.
But can you describe how building from the same sha will result in different outcomes.

If you do a `git checkout SHA123` and a `composer install` on the same server, that should result in the same build - not?
I can imagine that based on server configuration it could be build in different folders or anything. But please show me what you mean

**Comment by antonmedv** [comment]
This is interesting. But what if user what to deploy it any way?

**Comment by skarnl** [comment]
> we can opt to bail or to ask a confirmation to make sure someone wants to deploy the same version again.

We could ask for a confirmation: `Revision ab3492eef33 seems to be already the latest release. Are you sure you want to deploy this version again? [y/N]`
Something like that

**Comment by skarnl** [comment]
I now realize that this 'problem' might be smaller if you deploy and build using `git` on the server ^^
Because of server constraints I decided to build my project locally and rsync it to the server. So then we don't have any information regarding the git version/branch.
If you use the _default_ deployer way of deploying, you do a `git clone / checkout` on the server and can actually ssh to the server and check everything there.

I do prefer having no git on the server and having the server completely clean without all the source-files and I don't think this feature will interfere with the _default_ deploy (`deploy:update_code`) method so would still be a great feature/addition.

**Comment by skarnl** [comment]
I also do this. I just have a simple task:

```
task('add-deploy-info', function() {
    $sha = runLocally('git rev-parse HEAD');
    $username = runLocally('whoami');
    $date = runLocally('date +"%Y-%m-%d @ %H:%M:%S"');

    run("echo '$sha - $date - $username' >> {{release_path}}/.version");
});

after('upload', 'add-deploy-info');
```

And sure I can also make a task that checks for if the released sha is the same as on the server and ask for confirmation. But I figured, before creating this task myself, maybe I should first inform with the community if this is something we'd all would like to have. So I can add this to the core package instead of making a custom task.

**Comment by antonmedv** [comment]
Yes, this is very project depending stuff. Hard to tell which one is good to adapt in common recipe. 
But this stuff need to be putted into docs, tutorials. 

Now i'm working on new better website (and docs) there every one can write an article for.

**Comment by antonmedv** [comment]
Okay, but keep in mind what now I'm actively working on next v7 (on weekends only :( ) and think to finish work within next months.

**Comment by antonmedv** [comment]
I welcome all PR :)

**Comment by antonmedv** [comment]
Doce in 6.5.0
