### ISSUE TITLE
[RuntimeException] Could not login with PhpSecLib.

### ISSUE THREAD

**Issue by robinwo** [deployphp/deployer#150]
Tried configuring server with a pubkey and username / password combination. Keep getting this error:

      [RuntimeException] Could not login with PhpSecLib.

This did not work:

    server( 'development-server', '123.45.67.8', 22 )
    	->path( '/var/www/site.com' )
    	->user( 'username'  )
    	->pubKey( '~/.ssh/site.pub', '~/.ssh/site' );

Neither did this:

    server( 'development-server', '123.45.67.8', 22 )
    	->path( '/var/www/site.com' )
    	->user( 'username', 'password' );

When I SSH via terminal, it all works fine (with the provided certificate in ~/.ssh).

Any idea what's causing this error?

**Comment by elfet** [comment]
What Deployer version? Can you run command with `-vvv` option?

**Comment by robinwo** [comment]
Latest, 3.0.

➜  site.com git:(develop) ✗ dep deploy -vvv
Preparing server for deploy
Run task deploy:prepare on server development-server
[91.238.155.135] cd /var/www/dev.site.com && cd {deploy_path} && if [ ! -d releases ]; then mkdir releases; fi



  [RuntimeException]
  Could not login with PhpSecLib.



Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/PhpSecLib.php:46
 Deployer\Server\PhpSecLib->connect() at phar:///usr/local/bin/dep/src/Server/PhpSecLib.php:72
 Deployer\Server\PhpSecLib->checkConnection() at phar:///usr/local/bin/dep/src/Server/PhpSecLib.php:81
 Deployer\Server\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:115
 run() at /Users/robinwouters/Development/hoe/site.com/deploy.php:33
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Runner.php:45
 Deployer\Task\Runner->run() at phar:///usr/local/bin/dep/src/Console/RunTaskCommand.php:168
 Deployer\Console\RunTaskCommand->runSeries() at phar:///usr/local/bin/dep/src/Console/RunTaskCommand.php:118
 Deployer\Console\RunTaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:114
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:51
 require() at /usr/local/bin/dep:4


deploy [--dry-run] [--server[="..."]] [stage]

**Comment by elfet** [comment]
Well, 3.0 now in dev state. Will try to do it myself. Now you can only
install php ext ssh2 or use Deployer 2.0.0

2015-01-26 15:58 GMT+03:00 Robin Wouters <notifications@github.com>:

**Comment by robinwo** [comment]
My mistake, I'm using v2.0.

Any idea what I'm doing wrong? Or is it a bug?

**Comment by elfet** [comment]
@robinwo sorry do not know right now. Will try to solve it!

**Comment by racastellanosm** [comment]
I have this same issue with v2.0 (the server needs something special in it?)

**Comment by elfet** [comment]
Done.

**Comment by tunh** [comment]
I have the same problem, how to fix it?

**Comment by dancostinel** [comment]
v4.0.2 here, and I'm having the same problem. any fix? thanks!

my deploy.php:
-------------------
set('default_stage', 'production');

server('prod', '195.254.135.18', '2082')
    ->user('user')
    ->password('pass')
    ->set('deploy_path', '/home/www')
    ->stage('production');

desc('Run a simple terminal command');
task('pwd', function () {
    $result = run('pwd');
    writeln("Current dir: $result");
});


the error:
-----------

zzz20$ dep pwd -vvv
➤ Executing task pwd
[prod] > cd /home/www && (pwd)

PHP Notice:  Connection closed by server in phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1079

                                                  
  [RuntimeException]                              
  Unable to login with the provided credentials.  
                                                  

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:99
 Deployer\Server\Remote\PhpSecLib->connect() at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:109
 Deployer\Server\Remote\PhpSecLib->checkConnection() at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:118
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:310
 Deployer\run() at /var/www/zzz20/deploy.php:31
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:91
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:79
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:186
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:110
 require() at /usr/local/bin/dep:4

pwd [-p|--parallel]

**Comment by elfet** [comment]
Check your user/password or try to use identity keys.
