### ISSUE TITLE
Add docs folder to allow documenting the included recipes

### ISSUE THREAD

**Issue by frederickjh** [deployphp/deployer#1500]
Issue Type: Feature Request

### Description 
Add a `docs` folder  to allow documenting the included recipes or a `recipes_docs` folder to make it clearer that this only the documentation for the included recipes.

The [deployphp/recipes](https://github.com/deployphp/recipes) project has this and an .md file of documentation for each recipe. Adding this would allow people to start documenting these included recipes and their usage.

Thanks for your consideration of this feature!
Frederick

**Comment by antonmedv** [comment]
Actually docs for deployer in separate repository. Better for maintaining. 
But you are right, will be cool to have more docs. What about help command?
```
dep help deploy:release
```

**Comment by frederickjh** [comment]
The help command is good and provides a lot of information but from what I see it does not provide help relevant to recipes other than common. I just saw that in the deployer/recipes project one could get a very quick overview of a recipes usage and configuration without having to dig it out of the code in the help file provided for each recipe in the docs folder. 

This was just a idea that I thought would help noobies get started quicker with an included recipe. I thought if a folder was added with a document that says this folder should be used to document usage and configuration for recipes, that this would encourage others to write the help.

**Comment by antonmedv** [comment]
@frederickjh I see what you mean. I want to do something like this too, but I afraid what docs will be unsynced, for example in deployphp/docs and in main repo. 
I'm thinking about more inline documentation, maybe add better descriptions and so on.
