### ISSUE TITLE
Custom arguments prepended to Deployer arguments

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#1501]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | Ubuntu
| Remote Machine OS | N/A

### Description 
If a `deploy.php` or a custom recipe defines a CLI argument, it is prepended to the Deployer arguments. This especially affects the `stage` argument of any task command which then cannot be passed as usual anymore. If you pass a placeholder value for the custom argument, you are able to fill the `stage` argument. Alternatively one can use `option()` instead but that requires option notation on CLI too.

### Steps to reproduce

1. Have an `argument()` in `deploy.php` or an included recipe.
2. Execute any task passing in a stage/hostname, e.g. `bin/dep deploy staging`

### Content of `deploy.php`
```php
argument('foo');
task('deploy', function() {});
```

### Output log
```

In HostSelector.php line 75:

  [Deployer\Exception\Exception]
  You need to specify at least one host or stage.


Exception trace:
 Deployer\Host\HostSelector->getHosts() at /var/www/vendor/deployer/deployer/src/Console/TaskCommand.php:118
 Deployer\Console\TaskCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/deployer/deployer/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:240
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/vendor/deployer/deployer/src/Deployer.php:324
 Deployer\Deployer::run() at /var/www/vendor/deployer/deployer/bin/dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

```

**Comment by kszymukowicz** [comment]
Unfortunately confirmed.

I have big headache now as I wanted to make https://github.com/sourcebroker/deployer-extended-database which is working with Deployer 4.3 only to be compatibile with Deployer 6.4.

This issue make that impossible.

Examples:
I have commands like "dep db:pull live" but also commands which requires to give two arguments like "dep db:copy live beta". If I will add new argument then the command "dep db:pull live" will not longer work properly.

**Comment by antonmedv** [comment]
I'm thinking of removing arguments at all. Only flags.

**Comment by mbrodala** [comment]
@antonmedv That's probably a good, albeit breaking, idea. This way recipes are forced to have named flags which would ensure namespacing to some extend.

**Comment by kszymukowicz** [comment]
In that case I will remove my custom arguments then.
