### ISSUE TITLE
rollback doesnt work properly

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1502]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
It seems that the rollback task does not call any methods from the actual recipes.
how is it supposed to work? In our case just switching the symlink to the old sources is not sufficient.
we also need a cache prune and webserver reload etc.
how to hook this additional tasks into the rollback?

see https://github.com/deployphp/deployer/blob/master/recipe/deploy/rollback.php

**Comment by staabm** [comment]
should my recipe just re-define the native rollback task?

**Comment by skarnl** [comment]
Since it's a task, can't you just do a `after('rollback', function() { })` where you run the needed tasks?
Not sure, just thinking out loud

**Comment by staabm** [comment]
technically this will work I guess. if this is the prefered solution it should be mentioned in the docs / tutorial

**Comment by antonmedv** [comment]
@skarnl is right.
