### ISSUE TITLE
Missing {{bin/php}} in deploy:vendors

### ISSUE THREAD

**Issue by gander** [deployphp/deployer#1503]
https://github.com/deployphp/deployer/blob/217935fc1e77a8305579bde936d3aa8fcc6a5430/recipe/deploy/vendors.php#L15

Should be:
```
run('cd {{release_path}} && {{bin/php}} {{bin/composer}} {{composer_options}}'); 
```
Detected on a server with different versions of php

**Comment by antonmedv** [comment]
Can you send PR?
