### ISSUE TITLE
How to set and persist ENV vars?

### ISSUE THREAD

**Issue by ivoba** [deployphp/deployer#1504]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.5
| Local Machine OS  | Ubuntu16
| Remote Machine OS | digitalocean ubuntu 17.10

### Description 
I tried to set ENV vars on a digitalocean droplet but after running a successful deploy i dont see any ENV vars with printenv or env.
Env vars should replace the .env file.

### Steps to reproduce
```
set('env', [
        'SS_BASE_URL' => 'xxx.xxx.xxx',
        'SS_DATABASE_CLASS' => 'MySQLPDODatabase',
        'SS_DATABASE_NAME' => 'SS_mysite',
        'SS_DATABASE_PASSWORD' => 'pw',
        'SS_DATABASE_SERVER' => 'localhost',
        'SS_DATABASE_USERNAME' => 'user',
        'SS_ENVIRONMENT_TYPE' => 'live',
]);
```

### Output log
 it seems deployer exports ENV vars for each operation, but they dont persist.

...
> export SS_BASE_URL='xxx.xxx.xxx' SS_DATABASE_CLASS='MySQLPDODatabase' SS_DATABASE_NAME='SS_mysite' SS_DATABASE_PASSWORD='pw' SS_DATABASE_SERVER='localhost' SS_DATABASE_USERNAME='user' SS_ENVIRONMENT_TYPE='live'; cd /var/www/ && (mkdir /var/www//releases/19)

...

**Comment by antonmedv** [comment]
`set('env'` available only per running commands. try:

```
run('echo $SS_BASE_URL');
```

**Comment by ivoba** [comment]
i tried with:
```
task('deploy:set_env_vars', function () {
    run('export SS_TEST=test');
});
```
but that doesnt seem to work.
>printenv
or
>echo $SS_TEST
return no value

**Comment by antonmedv** [comment]
Each run have it's own envs. 

What's your problem? What are you trying to accomplish?

**Comment by ivoba** [comment]
i thought i could share ENV vars through ssh sessions, so i could set them via deploy and the scripts could use the ENV vars as config.
but i guess im wrong here since ENV vars belong to the current session.
nevermind :)
