### ISSUE TITLE
Cant  use param's values inside .yml 

### ISSUE THREAD

**Issue by ihipop** [deployphp/deployer#1508]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | Debian SID
| Remote Machine OS | N/A

### Description 
It seems that `.yml ` file will express the param's value https://deployer.org/docs/hosts
![image](https://user-images.githubusercontent.com/423077/35109096-5d44e9ba-fcb0-11e7-98ed-cf87594fe134.png)
But, Actually not.

### Steps to reproduce
`host.yml`
```yml
dev:
    identityFile: "{{application}}"
```
### Content of `deploy.php`
```php
set('application', '~/dev.examle.com/key');
```

### Output log
![image](https://user-images.githubusercontent.com/423077/35109316-f88f03ba-fcb0-11e7-825c-bc579f5f01e0.png)

**Comment by antonmedv** [comment]
Yes, looks like a bug.

**Comment by antonmedv** [comment]
Should be fixed
