### ISSUE TITLE
shared_dir and shared_files should support * properly

### ISSUE THREAD

**Issue by vytsci** [deployphp/deployer#1510]
Hello, Ive noticed that shared_dir and shared_files does not support asterisk (*). It just creates directory or file with asterisk within name. Ive created my own task, but should be cool to have support for this by default. Is there any reason why this is not supported?

**Comment by antonmedv** [comment]
So what is purpose? Can you show example?

**Comment by vytsci** [comment]
For example we have module translation files in prestashop. Now you have to share each module translation files separately, with asterisk you can write "modules/*/translations" and all the modules will be shared with one line. I know its a stupid practice from prestashop, but I believe this would be useful in more ways than that. Ive made everything working with php glob.

**Comment by antonmedv** [comment]
But what to do with shared files: /some/*

**Comment by vytsci** [comment]
This may be less usable, but you may want to share for example only *.php files from certain folder or config files *.yml only. Either way it is useful to have asterisk supported. For software like prestashop where each module has its own structure it is crucial to have such feature. Im taking prestashop for example, because it is most recent project that I had problems with deployment using Deployer. So I made a suggestion which I think would be useful.

**Comment by antonmedv** [comment]
This is really tricky feature will be cool if someone can think it through and create PR
