### ISSUE TITLE
TTY mode is not supported on Windows platform.

### ISSUE THREAD

**Issue by lukchojnicki** [deployphp/deployer#1511]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | Windows
| Remote Machine OS | Linux (Debian)

### Description 
While deploy I have error:
"In Process.php line 1022:

  TTY mode is not supported on Wind
  ows platform."

How to get rid off it?
Deploy failed, but I don't know why because all I can see in console is this error.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', 'FireAds');

// Project repository
set('repository', 'git@bitbucket.org:lukchojnicki/fireads.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server
add('writable_dirs', []);


// Hosts
set('ssh_multiplexing', false);
set('default_stage', 'develop');

// Hosts

host('production')
    ->hostname('xxxxx')
    ->user('www')
    ->addSshOption('StrictHostKeyChecking', 'no')
    ->set('http_user', 'www-data')
    ->set('deploy_path', '/xxxxxxx/production');

host('develop')
    ->hostname('xxxxxxxx')
    ->user('www')
    ->addSshOption('StrictHostKeyChecking', 'no')
    ->set('http_user', 'www-data')
    ->set('deploy_path', '/xxxxxxxx/develop');


// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

//before('deploy:symlink', 'artisan:migrate');
```

### Output log
*With enabled option for verbose output `-vvv`.*

[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < master
✈︎ Deploying master on develop
• done on [develop]
➤ Executing task deploy:prepare
[develop] > echo $0
[develop] < bash
[develop] > if [ ! -d /home/www/xxxxxxxx/develop ]; then mkdir -p /home/www/xxxxxxxx/develop; fi
[develop] > if [ ! -L /home/www/xxxxxxxx/develop/current ] && [ -d /home/www/xxxxxxxx/develop/current ]; then echo 'true'; fi
[develop] > cd /home/www/xxxxxxxx/develop && if [ ! -d .dep ]; then mkdir .dep; fi
[develop] > cd /home/www/xxxxxxxx/develop && if [ ! -d releases ]; then mkdir releases; fi
[develop] > cd /home/www/xxxxxxxx/develop && if [ ! -d shared ]; then mkdir shared; fi
• done on [develop]
✔ Ok [4s 270ms]
➤ Executing task deploy:lock
[develop] > if [ -f /home/www/xxxxxxxx/develop/.dep/deploy.lock ]; then echo 'true'; fi
[develop] > touch /home/www/xxxxxxxx/develop/.dep/deploy.lock
• done on [develop]
✔ Ok [1s 427ms]
➤ Executing task deploy:release
[develop] > cd /home/www/xxxxxxxx/develop && (if [ -h release ]; then echo 'true'; fi)
[develop] < true
[develop] > cd /home/www/xxxxxxxx/develop && (rm -rf "$(readlink release)")
[develop] > cd /home/www/xxxxxxxx/develop && (rm release)
[develop] > cd /home/www/xxxxxxxx/develop && (if [ -d releases ] && [ "$(ls -A releases)" ]; then echo 'true'; fi)
[develop] > cd /home/www/xxxxxxxx/develop && (if [ -d /home/www/xxxxxxxx/develop/releases/1 ]; then echo 'true'; fi)
[develop] > cd /home/www/xxxxxxxx/develop && (date +"%Y%m%d%H%M%S")
[develop] < 20180120175022
[develop] > cd /home/www/xxxxxxxx/develop && (echo '20180120175022,1' >> .dep/releases)
[develop] > cd /home/www/xxxxxxxx/develop && (mkdir /home/www/xxxxxxxx/develop/releases/1)
[develop] > cd /home/www/xxxxxxxx/develop && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[develop] < true
[develop] > cd /home/www/xxxxxxxx/develop && (ln -nfs --relative /home/www/xxxxxxxx/develop/releases/1 /home/www/xxxxxxxx/develop/release)
• done on [develop]
✔ Ok [8s 128ms]
➤ Executing task deploy:update_code
[develop] > if hash command 2>/dev/null; then echo 'true'; fi
[develop] < true
[develop] > command -v "git"
[develop] < /usr/bin/git
[develop] > /usr/bin/git version
[develop] < git version 2.1.4
[develop] > cd /home/www/xxxxxxxx/develop && (if [ -h /home/www/xxxxxxxx/develop/release ]; then echo 'true'; fi)
[develop] < true
[develop] > cd /home/www/xxxxxxxx/develop && (readlink /home/www/xxxxxxxx/develop/release)
[develop] < releases/1
[develop] > cd /home/www/xxxxxxxx/develop && (/usr/bin/git clone -b master --depth 1 --recursive -q git@bitbucket.org:lukchojnicki/xxxxxxxx.git /home/www/xxxxxxxx/develop/releases/1 2>&1)
➤ Executing task deploy:failed
• done on [develop]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[develop] > rm -f /home/www/xxxxxxxx/develop/.dep/deploy.lock
• done on [develop]
✔ Ok [813ms]

In Process.php line 1030:

  [Symfony\Component\Process\Exception\RuntimeException]
  TTY mode is not supported on Windows platform.

Exception trace:
 Symfony\Component\Process\Process->setTty() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Ssh\Client.php:73
 Deployer\Ssh\Client->run() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\functions.php:296
 Deployer\run() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\recipe\deploy\update_code.php:90
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Task\Task.php:105
 Deployer\Task\Task->run() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Executor\SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Console\TaskCommand.php:142
 Deployer\Console\TaskCommand->execute() at C:\laragon\www\xxxxxxxx\vendor\symfony\console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at C:\laragon\www\xxxxxxxx\vendor\symfony\console\Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Console\Application.php:132
 Deployer\Console\Application->doRunCommand() at C:\laragon\www\xxxxxxxx\vendor\symfony\console\Application.php:240
 Symfony\Component\Console\Application->doRun() at C:\laragon\www\xxxxxxxx\vendor\symfony\console\Application.php:148
 Symfony\Component\Console\Application->run() at C:\laragon\www\xxxxxxxx\vendor\deployer\deployer\src\Deployer.php:324
 Deployer\Deployer::run() at C:\Users\pc\AppData\Roaming\Composer\vendor\deployer\deployer\bin\dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

**Comment by antonmedv** [comment]
```
// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', false);
```

**Comment by lukchojnicki** [comment]
Oh, I missed that...

**Comment by iampinheirosamuel** [comment]
C:\xampp\htdocs\laraDusk(test)>php artisan dusk

In Process.php line 1030:

  TTY mode is not supported on Windows platform.


Help... how do make it work?

**Comment by staabm** [comment]
how is this artisan issue related to deployer?
