### ISSUE TITLE
Add cron management to deployer

### ISSUE THREAD

**Issue by sdboer78** [deployphp/deployer#1515]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request

### Description 
Add cron management to deployer like: http://docs.ansible.com/ansible/latest/cron_module.html

**Comment by lashae** [comment]
@antonmedv Is there any progress or ETA for this issue?

**Comment by antonmedv** [comment]
Some progress already done on this issue (but not in public repo). Now I'm actively working on Deployer CI project, after will be more time for v7.

**Comment by cedricverhaeghe** [comment]
For the time being I created a custom task that reads cronjobs from a local txt file and installs them on the server.
Modify to your liking.

```
task('deploy:cronjobs', function () {
    # if there is no crontab yet, create an empty one
    $crontab_exists = run("crontab -l > /dev/null 2> /dev/null; echo $?") == 1 ? false : true;
    if (!$crontab_exists) {
        run("echo '' | crontab -");
    }

    $config = run("crontab -l");
    $arr_config = explode("\n", $config);
    array_walk($arr_config, function (&$value) {
        $value = trim(str_replace("\n", "", $value));
    });

    $cron_file = file('cronjobs.txt');
    foreach ($cron_file as $line) {
        $line = trim(str_replace("\n", "", $line));
        if (!in_array($line, $arr_config)) {
            run("(crontab -l; echo \"".$line."\") | crontab -");
        }
    }
})->desc('Install the necessary cronjobs');
after('deploy:symlink', 'deploy:cronjobs');
```

**Comment by cafferata** [comment]
We solved it at @JCID by adding the complete crontab file to the GIT repository and load the full file from there (only in production mode).

```
task(
    'cronjob:install',
    function () {
        if (Context::get()->getEnvironment()->get('env') === 'prod') {
            run('crontab /path/to/the/crontab/file');
        }
    }
)->desc('Install cronjobs');
```

I hope it helps you further on! Cheers!

**Comment by bolechen** [comment]
```
task('cronjob:install', function () {
    run('crontab {{release_path}}/conf/crontab.conf');
})->desc('Install cronjobs')->onStage('prod');
```

**Comment by loevgaard** [comment]
For people finding this on Google and wants a little more functionality than the recipe in the contribs folder, here is a lib that will help you out: https://github.com/Setono/deployer-cron
