### ISSUE TITLE
local task not executable when hosts defined

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1517]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | Ubuntu16 lts
| Remote Machine OS | N/A

### Description 
my understanding of `local()` on a particular task is, that I can run the task without the need to specify the host - as automatically "localhost" will be used.

as soon as I have hosts defined im my recipy I can no longer invoke my task without a hosts argument...?
is this intended or a bug?

when commenting the 4 host lines, it works.

I would like to register some of my tasks so they can run without a host parameter...

### Content of `deploy.php`
```php
<?php

namespace Deployer;

use Symfony\Component\Process\ProcessUtils;

require 'recipe/common.php';

host('devmst16')
    ->hostname('192.168.50.19')
    ->set('deploy_path', '/my/path/to/heaven/')
    ->stage('dev');

task('hallo123', function() {

})->local();

```

### Output log
*With enabled option for verbose output `-vvv`.*
```
dep hallo123 -vvv


  [Deployer\Exception\Exception]
  You need to specify at least one host or stage.


Exception trace:
 () at phar:///usr/local/bin/dep/src/Host/HostSelector.php:75
 Deployer\Host\HostSelector->getHosts() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:118
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:324
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

hallo123 [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]
```

**Comment by antonmedv** [comment]
This is by design. If host specified – you need to add it.

**Comment by staabm** [comment]
Hmm I want to define some dev tasks which dont require a host but just do some work on the local project.

I feels this is a good use case as deployer already provide lots of tools one needs to built those dev tasks.

Having a mandatory host for this task „doesnt make sense“ from a usage point of view. 

Any suggestions/ideas how I could handle that? Is my usage out of scope?

**Comment by antonmedv** [comment]
Actually I was thinking of it myself. But can't find appropriate solution right now. Maybe some api. 
Also I thinking making mandatory only for stage if defined.

**Comment by staabm** [comment]
what is the current use case for the `local` flag on `Task`?

is it only meant to make `run` act like `runLocally` or does it have further implications?

could we make assumptions like "when the single tasks invoked by the developer is a `local` task, don't handle hosts as beeing required and execute it on the `Localhost` host.

in case any of the subtasks/related tasks which get executed along the way try to `getHost()` from the `Context` throw an exception.
