### ISSUE TITLE
Deployer 4.x

### ISSUE THREAD

**Issue by oldo** [deployphp/deployer#1525]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | MacOS
| Remote Machine OS | N/A

I know this is not the ideal place to post this question but I haven't been able to find an answer elsewhere. I need to install Deployer 4.x because the rest of the team I'm working with is locked into using this version for the time being. How/where can I install this version?

Thanks, and again, sorry that this is not an ideal place to post this question.

**Comment by antonmedv** [comment]
Use composer or download it directly: https://deployer.org/download

Note what it's okay to add deployer phar to git cvs so everybody will use same version across the project.

**Comment by oldo** [comment]
Epic! Thank you @antonmedv 

I didn't notice that there was a listing of previous releases on the download page. Nice suggestion about adding the .phar to our git repo. Thanks :-)
