### ISSUE TITLE
properly support argument escaping via run()/runLocally()

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1526]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.5
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
when running commands with arguments like
`run("svn diff ". ProcessUtils::escapeArgument($fileName))`
we need to use `ProcessUtils::escapeArgument()` (or a similar self-implemented escaping method) to protect your command.

The `ProcessUtils::escapeArgument()`  method is deprecated since symfony 3.3 und was removed in 4.0.
when using this method we already get a deprecation warning.

https://github.com/symfony/symfony/blob/0023f4e84d525d2d95a672597e1219dd0954c0fd/src/Symfony/Component/Process/ProcessUtils.php#L43

symfony recommends to use a string-array instead of a plain string, so the process component can do the escaping internally.
see the docs https://symfony.com/doc/current/components/process.html#usage

atm using `run` and `runLocally` api deployer only supports string arguments, but not string array.
that way one needs to use a deprecated symfony api to make it work properly with arguments provided via user-input (`ask*`-methods)

`run(array("svn diff ", $fileName))` leads to

```
[Deployer\Exception\RuntimeException (127)]
  The command "cd /mypath/myproject && (Array)" failed.
  Exit Code: 127 (Command not found)
  Host Name: test
  ================
  bash: line 1: Array: command not found
```

**Comment by antonmedv** [comment]
This is possible to do only for `runLocally`. Not for `run` ssh - see implementation.

**Comment by antonmedv** [comment]
Closing as not really needed.
