### ISSUE TITLE
allow to mask sensitive output in verbose modes

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1527]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.0.5
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
in our recipe we ask the user for login credentials which we later on need to pass to some commands.
in our case we use `svn .... --username plainUserName --password plainPassword`.

while we ask the user for the password the input is hidden, but the credentials are rendered in plain text in the stdout while commands run.

it would be great if we could somehow blacklist things, so the plain passwords arent visible while running or even logged into file.

**Comment by antonmedv** [comment]
Nice feature. Definitely will be in v7.

**Comment by antonmedv** [comment]
This is done in master! `run('... %secret%...', ['secret' => '....']);`
