### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drchav** [deployphp/deployer#153]
Hi ppl,
I updated my dep today and start getting this message:

 Call to undefined method Deployer\Server\Builder::path() 

this is my deploy.php

require 'recipe/common.php';

server("main", 'MYSERVER',22)
    ->path("~/apps/ewallet")

anyone has this?

thanks in advance

**Comment by elfet** [comment]
Hi! From what and on what version you have updated?

**Comment by drchav** [comment]
i really do not know previous version but now i'm using:
Deployer version 3.0.0-beta

**Comment by elfet** [comment]
Try to download stable version 2.0.2: http://deployer.org/deployer.phar 
Now unstable version will be available here: http://deployer.org/beta/deployer.phar
