### ISSUE TITLE
RuntimeException is implemented inconsistently

### ISSUE THREAD

**Issue by nvahalik** [deployphp/deployer#1535]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | master
| Local Machine OS  | macOS
| Remote Machine OS | Ubuntu 16.04 LTS

### Description 
When accessing `$e->command()` of a RuntimeException thrown by calling the `run()` function , PHP will throw a `TypeError`:

    [TypeError] Return value of Deployer\Exception\RuntimeException::getCommand() must be of 
    the type integer, string returned

### Steps to reproduce
In my case, I was writing a custom `deploy:writable` task and my code looked like this:

```
task('deploy:writable', function () {
  try {
    $dirs = join(' ', get('writable_dirs'));
    cd('{{release_path}}');
    run("mkdir -p $dirs");

    $httpGroup = get('http_group', false);
    if ($httpGroup === false) {
      throw new RuntimeException("Please setup `http_group` config parameter.");
    }
    run("chgrp -fRH $httpGroup $dirs"); // Fails, but silently with the "-f".
  }
  catch (\Exception $e) {
    if (get_class($e) === "Deployer\Exception\RuntimeException" && strpos($e->getCommand(), 'chgrp') !== false) {
      echo "Chgrp failed, which we expected. Continuing.";
    }
    else {
      throw $e;
    }
  }
});
```

A `var_dump()` of the object shows that the `private $command` value is, indeed, the expected value of (approximately) `"cd /deploy_root/releases/2 && (chgrp -fRH www-data var media)"`. However, the `getCommand()` method is result cast to `int` in the code. Therefore, a `TypeError` is then thrown.

### Recommended fix?

Looks like one could simply remove the `: int` result cast from the code and just allow the value to be whatever one wants it to be. Since the `$command` isn't type-hinted in the constructor, this is never caught. However, I am unsure of what the implications are!

**Comment by antonmedv** [comment]
Fixed by 2161cec2c46f685701fdcbd58f243b6460d50875
