### ISSUE TITLE
Required to touch existing files?

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1540]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6
| Local Machine OS  | N/A
| Remote Machine OS | Ubuntu

### Description 
When a shared file does not yet exist, an empty file is created. This doesn't always make sense, because the file is usually not correct. This is usually the case with environment files, eg Laravel `.env` or Magento `app/etc/env.php`. 
For Laravel this is not a problem, but Magento expects an array for example. See https://github.com/magento/magento2/pull/13090

### Steps to reproduce
Deploy for the first time with that file.

### Solution?

Do we need to touch the file? If it doesn't exist, we can still create the symlink, which will be activated once the file is created, right? If so, should we just check if the file actually exists before touching, or do we not need `touch` at all?

**Comment by antonmedv** [comment]
No, actually deployer first trying to copy it from repo. If no files found - what to do? Maybe display warning and continue deploy?

**Comment by barryvdh** [comment]
Yeah it doesn't need it perhaps? I usually do a deployment, then set up the files, then re-deploy when the files are existing.

**Comment by antonmedv** [comment]
Touching was added to not forgot these files.

**Comment by memen45** [comment]
What do you mean with forgetting these files? If the user should not forget to add these files to git, then maybe a warning or full on deploy:failed would be better?
Otherwise I think the user would make a deliberate choice in not adding the shared files to the repository right?

**Comment by antonmedv** [comment]
Yes, some error/warning message will be preferable. Can somebody work on PR?
