### ISSUE TITLE
Question: how can I failed a deploy from custom task?

### ISSUE THREAD

**Issue by metfan** [deployphp/deployer#1544]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | 6

Hello, 

I'm doing some custom task for our specific use. One of them did some check and I want to failed the deploy if there are a problem.
How can I ftrigger a fail event from a task? 

Thank you.

**Comment by antonmedv** [comment]
```
throw new Exception('Your error');
```

**Comment by metfan** [comment]
Ok, thanks
