### ISSUE TITLE
Deploy on multiple stages at once

### ISSUE THREAD

**Issue by loranger** [deployphp/deployer#1546]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | master (6.0 but --version always return master)
| Local Machine OS  | macOS
| Remote Machine OS | Debian 8.10

### Description 
Is there a way to cascade deployments using stage() ?

Before v6, my prod server() used to have the `'production'` stage and my staging server() used to have the `['production', 'stage']` stages.

Whenever I deployed `stage`, my staging server only was up-to-date.
Whenever I deployed `production`, my staging server was also up-to-date.

Now it seems it's not possible anymore, until I missing something ?
Thanks

**Comment by antonmedv** [comment]
You can achieve this with roles:
```js
host('stage')->roles(['production', 'stage']);
host('prod')->roles(['production']);
```

```
dep deploy --roles production
```

**Comment by antonmedv** [comment]
Nope, sorry. But we can refactor `default_stage` to something more generic in v7.

**Comment by loranger** [comment]
Thanks ! I'll wait for v7 ;)

**Comment by antonmedv** [comment]
Take a look at master branch!!
