### ISSUE TITLE
Symfony 4 Support

### ISSUE THREAD

**Issue by mediavariance** [deployphp/deployer#1547]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Has anyone started working on support for Symfony 4? We've been rolling out Laravel 5.6 which requires version 4 of symfony and will begin working on a branch if no one else has made a effort yet.

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/pull/1440
https://github.com/deployphp/deployer/pull/1420
