### ISSUE TITLE
[API] Display non-fatal error on deployment

### ISSUE THREAD

**Issue by gordalina** [deployphp/deployer#155]
API to allow displaying that a task has failed but does not compromise the deployment.
Example: [newrelic recipe](https://github.com/deployphp/recipes/blob/master/recipes/newrelic.php#L42) and [slack recipe](https://github.com/deployphp/recipes/blob/master/recipes/slack.php#L50)

Possible APIs:
- `writeln('Task has failed', ERROR)` - the second argument could be `OK` (default) or `ERROR`
- `writeError('Task has failed')`
- `error('Task has failed') - this would be only for recoverable errors, as fatal errors are thrown exceptions

@elfet, let me know what you think

**Comment by elfet** [comment]
According to [Occam's razor](https://en.wikipedia.org/wiki/Occam%27s_razor) "_entities must not be multiplied beyond necessity_".
So i think is better (and simple) to have standard PHP ways to report errors - `throw` an exception. 
And if you do not want to break deploy process, simple inform user about your errors: `written('<error>...</error>')`, creating new arguments, or functions for that is unwarranted complication.

What do you think @gordalina?

**Comment by gordalina** [comment]
I agree totally on simple solutions

We could use `writeln(<error>)` but it wouldn't fit into the way tasks are printed. E.g.: A task name is displayed, and at the end a green check is displayed, it could print a red cross (✗).

A special exception could be thrown, for example `Deployer\Exception\NonFatalException` or something similar. Having a special exception would position the display logic in Deployer, rather than the task itself - as successful tasks do not have to write to the console, a task which caused an error should not as well (it follows the same principle).

What do you think?

**Comment by elfet** [comment]
Yes, special exception is good solution. Can you make PR?

**Comment by gordalina** [comment]
Yes, i will
