### ISSUE TITLE
'echo' in deploytasks doesnt behave like expected

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1551]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.5
| Local Machine OS  | Ubuntu16 lts
| Remote Machine OS | N/A

### Description 
printing output via std-in (e.g. via echo or printf etc.) does sometimes not get shown on the console at all and in other cases the output is overridden by the "OK" indicator.

IMO we should handle output from stdin the same as output written via `write()` or `writeln()`

### Steps to reproduce

error case 1: no output rendered at all when no newline is part of the output
```
$ dep greet
✔ Executing task greet
```

error case 2: the "ok" indikator is overlaying the printed output and parts of the printed string are not rendered at all
```
$ dep greet-friend
➤ Executing task greet-friend
✔ello
```

happy case: when using the `writeln` or `write` api everything works as expected.
```
$ dep greet-friend-writeln
➤ Executing task greet-friend-writeln
hello
myfriend
✔ Ok
```
### Content of `deploy.php`
```php
task('greet', function() {
    echo "hello";
});

task('greet-friend', function() {
    echo "hello\nmyfriend";
});

task('greet-friend-writeln', function() {
    writeln("hello\nmyfriend");
});
```

**Comment by noirsoldats** [comment]
Is there a reason to use echo?

**Comment by staabm** [comment]
From a technical point of view its not necessary.

From a DX point of view using echo to output stuff is more natural and creates more readable code

**Comment by noirsoldats** [comment]
I'd suggest checking out the Symfony Console component to understand why echo really shouldn't be specially supported.
