### ISSUE TITLE
Add support for Laravel 5.6 (Symfony 4.0 conflict)

### ISSUE THREAD

**Issue by solofeed** [deployphp/deployer#1552]
Q | A
-- | --
Issue Type | Feature Request
Deployer Version | 6.0.5
Local Machine OS | N/A
Remote Machine OS | N/A

**Comment by antonmedv** [comment]
Will do today. Use phar for now.

**Comment by tarampampam** [comment]
@antonmedv Please, say when we can see updated (and released) version?

**Comment by antonmedv** [comment]
Soon, I promise. :) Here is my motivator: https://www.paypal.me/antonmedv ;)

**Comment by Cryde** [comment]
@antonmedv  why don't you do a https://www.patreon.com ? Or something similar ?

**Comment by antonmedv** [comment]
Because it's not profitable, at all :(

Now trying to build pain service around deployer: https://deployer.org/pro/continuous-integration

**Comment by xakzona** [comment]
I made pull request https://github.com/deployphp/deployer/pull/1559

**Comment by xakzona** [comment]
Merged may close issue

**Comment by xakzona** [comment]
Please tag new version

**Comment by antonmedv** [comment]
Done!
