### ISSUE TITLE
prepared commands / transparent argument escaping

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1560]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
when building custom tasks to run custom commands you sometimes run into a situation in which you ask the user for information you later on pass into a command.

this of course requires some escaping, so things dont got horrible wrong.

symfony recently introduced the term 'prepared' commands:
http://symfony.com/blog/new-in-symfony-4-1-prepared-commands

maybe we can take some inspiration from this post and provide a api with deployer which does not require escaping when running commands with variable portions in it.

**Comment by antonmedv** [comment]
Will be cool to have it in some sort. Difficult part is to find right API with clear syntax (must be easy to understand without reading the docs)

**Comment by staabm** [comment]
to not break the API we could add support for the last example mentioned in the blog post
(separate the command parts with a passed in array)

![grafik](https://user-images.githubusercontent.com/120441/36906958-992391fe-1e37-11e8-813a-8c6c8d4137d0.png)

**Comment by antonmedv** [comment]
For later.
