### ISSUE TITLE
Add var/sessions to shared for symfony 4 recipe.

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1566]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.1.0

### Description 
Missing `var/sessions`.
Also add `cache:warmup` to standard flow.

**Comment by dorantor** [comment]
This one seems to be resolved. Even `cache:warmup` can be seen in 6bf05659740322e5440b5bd48fb45fadb3fced60 commit.
