### ISSUE TITLE
Deploy completes even if composer (in vendors) returns error exit code

### ISSUE THREAD

**Issue by designermonkey** [deployphp/deployer#1569]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | ~5.0
| Local Machine OS  | OsX, Ubuntu
| Remote Machine OS | Ubuntu

### Description 

When the `vendors` task runs, and composer is run on the remote machine, if composer exits with a status code other than 0, deployer still completes as though the deployment was successful.

### Steps to reproduce

1. Overide `composer_options`: `set('composer_options', '{{composer_action}} --verbose --prefer-dist --no-interaction --no-dev --optimize-autoloader 2>&1 | tee storage/logs/composer.log');` (outputs composer to a log file).
2. Use an invalid composer file somehow, we have dependencies that fail.
3. dep deploy the project
4. Read the composer log and see it has failed
5. See that deployer has completed successfully.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/common.php';

// Configuration

set('repository', 'git@bitbucket.org:thoughtriver/hermes-api.git');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
set('shared_files', []);
set('shared_dirs', [
    'storage',
]);
set('writable_dirs', [
    'storage/cache',
    'storage/logs',
]);
set('allow_anonymous_stats', false);

set('composer_options', '{{composer_action}} --verbose --prefer-dist --no-interaction --no-dev --optimize-autoloader 2>&1 | tee storage/logs/composer.log');

// Hosts

host('development')
    ->hostname('xxx.xxx.xxx.xxx')
    ->stage('development')
    ->port(22)
    ->user('xxx')
    ->identityFile('~/.ssh/id_rsa')
    ->forwardAgent(true)
    ->set('deploy_path', '/var/www')
    ->set('branch', 'development')
    ->set('composer_action', 'update');

// Tasks

/**
 * Setup the environment file in the new release
 */
desc('Environment file setup');
task('environment', function () {
    run('ln -s {{deploy_path}}/.env {{release_path}}/.env');
});
after('deploy:vendors', 'environment');

/**
 * Ensure composer has a clear cache
 */
desc('Clear Composer Cache');
task('composercache', function () {
    run('composer clearcache');
});
before('deploy:vendors', 'composercache');

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

```

### Output log

I can't get this as the deployment was successful last time I ran it, and as I have a large team, I can't force it to fail with people needing the server. If it is imperative, I can try and fail it at some point.

**Comment by antonmedv** [comment]
Should be fixed in master. Please check.
