### ISSUE TITLE
Set revision variable even if option is not used

### ISSUE THREAD

**Issue by alterphp** [deployphp/deployer#1572]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

I'd like to know, during deployment, the revision being deployed. Even if I don't use the `revision` option. I think it should be achieved globally, to always have access to this information.

My main use case is when I need to clear opcode cache, I want to be sure it is achieved by returning the revision of the release considered by opcode cache.

What do you think ?

**Comment by antonmedv** [comment]
Done!
