### ISSUE TITLE
General 'git error' when deploying

### ISSUE THREAD

**Issue by lukashillebrand** [deployphp/deployer#1573]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.1
| Local Machine OS  | Mac OSX
| Remote Machine OS | Linux Server

### Description 
I'm new to PHP deployer and either a full-stack dev. I wanna deploy to a server. 
Maybe the issue is related with SSH keks on our Gitlab Repo? Thanks :-)

### Content of `hosts.yml`
jenny.nexxo.me:
    stage: dev
    user: p434960
    port: 22
    deploy_path: /home/www/p434960/html/dev
    branch: master
    configFile: ~/.ssh/config
    identityFile: ~/.ssh/id_rsa
    # sshOptions:
    #     UserKnownHostsFile: ~/.ssh/known_hosts
    #     StrictHostKeyChecking: no

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/common.php';

 inventory('hosts.yml');

// Configuration
set('repository', 'git@gitlab.nexxo.me:nexxo/jenny.git');
set('writable_dirs', []);
add('shared_files', []);
set('shared_dirs', []);
set('log_file', 'deploy.log');

// Tasks
desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

after('deploy:failed', 'deploy:unlock');
```

### Output log
dd -vvv
✈︎ Deploying master on jenny.nexxo.me
• done on [jenny.nexxo.me]
➤ Executing task deploy:prepare
[jenny.nexxo.me] > echo $0
[jenny.nexxo.me] < ssh multiplexing initialization
p434960@jenny.nexxo.me's password:
[jenny.nexxo.me] < Last login: Thu Mar 22 17:39:03 CET 2018 from 189.216.67.172 on ssh

[jenny.nexxo.me] < bash
[jenny.nexxo.me] > if [ ! -d /home/www/p434960/html/dev ]; then mkdir -p /home/www/p434960/html/dev; fi
[jenny.nexxo.me] > if [ ! -L /home/www/p434960/html/dev/current ] && [ -d /home/www/p434960/html/dev/current ]; then echo 'true'; fi
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && if [ ! -d .dep ]; then mkdir .dep; fi
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && if [ ! -d releases ]; then mkdir releases; fi
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && if [ ! -d shared ]; then mkdir shared; fi
• done on [jenny.nexxo.me]
✔ Ok [44s 845ms]
➤ Executing task deploy:lock
[jenny.nexxo.me] > if [ -f /home/www/p434960/html/dev/.dep/deploy.lock ]; then echo 'true'; fi
[jenny.nexxo.me] > touch /home/www/p434960/html/dev/.dep/deploy.lock
• done on [jenny.nexxo.me]
✔ Ok [1s 169ms]
➤ Executing task deploy:release
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (if [ -h release ]; then echo 'true'; fi)
[jenny.nexxo.me] < true
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (rm -rf "$(readlink release)")
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (rm release)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (if [ -d releases ] && [ "$(ls -A releases)" ]; then echo 'true'; fi)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (if [ -d /home/www/p434960/html/dev/releases/1 ]; then echo 'true'; fi)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (date +"%Y%m%d%H%M%S")
[jenny.nexxo.me] < 20180322174901
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (echo '20180322174901,1' >> .dep/releases)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (mkdir /home/www/p434960/html/dev/releases/1)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[jenny.nexxo.me] > cd /home/www/p434960/html/dev && (ln -nfs /home/www/p434960/html/dev/releases/1 /home/www/p434960/html/dev/release)
• done on [jenny.nexxo.me]
✔ Ok [5s 924ms]
➤ Executing task deploy:update_code
[jenny.nexxo.me] > if hash command 2>/dev/null; then echo 'true'; fi
[jenny.nexxo.me] < true
[jenny.nexxo.me] > command -v 'git'
➤ Executing task deploy:failed
• done on [jenny.nexxo.me]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[jenny.nexxo.me] > rm -f /home/www/p434960/html/dev/.dep/deploy.lock
• done on [jenny.nexxo.me]
✔ Ok [595ms]

In Client.php line 96:

  [Deployer\Exception\RuntimeException (1)]
  The command "command -v 'git'" failed.

  Exit Code: 1 (General error)

  Host Name: jenny.nexxo.me

  ================

Exception trace:
 Deployer\Ssh\Client->run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/functions.php:304
 Deployer\run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/functions.php:758
 Deployer\locateBinaryPath() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/recipe/common.php:106
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Configuration/Configuration.php:87
 Deployer\Configuration\Configuration->get() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/functions.php:537
 Deployer\get() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/recipe/deploy/update_code.php:51
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Task/Task.php:105
 Deployer\Task\Task->run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Console/TaskCommand.php:142
 Deployer\Console\TaskCommand->execute() at /Users/lukashillebrand/Sites/jenny/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /Users/lukashillebrand/Sites/jenny/vendor/symfony/console/Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at /Users/lukashillebrand/Sites/jenny/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /Users/lukashillebrand/Sites/jenny/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/src/Deployer.php:331
 Deployer\Deployer::run() at /Users/lukashillebrand/Sites/jenny/vendor/deployer/deployer/bin/dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

**Comment by antonmedv** [comment]
Try to run this in server: `command -v 'git'` and clone manually.

**Comment by lukashillebrand** [comment]
When I SSH into my server it dosen't recognise this command: `command -v 'git'`. Can you explain with more detail how I could debug this? Thanks!

**Comment by antonmedv** [comment]
Check if git installed on server.

**Comment by antonmedv** [comment]
Set git bin directly in deploy.php code: `set('bin/php', '...');`

**Comment by liugaohua** [comment]
how to resolved?

**Comment by antonmedv** [comment]
Try to use git tty.
