### ISSUE TITLE
test and testLocally do not work as documented

### ISSUE THREAD

**Issue by TankTheFrank** [deployphp/deployer#1577]
Now test and testLocally do this

```
"if $command; then echo 'true'; fi" === 'true'
```

which works as long as the command itself has no output. This makes it rather useless to test if the command is successful or not.

Given how 'test' and 'testLocally' are documented this is clearly a bug - I would expect test('ls') to behave like "if ls; then ..." in sh/bash/zsh whatever. Or, with your example, "[ ls ]" in shell is true, in deployer test('ls') is false.

Redirecting output to /dev/null for every single command or writing a custom function is always an option but as they are now test and testLocally are traps.

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.1.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce

run with 'testLocally' something that has an output

### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by antonmedv** [comment]
I know how to this it and maybe going to do it in v7. 

But what do you expect from `[ ls ]`?

**Comment by TankTheFrank** [comment]
[ ls ] is just an example to reproduce the issue. My particular use case was checking if a git branch exists or not.

**Comment by antonmedv** [comment]
Okay, please show real example of problem. Looks like everything is normal for me now.
