### ISSUE TITLE
[Request] New recipe specific for Laravel 5.6

### ISSUE THREAD

**Issue by neorganic** [deployphp/deployer#1581]
| Q                 | A
| ----------------- | ---
| Issue Type        | Request

Hello, so in Laravel 5.6 ``artisan:optimize`` is no more relevant and can be removed. Will update this, but I believe some other changes have been since then.

**Comment by antonmedv** [comment]
Should be fixed: https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L113-L116
