### ISSUE TITLE
magento 2.2 receipe autload error in remote server

### ISSUE THREAD

**Issue by sivajik34** [deployphp/deployer#1587]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
                                                                                                                                             
  ================                                                                                                                            
  Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.                               
                                                                                                                                              

Exception trace:
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:304
 Deployer\run() at phar:///usr/local/bin/dep/recipe/magento2.php:50
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:155
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:331
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/magento2.php';
inventory('hosts.yml');
// Project name
set('application', 'nthrive');
set('default_stage', 'staging');
// Project repository
set('repository', 'git@gitlab.com:fff/ggg.git');


set('writable_mode','chmod');

task('magento:enable', function () {
    run("pwd");
});

  
 task('deploy:update_code', function () {
   run("cd /home/nthrive/public_html && git checkout test.php && git pull origin develop");
});  

// Tasks

desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:magento',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] If deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by antonmedv** [comment]
> Please run 'composer install' under application root directory.

**Comment by sivajik34** [comment]
how to tell in deploy.php to run from application root directory.
there are two things deploy_path,release_path.
its trying to run release_path .

**Comment by antonmedv** [comment]
Override `deploy:vendor` task.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
