### ISSUE TITLE
Using "add" in a host overwrites global configuration

### ISSUE THREAD

**Issue by brunodevel** [deployphp/deployer#1588]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.1.0
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | N/A

### Description 
It seems like using `add` in a host overwrites the global `shared_dirs` configuration.
Is that an expected behavior?

### Steps to reproduce
Set global `shared_dirs` and then add new dirs per host.
The global `shared_dirs` are not created during deployment.
In the example below, `public/global/dir` would not be created.

### Content of `deploy.php`
```php
add('shared_dirs', [
    'public/global/dir',
]);

host('production')
    ->add('shared_dirs', [
        'public/specific/host/dir',
    ]);
```

**Comment by antonmedv** [comment]
Will fix it in v6.1

**Comment by antonmedv** [comment]
Actually this requires some major refactoring, so I think it will go to v7. :(

**Comment by antonmedv** [comment]
...and now it's fixed!!!!
