### ISSUE TITLE
How to set absolute path in "Specify Deployer File" (-f, --file) on Windows

### ISSUE THREAD

**Issue by a-r-m-i-n** [deployphp/deployer#1590]
`dep -f"C:\Path\To\deploy.php"` will be converted to `C:\current\working-dir/C:/Path\To\deploy.php` because it always prepends the current working directory, when the given path does not start with a slash. But this will fail on Windows, always, cause you need to prepend the drive letter.

Cygwin would work, but this should also work on native Windows CLI, imo.

**Comment by ArminVieweg** [comment]
Btw. when you change

```
$deployFile = ($userSpecifiedFile[0] === '/' ? '' : getcwd() . '/') . $userSpecifiedFile;
```
To
```
$deployFile = ($userSpecifiedFile[0] === '/' || preg_match('/^\w{1,2}\:.*/', $userSpecifiedFile) ? '' : getcwd() . '/') . $userSpecifiedFile;
```

It also works for absolute Windows paths. It checks not just for starting /, it also checks for "C:" or even "AB:" using a simple regular expression.

**Comment by antonmedv** [comment]
Done!
