### ISSUE TITLE
download() not respecting --copy-links option

### ISSUE THREAD

**Issue by colinodell** [deployphp/deployer#1596]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.1
| Local Machine OS  | Ubuntu 17.10
| Remote Machine OS | Ubuntu 16.04

### Description 

`download()` uses rsync to transfer the files.  You have the ability to provide options to the `rsync` command, but `-azP` are defined by default.  Per the man page, using the `a` flag also turns on the `l` flag:

```
 -l, --links                 copy symlinks as symlinks
 -L, --copy-links            transform symlink into referent file/dir
```

`-l` and `-L` are opposites.  I'm therefore unable to have `rsync` resolve symlinks for me prior to downloading files (which I have the need for in one particular task) because rsync is using both the `-a` flag and `-L`, thus ignoring the latter one.

### Suggested Fix

Provide a way to override/remove/avoid the default options

### Steps to reproduce

1. Create a symlink on the remote server
2. Run `download('path/to/symlink', "path/to-local", ['--copy-links']);`
3. Notice that rsync downloads a broken symlink, not the referent file

### Content of `deploy.php`
The only important line is `download('path/to/symlink', "path/to-local", ['--copy-links']);`

### Output log
Nothing special - the download succeeds but you get a broken symlink

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
