### ISSUE TITLE
shared_dirs and shared_files per staging?

### ISSUE THREAD

**Issue by dkorpar** [deployphp/deployer#1597]
| Q                 | A
| ----------------- | ---
| Issue Type        |Question
| Deployer Version  | 6.1.0
| Local Machine OS  | macOS High Sierra
| Remote Machine OS | N/A

### Description 
How to configure `shared_files` or `shared_dirs` to be added only to predefined stages? The idea is to configure shared files for all stages and for specific ones to add more shared files. The code below shows my attempt:

### Steps to reproduce
Run `dep deploy production`. Expected result is to have shared file `a`.
Run `dep deploy local`. Expected result is to have shared files `a` and `b`. Only `b` is shared.

### Content of `deploy.php`
```php
set('shared_files', ['a']);

task('deploy:shared:reports', function () {
    add('shared_files', ['b']);
})->onStage(['local', 'develop']);
```

**Comment by antonmedv** [comment]
Not it's possible only by getting all stage and then setting back.
Try this:
```php
set('shared_files', ['a']);

task('deploy:shared:reports', function () {
    set('shared_files', get('shared_files') + ['b']);
})->onStage(['local', 'develop']);
```

**Comment by antonmedv** [comment]
In v7 where will be new function: `stage('production', function () {...})` there you can configure stage more easily.

**Comment by dkorpar** [comment]
Thanks! That would be handy to configure stages that way.
