### ISSUE TITLE
Call to undefined method Deployer\Server\Builder::path()

### ISSUE THREAD

**Issue by tomzx** [deployphp/deployer#160]
I'm currently trying out master @ 293d9f7e13960516a3f78a2ebbf3eda7a5cad9de and I get the following errors running

```bash
PHP Fatal error:  Call to undefined method Deployer\Server\Builder::path() in deploy.php on line 6
```

Here is the deploy.php (stripped anything that isn't useful to this issue).

```php`
<?php

require_once 'recipe/common.php';

server('production', '192.168.2.100')
	->user('www-data')
	->path('/var/www/test-target');
```

It appears that @ 503e19234ca4a5ede62b155ee003271401fb950c, you did a major refactoring which removed `path()` from Configuration.

What will be the way the `path` is defined in v3? Will it be through `set('deploy_path', '/var/www/test-target');`?

**Comment by elfet** [comment]
Yes, it will be `->env('deploy_path', '/var/www/test-target');`.
Doc for v3 will be latter sorry about this.

**Comment by tomzx** [comment]
Duplicate of #153.

**Comment by gordalina** [comment]
Actually, this should be in an UPGRADING.md file (like symfony does)
