### ISSUE TITLE
Compatibility with the Win32 port of OpenSSH

### ISSUE THREAD

**Issue by marcharding** [deployphp/deployer#1600]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.2.0
| Local Machine OS  | Windows
| Remote Machine OS | Ubuntu 16.04

### Description 
When using the [Win32 port of OpenSSH](https://github.com/PowerShell/openssh-portable) the ssh command needs to be enclosed by double quotes, because windows executables need double quotes for arguments.

E.g. (when using the Win32 port of OpenSSH)

```
> ssh.exe test@example.com 'echo "foobar"'
bash: echo foobar: command not found
```

```
> ssh.exe test@example.com "echo 'foobar'"
foobar
```

The Client class produces a command with single quotes, see https://github.com/deployphp/deployer/blob/master/src/Ssh/Client.php#L86

When one changes this to 

`$ssh = "ssh $sshArguments $host $become \"$shellCommand; printf '[exit_code:%s]' $?;\"";` 

it will work with the windows ssh.exe, but then shell expansion would be applied to the $shellCommand ($var would be evaluated), which could cause problem (although that change works fine for me).

One way around this, would be to check which ssh.exe is used and then apply the correct quoting style (when using windows $var will not be evaluated, so it should be safe).

```
$sshVersionProcess = new Process('ssh -V');
$sshVersionProcess->run();
// the version info is on STDERR
if(strpos($sshVersionProcess->getErrorOutput(), 'OpenSSH_for_Windows') !== false){
    $ssh = "ssh $sshArguments $host $become \"$shellCommand; printf '[exit_code:%s]' $?;\"";
} else {
    $ssh = "ssh $sshArguments $host $become '$shellCommand; printf \"[exit_code:%s]\" $?;'";
}
```

It would be nice to get the version info only once, but i'm not sure where...

Should i create a pull request for my supposed solution?

### Steps to reproduce
Execute deployer deploy with the Win32 port of OpenSSH.

**Comment by marcharding** [comment]
This will probably fix https://github.com/deployphp/deployer/issues/1436.

Maybe one could only rely on just checking if php is run from windows or not (with the PHP_OS-constant) since when it is run from windows, it will need double quotes regardless where ssh.exe comes from (e.g. the older one mentioned in 1436)

**Comment by RdeWilde** [comment]
I ended up merging all the fixes.
https://github.com/digizijn/deployer/

**Comment by marcharding** [comment]
I ended up using capistrano again 😉

**Comment by dionysiosarvanitis** [comment]
Works for me on Windows 10.

**Comment by AzeredoGabriel** [comment]
@marcharding it works for me too. Try submit a PR to fix this.

**Comment by antonmedv** [comment]
Is it working now? Ok to close?
