### ISSUE TITLE
Documentation / Information regarding the Drupal 7 Recipe - drupal:settings

### ISSUE THREAD

**Issue by frederickjh** [deployphp/deployer#1603]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | master
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
The Drupal 7 recipe includes a **drupal:settings** task. However how to configure it is not clear even tracing through the history of that file. Originally the configuration was in a [secrets.yml](https://github.com/deployphp/deployer/commit/f0906e600d11998a8175d9b92743125b189bf557#diff-d57ba144b92c6c5e688db132b10eba5d) file. Then this got [moved to the servers.yml file](https://github.com/deployphp/deployer/commit/1d56af69762dc3e10d86d61f0e2b0057e1a53db7#diff-9ad9fdf125afa9036166eb7d16f986b4).
I found that in version 5 [servers was renamed hosts](https://deployer.org/docs/servers).

@sergiocarracedo is the developer listed in the recipe, so I am hoping that he or another developer can chime in and provide some information that should really be in the documentation. For me a sample of the configuration file would be enough.
Thanks for your time and help!
Frederick

**Comment by sergiocarracedo** [comment]
Hi @frederickjh, I think drupal:settings still working in version 5, but I will test task in version 5, and create clear documentation.

**Comment by frederickjh** [comment]
@sergiocarracedo  A example **hosts** file with the secrets in it to create a settings.php would enough for me now to move forward. I can test with that if it helps.

**Comment by sergiocarracedo** [comment]
There was a bug in recipe, it tried to use deployer path to find settings.php template, but that is incorrect.
I created a pull request who contains bugfix https://github.com/deployphp/deployer/pull/1613

Here is my example deployer config:
`host('vagrant')
  ->port('2222')
  ->user('vagrant')
  ->set('deploy_path', '/home/vagrant/deployer')
  ->set('database.name', 'localhost')
  ->set('settings_template', __DIR__ . DIRECTORY_SEPARATOR . 'settings.php.template')
  ->set('settings', [
    'database.name' => 'db_name',
    'database.username' => 'db_username',
    'database.password' => 'db_password',
    'database.host' =>  'db_host'
  ])
  ->set('branch', 'master')
  ->set('drupal_site', $drupal_site)
  ->stage('vagrant');`

And settings.php.template contains:
`
$databases = array (
  'default' =>
    array (
      'default' =>
        array (
          'database' => '{{database.name}}',
          'username' => '{{database.username}}',
          'password' => '{{database.password}}',
          'host' => '{{database.host}}',
          'port' => '',
          'driver' => 'mysql',
          'prefix' => '',
        ),
    ),
);
`
Full content https://pastebin.com/4UiRcN6D

You can set other variables in settings array and set {{variablename}} in settings.php

**Comment by sergiocarracedo** [comment]
Merged! https://github.com/deployphp/deployer/pull/1613

**Comment by frederickjh** [comment]
Thanks @sergiocarracedo!

Here are the examples with formatting.

#### example deployer config:
```bash
host('vagrant')
     ->port('2222')
    ->user('vagrant')
    ->set('deploy_path', '/home/vagrant/deployer')
    ->set('database.name', 'localhost')
    ->set('settings_template', __DIR__ . DIRECTORY_SEPARATOR . 'settings.php.template')
    ->set('settings', [ 
    'database.name' => 'db_name',
    'database.username' => 'db_username',
    'database.password' => 'db_password',
    'database.host' => 'db_host'
    ])
    ->set('branch',
    'master')
    ->set('drupal_site', $drupal_site) ->stage('vagrant');
```

#### database array from settings.php.template
```php
$databases = array (
  'default' =>
    array (
      'default' =>
        array (
          'database' => '{{database.name}}',
          'username' => '{{database.username}}',
          'password' => '{{database.password}}',
          'host' => '{{database.host}}',
          'port' => '',
          'driver' => 'mysql',
          'prefix' => '',
        ),
    ),
);
```

This should get tagged to be added to the non-existent documentation for the included recipes.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
