### ISSUE TITLE
Filter servers

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#161]
How do I filter actions to only one server inside a task?

**Comment by elfet** [comment]
Now it does not possible to do (I think). You can only create task for a specified server:
```php
task(...)->onlyOn('server');
```

Why do you need this functionality? If you can explain why this functionality needed for, I'll think about implementation.

**Comment by EkAndreas** [comment]
I'm using the Deployer to pull data and files from the production to my Vagrant development environment (Bedrock).
In that case I just want to do the pull to this single machine and not to the server.

I'm really happy to use the Deployer instead of Capistrano. I'm not a fan of Ruby :-)

Thanks!

:+1:
