### ISSUE TITLE
Add support for + in --roles option

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1610]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 7.0

### Description 
Implement `+` for roles filtering:
```
--roles drupal7+active,drupal6+active
```

### Issues
#1608

**Comment by bahl24** [comment]
Hey, I am a newbie and looking for an easy bug fix. Can I take up this issue for #hacktoberfest

**Comment by reneroboter** [comment]
@antonmedv I will do it. I'm started and almost finished but I guess I found not working tests in `HostSelectorTest`. Maybe I had made a mistake (... missing configuration or something like that), but at the moment I think the Deployer instance is not mocked in some test cases.

**Comment by reneroboter** [comment]
Ignore my last comment. I had troubles with my phpunit configurations. Now the tests runs successfully and I had updated my forked repo. In the next step I want to update the `CHANGELOG.md`. However I'm not sure if I should add this for the next minor version or added it to the next major version. Perhaps you can help me @antonmedv.

**Comment by antonmedv** [comment]
Just run `php bin/changelog` and follow instructions. Make sure your CHANGELOG.md file is unchanged before starting.
