### ISSUE TITLE
Is it possible to set hosts in an array?

### ISSUE THREAD

**Issue by sinbadxiii** [deployphp/deployer#1612]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  |  6.2.0

### Description 

Hi!

Is it possible to set hosts in an array?

$hosts = [
   'example.com',
   'example2.com',
   'example3.com'
];

host($hosts)
    ->user('ankas')
    ->port(1322)
...

**Comment by antonmedv** [comment]
Yes: `host(...$hosts)`.

**Comment by sinbadxiii** [comment]
O!  thanks
