### ISSUE TITLE
Timing updates/tracking

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1614]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request

### Description 
It would be nice to show some more information by default, eg. the estimated time for tasks (based on previous deployments), the task/total duration and perhaps and updating time how long it's busy. For some longer tasks (Magento2 compilation/assets etc) it can take multiple minutes (depending on server and configuration), so some feedback would be nice :)

**Comment by antonmedv** [comment]
It will be cool to have. I think for something like this for next major version.

**Comment by freestyledork** [comment]
I also would like to see this. Using npm install/build can take some time as well and it would be helpful to see a running time.

**Comment by staabm** [comment]
@barryvdh does https://github.com/deployphp/deployer/pull/1564 help you?

**Comment by barryvdh** [comment]
No, I meant the time it takes to process task on the server.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
