### ISSUE TITLE
After rollback deployer points to incorrect version for disassociate

### ISSUE THREAD

**Issue by dPhantum** [deployphp/deployer#1615]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v5.1.3
| Local Machine OS  | Linux/aws
| Remote Machine OS | linux

### Description 
I did a rollback on my live site:
dep deploy [branch-name]
and can no longer deploy new source moving forward. It is attempting to dissociate the directory/release which I rolled back, and so the deploy command doesn't seem to be in sync with the rollback which as changed the current release, because deploy is still looking at the highest release version, not the highest -1, which is now the current.

### Steps to reproduce
dep deploy rollback [name]
dep deploy [name]

### Content of `deploy.php`
```php
CONTENT
```
### Output log
*With enabled option for verbose output `-vvv`.*
✔ Executing task deploy:unlock

In Process.php line 239:
                                                                                          
  The command "ssh -A -tt -i /home/user/dir/../keys/deploy.pem user@<ip.address> '/u  
  sr/bin/git clone -b <branch-name> --recursive -q --reference /home/user/app/releases/97 -  
  -dissociate git@github.com:account/site.git  /home/user/app/releases/98 2>&1'" failed  
                                                                                          
  Exit Code: 128(Invalid exit argument)                                                                                                                                             
  Working directory: /home/ussa/deploy                                                    
                                                                                          
  Output:                                                                                 
  ================                                                                        
                                                                                          
  Error Output:                                                                           
  ================                                                                        
deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

The current directory pointers are as such:
On prod you can see the release pointers are:
lrwxrwxrwx 1 user user       11 May 16 02:34 current -> releases/95
lrwxrwxrwx 1 user user       11 May 16 18:17 release -> releases/97
￼￼￼￼￼
current is 95.

Ending up deleting the release directories and re-deploying to fix.

**Comment by antonmedv** [comment]
Just checked rollback on my prod site. Everything works fine. Can you show step by step how to reproduce?

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
