### ISSUE TITLE
dep ssh with error "cd xxx/current: No such file or directory"

### ISSUE THREAD

**Issue by Yelfive** [deployphp/deployer#1616]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.2.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Deployer is a great tool, and thanks for this project. However when #I use `dep ssh` into the server defined in `deployer.php`, and got error

```text
cd: /srv/webroot/xxx/current: No such file or directory
```

My server indeed doesn't have directory `current`, the deploy strategy is based on `git` tags, so I suppose there's no need for that.

And when I tried to find the solution I found the hard coded

```php
passthru("ssh -t $options $host 'cd '''$deployPath/current'''; exec \$SHELL -l'");
```

on `deployer/src/Console/SshCommand.php:87`

So my question is, is it possible in the future release maybe the hard coded path `current` can be configurable.

**Comment by Yelfive** [comment]
Cool, looking forward to that

**Comment by jan-wilhelm** [comment]
I'm experiencing the same issue, please fix this!

**Comment by deltatag** [comment]
A temporary workaround could be to set an default directory for the user via shell configuration file (e.g. .bashrc) like:
```shell
cd /path/to/your/deploy-path
```

**Comment by rajakhoury** [comment]
same issue here on Win 10 (default CMD) but using Git Bash solves the problem

**Comment by antonmedv** [comment]
Fixed in master. Please verify.
