### ISSUE TITLE
Deployer on windows 10 

### ISSUE THREAD

**Issue by webbyen** [deployphp/deployer#1617]
Need some help.

While running the following command
mv deployer.phar /usr/local/bin/dep

I get the following message 
mv: cannot create regular file '/usr/local/bin/dep': No such file or directory
it seems /usr/local/bin/dep does not exist. 
what will the right location on Windows 

Thanks a lot

**Comment by antonmedv** [comment]
Depends on your work flow. Will write better docs on using deploeyer on windows.

**Comment by MartDSam** [comment]
Is there no tutorial on how to install windows along with slack? I'm also having trouble finding some tutorial or information to help me.

**Comment by kl3sk** [comment]
I had the same problem and resolved it like this:

Remove openSSH client on WIndows 10 [You can check this tutorial](https://www.pcastuces.com/pratique/astuces/5235.htm) (fr) [or](https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/) (en)

Those tuts explains how to enable it, just disable it instead ;)

Then I use [Cmder](https://cmder.net/) and everything works well.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
