### ISSUE TITLE
WordPress Blog Folder Get Deleted When run dep deploy command

### ISSUE THREAD

**Issue by webbyben** [deployphp/deployer#1619]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

Hi,
I have installed a Wordpress blog on current/public/blog folder. When I run dep deploy command the blog folder gets deleted. 

What is the best way to handle this situation?

**Comment by antonmedv** [comment]
Yes
