### ISSUE TITLE
dont checkout full git repository on every release

### ISSUE THREAD

**Issue by Flyingmana** [deployphp/deployer#162]
we have a very big main repository, which is not a problem for a normal deploy via git, but it is with this tool, as it does not update the git on a central place but creates a complete new checkout on every run.

**Comment by elfet** [comment]
git pull?

**Comment by Flyingmana** [comment]
https://github.com/deployphp/deployer/blob/master/recipe/common.php#L80

**Comment by elfet** [comment]
Yes, i think we need to add `--deep` option.

**Comment by Flyingmana** [comment]
that reduces problems with big history, but not with big checkouts.
You would need to use something pull based, or somehow allow usage of the --reference flag.
But this needs maybe some bigger refctoring.

**Comment by tomzx** [comment]
#163 is probably what you're looking for.

**Comment by KennedyTedesco** [comment]
Shallow clone solves my problems.

**Comment by elfet** [comment]
Done.
