### ISSUE TITLE
Run tasks on default role, add extra roles for single option

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1620]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
When all tasks should run on 1 server, but just one commando on different server, it's currently hard to do this, you have to add it to all tasks, even the default ones.  It  is complicated further by https://github.com/deployphp/deployer/issues/1313

Usage could be something like:

```php
host('www.domain.com')
    ->roles(['web']);

host('db.domain.com')
    ->roles(['db']);

set('default_roles', ['web']);

task('deploy', [
    'deploy:update_code',
    'migrate',
    'deploy:unlock',
]);

desc('Migrate database');
task('migrate', function () {
    ...
})->onRoles('db');
```

And all tasks should be run on `web`, only `migrate` should run on database.

Similar to https://github.com/deployphp/deployer/issues/1409

**Comment by antonmedv** [comment]
I see. I think we can find some solution for upcoming v7. What others do for this problem? Like ansible?

**Comment by antonmedv** [comment]
v7 now have a new concept of selectors what is exactly what you are looking for.
