### ISSUE TITLE
Default file/folder permission too high

### ISSUE THREAD

**Issue by lakshmana** [deployphp/deployer#1621]
Hi there,

When I deploy the files on the server, the default file and folder permissions turns out to be 664 and 775. I perfer it to be 644 and 744 instead as there is no reason to have write permission for the group user. Is there any configuration that I missed for this change ?

My workflow is as follows:
- file permission is set as 644
- the file is commit and push to the remote git repo
- deployer updates the files on server by running a task
- now the file permission turns out to be 664! 

Thx
Laxman

**Comment by antonmedv** [comment]
Currently permissions doesn't setted by deployer. Only git clone combined.

**Comment by lakshmana** [comment]
@antonmedv, it is very unclear what your are trying to say. Git does not store file permissions, does it ?

**Comment by antonmedv** [comment]
Try do this on server: `git clone git@repo` 

What permissions?

**Comment by lakshmana** [comment]
@antonmedv when I git clone, I have 644 permission. That is why I posted as an issue.

**Comment by lakshmana** [comment]
@antonmedv the permissions are 664 with git clone on server. I guess this means I have to change the default permission for this user on server, right ? How can I do this ?

Thx

**Comment by antonmedv** [comment]
Yes, google umask

**Comment by lakshmana** [comment]
superb, thx @antonmedv I will try it.

**Comment by dharkness** [comment]
Is it possible to set umask with Deployer so we don't have to make every user change it themselves?
