### ISSUE TITLE
symfony/console v4.0.9 requires php ^7.1.3

### ISSUE THREAD

**Issue by mikebranderhorst** [deployphp/deployer#1623]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.2.0

### Description 
Deployer cannot be installed by composer with PHP versions less than 7.1.3 due to dependency requirements.

symfony/console 3 requires PHP ^5.5.9|>=7.0.8
https://packagist.org/packages/symfony/console#v3.4.10

symfony/console 4 requires PHP ^7.1.3
https://packagist.org/packages/symfony/console#v4.0.0

deployer/deployer 6.2.0 requires PHP ~7.0 (< this is incorrect, must be ^7.1.3 or change the dependency symfony/console to use PHP 7.0)
https://packagist.org/packages/deployer/deployer

### Steps to reproduce
```
$ composer global require deployer/deployer
```

### Output log
```
$ composer global require deployer/deployer
Changed current directory to /Users/mike/.composer
Using version ^6.2 for deployer/deployer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/console v4.0.9 requires php ^7.1.3 -> your PHP version (7.0.30) does not satisfy that requirement.
    - symfony/console v4.0.9 requires php ^7.1.3 -> your PHP version (7.0.30) does not satisfy that requirement.
    - symfony/console v4.0.9 requires php ^7.1.3 -> your PHP version (7.0.30) does not satisfy that requirement.
    - Installation request for symfony/console (locked at v4.0.9) -> satisfiable by symfony/console[v4.0.9].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by antonmedv** [comment]
Try using older version of deployer: https://deployer.org/download

**Comment by mikebranderhorst** [comment]
That is not the point. Version 6.2.0 has a dependency conflict. 

"php": "**~7.0**"
https://github.com/deployphp/deployer/blob/v6.2.0/composer.json#L30

"symfony/console": "~2.7|~3.0|**~4.0**"
https://github.com/deployphp/deployer/blob/v6.2.0/composer.json#L33

**Comment by antonmedv** [comment]
I see. Maybe update php deps.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
