### ISSUE TITLE
Problem detecting $httpUser on system running Prometheus exporter nginx-vts-exporter

### ISSUE THREAD

**Issue by w0rd-driven** [deployphp/deployer#1629]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.2.0
| Local Machine OS  | macOS Sierra 10.12.6 (16G1408)
| Remote Machine OS | Ubuntu 16.04.4 LTS

### Description 
The problem originates on this line https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php#L27. Running the first portion `ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root` on the affected host yields these results:
```
nginx-vts-expor prometheus-exporter
nginx           www-data
```

Adding in the next part of the pipe, `ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1`, shows
```
nginx-vts-expor prometheus-exporter
```

The user returned to $httpUser is `prometheus-exporter` and not `www-data` as we expect.

The solution seems simple enough and it just involves adding a space after nginx. There's also apache_exporter so it may be a good idea to add a space after apache or just add spaces after every section. The full line would be `$httpUser = run("ps axo comm,user | grep -E '[a]pache |[h]ttpd |[_]www |[w]ww-data |[n]ginx ' | grep -v root | head -1 | awk '{print $2}'");`

It's simple enough that I don't mind completing the PR but I don't know how pressing this is for other people. Fortunately in my case the user deploying is also the owner of the directories so the fix isn't really pressing but I can see a future where it could be.

Also to take a second, thank you for this project. It doesn't take much to get up and running and the flexibility I've been able to achieve is rarely matched by anything else I work with.

**Comment by antonmedv** [comment]
Thanks. I was also thinking about to move regexp to php code for flexibility.
