### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [deployphp/deployer#1631]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by antonmedv** [comment]
@mirzazulfan hi, actually I'm looking for a new logo for sometime already. What to change in from paper plane. 
If you can create new logo it will be super cool.

**Comment by mirzazulfan** [comment]
Okay. I'll do my best. give me time and i'll show it to you.

**Comment by mirzazulfan** [comment]
Hi @antonmedv ,, I've designed a logo for you. Tell me if you need something else i'll fix it. 
![dp](https://user-images.githubusercontent.com/36124339/41255397-984a7a46-6df0-11e8-9d3f-72883dadeb80.png)

**Comment by mirzazulfan** [comment]
How about this @antonmedv ?
![v2](https://user-images.githubusercontent.com/36124339/41475878-06eba3ac-70ea-11e8-9e55-bcad21b9a3b7.png)

**Comment by antonmedv** [comment]
Better, but very dark

**Comment by mirzazulfan** [comment]
What do you think?
![v3](https://user-images.githubusercontent.com/36124339/41499617-0629f6e4-71ad-11e8-8a18-2957dad49cb6.png)

**Comment by antonmedv** [comment]
Better then first one, try to find professionals and ask them on how you can improve your skills. 
Also take a look on dribbble.com
