### ISSUE TITLE
Set debug mode inside task

### ISSUE THREAD

**Issue by lbngoc** [deployphp/deployer#1635]
I write a task to sync all files from local to host, but I want to run in rsync --dry-run mode first.
I used askConfirmation function to get user answer to use dry-run mode or not, but when run deployer on default mode, nothing in rsync --dry-run mode could be displayed
```
$ dep deploy:sync
➤ Executing task deploy:sync
Run in DRY mode? [y/N] y
✔ Ok
```
Is there any way to set debug mode or show rsync results when user select "y" and without "-vvv" option?

**Comment by antonmedv** [comment]
No, I think now there is no such API. I want to do something with in in next release of deployer and improve it.

**Comment by antonmedv** [comment]
Can do! `output()->setVerbosity(...)`;
