### ISSUE TITLE
bash: bash -s; printf  $?;: command not found

### ISSUE THREAD

**Issue by eminos** [deployphp/deployer#1640]
| Issue Type        Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Windows 10 (17134)
| Remote Machine OS | CloudLinux 7.5 (RedHat 7.5)

### Description 
I suddenly started getting this error with my fairly simple deployer script.

λ dep deploy production -vvv
➤ Executing task git:pull
[production] > cd /home/website/production.website.se && (git pull)
[production] < bash: bash -s; printf  $?;: command not found

In Client.php line 99:

  [Deployer\Exception\RuntimeException (-1)]
  The command "cd /home/website/production.website.se && (git pull)" failed.

  Exit Code: -1 (Unknown error)

  Host Name: production

  ================
  bash: bash -s; printf [exit_code:%s] $?;: command not found

---

Any clue what can be causing this? It used to work and I'm not sure what has changed either on the local machine or remote that started causing this error.

Running the command `cd /home/website/production.website.se && (git pull)` directly on the server works fine.

**Comment by antonmedv** [comment]
Check which (bash, dsh, etc) loaded on server for deployer.

**Comment by eminos** [comment]
Thanks for the fast reply @antonmedv.
How do I check that?

**Comment by eminos** [comment]
I've done some more digging.
If I ssh into the server and run `echo $0` I get `-bash`.
There are references to that in other issues here, but I'm not sure what it means and how to fix it.
The command in question `cd /home/website/production.website.se && (git pull)` still works if I run it manually on the server.

**Comment by eminos** [comment]
If I then run `bash` on the server and then `echo $0` again, I get `bash` as output (without the dash).

If I try this with the deployer script, the `bash` command fails.

```php
host('test')
    ->hostname('server')
    ->stage('dev')
    ->set('deploy_path', '/home/website/dev.website.se');

task('testbash', function () {
    run('bash');
    cd(get('deploy_path'));
    run('echo $0');
});
```

λ dep testbash test
➤ Executing task testbash

In Client.php line 99:

  The command "bash" failed.

  Exit Code: -1 (Unknown error)

  Host Name: test

  ================
  bash: bash -s; printf [exit_code:%s] $?;: command not found

**Comment by eminos** [comment]
I've fixed it by disabling Windows 10's SSH Client (Manage optional features) which was enabled by default in the April update.
Still can't get ssh multiplexing to work and have to disable it in the deployer script, so the deployment is slow, but at least it works now.

**Comment by RdeWilde** [comment]
I experienced exactly the same problems, some more descriptional error message would help.

**Comment by RdeWilde** [comment]
I cannot seem to remove the OpenSSH client, so I'm stuck here. I tried both thru Windows Apps and Powershell (Remove-WindowsCapability).

So any other way to solve this error? I already have multiplexing disabled. But the `bash` error remains

**Comment by RdeWilde** [comment]
Might be related with this one:
https://github.com/deployphp/deployer/issues/1600

**Comment by antonmedv** [comment]
Is it fixed now? Ok to close?
