### ISSUE TITLE
Many linux commands throw runtime exception when there is no error

### ISSUE THREAD

**Issue by husseycoding** [deployphp/deployer#1643]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

### Description 
I am running a set of commands using on() to execute on a host different to the one being deployed to, and am finding that most standard linux commands (i.e. rm, chmod, mkdir) are throwing a runtime exception even if everything is fine, and often even if all output is thrown away with for instance &>/dev/null etc.  The only solution I have found is to surround each command in a try...catch, but in order to get every command to run each one has to be individually wrapped as otherwise the 'exception' would cause all other tasks to stop running when the exception is thrown.

Firstly why are these commands throwing an exception?  It seems like any command with any kind of output is treated as failed and throws an exception which doesn't make a lot of sense.  Secondly there must be a better way to handle this than countless indiividual try...catch around each individual command?

I have seen that there are a few old tickets highlighting this issue going back some time, but none of them conclude there is better way to handle it than a try...catch.

### Content of `deploy.php`
Every command below throws an exception even when completing without issue.
```php
task('some:task', function() {
    on(host('some.host'), function ($host) {
        run("rm -rf /some/path/which/exists &>/dev/null");
        run("mkdir -p /some/other/path &>/dev/null");
        run("chmod g+ws /some/other/oath/which/exists");
    });
});
```

### Output log
Nothing useful in the log, each command just throws a general error:
Exit Code: 1 (General error)

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
