### ISSUE TITLE
dep ssh <stage>

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1644]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request

### Description 
Similar to `dep deploy production`, it would be nice to be able to do `dep ssh production`.
I understand that multiple hosts are possible, but in a lot of cases there aren't. So it could work as a filter, similar to `dep ssh`. 

- 1 host for that stage = connect to that host
- multiple hosts = show all hosts for that stage

**Comment by nsrosenqvist** [comment]
@barryvdh I just signed on to submit the same issue! I guess it's not just me :)

**Comment by antonmedv** [comment]
Check out new version in master!
