### ISSUE TITLE
How to auto deploy on push to repo?

### ISSUE THREAD

**Issue by mirkhamidov** [deployphp/deployer#1645]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
How to make to deploy on push to repository (bitbucket, github, gitlab)?
I cand find any docs for that.
Thanks

**Comment by antonmedv** [comment]
Soon I’ll publish new service for it – Deployer CI

**Comment by mirkhamidov** [comment]
@antonmedv great hear))
is there an approximate publication time?

**Comment by antonmedv** [comment]
No, but i hope soon

**Comment by martinbertinat** [comment]
Any news on this? @antonmedv :)

**Comment by antonmedv** [comment]
Soon will be public beta, stay tuned. :)

**Comment by asafov** [comment]
For example catch webhook, connect by SSH to server with deployer and exec dep deploy.

**Comment by lucasdcrk** [comment]
Can't wait to take part in this beta!
Any news @antonmedv :) ?

**Comment by antonmedv** [comment]
Actuallly I'm working on `dep web` command which will open web-page with deploy buttons!!
