### ISSUE TITLE
Laravel recipe - Storage folder is untracked

### ISSUE THREAD

**Issue by eleftrik** [deployphp/deployer#1647]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.5
| Local Machine OS  | Mac OS 10.13.5
| Remote Machine OS | Debian 9

### Description 
I'm using the Laravel recipe.
After successfully running `dep deploy`, inside the `current` folder on the remote server I got this GIT status:

```
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json
	deleted:    storage/app/.gitignore
	deleted:    storage/app/public/.gitignore
	deleted:    storage/debugbar/.gitignore
	deleted:    storage/framework/.gitignore
	deleted:    storage/framework/cache/.gitignore
	deleted:    storage/framework/sessions/.gitignore
	deleted:    storage/framework/testing/.gitignore
	deleted:    storage/framework/views/.gitignore
	deleted:    storage/logs/.gitignore
	deleted:    storage/tinx/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	storage
```

How can I avoid having untracked files/directories?

Thank you

**Comment by eleftrik** [comment]
@antonmedv Is this the right solution?
I'm asking because stock `.gitignore` file in Laravel contains

`/storage/*.key`

Not all the `storage` folder is .gitignored

**Comment by eleftrik** [comment]
@antonmedv Yes.

The output of `git ls-files | grep storage` is

```
storage/app/.gitignore
storage/app/public/.gitignore
storage/debugbar/.gitignore
storage/framework/.gitignore
storage/framework/cache/.gitignore
storage/framework/sessions/.gitignore
storage/framework/testing/.gitignore
storage/framework/views/.gitignore
storage/logs/.gitignore
```

According to stock Laravel's `.gitignore` file, I think this is the correct behaviour, because, on the server, the `storage` subfolder has been replaced by a symlink,

What are the best practices to handle this case? I noticed this behaviour in all my projects where I use Deployer.
Not a blocking or serious problem, but I would like to know how to handle it, for the sake of knowledge.
Thanks

**Comment by antonmedv** [comment]
You can do nothing about it as it happend only on server and not in development, or add to .gitignore as i do in my projects.

**Comment by eleftrik** [comment]
Any update to the Laravel recipe? I'm still experiencing the same issue.
I think adding `storage` folder to .gitignore is wrong, because if you clone the project somewhere (e.g. another development workstation) errors will occur while running `php artisan` commands (because of cache folders missing etc.).
Any idea to avoid uncommitted files on the production server?

Thank you

**Comment by antonmedv** [comment]
You can write custom task for copying or deletend and rectreating storage folder.

**Comment by antonmedv** [comment]
Fixed in master. Please verify.

**Comment by eleftrik** [comment]
> Fixed in master. Please verify.

Thank you! I'll give it a try on my first deploy ;-)

**Comment by antonmedv** [comment]
Also, notice what master is BC for v7.
