### ISSUE TITLE
Truncated/corrupt end of output with run tty option

### ISSUE THREAD

**Issue by igloocube** [deployphp/deployer#1651]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | Deployer 6.2.0
| Local Machine OS  | Ubuntu 14.04.4 LTS
| Remote Machine OS | N/A

### Description 

When using runLocally() or run() with `['tty' => true]` as the options/2nd arg, the end of the tick and message/final line is corrupt.

### Content of `deploy.php`
```php
task('test:date', function() {
    runLocally(
        'date',
        ['tty' => true]
    );
});
```

### Output log

It is fine with -v[vv]. It's just when you are not using verbose.

With `['tty' => true]`, note the missing 'T' at the start of the last line:
```
$ dep test:date
➤ Executing task test:date
✔hu Jul 12 16:38:49 UTC 2018
```

Without:
```
$ dep test:date
✔ Executing task test:date
```

### Expected output:
Possibly a ➤ instead of ✔
```
$ dep test:date
✔ Executing task test:date
Thu Jul 12 16:38:49 UTC 2018
```

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
