### ISSUE TITLE
npm recipe not found

### ISSUE THREAD

**Issue by sachinsrtpl** [deployphp/deployer#1652]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Linux
| Remote Machine OS | AWS

### Description 
I do not have laravel file in my path as well but it does not give error but for npm it gives error. this is bit weird for me to understand why it works for laravel but for npm it gives error that file not found. from documentation i did looked at files and i found npm.php but why in the case of laravel it works and in the case of npm recipe we need to fetch that file. where is laravel.php situated ?

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';
require 'recipe/npm.php';


set('ssh_multiplexing', true);


// Project name
set('application', 'my_project');

// Project repository
set('repository', 'remote:test/fcg.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);
set('allow_anonymous_stats', false);

// Hosts

host('test')
    ->set('deploy_path', '/var/www/html');
    
// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'artisan:migrate');

task('pwd', function () {
    $result = run('pwd');
    writeln("Current dir: $result");
});

task('deploy:pushtorepo', function () {
    $result = run('git push bitbucket master');
    writeln("git push bitbucket master output: $result");
})->local();

task('assets:generate', function() {
    cd('{{release_path}}');
    run('npm run dev');
  })->desc('Assets generation');

before('deploy', 'deploy:pushtorepo');
after('deploy:update_code', 'npm:install');
after('npm:install','assets:generate');
```

### Output log
PHP Warning:  require(recipe/npm.php): failed to open stream: No such file or directory in /home/fcg/fcg/code/fcg/deploy.php on line 5
PHP Fatal error:  require(): Failed opening required 'recipe/npm.php' (include_path='phar:///usr/local/bin/dep/bin/../:.:/usr/share/php') in /home/fcg/fcg/code/fcg/deploy.php on line 5

**Comment by antonmedv** [comment]
It's because of include_path. Echo your include_path. Or require full path to npm.php.
