### ISSUE TITLE
Catch TTY warning instead of throwing an exception

### ISSUE THREAD

**Issue by igloocube** [deployphp/deployer#1653]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.2.0
| Local Machine OS  | Ubuntu 16.04.4 LTS
| Remote Machine OS | N/A

### Description 

As per resolved here in another project: https://github.com/laravel/dusk/pull/226/files#diff-9b77ed94c2c2c5083de8ec6cc456096e

Using `['tty' => true]` with `run()` or `runLocally()` on Jenkins produces error `TTY mode requires /dev/tty to be read/writable.`.

From reading up it's just because of colors, it will print ok, just in black and white, which is fine. So we should catch the exception and warn about it, as per the fix linked to above, instead of throwing and exception and halting everything.

### Steps to reproduce

Use `['tty' => true]` with `run()` or `runLocally()` on Jenkins.

### Content of `deploy.php`

```php
task('test:phpunit', function() {
    run('vendor/bin/phpunit', ['tty' => true]);
}
```

### Output log

```
In Process.php line 1042:
                                                   
  TTY mode requires /dev/tty to be read/writable.  
```

**Comment by antonmedv** [comment]
Hi,

What do you think proper behavior?

**Comment by igloocube** [comment]
As per my description:

From reading up it's just because of colors, it will print ok, just in black and white, which is fine. So we should catch the exception and warn about it, as per the fix linked to above, instead of throwing and exception and halting everything.

**Comment by iamphilrae** [comment]
I know this is old, but thought I'd follow-up as I just came across the same issue with Bitbucket Pipelines. In my `deploy.php` file, I simply altered this value to be 'false':

`set('git_tty', false);`

It then ran the Bitbucket Pipelines deployment perfectly.

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
