### ISSUE TITLE
Create changelog script

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1665]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next

### Description 

Create changelog script for automatically adding items to CHANGELOG.md. 
Now it's difficult to add items as links must be added manually and sorted. Also you need to choose right section.

Will be cool to have script for automate this process.

```
$ php scripts/change

> Which version? 
  master

> What kind of change?
  [ ] Added
  [x] Fixed
  [ ] Chan ged

> What is fixed?
  Some thing important...

> Which issues resolved?
  [ ] #1661 Adding some scripts
  [ ] #1660 fix important bug
  [x] #1659 Annoying bug, please fix.

> Safe to changelog?
  yes
```

**Comment by xyNNN** [comment]
Is this a feature which should be done by deployer?

**Comment by staabm** [comment]
the feature mentioned is meant for use to develop/manage deployer on github to ease contributions to the project itself. its not meant for use later on by the tool-users.

**Comment by xyNNN** [comment]
ah, sorry ... my fault ;)

**Comment by antonmedv** [comment]
Actually already done: https://github.com/deployphp/deployer/blob/master/bin/changelog
