### ISSUE TITLE
Remote server aliases not working on deploy

### ISSUE THREAD

**Issue by Sogl** [deployphp/deployer#1668]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Linux 4.9.93-linuxkit-aufs x86_64 (Alpine 6.4.0 Docker container), OSX Sierra 10.12.5 (host)
| Remote Machine OS | Linux 4.9.103-timeweb x86_64 (Ubuntu 14.04)

### Description 

I use some of php and composer aliases in my shared hosting:
```
alias composer='/opt/php71/bin/php -d memory_limit=1024M /home/s/soglme/bin/composer'
alias php='/opt/php71/bin/php -d memory_limit=1024M'
```

And all works fine when I ssh to remote host:
```
soglme@ttt:~$ php -v
PHP 7.1.9 (cli) (built: Sep 27 2017 19:45:21) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.2, Copyright (c) 2002-2018, by ionCube Ltd.
soglme@ttt:~$ composer --version
Composer version 1.7.0 2018-08-03 15:39:07
```

But aliases not work in Deployer:
```
➤ Executing task deploy:vendors
[timeweb] > if hash unzip 2>/dev/null; then echo 'true'; fi
[timeweb] < true
[timeweb] > cd ~/myhost.ru/releases/1 && composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader
[timeweb] < Loading composer repositories with package information
[timeweb] < Installing dependencies from lock file
[timeweb] < Dependency resolution completed in 0.001 seconds
[timeweb] < Your requirements could not be resolved to an installable set of packages.
[timeweb] <   Problem 1
[timeweb] <     - This package requires php ^7.1.3 but your PHP version (5.3.29) does not satisfy that requirement.
```

Part of `deploy.php`:
```php
//custom to 7.1 ver in timeweb
set('bin/php', function () {
    return 'php';
});
set('bin/composer', function () {
    return 'composer';
});
```

Why aliases not working when I execute deploy?

**Comment by antonmedv** [comment]
Use full path to bin in 
```
set('bin/php', function () {
    return 'php';
});
```

Also composer said:
[timeweb] < Your requirements could not be resolved to an installable set of packages.
[timeweb] <   Problem 1
[timeweb] <     - This package requires php ^7.1.3 but your PHP version (5.3.29) does not satisfy that requirement.

**Comment by antonmedv** [comment]
It's because of $PATH and files included during login. Looks like in non-tty mode there is no `/opt/php71/bin` in path.
