### ISSUE TITLE
Net_SFTP

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#167]
I've built the latest package for deployer.phar and getting this error when using the deployer:

PHP Fatal error:  Class 'Net_SFTP' not found in phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php on line 48

Any clue?

**Comment by elfet** [comment]
What is your deployer version?

**Comment by EkAndreas** [comment]
dev-master

**Comment by EkAndreas** [comment]
SSH2 missing in my php installation.
Solved the error with:
```bash
brew install php55-ssh2
```

http://www.codexpedia.com/apache-server/install-phps-ssh2-extension-on-ubuntu-and-mac/
