### ISSUE TITLE
Command to view current release metadata

### ISSUE THREAD

**Issue by kinglozzer** [deployphp/deployer#1670]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.1.0
| Local Machine OS  | OS X
| Remote Machine OS | Ubuntu

### Description 
It would sometimes be helpful to have a command to display data about the current release for a given host. For example:

- Release number
- Release date/time
- Tag/revision/branch/commit hash

e.g. `deploy info stage` or `deploy current stage`

Perhaps it would be possible to store the extra data in the `.dep/releases` CSV?

**Comment by antonmedv** [comment]
Hi, actually im working on this feature. :)

**Comment by antonmedv** [comment]
Done
<img width="1229" alt="Снимок экрана 2020-10-09 в 02 23 53" src="https://user-images.githubusercontent.com/141232/95527813-08819880-09df-11eb-912c-05c97e51b52a.png">
