### ISSUE TITLE
hosts.yml ranges

### ISSUE THREAD

**Issue by joelpittet** [deployphp/deployer#1671]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug / Feature Request
| Deployer Version  | 6
| Local Machine OS  | OS X 10.13
| Remote Machine OS | Redhat 7

### Description 
Tried to add ranges to the `host` or `hostname` in the hosts.yml file

Not sure if this a bug or feature request but likely the latter

### Steps to reproduce
```
production:
  hostname: www[01-05].example.com
  stage: production
```

### Content of `deploy.php`
```php

inventory('hosts.yml');
```

### Output log

```
  The command "rm -f /var/www/example/.dep/deploy.lock" failed.
  Exit Code: -1 (Unknown error)
  Host Name: www[01:05].example.com
  ================
  ssh: Could not resolve hostname www[01:05].example.com: nodename nor servname provided, or not known
```

**Comment by joelpittet** [comment]
Oh this change looks promising https://github.com/deployphp/deployer/pull/1541

**Comment by antonmedv** [comment]
Will fix it.

**Comment by antonmedv** [comment]
Fixed.

**Comment by joelpittet** [comment]
Thanks @antonmedv 

Should this work as well with the hostname key?

```
production:
  hostname: www[01-05].example.com
  stage: production
```

**Comment by joelpittet** [comment]
I gave it a whirl and doesn't seem to work with `hostname` key. But a big thanks, that was a fast fix!

**Comment by joelpittet** [comment]
I can work around that, thanks again for the fix
