### ISSUE TITLE
Broken symlinks after second deploy

### ISSUE THREAD

**Issue by Sogl** [deployphp/deployer#1674]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Linux 4.9.93-linuxkit-aufs x86_64 (Alpine 6.4.0 Docker container), OSX Sierra 10.12.5 (host)
| Remote Machine OS | Linux 4.9.103-timeweb x86_64 (Ubuntu 14.04)

### Description 

For use in shared hosting I created new task:
```php
task('deploy:symlink-public', function () {
    run("cd {{deploy_path}} && 
    {{bin/symlink}} {{deploy_path}}/current/public {{deploy_path}}/public_html");
});
```

In first release in works fine, but for second I got `403 Forbidden` and broken link to `public_html` folder with name `!public_html`. I can't use it.

Ok, I did `dep rollback` and got `!current` name with same problem.
What I see in mc:
![image](https://user-images.githubusercontent.com/7556290/43891983-6e93782c-9bd3-11e8-9e4a-cd037eb4916a.png)

Now both symlinks not working.
How to fix?

**Comment by Sogl** [comment]
Output of commands:
```
$ readlink current
1

$ readlink -f current
/home/s/soglme/myhost.ru/1

$ readlink public_html

$ readlink -f public_html
../2/public
```

**Comment by antonmedv** [comment]
Looks like a bug: https://github.com/deployphp/deployer/blob/master/KNOWN_BUGS.md#ubuntu-1404-coreutils-821
Try to switch off relative symlinks.

**Comment by Sogl** [comment]
3rd deploy without problem with this option. Need to check more.

**Comment by Sogl** [comment]
Solved with:
```php
set('use_relative_symlink', false);
```

No problem with deploy from 14 Aug 2018. 👍
