### ISSUE TITLE
How to run specific command only on one machine from cluster.

### ISSUE THREAD

**Issue by ZhukV** [deployphp/deployer#1678]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | latest
| Local Machine OS  | Mac OS
| Remote Machine OS | CentOS

### Description 

Hi. I have the two question.

1. How I can run the specific command only on one host from the cluster. As an example: we have more than one backends and we want to run the migrations only on one node.
2. How I can run the list of specifics commands only on one host from the cluster. As an example: we have the web nodes (PHP-FPM) and have the processing nodes for work in foreground (PHP-CLI), and we want to restart processes only on processing nodes.

Thank. Have a nice day.

**Comment by antonmedv** [comment]
Hi,

1. Use --hosts option.
2. Use roles to specify which tasks to run.
