### ISSUE TITLE
Where is phars for the new releases?

### ISSUE THREAD

**Issue by vaidasm** [deployphp/deployer#168]
There are no phars for 2.0.4/3 and also 3.x releases, how do i update?

**Comment by EkAndreas** [comment]
Just build them with the included build script!
Eg, 
``php ./build``
Perhaps you need to enable the write mode for phar-files in php.ini.

**Comment by vaidasm** [comment]
I guess I could do just that, but it's much more easy to just download it

**Comment by elfet** [comment]
You can download in here: http://deployer.org/deployer.phar for 2.x and http://deployer.org/beta/deployer.phar for 3.x.

**Comment by vaidasm** [comment]
Thanks
