### ISSUE TITLE
Custom Path

### ISSUE THREAD

**Issue by ASC** [deployphp/deployer#1680]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.20
| Local Machine OS  | macOS 01.13.6 
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
Hello all - apologies if this is a duplicated question. 
My repo is such that the folder I want to deploy to the server is not the root, rather the Laravel project is within a folder one level down from the root repo directory. 

How can I specify this in the deployer config?
I see I can set server deploy path but what I am looking for is the equivalent local machine option. 

Thanks in advance :) 

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', 'ProjectName');

// Project repository
set('repository', 'git@github.com:ASC/MyProject.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);


// Hosts

host('myhost.co.uk')
    ->set('deploy_path', '/var/www/project/public_html');
    
// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'artisan:migrate');


```

### Output log
N/A

**Comment by antonmedv** [comment]
I didn't understand what are you want. :)

**Comment by clearcss** [comment]
I think he meant inside the git repository, there is a folder, for instance "src".  That contains the code that needs to be deployed.  

As it stands using the laravel recipe, when deployer runs, it fetches the git repository and pulls it to the deploy_path. From there is tries to run the commands.  However, the commands should run within "src"

Has anyone else run into this?

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
