### ISSUE TITLE
Deployer on Jenkins can't connect to remote

### ISSUE THREAD

**Issue by DenisMir** [deployphp/deployer#1682]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3.0
| Local Machine OS  | Jenkins @ Debian 9.5 (Docker image of jenkins LTS)
| Remote Machine OS | Debian 9.5

### Description 
We are having a simple PHP application that we do build and deploy with deployer. When doing this locally on a local development machine we are able to deploy just fine to the remote server. 
Now we are trying to execute the deployer deployment process on a jenkins build server. The local tasks (== the build process) are executed just fine but as soon as the remote tasks get executed deployer fails with the output log mentioned below. 
In the jenkins job the ssh agent is activated for the specific job and the correct ssh key is selected. (its public key is deposited in the authorized keys file on the remote server) 
When letting jenkins execute a `ssh <user>@<hostname>` shell command manually in the build job the ssh connection gets initiated just fine. 

It would be great if someone does have an idea why the ssh connection initiated by deployer on the jenkins build server does fail! 

### Output log
```
➤ Executing task deploy:prepare
[production-system] > echo $0
[production-system] < ssh multiplexing initialization
[production-system] < Control socket connect(/var/jenkins_home/.ssh/deployer_<user>@<hostname>): Connection refused
[production-system] < Failed to connect to new control master
➤ Executing task deploy:failed
• done on [production-system]
✔ Ok [1ms]
• done on [production-system]

In Client.php line 99:
                                                                               
  [Deployer\Exception\RuntimeException (-1)]                                   
  The command "echo $0" failed.                                                
                                                                               
  Exit Code: -1 (Unknown error)                                                
                                                                               
  Host Name: production-system                                                 
                                                                               
  ================                                                             
  Control socket connect(/var/jenkins_home/.ssh/deployer_<user>@<hostname>):  
   Connection refused                                                          
  Failed to connect to new control master   
```

I have replaced the `user` and `hostname` in the log file but they are filled in correctly from our hosts.yml file.

**Comment by DenisMir** [comment]
As soon as I set `set('ssh_multiplexing', false);` the problem is gone.

**Comment by antonmedv** [comment]
Try to use tmpfs for socket.

**Comment by DenisMir** [comment]
Thank you for the hint @antonmedv. Mmmh. What does that mean in detail? (I think that I'm a newbie in that area)

**Comment by antonmedv** [comment]
Set control path of ssh to `/dev/shm`

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.

**Comment by andyexeter** [comment]
@antonmedv is the control path configurable within Deployer? I'm facing a similar issue and it looks like the control path is set within \Deployer\Ssh\Client with no ability to change it at the config level.

**Comment by andyexeter** [comment]
For anybody stumbling across this issue or similar, changing the ControlPath to /dev/shm worked for me. To do this I added the following to my host config:

```php
->addSshOption('ControlPath', '/dev/shm/deployer-%C')
```
