### ISSUE TITLE
Running codecept tests op deploy

### ISSUE THREAD

**Issue by RdeWilde** [deployphp/deployer#1683]
I have tests written in codecept. What is the best way to integrate these with the project so that it'll give usefull output and the deployment will actually fail when tests don't complete.

**Comment by antonmedv** [comment]
run('./test.sh')

**Comment by RdeWilde** [comment]
What is test.sh? And will it show me the test results?

**Comment by antonmedv** [comment]
Hmmm, `codecept`?

**Comment by RdeWilde** [comment]
Yes \o/

**Comment by antonmedv** [comment]
¯\_(ツ)_/¯

**Comment by RdeWilde** [comment]
phpunit would be fine too.... :1st_place_medal:

**Comment by antonmedv** [comment]
Just create task and run it:
```php
task('test', function () {
    runLocally('phpunit');
});
```

**Comment by RdeWilde** [comment]
TY

For reference, this seems usefull:
https://stackoverflow.com/questions/32740889/how-do-you-run-a-codeception-test-from-within-a-php-script

**Comment by RdeWilde** [comment]
@antonmedv 
I use this code:
```
task('test', function() {
	$user = posix_getpwuid(posix_getuid());
	if (!empty($user)) {
		require_once $user['dir'].'/.composer/vendor/codeception/codeception/autoload.php';
	}

	$Codecept = new \Codeception\Codecept(array(
		'steps' => true,
		'verbosity' => 2,
		// some other options (see Codeception docs/sources)
	));

	$Codecept->run('api');
});

// ...

before('deploy:prepare', 'test');
```

But this way it seems like the code is being executed on my local client.

Is it possible to move this to the server? Or is  the php code always executed locally?
I would like to run it on the server as env may be different there, like other extensions or settings. Also, that way we don't have to configure every client as a server

**Comment by antonmedv** [comment]
Php locally, only comands remotely.

**Comment by RdeWilde** [comment]
Okay, ty
