### ISSUE TITLE
How to deploy to one host then reload httpd on three more

### ISSUE THREAD

**Issue by dharkness** [deployphp/deployer#1694]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3.0
| Local Machine OS  | Ubuntu
| Remote Machine OS | CentOS

### Description 
Dev/QA/Stage are single-VM setups, but production consists of four web VMs with shared storage. I need to run all the normal deployment steps (checkout, config, reload Apache) on one of the hosts (`web1`) and then restart Apache on the other three hosts `web2`, `web3`, and `web4`.

Is this possible currently? Do I define the four web hosts separately and then loop over them to issue the restart step from within the `deploy` task run on `web1`?

Here's a little psuedocode to illustrate what I'm thinking. Is this on the right track?

    task('apache:reload', function () {
        if (get('stage') === 'production') {
            foreach (hosts('web1', 'web2', 'web3', 'web4') as $host) {
                // restart Apache on $host
            }
        } else {
            // restart Apache on current host
        }
    });

**Comment by antonmedv** [comment]
Hi, yes it's possible.

Create task with restart code, add role restriction on it, add web2:4 hosts with this role.

**Comment by dharkness** [comment]
The above didn't work so I moved all the `deploy` steps to a new `build` task and assigned roles. I am testing by pointing the `qa` stage to both the `dev` and `qa`.
```
host('dev-vm')
    ->stage('qa')
    ->roles('code', 'serve');
host('qa-vm')
    ->stage('qa')
    ->roles('serve');

task('deploy', [
    'build',
    'apache:reload',
]);

task('build', [ // original deploy task steps without apache:reload
    'deploy:info',
    ...
    'cleanup',
])->onRoles('code');

task('apache:reload', function () {
    run('sudo /sbin/service httpd reload');
})->onRoles('serve');
```
It's still executing the build on all VMs.
```
$ dep deploy qa
✈︎ Deploying master on dev-vm
✈︎ Deploying master on qa-vm
✔ Executing task deploy:prepare
...
✔ Executing task cleanup
✔ Executing task apache:reload
```
Both VMs got a new release in the `releases` directory, but `qa` should not because it is not in the `code` role. What am I missing about roles?

**Comment by dharkness** [comment]
I see that `TaskCommand` matches both hosts using the `qa` stage, gets the list of tasks that match any of their roles, and executes them on all hosts. It doesn't work at all how I expected. I need the dev/qa/staging hosts to both deploy the code and reload Apache, but the prod stage should deploy the code only to the first host and then tell all hosts to reload Apache.

Can you please explain further how I can achieve that?

**Comment by antonmedv** [comment]
I see what's you problem here. I agree, it's strange behavior what 
```php
task('build', [ // original deploy task steps without apache:reload
    'deploy:info',
    ...
    'cleanup',
])->onRoles('code');
```
this code doesn't restrict subtask too. I'll fix it in new release v7 (will be useing trees of task instead of plain list of tasks.)

Now you have to run it twice I think. You can run in from another task with `runLocally('dep deploy prod')` or something like this. Not elegant, hope to fix it in next release.

**Comment by dharkness** [comment]
Oh right, `runLocally` should work and is fine as far as hacks go. I just didn't want people forgetting to restart the other hosts. That's totally fine, thanks.

**Comment by dharkness** [comment]
I haven't had a chance to try `runLocally`, but couldn't I simply mark the code deployment that must run only on the first VM with `once()`? Does a task with `isOnce()` run on the first host only?

**Comment by dharkness** [comment]
I understand now, I have to mark every "build" subtask with `once()` instead of marking the main task itself. It's a little goofy, but it works.

**Comment by antonmedv** [comment]
Yes, it’s goofy. Can you share you deploy.php? 
Im working on improving it next v7 release.

**Comment by dharkness** [comment]
To fully support roles, once, etc. you'll definitely need to walk the Task tree instead of collecting all the tasks up front. Here's what I ended up with. It's both simpler and hacky at the same time. :rofl: 
```
host('web1', 'web2', 'web3', 'web4')
    ->stage('prod');

desc('Deploy the application');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    ...
    'deploy:unlock',
    'apache:reload',    // this is the one that must run on all hosts
    'cleanup',
]);

// make each "deploy" subtask that writes to the file system run on the first host only
// because the hosts have shared storage
foreach ([
    'deploy:info',
    'deploy:prepare',
    ...
    'deploy:unlock',
    // note: 'apache:reload' is absent
    'cleanup',
] as $task) {
    task($task)->once();
}
```

**Comment by antonmedv** [comment]
Yes, not nice (will be improved, I promise 🤗). But php to the rescue!  😄

**Comment by dharkness** [comment]
Hmm, now I'm wondering if that one subtask that isn't tagged with `once()` is actually running on every host.
```
✈︎ Deploying master on web1
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
...
✔ Executing task deploy:unlock
✔ Executing task apache:reload
✔ Executing task cleanup
```
Is there a way to see that `apache:reload` is actually run on all four hosts?
