### ISSUE TITLE
Unable to ask for ssh password

### ISSUE THREAD

**Issue by cstaelen** [deployphp/deployer#1699]
| Q                 | A
| ----------------- | ---
| Issue Type        | Unable to ask for password
| Deployer Version  | 6.3.0
| Local Machine OS  | OSX/Docker
| Remote Machine OS | N/A

### Description 
Hi there, 
I have an yaml file for my hosts informations, since version 4, I used to ask for password at each ssh connection by keeping password value empty in yaml. 
But with latest version of deployer, I'm not able to make it works.
Is there a new way to do this ? 

### Content of `servers.yml`
staging:
    host: staging.mydomain.fr #SET SSH HOST
    stage: staging
    user: ssh_user
    password: #SET SSH PASSWORD (Leave empty to ask)
    deploy_path: /var/www/vhosts/staging #SET SSH TARGET
    branch: develop #SET SSH BRANCH

### Content of `deploy.php`
```php
namespace Deployer;

require 'recipe/common.php';

inventory('.deploy/servers.yml');

set('ssh_type', 'native');
set('ssh_multiplexing', true);

// Project name
set('application', 'myproject');

// Project repository
set('repository', 'git@bitbucket.user/project.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
set('shared_files', []);
set('shared_dirs', []);

// Writable dirs by web server
set('writable_dirs', []);

// Tasks

desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] If deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
*With enabled option for verbose output `-vvv`.*
✈︎ Deploying develop on staging
• done on [staging]
➤ Executing task deploy:prepare
[staging] > echo $0
[staging] < ssh multiplexing initialization

And it keeps waiting for something at this point indefinitely.

**Comment by antonmedv** [comment]
No, there is no possibility to ask for passwords now. But you can use ssh keys. It's much secure way of using ssh.

**Comment by cstaelen** [comment]
Hello @antonmedv thx for your fast answer !
I will deal with docker && ssh keys :)
