### ISSUE TITLE
RuntimeException: Object `deploy:start` does not exist in ScenarioCollection.

### ISSUE THREAD

**Issue by KaipiYann** [deployphp/deployer#170]
Hi,

I'm trying to use the Deployer 3 Beta 3...I have downloaded the archive, built the phar, installer it in bin directory.
But then when I try to follow the Get Started example, as soon as I add "require 'recipe/symfony.php'; " I got these errors whn I run dep

PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///usr/local/bin/dep/src/functions.php on line 102

And 
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Object `deploy:start` does not exist in ScenarioCollection.' in phar:///usr/local/bin/dep/src/Collection/Collection.php:24

Could you help ?

Thks

**Comment by elfet** [comment]
Yeahhh... Deployer 3 recipes not ready now, sorry. Try to use Deployer 2: http://deployer.org/deployer.phar

**Comment by KaipiYann** [comment]
Thank you...step by step I'm trying to correct it...without doc not so easy ;-)

**Comment by KaipiYann** [comment]
And I have to say this project looks great ! Thank you !

**Comment by KaipiYann** [comment]
I have a strange issue now. I almost managed to make everything work except that when I launch the "dep deploy" the "deploy:assetic:dump" task return an error "Unable to find file "@CmfCreateBundle/Resources/public/vendor/hallo/src/hallo.coffee"
(this file is downloaded during the vendor step, it's a composer post install script "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor")

The strange thing is that if a relaunch the "dep deploy:assetic:dump" it works...

**Comment by KaipiYann** [comment]
Sorry it's not a problem with Deploy, it's a problem of cache warmup and assetic...don't really understand but found a solution.

**Comment by elfet** [comment]
Ok. Feel free to ask any questions.
