### ISSUE TITLE
Rollback fails due to not running with sudo

### ISSUE THREAD

**Issue by nsrosenqvist** [deployphp/deployer#1700]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.3.0
| Local Machine OS  | Ubuntu 18.04
| Remote Machine OS | Ubuntu 16.04

### Description 
The rollback task doesn't take required sudo privileges into account. It would be great if you could check a variable if `rm` needs to be run with sudo or not.

### Steps to reproduce
Deploy to a directory requiring sudo

### Content of `deploy.php`
_irrelevant - default rollback task_

### Output log
`rm: cannot remove '/var/www/[redacted]': Permission denied`

**Comment by antonmedv** [comment]
Check your permissions. If it can create folders there, you should be able to delete as well.

**Comment by nsrosenqvist** [comment]
@antonmedv, I assume it is because I chown www-data:www-data as part of the release process. This can't be an entirely uncommon use case though? Can't it be added as an option, just like many other deploy tasks has one to run commands as sudo?

**Comment by antonmedv** [comment]
Hmmm, this will compilcate recie. And I don't like spreading sudo around. Not secure option.
Maybe fix init reelase with proper addgropup comands.

**Comment by bbceg** [comment]
I'm in a similar position here. In my case the website files are owned by a user and group specific to the website's php-FPM pool. The user has write access to the files (to allow uploads etc.), but the group does not. As I suspect may be the case for @nsrosenqvist these permissions are altered only for deployment. 

@antonmedv I think I am right in saying you are proposing adding the deploy user to the group and giving the group write access to the directories. My understanding was that this was not recommended but, with tight permission management, would seem safe enough.

Might a possible alternative be to precede the rollback with a task to soften permissions? I've just tried the following and it seems to do the trick:

`task('rollback:soften_permissions', function () {
    $releases = get('releases_list');
    if (isset($releases[1])) {
        run("sudo find {{deploy_path}}/releases/{$releases[0]} -type d -exec chmod 775 {} \;");
    }    
});

before('rollback', 'rollback:soften_permissions');`

Thoughts welcome.
