### ISSUE TITLE
 Failed opening required 'recipe/common.php' 

### ISSUE THREAD

**Issue by chukey** [deployphp/deployer#1705]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 6.3.0
| Local Machine OS  | windows
| Remote Machine OS | ubuntu 16

### Description 
i tried install deployer for first on debian 8 and this is work well, then install on debian 9 and ubuntu 16 
command dep init working and i set all steps
then i try to run **dep deploy** exit with error

`PHP Fatal error:  require(): Failed opening required 'recipe/common.php' (include_path='phar:///usr/local/bin/dep/bin/../:.:/usr/share/php:/usr/share/pear:/usr/local/bin/dep/src') in /var/www/www-root/data/www/test/deploy.php on line 4`
if do u see i tried many include path) but this not work

### Content of `deploy.php`
standart from init
```php
<?php
namespace Deployer;

require 'recipe/common.php';

// Project name
set('application', 'my_project');

// Project repository
set('repository', 'git@bitbucket.org:durachook/test.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
set('shared_files', []);
set('shared_dirs', []);

// Writable dirs by web server 
set('writable_dirs', []);
set('allow_anonymous_stats', false);

// Hosts

host('project.com')
    ->set('deploy_path', '~/{{application}}');    
    

// Tasks

desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] If deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

```

### Output log
dep deploy -vvv
PHP Fatal error:  require(): Failed opening required 'recipe/common.php' (include_path='phar:///usr/local/bin/dep/bin/../:.:/usr/share/php:/usr/share/pear:/usr/local/bin/dep/src') in /var/www/www-root/data/www/test/deploy.php on line 4

**Comment by chukey** [comment]
Антон, если можно ответь на Русском тоже.. с анг не очень дружу

**Comment by chukey** [comment]
already solved the problem, installed via composer require deployer/deployer --dev in the working directory
it is strange that after this deep and earned..
---------------------------
уже решил проблему, установил через composer require deployer/deployer --dev в рабочем каталоге
странно что после этого и dep заработал..

**Comment by rafaelstz** [comment]
Replacing `require` to `require_once` works too.
