### ISSUE TITLE
Asking question and sharing answer with other tasks

### ISSUE THREAD

**Issue by chrispage1** [deployphp/deployer#1710]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2.0
| Local Machine OS  | Mac OS
| Remote Machine OS | N/A

Hi, I am trying to write a step that asks the user if they would like to re-compile local sources. If they select yes, then it'll run compile task, however if they choose no it will just copy from a previous release. My thinking was to do something like the following - 

```
// ask if we are compiling resources
task('compile_resources', function () {
    $compile_resources = ask('Would you like to compile resources [y|Y|Yes]?');
    $compile_resources = in_array(strtolower($compile_resources), ['y', 'Y', 'Yes']);
    set('compile_resources', $compile_resources);
})->local();
before('deploy', 'compile_resources');
```

Then on the actual deployment task - 

````
// Build our assets locally
task('npm:build', function () {
    if (get('compile_resources')) {
        // compile our assets
        writeLn("Compiling assets locally for {{stage}}. This can take a while...\n");
        runLocally('npm run prod -s');
    } else {
        // ToDo: copy our code from a previous release
    }
})->desc('Compile npm files locally');
after('deploy:shared', 'npm:build');
````

The problem I am having is I can't seem to find a way of getting the `compile_resources` attribute within another task. Is there a way of doing this?

Thanks,
Chris.

**Comment by staabm** [comment]
things you set with `set()` are avaiable with `get()`.

you used `input()->get()`, not sure why?

**Comment by chrispage1** [comment]
Thanks @staabm, you're completely right and I've updated my question to reflect that. I was trying a few different things and that was the last scenario I had. I've managed to come up with a fix. I was using the `->local()` method - I didn't realise that variables weren't shared across environments in that case.

I've now got the following - 

```
//check if we are compiling resources
task('compile_resources', function () {
    $compile_resources = ask('Would you like to compile resources [y|yes]?');
    $compile_resources = in_array(strtolower($compile_resources), ['y', 'yes']);
    set('compile_resources', $compile_resources);
});
before('deploy', 'compile_resources');
```

```
// Build our assets locally
task('npm:build', function () {
    
    if (get('compile_resources') || !test('[ -d {{previous_release}}/public ]')) {

        // compile resources locally
        writeLn("Compiling assets locally for {{stage}}. This can take a while...");
        runLocally('npm run prod -s');

    } else {

        // load our compiled assets from a previous release
        writeLn('Copying public directory from previous release');
        if (test('[ -d {{previous_release}}/public ]')) {
            run('cp -R {{previous_release}}/public {{release_path}}');
        }
    }
})->desc('Compile npm files locally');
after('deploy:shared', 'npm:build');
```

This works just as I'd hoped and will hopefully be useful to someone else :)
