### ISSUE TITLE
deploy:update_code - project files and folders permissions

### ISSUE THREAD

**Issue by Udimi** [deployphp/deployer#1718]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

My version of deployer is 4.x

Hi!

If I run the command git clone manually, I get the files and folders with the 775 and 664 permissions.
If the repository cloning executes across deployer (deploy:update_code), then I get the permissions to the project files 755 and 644. How do I change this behavior? I would like to have 775 and 664 after deploer execute.

Thanks.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
