### ISSUE TITLE
Ability to hide tasks from dep list but still allow them to be run

### ISSUE THREAD

**Issue by bbceg** [deployphp/deployer#1720]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.3.0
| Local Machine OS  | Ubuntu 18
| Remote Machine OS | Ubuntu 18

Similar to closed issued #212 it would be useful to hide tasks from the dep list _but_ also be able to run them independently.

A typical scenario when this would be useful is when a deploy falls over because one of its sub tasks (set to private) fails to complete. I then need to complete the remaining tasks one by one and this currently involves removing setPrivate from each task, running them and then reinstating setPrivate. 

This could be achieved by allowing tasks to be run irrespective of whether setPrivate is set or by providing a setHidden option instead.

Another alternative (though I have a feeling this won't technically be possible) would allow a task to be started from a particular sub task (skipping the ones already successfully completed) with a syntax like this:
dep task --start=sub-task
e.g. dep deploy --start=deploy:update_code

Great tool by the way.

**Comment by antonmedv** [comment]
Done in master!
