### ISSUE TITLE
Bug - can ssh in terminal but deployer reporting 'ssh' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by danielpclin** [deployphp/deployer#1725]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 6.3
| Local Machine OS  | Windows 10
| Remote Machine OS | Ubuntu 18.04

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
running` vendor\bin\dep deploy -vvv` on windows with ssh support
When I ssh on command prompt, there is ssh help message. But deployer seems to not see ssh.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', REMOVED);
set('default_stage', 'staging');


// Project repository
set('repository', REMOVED);

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true); 

// Shared files/dirs between deploys 
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server 
add('writable_dirs', []);


// Hosts

host('production')
    ->hostname(REMOVED)
    ->port(25560)
    ->set('deploy_path', '/var/www/{{application}}');

host('staging')
    ->hostname(REMOVED)
    ->port(25560)
    ->set('deploy_path', '/var/www/staging_{{application}}');
    
// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'artisan:migrate');

```

### Output log
*With enabled option for verbose output `-vvv`.*

> vendor\bin\dep deploy -vvv

[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < Development
✈︎ Deploying Development on staging
• done on [staging]
➤ Executing task deploy:prepare
[staging] > echo $0
[staging] < ssh multiplexing initialization
[staging] < 'ssh' is not recognized as an internal or external command,
[staging] < operable program or batch file.
➤ Executing task deploy:failed
• done on [staging]
✔ Ok [1ms]
➤ Executing task deploy:unlock
[staging] > rm -f /var/www/REMOVED/.dep/deploy.lock
[staging] < ssh multiplexing initialization
[staging] < 'ssh' is not recognized as an internal or external command,
[staging] < operable program or batch file.

In Client.php line 99:
                                                                      
  [Deployer\Exception\RuntimeException (-1)]                          
  The command "rm -f /var/www/REMOVED/.dep/deploy.lock" failed.  
                                                                      
  Exit Code: -1 (Unknown error)                                       
                                                                      
  Host Name: staging                                                  
                                                                      
  ================                                                    
  'ssh' is not recognized as an internal or external command,         
  operable program or batch file.                                     
                                                                      

Exception trace:
 Deployer\Ssh\Client->run() at REMOVED\vendor\deployer\deployer\src\functions.php:304
 Deployer\run() at REMOVED\vendor\deployer\deployer\recipe\deploy\lock.php:30
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at REMOVED\vendor\deployer\deployer\src\Task\Task.php:105
 Deployer\Task\Task->run() at REMOVED\vendor\deployer\deployer\src\Executor\SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at REMOVED\vendor\deployer\deployer\src\Console\TaskCommand.php:155
 Deployer\Console\TaskCommand->execute() at REMOVED\vendor\symfony\console\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at REMOVED\vendor\symfony\console\Application.php:948
 Symfony\Component\Console\Application->doRunCommand() at REMOVED\vendor\deployer\deployer\src\Console\Application.php:133
 Deployer\Console\Application->doRunCommand() at REMOVED\vendor\symfony\console\Application.php:250
 Symfony\Component\Console\Application->doRun() at REMOVED\vendor\symfony\console\Application.php:148
 Symfony\Component\Console\Application->run() at REMOVED\vendor\deployer\deployer\src\Deployer.php:331
 Deployer\Deployer::run() at REMOVED\vendor\deployer\deployer\bin\dep:120

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

**Comment by antonmedv** [comment]
Check what your local system has ssh installed.

**Comment by danielpclin** [comment]
My ssh is installed in `C:\Windows\System32\OpenSSH\ssh.exe`
Version is `OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4`

**Comment by staabm** [comment]
Is the ssh command with $PATH ?

**Comment by danielpclin** [comment]
yes it is in PATH, and i can directly call `ssh` in terminal anywhere

**Comment by staabm** [comment]
It seems its not accessible to your php cli

**Comment by danielpclin** [comment]
What can i do to test it?

**Comment by staabm** [comment]
Maybe `php -r 'exec("ssh -v")'`

**Comment by danielpclin** [comment]
There is no output

**Comment by staabm** [comment]
Missed a echo, just added it above

**Comment by danielpclin** [comment]
```
PHP Parse error:  syntax error, unexpected ''echo' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1

Parse error: syntax error, unexpected ''echo' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1
```

**Comment by staabm** [comment]
Semicolon on the wrong plase... another edit above

**Comment by danielpclin** [comment]
Still not working. I tried `php -a` to get into interactive mode and ran `echo exec("ssh -v");`, it confirms that php can't access ssh. `'ssh' is not recognized as an internal or external command, operable program or batch file.`

**Comment by danielpclin** [comment]
I’m quite sure that my $PATH is set correctly

**Comment by antonmedv** [comment]
Check user/group on ssh bin.

**Comment by antonmedv** [comment]
Can user you are running from.

**Comment by danielpclin** [comment]
I'm running on windows.

**Comment by antonmedv** [comment]
Try windows subsystem for ubuntu

**Comment by danielpclin** [comment]
The main problem is that php can't ssh while I can in command prompt. I also tried other commands like `git` in php and it works flawlessly. Not sure what it is all about.

**Comment by antonmedv** [comment]
Can't tell too. I need your machine to investigate :)

**Comment by danielpclin** [comment]
I did some more investigation, it seems that in php, it doesn't see some directories. like OpenSSH in Windows\System32

**Comment by danielpclin** [comment]
I think this may be a issue with php and Windows 10. Closing the issue.

**Comment by danielpclin** [comment]
The reason that ssh can't be called is because XAMPP uses 32bit version of php, and `exec` in 32bit php uses cmd in `C:\Windows\SysWOW64` which somehow doesn't have ssh. The solution is to use 64 bit php.

**Comment by wnateg** [comment]
> The reason that ssh can't be called is because XAMPP uses 32bit version of php, and `exec` in 32bit php uses cmd in `C:\Windows\SysWOW64` which somehow doesn't have ssh. The solution is to use 64 bit php.

@danielpclin Just thought you should know, this comment really helped me out. Thank you.
