### ISSUE TITLE
Intent to implement `deploy_dir` option

### ISSUE THREAD

**Issue by jdecool** [deployphp/deployer#1735]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.x

### Description 

I'm working on an application based on microservices architecture. At the moment each services has its own Git repository and they are deploy with Deployer.

I'm going to merge all repository in a monolithic repository. For the new deployment process, I will checkout all the monorepository on the server but I want to keep a deploy for each services with their own `current` directories.

I thought about adding an option `deploy_dir` to specify which directory of the repository need to be deploy for a host.

Is a feature that could be interesting for Deployer ?

**Comment by antonmedv** [comment]
This is possible. I think to add it too in new version.

**Comment by jdecool** [comment]
Is it planed ?

I start to look at, how I can implement this feature.

**Comment by antonmedv** [comment]
Yes, also you can find PR here with same feature #1688

**Comment by jdecool** [comment]
I don't really want to implement the same feature.

I have a Git repository that host multiple app. Something like this:

```text
myRepository.git
├── app1
├── app2
├── app3
```

When I want to deploy, all the repository is clone, but I only want to link 1 app.

So I want to implement an option to do that on the deployed server:

```text
deployDirOnServer
├── current -> releases/1/app1
├── releases
│   ├── 1
│   │   ├── app1
│   │   ├── app2
│   │   ├── app3
├── shared
```

Through this configuration :

```php
host('prod')
    ->hostname('prod')
    ->set('deploy_path', '/var/www/my-project')
    ->set('deploy_dir', 'app1')
    ->set('repository', 'git@gitscm.com:provider/project.git')
```

But maybe the name `deploy_dir` is not really explicit.

**Comment by antonmedv** [comment]
This is possible, override tasks.

**Comment by jdecool** [comment]
Yes I could override the `deploy:symlink` task.

But through this issue, I want to ask if it's interesting to implement the feature natively in Deployer ?

**Comment by antonmedv** [comment]
I dont think so, as this very non common way.

**Comment by jdecool** [comment]
OK, no problem with that.

I'm going to mutualize it in a custom recipes 👍 .

Thanks for your work on the tool and for the time you taken to discuss on this issue.
