### ISSUE TITLE
Don't modify include_path

### ISSUE THREAD

**Issue by ntzm** [deployphp/deployer#1744]
We recently came across a perplexing bug, where the cause was a different library using `require 'autoload.php';` where they wanted to load the file in the same directory, but it was including your autoload file instead. I understand this would be a large breaking change for you, but I don't think you should be modifying include_path. It could be done in the next major release.

**Comment by antonmedv** [comment]
Yes, I'm thinking about refactoring all this autoload part of deployer.

**Comment by antonmedv** [comment]
Fixed in master. Please verify.
