### ISSUE TITLE
How to know which tasks were already executed?

### ISSUE THREAD

**Issue by roldan** [deployphp/deployer#1749]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | 6.2.0
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description 
Hi guys, 

this a question to know if there is any way to know which tasks were executed inside a deploy flow. 
In my case, I've a "deploy:failed" task that should run some tasks regarding which tasks were already executed. For example: if my "deploy" task failed after "task1" I should run "reverse:task1", if "deploy" task failed after "task2" I should run "reverse:task2" and "reverse:task1".

I was looking into the code in ProcessRunner::run() but didn't found nothing like a "executed task collection" or something like that... 

Only way I've found to do this is overriding all subtasks of "deploy" task in my deploy.php and do something like this:

```
$executedTasks = [];

task("task1", function() use ($executedTasks){
    // Original code
    $executedTasks[] = "task1";
});

task("task2", function() use ($executedTasks){
    // Original code
    $executedTasks[] = "task2";
});

task("deploy:failed", function() use ($executedTasks){
    if(in_array("task2", $executedTasks)){
        invoke("reverse:task2");
    } 
    if(in_array("task1", $executedTasks)){
        invoke("reverse:task1");
    }
}); 
```
Is there an easy way of doing this instead of overriding all tasks?

Thanks,
Matías

**Comment by antonmedv** [comment]
You can add after hook: `after('deploy:failed', 'reverse:task1');`
But your solution is okay. One of advantages of deployer being written in php - you can program what's you want.

**Comment by roldan** [comment]
thanks @antonmedv !
