### ISSUE TITLE
Make deploy:writable aware of links

### ISSUE THREAD

**Issue by RdeWilde** [deployphp/deployer#1752]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | HEAD
| Local Machine OS  | Ubuntu 18
| Remote Machine OS | Ubuntu 16

### Description 
https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php#L41

This function checks if directory exists, but not if it is a link. It should differentiate operations when it is a symlink

I fixed it like this:
```php
        // Create directories if they don't exist
		$create = array_filter(get('writable_dirs'), function($dir) {
			return !file_exists($dir) && !is_link($dir);
		});
		if (!empty($create)) {
			$create = join(' ', $create);
        	run("mkdir -p $create");
		}

		// Only operate on non-symlinks
		$writeable = array_filter(get('writable_dirs'), function($dir) {
			return !is_link($dir);
		});
		if (empty($dirs)) {
			return;
		} else {
			$dirs = join(' ', $writeable);
		}
```

### Output log
```
Something like "cannot create directory .... file exists
```

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
