### ISSUE TITLE
Request input during deploy

### ISSUE THREAD

**Issue by trsteel88** [deployphp/deployer#1754]
Apologies if this isn't the correct place to ask.

Is there a way to request user input during a deploy. I want to write a custom output which dump the Doctrine Schema updates that will execute. I then want the task to pause and ask the person deploying to confirm the execution. e.g. by typing "Confirm" or "Y". After confirming the task will then execute and the deployment will continue.

If there were no schema updates required it would continue as is.

I don't need help writing the actual task, it's just how to request input during the deployment. However, I can't find any documentation for this.

Thank you.

**Comment by ahmadmayahi** [comment]
It's easy to achieve by using the Symfony `option` command as follows:
```php
# For options
option('without-db-migration', null, \Symfony\Component\Console\Input\InputOption::VALUE_NONE, 'Deploy without running database migration.');

$option = \Deployer\input()->getOption($option);
if ($option == 1) {
     echo "Huura!
}

# For input
if (askConfirmation("Would you like to continue?")) {
     //TODO: continue the task here
}
```

**Comment by trsteel88** [comment]
Thanks @ahmadmayahi. Thought I'd paste my code for anyone else that is looking for a similar solution.

The task just puts itself in a loop and won't let the deployment complete until the schema is synchronised. 

![screen shot 2018-11-21 at 10 18 27 am](https://user-images.githubusercontent.com/869933/48810859-d75e3780-ed76-11e8-8e03-22297b8c5895.png)

The terminal will output the schema updates, you should then run these manually on your database and press enter inside the terminal once your schema is up to date. It will then allow you to proceed past the loop.

```php
// Tasks
task('sync_schema', function () {
    $dbSynced = false;

    while (false === $dbSynced) {
        $schemaUpdates = run('cd {{release_path}} && bin/console doctrine:schema:update --dump-sql');

        if (false !== strpos($schemaUpdates, 'Nothing to update')) {
            $dbSynced = true;
            continue;
        }

        $schemaUpdates = str_replace('The following SQL statements will be executed:', '', $schemaUpdates);
        $schemaUpdates = trim($schemaUpdates);

        writeln('The database requires schema updates.');
        writeln('');

        writeln('<error>'.$schemaUpdates.'</error>');
        writeln('');

        ask("Press enter to continue.");
    }
});

before('deploy:symlink', 'sync_schema');
```
