### ISSUE TITLE
Is it possible to set a password for sudo commands?

### ISSUE THREAD

**Issue by Dasky** [deployphp/deployer#1757]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3
| Local Machine OS  | Ubuntu 17.10
| Remote Machine OS | Ubuntu 16.10

Hi,
Is it possible to pass a hardcoded password  to act as sudoer while executing remote commands ?
The initial connection is done by SSH, normally.
We are looking for any alternative to adding NOPASSWORD rule in /etc/sudoers.d/.

Thanks

**Comment by antonmedv** [comment]
Only if tty is used, but you will need to enter it manually.

**Comment by Dasky** [comment]
Ok, thanks 

Is it possible to set a deployer variable to set **tty** for every sudo command by default?

I began by setting the following :
```
set('writable_use_sudo', true);
```
And when launching `dep deploy`, I have this error :
```
In Client.php line 99:                                                                                                                           
  [Deployer\Exception\RuntimeException (1)]                                                                                    
  The command "export SYMFONY_ENV='prod'; cd /opt/www/project.com/public && if [ ! -d .dep ]; then mkdir .dep; fi" failed.            
  Exit Code: 1 (General error)                                                                                                                                                                                              
  Host Name: production                                                                                                                                                                                                            
  ================                                                                                                             
  mkdir: cannot create directory ‘.dep’: Permission denied
```

Any guidelines ?
Thanks

**Comment by Dasky** [comment]
**New tests with TTY** with the objective to execute sudo commands by typing manually the password.

I have used the directive **RequestTTY force** in my **~/.ssh/config**
with 2 differents deployer config :

**Case 1** : using "become" with an other user than the SSH one :
```
set('writable_use_sudo', true);
host('production')
    ->become('other-user-than-ssh')
```
Result : stucked with the prompt waiting for password, stucked even after writing the password.
```
➤ Executing task deploy:prepare
[lims-production] > export SYMFONY_ENV='prod'; echo $0
[lims-production] < [sudo] password for myuser:
```

**Case 2** : without overriding the user but with "writable_use_sudo"
```
set('writable_use_sudo', true);
```
Result : stucked with the prompt, without asking for the password.
```
➤ Executing task deploy:prepare
[lims-production] > export SYMFONY_ENV='prod'; echo $0
[lims-production] < myuser@vps:~$
```

Hypothesis : It seems that sudo is executed when overriding the origin ssh user.

Thanks for any help.

Great tool by the way :+1:  I am using it for creating releases, deploy to my staging server, create tag, etc.., works fine.

**Comment by Dasky** [comment]
Read carefully documentation about "become" behaviour and how it handles "sudo"
Set correct permissions
Deleted previous noisy comment.
Thanks
