### ISSUE TITLE
Add input argument to Task

### ISSUE THREAD

**Issue by KaipiYann** [deployphp/deployer#176]
Hi,

Would love to add an option or argument to my task, is it possible ?  How can we pass a parameter to the task ?

Thks

**Comment by elfet** [comment]
Hi! Yes, it is possible! But now this feature now in pull request #143 and still now finished. This feature 100% will be in Deployer 3 when i or somebody else finish it.

**Comment by elfet** [comment]
Done! Use `argument` and `option` functions.
