### ISSUE TITLE
Interactive questions

### ISSUE THREAD

**Issue by ahmadmayahi** [deployphp/deployer#1760]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.4

### Description 
I like Symfony when it comes to creating an entity using the `maker` bundle, It asks you some questions about the fields that you are adding, like the field name, field type etc...

It's so nice to see Deployer asks some questions when we run `dep deploy init`, questions like:

- hostname.
- ssh port.
- password / identity file

**Comment by antonmedv** [comment]
Done.
