### ISSUE TITLE
The file 'dep' is not executable by this user

### ISSUE THREAD

**Issue by simpel** [deployphp/deployer#1766]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | MacOS
| Remote Machine OS | N/A

### Steps to reproduce

1. Follow the installation instructions on deployer.org
2. Try to run `dep` but it fails eventhough `/usr/local/bin` is in my `$PATH`

### Output log
```
simpel@star ~/d/G/p/joelsanden.se> dep init
fish: The file 'dep' is not executable by this user
simpel@star ~/d/G/p/joelsanden.se> 
sudo dep init
sudo: dep: command not found
simpel@star ~/d/G/p/joelsanden.se> 
```

```
simpel@star ~/d/G/p/joelsanden.se> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
```

**Comment by xyNNN** [comment]
What's the output of `ls -halt /usr/local/bin/dep`?

**Comment by xyNNN** [comment]
You don't have execution rights for the phar file with this user.
`chmod +x deployer.phar' should solve your problem.
