### ISSUE TITLE
Why was the cd() function removed?

### ISSUE THREAD

**Issue by tomzx** [deployphp/deployer#177]
I think that the following syntax is much nicer than the second one.

```php
cd('{some_path}');
run('my_super_command'); // in {some_path}
```

```php
run('cd {some_path} && my_super_command');
```

Thus my question: why was cd() removed in v3?

**Comment by elfet** [comment]
I removed `cd` function to simplify `run` function. I think `run('cd {some_path} && my_super_command')` more readable than. But if is possible to bring back `cd` function.

**Comment by tomzx** [comment]
Most tasks generally occur within a specific directory. I think the `cd` syntax follows the DRY (Don't Repeat Yourself) principle which is a good thing. Furthermore, since your preference (`cd`-ing on every command) still would work with `cd` support, it would probably be better to have it than not.

```php
cd('{some_path}');
run('my_super_command');
run('my_super_command');
run('my_super_command');
run('my_super_command');
```

```php
run('cd {some_path} && my_super_command');
run('cd {some_path} && my_super_command');
run('cd {some_path} && my_super_command');
run('cd {some_path} && my_super_command');
```

I do understand that the removal of `cd` (and the working path paradigm) was to simplify the `run` function. I guess the problem is that the phpseclib (and I assume the ssh2 extension) both run one-off commands where you are back to the home directory after each command, which means if we want emulate a working directory, we have to do it ourselves.

**Comment by elfet** [comment]
Ok, will bring back `cd` func. :+1:

**Comment by elfet** [comment]
`cd` is back!
