### ISSUE TITLE
Cache for Build server strategy

### ISSUE THREAD

**Issue by coreyworrell** [deployphp/deployer#1773]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
If using the "Single server" strategy, `update_code` task uses option `git_cache`. If using the recommended "Build server" strategy, no cache is available by default. It is easy enough to create task, but maybe this could be integrated into core somehow.

```php
task('deploy:update_code', function () {
  if (has('previous_release')) {
    run('rsync -a {{previous_release}}/ {{release_path}}/');
  }
  
  upload('.', '{{release_path}}', ['options' => [
    '--checksum',
    '--delete',
  ]]);
});
```

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
