### ISSUE TITLE
Access current stage parameter in local task

### ISSUE THREAD

**Issue by DenisMir** [deployphp/deployer#1776]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 6.2
| Local Machine OS  | OSX
| Remote Machine OS | Google Cloud

I have the following issue. I'd like to deploy some files of the project to a Google Cloud CDN. 

I'm doing this as a task running locally. But I want to use the stage parameter in code when running something like `.bin/dep google:deploy production`. 

Unfortunately `get('stage')` does hand back an empty string when running a task locally. Is there another way to access the current stage parameter in a local task so that I'm getting back `production` in the example above?

**Comment by antonmedv** [comment]
This is known issue. Will be fixed in next v7 release. Now you can pass it as env variable.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
