### ISSUE TITLE
Make user confirm if older tag is deployed

### ISSUE THREAD

**Issue by tobias47n9e** [deployphp/deployer#1777]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | master
| Local Machine OS  | Linux
| Remote Machine OS | Linux

### Description 
Is it currently possible to configure or is it planned to warn the user if they don't deploy the newest tag?

I think that would add a lot of security to deploying if I would get a prompt for older tags which I need to confirm in order to continue with deployment. A small typo could potentially deploy code that is months or even years old.

**Comment by antonmedv** [comment]
You can do it by your self in custom task.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
