### ISSUE TITLE
http_user detection command can return wrong user

### ISSUE THREAD

**Issue by krukru** [deployphp/deployer#1778]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug/Feature Request
| Deployer Version  | v6.3.0
| Local Machine OS  | Tried on macOS 10.14.1 (but shouldn't be relevant in this case)
| Remote Machine OS | Ubuntu server 16.04, Running apache2

### Description 
The command for detecting http_user (`ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | awk '{print $2}'`) returned a user who is not the true webserver user, in my case I am running apache webserver.
In turn this prevents writable_dirs to work properly.

Why does this happen and who was the user returned? 

On my server, I have a service running called "apache_exporter", owned by user "foo".
When running the first part of the command `ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx'` I can see that "apache_exporter" service survives grep and pops up on top of the list and in turn the owner of this services (foo) gets returned as `http_user` in deployer.

Maybe a better strategy would be to throw an exception when there are multiple unique http_user candidates, and request the user to manually set this variable. This would of course break BC in a very bad way, but would never result in a bad build.

How to mitigate: Manually set http_user. Also note in docs that this detection strategy produces fuzzy results, and suggest manually setting whenever possible.

### Steps to reproduce

Create new daemon service called "apache_exporter", run it under some user who is not your webserver user.
Run deployer, but do not manually set http_user

Expected: http_user will be that of the webserver
Actual: http_user equals the user who owns apache_exporter service

**Comment by antonmedv** [comment]
> Maybe a better strategy would be to throw an exception when there are multiple unique http_user candidates, and request the user to manually set this variable.

This will be awesome. Can you create it as PR?

**Comment by krukru** [comment]
Yea, no problem :)

**Comment by andrey-helldar** [comment]
@antonmedv, In the latest version of the deplorer, the problem has reappeared:

v.6.4.3 (working):
```
$httpUserCandidates = explode("\n", run("ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort | awk '{print $2}' | uniq"));
```

v6.4.4 (not working):
```
$httpUserCandidates = explode("\n", run("ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort | awk '{print $NF}' | uniq"));
```

Diff:
```
...awk '{print $2}' | uniq")); // working
...awk '{print $NF}' | uniq")); // not working
```

PR( https://github.com/deployphp/deployer/compare/v6.4.3...v6.4.4#diff-79c5ca66796e35d33eedee02bae72ad8R27) 

File: [recipe/deploy/writable.php#L27](https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php#L27)

**Comment by andrey-helldar** [comment]
This bug is caused by changes in https://github.com/deployphp/deployer/commit/10ba0fae78e9635eebc597566ba5fd32d77667ac commit.
