### ISSUE TITLE
How do i write a task for a remote host?

### ISSUE THREAD

**Issue by hobsRKM** [deployphp/deployer#1780]
desc('Run a bash script');
task('test', function () {
    run('sh test.sh');
});
If I run dep --hosts domain.com test

i get an error 
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "domain.com" is not defined.
Although domain.com is defined and works if i run dep deploy staging

**Comment by antonmedv** [comment]
try dep test --hosts="domain.com"
