### ISSUE TITLE
Build Server uploading zip

### ISSUE THREAD

**Issue by fnowacki** [deployphp/deployer#1783]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question/Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Is any way to upload by Build Server .zip with built project? Uploading 115k files to 15 app nodes sucks 😓

**Comment by lexjwa** [comment]
When I try to upload zip file, it is uploading but it corrupt the file on the production server. 

task('upload', function () {
    upload(__DIR__ . "/.build/current.zip", '{{release_or_current_path}}');
});

@antonmedv @fnowacki 
Can you please take a look on upload task if I am doing something wrong here?
