### ISSUE TITLE
Strange problem about link path.

### ISSUE THREAD

**Issue by kisexu** [deployphp/deployer#1785]
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 

   https://www.patreon.com/deployer

#####################################################################

| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3.0
| Local Machine OS  | macOS
| Remote Machine OS | ubuntu

### Description 

**nginx config**
`root project_path/current/public;`

**my laravel project document**
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 

   https://www.patreon.com/deployer

#####################################################################
Strange problem about link path

| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3.0
| Local Machine OS  | macOS
| Remote Machine OS | ubuntu Laradock

### Description 

**nginx config**
`root project_path/current/public;`

**my laravel project document**
![image](https://user-images.githubusercontent.com/1040190/50753668-94581500-128d-11e9-8ccf-fb130dfdc122.png)

**Strange problem**
1. I can open "domain.com/2.txt",It means "current" symbolic link works.
2. But all code under path releases/2 is not worked. When I change route.php under releases/1 , the  route changed.
3. I cleared all cache, also can't olve the problem.

**Comment by micvog** [comment]
When you say "cleared all cache", do you mean the laravel/composer caches? Because this sounds to me like you're using a nginx/php-fpm setup and you didn't clear the opcache. Does a "systemctl restart php-fpm" help?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
