### ISSUE TITLE
Check for changes in directory

### ISSUE THREAD

**Issue by sweebee** [deployphp/deployer#1786]
I'm using deployer for a lot of Laravel web applications. I also build the front-end with ```npm ci; npm run prod```. The problem with this is that it can take quite some time while most of the time, I did not change anything in the front-end code that needs to be builded.

So I found a solution for this, why not check for changes in specific folders and only build if there are any. This simple solution works perfectly.

It checks if there are changes in a specific folder based on the previous commit.

```php
// Which folders to check if need to build front-end
set('asset_dirs', [
	'resource/assets'
]);

// Build assets
task('npm', function () {
	$should_build = false;
	foreach(get('asset_dirs') as $asset){
		if(exec('git diff --name-only HEAD~1..HEAD ' . $asset)){
			$should_build = true;
		}
	}
	if($should_build) {
		run( 'npm ci; npm run prod' );
	}
});

```

Would be a nice feature to include into the core so you don't have to add this code manually.

**Comment by antonmedv** [comment]
Awesome! Will think about it more. But `git diff --name-only HEAD~1..HEAD ` part maybe difficult. Why only one commit `~1`?

**Comment by sweebee** [comment]
Well i think it depends on how you deploy. I deploy on every commit and for production on a merge request from dev > prod.

But i think it will be saver to look at some more commits. Also make sure you deploy the assets to a shared directory.

**Comment by kanevbg** [comment]
I will add there this addition there should be a general-purpose check enabled by default - if the last release uses the same commit as the one requested for deployment than skip updating (if not in forced mode)

**Comment by antonmedv** [comment]
I find this is really difficult to implement. If someone whats to implement in as contrib recipe - your are well come.

**Comment by sbrow** [comment]
What makes this so difficult to implement? The way I see it, all that's needed is to add a property to tasks that contains the files to watch, and before each task is run, check all the listed files against the previous release. If none of them changed, skip the task. 

e.g.
```php
// src/Task/Task.php
<?php
namespace Deployer\Task;

class Task
{
   // An array of globs to check before running the task.
    public array $watch = [ '*' ];

    // ...
}

**Comment by Schrank** [comment]
@sbrow Thanks for your comment and I think if you put all the configuration on the user, you are right. One needs to make sure, that files which are not on git are ignored for example.

I can only repeat Anton: Feel free to volunteer and implement it! Happy to review your PR and if you have questions feel free to ask!
