### ISSUE TITLE
How deploy via shell_exec?

### ISSUE THREAD

**Issue by Rishats** [deployphp/deployer#1794]
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 

   https://www.patreon.com/deployer

#####################################################################

| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | v6.3.0
| Local Machine OS  | Linux Ubuntu 18.04 (Homestead)
| Remote Machine OS | Linux Ubuntu 16.04 LTS

### shell_exec
I try run ```shell_exec(./vedor/bin/dep deploy production)``` 
After i got ```➤ Executing task deploy:failed``` but if try to do it via CLI, all good.

What should i do to fix this problem?

### Output log
*17-01-2019 (07:10:49)
*** AUTO DEPLOY INITIATED ***
✈︎ Deploying production on production
• done on [production]
➤ Executing task deploy:prepare
[production] > echo $0
[production] < ssh multiplexing initialization
[production] < Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 2.6.32-042stab134.3 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

[production] < bash
[production] > if [ ! -d /var/www/example.com ]; then mkdir -p /var/www/example.com; fi
[production] > if [ ! -L /var/www/example.com/current ] && [ -d /var/www/example.com/current ]; then echo 'true'; fi
[production] > cd /var/www/example.com && if [ ! -d .dep ]; then mkdir .dep; fi
[production] > cd /var/www/example.com && if [ ! -d releases ]; then mkdir releases; fi
[production] > cd /var/www/example.com && if [ ! -d shared ]; then mkdir shared; fi
• done on [production]
✔ Ok [3s 373ms]
➤ Executing task deploy:lock
[production] > if [ -f /var/www/example.com/.dep/deploy.lock ]; then echo 'true'; fi
[production] > touch /var/www/example.com/.dep/deploy.lock
• done on [production]
✔ Ok [690ms]
➤ Executing task deploy:release
[production] > cd /var/www/example.com && (if [ -h release ]; then echo 'true'; fi)
[production] > cd /var/www/example.com && (if [ -d releases ] && [ "$(ls -A releases)" ]; then echo 'true'; fi)
[production] < true
[production] > cd /var/www/example.com && (cd releases && ls -t -1 -d */)
[production] < 29/
[production] < 28/
[production] < 27/
[production] < 26/
[production] < 25/
[production] > cd /var/www/example.com && (if [ -f .dep/releases ]; then echo 'true'; fi)
[production] < true
[production] > cd /var/www/example.com && (tail -n 15 .dep/releases)
[production] < 20190103121056,18
[production] < 20190103123226,19
[production] < 20190107220546,20
[production] < 20190109021616,21
[production] < 20190109142425,22
[production] < 20190110000429,22
[production] < 20190110002037,23
[production] < 20190111014403,24
[production] < 20190114072853,25
[production] < 20190116003427,26
[production] < 20190116060331,27
[production] < 20190117014502,28
[production] < 20190117015734,29
[production] < 20190117015845,29
[production] < 20190117020646,29
[production] > cd /var/www/example.com && (if [ -d /var/www/example.com/releases/30 ]; then echo 'true'; fi)
[production] > cd /var/www/example.com && (date +"%Y%m%d%H%M%S")
[production] < 20190117021056
[production] > cd /var/www/example.com && (echo '20190117021056,30' >> .dep/releases)
[production] > cd /var/www/example.com && (mkdir /var/www/example.com/releases/30)
[production] > cd /var/www/example.com && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[production] < true
[production] > cd /var/www/example.com && (ln -nfs --relative /var/www/example.com/releases/30 /var/www/example.com/release)
• done on [production]
✔ Ok [4s 208ms]
➤ Executing task deploy:update_code
[production] > command -v 'git' || which 'git' || type -p 'git'
[production] < /usr/bin/git
[production] > /usr/bin/git version
[production] < git version 2.7.4
[production] > cd /var/www/example.com && (if [ -h /var/www/example.com/release ]; then echo 'true'; fi)
[production] < true
[production] > cd /var/www/example.com && (readlink /var/www/example.com/release)
[production] < releases/30
[production] > cd /var/www/example.com && (/usr/bin/git clone -b production --recursive -q --reference /var/www/example.com/releases/29 --dissociate git@gitlab.ibecsystems.kz:web/example.com.git  /var/www/example.com/releases/30 2>&1)
[production] > cd /var/www/example.com && (/usr/bin/git clone -b production --recursive -q git@gitlab.ibecsystems.kz:web/example.com.git /var/www/example.com/releases/30 2>&1)
➤ Executing task deploy:failed
• done on [production]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[production] > rm -f /var/www/example.com/.dep/deploy.lock
• done on [production]
✔ Ok [355ms]

*** AUTO DEPLOY TO PRODUCTION COMPLETE ****

**Comment by antonmedv** [comment]
Check if you can clone git repo. or use deploy key.

**Comment by Rishats** [comment]
> Check if you can clone git repo. or use deploy key.

I can clone repo via user deployer.

**Comment by antonmedv** [comment]
See
>  cd /var/www/example.com && (/usr/bin/git clone -b production --recursive -q git@gitlab.ibecsystems.kz:web/example.com.git /var/www/example.com/releases/30 2>&1)
➤ Executing task deploy:failed

Looks it failed here.
