### ISSUE TITLE
Deployer release policy

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1797]
How often Deployer should be released?

**Comment by kanevbg** [comment]
Here is my opinion.

"As needed" where needed is considered to help the users as soon as possible whether by fixing bug or giving new feature.

New future: planned, developed, tested.
Bug: verified, fixed, tested.
At the end of the day everything tested gets released, no unnecessary hold.

Versioning may stay the same MAJOR.MINOR.PATCH.

Patch increases when the release has only fixes.

Minor changes when there is a change in the functionality (modified or new) but causes no breaking changes. Changes with small BC may be included here if it is possible to use migration algorithm which will auto-execute and self-verify for success.

Major changes when BC introduced and user should manually do changes to upgrade from previous version.

**Comment by krskrs** [comment]
Hi @antonmedv First, I'd like to thank you for developing this very good piece of software! I've a question, not directly related with this thread, but anyways, I've read in various comments that you're woking on some new interesting features for the 7.0 release. Will you commit the new code all together with the 7 release? Or is some 7.0 code already available somewhere on github and I just haven't been able to find it? Some sort of alpha/beta branches where one could see how is development going and/or contribute/comment?

**Comment by antonmedv** [comment]
It's currently in my local _next_ brunch. Then I will ready, I'll push it.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
