### ISSUE TITLE
self-update not working, missing manifest.json

### ISSUE THREAD

**Issue by todeveni** [deployphp/deployer#1802]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.4.3

### Steps to reproduce
Run `dep self-update`

### Output log
```
Looking for updates...
PHP Warning:  file_get_contents(https://deployer.org/manifest.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

**Comment by antonmedv** [comment]
Should be fixed now.

**Comment by todeveni** [comment]
Well, that was quick. Thanks!
