### ISSUE TITLE
Laravel migrations are broken when using inventory

### ISSUE THREAD

**Issue by apihlaja** [deployphp/deployer#1803]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v6.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

It seems #1679 broke multi-target deployments. Now migrations are run only on the first deployment target.

### Steps to reproduce

Configure inventory with two hosts with same stage name and deploy using stage-name. Migrations aren't run on 2nd host.

**Comment by ansraliant** [comment]
Looks like this fragment of code from `ParalellExecutor` might be responsible for the behavior you are describing. 
```
  foreach ($hosts as $host) {
    if ($task->shouldBePerformed($host)) {
      $processes[$host->getHostname()] = $this->getProcess($host, $task);
        if ($task->isOnce()) {
          $task->setHasRun();
        }
    }
  }
``` 
If I'm not mistaken this will create a php process to execute on each host a given task, but if the task was marked as `once` it will only run it in the first host. 

Maybe it was expected for the `once` task this behavior. If we have 3 servers, if all of them share the same DB, which is most likely, then if only one executes the `migrate` task, then it with be fine.

**Comment by martijn94** [comment]
Running into the same problem. The PR doesn't give much insight into why the change was made. Wouldn't it make more sense to add `task('artisan:migrate')->once();` to your deploy file as there is no way(?) to do that the other way around?

**Comment by apihlaja** [comment]
I think `migrate` is safe to run more than once, even against same database. So I guess #1679 is purely performance optimization, ie. it can be safely reverted?

**Comment by leo108** [comment]
@apihlaja I don't think it's safe to run *at the same time in more than one server*, Laravel will run DDL SQL first and then insert the migration name into `migrations` table. It may take a long time to execute DDL SQL if that table has many records.

**Comment by martijn94** [comment]
> @apihlaja I don't think it's safe to run _at the same time in more than one server_, Laravel will run DDL SQL first and then insert the migration name into `migrations` table. It may take a long time to execute DDL SQL if that table has many records.

But wouldnt it make more sense to have this as default behaviour that can be overriden. Especially because it's not possible to undo this in your `deploy.php` file.

**Comment by srgvrnv** [comment]
> Especially because it's not possible to undo this in your `deploy.php` file.

@martijn94 In fact you can have this by adding next code to your `deploy.php`. It will override the default behaviour and run migrations for each target
```
task('artisan:migrate', function () {
    run('{{bin/php}} {{release_path}}/artisan migrate --force');
});
```

**Comment by martijn94** [comment]
> > Especially because it's not possible to undo this in your `deploy.php` file.
> 
> @martijn94 In fact you can have this by adding next code to your `deploy.php`. It will override the default behaviour and run migrations for each target
> 
> ```
> task('artisan:migrate', function () {
>     run('{{bin/php}} {{release_path}}/artisan migrate --force');
> });
> ```

Sounds like a solution for me.

Thanks

**Comment by antonmedv** [comment]
Fixed in master. Please verify.
