### ISSUE TITLE
Is there a way to have a shared directory for the VCS?

### ISSUE THREAD

**Issue by stat1x** [deployphp/deployer#1806]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Hi,
Is it possible to have a dedicated directory for the git repository (as capistrano does https://capistranorb.com/documentation/getting-started/structure/)? This would avoid a `git clone` on each deployment.
Thanks.

**Comment by antonmedv** [comment]
There is no need for this now. git has a feature called shallow clone: reuse files from previuos cloned repos, so only new files are synced. 
https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L88

**Comment by stat1x** [comment]
Ok nice did not know about it! Thanks for the answer.

**Comment by cafferata** [comment]
@stat1x now you know this, can you close this issue? Thanks!
