### ISSUE TITLE
Question: Why `deploy:update_code` task don't use current ref to deploy by default?

### ISSUE THREAD

**Issue by lptn** [deployphp/deployer#1808]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.4.3
| Remote Machine OS | Ubuntu 14.04 (docker image)

`deploy:update_code` task uses the fallowing code:
https://github.com/deployphp/deployer/blob/06658c793e4a52960f3d8fd66cd51740538afb8d/recipe/deploy/update_code.php#L48-L100

The must interesting part is:
```php
$at = '';
if (!empty($branch)) {
    $at = "-b $branch";
}
// ...
run("$git clone $at $depth $recursive $quiet $repository {{release_path}} 2>&1", $options);
```

It has few problems:
 1. HEAD^ for the same branch at remote/origin and local copy of repo maybe different (a developer have forgotten to push their new commit OR other developers have pushed new commits to remote repo). It may lead to unexpected results.
 1. If deployer is the last step of CI+CD pipeline and there are some time-consuming operations (like running tests), developers may push new commits to the branch we want to deploy. So, CI+CD pipepline will ship code that is not the same as code it tested
 1. `'git rev-parse --abbrev-ref HEAD'` returns `HEAD` if CI clones branch and then do checkout to the latest commit on this branch (like Codeship CI does). That means `get('branch')` returns `null`, `$at`  === `null` and `run("$git clone $at $depth $recursive $quiet $repository {{release_path}} 2>&1", $options);` runs `git clone --depth 1 --recursive org/repo {{release_path}} 2>&1` (so it will clone `HEAD` instead of current commit on CI).

https://github.com/deployphp/deployer/blob/06658c793e4a52960f3d8fd66cd51740538afb8d/recipe/deploy/update_code.php#L10-L29

What I propose is to ship current revision/commit by default, it will solve all 3 problems:
 1. `git clone` exits with non-zero status for the case, what is more correct IMO
 1. CI will deploy a commit it tested, not the latest commit on the branch
 1. Codeship (and probably Travis and other CIs) will work without `--revision` or `--branch`  or `--tag` params

## Current (temp) solution
Current solution is to specify revision explicitly:
```sh
deployer.phar deploy $HOST_TO_DEPLOY --revision=$CI_COMMIT_ID
```
where `$CI_COMMIT_ID` is [env variable available on codeship](https://documentation.codeship.com/basic/builds-and-configuration/set-environment-variables/)

PS: I didn't find in deployer what deployer deploys by default (the answer: it tries to deploy current branch (in which the `vendor/bin/dep deploy` is ran.))

**Comment by bolechen** [comment]
+1, any workarounds for github actions?

**Comment by antonmedv** [comment]
So, what is your propose? We can ship in in new v7 with come BC. 

Deploying current branch was good for local deploys. i.e. from developers machine.

**Comment by bolechen** [comment]
> +1, any workarounds for github actions?

EDIT: I found the github actions variables doc at https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables

so you can use like this

```
dep deploy staging -vv --revision=${GITHUB_SHA}
```

**Comment by lptn** [comment]
@antonmedv 
>So, what is your propose? We can ship in in new v7 with come BC.

Basically I just wanted to ship the state of the branch we've tested on our CI. I've described 3 problems with current approach, 2nd is the most important for my case:
>If deployer is the last step of CI+CD pipeline and there are some time-consuming operations (like running tests), developers may push new commits to the branch we want to deploy. So, CI+CD pipepline will ship code that is not the same as code it tested

**Comment by antonmedv** [comment]
So you suggest instead of a branch, deploy a current ref as default?

**Comment by lptn** [comment]
@antonmedv 
>So you suggest instead of a branch, deploy a current ref as default?

exactly
