### ISSUE TITLE
Custom 'on' Filters

### ISSUE THREAD

**Issue by bbceg** [deployphp/deployer#1809]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Hi,
I have several tasks that make use of the onHosts filter. One example is to ensure apache related tasks happen only on apache web servers and nginx related tasks happen only on nginx web servers. These individual tasks usually make up part of the same 'parent' task but are skipped depending on the environment. However because I'm using the onHosts filter this means that every time I create a new web server I have to add a new host to each of the relevant onHosts filters depending on the type of web server it is. This is ungainly and the list will grow infinitely until I decommission servers.

I'm wondering if it would be possible to allow custom filters e.g. on('custom-filter-name') or, in the case of the above example, on('apache') and on('nginx'). Naturally the custom filter values would need to be added to any host definitions.

In case it helps here is a simple example before the proposed change:

```
task('initialise_website', [
    'setup_remote',
    'deploy',
    'web_server:apache_reload',
    'web_server:nginx_reload'
]);

task('web_server:apache_reload', function () {
    run('sudo service apache2 reload');
})->onHosts('
	apachehostone.com,
	apachehosttwo.com,
	apachehostthree.com,
	apachehostfour.com
)->setPrivate();

task('web_server:nginx_reload', function () {
    run('sudo systemctl reload nginx');
})->onHosts(
	'nginxhostone.com',
	'nginxhosttwo.com',
	'nginxhostthree.com',
	'nginxhostfour.com'
)->setPrivate();
```

and after:

```
task('initialise_website', [
    'setup_remote',
    'deploy',
    'web_server:apache_reload',
    'web_server:nginx_reload'
]);

task('web_server:apache_reload', function () {
    run('sudo service apache2 reload');
})->on('apache')->setPrivate();

task('web_server:nginx_reload', function () {
    run('sudo systemctl reload nginx');
})->on('nginx')->setPrivate();
```

Of course it's entirely possible there's a better way to tackle this sort of problem, so if anyone has any suggestions I'd be grateful to hear them. I considered using variables but the code seems more cluttered with this approach.

**Comment by antonmedv** [comment]
You can use rule filter for this.

**Comment by antonmedv** [comment]
https://deployer.org/docs/tasks.html#by-roles

**Comment by bbceg** [comment]
Thanks Anton. I did consider that and am not quite sure why I didn't follow through with it... Seems like it'll work just fine. Thanks for the tool by the way.
