### ISSUE TITLE
Update Sym Link after deploy to another site

### ISSUE THREAD

**Issue by albertski** [deployphp/deployer#1815]
I currently have a Drupal 7 site that uses Deployer and a separate Drupal 8 site which is a folder inside the Drupal 7 site.

I have the following inside my deploy.php for the Drupal 7 site:

```
set('shared_dirs', [
  'web/d8_site',
]);
```

I have a simlink setup to the d8 site inside `shared/web`.

```
d8_site ->  /home/myserver/sites/d8_site/current/web/
```

The problem is that inside the Drupal 7 releases, the sym link is not to current but to an actual release number:

```
d8_site -> ../../../../d8_site/releases/10/web/
```

So whenever I make a change to the D8 site, it never shows the latest code on live because the sym link stays to the same release number.

Anyone know of a good way to handle updating the sym link on a separate site that was not updated.

**Comment by antonmedv** [comment]
Create a task for manual symlinking currect d8. Add it last in chain.

**Comment by albertski** [comment]
Do you by any chance know if there is an easy way to get the latest release number?  I have to get the latest release number from the D8 site and then get the latest release number of the D7 site and update the symlink in the latest D7 release to the latest D8 release.

**Comment by antonmedv** [comment]
Can `.dep/releases` file, tail is your latest)

**Comment by albertski** [comment]
Turns out I didn't even need to go through `.dep/releases`.   I created this task:

```
task('d7:symlink', function () {
  run('cd ~/sites/d7/current/web && ln -nfs {{release_path}}/web d8_site');
});
``
