### ISSUE TITLE
Version of `phpseclib` dependencies should be fixed

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#182]
> Package phpseclib/phpseclib#dev-master@dev is not fixed.

WTF with phpseclib? Still cannot install via composer require...

**Comment by elfet** [comment]
What the solution to be able to install Deployer via Composer?

We need this: `composer require deployer/deployer:*` :angry:

**Comment by swemaniac** [comment]
@elfet I'm not really sure what the problem is, can I help somehow?

**Comment by elfet** [comment]
Try in your terminal next command:
```
composer require deployer/deployer:~3.0@dev
```
Got error?
Now we need to fix it.

**Comment by swemaniac** [comment]
Okay so it works if I manually require phpseclib/phpseclib:2.0.*@dev first, so if you change the deployer package require to 2.0.*@dev instead of dev-master@dev maybe it'll work?

**Comment by elfet** [comment]
Now fixed. Hardcoded :scream:

**Comment by swemaniac** [comment]
Hardcoding a dependency version is fine in my opinion. You can always change it if you need to update!

My issue with this though is that the phpseclib package apparently isn't in 2.x stable (last stable is 0.3?) and you're requiring 2.x@dev so if you want to use deployer you need to specify minimum-stability as dev in your composer file. Otherwise that dependency will fail :(

**Comment by elfet** [comment]
Now must work. Try it: `composer require deployer/deployer:dev-master@dev`

**Comment by swemaniac** [comment]
Yes that works :) But the @dev is the same as saying I want the dev/beta stuff and not stable stuff, but I guess that's because phpseclib has no stable package right?

**Comment by elfet** [comment]
Yes, right.

**Comment by naquad** [comment]
When will this get to composer package? I still experience the same error in 2.x:

```
composer require --dev deployer/deployer:'~2.0'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing elfet/php-ssh (v1.1.0)
    Downloading: connection...    Failed to download elfet/php-ssh from dist: The "https://api.github.com/repos/elfet/php-ssh/zipball/439becf180272542cbf154df4856a49dd3c4bf04" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing elfet/php-ssh (v1.1.0)
    Cloning 439becf180272542cbf154df4856a49dd3c4bf04


                                                                                             
  [RuntimeException]                                                                         
  Failed to clone git@github.com:elfet/php-ssh.git via git, https, ssh protocols, aborting.  
  - git://github.com/elfet/php-ssh.git                                      
```

and when I try to install dev or >=2.0.2:

```
composer require --dev deployer/deployer:'~2.0, >=2.0.2'                                                                                                        ⏎
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - deployer/deployer v2.0.5 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v2.0.4 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v2.0.3 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v2.0.2 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - Installation request for deployer/deployer ~2.0, >=2.0.2 -> satisfiable by deployer/deployer[v2.0.2, v2.0.3, v2.0.4, v2.0.5].


```

**Comment by elfet** [comment]
Шебы because of phpseclib. Add minimum-stability `dev` to composer.json file. Will be fixed when phpseclib will release lib.

**Comment by elfet** [comment]
Try this:
```json
{
    "require": {
        "deployer/deployer": "2.0.5"
    },
    "provide": {
        "ext-ssh2": "*"
    },
    "minimum-stability": "dev"
}
```
