### ISSUE TITLE
Question about symlinks and realpath cache

### ISSUE THREAD

**Issue by jpleau** [deployphp/deployer#1821]
Issue Type: Question 
Deployer Version: 6.4
Local Machine OS: Ubuntu 18.04
Remote Machine OS: cPanel / CloudLinux / RHEL (I think?)

Hi.

I'm using deployer to deploy PHP code to servers managed by cPanel. I don't have root access or any privilege to reload php-fpm.

Here's how this is setup:

/home/user/public_html is a symlink to /home/user/code/current/public

The issue I'm facing is that right after the deploy:symlink task is done, some users will encounter old versions of the project, and some files are getting included twice leading to errors (ie: releases/4/my_file.php and releases/5/my_file.php both being included with require_once).

After reading a bit this seems to be caused by PHP's realpath cache (this server doesn't use nginx so I cannot use $realpath_root.).

The workaround I had was to upload a script that contained cleatstatcache(true), and run it via `curl` after symlink, but it doesn't seem to always work (if I spam refresh the website during the deploy I am bound to land on a page that tries to load files from 2 releases).

So I'm asking here in hope someone has an idea on how to workaround this little problem.

Cheers

**Comment by lkraav** [comment]
https://deployer.org/recipes/cachetool.html

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
