### ISSUE TITLE
Unable to disable recursive mode excepts setfacl mode

### ISSUE THREAD

**Issue by janreges** [deployphp/deployer#1822]
Hi,

Thank you for Deployer - we use it few years and it's great tool! 👍 

We encountered one problem. Deployer contains `writable_chmod_recursive` which is handled only for mode "chmod" and it is not suitable for us.

All another modes are forced to be recursive without option to disable recursive mode.

Default mode `setfacl` is optimal, but when project contains a lot of files, task `deploy:writable` then runs long minutes due to recursive mode, which is unnecessary :-(

Optimal would be one common parameter `writable_recursive` (default: true) used by all modes. Due to backward compatibility, `writable_chmod_recursive` would have priority in `chmod` mode.

What do you think?

Thank you.

**Comment by antonmedv** [comment]
I think this is better. Can you create pull request?

**Comment by janreges** [comment]
@antonmedv PR is ready with updated CHANGELOG.md. Thank you for merge :-)
