### ISSUE TITLE
wrong current dir

### ISSUE THREAD

**Issue by stloc** [deployphp/deployer#1825]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 6.4.3
| Local Machine OS  | ubuntu
| Remote Machine OS | ubuntu

### Description 
current dir must be /home/etudes/www/methode instead of /home/etudes

### Steps to reproduce
dep pwd dev

### Content of `deploy.php`
```php
host('etudes@172.24.XXX.X')
    ->stage('dev')
    ->set('deploy_path', '/home/etudes/www/methode')
;
task('pwd', function () {
    $result = run('pwd');
    writeln("Current dir: $result");
});
```

### Output log
➤ Executing task pwd
Current dir: /home/etudes
✔ Ok

**Comment by rikwillems** [comment]
Deployer does not go into the deploy_path when connecting to the server. You need to add it to your task.
See usage: https://github.com/deployphp/deployer/search?q=deploy_path&unscoped_q=deploy_path

**Comment by stloc** [comment]
the documentation is not going in this direction

![image](https://user-images.githubusercontent.com/4832070/57618429-aa4f4c80-7583-11e9-8f9c-498a1ab096c4.png)

**Comment by antonmedv** [comment]
Doc update is needed.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
