### ISSUE TITLE
Missing explicit extension dependencies in composer.json

### ISSUE THREAD

**Issue by guillaume-perreal** [deployphp/deployer#1826]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.4.3
| Local Machine OS  | Irrelevant
| Remote Machine OS | Irrelevant

### Description 

Right now, deployer uses a few PHP extensions. Unfortunately they are not listed in the composer.json, which prevents checking them at installation time.

According to [ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker), the following symbols and matching extensions are used:

| unknown symbol         | guessed dependency |
| ----------------------- | ------------------- |
| [...] | |
| pcntl_fork             | ext-pcntl          |
| posix_setsid           | ext-posix          |
| CURLOPT_SSL_VERIFYPEER | ext-curl           |
| json_encode            | ext-json           |
| JSON_PRETTY_PRINT      | ext-json           |
| curl_init              | ext-curl           |
| curl_setopt            | ext-curl           |
| CURLOPT_CUSTOMREQUEST  | ext-curl           |
| CURLOPT_HTTPHEADER     | ext-curl           |
| CURLOPT_POSTFIELDS     | ext-curl           |
| CURLOPT_RETURNTRANSFER | ext-curl           |
| CURLOPT_FOLLOWLOCATION | ext-curl           |
| CURLOPT_MAXREDIRS      | ext-curl           |
| CURLOPT_CONNECTTIMEOUT | ext-curl           |
| CURLOPT_TIMEOUT        | ext-curl           |
| curl_exec              | ext-curl           |
| curl_close             | ext-curl           |
| json_decode            | ext-json           |
| json_last_error        | ext-json           |
| JSON_ERROR_NONE        | ext-json           |
| json_last_error_msg    | ext-json           |
| [...] | |

I suggest to explicit these dependencies in composer.json (or suggesting those that are optional).

**Comment by antonmedv** [comment]
Not all of them are requirements. For example you can use deployer without curl.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
