### ISSUE TITLE
Documentation parses markdown in command

### ISSUE THREAD

**Issue by MartijnDwars** [deployphp/deployer#1827]
On https://deployer.org/docs/configuration.html the page says 'writablechmodmode' when in fact the option is named `writable_chmod_mode`. The underscores are parsed as markdown and make "chmod" italic. I already thought the formatting was strange, but I had to check the deployer source code to figure out my mistake.

**Comment by antonmedv** [comment]
Thanks! Will fix it.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
