### ISSUE TITLE
How to abort if some checks fail

### ISSUE THREAD

**Issue by dustingraham** [deployphp/deployer#1828]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question/Feature Request
| Deployer Version  | 6.0.5
| Local Machine OS  | centos 7
| Remote Machine OS | centos 7

### Description 
I searched documentation for "abort" "cancel" "exit" but couldn't find any instructions on how to cancel a deploy if some checks are not met.

When running in *parallel mode* despite calling "exit" it displays the error message on all three hosts, then continues on to the next step.

Question: How can I do this so it aborts when running in parallel?
Feature Request: Document how to exit if some pre-flight checks fail.

### Steps to reproduce
```php
task('deploy:tool_check', function() {
    // Consider checking other versions of stuff as well?
    $required = [
        'npm' => '6.4.1',
    ];
    $version = run("{{bin/npm}} --version");
    writeln('➤ NPM Version: <comment>'.$version.'</comment> From: {{bin/npm}}');
    if ($version < $required['npm']) {
        writeln('<error>✗ Required NPM Version: '.$required['npm'].' Found:'.$version.'</error>');
        exit;
    }
});
```

```
task('checknpm', [
    'apache-shell:on',
    'deploy:tool_check',
    'apache-shell:off',
]);
```

Running `dep checknpm production -p` I expect it to quit after `deploy:tool_check` but it continues to `apache-shell:off`

Somewhat similar to issue #767

**Comment by antonmedv** [comment]
Throw GrasefulSutdownException.

**Comment by dustingraham** [comment]
I don't see any GracefulShutdownException class, but i see if i `throw new \Exception('Required NPM missing.');` it does abort the parallel execution.

Thank you, might be useful to add to the documentation.

**Comment by VitruxPT** [comment]
Hey @dustingraham 😄 

Just came upon this issue and @antonmedv had some typos in the class name, I believe he was trying to say this instead:

`throw new GracefulShutdownException('your optional msg here')`

Cheers!
