### ISSUE TITLE
Upload dependecies only if vendor directory is changed

### ISSUE THREAD

**Issue by Sogl** [deployphp/deployer#1829]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.2
| Local Machine OS  | Linux 4.9.93-linuxkit-aufs x86_64 (Alpine 6.4.0 Docker container), OSX Sierra 10.12.5 (host)
| Remote Machine OS | Linux 4.9.103-timeweb x86_64 (Ubuntu 14.04)

### Description 

Hello!
Fisrt of all, thank you for beautiful library and quick support.

I use Deployer to deploy Laravel project to shared Timeweb hosting (see my script in Steps to reproduce section and its output in Output log section). All works fine, but I have memory limit on remote server for executing command `composer install / update` and `yarn/npm install`. Sometimes I have updates in `composer.json` and it become troubles with doing FTP upload or Hosting CP upload `vendor` to server by hands.

My idea for now is to check `vendor` size on localhost and remote host and if folder has changes, delete `vendor` on remote and upload updated version (it would be nice to gzip it first). If this can be done with minimal data transfer (check and transfer only the changed `vendor` directories/files), then it is even better.

Any ideas/thoughts how to achieve that with Deployer?

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/laravel.php';
// require 'recipe/npm.php';

//custom to 7.1 ver in timeweb
set('bin/php', '/opt/php71/bin/php -d memory_limit=1024M');
set('bin/composer', '/opt/php71/bin/php -d memory_limit=1024M /home/s/user/bin/composer');

//disable relative symlinks
set('use_relative_symlink', false);

// Project name
set('application', 'mysite.ru');

// Project repository
set('repository', 'git@bitbucket.org:User/project.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server
add('writable_dirs', []);


// Hosts

//host('timeweb')
host('server.timeweb.ru')
    ->user('user')
    ->identityFile('~/.ssh/timeweb')
    ->set('deploy_path', '~/{{application}}');

// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// Build assets remote
task('npm:build', function () {
    run("cd {{release_path}} && {{bin/npm}} run production");
});

task('deploy:symlink-public', function () {
    run("cd {{deploy_path}} && {{bin/symlink}} {{deploy_path}}/current/public {{deploy_path}}/public_html");
});

// Build assets locally
task('npm:local:build', function () {
  runLocally("yarn run production");
});

task('upload:env', function () {
    upload('.env.production', '{{deploy_path}}/shared/.env');
})->desc('Environment setup');


// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.
//before('deploy:symlink', 'artisan:migrate');

task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'upload:env',
    'deploy:shared',
    'deploy:vendors',
    // server drop this option (memory limit)
    // 'npm:install',
    // 'npm:build',
    // ...
    // 'deploy:writable',
    'artisan:storage:link',
    'artisan:view:clear',
    'artisan:config:cache',
    'artisan:optimize',
    'deploy:symlink',
    'deploy:symlink-public',
    'deploy:unlock',
    'cleanup',
]);



```

### Output log

All works fine now:
```
laradock@8d9c2dbed70e:/var/www/user$ dep deploy
✈︎ Deploying master on server.timeweb.ru
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
Counting objects: 687, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (349/349), done.
Writing objects: 100% (687/687), done.
Total 687 (delta 294), reused 684 (delta 291)
Connection to server.timeweb.ru closed.
✔ Ok
✔ Executing task upload:env
✔ Executing task deploy:shared
✔ Executing task deploy:vendors
✔ Executing task artisan:storage:link
✔ Executing task artisan:view:clear
✔ Executing task artisan:config:cache
✔ Executing task artisan:optimize
✔ Executing task deploy:symlink
✔ Executing task deploy:symlink-public
✔ Executing task deploy:unlock
✔ Executing task cleanup
```

**Comment by Sogl** [comment]
@antonmedv need your attention

**Comment by antonmedv** [comment]
But composer has a cache.

**Comment by Sogl** [comment]
I can clear cache on remote server on next step, I don't think that it costs much server resources like `composer install / composer update`

**Comment by roberto910907** [comment]
@Sogl how much memory do you have available? 
What if you force PHP to use as much memory as is available?
```
set('bin/php', '/opt/php71/bin/php -d memory_limit=-1');
set('bin/composer', '/opt/php71/bin/php -d memory_limit=-1 /home/s/user/bin/composer');
```
Of course this won't work if you only have **1024MB** available. :smile:

**Comment by Sogl** [comment]
@roberto910907 I asked some questions to my hosting service. I have only **256MB** `memory_limit` and **120 seconds** `max_execution_time`.

What do you mean in `new compare function`?
Do I need to build different versions of `vendor` folder and compare last and previous before upload to remote server?

**Comment by roberto910907** [comment]
@Sogl From my point of view, comparing vendor folder's size is easier than comparing the composer.lock content(which is for me the best solution). You could use either method to create a **compare function**. [Functions](https://github.com/deployphp/deployer/blob/master/src/functions.php) are the foundation of deployer, almost every function that you call in your **deploy.php** is declared there. 

That being said, I'd recomend you to compare composer.lock file instead of comparing vendor size. Once you run composer update there could be a remote posibility that both vendor sizes are still being equals(you could have removed a package with the same size that one you installed), also you would need to execute a recursive operation when calculation files size which would affect performance, but if any package hash is changed the content comparison will fail.

Overwrite the default task **deploy:vendors**:

```
task('deploy:vendors', function () {
    // Retrieving composer.lock content from you local environment
    $localComposerContent = runLocally('cat /var/www/html/myLocalProject/composer.lock');
    // Retrieving composer.lock content from you remote server
    $remoteComposerContent = run('cd {{ deploy_path }}/current && cat composer.lock');

    // Something has changed in your local file
    // Probably because you executed `composer update` command
    if ($localComposerContent !== $remoteComposerContent) {
        // Upload your new vendors folder to the remote server
        upload(__DIR__ . "/../vendor", '{{ deploy_path }}/current', ['--recursive', '--compress', '--delete-during', '--force']);
    }
});
```

> If this can be done with minimal data transfer (check and transfer only the changed vendor directories/files)

The upload command will do everything you asked for:
- use rsync
- --compress will compress files when transfering
- --delete-during option deletes files located at the destination which are no longer at the source.

Hope this helps. Please let me know if you have any other question.

**Comment by roberto910907** [comment]
@Sogl 
cc/ @antonmedv 
Would you consider that the provided solution solve the problem?

**Comment by antonmedv** [comment]
I think runLocally + rsync. :).

**Comment by antonmedv** [comment]
Actually this issue can be closed, composer is REALLY fast. And can detect changes much better when we are.
