### ISSUE TITLE
SSH authentication API makes no sense

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#183]
The documentation claims you can authenticate over SSH with a *public key*. It is impossible to authenticate with a public key. A private key is needed to connect to a foreign host over SSH.

The following example from the documentation makes no sense:

```php
server(...)->pubKey('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'pass phrase');
```

Here are the problems:
* The method name implies that a public key can be used for authentication. As discussed, this is impossible.
* The second parameter is a private key. That is; you're passing a private key to a method named *pubKey*. This API makes no sense.

I was considering using Deployer but I would be remiss to use software that is so chronically confused about secure authentication mechanisms.

**Comment by tomzx** [comment]
Hi @Bilge, I had the same questioning and found the following answer in the phpseclib documentation.

> Some private key formats define the public exponent and some don't.  Those that don't define it are problematic when used in certain contexts.  For example, in SSH-2, RSA authentication works by sending the public key along with a message signed by the private key to the server.  The SSH-2 server looks the public key up in an index of public keys and if it's present then proceeds to verify the signature.  Problem is, if your private key doesn't include the public exponent this won't work unless you manually add the public exponent. phpseclib tries to guess if the key being used is the public key but in the event that it guesses incorrectly you might still want to explicitly set the key as being public.

Note that it is a public/private key authentication, hence the name.

**Comment by elfet** [comment]
@Bilge what do you propose?

**Comment by Bilge** [comment]
I propose not using this project.
