### ISSUE TITLE
Config documentation issues

### ISSUE THREAD

**Issue by jamieburchell** [deployphp/deployer#1830]
In the config documentation here:

https://deployer.org/docs/configuration.html#writablechmodrecursive

I believe it should be `writable_chmod_recursive` (with underscores). Several other options here seem to be missing underscores too.

`writable_recursive` and `http_group` are not documented.

Also can't see why chmod needs it's own recursive parameter.

**Comment by antonmedv** [comment]
I see. Will fix it.

**Comment by jamieburchell** [comment]
I believe the last part of this issue is still outstanding.
