### ISSUE TITLE
Set up another SSH connection within a task

### ISSUE THREAD

**Issue by picks44** [deployphp/deployer#1831]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.3.4
| Local Machine OS  | Windows
| Remote Machine OS | Linux (Debian)

Hi, I would like to create a task that can restart PHP-FPM, but my hosting provider only allows me to do this using an admin/sudo account which is global to the VM and different from the one I'm using to deploy my app.

How can I set up, within my deployment process, a new task that will create a second SSH connection with this admin/sudo user to perform the restart?
I have found anything on this around 

Thanks a lot!

**Comment by antonmedv** [comment]
There is a better way of doing this: sudoers
You can allow your user restart server with sudo without using password.

If you are want to connect as admin any way you can create separate host with admin credentials and define only one task for it - restarting.

**Comment by picks44** [comment]
Hi @antonmedv, thanks for your answer, but as I said, my provider won't let me have sudo rights with my user. I can only have those rights with a second user which is global to the VM.

**Comment by antonmedv** [comment]
You can do this with separate host define.

**Comment by picks44** [comment]
Yes, I'm currently trying this, but I'm wondering how to trigger the task with the other connection

```
/**
 *  Admin connection
 */
server('name', 'XX.XXX.XXX.XXX')
    ->user('adm_user')
    ->password('mypassword');

/**
 * Reload PHP-FPM 
 */
task('restart:php', function () {
    run(' sudo /etc/init.d/php7.2-fpm reload');
})->desc('Reload PHP-FPM');

/**
 * Trigger the task 
 */
after('deploy:unlock', 'restart:php')

```

**Comment by antonmedv** [comment]
Try `invoke`
Or just add it to deploy task and restrict to this host

**Comment by picks44** [comment]
I've tried this but it's not working either

```
task('restart:php', function () {
    run('sudo /etc/init.d/php7.2-fpm reload');
})->desc('Reload PHP-FPM')->isOnServer('adm-user');
```

**Comment by antonmedv** [comment]
Hmmm, can't tell why. Try to runnig it with -vvv option.

**Comment by picks44** [comment]
It's not trigerring the new connection

```
Ô×ñ Executing task restart:php
[name] > sudo /etc/init.d/php7.2-fpm reload

```

**Comment by antonmedv** [comment]
Turn off mutliagent

**Comment by picks44** [comment]
I already did!

`set('ssh_multiplexing', false);`

In fact the isOnServer() function is not the one that will trigger the task with the new connection. I'm trying to find it (remember I'm using an old version of Deployer - 4.3.4 - since I'm still on PHP 5.6).

**Comment by picks44** [comment]
I have migrated to v6.4.3 but I still can't see how to do this.

**Comment by antonmedv** [comment]
So, what is the problem?

**Comment by picks44** [comment]
@antonmedv well now I can't even connect as root/admin separately because the password function has been removed apparently...

**Comment by antonmedv** [comment]
Yes, it's unsecure.

**Comment by picks44** [comment]
OK, I've finally managed to do this. I've created a second host and here is my task which I call after deploy

```
task('reload:php-fpm', function () {
    on(host('preprod-adm'), function () {
        run('sudo /etc/init.d/php7.2-fpm reload');
    });
});

after('deploy', 'reload:php-fpm');
```
