### ISSUE TITLE
Use cachetool recipe with deployer.phar

### ISSUE THREAD

**Issue by picks44** [deployphp/deployer#1832]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.4.3
| Local Machine OS  | Windows
| Remote Machine OS | Linex (Debian)

How can I use the cachetool recipe with deployer.phar?
I don't want to use Deployer with Composer...

**Comment by antonmedv** [comment]
Take a look at recioes repo

**Comment by picks44** [comment]
@antonmedv well I did, but it's only talking about the Composer install, which I don't want as I'm using the .phar file...

**Comment by pluseg** [comment]
@picks44 even if you use deployer.phar, you need to create deploy.php with your configs, right? Include desired recipes there:
```
<?php
namespace Deployer;
require 'recipe/symfony4.php'; // or any other

// Application settings
set('application', 'Your App');
set('keep_releases', 3);
...
```

**Comment by carestad** [comment]
> @picks44 even if you use deployer.phar, you need to create deploy.php with your configs, right? Include desired recipes there:
> 
> ```
> <?php
> namespace Deployer;
> require 'recipe/symfony4.php'; // or any other
> 
> // Application settings
> set('application', 'Your App');
> set('keep_releases', 3);
> ...
> ```

The symfony recipe is built-in to this repo, while third-party recipes for Bugsnag, Cachetool, Sentry and Slack (to mention some), are in a separate repo.

I am also wondering if there is a way to use these with the .phar file though.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
