### ISSUE TITLE
new release with updated dependencies

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1835]
would be great if we could get a new release with updated dependencies.

**Comment by pluseg** [comment]
@staabm What deps do you mean? As I see https://packagist.org/packages/deployer/deployer, it uses only few deps and all of them are on bleeding-edge.

**Comment by staabm** [comment]
the phars available via https://deployer.org/download/ contain symfony 3.4 components.

**Comment by pluseg** [comment]
@staabm Okay, got it. Do you see any error with this version of phar? Any deprecations or conflicts? Or it's just a reminder for the future? If you have trouble with that (but I guess it shouldn't conflict with an app code), I would recommend installing deployer via composer globally.

**Comment by staabm** [comment]
I dont have concrete problems, but using symfony 4.x console etc. should provide the latest features of the component

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
