### ISSUE TITLE
Make 'current' directory name configurable

### ISSUE THREAD

**Issue by rikwillems** [deployphp/deployer#1838]
We are using a setup in which the 'current' directory name hold the name of the stage so it becomes: production_current or staging_current
This creates more awareness when working in these directories and is intended to decrease errors by accidental mistakes.

I'd like to propose to make the current directory name configurable so every deploy can arrange it as desired. Would such a feature PR be accepted?

**Comment by antonmedv** [comment]
Long waited feature finally here: c88ebe275f88780b90f4f17774371a556a1ffad4
