### ISSUE TITLE
Deployer is leaving zombie processes

### ISSUE THREAD

**Issue by lukepass** [deployphp/deployer#1839]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v6.4.3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu Server 16.04

### Description 
When executing one of Deployer's command the process is left as a zombie process in my local machine:

![image](https://user-images.githubusercontent.com/6429961/57282005-74eebe80-70ac-11e9-87b4-df0ac9b44a09.png)

I have to terminate them by hand every time or restart the computer.

EDIT: I am using the following command:
```
ps -aux | grep -E 'dep (ssh|deploy)' | grep -v grep | awk '{print $2}' | xargs kill
```

Thanks.

### Steps to reproduce
Execute one of the Deployer commands:

```
dep ssh stage
dep deploy prod
etc...
```

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/symfony4.php';

//
// Configuration
// =============

set('repository', '***');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
add('shared_files', ['.env.local']);
add('shared_dirs', ['public/upload/media']);
add('writable_dirs', ['public/upload/media']);

//
// Hosts
// =====

inventory('hosts.yml');

//
// Tasks
// =====

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'database:migrate');
```

**Comment by antonmedv** [comment]
Will take a look.

**Comment by antonmedv** [comment]
Fixed in master. Please verify.
