### ISSUE TITLE
Getting Symfony timeout

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#184]
Regarding setting the php timeout max_execution_time, set_time_limit, etc the Deployer gives me a timeout when transfering large files between remote and local.

Symfony\Component\Process\Exception\ProcessTimedOutException
The process "..." exceeded the timeout of 60 seconds.

Any hint to increase the value of 60s?

**Comment by EkAndreas** [comment]
Making a pull request to fix this.

**Comment by elfet** [comment]
@EkAndreas please, show all backtrace.

**Comment by EkAndreas** [comment]
What is a backtrace?

**Comment by EkAndreas** [comment]
This issue is solved with my accepted merge. Thanks!

**Comment by lutek** [comment]
the same error:

`
Executing task deploy:prepare
Executing task deploy:release
Executing task deploy:update_code
Executing task deploy:vendors

  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "cd /srv/www/xxxx/dev.xxxxx.pl/releases/20160202154731 &&  composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-interaction" exceeded the timeout of 300 seconds.
`

**Comment by ekandreas** [comment]
You can add a timeout parameter to the task.

**Comment by lutek** [comment]
thx.

**Comment by Dmitri10** [comment]
@lutek, @ekandreas, 
Guys, so how do you use it?

task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'supervisor:stop',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
...
    'cleanup',
])->desc('Deploy your project'); 
I don't see such ability in deployer 5.0.3

**Comment by antonmedv** [comment]
#1256
