### ISSUE TITLE
Deployer detects wrong version when using composer global bin

### ISSUE THREAD

**Issue by xuanquynh** [deployphp/deployer#1842]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v6.4.3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description 
Deployer detects wrong version when using composer global bin.

I installed `deployer/deployer` package as a global composer package instead of using `deployer.phar` file.

```bash
$ composer global show deployer/deployer # Show the installed information of deployer
Changed current directory to /home/xuanquynh/.composer
name     : deployer/deployer
descrip. : Deployment Tool
keywords : 
versions : * v6.4.3
type     : library
$ which dep # Find the executable file
/home/xuanquynh/.composer/vendor/bin/dep
$ dep --version
Deployer master
```

### Steps to reproduce

1. Install deployer as a global composer package.
```bash
$ composer global require deployer/deployer
```

2. Export the composer bin dir to the `PATH` environment variable.
```bash
$ export PATH="$HOME/.composer/bin:$PATH"
```

3. Execute `dep` command with the '--version' option.
```bash
$ dep --version
```

Expected: "Deployer {{expected_version}}"

Actual: "Deployer master"

### Output log
This isn't a bug about deploying, so I just try to describe the problem above.

### Suggestion

I think we may use `vendor/composer/installed.json` file instead of `composer.lock` file.

Quickly refer this line for more details.
https://github.com/deployphp/deployer/blob/a7d03f8febc547344c4f205dd2291a6d40a2af44/bin/dep#L94

It's simply solved by the code sample below:
```php
<?php

$autoload = [
    $deployFilePath . '/vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
    __DIR__ . '/../vendor/autoload.php'
];

$includes = [
    $deployFilePath . '/vendor/deployer/deployer',
    __DIR__ . '/../../../deployer/deployer',
    __DIR__ . '/../'
];

$loaded = false;
$includePath = false;

for ($i = 0; $i < count($autoload); $i++) {
    if (file_exists($autoload[$i]) && file_exists($includes[$i])) {
        require $autoload[$i];
        $vendorDir = dirname($autoload[$i]);
        $includePath = $includes[$i];
        $loaded = true;
        break;
    }
}

// Detect version
$version = 'master';

$installedFile = $vendorDir.'/composer/installed.json';
if (is_readable($installedFile)) {
    $packages = json_decode(file_get_contents($installedFile), true);
    foreach ($packages as $package) {
        if ($package['name'] === 'deployer/deployer') {
            $version = $package['version'];
            break;
        }
    }
}

**Comment by xuanquynh** [comment]
Please correct me if I miss something. Thank you!

**Comment by antonmedv** [comment]
Nice. I think we can use it.

**Comment by xuanquynh** [comment]
@antonmedv Can I help to create a pull request? I have to target "master" branch, don't I?

**Comment by antonmedv** [comment]
Yes, master.

**Comment by xuanquynh** [comment]
This issue is solved.
