### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by rabol** [deployphp/deployer#1844]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | dev.master
| Local Machine OS  | MacOs
| Remote Machine OS | Ubuntu

### Description 
get the latest version

### Steps to reproduce
do a deployment
### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*
Undefined variable: NF in /home/vagrant/code/testdeployer/vendor/deployer/deployer/recipe/deploy/writable.php on line 27

**Comment by antonmedv** [comment]
Hmmm, yes. This maybe a bug. Can you blame git?

**Comment by Schrank** [comment]
https://github.com/deployphp/deployer/pull/1805
https://github.com/deployphp/deployer/blame/master/recipe/deploy/writable.php#L27

I ended up in this code branch because of a missing `set('writable_mode','chmod');`

**Comment by possi** [comment]
This issue breaks deployment: `$NF` isn't escaped. As it is undefined in PHP, therefore awk is executed in shell with empty value at its place:

```
[xxx] > ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort | awk '{print }' | uniq
[xxx] < httpd           nobody
[xxx] > cd ~/webs/core/releases/101 && (mkdir -p var)
[xxx] > cd ~/webs/core/releases/101 && (chmod 2>&1; true)
[xxx] < chmod: missing operand
[xxx] < Try 'chmod --help' for more information.
[xxx] > cd ~/webs/core/releases/101 && (if hash setfacl 2>/dev/null; then echo 'true'; fi)
[xxx] < true
[xxx] > cd ~/webs/core/releases/101 && (getfacl -p var | grep "^user:httpd           nobody:.*w" | wc -l)
[xxx] > cd ~/webs/core/releases/101 && (setfacl -L -R -m u:"httpd           nobody":rwX -m u:`whoami`:rwX var)
[xxx] < setfacl: Option -m: Invalid argument near character 3
```

**Comment by YetiCGN** [comment]
+1 and it's made its way into version 6.4.4 which means I need to downgrade to 6.4.3 to continue.

**Comment by Schrank** [comment]
I would love to send a PR, but I can't test it properly. So it is up to you @YetiCGN - I assume it is only a missing `\` in front of `$NF`.

**Comment by YetiCGN** [comment]
> Hmmm, yes. This maybe a bug. Can you blame git?

Commit 10ba0fa: "Avoid zombie processes in http user resolution. (#1805)"

Changed the variable from `$2` to `$NF`.

**Comment by YetiCGN** [comment]
@Schrank Oh, now I see that you already referenced that last week.

The deployment went through with that 1-byte change. 😉 

	➤ Executing task deploy:writable
	[test] > ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort | awk '{print $NF}' | uniq
	[test] < www-data
	[...]
	• done on [test]
	✔ Ok [839ms]

**Comment by antonmedv** [comment]
Fixed in master. Please verify.
