### ISSUE TITLE
Set a host as default for short command

### ISSUE THREAD

**Issue by lbngoc** [deployphp/deployer#1854]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request

### Description 

I define 2 hosts (`test` & `live`) to deploy my project. Because I often have 1 host per project (only `test`) so I often run with short command `dep deploy`, since after having 2 hosts, the short command also working but it run on 2 hosts sequentially (I don't want deploy to `live` host this time :( ).

Is there any options to require the host name in the command (if have multiple hosts) or set a host as default with it?

I am not sure if Deployer has this option about this because I could not find it on the Wiki [https://deployer.org/docs/hosts.html](https://deployer.org/docs/hosts.html)

**Comment by pluseg** [comment]
@lbngoc If I got your question correctly, you should specify `stage` parameter for each host. For example, `stage: test` and `stage: live` in yaml config (or via `->stage()`). Then specify `set('default_stage', 'test');` in the deploy.php. Next time `dep deploy` will be run on hosts with stage = default_stage. BTW, I recommend specifying stage explicitly every time: `dep deploy test`.
Also, you could specify the target hostname directly: `dep deploy <hostname>`. You didn't share your server inventory config, so I can't help you with concrete command.

**Comment by lbngoc** [comment]
Thanks you for that! It's working.
I only define 2 hosts in inventory file without `stage` param, so that the short command is run all on 2 hosts.
