### ISSUE TITLE
System link pointing to the right release but application running old release

### ISSUE THREAD

**Issue by adekoder** [deployphp/deployer#1859]
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 

   https://www.patreon.com/deployer

#####################################################################

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by adekoder** [comment]
The fist time i deployed the current dir is point to releases/1 which is fine in this case but when i deployed the 2nd release i can see that current dir is pointing to releases/2 but the changes made releases/2 did not show up in the app.

So i cd into the releases/1 and add the changes now the changes reflected in the application,
I have a feeling the system link is cached some how i don't know any help.

**Comment by antonmedv** [comment]
Try restarting server.

**Comment by antonmedv** [comment]
Or clear cache.

**Comment by adekoder** [comment]
i have done those.

**Comment by adekoder** [comment]
i restarted the server , cleared my application cache , it did not work that when i decided to add the changes in the first release to see if it take it take effect and it did.

**Comment by antonmedv** [comment]
Check if server respects symlinks

**Comment by adekoder** [comment]
ok will check it out.

**Comment by adekoder** [comment]
Hi @antonmedv how do i know if server respects symlinks

**Comment by pluseg** [comment]
@adekoder Unfortunately, this question is out of Deployer scope, as we don't know what server you are using. Please try to contact system administrator of your server and/or read thematic forums.
Please try to run `cd /path/to/project/current` — is it pointing to the latest release? If yes, then deployer works fine.

**Comment by adekoder** [comment]
Hey thanks. 
Issue gas been solve , I added tasks in my deployer config file to restart the server and also to reload php-fpm after a successful deploy.

**Comment by pluseg** [comment]
@adekoder Yeah, in php-fpm case it should be done every deploy to see changes immediately.
Cheers!
