### ISSUE TITLE
Revert "Add resource vendors." changes

### ISSUE THREAD

**Issue by tomzx** [deployphp/deployer#186]
Hi,

I don't think it is a good idea to include vendors like it was done in @ f3b8723a8b30fac2d3096f7dd4f32eadf21c7e8c. I'd suggest we revert this change and go back to how it was done before. Here is the reason why I think this:

* `deployer` is not supposed to be included in a project using it as a composer dependency. Much like `composer`, it should be distributed as a `phar`. This way, users do not care about the minimum-stability as the `phar` encapsulates all the requirements.
* Including future changes will be a pain, because it means we have to support/integrate these changes manually instead of simply building a `phar` with their latest revision. This brings me to the point that `deployer` should put its `composer.lock` file under revision.
* Finally, going this route gives us a lot more flexibility. We can decide to switch library without having to care if it'll impact our users.

Let me know what you think.

**Comment by elfet** [comment]
There were several reasons for f3b8723, main is what Deployer must be available via Composer. A lot of users may include in in `require-dev` section. Otherwise instructions to install via Composer will be looking like this:
```
composer require phpseclib/phpseclib:dev-master@dev
composer require deployer/deployer:~3.0
If you does not have ext-ssh2 installed, add "provide": ["hezern/php-ssh"] to composer.json.
```
And this is why:
> Deployer require additional packages, but can not require them through Composer due next issues:
>
> * PhpSecLib does not have stable enough version to require.
> * Herzult/php-ssh requires ext-ssh2, Deployer does not.
>
> Resources vendors must updated manually, or if you know solution create pull request.

**Comment by tomzx** [comment]
I think we should look into what is suggested by [Matthias Noback](http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/). Basically, have `phpseclib` as the main ssh handler and `herzult/php-ssh` as a suggested dependency.

```
    "require": {
        "phpseclib/phpseclib": "dev-master"
    },
    "suggest": {
        "herzult/php-ssh": "SSH support through ext-ssh2"
    },
```

As for `phpseclib` stability, I believe you can replace the `dev-master@dev` to `dev-master` and it'll be considered "stable" (so no need to require it in the including `composer.json`). We should also try to encourage them to release a stable 2.x release so that we may depend on that instead of `dev-master`.

**Comment by elfet** [comment]
Agree with phpseclib. 
But 
```
"suggest": {
        "herzult/php-ssh": "SSH support through ext-ssh2"
    }
```
look not so smooth.

**Comment by tomzx** [comment]
What do you mean by "not so smooth"?

**Comment by elfet** [comment]
How to build phar with `"herzult/php-ssh"`?

**Comment by elfet** [comment]
Done :coffee: fddc573f2897fd847c6b36fb446b0231be8c8bff

**Comment by tomzx** [comment]
:+1: Awesome.

**Comment by EkAndreas** [comment]
But why not move the herzult/php-ssh to require-dev?

**Comment by elfet** [comment]
> But why not move the herzult/php-ssh to require-dev?

Great idea! Thanks!

**Comment by EkAndreas** [comment]
Happy me! Thanks!
