### ISSUE TITLE
build deployer phar with php-scoper

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#1861]
it would be great if the composer.phar could be built with https://github.com/humbug/php-scoper - so the bundled libraries cannot clash with different versions of the same library within the runtime/application.

**Comment by antonmedv** [comment]
Ye, this will be perfect. I'm looking forward to use it.

**Comment by staabm** [comment]
maybe the higher-level component https://github.com/humbug/box from the same github org is also helpful

**Comment by antonmedv** [comment]
The current script is really okay.
