### ISSUE TITLE
New Release Requested

### ISSUE THREAD

**Issue by lucadello91** [deployphp/deployer#1862]
Hello
would it be useful to have a new release for all those that use packages that include deployers and that cannot reference the master directly via composer?

For me it would be very important to have this change (#1775) in order to use ssh in a windows environment.  

Thanks a lot.
Greetings

**Comment by antonmedv** [comment]
Hi, yes. Will release today.

**Comment by neochief** [comment]
+1

**Comment by lucadello91** [comment]
Are there any news about it?

Greetings
Luca
