### ISSUE TITLE
Deployer doesn't display error output from server.

### ISSUE THREAD

**Issue by lichtner** [deployphp/deployer#1864]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug

laravel recipe

### Description 

When some problem appears during deployment to the server, deployer didn't display error output from the server. For that reason is impossible to get what was wrong. I give you two examples.

### Example 1

`laravel/telescope` is the package for debugging. Usually, it is used only on localhost, so developer add it into "require-dev" section in `composer.json`. But sometimes some strange problems appear on the production server. So I tried to use it for production, but I forgot to move a package from `require-dev` to `require`. The problem was that the deployment process fails, but I didn't see the output from the server. I have to run this:

`@php artisan package:discover --ansi`

on production server to see the real output. I lost a few hours when I realize this. I did not expect that deployer did not display the exact same error output from the server.

### Example 2

Laravel recipe includes also `php artisan route:cache` command. There was also a problem with an exception (doesn't matter which one, in this case it was this):

`LogicException  : Unable to prepare route [api/user] for serialization. Uses Closure.`

But I didn't know about it, because deployer did not display it. 

### Question

It is possible to display all server output exactly like on the server during the deployment process?

**Comment by antonmedv** [comment]
Try `-vvv` option.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
