### ISSUE TITLE
Is it possible to add ignored directories and files to update_code task?

### ISSUE THREAD

**Issue by Chrisedmo** [deployphp/deployer#1865]
Is it possible to add ignored directories and files to _update_code_ task? I know I can use rsync, but I'm having trouble getting it to work. And I prefer to to use git… but I need to exclude the a few folders, but I want them in my git repo; ie SASS and Src JS files etc?

**Comment by antonmedv** [comment]
Since deployer is using git clone, you can try to use .gitattributes or just delete dirs after update_code.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
