### ISSUE TITLE
Console info looks corrupted

### ISSUE THREAD

**Issue by hanckey** [deployphp/deployer#1867]
Console info looks corrupted. Something like this http://joxi.ru/KAxMYKoIZpaBgr.jpg
What am I doing wrong? Working on MacBook Air, MacOS Mojave 10.14.5

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
