### ISSUE TITLE
On parallel mode the process hangs of "deploy: prepare"

### ISSUE THREAD

**Issue by tebaly** [deployphp/deployer#1868]
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 

   https://www.patreon.com/deployer

#####################################################################

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug 
| Deployer Version  | v6.4.3
| Local Machine OS  | ubuntu 16.04
| Remote Machine OS | ubuntu 18.04

### Description 
According to the documentation, it is possible to execute a deployment of several application variants (stages) on one server. When I enable parallel mode (-p option), the process hangs on the execution of "deploy: prepare" in one of the stages (from 3 to 5 depending on the server).

### Steps to reproduce
This seems to be due to the simultaneous connection to the same server several times when the stages are on the same server.

### Content of `deploy.php`
```php
// In normal mode(not parallel mode), it works fine.
```

### Output log
enable detailed debugging (-vvv option) - hangs immediately after "done on [previous stage]"

---

I tried to increase the SSH parameter
MaxSessions - it did not help.

**Comment by antonmedv** [comment]
Fixed in #1904
