### ISSUE TITLE
Reload php on several stages on one server

### ISSUE THREAD

**Issue by tebaly** [deployphp/deployer#1869]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | v6.4.3
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
According to the documentation, it is possible to execute a deployment of several application variants (stages) on one server.
https://deployer.org/docs/hosts.html#one-host-for-a-few-stages

```php
host('production')
    ->hostname('domain.com')
    ->set('deploy_path', '~/domain.com')
    ->roles('app', 'test');
    
host('beta')
    ->hostname('domain.com')
    ->set('deploy_path', '~/beta.domain.com')
    ->roles('app', 'dev');
```
Then task 'reload:php' will be executed twice.
* there is no way to use `onHost` - if you specify onHost('beta') task task skipped to 'production'
* there is no way to use `onStage` - if you specify onStage('dev') task task skipped on stage  'test'
* there is no way to use `onRoles` -  task 'reload:php' will be executed twice.

```php

task('reload:php', function() {
    run('service php7.2-fpm reload');
}); 
after('deploy', 'reload:php');
```

This may cause an error (I have more than two stages).

> php7.2-fpm.service: Start request repeated too quickly.
> php7.2-fpm.service: Failed with result 'start-limit-hit'.
> Failed to start The PHP 7.2 FastCGI Process Manager.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
