### ISSUE TITLE
Add composer.lock to git

### ISSUE THREAD

**Issue by tomzx** [deployphp/deployer#187]
Reference: #186.

**Comment by elfet** [comment]
Libs may not contains `composer.lock`, but i'm thinking `composer.lock` is good solution for Deployer (better for building phar).

**Comment by tomzx** [comment]
I don't think `Deployer` falls into the library category. I think the tool category is more appropriate. One does not really make use of the `deployer` sources other than through the `dep` _binary_.

I wouldn't pretend to know composer in depth, but I believe that if you `require` a library that has a `composer.lock`, it will not be considered during the dependency resolution step. Thus it shouldn't pose a problem to have one under version control.

**Comment by elfet** [comment]
>I wouldn't pretend to know composer in depth, but I believe that if you require a library that has a composer.lock, it will not be considered during the dependency resolution step. Thus it shouldn't pose a problem to have one under version control.

`composer.lock` considered during only when `install` appears.

**Comment by gordalina** [comment]
From [composer's documentation](https://getcomposer.org/doc/02-libraries.md#lock-file):

# Lock file

For your library you may commit the `composer.lock` file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

If you do not want to commit the lock file and you are using git, add it to the `.gitignore`.

**Comment by elfet** [comment]
Now with composer.lock :cyclone:
