### ISSUE TITLE
Issues trying to use PHP Deployer on windows with Cmder to a local XAMPP server

### ISSUE THREAD

**Issue by freestyledork** [deployphp/deployer#1870]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6+
| Local Machine OS  | Windows 10
| Remote Machine OS | Windows 10

### Description 
Using Windows 10 Cmder to try and deploy to a local file the php script doesnt use the cmder bash terminal. I believe this comes down to php using windows cmd instead of a emulator to run the scripts. Not sure if there is any solution. 

### Steps to reproduce
run a task to echo $0 
the result is $0 
expected result using cmder:
$ echo $0 
/usr/bin/bash

### Content of `deploy.php`
```php
task('test', function () {
    // Check if shell is POSIX-compliant
    $result = runLocally("echo $0");
    echo $result;
//    if (!str_contains($result, 'bash') && !str_contains($result, 'sh')) {
//        throw new \RuntimeException(
//            'Shell on your server is not POSIX-compliant. Please change to sh, bash or similar.'
//        );
//    }

});
```

### Output log
λ dep test -vvv
➤ Executing task test
[localhost] > echo $0
[localhost] < $0
$0• done on [local]
✔ Ok [353ms]

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
