### ISSUE TITLE
Your configuration files are not serializable.

### ISSUE THREAD

**Issue by pmathulan** [deployphp/deployer#1871]
When I run `dep deploy ` on my terminal and I got a General error

In Client.php line 99:

The command "/usr/bin/php /var/www/dev/dev/releases/1/artisan config:cache" failed.

Exit Code: 1 (General error)

Host Name: ****.****.com

================
Configuration cache cleared!

In ConfigCacheCommand.php line 71:

Your configuration files are not serializable.                                     
In config.php line 123:

Call to undefined method Closure::__set_state()

**Comment by xuanquynh** [comment]
This exception comes from Laravel framework, not from deployer. See [this](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Foundation/Console/ConfigCacheCommand.php#L71) for more details.

You should check your configuration file.

**Comment by pmathulan** [comment]
Ok, Thank you

**Comment by cafferata** [comment]
@pmathulan can you close this issue? :-)

**Comment by pmathulan** [comment]
Yes sure :)
