### ISSUE TITLE
Allow ~/.ssh/config at Windows

### ISSUE THREAD

**Issue by rentalhost** [deployphp/deployer#1872]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | master
| Local Machine OS  | Windows 10
| Remote Machine OS | N/A

### Description 
Windows cannot handle path to `~` by default. But to make `deploy.php` environment-aware, maybe it could be implemented to emulate unix. It should points to current user (aka `%USERPROFILE%`).

### Content of `deploy.php`
```php
host('...')
    ->configFile('~/.ssh/config');
```

**Comment by ricardovigatti** [comment]
I don't think Deployer is Windows compatible.

**Comment by rentalhost** [comment]
Yeah, seems that it is not totally compatible. But I think that we can work to make it compatible due to Win 10 ssh support. I will close it for now to make this issue as passive, but could you tell me if I can run it on Windows using cygwin or something like else?

**Comment by ricardovigatti** [comment]
I have tried to run on Windows using cygwin with no success. For now, I sticky with Linux.

**Comment by rentalhost** [comment]
Oh, it is bad! :(
