### ISSUE TITLE
Register in https://github.com/sponsors

### ISSUE THREAD

**Issue by andrey-helldar** [deployphp/deployer#1877]
https://github.com/sponsors

![2019-07-01_15-36-36](https://user-images.githubusercontent.com/10347617/60437020-0cd4d880-9c16-11e9-8282-0479bfc0b3a9.png)

**Comment by antonmedv** [comment]
Already)

**Comment by andrey-helldar** [comment]
Okay. Just saw a message that these users do not have sponsorship rights.
Probably just need to wait.
