### ISSUE TITLE
Need help with laravel config

### ISSUE THREAD

**Issue by iamoskvin** [deployphp/deployer#1884]
I have a project structure like at the attached screenshot (root test directory is the app). Laravel (actually lumen) app is located in subdirectory "lumen" and not in the root. So, with the standard laravel receipt I have path problems with vendors and shared tasks. 
What is the right way to configure deployer in that case?

![lumen](https://user-images.githubusercontent.com/44796732/61170742-953c6d00-a576-11e9-9c0d-6e399c7d1740.png)

**Comment by xuanquynh** [comment]
With this customized directory structure, I think you have to specify your own paths and tasks. For example

```php
namespace Deployer;

set('shared_dirs', [
   'lumen/storage',
]);

set('shared_files', [
    'lumen/.env',
]);

desc('Installing vendors');
task('deploy:vendors', function () {
    run('cd {{release_path}}/test/lumen && {{bin/composer}} {{composer_options}}');
});
```

**Comment by iamoskvin** [comment]
Thank you so much.
