### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '<' when run as phar

### ISSUE THREAD

**Issue by solo-framework** [deployphp/deployer#1885]
Ubuntu 16.04 x86_64 GNU/Linux
PHP 7.2 (7.0)
Deployer 6.4.5

I'm geting error when trying run 
`php7.2 ./deployer.phar --file=1.php test:first`

1.php is
```php
<?php

namespace Deployer;
require_once "recipe/config/hosts.php";

inventory("hosts.yaml");
localhost();

task('test:first', function () {

	$result = run('ls -l');
	write($result);

})->onHosts(["queue"]);
```

Error message:
```
PHP Warning:  include(phar:///*****/deploy/deployer.phar/vendor/composer/../symfony/polyfill-mbstring/Mbstring.php): failed to open stream: phar error: internal corruption of phar "/*****/deploy/deployer.phar" (crc32 mismatch on file "vendor/symfony/polyfill-mbstring/Mbstring.php") in phar:///*****/deploy/deployer.phar/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening 'phar:///*****/deploy/deployer.phar/vendor/composer/../symfony/polyfill-mbstring/Mbstring.php' for inclusion (include_path='phar:///*****/deploy/deployer.phar/bin/../:.:/usr/share/php') in phar:///*****/deploy/deployer.phar/vendor/composer/ClassLoader.php on line 444

PHP Parse error:  syntax error, unexpected '<', expecting end of file in phar:///*****/deploy/deployer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 116
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
```

**Comment by webtekindo** [comment]
@solo-framework I have the same issue with the Ubuntu bash of Windows 10. Do you have a solution?

**Comment by mrDueDate** [comment]
Exact same problem on Ubuntu 19.10, PHP 7.3.11-0ubuntu0.19.10.1 (cli), deployer 6.6.
When running even ./deployer.phar debug:task I get:
 `PHP Warning:  include(phar:///usr/local/bin/dep/vendor/composer/../symfony/polyfill-mbstring/Mbstring.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/dep" (crc32 mismatch on file "vendor/symfony/polyfill-mbstring/Mbstring.php") in phar:///usr/local/bin/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening 'phar:///usr/local/bin/dep/vendor/composer/../symfony/polyfill-mbstring/Mbstring.php' for inclusion (include_path='phar:///usr/local/bin/dep/bin/../:.:/usr/share/php') in phar:///usr/local/bin/dep/vendor/composer/ClassLoader.php on line 444

PHP Parse error:  syntax error, unexpected '<', expecting end of file in phar:///usr/local/bin/dep/vendor/symfony/polyfill-mbstring/Mbstring.php on line 116
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
`

**Comment by mrDueDate** [comment]
OK. Installing current mbstring package for my php version. Basically:
```sudo apt install php7.3-mbstring ``` solved the problem.
