### ISSUE TITLE
Set sshOptions inside a task

### ISSUE THREAD

**Issue by jonnitto** [deployphp/deployer#1891]
I need to create a localhost port forwarding (`ssh -L 2222:127.0.0.1:22`) if I want to connect to the server via FTP or to connect to the database. This is because of a need for a ProxyJump. I would like to create a task to make it easier to create this connection. It is possible to add a SSH Option inside a specific task or how can I achieve this?

**Comment by antonmedv** [comment]
Task is a simple function. Run call will execute command on remote machine. You can pass options via run argument.

**Comment by jonnitto** [comment]
Sorry, I'm relatively new to PHP and deployer. Can you provide an example with the parameters above? I didn't get it running.

**Comment by antonmedv** [comment]
`run('...', [OPTIONS HERE]);`

**Comment by jonnitto** [comment]
The thing with `run`de is, that the connection is closed after it was finished. I don't want to run any task on the host, I want to create just the connection. Something like this:

```
desc('Create a tunnel connection for access databases and SFTP via localhost');
task('tunnel', function () {
    // Create ssh tunnel with '-L 2222:127.0.0.1:22' parameter
    ask(' Hit enter close the connection ');
    // Close tunnel
});
```

In my `sshOptions` I've a `ProxyJump` enabled and set up. The default connection works fine. But I've no clue if my task is possible

**Comment by antonmedv** [comment]
Try this:
```php
desc('Create a tunnel connection for access databases and SFTP via localhost');
task('tunnel', function () {
    run('ssh -L 2222:127.0.0.1:22 domain.com');
});
```

**Comment by jonnitto** [comment]
Then I got

**Comment by jonnitto** [comment]
Then I got 
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
  Host key verification failed.
```

if I run it with `run('ssh -L 2222:127.0.0.1:22 {{user}}@{{hostname}}', ['timeout' => null, 'tty' => true]);` it also don't create the port forwarding.

With `runLocally('ssh -L 2222:127.0.0.1:22 -J jumping@ssh-jumphost.karlsruhe.punkt.de {{user}}@{{hostname}}', ['timeout' => null, 'tty' => true]);` it would work, but I want to use the `sshOptions` dynamically

**Comment by jonnitto** [comment]
Do you have an idea how I can solve this?

**Comment by antonmedv** [comment]
No, sorry. Don't have time now for investigating.

**Comment by antonmedv** [comment]
This is possible via `currentHost()->setSshOptions()`. Fixed in master. Please verify.
