### ISSUE TITLE
Use tag/branch name as 'release_name'

### ISSUE THREAD

**Issue by bmatsupa** [deployphp/deployer#1896]
Hello! 
How to use tag/branch name which I specify during deployment (for example deployer.phar -vv deploy production --tag="0.0.1_testtag") as "release_name" in releases folder instead of numbers? 
I know about "set('release_name', function () {" but can't implament this with tag/branch name.
Thank you in advance!

**Comment by antonmedv** [comment]
set('release_name', function () { get branch here; see other examples in recipes; });
