### ISSUE TITLE
Option to force tag-only-deployment on production

### ISSUE THREAD

**Issue by ScreamingDev** [deployphp/deployer#1902]
Right now deployer can deploy anything to any target.
This would also mean that any revision can be deployed to production which might cause some trouble.
We want to suppress this and assert that only tags are deployed to production.

* Please add an option or show a way how to achieve this.
* Other server (like dev, test, stage, rc) shall work as before.
* Adding custom rules per server would be a thing.

**Comment by antonmedv** [comment]
Try something like this:
```php
task('check:tag', function () {
     $tag = input()->getOption('tag');
     if (empty($tag)) {
            throw new Exeption("Only tags are allowed");
     }
})->onRoles('proguction');

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
