### ISSUE TITLE
Laravel deploy process and database config, issue with other recipes

### ISSUE THREAD

**Issue by robolmos** [deployphp/deployer#1908]
In the "How to deploy Laravel" docs it doesn't state steps on preparing and configuring the database credentials.

What's the best practice for doing that with Laravel and other projects? I believe Magento 2 requires an "install" process on initial deploy.

For Magento, by default it looks like Deployer recipe creates the app/etc/env.php file, but it's empty. However, by being present it causes commands like "install" to fail due to "Invalid configuration file" error message.

IIRC, Capifony had a "setup" stage, where it would populate the structure, and then require setup/install of the application, which would include the database configuration.

It doesn't seem that Deployer has such a stage. It seems that such as a stage should be added for initial deployments.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
