### ISSUE TITLE
Configuration parameter `stage` does not exist

### ISSUE THREAD

**Issue by kinoute** [deployphp/deployer#1909]
Hello,

After upgrading from 6.4.3 to 6.5.0, I'm getting the error ``Configuration parameter `stage` does not exist.`` when deploying, where `config:current` is called.

When I run `dep config:current`, I get the same error. It seems related to this commit: https://github.com/deployphp/deployer/commit/6180366acff3ca5b2ec511a84e671321c02e7af1

I have `default_stage` set to production. If I add to my host configuration, the stage attribute like this:

```
host('production')
    ->stage('production')
    ->hostname('1.2.3.4')
    ->port('80')
```

The deployment goes through, but the `config:current` doesn't return anything:

![Capture d’écran 2019-08-18 à 10 48 57](https://user-images.githubusercontent.com/623763/63263348-a15bce80-c288-11e9-9640-0ee222d5b01e.png)

Am I missing something?

Regards

**Comment by antonmedv** [comment]
Yes, you are correct. This is because `get('stage')`. This is a bug. Can you send fix PR?

**Comment by david884** [comment]
Anton Medvedev <notifications@github.com> 於 2019年8月19日 週一 21:22 寫道：

**Comment by dnaber-de** [comment]
Hello there. I'm facing the same issue with `dep config:hosts`. PR is available. However I wonder why the task `config:hosts` is defined as one time task and not a local task? What is the reason for this @antonmedv 
```
task('config:hosts', function () {
   
})->once();
```
As it just prints configuration it should be only executed on the local machine, shouldn't it?

**Comment by ihommani** [comment]
Hi there, 
Why this issue is closed? 
I experience the same issue. To reproduce, create a task to display 'stage':
```
desc('Display stage');
task('deploy:stage', function () {
    //run('cd {{deploy_path}} & test -f scripts && rm scripts & mv current scripts');
    $stage = get('stage');
    writeln($stage);
});
```
If I don't set a default stage I get the same issue: 
`Configuration parameter `stage` does not exist.`

If I set a default stage, this one is always displayed, no matter the stage I put on CLI. 
Quickwin is to set the defaut_stage with a callback to get a custom option called stage.

Note: I get the very same issue with the fix from @dnaber-de

**Comment by dnaber-de** [comment]
My fix affected only the `config:*` tasks of the default recipes. Try to aks for `has('stage')` before you accessing the value via `get('stage')`.

**Comment by ihommani** [comment]
My bad. I misunderstood the fix and deploy behavior. All is fine. @dnaber-de
