### ISSUE TITLE
Deployer 2 missing dependencies

### ISSUE THREAD

**Issue by JeroenReumkens** [deployphp/deployer#191]
Hi,

At the moment we are still using Deployer 2, since we haven't had the time to upgrade to version 3. Unfortunately I've noticed today that elfet/php-ssh has been abandoned which results in a missing dependencies when updating composer.. Currently the only fix I can think of, is creating our own checkout and changing the dependency to herzult. Do you have a better idea for this?

Thanks in advance,
Jeroen.

**Comment by elfet** [comment]
Upgrade to latest Deployer 2: https://github.com/deployphp/deployer/releases/tag/v2.0.4
