### ISSUE TITLE
Mix Rsync and Git Deploys

### ISSUE THREAD

**Issue by jledfordtbc** [deployphp/deployer#1911]
Is it possible to create a recipe that mixes rsync and git deployments?  Example, in 1 project I have multiple servers, some I want to rsync to and some I want to use a git deployment to.  In the task deploy I don't see a way to interchange that, I either add the rsync tasks OR add the update_code tasks, but not both.  Help is appreciated.

**Comment by antonmedv** [comment]
You can copy-paste code from both.

**Comment by jledfordtbc** [comment]
Not sure I follow.  I want to have a stage that is git based and does not rsync, and then I want to have a stage that rsyncs and does not pull from git.  Is that possible with a single deploy task?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
