### ISSUE TITLE
Is this repository being maintained?

### ISSUE THREAD

**Issue by petrenkorf** [deployphp/deployer#1912]
There's a lot of old open issues without resolutions, I would like to help maintaining this project.

**Comment by antonmedv** [comment]
This is awesome. Some kind of. Please take a look the next branch. Also I had roadmap, but it in my head. Maybe we can gave a call and I’ll explain everything what is going on.

**Comment by antonmedv** [comment]
I came back! Checkout new and awesome Deployer (in the master branch now).
