### ISSUE TITLE
Accessing deployer's OutputInterface or ConsoleOutput objects

### ISSUE THREAD

**Issue by mf** [deployphp/deployer#1919]
Is there a clean way of getting the OutputInterface from deployer? Output only has the OutputWatcher, which unfortunately does not expose full interface and it also does not return the private $output.
We wanted to use the section() methods of ConsoleOutput in order to have multiple progressBars for long running tasks.

Thank you

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.
