### ISSUE TITLE
Non-public tasks

### ISSUE THREAD

**Issue by mabrahamde** [deployphp/deployer#192]
During the deployment i am using multiple tasks. All tasks are called internal during the deployment, however i do not want to expose all tasks to CLI. It would be great if you can tag tasks as non-public. Non-public tasks should not be callable via CLI directly.

**Comment by elfet** [comment]
Ok, will add to v3.

**Comment by elfet** [comment]
Done. Now you can use it like `task(...)->setPrivate();` :beer:

**Comment by mabrahamde** [comment]
:thumbsup:
