### ISSUE TITLE
Rsync options in upload are not being interpreted

### ISSUE THREAD

**Issue by dareenzo** [deployphp/deployer#1922]
Hi,

I have a task that runs upload,the task keeps failing because rsync tries to preserve owners and groups by default. I tried adding more options using the third parameter given in upload but then the command that is executed does not include any of the options I specified as seen below.

```php
desc('Uploads compiled files built locally to the server');
task('upload-files', function () {
    // rsync("pub/static", "{{release_path}}/pub/static");
    upload(
        'pub/static/',
        '{{release_path}}/pub/static/',
        [
            "no-g",
            "no-a",
            "recursive",
            "links",
            "super", // receiver attempts super-user activities
            "delete", // delete extraneous files from destination dirs
            "force",
        ]
    );
});
```

```
bazara on  master [$✘!?] via 🐘 v7.2.19 took 7s
➜ dep upload-files --hosts=staging_01 -v
➤ Executing task upload-files

In Process.php line 239:

  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "rsync -azP -e 'ssh -A' 'pub/static/' '63.34.219.165:/var/www/bazara/releases/20190920125325/pub/static/'" failed.
```

**Comment by mf** [comment]
I think the rsync options need to be nested under "options" key, look at rsync utility function in 
deployer/Rsync.php @ line 42:
https://github.com/deployphp/deployer/blob/0b2179632c8857db160e5fe8a3efb0a3da647da6/src/Utility/Rsync.php#L42

$rsync = "rsync -azP " . implode(' ', $config['options']) . " $escapedSource $escapedDestination";

**Comment by dareenzo** [comment]
Thanks!

**Comment by tmsss** [comment]
I'm also struggling with this one, I've tried to use the following syntax, but the options aren't applied to rsync. Can you help me on the correct syntax? Thanks!

`upload($tmpFilename, '{{release_path}}/sites/{{site}}/local.settings.php', ['options'=> ['inplace']]);`

**Comment by mbrodala** [comment]
@tmsss You need to use `['options' => ['--inplace']]` instead, thus a raw CLI option.
