### ISSUE TITLE
Pass own CLI args

### ISSUE THREAD

**Issue by c-gross** [deployphp/deployer#1925]
I was not able to find anything about passing own CLI arguments. $argv and getopt() are not available inside the deployer script.

I have the same webapp with different databases. By default the deployer is deploying all which is working. But I would like to have the option to add some parameter to the CLI command to deploy only some specfic and not all.

like: dep deploy --shops="de,at"

Deploy loop look like: (changed ip and user)
```
foreach($shops as $shopCode => $shopDir) {
    host('1.1.1.1/'.$shopCode)
        ->user('admin')
        ->port(22)
        ->configFile('~/.ssh/config')
        ->identityFile('~/.ssh/id_rsa')
        ->forwardAgent(true)
        ->multiplexing(true)
        ->addSshOption('UserKnownHostsFile', '/dev/null')
        ->addSshOption('StrictHostKeyChecking', 'no')
        ->set('http_user', 'www-data')
        ->set('deploy_path', '/var/www/'.$shopDir);
}
```

**Comment by antonmedv** [comment]
https://deployer.org/docs/tasks.html#using-input-options

**Comment by c-gross** [comment]
I tested this but I think that can't work in my case.

Hosts have to be defined outside of any task.
input()->getOption() is only inside tasks available and I haven't found a way to skip a host based on a task check. ([Deployer\Exception\Exception] Context was required, but there's nothing there.)

**Comment by antonmedv** [comment]
Yes, can use roles for this job.
