### ISSUE TITLE
Feature/question - parallel execution of processes in a task

### ISSUE THREAD

**Issue by micdobro** [deployphp/deployer#1933]
I would like to ask whether this is something that could possibly open a bag of problems. In case there's nothing in the way - I am willing to help developing it.

Part of my deployment flow is a task where I execute a command for every tenant that lives on a given machine. In the current situation I am bound to sequential execution. I am interested in executing these in parallel - but not w/o any constraints. Some parts of this project: https://github.com/asyncphp/doorman actually do what I want to achieve, i.e. "execute at most 3 processes at a time". This way for `N(tenants)=30` I can utilize multiple CPUs and actually have the whole process run almost 3 times faster. 

I have briefly looked at the code - but before I dig deeper - are there any issues/showstoppers on the way? I am mostly interested in the simplest constraint that just limits the number of running processes. 

Example before:
```php
task('deploy:tenantExecutor', function () {
    cd("{{release_path}}"); 
    $tenants = getTenantsArray(); 

    foreach($tenants as $tenant) {
        $out = run("command {$tenant}"); 
    }        

})->desc("Running Tenant Jobs"); 
```

After/proposed idea:
```php
task('deploy:tenantExecutor', function () {
    cd("{{release_path}}"); 
    $tenants = getTenantsArray(); 
    $tenantCmds = [];

    foreach($tenants as $tenant) {
        $tenantCmds = [
          'command' => "command {$tenant}",
          'jobId' => $tenant // could be anything else that can identify individual runs
        ];
    }        
   
   $outlog = runInParallel($tenantCmds, ['maxProcesses' => 3, 'timeout' => '600']);
   // outlog will contain the output indexed by jobID
   // $outlog[$jobId] = $resultData;  

})->desc("Running Tenant Jobs"); 
```
Of course this is just a simple example - arrays can be enhanced with exec time and other stats - and additional constraints can be taken into consideration. Since that would be just "a collection of tasks run in parallel" - they should obey the same rules for parallel execution on multiple hosts.

**Comment by micdobro** [comment]
Another idea: 

```php
$outlog = runInParallel($tenantCmds, ['maxProcesses' => 3, 'timeout' => '600', 'outputHandler' => function ($jobId, $output) { ...}]); 
```
...here one could process the output "as it comes". Those callbacks will be then outputed "in series" to the screen so that we don't get a mix of output from processes running in parallel.

**Comment by antonmedv** [comment]
Well, actually you can already achieve this with you are going to treat tasks as a small, independent block. Each task can be easily be paralleled. So try to separate what you are actually want to run in parallel into a simple task, and compose it with other task using roles/after/before/grouping.

**Comment by micdobro** [comment]
Thanks for a quick response. Does that mean: 

```php
before('deploy:symlink', 'deploy:parallelPart1'); 
before('deploy:symlink', 'deploy:parallelPart2');
before('deploy:symlink', 'deploy:parallelPart3');
```
That the three **parallelPart[1-3]** parts will be executed actually in parallel? I could not find anything around the documentation mentioning it - although I can see why this could make sense (multiple bindings to the same stage and hook result in parallel execution).

**Comment by antonmedv** [comment]
https://deployer.org/docs/tasks.html#parallel-task-execution

**Comment by micdobro** [comment]
Thanks. If I understand it correctly - that is pure horizontal parallelism, i.e. tasks are executed concurrently on **multiple machines** and deployer is making sure that they are all synchronized - by host and task. 

What I want to achieve is the ability to run concurrent processes on each machine within boundaries of a single task. 

This means that Task1 spawns processes p1, p2 & p3 that each run concurrently within the frame setup by Task1. And Task1 is first marked as "finished" once all concurrent processes within the queue are executed (or aborted). So in theory this should not break any other synchronization when deploying in parallel on multiple hosts. The key is to spawn extra processes that run concurrently inside a task - and set the `parallelism` count for that execution. 

![Selection_999(249)](https://user-images.githubusercontent.com/13837792/66462131-b7ad2c00-ea7a-11e9-92d8-6967d6786182.png)

**Comment by antonmedv** [comment]
Yes, you are right.

**Comment by micdobro** [comment]
After reviewing the code and checking all internals I decided to go with `parallel` (GNU parallel) and write my own wrapper around everything. This seems to be the best option taking into account remote execution - especially for situations where ssh multiplexing is not being used. 

Such solution requires installation of GNU parallel on all machines - but on the other hand it removes a lot of complexity. It has also a nice option `-k` which returns grouped output from all commands - perfect for parsing. I will be experimenting more and checking whether this can _just work_.

In case of positive results - should I consider implementing it in deployer (wrapper for easy running/output gathering) or keep it in-house? (as the feature has external deps)

**Comment by antonmedv** [comment]
It will be cool if you can share with the community your experience.

**Comment by micdobro** [comment]
No problem. I might have some additional architectural questions - I will post them here in case I'm in doubt.

**Comment by antonmedv** [comment]
Closing as inactive.
