### ISSUE TITLE
Upload function of local symlink file uploads the symlink and not the file it points to

### ISSUE THREAD

**Issue by neamtua** [deployphp/deployer#1948]
I'm having an issue using upload function to upload a .env file for Laravel.
I have it symlinked because I sync my files on all my workstations but upload function actually uploads the symlink, not the file it's pointing to.

Is there any way to make it follow that symlink?

**Comment by antonmedv** [comment]
It uses rsync

**Comment by neamtua** [comment]
> It uses rsync

Could you elaborate on this a bit? I know there's a -L flag on rsync but can i pass that through the upload function?

**Comment by antonmedv** [comment]
Hmmm,  maybe we should just add this flag to function?

**Comment by neamtua** [comment]
I see no reason why not. I'm guessing right now there isn't a way to pass that flag to rsync?

**Comment by antonmedv** [comment]
I think there is not. But I may be wrong.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
