### ISSUE TITLE
WordPress Bedrock recipe

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#195]
Hi!
I'm currently using Deployer for deploying WordPress Bedrock instances.
The common-recipe fails on some settings but it is close :-)
Would it be ok to add a bedrock.php -recipe to the repo dev-master for merge?

**Comment by elfet** [comment]
Yes! Great! But it will be better to add `wordpress` recipe. :newspaper:

**Comment by EkAndreas** [comment]
I'm not sure because Roots Bedrock is a very specific environment.

**Comment by EkAndreas** [comment]
It's all ok for me but I'm sure it will create a lot of problems for other WordPress-users :-)

**Comment by elfet** [comment]
Well, `bedrock` is ok :)

**Comment by EkAndreas** [comment]
No need for a Bedrock recipe! The newly updated common.php does exactly all things right.
Thanks!
I will write a blog post to all this for us Bedrock developers :-)

**Comment by VivekShingala** [comment]
Hi @ekandreas 

You already wrote the blog post for bedrock and deployer setup?
