### ISSUE TITLE
after 'become' change user for single task

### ISSUE THREAD

**Issue by derkaan** [deployphp/deployer#1950]
Hi, 

I'm trying to change the executing user for a single task, but couldn't find anything related yet.
The user used to ssh to the server has sudo permissions and afterwards the deployment continues as www-data.

My host config
```php
host('example.com')
    ->stage('stage')
    ->user('my-ssh-user-with-sudo')
    ->become('www-data')
...
```

This works well for all needed tasks, except reloading the webserver and fpm.
For these tasks I would need to become back to my 'my-ssh-user-with-sudo'-user.

This task fails, as the www-data user from the above config has now sudo permission (and should not have any, due to security aspects)

```php
desc('Reload nginx and php-fpm');
task('custom:reload_server', function () {
    run('sudo service nginx reload ; sudo service php7.3-fpm reload');
});
```

Is there a way to un-become the prior user or to set a specific user for a task or run?

If possible I would like to avoid prefixing all my run commands with something like this

```php
 run('sudo -u www-data {{bin/php}} do-something ');
```

**Comment by antonmedv** [comment]
You last example is actually okay. Really straightforward and verbose about what you want to do.

**Comment by derkaan** [comment]
well, this would mean that I have to change all run tasks to run as the user I used to in my host configuration (->become('www-data')).

Ideally I would like to become my user that I used to login just for this task.
Something like
```php
run('sudo -u www-data {{bin/php}} do-something ')->as('my-ssh-user-with-sudo');
```
as this is not available yet(?), it would alternatively help if I can reset the become-user, execute the necessary command and become back the prior user.
e.g.

```php
desc('Reload nginx and php-fpm');
task('dcl:reload', function () {
    // currentHost shall represent the host that is currently used for this deployment
    // switching the user temporarely would help to execute command that require 
    // sudo priviledges  
    currentHost->become('my-ssh-user-with-sudo');

    // this run task shall then run as 'my-ssh-user-with-sudo'
    run('sudo service nginx reload ; sudo service php7.3-fpm reload');

    // switching back to the originally set 'become'-user to continue with the deployment
    // this user should not get any sudo priviledges 
    currentHost->become('www-data');
});

```

Can I somehow change the host config/setting on the run?
