### ISSUE TITLE
Deploy to server via Gitlab CI

### ISSUE THREAD

**Issue by GlennM** [deployphp/deployer#1951]
Hi,

I'm trying to implement deployer for the deployment stage of GitLab CI.
Unfortunately, I've been unable to get it fully working.

## Setup
- Push to GitLab repo
- Run GitLab CI
- In the deploy stage, deploy to our server using SSH

## Issue
I've been seeing various error messages (e.g. TTY error, hopefully solved by disabling `git_tty` option).

The error I am unable to solve is:
```
In Client.php line 103:

The command "cd [PATH] && (git clone   --recursive  [REPO CLONE URL (SSH)] [PATH]/releases/1 2>&1)" failed.

Exit Code: 128 (Invalid exit argument)

Host Name: [HOSTNAME]
================
Cloning into '[PATH]/releases/1'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```
(I've replaced some specific info with general info, see the `[]`).

I did several attempts, e.g.
- [this comment](https://github.com/deployphp/deployer/issues/1522#issuecomment-381517913)
- I had a look at [this tutorial](https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/#the-deploy-stage). It's about Laravel-docker which uses the Deployer package. I can't use Laravel-docker as I am trying to deploy a common application.
- I've tried adding private and public keys, but probably I am not doing it 100% correct. (public key on own server, private key as project variable in GitLab).

## Question
Is there someone who could point me to the right direction to get my setup with GitLab and push to server working?

**Comment by antonmedv** [comment]
Just use deploy keys. This is most easy to go solution and should work 100% in implemented correctly. Don't rely on agent forwarding, just allow your server to pull changes from git.

**Comment by GlennM** [comment]
Thanks for your quick reply @antonmedv !
Unfortunately, I think there's still some confusion about the deployment keys. I've tried several combinations, but have been unable to get it working.

To be specific:
- I've tried to follow the [GitLab instructions](https://docs.gitlab.com/ee/ci/ssh_keys/#how-it-works).
- When generating the [SSH key pair](https://docs.gitlab.com/ee/ssh/README.html#generating-a-new-ssh-key-pair), I am not quite sure what email address to use. Or doesn't that matter?
- Should I run `ssh-keygen` on my local machine or on the server I'm trying to push the code to?
- I added the private key as a private variable to GitLab project
- I added the public key as a deployment key to GitLab project
- I added the `before_script` part from the [GitLab docs](https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor) to my `.gitlab-ci.yml`

**Comment by antonmedv** [comment]
>I've tried to follow the GitLab instructions.

👍🏻

> When generating the SSH key pair, I am not quite sure what email address to use. Or doesn't that matter?

Any email. Keys are just files.

> Should I run ssh-keygen on my local machine or on the server I'm trying to push the code to?

Doesn't matter. Make sure git using them on machine which trying to access git server.

> Will it cause any issues if I have a different name for the keypair (e.g. id_rsa_gitlab) or do I need to adjust something in that case?

No. As long as your git is using them.

> I added the private key as a private variable to GitLab project

Okay. But why?

> I added the public key as a deployment key to GitLab project

Okay. But why?

> I added the before_script part from the GitLab docs to my .gitlab-ci.yml (job-specific, not global before_script).

This is releated only for gitlab, can help here.

**Comment by GlennM** [comment]
Thanks, but I still don't get it working.
- I created the key pair
- I added the public key as a Deploy key to GitLab

**Result**
- I'm able to do a git clone on my server from GitLab repo now (via SSH).
- I am able to connect from Deployer to my server (e.g. run the `pwd` task mentioned on the [deployer docs](https://deployer.org/docs/getting-started.html).

However, when I'm trying to deploy, I get an error, which I think has to do with permissions for GitLab, as the error occurs specifically when trying to perform `deploy:update_code'`.
Error:
```
Cloning into '[PATH]/releases/1'...                             
  Host key verification failed.                                                
  fatal: Could not read from remote repository.                                
                                                                               
  Please make sure you have the correct access rights                          
  and the repository exists.
```

**Comment by antonmedv** [comment]
Make sure what user which connect from gitlab to your server uses same keys.

**Comment by GlennM** [comment]
Thanks for your help @antonmedv, I got it working now.
Probably it was a combination of multiple factors, but the root cause seems to be that `dep init` put a wrong repository url in the deploy.php file (config related, not a bug in deployer package).
