### ISSUE TITLE
Guides on how to trigger tasks from web instead of command line

### ISSUE THREAD

**Issue by ngbsoft** [deployphp/deployer#1957]
I am new to this great tool and I am still learning. My guess is that is possible to start deployment tasks from a web UI ( nginx / apache + php-fpm), but not very straightforward. Hope someone can shed some light on this. Thanks

**Comment by 949mac** [comment]
How about `<?php shell_exec('dep deploy'); ?>`?

https://www.php.net/manual/en/function.shell-exec.php

**Comment by ngbsoft** [comment]
> How about `<?php shell_exec('dep deploy'); ?>`?
> 
> https://www.php.net/manual/en/function.shell-exec.php

Yeah, I had it work using that technique. I almost forget to update thread... I will post the detailed how-to later. Let's close the issue for now. Thanks
