### ISSUE TITLE
nginx user permission missing despite of http_user set

### ISSUE THREAD

**Issue by shayan-ys** [deployphp/deployer#1962]
Q | A
-- | --
Issue Type | Bug
Deployer Version | 6.6
Local Machine OS | OSX Mojave
Remote Machine OS | CentOS Linux 7 (Core) 

I'm using deployer to sync WordPress folder (uploads), but when uploads folder is created, it misses the nginx user write permission.
When I run: `getfacl uploads/` , `user:nginx:rwx` is missing:
```shell
$ getfacl uploads/
# file: uploads/
# owner: staging
# group: staging
user::rwx
group::rwx
other::r-x
```
I need to manually give nginx permission using the following command:
`setfacl -R -m u:nginx:rwx {{deploy_path}}/shared/wp-content/`

The deploy.php configs are as below, http_user is already set to nginx.
```php
<?php
namespace Deployer;

require 'vendor/deployer/deployer/recipe/common.php';

set('http_user', 'nginx');

// Shared files/dirs between deploys
set('shared_files', []);
set('shared_dirs', [
    'wp-content/uploads',
]);

// Writable dirs by web server
set('writable_dirs', [
    'wp-content',
    'wp-content/uploads',
]);

set('clear_paths', [
    'dep',
    'deploy.php',
    'puphpet',
    'Vagrantfile',
    'scripts',
    '.gitignore',
    '.htaccess',
    'README.md',
    'license.txt',
    'readme.html'
]);

set('ssh_type', 'native');
set('ssh_multiplexing', true);

// Binaries/Scripts: These can be overriden at server config level if needed
set('bin/php', '/usr/bin/php71');
set('bin/composer', '{{bin/php}} /usr/bin/composer');

// Shared settings across servers
set('fastcgi_path', '/var/run/php70-fpm.sock');
```

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
