### ISSUE TITLE
deployer.org down since the weekend

### ISSUE THREAD

**Issue by andreaswolf** [deployphp/deployer#1964]
Since at least Dec 1st, deployer.org is not reachable anymore. Gone with it are e.g. the PHAR file downloads and documentation.

Is there anything that the community can do to help getting things back online?

**Comment by ilyabrilev** [comment]
Is that the reason why I'm receiving an error:
`/usr/local/bin/dep: line 1: syntax error near unexpected token `newline'
/usr/local/bin/dep: line 1: `<!DOCTYPE html>'`
when trying to deploy?

**Comment by tehplague** [comment]
I suppose, your `/usr/local/bin/dep` contains the Cloudflare error HTML. Maybe @antonmedv should mirror the Deployer release PHARs to GitHub.

In the meantime I did so myself: https://github.com/tehplague/deployer/releases/download/v6.6.0/deployer-6.6.0.phar

**Comment by leecrosdale** [comment]
Still down, does anyone know if there are any updates from @antonmedv anywhere?

**Comment by haswalt** [comment]
Somewhat concerned/curious why I get the same error as @ilyabrilev when deploying. I'd assume with anonymous stats off that no other requests should be made to deployer.org?

Also yes, PHARs should be added as releases here I think. More than happy to help if @antonmedv doesn't have time / needs a hand

**Comment by GeorgeGedox** [comment]
The problem is that everyone here depends on the main website to serve the .phar file to be used in the deployment. Why did the developer force everyone to use their website without a CDN in place blows my mind.

I highly suggest the developer to use either github's release in sync with main website release or a separate packagist build that contains the phar.

**Comment by zuernBernhard** [comment]
![Bildschirmfoto 2019-12-02 um 21 19 22](https://user-images.githubusercontent.com/1442798/69992276-9e3fd200-1549-11ea-9329-d0bdaa171dd9.jpg)

Where are the instructions to build the phar-archive in the same way like the ones which were downloadable ? So perhaps everyone could "package" it locally until the service is back.

**Comment by tinogo** [comment]
In the meantime I've switched all my projects to the official deployer distribution package:
https://packagist.org/packages/deployer/dist

With the distribution package you're just getting the `dep` executable, i.e. without all the dev-dependencies, etc. So it's perfect for deployments. :)

**Comment by andreaswolf** [comment]
Thanks for the pointer @tinogo. To make accessing the files a bit easier, I downloaded them all and created a mirror at https://deployer.a-w.io/.

This should work as a drop-in replacement for the original URLs (the structure is the same as https://deployer.org/releases/, also the checksums are the same as far as I could check (for some 6.3 and 6.4 versions).

**Comment by antonmedv** [comment]
Hello, guys! Sorry for inconvenient, I was on vacation. going to investigate what is going on there.

**Comment by antonmedv** [comment]
The web site is online!

I'm gonna put in separate VPS to prevent in from other websites (it was the case).

**Comment by leecrosdale** [comment]
Thanks @antonmedv! Sorry to take you away from your vacation. Enjoy!
