### ISSUE TITLE
Update Symfony console 5.0

### ISSUE THREAD

**Issue by Wait4Code** [deployphp/deployer#1965]
Hi,

It's not really a bug but is there any plans to upgrade symfony required components to new version ^5.0 ? 
As deployer is a require-dev dependency of my main projects, I can't upgrade them to 5.0 version of symfony because of that. It's a little bit constraining...

I can work on a pull request if you are interested into.

**Comment by cmen** [comment]
Master branch is already compatible with Symfony 5. A new version will be released soon.
See https://github.com/deployphp/deployer/pull/1956.

**Comment by malupixel** [comment]
And where will be updated deployer/phar-update? We need new version to :)

**Comment by kl3sk** [comment]
Yes please update, this package is so useful.

**Comment by antonmedv** [comment]
Can somebody send PR?

**Comment by kl3sk** [comment]
You not just have to push to packagist ? Master is already compatible has I understand.

**Comment by antonmedv** [comment]
What about phar-update lib?

**Comment by kl3sk** [comment]
Does `composer.json` update is enough ?

**Comment by cmen** [comment]
https://github.com/deployphp/phar-update/pull/3

**Comment by kl3sk** [comment]
@antonmedv Do you think you can update the package on packagist ?

**Comment by antonmedv** [comment]
Yes, sure. Will do!

**Comment by kl3sk** [comment]
When do you think master will be available to packagist ? Installation is not yet possible

**Comment by antonmedv** [comment]
Release! Also phar updated and deployer/dist too!

**Comment by kl3sk** [comment]
This is a really good news ! Thanks.
