### ISSUE TITLE
No release backups?

### ISSUE THREAD

**Issue by bigtunacan** [deployphp/deployer#1966]
Just setup a basic deployment and testing it against a dev server.  

I ran `dep deploy` and that worked fine, then ran a couple of tagged deploys like `dep deploy -o branch=v0.01` `dep deploy -o branch=v.0.02`

Everything seemed to be working at that point so I tried testing the rollback functionality `dep rollback`, but I just get the message **"No more releases you can revert to"**

Checked the server and after each deployment the releases folder only has 1 directory.  I have `set('keep_releases', 10);` in my deploy.php file.

**Comment by ngbsoft** [comment]
if you use recipe , you should invoke   'deploy:prepare',    'deploy:release', to create release so that you can rollback later. 

Something like this :
`
task('deploy', [
    'deploy:info',
    'deploy:prepare',
 
    'deploy:release',
    'deploy:update_code',
    'deploy:vendors',
  
    'deploy:shared',
    'deploy:writable',
 
    'deploy:symlink',
 
])->desc('Deploy your app ');`

**Comment by bigtunacan** [comment]
@ngbsoft Yes, that is what I'm doing currently, but it only creates a release directory named "releases/1" every single deploy.

My deploy recipe looks like the below.

    task('deploy', [
        'deploy:info',
        'deploy:prepare',
        'deploy:lock',
        'deploy:release',
        'deploy:update_code',
        'deploy:shared',
        'deploy:writable',
        'deploy:vendors',
        'deploy:clear_paths',
        'deploy:symlink',
        'deploy:unlock',
        'cleanup',
        'success'
    ]);

**Comment by DrizzlyOwl** [comment]
@bigtunacan do you have `set('release_name', 'foo');` anywhere in your deploy.php?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
