### ISSUE TITLE
magento:maintenance:disable might cause frontend errors 

### ISSUE THREAD

**Issue by peterjaap** [deployphp/deployer#1968]
We reviewed the Magento 2 deployment thoroughly and ran into an interesting issue. It appears the `magento:maintenance:disable` task in the [Magento 2 recipe](https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L58) is useless and might in fact in some cases produce an error on the frontend.

This is the task sequence in the default recipe;

- deploy:info,
- deploy:prepare,
- deploy:lock,
- deploy:release,
- deploy:update_code,
- deploy:shared,
- deploy:vendors,
- deploy:writable,
- deploy:clear_paths,
- magento:compile,
- magento:deploy:assets,
- **magento:maintenance:enable,**
- **magento:upgrade:db,**
- **magento:cache:flush,**
- **magento:maintenance:disable**
- deploy:symlink,
- deploy:unlock,
- cleanup,
- success

The interesting ones are in bold.

The maintenance is set on the `current` dir (the code base that is live). The setup:upgrade command is then run on the `release` dir (the new code base that is about to be put live). Then the cache is flushed, followed by a disabling of the maintenance mode of the live version.

At this point in time, the database is upgraded but the previous release is still the live version but it has **no maintenance mode enabled**. If a visitor comes at that exact moment, they might face an error since the code base isn't in sync with the database.

Next, the symlink is swapped and the `release` dir is put live. This is now `current`. This dir had no maintenance mode set in the first place so it'll automatically become available. The question is: why is `magento:maintenance:disable` even in there? It serves no purpose and in fact may cause customer-facing errors.

My proposal would be to remove [this line](https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L79) (and keep the task itself).

**Comment by peterjaap** [comment]
Even if `deploy:symlink` for whatever reason will fail, the site will probably shown an error. If the `magento:maintenance:disable` is removed from this sequence, at least a maintenance page is shown.

**Comment by barryvdh** [comment]
I usually enable/disable the maintenance mode on both current and release folders, so that they are in sync:

```php
desc('Enable maintenance mode');
task('magento:maintenance:enable', function () {
    run("if [ -d $(echo {{deploy_path}}/current) ]; then {{bin/php}} {{deploy_path}}/current/bin/magento maintenance:enable; fi");
    run("if [ -d $(echo {{deploy_path}}/current) ]; then {{bin/php}} {{release_path}}/bin/magento maintenance:enable; fi");

});

desc('Disable maintenance mode');
task('magento:maintenance:disable', function () {
    run("if [ -d $(echo {{deploy_path}}/current) ]; then {{bin/php}} {{deploy_path}}/current/bin/magento maintenance:disable; fi");
    run("if [ -d $(echo {{release_path}}/current) ]; then {{bin/php}} {{release_path}}/bin/magento maintenance:disable; fi");
});
```

**Comment by peterjaap** [comment]
That might be the best way @barryvdh thanks.

Maybe we could incorporate this into the default recipe?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
