### ISSUE TITLE
[BUG] Fatal error for tasks without description (PHP7.4, symfony/console ^5.0)

### ISSUE THREAD

**Issue by sirian** [deployphp/deployer#1969]
![image](https://user-images.githubusercontent.com/897643/70849463-c6a3c680-1e8f-11ea-9b27-b9a0bf2d5695.png)

```php
<?php
namespace Deployer;

task('test', function(){});
```

```json
{
    "require": {
        "symfony/console": "^5.0",
        "deployer/deployer": "^6.7"
    }
}
```

**Comment by sirian** [comment]
@antonmedv

**Comment by antonmedv** [comment]
What PHP version? Works for me.

**Comment by sirian** [comment]
@antonmedv php7.4 i mentioned it in subject :)

**Comment by sirian** [comment]
<img width="682" src="https://user-images.githubusercontent.com/897643/70854077-bf98aa80-1ec7-11ea-886e-c9c863c49806.png">

**Comment by antonmedv** [comment]
I see. This is odd, as I just testes it in 7.4 and for me everything is working.

**Comment by sirian** [comment]
probably you tried at symfony/console 4. Bug happens with symfony/console 5.

Try this

```sh
mkdir /tmp/test && cd/tmp/test
echo "<?php namespace Deployer;task('test', function(){});" > deploy.php
composer require symfony/console ^5.0 deployer/deployer ^6.7
vendor/bin/dep
```

**Comment by antonmedv** [comment]
Okay, will try this

**Comment by sirian** [comment]
@antonmedv And there are plenty more errors due to type hints in symfony/console 5 and some breacking changes. For example
![image](https://user-images.githubusercontent.com/897643/70861362-f14c5880-1f3d-11ea-8f67-f31566bce7d1.png)

![image](https://user-images.githubusercontent.com/897643/70861388-36708a80-1f3e-11ea-988c-7bf0c771e9e2.png)

**Comment by antonmedv** [comment]
Yeah. Looks like PR for symphony 5 was incomplete.

**Comment by sirian** [comment]
`composer require --dev phpstan/phpstan` (or  any other static code
analyzer) will help you analyze code and fix bugs

вс, 15 дек. 2019 г., 13:30 Anton Medvedev <notifications@github.com>:

**Comment by antonmedv** [comment]
Got only one error:
```
vendor/bin/phpstan analyse src
 79/79 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------------
  Line   Initializer/Exception/TemplateNotFoundException.php
 ------ -------------------------------------------------------
  29     Unsafe usage of new static().
         💡 Consider making the class or the constructor final.
 ------ -------------------------------------------------------


 [ERROR] Found 1 error

```

**Comment by antonmedv** [comment]
Done in 86c7b3848f11bcc992906bbb5670c7a73d625356

**Comment by sirian** [comment]
> Got only one error:
> 
> ```
> vendor/bin/phpstan analyse src
>  79/79 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
> 
>  ------ -------------------------------------------------------
>   Line   Initializer/Exception/TemplateNotFoundException.php
>  ------ -------------------------------------------------------
>   29     Unsafe usage of new static().
>          💡 Consider making the class or the constructor final.
>  ------ -------------------------------------------------------
> 
> 
>  [ERROR] Found 1 error
> ```


@antonmedv Consider to check with strict phpstan-strict-rules and witth vimeo/psalm. Currently on master psalm displays 95 errors, phpstan - 89

```
composer require --dev phpstan/phpstan phpstan/phpstan-strict-rules phpstan/extension-installer vimeo/psalm
vendor/bin/phpstan analyse src
vendor/bin/psalm --show-info=false src
```

For example psalm errors:
![image](https://user-images.githubusercontent.com/897643/70864339-f02d2280-1f61-11ea-9341-61cf9d7ee9c2.png)

**Comment by sirian** [comment]
currently (6.7.1) ssh cleanup doesn't work :(
```shell
➤ Executing task cleanup

 [TypeError] Argument 1 passed to Symfony\Component\Process\Process::__construct() 
must be of the type array, string given
called in /tmp/test/vendor/deployer/deployer/src/Ssh/Client.php on line 149
```

**Comment by antonmedv** [comment]
Working on it too)
