### ISSUE TITLE
Deployer SSH Client vs Symfony Console 5.0.1

### ISSUE THREAD

**Issue by ausy-kimkennof** [deployphp/deployer#1972]
There seems to be a problem passing the argument to the Symfony Process class in the current SSH Client.php class on line 149.

It seems the new 5.0.1 version requires an array as first argument, and not a string.

Current solution: downgrade to Symfony/Process 4.4.1

**Comment by kl3sk** [comment]
see https://github.com/deployphp/deployer/pull/1971

**Comment by kl3sk** [comment]
this issue can be closed.
