### ISSUE TITLE
Get host and remote release_path in local task

### ISSUE THREAD

**Issue by fritzmg** [deployphp/deployer#1973]
I want to do a basic task that looks like this:

```php
task('theme:deploy', function() {
    $host = (string) Context::get()->getHost();
    $path = (string) Context::get()->getConfig()->get('release_path');
    run('gulp build');
    run("scp -r files/themes/*/dist $host:$path");
})->local();
```

i.e., theme resources should be locally built and then simply copied to the host (since the built resources aren't part of the Git repository).

However, this does not work, as apparently Deployer creates a custom localhost context for local tasks, thus the information from the host of the deployed stage will be lost within the context of the local task.

Is there no way to run a local task _and_ have information about the target stage?

**Comment by Nimesin-Boxmark** [comment]
runLocally('gulp build');

**Comment by fritzmg** [comment]
Ah, thank you :)
