### ISSUE TITLE
setfacl - Operation not permitted

### ISSUE THREAD

**Issue by lukepass** [deployphp/deployer#1976]
Hello, I am getting an error with Symfony 4 projects when using setfacl. It was working fine with my Symfony 3.4 projects. The error is this:

```
  The command "cd /var/www/html/my_website/releases/48 && (setfacl -L -R -  
  m u:"www-data":rwX -m u:`whoami`:rwX var)" failed.                                
                                                                                    
  Exit Code: 1 (General error)                                                      
                                                                                    
  Host Name: mywebsite.com                                          
                                                                                    
  ================                                                                  
  setfacl: var/log/prod-2019-12-18.log: Operation not permitted                     
```

Every day I have to login into the server and launch this script before launching Deployer:

`sudo chmod -R 777 var/`

Do you know why it's giving this error?

Thanks!

**Comment by antonmedv** [comment]
Add this `sudo chmod -R 777 var/` as task for deploy)) Some owners issues.

**Comment by lukepass** [comment]
The problem is that the deployer user has no right to perform sudo commands. Why was it working with Symfony 3.4? What was changed in the recipe? Thanks

**Comment by sral97** [comment]
I had the same issue with setfacl and could fix it by adding the user that i deploy with to the group of my web-server user.

**Comment by chr1git** [comment]
same issue. In my case it was the rights of the log file. Don't know why deployer needs to touch that. 
command that failed `cd /srv/www/myproject/releases/14 && (setfacl -L -R -m u:"www-data":rwX -m u:`whoami`:rwX var)`
`../shared/var/log/prod.log`
Solution was to put the file to rwxrwxr--, while rw-rw-r-- was not enough.
My deployer user belongs to the www-data group

**Comment by ryancwalsh** [comment]
Maybe that's what https://serverfault.com/a/936550/119666 is suggesting.

**Comment by zarulizham** [comment]
It is better for you to create a new user for the deployment. Do not use 777 in production mode. You may read my write up regarding server configuration with deployer in [here](https://medium.com/@zarulizham/configure-laravel-with-deployer-215fc333b0aa)

**Comment by lukepass** [comment]
Unfortunately the bug is still here but I managed to resolve it by editing the `writable_dirs`. Instead of using `add` I use `set` and I manually configure the folders:

```
<?php

namespace Deployer;

require 'recipe/symfony4.php';

//
// Config
// ======

// project name
set('application', 'mywebsite');

// project repository
set('repository', 'git@bitbucket.org:myhost/mywebsite.git');

// allows you to enter a passphrase for keys or add host to known_hosts
set('git_tty', true);

// shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', ['public/upload/media']);

// writable dirs by web server
set('writable_dirs', ['public/upload/media', 'var/cache', 'var/log', 'var/sessions']); // <=== please note this setting
```

I'm not 100% sure though why this is working.
In my opinion the default recipe **should not** mark as writable the whole `var` folder.

**Comment by romainguerrero** [comment]
FYI : there is a better solution without using sudo by overriding the `writable_dirs` variable. See : https://github.com/deployphp/deployer/issues/2932#issuecomment-1026341540
