### ISSUE TITLE
v6.7.3 breaks php7.0 support

### ISSUE THREAD

**Issue by rickmills** [deployphp/deployer#1981]
As the title says, we came in this morning to builds failing with this error:

> PHP Parse error:  syntax error, unexpected '?' in phar:///usr/local/bin/dep/vendor/symfony/console/Terminal.php on line 127

Digging into it, deployer is now bringing in Symfony 5 which isn't compatible with php 7.0

Appreciate that 7.0 is an older version but such a huge breaking change on a patch release isn't a good sign.

 I can't even get to the docs to see about downgrading to an older release because the deployer site has gone down again (seems to be happening far too often, can't it be moved to github pages?)

**Comment by antonmedv** [comment]
deployed.org is online. And yes I was in rush for Symfony 5 and introduced BC. 

I’m gonna fix it be releasing v7 with Symfony 5 only return compatibility with PHP 7.0. 

Or you can fix version of deployer in composer.json.  What do you think?
