### ISSUE TITLE
regression in shared folder handling

### ISSUE THREAD

**Issue by Gamesh** [deployphp/deployer#1982]
related to #896

```
 ➤ Executing task deploy:shared
> export APPLICATION_ENV='test'; if [ -d /var/www/dimauta/shared/data/cache/ ]; then echo 'true'; fi
< true
> export APPLICATION_ENV='test'; rm -rf /var/www/dimauta/releases/1/data/cache/
> export APPLICATION_ENV='test'; mkdir -p `dirname /var/www/dimauta/releases/1/data/cache/`
> export APPLICATION_ENV='test'; ln -nfs --relative /var/www/dimauta/shared/data/cache/ /var/www/dimauta/releases/1/data/cache/
< ln: target '/var/www/dimauta/releases/1/data/cache/' is not a directory: No such file or directory
```

deploy.php config i have 
```php
add('shared_dirs', ['data/cache/']);
add('writable_dirs', ['data/cache/']);
```

it seems `dirname /var/www/dimauta/releases/1/data/cache/` returns upper dir `/var/www/dimauta/releases/1/data/` and does not create all the way recursively so the `cache` subfolder is missing and symlink fails

Deployer 6.7.3

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).

**Comment by Gamesh** [comment]
was fixed with https://github.com/deployphp/deployer/commit/112601294c3c76273322ecc4e5f995e34f27b6f6
