### ISSUE TITLE
Deploy locked

### ISSUE THREAD

**Issue by maxlipsky** [deployphp/deployer#1986]
I made:
![image](https://user-images.githubusercontent.com/2071263/72982244-b1f01200-3def-11ea-83f4-47def299eea4.png)

Next I made `dep deploy:unlock dev`
I checked on the server — lock file was removed.

I run `dep deploy dev` and got same error again.
I tried to reinstall, I tested on 5.0.0, 5.1.3 and 6.7.2 — got same result.

**Comment by antonmedv** [comment]
Try with `-vvv`

**Comment by maxlipsky** [comment]
Thanks, I found error, this part was called twice: 
host('domain.com', '192.168.11.111')

It's old config, maybe logic was changed in new version of deployer...

**Comment by maxlipsky** [comment]
> Try with `-vvv`

Thanks, I found error, this part was called twice: 

`host('domain.com', '192.168.11.111')`

It's old config, maybe logic was changed in new version of deployer...
