### ISSUE TITLE
Get param from host.yml

### ISSUE THREAD

**Issue by iGavrilo** [deployphp/deployer#1988]
Hey, 

Im trying to take value of Application from host.yml and use it in deploy.php 

How can i do it please ? This is not working ... 

// Nastavenie priečinkou
$applicationName = get('application');

if ($applicationName === 'lol') {
	set('shared_dirs', ['log', 'www/media', 'temp/cache', 'backups']);
	set('writable_dirs', ['www', 'shared', 'backups']);
	set('copy_dirs', ['vendor', 'node_modules', 'backups']);
} else {
	set('shared_dirs', ['log', 'www/media', 'temp/cache']);
	set('writable_dirs', ['www', 'shared']);
	set('copy_dirs', ['vendor', 'node_modules']);
}

Thanks

**Comment by agmckee** [comment]
I seem to have this problem too, though it might be slightly different. I'm able to get a value in the first task but in the next task I can't get the value. I've tried setting it again in the first task (using the set function) but I still can't get it in the next task.

**Comment by agmckee** [comment]
Just tried with the current release (3.8) and it still behaves oddly. 
![image](https://user-images.githubusercontent.com/722096/84422349-d02aa300-ac14-11ea-93b6-1ee338c6625e.png)

In the first task (getconfig) I am able to use the get function to retrieve the stage parameter from the hosts inventory file. In the next task (build) trying to get the stage parameter results in the error message stating the "stage" configuration parameter doesn't exist. I only added the first function (getconfig) to test retrieving this parameter, it doesn't matter if I remove it from the pipeline of the parent function - trying to retrieve 'stage' in the 'build' function just fails. I don't understand why.

**Comment by antonmedv** [comment]
Please, check master branch.

**Comment by agmckee** [comment]
Hi Anton,

Thank you very much for your reply, I appreciate you taking the time to reply.

I've just tried with deployer required as dev-master, I get the following:

![image](https://user-images.githubusercontent.com/722096/84431125-af694a00-ac22-11ea-88c8-6d0912196ec3.png)

Unfortunately it still cannot load the "stage" configuration parameter in the build function. I tested with the 'getconfig' function as well at it does load correctly in that function but still fails in the build function.

Is there any specific information I can provide that might help debug this issue?

**Comment by antonmedv** [comment]
dev-master has breacking changes. No more stage option. Instead concept of selectors/labels added.

**Comment by agmckee** [comment]
Ah, OK thanks for clarifying. I will look into the usage of selectors and labels and see if it meets my use case. Thank you.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
