### ISSUE TITLE
Prevent SSH timeout when data was read 

### ISSUE THREAD

**Issue by marvinhinz** [deployphp/deployer#1993]
**Describe the bug**
When running a first deployment (eg. magento2) composer install can take reaaally long. After 300 seconds deployer terminates the ssh session because of a timeout.

**Expected behavior**
The timeout should be reset, when data was read from the ssh session. Only after 300 seconds of no answer the session should be terminated. (If this is possible at all)

**Environment**
* Deployer version: 6.4.6
* PHP version: PHP 7.3.11-1~deb10u1 
* Deployment target(s) OS: Debian 10

**Output log with enabled option for verbose output `-vvv`**
```
The process "ssh -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_{server ip}. {server ip} 'bash -s; printf "[exit_code:%s]" $?;'" exceeded the timeout of 300 seconds
```

**Comment by GlennM** [comment]
Encountered the same error, so would be nice when this gets implemented =)

**Comment by marvinhinz** [comment]
https://symfony.com/blog/new-in-symfony-2-4-limit-a-process-run-with-an-idle-timeout

This actually looks like an easy fix :)

**Comment by GlennM** [comment]
> https://symfony.com/blog/new-in-symfony-2-4-limit-a-process-run-with-an-idle-timeout
> 
> This actually looks like an easy fix :)

You're most welcome to provide a PR for it if it looks like an easy fix to you :)

**Comment by antonmedv** [comment]
After some thinking I decided to not implement it as default behavior. As it may be lead to potential leaks in CI. But it added extra option:

```php
run('while true; do date; sleep 1; done', ['idle_timeout' => 2]);
```

**Comment by GlennM** [comment]
Hi @antonmedv 
Thanks for the addition.
I do only need to add `['idle_timeout' => 2]` to my `run()` command right? (so not the while part).

E.g.
```php
run(
    "{{bin/php}} <path-to-php-file>",
     ['idle_timeout' => 2]
 );
```

I'm still getting an error (data obfuscated for security reasons):
```
In Process.php line 1201:
                                                                                                                             
  The process "ssh -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/X@  
  X X@X  'bash -s; printf "[exit_code:%s]" $?;'" exceeded the timeout of   
  300 seconds. 
```
What am I missing?

**Comment by antonmedv** [comment]
Yes, timeout should be set to null as well. Also note what this is in master branch only.
