### ISSUE TITLE
Change anonymous contribution from `opt-out` to `opt-in` during `deployer init`

### ISSUE THREAD

**Issue by codekandis** [deployphp/deployer#1996]
Creating a new deployer recipe with `deployer init` requests for an agreement to support deployer with anonymous stats.

I understand your intentions to gain informations as explained in the init process. I can assume a lot of scenarios how this informations would gain your development process. But I'd recommend to set focus to the need of data security. So I highly encourage you all to change your preferred `opt-in` of the default answere of `yes` to an `opt-out` with the default answere `no`.

Furtheron I'd encourage you to provide a link in your explanation where any user will be informed which exactly explained data will be provided to you. In the current state your explanation is to untransparent.

I'm an experienced PHP developer. I could take a deep dig into your code to analyze what informations would be sent to you. But this cannot be the intention if you want to be a serious product - please don't understand this as an affront, it's a view of a general audience.

I for myself would be willing to create recipe scenarios without sensitive data representing 1:1 scenarios of my production recipes - but without any sensitive SSH credentials and so on. I can imagine to deploy my projects in a parallel manner to support you with the informations you request with my participation.

**Comment by antonmedv** [comment]
What about making it opt-in for all by default. And supporting env var DONT_TRACK?

**Comment by codekandis** [comment]
I'm sorry I made a logical mistake of verbalization due to hurry during my needs to open an issue and while I'm not a native english speaker.

Please consider my change my 2nd passage to:

> I understand your intentions to gain informations as explained in the init process. I can assume a lot of scenarios how this informations would gain your development process. But I'd recommend to set focus to the need of data security. So I highly encourage you all to change your preferred `opt-out` of the default answere of `yes` to an `opt-in` with the default answere `no`.

To be clear:

Don't ask by default to participate your anonymous data collection with `yes` but with `no` for data security reasons.

**Comment by antonmedv** [comment]
Yes, I understand what you saying. What about my idea with DONT_TRACK env?

**Comment by codekandis** [comment]
Your idea does in fact require an opt-in like it currently is but with an extra layer on an `ENV` basis. This does not solve the general security need of an opt-out. What you actually recommend would harden the current state in a more obscure way.

**Comment by antonmedv** [comment]
I think I don't understand. Currently, there is a message that asks the user about sharing. Do you suggest to remove it? I think it's not fear for the user. USer must know what I'm using it for.

**Comment by codekandis** [comment]
No. I don't ask to remove the message. I understand your attempts to request shared informations.

The default answere is `yes`. So if one accidentially hits enter deployment data will be shared to you. This is the opt-out. You must explicitely enter `no` to prevent it. So if you change it to an `opt-in` the default answere just needs to be changed to `no`. So it's an `opt-in` then. If one accidentially hits enter no data will be shared which would be the safer and I think more fairer strategy then.

Additionally it would be nice to have at least a link in your message to a document describing which specifically data will be shared.

**Comment by antonmedv** [comment]
But most of users would like to share statistics. This will make init process for them a little more complicated and some of users may acid accidentally opt-out instead of opt-in. I think we need to find solution which provides consistent experience and best privacy policy.

**Comment by bhhaskin** [comment]
The best privacy policy would be to remove it altogether.  The next best thing would be to make it opt-out. Sure you might see a drop in statistics data. But really the statistics data doesn't matter.

**Comment by antonmedv** [comment]
> But really the statistics data doesn't matter.

But I use it to improve Deployer. It's really useful for me.

**Comment by antonmedv** [comment]
I'm going to rework it to something new in the next version. Changes already in master. Please verify.

**Comment by bbashy** [comment]
I did wonder why Little Snitch was popping up with connections to `deployer.org` after every deploy.

Needs something doing here https://github.com/deployphp/deployer/blob/master/src/Deployer.php#L330-L332

**Comment by antonmedv** [comment]
Yes, during init script there is an explanation about it.

**Comment by bbashy** [comment]
@antonmedv Had nothing of the sort when following this guide: https://deployer.org/docs/how-to-deploy-laravel.html

```
$ dep init -t Laravel
Successfully created: /Users/bashy/code/deployer/deploy.php
```

**Comment by antonmedv** [comment]
Yes, this because it was not in iterative mode. To prevent this I decided to disable -t option.

**Comment by bbashy** [comment]
If it's only displayed in the init command, this could be missed by someone just using deployer by making the file manually. It doesn't say anywhere on your site about it either: https://duckduckgo.com/?q=site%3Adeployer.org+allow_anonymous_stats&t=ffab&ia=web

And anyway, it should be opt-in, not opt-out.

**Comment by antonmedv** [comment]
Agree.

**Comment by antonmedv** [comment]
I refactored all this in Deployer v7. Now we use telemetry instead of statistic.

**Comment by codekandis** [comment]
Can you explain how the telemetry is intended to work?

**Comment by bbashy** [comment]
> Can you explain how the telemetry is intended to work?

https://github.com/deployphp/deployer/blob/master/src/Command/CommandCommon.php

That function is called on certain events like SSH https://github.com/deployphp/deployer/search?q=telemetry
