### ISSUE TITLE
Laravel db:seed specify class

### ISSUE THREAD

**Issue by zarulizham** [deployphp/deployer#2003]
Hello. 

I am wondering is there any command that can execute db:seed while specifying the class? 

In Laravel we can achieve like this:
```
php artisan db:seed --class=SettingsTableSeeder
```

Expected Deployer command:
```
dep db:seed --class=SettingsTableSeeder
```

I go through laravel.php recipe and did not found related to my problem.

Regards

**Comment by GlennM** [comment]
How about writing your own task based upon the native `artisan:db:seed` from Deployer?

You may try using options to specify the class:
[Using input options](https://deployer.org/docs/tasks.html#using-input-options)

Arguments might work as well, but I'm not sure [whether they will be supported in the future](https://github.com/deployphp/deployer/issues/1501#issuecomment-548768424).

**Comment by zarulizham** [comment]
Ahh thank you! Almost forgot the input options.
