### ISSUE TITLE
Hanging on SSH Multiplexing

### ISSUE THREAD

**Issue by garhbod** [deployphp/deployer#2004]
**Describe the bug**
Once deployer reaches `ssh multiplexing initialization` it just hangs there and never continues. I did some testing in terminal and I think maybe the `-N` option for ssh isn't working as expected as it is open an ssh connection but not exiting immediately after. The terminal stays in the ssh connection and requires `exit` to get back out.

**To reproduce**
Run deployer with multiplexing set to true

**Expected behavior**
Continues to run through the deployer tasks

**Environment**
* Deployer version: 5.1.3
* PHP version: 7.1.33
* Deployment target(s) OS: Ubuntu 18.04

**Comment by antonmedv** [comment]
Works for me ¯\_(ツ)_/¯

**Comment by mbardelmeijer** [comment]
What we noticed during this, is that the server isn't in the `~/.ssh/known_host` file. When connecting manually with `ssh HOSTNAME` and accepting the fingerprint, then the multiplexing works.

**Comment by antonmedv** [comment]
Strange, ssh -N should ask for a fingerprint as well. Can you check it with a different ssh version?

**Comment by garhbod** [comment]
What is the expected behaviour of the -N option?

**Comment by antonmedv** [comment]
Do not execute a remote command.  This is useful for just forwarding ports (protocol version 2
        only).

**Comment by antonmedv** [comment]
Closing this issue as inactive. If you still have this problem, please open a new issue.

**Comment by dnaber-de** [comment]
I could reproduce it and the issue was, that my host configuration was not correct:

```
host('myhost.myserver.tld')
    // the host name didn't match with the one in ~/.ssh/config
    ->hostname('my-ssh-alias')
    ->user('me');
```

**Comment by antonmedv** [comment]
Please, check the master branch as the fix was implemented there. Also, run command with `-vvv` option.

**Comment by dnaber-de** [comment]
As I said: the issue occurred to me as a result of invalid host configuration. So no issue at all for me. I just dropped a comment if others with the same symptoms find this issue.
