### ISSUE TITLE
Fatal Error after installation

### ISSUE THREAD

**Issue by prolificjones82** [deployphp/deployer#2006]
**Describe the bug**
New install running dep self-update fails.

**To reproduce**
```sh
curl -LO https://deployer.org/deployer.phar
mv deployer.phar /usr/local/bin/dep
chmod +x /usr/local/bin/dep
dep self-update 
```
... or any dep command

**Environment**
* PHP version: PHP 7.1.23

**Output log with enabled option for verbose output `-vvv`**
```sh
Fatal error: Declaration of Symfony\Component\Console\Input\Input::getArgument($name) must be compatible with Symfony\Component\Console\Input\InputInterface::getArgument(string $name) in phar:///usr/local/bin/dep/vendor/symfony/console/Input/Input.php on line 28
```

**Comment by jamesj2** [comment]
I ran into the same issue using Laradock v10.0.  Deployer 6.7.0 works but 6.7.1 does not.

**Comment by mmikhalko** [comment]
I got it as well, so when it will be fixed?

**Comment by vlamirc** [comment]
Exactly same error here.
PHP 7.1.33
Ubuntu 19.10

Tried last five versions of Deployer.

**Comment by antonmedv** [comment]
Try to update PHP to 7.3.

**Comment by vlamirc** [comment]
Thanks @antonmedv 

Update to 7.3 worked for me.
