### ISSUE TITLE
Parsing vars on array changes some chars

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#2008]
**Describe the bug**
I am not sure how is that for other chars but the case I am describing is for char "/".
If you use var inside other set() as array then the final string is ok but the char "/" is not recognized by php in explode and basepath method.  

**To reproduce**

Deploy.php
```
set('path', '/folder1/folder2/file.txt');
set('newVar', ['{{path}}']);

task('test', function () {
    $newVar = get('newVar');
    writeln(basename($newVar[0]));
    writeln(implode('-', explode("/", $newVar[0])));
});
```

the result is:

```
/folder1/folder2/file.txt
/folder1/folder2/file.txt
```

**Expected behavior**
```
file.txt
-folder1-folder2-file.txt
```

**Environment**
* Deployer version: 6.7.3
* PHP version: 7.2.15
* Deployment target(s) OS: osx

**Comment by kszymukowicz** [comment]
I forget to mention:
Setting
```set('newVar', [get('path')]);```
instead of
```set('newVar', ['{{path}}']);```
makes it working.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
