### ISSUE TITLE
Feature: Fix composer version between deploys

### ISSUE THREAD

**Issue by downace** [deployphp/deployer#2012]
Currently `deploy:vendors` uses `bin/composer` option which downloads the latest Composer binary on every deploy. This can lead to unexpected breaking changes. For example, 1.10.0 started to output a lot of deprecation warnings in my case

There are lots of easy workarounds (override `bin/composer` option, use pre-installed Composer, etc.). But it would be nice to just add something like `set('composer_version', '1.9.3')`. Or just save composer binary somewhere between deploys (maybe in `.dep` dir)

**Comment by asafov** [comment]
As i see - master branch first try to find composer binary.
```
set('bin/composer', function () {
    if (commandExist('composer')) {
        $composer = '{{bin/php}} ' . locateBinaryPath('composer');
    }

    if (empty($composer)) {
        run("cd {{release_path}} && curl -sS https://getcomposer.org/installer | {{bin/php}}");
        $composer = '{{bin/php}} {{release_path}}/composer.phar';
    }

    return $composer;
});
```
Try to set it:
`set('bin/composer', 'your_composer_path');`

**Comment by asafov** [comment]
PR #2110 ready

**Comment by antonmedv** [comment]
Fixed! Now composer will be saved!
