### ISSUE TITLE
Where can I get php7.0 version deployer?

### ISSUE THREAD

**Issue by toknT** [deployphp/deployer#2013]
In 2020 I'm reqired to use php7.0 (2019 php7.4), the current deployer in php7.0 return this error
```sh
$ dep init
PHP Parse error:  syntax error, unexpected '?' in phar:///usr/local/bin/dep/vendor/symfony/console/Terminal.php on line 127
```

so where can I get pre version dployer which support php 7.0?

**Comment by antonmedv** [comment]
I think previous version will work.

**Comment by antonmedv** [comment]
Now in master.

**Comment by antonmedv** [comment]
Or download older version on site.
