### ISSUE TITLE
Deploy magento 2.3 error about module:enable --all

### ISSUE THREAD

**Issue by gosipjalanan** [deployphp/deployer#2020]
Hai, 

I run deployer command for magento 2.3 (use recipe file magento 2.php), but i found a error like

"You cannot run this command because modules are not enabled. You can enable modules by running the 'module:enable --all' command."

can you help me?

Thanks

**Comment by riconeitzel** [comment]
can you get us some anonymized -vvv output … that error message is a magento specific one and might not be related to deployer.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).

**Comment by micahlagrange** [comment]
it's because you didn't commit config.php :)

**Comment by riconeitzel** [comment]
Sounds reasonable if you don't have a module:enable --all step in your deploy.php
