### ISSUE TITLE
Evaluate strings lazily in parallel mode

### ISSUE THREAD

**Issue by freywald** [deployphp/deployer#2026]
There are differences in behavior regarding to variable evaluation when running code in parallel mode and without. 

In /src/Host/Storage.php there is:
```
            // Materialize config values
            foreach ($host->getConfig()->getCollection() as $key => $value) {
                $values[$key] = $host->get($key);
            }
```
I think it's better to have:
```
            // Materialize config values
            foreach ($host->getConfig()->getCollection() as $key => $value) {
                if (is_string($value)) {
                    $values[$key] = $value;
                } else {
                    $values[$key] = $host->get($key);
                }
            }
```
I propose when dealing with strings we materialize the raw value and let the worker lazily parse the raw value on use within the worker task – and not before.

With parallel mode, all configuration variables are baked "materialized" before the worker task runs. You will see the materialized values in the files which are created by the expression ```sys_get_temp_dir() . '/' . uniqid('deployer-') . '-' . $host->getHostname() . '.dep'``` as you can see in the file Storage.php as well.

The variable *y* with contents **"{{x}}"** where *x* is **2** will be materialized as **2** in parallel mode instead of the raw value **"{{x}}"** – before the worker task is executed. If such a task changes *x* to **3**, *$y* keeps it value (**2**), because the parsed contents **2** are materialized instead of the raw value **"{{x}}"**.

At least, I'd love to have it as a configuration setting.

**Comment by antonmedv** [comment]
Actually I was thinking of refactoring executor to only run in parallel.

**Comment by antonmedv** [comment]
Please, check master branch. Should be fixed now.
