### ISSUE TITLE
Get current command

### ISSUE THREAD

**Issue by freywald** [deployphp/deployer#2027]
Is there a good way to get the current command? 

For example, on executing ```dep deploy:info -p``` I'd like to get the value "deploy:info".

On executing ```dep dump -p``` I get "Command "dump" is not defined.", which is fine.
"Do you want to run "config:dump" instead?  (yes/no) [no]:" yes, I type "yes". Here of course I'd like to get the corrected value "config:dump" instead of "dump". (all after "dep init" with defaults)

Is there a way?

**Comment by antonmedv** [comment]
Yes, via arguments.

**Comment by freywald** [comment]
Ah, thanks. Sure, I can do ```input()->getArgument('command')``` in a task. But there are two issues with that:

First, I'd like to get the command in the main script (not within a task) to configure some things which need to be done before the tasks run. But there is yet not Context object, so input() does not work (I know I could use multiple Deployer files and ```dep -f deploy-1.php```, but still…).
 
Second, in parallel mode, when I retrieve the command as shown above in a task, the *command* is "worker" instead of the real command.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
