### ISSUE TITLE
Git path

### ISSUE THREAD

**Issue by cheetos22** [deployphp/deployer#2029]
Hi, when i try to deploy my project i have an error 

> In Client.php line 103:
> 
>   The command "command -v 'git' || which 'git' || type -p 'git'" failed.  
> 
>   Exit Code: 1 (General error)
> 
>   Host Name: 51.83.249.158
> 
>   ================
>   which: no git in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

But when i run manualy on virtalmachine command -v 'git' or which 'git' or type -p 'git' i get /usr/bin/git path

```
vagrant@homestead:~/code$ command -v 'git'
/usr/bin/git
```
anyone has any idea how to fix it?

Regards

**Comment by martijn94** [comment]
Deployer needs GIT on the server you are deploying to, not on the server you are deploying from.

**Comment by cheetos22** [comment]
Thanks for the fresh look at the case. You have right i didn,t install git on my deployment server.
Everything works when i install git.

Thanks and Regards
