### ISSUE TITLE
FEATURE: validate var on set()

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#2034]
I suppose it can be good to have possibility to validate variable on set() as its hard to predict all possible values user can use.

For example user can set:

`set('web_path', 'public/')`;
`set('web_path', '/public')`;
`set('web_path', '/public/')`;

So maybe it would be possible to have smth like:

```
validate('web_path', function($value) {
   // validate here or throw exceptions
  // return false / true;
})
```

This callable function would need to be called on `src/functions.php` `function set($name, $value)` level.

**Comment by antonmedv** [comment]
What about validation on usage?

**Comment by kszymukowicz** [comment]
Well. What If I would like to validate `get('deploy_path')` on usage ? 
I would need to change all core task ?

**Comment by antonmedv** [comment]
But what kind of validation do you want? Existing on server? There is -p option.

**Comment by antonmedv** [comment]
I also was thinking about validation for options, but still no good implementation (please, take a look at "next" branch).

**Comment by kszymukowicz** [comment]
Look for this example.  

```
host('beta')
    ->hostname('example.com')->port(24)
    ->user('deploy')
    ->set('branch', 'master')
    ->set('public_urls', ['https://beta.example.com'])
    ->set('deploy_path', '/home/www/beta');

```

- I'd like to throw error if user will use string instead of array when using `set('public_urls')`
- I'd like to throw error if user will use url address without http schema when using `set('public_urls')`
- I'd like to throw error if user will set path with slash at the end when using `set('deploy_path')`

I just found this issue https://github.com/deployphp/deployer/issues/1460 which is probably the same what I mean :)

But in your proposal from https://github.com/deployphp/deployer/issues/1460 I am not sure if it would be easy to replace validator.

**Comment by antonmedv** [comment]
Yes, for example, if validator for `deploy_path` is set, how it's possible to override it? And how to extend (for example add validation on top of existing one).

**Comment by kszymukowicz** [comment]
Just idea.

If you define `validate('deploy_path', function($value){....})` in deployer core.
Then in deploy.php I can overwrite it with my own `validate('deploy_path', function($value){....})`.

If you want to have some validation chain then the validate function can be maybe extended with some priority. So in core:
`validate('deploy_path', 100, function($value){....})`

then I can define in my deploy.php
`validate('deploy_path', 100, function($value){....})` -> which will overwrite core validator,

or

`validate('deploy_path', 110, function($value){....})`-> which will run after core validator,

or

`validate('deploy_path', 90, function($value){....})`-> which will run before core validator.

**Comment by antonmedv** [comment]
I not really like this number. It's unclear what will be first, what second. Maybe there is no need to extend vslidators at all? Only to override?

**Comment by kszymukowicz** [comment]
Maybe the order of validators its not important at all? 
Then we can have string keys instead of numbers.
`validate('deploy_path', 'no_ending_slash', function($value){....})`
`validate('deploy_path', 'something_else', function($value){....})`

This way we can have "extending without order" and the way to unset some validators.

**Comment by antonmedv** [comment]
But what is some validation can be omitted and replaced with `normalized` step? Like for example adding tail `/` to deploy_path. I think this is even better as no user required to fix it. What is good.

Maybe it's a good idea to take a look at what other frameworks/libraries/languages deals with validation/normalization?

**Comment by antonmedv** [comment]
Can you make a PR? With `set()->validate(function)` API?

**Comment by kszymukowicz** [comment]
I can try.

So this is how it should work or you have some other idea ?

```
set('variableName', 'variableValue')->validate(function($value){
    return someBooleanCheckHere();
});
```

then if I someone would like to overwrite then he can use:

```
validate('variableName', function($value){
    return someMyBooleanCheckHere();
}));
```

**Comment by antonmedv** [comment]
Okay!

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
