### ISSUE TITLE
When `symfony_env` is set to `dev`, composer `require-dev` dependencies aren't installed.

### ISSUE THREAD

**Issue by oleg-andreyev** [deployphp/deployer#2035]
**Describe the bug**
When `symfony_env` is set to `dev`, composer `require-dev` dependencies aren't installed.

**To reproduce**
- Have something in require-dev in composer.json
- set symfony_env to dev
- run deployer, require-dev won't be installed

**Expected behavior**
require-dev dependencies are installed

**Comment by brettins** [comment]
Hi, I'm on `6.8.0` with `symfony_dev` set to `dev` and  deployer is still trying to use no dev: 

```
/usr/local/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest
```

```
set('symfony_env', 'dev');
set('env', [
    'SYMFONY_ENV' => get('symfony_env'),
]);

```

Is there something else needed to enable this feature?

**Comment by antonmedv** [comment]
Yes, update composer_option config.

**Comment by brettins** [comment]
Wouldn't that just do the same thing as the fix itself and/or override it? The fix itself in the recipe is a `set('composer_options', ...)` set of code.
