### ISSUE TITLE
Composer deployment no longer works due to writeError

### ISSUE THREAD

**Issue by AlexStansfield** [deployphp/deployer#204]
I've noticed that all my deployments now fail because of composer. But composer is working fine however deployer seem to be failing.

The problem appears to be because of this change in composer:
https://github.com/composer/composer/commit/cb336a5416595efa321c024735e6452c9c7df106

It's now outputting a LOT of messages on to stderr even when things work fine. I'm being caught out by "Loading composer repositories with package information".

This has stopped me being able to deploy. The only work around I can see at the moment is to find an older composer.phar and put it in my repo so deployer doesn't download it.

I'm raising this with the composer project and it seems mad to throw every message out as an error.

**Comment by AlexStansfield** [comment]
Issue on composer project: https://github.com/composer/composer/issues/3792

**Comment by AlexStansfield** [comment]
This is where the changes are discussed: https://github.com/composer/composer/pull/3715

**Comment by oRastor** [comment]
You can build new deployer.phar from 2.x branch. And run it without ssh2 php extension.

**Comment by oRastor** [comment]
For me works fine as hot solution.

**Comment by AlexStansfield** [comment]
Weird, I tried it with the latest code earlier and still got an issue. But just built again and it works. Maybe a problem between keyboard and user this end.

**Comment by elfet** [comment]
Check out latest on master and 2.x branch: #199 #200 
Download v2.0.5. It's fixed there. Now have an issue with phpseclib package version.

**Comment by elfet** [comment]
Fixed.
