### ISSUE TITLE
Rsync warmup fails with exclude-file

### ISSUE THREAD

**Issue by coreyworrell** [deployphp/deployer#2042]
https://github.com/deployphp/deployer/blob/71bd8a99f65b8a594b58ad8f654fa0701c1ba3c6/contrib/rsync.php#L98

When using an exclude file for `exclude-file` argument, if the file exists locally then it is added to the rsync options... But if the exclude file itself is excluded (no need to have exclude file on production server) then the warmup task fails as it cannot find the exclude file.

This task should verify that the file exists on remote or just simply remove the exclude options entirely because none of those files would be on the remote server in the first place.

ie: drop `{{rsync_excludes}}` (and `rsync_includes` and `rsync_filters` for that matter) from the command:

```php
run("rsync -{$config['flags']} {{rsync_options}}{{rsync_includes}}{{rsync_filter}} $source/ $destination/");
```

**Comment by coreyworrell** [comment]
Actually, it seems it can't find the exclude file even when it is deployed. Not sure what directory it is looking for it in. Another side question, why does rsync recipe not just use the `upload` function?

**Comment by antonmedv** [comment]
ping @johnny-bit

**Comment by johnny-bit** [comment]
I have no idea since on my servers It Works (TM).

generally warmups for rsync can be safelly set without exclude file on productions. @coreyworrell - would you like to write patch agains it?

**Comment by coreyworrell** [comment]
@johnny-bit could it be that it's different because I have `deployer/recipes` installed via composer globally?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
