### ISSUE TITLE
Task `artisan:config:clear` not found  

### ISSUE THREAD

**Issue by neatstudio** [deployphp/deployer#2048]
**Describe the bug**
Task `artisan:config:clear` not found  

**To reproduce**
1、install deployer

>    curl -LO https://deployer.org/deployer.phar
>    mv deployer.phar /usr/local/bin/dep
>    chmod +x /usr/local/bin/dep

2、dep init -t laravel
    modify deploy.php
    add code:

```php
    desc("only update" );
    task("update", [
        'deploy:update_code',
        'artisan:config:clear',
        'artisan:route:clear',
        'artisan:view:clear',
        'artisan:event:clear'
    ]);
```
3、 result：

> In TaskCollection.php line 19:                           
> Task `artisan:config:clear` not found  
> update [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

-----
I opend 'recipe/laravel.php',  this task:(artisan:config:clear) is already exists  ,why i cant use it ?

thanks

**Comment by antonmedv** [comment]
Looks like a bug. Need more context. Please, aslo try master brunch. Laravel recipe was redesigned there.

**Comment by neatstudio** [comment]
thanks !
