### ISSUE TITLE
Please add phar files to each release

### ISSUE THREAD

**Issue by AlexStansfield** [deployphp/deployer#205]
The last 2.x release to have one was 2.0.1. 

 It's not really clear which version of deployer.phar is linked from the deployer.org website. It would be good if each release had one so we could grab it from github.

**Comment by AlexStansfield** [comment]
Also perhaps have two links on the website. One to latest 3.x and one to latest 2.x

**Comment by elfet** [comment]
Now deployer.org has two links: one for beta http://deployer.org/beta/deployer.phar and one for stable: http://deployer.org/deployer.phar

**Comment by elfet** [comment]
Does GitHub has API for automatically upload files to releases?

**Comment by boonkerz** [comment]
The Stable Link is not working

**Comment by elfet** [comment]
A bug :beetle: Sorry. Now fixed.

**Comment by boonkerz** [comment]
np btw nice tool :+1:

**Comment by elfet** [comment]
Thanks! :beer:

**Comment by msidorenko** [comment]
The last 2.x release to have one was 2.0.5.  Currently the phar file are 2.0.2 version

**Comment by elfet** [comment]
This is mistake. Version is 2.0.5, need to fix version number.
