### ISSUE TITLE
Shouldn't `rollback` fail if there are no more releases to revert to?

### ISSUE THREAD

**Issue by aboks** [deployphp/deployer#2052]
If one runs the `rollback` task but there are no more previous releases to revert to, the task will output a corresponding message (https://github.com/deployphp/deployer/blob/9b019bbcb4351396090d88e22bc2c2e5d9678ff3/recipe/deploy/rollback.php#L26), but the rollback task still succeeds. This also means that the `dep` CLI command exits with a zero status code. When automating things, this may hide failures.

Wouldn't it be better to make the message an Exception, or to mark the task (and thus the `dep` CLI command) as failed in some other way?

**Comment by antonmedv** [comment]
Yes, will be cool.
