### ISSUE TITLE
Can not install via PHIVE

### ISSUE THREAD

**Issue by Lapsus** [deployphp/deployer#2053]
When trying to install deployer via phive (phar.io) an error with the phar archive is reported.

**To reproduce**
phive install https://deployer.org/deployer.phar
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Could not extract PHAR version from https://deployer.org/deployer.phar 

Other ways of installation for example `phive install deployphp/deployer` (utilizing github) also dont. 

I dont know what requirements have to be met to enable installation via phive, but if  you could  make it work it would be a real blast.

**Comment by antonmedv** [comment]
I think this is relevant to phive project, not Deployer.

**Comment by Lapsus** [comment]
https://phar.io/distribute-your-own.html

Please check the docs. Maybe you could add the phar and the asc file to your release or use 
https://github.com/sebastianbergmann/phar-site-generator to make https://deployer.org/deployer.phar to comply with phive?

**Comment by antonmedv** [comment]
Do we really need another way of installing? Have you seen [deployer/dist](https://packagist.org/packages/deployer/dist)?

**Comment by Schrank** [comment]
I want to answer this questions with a yes :-) Because phive takes care of signature checking and is a standardized way to install tools.
I'm happy to take care of the support. Imho we "only" need to add a signature to each new release with the paar file.

**Comment by Schrank** [comment]
@antonmedv ping - not sure you see this message on a closed issue without.

**Comment by antonmedv** [comment]
How many users are using it?

**Comment by Schrank** [comment]
> No, and I wouldn't know how to track it? The only request hitting our servers is the one for the central alias file. That's of course an rather vague number.

> My log dumps since the beginning of 2020 show ~130k downloads from ~60k IPs.

I would say quite a few :-)

@antonmedv I'm happy to provide a GitHub action or something to take care of the gig signing (although never done before - might take a while 🙈) but this is your playground :-) So you decide wether you want this feature. Maybe it is better in the dist repo?

**Comment by Schrank** [comment]
For reference I'll leave this here: https://github.com/composer/composer/actions/runs/361951869/workflow

**Comment by antonmedv** [comment]
Sounds good. Will add gpg signs.

**Comment by thePanz** [comment]
The above link is not working anymore.
Here is the updated one: https://github.com/composer/composer/blob/main/.github/workflows/release.yml

**Comment by thePanz** [comment]
@antonmedv any updates on this?

**Comment by antonmedv** [comment]
Sure! Let's integrate.
