### ISSUE TITLE
Differences between runLocally() and task()->local();

### ISSUE THREAD

**Issue by dnaber-de** [deployphp/deployer#2055]
**Describe the bug**
I noticed there is a difference between the behavior in command parsing of a local defined task `task()->local()` and a `runLocally()` call inside a remote task(). In detail, `{{bin/composer}}` is evaluated on the remote host if it is part of a `runLocally()` command. 

**To reproduce**
Run Deployer with the provided deploy.php

**Expected behavior**
I would expect both `{{bin/composer}}` configurations to be evaluated on localhost.

**Environment**
* Deployer version: 6.8.0
* PHP version: 7.4.5
* Deployment target(s) OS: CentOS 7

**Content of `deploy.php`**
```php
<?php

declare(strict_types=1);

namespace Deployer;

// Deployer common recipes
require_once 'recipe/common.php';

host('remote-host')
    ->hostname('my-host')
    ->user('my-user')
    ->port(22)
    ->stage('test')
    ->set(
        'deploy_path',
        '/home/my-user/tmp/deployer-test'
    );

set('default_stage', 'test');

task(
    'test:run-locally',
    static function() {
        runLocally("{{bin/composer}} diagnose");
    }
);

task(
    'test:local-task',
    static function() {
        run("{{bin/composer}} diagnose");
    }
)->local();

task(
    'deploy',
    [
        'test:run-locally',
        'test:local-task',
    ]
);
```

**Output log with enabled option for verbose output `-vvv`**
Output of `task()->local()`
```sh
$ ../vendor/bin/dep test:local-task -vvv
➤ Executing task test:local-task
[localhost] > if hash composer 2>/dev/null; then echo 'true'; fi
[localhost] < true
[localhost] > command -v 'composer' || which 'composer' || type -p 'composer'
[localhost] < /usr/local/bin/composer
[localhost] > /usr/local/bin/composer diagnose
[localhost] Output of composer diagnose here ...
✔ Ok [1s 540ms]
```

Output of `runLocally()`
```sh
$ .vendor/bin/dep test:run-locally -vvv
➤ Executing task test:run-locally
[remote-host] > if hash composer 2>/dev/null; then echo 'true'; fi
[remote-host] < true
[remote-host] > command -v 'composer' || which 'composer' || type -p 'composer'
[remote-host] < /usr/local/bin/composer
[localhost] > /usr/local/bin/composer diagnose
[localhost] Output of composer diagnose … 
• done on [remote-host]
✔ Ok [2s 446ms]
```
As you can see, the `command -v 'composer' || which 'composer' || type -p 'composer'` runs on the remote host in this case.

**Additional context**

```
function runLocally($command, $options = [])
{
    $process = Deployer::get()->processRunner;
    $hostname = 'localhost';
    $command = parse($command);

    $env = get('env', []) + ($options['env'] ?? []);
    if (!empty($env)) {
        $env = array_to_string($env);
        $command = "export $env; $command";
    }

    $output = $process->run($hostname, $command, $options);

    return rtrim($output);
}
```
The reason is that the command is parsed while the global context is still the remote host here. Maybe a simple context switch before the command parsing would fix that?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
