### ISSUE TITLE
Issue with root access

### ISSUE THREAD

**Issue by nashsaint** [deployphp/deployer#2060]
I cannot use root for composer, if I do, composer will throw an error.  I can fix this in two ways: change chown to a non-sudo user or give all the folders a 667 permissions.  

What is the best way should I take that is acceptable for deployer?

**Comment by antonmedv** [comment]
Why do you run composer under root?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
