### ISSUE TITLE
Site Down After Deploy

### ISSUE THREAD

**Issue by jledfordtbc** [deployphp/deployer#2061]
I am using deployer to deploy a Magento site and after deploy I experience some brief downtime immediately when finished.  I believe I have narrowed this down to the symlink.  The server itself sees the symlink change immediately but PHP reports "PHP Fatal error:  Unknown: Failed opening required " on files within the current folder.  My deploy config is pretty much the magento recipe with some additions and host definitions. Its short lived, less then 30 seconds.  I have experimented with a custom task doing the following:
    run("{{bin/php}} -r 'clearstatcache(true);'");
    run("{{bin/php}} -r 'opcache_reset();'");
and that shortens the downtime to more like 5-10 seconds but my preference would be none.  Any advice or other places to look?  Let me know what information you need from me.

**Comment by JNeligan** [comment]
+1 for this

**Comment by hardyjohnson** [comment]
Are you stopping Magento cron during your deploy?

**Comment by antonmedv** [comment]
Please provide more details on the error. Did you tried restarting php-fpm?

**Comment by jledfordtbc** [comment]
I am not stopping cron but on this particular test site I don't have Magento cron jobs setup so it's not interfering in my test.  We are using apache+php so no fpm to restart.  If I restart apache right away after a deploy everything is good, but I am not keen on that as a process either since it drops connections as well.  The errors I see in the apache logs look like this:
```
PHP Fatal error:  Unknown: Failed opening required.........
PHP Warning:  Unknown: failed to open stream: No such file or directory in
```
As a basic test I added a phpinfo file, loads fast and I can see results quick.  After a deploy the phpinfo file throws the same errors in the logs.  As soon as everything is cleared up all files load without issue and no errors in the apache logs.  As a test I changed php realpath_cache_size to 0, restarted apache.  After a deploy everything seems normal and I get no failures in the logs, but reading up on that php parameter it sounds like it would be a huge performance hit to disable.  Any other thoughts or need any more info from me?

**Comment by jledfordtbc** [comment]
I did another test.  I created the following file:
```
<?php
error_log(getcwd(), 0);
```
just to echo the path to apache logs.  Then I reload the tab in my browser every 1 second.  During the deploy this is what I see right after the symlink is created:
```
[Wed May 20 09:08:26.980767 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/68
[Wed May 20 09:08:28.989616 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/68
[Wed May 20 09:08:30.987431 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/68
[Wed May 20 09:08:32.985211 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/68
[Wed May 20 09:08:34.983630 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/69
[Wed May 20 09:08:36.988241 2020] [php7:notice] [pid 20127] [client 10.76.2.41:64851] /......../releases/69
[Wed May 20 09:08:38.985322 2020] [php7:warn] [pid 20127] [client 10.76.2.41:64851] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Wed May 20 09:08:38.985482 2020] [php7:warn] [pid 20127] [client 10.76.2.41:64851] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Wed May 20 09:08:38.985570 2020] [php7:error] [pid 20127] [client 10.76.2.41:64851] PHP Fatal error:  Unknown: Failed opening required '/......../current/logger.php' (include_path='.:/usr/share/php') in Unknown on line 0
[Wed May 20 09:08:41.328840 2020] [php7:notice] [pid 20142] [client 10.76.2.41:64932] /......../releases/69
```

In the above, its weird that before it fails it does see the correct path, but then fails for a period.  If I set realpath_cache_size = 0 , restart apache then deploy this is what I get where it just rolls right through:
```
[Wed May 20 09:18:04.666531 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:05.670427 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:06.673484 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:07.668229 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:08.665911 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:09.667866 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/69
[Wed May 20 09:18:10.677412 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:11.675907 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:12.667338 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:13.666821 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:14.685473 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:15.674765 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:16.675682 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
[Wed May 20 09:18:17.678610 2020] [php7:notice] [pid 2636] [client 10.76.2.41:65138] /......../releases/70
```
Everything I read though says setting realcache path to 0 comes at a large performance hit so that doesn't seem like a solution.  Help is greatly appreciated.

**Comment by antonmedv** [comment]
So this looks like a problem with the cache. After `current` symlink is changed PHP still uses the old path. What is your keep_releases config? Also, there is no need to disable realpath_cache_size. Just clear realpath_cache right after deploy. Also, try clear opcache (maybe it will help)

**Comment by jledfordtbc** [comment]
I tried the following:
```
run("{{bin/php}} -r 'clearstatcache(true);'");
run("{{bin/php}} -r 'opcache_reset();'");
```
and honestly didn't notice the difference I was expecting.  Is there a better/different way you are aware of to clear that cache?  I am also looking into swapping to Nginx since reading suggests its easier to handle this issue, swapping to Nginx is not a quick thing though.  Thanks again

**Comment by antonmedv** [comment]
You cleared cache for cli, you need to clear it for apache worker. Create some endpoint and curl it.

**Comment by jledfordtbc** [comment]
I didn't even catch that, your right.  Let me play around with that some and test and I will report back.

**Comment by jamieburchell** [comment]
You might be interested in the cachetool recipe for this...

```
host('x')
    ->set('cachetool', '/run/php-fpm/www.sock');
...
after('deploy:symlink', 'cachetool:clear:opcache');
```

**Comment by jledfordtbc** [comment]
Sorry for the late reply.  With apache I can't get the cache to clear in a reasonable amount of time at all, and still experience some sort of downtime.  I did some testing with Nginx and am able to make this go away with these changes https://serverfault.com/questions/848503/nginx-caching-symlinks.  I am going to follow that road and work to remove Apache from my magento environment.  Thanks for the help.

**Comment by jamieburchell** [comment]
If you are using PHP with Apache without FPM I assume you are using mod_php? You may find if you want to continue using Apache that switching to PHP FPM is more performant.
