### ISSUE TITLE
Docs recipe page lists 'recipe/sentry.php'; but not in current release

### ISSUE THREAD

**Issue by sdevore** [deployphp/deployer#2064]
Currently the [documentation](https://deployer.org/recipes.html) lists sentry as a recipe but it is not in the [repository](https://github.com/deployphp/deployer/tree/master/recipe) are there plans to take it from the [Archived Recipe Repository](https://github.com/deployphp/recipes/tree/master/recipe) and bring it forward to the current one?  Or is there an easy way to make use of it?

**Comment by antonmedv** [comment]
Yes, there are plans to combine recipes with docs.

**Comment by sdevore** [comment]
So I was able to use it by just making a folder next to my deploy script called recipe and put in the file from the archived repo

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
