### ISSUE TITLE
Need to cd ../; cd - after each deploy

### ISSUE THREAD

**Issue by BenasPaulikas** [deployphp/deployer#2065]
**Describe the bug**

After php vendor/bin/dep deploy in remote server I need to do cd ../; cd - so the files would be updated

**To reproduce**

1. On remote server ssh into directory
2. cat file returns content
3. php vendor/bin/dep deploy
4. cat file returns same content
5. cd ../; cd -
6. cat file now returns different content

**Expected behavior**

Expected after each php vendor/bin/dep deploy no need for cd ../; cd -

**Screenshots**

**Environment**
* Deployer version:
* PHP version:
7.4
* Deployment target(s) OS:
Linux

**Content of `deploy.php`**
```php
// your code here
```

**Output log with enabled option for verbose output `-vvv`**
```sh
# output here
```

**Additional context**

**Comment by BenasPaulikas** [comment]
Looks like this is issue with all of my servers. Tried both mv -T and ln and it's still same result need to cd ../; cd - to see changes..

**Comment by BenasPaulikas** [comment]
I only needed to use absolute paths in my background scripts.

I had start.sh code with

cd folder; php code.php

instead of php /folder/code.php

**Comment by antonmedv** [comment]
This is a feature.
