### ISSUE TITLE
Retrieve a value from one host, share it across all hosts

### ISSUE THREAD

**Issue by jtomka** [deployphp/deployer#2068]
I'm having a hard time setting a common static assets version across all nodes (magento setup:static-content:deploy --content-version).

The idea is to get timestamp from one host and use it with the above command on all nodes. At the moment it only works on the node where the timestamp was retrieved, so I'm wondering how a value retrieved from one host can be made available across all hosts. Thanks.

```
desc('Get custom version for all nodes');
task('magento:deploy:assets:version', function () {
    $timestamp = run("{{bin/php}} -r 'echo (new \DateTime())->getTimestamp();'");
    set('magento_deployed_version', $timestamp);
})->onRoles('app')->once()->setPrivate();

// vars: magento_langs (opt)
desc('Deploy assets for required languages');
task('magento:deploy:assets', function () {
    run("{{bin/php}} {{release_path}}/bin/magento setup:static-content:deploy --content-version=" . get('magento_deployed_version'));
})->onRoles('app')->addBefore('magento:deploy:assets:version');
```

**Comment by antonmedv** [comment]
This is due to set/get works in context of its own host. Two solutions:
* build on one host, copy to others
* use run on

```php
on(hosts(), function () { 
    set('magento_deployed_version', $timestamp);
});

**Comment by jtomka** [comment]
Thanks, Anton.

Build on one host, copy to others might work, since, by default, the value is generated on each host and saved into a text file. How would I go about copying the file from one host to all others with Deployer?

The on() seems to be exactly what I was after -- a way to assign the variable on all hosts. Unfortunately, it doesn't seem to work with parallel enabled. Just to make sure I've got it right, this is how I've set it up:
```
desc('Get custom version for all nodes');
task('magento:deploy:assets:version', function () {
    $timestamp = run("{{bin/php}} -r 'echo (new \DateTime())->getTimestamp();'");
    on(Deployer::get()->hosts, function($host) use (&$timestamp) {
        set('magento_deployed_version', $timestamp); 
    });
})->onRoles('app')->once()->setPrivate();

desc('Deploy assets for required languages');
task('magento:deploy:assets', function () {
    run("{{bin/php}} {{release_path}}/bin/magento setup:static-content:deploy --content-version=" . get('magento_deployed_version'));
})->onRoles('app')->addBefore('magento:deploy:assets:version');
```

**Comment by antonmedv** [comment]
Yes, I think there is a bug with parallel mode and `on` in the current version that I already fixed in the master branch. Please, test it there?

**Comment by jtomka** [comment]
I'd love to test it with master, but I'm running into incompatibilities with my setup, e.g. no roles, no stages? Is it fixed in v6.8? Thanks again.

**Comment by antonmedv** [comment]
Yes, new version has new concept: labels and selectors.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
