### ISSUE TITLE
Confusion about shared_dirs and Laravel storage folder

### ISSUE THREAD

**Issue by ryancwalsh** [deployphp/deployer#2069]
First, I really enjoy and appreciate Deployer. Thank you so much for making it.  It has been working well for me.

The only problem I've had recently is that now in my Laravel 7 project I commit to git some special files into my `storage/files` directory, and then those don't seem available after deployment.

I think the problem happens because of https://github.com/deployphp/deployer/blob/29a643b62389542394c7b254f6c913f7191132ba/recipe/deploy/shared.php

I'm not sure that this is a bug... but maybe just a lack of documentation.

I probably just don't know what this means: https://deployer.org/docs/configuration.html#shared_dirs

In my config, my `shared_dirs` is still empty.

I think a lot of other people have been confused about similar points too (and I still don't understand):

- https://github.com/deployphp/deployer/issues/572
- https://github.com/deployphp/deployer/issues/875
- https://github.com/deployphp/deployer/issues/957
- https://github.com/deployphp/deployer/issues/1593
- https://github.com/deployphp/deployer/issues/1647

Can you please clarify what `shared_files` and `shared_dirs` mean and whether they're related to my problem? Or maybe I'm accidentally not following Laravel patterns?

Thanks!

**Environment**
* Deployer version: I'm not sure how to tell
* PHP version: PHP 7.4.5 (cli)
* Deployment target(s) OS: Ubuntu

**Comment by antonmedv** [comment]
Hi, thanks. Please, provide more info and context. I’m not really laravel expert, and don’t know storage is for.

**Comment by ryancwalsh** [comment]
Thanks for your response.

In `routes/web.php`, let's say I have:
```
Route::get('some_path/mydocument.pdf', function () {
    return response()->file(storage_path('files/anydocument.pdf'));
});
```
such that visiting example.com/some_path/mydocument.pdf should display the PDF hosted within `/storage/files/anydocument.pdf`

I'm intentionally not following the Laravel pattern of storing my file in `/storage/app/public/`, which is a [special directory](https://laravel.com/docs/7.x/filesystem#the-public-disk) involved with a symbolic link, because I don't want it to be found there.

My `/storage/files/anydocument.pdf` exists within git (rather than being ignored) because I want to track version history.

Thanks.

**Comment by bbashy** [comment]
@ryancwalsh From previous experience with deployment setups like this, I believe you will need to copy any _new_ files within storage to the shared folder already on the server(s)?

Maybe list the `/storage/files` folder in the `shared_dirs` setting as that will copy it before it removes the storage folder in each release.

**Comment by ryancwalsh** [comment]
@bbashy Thanks. I'll try that on the next deployment. And how did you get your GitHub profile to say Vegan when I hover over your username?

**Comment by bbashy** [comment]
@ryancwalsh Yeah let me know how you get on. I've been doing a lot of DevOps stuff over the years.

p.s. click on your photo (top right) and you should be able to set your status there. If not, on your profile near your photo.

**Comment by ryancwalsh** [comment]
@bbashy I finally had the opportunity to deploy again today, and unfortunately `add('shared_dirs', ['/' . \App\Constants\Routes::STORAGE . '/' . \App\Constants\Routes::FILES]);` resulted in:

```
deployer@ubuntu-s-1vcpu-1gb-sfo2-01:/apps/myproject$ ls -lah current/storage/
total 36K
drwxrwsr-x+ 5 deployer www-data 4.0K Jun 25 15:20 .
drwxr-sr-x  3 deployer www-data 4.0K Jun 25 15:20 ..
drwxrwsr-x+ 4 deployer www-data 4.0K Apr 21 17:12 app
lrwxrwxrwx  1 deployer www-data    5 Jun 25 15:20 files -> files
drwxrwsr-x+ 6 deployer www-data 4.0K Apr 18 22:03 framework
drwxrwsr-x+ 2 deployer www-data 4.0K Jun 25 15:22 logs
deployer@ubuntu-s-1vcpu-1gb-sfo2-01:/apps/myproject$ ls -lah shared/storage/
total 36K
drwxrwsr-x+ 5 deployer www-data 4.0K Jun 25 15:20 .
drwxr-sr-x  3 deployer www-data 4.0K Jun 25 15:20 ..
drwxrwsr-x+ 4 deployer www-data 4.0K Apr 21 17:12 app
lrwxrwxrwx  1 deployer www-data    5 Jun 25 15:20 files -> files
drwxrwsr-x+ 6 deployer www-data 4.0K Apr 18 22:03 framework
drwxrwsr-x+ 2 deployer www-data 4.0K Jun 25 15:22 logs

deployer@ubuntu-s-1vcpu-1gb-sfo2-01:/apps/myproject$ touch /apps/myproject/shared/storage/files/test.txt
touch: cannot touch '/apps/myproject/shared/storage/files/test.txt': Too many levels of symbolic links
```

I must be making incorrect assumptions about the sparse docs at https://deployer.org/docs/configuration.html#shared_dirs

**Comment by bbashy** [comment]
@ryancwalsh I'd maybe opt for just using the resources folder. If it's in git anyway, it's no harm being in resources instead?

If not, just upload the file manually with a task. I use that to upload a new .env file to my servers.
```
task('upload:file', function () {
    upload('somefile.txt', '{{deploy_path}}/shared');
});
```

**Comment by ryancwalsh** [comment]
@bbashy Yeah I appreciate the idea. I similarly automatically upload `.env` on every deployment like that, and I was thinking my last resort would be to hard-code into this Deployer file that I want to upload this other file every time too.

Thanks!

P.S. I just figured it was worth opening this issue since I'm very likely misunderstanding something about the docs OR there is some very useful functionality missing. I'd definitely _want_ to be able to have a specified directory automatically stay updated without specifying each individual file.

**Comment by antonmedv** [comment]
Can someone validate if this still a problem in v7?

**Comment by bbashy** [comment]
Where's v7?

**Comment by antonmedv** [comment]
In master branch. First RC should be soon.

**Comment by aryanjaya** [comment]
Hi, thanks for creating this issue.

I am also having the same problem with you and I think I found out what causes it.
If you look again at line 32 in this file https://github.com/deployphp/deployer/blob/55177c5b18440912076be6d03f700fc1973de56a/recipe/deploy/shared.php#L32

That command will run if shared directory doesn't exists in shared path and if release contains shared directory.
In other words, if your shared directory is already deployed and you add something to it, the command will not run and your update will not be applied.

To fix this problem, I'm creating a new task to change the flow of creating shared directory. I also made a change in shared files

Here's the task I made.
```
<?php
namespace Deployer;

use Deployer\Exception\Exception;
use Symfony\Component\Console\Output\OutputInterface;

desc('Creating symlinks for shared files and dirs');
task('deploy:full_shared', function () {
    $sharedPath = "{{deploy_path}}/shared";

    // Validate shared_dir, find duplicates
    foreach (get('shared_dirs') as $a) {
        foreach (get('shared_dirs') as $b) {
            if ($a !== $b && strpos(rtrim($a, '/') . '/', rtrim($b, '/') . '/') === 0) {
                throw new Exception("Can not share same dirs `$a` and `$b`.");
            }
        }
    }

    $copyVerbosity = output()->getVerbosity() === OutputInterface::VERBOSITY_DEBUG ? 'v' : '';

    foreach (get('shared_dirs') as $dir) {
        // Make sure all path without tailing slash.
        $dir = trim($dir, '/');

        // Check if shared dir does not exist.
        if (!test("[ -d $sharedPath/$dir ]")) {
            // Create shared dir if it does not exist.
            run("mkdir -p $sharedPath/$dir");
        }

        // If release contains shared dir, copy that dir from release to shared.
        if (test("[ -d $(echo {{release_path}}/$dir) ]")) {
            run("cp -ru{$copyVerbosity} {{release_path}}/{$dir} {$sharedPath}/" . dirname(parse($dir)));
        }

        // Remove from source.
        run("rm -rf {{release_path}}/$dir");

        // Create path to shared dir in release dir if it does not exist.
        // Symlink will not create the path and will fail otherwise.
        run("mkdir -p `dirname {{release_path}}/$dir`");

        // Symlink shared dir to release dir
        run("{{bin/symlink}} $sharedPath/$dir {{release_path}}/$dir");
    }

    foreach (get('shared_files') as $file) {
        $dirname = dirname(parse($file));

        // Create dir of shared file if not existing
        if (!test("[ -d {$sharedPath}/{$dirname} ]")) {
            run("mkdir -p {$sharedPath}/{$dirname}");
        }

        // Check if shared file exist in release
        if (test("[ -f {{release_path}}/$file ]")) {
            // Copy file in shared dir if not present
            run(
                "cp -ru{$copyVerbosity} {{release_path}}/{$file} {$sharedPath}/{$file}"
            );
        }

        // Remove from source.
        run("if [ -f $(echo {{release_path}}/$file) ]; then rm -rf {{release_path}}/$file; fi");

        // Ensure dir is available in release
        run("if [ ! -d $(echo {{release_path}}/$dirname) ]; then mkdir -p {{release_path}}/$dirname;fi");

        // Touch shared
        run("touch $sharedPath/$file");

        // Symlink shared dir to release dir
        run("{{bin/symlink}} $sharedPath/$file {{release_path}}/$file");
    }
});

```

If you have noticed, I used the `cp -ru` command to copy the directory and file. You can find out the detail of this command in this link https://man7.org/linux/man-pages/man1/cp.1.html

ps: I think this problem still exists in v7

Thanks

**Environment**

Laravel Depolyer: 0.3.5
Deployer version: 6.8.0
PHP version: PHP 7.4.3 (cli)
Deployment target(s) OS: Ubuntu 20.04

**Comment by antonmedv** [comment]
Awesome! What about creating PR fir v7?  If you can add some tests if will be cool too.

**Comment by aryanjaya** [comment]
@antonmedv thanks for your response. I will try to make PR for this issue.
