### ISSUE TITLE
How do I filter which branch to use in specific stage environment deploy?

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#207]
Version 3 supports stage environments for deployment.
The branch to use is set with environment parameter, eg:
``env('branch', 'master');``
How do I set this to a specific stage environment?

**Comment by EkAndreas** [comment]
Just put it to the stage definition like this?
```
server( 'production', 'myserver' )
    ->env('deploy_path','/var/www/myweb')
	->user( 'mydeployuser' )
        ->env('branch', 'master')
	->pubKey();
```

**Comment by EkAndreas** [comment]
Seems to work perfectly! Sorry for adding another issue here!

**Comment by elfet** [comment]
```php
server(...)
    ->env('branch', 'master');
```
