### ISSUE TITLE
deployer.org down

### ISSUE THREAD

**Issue by sandermarechal** [deployphp/deployer#2070]
deployer.org appears to be down, causing docker build scripts that automatically download https://deployer.org/deployer.phar to fail

**Comment by Turpoint** [comment]
Same problem over here

**Comment by sandermarechal** [comment]
As a (future) work-around, perhaps the Phar file can be added as an asset to the Github releases? Then we can download from Github directly as well.

**Comment by antonmedv** [comment]
Yes, some issues with my linode host. Will think about publishing it to release pages as well.

**Comment by antonmedv** [comment]
Now everything should be back at normal.

**Comment by sandermarechal** [comment]
Can confirm, thank!
