### ISSUE TITLE
Build assets on single host and upload them to other hosts

### ISSUE THREAD

**Issue by ggolda** [deployphp/deployer#2071]
Sorry, was unable to find exact same issue so decided to create a new one.

Is it possible to build all assets (frontend and composer dependencies) on one host and then upload it to other hosts? Will it work with `parallel` flag so that build step is executed only once on provided host?

Thanks!

**Comment by antonmedv** [comment]
Yes, it’s possible. Take a look on on/invoke func. Will write a guide on how to do it if  I have enough time.

**Comment by ggolda** [comment]
Thanks! Will take a look!

**Comment by ggolda** [comment]
Hey, any updates related to this problem? From the docs its not clear how invoke works and how to upload build artifacts to other servers from my inventory file. Thank you.

**Comment by antonmedv** [comment]
Docs will be updated.

**Comment by 1ma** [comment]
I was looking for the same thing, it's explained here: https://deployer.org/docs/advanced/deploy-strategies.html

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
