### ISSUE TITLE
Change host deploy

### ISSUE THREAD

**Issue by demesiooliveira** [deployphp/deployer#2074]
Hi guys.

I'm trying to create a function that runs before the deployment in which it lists the hosts in the file and the user can select which host to deploy. However I am not able to select the host after choosing the user.

can anybody help me?

```
host('app-test')
    ->hostname('xxx.xxx.xxx.xxx')
    ->user('user')
    ->identityFile('~/user/file.pem')
    ->stage('test')
    ->roles('app')
    ->forwardAgent()
    ->set('deploy_path', '~/apps/{{application}}/test');

host('app-prod')
    ->hostname('xxx.xxx.xxx.xxx')
    ->user('user')
    ->identityFile('~/user/file.pem')
    ->stage('prod')
    ->roles('app')
    ->forwardAgent()
    ->set('deploy_path', '~/apps/{{application}}/prod');
```

```
task('select_host', function () {

    $hosts = Deployer::get()->hosts->toArray();
    $keysHost = array_keys($hosts);

    $hostSelected = askChoice('Select the version you want to deploy: ', $keysHost, null, false);

    writeln("Deploy: " . $hostSelected);

})->local();
```

> $ dep deploy
> Select the version you want to deploy:  
>   [0] app-test
>   [1] app-prod

**Comment by antonmedv** [comment]
Actually this already implemented in master branch. Take a look.

**Comment by demesiooliveira** [comment]
Hi @antonmedv, thanks for the replies.


I checked Milestone 7.0 and the docs and changelog files but I just found this function #1532. Would it be this?

**Comment by antonmedv** [comment]
Yes, but in master branch there is already host selector implemented you can just not specify host at all.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
