### ISSUE TITLE
Can't deploy artifacts

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2075]
This is more of a question. Sorry.

According to the *getting started* instructions, one must define a *repository*.

>  You need to configure parameters such as `repository`

This implies we must deploy from a repository and therefore cannot deploy artifacts. Can Deployer deploy artifacts (e.g. compressed archives) or not?

**Comment by antonmedv** [comment]
Yes, just override `deploy:upload_code` task.

**Comment by Bilge** [comment]
Rather than override `deploy:update_code`, I replaced it with my own `deploy:artifact`. This works well for me.

![image](https://user-images.githubusercontent.com/470626/84509490-b1cbb280-acbb-11ea-9df8-dc293b66319d.png)

One thing to note is that whilst most stuff related to Git is self-contained in the `deploy:update_code` task, there is some Git-specific stuff in `common.php` as well, which is inherited by everyone unless they avoid extending *common* altogether. It might be a good idea to split out the Git-specific stuff from `common.php`, e.g. tag/branch/revision options and repository URL, to avoid assuming everyone wants to use Git to deploy (hint: Git was never designed for that).
