### ISSUE TITLE
Running Deployer on Windows 10

### ISSUE THREAD

**Issue by Quin452** [deployphp/deployer#2078]
**Describe the bug**
I cannot use Deployer on Windows 10, returns some error code.
```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../deployer/deployer/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/dep" "$@"
```

**To reproduce**
Fresh install, using Cmder or Git Bash, installing with the "Source composer installation" instructions.

**Expected behavior**
Something to happen (following the guide and cannot get to `dep list`)

**Screenshots**

**Environment**
* Deployer version: Latest (6.8, I belive)
* PHP version: 7.3.18
* Deployment target(s) OS: Windows 10 (64bit)

**Content of `deploy.php`**
```
<?php
namespace Deployer;

require 'recipe/symfony.php';

// Project name
set('application', 'my_project');

// Project repository
set('repository', 'git@bitbucket.org:ruddygood/corpdb.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server
add('writable_dirs', []);


// Hosts

host('project.com')
    ->set('deploy_path', '~/{{application}}');

// Tasks

task('build', function () {
    run('cd {{release_path}} && build');
});

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.

before('deploy:symlink', 'database:migrate');
```

**Output log with enabled option for verbose output `-vvv`**
```sh
# output here
```

**Additional context**
Literally following the guide, as is.

**Comment by antonmedv** [comment]
Use WSL.

**Comment by Quin452** [comment]
> Use WSL.

I've tried that, 10 mins ago, exact same results.
Even tried Cygwin, and that also errors out the same way.

dep is "update or use php" and php is the error code.

**Comment by antonmedv** [comment]
Need more context. For me it’s working on Windows.

**Comment by Quin452** [comment]
That's great for you, but I cannot add more context, because I have put down everything that I've done to try and get it to work.

**Comment by Quin452** [comment]
I love how you close the ticket when you've haven't been able to resolve the issue or work with me on it!

Luckily for me, I've been able to get it sorted out, but I shan't post the answer here, since I did all the figuring out myself.
