### ISSUE TITLE
Naming Consistency with hosts.yaml

### ISSUE THREAD

**Issue by exts** [deployphp/deployer#2082]
Currently inside the `hosts.yaml` file there are snake case & camelcase in the naming conventions. I propose in the next major version to break backwards compatibility to make the naming conventions consistent across the board.

The two examples I'm speaking of is `deploy_path` and `indentityFile` or `forwardAgent`. I think the values need to either be all snake case or all camelCase.

**Comment by antonmedv** [comment]
Fully agree. And actually this is already done in master. Please, take a look.
