### ISSUE TITLE
Shared files undocumented

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2085]
[This doesn't seem like documentation to me](https://deployer.org/docs/configuration.html#shared_files).

![image](https://user-images.githubusercontent.com/470626/84452214-1ef42f00-ac4d-11ea-9d75-3b731c4a17d3.png)

* What is the purpose of shared files?
* How are shared files deployed?
* In what sense are they shared; what are they shared with?
* What are the intended use-cases for shared files?
* How are shared files persisted between deployments or shared between releases?

These kinds of questions should be addressed in the documentation.

**Comment by antonmedv** [comment]
I will for on better docs soon.

**Comment by Bilge** [comment]
There is some documentation [here](https://deployer.org/docs/flow.html#deployshared).

**Comment by antonmedv** [comment]
Done! As well as autodoc generation. Now doc should be more in sync with code.
