### ISSUE TITLE
Deployment errors omit output 

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2086]
Deployment errors give no indication as to the cause of failure because they omit output. The best clue you have is a command to reproduce the error manually.

>./deployer.phar  deploy --tag 1.0

```
✈︎ Deploying tag 1.0 on [redacted]
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
✔ Executing task deploy:failed
✔ Executing task deploy:unlock

In Client.php line 103:

  The command "cd ~/my_project && (/usr/bin/git clone -b "1.0" --recursive  git@github.com:[redacted].git ~/my_project/releases/2 2>&1)" failed.

  Exit Code: 128 (Invalid exit argument)

  Host Name: [redacted]

  ================
  mux_client_request_session: read from master failed: Connection reset by peer
  ControlSocket C:\\Users\\Bilge/.ssh/deployer_[redacted] already exists, disabling multiplexing
```

The correct error message here should be `fatal: Remote branch 1.0 not found in upstream origin`, but it is not displayed.

**Comment by antonmedv** [comment]
Yes, you are right. Please, check master branch. I really improved it there.

**Comment by Bilge** [comment]
Can you make a release?

**Comment by antonmedv** [comment]
No, there is currently work in progress.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
