### ISSUE TITLE
Provide argument extension point

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2087]
Relating to #2075, if we're changing the deployment paradigm from Git to artifacts, there isn't really a good way to specify which version we want to deploy. We can definitely abuse `--tag` to set the version that way, but it would be preferable to say what we mean and set `--version` (although that particular option seems to be reserved for some other purpose). In any case, the point is that Deployer does not currently provide any (simple) mechanism to expand the arguments or options accepted by commands.

The only way I can see to do this would be to call `Context::getInput()` to get the Symfony `InputInterface` and then start augmenting it. In the case of options, this means calling `Symfony\Component\Console\Input\Input::bind` to replace the entire `InputDefinition`, which is very awkward because it doesn't preserve the existing definition, thus we lose all existing arguments and options, which may not be desirable.

**Comment by antonmedv** [comment]
Sorry, I didn’t get what do you mean. Please, clarify.

**Comment by Bilge** [comment]
Add more of these.

![image](https://user-images.githubusercontent.com/470626/84494810-095d2480-aca2-11ea-8baa-d2bb297e3d86.png)

**Comment by Bilge** [comment]
Never mind, seems [that's supported](https://deployer.org/docs/tasks.html#using-input-options).
