### ISSUE TITLE
Task inhertance mechanism

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2088]
Although it is possible to *override* tasks by registering a new task with an existing name, there appears to be no way to call the original implementation. So for example, if I want to add some additional sanity checks to `deploy:prepare`, the best I can do is insert an entirely new task before/after it when what I really want to do is *extend* it with new behaviour.

**Comment by antonmedv** [comment]
In new version you can pass function as second argument to after/before func.

**Comment by Bilge** [comment]
Sounds good. Do we know when the new version will be released?

**Comment by antonmedv** [comment]
No. I hope to find some time to finish it.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
