### ISSUE TITLE
Idea - ability to list loaded recipes

### ISSUE THREAD

**Issue by asafov** [deployphp/deployer#2091]
Hello, dear users.
How about do function, that will return list of loaded recipes, and get base recipe name.
At this moment i develop ISPManager recipe and i think, that it will be very nice, if my recipe can detect, that loaded laravel base recipe for create custom http server config for this.
Or exist crontab recipe - if it can detect, that laravel is loaded, it can generate crontab string himself.
I think it can be many use cases for this function.

**Comment by asafov** [comment]
Another case - create database by ISPManager and generate .env file with connection params.

**Comment by antonmedv** [comment]
You can check master branch. There is a command for this: list.

**Comment by asafov** [comment]
And how to call it from recipe code?

**Comment by antonmedv** [comment]
What exactly are you looking for? What kind of information. List is available in Symfony api.

**Comment by asafov** [comment]
I mean to create global array, which have list of all loaded recipes.
For this operation need to append data to this array from all current recipes.
For example take laravel.php recipe and do something like:
```
    add('loaded_recipes', [
        'laravel' => [
            'type' => 'template',
            'version' => '6.5',
            'features' => [
                'use_horizon' => true,
                'use_telescope' => true,
                'use_cronjobs' => true,
            ],
            'additional' => [
                'somekey' => 'somevalue',
            ],
        ],
    ]);
```

For telegram:
```
    add('loaded_recipes', [
        'telegram' => [
            'type' => 'service',
            'features' => [
                'success_notify' => true,
                'failure_notify' => false,
            ],
        ],
    ]);
```

So in my crontab recipe i can detect, that laravel recipe used, read features and find, that cronjobs is enabled, so can do some actions auto.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
