### ISSUE TITLE
Frequent intermittent failures

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2092]
**Describe the bug**
A working deployment pipeline often fails at random points. The deployment has to be retried several times until it finally suceeds.

**To reproduce**
1. `vendor/bin/dep deploy`

**Expected behavior**
Deployment should complete in first pass if there are no permanent errors.

**Environment**
* Deployer version: v6.8.0
* PHP version: 7.4.2
* Deployment target(s) OS: Ubuntu 18.04

**Output log**
```sh
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
➤ Executing task deploy:release
✔ Executing task deploy:failed
✔ Executing task deploy:unlock

In Client.php line 103:

  The command "cd /var/www/"foo bar" && (if [ -d releases ] && [ "$(ls -A releases)" ]; then echo 'true'; fi)" failed.

  Exit Code: -1 (Unknown error)

  Host Name: ipv6.example.com

  ================
  mm_send_fd: sendmsg(2): Connection reset by peer
  mux_client_request_session: send fds failed

```

**Additional context**
Deploying from Windows 10 to Ubuntu 18 over IPv6.

**Comment by antonmedv** [comment]
Looks like connection problems: Connection reset by peer.

**Comment by Bilge** [comment]
OK, but it should be noted I have no such problems using PuTTY or SSH or any other mechanism of SSHing to the same server and have had no problems for over 10 years with several different ISPs. This problem is exclusive to Deployer.

**Comment by antonmedv** [comment]
I can't tell more on these types of messages.

**Comment by asafov** [comment]
It's only with IPv6 connections? With IPv4 works fine?

**Comment by Bilge** [comment]
I cannot use IPv4.

**Comment by asafov** [comment]
IPv4 disabled in OS?

**Comment by Bilge** [comment]
CGNAT.

**Comment by asafov** [comment]
OpenSSL library in OS at last version? I see same issues in other products, seems not deployer bug, may be OpenSSL bug.
https://community.cisco.com/t5/sd-wan-and-cloud-networking/ansible-copy-broken-for-release-19-1-0/m-p/3889112#M914

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).

**Comment by Bilge** [comment]
This issue is still rife.
