### ISSUE TITLE
Add real time output when in verbose/debug mode

### ISSUE THREAD

**Issue by tomzx** [deployphp/deployer#210]
If I am not mistaken, it is possible to have `phpseclib` output what is currently outputted when `exec` is called with a callback.

This would allow us to follow the progression of a long running command (which can let us know if there's a problem or if everything is working correctly).

**Comment by elfet** [comment]
Do you know how to do it?

**Comment by yannschepens** [comment]
Hi people,

Check that : https://github.com/deployphp/deployer/pull/275

**Comment by tomzx** [comment]
@elfet No, I've never used phpseclib. But [this page](http://phpseclib.sourceforge.net/ssh/examples.html#callback) from their documentation seems to show a simple example of how to do it.

**Comment by elfet** [comment]
Can you create PR for this?

**Comment by tomzx** [comment]
I do not see myself working on this anytime soon, so no.

**Comment by dima-stefantsov** [comment]
I'd like to have it as well.
