### ISSUE TITLE
Excluding a specific sub-directory from shared_dirs

### ISSUE THREAD

**Issue by bbceg** [deployphp/deployer#2107]
Hello,
I need to be able to deploy a sub-directory (let's call it 'versioned-sub-directory') of a directory ('parent-directory') that is currently specified under shared_dirs. 

I could use 'shared_dirs' to specify all of the sub-directories under 'parent-directory', leaving out both the 'parent-directory' and 'versioned-sub-directory' however the contents of 'parent-directory' can change without my knowledge so I would prefer to avoid this. 

Here's my current directory structure for shared dirs:

parent-directory
--unversioned-sub-directory-1
--unversioned-sub-directory-2
--unversioned-sub-directory-3
--versioned-sub-directory
--unversioned-sub-directory-4

By default that configuration won't deploy --versioned-sub-directory

I hope that makes sense. Is there a way of achieving this?

Many thanks

**Comment by antonmedv** [comment]
Dud not get it.

**Comment by bbceg** [comment]
:) I'll try again...

I have a directory specified in shared_dirs but I need to ensure one of its children is deployed.

Is that any clearer!?

**Comment by antonmedv** [comment]
Solution: write your own task for doing it.

**Comment by bbceg** [comment]
Just in case anyone else comes across this, here's my approach to solving it:

### New Tasks (Marked private as not expected to be run independently)
```
desc('Copy directories to be excluded from shared dirs');
task('shared_exclusions:copy', function () {
    $tempPath = "/tmp/";

    foreach (get('shared_dirs_exclusions') as $dir) {
        // If release contains excluded shared dir, copy that dir from release to tmp.
        if (test("[ -d $(echo {{release_path}}/$dir) ]")) {
            run("mkdir -p $tempPath" . dirname(parse($dir)));
            run("cp -rv {{release_path}}/$dir $tempPath" . dirname(parse($dir)));
        }
    }
})->setPrivate();

desc('Reinstate directories excluded from shared dirs');
task('shared_exclusions:reinstate', function () {
    $tempPath = "/tmp/";

    foreach (get('shared_dirs_exclusions') as $dir) {
        // If tmp contains excluded dir, copy that dir from release to tmp.
        if (test("[ -d $(echo $tempPath$dir) ]")) {
            run("cp -rv $tempPath$dir {{release_path}}/" . dirname(parse($dir)));
            run("rm -r $tempPath" . dirname(parse($dir)));
        }
    }
})->setPrivate();
```

### Update deploy routine
```
desc('DEPLOY - Regular deployment');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'shared_exclusions:copy',
    'deploy:shared',
    'shared_exclusions:reinstate',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);
```

### Example Config
```
set('shared_dirs_exclusions', [
    'public_html/content/plugins/dir-to-exclude'
]);
```

### Add a Default (to avoid errors when there are no directories to be ignored)
`set('shared_dirs_exclusions', array());`
