### ISSUE TITLE
Slack recipe

### ISSUE THREAD

**Issue by BenasPaulikas** [deployphp/deployer#2108]
https://deployer.org/recipes/slack.html

But it's not found in https://github.com/deployphp/deployer/tree/6.x/recipe

**Comment by asafov** [comment]
Recipes moved to contrib folder.
https://github.com/deployphp/deployer/blob/master/contrib/slack.php

**Comment by BenasPaulikas** [comment]
Ok thank you but

I have     "deployer/deployer": "^6.8" this version but there's no contrib folder there. Am I doing something wrong ?

![image](https://user-images.githubusercontent.com/6473565/85504712-37712b80-b5f5-11ea-8403-6617b04e2eb3.png)

**Comment by asafov** [comment]
use dev-master

**Comment by BenasPaulikas** [comment]
That would work but dev-master has symfony/yaml: ^5 but 6.8 uses symfony/yaml: ~2.7|~3.0|~4.0|~5.0

My project has package which use yaml < 5. I will just copy paste slack recipe to my project thank you :)

**Comment by inverse** [comment]
When is a new release expected to land?

**Comment by antonmedv** [comment]
I hope soon. But can’t promise anything)

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
