### ISSUE TITLE
Laravel recipe: artisan config:cache is called twice

### ISSUE THREAD

**Issue by bjoerne2** [deployphp/deployer#2113]
The deploy tasks of the current Laravel recipe (recipe/laravel.php) contain the following steps
```
    'artisan:config:cache',
    'artisan:optimize',
```

In Laravel the ```artisan:optimize``` command (Illuminate\Foundation\Console\OptimizeCommand) calls
```
        $this->call('config:cache');
        $this->call('route:cache');
```

That means that Deployer executes effectively
* artisan config:cache
* artisan config:cache
* artisan route:cache

artisan config:cache is called twice.

I see two variants to fix it:

# Variant 1: only artisan:optimize

```
    'artisan:optimize',
```

# Variant 2: artisan:route:cache instead of artisan:optimize

```
    'artisan:config:cache',
    'artisan:route:cache',
```

**Environment**
* Deployer version: 6.8.0
* PHP version: 7.2.24
* Deployment target(s) OS: Ubuntu 18.04.4 LTS
* Laravel version: 7.15.0

**Comment by antonmedv** [comment]
Please, take a look at master branch. I think it’s already fixed there. Please, verify?

**Comment by bjoerne2** [comment]
True, but artisan:route:cache is missing in the deploy process. It that intended?

**Comment by antonmedv** [comment]
I’m not sure.

**Comment by denisgorbunov** [comment]
Since [version 5.5](https://laravel.com/docs/5.5/upgrade), this task can be removed from the script: 

> The optimize Command
> With recent improvements to PHP op-code caching, the optimize Artisan command is no longer needed. You should remove any references to this command from your deployment scripts as it will be removed in a future release of Laravel.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
