### ISSUE TITLE
Upload a specific folder to remote server

### ISSUE THREAD

**Issue by sefaYavuz** [deployphp/deployer#2117]
I'm using laravel and docker in my git project. With the following directory structure:

```
- docker
-- <docker stuff>
- src
-- <laravel application>
```

I'm using deployer with the laravel recipe and want deployer to upload only the files in the `src` folder. How can i achieve this? The code in `recipe/deploy/update_code` moves all the files from the repository to the remote server:

```
 run("$git clone $at $recursive $quiet --reference {{previous_release}} $dissociate $repository  {{release_path}} 2>&1", $options);
```

**Comment by GlennM** [comment]
Not sure if that would be possible, since the main idea is to clone repositories.
You can, however, write a custom task which removes your `docker` directory from your server.

**Comment by sefaYavuz** [comment]
@GlennM I suppose that could work in my case. Gonna implement this, tnx!

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
