### ISSUE TITLE
When deployer fails it returns exit code 0

### ISSUE THREAD

**Issue by nickygerritsen** [deployphp/deployer#2119]
**Describe the bug**
It seems Deployer doesn't return a non-zero exit code when an exception occurs.

**To reproduce**
This is a (slightly modified because of internal data) version of our entry.php:
```php
<?php
/**
 * Main entry file for deployment
 */

namespace Deployer;

// Include common recipes
use Deployer\Task\Context;

include __DIR__ . '/../vendor/deployer/deployer/recipe/common.php';

inventory(__DIR__ . '/hosts.yml');

// Set the shared files and folders
set('shared_files', [/* hidden */]);
set('shared_dirs', [/* hidden */]);
set('project_root', realpath(__DIR__ . '/../'));

set('deploy_user', function () {
    return Context::get()->getHost()->getUser();
});

/**
 * Global deployment task
 */
desc('Deployment');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:unpack',
    'deploy:shared',
    'deploy:writable',
    'deploy:migrate_db',
    'deploy:post_install',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])->onRoles(['web', 'db', 'worker']);

/**
 * Unpack archive
 */
desc('Unpacking archive');
task('deploy:unpack', function () {
    writeln('📦 Unpacking build <fg=magenta>{{release_name}}</fg=magenta> to <fg=yellow>{{release_path}}</fg=yellow> on <fg=cyan>{{hostname}}</fg=cyan>');

    $scpBinPath = runLocally('which scp');
    runLocally($scpBinPath . ' {{project_root}}/dist/project.tar.gz {{deploy_user}}@{{hostname}}:{{release_path}}');
    run('tar -zxvf {{release_path}}/project.tar.gz -C {{release_path}}');
    run('rm {{release_path}}/project.tar.gz');
});

/**
 * Execute composer post install
 */
desc('Composer post install');
task('deploy:post_install', function () {
    run('cd {{release_path}} && ./vendor/bin/composer run post-install-cmd --no-interaction');
});

/**
 * Define a migration task
 */
desc('Migration of database');
task('deploy:migrate_db', function () {
    run('cd {{release_path}} && ./vendor/bin/composer run migrate --no-interaction');
    run('{{release_path}}/bin/cake orm_cache clear');
    run('{{release_path}}/bin/cake orm_cache build');
})->onRoles('db');

/**
 * Ensure opcache is reloaded
 */
task('server:opcache_reload', function () {
    writeln('Reloading opcache');
    run(locateBinaryPath('php-cachetool') . ' opcache:reset --fcgi');
})->onRoles('web');

/**
 * Set our own info task
 */
task('deploy:info', function () {
    writeln("✈︎ Deploying <fg=magenta>{{release_name}}</fg=magenta> on <fg=cyan>{{hostname}}</fg=cyan>");
})->shallow()
  ->setPrivate();


after('deploy', 'success');
after('deploy:failed', 'deploy:unlock');
after('success', 'server:opcache_reload');
```

Then if the deployment fails (for example because it can't connect to a host) it prints an exception but then gives exit code 0.

**Expected behavior**
I expect a non-zero exit code

**Environment**
* Deployer version: Tested with both 6.3 and 6.6
* PHP version: 7.4
* Deployment target(s) OS: Ubuntu 20.04

**Content of `deploy.php`**
```php
// see above
```

**Additional context**

I did some digging in the Symfony code, and it seems that in `Symfony\Component\Console\Application` `$catchExceptions` is set to `true` by default, which makes the `run` method catch exceptions, even if a custom exception handler is set (which Deployer does). That `run` method then *does* return a non-zero value, but that is not used by `Deployer\Deployer::run` to exit with that code.

A possible solution would be to let `Deployer\Deployer::run` return the code returned from `$console->run` and let `bin/dep` exit with that code.

I did see another issue here (#1045) that in 2017 this was broken but fixed with an update, so this feels to me like I might be doing something wrong. However, I don't know what.

**Comment by antonmedv** [comment]
Looks like a floating bug. Some test maybe needed. Can you write such test? Also in master it’s fixed already.

**Comment by nickygerritsen** [comment]
How exactly does it work in master? Anyway, if it is fixed there, that is fine for me. Then we will update at some point.

**Comment by antonmedv** [comment]
Fixed,
