### ISSUE TITLE
Support private tasks

### ISSUE THREAD

**Issue by KingCrunch** [deployphp/deployer#212]
Tbh I don't know, if it's not already possible, but at least it is not mentioned anywhere :smile: 

```php
task('foo', function() {
    // internal use only
});

before('deploy', 'foo');
```

I want, that some tasks aren't callable from CLI and aren't visible from `deployer.phar list`. The rationale behind this is, that this task only exists to fulfill certain conditions for other tasks and as such should only be used as a depency. For example `deploy:prepare` is only to fullfil conditions for other tasks, but doesn't serve any other purpose, especially there is never a reason to call it manually.

**Comment by tomzx** [comment]
Looks like that already exist. See https://github.com/deployphp/deployer/blob/dc939056edee6ec7fe9a73fcae568df2c55d5825/recipe/common.php#L274.

**Comment by KingCrunch** [comment]
Thanks, that's indeed exactly what I was looking for. When I find some time I'll try to add this to the docs.

**Comment by david884** [comment]
感謝您們的指教.我英文都不會手機又常常換才會有那麼多問題 現在都把手機當個人電腦.朋友電話聊天等等資訊都在手機里.但是手機一上網就又是公用平臺 有時寫上去的文字得罪了人自己還不知道.有些人或許會提醒有些就會拿來當笑話給人看.沒辦法誰要我們自己不會還當藉口抱歉了。
