### ISSUE TITLE
Sentry release

### ISSUE THREAD

**Issue by IP-Developer** [deployphp/deployer#2125]
Currently there is no way to set the `repository` parameter for a Sentry release using the sentry recipe. It is mandatory for proper integration of Sentry with Github, for example. The `repository` value from global config could be used to solve this, but it should be possible to overwrite it in the `sentry` config.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
