### ISSUE TITLE
Collapsible output in CI

### ISSUE THREAD

**Issue by colinodell** [deployphp/deployer#2126]
When I run deployments via CI, I would like for verbose output to become collapsed in the CI logs so that I can more easily see both the overall progress and the details of certain tasks.

Some CI tools have a way for processes to delineate the start and end of collapsible sections by outputting some kind of delimiter to stdout:

 - [Travis CI](https://github.com/travis-ci/travis-rubies/blob/9f7962a881c55d32da7c76baefc58b89e3941d91/build.sh#L38-L44)
 - [Gitlab CI](https://docs.gitlab.com/ee/ci/pipelines/#custom-collapsible-sections)

It would be great if Deployer had the ability to output these delimiters when running with `-v`, `-vv`, or `-vvv`.  Perhaps automatic support for major CI platforms could be baked right in, or maybe just allow for easy customization of the output strings so users can do this themselves by defining some kind of string template.

**Comment by antonmedv** [comment]
Awesome idea! Can you implement it in PR?

**Comment by wotta** [comment]
Really love this idea. I am currently searching for a similar way to display the output per command ( invokes ) for local builds.
Does these two have some sort of overlap by any change?

**Comment by Gamesh** [comment]
Gitlab CI docs about collapsable sections seems be broken, found this while searching the docs https://docs.gitlab.com/ee/ci/jobs/#custom-collapsible-sections

really awesome feature

**Comment by antonmedv** [comment]
Done! Now Deployer has it:
<img width="395" alt="Снимок экрана 2021-10-16 в 00 17 11" src="https://user-images.githubusercontent.com/141232/137559323-860e7aed-05fe-4758-a7a9-fea8b75d55d9.png">
!

**Comment by antonmedv** [comment]
@stefanzweifel take a look ☝🏻

**Comment by stefanzweifel** [comment]
@antonmedv Looks dope! 🤩
