### ISSUE TITLE
How to change storage symlink to custom symlink

### ISSUE THREAD

**Issue by gadangmadhulika** [deployphp/deployer#2136]
Hi @antonmedv, In our project the symlink path should be constant as it is mounted from volume and the path is being saved into database for getting relations and old relations are missing due to the deployer storage symlink path.
I need the storage symlink path as below
/var/www/project/public/storage/files/testfolder/paper.jpg
but the symlink path used in deployer as   /var/www/project/releases/1/public/storage/files/testfolder/paper.jpg.
Please kindly advice.
Thank you for your response in advance.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
