### ISSUE TITLE
Use same release number on different servers

### ISSUE THREAD

**Issue by alexander-schranz** [deployphp/deployer#2138]
**Describe the bug**

It is more a change request then a bug:

Currently if you deploy an application the release number is increased to the new release of that server. That means that you could have different releases numbers betweens server e.g.:

```yaml
Server 1: /var/www/app/releases/28
Server 2: /var/www/app/releases/30
```

This could make problems in php framework which uses the realpath to its project to create cache seed when using a central redis cache. E.g. Symfony

**To reproduce**

Deploy an application to multiple servers, the releases number could be different between this servers.

**Expected behavior**

It should be possible that the release number between the servers stay the same so it will always use the highest release number, maybe possible by using an own cache.

**Screenshots**

Not needed for this issue.

**Environment** 
* Deployer version: v6.8.0
* PHP version: 7.4.7
* Deployment target(s) OS: Linux / Ubuntu

**Content of `deploy.php`**

See: https://sulu.io/blog/deploy-sulu-with-deployer

**Output log with enabled option for verbose output `-vvv`**

Not needed for this issue.

**Additional context**

Not needed for this issue.

**Comment by antonmedv** [comment]
This is possible but there should be single source of truth. If there are many servers it’s difficult to implement. Possible some kind of synchronisation across all servers, but it’s difficult and will slow down a release process as well as forbid multi step deploys there one part of servers deployed per day. 

One of simplest solutions is to use git tags names as release name. This is simply achievable by replacing release name definition.

**Comment by alexander-schranz** [comment]
@antonmedv have the possibility to use git tag name sounds like a good idea, for branch deploy maybe the short commit hash could be used.

**Comment by alexeightsix** [comment]
We have it working on our setup. not sure if this is what you wanted but thought I would share.

We have a higher level script that we fire off from our CI which kicks off the process:

`set -o pipefail

if ! test -z "$1"
then
    revision=--revision=$1
fi

bash build/build && \
docker run -i \
--volume $(pwd)/deployments/xxx-xxx-app/deploy.php:/project/deploy.php \
--volume $(pwd)/deployments/xxx-xxx-app/hosts.yml:/project/hosts.yml \
--rm xxx/deployer:latest \
deploy prod --timestamp="$(date +%s)" --hosts aow-scms-app-1 $revision --parallel -vv \
|& tee logs/xxx-xxx-app-$(date +%s).log`


We then define the release_name like so:


`
set('release_name', function () {
    if (input()->hasOption('timestamp') && !empty(input()->getOption('timestamp'))) {
        return input()->getOption('timestamp');
    } else {
        return time();
    }
});`

**Comment by alexander-schranz** [comment]
@alexeightsix thanks didn't know that there is a `release_name` option. @antonmedv seems like its missing in the [docs](https://deployer.org/docs/configuration.html).

**Comment by antonmedv** [comment]
Yes, now I'm working on autogenerating docs from code.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
