### ISSUE TITLE
Run tasks on the same host in parallel 

### ISSUE THREAD

**Issue by alexeightsix** [deployphp/deployer#2141]
Our deployments are taking longer and longer as we add more pipelines. Is it possible to run multiple tasks at once on the same host?

**Comment by antonmedv** [comment]
Currently only one task per host. But you can start a view parallel pipelines.

**Comment by alexeightsix** [comment]
> Currently only one task per host. But you can start a view parallel pipelines.

what do you mean?

**Comment by antonmedv** [comment]
Start a few processes of deploy.

**Comment by alexeightsix** [comment]
> Start a few processes of deploy.

i still don't understand your response, can you provide an example on how this would be done?

**Comment by antonmedv** [comment]
Just start a few bash scripts

**Comment by alexeightsix** [comment]
Got it, thanks!
