### ISSUE TITLE
Implement host selector

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2154]
I'm looking for somebody to develop "host selector" feature. 

Idea:
- A host can have few labels: `['stage' => 'prod', 'role' => 'db', 'tier' => 'df.2']`
- User "selects" on which hosts to run a deploy: `dep deploy 'stage=prod'`
- Or can define custom selectors in code `selector('prod', 'stage=prod AND (role=db OR role=app)')` `dep deploy prod`
- Also default selector can be defined.
- Selector features: `label=value`, `and/or`, brackets `(...)`. Maybe also regexp `label~=^v.+?`

Code points:
- https://github.com/deployphp/deployer/blob/master/src/Selector/Selector.php#L41-L56

**Comment by antonmedv** [comment]
Did myself ┬─┬ノ( º _ ºノ)

**Comment by kanevbg** [comment]
Is this allowing to run deployment to given stage which is linked to multiple servers while specific which server to run at from the CLI. Eg, if I have host definition like this:

> host('55.55.55.[98:100]/stage') # https://deployer.org/docs/hosts.html#host-aliases
->user('username')->port(22)
    ->stage('stage')
    ->set('deploy_location_name', 'Custom deployment name')
    ->set('branch', 'development')
    ->set('deploy_path', '~/deps');

Can I run it only on single node like:
`dep deploy stage --hosts 55.55.55.98`

**Comment by antonmedv** [comment]
In process of writing docs on it.

**Comment by CodeNinjaUG** [comment]
Was this error worked upon .. i cant seem to find a solution for the deployer 
host('example.com')
    ->setHostname('127.0.123.23')
    ->setRemoteUser('root')
    ->set('stage','production')
    ->setDeployPath( '/var/www/html/yotta-api');

**Comment by Schrank** [comment]
Hi @CodeNinjaUG, thanks for your comment! But unfortuantely I have no clue what you are talking about 🙈 

- What did you try?
- What did you expect?
- What happened instead?

Happy to help! _Maybe_ it makes sense to open another issue!
