### ISSUE TITLE
Can't access variables when using invoke

### ISSUE THREAD

**Issue by alexeightsix** [deployphp/deployer#2157]
I'm trying to run tasks like this:

```
task('deploy', function() {
    invoke("deploy:start-timer");
    invoke("deploy:stop-timer");
});
```

The first task defines a variable, the 2nd task needs to access it but I'm getting this error:

```
In Configuration.php line 74:
                                  
  [Deployer\Exception\ConfigurationException]           
  Configuration parameter `start-time` does not exist.  
                                                        
```

Thanks

**Comment by antonmedv** [comment]
Why not just call php function? startTimer()/stopTimer()?

**Comment by alexeightsix** [comment]
i just used those tasks as examples but we'll have other tasks that we would use in the same matter. We've been playing around with this library: https://github.com/amphp/parallel and ideally would like to implement the library so we can run tasks async. Do you think this would be possible or do you have a better way? We tried a few quick tests and we had issues with the context.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
