### ISSUE TITLE
Deployer under proxy

### ISSUE THREAD

**Issue by brunowego** [deployphp/deployer#216]
Will be nicer if this package supports proxy settings :+1:

**Comment by elfet** [comment]
Like what? Please show an example and more details.

**Comment by brunowego** [comment]
@elfet I try use deployer under proxy network, but not work, return a message to configure proxy in deployer.

**Comment by pilotftzi** [comment]
How can I connect to server where he is via 3rd ssh connects with Deployer?

Server1(loaclhost)->Server2->Server3(deployment server)

Thanks.

**Comment by elfet** [comment]
You can use VPN tunnel.

**Comment by gordalina** [comment]
Actually a simple solution would be to create an ssh tunnel from server1 to server2 (one simple ssh command), which provides socks4 & 5, and then operate on server 2 to server 3.

**Comment by brunowego** [comment]
Thanks @pilotftzi @gordalina @elfet :+1:
