### ISSUE TITLE
[Enhancement] Make deploy:check_remote more specific as to which host is up-to-date

### ISSUE THREAD

**Issue by bsacharski** [deployphp/deployer#2160]
When using the `deploy:check_remote` step, to prevent multiple releases of the same revision, the current output simply says:
```
➤ Executing task deploy:check_remote

In check_remote.php line 57:
                       
  Already up-to-date.  
```
After showing that message, the deploy procedure is being stopped.

This can be too vague in a situation where stage has multiple hosts - deployer does not convey any information about the host that is up-to-date. I can imagine a scenario, where for some reason, one of the hosts is on newest deployment and the rest isn't. Having some sort of information about which host to skip would be beneficial here.

I would propose to include host information in the "is up-to-date" message, for instance:
```
   YOUR-HOST (your.host.domain) is already up-to-date
```
where `YOUR-HOST` is a _host_ and `your.host.domain` is a _hostname_.

Alternatively, the `deploy:check_remote` could mark specific host as being up-to-date and would skip next steps for this configuration. Deploy for other hosts would still continue. I don't know however if this is currently possible to implement, without major overhaul.

**Comment by antonmedv** [comment]
Done.
