### ISSUE TITLE
Please release 6.9.0

### ISSUE THREAD

**Issue by oliverklee** [deployphp/deployer#2164]
Dear Deployer team, in one of our projects, we're using Symfony 5 and would like to use the Symfony 5 recipe. A release of Deployer 6.9.0 (with the Symfony 5 recipe) would be very much appreciated. Thanks! :heart:

**Comment by antonmedv** [comment]
Soon v7 will be ready.

**Comment by oliverklee** [comment]
Thanks! :heart:

**Comment by inverse** [comment]
It's coming https://github.com/deployphp/deployer/releases/tag/v7.0.0-beta.1
