### ISSUE TITLE
Use $options env overwirte default env config in run() and runLocally() function

### ISSUE THREAD

**Issue by demokn** [deployphp/deployer#2165]
Usually, remote server's env variables is different from localhost.
When set `env` for remote host, `runLocally()` will use the same `env`.
I want to use the second param `$options` to overwrite the default `env` setting for remote host.
While, the fact is `$options`'s priority is lower than default setting.

Current codes:
```php
$env = get('env', []) + ($options['env'] ?? []);
```

Solution:
```php
$env = array_merge_alternate(get('env', []), $options['env'] ?? []);
```

**Comment by antonmedv** [comment]
Can you make PR with test for it?
