### ISSUE TITLE
To support rollback function only?

### ISSUE THREAD

**Issue by hezll** [deployphp/deployer#2171]
**Is your feature request related to a problem? Please describe.**
We want use Jenkins UI and deployer together  to deploy our system.

**Describe the solution you'd like**
We use deployer before, this is a good tool and everyone like it. But it looks like only support git pull code from itself.

**Describe alternatives you've considered**
Hope we can utilize Jenkins to pull and build the code, push the code to a local server, then we can use deployer to deploy. 
Then deployer can help us build up the rollback function.

**Additional context**
None.

**Comment by antonmedv** [comment]
It's possible. Just write your own recipe using tasks as code blocks. Add your own tasks as needed.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
