### ISSUE TITLE
if a git submodule is not available the deployment fails

### ISSUE THREAD

**Issue by flobee** [deployphp/deployer#2173]
**Is your feature request related to a problem? Please describe.**

my core application loads several git submodules in the deployent process. Submodules are additional features (in this senario)
One of them coulnd fetch the submodule because of missing credetials (ssh key in this case)

'-vvv' was the only option without using the log to find the reason of the error. 
Actually this should be an direkt error for level '-v'

**Comment by antonmedv** [comment]
Can you send pr to fix it?

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
