### ISSUE TITLE
Host::__toString user variable substitution

### ISSUE THREAD

**Issue by Mararok** [deployphp/deployer#2174]
I forked code from branch 6.x and fixed it but that branch isn't include last version 6.8.0 and master is changed too much for it now :(

My changes here: 
https://github.com/deployphp/deployer/compare/6.x...Mararok:unify-getting-user-in-host

**Describe the bug**
Host::__toString() using plain user value

**To reproduce**
Create config with 
```php
set("deploy_user", function () {
    return "test_user";
});

host("test")
    ->hostname("x.x.x.x")
    ->user('{{deploy_user}}')
```
Deployer will try connect to deploy_user@x.x.x.x

**Expected behavior**
Deployer will try connect to test_user@x.x.x.x

**Environment**
* Deployer version: 6.8.0
* PHP version: 7.4.3

**Comment by antonmedv** [comment]
I've added a test case. Now it's fixed in master. 
fb66dc3dba60a68642839c91d92842e6083a7f8e

**Comment by Mararok** [comment]
Thx :), I saw current master code before and it's better for use substitution, but now I must wait for 7.0. It isn't problem I can still change my deployment user manually in code. I hope new version will be soon released :)
