### ISSUE TITLE
within() should pass thru the $callback return

### ISSUE THREAD

**Issue by WindBridges** [deployphp/deployer#2178]
**Is your feature request related to a problem? Please describe.**
Currently it's unable to wrap run('command') call into within() helper and get command output back.

**Describe the solution you'd like**
The return of $callback() must be returned as result of within().

**Describe alternatives you've considered**
Current solution is just copy/paste the within() sources into client code and replace $callback to `$output = run('command');`

**Comment by bsacharski** [comment]
You could always use closure with reference passed to the functions body:

```php
task('i2178', function () {
    within('/tmp', function () use (& $output) {;
        $output = runLocally('ls -la');
    });

    writeln("The ls for /tmp is:");
    writeln($output);
});
```

**Comment by bsacharski** [comment]
After having some thoughts, I think it would actually be nice for the `within()` to return whatever is the result of the callback.
This would definitely make things like:

```php
$foo = within('/tmp', [ $this, 'bar' ]);
```

easier to write, than to use closures and to pass references.

If @antonmedv is fine with that, I could modify the code, add some unit tests and make a PR.

**Comment by antonmedv** [comment]
Yes, go ahead. 👍
