### ISSUE TITLE
Add type declarations to the methods

### ISSUE THREAD

**Issue by bsacharski** [deployphp/deployer#2187]
To improve the quality of code, the methods and functions should use type declarations to define what types of arguments are accepted and what types of values are being returned.

Native type declarations should be used where possible with the fallback to comment-based annotations.

TODO:

- [x] `src/Collection/`
- [x] `src/Component/`
- [x] `src/Configuration/`
- [ ] `src/Console/`
- [x] `src/Documentation/`
- [x] `src/Exception/`
- [x] `src/Executor/`
- [x] `src/Host/`
- [x] `src/Logger/`
- [ ] `src/Selector/`
- [ ] `src/Support/`
- [x] `src/Task/`
- [x] `src/Utility/`
- [ ] `src/Deployer.php`
- [x] `src/functions.php`

**Comment by antonmedv** [comment]
What about adding all files to phpcs lint but with weaker checks? And steady move them to more strict grouping?

This way we can be sure new files will not be missed.

**Comment by bsacharski** [comment]
Type hints in `functions.php` added in https://github.com/deployphp/deployer/pull/2210

**Comment by antonmedv** [comment]
ping @bsacharski 
Should we wait for everything is done bore final release v7?

**Comment by bsacharski** [comment]
@antonmedv nah, I think it's a thing that's nice to have, but I don't think it should impact release ;)
To be honest, I don't have that much time to work on this at the moment (as there were little to no commits from my side) and I don't want to imact the release in any way.

**Comment by antonmedv** [comment]
Only a few left. Will add it myself.
