### ISSUE TITLE
Error when executing deployer.phar

### ISSUE THREAD

**Issue by DaLt0n** [deployphp/deployer#2190]
The latest versions of deployer.phar are not working: 6.8.0, 6.7.3, 6.7.2, 6.7.1

Error:
`PHP Parse error:  syntax error, unexpected '?' in phar:///root/deployer.phar/vendor/symfony/console/Terminal.php on line 127`

Tested ok: 6.7.0

**Comment by antonmedv** [comment]
What php version?

**Comment by antonmedv** [comment]
Unconfirmed.

**Comment by DaLt0n** [comment]
> What php version?

php 7.0.33

**Comment by antonmedv** [comment]
Upgrade.

**Comment by DaLt0n** [comment]
I understand but not every project can be updated at the same time thats not the correct answer. If a new version of php is needed for the deployer it should be mentioned like codeception does (example: https://codeception.com/install).
Best regards.

**Comment by antonmedv** [comment]
Now there’s more accurate check for php ver. Will show error.  Thanks for regards 😁
