### ISSUE TITLE
Detecting vendor/bin/dep

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2199]
Currently Deployer can detect autoload.php file:
https://github.com/deployphp/deployer/blob/master/bin/dep#L63-L67

We need to be able also to detect `vendor/bin/dep` files and execute them instead. 

Who wants to implement it?

**Comment by akshay-kh** [comment]
@antonmedv i am interested in implementing this feature but i would like to know little more about this feature.

**Comment by antonmedv** [comment]
Sure! Here is the deal:
- Deployer can be installed globally to have simple access to `dep` command, be able to run `dep init` in my project, etc.
- Project may have Deployer as a dependency with another version.
- We want in the project dir run global dep command, which should start local dep command if it is available.

Let's imagine we have Deployer globally installed, now some project may have Deployer installed in the next ways:
- Via `composer require deployer/deployer`
  - So we have Deployer files in the _vendor_ directory.
  - Currently `dep` correctly detects this and uses local Deployer instead of global. 
    This is done by this part of code: [bin/dep#L70-L92](https://github.com/deployphp/deployer/blob/master/bin/dep#L70-L92).
- Via `composer require deployer/distribution`
  - Phar archive will be downloaded and located in `vendor/bin/dep`.
  - Not supported at this point. <-- The issue about this part.
- Via downloading phar from site and placing in repo root as `bin/dep` or `deployer.org`.
  - Not supported at this point. <-- The issue about this part.


How to implement this feature:
- First, create tests for all cases (even older phar archives may be downloaded and committed to repo tests).
- Try to implement redirect of call for 2, 3 cases.
  - If during implementation some _eureka!_ moments appeared, or a better solution found, feel free to refactor everything related.

Feel free to ask any questions before and during implementation.

**Comment by akshay-kh** [comment]
@antonmedv thanks for the explanation in detail,

> *  Via composer require deployer/deployer

     This is related with this repository right https://github.com/deployphp/distribution

**Comment by antonmedv** [comment]
Yes distribution phar is there.

**Comment by antonmedv** [comment]
Looking for a contributor!
