### ISSUE TITLE
Conditionally enable/disable maintenance mode in Magento2 recipe

### ISSUE THREAD

**Issue by andyexeter** [deployphp/deployer#2202]
This Capistrano Magento2 gem has some smart maintenance mode handling which Deployer could take inspiration from:

https://github.com/davidalger/capistrano-magento2/blob/3d32c7d654bd9221f67e20c27fc4e62503bdd73d/lib/capistrano/tasks/magento.rake#L384-L466

As well as resolving #1379, this would enable zero-down deploys when the database schema/data and app config does not require an update.

I am happy to look at providing a PR for this feature when I get some time.

**Comment by peterjaap** [comment]
This feature is the biggest reason why [Magento 2 Deployer Plus](https://github.com/jalogut/magento2-deployer-plus) exists. I'm not sure whether it's a good idea to start copying that project, since it uses Deployer as the basis. I would be more in favor of keeping this recipe simple and straight forward, and let people with advanced use-cases use Magento 2 Deployer Plus on top of Deployer.

**Comment by andyexeter** [comment]
Interesting, I didn't know that existed.

I don't agree with the notion that Deployer should be intentionally deprived of a general enhancement just because a third party has made a recipe providing equivalent functionality. I also don't agree that this is an "advanced use-case". Surely 100% of users would prefer a zero-down deploy if it is possible.

For these reasons, I believe this does belong in Deployer.

**Comment by antonmedv** [comment]
> Surely 100% of users would prefer a zero-down deploy if it is possible.

I also agree with @andyexeter.

Let's try to incorporate  Magento 2 Deployer Plus into Deployer recipes @peterjaap?  As soon v7 will be ready, it also will be really awesome to copy/paste such wonderful recipe from @jalogut.

Can we do it @jalogut @peterjaap @andyexeter @Schrank ?

**Comment by Schrank** [comment]
I don't do much M2 lately and especially no deployer with it. But I think having more functionality is good. Maybe we add a configuration option to turn it off/on so it is OFF by default?

**Comment by antonmedv** [comment]
I'm actually thinking of just implementing a more advanced recipe. Better to provide users the best functionality out of the box.

**Comment by Schrank** [comment]
Agree. I didn't read the Capistrano implementation, but I think it is a good way. My fear is, that it breaks with translations, not sure the CLI is translated. So maybe it is a good idea to provide a PR on magento2 to make sure, that we get a machine readable format.

👍  from my side.

**Comment by antonmedv** [comment]
@peterjaap what do you think?

**Comment by antonmedv** [comment]
@peterjaap so, I'd like to implement it. Or you have some other thoughts?

**Comment by antonmedv** [comment]
Ping @peterjaap

**Comment by antonmedv** [comment]
Ping @peterjaap 😄

**Comment by peterjaap** [comment]
Agreed. In general a good idea, we're discussing implementation details over here -> ou als m'n zus enthousiast is dan zit het wel goed :joy:





10:31
En als zij het duurt vindt al helemaal! (edited)

**Comment by antonmedv** [comment]
Fixed in #2262. Right, @peterjaap?
