### ISSUE TITLE
Downloads broken

### ISSUE THREAD

**Issue by timkley** [deployphp/deployer#2204]
### Describe the bug

It seems like all downloads on https://deployer.org/download/ are currently broken it seems.
Newest release and 6.8. are throwing a 404:

https://deployer.org/releases/v6.8.0/deployer.phar

### To reproduce

Try downloading https://deployer.org/releases/v6.8.0/deployer.phar
Get 404

### Expected behavior

Download should work ;)

**Comment by chosroes** [comment]
All the deployer website is in 404

**Comment by kierenevans** [comment]
https://github.com/deployphp/distribution/tree/v6.8.0 has a file called `dep` which seems to be the PHAR archive. The SHA1 matches.

**Comment by antonmedv** [comment]
Problems with new releases. Calling:
```
dep rollback
```
Now everything should work.
