### ISSUE TITLE
shared folder file copying is too verbose

### ISSUE THREAD

**Issue by Gamesh** [deployphp/deployer#2209]
### Describe the bug
When shared folders in release contain lots of files, each and everyone of them is listed then copying. Which causes lots of spam output. In severe cases when lots of output fails GitLab CI builds because it's exceeds 4194304 bytes, which GitLab can handle: 
> Job's log exceeded limit of 4194304 bytes.

### To reproduce
1. create a release with a shared folder that has thousands of files
2. set that folder as shared in deployer
3. release

### Expected behavior
1. should specify only a folder that is getting copied.

### Environment
- Deployer version: 6.8.0
- PHP version: 7.3
- Deployment target(s) OS: Debian stretch

**Comment by Gamesh** [comment]
this line is the culprit https://github.com/deployphp/deployer/blob/112601294c3c76273322ecc4e5f995e34f27b6f6/recipe/deploy/shared.php#L29
can we remove the `-v` ? 
or maybe make it depend on deplyer verbosity level say `-vvv` would use `cp -v` ?

**Comment by antonmedv** [comment]
I think -v for -vvv is okay. Can you make PR?

**Comment by Gamesh** [comment]
yes. how can i get verbosity level inside the task?

**Comment by antonmedv** [comment]
output()->getVerbosity()
