### ISSUE TITLE
"arguments" not included in distributed phar?

### ISSUE THREAD

**Issue by EkAndreas** [deployphp/deployer#222]
When downloading the version 3 beta 5 and using recipe "common.php" the argument-functions is missing.
If I clone and build the v3b5 everything is ok with the "argument" function.

**Comment by elfet** [comment]
`argument` function available only on master branch now. Wait for release please or use master branch :smile:

**Comment by EkAndreas** [comment]
ok, lets see if I understand this. So the v3b5 is not including "arguments"? Is the beta some kind of reduced version of what will be released?

**Comment by elfet** [comment]
Not all functions included in beta, them are not ready now.
