### ISSUE TITLE
Add check-platform-reqs option for composer install?

### ISSUE THREAD

**Issue by jamieburchell** [deployphp/deployer#2233]
As per blog post here:

https://blog.packagist.com/composer-2-0-is-now-available/

> To avoid issues when deploying to production it is recommended to run `composer check-platform-reqs --no-dev` with the production PHP process as part of your build or deployment process.

I think this would only apply to composer 2 though :/

**Comment by jamieburchell** [comment]
Ah, just realised this can be specified in https://deployer.org/docs/configuration.html#composer_options

**Comment by lidoma** [comment]
@jamieburchell Please provide sample configuration codes.

**Comment by jamieburchell** [comment]
> @jamieburchell Please provide sample configuration codes.

The default composer options are here:

https://github.com/deployphp/deployer/blob/22e2e07f7afd1d596f831c55df5925c95305ae6f/recipe/deploy/vendors.php#L7

But looking at this again, I've made a mistake. `check-platform-reqs` is of course a composer command and not an option/parameter.

If you need to run `composer check-platform-reqs --no-dev` I think you'd need to create your own task and hook it in to run before the vendors task.

Not sure if this should be part of the built in task. Reopening.

**Comment by antonmedv** [comment]
Let’s add this to vendors recipe. Will do it.

**Comment by antonmedv** [comment]
After thinking, this should not go to deploy recipe. No need to check it every single time. It's possible to do it just after provisioning:
```bash
dep run -c 'composer check-platform-reqs --no-dev'
```
