### ISSUE TITLE
Notice : Undefined index : name on ...vendor\deployer\deployer\bin\dep on line 111 

### ISSUE THREAD

**Issue by fvsadem** [deployphp/deployer#2237]
### Describe the bug

It seems there is a notice when i deploy my project :
``Undefined index:name on vendor\deployer\deployer\bin\dep on line 111 ``

I don't know if there is an impact !

### To reproduce

``dep deploy``

I have just updated composer to version 2...

### Environment
- Deployer version: 6.7.1
- PHP version: 7.1.9
- Deployment target(s) OS: debian

**Comment by antonmedv** [comment]
Can’t reproduce.

**Comment by dbalabka** [comment]
@antonmedv same problem appears. It seems it is somehow related to Composer v2.

**Comment by dbalabka** [comment]
@antonmedv, @fvsadem it is fixed in `v6.8.0`:
https://github.com/deployphp/deployer/blob/6d486c84cd384ee3951186c4c9eb39f61f02aa22/CHANGELOG.md#v680
