### ISSUE TITLE
Slack recipe is missing "target" option

### ISSUE THREAD

**Issue by martijngastkemper** [deployphp/deployer#2238]
### Describe the bug
`contrib/slack.php` uses `{{ target }}`, but that option doesn't exists:

![Screenshot 2020-10-27 at 11 31 53](https://user-images.githubusercontent.com/250662/97289846-070df800-1848-11eb-9ea1-4d75a726ff92.png)

### To reproduce

Just follow the docs to add a basic Slack notification. But below the lines I've added to `deploy.php`:
```
require 'contrib/slack.php';
set(
    'slack_webhook',
    '....'
);
after('deploy:failed', 'slack:notify:failure');
```

### Expected behavior

I would expect the target option to exists or information in the docs.

### Environment
- Deployer version: `v7.0.0-beta.2`
- PHP version: `7.4.10`
- Deployment target(s) OS: `Linux`

**Comment by antonmedv** [comment]
Who wants to write PR to fix it?))

**Comment by carstendietrich** [comment]
> Who wants to write PR to fix it?))

I will take a look and provide a PR if I'm able to fix 😁

**Comment by martijngastkemper** [comment]
I thought the target option must have been some internal option, because it's so widely used. But just defining is sufficient. @carstendietrich Many thanks for your PR.

**Comment by antonmedv** [comment]
Fixed.
