### ISSUE TITLE
run() timeout does not abort a ssh command

### ISSUE THREAD

**Issue by Gamesh** [deployphp/deployer#2263]
### Describe the bug
When deployer sends a command over ssh it sets a timeout that is either passed by options `timeout` or `default_timeout` is used. This timeout then is set on symfony Process component command. 
I observed a weird behavior: when a remote process was executed over ssh, what was supposed to do a database migration by invoking a java tool called Liquibase. After a set timeout expired deployer aborted the deployment but the java migration continued to run on the server. 
So it seems the process was not aborted, it only times out deployer execution.
Another minor issue form the output it's not clear what happened, there is no message saying "task/command timed out"

### To reproduce
execute `sleep 30` using `run()` on remote server with timeout of **5**
task will crash with error:
```
Exit Code: -1 (Unknown error)   
```

### Expected behavior
command is aborted after timeout and a message displayed:
```
Timeout of 300 running task "db:migrate" executing command "<run command name>" reached.
```

### Environment
- Deployer version: 6.8
- PHP version: 7.3
- Deployment target(s) OS: Debian

Not sure if it's supposed to work like that from the symfony process component perspective, maybe we should handle this case on our side?
Image where this could cause problems, when after failure we unlock the deployment and try again and a migration or other long running process then executes slowing down the server even more (if such command does not use locking to handle concurrent runs)
maybe adding `timeout X` bash command could solve the problem, but not very portable.
Also process component now supports `setIdleTimeout` which works more like a php max execution timeout, and times out only if no output was received within specified time, maybe it would make more sense to use this instead. As the migration was constantly sending output.

**Comment by antonmedv** [comment]
Yes, I can confirm what timeout does not abort `run()` command. This is strange. I fought it is dues to live connection in multiplexing, but with turned multiplexing off it's still is running. Odd.

`run()` also supports `idle_timeout` option.

**Comment by antonmedv** [comment]
As a workaround:
```php
run('sleep 5 & sleep 2; kill %1');
```

**Comment by Gamesh** [comment]
what if we catch the TimeoutException and then check if process is still alive and if it is send sigterm? so handle it on deployer side

**Comment by Gamesh** [comment]
> run() also supports idle_timeout option.

ah, it's not documented https://deployer.org/docs/api.html#run, i must have missed it in the code

**Comment by antonmedv** [comment]
Fixed in https://github.com/deployphp/deployer

**Comment by antonmedv** [comment]
For example:
```php
task('test', function () {
    run('sleep 10 & sleep 20', ['timeout' => 1]);
});

task('check', function () {
    writeln(run('ps aux | grep [s]leep'));
});

fail('test', 'check');
```

**Comment by antonmedv** [comment]
OR with idle_timeout:
```php
task('test', function () {
    run('
    sleep 1;
    date;
    sleep 1;
    date;
    sleep 1;
    date;
    sleep 1;
    date;
    sleep 1;
    date;
    sleep 5;
    echo "hmmm?";
    ', ['idle_timeout' => 2]);
});

task('check', function () {
    writeln(run('ps aux | grep [s]leep'));
});

fail('test', 'check');
```

**Comment by Gamesh** [comment]
@antonmedv nice, thanks for a quick fix. Do you think we should try with SIGTERM instead of sigkill so that process can gracefully finish up what it's doing?

**Comment by antonmedv** [comment]
Hmm, I thought about this. But this is timeout, what if the process unresponsive? I think SIGKILL better in this case. Can if graceful timeout is needed, I think this is better to solve on user side. Maybe some examples of how to do it in docs.

**Comment by Gamesh** [comment]
true, didn't think about unresponsive process 👍
