### ISSUE TITLE
Uninitialized "output" in Deployer container.

### ISSUE THREAD

**Issue by flo-sch** [deployphp/deployer#2268]
### Describe the bug

Invoking `runLocally()` on v7 with the default config (after running `php vendor/bin/dep init` and selecting `symfony` as recipe) causes a RuntimeException:

>  RuntimeException  in Deployer.php on line 103:
>
>  Uninitialized "output" in Deployer container.

According to the source code of that file, this is the default "output" on v7, so I guess I am missing some configuration about the output?)

I am currently using runLocally as input for the `sentry` recipe (see below).
Other examples of use-case include (from within a task):

- `runLocally('yarn run build')`
- `runLocally("rsync -rvxz -e 'ssh$port$identityFile' public/build/ $user$host:{{release_path}}/public/build/")`, not sure if I can switch to `upload()` for that perhaps?

### To reproduce

1. Create a fresh install (`dep init`) using Deployer v7.0.0-beta.3

2. Setup the sentry recipe invoking `runLocally`

```php
set('sentry', [
    'organization'  => 'my-org',
    'projects'      => ['my-project'],
    'token'         => '{token}',
    'version'       => runLocally('git log -n 1 --format="%h"')
]);
```

### Expected behavior

No RuntimeException is thrown

### Environment
- Deployer version: 7.0.0-beta.3
- PHP version: 7.4
- Deployment target(s) OS: OS X

**Comment by antonmedv** [comment]
Yes , runLocally meant to be run only in tasks. Use exec here instead if back qoures.

**Comment by flo-sch** [comment]
Perfect, thanks :)

Really looking forward this v7 since I cannot make v6.* work any more (issues related to Pimple)
