### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by yguedidi** [deployphp/deployer#227]

**Comment by elfet** [comment]
Yeah, i'm hosting on Linode, and my VPS falls under high load.

**Comment by elfet** [comment]
Must be online now.

**Comment by yguedidi** [comment]
It's not, I'm from France, and with Chrome I got this error: ERR_EMPTY_RESPONSE

**Comment by GrahamCampbell** [comment]
It's really slow for me in the UK too, but is working.

**Comment by yguedidi** [comment]
It doesn't work for me at all, even if I refresh several time

**Comment by elfet** [comment]
Solved. Was a problem with ipv6 nginx config. :smile:

**Comment by yguedidi** [comment]
:+1:
