### ISSUE TITLE
Error in cachetool.php on line 57

### ISSUE THREAD

**Issue by chriswalg** [deployphp/deployer#2275]
### Describe the bug

```
task cachetool:clear:opcache
[beta]  error  in cachetool.php on line 57:
[beta] run command -v 'cachetool.phar' || which 'cachetool.phar' || type -p 'cachetool.phar'
[beta] exit code 1 (General error)
```

https://gitlab.com/foodsharing-dev/foodsharing/-/jobs/835344131

Behavior is also after I installed cachetool via composer.json. Also downloaded the cachetool in bin and contrib and got the same error message.

I thought cachetool is downloaded in https://github.com/deployphp/deployer/blob/master/contrib/cachetool.php#L60

### To reproduce

- Git clone...
- cd deployer && composer install
- deployer/vendor/bin/dep deploy $CI_ENVIRONMENT_NAME --revision $CI_COMMIT_SHA

### Environment
- Deployer version: 7.0.0.beta4
- PHP version: 7.4.11
- CI-Image: https://gitlab.com/foodsharing-dev/images/-/blob/master/ci/Dockerfile
- Gitlab Deploy Config: https://gitlab.com/foodsharing-dev/foodsharing/-/blob/master/.gitlab-ci.yml
- Config: https://gitlab.com/foodsharing-dev/foodsharing/-/blob/master/deploy.php
- Composer files: https://gitlab.com/foodsharing-dev/foodsharing/-/tree/master/deployer
- Deployment target(s) OS: debian buster

**Comment by antonmedv** [comment]
Can you create PR to fix it?

**Comment by chriswalg** [comment]
> Can you create PR to fix it?

I don't know the cause. I'm a beginner in programming.
