### ISSUE TITLE
chmod (8.30) and setfacl (2.2.52) error when using default writable_mode=acl and using group value as http_user

### ISSUE THREAD

**Issue by arderyp** [deployphp/deployer#2279]
### Describe the bug
default `writable_mode=acl` causes errors:

```
[HOST] > cd /ROOT/releases/1 && (chmod 2>&1; true)
[HOST] < chmod: missing operand
[HOST] < Try 'chmod --help' for more information.
[HOST] > cd /ROOT/releases/1 && (if hash setfacl 2>/dev/null; then echo 'true'; fi)
[HOST] < true
[HOST] > cd /ROOT/releases/1 && (getfacl -p var | grep "^user:webmaster:.*w" | wc -l)
[HOST] > cd /ROOT/releases/1 && (setfacl -L -R -m u:"webmaster":rwX -m u:`whoami`:rwX var)
[HOST] < [error] setfacl: Option -m: Invalid argument near character 3
[Deployer\Exception\RuntimeException] The command "cd /ROOT/releases/1 && (setfacl -L -R -m u:"webmaster":rwX -m u:`whoami`:rwX var)" failed.
```
chmod error: https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php#L82
setfacl error: https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php#L102

### To reproduce
I'm using CentOS 8 (chmod=8.30 setfacl=2.2.53).  The error doesn't occur on CentOS 6 (chmod=8.22 setfacl=2.2.51).

### Environment
- Deployer version: 6.8.0
- PHP version: 7.4.12
- Deployment target(s) OS: CentOS 8
- Deployment target(s) chmod: 8.30
- Deployment target(s) setfacl: 2.2.53

**Comment by antonmedv** [comment]
So what is changed in chmod or setfacl? How to fix it?

**Comment by arderyp** [comment]
I do not know.  I will look further if/when I get the time.

**Comment by arderyp** [comment]
```
[CENTOS7] $ mkdir test
[CENTOS7] $ setfacl -dR -m u:webmaster:rwX -m u:$(whoami):rwX test

[CENTOS8] $ mkdir test
[CENTOS8] $ setfacl -dR -m u:webmaster:rwX -m u:$(whoami):rwX test
setfacl: Option -m: Invalid argument near character 3
```
The `webmaster` is actually a group, not a user.  It looks like `setfacl` was updated to no longer allow `-m u:GROUP...` and now requires `-m u:USER...` or '-m g:GROUP...`

**Comment by antonmedv** [comment]
But what about http_user? If you set it to the correct one, does it working?

**Comment by arderyp** [comment]
this issue is about when you set `http_user` to a group instead of a user.  This used to work, but it appears `setfacl` no longer allows `u:GROUP` and instead requires `u:USER`

**Comment by antonmedv** [comment]
Does anybody want to send PR with a fix for it? 🐼

**Comment by antonmedv** [comment]
Okay, let’s close this bug for bookkeeping purposes. If somebody will get same error, let’s reopen it.
