### ISSUE TITLE
Deployment broken with Composer 2.0 release

### ISSUE THREAD

**Issue by AlexandreKilian** [deployphp/deployer#2282]
- Deployer version: 6.0.8
- Deployment OS: macOs 10.15.7 -> Debian 8

Ever since the release of composer 2, all my deployments fail on every server, multiple projects are affected… weirdly enough, manually doing a composer install on the server with composer 2 works without any problems. 
Also, composer is giving this issue when deploying with deployer
>  You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
a possibility to manually choose, which composer-version to use would help as a quick fix

**Comment by antonmedv** [comment]
Fixed in v7.
