### ISSUE TITLE
Call to undefined method Deployer\Host\Host::hostname() in beta 7.0

### ISSUE THREAD

**Issue by AlexandreKilian** [deployphp/deployer#2287]
- Deployer version: 7.0.0-beta5
- Deployment OS: macOs

when using the option `hostname`, following exception is thrown: `Call to undefined method Deployer\Host\Host::hostname()``
Must have gotten lost in the update, couldnt find any indices it had been renamed either.

**Comment by antonmedv** [comment]
Please read https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md#upgrade-from-6x-to-7x

**Comment by AlexandreKilian** [comment]
why is the config file beeing renamed with every version? 😅

**Comment by antonmedv** [comment]
¯\_(ツ)_/¯

**Comment by antonmedv** [comment]
When hosts() has different names?)

**Comment by AlexandreKilian** [comment]
According to the upgrade guide:
> Change real_hostname to hostname.
But hostname isn't defined 😅

**Comment by AlexandreKilian** [comment]
Also  `Call to undefined method Deployer\Host\Host::alias()`

**Comment by antonmedv** [comment]
Read https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md#upgrade-from-6x-to-7x one more time.
