### ISSUE TITLE
An example that includes using a Repository

### ISSUE THREAD

**Issue by ksidibe** [deployphp/deployer#229]
Can someone, please, provide an example of how to use Deployer to deploy to a server from a remote Git repo? I have gone through the documentation on the website. I understand the general principle of the tool but I still can't get going. Also, will it only update the files that need updating or will it write all the files from the repo to the server every time? Thanks.

**Comment by elfet** [comment]
Soon will be new docs with more examples.

**Comment by oanhnn** [comment]
Dear @ksidibe 
Until new documents is completed, you can refer to this [repo](https://github.com/oanhnn/deployer-example).

**Comment by ksidibe** [comment]
Thanks @elfet  and @oanhnn. @oanhnn , I'm checking out the repo you suggested. Thanks again.

**Comment by oanhnn** [comment]
Dear @ksidibe,
I have updated the README file for the more understandable and hopes it will help you.

**Comment by vanquang9387** [comment]
@ksidibe For using Deployer, follow these steps:
1. Clone this repo to <your_dir>
2. cd to <your_dir>
3. run
```
composer install
```
4. run
```
php ./build
```
This will create deployer.phar file.
5. Create deploy.php file in which you will set server, stage, repository, shared_dirs, etc, define additional tasks and main task. You can refer to [oanhnn's deploy.php file] (https://github.com/oanhnn/deployer-example/blob/master/deploy.php)
Have a look at [common recipe](https://github.com/deployphp/deployer/blob/master/recipe/common.php) to understand base tasks.
6. To exec a task, run
```
php deployer.phar <task> <defined stage name>
```
For example, to exec main "deploy" task on "dev" stage, run
```
php deployer.php -vvv deploy dev
```
-vvv is for debuging

**Comment by ksidibe** [comment]
@vanquang9387 Thanks a lot. You guys have been awesome. I'm currently going through the suggestions you guys have made. Thanks.

**Comment by vanquang9387** [comment]
Glad to be helpful :smile:

**Comment by elfet** [comment]
New docs are ready! Please help mу check them and finish them.
