### ISSUE TITLE
Spinner - integer overflow on 32-bit systems

### ISSUE THREAD

**Issue by xpablos** [deployphp/deployer#2291]
- Deployer version: 7.0.0-beta.5
- Deployment OS: Armbian 20.08

> dep deploy

fails with error

> In Master.php line 28:
>                         
>   Undefined offset: -5  
 
On 32-bit systems, integer range overflows when trying to calculate microtime(true)*10
https://github.com/deployphp/deployer/blob/master/src/Executor/Master.php#L28

**Comment by antonmedv** [comment]
Please, check what next code will solve it:
```diff
function spinner(string $message = ''): string
{
-    $frame = FRAMES[(int)(microtime(true) * 10) % count(FRAMES)];
+    $frame = FRAMES[(int)(microtime(true) * 10) % count(FRAMES)];
    return "  $frame $message\r";
}
```

**Comment by xpablos** [comment]
It seems working fine now. Great job!
