### ISSUE TITLE
Newest release 7.0.0-beta.8 seems to have broken the download from deployer.org

### ISSUE THREAD

**Issue by RoflCopter24** [deployphp/deployer#2292]
Just to let you know:
I just noticed the recommended path for installation from deployer.org `https://deployer.org/deployer.phar` returns a 404 error now.
It took me a while until I noticed that the files curl downloaded were empty 😀 
The manual download of a specific version works fine up to 7.0.0-beta.5 though!
![image](https://user-images.githubusercontent.com/8280334/99546375-a5f4c280-29b6-11eb-880d-d3bb801468f9.png)

**Comment by antonmedv** [comment]
Yes, did some refactoring and broke things. Will fix it.

**Comment by antonmedv** [comment]
Fixed.
