### ISSUE TITLE
npm:install throws error when package.json is changed

### ISSUE THREAD

**Issue by xpablos** [deployphp/deployer#2295]
- Deployer version: 7.0.0-beta.9
- Deployment OS: Ubuntu 20 LTS

When package.json is changed, error is thrown and deploy fails.

> task npm:install
> [localhost]  error  in npm.php on line 41:
> [localhost] run export ........; diff /var/www/example.com/releases/2/package.json /var/www/example.com/releases/3/package.json
> [localhost] 30c30
> [localhost] <     "laravel-mix": "^5.0.4",
> [localhost] ---
> [localhost] >     "laravel-mix": "^5.0.9",
> [localhost] exit code 1 (General error)
> task deploy:failed
>

**Comment by antonmedv** [comment]
This diff thing is completely unnecessary. Will remove it.

**Comment by xpablos** [comment]
It can probably make deploy process faster, if there are no changes in NPM packages.

I am using sha1sum for detecting changes at this moment. Not sure if there is some better solution.

> $shaRelease = run("sha1sum {{release_path}}/.env.example | cut -d ' ' -f 1");
> $shaPrevious = run("sha1sum {{previous_release}}/.env.example | cut -d ' ' -f 1");
> if ($shaRelease === $shaPrevious) {
>    .......
> }

**Comment by antonmedv** [comment]
Fixed in https://github.com/deployphp/deployer/releases/tag/v7.0.0-beta.10
