### ISSUE TITLE
"no tty present and no askpass program specified" exception with sudo in deploy:writable task

### ISSUE THREAD

**Issue by vanquang9387** [deployphp/deployer#231]
Hi,
I'm using username/password ssh
```
server(...)
    ->user('username', 'password')
```
and
```
set('writable_use_sudo', true); // Using sudo in writable commands?
```
And there was RuntimeException with sudo commands at deployment:
```
 [RuntimeException]
  sudo: no tty present and no askpass program specified
```
Is there a solution for this or passwordless sudo is a must?
Thank you.

**Comment by elfet** [comment]
Yes, now passwordless sudo is a must.

**Comment by vanquang9387** [comment]
Thanks @elfet

**Comment by oanhnn** [comment]
I think it would be unsafe when deploy user can change permission of directory and files without `sudo` password.

**Comment by naitsirch** [comment]
@oanhnn You can configure `sudo` to allow explicit commands and arguments to be executed without asking for a password. See https://stackoverflow.com/a/24107529/1119601
