### ISSUE TITLE
tty option of run() not work if a host is remote

### ISSUE THREAD

**Issue by TrueXakeP** [deployphp/deployer#2318]
I'm trying to provision a remote host and set mysql root password on it. Worried about the mysqladmin warning that `Using a password on the command line interface can be insecure`, I want to let him prompt for the password via tty. But there is no output or request in the console.
- Deployer version: 7.0.0-beta.11
- Deployment OS: Ubuntu 18.04.5 LTS
- $ php -v:
```
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

A minimal reproducible example of deploy.php:
```php
<?php

namespace Deployer;

host('localhost');

task('test_pass', function () {
    run('mysqladmin -u root password', ['tty' => true]);
});
```
Actual output:
```
$ dep test_pass
task test_pass
$ 
```
Verbose output:
```
$ dep test_pass -vvv
[localhost] /usr/bin/php7.4 /mnt/c/tools/openserver/userdata/composer/vendor/deployer/deployer/bin/dep connect --host localhost --decorated -vvv
[localhost] ssh -O check  -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/home/unix/.ssh/deployer_localhost echo 2>&1
[localhost] Master running (pid=4293)
task test_pass
[localhost] /usr/bin/php7.4 /mnt/c/tools/openserver/userdata/composer/vendor/deployer/deployer/bin/dep worker --task test_pass --host localhost --port 36811 --decorated -vvv
[localhost] ssh -O check  -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/home/unix/.ssh/deployer_localhost echo 2>&1
[localhost] Master running (pid=4293)
[localhost] ssh  -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/home/unix/.ssh/deployer_localhost localhost  ': 3b5ed80813a368c789dd; bash -ls; printf  $?;'
[localhost] run mysqladmin -u root password
[localhost] err New password: Confirm new password: Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
done on localhost
done test_pass 1s 641ms
```

Replacing the `host()` call to the `locahost()` or the `run()` to the `runLocally()` makes it look more like what I need:
```
$ dep test_pass
task test_pass
  ⠦ password:   ⠋
  ⠙ irm new password:   ⠦
Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
```
He actually waits and accepts a new password for input. But I need it on a remote host.

Also you can see an output corruption in last example as described in #1651. There should be `New password:` and `Confirm new password:`.

**Comment by antonmedv** [comment]
This is because remote hosts not support tty option now, as it considered dangerous and bad for automation.

**Comment by TrueXakeP** [comment]
OK I understood.
How do you propose to achieve my goal in this case? Just ignore the warning?

**Comment by antonmedv** [comment]
tty was removed as it will not work in parallel deploy to a few hosts. One possibility bring back tty, but neet to somehow mark tasks as sequential too. 
Also run() now has `secret` option:
```php
run('password %secret%', ['secret' => getenv('CI_SECRET')]);
```

**Comment by TrueXakeP** [comment]
Yes, for now I am using `mysqladmin -u root password '%secret%'`. But mysqladmin tells me it is insecure and it worries me.

**Comment by antonmedv** [comment]
It’s insecure if password are getting logged somewhere. For example in history. Or ci logs. Deployer has secrets specifically for this case.

**Comment by stenvdb** [comment]
I'm having a small similar issue that the text is getting truncated as mentioned here. This is something that could be improved.

**Comment by antonmedv** [comment]
So you are using tty?

**Comment by stenvdb** [comment]
Yes, I noticed that I have to use it to run a command inside a docker container that asks for something via a prompt. Everything works fine, but the messages are truncated as stated above.

**Comment by antonmedv** [comment]
Let’s close this one and open another one for truncated text.

**Comment by joelpittet** [comment]
We were using this feature to run `drush`, once during deployment, for when it has questions about importing config. Sometimes that allowed us to catch things that were changed in production and abort. Thought I'd drop a line about the use-case. We are changing some of our workflows.

https://github.com/ubc-cpsc/deployer-recipes/commit/ba392e2281225196a754a96c4c442922577ddc65
