### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by creakiwi** [deployphp/deployer#232]
Is there a way to make it work with private repos. I only found exemples using public repositories. I didn't tried it yet, but it seems that we can't pass public key or whatever like for "server" function.

**Comment by elfet** [comment]
You can use new forward agent functionality or add your servers keys to your repositories.

**Comment by creakiwi** [comment]
The fact is my repository know my server key (but the key contains a passphrase).

I use "dep deploy -vvv" on my local machine, the connection to my server is ok, but when cloning the repository, it fails "permission denied". So I manually did the git clone displayed with the "-vvv" option on my server, it asks for my key, and the clone is a success...

**Comment by oanhnn** [comment]
Dear @creakiwi 

I also met a problem as you, and I have to use features forward agent successful to solve that problem.

The first, you need to setup your system support forward agent.
On your local machine, content file `~/.ssh/config` : 
```
Host <your-server-ip>
  ForwardAgent yes
```
On your server, uncomment line `#AllowAgentForwarding yes` in file `/etc/ssh/sshd_config` to allow agent forwarding feature.
```
AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#X11Forwarding no
```
Reload sshd service on your server.
```shell
$ sudo service sshd restart
```
Test forward agent from your local machine.
```ssh
$ ssh-add /path/to/your-key-file
$ ssh <username>@<server_ip>
$ ssh-add -l
```
Check your key really loaded.
Finally, using `deployer` v3.0 and forward agent feature.
```php
server('your-server', 'xxx.xxx.xxx.xxx', 22)
    ->user('username')
    ->forwardAgent()
    ->stage(['dev'])
    ->env('deploy_path', '/var/www/apps/yourappname')
    ->env('branch', 'master')
```

Wish you success !!!
Refs:
https://developer.github.com/guides/using-ssh-agent-forwarding/
https://github.com/oanhnn/deployer-example

**Comment by alex-ception** [comment]
Thanks for you answer @oanhnn, I'll try that tonight. (I'm handling the @creakiwi account).
Your deployer-example repo seems to be a good start, thanks for your additional informations about ssh configuration.
