### ISSUE TITLE
Duplicate releases in status

### ISSUE THREAD

**Issue by patrickhoehn** [deployphp/deployer#2320]
- Deployer version: 7.0.0-beta.11
- Deployment OS:

I'm getting duplicate releases when running `dep status`.

<img width="522" alt="status" src="https://user-images.githubusercontent.com/17851700/100991160-fc373900-3552-11eb-8930-6f7133c186bc.png">

**Comment by antonmedv** [comment]
This is strange, as dates are different. Please show content of `cat .dep/releases` and `ls -lah releases/`.

**Comment by patrickhoehn** [comment]
Here you go:

<img width="288" alt="1" src="https://user-images.githubusercontent.com/17851700/100999449-170eab00-355d-11eb-8d7e-713e7c65a703.png">
<img width="342" alt="2" src="https://user-images.githubusercontent.com/17851700/100999456-183fd800-355d-11eb-9309-711b7a52622f.png">

**Comment by antonmedv** [comment]
Problem with duplicate lines in .dep/releases. What is your deploy.php file looks like? Can you run deploy with -v option?

**Comment by patrickhoehn** [comment]
On the server are just two releases left now (26 and 27) where should be 5. Is that because Deployer adds up the duplicates? What should I look for in -v? Here is my deploy.php:

```<?php
namespace Deployer;

require 'recipe/laravel.php';

// Project name
set('application', 'xyz');

// Project repository
set('repository', 'git@github.com:patrickhoehn/xyz.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

set('ssh_multiplexing', true);

// Shared files/dirs between deploys 
add('shared_files', [
    'public/.htaccess',
    'config/statamic/protect.php'
]);
/* add('shared_dirs', [
    'content',
    'public/assets'
]); */

set('writable_mode', 'chmod');

set('bin/php', function () {
    return '/usr/bin/php7.4-cli';
});

// Writable dirs by web server 
add('writable_dirs', []);

// http_user
set('http_user', 'u102339275');

// Hosts
host('xyz')
    ->set('remote_user', 'u102339275')
    ->set('identity_file', '~/.ssh/id_rsa')
    ->set('deploy_path', '/xyz');    
    
// Tasks
task('build', function () {
    run('composer install');
    run('npm install');
    run('npm run production');
})->local();

task('clear', function () {
    run('cd {{release_path}} && /usr/bin/php7.4-cli artisan cache:clear');
    run('cd {{release_path}} && rm -rf node_modules/');
});

task('upload', function () {
    upload(__DIR__ . "/", '{{release_path}}');
});

// TEST!

task('download', function () {
    download("{{deploy_path}}/shared/config", __DIR__ . "/test");
});

// TEST!

task('release', [
    'deploy:prepare',
    'deploy:release',
    'upload',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
]);

task('deploy', [
    'build',
    'release',
    'deploy:cleanup',
    'clear',
    'deploy:success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');```

**Comment by patrickhoehn** [comment]
Now I can't deploy anymore :( The first time I tried I got:
`Deployer\Exception\GracefulShutdownException  in lock.php on line 14: Deploy locked. Execute "deploy:unlock" task to unlock.`
Then I tried it again:
`In ClassLoader.php line 444:   include(phar:///usr/local/bin/dep/vendor/composer/../../src/Executor/Server.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/dep" (crc32 mismatch on file "src/Executor/Server.php")`
and when I run dep status the first time:
`ParseError  in Server.php on line 131: syntax error, unexpected '<', expecting end of file`
The second time:
`Error  in Deployer.php on line 160: Class 'Deployer\Executor\Server' not found`
And the third times it works again

**Comment by antonmedv** [comment]
This is really strange. Let's try to investigate what is going on. Try to unarchive phar and show the content of modified files. Your deploy.php looks all right, I use something similar, and my phar dep works just fine. 

Can you find a way to reproduce the problem?

**Comment by patrickhoehn** [comment]
I extracted the files. Which content exactly do you need? I could try to deploy it to another and fresh server directory and see if it happens again. It was running 6.8 before and had some deployments in this project, then I downloaded the v7 beta and installed it with `mv deployer.phar /usr/local/bin/dep
chmod +x /usr/local/bin/dep`, updated my deploy.php to work with v7 and then those issues occurred

**Comment by antonmedv** [comment]
Difficult to tell. I need your machine to debug))

**Comment by patrickhoehn** [comment]
I deleted the dep an reinstalled it and then deployed to a fresh directory on the server. The errors persist and I ended up with two release 1s with different time codes :/

**Comment by antonmedv** [comment]
Please, show output of dep deploy with `-v` option on. Can't tell what is wrong, I'm not a telepath :)

**Comment by patrickhoehn** [comment]
Sure, here it is:
[output.txt](https://github.com/deployphp/deployer/files/5641397/output.txt)

**Comment by antonmedv** [comment]
It’s already contains this release. 
run cd /kunden/homepages/15/d8447XXXXX/htdocs/sites/test && (tail -n 10 .dep/releases)
[domain.com] 20201203231109,1,Patrick Hoehn,master
[domain.com] 20201203231135,1,Patrick Hoehn,master
[domain.com] 20201204090344,2,Patrick Hoehn,master
[domain.com] 20201204090400,2,Patrick Hoehn,master

**Comment by antonmedv** [comment]
Create new deploy path, download new binary. And try again, record logs with -v. 
From current logs can’t tell why this is happening. 
Something wrong with your setup obviously, not deployer.

**Comment by patrickhoehn** [comment]
I deleted the binary, downloaded it again but then suddenly got git errors (publickey) in addition to the known ones. So for now I rolled back to 6.8 and it's working like it should again. All errors were about src/Executor/Server.php somehow.

**Comment by patrickhoehn** [comment]
Short update on a new project running on v7 beta 13: The issue with the duplicate releases in the status table persists but I get absolutely no errors and it's working as it should. The only thing I need to do is set 2x the value of releases I want to keep.
