### ISSUE TITLE
Package deployer/phar-update is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by PhilippKuhlmay** [deployphp/deployer#2325]
- Deployer version: 6.8.0
- Deployment OS: MaxOS 11.0.1

composer says, that deployer/phar-update is abandoned

<img width="720" alt="Bildschirmfoto 2020-12-04 um 19 32 11" src="https://user-images.githubusercontent.com/57705869/101201050-6e00a700-3667-11eb-8519-a1d3e88a470d.png">

**Comment by antonmedv** [comment]
This is correct.
