### ISSUE TITLE
Any ETA on stable version supporting PHP 8?

### ISSUE THREAD

**Issue by racinmat** [deployphp/deployer#2334]
Hi, the latest stable version is not compatible with PHP 8 according to composer.json, can we expect it released any time soon?
Thanks.

**Comment by antonmedv** [comment]
Well, beta 11 already supports it.

**Comment by racinmat** [comment]
I know, but beta is not stable.

**Comment by antonmedv** [comment]
I can release stable now, but what to do a few more minor things.

**Comment by racinmat** [comment]
No rush, I don't needed anytime soon, I just wanted to know when roughly could I expect it.

**Comment by ROTGP** [comment]
@antonmedv any news on this? A stable release means that other [packages](https://github.com/atymic/deployer-php-action) that depend on deployer could also start migrating to PHP8.

**Comment by antonmedv** [comment]
I hope soon) Still have to finish some parts.
