### ISSUE TITLE
Automated rector update recipe from v6 to v7

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#2335]
Using rector it should be possible to automate most (all?) steps of thr [upgrade guide](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md) to get a recipe from v6 to v7

https://github.com/rectorphp/rector

**Comment by antonmedv** [comment]
It will be really difficult as also some parts not completely different. For example, there is no stage, labels/selectors must be used to this. Inventory yaml files refactored significantly. 

I think manually is much easier, as recipes usally not longer than ~1k lines. Writing automation for this requires more time.

**Comment by antonmedv** [comment]
I tried to come up with some solution, but for now, it's too much work for a single maintainer.
