### ISSUE TITLE
Package deployer/phar-update is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by TrogWarZ** [deployphp/deployer#2336]
- Deployer version: `6.8.0`
- Deployment OS: `Ubuntu 18.04.x LTS`

Every time i get this notification but in `composer.json` i use ONLY `deployer/deployer`, no receipes or phar-update repo.

So, i thing this is bug – i don't need to be notified on package i didn't install. How to fix that?

**Comment by antonmedv** [comment]
Update to deployer v7
