### ISSUE TITLE
unexcept php version requirements

### ISSUE THREAD

**Issue by gpgkd906** [deployphp/deployer#2344]
- Deployer version: 
confirmed on deployer 6.3.0
but can be replay on all version.
- Deployment OS:
Centos 7
PHP 7.2.9
- details
deploy failed with error message like the image
![version_failed](https://user-images.githubusercontent.com/869103/102040462-35539100-3e10-11eb-8190-3851bd3479e4.png)

I have checked the deploy-flow and figure out the reason.
in the recipe/cachetool.php
it download cachetool from https://gordalina.github.io/cachetool/, and on PHP 7.2, it download the latest one which is need PHP 7.3 or higher.
yesterday they released that which need PHP 7.3 
https://github.com/gordalina/cachetool/releases/tag/6.0.0

maybe I should update the PHP but its not so easy to do that in Production Environment just now.
so, I think we should add some variable like {{cachetool_version}} to specify it.
when I finish the deployment, maybe, I can make some patch for this.

      Please, provide a minimal reproducible example of deploy.php

```
<?php
namespace Deployer;

require 'recipe/common.php';
require 'recipe/rsync.php';
require 'recipe/cachetool.php';

// Project name
set('application', 'demo');

// Writable dirs by web server
set('writable_dirs', [
    'var',
    'public',
]);

set('shared_dirs', [
    'var'
]);

set('shared_files', [
    'public/healthcheck.html'
]);

set('rsync', [
    'exclude'      => [
        '.git',
        '.docker-sync',
        '.phan',
        '.sami',
        '.vscode',
        'private',
        'deploy.php',
    ],
    'exclude-file' => false,
    'include'      => [],
    'include-file' => false,
    'filter'       => [],
    'filter-file'  => false,
    'filter-perdir'=> false,
    'flags'        => 'rz', // Recursive, with compress
    'options'      => ['update', 'delete'],
    'timeout'      => 60,
    'tty'          => true,
]);

set('rsync_src', __DIR__);
set('rsync_dest', '{{release_path}}');
set('allow_anonymous_stats', false);
set('cachetool', '127.0.0.1:9000');

// Hosts
inventory('private/deployer/hosts.yml');

after('deploy:failed', 'deploy:unlock');

// Tasks
desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'rsync',
    'deploy:shared',
    'deploy:writable',
    'deploy:env',
    'deploy:clear_paths',
    'deploy:symlink',
    'cachetool:clear:opcache',
    'deploy:unlock',
    'cleanup',
    'success'
]);
```

**Comment by t3rmix** [comment]
Hi,
workaround for this is override option **bin/cachetool** in you deployment configuration

`set('bin/cachetool', function(){
    return run("{{bin/php}} -r \"echo version_compare(phpversion(), '7.1') == -1 ? 'cachetool-3.2.1.phar' : 'cachetool-5.1.3.phar';\"");
});`
