### ISSUE TITLE
v6.8.1 Undefined index: name

### ISSUE THREAD

**Issue by helsner** [deployphp/deployer#2348]
- Deployer version: 6.8.1
- Deployment OS: MacOS Catalina

I got this on deployment:
Notice: Undefined index: name in /.../vendor/deployer/deployer/bin/dep on line 100
Call Stack:
0.0010     407048   1. {main}() /.../vendor/deployer/deployer/bin/dep:0

This seems to be introduced with the .1 version, .0 works fine

**Comment by antonmedv** [comment]
Will unrelease it
