### ISSUE TITLE
v.6.8.1 removes Composer v2 installed.json compatibility

### ISSUE THREAD

**Issue by janolivermr** [deployphp/deployer#2352]
- Deployer version: v.6.8.1

Version 6.8.0 has a compatibility fix for composer v2 installed.json file here:
https://github.com/deployphp/deployer/blob/v6.8.0/bin/dep#L110

Version 6.8.1 was tagged on an a commit that doesn't have this fix

**Comment by antonmedv** [comment]
I dropped v6.8.1. Please follow at discussion section.
