### ISSUE TITLE
The docs site should be for all versions rather than only the latest

### ISSUE THREAD

**Issue by dareenzo** [deployphp/deployer#2358]
I'd appreciate if it would be possible to allow the user to pick the version for which he's browsing the docs.

This is because sometimes you'll visit the site and if not aware you'll think that deployer always worked the way its described there, until hours later you realize that you're some versions behind and that things don't quite apply to you.

**Comment by antonmedv** [comment]
Yes, I’m agree with. Will do it.

**Comment by van-chin** [comment]
@antonmedv  where is docs v7

**Comment by antonmedv** [comment]
BTW, docs for v6 still avaialbe here: https://github.com/deployphp/docs
