### ISSUE TITLE
instalation via composer fail

### ISSUE THREAD

**Issue by andrescevp** [deployphp/deployer#236]
when I try to install the library via composer I recive this:

>- Installing elfet/php-ssh (v1.1.0)
>Downloading https://api.github.com/repos/elfet/php-ssh/zipball/439becf180272542cbf154df4856a49dd3c4bf04
    Downloading: connection...
>
>Failed: [Composer\Downloader\TransportException] 404: The "https://api.github.com/repos/elfet/php-ssh/zipball/439becf180272542cbf154df4856a49dd3c4bf04" file could not be downloaded (HTTP/1.1 404 Not Found)
>    Failed to download elfet/php-ssh from dist: The "https://api.github.com/repos/elfet/php-ssh/zipball/439becf180272542cbf154df4856a49dd3c4bf04" file could not be downloaded (HTTP/1.1 404 Not Found)
>    Now trying to download from source
>  - Installing elfet/php-ssh (v1.1.0)
>    Cloning 439becf180272542cbf154df4856a49dd3c4bf04
>Executing command (CWD): git clone --no-checkout 'git://github.com/elfet/php-ssh.git' '/srv/www/vhosts/online-gadget.local/vendor/elfet/php-ssh' && cd '/srv/www/vhosts/online-gadget.local/vendor/elfet/php-ssh' && git remote add composer 'git://github.com/elfet/php-ssh.git' && git fetch composer
>Executing command (CWD): git clone --no-checkout 'https://github.com/elfet/php-ssh.git' '/srv/www/vhosts/online-gadget.local/vendor/elfet/php-ssh' && cd '/srv/www/vhosts/online-gadget.local/vendor/elfet/php-ssh' && git remote add composer 'https://github.com/elfet/php-ssh.git' && git fetch >composer
>Username for 'https://github.com': 

and in packagist :

>This package is abandoned and no longer maintained. The author suggests using the herzult/php-ssh package instead.

**Comment by GrahamCampbell** [comment]
You need to run `composer self-update` then `composer clear-cache`. :)

**Comment by andrescevp** [comment]
thanks, but the problem it's the same, continue try use elfet/php-ssh and request error:
>[RuntimeException]
  Failed to clone git@github.com:elfet/php-ssh.git via git, https, ssh protocols, aborting.
  - git://github.com/elfet/php-ssh.git
    Cloning into '/srv/www/vhosts/.../vendor/elfet/php-ssh'...
    fatal: remote error:
      Repository not found.
  - https://github.com/elfet/php-ssh.git
    Cloning into '/srv/www/vhosts/.../vendor/elfet/php-ssh'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/elfet/php-ssh.git/'
  - git@github.com:elfet/php-ssh.git
    Cloning into '/srv/www/vhosts/.../vendor/elfet/php-ssh'...
    Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

 >   Please make sure you have the correct access rights
    and the repository exists.



>Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/Git.php:221
 Composer\Util\Git->throwException() at phar:///usr/bin/composer/src/Composer/Util/Git.php:80
 Composer\Util\Git->runCommand() at phar:///usr/bin/composer/src/Composer/Downloader/GitDownloader.php:54
 Composer\Downloader\GitDownloader->doDownload() at phar:///usr/bin/composer/src/Composer/Downloader/VcsDownloader.php:66
 Composer\Downloader\VcsDownloader->download() at phar:///usr/bin/composer/src/Composer/Downloader/DownloadManager.php:201
 Composer\Downloader\DownloadManager->download() at phar:///usr/bin/composer/src/Composer/Installer/LibraryInstaller.php:156
 Composer\Installer\LibraryInstaller->installCode() at phar:///usr/bin/composer/src/Composer/Installer/LibraryInstaller.php:87
 Composer\Installer\LibraryInstaller->install() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///usr/bin/composer/src/Composer/Installer.php:580
 Composer\Installer->doInstall() at phar:///usr/bin/composer/src/Composer/Installer.php:230
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:43
 require() at /usr/bin/composer:25

**Comment by elfet** [comment]
Which version of deployer are you trying to install?

**Comment by andrescevp** [comment]
~2.0

**Comment by elfet** [comment]
Try to install `2.0.5`. And v3 stable will be very soon.

**Comment by andrescevp** [comment]
nice, now works, so thanks very much ! :)

**Comment by elfet** [comment]
:beer:
