### ISSUE TITLE
`--ansi` causes an error

### ISSUE THREAD

**Issue by jkuchar** [deployphp/deployer#2364]
- Deployer version: dev-master@ da432e01399489a896e880e9469c01ffad5491e6
- Deployment OS: Mac, Ubuntu 20.04

```bash
vendor/bin/dep deploy staging --ansi
```

Output is then:
```
 TypeError  in Stringify.php on line 67:

  Deployer\Support\Stringify::escape(): Argument #1 ($token) must be of type string, bool given, called in /Users/jkuchar1/Documents/www/grifartis/source/PHP/vendor/deployer/deployer/src/Support/Stringify.php on line 35

```

It looks like option --ansi is interpreted as `true` which then fails on escaping code which can handle only strings.

**Comment by antonmedv** [comment]
Should be fixed. Please verify.
