### ISSUE TITLE
How connect reposirtory via SSH Keys

### ISSUE THREAD

**Issue by andrescevp** [deployphp/deployer#237]
I see that you can connect to host via SSH keys, but I don't see any function or set witch you can connect to git with SSH keys without password... maybe it's a future feature, and i thin that it's really important... or maybe the libraru alredy have this and i don't see. Thanks

**Comment by elfet** [comment]
You can use SSH Agent Forwarding.

**Comment by andrescevp** [comment]
If i try this, I must specify config file, I then the host connection it's refused because I use username and password. I have first connect  to host with user and password (it's a vagrant machine) and for make the code_update (git pull) I must specify the repository but for auth in the repository I must connect via SSH Keys

**Comment by elfet** [comment]
You can override task `update_code` to use your keys.

**Comment by andrescevp** [comment]
I see, i will try this, but please think about add a method for specify this parameters. thanks very much !
