### ISSUE TITLE
 [Error] Call to undefined function Deployer\warning()   

### ISSUE THREAD

**Issue by ndlinh** [deployphp/deployer#2374]
- Deployer version: 6.8.0
- PHP version: 7.4.11
- Deployment OS: Ubuntu 20.04

Deploy an Laravel app with missing .env file. The deploy failed, at `Executing task deploy:unlock` it showing Error ` [Error] Call to undefined function Deployer\warning()   `

If I add an empty function as bellow to deploy.php, it work without error.
```
function warning(string $message) {
    
}
```

**Comment by antonmedv** [comment]
warning is function from v7. Not in v6.
