### ISSUE TITLE
Getting stuck on dep:prepare

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [deployphp/deployer#2376]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.8.0
| Local Machine OS  | macOS 11.1 (Desktop)
| Remote Machine OS | Ubuntu 20.04 (Server)

### Description 
I'm starting to play with deployer and wanted to see how it's gonna work. Unfortunately it does not, getting stuck on "echo $0".

I commented the `after` at the end to get the error before the error at the deploy:unlock task.

### Content of `deploy.php`
I use standard recipe with following configuration
```php
<?php

namespace Deployer;

require 'recipe/common.php';

set('application', 'Secrets');
set('repository', 'https://github.com/Luca-Castelnuovo/secrets.git');

set('git_tty', true);
set('allow_anonymous_stats', false);

host('REDACTED_IP_ADDR')
    ->stage('production')
    ->user('webserver')
    ->set('deploy_path', '~/test');

desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success',
]);

// after('deploy:failed', 'deploy:unlock');
```

### Output log
![Screenshot 2021-01-16 at 18 41 09-redacted_dot_app](https://user-images.githubusercontent.com/26206253/104818998-1e4af900-582b-11eb-8d31-9d02acb51e7d.png)

**Comment by antonmedv** [comment]
What error message? Run with -vvv

**Comment by Luca-Castelnuovo** [comment]
<img width="1378" alt="Screenshot 2021-01-17 at 12 43 49" src="https://user-images.githubusercontent.com/26206253/104839469-a7147400-58c1-11eb-8f89-0ac19681a64e.png">

**Comment by antonmedv** [comment]
It fails on initialisation of ssh multiplexing. Try turn it off

**Comment by Luca-Castelnuovo** [comment]
<img width="1391" alt="Screenshot 2021-01-17 at 13 27 03" src="https://user-images.githubusercontent.com/26206253/104842850-c1e9e700-58c7-11eb-817b-0cbb4a8cc2c2.png">

**Comment by Luca-Castelnuovo** [comment]
Why is this closed?

**Comment by antonmedv** [comment]
Without error I can’t help you.

**Comment by Luca-Castelnuovo** [comment]
So there is no reason why it shouldn't work?

**Comment by antonmedv** [comment]
Check you login shell. echo $0 is the first command and it should work.

**Comment by Luca-Castelnuovo** [comment]
<img width="628" alt="Screenshot 2021-01-19 at 16 40 43" src="https://user-images.githubusercontent.com/26206253/105057162-3a41db00-5a75-11eb-8ec7-c957fb4cd5ef.png">

**Comment by antonmedv** [comment]
It should work on bash.

**Comment by Luca-Castelnuovo** [comment]
Are you saying that on my client machine my shell should also be bash?

**Comment by antonmedv** [comment]
On server it should be bash.

**Comment by Luca-Castelnuovo** [comment]
On the server it is bash

**Comment by antonmedv** [comment]
Did you get it to run?

**Comment by Luca-Castelnuovo** [comment]
No the deploy still fails, if comment out the `after('deploy:failed', 'deploy:unlock');`

It also errors but says that even executing "echo $0" fails.

**Comment by antonmedv** [comment]
But why it stops at echo $0?

**Comment by johnorourke** [comment]
@Luca-Castelnuovo I think there are 2 different issues here:

* your deploy.php shows user 'webserver' but your `dep ssh -vvv` test shows user 'luca' - if you log in with 'ssh webserver@x.x.x.x' does ~/test exist and is the shell bash?
* the default deploy:unlock task needs to be modified so that the `rm -f {{deploy_path}}/.dep/deploy.lock` command is allowed to fail, in case the file was not created (in your case, it failed during deploy:prepare so the lock file perhaps did not exist)

I hope that helps.

**Comment by Luca-Castelnuovo** [comment]
Thank you for the reply.

> * your deploy.php shows user 'webserver' but your `dep ssh -vvv` test shows user 'luca' - if you log in with 'ssh [webserver@x.x.x.x](webserver@x.x.x.x)' does ~/test exist and is the shell bash?

This is no coincidence or mistake. I use moul/sshportal to manage SSH access to my servers. It works by using the username as the server you want to connect to, so `webserver@sshIP --> luca@webserverIP`.


> * the default deploy:unlock task needs to be modified so that the `rm -f {{deploy_path}}/.dep/deploy.lock` command is allowed to fail, in case the file was not created (in your case, it failed during deploy:prepare so the lock file perhaps did not exist)
How would you go about doing this?
The lock file does indeed not exist, because the entire deploy_path doesn't get created.

I think it errors somewhere in the ssh connection. But I don't understand why `dep ssh production` completes succesfully.

**Comment by antonmedv** [comment]
> But I don't understand why dep ssh production completes succesfully.

looks like not. Try disable moul.

**Comment by Luca-Castelnuovo** [comment]
That is not really possible. The connection establishes and I can interact with the shell. It just doesn't auto open the `/home/luca/test/current` path because `/home/luca/test` doesn't exist.

**Comment by antonmedv** [comment]
So it not deployer related? And moul related?

**Comment by Luca-Castelnuovo** [comment]
No I'm saying the opposite, moul seems to work fine. So maybe the interaction between the two.

Deployer basically shouldn't notice mouls existence.

**Comment by antonmedv** [comment]
Deployer only makes call to ssh client on local machine. Try to place echo in sshclient class. Or upgrade to v7 and run with -vvv option. It will display actual command.

**Comment by Luca-Castelnuovo** [comment]
I will try the upgrade and debug again.

**Comment by nicoloko002** [comment]
Hi, I went into the same problem, maybe it can help to guess what is happening.
For me, running with -vvv all ssh was returning with: 
`SOMETHING [exit_code`

So, I changed on Component/Ssh/Client.php the line:
`$ssh = "ssh $options $connectionString $become " . escapeshellarg(": $shellId; $shellCommand; printf [exit_code:%s] $?;");`

To:
`$ssh = "ssh $options $connectionString $become " . escapeshellarg(": $shellId; $shellCommand; printf [exit_code:$?];");`

Not sure what %s should mean in that case, but googling for "exit code from ssh" I found that $? returns the exit code.
That solved the problem for me =-)

**Comment by Luca-Castelnuovo** [comment]
> Deployer only makes call to ssh client on local machine. Try to place echo in sshclient class. Or upgrade to v7 and run with -vvv option. It will display actual command.

### deploy.php
```php
<?php

namespace Deployer;

require_once __DIR__.'/vendor/autoload.php';
require 'recipe/composer.php';

set('application', 'secrets');
set('repository', 'https://github.com/Luca-Castelnuovo/secrets.git');
set('use_relative_symlink', false);

add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

host('production')
    ->setHostname('redacted_ip')
    ->setPort(22)
    ->setRemoteUser('webserver')
    ->setSshMultiplexing(false)
    ->setDeployPath('~/{{application}}');
    // ->setIdentityFile(__DIR__ . '/.env');

task('build', function () {
    cd('{{release_path}}');
    run('touch test');
});

after('deploy:failed', 'deploy:unlock');
```
### Version
![Schermafbeelding 2021-01-30 om 12 38 39 PM](https://user-images.githubusercontent.com/26206253/106355435-1a71a900-62f8-11eb-95af-8a806de5f061.png)

### Output
![Schermafbeelding 2021-01-30 om 12 37 54 PM-redacted_dot_app](https://user-images.githubusercontent.com/26206253/106355455-455bfd00-62f8-11eb-9079-b2a5ea2a06f9.png)

**Comment by Luca-Castelnuovo** [comment]
> Hi, I went into the same problem, maybe it can help to guess what is happening.
> For me, running with -vvv all ssh was returning with:
> `SOMETHING [exit_code`
> 
> So, I changed on Component/Ssh/Client.php the line:
> `$ssh = "ssh $options $connectionString $become " . escapeshellarg(": $shellId; $shellCommand; printf [exit_code:%s] $?;");`
> 
> To:
> `$ssh = "ssh $options $connectionString $become " . escapeshellarg(": $shellId; $shellCommand; printf [exit_code:$?];");`
> 
> Not sure what %s should mean in that case, but googling for "exit code from ssh" I found that $? returns the exit code.
> That solved the problem for me =-)

### Output (after updating Client.php):
![Schermafbeelding 2021-01-30 om 12 41 15 PM-redacted_dot_app](https://user-images.githubusercontent.com/26206253/106355483-881dd500-62f8-11eb-97fb-24a9ecb86c31.png)

**Comment by antonmedv** [comment]
Now try to run this ssh command.

**Comment by Luca-Castelnuovo** [comment]
Which command do you mean? `if [-h ~/secrets/release ]; then echo 'true'; fi`?

**Comment by antonmedv** [comment]
Starting with ssh p

**Comment by Luca-Castelnuovo** [comment]
I don't have my SSH key with me, once I do I will test this.

**Comment by Schrank** [comment]
@Luca-Castelnuovo any news on that? :)

**Comment by Luca-Castelnuovo** [comment]
Hi, sorry for the lack of response. Unfortunately I have not enough time to work on this now. 

Would it be okay if I close this issue and later reopen it?

**Comment by antonmedv** [comment]
Let’s close this issue to keep it clean. If someone encounters same issue fill free to open new issue.
