### ISSUE TITLE
Force ssh to use specific key

### ISSUE THREAD

**Issue by shvlv** [deployphp/deployer#2380]
Generally this issue and community answer described at https://superuser.com/questions/1610623/why-ssh-always-using-first-key-accepted-by-server.

I force to ssh using specific key via dirty hack:
```php
if (\Deployer\Support\str_contains($command, '/usr/bin/git clone')) {
     $ssh = "ssh-agent ssh -A -tt -o AddKeysToAgent=yes -i ~/.ssh/id_rsa $host $command";
 } else {
     $ssh = "ssh $sshArguments $host $command";
 }
```
Should we realize this behavior by default if user add `identityFile` to config?
I can try to prepare pull request after discussion.
@antonmedv

**Comment by antonmedv** [comment]
I didn’t get it. You can specify key for ssh.

**Comment by shvlv** [comment]
@antonmedv You can specify key  but command `ssh -i ~/.ssh/id_rsa user@ip` does not guarantee that this particular key will be used if you have several ssh for current server.

**Comment by antonmedv** [comment]
Did not get it, can you show an example?

**Comment by shvlv** [comment]
For example, I have 3 keys -  `ssh-add -L`:
```
ecdsa-sha2-nistp521....
ssh-rsa-github...
ssh-rsa2...
```
All this keys can be used for access `current_host`, but only one of them can be used for remote repository access. If I want use agent-forwarding and run
 ```bash
ssh -A -tt -i ~/.ssh/ssh_rsa_github user@current_host 'git clone...'
```
ssh whatever use first key are accepted by the remote server. So I can not clone repository because wrong key is used.

**Comment by antonmedv** [comment]
What if you disable forwardAgent?

**Comment by shvlv** [comment]
But I can't do it. I need forwardAgent to access my remote repository.

**Comment by johnorourke** [comment]
@shvlv could this be done outside of deployer?  You can start multpile ssh-agents.  So you could start a new ssh-agent, and add only the key that you want to it, and then use that in the terminal/script that you're running deployer from.

**Comment by shvlv** [comment]
@johnorourke I think this can resolve my problem. Could you provide quick code example?

**Comment by johnorourke** [comment]
@shvlv something like this (assuming you are using ssh-agent as your agent - I am using Keepass, other people might be using Pageant)

```
[user@host:~]  eval `ssh-agent`   # start new agent and set environment variables SSH_AUTH_SOCK and SSH_AGENT_PID in *this* terminal
[user@host:~] ssh-add ~/.ssh/ssh_rsa_github  # prompt for pass-phrase if required
[user@host:~] dep ssh -vvv
...now deployer can only use that key...

[user@host:~] kill $SSH_AGENT_PID # clean up by removing our temporary agent
```

**Comment by shvlv** [comment]
@johnorourke Yes, it works. Thank you for explanation.
