### ISSUE TITLE
How to use the .env provided from application

### ISSUE THREAD

**Issue by Brotzka** [deployphp/deployer#2383]
We use TeamCity to build our application. Only for deploying we use deployer as last step in our build pipeline in TeamCity. Because we maintain the env-files for all environments directly in our repository (e.g. .env.production, .env.staging) we copy and rename the relevant .env file during build process.

That means that we need to copy the provided .env by our build chain to replace the .env in the shared-folder. Is there a way to accomplish this? I've removed the .env file from the set('shared_files').

**Comment by antonmedv** [comment]
Sure, just upload it there needed.
