### ISSUE TITLE
Class 'phpseclib\Net\SFTP' not found

### ISSUE THREAD

**Issue by e-edgren** [deployphp/deployer#2384]
Hi.

I installed phpseclib (dev-master) via Composer and using the following to connect to my SFTP server.

```
require_once 'vendor/autoload.php';
use phpseclib\Net\SFTP;

$sftp = new SFTP('address');
if(!$sftp->login('username', 'password')) {
    exit('Login Failed');
}

$sftp->put('remote.php', 'local.php', SFTP::SOURCE_LOCAL_FILE);
```

I get this error message: `Fatal error: Uncaught Error: Class 'phpseclib\Net\SFTP' not found in ...`

Have I missed something?

**Comment by antonmedv** [comment]
Please go to phpseclib issues.

**Comment by e-edgren** [comment]
Oops! I am so sorry. I thought I already were there after a DuckDuckGo search and didn't look closely.
