### ISSUE TITLE
Again / revisit: unix_listener: path "[...]" too long for Unix domain socket 

### ISSUE THREAD

**Issue by nvaken** [deployphp/deployer#2388]
Pretty much a revisit of #1356 

Today I had a connection that had a control path that was exactly one character too big and still gave me the error `unix_listener: path "/path/to/UnixDomainSocket" too long for Unix domain socket`. I found out that I've made the mistake (or OpenSSH has been updated on Mac OS) that `%C` is not 16 characters long but 17. An real life example would be: `.MvQNcnG7oik0cM1V`. Though, probably that has actually _is_ 16 characters long, but it get's prefixed by a `.`. 

Should fix this to set `$connectionHashLength` in `src/Ssh/Arguments.php` to 17 instead of 16. 

FYI, working on 6.8.0 atm.

**Comment by antonmedv** [comment]
Sure, let's try it. Fixed in https://github.com/deployphp/deployer/pull/2464
