### ISSUE TITLE
Improve symlink check in deploy:release task

### ISSUE THREAD

**Issue by Max-Might** [deployphp/deployer#239]
This just happened to me.
In the case of a failed deploy we may have a `release` symbolic link that points to a directory that does not exist.
Now, on the next deployment the `deploy:release` task checks if the `release` directory exists with `[ -e release ]` but it returns false because the directory the symbolic link points to does not exist. On the next step `ln` fails because the symbolic link is actually there.

So my suggestion is to check if the release directory exists with the `-h` or `-L` option instead of `-e`.

**Comment by elfet** [comment]
Ok, it will be great. Please, create PR for it. Also you can adв test case for this in `test/recipe`. Thanks!
