### ISSUE TITLE
Branch 6.x points to old version and misses commits between 6.4.5 and 6.8.0

### ISSUE THREAD

**Issue by aboks** [deployphp/deployer#2390]
- Deployer version: N/A
- Deployment OS: N/A

As noted in https://github.com/deployphp/deployer/issues/2345#issuecomment-767522584.

**Comment by tchapi** [comment]
Eagerly waiting for that !

**Comment by antonmedv** [comment]
Done with reset branch 6.x to:
```
4e243a6 (HEAD -> 6.x, tag: v6.8.0, origin/6.x) Release v6.8.0
```
