### ISSUE TITLE
Error returns code 0

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#2392]
- Deployer version:  7.0.0-beta.13
- Deployment OS: Ubuntu 20.04

I'm getting following error
>  TypeError  in Stringify.php on line 67:
>  Argument 1 passed to Deployer\Support\Stringify::escape() must be of the type string, bool given, called in phar:///home/circleci/app/bin/dep/src/Support/Stringify.php on line 35

See attached image:
![Schermata da 2021-01-28 11-17-55](https://user-images.githubusercontent.com/179866/106123662-81f1f200-615a-11eb-8a18-6bba54005816.png)

apart from weird error, I would expect that such case would return a code different from zero (otherwise I'm not able to notice that something went wrong)

**Comment by antonmedv** [comment]
Can you show you deploy.php? Or provide some example?

**Comment by garak** [comment]
I'm not sure my config can be relevant (apart from the error on escape, that's secondary).
The main problem here is that deployer is not taking into account exceptions/errors to give a proper return code.

**Comment by garak** [comment]
I found a way to reproduce:
```php
task('dummy', function () {
    $func = static function (string $a) {};
    $func(true);
});
```
Run the "dummy" task, as defined above, and see "unexpected '(bool)'" error happens. Then, run `echo $?`.
You should get a code different from zero, but you get zero instead.

**Comment by cafferata** [comment]
It's in the [Deployer options](https://deployer.org/docs/cli.html) `--no-ansi`, `--ansi`, `--no-interaction`

```php
<?php

namespace Deployer;

require_once __DIR__.'/vendor/deployer/deployer/recipe/symfony.php';

set('repository', 'git@github.com:deployphp/deployer.git');

$host = host('deployer.org');
$host->setRemoteUser('test');
$host->setDeployPath('/var/www/');
```

```bash
./vendor/bin/dep deploy --no-ansi
```
``` TypeError  in Stringify.php on line 67:
Deployer\Support\Stringify::escape(): Argument #1 ($token) must be of type string, bool given, called in /Users/cafferata/jcid/deployphp/deployer/vendor/deployer/deployer/src/Support/Stringify.php on line 35
```

```bash
./vendor/bin/dep deploy --ansi
```
``` TypeError  in Stringify.php on line 67:
Deployer\Support\Stringify::escape(): Argument #1 ($token) must be of type string, bool given, called in /Users/cafferata/jcid/deployphp/deployer/vendor/deployer/deployer/src/Support/Stringify.php on line 35
```

```bash
./vendor/bin/dep deploy --no-interaction
```
``` TypeError  in Stringify.php on line 67:
Deployer\Support\Stringify::escape(): Argument #1 ($token) must be of type string, bool given, called in /Users/cafferata/jcid/deployphp/deployer/vendor/deployer/deployer/src/Support/Stringify.php on line 35
```

**Comment by cafferata** [comment]
I can't (yet) oversee the impact of this commit https://github.com/deployphp/deployer/commit/18bdfc8bd94a8aa408f59dac1fb9daa6a8800c8c#diff-b872a77de62f6d05e055c5c2c19e0175ad4b9f4075531eee37dcba67a6d3cea8R63

```diff
            foreach ($option as $value) {
-                $options[] = "--$name " . self::escape($value);
+                $options[] = "--$name " . self::escape((string) $value);
            }
```
