### ISSUE TITLE
Create multiple localhost entries with different stages

### ISSUE THREAD

**Issue by adatta02** [deployphp/deployer#2395]
Apologizes if this is possible right now but I can't see how to set it up.

My use case is the following:

1. I've got a Symfony 5+ app that's being deployed via deployer across 3 stages (dev, qa, prod). This is working great.
2. Now, I'm trying to add the deployer piece into an Ansible playbook
3. I have my Ansible playbook setup so that it runs on localhost to enable autoscaling

So what I'd like to do with deployer is configure multiple localhost() configurations, one per each stage.

I thought something like this would work:

```
localhost()
    ->stage('dev')
    ->user('ubuntu')
    ->set('deploy_path', '~/dev-{{application}}');

localhost()
    ->stage('qa')
    ->user('ubuntu')
    ->set('deploy_path', '~/qa-{{application}}');
```

But it looks like localhost() calls overwrite the previous configuration entry.

Would love any thoughts.

Thanks!

**Comment by antonmedv** [comment]
Try giving aliases to your localhosts. localhost(“prod”)

**Comment by adatta02** [comment]
Oh awesome, thanks. Not sure how I missed that!
