### ISSUE TITLE
Guide for using recipes 

### ISSUE THREAD

**Issue by memen45** [deployphp/deployer#2401]
Trying to use a recipe to deploy magento2, however I cannot find out how to do it. Steps I tried:

Install Deployer according to [Getting Started](https://deployer.org/docs/getting-started.html)
Run `dep init` and now there are 10 recipes that can be chosen from. However, magento2 is not one of them. Also, in the [recipe](https://github.com/deployphp/deployer/tree/master/recipe) directory, there are other recipes available than in the list of 10. 

How can these recipes be used?

**Comment by memen45** [comment]
More details:
OS: Windows 10 WSL2 - Ubuntu 20.04 LTS 
Deployer v6.8.0

`dep init` returns the following output
```
 Please select your project type [Common]:
  [0 ] Common
  [1 ] Laravel
  [2 ] Symfony
  [3 ] Yii
  [4 ] Yii2 Basic App
  [5 ] Yii2 Advanced App
  [6 ] Zend Framework
  [7 ] CakePHP
  [8 ] CodeIgniter
  [9 ] Drupal
  [10] TYPO3
```

In the repository there seem to be two directories with 'recipes'. First the deployer/recipe directory contains most of the 10 listed above, but also many more (which I do not know how to use/install). Second the deployer/contrib directory contains the recipes as listed on the [deployer.org/recipes](https://deployer.org/recipes.html) website. 

Then there is the deployer/recipes package that can be installed from composer containing another set of recipes (old ones?) that can be installed with `composer require deployer/recipes --dev` . This however shows a warning about an abandoned package. 

It seems this has been raised already (see #2200 #2122), but for me the solution is not clear. Is v7 released now? Cause default installation seems to install version 6.8, not v7. How can these recipes be used/installed with version 6.8? Or if it is not possible, how can v7 be installed instead of 6.8? 

Help or clarification much appreciated!

**Comment by pduersteler** [comment]
The `deploy.php` file that is being generated in your project through `dep init` can also be written manually. Maybe create the `Common` one and then you'll see that there is a `require` for the recipe. Just change that one to include the `magento2` recipe you want and go through the `magento2` recipe to see what you need to configure in your `deploy.php` file.

At least that's how I am doing it right now because I'm customizing the TYPO3 recipe for a project.

**Comment by memen45** [comment]
Thanks! I had created a deploy file manually, but that did not work. Your suggestion results in a executable deploy file. Thanks a lot.

However, with the magento2 deploy recipe, I cannot find out how to perform the initial installation. It seems like the recipe can only handle upgrades, no setup:install, so how should the first install be performed on the host?

Trying `dep deploy host` on the empty directory returns an `Invalid configuration file: /var/www/my-project/releases/1/app/etc/env.php` error during the magento setup:di:compile. 

I also tried to add a deploy_install task replacing the deploy:magento line from the original deploy task with a deploy:magento:install task, which is effectively calling the magento setup:install with all the required parameters. However, on an empty directory, the `dep deploy_install host` returns a `The command "readlink /var/www/my-project/current" failed`.

The git repository consists of simply the magento2 composer.json that was retrieved from the composer create-project --noinstall command.

**Comment by memen45** [comment]
Moved the magento2 question to a separate issue #2413. The bottomline for this issue is that the documentation is lacking explanation on how to properly use recipes. To get started with a recipe, the following steps should work:

Simply follow the [Install Deployer steps](https://deployer.org/docs/getting-started.html) and choose common when asked for which recipe to use. This makes sure the required settings are inside the deploy.php file. Then edit the deploy.php file and modify the `require` line to the recipe you need. Note that there are apparently two directories with recipes:
```
require 'recipe/common.php';
require 'contrib/slack.php';
```

Probably one can skip the above, and create the deploy.php from scratch. I think however there are some variables/options that are necessary for a working deploy.php file.

**Comment by antonmedv** [comment]
> I think however there are some variables/options that are necessary for a working deploy.php file.

deploy.php can be created from empty file. No required require.

**Comment by memen45** [comment]
Yes that is true. However, as soon as a 'require' is used, some requirements seem to be imposed on the deploy.php file, e.g. defining the host and repository variables.

**Comment by antonmedv** [comment]
Yes, if you require common recipe
