### ISSUE TITLE
cleanup_use_sudo removed

### ISSUE THREAD

**Issue by mtwalsh** [deployphp/deployer#2404]
- Deployer version: v7.0.0-beta.13
- Deployment OS: Linux Ubuntu 18.04

Hi,

I've noticed in [this commit](https://github.com/deployphp/deployer/commit/29a643b62389542394c7b254f6c913f7191132ba#diff-1600ca79102179937ce6b657449b8c322b6243fbe7f2c00eb0bd044e7a68e0ba) that the `cleanup_use_sudo` configuration parameter has been removed. When using `writable_use_sudo` it seems a necessity to also use `cleanup_use_sudo`. Would it be possible to reinstate it? Or perhaps elevate the cleanup command depending on  `writable_use_sudo`? Otherwise, when Deployer attempts to cleanup a failed deployment, the cleanup fails and we have to manually remove the release's folder.

FYI we're using `set('writable_mode', 'chown');`.

**Comment by antonmedv** [comment]
Returned it back =)

**Comment by mtwalsh** [comment]
Awesome, thanks!
