### ISSUE TITLE
Trying to set node path not working.

### ISSUE THREAD

**Issue by scryba** [deployphp/deployer#2406]
- Deployer version: 6.8.0 
- Deployment OS: Ubuntu 16.04.7 LTS

      Please, provide a minimal reproducible example of deploy.php

```
set('bin/npm', '/root/.nvm/versions/node/v15.8.0/bin/npm');
set('bin/node', '/root/.nvm/versions/node/v15.8.0/bin/node');

task('npm:production', '{{bin/npm}} run prod');
```

I get the error:

25 verbose Linux 4.4.0-201-generic
26 verbose argv "/usr/bin/node" "/root/.nvm/versions/node/v15.8.0/bin/npm" "run" "prod"
27 verbose node v10.23.3
28 verbose npm  v7.5.1

deployer is not using /root/.nvm/versions/node/v15.8.0/bin/node but rather uses /usr/bin/node

how do I get it to use my set node?

**Comment by antonmedv** [comment]
Looks what everything works for me. Please add minimal reproducible deploy.php file to show your error.
