### ISSUE TITLE
Laravel migrations are only run on the first host due there being a `->once` on the task

### ISSUE THREAD

**Issue by ThaDaVos** [deployphp/deployer#2407]
- Deployer version: * v6.8.0
- Deployment OS: Linux

Simple have a hosts.yaml file with multiple hosts per stage - only the first host will have it's migrations done

https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L87

**Comment by antonmedv** [comment]
Let's open another issue?

**Comment by joelpittet** [comment]
@Kauhsa I've forked it a bit here because I have some permission/cache clearing things I needed to bake in:
https://github.com/ubc-cpsc/deployer-recipes/blob/main/recipes/laravel.php

I agree with @antonmedv, open another issue if it needs to be tweaked for the general case.
