### ISSUE TITLE
Where is Rsync ?

### ISSUE THREAD

**Issue by Wikiki** [deployphp/deployer#2410]
Hi,

I want to use deployer with rsync but it seems `https://github.com/deployphp/recipes` is deprecated and v7 (which should integrate it if we follow the recommandation on the recipes repository is still in beta. So how to use deployer with rsync ?
Why flag `https://github.com/deployphp/recipes` as deprecated when there is no release including it available ?

**Comment by rrrrando** [comment]
All recipes are in contrib. Check [here](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md)

**Comment by Schrank** [comment]
for v6 you use recipes, for v7 you use /contrib

deprecated means "we'll remove it in the future and it is not maintained anymore"

So please use either v7 unstable or the recipes repo.

Does that solve your problem?
