### ISSUE TITLE
upgrade guide misleading

### ISSUE THREAD

**Issue by romanstingler** [deployphp/deployer#2412]
- Deployer version: 
- Deployment OS:

in your upgrade guide you have following line 
`Update addSshOption('UserKnownHostsFile', '/dev/null') to setSshArguments(['-o UserKnownHostsFile=/dev/null']);`

this is wrong 

  `  Call to undefined function Deployer\setSshArguments()`

probably you meant 
`set('SshArguments', ['-o UserKnownHostsFile=/dev/null']);`

**Comment by antonmedv** [comment]
Fixed.
