### ISSUE TITLE
Recipe Magento2 first deploy

### ISSUE THREAD

**Issue by memen45** [deployphp/deployer#2413]
- Deployer version: 6.8.0
- Deployment OS: Ubuntu 20.04 LTS / WSL 2 / Windows 10

With the magento2 deploy recipe, I cannot find out how to perform the initial installation. It seems like the recipe can only handle upgrades, no setup:install, so how should the first install be performed on the host?

The Production server was installed with all the required packages, databases and settings that are needed to run a successful magento install. Then the SSH was setup to allow access from the deployer server. Then the following was tried on the deployer server, without success.

Trying `dep deploy host` on the empty directory returns an `Invalid configuration file: /var/www/my-project/releases/1/app/etc/env.php` error during the magento setup:di:compile. This is probably related to #2377 and more closely to #2106, however, I cannot find a solution in those issues.

I also tried to add a deploy_install task replacing the deploy:magento line from the original deploy task with a deploy:magento:install task, which is effectively calling the magento setup:install with all the required parameters. However, on an empty directory, the `dep deploy_install host` returns a `The command "readlink /var/www/my-project/current" failed`. The code added to the deploy.php file to do the setup:install:
```
desc('Magento2 deployment for install');
task('deploy:magento:install', function () {
        run("{{bin/php}} {{release_path}}/bin/magento module:enable --all");
        run("{{bin/php}} {{release_path}}/bin/magento setup:install --admin-firstname={{magento_adminfirstname}} --admin-lastname={{magento_adminlastname}} --admin-email={{magento_adminemail}} --admin-user={{magento_adminuser}} --adminpassword={{magento_adminpassword}} --db-host={{magento_dbhost}} --db-name={{magento_dbname}} --db-user={{magento_dbuser}} --db-password={{magento_dbpassword}}");
});

desc('Deploy your project first time');
task('deploy_install', [
    'deploy:prepare',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:magento:install',
]);
```

The git repository consists of simply the magento2 composer.json that was retrieved from the composer create-project --noinstall command. Should there be more files included in the Git repo?

How do you perform the first deploy on a freshly installed host?

**Comment by peterjaap** [comment]
I think you're right that this recipe does not support initial installation - I've always done that manually - install Magento like you would without Deployer on the server (so a git pull, composer install, etc), then run the deployment (which will fail) and update the symlinks for the shared files (the directories should be created by then).

**Comment by memen45** [comment]
If I understand correctly, the setup:install only initializes the empty magento database? This would make it possible to indeed install on a different server, then import the database on production. 

However, in case I would like to deploy magento2 on a new host, I have to manually fix these symlinks, while this should be handled by deployer. When looking further in the deployer code, I found that the shared files are touched one by one
```
run("touch $sharedPath/$file");
```
From [recipe/deploy/shared.php#71](https://github.com/deployphp/deployer/blob/c714d1035675400473569b2bba883877110e258f/recipe/deploy/shared.php#L71). I think the shared files should not be touched, as they should just be copied from the git repository if available, or not copied at all. Is there a use for touching the shared files?

**Comment by peterjaap** [comment]
That part is not Magento-specific so I'm a bit out of my depth here. Maybe @antonmedv can chime in here?

**Comment by memen45** [comment]
Updated deploy.php file to perform installation if necessary (for others having the same problem):
```
<?php
namespace Deployer;

require 'recipe/common.php';
require 'recipe/magento2.php';

// Project name
set('application', 'my-project');

// Project repository
set('repository', 'git@github.com:gituser/my-project.git');

// Hosts
host('shop')
  ->hostname('shop.domain.com')
  ->stage('production')
  ->user('deploy')
  ->identityFile('~/.ssh/id_rsa')
  ->port(22)
  ->set('deploy_path', '/var/www/{{application}}')
  ->set('deploy_mode', 'production');

set('keep_releases', 2);
set('writable_mode', 'chown');
set('http_user', 'deploy');

// Magento install options
set('magento_adminfirstname', 'Admin');
set('magento_adminlastname', 'Admin');
set('magento_adminemail', 'admin@domain.com');
set('magento_adminuser', 'admin');
set('magento_adminpassword', 'admin123');

set('magento_dbhost', 'localhost');
set('magento_dbname', 'magento_database_name');
set('magento_dbuser', 'magento_database_username');
set('magento_dbpassword', 'magento_database_password');

desc('Install Magento');
task('magento:install', function () {
  $installed = has('previous_release');
  echo $installed ? "Magento is already installed\n" : "Magento will be installed now...\n";

  if ($installed) return;

  $confirm = askConfirmation("Are you sure you want to perform a clean install of Magento on {{hostname}}?");
  if ($confirm) {
          run("{{bin/php}} {{release_path}}/bin/magento setup:install --base-url=https://shop.domain.com --use-secure=1 --use-secure-admin=1 --use-rewrites=1 --admin-firstname={{magento_adminfirstname}} --admin-lastname={{magento_adminlastname}} --admin-email={{magento_adminemail}} --admin-user={{magento_adminuser}} --admin-password={{magento_adminpassword}} --db-host={{magento_dbhost}} --db-name={{magento_dbname}} --db-user={{magento_dbuser}} --db-password={{magento_dbpassword}} --cleanup-database", ['timeout' => null]);
          echo "Installation completed\n";
          run("{{bin/php}} {{release_path}}/bin/magento deploy:mode:set {{deploy_mode}}");
          run("{{bin/php}} {{release_path}}/bin/magento cron:install");
  }
});

before('deploy:magento', 'magento:install');
```
It is assuming all required packages are available and also the database user is set up properly.

For the Magento related questions, could you share your thoughts/practices with regards to the following:

-  Do you add the env.php file and config.php files to git?
- Which changes do you make to git and which ones should be made in the admin panel on production?
- How do you perform magento updates? Composer update, `git add composer.json` and `git push` on development server, followed by a `dep deploy shop` on the deployer server?
- How do you add modules? My guess would be: composer require and module:enable on the development server, then git add config.php composer.json, git push, then run dep deploy shop on the deployer server. Is that correct?

With regards to the Deployer part of the question: it is still an issue that you need to have either no env.php file (so touch should NOT be executed for shared files), or a valid env.php (which could be placed through git repository, but is not desirable as it should be locally stored through updates and not overwritten each deploy as is proposed now by PR #2267 ). Therefore I would strongly suggest to remove this touch line [recipe/deploy/shared.php#L71](https://github.com/deployphp/deployer/blob/c714d1035675400473569b2bba883877110e258f/recipe/deploy/shared.php#L71) from the code. Would that result in issues for other use-cases of Deployer?

**Comment by Schrank** [comment]
Not doing M2 anymore, but... (feel free to ignore me, just my 2 cents)

> Do you add the env.php file and config.php files to git?
No, credentials like smtp and database don'T belong into git.

> Which changes do you make to git and which ones should be made in the admin panel on production?
Back in M1 days we didd everything possible in git with install/setup scripts. Setting up websites, categories, attributes, taxes, customer groups. And even products if possible or the first launch.

So imho put as much as possible in install scripts, so you can be sure, that the difference between local, dev, stage and prod its minimal.

**Comment by memen45** [comment]
Thanks for your comments. I started searching some more and found a mistake in the magento2 recipe. I created a pull request for it.

**Comment by peterjaap** [comment]
@memen45 The shared files are not in version control, they exist solely on the production server and are therefore by definition shared. If we would merge this, the config file would be shared on the server between releases - which is exactly what we don't want.

**Comment by peterjaap** [comment]
> Do you add the env.php file and config.php files to git?
env.php is on the sever, not in Git. config.php is in Git.
> Which changes do you make to git and which ones should be made in the admin panel on production?
Preferably as little as possible in the admin panel - that is for customer-generated content only.
> How do you perform magento updates? Composer update, git add composer.json and git push on development server, followed by a dep deploy shop on the deployer server?
We don't use development servers but do everything locally but basically yes.
> How do you add modules? My guess would be: composer require and module:enable on the development server, then git add config.php composer.json, git push, then run dep deploy shop on the deployer server. Is that correct?
Not `module:enable`, but `setup:upgrade` (which runs database migrations *and* enables the module). But yes, that is correct.

**Comment by memen45** [comment]
> @memen45 The shared files are not in version control, they exist solely on the production server and are therefore by definition shared. If we would merge this, the config file would be shared on the server between releases - which is exactly what we don't want.

Ah yes, I understand now. Shared files are the ones shared throughout the releases, files shared between servers are part of source control. 

Thanks a lot for your clarifications, it makes things a lot clearer now!
