### ISSUE TITLE
Laravel website not updated after keep_releases + 1

### ISSUE THREAD

**Issue by alexmro** [deployphp/deployer#2417]
- Deployer version: latest
- Deployment OS:  SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64

This is my _deploy.php_
```
<?php
namespace Deployer;

require 'recipe/rsync.php';
require 'recipe/laravel.php';
require 'recipe/npm.php';

inventory('hosts.yml');

set('keep_releases', 3);

set('rsync_src', __DIR__);
set('rsync_dest','{{release_path}}');

set('writable_use_sudo', true);
set('clear_use_sudo', true);
set('cleanup_use_sudo', true);
set('http_group', 'daemon');
set('http_user', 'daemon');

task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'rsync',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
    'artisan:storage:link',
    'artisan:view:clear',
    'artisan:cache:clear',
    'artisan:config:cache',
    'artisan:optimize',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])->desc('Deploy project');

after('deploy:failed', 'deploy:unlock');

after('artisan:optimize', 'artisan:migrate');
after('artisan:migrate', 'artisan:db:seed');

after('deploy', 'success');

```
and what happens is that if I start from scratch (release 1) everything works fine. If I push changes and the pipeline runs again generating release 2 I can see the changes. But once I push again and I reach release 2 and forth, even though I see no error in the console, the changes no longer are shown in the browser. 

I can see the code has been updated but it's like the shared folder is not updated. I have to remove everything and start back from release 1.

**Comment by peterjaap** [comment]
Are the folders correctly symlinked? What do you see if you run `ls -1latrh` ?

**Comment by martijngastkemper** [comment]
Do you run PHP-FPM and didn't you reload it?

**Comment by alexmro** [comment]
> Are the folders correctly symlinked? What do you see if you run `ls -1latrh` ?

So, once I have release 1, 2, 3, these are the symlinks

drwxrwxr-x 6 bitnami root    4.0K Nov 30 12:58 ..
drwxr-xr-x 3 bitnami bitnami 4.0K Feb 18 20:17 shared
drwxr-xr-x 5 bitnami bitnami 4.0K Feb 21 20:15 releases
lrwxrwxrwx 1 bitnami bitnami   10 Feb 21 20:15 current -> releases/3
drwxr-xr-x 5 bitnami bitnami 4.0K Feb 21 20:16 .
drwxr-xr-x 2 bitnami bitnami 4.0K Feb 21 20:16 .dep

and at this point I no longer see the changes. Even if I clear laravel views and everything with `clear:optimize`. It only worked for release/1 and release/2. Now I have to clear everything and run the pipeline again (until I get to release/3)

**Comment by peterjaap** [comment]
Could you run this to check all symlinks? `ls -lR /path/to/folder | grep ^l`

**Comment by alexmro** [comment]
> Could you run this to check all symlinks? `ls -lR | grep ^l`

I just realized it also happens in production, where it doesn't work even for the second release. I push the first release, it works. I push the second one and I don't see the changes.

This is what the ls `-lR | grep ^l ` command outputs:

```
lrwxrwxrwx 1 bitnami bitnami   10 Feb 22 20:51 current -> releases/2
lrwxrwxrwx  1 bitnami bitnami     20 Feb 21 23:10 storage -> ../../shared/storage
lrwxrwxrwx 1 bitnami bitnami   67 Feb 21 23:10 storage -> /opt/bitnami/apache/htdocs/production/releases/1/storage/app/public
lrwxrwxrwx 1 bitnami bitnami 27 Feb 21 23:10 carbon -> ../nesbot/carbon/bin/carb on
lrwxrwxrwx 1 bitnami bitnami 35 Feb 21 23:10 commonmark -> ../league/commonmark/bin/commonmark
lrwxrwxrwx 1 bitnami bitnami 36 Feb 21 23:10 jp.php -> ../mtdowling/jmespath.php/bin/jp.php
lrwxrwxrwx 1 bitnami bitnami 33 Feb 21 23:10 php-parse -> ../nikic/php-parser/bin/php-parse
lrwxrwxrwx 1 bitnami bitnami 22 Feb 21 23:10 psysh -> ../psy/psysh/bin/psysh
lrwxrwxrwx 1 bitnami bitnami 51 Feb 21 23:10 var-dump-server -> ../symfony/var-dumper/Resources/bin/var-dump-server
lrwxrwxrwx  1 bitnami bitnami     20 Feb 22 20:51 storage -> ../../shared/storage
lrwxrwxrwx 1 bitnami bitnami   67 Feb 22 20:51 storage -> /opt/bitnami/apache/htdocs/production/releases/2/storage/app/public
lrwxrwxrwx 1 bitnami bitnami 27 Feb 22 20:51 carbon -> ../nesbot/carbon/bin/carbon
lrwxrwxrwx 1 bitnami bitnami 35 Feb 22 20:51 commonmark -> ../league/commonmark/bin/commonmark
lrwxrwxrwx 1 bitnami bitnami 36 Feb 22 20:51 jp.php -> ../mtdowling/jmespath.php/bin/jp.php
lrwxrwxrwx 1 bitnami bitnami 33 Feb 22 20:51 php-parse -> ../nikic/php-parser/bin/php-parse
lrwxrwxrwx 1 bitnami bitnami 22 Feb 22 20:51 psysh -> ../psy/psysh/bin/psysh
lrwxrwxrwx 1 bitnami bitnami 51 Feb 22 20:51 var-dump-server -> ../symfony/var-dumper/Resources/bin/var-dump-server

```

Btw, the pipeline does this (for production)

```
- apt-get update && apt-get install -y unzip git git-core openssh-client rsync
- curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
- composer install
- composer global require deployer/deployer
- composer global require deployer/recipes
- vendor/bin/phpunit
- /root/.composer/vendor/bin/dep deploy production
```

**Comment by peterjaap** [comment]
Hm I don't see anything strange there. Are you running opcache or similar? Are the changes you're not seeing PHP changes or frontend changes?

**Comment by alexmro** [comment]
I think I am on a track here and it's probably permissions related.

So, I have these settings for the file permissions and ownership:

```
set('writable_use_sudo', true);
set('clear_use_sudo', true);
set('cleanup_use_sudo', true);
set('http_group', 'daemon');
set('http_user', 'daemon');
```

Now, the user with SSH access is _bitnami_ but the Apache runs as _daemon_.
When files are sent to the server, they belong to _bitnami/bitnami_ user/group. File generated later inside the cache folder (like cached views inside the shared folder) have _daemon/daemon_ user/group and sometimes _daemon/bitnami_.

The problem is that _bitnami_ user cannot clear the cache files (belonging to _daemon_) and I don't understand why?

**Comment by antonmedv** [comment]
Yes, it’s strange what laravel not showing an error. Did you managed to find root cause?

**Comment by antonmedv** [comment]
I’m closing this as a stale. Please, reopen if needed.

**Comment by alexmro** [comment]
The solution was to limit 'keep_releases' to 1. I don't even need more than one and looks like this works. Thanks for closing it

**Comment by gtsiou** [comment]
From what I can tell, this has to do with php-fpm OPcache and Realpath cache like @martijngastkemper mentions. I cannot figure out why this started happening on the Deployer 7 beta but I had never seen this before at least. Could be also something changed with the latest PHP versions (> 7.3).

I am experiencing this with both wordpress and magento while keeping 3 releases, so not Laravel specific. Debian 10, Apache 2.4, PHP both 8 and 7.4 can replicate.

There are workarounds based on the vhost configuration (https://medium.com/hackernoon/truly-atomic-deployments-with-nginx-and-php-fpm-aed8a8ac1cd9) but I am pretty sure this https://github.com/deployphp/deployer/pull/2487 will do the trick.
