### ISSUE TITLE
shopware: task sw:plugin:activate:all runs migration script in wrong order

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2423]
If I deploy I have migration scripts which connect languages with sales_channels. Unfortunately is my module the first in the list and therefore called first. I added the dependency into the composer.json but of course this is ignored.

Solution (I'm goin to implement now) is, to parse all composer.json files and calculate the correct order to activate/update the modules

**Comment by Schrank** [comment]
@peterjaap If you have ideas/opinions on that, please tell me, happy to spend the time on the weekend not solving a problem we don't have 😂

**Comment by Schrank** [comment]
Can I assume there exists a composer.lock on the server? Without it, there is no autoload, etc. correct?

**Comment by peterjaap** [comment]
> Can I assume there exists a composer.lock on the server? Without it, there is no autoload, etc. correct?

Yes you can safely assume that.
