### ISSUE TITLE
Improve documentation/homepage

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2424]
- Use versions in the documentation
- Mark incomplete sections in the documentation (e.g. 'This section is incomplete', 'This section requires examples' etc). This way users are aware that it isn't complete, and at the same time potential contributors know how to contribute.
- Provide some steps for contributors to contribute properly (i.e. how to build and test the project locally on your pc). I noticed a pull request #2267 where the contributor doesn't know how to make a test. And for me, I know some php and the code base seems to be very clearly written, but I have no idea how to modify and then build the source code again. Adding a small guide (if possible just provide links to existing guides and make remarks for the changes) could really help to make contributing easier.

@jamieburchell @memen45 Thanks for this. I hope I'll find some time to take care of this, because I have the same problems currently setting up a new shopware project 😅

**Comment by antonmedv** [comment]
Well, we have new website already. :)
