### ISSUE TITLE
Show execution time during execution of receipt

### ISSUE THREAD

**Issue by kanevbg** [deployphp/deployer#2426]
Show the execution time for each task from the executing receipt in CLI.
Show total execution time at the end of execution.
The time measured show be the actual time passed

**Comment by Schrank** [comment]
Short info for you, with -vv or -vvv your get times:
https://github.com/deployphp/deployer/blob/master/src/Executor/Messenger.php#L61

but it is a good idea to have a --time parameter or something so we don't have everything else of -vvv one isn't interested in.

**Comment by antonmedv** [comment]
We have a —profile option. Does it gelp?

**Comment by antonmedv** [comment]
And also you can run deployer with `-vv`.
