### ISSUE TITLE
Magento 2 recipe permissions 

### ISSUE THREAD

**Issue by memen45** [deployphp/deployer#2431]
- Deployer version: 6.8.0
- Deployment OS: Ubuntu 20.04 LTS / WSL2 / Windows 10

Use the default magento2 recipe in deploy.php with 
set('http_group', 'www-data'); 
set('writable_mode', 'chgrp'); 
set('writable_recursive', true);

The deploy:writable will fix permissions for directories ('var', 'pub/static', 'pub/media', 'generated') by doing chgrp . Then deploy:magento task will be called, adding some directories (most importantly var/page_cache/*). Since - based on Magento guidelines - the deploy is executed with the deploy user, these new directories will have deploy:deploy as owner, while deploy:www-data would be desired. Every new deployment will face this problem again.

Current workaround:
Add `after('deploy:magento', 'deploy:writable');` to the deploy.php file.

Directory structure in var after deploy:writable and before deploy:magento
```
lrwxrwxrwx  1 deploy deploy     27 Feb 25 19:50 backups -> ../../../shared/var/backups
lrwxrwxrwx  1 deploy deploy     25 Feb 25 19:50 cache -> ../../../shared/var/cache
lrwxrwxrwx  1 deploy deploy     33 Feb 25 19:50 composer_home -> ../../../shared/var/composer_home
lrwxrwxrwx  1 deploy deploy     26 Feb 25 19:50 export -> ../../../shared/var/export
lrwxrwxrwx  1 deploy deploy     34 Feb 25 19:50 import_history -> ../../../shared/var/import_history
lrwxrwxrwx  1 deploy deploy     32 Feb 25 19:50 importexport -> ../../../shared/var/importexport
lrwxrwxrwx  1 deploy deploy     23 Feb 25 19:50 log -> ../../../shared/var/log
lrwxrwxrwx  1 deploy deploy     26 Feb 25 19:50 report -> ../../../shared/var/report
lrwxrwxrwx  1 deploy deploy     27 Feb 25 19:50 session -> ../../../shared/var/session
lrwxrwxrwx  1 deploy deploy     23 Feb 25 19:50 tmp -> ../../../shared/var/tmp
drwxrwxr-x 10 deploy www-data 4.0K Feb 25 19:51 vendor
```
Directory structure after deploy:magento
```
lrwxrwxrwx  1 deploy deploy     27 Feb 25 19:29 backups -> ../../../shared/var/backups
drwxrwxr-x  3 deploy deploy   4.0K Feb 25 19:34 cache
lrwxrwxrwx  1 deploy deploy     33 Feb 25 19:29 composer_home -> ../../../shared/var/composer_home
lrwxrwxrwx  1 deploy deploy     26 Feb 25 19:29 export -> ../../../shared/var/export
lrwxrwxrwx  1 deploy deploy     34 Feb 25 19:29 import_history -> ../../../shared/var/import_histor                  y
lrwxrwxrwx  1 deploy deploy     32 Feb 25 19:29 importexport -> ../../../shared/var/importexport
lrwxrwxrwx  1 deploy deploy     23 Feb 25 19:29 log -> ../../../shared/var/log
drwxrwxr-x  3 deploy deploy   4.0K Feb 25 19:31 page_cache
lrwxrwxrwx  1 deploy deploy     26 Feb 25 19:29 report -> ../../../shared/var/report
lrwxrwxrwx  1 deploy deploy     27 Feb 25 19:29 session -> ../../../shared/var/session
lrwxrwxrwx  1 deploy deploy     23 Feb 25 19:29 tmp -> ../../../shared/var/tmp
drwxrwxr-x 10 deploy www-data 4.0K Feb 25 19:30 vendor
drwxrwxr-x  3 deploy deploy   4.0K Feb 25 19:33 view_preprocessed
```

As you can see, page_cache (and some other directories) have deploy:deploy as owner, but should have deploy:www-data (just like vendor).

**Comment by peterjaap** [comment]
The `deploy:writable` tries to find your web-user based on running processes, see here: https://github.com/deployphp/deployer/blob/6d357e94b63878f0e310b763b6ac55a21babfa20/recipe/deploy/writable.php#L6

Maybe for some reason it picks the wrong user? You could also try setting the `writable_mode` to `chgrp` to base permissions on group settings; https://github.com/deployphp/deployer/blob/6d357e94b63878f0e310b763b6ac55a21babfa20/recipe/deploy/writable.php#L67

Eitherway, this doesn't seem like a Deployer bug, but a configuration issue on your end.

**Comment by memen45** [comment]
As you can see, I have set the http_group to www-data and the mode to chgrp. I have added the deploy user to the www-data group. I am not sure whether Deployer or just the Magento recipe is 'at fault', since they both work as expected. However, in the end the permissions are not correct, and with the defined orders (first deploy:writable, then create directories with user deploy:deploy during deploy:magento) I would not expect them to have group www-data. However one ends up with an internal server error after a successful deploy, due to var/page_cache not writable.

Either the Magento recipe could be updated to address this. However, as there is no deploy.php example for magento2, this issue could also just help create others a better (i.e. working) deploy.php file.

**Comment by antonmedv** [comment]
So, who is making wrong permission. I did not get it.

**Comment by memen45** [comment]
No one is setting the permissions on directories that are created during `deploy:magento`. The purpose of the task `deploy:writable` is to set those permissions, but it is executed before those folders exist.

All files and directories during the task `deploy:magento` have deploy:deploy as owner.
The folders specified in 'writables' should have deploy:www-data as owner (with settings `set('http_group', 'www-data');` `set('writable_mode', 'chgrp');` `set('writable_recursive', true);`)

**Comment by antonmedv** [comment]
I see. So changing order will help?  Cam we create pr and add magento devs for discussion?

**Comment by memen45** [comment]
Yes, indeed. However the deploy:writable is not explicitly mentioned in the deploy:magento task list, so probably it is implied with these lines [magento2.php#L183-185](https://github.com/deployphp/deployer/blob/4ac6e131ccaa7044f538440926808fc13d312497/recipe/magento2.php#L183)

According to the [default flow](https://deployer.org/docs/flow.html), the deploy:vendors is performed after the deploy:writable task. I think however that deploy:vendors might create some of the writable (sub)directories? If so, that would mean not only magento2 recipe has this issue, but any recipe following the default flow might run into this if writable subdirectories are created during deploy:vendors or later tasks.

**Comment by antonmedv** [comment]
Docs can be outdated))
