### ISSUE TITLE
change access modifier Configuration\fetch() to public

### ISSUE THREAD

**Issue by freywald** [deployphp/deployer#2433]
Hello Anton Medvedev,

could you make \Deployer\Configuration\Configuration\fetch() a public method? In the v6 releases there was the concept of collections and I was able to get the raw (non-parsed()) "uninterpreted" configuration value. In v7 there seems to be no other way, but a public fetch() works fine for me.

Thanks!

**Comment by freywald** [comment]
On a second though, it's much better to create a separate more complete method (or add a flag to get() to optionally not use parse).

Something like this:
```
	/**
	 * @param mixed|null $default
	 * @return mixed|null
	 */
	public function getRaw(string $name, $default = null)
	{
		if (array_key_exists($name, $this->values)) {
			if (is_closure($this->values[$name])) {
				return call_user_func($this->values[$name]);
			} else {
				return $this->values[$name];
			}
		}

		if ($this->parent) {
			$rawValue = $this->parent->fetch($name);
			if ($rawValue !== null) {
				if (is_closure($rawValue)) {
					return call_user_func($rawValue);
				} else {
					return $rawValue;
				}
			}
		}

		if ($default !== null) {
			return $default;
		}

		throw new ConfigurationException("Config option \"$name\" does not exist.");
	}
```

**Comment by freywald** [comment]
Something else I've noticed. My getRaw() does not cache the value – get() does. I had a case where get('branch') was called (it's defined as a closure, but there was no context available, so the closure returned ''). Then the '' value was cached although by the next call get('branch') may have been eventually successfully returning the correct value. I think not caching it even with get() is preferable.

**Comment by antonmedv** [comment]
You have a point for not caching, but usually get closure performe run command, so it’s better to cache it. Line current_path is called a lot.

**Comment by antonmedv** [comment]
Adding no parse or raw param is ok i think.

**Comment by freywald** [comment]
Yes, it might be important for some to have a slight performance increasement that desires caching, I understand. 
But I've seen cases where this goes wrong (I'm not saying I'm doing nothing wrong in any case) and would love to have it optional, for example set('configuration_cache_enabled', TRUE); could be the default setting. Or maybe set(string $name, $value, bool $isCached=TRUE) gets a third parameter which controls caching.

Previously in v6, the Collection::get() was not caching its values.
I think it's important when having get(...,isRaw: true) in v7 there is no caching at all. But we need to make sure, when we've previously called get(..., isRaw: false) followed by get(..., isRaw: true) we're not retrieving the cached value.

In any case, controlling the caching regardless of an eventual raw mode is very good for my use case.

**Comment by antonmedv** [comment]
I agree. Let’s think of some cache control mechanism.

**Comment by antonmedv** [comment]
I went the easy way: made fetch public. :)
