### ISSUE TITLE
Task success renamed to deploy:success

### ISSUE THREAD

**Issue by ostrolucky** [deployphp/deployer#2437]
- Deployer version: v7.0.0-beta.13
- Deployment OS: Debian 9

I'm trying out deployer 7.x and there seems to be some change that is undocumented at https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md

I have following code:

```php
after('deploy', 'success');
```

however this stopped working with error

```
In TaskCollection.php line 20:

  [InvalidArgumentException]
  Task `success` not found.

```

**Comment by ostrolucky** [comment]
Looks like new name is `deploy:success`

**Comment by ostrolucky** [comment]
Another BC break:

```
[localhost]   Call to undefined function Deployer\isDebug()
```

**Comment by antonmedv** [comment]
Is yes, not it’s output()-isDebug

**Comment by antonmedv** [comment]
Updated doc.
