### ISSUE TITLE
Deployer 7 doesn't list nested tasks

### ISSUE THREAD

**Issue by ostrolucky** [deployphp/deployer#2438]
- Deployer version: v7.0.0-beta.13
- Deployment OS: Debian 9

```
vagrant@shopping:/vagrant/deployer-example$ php vendor/bin/dep deploy
task deploy
task deploy:dev
[localhost] info successfully deployed!
```

This says it's executing deploy:dev, but doesn't say what's happening after that. deploy:dev looks like following:

```
task('deploy:dev', [
    'configuration',
    'prepare',
    'configtest',
    'migration',
    'services',
    'crontab',
    'postdeploy'
])->select('stage='.getDefaultStage());
```

Running deploy:dev manually, it then finally lists other tasks that deploy:dev is executing. However, they also have subtasks that deployer 7 is not showing...
```
vagrant@shopping:/vagrant/deployer-example$ php vendor/bin/dep deploy:dev
task configuration
task prepare
task configtest
task migration
task services
task crontab
task postdeploy
```

**Comment by ostrolucky** [comment]
This looks to be because of select() not matching, so even though it would be nice if deployer mentioned in logs that it's skipping something, issue is on my side I guess. Sorry for creating unnecessary issue.

**Comment by antonmedv** [comment]
There is a —plan option to show what tasks will be included. 

Try: dep deploy —plan
