### ISSUE TITLE
[Deployer 7] Selector is lacking support for arrays

### ISSUE THREAD

**Issue by ostrolucky** [deployphp/deployer#2439]
deploy.php:
```php
task('foo', function() {
    info('yes!');
})->select('roles=foo');

localhost()
    ->set('labels', ['roles' => ['foo', 'bar', 'baz']]);
```

```
vagrant@shopping:/vagrant/deployer-example$ php vendor/bin/dep foo -vvv
task foo
 TypeError  in Selector.php on line 67:

  Deployer\Selector\Selector::compare(): Argument #2 ($a) must be of type ?string, array given, called in /vagrant/deployer-example/vendor/deployer/deployer/src/Selector/Selector.php on line 58

#0 /vagrant/deployer-example/vendor/deployer/deployer/src/Selector/Selector.php(58): Deployer\Selector\Selector::compare()
#1 /vagrant/deployer-example/vendor/deployer/deployer/src/Executor/Master.php(90): Deployer\Selector\Selector::apply()
#2 /vagrant/deployer-example/vendor/deployer/deployer/src/Command/MainCommand.php(119): Deployer\Executor\Master->run()
#3 /vagrant/deployer-example/vendor/symfony/console/Command/Command.php(256): Deployer\Command\MainCommand->execute()
#4 /vagrant/deployer-example/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#5 /vagrant/deployer-example/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#6 /vagrant/deployer-example/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#7 /vagrant/deployer-example/vendor/deployer/deployer/src/Deployer.php(289): Symfony\Component\Console\Application->run()
#8 /vagrant/deployer-example/vendor/deployer/deployer/bin/dep(105): Deployer\Deployer::run()
#9 {main}
```

This makes Deployer 7.x unusable for us. We used to do
```php
task('foo', function() {
    info('yes!');
})->onRoles('foo');

localhost()
  ->roles('foo', 'bar', 'baz');
```

and now there doesn't seem to be alternative

**Comment by ostrolucky** [comment]
@antonmedv This is quite important for us. What are your thoughts? How about this: Remove a typehint so it accepts both array and string. If it's array, it loops through values and checks if `foo` matches one of it's elements. So that with `roles=foo` it would check in a loop  `role==foo`, `role==bar`, `role==baz` and if any of those is true, return true.

**Comment by Schrank** [comment]
@ostrolucky I'm not into that topic, but did you try $host->set('roles', ['db', 'app']) 

I tried to understand the code but can't do that asap. But in any case that should be possible, so either `$host->set('roles', ['db', 'app']) ` works or this is a bug we (as in you and us :) ) need to fix.

**Comment by Schrank** [comment]
P.S. Thanks for the report, good catch! Although annoying

**Comment by ostrolucky** [comment]
>  either $host->set('roles', ['db', 'app']) works 

Nope, that unfortunately doesn't work. [Selector accesses labels only](https://github.com/deployphp/deployer/blob/27c7b6182c77ed69059bffee8b2e288526ccde67/src/Selector/Selector.php#L46)

I've created a PR which should fix this issue
