### ISSUE TITLE
[Deployer 7] GroupTask via invoke() is ignored

### ISSUE THREAD

**Issue by ostrolucky** [deployphp/deployer#2445]
- Deployer version: 1669ffb11d6b176dbc00bebf915af1327d6f557d

This works in Deployer 6.x, but not 7.x

```php
task('baz', function() {
    info('baz');
});
task('quix', function() {
    info('quix');
});
task('bar', ['baz', 'quix']);

task('foo', function() {
    invoke('bar');
});

localhost();
```

Output:
```
task foo
task bar
```

Expected output:
```
task foo
task bar
task baz
[localhost] info baz
task quix
[localhost] info quix
```

**Comment by antonmedv** [comment]
Are you sure what it work in v6?  Invoke was just call to one task, no hooks and no group tasks. But as v7 is still going on we can add support for group tasks.

**Comment by ostrolucky** [comment]
yep i'm sure

**Comment by antonmedv** [comment]
Can somebody create a pr with fix?

**Comment by ostrolucky** [comment]
PR created
