### ISSUE TITLE
Task {{user}} outputting no_user

### ISSUE THREAD

**Issue by josephlewisnz** [deployphp/deployer#2449]
- Deployer version:  6.8.0
- Deployment OS:  Debian docker

Hey there, I am just trying to create a backup/save from remote task. However, I am not getting the host "user" during running

```
task('savefromremote', function () {
    writeln('host: {{hostname}}');
    writeln('user: {{user}}');
    writeln('stage: {{stage}}');
    // runLocally('rsync -az {{user}}@{{hostname}}:{{backup_latest}} place_to_sync_on_local_machine');
});
```

This is my host setup

```
set('default_stage', 'staging');

host('mydomain.com')
    ->user('mysshuser')
    ->stage('staging')
    ->roles('app');
```

I would expect this "savefromremote" task to output "mysshuser" instead it is outputing "no_user"

`dep savefromremote` 
![image](https://user-images.githubusercontent.com/57464168/110409046-7bf11880-80eb-11eb-9a7f-78f5d20361b4.png)

Any ideas? or am I approaching this wrong?

**Comment by antonmedv** [comment]
Hi, your approach is correct, I think something wrong in user() helper. 

In v7 it was renamed to remote_user and works as expected.

**Comment by antonmedv** [comment]
I’m closing this as a stale. Please, reopen if needed.
