### ISSUE TITLE
if the ip addresses of the two hosts are the same, prod will not be found

### ISSUE THREAD

**Issue by tlerbao** [deployphp/deployer#2456]
- Deployer version: 6.8.0
- Deployment OS:MacOS
![image](https://user-images.githubusercontent.com/20442232/110946755-401fb280-837a-11eb-867d-98d128d7bced.png)
As shown in the figure, if the ip addresses of the two hosts are the same, prod will not be found

**Comment by antonmedv** [comment]
You can use host aliases for it.

**Comment by Schrank** [comment]
https://deployer.org/docs/hosts.html#one-host-for-a-few-stages

**Comment by Schrank** [comment]
Hope that helps :-)

**Comment by tlerbao** [comment]
@Schrank Thanks for the answer. There are always various errors in deploy:vendors. How can I solve it or is there anything I need to pay attention to?
![image](https://user-images.githubusercontent.com/20442232/110949326-70b51b80-837d-11eb-9911-e4c4321e063a.png)

**Comment by Schrank** [comment]
I'm not at all into these packages and my understanding of composer is, that this is not allowed to happen, but it seems you have an incompatible set of dependencies?

The only reason I can imagine this happens is, that the php version which the last composer update ran on it not the same as the server one and therefore the server tries to install other package version which can't find a compatible combination

You can force composer to use a specific PHP version to resolve the packages:
https://stackoverflow.com/a/54736948/1480397

Maybe that helps, good luck!

**Comment by tlerbao** [comment]
![image](https://user-images.githubusercontent.com/20442232/110962592-196a7780-838c-11eb-9abf-b35ad851e525.png)
New problem, after running dep deploy, it got stuck in deploy:vendors, it took a long time, and finally failed.

I try to manually ssh to the server and execute composer install. It is ok. What's the problem?

**Comment by Schrank** [comment]
dep deploy -vvv helps 

I might be, that your server takes too long and composer is running into a timeout. https://deployer.org/docs/api.html#run
