### ISSUE TITLE
Cannot run version 3

### ISSUE THREAD

**Issue by pbudzon** [deployphp/deployer#246]
I tried running version 2, but the composer install doesn't work. So I switched to 3.0.0-beta.

I have the following issue when trying to run `vendor/bin/dep`:

```RuntimeException: Object `deploy:start` does not exist in ScenarioCollection.```

Happens on `v3.0.0-beta.4` and `v3.0.0-beta.5`.

I tried using all 3 scenarios (common, composer and symfony) and each of them gives this kind of issue.

This basically means that there's no version of deployer that can be install with composer and used successfully :(

**Comment by oanhnn** [comment]
Dear @pbudzon 
Version `v3.0.0-beta.5` is out of date, please try `dev-master`

**Comment by pbudzon** [comment]
I get the following error when running with  `dev-master`:

```
PHP Fatal error:  Call to undefined method Deployer\Server\Builder::path() 
```

Stack trace:
```
PHP Stack trace:
PHP   1. {main}() /Users/paulina/Sites/pgsql/vendor/deployer/deployer/bin/dep:0
PHP   2. require() /Users/paulina/Sites/pgsql/vendor/deployer/deployer/bin/dep:59
```

Triggered by calling `server()->path()` in `deploy.php`.

**Comment by elfet** [comment]
@pbudzon Deployer now have another API. (Docs will be ready soon.) 
Try use in:
```php
server(...)->env('deploy_path', ...);
```
