### ISSUE TITLE
deploy:unlock takes a long time to return an error

### ISSUE THREAD

**Issue by benoitchantre** [deployphp/deployer#2460]
- Deployer version: 6.8
- Deployment OS: Ubuntu 20.4

I'm using the common receipe with Github action to deploy.

When there's an SSH connexion issue, the deploy fails as expected and `deploy:unlock` is triggered.

The issue is that it takes a long time before the error appears with the `deploy:unlock` task.

I have tried to reduce the connection timeout, but it doesn't help. Any idea what to try?

```
inventory( 'config/hosts.yml' )
	->addSshOption('ConnectTimeout', '5');
```

In the output below, the domain name and deploy path have been redacted.
```
➤ Executing task deploy:prepare
[example.com] > echo $0
[example.com] < ssh multiplexing initialization
[example.com] < Permission denied, please try again.
[example.com] < Permission denied, please try again.
[example.com] < runner@example.com: Permission denied (publickey,password).
➤ Executing task deploy:failed
• done on [example.com]
✔ Ok [1ms]
➤ Executing task deploy:unlock
[example.com] > rm -f ~/sites/example.com/.dep/deploy.lock
[example.com] < ssh multiplexing initialization
...
The command "rm -f ~/sites/example.com/.dep/deploy.lock" failed.
Exit Code: -1 (Unknown error)
...
ssh: connect to host example.com port 22: Connection timed out
```

Thanks for your help

--

Update : when `ConnectTimeout` is set in `./ssh/config`, the custom value is used and the task can fails sooner.

**Comment by antonmedv** [comment]
I can’t reproduce, looks like issue with your side.

**Comment by benoitchantre** [comment]
Thank you for your quick reply @antonmedv.

I'll do more testing and update/close this issue.

**Comment by benoitchantre** [comment]
I did more tests and found that adding the SSH option to the inventory doesn't work

```php
inventory( 'config/hosts.yml' )
	->addSshOption('ConnectTimeout', '5');
```

But when it's added to an host defined in deploy.php, the option works as expected.
