### ISSUE TITLE
Setting options with a callback no longer works as expected: Config option "xxx" does not exist when using a function call

### ISSUE THREAD

**Issue by leevigraham** [deployphp/deployer#2462]
- Deployer version: v7.0.0-beta.15
- Deployment OS: osx
- Reproduction Repo: https://github.com/leevigraham/deployer-bug

Setting options with a callback no longer works as expected.

Run:

✅ Success -> `vendor/bin/dep test static -vvv`
❌ Fail -> `vendor/bin/dep test function -vvv`

Deployer.php:

```php
namespace Deployer;

localhost('function')
    ->set('db_password', function() {
        return 'password';
    });

localhost('static')
    ->set('db_password', 'password');

task('test', function() {
    runLocally('echo "{{ db_password }}"');
});
```

**Comment by antonmedv** [comment]
Yes, you're right. Nice catch. Will try to look at this today evening.

**Comment by antonmedv** [comment]
Fixed! Please update and test.

**Comment by leevigraham** [comment]
Seems to be working :)
