### ISSUE TITLE
No such file or directory error when adding folders to shared_dir config

### ISSUE THREAD

**Issue by thinkcube-solutions** [deployphp/deployer#2465]
- Deployer version:  6.8.0
- Deployment OS: Ubuntu 20.04.2 LTS x86_64

Hello! I keep getting errors whenever I add a new **shared_dir** folder on a new deploy. I have some folders that are not tracked by git so I am not sure if that is what is causing the issue. I don't recall it being a problem in the past. I just had some image folders on the live site that are dynamically populated with image uploads by writers so I wanted those linked between each release.

I get the following error:

In Client.php line 103:
                                                                                                  
  The command "ln -nfs --relative /var/www/staging.api.com/shared/public_html/assets/img  
  /blogs/single/ /var/www/staging.api.com/releases/3/public_html/assets/img/blogs/single/" failed.                                                                        
                                                                                                  
  Exit Code: 1 (General error)                                                                    
                                                                                                  
  Host Name: deployer                                                                 
                                                                                                  
  ================                                                                                
  ln: target '/var/www/staging.api.com/releases/3/public_html/assets/img/blogs/single/' is not a directory: No such file or directory       

Here is what I have set in my shared_dir config

```
set('shared_dirs', [
  'public_html/assets/img/blogs/single/',
  'public_html/assets/img/blogs/360/',
  'public_html/assets/img/blogs/applications/',
  'public_html/assets/img/articles/',
  'public_html/assets/img/social-shares/',
  'public_html/assets/downloads/',
]);
```

**Comment by antonmedv** [comment]
Looks like dir public_html/assets/img/blogs/single/ doesn’t exist in your repository.

**Comment by thinkcube-solutions** [comment]
> Looks like dir public_html/assets/img/blogs/single/ doesn’t exist in your repository.

Thank you for the quick reply. That is correct it does not. Is there no way to share folders that do not exist in the repository? I was trying to keep the repo size down for certain directories that contain large image files such as PDFs that currently do not need to be tracked.

**Comment by antonmedv** [comment]
You can create custom task to create missing dir in release.

**Comment by thinkcube-solutions** [comment]
> You can create custom task to create missing dir in release.

Thanks. I did that and when I run the deploy again, it does get rid of the error. However, while the folders are there, the files from the previous release/current folder's path are not pulled into that shared directory.
