### ISSUE TITLE
While deploying github CI show the next error Error: Call to undefined function Deployer\host() in /home/timur/actions-runner/queue/queue.backend/queue.backend/deploy.php 

### ISSUE THREAD

**Issue by timur265** [deployphp/deployer#2472]
- Deployer version: 6.8.0
- Deployment OS: Linux 18.04

   This is my host part:
   host('nq.alif.tj')
    ->hostname('192.168.13.178')
    ->stage('staging')
    ->roles('app')
    ->user('timur')
    ->set('branch', 'develop')
    ->set('deploy_path', '/var/www/p');
    
    It works when I deploy from my local machine
    The deployer installation and ssh connection are passing well:

    Run atymic/deployer-php-action@master
    - Install Deployer [1/2]
    - Install Deployer [1/2]
    - Setup SSH [2/2]
    - Install Deployer [1/2]
    - Setup SSH [2/2]
    - Install Deployer [1/2]
    - Setup SSH [2/2]
    
     But then I get this error
     Error: Call to undefined function Deployer\host() in                   
         /home/timur/actions-runner/_work/queue.backend/queue.backend/deploy.php
         :35                                                                    
         Stack trace:                                                           
         #0 /home/timur/.config/composer/vendor/deployer/deployer/bin/dep(115): 
         require()                                                              
         #1 /home/timur/.config/composer/vendor/deployer/deployer/bin/dep(116): 
         {closure}
         

Do you know what can be the reason?

**Comment by antonmedv** [comment]
No, something with autoloading in your setup.

**Comment by timur265** [comment]
Got it. Thanks

**Comment by yb1506** [comment]
> Got it. Thanks

Hi, I have a similar issue, can you tell your solution? would be great, thx

**Comment by antonmedv** [comment]
Add namespace Deployer;

**Comment by yb1506** [comment]
I've already added namespace Deployer;

**Comment by timur265** [comment]
Hi
