### ISSUE TITLE
Bundle recipe dependencies in PHAR

### ISSUE THREAD

**Issue by jankal** [deployphp/deployer#2473]
- Deployer version: 6.8.0
- Deployment OS: Debian 10

The `shopware` recipe requires the `marcj/topsort` package to be present. This package is not present in the phar's `vendor` directory thus leading the `shopware` recipe unusable with the PHAR release.

Error:
```
[Error] Class 'MJS\TopSort\Implementations\FixedArraySort' not found
```

**Comment by Schrank** [comment]
The shopware recipe in the master is for deployer version 7, may I offer you a beta part built? :-)

[deployer.phar.zip](https://github.com/deployphp/deployer/files/6195674/deployer.phar.zip)

**Comment by jankal** [comment]
@Schrank my bad! Thank you, I'll try the v7 beta.
