### ISSUE TITLE
Prevent deployer running cache:clear 

### ISSUE THREAD

**Issue by VinceG** [deployphp/deployer#2475]
- Deployer version: 6.7.3
- Deployment OS: Mac -> Linux

Currently deployer laravel recipe runs `php artisan cache:clear` on each deploy, this is insane since a cache store is used for various things such as the queue manager, session etc.. we have a task that should override the cache clear task

```
task('artisan:cache:clear', function () {
    writeln('Cache clear disabled');
});
```

but recently it stopped working and cache:clear actually runs on the servers.

anyway to disable this?

**Comment by amayer5125** [comment]
Are you overwriting the `deploy` task? The default deploy task does not call `artisan:cache:clear`.

https://github.com/deployphp/deployer/blob/v6.7.3/recipe/laravel.php#L209-L225
