### ISSUE TITLE
Shell commands should probably include bang

### ISSUE THREAD

**Issue by pbudzon** [deployphp/deployer#248]
Hi!

The deployer 2.X doesn't work when trying to deploy on server that does not use sh/bash as a default shell (like many *BSD machines). Because of that, commands like this:
```
run("if [ ! -d $(echo $basePath) ]; then mkdir $basePath; fi", true);
```
die with errors like
```
[RuntimeException]      
  Illegal variable name.  
````

This can be simply prevented by adding bang (`#!/bin/sh `) before the actual command.
For example:
```
run("#!/bin/sh \n if [ ! -d $(echo $basePath) ]; then mkdir $basePath; fi", true);
```

runs perfectly fine :)

**Comment by elfet** [comment]
Ok. Cool one :+1: I thing need to add some parameter with pre_run name or similar.

**Comment by pbudzon** [comment]
It doesn't work with version 3 though :( 

To prevent this from not working for people, I'd suggest doing something like `echo $SHELL` before running the commands to make sure the shell we are connected to is compatible with `sh`. For example `/bin/tcsh` is not :) 
This while issue can be simply solved by the user by setting a default shell for the user to something compatible (sh, bash, etc). But giving people a warning would be nice.

**Comment by elfet** [comment]
Can you create PR with shell cheking and warning? This will be so great! :green_apple:

**Comment by pbudzon** [comment]
Will do!

**Comment by elfet** [comment]
Thanks you a lot! :)

**Comment by Max-Might** [comment]
I just noticed that the exception is thrown when `{{deploy_path}}` does not exist on the server.
This will confuse people. Maybe we should check with `/tmp` or `/home` or something else.

**Comment by elfet** [comment]
Done: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L61
