### ISSUE TITLE
Output of stdout/stderr incorrect order 

### ISSUE THREAD

**Issue by marvinhinz** [deployphp/deployer#2482]
- Deployer version: 6.8
- Deployment OS: Debian 10

I am not sure if this is a bug or intended behaviour, but its at least inconsistent behaviour. When an exception is thrown (or when response code is not zero?) the output of stdout and stderr is split apart. This alone can be inconvenient. 

With runLocally the output contains always both streams, regardless of verbosity level. Using run without verbose prints only stderr, with full verbosity it prints the ssh log containing both streams, and appends the same runtimeexception with stderr.

To reproduce this i prepared a minimal symfony console script that outputs 4 alternating test lines, two are printed into stdout and the other two to stderr at last an \Exception is thrown:

```
(new SingleCommandApplication())
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $stderr = $output instanceof ConsoleOutputInterface ? $output->getErrorOutput() : false;
        $output->writeln('STDOUT: <comment>TEST 1</comment>');
        $stderr->writeln('STDERR: <comment>TEST 2</comment>');
        $output->writeln('STDOUT: <comment>TEST 3</comment>');
        $stderr->writeln('STDERR: <comment>TEST 4</comment>');
        throw new \Exception("This is an exception\ntest");
    })->run();
```

This produces the following output when run manually:

![image](https://user-images.githubusercontent.com/35603466/112907121-9cf6c900-90ed-11eb-9896-53fecd7eff1c.png)

When the test script is run with runLocally the output looks like this (no difference with or without -vvv):

![image](https://user-images.githubusercontent.com/35603466/112907620-7be2a800-90ee-11eb-8f95-3b26db265c1e.png)

When the test script is run over ssh with run the output looks like this:

![image](https://user-images.githubusercontent.com/35603466/112907907-e5fb4d00-90ee-11eb-9f64-c1a1c7736e6c.png)

same as the above with -vvv:
![image](https://user-images.githubusercontent.com/35603466/112908223-720d7480-90ef-11eb-8b48-c907b5fe5d7d.png)

**Comment by antonmedv** [comment]
Can you also check this in master  branch. It nay be fixed there.

**Comment by marvinhinz** [comment]
This is the output for deployer 7 beta 16:

testLocal
![image](https://user-images.githubusercontent.com/35603466/112982132-67d58f80-915c-11eb-9f29-0ad2cdb964bc.png)


testLocal -vvv
![image](https://user-images.githubusercontent.com/35603466/112982938-5b056b80-915d-11eb-8fbb-a5f7c3e366b1.png)


testRemote
![image](https://user-images.githubusercontent.com/35603466/112982618-f77b3e00-915c-11eb-85a3-b803a93977b5.png)


testRemote -vvv
![image](https://user-images.githubusercontent.com/35603466/112982758-22659200-915d-11eb-9fa1-0d9ee357927a.png)

**Comment by antonmedv** [comment]
I think this is how Symfony process component is handling std err/out. Not possible to fix in Deployer.

**Comment by antonmedv** [comment]
I think this is a Symfony Process related issue.
