### ISSUE TITLE
Sentry recipe is not able to detect version automatically

### ISSUE THREAD

**Issue by jnugh** [deployphp/deployer#2484]
- Deployer version: v7.0.0-beta.16
- Deployment OS: MacOS (latest)

The default `update_code` changed it's behavior in version 7. There is no .git directory in `{{release_path}}`anymore which breaks the sentry recipe if no explicit version number is being provided.

```php
function releaseIsGitDirectory()
{
    return (bool) run('cd {{release_path}} && git rev-parse --git-dir > /dev/null 2>&1 && echo 1 || echo 0');
}
```

This should probably be documented somewhere or maybe a version could be extracted in `update_code` and stored for later use or something. I will now use an env variable that comes from our CI so documentation would have been enough in my case :)

**Comment by antonmedv** [comment]
Yes, one way is to read RELEASE file which contains rev.

**Comment by antonmedv** [comment]
Actually, what about saving revision in the config of a host during update_code task?

**Comment by jnugh** [comment]
Yeah, potentially. As I said in my case I'm now using data from our CI system and set it as a config before deployment but an old config breaks if it uses sentry and does not specify a version. So you mean add it to the default update_code task? (e.g. here: https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php#L76)

There is also this function https://github.com/deployphp/deployer/blob/master/contrib/sentry.php#L213 `getGitCommitsRefs` which reads a list of differences from both repos which will also not work after updating.

Just looked at `update_code` did you mean `.dep/releases` in the previous comment? So using the ref from update_code as well as the previous one from the `.dep/releases` file both values could be generated and stored for further action like the sentry recipe.

**Comment by mortenscheel** [comment]
I'm using this workaround to insert the deployed revision:
```php
set('sentry', [
    // ...
    'version' => function() {
        return trim(run("awk 'END {print $5}' FS=, {{deploy_path}}/.dep/releases"));
    },
]);
```

It would certainly be a lot easier if the value was stored in a variable automatically during `deploy:update_code`

**Comment by antonmedv** [comment]
Now there is {{release_revision}} variable which hops git ref. Can someone update the recipe to support it?

**Comment by shakalandy** [comment]
> 

Hi Anton,

I'm currently trying this one out and will create PR if it works.

I changed the default value of 'version' in sentry.php to "release_version":

```        $defaultConfig = [
            'version' => ('{{release_revision}}'),
```
Was this the change you meant by your comment?

Trying it out on CLI it seems to work:

```
[staging] Sentry: Release of version 5fc4a38f7b98e30e7ccf2311f722b514abcdc32e for projects: example-web created successfully.
[staging] Sentry: Deployment 13 for environment prod created successfully
```

But sentry has not received a "new release" for that. The releases page doesn't get updated with the version from above.
This has worked before using "dummy values" as version.

Do you see any error?

**Comment by antonmedv** [comment]
I can’t test it as I don’t use Sentry.

**Comment by antonmedv** [comment]
I can’t test it as I don’t use Sentry.

**Comment by shakalandy** [comment]
Thanks @antonmedv - it does work with the current state in master, but not with the one delivered in "Deployer v7.0.0-rc.3".
There have been some changes to the logic.

With the current RC the output works, but sentry does receive this in it's logs (if somebody else stumbles upon this issue):

``` 
127.0.0.1 - - [05/Jan/2022:18:45:46 +0000] "POST /api/0/organizations/sentry/releases/{{release_revision}}/deploys/ HTTP/1.0" 201 130 "-" "Deployer v7.0.0-rc.3" "XXX.XXX.XXX.XXX"
```

**Comment by antonmedv** [comment]
Release will be soon)
