### ISSUE TITLE
Allowing to specify host as array and not seperate arguments

### ISSUE THREAD

**Issue by fliespl** [deployphp/deployer#2494]
Currenty it's only possible to specify hosts as follows:

`host('a', 'b', 'c')`

it would be great if it would also be possible to specify array.

`host(['a', 'b', 'c'])`

Currently the only workaround is to use such code:

```
call_user_func_array('Deployer\\host', explode(',', getenv('PRODUCTION_DEPLOY_HOSTS')));
```

In our case we have production hosts, which do not follow node1/node2 etc semantics to allow ranges [1-2] in their name.

**Comment by Schrank** [comment]
you can do `host(...explode(',', getenv('PRODUCTION_DEPLOY_HOSTS')))`

**Comment by fliespl** [comment]
Totally forgot about this syntax.... Thanks @Schrank !
