### ISSUE TITLE
The --log flag seems to do nothing

### ISSUE THREAD

**Issue by JackWH** [deployphp/deployer#2495]
- Deployer version: 7.0.0-master
- Deployment OS: Ubuntu 20.04.2 LTS
- Deployer installation: Composer global package
- PHP version: 8.0

When I call `dep deploy --log=deployer.log`, Deployer deploys as expected — but no `deployer.log` file is created or written to. There's no difference if the file exists beforehand, either.

However, calling `dep deploy --profile=profile.log` *does* write profile details to a `profile.log` file (whether it exists previously or not).

**Comment by antonmedv** [comment]
Fixed in 457eb6d0749e8bdb7aeacaac07ab60a95a4388b3

**Comment by antonmedv** [comment]
Also released in https://github.com/deployphp/deployer/releases/tag/v7.0.0-beta.20
