### ISSUE TITLE
upload/download - return output

### ISSUE THREAD

**Issue by fliespl** [deployphp/deployer#2497]
Sometimes it might be needed to get only final stats and not progress of rsync command.

Currently we can only do it by using verbose flag which is a bit noisy + changing upload configs flags to -az and adding --stats to options (or alternatively use rsync contrib recipe which also would need some code overwriting since it doesn't return run / runLocally output as well).

```
    upload(__DIR__ . "/bin/", '{{release_path}}', [
        'options' => ['--stats'],
        'flags' => '-az'
    ]);
```

If would be great if upload / download were returning final output so anyone can use it as desired if needed.

**Comment by antonmedv** [comment]
Nice idea! Or maybe as a configurable option? Can you create a PR for it?

**Comment by fliespl** [comment]
Sure, will try to figure it out over the weekend.

**Comment by Schrank** [comment]
May I assume this ticket is fixed @fliespl ? <3 If not please tell me, then I'll reopen.

Thanks for the PR!

**Comment by fliespl** [comment]
@Schrank that's correct :) And you are welcome!
