### ISSUE TITLE
localCD

### ISSUE THREAD

**Issue by lce-fr** [deployphp/deployer#250]
Hi,
Before anything else, thank your for your work ! I like how easy it is to start with your tool without reading tons of documentation : )

I want to use this tool to set up new project both on deploiement server and on my local machine. Therefore I would like to have a way to control local current directory. 

Indeed runLocally('cd my/dir'); does not work.I think I can understand why but It would be nice to supply a locallyCD. 

Kind regards

**Comment by Max-Might** [comment]
Perhaps you could use the local server to deploy the project on your machine?
Check this out: https://github.com/deployphp/deployer/blob/master/src/Server/Local.php

I think the tests use it too.

**Comment by lce-fr** [comment]
Hm even though I found a localServer() function in the repository, it throws me an error when I try to use it. (I self-updated dep)

[edit] And the reason is that I had v2  because I downloaded it from the doc link http://deployer.org/docs which points to v2.

In v2 there is no local or localServer so I will try to see with v3.

**Comment by elfet** [comment]
You can upgrade to v3 by this command: `dep self-update --upgrade --pre`

**Comment by lce-fr** [comment]
Okay so I tried to use the function localServer('myServ');  for my local workflow. 

My rational was that using localServer() allows me usung run and cd function because they will be run on local host. However I got the following exception :

 [RuntimeException]                                    
  Environment parameter `deploy_path` does not exists.

Which I found to be raised because I did not set the working path. Unfortunatly the Builder class no longer has the ->path method which is sadening me :'(

**Comment by lce-fr** [comment]
But you're not done with me yet ! 

I would be very happy if I could register tasks with the server I want. like

task('local:init, $myLocalServe, function(){
   //etc
}

of just simply be able to call server or serverLocal inside task callbacks.

I am aware that is not very useful as I can have two separate files with local tasks and remote tasks but some deploiements requires local tasks such as running tests locally before deploying.

**Comment by oanhnn** [comment]
Dear @lce-fr 
On deployer v3, please try:
```php
task('local:init', function(){
    //etc
})->onlyOn(['local-svr']);
```
Goodluck!!!

**Comment by elfet** [comment]
Now `runLocally` you can you like this: 
```php
runLocally('cd {{path}} && do-stuff');
```

I think we do not need `localCD`.
