### ISSUE TITLE
get('branch') when run locally returns hidden chars in beta.17

### ISSUE THREAD

**Issue by leevigraham** [deployphp/deployer#2505]
This commit: https://github.com/deployphp/deployer/commit/b6b8eacef51a7d7014ce5cbe8cba96a488ce5a29 seems to have caused an issue in our deployments.

I'm running zsh (not bash) in phpstorm terminal and the value returned for `runLocally` to get the branch contains ansii escape sequence and hidden characters:

`(B[mmain`

![Screen Shot 2021-04-15 at 15 49 12](https://user-images.githubusercontent.com/25124/114820361-374f5000-9e02-11eb-904d-79b16001d3b2.png)

The solution for me was the manually set a default branch `set('branch', 'main');` in my config.

For reference: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences

**Comment by antonmedv** [comment]
What dep version are you using?

**Comment by leevigraham** [comment]
> What dep version are you using?

beta.20 but anything from beta 17 causes the issue.

**Comment by antonmedv** [comment]
Can you try to run same command in same Symfony Process component?

**Comment by tuupola** [comment]
You could also check that your `.profile` does not output anything.
