### ISSUE TITLE
.env.local.php in Symfony recipe

### ISSUE THREAD

**Issue by victor-paumier** [deployphp/deployer#2506]
Hi !

I'm a bit confused with the .env.local.php value in the shared_files of the Symfony recipe (and regarding #1907 and #1923 i am probably not the only one :p)

For me, this file should not be include here, as it have to be generate using the symfony:dump-env command (which is part of Symfony/Flex, see https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-production) in order to compile the .env file which is versioned, with the .env.local which is stored on the server.

The problem here is that if you add a new bundle requiring a new env value, deploy:vendors will fail as the .env.local.php will not include it even if you already added it to your .env.local, because .env.local.php will be called first. And it is not possible to generate a new .env.local.php as the vendors aren't installed yet.

For me, the best solution would be to remove the .env.local.php file from the shared_files, create a deploy:dump-env task and call it just after the deploy:vendors task

**Comment by Schrank** [comment]
So if I get that correct, then we want to share .env.local between deployments and run  `composer dump-env prod` on each deployment?

**Comment by victor-paumier** [comment]
Yes, exactly!

```
set('shared_files', ['.env.local']);
```

And

```
desc('Compile .env files');
task('deploy:dump-env', function () {
    run('cd {{release_path}} && {{bin/composer}} dump-env {{symfony_env}}');
});

```

**Comment by Schrank** [comment]
Sounds good! Do you want to provide a PR? Would be a blast! <3

**Comment by Cryde** [comment]
Hi 
Just for you to know, it cause a regression : we now need to define `symfony_env` (that doesn't exist in version `v7.0.0-beta.20`)

**Comment by antonmedv** [comment]
@Cryde I've added symfony_env in c23688adcfb6050dcf847bc58bf6adfac3b68147, Thanks for noticing!

**Comment by Cryde** [comment]
Thank you (and the other contributors) for all your work !
