### ISSUE TITLE
Can't access to {{release_path}}

### ISSUE THREAD

**Issue by amsolucionesweb** [deployphp/deployer#251]
I defined a custom task en my deploy.php script

```php
task('deploy:clear_redis', function () {
    run("php {{release_path}}/app/console redis:flushall --env={{env}} --no-debug --no-interaction");
})->desc('Redis flushall');
```
When the task is executed `dep deploy -vvv` I get a RuntimeException, the command run in the server is:
 
`cd /var/www/vhosts/site.com/httpdocs && php {{release_path}}/app/console redis:flushall --env={{env}} --no-debug --no-interaction`

The release path is not replaced by physically path.

**Comment by elfet** [comment]
`{{ ... }}` available only in v3.
