### ISSUE TITLE
Deploy stuck in bitbucket piplines on prepare (ssh: 1: ssh: not found)

### ISSUE THREAD

**Issue by apiotrowski** [deployphp/deployer#2515]
My deploy is stuck when I use pipline in bitbucket on second task deploy:prepare with such error. 

In other hand when I execute this manually from my ubuntu, everything is working properly. Is anybody use deployer to deploy application using bitbucket pipline and could help me with such issue.  Thanks in advance

**host configuration (I replace my ip address with three dots sign just for call issue):**
host('...')
    ->hostname('...')
    ->user('...')
    ->identityFile('~/.ssh/bitbucket_pipline')
    ->stage('production')
    ->port(57185)
    ->set('deploy_path', '/var/www/html/project')
    ->set('branch', 'master')
    ->addSshOption('UserKnownHostsFile', '/dev/null')
    ->addSshOption('StrictHostKeyChecking', 'no');

**my task configuration for desired deploy:**
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

**bitbucket pipline logs:**
`<1s
+ /usr/local/bin/dep deploy production -vvv
✈︎ Deploying master on ...
• done on [...]
➤ Executing task deploy:prepare
[...] > echo $0
[...] < sh: 1: ssh: not found
➤ Executing task deploy:failed
• done on [...]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[...] > rm -f /var/www/html/project/.dep/deploy.lock
[...] < sh: 1: ssh: not found
In Client.php line 103:
                                                                           
  [Deployer\Exception\RuntimeException (-1)]                               
  The command "rm -f /var/www/html/project/.dep/deploy.lock" failed.  
                                                                           
  Exit Code: -1 (Unknown error)                                            
                                                                           
  Host Name: ...                                                     
                                                                           
  ================                                                         
  sh: 1: ssh: not found                                                    
                                                                           
Exception trace:
  at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Ssh/Client.php:103
 Deployer\Ssh\Client->run() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/functions.php:304
 Deployer\run() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/recipe/deploy/lock.php:30
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Task/Task.php:105
 Deployer\Task\Task->run() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Console/TaskCommand.php:157
 Deployer\Console\TaskCommand->execute() at /opt/atlassian/pipelines/agent/build/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /opt/atlassian/pipelines/agent/build/vendor/symfony/console/Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at /opt/atlassian/pipelines/agent/build/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /opt/atlassian/pipelines/agent/build/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at /opt/atlassian/pipelines/agent/build/vendor/deployer/deployer/src/Deployer.php:326
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:136
 require() at /usr/local/bin/dep:4`

**Comment by Schrank** [comment]
Good morning!

Your docker image doesn't support ssh.

You can use this as a base:

image: php:7.4-cli

```
pipelines:
  default:
    - step:
        name: PHPUnit
        caches:
            - composer
        script:
            - apt-get update && apt-get install -y libssh2-1-dev git unzip
            - git clone https://github.com/php/pecl-networking-ssh2.git /usr/src/php/ext/ssh2 && docker-php-ext-install ssh2
            - docker-php-ext-install -j$(nproc) ssh2
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --ignore-platform-reqs
            - php --version
            - vendor/bin/dep --version
            - vendor/bin/dep deploy stage -vvv```

**Comment by antonmedv** [comment]
Pretty obvious: ssh: not found

**Comment by Schrank** [comment]
Thanks for being explicit!:-)
