### ISSUE TITLE
Command "dump-env" is not defined

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#2517]
- Deployer version: v7.0.0-beta.22
- Deployment OS: Ubuntu

Dumping of `.env` recently introduced in Symfony recipe is too opinionated.
Symfony doesn't require to use `.env` files, so such step should be made optional.

**Comment by Schrank** [comment]
Thanks! Does it make sense to check for the command and if existibg call it?

alternative would be to not make it a default step but comment it iut, so ppl can include it?

other ideas? Opinion on these options?

**Comment by garak** [comment]
> Thanks! Does it make sense to check for the command and if existibg call it?

checking for it can be a good compromise.

**Comment by antonmedv** [comment]
Or maybe just remove task? It pretty simple.

**Comment by Schrank** [comment]
Cc @victor-paumier opinions?

**Comment by victor-paumier** [comment]
I agree that using the `.env` files is as optional as using the `dump-env` command.
These are just best practice recommendations, like the doctrine migration task, so making the task optional and letting users include it sounds good to me.

**Comment by garak** [comment]
It works since the release of beta.23
Thanks!
