### ISSUE TITLE
Git version below 2.2 breaks on initial deploy

### ISSUE THREAD

**Issue by Sterioss** [deployphp/deployer#2521]
- Deployer version: 7.0.0-beta.22 / 7.0.0-beta.23
- Deployment OS: Linux to Linux

Using dep deploy on a sub 2.2 git version throws this error : 

`[prod]  error  in update_code.php on line 68:
[prod] run cd .dep/repo && (/usr/bin/git remote get-url origin)
[prod] err error: Sous-commande inconnue : get-url
[prod] err usage : git remote [-v | --verbose]
`

Going back to 7.0.0-beta.21 fixes the issue,
Here is the breaking change location.

https://github.com/deployphp/deployer/commit/da8bb1adffab871c94305c47d34beb10ac2c51da#diff-603dddef04f285d9a2ff024cb7bbe3d8c242011d0f7bca49a00446d769033325L73

**Comment by antonmedv** [comment]
Fixed in https://github.com/deployphp/deployer/pull/2520
