### ISSUE TITLE
Error message "Call to undefined method Deployer\Host\Localhost::stage()"

### ISSUE THREAD

**Issue by zeitakuhoshitsu** [deployphp/deployer#2523]
- Deployer version: v7.0.0-beta.23
- Deployment OS:Amazon Linux release 2 (Karoo)

Hi. I am using laravel8.
I updated the deployer from 6.8 to 7, and when I tried deploying in the staging environment, I got the following error and could not deploy.

> $ vendor/bin/dep deploy staging -vvv
> 
>  Error  in deploy.php on line 33:
> 
>   Call to undefined method Deployer\Host\Localhost::stage()
> 
> #0 /var/www/my-progect/vendor/deployer/deployer/src/Importer/Importer.php(44): require()
> #1 [internal function]: Deployer\Importer\Importer::Deployer\Importer\{closure}()
> #2 /var/www/my-progect/vendor/deployer/deployer/src/Importer/Importer.php(53): call_user_func()
> #3 /var/www/my-progect/vendor/deployer/deployer/src/Deployer.php(299): Deployer\Importer\Importer::import()
> #4 /var/www/my-progect/vendor/deployer/deployer/bin/dep(105): Deployer\Deployer::run()
> #5 {main}

In deployer.php, line 33 looks like this.

`localhost('local-staging')
    ->stage('staging')
    ->set('branch', 'master')
    ->set('deploy_path', '/var/www/staging.{{application}}');`

I did not see such an error in 6.8. Is there a mistake in my writing?

**Comment by antonmedv** [comment]
> Call to undefined method Deployer\Host\Localhost::stage()

I think this is a problem. 

Please follow guide on https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md to upgrade from 6 to 7.
