### ISSUE TITLE
Slack notification branchname duplication

### ISSUE THREAD

**Issue by tuupola** [deployphp/deployer#2531]
- Deployer version: 7.0.0-master
- Deployment OS: masOS Mojave

Currently when deploying the {{target}} paremeter is the branchname. Since the default Slack notification is:

```php
  set('slack_text', '_{{user}}_ deploying `{{branch}}` to *{{target}}*');
 ```
 The resulting text is:
 
 _Firstname Lastname_ deploying `branchname` to *branchname*.

**Comment by antonmedv** [comment]
Fixed!
