### ISSUE TITLE
Npm fails

### ISSUE THREAD

**Issue by ahmadmayahi** [deployphp/deployer#2535]
- Deployer version: 6.8.0
- Deployment OS: macOS BigSur 11.3

The following task fails without giving a reasonable reason:
```php
task('build:npm', function () {
    run('cd {{release_path}} && npm install && npm run prod');
});
```

Error message:
```bash
  The command "cd ~/mysite/releases/4 && npm install && npm run prod" failed.

  Exit Code: 127 (Command not found)

  Host Name: xx.xx.xx.xx

  ================
  bash: line 1: npm: command not found
```

Both `npm` and `node` do exist in the following paths:
```bash
which node
/home/web/.nvm/versions/node/v16.0.0/bin/node

which npm
/home/web/.nvm/versions/node/v16.0.0/bin/npm
```

**Comment by antonmedv** [comment]
Verify what npm in path for non-login shell. 

Also please check with dep v7.

**Comment by klaasnicolaas** [comment]
Did you ever found a solution? I run into the same problem in the 7.x versions.

**Comment by Schrank** [comment]
Easiest fix: use absolute paths. If this works, the problem is your $PATH variable.

**Comment by jawira** [comment]
Same here. I even used absolute paths, but then I got this error:

> In Client.php line 103:
> 
>   [Deployer\Exception\RuntimeException (127)]
>   The command "cd /var/www/myproject/releases/5 && (/home/myuser/.nvm/versions/node/v12.22.7/bin/npm install --production)" failed.
> 
>   Exit Code: 127 (Command not found)
> 
>   Host Name: xxxxxxxx
> 
>   ================
>   /usr/bin/env: ‘node’: No such file or directory

So `npm` can't found `node`. 

I used `nvm` to install `npm`.

**Comment by jawira** [comment]
In my case the problem was `nvm`:

1. I uninstalled `nvm` (including `node` & `npm`) as described in https://github.com/nvm-sh/nvm/issues/298
2. Use PPA to install `node` and `nvm` as described in https://github.com/nodesource/distributions#installation-instructions
3. Done, deployer works like a charm :)

**Comment by matiasvelizb** [comment]
If you still wants to use NVM in the older versions without much configuration, you need to source it everytime you run a command, since deployer is working with a non interactive shell.

I did this small workaround to avoid uninstalling nvm.

```
// NVM source, must be called every run command
set('nvm', 'source $HOME/.nvm/nvm.sh &&');

task('test', function () {
    $test = run("{{nvm}} npm --version");
    writeln($test);
});
```

**Comment by Mickeel** [comment]
> If you still wants to use NVM in the older versions without much configuration, you need to source it everytime you run a command, since deployer is working with a non interactive shell.
> 
> I did this small workaround to avoid uninstalling nvm.
> 
> ```
> // NVM source, must be called every run command
> set('nvm', 'source $HOME/.nvm/nvm.sh &&');
> 
> task('test', function () {
>     $test = run("{{nvm}} npm --version");
>     writeln($test);
> });
> ```

Thank you @matiasvelizb !
For anyone finding this still a problem, make sure to run all npm related command in the same 'run' command. Because whenever each 'run' command is separate shell session. 

It still works in v7. Attached is our implementation.

```
// NVM source location
set('nvm', 'source $HOME/.nvm/nvm.sh');

// Must be called in every run command related to npm
// Note: do not separate run command, as it is accounted as different shell session
set('use_nvm', function () {
    return '{{nvm}} && node --version && nvm use 18';
});

// Tasks
desc('Installs npm packages');
task('npm:install', function () {
    run('{{use_nvm}} && cd {{release_path}} && npm ci');
});

desc('Build production assets');
task('npm:prod', function () {
    run('{{use_nvm}} && cd {{release_path}} && npm run prod');
});
```

**Comment by olivier1208** [comment]
> > If you still wants to use NVM in the older versions without much configuration, you need to source it everytime you run a command, since deployer is working with a non interactive shell.
> > I did this small workaround to avoid uninstalling nvm.
> > ```
> > // NVM source, must be called every run command
> > set('nvm', 'source $HOME/.nvm/nvm.sh &&');
> > 
> > task('test', function () {
> >     $test = run("{{nvm}} npm --version");
> >     writeln($test);
> > });
> > ```
> 
> Thank you @matiasvelizb ! For anyone finding this still a problem, make sure to run all npm related command in the same 'run' command. Because whenever each 'run' command is separate shell session.
> 
> It still works in v7. Attached is our implementation.
> 
> ```
> // NVM source location
> set('nvm', 'source $HOME/.nvm/nvm.sh');
> 
> // Must be called in every run command related to npm
> // Note: do not separate run command, as it is accounted as different shell session
> set('use_nvm', function () {
>     return '{{nvm}} && node --version && nvm use 18';
> });
> 
> // Tasks
> desc('Installs npm packages');
> task('npm:install', function () {
>     run('{{use_nvm}} && cd {{release_path}} && npm ci');
> });
> 
> desc('Build production assets');
> task('npm:prod', function () {
>     run('{{use_nvm}} && cd {{release_path}} && npm run prod');
> });
> ```

:tada: Awesome !

Here's the YAML version for whom it can help :smirk: 

```yaml
config:
  nvm: 'source $HOME/.nvm/nvm.sh'
  use_nvm: '{{nvm}} && node --version && nvm use 18'

tasks:
  npm:install:
    script:
      - '{{use_nvm}} && cd {{release_path}} && npm ci'

  npm:prod:
    script:
      - '{{use_nvm}} && cd {{release_path}} && npm run prod'

```
