### ISSUE TITLE
Deploy fails with multiplexing enabled

### ISSUE THREAD

**Issue by Gamesh** [deployphp/deployer#2536]
- Deployer version: 6.8.0
- Deployment OS: Debian 9.13

```
export APP_ENV='stage' APP_DEBUG='0'; if [ -f /var/www/*************/.dep/deploy.lock ]; then echo 'true'; fi
< ssh multiplexing initialization
< Warning: Permanently added '**************,***.***.***.**' (ECDSA) to the list of known hosts.
< unix_listener: cannot bind to path /root/.ssh/deployer_deployer@**************.LiZt386qtCUqfmHr: No such file or directory
```

deploy example:

```
host('**************')
    ->stage('stage')
    ->set('deploy_path', '/var/www/stage-{{application}}')
    ->multiplexing(true)
    ->addSshOption('UserKnownHostsFile', '/dev/null')
    ->addSshOption('StrictHostKeyChecking', 'no')
    ->user('deployer');
```

when i disable multiplexing it works again

**Comment by antonmedv** [comment]
> unix_listener: cannot bind to path /root/.ssh/deployer_deployer@**************.LiZt386qtCUqfmHr: No such file or directory

Looks like a problem on your side.

**Comment by Gamesh** [comment]
Isn't it a socket that deployer is creating? 

It worked before like a charm, and only recently for some reason stopped, not sure maybe some OS update broke it

**Comment by antonmedv** [comment]
Try to run with dep -vvv, there will be ssh commands. Get failing one and try to debug it. Also with -v.

**Comment by Gamesh** [comment]
that's all ssh commands i already posted it fails on initial connection, there are no more command and it's already run with `-vvv`

it probably fails on `ssh multiplexing initialization` it's not visible what it tries to do there
```
APP_VERSION=$CI_COMMIT_SHORT_SHA php dep.phar deploy -vvv stage
➤ Executing task deploy:lock
[*******] > export APP_ENV='stage' APP_DEBUG='0'; if [ -f /var/www/stage-*******/.dep/deploy.lock ]; then echo 'true'; fi
[*******] < ssh multiplexing initialization
[*******] < Warning: Permanently added '*******,176.223.130.25' (ECDSA) to the list of known hosts.
[*******] < unix_listener: cannot bind to path /root/.ssh/deployer_deployer@*******.LiZt386qtCUqfmHr: No such file or directory
➤ Executing task deploy:failed
• done on [*******]
✔ Ok [0ms]
```

**Comment by antonmedv** [comment]
I see. Try to use v7 beta, it has much more debug output for -vvv.

**Comment by Gamesh** [comment]
it's not compatible with v6.8 config, for example:
Call to undefined method Deployer\Host\Host::stage()

it seems stage method got renamed or removed, not sure. so can't run it without an upgrade guide to update my deploy.php file

**Comment by antonmedv** [comment]
It is here: https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md

**Comment by Gamesh** [comment]
> It is here: [https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md?rgh-link-date=2021-05-03T22%3A05%3A06Z)

oh, was looking for it in the tagged revision of v7. Will give it another shot, thanks

**Comment by Gamesh** [comment]
so i see:

```
[********] ssh -O check '-o' 'StrictHostKeyChecking=no' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' echo 2>&1
[********] Control socket connect(/dev/shm/c23391cf8ed674d30387b9b151b3b49b1fd01b37): No such file or directory
[********] ssh multiplexing initialization
[********] ssh -N '-o' 'StrictHostKeyChecking=no' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' deployer@********
[********] Control socket connect(/dev/shm/c23391cf8ed674d30387b9b151b3b49b1fd01b37): No such file or directory
```
dir for the socket seems to have changed, but no idea why it doesn't work

**Comment by antonmedv** [comment]
Try to tun it

ssh -N '-o' 'StrictHostKeyChecking=no' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' deployer@********
[

**Comment by Gamesh** [comment]
```
Authenticated to ****************** ([****************]:22).
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /dev/shm/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.DuxhauuFGI7k1sjq
unix_listener: cannot bind to path /dev/shm/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.DuxhauuFGI7k1sjq: No such file or directory
```

does not seem to show anything useful, will try restarting server tonight

**Comment by antonmedv** [comment]
I think problem with a path for socket  /dev/shm/
Try changing it. Don’t remember if it possible.

**Comment by Gamesh** [comment]
yes if i change the path to /tmp it works without issues
```
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /tmp/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.x6yIunMRwJs0XfSQ
```
so i guess one can't just create a socket anywhere he pleases

**Comment by Gamesh** [comment]
`-o ControlPath=~/.ssh/control-%h-%p-%r` also works fine, maybe the filename it creates with `%C` is too long, read about it somewhere

**Comment by Gamesh** [comment]
> ControlPath
>              Specify the path to the control socket used for connection sharing as described in the ControlMaster section above or the string none to disable connection
>              sharing.  Arguments to ControlPath may use the tilde syntax to refer to a user's home directory or the tokens described in the TOKENS section.  It is recom-
>              mended that any ControlPath used for opportunistic connection sharing include at least %h, %p, and %r (or alternatively %C) and be placed in a directory that
>              is not writable by other users.  This ensures that shared connections are uniquely identified.

it's written in the manual that socket should be placed in the directory not writable by other users, so is it a good idea to use `/dev/shm` by default?

and in v6 it tried to place it in a path `/root/.ssh/` but deployer is not root, so it can't , why would it even attempt to use root

**Comment by antonmedv** [comment]
If I remember correctly, /dev/shm used as fallback for CI systems.

**Comment by Gamesh** [comment]
not sure what do you mean, socket is created on the server we're deploying to, not on CI we're deploying from. Why should it be /dev/shm when deploying from CI

found this
```
* Return SSH multiplexing control path
     *
     * When ControlPath is longer than 104 chars we can get:
     *
     *     SSH Error: unix_listener: too long for Unix domain socket
     *
     * So try to get as descriptive path as possible.
     * %C is for creating hash out of connection attributes.
     */
    private static function generateControlPath(Host $host): string
    {
        // In case of CI environment, lets use shared memory.
        if (getenv('CI') && is_writable('/dev/shm')) {
            return '/dev/shm/%C';
        }
```

so it doesn't look like a length issue:
`/dev/shm/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.DuxhauuFGI7k1sjq` is 66 chars long, but somehow it passes is_writable check but fails in the end

**Comment by sluxzer** [comment]
hey there, is there any fix for this? i update my deployer to the latest beta, and error below is showed

> ```
> Authenticated to ****************** ([****************]:22).
> debug1: setting up multiplex master socket
> debug3: muxserver_listen: temporary control path /dev/shm/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.DuxhauuFGI7k1sjq
> unix_listener: cannot bind to path /dev/shm/c3af3e3b12dac4cae54c9f980f01b8eddd1f5ae8.DuxhauuFGI7k1sjq: No such file or directory
> ```
> 
> does not seem to show anything useful, will try restarting server tonight

**Comment by antonmedv** [comment]
Let's keep track in #2680

**Comment by seyuf** [comment]
Hi there IMO this can be assimilated to a bug? As the deployer in v6 is trying to use `/root/.ssh` for no apparent reason? As mentioned by @Gamesh. Also he proposed a PR @antonmedv why not simply accept the free help? As nothing seems to be going on in #2680 ... 
Regards

**Comment by antonmedv** [comment]
Yes, we can try to fix the issue. As this issue not wide spread it’s difficult propose a fix. 

Let’s create a pr with a fix?

**Comment by seyuf** [comment]
Thanks for the speedy response.
I just found out why the deployer is try the /root/.ssh.
The deployer already does try to get the current remote user [see here](https://github.com/deployphp/deployer/blob/85b771fb9fb778e6fa774656da6ce21748ce74ac/src/Host/Host.php#L246).
But, unfortunately, if RemoteUser is not set in the `~/.ssh/config` file or if the [remote_user](https://deployer.org/docs/7.x/hosts#remote_user) is not in the config of the deployer, the code replaces it with the current os username (i.e the host running the deployer). In our case because we run the deployer from github-actions the root user gets picked up instead of the ssh actual remote user. So a workaround would be to fill one of the config files.

**Comment by seyuf** [comment]
@antonmedv i've just migrated from v6 to v7. This issue is fixed in that version. So i think  #2680 is no longer relevant.
Thanks for this project and even the others 🙏

**Comment by antonmedv** [comment]
Awesome!
