### ISSUE TITLE
require php in composer.json

### ISSUE THREAD

**Issue by smknstd** [deployphp/deployer#2538]
I don't see "php" in composer.json, why is that ?

https://github.com/spatie/package-skeleton-php/blob/master/composer.json#L18

**Comment by antonmedv** [comment]
We can add it.

**Comment by amayer5125** [comment]
It looks like [bin/dep](https://github.com/deployphp/deployer/blob/master/bin/dep#L16-L24) checks to make sure the PHP version is at least 7.3. Some of the tests use named parameters so deployer might work with PHP 7.3, but if you want to work on the project and run the tests you need at least php 8.0.

[This commit](https://github.com/deployphp/deployer/commit/387b4c1d511006932a7a495b714e8b7072dd43f9#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L47) seems to have removed the php version. If we want to add it back, should we add `"php": ">=7.3"` or `"php": ">=8.0"`?

**Comment by Schrank** [comment]
Tests don’t matter, what version is needed to run the software. (I don’t know) this is the version we add 😅

**Comment by antonmedv** [comment]
There was a reason why it wws deleted))
