### ISSUE TITLE
Issue with executing on Windows 10

### ISSUE THREAD

**Issue by 3579km** [deployphp/deployer#2540]
**Environment:** Windows 10, Powershell 5.1, PHP7.2, Deployer 6.8.0

**Issue:** Can't execute specific custom command run on Windows 10 powershell
Command example: `task('deploy_windows:react_app_build', function () {
    run('cd backend/react-app | npm install');
});`

- Command from Windows powershell cli directly works correctry `cd backend/react-app | npm install`
- Command for linux works correctly: `task('deploy:react_app_npm', function () {
    run('cd $PWD/backend/react-app && npm install');
});`

**Comment by Schrank** [comment]
Can you please run the command with -vvv so we see the difference?

Thanks in advance!

**Comment by 3579km** [comment]
- When running directly from powershell terminal in the projects root directory: 

`cd backend/client-apps | ng build --prod`

Result: works good

- When running from deploy.php file in the projects root directory:

`dep deploy . -vvv`

Task example:
`task('deploy_windows:ng build', function () {
    run('cd backend/client-apps | ng build --prod');
});`
 
Result: error

```[Symfony\Component\Process\Exception\ProcessFailedException]
  The command "cd backend/client-apps | ng build --prod" failed.

  Exit Code: 1(General error)

  Working directory: C:\Server\apps\study-space

  Output:
  ================


  Error Output:
  ================
  Unable to find "@angular/cli" in devDependencies.

  Please take the following steps to avoid issues:
  "npm install --save-dev @angular/cli@latest"

  node_modules appears empty, you may need to run `npm install`
