### ISSUE TITLE
v7 - Custom ssh config host names warnings

### ISSUE THREAD

**Issue by iBotPeaches** [deployphp/deployer#2544]
- Deployer version: v7 beta 23
- Deployment OS: unix

So I have one server with a few projects. When I try and pull them GitHub doesn't allow re-using deployment keys so I did some tricks of leveraging `.ssh/config` to name the host under a specific name.

```
Host project1
        ForwardAgent no
        User git
        HostName github.com
        IdentityFile /home/deploy/.ssh/project1
```
(~/.ssh/config)

So now the new v7 attempts to reach out to these projects even if they aren't valid domains.

```
task deploy:update_code
[prod] run command -v 'git' || which 'git' || type -p 'git'
[prod] /usr/bin/git
[prod] run ssh-keygen -F project1
[prod] run ssh-keyscan -H project1 >> ~/.ssh/known_hosts
[prod] getaddrinfo project1: Name or service not known
[prod] getaddrinfo project1: Name or service not known
[prod] getaddrinfo project1: Name or service not known
[prod] run [ -d /usr/share/nginx/html/.dep/repo ] || mkdir -p /usr/share/nginx/html/.dep/repo
```

**Comment by AngelinCalu** [comment]
Could you please share your "tricks of leveraging .ssh/config"? I am now facing the same situation and trying to get the `.ssh/config` to work.

**Comment by Schrank** [comment]
# .ssh/config
    Host name-you-use-in-deployer.php
            ForwardAgent no
            User git
            HostName realname-or-ip-address
            IdentityFile /home/deploy/.ssh/project1

    # deployer.php
    host('name-you-use-in-deployer.php')
        ->set('hostname', '255.255.255.256')
        ->setRemoteUser('my-user')
        ->setConfigFile('~/.ssh/config')

**Comment by Sander-Toonen** [comment]
I assume that this one is fixed as well by #2667. Can anyone confirm?

**Comment by antonmedv** [comment]
Well. No. But actually what @Schrank suggested is a solution.

**Comment by iBotPeaches** [comment]
@Schrank solution is what I was doing behind the scenes, which was broken in Deployer because it assumed it would be a URL and not a reference to a `.ssh/config` entry.

Either way, this PR does look to resolve that issue, but I no longer run Deployer to confirm.
