### ISSUE TITLE
`get()` throws ConfigurationException when default is passed as `null`

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#2545]
I didn't expect this code would throw a `ConfigurationException: Configuration parameter project_mattermost_hook does not exist` error -  but just return the `null` default-value which was passed in.

```
$mattermostHook = get('project_mattermost_hook', null);
```

- Deployer version: 6.8.0
- Deployment OS: ubuntu20 lts

**Comment by Schrank** [comment]
get checks if the value is null if yes, it throws an exception. I had the same problem already with https://github.com/deployphp/deployer/issues/2525

Easiest fix is to return false. Hope this works in your case as well. If it doesn't work, lets think about how to change it (your code or deployer), but:

I think it is good to throw an exception, so it is easier to find undefined configurations.

Feel free to comment, if needed I'll reopen. Good luck!

**Comment by staabm** [comment]
I would expect deployer to use e.g. https://www.php.net/func_num_args or similar to check whether there was actually a default given from the outside or whether there wasn't
