### ISSUE TITLE
PHP8 support 

### ISSUE THREAD

**Issue by it-can** [deployphp/deployer#2548]
Can you please release a v6.8.1 version of deployer with PHP8 support? thanks!

**Comment by eleftrik** [comment]
Same here. On my laptop I run PHP 8.0 and I had to run `composer require deployer/deployer --dev --ignore-platform-reqs` to install Deployer.

**Comment by it-can** [comment]
> Same here. On my laptop I run PHP 8.0 and I had to run `composer require deployer/deployer --dev --ignore-platform-reqs` to install Deployer.

Yeah and I testes version 7 beta but the upgrade is pretty hard, still getting lot of errors

**Comment by YetiCGN** [comment]
Yeah, that would be awesome! 

+1

**Comment by PlorvenT** [comment]
+1

**Comment by smknstd** [comment]
https://github.com/deployphp/deployer/discussions/2351

**Comment by wickyaswal** [comment]
+1

**Comment by MazzMazz** [comment]
+1

**Comment by gesior** [comment]
+1
on PHP 8.0 it downloads 4.3.4 as last stable version compatible with 8.0 (>=5.6.0)

**Comment by antonmedv** [comment]
Deployer v7 supports php8. V6 is only for php7.

**Comment by ampaze** [comment]
> Deployer v7 supports php8. V6 is only for php7.

Deployer v6 works fine with PHP 8 for me, what exactly is not supported?

**Comment by Schrank** [comment]
Hopefully soon :D https://github.com/deployphp/deployer/issues/2620#issuecomment-897125638

**Comment by YetiCGN** [comment]
@antonmedv Kind request to please reconsider making 6.8 PHP 8 compatible as well. Deployer 7 declares a dependency on Symfony 5, which is totally fine. But this way we cannot use Deployer on a Symfony 4 LTS project and require PHP 8. Symfony 4.4 will be supported until November 2023.

**Comment by Schrank** [comment]
@YetiCGN please consider using phar files of development tools like deployer, phpunit, etc. You don't want your dev-tools to tell you what PHP version/symfony etc. to use :-)

If you want to makle 6.8 PHP8 compatible, feel free, happy to review your PR!

but we don't.

**Comment by antonmedv** [comment]
> If you want to makle 6.8 PHP8 compatible, feel free, happy to review your PR!

I tried to do this once - really difficult, better start using v7.

**Comment by YetiCGN** [comment]
> @YetiCGN please consider using phar files of development tools like deployer, phpunit, etc. You don't want your dev-tools to tell you what PHP version/symfony etc. to use :-)
> 
> If you want to makle 6.8 PHP8 compatible, feel free, happy to review your PR!
> 
> but we don't.

I would still need to keep PHP 7.4 around for `deployer.phar`. And `deploy.php` is part of my code repository, so there is a dependency to a specific Deployer version. I like to keep my project dependencies tightly together and not manually update and maintain dev-tools in lots of versions.

**Comment by Schrank** [comment]
I understand the problem. Then we are back at: Feel free to make a PR :-)

**Comment by YaroslavMolchan** [comment]
@Schrank I see, that v7.0.0-rc.3 has 8.1 support, do you have any plans to release 7.0 version with PHP8 support? It's working fine with 8.0 for me, but I need to use `--ignore-platform-req`, and this is sad.

**Comment by Schrank** [comment]
Yes, 7.0 will be released soon, but beside of that, let my highly recommend to throw out all your build, testing and deployment libs from composer.json and instead use phars… because … you guessed it … dependency hell 😅🤪🙈

**Comment by YetiCGN** [comment]
I think Phar tools hell is "phar" 😉 worse. I have close to 20 projects currently checked out that we still support with a variety of PHP versions, frameworks and tools. It's much easier to have everything installed by `composer install` than to tell the developer (in the `README.md` of course): "For this project you need PHPUnit 7 and CodeSniffer 2.8 or 3.x and Deployer 6.7 or up..."

We've been using Deployer 7 since beta though without problems so I don't see why a stable release is necessarily required. Though it is nice that there's one coming soon and the "RC" tags suggest that it's almost ready, so I appreciate your work. 🙂

**Comment by YetiCGN** [comment]
Aaah, this is great! Thanks for the pointer.

**Comment by kdambekalns** [comment]
> I pack deployer phar into deployer/dist tags.
> 
> Just install it instead, same via composer. But you will get phar archive.

If you talk about https://packagist.org/packages/deployer/dist then I would be put off by this warning:

_This package is abandoned and no longer maintained. The author suggests using the [deployer/deployer](https://packagist.org/packages/deployer/deployer) package instead._
