### ISSUE TITLE
Change packagist name

### ISSUE THREAD

**Issue by oanhnn** [deployphp/deployer#255]
Current, packagist name of deployer is `deployer/deployer`, but packagist name of recipes is `deployphp/recipes`. I think you should rename packgist name to `deployphp/deployer`.

**Comment by elfet** [comment]
Hmm, i think it's better to rename **deployphp/recipes** to **deployer/recipes**.

**Comment by oanhnn** [comment]
But your organization is `deployphp`. I think `deployphp` is more suitable.

**Comment by elfet** [comment]
But project is `Deployer`, and. :fried_shrimp: There are a lot of other projects what has different org name ([silexphp/Silex](https://github.com/silexphp/Silex), ...)

**Comment by oanhnn** [comment]
it looks like someone tried to create `deployer` organization as ghost organization. Have you tried contacts and reporting with github? If not, name `deployer/deployer` do people think that it is `deployer` organization's

**Comment by elfet** [comment]
Not, did not contact Github. What i'm gona say to them? That somebody register org with name what prefer?

**Comment by GrahamCampbell** [comment]
@elfet It's against GitHub's terms to take an account and not do anything with it. They can free it up for you.
