### ISSUE TITLE
Discord recipe

### ISSUE THREAD

**Issue by eleftrik** [deployphp/deployer#2550]
If I'm not wrong, https://github.com/deployphp/recipes have been archived and many recipes have been moved into the main repository. But [here](https://github.com/deployphp/deployer/tree/master/recipe) I don't see Discord recipe listed.
Is it possible to move it to the main repository?

Thank you very much.

**Comment by Schrank** [comment]
Hey! Yes, let’s do that! Would you mind to add one as a PR?
