### ISSUE TITLE
php-ssh composer package is missing?

### ISSUE THREAD

**Issue by Max-Might** [deployphp/deployer#256]
Hello.

There is an error running deployer 3.0 downloaded from the website.

`PHP Fatal error:  Class 'Ssh\Configuration' not found in phar:///home/koce/www/jirarepl/deployer.phar/src/Server/Remote/SshExtension.php on line 47`

Maybe the php-ssh composer package is missing?

**Comment by elfet** [comment]
Yes, truly. `php-ssh` was removed from `deployer.phar` archive. You can install this package via composer. 
Reason is what i'm going to drop support for `ext-ssh2` in new Deployer releases. So Deployer will be 100% php without any extra extensions.
