### ISSUE TITLE
Problem with upload() on Windows

### ISSUE THREAD

**Issue by Max-Might** [deployphp/deployer#257]
Hello.

I have found a problem running `upload()` on windows and uploading a directory (to a linux server).
Lets say I am trying to upload a directory named `module`, which contains a subdirectory called `ApiTester`. And lets say I have a file named `Module.php` in the `ApiTester` directory.

I am uploading it with `upload('module', 'module')`. When I execute the recipe on linux it runs ok but when I execute it on windows something strange happens.

It creates the `module` directory but instead of creating an `ApiTester` subdirectory and a `Module.php` file in it it creates a file named `ApiTester\Module.php` (with a slash in its name!?) in the `module` directory.

I think this happens with the PhpSecLib backend because I do not have the ssh extension installed on this machine.

Edit: I just want to add that this happened on a Windows 8.1 system.

**Comment by elfet** [comment]
Officially Deployer does not support Windows (But it may work).

I know where is problem, in `upload` function. Need to add one `str_replace` to it.

**Comment by elfet** [comment]
Fixed! Now on master branch, soon will be in Deployer 3.0.1.

**Comment by Max-Might** [comment]
Awesome! Thanks. :beer:

**Comment by clphillips** [comment]
Either still broken or is broken again in 3.0.10.

**Comment by oanhnn** [comment]
@elfet reverted by commit https://github.com/deployphp/deployer/commit/c9f3c5d

**Comment by clphillips** [comment]
I really think

```php
$remote = str_replace('\\', '/', $remote);
```

should be

```php
$remote = str_replace(DIRECTORY_SEPARATOR, '/', $remote);
```

Especially considering the comments on 4f16be0

**Comment by elfet** [comment]
Agree! Can you do PR?

**Comment by clphillips** [comment]
@elfet, yup.
