### ISSUE TITLE
Add an option to deploy only a sub-folder of the repository

### ISSUE THREAD

**Issue by Baltazardoung** [deployphp/deployer#2570]
In some projects, we want to deploy only a sub-folder of a git repository (as a deployment root).

Until now, I was using a hook like this (with all the problems associated with the use of "git filter-branch")

```php
task('repository:filter_branch', function () {
    if (has('deploy_repository_path')) {
        run("cd {{release_path}} && {{bin/git}} filter-branch --subdirectory-filter {{deploy_repository_path}} > /dev/null");
    }
})
```

With the new version `7`, this can be simplified by simply adding this option within the "`git archive`" command of `deploy:update_code` :

```php
run("$git archive $at:{{deploy_repository_path}} | tar -x -f - -C {{release_path}} 2>&1");
```

If you are interested, I can try to push a PR.

**Comment by klaasnicolaas** [comment]
It would be really nice if this feature was introduced. My laravel projects are always in a subfolder and because of that I only want to deploy part of the entire project.

Can create a PR, I'm currently testing something on a fork 🤔

**Comment by matsn0w** [comment]
Natively supporting subdirs would be a very big +1!

I was expecting to find a config var for a subdirectory inside `deploy_path`, but as this issue proved this is not the case.

**Comment by matsn0w** [comment]
Created a PR for this! See #2820
