### ISSUE TITLE
Check Laravel, Zend Framework, Yii, WordPress recipes

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#258]
Hi everyone!
Is someone want to check one of new recipes:
* Laravel 
* Zend Framework 
* Yii
* WordPress

**Comment by lasselehtinen** [comment]
Dunno if you targeting to Laravel 4 or 5, but at least for Laravel 5 I probably would add:

set('shared_files', ['.env']);

Laravel 5 uses the [phpdotenv](https://github.com/vlucas/phpdotenv) package. Normally you don't put this in the repo, but create it once. Now with deployer you could put it in shared, so you would only have to create it once and it would be linked after deployment.

One another thing, you might want to create a Laravel spesific 'php artisan migrate' task. Also probably 'php artisan migrate:rollback' should be run if rollback is called.

**Comment by nWidart** [comment]
I wrote a blog post with laravel usage : https://nicolaswidart.com/blog/deploy-your-projects-with-zero-downtime 
I basically have a `.env` file in the shared folder which I copy in the current dir after deployment.

**Comment by oanhnn** [comment]
@nWidart , you have good post by i have some comments ( i can't comment on your blog )
1. In current version (~3.0), `deployer` use 
```php
server('svr-dev', 'example.com', 22)
    ->user('username')
    ->password('pass');
```
not use:
```php
server('svr-dev')
    ->user('username', 'pass');
``` 
We had a few issues with this problems.
2. I think we can use `set('shared_files', ['.env'])` to replace your `environment` task.
3. I think you should update your post and using `laravel` recipe for simple

**Comment by nWidart** [comment]
Thank you for your comments.

1. Cool, will update. I only copied that from the docs as I use the ssh keys myself to log into the server.

2. Not sure, since you still have to tell laravel where to look for this file.

3. Same as `2.`, I tried the laravel recipe, but it didn't work, that's why I did it the manual way. To move the storage directory into the shared folder would require a rewrite of the laravel `Application` class to overwrite those paths.
In 4.2 this was just a config value to change, sadly it's not the case anymore.

**Comment by oanhnn** [comment]
@nWidart , I will debug `laravel` recipe with Laravel 5. :sleepy:

**Comment by nWidart** [comment]
It basically works, it just a matter of extending the `Application` class of laravel to indicate new paths. That, I haven't figured out yet.

Though I still prefer to have my own deploy script to keep fill control over it, instead of using the `laravel` recipe.

**Comment by elfet** [comment]
@nWidart great article! If you can test and refactor `common/laravel.php` recipe, it will be 100% awesome!
