### ISSUE TITLE
get('hostname') returns the identifier of the host, not the URL

### ISSUE THREAD

**Issue by dingo-d** [deployphp/deployer#2582]
- Deployer version:  6.8.0
- Deployment OS: GH Actions Ubuntu 20.04.2 LTS

In my config I have:

```php
host('staging')
	->hostname($stgServerAddress)
	->user($stgServerUser)
	->port($stgPort)
	->stage('staging')
	->roles('app')
	->set('branch', 'staging')
	->set('deploy_path', "~/www/{$stgDeployPath}")
	->addSshOption('UserKnownHostsFile', '/dev/null')
	->addSshOption('StrictHostKeyChecking', 'no');
```

With all the variables defined above in the file. In my task where I execute some scripts on the deployment server, I use `$host = get('hostname');` to retrieve the URL.

However, that returns the `staging` string instead of the URL (which is set as `host` identifier). Am I missing something?

**Comment by antonmedv** [comment]
Yes, it’s confusing and was fixed in v7. 

In v6 user real_hostname.

**Comment by dingo-d** [comment]
Oh forgot about that! The GH action uses 6.8, since 7 is in beta. Will write this down for future update. Thanks!
