### ISSUE TITLE
Composer installation issue

### ISSUE THREAD

**Issue by nspyke** [deployphp/deployer#259]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for deployer/deployer ^3.0 -> satisfiable by deployer/deployer[v3.0.0].
    - deployer/deployer v3.0.0 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
```

Either switch the require to dev-master or the packages version tag.

**Comment by oanhnn** [comment]
Please try with this `composer.json` file:
```json
{
    "require": {
        "php": ">=5.4.0",
        "phpseclib/phpseclib": "dev-master#2c96af214bf1b5e29b707249108504b4e0041a21",
        "deployer/deployer": "~3.0.0"
    },
}
```
And run `composer clear-cache` command before `composer install` command.
Good luck !

**Comment by elfet** [comment]
This will gone away, when phpseclib do release. Or i will implement ssh in php myself :fist:

**Comment by gpupo** [comment]
It worked with what was said by @oanhnn

**Comment by DanceOctopus** [comment]
I have the same issue, but @oanhnn solutin don't work for me.
In composer.json file:
```
        "phpseclib/phpseclib": "dev-master#2c96af214bf1b5e29b707249108504b4e0041a21",
        "deployer/deployer": "~3.0.0"
```

Problem:
```
  Problem 1
    - deployer/deployer v3.0.0 requires elfet/pure ~1.1 -> satisfiable by elfet/pure[v1.1.0].
    - deployer/deployer v3.0.1 requires elfet/pure ~1.1 -> satisfiable by elfet/pure[v1.1.0].
    - deployer/deployer v3.0.2 requires elfet/pure ~1.1 -> satisfiable by elfet/pure[v1.1.0].
    - Conclusion: don't install elfet/pure v1.1.0
    - Installation request for deployer/deployer ~3.0.0 -> satisfiable by deployer/deployer[v3.0.0, v3.0.1, v3.0.2].
```

Without phpseclib/phpseclib i have:

```
Problem 1
    - The requested package phpseclib/phpseclib could not be found in any version, there may be a typo in the package name.
  Problem 2
    - deployer/deployer v3.0.2 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.1 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.0 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - Installation request for deployer/deployer ~3.0 -> satisfiable by deployer/deployer[v3.0.0, v3.0.1, v3.0.2].
```

**Comment by DanceOctopus** [comment]
Now it's working. I forgot about:

```
    "minimum-stability": "dev",
```

**Comment by deframe** [comment]
I don't mean to be "that guy" but a stable package shouldn't really be requiring an unstable dependency, even if it is a specific commit.

**Comment by ZeeCoder** [comment]
I don't quite get this.
The phpseclib package has a lot of releases: https://packagist.org/packages/phpseclib/phpseclib

What do you mean by "when phpseclib do release" @elfet ?
Are you waiting for a 0.4.x version?

**Comment by kenjis** [comment]
See the date of the commit: https://github.com/phpseclib/phpseclib/commit/2c96af214bf1b5e29b707249108504b4e0041a21

It is  23 Feb. There is no release containing the commit: https://github.com/phpseclib/phpseclib/releases

**Comment by ZeeCoder** [comment]
I see.
Then this solution should be noted on the website until it gets fixed somehow.
Now the tool basically seems broken from an outsider's point of view, if he tries to install it via Composer.
Even if he stumbles upon this thread, it will still leave a bad taste in his mouth, the tool loses some of it's credibility.

**Comment by kenjis** [comment]
@ZeeCoder :+1:

**Comment by elfet** [comment]
I thinking about ugly hack, until phpseclib release. Include phpseclib to project. What do you think? 
ping @ZeeCoder @oanhnn  @kenjis @gordalina @nspyke

**Comment by nspyke** [comment]
I personally wouldn't include a dependent package into this one. That's a short sighted fix for what could become a bigger issue later on.
I tried to track down where this referenced commit was merged into, but have had no luck.

What is in this commit's tree that is required and not in the master branch? Has anyone tried running this using the phpseclib master branch?

**Comment by deframe** [comment]
I'm more curious about why Deployer needs such a recent version of phpseclib in the first place. What essential feature was added in 2c96af214bf1b5e29b707249108504b4e0041a2 that isn't available in the 0.3.10 tag?

The phpseclib repository is difficult to grasp - '1.0' and '2.0' branches that are both being merged into master, yet the latest tag is 0.3.10. Ugh.

**Comment by ZeeCoder** [comment]
Same questions here.

**Comment by kenjis** [comment]
@elfet :+1: 

1. The next release might be next year. Until then all users using Composer have  to set the version of phpseclib to composer.json. Or might be github issue will be reported again and again.
2. `dev-master` won't work if a bug will be introduced.

**Comment by oanhnn** [comment]
Dear all,
Fix version of `phpseclib` as a commit is my idea. It is temporary solution for issue #228 .
As commit 2c96af214bf1b5e29b707249108504b4e0041a21, deployer was run good.
I'm not sure a current stable version of `phpseclib` is good for deployer. it must be tested. I'm happy if someone can do it.
Thank you!

**Comment by elfet** [comment]
I think fork phpseclob and release it myself, until phpseclib will release.

**Comment by ZeeCoder** [comment]
It's better than nothing.
Not an elegant solution but still better than including the whole project in Deployer.

**Comment by gpupo** [comment]
Yep, better than nothing

**Comment by kenjis** [comment]
v3.0.5 still has this problem. I hope fixed soon.

**Comment by ZeeCoder** [comment]
The fork already exists, I think it will be in the next release.

**Comment by ZeeCoder** [comment]
If I'm not mistaken, Deployer v3.0.6 includes the above mentioned fix.
Could you check if it works as expected @kenjis?

**Comment by kenjis** [comment]
Good! No problem.

By the way,

> Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.

What's using `guzzle/parser`?

**Comment by kenjis** [comment]
This is it: https://github.com/reactphp/http/issues/24#issuecomment-96585142

**Comment by goreilly** [comment]
There were some new releases on phpseclib/phpseclib on August 3rd. Is the code you guys wanted in any of their releases now?

**Comment by ZeeCoder** [comment]
Hmm, I think so, based on the commit: https://github.com/phpseclib/phpseclib/commit/2c96af214bf1b5e29b707249108504b4e0041a21
I think [v2.0](https://github.com/phpseclib/phpseclib/releases/tag/2.0.0) should be the thing Deployer needs.

Can you confirm this @elfet ?

**Comment by elfet** [comment]
Yes! Can anyone place new release?

**Comment by loranger** [comment]
This bug still occurs.
I was not able to install deployer from composer, and the standalone phar version cannot self-update.

**Comment by oanhnn** [comment]
@loranger Can you try run and show ouput to here:
```
$ composer init
$ composer require deployer/deployer
```

**Comment by wesleywesley** [comment]
```
Using version ^3.0 for deployer/deployer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - deployer/deployer v3.0.5 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.4 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.3 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.2 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.1 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.0 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - Conclusion: don't install deployer/deployer v3.0.10
    - Conclusion: don't install deployer/deployer v3.0.9
    - Conclusion: don't install deployer/deployer v3.0.8
    - Conclusion: don't install deployer/deployer v3.0.7
    - Conclusion: remove symfony/yaml v3.0.2
    - Installation request for deployer/deployer ^3.0 -> satisfiable by deployer/deployer[v3.0.0, v3.0.1, v3.0.10, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - Conclusion: don't install symfony/yaml v3.0.2
    - deployer/deployer v3.0.6 requires symfony/yaml ^2.6 -> satisfiable by symfony/yaml[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - Can only install one of: symfony/yaml[v2.8.0, v3.0.2].
    - Can only install one of: symfony/yaml[v2.8.1, v3.0.2].
    - Can only install one of: symfony/yaml[v2.8.2, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.0, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.1, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.10, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.11, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.12, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.13, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.2, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.3, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.4, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.5, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.6, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.7, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.8, v3.0.2].
    - Can only install one of: symfony/yaml[v2.6.9, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.0, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.1, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.2, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.3, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.4, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.5, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.6, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.7, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.8, v3.0.2].
    - Can only install one of: symfony/yaml[v2.7.9, v3.0.2].
    - Installation request for symfony/yaml == 3.0.2.0 -> satisfiable by symfony/yaml[v3.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by oanhnn** [comment]
@wesleywesley You are using symfony component >= 3.0 
Current deployer has problem with symfony 3.x
Please #495

**Comment by wesleywesley** [comment]
@oanhnn this issue exists for 1 year and still not fixed? Wow..
