### ISSUE TITLE
Misleading error message when the "deploy_path" does not exist on the remote server

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#260]
**Deployer version:** 3.0.0
**Remote host:** Ubuntu 14.04.2 LTS

The title says it all, I tried to run `dep deploy` but I got an error, saying:

```
Shell on your server is not POSIX-compliant. Please change to sh, bash or similar.  
Usually, you can change your shell to bash by running: chsh -s /bin/bash
```

The actual "error" was that the directory specified as deploy_path did not exist on the remote server.

Luckily I got a proper error right after the first one:

```
[RuntimeException]
bash: line 0: cd: /var/www/somefolder: No such file or directory
```

but the first one shouldn't have shown up in my opinion.

**Comment by elfet** [comment]
Hmm, yes. You are right. This is because of [common.php#L61](https://github.com/deployphp/deployer/blob/master/recipe/common.php#L61). 
Will be fixed.

**Comment by ZeeCoder** [comment]
Thanks for the fast reply. :+1:

**Comment by elfet** [comment]
Fixed. :+1:

**Comment by ZeeCoder** [comment]
Excellent, thanks. :)
