### ISSUE TITLE
Add Option to keep the `.git` directory like in older version

### ISSUE THREAD

**Issue by alexander-schranz** [deployphp/deployer#2616]
I'm currently trying out the new 7.0 beta version. It seems like from 6 to 7 it changed that the `.git` exist in the releases directory and so the `current` directory and so you have no information on the server which commit is checked out.
This is for us important also as we have such tools which check this kind of `.git` directories, to show what kind of things are currently running on the servers. It would be great if we can get the `.git` directory back or if it would be possible to enable this over an option again.

Looks for me this was changed in #2461.

**Comment by fabianmarz** [comment]
@alexander-schranz we are also running into issues with the change mentioned. As we are unsure what is the correct way of cloning/getting submodules into the deployment.

Anyone has a suggestion on how to achieve this in v7?

**Comment by antonmedv** [comment]
It’s possible to override deploy:update_code task.

**Comment by alexander-schranz** [comment]
@antonmedv Would it be possible that we could add some option flag like `keepgit`. Think switching to git archive had other advantages as the solution before? It would be great to have such a flag for getting the old behaviour again.

**Comment by aanderse** [comment]
@alexander-schranz I agree :+1:. Overriding `deploy:update_code` doesn't sound fun, especially.

**Comment by antonmedv** [comment]
Yes, it’s possible  introduce clone strategies.

**Comment by alexander-schranz** [comment]
@antonmedv would be great. Thx for the fast responses and thank you for the deployer, great work 👍

**Comment by claytonrcarter** [comment]
Was also just bitten by this. We have a build script that captures the deployed git SHA for error logging and it's no longer working. Happy to just override update_code to the old version for a while, but would be happier to not have to do so! 😄  Thanks again for all of your work on this, v7 feels  lot nicer and faster.

**Comment by antonmedv** [comment]
Done! Now there is `update_code_strategy` config option.

**Comment by alexander-schranz** [comment]
@antonmedv Thank you that's really great 👍

**Comment by sun** [comment]
Yes.  Unfortunately the originally proposed solution in https://github.com/deployphp/deployer/pull/2664 does not set up an actual git worktree with a .git folder.

Adding it as a setting `update_code_strategy` is a good approach though.  I would propose to resolve the problem with two new values for the option:

1. `worktree`: Uses [`git worktree`](https://git-scm.com/docs/git-worktree) to set up a proper git worktree checkout on the server.  Only available with Git v2+.  This should set up an actual / regular worktree as if the repository would be cloned normally.

2. `clone`: Uses [`git clone`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---local) to create a local clone of the bare repository.  Faster because git objects are hardlinked to the bare repository.  The local clone may be limited further by passing additional options.

**Comment by rrrrando** [comment]
How to use this with statamic, which uses git auto push to remote repo?

**Comment by codedge** [comment]
@rrrrando As I had the exact problem you asked about, I used a `post-receive` hook on the bare repository, that deployer is creating in `.dep/repo`.

So I added `.dep/repo/hook/post-receive` and put this inside:

```
#!/usr/bin/env bash

# Temporary folder
TMP_DIR=/tmp/repo

# Delete directory, if exists
[ -d "$TMP_DIR" ] && rm -rf $TMP_DIR && echo "Deleting $TMP_DIR..."

# Create new folder and clone repo into it.
# Before, get the origin url where the repository is hosted, f. ex. Github
ORIGIN_URL=$(git remote get-url origin)
mkdir $TMP_DIR && git clone $(pwd) $TMP_DIR
echo "Directory $TMP_DIR created..."

# Reconfigure the origin url
echo "Setting remore url of origin to $ORIGIN_URL"
git remote set-url origin $ORIGIN_URL

# Push your changes
echo "Pushing your changes..."
git push

# Delete the temporary folder
rm -rf $TMP_DIR
echo "Deleted $TMP_DIR"
```

The reason for that is, that Deployer checks out your working copy into the `.dep/repo` folder and not into the remote, where the repository is originally coming from. So Statamic is committing and pushing changes into the bare repository located at `.dep/repo`... but from there we need to sync it back to, f. ex. Github.
