### ISSUE TITLE
inventory is removed in beta 2

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#2617]
- Deployer version: 7.0.0-beta.2
- Deployment OS:

The helper function "inventory" is removed in beta2. Why is that? And when will it be recovered?

**Comment by antonmedv** [comment]
Instead v7 has much powerful import func.

**Comment by leasify** [comment]
Ok, sorry to hear that. We then have to replace deployer as we are in a hurry up to PHP8.
