### ISSUE TITLE
Do not escapeshellargs for env variables

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2620]
- Deployer version: 7-beta24 
- Deployment OS: Linux Ubuntu 20.04.2

@antonmedv you changed https://github.com/deployphp/deployer/blame/master/src/Support/helpers.php#L89 so we escape shell args.

I'm trying to extend the bash $PATH variable. In the past it worked this way (not nice, but did its job):

        ->set('env', ['PATH' => $deployPathStage . '/.dep:\'+$PATH+\''])

But with the escapeshellargs it is not longer possible - please correct me that I'm wrong!

If not I would love to remove the escapeshellargs again.

**Comment by antonmedv** [comment]
The escaping shell arguments is a good think. And actually we need to think about adding more escaping. Much more. 

Problem is now it’s difficult to access remote host env vars. Will access to it, extending PATH will be not a problem anymore. 

I actually think this can be the last feature before v7 release.

**Comment by Schrank** [comment]
> The escaping shell arguments is a good think. And actually we need to think about adding more escaping. Much more.

100% agree

> Problem is now it’s difficult to access remote host env vars. Will access to it, extending PATH will be not a problem anymore.

So we'll find a nice format, like {{env:PATH}} and use that?

**Comment by antonmedv** [comment]
Added remoteEnv() func!

```php
$path = remoteEnv()['PATH'];
run('echo $PATH', env: ['PATH' => "/home/user/bin:$path"]);
```
