### ISSUE TITLE
Magento 2 deploy:vendors very slow

### ISSUE THREAD

**Issue by VivekShingala** [deployphp/deployer#2621]
- Deployer version: v6.8.0
- Deployment OS: CloudLinux/Apache

While deploying the release, deploy:vendors takes too long to complete. Is it possible to make the vendor directory shared which can save lot of time?

**Comment by antonmedv** [comment]
Make sure composer cache is working.

**Comment by Schrank** [comment]
> Is it possible to make the vendor directory shared which can save lot of time?
@VivekShingala Yes, you can just add it to the shared folders, but I wouldn't recommend. As Anton said: Make sure composer caching works, then this should run smoothly - and use composer2 ! More on that here: https://github.com/magento/community-features/issues/302
