### ISSUE TITLE
Rollback architectural improvement

### ISSUE THREAD

**Issue by kanevbg** [deployphp/deployer#2622]
I purpose of adding some empty tasks to be invoked during the rollback task, or make the rollback from task to flow.
Use case: when opcache is used the FPM server should be instructed to cleanup the caches after changing the symlink but before removing the directory of the current release:

For abstraction I suggest these to be separate tasks, empty by default (like events without observers).
Than we will be able to specify easily additional custom algorithms during the rollback. Something like this:
![image](https://user-images.githubusercontent.com/11477130/129490195-98f41fe7-4a58-4c9b-a2bf-824aef9f2483.png)

In addition it will be more complete if you set the releaseDir with set() and $releases[0] with set() in order to be accessible from the invoked sub tasks.

**Comment by antonmedv** [comment]
Nice ideas. We can definitely use config for it and separate task to a few.

**Comment by antonmedv** [comment]
Fixed. Not possible to specify where to rollback.
```
dep rollback -o rollback_candidate=18
```
