### ISSUE TITLE
deploy:release improvement

### ISSUE THREAD

**Issue by kanevbg** [deployphp/deployer#2623]
In deploy:release there is logic called "Fix collisions". This fix actually breaks the expected result which is release_name to be as specified. If there is conflict it is more proper to report it before the actual release. I propose to add additional task deploy:release:verify before deploy:release. If there is problem the deployment should stop. Only release_name to be responsible for the generated release name.

**Comment by antonmedv** [comment]
No more "Fix collisions" logic.
