### ISSUE TITLE
{{host}} shortcut for currentHost()

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2625]
Does something exist which returns the current host to use easily in a string? If not I'm happy to add it!

**Comment by antonmedv** [comment]
Yes, let’s add it. host or current_host?

**Comment by Schrank** [comment]
I’d prefer current_host, it is more explicit, that there might be more than one

**Comment by antonmedv** [comment]
Actually we already have {{hostname}} =) It's already in host definition.
