### ISSUE TITLE
Allow overriding DEPLOYER_ROOT or default process runner cwd

### ISSUE THREAD

**Issue by kjkooistra-youwe** [deployphp/deployer#2628]
For issue [1774](https://github.com/deployphp/deployer/issues/1774) a [DEPLOYER_ROOT constant](https://github.com/deployphp/deployer/blob/88f6e423688bfe812c125a023bfbc024cd097118/bin/dep#L104) was introduced, which is used in the [ProcessRunner](https://github.com/deployphp/deployer/commit/29a643b62389542394c7b254f6c913f7191132ba#diff-b50c325c16c55b4ce886df4de55eb0f3aff1c44677a1a80f35c4fa96e8df3cfbR44) to set the default cwd. When commands are executed from the root of a project this would mean all run commands have to be configured to override the cwd.

Unfortunately there is no way to override the constant or cwd option globally. Therefore I'd like to suggest making the constant, default cwd option or both overridable, either via a setting or an environment variable. Something like:

bin/dep
```php
define('DEPLOYER_ROOT', getenv('DEPLOYER_ROOT') !== false ? getenv('DEPLOYER_ROOT') : dirname($deployFile));
```

ProcessRunner::run()
```php
'cwd' => has('deployer_root') ? get('deployer_root') : (defined('DEPLOYER_ROOT') ? DEPLOYER_ROOT : null),
```

**Comment by lazka** [comment]
Wouldn't it make more sense to allow override this in the deploy.php? I can't expect users to set the correct env var all the time when running deployer :/

**Comment by kjkooistra-youwe** [comment]
> Wouldn't it make more sense to allow override this in the deploy.php? I can't expect users to set the correct env var all the time when running deployer :/

That was my thought as well, but it was requested to remove that option in the pull request.

**Comment by lazka** [comment]
I see, thanks.

**Comment by antonmedv** [comment]
You can just call setenv at beginning of deploy.php.

**Comment by lazka** [comment]
Do you mean `putenv()`? I've already tried that, but it didn't help.
`putenv('DEPLOYER_ROOT=/');`

**Comment by kjkooistra-youwe** [comment]
> Do you mean `putenv()`? I've already tried that, but it didn't help. `putenv('DEPLOYER_ROOT=/');`
> 
> That's too late from what I can see.

You're right. The file is loaded after the environment variable is read in the dep binary. The only alternative I see for now would be to provide your own script where you prefix the environment variable. For example:

`#!/bin/bash

DEPLOYER_ROOT=/ ./vendor/bin/dep $@`

**Comment by lkraav** [comment]
> You're right. The file is loaded after the environment variable is read in the dep binary. The only alternative I see for now would be to provide your own script. For example:
> 
> ```shell
> #!/bin/bash
> 
> DEPLOYER_ROOT=/ ./vendor/bin/dep $@
> ```

I am also in this boat now after v6 -> v7 transition.

Setting this as a system-wide env value is obscure.

Ideally, I would also like to set it at my central `deploy.php` file, which makes things crystal clear to the team.

As of [v7.0.0-rc.4](https://github.com/deployphp/deployer/releases/tag/v7.0.0-rc.4) I think not possible yet?

**Comment by lazka** [comment]
I've personally settled on the following for now:

```php
$PROJECT_ROOT = dirname(__DIR__);

task('custom', function () use ($PROJECT_ROOT) {
    $options = ['cwd' => $PROJECT_ROOT];

    runLocally("...", $options);
    runLocally("...", $options);
    runLocally("...", $options);
    runLocally("...", $options);
}
```

**Comment by lkraav** [comment]
```php
task('custom', function () use ($PROJECT_ROOT) {
    $options = ['cwd' => $PROJECT_ROOT];
   ...
}
```

Hmmm, that only works for `runLocally()` calls?

What if my task is simply

```php
task( 'deploy', [
    'deploy:prepare',
    'deploy:publish',
] )->desc( 'Deploy project' );
```
