### ISSUE TITLE
Syntax for parameters

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#263]
Now it's possible to insert environment variable with `{{...}}`, need to think some for parameters, to refactor from this:
``` php
run('php {{release_path}}/' . trim(get('bin_dir'), '/') . '/console assetic:dump --env={{env}} --no-debug');
```
To this:
``` php
run('php {{release_path}}/%bin_dir%/console assetic:dump --env={{env}} --no-debug');
``` 

Also separate parse from `Environment` class to separate unit.

Does anybody wants to take care of this? :eyes:

**Comment by elfet** [comment]
Available syntaxes: 
1. `%...%`
2. `{%...%}`
3. `{{%...%}}`

**Comment by ZhukV** [comment]
+1 - `%parameter_name%`
