### ISSUE TITLE
Support deployment to Kubernetes

### ISSUE THREAD

**Issue by thanhtoan1196** [deployphp/deployer#2631]
Please support deployment to Kubernetes.

**Comment by Schrank** [comment]
Good morning @thanhtoan1196 and thanks for this idea!

I understand each word of this sentence but have no clue what it means.

do you want deployer to build docker images and communicate with kubernetes cluster?

**Comment by antonmedv** [comment]
There is a plenty of ways it can be achieved. What in the scope?

**Comment by thanhtoan1196** [comment]
> do you want deployer to build docker images and communicate with kubernetes cluster?

@Schrank That's right, for example it builds image from Laravel app and deploys to k8s

**Comment by minkbear** [comment]
@antonmedv I have ever used https://devspace.sh/cli/docs/quickstart to build image.
