### ISSUE TITLE
DEPLOYER_BIN with spaces in path doesn't work on Windows

### ISSUE THREAD

**Issue by froberts0n** [deployphp/deployer#2632]
Hi there,

I know everybody will say that spaces in paths are bad, but they happen, especially on Windows where most users are created by using their full names, including the space. I thought I'd get that out of the way first. 😉

I didn't have any issue with that in v6 but in v7(b24) however, it causes a problem. I think it has to do with the `createProcess()` function in `src/Executor/Master.php` because `$dep` is not enclosing `DEPLOYER_BIN` in quotes (at least on Windows). I'm using Deployer in my own user account, the path of which contains a space, and `deployer.phar` is in my projet directory so `__FILE__` expands to a path with spaces and the process cannot execute.

Browsing the code without being too familiar with it, I assume that this is where the problem lies, but there can be other similar cases elsewhere.

Hope this helps.

**Comment by Schrank** [comment]
Thanks for the report!

**Comment by antonmedv** [comment]
Should be fixed, please verify.

**Comment by froberts0n** [comment]
Yep! beta26 seems to be working now!
That was quick!
Thanks!
