### ISSUE TITLE
Fix cloudflare response handling

### ISSUE THREAD

**Issue by usernotnull** [deployphp/deployer#2636]
- Deployer version: v7.0.0-beta.24

- Deployment OS: Windows WLS Ubuntu 20

Reaching the task deploy:cloudflare, I get this error:
```
 ErrorException  in cloudflare.php on line 86:
Trying to access array offset on value of type bool
```

Upon further inspection, it seems the response from cloudflare, if successful, does not include a 'success' key.

```
    if (empty($zones['success']) || !empty($zones['errors'])) {
        throw new \RuntimeException("Problem with zone data");
    } else {
        $zoneId = current($zones['result'])['id'];
    }
```

I tested by removing 'empty($zones['success']) || ' and the task worked, the cache was purged.

Do I submit a PR?

**Comment by Schrank** [comment]
Hi @RJFares! Thanks for the issue.

> Do I submit a PR?

Yes! Please :-)

**Comment by RJFares** [comment]
@Schrank done. 

See PR https://github.com/deployphp/deployer/pull/2637
