### ISSUE TITLE
Is there a way to contribute to the documentation and descriptions on the site?

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#264]
I think this project could be way bigger if the spelling was better on the site.

Example: "Deployer has very clean code and good tested."
should be something like: "Deployer has a very clean, and well tested code."

IMHO sentences like this does not help the credibility of the project.

What do you think @elfet ?

**Comment by elfet** [comment]
YES! It's will be so gooв! English is not my primary language, so i have problems some time with. 

Doc located here: https://github.com/deployphp/docs
Site located here: https://github.com/deployphp/deployer.org ([pages](https://github.com/deployphp/deployer.org/tree/master/pages))

**Comment by ZeeCoder** [comment]
Excellent, I'll see what I can do there. :)
