### ISSUE TITLE
The new doc URLs break the old Google URLs

### ISSUE THREAD

**Issue by atimmer** [deployphp/deployer#2642]
The new URL scheme of the documentation breaks all the URLs that are already in Google. For example: https://www.google.com/search?client=firefox-b-d&q=deployer+hosts. Every deployer.org result on that page goes to a 404. From an SEO perspective, it's highly recommend to never break URLs ever. Google will usually penalise the domain for excessive 404s.

As a lesser but still important concern, It will also break people's bookmarks.

My recommendation would be to create 301 redirects to make sure Google moves (some of) the ranking to the new pages.

Let me know if I can help out doing some of the work.

**Comment by Schrank** [comment]
Thanks for the info! 
@antonmedv good job! Happy to help as well!

**Comment by antonmedv** [comment]
Looks like google websearch updated everything already.
