### ISSUE TITLE
Trying to get the "release_path" env variable in a custom task throws a RuntimeException without message.

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#265]
I tried the following command (Migrating some tasks from v2 to v3):

```php
task('test:test', function () {
    var_dump(env('release_path'));
})->desc('test');
```

It throws a RuntimeException without any explanation.

Trying to get an 'asd' env variable do have a proper message hovewer:

```
Environment parameter `asd` does not exists.
```

**Comment by elfet** [comment]
I think it's because of callback in release_path env. 
Try run this command with -vvv option, and show output here.

**Comment by ZeeCoder** [comment]
I run this task separately, not as part of a deployment process:
`dep test:test target`
So I think I would not be able to access the env var anyway, since no task could ran that could've set that env variable.

But even then of course I should get a proper exception message. 

```
➤ E➤ecuting task test:test
⤷ on [emese-server]
Run: cd /var/www/z_lon_heernew_dep3 && readlink /var/www/z_lon_heernew_dep3/release


                      
  [RuntimeException]  
                      


Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:289
 run() at phar:///usr/local/bin/dep/recipe/common.php:87
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Server/Environment.php:59
 Deployer\Server\Environment->get() at phar:///usr/local/bin/dep/src/functions.php:556
 env() at /home/zeecoder/work/z_lon_heernew/.deployer/test.php:4
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:66
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:116
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:91
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:62
 require() at /usr/local/bin/dep:4
```

**Comment by elfet** [comment]
This happens because `release_path` does not exist yet. Add to you script this:
``` php
before('test:test', 'deploy:release');
```

I will fix error message.

**Comment by garak** [comment]
I just ran into a similar issue, trying to execute a task outside a deploy. I'm afraid that solution proposed by @elfet is just an ugly workaround...
We should be able to execute **any** task outside a deploy, think of executing only cache clearing, or only database migrations, etc.
Obviously, we cannot set a ``before`` for every single task

**Comment by elfet** [comment]
are you want to execute some task before every others?

**Comment by garak** [comment]
No, I want to execute a single task.

**Comment by elfet** [comment]
Add `once`.

**Comment by garak** [comment]
Can you give an example? Suppose you want to execute a single task that is already defined, like ``database:migrate`` (in symfony)

**Comment by elfet** [comment]
```php
task(...)->once();
```

**Comment by garak** [comment]
But the task is already defined. See the symfony recipe, there is a ``database:migrate`` task.
If I try to run ``dep database:migrate foobar`` I get the error above

**Comment by elfet** [comment]
You can override task.

**Comment by garak** [comment]
So, your solution is to override every single task, only to add a ``once``?
After doing that, every task I overridden stays with ``once``, so will I be able to use it without ``once``?

**Comment by elfet** [comment]
This will be able with Events system form next Deployer v4. Now you can use `before` and `once` combination.

**Comment by garak** [comment]
So, can you give me an example? Some code, please!
