### ISSUE TITLE
Replace rsync with cp in copy_dirs.php

### ISSUE THREAD

**Issue by gjuric** [deployphp/deployer#2656]
Is there a reason while rsync is used in the default `deploy:copy_dirs` task?

It seems to me that it would be simpler to replace:

```php
    run("mkdir -p {{release_path}}/$dir");
    run("rsync -av {{previous_release}}/$dir/ {{release_path}}/$dir");
````

with

```php
    run("cp -r {{previous_release}}/$dir {{release_path}}/");
```

and it wouldn't require installation of rsync on the host.

**Comment by antonmedv** [comment]
Actually there is no reason. Found this: https://github.com/deployphp/deployer/pull/1072

If you want you can work on PR for this (include checks for tailing slash, -rtf, and other disscussed stuff from #1072) and it will be included to v7 release!

It will be cool.

**Comment by gjuric** [comment]
I've created a PR and tested if manually, copying nested directories worked.
