### ISSUE TITLE
Is there a way to access the current server configuration in a task?

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#266]
I'm trying to re-implement the following:
`$host = config()->getHost();`

Since the `config()` function seems to be removed, I tried to find the current alternative, but nothing I tried so far worked.

**Comment by elfet** [comment]
Server config now are private, you should set separate env var: `->env('host', '...')`.

If you still what access config, try this:
``` php
Context::get()->getServer()-> getConfiguration();
```

**Comment by ZeeCoder** [comment]
Okay, with the latter code snippet I can access the server configuration.

Simply setting and getting an env variable wouldn't work, because I need the configuration of the server which is under deployment.

What were the reasons behind removing the `config()` function?

**Comment by elfet** [comment]
> What were the reasons behind removing the config() function?
Separation of concepts. I think everything accessible and server specified should be in env vars. 

You can define something like this:
```php
server('host1.domain.com')
    ->env('host', 'host1.domain.com');

server('host2.domain.com')
    ->env('host', 'host2.domain.com');
```

Maybe create a PR which will be setting this env vars from config on run?

**Comment by ZeeCoder** [comment]
That example code would be too redundant, but setting the environment vars automatically when using the `server` function, would solve the issue.
I'll look into it.

**Comment by elfet** [comment]
Take a look at: [functions.php#L54](https://github.com/deployphp/deployer/blob/master/src/functions.php#L54)

**Comment by ZeeCoder** [comment]
Closing this, since the discussion has moved to the pull request's page.
