### ISSUE TITLE
Cachetool recipe missing from v7

### ISSUE THREAD

**Issue by jamieburchell** [deployphp/deployer#2660]
Hi there

Please can the Cachetool recipe be included in v7?

https://github.com/deployphp/recipes/blob/master/recipe/cachetool.php

I have no idea if this is a case of just copying the file over / if this recipe is compatible as-is with v7?

Thanks
Jamie

**Comment by antonmedv** [comment]
Can you create a pr?

**Comment by Schrank** [comment]
It is : https://github.com/deployphp/deployer/blob/v7.0.0-beta.25/contrib/cachetool.php

**Comment by jamieburchell** [comment]
Sorry, was looking for this in the "recipe" directory. Perhaps "recipe/contrib" would have been better.

**Comment by Schrank** [comment]
Maybe :) recipe is "systems" and "contrib" is "infrastructure" :) Hope that helps! Have a good day!
