### ISSUE TITLE
ssh keyscan with username

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2667]
### Discussed in https://github.com/deployphp/deployer/discussions/2666

<div type='discussions-op-text'>

<sup>Originally posted by **underdpt** September 23, 2021</sup>
Hello,

With v7.0.0-beta25, this setup:

```php
set('repository', 'ssh://git@git.server.com:2233/folder/project.git');
set('ssh_multiplexing', PHP_OS_FAMILY === 'Windows' ? false : true);
set('default_timeout', null);

host('my.server.host')
    ->set('labels', ['stage' => 'production'])
    ->set('branch', 'master')
    ->set('remote_user', 'mainsip')
    ->set('port', 2223)
    ->set('deploy_path', '/var/www/project');
```

produces this error:

```
info deploying master
task deploy:setup
task deploy:lock
task deploy:release
task deploy:update_code
[my.server.host]  error  in update_code.php on line 54:
[my.server.host] run ssh-keyscan -p 2233 -H git@git.server.com >> ~/.ssh/known_hosts
[my.server.host] err getaddrinfo git@git.server.com: Name or service not known
[my.server.host] err getaddrinfo git@git.server.com: Name or service not known
[my.server.host] err getaddrinfo git@git.server.com: Name or service not known
[my.server.host] err getaddrinfo git@git.server.com: Name or service not known
[my.server.host] err getaddrinfo git@git.server.com: Name or service not known
[my.server.host] exit code 1 (General error)
```

I think the error might be that the hostname is including the user part `git@...` for the ssh-keyscan command.

This works with v7.0.0-beta24</div>

**Comment by Sander-Toonen** [comment]
https://github.com/deployphp/deployer/blob/363f7ed6a15c4a7a967f38a29bf357a82784196f/recipe/deploy/update_code.php#L48

This regex is to naïve. It will also fail when the repository is pulled over http, in which case key-scanning makes no sense.

**Comment by Sander-Toonen** [comment]
Coming up...

**Comment by Sander-Toonen** [comment]
Could you please release a new beta? This issue is breaking quite some pipelines.

**Comment by antonmedv** [comment]
Released beta.26
