### ISSUE TITLE
Is there a way to declare a stage and/or server as default?

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#268]
Basically what I'm searching for is the `multistage()` function, or something similar.
I didn't find anything regarding this in the documentation.

Also: is it possible now to declare multiple stages on a single server, then deploy to there.
For example:
`dep deploy server stage`

I couldn't get this information from the documentation either.

**Comment by elfet** [comment]
You can set stages to a few servers:
```
server(...)
    ->stage('prod');

server(...)
    ->stage(['prod', 'stage']);    

server(...)
    ->env('stages', ['stage']);    
```

I think is better to separate something like `ServerSelector` class, and implement all of this into it.

**Comment by ZeeCoder** [comment]
Hmm, could you please explain to me what stages are exactly here?
I have a feeling that I have a different idea, and I couldn't find an explanation in the docs.

It seems to me, that stages here are really a way to group servers.
So if I have a server cluster, which contains multiple servers for production, and some for testing purposes, then by declaring for each of them which "stage" they are in, I can deploy to "production" and "development" servers separately.
Do I get this right?

Because if I do, then my second question is kind of nonsensical.

I'm still curious though about how I can set which server should the deploy command deploy to by default.
What I'm trying to achieve is that running `dep deploy` should deploy to the development server by default.

**Comment by elfet** [comment]
Yes, stages is for grouping server.

Now, by default will be deployed to server without specified stage.

**Comment by ZeeCoder** [comment]
Oh, forgot to answer here.

I think this should be explained more in-depth on the website.

**Comment by AlexStansfield** [comment]
Would it be possible to add a way to define a default stage. All my 2.x configs are setup with staging and production where staging is the default. I was hoping to be able to update the config files without having to update everyone's behaviour when they use the deployer

**Comment by ZeeCoder** [comment]
I'm missing this feature too. :+1:

**Comment by ZeeCoder** [comment]
2 months ago @elfet said it's on its way: http://deployer.org/discuss#comment-1968357574

**Comment by elfet** [comment]
Yes, i'm going to implement this soon. Already decouple StageStrategy. :+1:
