### ISSUE TITLE
Echo sudo password

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#269]
What about automatically echo sudo password? No more sudoers needed.
Parse this commands:
```
sudo chmod ....
```
Into this:
```
echo "password" | sudo -S chmod ...
```

**Comment by oanhnn** [comment]
I'm agree, but output isn't include `echo "password" | `

**Comment by elfet** [comment]
It's possible to do after outputting to term. What about other potential vulnerability? bash_history, top processes?

**Comment by Blackskyliner** [comment]
Why not using the Proccess constructot class third argument ($input) to specify the input to STDIN? In this way it should be possible to input the password like a user woud do or am I wrong?

I think to echo an password shouldm't be an suitable solution... Never... Too much possibilities of security risks. (Like the mentioned cmd shown in top, otherwise maybe stored in some way in /proc ?)

**Comment by elfet** [comment]
It's not possible, because `Proccess` class only for local machine. `PhpSecLib` using on remote, and it's not possible to do this it. 

What can be against echoing sudo password?

**Comment by Blackskyliner** [comment]
I just did a little lookup and what may be a somehow better solution would be to run it as 
```
echo "password" | sudo -S -v
sudo command
```
this way, we would not have the password on a long-running proccess, but it would also mean that we need caching credentials support on the hosts site (I guess its enabled by default on most hosts). It also means we should not close the connection between several calls (which we already do I guess).

The big problem I see are "what if" arguments. 
What if someone gets a grip of the sent command where the password is in (like being on the host machine loogin for processes cmd's)? 
What if the "administrator" did not configure sudo to be restrictive enough (like using ALL for sudo CMDs) and through the previous leakage they may get full root rights?

Maybe if we push a temp file to the machine with the password in it, pipe the content of that file as STDIN into the sudo may be a better solution. At least as far as we think about the "attacker" does not have the rights to read that password file, which we can achieve by only having the mode set to 0400. Then after doing the `sudo -S -v`, if we go down that path, we can maybe already delete this file again, but have sudo access for like 5 minutes or so. (depends on host auth cache configuration)

**Comment by elfet** [comment]
I think using tmp file for password is good solution. 
But i think implementing this too complicated. And this needed only for `deploy:writable` task. I think we can leave thinks as they are for now.
