### ISSUE TITLE
bin/php issue in 7.0.0-beta.27

### ISSUE THREAD

**Issue by claytonrcarter** [deployphp/deployer#2692]
- Deployer version: 7.0.0-beta.27
- Deployment OS: Debian 10.x

Please, provide a minimal reproducible example of deploy.php:

```php
<?php

namespace Deployer;

require 'recipe/common.php';

task('foo', fn () => var_dump(get('bin/php')));
```

Running:
```
 $ ./vendor/bin/dep foo
task foo
[@localhost]  What PHP version to install?  (default: 8.0)
```

This appears to have been introduced this morning via 0b9b525bdbedb82f7c9041f239ecca751e099b29, which uses `has('php_version')` which will always eval to `true` (I think?) b/c `php_version` is set, but it's set to a closure.

This affects anything that uses `{{bin/php}}`, such as `deploy:vendors` (via `bin/composer`), which is where it bit me. The workaround I'm using is to just `set('php_version', '')` but this feels counterintuitive. I would expect it to just look for the `php` command if I have not explicitly asked it to ask for a PHP version.

Thank you!

**Comment by antonmedv** [comment]
Yes, it’s a bug.

**Comment by antonmedv** [comment]
Fixed in beta.28
