### ISSUE TITLE
There should be a way to be able to access the server configurations (host, name, etc.)

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#270]
I would need information about the server I'm currently deploying to, so that I can output proper messages if I need to.

I do understand why it's not ideal to give full access to the Configuration object through a global `config()` function, because then any task could - in theory - modify the server configuration values.

So in short, I think there should be a way to "get" the configuration values, but it should not expose "setters".

Here's an example of a 3rd party recipe to show an actual use-case for the old `config()` function:
https://github.com/deployphp/recipes/blob/master/recipes/slack.php

**Comment by elfet** [comment]
I think better place for this data is env. 
`env('host')`

**Comment by ZeeCoder** [comment]
Yeah, the problem was with that approach is that if we follow that naming pattern, then it can easily conflict with other env variable names.

Like: `env('name')` -> this doesn't tell you much about what's name is it, and it also conflicts with some tests, where the `env('name', 'value')`.

I thought about prefixing them, like:
`env('server-name', '...')`,
but it starts to feel like there's just too much magic involved, that would happen under the hood.

What do you think?

**Comment by elfet** [comment]
It’s good approach. Env already support this. 
You can do this:
```php
env(‘config’, [
    ’name’ => ‘prod’,
    ...
]);
```

Now possible:

```php
echo env(‘config.name’); // prod
```

**Comment by ZeeCoder** [comment]
Oh, I see, so I could implement the following code in the Builder constructor:

```php
// ...
$env->set('server', [
    'name' => $config->getName(),
    'host' => $config->getHost(),
    // ...
])
// ...
```

So that later in a task, I could access them as follows:
```php
$serverName =  env('server.name');
$serverHost =  env('server.host');
```

I would like that approach.
One question though: can I get the full array just by saying: `env('server')`?

**Comment by elfet** [comment]
Honestly, i don't know :sunglasses: I don't implemented this feature.

**Comment by ZeeCoder** [comment]
Okay, I'll check out it later then.
But about the Builder class: does that look okay to you?

Because if it does, I'll be sure to implement that feature, and if that's done,
I think I'll create another pull request, to fix the 3rd party slack recipe too. :)

**Comment by elfet** [comment]
Yes, look good for me.

**Comment by ZeeCoder** [comment]
I'm closing this issue in favor of the #272 pull request.
