### ISSUE TITLE
Bitbucket pipeline ssh key

### ISSUE THREAD

**Issue by gabrielkollum** [deployphp/deployer#2700]
- Deployer version:  6.8.0
- Deployment OS: Ubuntu 18.4

I'm try to deploy my project with bitbucket pipelines. But 'im facing this problem:

• done on [stage]
✔ Ok [3s 647ms]
➤ Executing task deploy:update_code
[stage] > command -v 'git' || which 'git' || type -p 'git'
[stage] < /usr/bin/git
[stage] > /usr/bin/git version
[stage] < git version 2.30.1
[stage] > cd /home2/xxxx/xx.xx.xx.com && (if [ -h /home2/xx/xx.xx.xx.com/release ]; then echo 'true'; fi)
[stage] < true
[stage] > cd /home2/xxxx/xxxx.xxx.xx.com && (readlink /home2/xxxx/xxxx.xxxx.xxxxx.com/release)
[stage] < /home2/xxxxx/xxxxx.xxxx.xxxxx.com/releases/1.1
[stage] > cd /home2/xxxxx/xxxxx.xxxxx.xxxxx.com && (/usr/bin/git clone -b "stage"  --recursive  git@bitbucket.org:xxxxx/xxxxx.git /home2/xxxxx/xxxxx.xxxxx.xxxxx.com/releases/1.1 2>&1)
[stage] < Cloning into '/home2/xxxxx/xxxxx.xxxxx.xxxxx.com/releases/1.1'...
[stage] < Error reading response length from authentication socket.
[stage] < Permission denied (publickey).
[stage] < fatal: Could not read from remote repository.
[stage] < Please make sure you have the correct access rights
[stage] < and the repository exists.
➤ Executing task deploy:failed
• done on [stage]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[stage] > rm -f /home2/xxxxx/xxxxx.xxxxx.xxxxx.com/.dep/deploy.lock
• done on [stage]
✔ Ok [250ms]
In Client.php line 103:
                                                                               
  [Deployer\Exception\RuntimeException (128)]                                  
  The command "cd /home2/xxxxx/xxxxx.xxxxx.xxxxx.com && (/usr/b  
  in/git clone -b "stage"  --recursive  git@bitbucket.org:onip-sistemas/crisp  
  i.git /home2/xxxxx/xxxxx.xxxxx.xxxxx.com/releases/1.1 2>&1)"   
  failed.                                                                      
                                                                               
  Exit Code: 128 (Invalid exit argument)                                       
                                                                               
  Host Name: stage                                                             
                                                                               
  ================                                                             
  Cloning into '/home2/xxxxx/xxxxx.xxxxx.xxxxx.com/releases/1.1  
  '...                                                                         
  Error reading response length from authentication socket.                    
  Permission denied (publickey).                                               
  fatal: Could not read from remote repository.                                
                                                                               
  Please make sure you have the correct access rights                          
  and the repository exists.                                                   
                                                                               
Exception trace:
  at phar:///usr/local/bin/dep/src/Ssh/Client.php:103
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:304
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/update_code.php:96
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:144
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:924
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:265
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:141
 Symfony\Component\Console\Application->run() at [phar:///usr/local/bin/dep/src/Deployer.php:326]()
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:136
 require() at /usr/local/bin/dep:4
deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

The most weird is that I can clone the same repository by command line.
I've ready put the pipeline's ssh key in repository keys.

![error](https://user-images.githubusercontent.com/58408268/137404793-91c8085b-010a-4f9c-b039-185eafa61f33.png)

**Comment by webspin** [comment]
@gabrielkollum Did you eventually solve this? I have the same issue...

**Comment by Schrank** [comment]
@webspin Does that help?
