### ISSUE TITLE
Memory exhausted (2Gb) on version v7.0.0-beta.29 to beta.31

### ISSUE THREAD

**Issue by underdpt** [deployphp/deployer#2703]
- Deployer version: v7.0.0-beta.29 to beta.31
- Deployment OS: Windows

After upgrading on windows from v7.0.0-beta.28 to any more recent version, I get memory exhausted error simply getting the help:

```
❯ .\vendor\bin\dep --help
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in D:\desarrollos\davanni\gastos\web\vendor\bin\dep on line 21
```

Trying to run with `-vvv` produces the same output.

**Comment by antonmedv** [comment]
Also please test beta.33.
