### ISSUE TITLE
Implement sorter for Shopware

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2710]
Hi, @Schrank 

I had trouble with dependency for sorting. Ended up deleting it. Please reimplement sorter here:

https://github.com/deployphp/deployer/blob/33bdaacfea8d8ecea41ec299d3556bfcdac10861/recipe/shopware.php#L121-L122

Thanks.

**Comment by Schrank** [comment]
> But why topological sort is needed?

Because the shopware plugins are composer packages and can have different dependencies, therefore we need to take care of the right order to activate and install them :-/

**Comment by antonmedv** [comment]
@Schrank lets create two recipes? :)

**Comment by antonmedv** [comment]
I’ll refactor current recipe to simple recipe. You more complex is needed, consider adding it too? It it okay with everyone?

**Comment by antonmedv** [comment]
Updated in b40c641ee21ef1e4cc5921a5dc704d21d8ffd7b5. Please verify in beta.39.

**Comment by UlrichThomasGabor** [comment]
@antonmedv Is the documentation generated by hand or automatically? I would change `This task is group task which contains next tasks:` to `This task is a group task which contains the following tasks:`

I'll try the recipe out but on the first glance it looks good!

**Comment by antonmedv** [comment]
Yes, it’s generated. See src/Documentation.
