### ISSUE TITLE
Add message if command is proxied to local deployer

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2723]
If you have a local installation, a global deployer.phar file might proxy commands to it, so for example it can happen, that you have a global version 7 but `dep version` return 6.8:
https://github.com/deployphp/deployer/issues/2722

If the proxying happens, we should log a note to the cli, so people know, that not the global deployer runs, but the local one and don't wonder about version, etc.

**Comment by antonmedv** [comment]
Fixed!
