### ISSUE TITLE
Deploy fails on Cygwin

### ISSUE THREAD

**Issue by lucaciotti** [deployphp/deployer#2729]
- Deployer version: v7.0.0-beta.38
- Deployment OS: Windows

WIth the last update my deploy cmd fails:

> Using  D:\myProjects\<project>/vendor/bin/dep
> 
> dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../deployer/deployer/bin" && pwd)
> 
> if [ -d /proc/cygdrive ]; then
>     case $(which php) in
>         $(readlink -n /proc/cygdrive)/*)
>             # We are in Cygwin using Windows php, so the path must be translated
>             dir=$(cygpath -m "$dir");
>             ;;
>     esac
> fi
> 
> "${dir}/dep" "$@"

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2729">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2729/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2729/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Can’t tell what is wrong.

**Comment by lucaciotti** [comment]
Ok I found out what disturbs my deploy ...

I state that I use Laravel 8 and I use your package for the deployment.
The command I used for the deployment is:

`vendor/bin/dep deploy production`

Now the "sh" command contained in bin calls the execution of "deployer/bin/dep" ... here since beta 28 a block of code "// Find project-local Deployer installation" has been inserted.
![image](https://user-images.githubusercontent.com/5623252/141676359-6793edde-2f9c-490c-9508-06abce7da3eb.png)

However here the code calls the dep.sh file contained in "vendor/bin" and everything crashes ...

This piece of code is not clear to me.

Hope it helps to fix the problem.

**Comment by Schrank** [comment]
The code is to have a global deployer installation but the correct version locally. It seems you have a deploy script(?), the question is, where is it and why is it used. If the name is dep.sh it shouldn’t be used.

Can you please rename the file (my-personal-sh something which doesn’t contain dep 😅) and try again?
