### ISSUE TITLE
once() Can not use Task grouping?

### ISSUE THREAD

**Issue by ezsky** [deployphp/deployer#2737]
- Deployer version: 6.8
- Deployment OS:centos 8

I want to deploy multiple host , but code just in host1, other  hosts will reload php-fpm.

```
task('release', [
    'deploy:prepare',
    'deploy:release',
    'upload',
    'extract',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink'
])->once();
```

**Comment by antonmedv** [comment]
Fixed in c1bef573969d8339d82561f893a2aa62067a81e4
