### ISSUE TITLE
Deployer failing after upgrading to rc1

### ISSUE THREAD

**Issue by alexander-schranz** [deployphp/deployer#2743]
- Deployer version: v7.0.0-rc.1
- Deployment OS: MacOS -> Ubuntu 20

I upgraded deployer to the latest version:

>   - Upgrading deployer/deployer (v7.0.0-beta.24 => v7.0.0-rc.1): Extracting archiv

After update I tried to deploy:

```
vendor/bin/dep deploy stage=prod 
```

Deployment fails with:

```
[54.78.255.164]  Deployer\Exception\Exception  in release.php on line 108:
[54.78.255.164]
[54.78.255.164]   Release name "1" already exists.
[54.78.255.164]   Release name can be overridden via:
[54.78.255.164]   dep deploy -o release_name=1
```

Also running

```
vendor/bin/dep deploy -o release_name=1
```

Did not help.

**Comment by alexander-schranz** [comment]
Oh sorry:

```
dep deploy -o release_name=2
```

Actually did fix it need to use another name that the one which was failing 🙈

**Comment by antonmedv** [comment]
It also in https://deployer.org/docs/7.x/UPGRADE

**Comment by Navi2016** [comment]
Same happened to me, manually specifying once did help, but in the docs it says this should be when migrating from v6 to v7, but i already was on v7 (beta 23) and upgraded to latest v7 (rc3).
