### ISSUE TITLE
Blackjack, 2 aces counted as 12

### ISSUE THREAD

**Issue by L00Cyph3r** [deployphp/deployer#2746]
- Deployer version: v7.0-master
- Deployment OS: n/a

While waiting for a CI job to finish I decided try some blackjack. Now before I was broke I had a hand with 2 aces, so I hit. Got a 3, hit. Got a 7, and was bust?
A+A+3+7 = 12 or 22 or 32, but in this case I was bust with 22.

Could this be added to the bottom of the lowest priority todo-list? And I also like to have my $25 back 😇

[Screenshot](https://user-images.githubusercontent.com/10772371/141441523-65f78052-ec7c-4c39-a3a5-9390e8fc5b47.png)

**Comment by antonmedv** [comment]
Yes, I see the error in code. Will fix it, as this has the highest priority.

PS And I will return your 25$ back 😉

**Comment by antonmedv** [comment]
Done. Fixed in master.
```
MONEY='twenty five bucks' dep blackjack
```
