### ISSUE TITLE
Improve Slack recipe with deployed commits

### ISSUE THREAD

**Issue by peterjaap** [deployphp/deployer#2750]
We've extended the Slack recipe a bit by adding some info about the latest deployment. This is a drop in task and hook, but maybe we can incorporate this in the default Slack recipe somehow?

```php
before('slack:notify:success', 'slack:build-message');

desc('Build Slack notification message with git logs');
task('slack:build-message', function () {
    $message = "Deployed commits:\n";
    $prevRef = trim(run('cd {{deploy_path}} && if [ -e .revision ]; then cat .revision; else echo 0; fi'));
    $currentRef = trim(runLocally('git rev-parse --verify HEAD'));
    if ($prevRef && $currentRef) {
        $message .= runLocally('git log ' . (string)$prevRef . '..' . (string)$currentRef . ' --format="%an: %s"');
    } elseif ($currentRef) {
        $message .= "Fresh deployment, these are the last 5 commits:\n";
        $message .= runLocally('git log -5  --format="%an: %s"');
    } else {
        $message .= 'Could not correctly fetch recent commits (previous commit: ' . $prevRef . ', current commit: ' . $currentRef . ')';
    }
    $message .= "\n";
    if (get('labels') && isset(get('labels')['stage'])) {
        $message .= "\nStage: " . get('labels')['stage'];
    }
    $branch = get('branch') ?? runLocally('git branch --show-current');
    $message .= "\nBranch: " . $branch;
    $message .= "\nHost: https://" . get('hostname');
    set('slack_title', 'Deploy successful');
    set('slack_success_text', $message);
});
```

**Comment by antonmedv** [comment]
Looks nice. But assumes deploy is done from CI. Locally can be checked out some branch and deployed master branch. 

We need to keep assuming what only piece of information we have is on remote host. 

All recipes is designed to be deployed from a local machine to one production host. And extension to build host, or CI is done by users. 


For example currently deployed ref can be retrieved from release-path/.REVISION.

**Comment by peterjaap** [comment]
Closing this, might be interesting for somebody else sometime.

**Comment by campaignupgrade** [comment]
@peterjaap I've been thinking about something like this a lot! I'm looking at it this way:

A process, possibly a git hooks, that looks at the previous Git release tag eg. v1.03
The same process increments the git tag e.g. v1.04
The creates a commit message that is a compilation of the first lines of the commit messages from the first to current tags. i.e. automatic release notes!
Deploys posts these release notes to Slack on successful deploy. 

Why would this be limited to CI though and not local run?
