### ISSUE TITLE
Improve Sentry recipe with environments

### ISSUE THREAD

**Issue by peterjaap** [deployphp/deployer#2753]
Here is our drop-in task & hook to configure Sentry so it will also add an environment along with a release. Maybe this can somehow be part of the Sentry recipe?

We have the Sentry API token in our CI/CD setup as an environment variable `SENTRY_API_TOKEN`, which is optional.

```yml
sentry_projectname: projectnamehere
sentry_organization: organizationnamehere
```

```php
if (getenv('SENTRY_API_TOKEN')) {
    require 'contrib/sentry.php';
}
```

```php
desc('Configure Sentry');
task('sentry:configure', function () {
    add('sentry', [
        'organization' => get('sentry_organization'),
        'projects' => [get('sentry_projectname'),
        'version' => get('release_name'),
        'token' => getenv('SENTRY_API_TOKEN'),
        'environment' => get('labels')['stage'] === 'production' ? 'production' : get('hostname'),
        'deploy_name' => get('labels')['stage'] === 'production' ? 'production' : get('hostname'),
        'url' => 'https://' . get('hostname')
    ]);
});
```

```php
if (getenv('SENTRY_API_TOKEN')) {
    before('deploy:sentry', 'sentry:configure');
    after('deploy:success', 'deploy:sentry');
}
```

Tagging all the people I could find that worked on this recipe; @Big-Shark @endelwar @atymic @hranicka @Gamesh @vkrms @petermein

**Comment by Gamesh** [comment]
seems like configuration is very specific to your project, not sure how it can be a default

**Comment by peterjaap** [comment]
What part is specific to my project? There are some fields available, which by default aren't used. This fills in those fields.

**Comment by Gamesh** [comment]
for example url, imagine this will not work for most, as hostname doesn't always correspond to project domain, especially if you're deploying on multiple servers, the same goes for deploy_name and environment. Maybe `get(labels)['stage']` could be used for environment
for everything else not sure, would need to check where the values currently are coming from

**Comment by peterjaap** [comment]
Ok yeah fair point, hadn't thought about the multi server bit.

**Comment by peterjaap** [comment]
Closing this, might be interesting for somebody else sometime.

**Comment by chrillep** [comment]
since the sentry recipe uses `get('symfony_env', 'prod')`
https://github.com/deployphp/deployer/blob/dbc39848a458ac7957d1975cb98808ea2ee87268/contrib/sentry.php#L83

use `->set('symfony_env', 'production')` in your host
```php
host('xxx')
  ->set('symfony_env', 'production')
  ...
  
  // or for staging
  
  host('xxx')
  ->set('symfony_env', 'staging')
  ...
```

sidenote: @antonmedv 
the docs says "By default framework's environment is used", that is `true` if you use symfony ;).
i use laravel then its not so true anymore :).

https://github.com/deployphp/deployer/blob/dbc39848a458ac7957d1975cb98808ea2ee87268/contrib/sentry.php#L13-L14


Also thanks for a great deployment experience with deployer! ❤️
