### ISSUE TITLE
Temporary workaround in shopware recipe uses constant path

### ISSUE THREAD

**Issue by phizab** [deployphp/deployer#2754]
- Deployer version: 7.0.0-rc2
- Deployment OS: Ubuntu 20.04

The following line in the shopware recipe fixes absolute paths in theme config files. But the given absolute path can vary from deployment to deployment:

`runLocally('sed -i "" -E \'s/\\\\\/var\\\\\/www\\\\\/htdocs\\\\\/releases\\\\\/[0-9]+\\\\\///g\' files/theme-config/*');`

In my case the project is stored in an other path than "/var/www/htdocs". There is currently no way to change this path.

Btw: if I'm right the workaround is no longer needed, since it was fixed in Shopware 6.4.6.0: https://issues.shopware.com/issues/NEXT-17720. Maybe the workaround can simply be deleted.

**Comment by antonmedv** [comment]
I didn’t get it) Can you make a pr to discuss it?

**Comment by phizab** [comment]
Created PR #2755 for removal of the workaround.

**Comment by peterjaap** [comment]
The PR mentioned causes deployments on 6.4.6.0 not to fail, but still won't work for <6.4.6.0 where the release path is not exactly the same as `/var/www/htdocs/releases`. So that needs to be fixed.

**Comment by peterjaap** [comment]
Example file;

```json
[
    {
        "storefront": {
            "path": "Resources\/app\/storefront\/src",
            "entryFilePath": "Resources\/app\/storefront\/src\/main.js",
            "webpack": null,
            "styleFiles": [
                "\/var\/www\/htdocs\/releases\/20211124115627\/vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/base.scss",
                "\/var\/www\/htdocs\/releases\/20211124115627\/vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/skin\/shopware\/_base.scss",
                "@Plugins"
            ]
        }
    }
]
```

Run `sed -E 's#\\/var\\/www\\/htdocs\\/releases\\/[0-9]+\\/##g' test.json`;

```
[
    {
        "storefront": {
            "path": "Resources\/app\/storefront\/src",
            "entryFilePath": "Resources\/app\/storefront\/src\/main.js",
            "webpack": null,
            "styleFiles": [
                "vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/base.scss",
                "vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/skin\/shopware\/_base.scss",
                "@Plugins"
            ]
        }
    }
]
```

**Comment by peterjaap** [comment]
@Schrank I did a PR here; https://github.com/deployphp/deployer/pull/2801/files

**Comment by UlrichThomasGabor** [comment]
@peterjaap Very clean work!

**Comment by Schrank** [comment]
Thanks!
