### ISSUE TITLE
Repository parsing incorrectly parses numbers after : char

### ISSUE THREAD

**Issue by sluxzer** [deployphp/deployer#2769]
- Deployer version: v7.0.0-rc.2
- Deployment OS: Ubuntu 20.04.2 LTS

Description:
i try run the command manual on server and no output or error is shown.
i try to disable ssh_multiplexing, but the error still occurs

![image](https://user-images.githubusercontent.com/5717315/142714139-8f67cf95-aa1c-4dd8-82f1-bde344ee833f.png)

Here my deploy.php
```
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/npm.php';

set('application', 'XXX XXX');
set('repository', 'git@github.com:xxx/xxx-xxx.git'); // Git Repository
set('ssh_multiplexing', true);  // Speed up deployment

// Set up a deployer task to copy secrets to the server.
// Grabs the dotenv file from the github secret
task('deploy:secrets', function () {
    file_put_contents(__DIR__ . '/.env', getenv('DOT_ENV'));
    upload('.env', get('deploy_path') . '/shared');
});

// Hosts
host('staging')
    ->setHostname('xxx') // Hostname or IP address
    ->set('remote_user', 'root') // SSH user
    ->set('branch', 'staging') // Git branch
    ->set('deploy_path', '/var/www/xxx-staging'); // Deploy path

after('deploy:failed', 'deploy:unlock');  // Unlock after failed deploy

desc('Start of Deploy the application');

task('deploy', [
    'deploy:prepare',
    'deploy:secrets',
    'deploy:vendors',
    'artisan:storage:link',  //
    'artisan:view:cache',    //
    'artisan:config:cache',  // Laravel specific steps
    'artisan:migrate',       //
    'artisan:queue:restart', //
    'npm:install',
    'npm:run:prod',
    'deploy:publish',
]);

desc('compile js to production');

task('npm:run:prod', function () {
    cd('{{release_path}}');
    run('npm run prod');
});

desc('End of Deploy the application');
```

**Comment by antonmedv** [comment]
Show original set('repository', 'git@github.com:xxx/xxx-xxx.git'); // Git Repository

**Comment by sluxzer** [comment]
> Show original set('repository', '[git@github.com](mailto:git@github.com):xxx/xxx-xxx.git'); // Git Repository



> Show original set('repository', '[git@github.com](mailto:git@github.com):xxx/xxx-xxx.git'); // Git Repository

here is the original

set('repository', 'git@github.com:4ingcreations/dpmptsp-tangsel.git'); // Git Repository

thanks for quick reply

**Comment by sluxzer** [comment]
@antonmedv i've good news, this error not occur on **v7.0.0-rc.1**, i try it out of my curiosity.

**Comment by antonmedv** [comment]
I think I know there’s error. Method of parsing repository url thinks it’s a port number 4.

**Comment by sluxzer** [comment]
> I think I know there’s error. Method of parsing repository url thinks it’s a port number 4.

i see, just realize it after you said it.

Sorry i can't contribute to fix this due to my lack of knowledge.

Thanks for your hardwork to build and maintain this package.

**Comment by antonmedv** [comment]
Fixed!
