### ISSUE TITLE
deploy:rollback in v3

### ISSUE THREAD

**Issue by ngmy** [deployphp/deployer#277]
I want to write a post-processing of exceptions in v3.

How do I write a process corresponding to v2 of the `deploy:rollback` task?

**Comment by elfet** [comment]
Sorry, can you explain in detail what you want to?

**Comment by ngmy** [comment]
Thank you for your quick reply.

I want to delete new release if something goes wrong:

```php
task('deploy:rollback', function () {
    if (env()->get('is_new_release', false)) {
        $server = config()->getName();
        writeln("<error>Rolling back to previous release on server $server</error>");
        $releasePath = env()->getReleasePath();
        // Remove release
        run("rm -rf $releasePath");
    } else {
        writeln("<comment>If you want to rollback run \"rollback\" task</comment>");
    }
});
```

In v2, the `deploy:rollback` task was called in `rollbackOnDeploy()` of `RunTaskCommand` class when an exception is thrown.

**Comment by elfet** [comment]
Hmmm, you can try to catch exception somehow. But i think it’s not possible now. We need to implement events in Deployer to make it possible.

**Comment by ngmy** [comment]
If the new release is not deleted when something goes wrong, I think it becomes a state that can not be rollback.

I use the common recipe and define the `deploy` task as following:
```
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:vendors',                                                                                                                                                    
    'deploy:symlink',
    'cleanup',
]);  
```

The Initial state of the `releases` directory:
```
20150524140000
20150525140000 <- current
```

After the failure by running the `deploy` task:
```
20150524140000
20150525140000 <- current
20150526140000 <- release
```

Again, after the failure by running the `deploy` task:
```
20150524140000
20150525140000 <- current
20150526140000
20150526140500 <- release
```

This moment, I want to rollback to the previous release of the `current` (that is `20150524140000`).
However, when I run the `rollback` task, the release will be rollback to `20150526140000` (this release does not work probably ).
```
20150524140000
20150525140000
20150526140000 <- current
```

**Comment by elfet** [comment]
Hmm, i angerstand the problem. 
But what if after failure i want to see what's broken? ssh to server and look at `20150526140000` myself? Than fix and continue deploying. 
Maybe it's better to tell user before new deployment, what there if a `release` symlink (ie deploy in process)? So user run `cleanup` task manually and understand 100% what happens on the server?

**Comment by ngmy** [comment]
Thank you for your reply.

I think that it is safe that the new release is automatically deleted (in terms of fool-proof), but you have a point. 

If the deployment fails, I decided to run the `rollback` task manually.
