### ISSUE TITLE
Project-local Deployer installation is detected before each task, flooding output

### ISSUE THREAD

**Issue by tfedor** [deployphp/deployer#2771]
- Deployer version: 7.0.0-rc2
- Deployment OS: Windows

Detection of project-local Deployer installation is executed before each task, producing "Using: " input.

1. Create `deploy.php` in the root of the project, alongside vendor folder with following tasks:
```
task("test:first", function() {
    echo "test #1\n";
});

task("test:second", function() {
    echo "test #2\n";
});

task("test", [
    "test:first",
    "test:second"
]);
```

2. Run `./vendor/bin/dep test` with output:
```
Using C:\Data\codes\isthereanydeal/vendor/bin/dep
#!/usr/bin/env php
task test:first
Using C:\Data\codes\isthereanydeal/vendor/bin/dep
#!/usr/bin/env php
test #1
task test:second
Using C:\Data\codes\isthereanydeal/vendor/bin/dep
#!/usr/bin/env php
test #2
```

On Windows, auto generated .bat is called, which calls directly `vendor/deployer/deployer/bin/dep`. That then detects that /vendor/bin/dep exists and calls that, which in turn again includes and executes `vendor/deployer/deployer/bin/dep`.

Since tasks are run as separate processes this happens before each task.

Maybe we can skip whole find if we first check whether `vendor/deployer/deployer/bin/dep` was called?
Something like
```php
if (!isset($localBinaryOverrideFound) && realpath($argv[0]) != realpath(__FILE__)) {
```
here: https://github.com/deployphp/deployer/blob/dddfab7b620eed8179c0f409402f219d2af598f6/bin/dep#L45

But not sure how that behaves on Linux.

**Comment by antonmedv** [comment]
Actually it’m sure any more if this feature is good. Maybe delete it all together.

**Comment by antonmedv** [comment]
Delete the message.
