### ISSUE TITLE
Branch can't be overriden

### ISSUE THREAD

**Issue by tfedor** [deployphp/deployer#2772]
- Deployer version: 7.0.0-rc2
- Deployment OS: Windows

1. create `config.yaml` containing set up for branch, e.g.:
```yaml
hosts:
  my_host:
    branch: branchA
```

2. create `deploy.php` containing:
```php
import("/deployer.yaml");
set("branch", "branchB");
```

3. run `dep deploy --branch branchC`

*Result:*
branchA is used, even though it should have been twice overwritten.

When I removed branchA from config, branchB was used, and when I removed branchB, branchC was used, so it seems like these are not being overwritten.

**Comment by antonmedv** [comment]
All works as expected. Here is why:
```yaml
hosts:
  my_host:
    branch: branchA
```

Declares host config. This one is used.

```php
set("branch", "branchB");
```

This is NOT override. Order of calls not matter. This declared a global config branch which is overrides in my_host.

```
dep deploy --branch branchC
```

Here is a documentation problem. This is not config override. It's just set CLI option, but it's not used in your example as you overrides in my_host.

To override it properly use:

```
dep deploy -o branch=branchC
```

I will think about how to improve `--branch` option.

**Comment by antonmedv** [comment]
Fixed. Now it's possible to override with `--branch` as well.
