### ISSUE TITLE
Composer 2 installation

### ISSUE THREAD

**Issue by aidavia** [deployphp/deployer#2774]
- Deployer version: 7
- Deployment OS: Mac OS

Team,

I am trying to install deployer 7 on my new Magento instance 2.4.3, but i get the following error message after: composer require deployer/deployer:^7.0.0

![image (13)](https://user-images.githubusercontent.com/75987096/142763001-d907a7bb-05c6-4c8a-a136-c13537c80075.png)

Are there any issues with this version and composer 2?

**Comment by antonmedv** [comment]
Install deployer/dist

**Comment by aidavia** [comment]
@antonmedv Thanks for the tip. How would i install this without affecting the minimum-stability for the rest of my packages set to "stable"

**Comment by aidavia** [comment]
@antonmedv Thanks for the tip. Quick question.  How can i use recipes with the distr version?

**Comment by antonmedv** [comment]
Like require contrib/npm.php

**Comment by aidavia** [comment]
@antonmedv I am asking since i tried doing require 'recipe/magento2.php' but it looks like there is no recipe folder in the distr package

I  get the following

![image](https://user-images.githubusercontent.com/75987096/142767371-005b244c-138d-45d6-8297-fe4559229c27.png)

**Comment by antonmedv** [comment]
This is strange. Can you create a repo for me there I can take look?

**Comment by aidavia** [comment]
@antonmedv yeah sure. You can take a look at this https://github.com/aidavia/magento2.4.3
