### ISSUE TITLE
Extend $PATH

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2778]
In the past it was possible to extend $PATH, but it is not anymore, because of the input is properly escaped.

@antonmedv What do you think about having an explicit method to prefix and/or suffix $PATH? Because I don't think it is possible to implement it generically - at least I feel unable to.

**Comment by Schrank** [comment]
imho we only need prefix.

**Comment by antonmedv** [comment]
Can you share examples of what you are trying to do?

**Comment by Schrank** [comment]
I have the problem, that on one machine we have installed multiple PHP versions. Thankfully I can just set `bin/php` but unfortunatelly does shopware run its own php process with `php` which the only way I see to change the version (default 8) is to overwrite `$PATH`, so I can change the version by redirecting the default php binary.

Looks currently like this:

   PATH: <release>/.dep:/var/www/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

**Comment by Schrank** [comment]
😂 Okay, than that :D

**Comment by Schrank** [comment]
That is awesome <3

**Comment by Schrank** [comment]
For anyoine else who is stumbling over it.

There is this as well:

```
// Path to the `php` bin.
set('bin/php', function () {
    if (currentHost()->hasOwn('php_version')) {
        return '/usr/bin/php{{php_version}}';
    }
    return which('php');
});
```

living in common.php
