### ISSUE TITLE
How to log into server

### ISSUE THREAD

**Issue by nWidart** [deployphp/deployer#278]
Hello,

I'm trying to understand how to use the `->forwardAgent() ` part of the deploy script.
I cannot seem to find any documentation about this.

I'd like to use my public ssh key to log into a server, naively I tried: ` ->forwardAgent('~/.ssh/id_rsa.pub')`, but doesn't work.

Could anyone point me in the right direction ?

Thanks,

**Comment by nWidart** [comment]
I'm sorry, I overlooked the [server part](http://deployer.org/docs/servers), I also had to provide private key and passphrase. `->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', '')`.

**Comment by elfet** [comment]
You can skip params, like this:
```
->identityFile();
```

**Comment by oanhnn** [comment]
@nWidart 
See more `forwardAgent` function in [here](https://github.com/deployphp/deployer/issues/232)
@elfet 
I think we need more documents about `server`, `stage`, and setting up for authentication into server.
