### ISSUE TITLE
Return codes of all functions

### ISSUE THREAD

**Issue by danshumaker** [deployphp/deployer#2782]
I've got a deploy recipe that I'm writing for Magento 2. It has a very complicated setup with several stages I need to check before doing things like compiling code ( https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-compiler.html ).

What I'd like to do in the recipe is something like 

```php
db_status = run('bin/magento setup:db:status');
app_status = run('bin/magento app:config:status');
ready = db_status && app_status;
if (ready) {
   run('bin/magento setup:di:compile');
}
```

I'm looking in the docs for deployer ( https://deployer.org/docs/7.x/api#task) and none of the functions document their return code.   

Can we add all the functions return codes to the documentation?   Will they return the linux code return code?   

When those commands return errors I don't want my git lab ci job to fail, I just want deployer to skip the current step.

It's sort of a chicken egg issue but I figure we all have similar issues when setting up deploys for the first time.

**Comment by antonmedv** [comment]
I didn't get it. What codes?

**Comment by danshumaker** [comment]
Often times when documenting a function in an API you specify the arguments/parameters and the return codes/values (for example https://www.php.net/manual/en/function.array-map.php see return values section.)

For linux processes you also get return codes/values (https://shapeshed.com/unix-exit-codes/) .   Any value greater than 0 is considered an error.  I would like to trap that value coming from my command ( https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-compiler.html  in this case) , but if your "run" function doesn't return what linux returns then it won't do me much good to act upon it.  

Does that make sense?

I can dig into your actual code to determine if the run command returns the numeric value from linux, but I thought that perhaps a quicker way to find out would be to check the documentation.  But I don't see return codes/values listed there, but I do see the normal parameters described.

**Comment by peterjaap** [comment]
All of this is already done in the default Magento 2 recipe; https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L147

It would be best to use that recipe, at least as a base. But if you want to write one completely custom, fine too, but there's your example.

**Comment by antonmedv** [comment]
Func run return output only if exit code is 0. Otherwise throws an exception with exit code.
