### ISSUE TITLE
Git subodules not working with `clone` strategy

### ISSUE THREAD

**Issue by matsn0w** [deployphp/deployer#2802]
Hey there,

Previously, there was a `git_recursive` option available in `deploy:update_code`, but that was [removed in March](https://github.com/deployphp/deployer/commit/a200c1f9b0159c30ae846c28b84b9a306f611fd7#diff-603dddef04f285d9a2ff024cb7bbe3d8c242011d0f7bca49a00446d769033325) :(

Why is this removed? Can it be restored?

Thanks in advance!

PS: some additional background info, I'm building a Laravel application using [Laravel Modules](https://github.com/nWidart/laravel-modules) where every module has its own repo. These need to be pulled upon deployment.. 

When using the `update_code_strategy` option `clone`, the `.git` directory is preserved. But when I then manually run `git submodule update` in a different task, I'm getting an error:

```
[production] run cd ***/releases/1 && (
    # clone the submodules
    git submodule init
    git submodule update
)
[production] Submodule 'Modules/[MODULE-1]' (***/.dep/[MODULE-1].git) registered for path 'Modules/[MODULE-1]'
[production] Submodule 'Modules/[MODULE-2]' (***/.dep/[MODULE-2].git) registered for path 'Modules/[MODULE-2]'
[production] fatal: repository '***/.dep/[MODULE-1].git' does not exist
[production] fatal: clone of '***/.dep/[MODULE-1].git' into submodule path '***/releases/1/Modules/[MODULE-1]' failed
[production] Failed to clone 'Modules/[MODULE-1]'. Retry scheduled
[production] fatal: repository '***/.dep/[MODULE-2].git' does not exist
[production] fatal: clone of '***/.dep/[MODULE-2].git' into submodule path '***/releases/1/Modules/[MODULE-2]' failed
[production] Failed to clone 'Modules/[MODULE-2]'. Retry scheduled
[production] fatal: repository '***/.dep/[MODULE-1].git' does not exist
[production] fatal: clone of '***/.dep/[MODULE-1].git' into submodule path '***/releases/1/Modules/[MODULE-1]' failed
[production] Failed to clone 'Modules/[MODULE-1]' a second time, aborting
[production] fatal: repository '***/.dep/[MODULE-2].git' does not exist
[production] fatal: clone of '***/.dep/[MODULE-2].git' into submodule path '***/releases/1/Modules/[MODULE-2]' failed
[production] Failed to clone 'Modules/[MODULE-2]' a second time, aborting
[production]  error  in deploy.php on line 26:
[production] exit code 1 (General error)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2802">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2802/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2802/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
This is strange. Can you debug why clone is not enough?

**Comment by matsn0w** [comment]
Hey, when I simply clone the repo, the Modules/ folder only contains two empty folders (one for each module). Normally, running `git submodule init` and `git submodule update` clones those repos.

**Comment by fnagel** [comment]
A simple `git clone` is not sufficient to checkout submodules (https://github.blog/2016-02-01-working-with-submodules/). Using `update_code_strategy` with `archive` will result in empty submodule folders too.

This is a real blocker when using submodules. There needs to be a `git submodule update --init` somewhere, but afaik this will not work with a bare repo.

**Comment by antonmedv** [comment]
Let’s add support for it via special option. 

Like git_submodules.

**Comment by fnagel** [comment]
This works for me when using `clone` `update_code_strategy `.

```
after('deploy:update_code', 'deploy:git:submodules');
task('deploy:git:submodules', function () {
    $git = get('bin/git');

    cd('{{release_path}}');
    run("$git submodule update --init");
});
```

**Comment by Sogl** [comment]
Today I also encountered the fact that cloning submodules was removed from v.7 🤔 

@antonmedv Can we also support submodules for `archive` mode?

Possible solutions:
1. [one](https://stackoverflow.com/a/46551763/4827198)
2. [two](https://github.com/chrismaes87/git-archive-with-submodules)
3. [three](https://github.com/fabacab/git-archive-all.sh)

**Comment by LinkPool2** [comment]
I'm currently setting up a new project with deployer and we're using a TYPO3-project with many, many submodules.

Yes, it should be 

`git clone --recursive `

to get the submodules checked out.

Without the --recursive option the submodule directories will be empty.

The approach from @fnagel does not work for me:

```
[staging01]  error  in deploy.php on line 162:
[staging01] run cd /data/www/sites/xxxxxxxx.de/releases/3 && (/usr/bin/git submodule update --init)
[staging01] err fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
[staging01] exit code 128 (Invalid exit argument)
ERROR: Task deploy:git:submodules failed!
```

I don't understand why this work for  @fnagel.

Very very sad that the --recursice option has disappeared :(

**Comment by bbceg** [comment]
With nested submodules I had to add '--recursive' on the end of @fnagel 's submodule update command so in full that line now reads: 

`run("$git submodule update --init --recursive");`

**Comment by finex** [comment]
Thanks to @fnagel for the workaround. It should be documented on the [UPGRADE](https://deployer.org/docs/7.x/UPGRADE) file.
