### ISSUE TITLE
Do not prefix bin/composer with bin/php

### ISSUE THREAD

**Issue by midweste** [deployphp/deployer#2823]
- Deployer version: v7.0

When using to deploy to a shared host that already has composer installed, I'm getting strange output from deploy:vendors.  Using -vvv I found what command it is trying to run in order to build the vendor folder but when running the command on the host directly it returns this:

```
$ /usr/local/bin/php /usr/local/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader

PHP_BIN=${PHP_BIN:-php-recommended}
exec /usr/local/bin/$PHP_BIN -d memory_limit=4096M /usr/local/bin/composer.phar "$@"
```
It's odd that it just outputs this as the result of the command
```
PHP_BIN=${PHP_BIN:-php-recommended}
exec /usr/local/bin/$PHP_BIN -d memory_limit=4096M /usr/local/bin/composer.phar "$@"
```

Not sure the reason composer would be prefixed by the php executable when its not using the composer.phar

https://github.com/deployphp/deployer/blob/d5c95324af8b70a0f20eae835947f9faed900a13/recipe/deploy/vendors.php#L16

Running the composer command without the php prefix works just fine.

I realize that I can redefine 'bin/composer' but something seems off to have to do that on a server with composer already accessible and in the path

**Comment by midweste** [comment]
Seems like some sort of alias the host is using in order to run php command on the currently selected php version

**Comment by midweste** [comment]
It indeed does seem like the host specific wrapper though not sure why it doesn't execute when prefixed by php

```
$ cat /usr/local/bin/composer
#!/bin/sh

PHP_BIN=${PHP_BIN:-php-recommended}
exec /usr/local/bin/$PHP_BIN -d memory_limit=4096M /usr/local/bin/composer.phar "$@"
```

**Comment by antonmedv** [comment]
Fixed.

**Comment by antonmedv** [comment]
45e4708aad31931805e37387ccb7940cae9c9149
