### ISSUE TITLE
`writable_mode = "chgrp"`, `chgrp` is recursive, `chmod` is not?

### ISSUE THREAD

**Issue by UlrichThomasGabor** [deployphp/deployer#2832]
Any special reason why
https://github.com/deployphp/deployer/blob/a2b3da8c3265d4327c987bf55b723e7cbc63a5c4/recipe/deploy/writable.php#L94
is not using `$recursive` as in the line before
https://github.com/deployphp/deployer/blob/a2b3da8c3265d4327c987bf55b723e7cbc63a5c4/recipe/deploy/writable.php#L93
?

This looks wrong to me (and does not work properly in my case here)

**Comment by antonmedv** [comment]
Yes. If should be fixed.
