### ISSUE TITLE
Use name instead of host in CLI parameters

### ISSUE THREAD

**Issue by bilogic** [deployphp/deployer#2833]
Hi,

> https://deployer.org/docs/7.x/basics

Some of my hostnames are very complex and hard to type, possible to allow the use of names instead? e.g. production, sandbox etc

Thank you!

**Comment by Schrank** [comment]
You can filter by labels, like: dep deploy name=sandbos.

but you need to set them first. Happy to provide an example once I have a proper keyboard

**Comment by Schrank** [comment]
https://github.com/deployphp/deployer/issues/2576#issuecomment-884832851

**Comment by Schrank** [comment]
Hope that helps!

**Comment by antonmedv** [comment]
Or just host alias: host(prod)->setHostname(long.host-name)

**Comment by mxts** [comment]
> Or just host alias: host(prod)->setHostname(long.host-name)

Ohh cool! I thought `host` had to be the FQDN. Perhaps call it `handle` instead? Thank you!

**Comment by antonmedv** [comment]
It’s in the docs https://deployer.org/docs/7.x/hosts

**Comment by bilogic** [comment]
Yes, but what I'm trying to say is, it doesn't jump out right to me that `host` can actually not be a `hostname` , given that it is named `host` and the example used a `example.org` FQDN.

It's ok, just a suggestion only. Thank you.

**Comment by Schrank** [comment]
@bilogic The idea is a good one. But I think we should stay with "host" as central entry point for configuration. Maybe it makes sense to rename the parameter 🤔

**Comment by antonmedv** [comment]
Or we can improve docs and add more examples.
