### ISSUE TITLE
cachetool breaks PHP 7.4 Compatibility

### ISSUE THREAD

**Issue by sprankhub** [deployphp/deployer#2836]
- Deployer version: v7.0.0-beta.24
- Deployment OS: Ubuntu 20.04

If you add the following to your `deploy.php` and try to deploy a PHP 7.4 project, you will get an error.

      after('deploy:symlink', 'cachetool:clear:opcache');

The error looks like this:

    [my.host.com] run if [ -f /my/path/releases/55/cachetool.phar ]; then echo +right; fi
    [my.host.com] run cd /my/path/releases/55 && curl -sLO https://github.com/gordalina/cachetool/releases/latest/download/cachetool.phar
    [my.host.com] run cd /my/path/releases/55 && /usr/bin/php7.4 /my/path/releases/55/cachetool.phar opcache:reset --fcgi=/var/run/my-socket.sock
    [my.host.com] Composer detected issues in your platform:
    [my.host.com] Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.26.
    [my.host.com] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.26. in phar:///my/path/releases/55/cachetool.phar/vendor/composer/platform_check.php on line 24
    [my.host.com]  error  in cachetool.php on line 80:
    [my.host.com] exit code 255 (Unknown error)

The issue is that the cachetool is always used in the latest version:

https://github.com/deployphp/deployer/blob/2d16b6d2a808df72d7c4c9067637d10067ee99e8/contrib/cachetool.php#L57

Unfortunately, the latest version dropped support for PHP 7, see https://github.com/gordalina/cachetool#compatibility.

I could not find any official information which PHP versions Deployer officially supports, but I think it should at least support all still maintained PHP versions (even if that PHP version only gets security fixes). So my suggested fix for now would be to fix the cachetool to version 7 and not use the latest version. Happy to send a PR.

What do you think?

**Comment by sprankhub** [comment]
Well, according to https://github.com/deployphp/deployer/blob/2d16b6d2a808df72d7c4c9067637d10067ee99e8/composer.json#L43, PHP 7.3 / 7.4 should be supported, so we should really fix this :)

**Comment by Schrank** [comment]
@sprankhub Can you send a PR please? I'm happy to merge a pinned version.

And a cherry on the cake would be if you add a configuration to set the version/url :-)

**Comment by sprankhub** [comment]
@Schrank, thanks for the fast answer. Please review the linked PR. And sorry, not time for a configuration option at the moment :see_no_evil:

**Comment by gordalina** [comment]
🙏

**Comment by jamieburchell** [comment]
Historically this seems to have been handled by checking the PHP version (https://github.com/deployphp/recipes/blob/master/recipe/cachetool.php#L13) but I suppose moving forward having to keep track of and updating this is not really viable.

**Comment by Schrank** [comment]
I think it makes sense for the current braking changes. And if it times in the future, we add new versions again 🤷 

So feel free to send another PR :D @jamieburchell 

Thanks for coming up with the historical data <3
