### ISSUE TITLE
Add mechanism (config or PHP API) for providing custom binary paths for each software used by deployer

### ISSUE THREAD

**Issue by kanevbg** [deployphp/deployer#2844]
https://github.com/deployphp/deployer/discussions/2843
Eg. for ssh, rsync, etc.

**Comment by Schrank** [comment]
You can do it by using https://deployer.org/docs/7.x/api#remoteenv and add paths to $PATH.

Does this solves your problem?

**Comment by kanevbg** [comment]
It may, but this seems tricky, I am asking for direct support based on deployer's context.

So I can set it per task, per host, etc with ease.

**Comment by antonmedv** [comment]
We already doing it with bin/php, bin/composer, bin/symlink.

**Comment by Schrank** [comment]
I don't see a reason why not to do it with "everything" - feel free to provide a PR! :-)

**Comment by Schrank** [comment]
Or on a smaller scale: Everything which sucks for you, throw it into a config setting.
