### ISSUE TITLE
Deployer does not exit

### ISSUE THREAD

**Issue by bilogic** [deployphp/deployer#2853]
- Deployer version: Deployer 7.0.0-rc.2 
- Deployment OS: ubuntu impish

I use deployer to take backups as well as make deployments.

If my task starts a worker queue locally, deployer does not exit.
It only exits after I kill the worker process using another terminal.

Any way to allow starting a worker queue?

**Comment by antonmedv** [comment]
An example?

**Comment by bilogic** [comment]
@antonmedv 

Thanks for getting back, I tried to create a short example to narrow down the suspected culprit `exec()`, but was not successful in proving it. 

Nonetheless, if you run `core:test`, it should exit quickly, however when I `runLocally("php artisan core:test")`, deployer does not exit. You will need Laravel in order to run my example. Sorry about this.

```PHP
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Queue;

class CoreTest extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'core:test {--t|tries=1 : Number of times to check, useful if waiting for queue:worker to die}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Ensure queue:work process is running';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $tries = $this->option('tries');
        $job_count = Queue::size();
        $this->line("- There are <comment>$job_count jobs</comment> in the queue");
        $this->line("- Will check up to $tries time(s)");
        $path = base_path();

        $cmd = 'artisan queue:work --queue='.config('app.name').',default --tries=3';

        $pidfile = storage_path('app/queue/'.gethostname().'-work.pid');
        $stderr = storage_path('app/queue/stderr');
        $dirname = dirname($pidfile);
        if (! file_exists($dirname)) {
            mkdir($dirname, 0777, true);
        }

        $executed = false;
        while ($tries > 0) {
            $is_running = false;
            // $reason = "";
            if (file_exists($pidfile)) {
                $pid = file_get_contents($pidfile);
                $cleanedpid = strval(str_replace("\0", '', $pid));
                $fd = "/proc/$cleanedpid/cmdline";
                if ($cleanedpid != '') {
                    if (file_exists($fd)) {
                        // check that the running process cmdline matches what we want to run
                        $raw_cmd = file_get_contents("/proc/$pid/cmdline");
                        $running_cmd = trim(str_ireplace("\0", ' ', $raw_cmd));
                        if (stripos($running_cmd, $cmd) !== false) {
                            $is_running = true;
                        }
                    }
                }
            }
            if (! $is_running) {
                $this->line('- Starting queue:work process.');
                $this->line("- Running <comment>$cmd</comment>...");

                $command = "php -d register_argc_argv=1 {$cmd} >/dev/null 2>{$stderr} & echo $!";
                $number = exec($command);
                file_put_contents($pidfile, $number);

                $err = file_get_contents($stderr);
                if ($err != '') {
                    throw new \Exception($err);
                }
                $executed = true;
                break;
            }
            $tries--;
            sleep(1);
        }

        if (! $executed) {
            $this->error("- <comment>$cmd</comment> already running. Nothing to do.");
        }

        $this->info('- Exiting now');

        return Command::SUCCESS;
    }
}
```

```PHP
task('test', function () {
    // the 3 lines below exit correctly, I'm not sure what the issue is now
    // $cmd = '-r "sleep(1000);';
    // $stderr = 'err.log';
    // runLocally("php -d register_argc_argv=1 {$cmd} >/dev/null 2>{$stderr} & echo $!");
    
    // the 3 lines below will not exit even though core:test has completed
    runLocally('php artisan queue:restart');
    sleep(3);
    runLocally('php artisan core:test');
});
```

OUTPUT
```
task test
[live] run locally php artisan queue:restart
[live] Broadcasting queue restart signal.
[live] run locally php artisan core:test
[live] - There are 0 jobs in the queue
[live] - Will check up to 1 time(s)
[live] - Starting queue:work process.
[live] - Running artisan queue:work --queue=App,default --tries=3...
[live] - Exiting now
```

**Comment by antonmedv** [comment]
I think this is because exec is never returned and blocking Deployer task.

**Comment by bilogic** [comment]
@antonmedv `exec()` does return, see `[live] - Exiting now`

**Comment by antonmedv** [comment]
Yes, I see. For some reason runLocally thinks its not done. The rubLocally is actually just fancy wrapper around Symfony/Process. Can you try using it directly?

**Comment by bilogic** [comment]
What is it that I should try? Call `Symfony/Process` myself? How about I try `exec('php artisan core:test')`?

**Comment by bilogic** [comment]
Ok, `exec('php artisan core:test');` did not work as well.

**Comment by bilogic** [comment]
Any idea how to tackle this? Thank you.

**Comment by Schrank** [comment]
If I remember correctly, & only forces background. Unfortunately it is still attached to the ssh session, so if you disconnect, the process is killed.

the only solution for this I know is `screen`

**Comment by Schrank** [comment]
That means, you either don’t & and wait for the process‘ end or use screen, but have an endless running screen session + process

**Comment by bilogic** [comment]
@Schrank

Do you know location of the code that is waiting for the process to end?
I tend to think that restarting the queue worker should be considered as part of deployment, just like bringing down and up the website.

**Comment by Schrank** [comment]
I do only assumptions (!!)
Here is what I think:
- Deployer is opening an ssh connection
- Starting a process (or more than one)
- Waiting for the ssh connection to be process free
- Close it

and this is not deployer explicitly. It is deployer waiting for a „free“ ssh connection and the way & works it doesn’t happen.

So I guess the better way (cents just dropped here 😅) is to run your workers via serviced or systemd and call it to restart them. I would assume then the ssh connection is „free“ because systemd/serviced isn’t attaching them to ssh.

assumptions over assumptions. Hope it helps!

**Comment by antonmedv** [comment]
So what's the status? Let's close it for clean-up purposes. 

If it is still the problem, let's reopen the issue.
