### ISSUE TITLE
commands fail if server uses fish as default shell

### ISSUE THREAD

**Issue by lazka** [deployphp/deployer#2854]
Using Deployer v7.0.0-rc.3

When I run `dep releases stage=development` I get

```
task releases                                                                                                          
[development]  error  in release.php on line 17:
[development] run cd /home/user/app && (if [ -f .dep/releases_log ]; then echo +right; fi)
[development] err fish: Command substitutions not allowed
[development] exit code -1 (Unknown error)
```

Using `host(...)->setShell('bash')` fixes things, but the docs says that bash should be the default. Maybe that isn't true?

**Comment by antonmedv** [comment]
Yes, bash is default https://github.com/deployphp/deployer/blob/cfcb963ead5f993157d20478c8332c0c93908337/src/Deployer.php#L125

Check you .ssh/config.

**Comment by lazka** [comment]
Ah, you are right. It is `bash -ls`, but for some reason that invokes fish again on my server.

Sorry for the noise.
