### ISSUE TITLE
Branch and target are always reported as HEAD

### ISSUE THREAD

**Issue by jakobbuis** [deployphp/deployer#2858]
- Deployer version: v7.0.0-rc.3
- Deployment OS: Ubuntu 20.04.3

```php
task('check', function () {
    echo get('branch'); 
    echo get('target');
});
```

Previously, using deployer 6 this would report "main" which is the name of our primary branch and "staging" for target. Using the RC.3 release candidate  it reports both values as HEAD. 

This also occurs in the MS-Teams webhook with default messages set:
![Screenshot from 2021-12-22 16-55-05](https://user-images.githubusercontent.com/949674/147119898-d0c337ab-e62b-4dfc-9ac9-f8586886bb64.png)

And when I run `dep config` I get the following output (redacted):
```
staging:
    branch: HEAD
    target: HEAD
    // other values redacted
```

**Comment by antonmedv** [comment]
Works for me.

**Comment by antonmedv** [comment]
Can’t reproduce.

**Comment by jakobbuis** [comment]
I'm thinking this is because we had this task marked as `->local()`, which has been removed, and our deployment targets don't have git installed, so can't determine which branch we're on. I'll double-check.

**Comment by robbertrosario** [comment]
@jakobbuis did you manage to get this working? I'm using Deployer 7.0.2 and not using `->local()` and have the same problem.

`dep config` also returns branch: HEAD and target: HEAD even though the deployment targets do have git installed.
