### ISSUE TITLE
Mysql command behaving strangly

### ISSUE THREAD

**Issue by nWidart** [deployphp/deployer#286]
Hello,

I'm trying to swap the database per release too.
By doing to the following steps.

1. Export old database
2. Create new database (suffixing with latest release int)
3. Import old database into newly created one

Step 1 and 2 or ok. Then on step 3:
run("mysql -pmypwd -e '$newDatabaseName < {{deploy_path}}/shared/$oldDatabaseName.sql;'");

Throws: 
```
 ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'asgard_staging_20150523132714 < "/home/forge/staging.asgardcms.com/shared/asgard' at line 1`
```

This is strange since, just before this `run` command I have the following dumps, which output the correct data:

```
writeln("old db name: $oldDatabaseName");
writeln("new db name: $newDatabaseName");
```

![screen_shot_2015-05-23_at_12_46_11_pm](https://cloud.githubusercontent.com/assets/882397/7783817/02fe387a-0150-11e5-90a8-908bdac7d9e1.png)

For some reason it doesn't want to 'fill' in the file name to import ... I've even tried to hardcode the file to import, even that stops at `asgard_`.

I can't figure out why this is happening...

Thank you,

Edit:

After a long stare at the code, and multiple tried...

```
run("mysql -pMyPwd $newDatabaseName < {{deploy_path}}/shared/$oldDatabaseName.sql");
```
Doesn't throw the error.

Though I think the export isn't done properly, since it didn't import any data in the new database name.
When checking the contents of the exported SQL:

```

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `asgard_staging_20150523132714` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `asgard_staging_20150523132714`;
```
It's using the old database name in the exported sql file. 
I need to figure out how to somehow export the current database **tables** with the database name.

Edit 2: I can suppress the `create database` part using the `--no-create-db` flag on the export command. Though this still leaves the `USE ` statement... 

Edit 3: Found the solution, removing the `--databases` flag removes the use statements: 

```
run("mysqldump --defaults-file=/etc/mysql/my.cnf --no-create-db $oldDatabaseName > {{deploy_path}}/shared/$oldDatabaseName.sql");
```

**Comment by elfet** [comment]
Feel free to ask any questions :)
