### ISSUE TITLE
Allow Symfony 6 in Deployer 7 rc releases

### ISSUE THREAD

**Issue by wucdbm** [deployphp/deployer#2860]
Heya,

Would you be willing to up the dependency on Symfony to ^5|^6, I'd like to test 7.0 with Symfony 6

**Comment by antonmedv** [comment]
You can use deployer/dist instead.

**Comment by Schrank** [comment]
Let me emphasize that:
**Your build, deployment, testing tools should all be phar files to not poisen your dependencies :D**

**Comment by wucdbm** [comment]
Do we copy/paste recipes from the main repo then

**Comment by wucdbm** [comment]
Well, then there's that `PHP Notice:  fread(): Read of 8192 bytes failed with errno=5 Input/output error in phar:///usr/local/bin/dep/vendor/symfony/process/Pipes/UnixPipes.php on line 121`

**Comment by antonmedv** [comment]
Ohh, this is the real issue.
