### ISSUE TITLE
Wrong regexp for repository URL with credentials

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#2863]
- Deployer version: 7.0.0-rc.3
- Deployment OS: Ubuntu 20.04

The [regexp](https://github.com/deployphp/deployer/blob/92a0eb6eb156a0d891af64eca6715e5973a15847/recipe/deploy/update_code.php#L35) for https repositories is wrong: for example, with this repo URL `https://myuser:mypass@bitbucket.org/myrepo/` is getting the user as first match.

In my deploy.php I have `set('repository', 'https://myuser:mypass@bitbucket.org/myrepo.git');` and the error when I try to deploy is

>[production]  error  in update_code.php on line 42:
[production] run ssh-keygen -F myuser:22 || ssh-keyscan -p 22 -H myuser >> ~/.ssh/known_hosts
[production] err getaddrinfo myuser: Temporary failure in name resolution

**Comment by sts-ryan-holton** [comment]
Same issue

**Comment by antonmedv** [comment]
Fixed in fb6f2154ef36f03e4e4b0644206b06722ee09fd8
