### ISSUE TITLE
'dep' is not recognized

### ISSUE THREAD

**Issue by sutcliffe121** [deployphp/deployer#2869]
- Deployer version: deployer:v7.0.0-rc.3
- Deployment OS: Windows 10 Pro 64-bit
- Laravel 8.33.1
- Composer v2.0.12 2021-04-01 10:14:59

I install deployer into my project using:
'composer require deployer/deployer:v7.0.0-rc.3'

When I run 'dep init' in my terminal, I get:
'dep' is not recognized as an internal or external command,
operable program or batch file.

I am trying to follow:
https://lorisleiva.com/deploy-your-laravel-app-from-scratch/install-and-configure-deployer

Any help would be appreciated.
Thanks,

**Comment by Schrank** [comment]
You need to install deployer globally to run it via dep.

But if you are just starting, let me recommend you to NOT install testing, building and deployment tools like phpunit and deployer using composer but to use phar files. This way you don't have conflicts with your dependencies like symfony/console versions.

That said to fix your problem: Download https://github.com/deployphp/deployer/releases/download/v7.0.0-rc.3/deployer.phar put it somewhere, e.g. in your project (then you need to run `./deployer.phar`) or you can copy it over to `/usr/local/bin/dep` (this way it is available everywhere, so you can run ´dep`).

Hope that helps! And don't forget to `chmod +x deployer.phar`

If you have more questions or need help, tell us!

**Comment by mkocansey** [comment]
As a follow up to the comment by @Schrank ..  if you moved your deployer.phar file over to `/usr/local/bin/dep` then `chmod +x` should actually be applied to `/usr/local/bin/dep`
