### ISSUE TITLE
Tests before deploy

### ISSUE THREAD

**Issue by leandrogehlen** [deployphp/deployer#287]
I use in my application, Is there any way for run this tests before deploy?

Currently, i run manually this tests with following script
```php
$app = new Application('Codeception', Codecept::VERSION);
$app->setAutoExit(false);
$app->add(new Build('build'));
$app->add(new Run('run'));
$app->run(new ArrayInput( array('build') ));

$test = (isset($opts['t'])) ? $opts['t'] : '';
$coverage = (isset($opts['c'])) ? ' --coverage-html --coverage-xml' : '';

$app->run(new StringInput( 'run unit ' . $test . ' ' . $coverage) );
```

**Comment by leandrogehlen** [comment]
Another problem is that composer execute with param `--no-dev`

https://github.com/deployphp/deployer/blob/master/recipe/common.php#L235

**Comment by oanhnn** [comment]
@leandrogehlen , I think you can override this task for your case.
Add this code to `deployer.php` file, after line `require 'recipe/common.php';`
```php
/**
 * Installing vendors tasks.
 */
task('deploy:vendors', function () {
    if (commandExist('composer')) {
        $composer = 'composer';
    } else {
        run("cd {{release_path}} && curl -sS https://getcomposer.org/installer | php");
        $composer = 'php composer.phar';
    }
    run("cd {{release_path}} && {{env_vars}} $composer install --dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction");
})->desc('Installing vendors');
```

**Comment by elfet** [comment]
You can run tests locally too:
~~~php
task('test', function () {
    runLocally('cd project_dir && php vendor/bin/phpunit');
});
~~~

**Comment by leandrogehlen** [comment]
i made what @oanhnn suggested,

I think it could be created stage dependencies.
This means, the production stage occurs after the test stage, but if test fail does not will run production

The problem of the tests run locally, that is, will not be replicated routine deploy.
thus, it is necessary, update sources and composer manually

**Comment by kenjis** [comment]
I added `deploy:vendors-dev` task. Why don't you add a task like this to `common.php`?

```php
task('deploy:vendors-dev', function () {
    if (commandExist('composer')) {
        $composer = 'composer';
    } else {
        run("cd {{release_path}} && curl -sS https://getcomposer.org/installer | php");
        $composer = 'php composer.phar';
    }

    run("cd {{release_path}} && $composer install --verbose --prefer-dist --no-progress --no-interaction");
})->desc('Installing vendors including require-dev');
```

**Comment by leandrogehlen** [comment]
i think that should be used is a param like `set('composer_args', '--no-dev');`

**Comment by kenjis** [comment]
@lasselehtinen We run the task (`composer install`) twice. One is for testing, the other is for deployment. So, I think two tasks, `deploy:vendors-dev` and `deploy:vendors` are easy to understand.

Is it possible to use `set()`?

**Comment by vdBergMike** [comment]
> You can run tests locally too:
> 
> ```
> task('test', function () {
>     runLocally('cd project_dir && php vendor/bin/phpunit');
> });
> 
> before('deploy', 'test');
> ```

Even after all these years, this still works with the latest Deployer version. Thanks!
