### ISSUE TITLE
Overwriting existing tasks silently drops before/after hooks

### ISSUE THREAD

**Issue by UlrichThomasGabor** [deployphp/deployer#2878]
- Deployer version: 7.0.0-rc3

Overwriting an existing task by using `task()`, for example:
```php
task('deploy:update_code', static function () {
        // whatever
    ]);
});
```
results in removing all before/after hooks because the collection just replaces the whole task:
https://github.com/deployphp/deployer/blob/10a2f43b0a0b625c661741154230fa50a4abb5c1/src/functions.php#L198

I think this is unexpected and caused a silent issue on my side.

Can this be changed to either use `Task::setCallback()` when a task already exists or at least print a warning when an existing task is overwritten?

**Comment by antonmedv** [comment]
Yes, I this only callback should be replaced.

**Comment by lkraav** [comment]
So it's still unsafe to override tasks in [v7.0.0-rc.4](https://github.com/deployphp/deployer/releases/tag/v7.0.0-rc.4) and have to wait for another release?

I'm trying to avoid unpacking `deploy:prepare` for replacing `deploy:update_code` with `rsync`, but looks like I have to until next release?
