### ISSUE TITLE
Add new update_strategy rsync which do not require git repositoryy

### ISSUE THREAD

**Issue by alexander-schranz** [deployphp/deployer#2889]
- Deployer version: 7.0-rc3
- Deployment OS: MAC OSX Monterey

When configuring rsync for deploying my application: https://deployer.org/docs/7.x/contrib/rsync 

The `update_code` still requires `git` and that a `repository` is defined. 

Would be nice if the `deploy:prepare` works with `rsync` only when its configured and not requires to clone a repository. Maybe I'm misunderstanding and something like a feature for using a `update_strategy` `rsync` could be added?

`deploy.php` from the docs: https://deployer.org/docs/7.x/contrib/rsync

```php
host('hostname')
    ->hostname('10.10.10.10')
    ->set('rsync_src', __DIR__)
    ->set('rsync_dest','{{release_path}}');
    
task('deploy', [
    'deploy:prepare', // prepare fails as it depends on update_code as it depends on repository
    'deploy:release',
    'rsync',
    'deploy:vendors',
    'deploy:symlink',
])->desc('Deploy your project');
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2889">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2889/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2889/pledge.svg">
</picture>
</a>

**Comment by alexander-schranz** [comment]
My current workaround is doing the following:

```php
/** @var GroupTask $deployPrepareTask */
$deployPrepareTask = task('deploy:prepare');

$tasks = [];
foreach ($deployPrepareTask->getGroup() as $key => $value) {
    $tasks[$key] = 'deploy:update_code' === $value ? 'rsync' : $value;
}

task('deploy:prepare', $tasks);
```

Looks like something like `update_strategy`: `rsync` is what would be what I'm searching for which does not yet exist. So I will convert this "bug report" to "feature request".

**Comment by antonmedv** [comment]
You can also do this:
```php
task('deploy:update_code')->disable();
```

**Comment by alexander-schranz** [comment]
@antonmedv so I could go with:

```php
task('deploy:update_code')->disable();
after('deploy:update_code', 'rsync');
```

Or would rsync then not be executed?

**Comment by antonmedv** [comment]
You can verify it via:
```
dep tree deploy
```
Or 
```
dep deploy all --plan
```

**Comment by alexander-schranz** [comment]
The `--plan` it shows only the command which are executed, thats great 👍 .

The tree output was not clear for me as it was listed this way:

```
    │   ├── deploy:update_code  // disabled
    │   ├── rsync  // after deploy:update_code
```

Personally would not show the disabled commands by default and remove the // after to avoid confusen:

```diff
-    │   ├── deploy:update_code  // disabled
-    │   ├── rsync  // after deploy:update_code
+    │   ├── rsync
```

Maybe have a verbose output which would add disabled task and the after comments.

**Comment by satyakresna** [comment]
Thanks for create this issue, more than weeks I'm facing the problem with `git clone` via ssh then `rsync` come to rescue!

**Comment by antonmedv** [comment]
@satyakresna what is your problem with git? Check what you gave deploy_keys, and updated known_hosts.

**Comment by satyakresna** [comment]
We use self hosted git server in our ompany. I already add deploy keys and update known_hosts. But, it doesn't work and our infra team say that there's a problem in git server and still on progress to fix it. So, I choose to use rsync instead of `git clone`.

**Comment by mandrasch** [comment]
Hey everyone! A simple rsync-only example in the docs would be awesome! Came across this when we tried to build a typo3 project in bitbucket pipeline and wanted to rsync it to the target server. It's work in progress. If some has published an example, please let me know! :-)

**Comment by alexander-schranz** [comment]
You need a 7.* version, there the disable exists: https://github.com/deployphp/deployer/blob/v7.3.3/src/Task/Task.php#L262.

You can download the `.phar` directly from the [Github Releases Page](https://github.com/deployphp/deployer/releases): https://github.com/deployphp/deployer/releases/download/v7.3.3/deployer.phar

**Comment by DanielRuf** [comment]
> You can download every deployer.phar version directly from the [Github Releases Page](https://github.com/deployphp/deployer/releases): https://github.com/deployphp/deployer/releases/download/v7.3.3/deployer.phar

Please check my comment again, I had updated it. It seems the documentation for v7 does not mention the phar releases anymore. Try searching for "phar" at https://deployer.org/docs/7.x/installation

I had looked at the releases page then and found it. After that I had updated my comment.
