### ISSUE TITLE
Support comma separated list of deployment hosts

### ISSUE THREAD

**Issue by sts-ryan-holton** [deployphp/deployer#2899]
I'm using Deployer version 6 and would like to be able to use a comma separated list of deployment hosts. Currently only ranges are supported which could be quite dangerous for some setups, I'd like to provide a list of values such as:

`[10,11,12]`

example:

```php
host('ipv6:[36:37:38]')
    ->set('branch', 'dev')
    ->stage('brands')
    ->set('repository', 'git@fudge:company/application-fudge')
    ->user('root')
    ->set('deploy_path', '/var/www/include-forms/fudge');
```

**Comment by antonmedv** [comment]
You can list a few hosts as args.
