### ISSUE TITLE
M2: Config Import Not Executed For Patch Versions

### ISSUE THREAD

**Issue by sprankhub** [deployphp/deployer#2905]
- Deployer version: master
- Deployment OS: Ubuntu 20.04

The Magento version detection does not detect patch versions correctly:

https://github.com/deployphp/deployer/blob/b6d646d8e34f19df10e9b8edfa1c3a8c497809d3/recipe/magento2.php#L62

This will detect `Magento CLI 2.4.3-p1` incorrectly as `1` due to the `-p1` suffix. Hence, no config import will be executed:

https://github.com/deployphp/deployer/blob/b6d646d8e34f19df10e9b8edfa1c3a8c497809d3/recipe/magento2.php#L109-L112

This may lead to an error after the deployment.

I am working on a fix right now.

**Comment by antonmedv** [comment]
Can we separate this regexp in separate file and add tests for Magneto versions?

we saw quite of error on it.

**Comment by sprankhub** [comment]
Sure, we could, even though this would be much more effort :see_no_evil: If you think this should really be done, please create a new issue or re-open this one.

**Comment by antonmedv** [comment]
It’s just one unit test) Just copypaste regexp there and add comment to not forget update both of them simultaneously)
