### ISSUE TITLE
upgrade script for deploy.php v7?

### ISSUE THREAD

**Issue by vesper8** [deployphp/deployer#2909]
With v7 release looming around the corner, it would be nice if you or someone could cook up a nice little upgrade script (possibly in bash?) to make all the needed replacements to the deploy.php

I have over 50 deploy.php files and upgrading each of them seems like it's going to be quite tedious and take a while, I'm not sure but judging by the needed changes I think using tools like `sed` it should be possible to make all the replacements programatically?

What do you think?

**Comment by Schrank** [comment]
I would assume (as always) it is not 100% possible, but fixing 90% is already a win!

Do you want to provide a PR or a script on the readme? :-)

**Comment by antonmedv** [comment]
We have a doc on how to upgrade from v6 to v7: https://deployer.org/docs/7.x/UPGRADE

I think creating an automatic script is difficult, dangerous, and error-prone. For example, one of the steps requires special -o attributes on the first deploy with v7.

v7 is not just renaming of old methods (sorry can't just sed) but a paradigm change, with lots of breaking changes.

My recommendation is to leave old projects to v6. It still works, isn’t it? And upgrade to v7 if you really want some of the new features.
