### ISSUE TITLE
Issues with bin paths when using v7.0.0-rc.4

### ISSUE THREAD

**Issue by fnagel** [deployphp/deployer#2910]
- Deployer version: v7.0.0-rc.4
- Deployment OS: Ubuntu

When using the new RC 4 I'm no longer able to use bin path config as before due `composer install` fails.

This works in v7.0.0-rc.3 without issues:

```
hosts:
  development:
    bin/php: /usr/bin/php80
```

**Comment by antonmedv** [comment]
What's the error?

**Comment by antonmedv** [comment]
Related #2823

**Comment by fnagel** [comment]
> What's the error?

It's using the default CLI PHP (7.2.x) instead of the PHP 8.0 bin and so the install fails due to wrong constraints.

**Comment by fnagel** [comment]
#2823 definitely causes this error for me. I think I could add a bin path for composer with prefixed php bin to fix this, but it looks like the issue in 2823 is caused by a misconfiguration of the server.

**Comment by antonmedv** [comment]
I think it's caused by a new composer wrapper scripts, there bin/composer is not a phar but a bash wrapper script.

**Comment by antonmedv** [comment]
Fixed.
