### ISSUE TITLE
\Exception in Context.php line 50 - Context was requested but was not available.

### ISSUE THREAD

**Issue by michaelhume** [deployphp/deployer#2911]
- Deployer version: 7.0.0-rc.4
- Deployment OS: [Laravel Docker:8.0](https://github.com/lorisleiva/laravel-docker) *linux/amd64*

I ran into an exception when trying to deploy using 7.0.0-rc.4

```
 Deployer\Exception\Exception  in Context.php on line 50:

  Context was requested but was not available.
```

[edit] No changes to my deploy.php file since the last time this passed [/edit]

As a sanity check, tried to run a simple `dep releases` on my local machine and received the same error. Stack trace says:

```
==> dep releases -vvv
 Deployer\Exception\Exception  in Context.php on line 50:

  Context was requested but was not available.

#0 <path>/vendor/deployer/deployer/src/functions.php(108): Deployer\Task\Context::get()
#1 <path>/vendor/deployer/deployer/src/functions.php(350): Deployer\currentHost()
#2 <path>/vendor/deployer/deployer/src/functions.php(399): Deployer\{closure}('supervisorctl r...', Array)
#3 <path>/deploy.php(42): Deployer\run('supervisorctl r...')
#4 <path>/vendor/deployer/deployer/src/Importer/Importer.php(55): require('/Users/michaelh...')
#5 [internal function]: Deployer\Importer\Importer::Deployer\Importer\{closure}()
#6 <path>/vendor/deployer/deployer/src/Importer/Importer.php(64): call_user_func(Object(Closure))
#7 <path>/vendor/deployer/deployer/src/Deployer.php(315): Deployer\Importer\Importer::import(Array)
#8 <path>/vendor/deployer/deployer/bin/dep(98): Deployer\Deployer::run('7.0.0-rc.4', '/Users/michaelh...')
#9 <path>s/vendor/bin/dep(107): include('/Users/michaelh...')
#10 {main}
```

My deployment is pretty simple, but for good measure, here is the layout of my `deploy.php` file

```php
namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/php-fpm.php';
require 'contrib/npm.php';

// Config
set('repository', MY_REPO_PATH);
set('application', MY_APP_NAME);
set('php_fpm_version', '8.0');
set('keep_releases', '3');
set('http_user', MY_USER);
set('http_group', MY_GROUP);

// Hosts
host('development')
    ->set('hostname', MY_DEV_HOST)
    ->set('remote_user', MY_REMOTE_USER)
    ->set('deploy_path', MY_DEV_DEPLOY_PATH);

host('production')
    ->set('hostname', MY_PRODUCTION_HOST)
    ->set('remote_user', MY_OTHER_REMOTE_USER)
    ->set('deploy_path', MY_PRODUCTION_DEPLOY_PATH);

// Tasks
task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'artisan:view:cache',
    'artisan:config:clear',
    'artisan:migrate',
    'npm:install',
    'npm:run:prod',
    'deploy:publish',
    'php-fpm:reload',
    'deploy:writable',
    run('supervisorctl reload'),
    run('supervisorctl restart')
]);

task('npm:run:prod', function () {
    cd('{{release_or_current_path}}');
    run('npm run prod');
});

after('deploy:failed', 'deploy:unlock');

```

I'm deploying from GitLab CI/CD and been using v7 since the beginning for this project. 

Thanks for all your work on this project!!

**Comment by michaelhume** [comment]
Looking closer it seems that I did get the error on the last deployment as well, but the pipeline didn't fail for some reason.

**Comment by michaelhume** [comment]
Turns out this is a me problem.

**Comment by Schrank** [comment]
@michaelhume Sorry to hear, good you found a solution! If it helps the community with their me problems, we are happy, if you leave a few sentences of explanation here :-)

**Comment by michaelhume** [comment]
Sure thing - 

The lines causing the Exception were:

```php
// Tasks
task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'artisan:view:cache',
    'artisan:config:clear',
    'artisan:migrate',
    'npm:install',
    'npm:run:prod',
    'deploy:publish',
    'php-fpm:reload',
    'deploy:writable',
    // run('supervisorctl reload'),     <----- Exception disappears when these are commented out 
    // run('supervisorctl restart')
]);
```

The stranger part was that my pipeline was passing and since this project is still in the dev phases I wasn't actually paying attention to the results on the server as I'm just working locally.

Upon closer inspection, this had been failing since mid November!! 

I had a bunch of other issues that revealed themselves once I got the deployer to actually run, so I haven't been able to track down why those two commands are actually causing an Exception.

If you have any ideas - I'd be happy to hear them!

**Comment by antonmedv** [comment]
You are calling run() out of context. What host should they be executed?

**Comment by antonmedv** [comment]
Deployer runs in two steps:
 First task definition and second execution.

**Comment by michaelhume** [comment]
thanks @antonmedv  - I clearly need a bit more practice with this.

I thought the context was determined when invoking the command, for example this would be used as:

` dep deploy development` 

which would provide the context.

**Comment by antonmedv** [comment]
Yes, what if development contains two hosts? Which one to use for run()?

**Comment by michaelhume** [comment]
Got it - thanks.

Do you have an example of how this might look?

```php
run('supervisorctl reload', ['host' => currentHost()])     // ???
```

There is a similar call just below that I looked to for inspiration that doesn't throw an error and also doesn't include host options:

```php
task('npm:run:prod', function () {
    cd('{{release_or_current_path}}');
    run('npm run prod');
});
```

I don't quite see and example in the docs for the [run command](https://deployer.org/docs/7.x/api#run) 

Much appreciated.

**Comment by antonmedv** [comment]
run() can be called only from task(). There is no way around it.
