### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by lucaslohne** [deployphp/deployer#2912]
- Deployer version: 7.0.0-rc4
- Deployment OS: MacOS
- PHP Version: 8.1.1

 I'm trying to use Deployer in my local ddev TYPO3 environment with PHP 8.1 and i get the following error with `dep init` and `dep --version` :

`ddev exec dep --version
PHP Fatal error:  Uncaught ErrorException: dirname(): Passing null to parameter #1 ($path) of type string is deprecated in /var/www/html/vendor/deployer/deployer/bin/dep:96
Stack trace:
#0 [internal function]: {closure}(8192, 'dirname(): Pass...', '/var/www/html/v...', 96)
#1 /var/www/html/vendor/deployer/deployer/bin/dep(96): dirname(NULL)
#2 /var/www/html/vendor/bin/dep(107): include('/var/www/html/v...')
#3 {main}
  thrown in /var/www/html/vendor/deployer/deployer/bin/dep on line 96
Failed to execute command dep --version: exit status 255`

When I switch to PHP 8.0 everything works fine.
If I create an empty deploy.php and deploy.yaml I can use it with PHP 8.1. This error seems related to the following change in PHP 8.1:

> Passing null to non-nullable internal function parameters is deprecated.

**Comment by trsteel88** [comment]
Keen to see php8.1 support added too.
