### ISSUE TITLE
deploy:shared not using sudo and failing for mkdir and touch commands

### ISSUE THREAD

**Issue by VivekShingala** [deployphp/deployer#2914]
- Deployer version: 6.8
- Deployment OS: Ubuntu (AWS)

Standard Magento2 recipe is used, but failing due to sudo is not used in deploy:shared task. I am getting below errors.

```
mkdir: cannot create directory ‘/home/PROD/www/shared/var/cache’: Permission denied
mkdir: cannot create directory ‘/home/PROD/www/shared/var/report’: Permission denied
touch: cannot touch '/home/PROD/www/shared/app/etc/env.php': Permission denied
```

I have also enabled writable_use_sudo, but it is not used in the shared.php file anywhere to add sudo for above commands.

`set('writable_use_sudo', true);`

How to fix this issue? I can run all of the above commands on the server by adding `sudo` in it.

**Comment by antonmedv** [comment]
Try to use v7.

**Comment by VivekShingala** [comment]
Hi @antonmedv 

Thanks for your response. However, v7 doesn't look like to be the stable version and I checked the shared.php file, and it doesn't have the use of `sudo` either.

https://github.com/deployphp/deployer/blob/v7.0.0-rc.4/recipe/deploy/shared.php

**Comment by antonmedv** [comment]
writable_use_sudo is only for deploy:writable. 

Looks like your server configuration forbids creating files for deployment user. I think permissions on your server should be fixed. WDYT?

**Comment by VivekShingala** [comment]
Hi @antonmedv 

You're right. It was the ownership issue which was causing the permission issues. Thanks for your swift response on this ticket. Much appreciated.
