### ISSUE TITLE
Migrate e2e tests to php8

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2923]
I think Deployer v7 will be the latest version that supports php7. And Deployer v8 will be only php8. 

Currently, e2e tests run on php7, we need to migrate tests to php8 eventually. 

@bsacharski do you think you can contribute more? ;)

One other thought is to also test the provision recipe. It even may be simpler as no apache will be needed as the provision recipe will install and configure everything himself.

**Comment by bsacharski** [comment]
I wanted to write "sure, will work on that" but I see that @luigel is already doing an amazing job with that :)

**Comment by antonmedv** [comment]
Done!
