### ISSUE TITLE
Why in composer.json: platform: php: 7.3.0?

### ISSUE THREAD

**Issue by benoitchantre** [deployphp/deployer#2927]
These lines fake the PHP version available from the environment.

https://github.com/deployphp/deployer/blob/e3e1dace98b2cde30bb515281fbd9be123f2775f/composer.json#L64-L66

When the environment doesn't meet the requirements, there will be an error at runtine.
Without these lines, the error would be detected during `composer install`.

Are there any reasons to fake the environment?

**Comment by antonmedv** [comment]
¯\_(ツ)_/¯

**Comment by benoitchantre** [comment]
The platform config has been introduced with https://github.com/deployphp/deployer/commit/a22faa6806e9c82c3b70b18294e70cf1b1f92b89, then it has been updated when there was a bump of PHP requirement.

The commit message doesn’t help to understand why it has been introduced. I suspect there was a misunderstanding of that parameter.

I suggest to remove it and see what happens with automated tests.
