### ISSUE TITLE
Magento 2: Allow forcing maintenance mode

### ISSUE THREAD

**Issue by lfolco** [deployphp/deployer#2936]
We are on a hosting provider that does not support zero-downtime deployments, so we need to set maintenance mode on Magento 2 explicitly. Currently the Magento 2 recipe will dynamically check if maintenance mode is needed and set/unset accordingly. The issue is, if we set maintenance mode at the beginning of our deployment, it will get unset during these tasks.

Any chance to have a config to enable this behavior?

**Comment by antonmedv** [comment]
Why not override whole deploy task?

**Comment by lfolco** [comment]
I'm trying to avoid overriding, especially considering #2878. I'm not sure what I'll be breaking with an override.
