### ISSUE TITLE
The upload function does not work

### ISSUE THREAD

**Issue by Max-Might** [deployphp/deployer#294]
Hello.

I have downloaded the latest release from the website and I am trying to upload files to the server.
The procedure goes like normal, there are no errors on the screen but there are no files on the server either.
This recipe worked with the 2.x version of deployer. Maybe there have been some changes to PhpSecLib?

**Comment by elfet** [comment]
Can you run your command with `-vvv` options and show output?

**Comment by Max-Might** [comment]
This is the output from the upload-files task (I overrided it, it is not from the common recipe).

```
➤ E➤ecuting task deploy:upload-files
⤷ on [staging]
Run: ls /var/www/staging/releases
> 20150514153014
> 20150515104849
> 20150515110247
> 20150515165453
> 20150520101732
> 20150521102533
> 20150521123431
> 20150522101007
> 20150522110908
> 20150522174607
> 20150525145924
> 
Upload file composer.json to release/composer.json
Upload file composer.lock to release/composer.lock
Upload from public to release/public
```

**Comment by vanquang9387** [comment]
@elfet : I had problem with upload function, too,
Mentioned here: https://github.com/deployphp/deployer/commit/4f16be0a982840e351a4a8621504c85e6f08b784

**Comment by Max-Might** [comment]
Just tested with the reverted commit. It still does not upload anything to the server.

**Comment by elfet** [comment]
I do not know what is it. Can you find out why this is happening?

**Comment by elfet** [comment]
It's work for me: 
```php
upload(__DIR__ . '/README.md', '/home/user/project/README.md');
```
How are you uploading?

**Comment by Max-Might** [comment]
This is how I am uploading:

```
upload('composer.json', 'release/composer.json');
```

After I changed it to this it worked:
```
upload('composer.json', '/var/www/JiraRepl.Staging/release/composer.json');
```

In 2.x the second parameter used to be relative to the {{deploy_path}} of the server.
Now we have to specify the full path?

PS: it does not seem to be related to the strreplace windows fix you reverted.

**Comment by elfet** [comment]
Yes, now `cd` function has no effect on upload and download function. This is consciously to simplicity. If you want, you can create PR this `cd(deploy_path)` feature.

**Comment by Max-Might** [comment]
So here is what I came up with:

```
$path = env('deploy_path');
upload('composer.json', $path . '/release/composer.json');
```

I use `env('deploy_path')` so it uses the deploy path of the server we are connected to.
This is so because we can use the same task on different servers with different deploy paths.

**Comment by elfet** [comment]
Yes, you solution is correct.
