### ISSUE TITLE
Caddy can't load right configs after restarting a server

### ISSUE THREAD

**Issue by asamats** [deployphp/deployer#2948]
- Deployer version: v7.0.0-rc.4
- Deployment OS: Ubuntu 20.04

Related issue  #2876

By default Caddy loads config from `/etc/caddy/Caddyfile` but on deploying,  Deployer run the command `caddy reload` in the directory, where a config has putted, and all are working before reloading server. The same issue when we have one more site/deployment.

I suggest to put all configs in one directory `sites-enabled` and add to the main config(`/etc/caddy/Caddyfile`) this `sites-enabled/*`

*https://caddyserver.com/docs/caddyfile/directives/import

**Comment by gerardojbaez** [comment]
I'm not able to deploy more than one site and I believe this is the issue. I already have one site running and working properly. Provisioning and deploying a second site causes the first site to go offline; running `caddy reload` in the first's site directory brings it back online.

**Comment by antonmedv** [comment]
Fixed.
