### ISSUE TITLE
Could not open input phar when using parallel 

### ISSUE THREAD

**Issue by piotrekkr** [deployphp/deployer#295]
Hi,

today I tried to run Deployer in parallel mode but It just hung forever. After some debug I found that workers could not be created. Deployer starts workers with command:

    $ php phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep worker --master='127.0.0.1:3333' --server='dev.1' dev --tag -vvv 

And I get error when issuing same command in console:

    $ php phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep worker --master='127.0.0.1:3333' --server='dev.1' dev --tag -vvv
    Could not open input file: phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep

I tried:

    $ php phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep
    Could not open input file: phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep

    $ cd /home/piotrek/Vhosts/deployer/
    $ php phar://deployer.phar worker --master='127.0.0.1:3333' --server='dev.1' dev --tag -vvv
    Could not open input file: phar://deployer.phar

And this works:

     $ php -r "echo file_get_contents('phar:///home/piotrek/Vhosts/deployer/deployer.phar/bin/dep') , PHP_EOL;"
    .......

This one also works

    $ cd /home/piotrek/Vhosts/deployer/
    $ php deployer.phar worker --master='127.0.0.1:3333' --server='dev.1' dev --tag -vvv

What can be wrong? Could you change code a little so it won't use phar:// wrapper or some option to change it?

My PHP version:

        PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
        with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

PHP config:

    $ php -i | grep phar
    Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
    Phar-based phar archives => enabled
    Tar-based phar archives => enabled
    ZIP-based phar archives => enabled
    phar.cache_list => no value => no value
    phar.readonly => On => On
    phar.require_hash => On => On

My OS: Linux Mint 17

Thank you for help

**Comment by elfet** [comment]
Try chmod and chown phar file. Look like file has wrong permissions.

**Comment by piotrekkr** [comment]
I think permissions are correct:

    $ ls -la deployer.phar 
    -rwxr-xr-x 1 piotrek piotrek 2,5M maj 25 04:50 deployer.phar
    $ id
    uid=1000(piotrek) gid=1000(piotrek) groups=1000(piotrek),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lpadmin),110(sambashare)

**Comment by elfet** [comment]
Hmm, try to find how to fix it.

**Comment by elfet** [comment]
Fixed in v3.0.4.
