### ISSUE TITLE
NPM install fails on DigitalOcean server

### ISSUE THREAD

**Issue by revmitcz** [deployphp/deployer#2957]
- Deployer version: 6.8.0
- Deployment OS: MacOS (locally) / Ubuntu 20.04 (remotely)

I followed this guide : https://lorisleiva.com/deploy-your-laravel-app-from-scratch/install-and-configure-deployer

This was my original deploy.php (edited for anonymity)

```<?php
namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/php-fpm.php';
require 'contrib/npm.php';

// Project name
set('application', 'fakeproject');

// Project repository
set('repository', 'https://github.com/revmitcz/fakeproject.git');
set('php_fpm_version', '8.0');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);

// Shared files/dirs between deploys
add('shared_files', []);
add('shared_dirs', []);

// Writable dirs by web server
add('writable_dirs', []);
set('allow_anonymous_stats', false);

// Hosts

host('prod')
    ->set('remote_user', 'root')
    ->set('hostname', 'fakeproject.app')
    ->set('deploy_path', '/var/www/{{hostname}}');

// Tasks

task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'artisan:view:cache',
    'artisan:config:cache',
    'artisan:migrate',
    'npm:install',
    'npm:run:prod',
    'deploy:publish',
    'php-fpm:reload',
]);

task('npm:run:prod', function () {
    cd('{{release_path}}');
    run('npm run prod');
});

after('deploy:failed', 'deploy:unlock');
```

When I got to the dep deploy step, I had a number of issues - most of them I've worked out on my own, but now I'm absolutely stuck at this error message : 

```npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.```

I changed their deploy tasks, removing both `npm:install` and `npm:run:prod` and adding your recommended one of the line `after('deploy:update_code', 'npm:install');` while also removing the added npm:run task they added.

No matter what I do, I still run into that NPM error. What is the correct solution to this issue?

**Comment by revmitcz** [comment]
Update : Looks like forcing composer to use deployer ^7.0 fixed the issue.

For anyone also following the guide linked above, here's how the PHP deploy file should end (provided you're using deploy 7+), which will also avoid warnings about avoiding reloading php-fpm :

```
task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'artisan:view:cache',
    'artisan:config:cache',
    'artisan:migrate',
    'deploy:publish',
]);

after('deploy:update_code', 'npm:install');
after('deploy:failed', 'deploy:unlock');
```

**Comment by Kaos-Industries** [comment]
> I changed their deploy tasks, removing both `npm:install` and `npm:run:prod` and adding your recommended one of the line `after('deploy:update_code', 'npm:install');` while also removing the added npm:run task they added.

I'm currently following the same guide and have been weighing up whether to compile on the server or before pushing. Can I ask what made you decide to remove these and add the specified line?

**Comment by revmitcz** [comment]
> I'm currently following the same guide and have been weighing up whether to compile on the server or before pushing. Can I ask what made you decide to remove these and add the specified line?

Unfortunately, the simple answer is probably very unhelpful : I ran into issues, saw "_oh also change this_" and changed it.

I'm quite a newb in the world of even utilizing npm in the first place, so I don't have a great answer for what's the better solution. The site I was launching with this guide is like pre-alpha, just so I can show it properly to other team members without needing a separate service, and to test deployments to see if it'll hold up once the code is further along.

That said, so far, no issues. What I see locally on my system matches and functions exactly what I see on the live DO server after any deployment.
