### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by mcones** [deployphp/deployer#2958]
With laravel 9 update, nunomaduro/collision v6 is now a dependency, this projects needs symfony/console v5 but collision requires  console v6.

**Comment by luigel** [comment]
@mcones I already have PR for this one https://github.com/deployphp/deployer/pull/2924. This can support Laravel 9 when this is merged.

**Comment by luigel** [comment]
I'm just waiting @antonmedv to merge my PR to a new branch and tag a major version as stated here https://github.com/deployphp/deployer/issues/2923

**Comment by luigel** [comment]
@mcones For the mean time you can use this until the PR is merged.


```json
"repositories": [
        {
            "url": "https://github.com/luigel/deployer",
            "type": "vcs"
        }
],
"require": {
     "deployer/deployer": "dev-update-to-php-8"
}
```

**Comment by hailwood** [comment]
Similar issue with laravel/framework v9 requiring symfony/process v6 but deployer requires v5.
This is quickly going to become a major issue if we don't get this merged in soon.

**Comment by antonmedv** [comment]
Please use dist version.

**Comment by hailwood** [comment]
@antonmedv dist version from where?

**Comment by antonmedv** [comment]
https://packagist.org/packages/deployer/dist

**Comment by hailwood** [comment]
Huh, didn't know about that.

Thanks @antonmedv 🙂

**Comment by langeuh** [comment]
> https://packagist.org/packages/deployer/dist

The dist version doesn't support extra classes like `Dotenv\Dotenv` which is used by a lot of people (including me) to populate/sync .env files during deployment...

**Comment by Schrank** [comment]
Dotenv is already part of deployer did you try it and get an error "class not found?" 🤔

**Comment by antonmedv** [comment]
Actually I’m thinking on adding dotenv in v8
