### ISSUE TITLE
The command "deploy" is not defined.

### ISSUE THREAD

**Issue by ZhukV** [deployphp/deployer#296]
I install the Deployer to `/usr/local/bin/dep`, and create a deploy.php in root directory with content:

```php
server('production', 'foo-bar.com', 22)
    ->user('foobar')
    ->forwardAgent()
    ->stage('production')
    ->env('deploy_path', '/var/www/foo-bar.com');

set('repository', 'git@bitbucket.org:foo/bar.git');
```

But, if i run `dep deploy production` i see a error:

```
  [InvalidArgumentException]        
  Command "deploy" is not defined.
```

Why? Thank.

**Comment by elfet** [comment]
Require recipe at beginning of file:
```php
require 'recipe/common.php';
```

**Comment by ZhukV** [comment]
Thank. All ok.

**Comment by iamrutvik** [comment]
But I have added recipe file.
Here it is : 
`


require 'vendor/deployer/deployer/recipe/laravel.php';



server('prod', '192.168.91.128', 22)
    ->user('ubuntu')
	->password('e2m@123')
    ->stage('production')
    ->env('deploy_path', '/var/www/html'); // Define the base path to deploy your project to.

set('svnrepo', 'https://192.168.1.148/svn/dev-autodeployment/trunk/autodeploy');
set('svnuser', 'rutvikb');
set('svnpass', 'rutv@123');

task('deploy:update_code', function () {
    $svn = 'C:/Program Files/TortoiseSVN/bin';
    $repository = trim(get('svnrepo'));
    $user = trim(get('svnuser'));
    $pass = trim(get('svnpass'));
    run("$svn export --force --username $user --password $pass $repository {{release_path}} 2>&1");
})->desc('Updating code');`
