### ISSUE TITLE
Config option "port" does not exist.

### ISSUE THREAD

**Issue by fritzmg** [deployphp/deployer#2968]
- Deployer version: v7.0.0-rc.4
- Deployment OS: Windows 10 x64

In a task I want to retrieve the port of the configured host - if defined at all:

```php
currentHost()->getPort()
```

However, this yields

```
Config option "port" does not exist.
```

under Deployer 7.x, if `setPort` was not specifically defined for a particular host.

The return type of `Host::getPort` currently says `?int`:

https://github.com/deployphp/deployer/blob/86742c1f7584d8726074fe37e1f16ca74ce79e00/src/Host/Host.php#L128-L131

However, the code in `Host::getPort` only uses `$this->config->get('port')` instead of `$this->config->get('port', null)`. Thus this will never return `null` if no port was defined - at least with the current implementation of `Configuration::get`:

https://github.com/deployphp/deployer/blob/86742c1f7584d8726074fe37e1f16ca74ce79e00/src/Configuration/Configuration.php#L99-L101

A default value will only be returned, if it was specifically passed to the function.

This currently makes `Host::getPort` unusable for default port `22` (unless you manually specify it of course). I am not sure what the intention is though: should we now use

```php
currentHost()->config()->get('port', null)
```

instead of

```php
currentHost()->getPort()
```

? Or is it now best practise to always set the port of the host, even if it's the default `22`?

**Comment by antonmedv** [comment]
Tried to merge PR with fix, but it broke all tests.

**Comment by fritzmg** [comment]
In order to fix, I think every `get…` method in `Deployer\Host\Host` that allows `null` as a return type and returns the value from the config needs to add `null` as the second parameter for `$this->config->get(…)`.
