### ISSUE TITLE
Missing YAML docs

### ISSUE THREAD

**Issue by gglnx** [deployphp/deployer#2971]
- Deployer version: 7.0-rc4
- Deployment OS: Mac OS

I'm using an `deploy.yaml` with `runLocally` to prebuild my assets:

```yaml
tasks:
  deploy:assets:
    - runLocally: 'yarn install && yarn build'
    - upload:
        src: web/assets/
        dest: '{{release_path}}/web/assets'
```

This is the verbose output:

```
task deploy:assets
[hostname] /opt/homebrew/Cellar/php@7.4/7.4.27/bin/php /vendor/deployer/deployer/bin/dep worker --port 50806 --task deploy:assets --host hostname --decorated -vvv
[hostname] rsync '-azP' '-e' 'ssh '\''-A'\'' '\''-o'\'' '\''ControlMaster=auto'\'' '\''-o'\'' '\''ControlPersist=60'\'' '\''-o'\'' '\''ControlPath=/Users/dennis/.ssh/deploy@hostname'\''' 'web/assets/' 'deploy@hostname:/web/craft-cms/releases/19/web/assets'
[hostname] sending incremental file list
[hostname] rsync: [sender] change_dir "/web/assets" failed: No such file or directory (2)
[hostname] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1350) [sender=3.2.3]
[hostname]  error  in Importer.php on line 181:
[hostname] exit code 23 (Unknown error)
```

The uploads fails because `web/assets` wasn't generated by the `runLocally` build.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2971">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2971/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2971/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Found the issue:
```diff
-    - runLocally: 'yarn install && yarn build'
+    - run_locally: 'yarn install && yarn build'
```

**Comment by antonmedv** [comment]
Add docs to prevent misuse of YAML (runLocally instead of run_locally).
