### ISSUE TITLE
Deploying current (local) branch doesn't work

### ISSUE THREAD

**Issue by cmcfadden** [deployphp/deployer#2980]
- Deployer version:  7.0.0-rc4
- Deployment OS: MacOS

When not specifying a branch, the deploy:info stage reports the current local branch by calling `git rev-parse --abbrev-ref $target`, but that just get assigned to a local variable (https://github.com/deployphp/deployer/blob/master/recipe/deploy/info.php#L8). When the update_code task runs, it doesn't actually look at the local git repo at all. It seems like the intended behavior might be that the info task actually calls `set` to set the target if it's not specified?

**Comment by antonmedv** [comment]
It's a bug)

**Comment by antonmedv** [comment]
Probably fixed by https://github.com/deployphp/deployer/commit/4ec52d645e706200f008b6c8e31486a03c3bd61c

**Comment by kidk** [comment]
Thanks for the fix. Is it possible to push out a new RC?

**Comment by antonmedv** [comment]
Will do it on the week.  Not at home right now.

**Comment by antonmedv** [comment]
Should be fixed now. Both update_code and info tasks now using target. 

If issue popups again, please open a new issue.
