### ISSUE TITLE
Merge deployer/deployer and deployer/dist

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2997]
I saw lots of bug requests to update composer.json deps. Solution usually is to use dist version. 

What if we going to merge dist into main repo?  Master branch will have the code and tags will have packed phar. 

What do you think? @Seldaek, is it ok? Thanks.

**Comment by Seldaek** [comment]
Not sure.. I guess it's probably fine but I can't guarantee :)

**Comment by antonmedv** [comment]
@Schrank what do you think?

**Comment by Schrank** [comment]
I like the idea a lot <3 Need help?

**Comment by antonmedv** [comment]
I’ll do it myself, thanks)

**Comment by antonmedv** [comment]
Done in #3051

**Comment by gharlan** [comment]
When using this new version, how can I get autocompletion in phpstorm for the deployer functions in my `deployer.php`?
I've preferred the previous non-dist version, which I've installed in a separate dir in my project (with separate composer.json).

**Comment by antonmedv** [comment]
Lots of people complained about version incompatibility. So I decided to merge dist into the main repo. You can try to add vendor/bin/dep as include path deps.

**Comment by gharlan** [comment]
It seems not to work because of the missing `.phar` extension. With this extension, phpstorm would analyze the content.

**Comment by antonmedv** [comment]
Hmm, I guess I'm going to rename it back from dep to deployer.phar.

**Comment by gharlan** [comment]
Or maybe add a `dep` symlink to the phar file and use this symlink for the composer bin script. (Don't know if it works)

**Comment by antonmedv** [comment]
The symlink can cause different bugs on its own. Can't tell how it will be working on git/windows.
