### ISSUE TITLE
deploy:release failed when there are too many releases_log

### ISSUE THREAD

**Issue by nashiracn** [deployphp/deployer#3008]
- Deployer version:  v7.0.0-rc.4
- Deployment OS: debian 11.1

`deploy:release` failed when there are too many releases_log.

 When there are too many releases_log, `React\Http\HttpServer` will ues `React\Http\Io\HttpBodyStream` instead of `React\Http\Io\BufferedBody`,  so `$request->getBody()->getContents()` within `src/Executor/Server.php` returns empty.

**Comment by antonmedv** [comment]
Fixed in 019eec13984982888046ce8016be958417196131
