### ISSUE TITLE
Error: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by guilhermegonzaga** [deployphp/deployer#301]
My task in deploy.php:
~~~ php
require 'recipe/common.php';

// server(...);

task('deploy:start', function(){

	\Deployer\Task\Context::get()->getServer()->connect();

	run("cd {{deploy_path}}");

})->desc('Testing...');
~~~

Error in the console by calling: dep deploy:start -vvv production
~~~
➤ E➤ecuting task deploy:start
⤷ on [prod]

Run: cd /var/www/html/xxxxxxxxx.com.br/web && cd /var/www/html/xxxxxxxxx.com.br/web
> reset: standard error: Inappropriate ioctl for device
> 
> 
⤶ done on [prod]
✔ Ok
~~~

Including deploys applications laravel, etc.
All commands `run();` return the same error.

**Comment by elfet** [comment]
Try to remove this line:
```php
 \Deployer\Task\Context::get()->getServer()->connect();
```

**Comment by guilhermegonzaga** [comment]
I had tried this, but the error insists on continuing.
I believe they are the permissions of my server , not a problem deployer.
Anyway thanks for your help, will continue trying to solve.

**Comment by elfet** [comment]
Feel free to ask any questions.
