### ISSUE TITLE
Restarting php5-fpm

### ISSUE THREAD

**Issue by nWidart** [deployphp/deployer#302]
Hello,

I saw from the examples page a task to restart php5-fpm:

``` php
task('reload:php-fpm', function () {
    run('sudo /usr/sbin/service php5-fpm reload');
});

after('deploy', 'reload:php-fpm');
after('rollback', 'reload:php-fpm');
```

I need to use this to refresh the php5 paths to the new current symlinked folder.

The problem I have though, is that running sudo requires entering the password, which when running from the deploy script can't happen, I'm getting this:

```
sudo: no tty present and no askpass program specified 
```

I did add my user to the sudoers file like so:

```
myUser    ALL=(ALL:ALL) NOPASSWD: ALL
```

Though this still gives the same error.

Is there some sort of trick to make this work ?

Thank you!

**Comment by ZhukV** [comment]
This is a problem in rights for access sudo.
Please check you /etc/sudoers file!

As example (my sudoers):
```
taleforchild ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
```

Where:
**taleforchild** - user in operation system
Working in CentOS 7.0

**Comment by nWidart** [comment]
Yes, it's something related to sudo rights, though I don't get what, hence my post here.

Using `myUser    ALL=(ALL:ALL) NOPASSWD: ALL` should have done the trick... 

I tried `forge ALL=NOPASSWD:/usr/sbin/service php5-fpm reload` , but in CLI this returns: 

``` bash
service php5-fpm reload
reload: Rejected send message, 1 matched rules; type="method_call", sender=":1.305" (uid=1000 pid=8681 comm="reload php5-fpm ") interface="com.ubuntu.Upstart0_6.Instance" member="Reload" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
```

**Comment by ZhukV** [comment]
If you use Ubuntu OS:

Command for restart PHP-FMP service:
```sh
/etc/init.d/php-fpm restart
```

And, you should add rights for run this command without sudo password in you system.

Deployer task:
```php
task('reload:php-fpm', function () {
    run('sudo /etc/init.d/php-fpm restart'); // Using SysV Init scripts
});
```

And you sudoers rule:
```
you_user_name ALL=NOPASSWD: /etc/init.d/php-fpm restart
```

If you use another operation system, please write os and version.

P.S. The wrapper scripts (as example `service`) redirecting call to other executable files, then you must write a real command in `/etc/sudoers`

**Comment by nWidart** [comment]
Hm I can reload php5-fpm using either of those:

```
service php5-fpm reload
# or
/etc/init.d/php5-fpm reload
# or 
/usr/sbin/service php5-fpm reload
```

I tried it with your setup, logged out of the VPS to be sure, then ran `sudo /etc/init.d/php-fpm restart`, still getting asked for password. :disappointed:

**Comment by ZhukV** [comment]
So, the real script for reload php-fpm `/etc/init.d/php-fpm`.
For run this script, you should have a superadmin rights (sudo).
If asked password (if you called from another user), then the rule of sudoers not working.

Please try (user for available restart without password - `new_user`, as example):

1. Login to system as root. (create a user, if not exists. Please check in `/etc/passwd`)
2. Change `/etc/sudoers`. Adds:
```
new_user ALL=NOPASSWD: /etc/init.d/php-fpm restart
```
3. Login to system as `new_user` (NOT `su`, can open new console).
4. Try run:
```sh
sudo /etc/init.d/php-fpm restart
```

Should work.

**Comment by nWidart** [comment]
That's what I did, it doesn't work.
Also the script to reload php-fpm is not `/etc/init.d/php-fpm` but `/etc/init.d/php5-fpm`.

**Comment by ZhukV** [comment]
Ok, replace `/etc/init.d/php-fpm` to `/etc/init.d/php5-fpm` in sudoers

**Comment by nWidart** [comment]
I did, of course, but that still makes me ask for sudo password when running the command.

**Comment by ZhukV** [comment]
hm... interesting... in another system (debian, centos) this is a good work. 
Can file `/etc/sudoers` not reading...

**Comment by nWidart** [comment]
When I `cat /etc/sudoers` I do see my changes in it, so it was written correctly.

**Comment by oanhnn** [comment]
Please try:
```
you_user_name ALL=NOPASSWD: /etc/init.d/php5-fpm
                           ^
                           | no space
```

**Comment by nWidart** [comment]
Tried without a space:

```
forge ALL=NOPASSWD:/etc/init.d/php5-fpm restart
```

And running `sudo /etc/init.d/php5-fpm restart` as the `forge` user, still asks me for a password.
Running `/etc/init.d/php5-fpm restart` without sudo, doesn't though. But when I commented the line in the sudoers file, it still doesn't ask root password for it.. so I don't know...

**Comment by oanhnn** [comment]
Please try run deploy with `-vvv` option and show out to here. @nWidart

**Comment by nWidart** [comment]
This is the error with stacktrace, when running `-vvv`:

```
Run: /etc/init.d/php5-fpm restart


                      
  [RuntimeException]  
                      


Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:289
 run() at /Users/nicolaswidart/Sites/Asguard/presentation-site/deploy.php:29
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:66
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:116
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:91
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:62
 require() at /usr/local/bin/dep:4

```

**Comment by gordalina** [comment]
@nWidart restarting php-fpm can close connections and/or connection attempts (tcp syn).
You can use [cachetool](https://github.com/gordalina/cachetool) to clear opcode cache (apc or opcache). Also, there's a deployer recipe for it [deployphp/recipes](https://github.com/deployphp/recipes/blob/master/docs/cachetool.md)

**Comment by nWidart** [comment]
Oh ok, thanks.

I've installed deployer and this recipes repository with composer , globally, do I include the file like so, or ?:

``` php
require 'recipes/recipes/cachetool.php';
```

Or is it recommended to install on a per project basis ?

**Comment by gordalina** [comment]
You only need to require the recipes in composer, usually you won't need
deployer as a dependency because you use it as an app.
And yes, it should be per project.
Hope it solves your problem.

**Comment by elfet** [comment]
@nWidart so it's turn out?
Here is my `sudoers` on debian:
```
elfet   ALL=(ALL) NOPASSWD: /usr/sbin/service php5-fpm reload
```

**Comment by nWidart** [comment]
Still not working, no.

I tried the cache tool, but that throws: ` Object `cachetool` does not exist in Collection.`

I required the package in the project and required: `vendor/deployphp/recipes/recipes/cachetool.php`.

**Comment by Lynnworld** [comment]
My sudoer configure is
```
lynn ALL=(ALL) NOPASSWD:/usr/bin/service php5-fpm restart
```
using `service php5-fpm restart` works for me.

**Comment by Roquie** [comment]
If u getting error "sorry, you must have a tty to run sudo", just comment this line `Defaults    requiretty` in sudoers file. Work for me.

**Comment by geekdevs** [comment]
Also note that order is important in sudoers config!

```
When multiple entries match for a user, they are applied in order. Where there are multiple matches, the last match is used (which is not necessarily the most specific match).
```

http://askubuntu.com/a/100112/286499
