### ISSUE TITLE
phpseclib version could not be resolved

### ISSUE THREAD

**Issue by marcosh** [deployphp/deployer#303]
I tried to install deployer with `php composer.phar require deployer/deployer:~3.0` but I get the following error

    Your requirements could not be resolved to an installable set of packages.

      Problem
     - deployer/deployer v3.0.4 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.3 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.2 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.1 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - deployer/deployer v3.0.0 requires phpseclib/phpseclib dev-master#2c96af214bf1b5e29b707249108504b4e0041a21 -> no matching package found.
    - Installation request for deployer/deployer ~3.0 -> satisfiable by deployer/deployer[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4].

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

I tried to search for the given commit the phpseclib repository but I was not able to find it

**Comment by oanhnn** [comment]
Please see #259
