### ISSUE TITLE
7.0.0-rc.4: allow DEPLOYER_ROOT override from recipe

### ISSUE THREAD

**Issue by lkraav** [deployphp/deployer#3048]
**PROBLEM**

https://github.com/deployphp/deployer/issues/2628 left things somewhat incomplete.

Given `deploy.php` that is

* shared across multiple modules
* located outside module releases dirs, and symlinks would unnecessarily pollute module trees

...I now have to patch every module `composer.json` deployment script key with `DEPLOYER_ROOT=.`

Setting this env variable globally at shell level is hidden, and doesn't transfer well if other team members would like replicate.

**SOLUTION**

In recipe, we could allow

* configuring `task()` with `cwd` option, like `runLocally()`
* some `set()` configuration key, maybe also named `cwd`

Your thoughts?

**Comment by antonmedv** [comment]
What about adding to your recipe this?
```php
putenv('DEPLOYER_ROOT', 'correct path');
```
Will it help?

**Comment by lkraav** [comment]
> Will it help?

Code doing `$process->setWorkingDirectory()` pulls it from `defined()` constant, which cannot be overriden in recipe.

https://github.com/deployphp/deployer/blob/7360569cbfa982ecf3aadcbff54a0002be075f6d/src/Component/ProcessRunner/ProcessRunner.php#L46

Recipe is included after constant initialization is already done:

https://github.com/deployphp/deployer/blob/2003ca9b89e9096f49496739764f6f54d1cc78c8/bin/dep#L96

I'm not convinced `DEPLOYER_ROOT` really needs to be a constant. Might make more sense as some process object property after all.

**Comment by antonmedv** [comment]
Agree, let's refactor this part. Let's use only env vars?

**Comment by lkraav** [comment]
> Agree, let's refactor this part. Let's use only env vars?

I think `getenv('DEPLOYER_ROOT') !== false ? getenv('DEPLOYER_ROOT') : dirname($deployFile)` is OK to seed the initial value, it just needs to be somehow overrideable in recipee.

**Comment by antonmedv** [comment]
Done, no there is no DEPLOYER_ROOT const. Only env var DEPLOYER_ROOT.

**Comment by lkraav** [comment]
Thank you, `putenv( 'DEPLOYER_ROOT=.' )` inside `deploy.php` seems to work as expected now.
