### ISSUE TITLE
Latest release not updated in packagist.

### ISSUE THREAD

**Issue by BorisovskiP** [deployphp/deployer#3055]
While trying to update `deployer/dist` to `v7.0.0-rc.6` we saw that the package was not update at  https://packagist.org/packages/deployer/dist. It is still on version`v7.0.0-rc.4`

@antonmedv do you mind having a look?

**Comment by antonmedv** [comment]
deployer/dist now merged with deployer/deployer. Please change.

**Comment by BorisovskiP** [comment]
@antonmedv thanks for clearing that up.
