### ISSUE TITLE
Required PHP version missing in v7.0.0-rc7

### ISSUE THREAD

**Issue by benoitchantre** [deployphp/deployer#3057]
I think that the required version of PHP should be kept in `composer.json`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3057">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3057/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3057/pledge.svg">
</picture>
</a>

**Comment by benoitchantre** [comment]
And requirement for `ext-json`.

**Comment by antonmedv** [comment]
This should be fixed in release.yaml workflow. Probably we can switch from bash to google/zx (also my project) there.

**Comment by benoitchantre** [comment]
While doing this PR, I wondered if the config properties are really required.
