### ISSUE TITLE
Possiblitity to rollback to failed release

### ISSUE THREAD

**Issue by kenjis** [deployphp/deployer#306]
I added phpunit testing before release.
And if testing fails, I get `[RuntimeException]` and deployer stops, so it won't be released.

But there is still a failed release folder in `releases`. So if I deploy new release and rollback, the failed release folder will be released. To avoid it, we have to remove failed release folder manually.

Is there any good solutions?

**Comment by elfet** [comment]
Run test before `deploy` task. Specifically `deploy:release` task.

**Comment by kenjis** [comment]
Before `deploy:release`, there is no source code.

We have to clone git repository twice, for testing and for releasing.
It is not big problem, but only once is better.

**Comment by elfet** [comment]
If test fails you can run `cleanup` task.

**Comment by kenjis** [comment]
`cleanup` removes older releases. In this case, failed release is latest.

**Comment by elfet** [comment]
You can catch Exception and remove release dir, and everything you want.

**Comment by kenjis** [comment]
Thank you!

This works fine.

~~~php
task('phpunit', function () {
    try {
        run("cd {{release_path}} && sh phpunit.sh");
    } catch (\RuntimeException $e) {
        // test fails
        run("cd {{deploy_path}} && if [ ! -d releases-failed ]; then mkdir releases-failed; fi");
        run("mv {{release_path}} {{deploy_path}}/releases-failed");
        run("cd {{deploy_path}} && if [ -h release ]; then rm release; fi");

        throw $e;
    }
})->desc('Run PHPUnit');
~~~
