### ISSUE TITLE
Control socket path inconsistent in CI

### ISSUE THREAD

**Issue by biomedia-thomas** [deployphp/deployer#3064]
- Deployer version: 7.0.0-rc.7
- Deployment OS: alpine -> almalinux

I have issues with multiplexing when the CI environment value is set. The SSH client switches to `/dev/shm/%C` for the control path. %C is a hash of the local and remote hostnames and usernames. However when `ssh -O check` is used to check if the master is running, no remote user and hostname is passed to the command, causing the hash and thus shm path do differ from the other commands:
```
     [staging] ssh: is master running?
-->  [staging] ssh -O check -p 2250 -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/dev/shm/%C echo
     [staging] Control socket connect(/dev/shm/b325e102bd7f3f9f565a10ee6fe69c67c348abc0): No such file or directory
     [staging] ssh: multiplexing initialization
     [staging] ssh -N -p 2250 -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/dev/shm/%C thomas@localhost
     [staging] ssh '-p' '2250' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' 'thomas@localhost' ': 0b564c7412ebc17a4db1; bash -ls'
```

Because of this the check will always fail if for example the local and remote username differ, and each time the initialization command will run again (the above logs are repeated for every task).

From what I can see `Deployer\Component\Ssh\Client::isMasterRunning` should add a `remote-user@remote-host` before the echo command, so the correct path is checked. For example:
```
ssh -O check -p 2250 -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/dev/shm/%C echo
-> /dev/shm/b325e102bd7f3f9f565a10ee6fe69c67c348abc0
ssh -O check -p 2250 -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=/dev/shm/%C thomas@localhost echo
-> /dev/shm/792dda152196860f8c199eac02fa05b229d4ef07
```
Possibly related: #2536

**Comment by antonmedv** [comment]
One possibility is to switch from %С то own path.
