### ISSUE TITLE
More sophisticated error message when git clone on remote doesn't work

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#307]
Based on https://github.com/deployphp/deployer/issues/305#issuecomment-106450979

When the remote server is not set up properly to be able to clone the repo, there could be a smarter error message.

So instead of just dumping
`Host key verification failed.`

It could say something like
```
Host key verification failed. It seems you forgot to add the repository's host's
fingerprint as a 'known host'. Run `ssh -T git@bitbucket.org` on the remote
server to add it to the list of known hosts, then try deploying again.
```

This could avoid the creation of new issues in this repo, when the developer using Deployer doesn't realise that it's not the tool that's wrong, but rather the remote server configuration.

**Does anyone know whether this could be implemented?**

Of course this could lead us to even more error-checking regarding the remote ssh key which could have different error messages:
- Is an ssh key in use?
- If it is, then is the git repo's host added to the known hosts?
- If it still errors for some reason, output the default `Host key verification failed.` error message.

This could help developers instantly locate the problem.

@elfet I propose a new issue label called "DX" which would focus on Developer Experience, and this issue could be labeled as such.

For usage of the DX label, see: [Symfony DX](https://github.com/symfony/symfony/labels/DX)

**Comment by elfet** [comment]
Done.

**Comment by ZeeCoder** [comment]
:+1:
