### ISSUE TITLE
Disabling the run timeout with `null` doesn't work anymore

### ISSUE THREAD

**Issue by soyuka** [deployphp/deployer#3074]
```
run('sleep 400', timeout: null);
```

Will timeout after 300 sec by default.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3074">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3074/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3074/pledge.svg">
</picture>
</a>

**Comment by ToshY** [comment]
@antonmedv This is still relevant. I'm unsure if this counts as `idle_timeout`, but I had the same problem with long running commands (without output), and applied both `timeout: null, idle_timeout: null`, which still timed-out the specified `run` after 300 seconds (default_timeout not specified).
