### ISSUE TITLE
Recipes page on deployer.org

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#309]
Looking for contributor who can implement *deployer.org/recipes* page.
This page must have next features:
* Search recipes.
* Docs for recipes.
* Publish recipes.
* Autoupdate docs in recipe updatet. 
* Be simple as possible. 

> Reward will be PhpStorm Deployer license.

**Comment by ZeeCoder** [comment]
What do you mean by "publish recipes"?
Also: I assume this page would list the built-in and the 3rd party recipes too, right?

**Comment by elfet** [comment]
To anybody can add there recipes to lib.
Yes, 3rd party recipes too.

**Comment by ZeeCoder** [comment]
So for example: I could create a new repo dedicated to a Deployer recipe, then I would submit the repo link on the site?
If so, there should be a way to moderate submitted repo links, so that the site can't be flooded with trash.

The internet can be mean. :)
