### ISSUE TITLE
Proper way to use AWS .pem file?

### ISSUE THREAD

**Issue by jimbojsb** [deployphp/deployer#31]
Hi, I'm trying to test a deployment with ssh + git, but I cannot figure out the proper way to use my .pem private key that lets me SSH into AWS instances. This is normally done with ssh -i key.pem or similar. I've tried setting is as both a public and a private key, to no avail. Also it seems that deployer is not properly recognizing the fact that phpseclib is failing in this case.

**Comment by notflip** [comment]
I'm getting the following error

     [Error] Call to undefined method Deployer\Host\Host::pemFile()

**Comment by antonmedv** [comment]
This is deprecated, use identyFilr
