### ISSUE TITLE
`auto_migrate` in the symfony task seems to do nothing

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#310]
It's even in the documentation, but it seems to do nothing right now.

**Comment by elfet** [comment]
Yeah, it's kind of deprecated.

**Comment by ZeeCoder** [comment]
Hmm, then it should be removed, and the docs should be updated.
But since this is removed, the `database:migrate` command must be documented properly as the alternative solution.

Basically what needs to be done to have db migrations is this:

```php
after('some-task', 'database:migrate');
```

I'll create the PRs, as soon as I find the time for it.
