### ISSUE TITLE
Idea: Setting for composer --no-dev

### ISSUE THREAD

**Issue by Danielss89** [deployphp/deployer#311]
I'm using deployer to deploy to dev-environment too, and i need dev-dependencies from composer for that. 
My idea is to allow for a setting, something like env("composer.dev", true); which would make the composer task remove the --no-dev value. "composer.dev" would be false by default so there is no BC break.

What do you think? Do you want a PR for this?

**Comment by elfet** [comment]
I think its better to have something like this:
```php
set('composer_options', '--no-dev --no-interaction ...');
```

**Comment by Danielss89** [comment]
That's a good idea too. Want me to PR that?

**Comment by leandrogehlen** [comment]
ref #287

**Comment by elfet** [comment]
@Danielss89 will implement myself.

**Comment by elfet** [comment]
Done.

**Comment by Danielss89** [comment]
Nice! thanks.

**Comment by elfet** [comment]
@Danielss89 you can specify this option server specified (for one, or for all servers):
```php
server(...)
    ->env('composer_options', '...');
```
