### ISSUE TITLE
provision:deployer creates deployer user but can't use sudo

### ISSUE THREAD

**Issue by OhMyC** [deployphp/deployer#3131]
- Deployer version: dev
- Deployment OS: 20.04 lts

Adding this line to provision.php:237 fixes this:
`run('echo "deployer ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers');`

**Comment by antonmedv** [comment]
This is un secure.

**Comment by OhMyC** [comment]
Well it doesn't work otherwise, what's your solution?

**Comment by antonmedv** [comment]
What part doesn’t work?

**Comment by OhMyC** [comment]
```
[192.168.56.106] run [ -d ~/test ] || mkdir ~/test
[192.168.56.106] sudo: a terminal is required to read the password; either use the -S op
tion to read from standard input or configure an askpass helper
```
Makes sense since deployer user doesn't have passwordless sudo.

**Comment by antonmedv** [comment]
This is strange. Please check permissions on home dir of deployer user.

**Comment by OhMyC** [comment]
Permissions are fine. I delved deeper and discovered that if:
        `if ($host->has('become')) {`

It's run as sudo, so it asks deployer for password because provision:website changes user to "deployer". The deployer user is created, but since config has become=root, it's still run as sudo whenever user is changed to deployer. BUT it's impossible to do any provisioning without become=root. 
So it's not strange, it just doesn't work.

**Comment by antonmedv** [comment]
To provision run dep like this:

    dep provision -o remote_user=root
