### ISSUE TITLE
Support php 7 and php 8

### ISSUE THREAD

**Issue by eerison** [deployphp/deployer#3134]
Hi I saw that this library only support one major php `version 7.x` and I was trying to update only php in the servers

would it be possible accept 2 major versions?

for example: ^7.2 | ^8.0 ?

**Comment by freesh** [comment]
In master composer.json i found this:
```json
    "require": {
        "php": "^8.0|^7.3",
```
Maybe you load an old version?

**Comment by eerison** [comment]
Yeah in master it support, but it's not in any release, Just in beta 👀

I'm using  6.8.0

**Comment by freesh** [comment]
Ah yes i see. :-/

I testet the 6.8 some minutes ago with php8 and it worked fine for Neos CMS and Flow framework.

My solution for the moment is, to use it as part of my project.
I downloaded it, modified the composer.json, and require it directly from the ./DistributionPackages/ path 👀

```json
    "require-dev": {
        "deployer/deployer": "@dev"
    },
    "repositories": {
        "distributionPackages": {
            "type": "path",
            "url": "./DistributionPackages/*"
        }
    },
```
Not the best solution, but worked für the moment. Until 7.0 is released.

**Comment by sebastian-ehrling** [comment]
Hi @antonmedv 
when will V7 be available?

**Comment by antonmedv** [comment]
Soon, I guess.

**Comment by eerison** [comment]
well I guess it's fine we close this issue :)
