### ISSUE TITLE
Problem with remote server commands output

### ISSUE THREAD

**Issue by php4umagento** [deployphp/deployer#3140]
- Deployer version: ^7.0@RC - v7.0.0-rc8
- Deployment OS: Ubuntu 22.04 / php 8.1

test method in functions.php compares output from the command
```
function test(string $command): bool
{
    $true = '+' . array_rand(array_flip(['accurate', 'appropriate', 'correct', 'legitimate', 'precise', 'right', 'true', 'yes', 'indeed']));
    return run("if $command; then echo $true; fi") === $true;
}
```

On some servers that output command contains some extra output such as hostname and extra characters, and that breaks the test result see below

```
[upgrade] run if [ -h /microcloud/domains/xxxx/domains/xxxxx/___repository/release ]; then echo +correct; fi
[upgrade] ]0;xxx.xxx.xxx.xxxx.com.xxxx
[upgrade] ]0;
[upgrade] +correct
```

if command returned `+correct` it would work

Deployer 6.0 connecting to same server returns just output and test is ok, but here it throws fatal error

I was trying to debug it but I am unable to find what might be causing that extra info and chars to be returned

**Comment by antonmedv** [comment]
Deployer v6 uses `bash -s` and Deployer v7 uses `bash -ls`.

>  -l  act as if it had been invoked as a login shell (i.e. source ~/.profile file)

Something in your .(bash_)profile/.bashrc files echos extra lines.

You can:
- Remove "extra stuff" from .profile.
- Set `shell` to `bash -s`:
   - `dep deploy -o "shell=bash -s"`

**Comment by php4umagento** [comment]
Thank you @antonmedv that worked
