### ISSUE TITLE
Filtered tasks with ->select() display in task output.

### ISSUE THREAD

**Issue by leevigraham** [deployphp/deployer#3141]
- Deployer version:  v7.0.0-rc.8
- Deployment OS: OSX

`vendor/bin/deployer.phar  deploy --plan all` shows the `feature` host with `craft:deploy:prepare`. 

When I run `vendor/bin/deployer.phar deploy stage` the task `craft:deploy:prepare` appears in the list of tasks… although I'm not actually sure anything is run because there is nothing output in verbose mode.

`craft:deploy:prepare` should only be shown when it's actually run.

Plan vs output

![image](https://user-images.githubusercontent.com/25124/170390203-62d4eb0d-e1cc-4419-82d0-0b683726c52e.png)

Output in debug mode (stage):

![Screen Shot 2022-05-26 at 10 26 10 am](https://user-images.githubusercontent.com/25124/170390693-d3bce2ce-2e3a-4419-935c-a3affa237e72.png)

Output in debug mode (feature):

![Screen Shot 2022-05-26 at 10 29 03 am](https://user-images.githubusercontent.com/25124/170390962-f1f3156a-303c-48a3-b18d-b74b1a81984b.png)

```php
<?php

namespace Deployer;

require __DIR__ .'/config/bootstrap.php';
require 'recipe/composer.php';

set('application', 'craft-boilerplate');

set('repository', 'git@github.com:newism/[redacted].git');
set('branch', 'main');

host('feature')
    ->set('hostname', 'xxx.xxx.xxx.xx')
    ->set('remote_user', 'forge')
    ->set('deploy_path', '/home/forge/[redacted]/feature')
    ->set('php_version', '8.0')
    ->set('cachetool', '/run/php/php8.0-fpm.sock')
;

host('stage')
    ->set('hostname', 'xxx.xxx.xxx.xx')
    ->set('remote_user', 'forge')
    ->set('deploy_path', '/home/forge/[redacted]/stage')
    ->set('php_version', '8.0')
    ->set('cachetool', '/run/php/php8.0-fpm.sock')
;

host('production')
    ->set('hostname', 'xxx.xxx.xxx.xx')
    ->set('remote_user', 'forge')
    ->set('deploy_path', '/home/forge/[redacted]/prod')
    ->set('php_version', '8.0')
    ->set('cachetool', '/run/php/php8.0-fpm.sock')
;

after('deploy:failed', 'deploy:unlock');

task('deploy:vendors')->addAfter('craft:deploy:prepare');

desc('Run craft setup scripts');
task('craft:deploy:prepare', function () {
    run('ls -la');
})->select('feature');
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3141">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3141/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3141/pledge.svg">
</picture>
</a>

**Comment by leevigraham** [comment]
Additionally when running a filtered task directly the process does not end and has to be quit manually.

![image](https://user-images.githubusercontent.com/25124/170391429-d2335395-78b6-4298-a2e4-0d5c0b1f0366.png)

**Comment by JorenV** [comment]
Can confirm, having the same issue
