### ISSUE TITLE
symphony/process requirement conflict

### ISSUE THREAD

**Issue by iantearle** [deployphp/deployer#3148]
- Deployer version: 4.3.0
- Deployment OS: osx monterey

Trying to install with another package "spatie/browsershot" and get the following:

```
Problem 1
    - deployer/deployer[v4.3.0, ..., v4.3.4] require symfony/process ~2.6|~3.0 -> found symfony/process[v2.6.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires deployer/deployer ^4.3 -> satisfiable by deployer/deployer[v4.3.0, ..., v4.3.4].

```

**Comment by antonmedv** [comment]
> Deployer version: 4.3.0

Wow 😯 
Try to upgrade to v7-rc.

**Comment by iantearle** [comment]
I should mention this was running `composer require deployer/deployer` which seems to be locked on ^4.3.0 - have since specifically run `composer require deployer/deployer:v7.0.0-rc-8` which installed fine.
