### ISSUE TITLE
On Deployer's "global" nature

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#315]
I'm starting to have a problem.

Deployer has a "global" nature, where you can set and get global variables, environment variables; we also have global functions, etc.

It simplifies things of course, but it also introduces numerous possibilities for errors.
This is the reason why we had to implement the ability to protect certain environment variables not so long ago: https://github.com/deployphp/deployer/pull/276

To further explain, and demonstrate my problem, consider the [Symfony](https://github.com/deployphp/deployer/blob/master/recipe/symfony.php) recipe.

Just in this recipe alone, there's a bunch of global variable declarations.
Since both the env and global variables declared here are "global", other tasks or recipes could conflict with them.

Look at this issue: https://github.com/deployphp/deployer/issues/311

Suppose I have a 3rd party recipe installed in my project, which already sets the "composer_options" global variable.

Now if this change gets implemented and merged in, my deployment workflow could be broken the next time I update Deployer to the newest version.

Having said all the above, I think there should be a discussion about how configuring the tasks could be solved a different way, which would address these issues.

**To start off**: I have an idea which could be implemented in the next (v4) version.
```php
<?php

// in deployer.php
set_config('task-name', [
    'bin_dir' => '...',
    'composer_params' => '...',
]);


// in the recipe
task('task-name', function() {
    $config = get_config('task-name', [
        // default values
        'bin_dir' => '...',
        'var_dir' => '...',
        'composer_params' => '...',
    ]);
});
```

The idea here is similar to the global parameters, but now the variables are "scoped" under the task's name, so for example the "bin_dir" parameter could be used by any number of tasks, and they won't conflict with each other.

Just think about how simpler the 3rd party [slack](https://github.com/deployphp/recipes/blob/master/recipes/slack.php) task could be.

With this solution the need for "global variables/parameters" would be gone too.

**Comment by ZeeCoder** [comment]
A somewhat relevant issue: https://github.com/deployphp/deployer/issues/292

**Comment by elfet** [comment]
Nice idea! But the main appointment is to keep config simple as possible. 
Issues you linked are not about separating setting conflicts. Them are for add some more configs. 
Also if you do not require 3rd party recipes with `require`, this does not lead you to errors. 
The next features i suggest to implement in Deployer is next:
* Immutable settings by default. With available to override, and parallel support. 
* Events with `on('...', function ($event) {...});` based on [The EventDispatcher Component](http://symfony.com/doc/current/components/event_dispatcher/introduction.html).
* DI Configuration based on [Pimple](http://pimple.sensiolabs.org/).
So, this is my little roadmap :)
PS
* Native SSH support (slow, but 100% featureful)

**Comment by ZeeCoder** [comment]
I see, that seems neat!

If you're going to use pimple, there's no need to implement my proposed solutions, since that can be achieved in a nicer way through container registration.

The introduction of the event dispatcher would be very nice too. :+1: 
There would be no need to fully override a task just to do something a little bit different.

Are these plans for the 4.x release?
I'm just assuming, since these would be BC-breaking changes.

**Comment by elfet** [comment]
This all will be for v3.1. No BC-breaks.

**Comment by ZeeCoder** [comment]
Sounds great!
I can't wait. :)

**Comment by elfet** [comment]
If you want you can help with implementation of this things :)

**Comment by ZeeCoder** [comment]
Well first we have to plan exactly how the features are going to be implemented.
We could use the [gitter](https://gitter.im/deployphp/deployer) channel for that.
And then if I feel capable I will gladly help. :)

**Comment by ZeeCoder** [comment]
Another example why the "global" way Deployer works could be harmful: https://github.com/deployphp/deployer/issues/316
