### ISSUE TITLE
PHP 8 compatibility for the 6.x branch

### ISSUE THREAD

**Issue by rutgerrademaker** [deployphp/deployer#3159]
As upgrading to 7.x is not really straight forward AND there is no stable release for 7.x yet, it would be great to see PHP 8 compatibility for the 6.x branch.

It might just be as simple as just replacing   "^7.2" by "^7.2 || ^8.0" in https://github.com/deployphp/deployer/blob/6.x/composer.json

I get the focus is on 7.x but if this idea is supported I could open a PR and see what the impact on the rest of the codebase would be (if any)

**Comment by antonmedv** [comment]
> if any

You can try. But there will be much more problems. One solution is to use phar v6

**Comment by rutgerrademaker** [comment]
Thanks for the quick reply, and the suggestion!
Our main issue is that we do a `composer require deployer/deployer` in a lot of places to get the phar installed
Will just give it a try and let you know

**Comment by kiropowered** [comment]
@rutgerrademaker hi, we also can't upgrade php version because deployer v6 is stuck to php7.
Did you have any trouble removing deployer from composer and using the phar on PHP8 ?

**Comment by rutgerrademaker** [comment]
@kiropowered I did not try to go the phar way yet, as in our situation it's not really easy to accomplish
Instead I'm trying to figure out how much work it would be to actually make 6.x compatible
You can see my progress over here >  https://github.com/deployphp/deployer/compare/6.x...rutgerrademaker:deployer:6.x

**Comment by rutgerrademaker** [comment]
I gave it a try and openened this PR > https://github.com/deployphp/deployer/pull/3189
Great chance I missed something, but for me this seems to do the trick until we have adopted deployer 7

**Comment by antonmedv** [comment]
Some Symfony dependencies also only php7.
