### ISSUE TITLE
Laravel override get() function

### ISSUE THREAD

**Issue by Zae** [deployphp/deployer#316]
I'm getting this error when trying to run deployer.

I installed deployer ^3.0 through composer in a laravel 5 project

running PHP 5.6.8 or PHP 7.0.0-dev (did not test any other versions)

**Comment by elfet** [comment]
What version of Laravel?

**Comment by Zae** [comment]
Version v5.0.32 according to my composer.lock file.

**Comment by elfet** [comment]
Show full `deploy.php ` file here, please.

**Comment by Zae** [comment]
~~~~php
<?php

require 'recipe/laravel.php';

server('prod', 'XXXX', 22)
	->user('ezra')
	->identityFile()
	->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
	->stage('production')
	->env('deploy_path', '/home/ezra/apps/'); // Define the base path to deploy your project to.

// Specify the repository from which to download your project's code.
// The server needs to have git installed for this to work.
// If you're not using a forward agent, then the server has to be able to clone
// your project from this repository.
set('repository', 'XXXXXX');
~~~~

**Comment by elfet** [comment]
Do your require your `autoload.php` file? You shoud not to do this.

**Comment by Zae** [comment]
I do not, I installed deployer with composer into my vendors directory and called deployer using

~~~~
./vendor/bin/dep deploy production
~~~~

I guess that composer is automatically loading laravel's helper file before your helper file and because they both define a global get() function they clash.

**Comment by elfet** [comment]
Yeah, seems like that. Can you use phar?

**Comment by Zae** [comment]
I can and that works, but wanted to let you know of the bug anyway.
Op 1 jun. 2015 15:13 schreef "Anton Medvedev" <notifications@github.com>:

**Comment by andreascreten** [comment]
Are there any plans to make Deployer L5 and Lumen compatible?

**Comment by kenjis** [comment]
Don't worry. It is on going. See #356 

And you can deploy now if you use `deployer.phar`.

**Comment by elfet** [comment]
@andreascreten you can implement Lumen recipe by yourself.

**Comment by felipepodesta** [comment]
+1

**Comment by ceesvanegmond** [comment]
We do need the deployer namespace. I really want to use composer, since it is an dependency of my project, but when using Laravel 5.1, I have to use the .phar file, which is annoying me.

This means that all Laravel users cannot use the composer dependency, but have to use the phar file.

I hope this is going to be fixed soon.

**Comment by dimsav** [comment]
+1

**Comment by elfet** [comment]
Working on that! :)

**Comment by JHGitty** [comment]
Workaround until version 4: https://github.com/deployphp/docs/issues/44

**Comment by ablunier** [comment]
+1

**Comment by oanhnn** [comment]
This issue will be resolved with Deployer v4.x (namespace function)
