### ISSUE TITLE
Sentry recipe : increase Httpie timeout

### ISSUE THREAD

**Issue by franck-grenier** [deployphp/deployer#3160]
- Deployer version: 7.0.0-rc-8
- Deployment OS: Gitlab CI (Docker runner)

Hello Deployer,
I'm having troubles to POST my releases and their deploys to my self-hosted Sentry.

Randomly, POST requests are ended on client-side by Httpie timeout of 5s (https://github.com/deployphp/deployer/blob/master/src/Utility/Httpie.php#L153).
I can see them arrive on my Sentry server responding 499.

Do you know how i can increase these Curl timeout params for the Sentry recipe ?

Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3160">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3160/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3160/pledge.svg">
</picture>
</a>

**Comment by norkunas** [comment]
having same problem..

**Comment by franck-grenier** [comment]
What  I did to avoid deployment failures due to timeouts : **catch the exception**

```php
task('deploy:sentry:once', function(){
    try {
        invoke('deploy:sentry');
    } catch (\Exception $e) {
        info('Unable to push release or deploy to Sentry : ' . $e->getMessage());
    }
})->once();
```

**Comment by antonmedv** [comment]
Clever)

**Comment by jackd248** [comment]
Okay I see, using the `setopt` function is helping with this issue:
https://github.com/deployphp/deployer/blob/master/src/Utility/Httpie.php#L141

**Comment by thyseus** [comment]
@jackd248 could you please give an example what you have written into your `deploy.php` to raise that timeout? Thanks a lot !

**Comment by jackd248** [comment]
Hej @thyseus,
i have only adjusted my task to send a notification, no global configuration.
```
Httpie::post(get('webhook'))
        ->setopt(CURLOPT_TIMEOUT, 10)
        ->jsonBody(
            [
                'text'       => $message
            ]
        )
        ->send();
```
