### ISSUE TITLE
Empty response from command: $git config --get remote.origin.url

### ISSUE THREAD

**Issue by xmannv** [deployphp/deployer#3162]
https://github.com/deployphp/deployer/blob/8e4366bb42f10421ea0aacc93f7bab59cf29d6ed/recipe/deploy/update_code.php#L95

I must add '-f config' to get correct result.

```
$git config -f config --get remote.origin.url
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3162">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3162/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3162/pledge.svg">
</picture>
</a>

**Comment by sviriden** [comment]
I also have problems because of `remote.origin.url`.

Task `deploy:update_code` generates infinite loop.

Probably it's because I don't have at all  `remote` named `origin` in my repositories.

So I just commented this block, then task works fine:

https://github.com/deployphp/deployer/blob/8e4366bb42f10421ea0aacc93f7bab59cf29d6ed/recipe/deploy/update_code.php#L94-L99

**Comment by Base29** [comment]
> I also have problems because of `remote.origin.url`.
> 
> Task `deploy:update_code` generates infinite loop.
> 
> Probably it's because I don't have at all `remote` named `origin` in my repositories.
> 
> So I just commented this block, then task works fine:
> 
> https://github.com/deployphp/deployer/blob/8e4366bb42f10421ea0aacc93f7bab59cf29d6ed/recipe/deploy/update_code.php#L94-L99

Hello @sviriden where did you comment on this code? I am using laravel and I have commented out this code in `vendor/deployer/deployer/recipe/deploy/update_code.php` but it did not take effect because the deployer is still running the same command .. any suggestions on this?

**Comment by syarifid** [comment]
> Had the same issue, but the problem was actually a permissions issue on the server. The .dep folder in particular has to be owned by the user that is triggering the deployment.

After I changed the .dep folder to be owned by the user `deployer`, it was successfully deployed. But, the .dep folder back to www-data user. How do you think I could solve it?

**Comment by antonmedv** [comment]
Try to understand who is making the .dep dir owned by www-data.
