### ISSUE TITLE
Deployer changes directory when executing recipes

### ISSUE THREAD

**Issue by KevinKromjong** [deployphp/deployer#3165]
- Deployer version: 6.8.0 and 7.0.0-rc.8
- Deployment OS: MacOS/Linux

For our Magento 2 projects, we put Deployer in a subfolder (build/deployer) of the main project and run the Deployer commands from the root of the project. We then use the `--file` flag to target our own recipes. One reason for this is that we need some Magento 2 files and folders for preparation, which resides in the project root.

When using version 6.8.0, this works fine as the Deployer recipes that are executed are run from the project root. However, when using the newest RC of Deployer, for some reason it `cd`'s into the directory that the `--file` flag points towards and executes all the task within that directory. 

**Example**
`build/deployer/vendor/bin/deployer.phar -vv --file=build/deployer/recipe/build.php build`
(where the build.php is a custom recipe that prepare some files before deploying and build is the name of the task)

The only task I put in this file is the following:
```
task('build', function () {
    writeln(run('pwd'));
});
```

The outcome is the following:

**6.8.0**
```
➤ Executing task build
[localhost] > pwd
/var/www/html
```

**7.0.0-rc.8**
```
task build
[localhost] run pwd
[localhost] /var/www/html/build/deployer/recipe
```

As you can see, the newest version executes our task from within the recipe directory, while the old one executes it from the root of the project. This causes our build and deploys to fail.

I've tried to use the `cd` command from the `deployer.phar` file to change back to the root of the project before executing tasks, but to no avail. It looks like that command is ignored. We've basically tried all kind of sketchy solutions to make it work, but I'm not sure why the newest version of Deployer executes from within the recipe directory instead of the location from where the Deployer command is run.

Is this expected behaviour? And if so, is there a command or another way to let it execute from the root of the project again without `cd`-ing into the recipe file's directory?

Thanks in advance!

**Comment by antonmedv** [comment]
An you provide a minimal reproducible example?Can tell without debugging.

**Comment by KevinKromjong** [comment]
Take a random project as your root, I'm taking Magento here as an example:
`composer create-project --repository-url=https://repo.magento.com/magento/project-enterprise-edition <install-directory-name>`
(or open source if you don't have enterprise keys: `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <install-directory-name>`)

It shouldn't matter if you use `composer require deployer/deployer` or clone this repo. I went for the latter option to easily test it:
`git clone https://github.com/deployphp/deployer.git build/deployer`

Then afterwards:
- go into `build/deployer` and switch to the `6.x` branch. Make sure you have a PHP version lower than 8 enabled. 
- Run `composer install` afterwards.
- make a `recipe` directory and create a `build.php` file in there
- Add the following code to that file:
```<?php
namespace Deployer;

localhost();

task('build', function () {
    writeln(run('pwd'));
});
```
Go back to the root of the project and execute the command to run the deployer with the custom recipe: `build/deployer/bin/dep -vv --file=build/deployer/recipe/build.php build`

The output is:
```
➤ Executing task build
[localhost] > pwd
/var/www/html
• done on [localhost]
✔ Ok [7ms]
```
As you can see, the current path is the root from where I executed the command.

Now:
- Just to be sure we don't end up with old and newer files mixed up, remove the `build/deployer` folder and check it out again.
- Switch to the 7.0 RC branch: `git checkout v7.0.0-rc.8` and make sure you have PHP 8.1 enabled.
- Do a `composer install`
- Recreate the recipe in the same location with the same contents.
- Go back to the root of the project and execute the command to run the deployer with the custom recipe: 
`build/deployer/deployer.phar -vv --file=build/deployer/recipe/build.php build`

The output is:
```
task build
[localhost] run pwd
[localhost] /var/www/html/build/deployer/recipes
[localhost] /var/www/html/build/deployer/recipes
done on localhost
done build 157ms
```

As you can see, the current path is the path of the recipe I'm executing.

The expected output should be the same as the code from version 6.x: that the path is not changed to the directory of the recipe, but you stay in the directory from where you executed the command.


Hope this helps a bit reproducing the bug. Let me know if you need more information!

**Comment by KevinKromjong** [comment]
Hi @antonmedv,

Do you have an idea when you have some time looking into this?

Thanks!

**Comment by antonmedv** [comment]
Hi, right now I don't have time to look into this.

**Comment by kjkooistra-youwe** [comment]
This change was introduced in https://github.com/deployphp/deployer/issues/1774
You can fix this by prefixing the command with `DEPLOYER_ROOT=.`. Also see:

- https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md (item 10)
- https://github.com/deployphp/deployer/issues/2628
