### ISSUE TITLE
Provide a possibility to skip validateConfig

### ISSUE THREAD

**Issue by h1nds1ght** [deployphp/deployer#3170]
This commit https://github.com/deployphp/deployer/commit/76f07b4e05b898db852686ef8cac93d8b1a7f692#diff-8558493b7152a73eb3ba31b63463fcb735f23d4af82de6e982c39df5a040ff21R112 introduced a new function `validateConfig`. If you use code which uses similiar config names it emits a warning

```
warning Did you mean "site" or "sites"?

    6: set('site', 'default');
    7: set('sites', function () {
    11:   get('sites');

task releases
```
Actually I don't like this feature since I want to write my code the way I want. Nevertheless it would be at least nice to have an option to opt out of this behaviour.

Example deploy.php:
```
<?php
namespace Deployer;

require  'recipe/common.php';

set('site', 'default');
set('sites', function () {
  return ['foo', 'bar'];
});
get('releases', function() {
  get('sites');
});
host('localhost');
```

**Comment by antonmedv** [comment]
Yes! I think this feature can be removed.

**Comment by antonmedv** [comment]
Done.
