### ISSUE TITLE
Migration does not mention about remowing onHosts onRoles onStages filters on tasks

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#3176]
- Deployer version: 7.0.0-rc8

as I understand filters like `onHosts` `onStages` has been removed? At least don't see it in Task class. but migration documentation does not mention anything about this. What do I have to do in the new version instead of `onHosts` filter? my guess there is new `select` I should replace with this somehow no?

**Comment by davideprevosto** [comment]
Hello @svycka,

were you able to fix your issue? I am trying to replace onStage too, unluckily with no success yet.

**Comment by tomvo** [comment]
Bumping this as running into the same problem.

**Comment by daniel-kratohvil** [comment]
`onHosts()`, `onStage()` and `onRoles()` have been replaced by labels and selector in `7.x`

```
task(...)
    ->select('stage=prod');
```

It's documented here:
[https://deployer.org/docs/7.x/selector](https://deployer.org/docs/7.x/selector)
[https://deployer.org/docs/7.x/UPGRADE](https://deployer.org/docs/7.x/UPGRADE)
