### ISSUE TITLE
[Docs] Provide an "Examples" section for beginners?

### ISSUE THREAD

**Issue by mandrasch** [deployphp/deployer#3182]
Hey, first of all thanks so much for providing this awesome and open piece of software! 🙏

I have a few ideas for the docs: 

Deployer was recommend to me by a colleague. While I was first looking at the v7 docs, I just couldn't understand how an existing recipe could be used for simple deployments. 

Something like this snippet would have been very helpful for me: 

### Use a recipe

```php
<?php
// deploy.php

namespace Deployer;

import('recipe/statamic.php');

set('application', 'My Statamic Site');

set('repository', 'git@github.com:exampleuser/my-statamic-site.git');

// Target server (SSH)
host('live')
    ->set('remote_user', 'root')
    ->set('hostname', '123.456.789.123')
    ->set('deploy_path', '~/html/my-statamic-site.dev/');
```
Call this task via `dep deploy live` for the target server "live".  

<hr> 

### Overwrite deploy()-task

Also helpful would be the information that imported tasks, such as `deploy()`, can be easily overriden by simple defining this task again: 

```php
task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    // add a custom task
    'my-custom-task',
    'artisan:storage:link',
    'artisan:cache:clear',
    'statamic:stache:clear',
    'statamic:stache:warm',
    'deploy:publish',
]);
```

<hr>

And in the end it would be helpful to have a small description like:

### What is happening when I deploy?

```
Deployer connects to the target server via SSH and runs the tasks defined in `deploy.php` / `deploy.yaml`. Therefore your server needs to have _git_ installed.

Deployer will create special folder structure for releases:

Deployer will create a shared/-folder which will be kept during new deployments: 

Requirements: 
- the public SSH key of the machine who is running Deployer is added to the targets server `~/.ssh/authorized_keys`
- the public SSH key of the target server has been added to the git repository (if you use a private repository), otherwise Deployer can't pull the git repository on the target machine
```

https://t3terminal.com/blog/typo3-deploy/ has for example good graphic of what is happening:

![image](https://user-images.githubusercontent.com/777278/177036799-68e35bc0-a34a-42b3-b134-45c379cd520e.png)

<hr>

It would be also very helpful to have a list with tutorials for different CMSes maybe to get started more easily with Deployer. Or maybe an `awesome-deployer` repository (such as https://github.com/ziadoz/awesome-php#readme) could be helpful. 

Much success with Deployer! If it's irrelevant, please just close this issue. :-) 

Cheers, Matthias
PS: I blogged about my first steps with Deployer here - https://dev.to/mandrasch/statamic-meets-hetzner-cloud-ploi-and-deployer-2ko5
PPS: Just saw after publishing that https://deployer.org/docs/7.x/yaml has a good snippet, but the PHP snippet is missing

**Comment by antonmedv** [comment]
Awesome! Thanks. Docs suggestion are supper. Will definitely use it.
