### ISSUE TITLE
Deployer (SSH) doesn't ask for the password nicely

### ISSUE THREAD

**Issue by tomaszkane** [deployphp/deployer#3196]
It's trival case, but confusing. When SSH waiting for password Deployer 6 prints `Password: `
Deployer 7 prints `  ⠇ word:   ⠴` with rolling animations...

- Deployer version: 7.0.0-rc.8

`$ dep deploy -vvv`

```bash
task deploy:setup
[production] /usr/bin/php /home/deployer/vendor/deployer/deployer/deployer.phar worker --port 46827 --task deploy:setup --host production --decorated -vvv
[production] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/app-deployer@x.x.x.x' 'app-deployer@x.x.x.x' ': xxxxxx; bash -ls'
[production] run [ -d /var/www/foo.com ] || mkdir -p /var/www/foo.com;
cd /var/www/foo.com;
[ -d .dep ] || mkdir .dep;
[ -d releases ] || mkdir releases;
[ -d shared ] || mkdir shared;
The authenticity of host 'x.x.x.x (x.x.x.x)' can't be established.
ECDSA key fingerprint is xxxxx
ECDSA key fingerprint is xxxxx
  ⠸  ou sure you want to continue connecting (yes/no)?   ⠏ 
[production] Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.
  ⠇ word:   ⠴
```

This is confusing, I thought my SSH configuration was wrong or the routing network didn't allow connection and I have a timeout here.

**Comment by tomaszkane** [comment]
Some of my servers using ssh-keys so I don't always expect password ask.
BTW `ssh user@host` prints `Password: ` when it need password :-)

**Comment by antonmedv** [comment]
Deployer v7 don't have this functionality any more. In v7 each task is executed inside of a worker process, so no passing on tty happends. Deployer -> Worker -> SSH -> Remote host.

**Comment by tomaszkane** [comment]
Więc jesteśmy skazani na enigmatyczne komunikaty? :-|

**Comment by antonmedv** [comment]
You can configure you ssh client to not show such messages, or just generate host keysign before connecting.

**Comment by antonmedv** [comment]
I’m not getting it. What security permissions? 

Please, share what’s happening for a normal ssh user@host.

**Comment by tomaszkane** [comment]
Just SSH password.

**Comment by antonmedv** [comment]
Yes, Deployer v7 doesn’t support ssh password. Consider switching to ssh_key.

**Comment by tomaszkane** [comment]
But it actually works:
```
$ dep deploy:is_locked production
task deploy:is_locked
  ⠧ word:   ⠼ 
[production] info Deploy is unlocked.
```
after `⠧ word:   ⠼` I paste password from clipboard ant hit _enter_. So You mean, "deployer 7 works with ssh password but not officially support it" ?

**Comment by antonmedv** [comment]
I’m suppressed it is working actually))
