### ISSUE TITLE
Caddy provisioning failed

### ISSUE THREAD

**Issue by gizamichal** [deployphp/deployer#3201]
- Deployer version: 7.0.0
- Deployment OS: Ubuntu 20.04

```
<?php
namespace Deployer;
require 'recipe/common.php';
host('X.X.X.X');
after('deploy:failed', 'deploy:unlock');
```

dep provisioning fails when installing Caddy:

[X.X.X.X] Err:6 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease
[X.X.X.X]   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
[X.X.X.X] Get:8 https://deb.nodesource.com/node_16.x focal/main amd64 Packages [774 B]
[X.X.X.X] Reading package lists...
[X.X.X.X] W: GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
[X.X.X.X] E:
[X.X.X.X] The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is not signed.
[X.X.X.X]  error  in provision.php on line 98:
[X.X.X.X] exit code 100 (Unknown error)

Related discussion: https://github.com/caddyserver/dist/issues/83

**Comment by antonmedv** [comment]
Is there some solution or workaround?

**Comment by gizamichal** [comment]
It just works today, probable Caddy developers fixed public key issue.

**Comment by hansipete** [comment]
I got this error today :( Is there any workaround? Thank you
