### ISSUE TITLE
GitHub Action removed lots of files

### ISSUE THREAD

**Issue by torhoehn** [deployphp/deployer#3207]
Is there a reason why a GitHub action removed lots of files?

- https://github.com/deployphp/deployer/commit/1de9b97611fb27e05e274ac69daa9346bdc72c34
- https://github.com/deployphp/deployer/commit/e23a2111bc4ea3795c3037bd933d8055125416c7
- https://github.com/deployphp/deployer/commits/v7.0.0-rc.7
- https://github.com/deployphp/deployer/commits/v7.0.0-rc.8

**Comment by antonmedv** [comment]
Fixed.
