### ISSUE TITLE
Run task inside another task

### ISSUE THREAD

**Issue by marcosh** [deployphp/deployer#322]
I find that it would be useful to be able to call another task inside a task. 

Maybe some code can say this more clearly... I would like to be able to do something like

    task('subtask_1', function () {}):
    task('subtask_2', function () {});

    task ('task', function () {
        if ($condition) {
            task('subtask_1');
        } else {
            task('subtask_2');
        }
    });

At the moment this gives me an error because we I call `task` it expects two arguments. 

Do you think it would be interesting to have such a functionality?

**Comment by elfet** [comment]
This is functionality is in contradiction with Deployer philosophy. 
Deployer runs each task, on each server, if everything is ok, then next task is executed. That's helps keep server states consistency, if something broke during executing task on on server, thats stop execution on all servers. 

Howether, you can still execute your code(you need separate code body from tasks):
```php
$subtask_1 = function () {...};
$subtask_2 = function () {...};

task('subtask_1', $subtask_1):
task('subtask_2', $subtask_2);

task ('task', function () {
    if ($condition) {
        $subtask_1();
    } else {
        $subtask_2();
    }
});
```
But i do not recommend to do this. Try refactor you deploy strategy to separate independent tasks.
Take a look at [common.php](https://github.com/deployphp/deployer/blob/master/recipe/common.php) recipe tasks for an example.

**Comment by marcosh** [comment]
Thanks @elfet for your reply.
At the moment I have my code, with the `if` separating the two cases, all inside a single task.
I would like to use the `if` to differentiate the first deploy, when there an no other releases, and the following deploys, when I can use a previous release to copy all the code to fasten the deploy, as it is discussed on [issue 206][1]. Do you think this is a bad practice?

[1]: https://github.com/deployphp/deployer/issues/206

**Comment by elfet** [comment]
I think correct solution for #206 is to use new git option `--dissociate/--reference`, this will be implemented in Deployer 3.1.
```
$ git clone --reference ../oldclone --dissociate https://github.com/gitster/git.git
```

**Comment by marcosh** [comment]
Cool stuff! This will be nice to speed up the clone operation.
I didn't try it, but I think that the result will be the same of a simple clone, so, for example, you would not get a copy of the vendor directory and so you would not solve the use case the was raised in the beginning of #206.

**Comment by elfet** [comment]
Composer cache vendors while installing too.

**Comment by marcosh** [comment]
@elfet I just realized that your idea of using the git `--dissociate` option for the cloning process is quite problematic, since it is available only in git version `2.3` and both Debian 8 and Ubuntu 15.04 are using git 2.1.4. I'm not sure if everybody id going to upgrade its git version to have this feature.

**Comment by elfet** [comment]
But if you want this feature - you have to upgrade git, all simple :smile:

**Comment by johnny-bit** [comment]
@marcosh You can try having it another way - currently `dissociate/reference` is enabled only if Your git is new enough. Instead You can use `rsync:warmup`. Depending on Your settings it can copy vendors and others. Problem would only lie in the fact that cloned git copy is shalow, but You can actually (i think) do pull&ff on shallow clone.

**Comment by marcosh** [comment]
@johnny-bit correct me if I'm wrong, but I realized that your approach could have a drawback. Suppose that a deploy goes wrong, the release directory is created but no file is actually copied there. When you deploy then next time, `rsync:warmup` will have no file to copy. In particular the `git pull` command will not find the `.git` files and it will fail. With @elfet this will not happen because you're always doing a `git clone` and you're not assuming the presence of anything.

**Comment by johnny-bit** [comment]
Yes, that's right. It has this drawback. Plus, by default, rsync is set not
to copy `.dir`, so You'd have to be smart about what You're doing.

With `rsync:warmup` + `git pull` I'd do same thing that I did for
reference/dissociate: try. Then in case of failed pull, do normal clone.
Then there's no drawbacks :D

The beauty of it is: if You do it smart then You either get same behaviour
or advantage, no disadvantages.

**Comment by arderyp** [comment]
for anyone finding this way after the fact, this is now possible with `invoke("my:task")`
