### ISSUE TITLE
symfony recipe not available in 7

### ISSUE THREAD

**Issue by arderyp** [deployphp/deployer#3221]
- Deployer version: v7.0.0-rc.9
- Deployment OS: Ubuntu 20.4

I am migrating from Deployer 6 to deployer 7, and there used to be a symfony4.php recipe.  It looks like it is no longer available in deployer 7.

**Comment by marvinhinz** [comment]
Try symfony.php instead of symfony4.php

**Comment by arderyp** [comment]
The file does not exist.  No Symfony recipes here: https://github.com/deployphp/deployer/tree/master/contrib

**Comment by marvinhinz** [comment]
Its not in contrib : https://github.com/deployphp/deployer/blob/master/recipe/symfony.php

**Comment by arderyp** [comment]
ahh, right, okay, I see it now

**Comment by antonmedv** [comment]
Also deployer.org has a nice search.
