### ISSUE TITLE
6 to 7 upgrade documentation does not include deprecation of Task->setPrivate()

### ISSUE THREAD

**Issue by arderyp** [deployphp/deployer#3222]
- Deployer version: v7.0.0-rc.9
- Deployment OS: Ubuntu 20.4

Is there a replacement, or private tasks are no longer supported?

https://deployer.org/docs/7.x/UPGRADE#step-1-update-deployphp

**Comment by arderyp** [comment]
based on the updated docs, I suspect the new usage is `->hidden()`: https://deployer.org/docs/7.x/tasks#hidden

I will leave this open as a reminder to update the migration docs.

**Comment by antonmedv** [comment]
Done.
