### ISSUE TITLE
renaming of deployer.phar to dep breaks phpstan

### ISSUE THREAD

**Issue by arderyp** [deployphp/deployer#3223]
- Deployer version: v7.0.0-rc.9
- Deployment OS: Ubuntu 20.4

In `v7.0.0-rc.9`, `deployer.phar` was renamed back to `dep`.  The lack of a `.phar` extension does not play nicely with phpstan.

In [v7.0.0-rc.8](https://github.com/deployphp/deployer/releases/tag/v7.0.0-rc.8), the following working in my `phpstan.neon`:

```
scanDirectories:
    # https://github.com/phpstan/phpstan/discussions/5025
    - phar://vendor/deployer/deployer/deployer.phar
```

But under `v7.0.0-rc.9`, the following does not work:

```
scanDirectories:
    # https://github.com/phpstan/phpstan/discussions/5025
    - phar://vendor/deployer/deployer/dep
```

It throws:  `Path phar://vendor/deployer/deployer/dep does not exist`

If I copy `dep` to `dep.phar` and use the following, it works:

```
scanDirectories:
    # https://github.com/phpstan/phpstan/discussions/5025
    - phar://vendor/deployer/deployer/dep.phar
```

Not sure if this is a phpstan issue or a deployer issue.

**Comment by antonmedv** [comment]
Deployer starts with rc.9 ships with src/ code. So you can simply delete all phar scan steps and everything should just work.

**Comment by arderyp** [comment]
I was hoping that would be thew case, but I don't actually see it.  I have v7.0.0-rc.9 installed and here is what I see:

```
$ ls -l vendor/deployer/deployer/
total 1556
-rw-rw-r-- 1 arderyp arderyp    722 Jul 24 04:28 composer.json
drwxrwxr-x 2 arderyp arderyp   4096 Jul 24 04:28 contrib
-rwxrwxr-x 1 arderyp arderyp 777027 Jul 24 04:28 dep
-rw-rw-r-- 1 arderyp arderyp    820 Jul 24 04:28 deploy.yaml
-rw-rw-r-- 1 arderyp arderyp   1087 Jul 24 04:28 LICENSE
-rw-rw-r-- 1 arderyp arderyp   1753 Jul 24 04:28 phpcs.xml
-rw-rw-r-- 1 arderyp arderyp    305 Jul 24 04:28 phpstan.neon
-rw-rw-r-- 1 arderyp arderyp    935 Jul 24 04:28 phpunit.xml
-rw-rw-r-- 1 arderyp arderyp   1287 Jul 24 04:28 README.md
drwxrwxr-x 8 arderyp arderyp   4096 Jul 24 04:28 tests
```

No `src` directory.

**Comment by antonmedv** [comment]
Hmmm, maybe misconfigured something. Will check.

**Comment by arderyp** [comment]
amazing, thanks for the quick reply!
