### ISSUE TITLE
Download link on the document does not work

### ISSUE THREAD

**Issue by hirockhirock** [deployphp/deployer#3225]
- Deployer version: 6.x
- Deployment OS: Any

Download link for 6.x which is on [the installation document (v6.x)](https://deployer.org/docs/6.x/installation) does not work.
It returns 404 now.
```
curl -LO https://deployer.org/deployer.phar
```
I believe many developers using deployer on GitHub Actions use the link.
Is it no longer supported?

**Comment by antonmedv** [comment]
Yes, looks like v7 release broke that link. Will fix, but notice, this link will be pointing to v7.

**Comment by pyr0hu** [comment]
Will there be a download link for 6.x?

**Comment by antonmedv** [comment]
We have plenty of links: https://deployer.org/download ;)

**Comment by antonmedv** [comment]
Or should `/deployer.phar` be always pointing to v6? 🤨

**Comment by pyr0hu** [comment]
@antonmedv great, thanks! The 6.x docs just mentioned `https://deployer.org/deployer.phar` so it was a bit confusing

**Comment by PimButton** [comment]
@antonmedv this is also breaking the Github Action that uses Deployer: https://github.com/deployphp/action/issues/40

**Comment by alanaasmaa** [comment]
> Or should `/deployer.phar` be always pointing to v6? 🤨

I would suggest to keep /deployer.phar to v6 because documents are suggested to use this for ages. And might brake a lot of things.

maybe /deployer-7latest.phar or something for latest 7 version.

**Comment by antonmedv** [comment]
Yes, gonna pin /deployer.phar to v6.8.0, permanently)

**Comment by sandermarechal** [comment]
This broke my CI images as well. Will there be custom links for v6-latest and v7-latest? I don't want to pin to a specific patch release

**Comment by hirockhirock** [comment]
The link works correctly now. Thanks!

**Comment by Amunak** [comment]
You might want to consider using the same scheme as Composer: having `latest-stable` (latest major version), `latest-7.x` (latest v7), `latest-6.8.x` (latest 6.8LTS), ... See https://getcomposer.org/download/, section "Manual download".
