### ISSUE TITLE
Writable dirs: Allow -R param

### ISSUE THREAD

**Issue by Danielss89** [deployphp/deployer#323]
I have a data/cache folder with several folders and subfolders, and it would be nice if i could just add data/* to the `writable_dirs` options(with a -R param), instead of having to add each subfolder individually.

**Comment by ZeeCoder** [comment]
Hmm, looking at the current implementation that would be hard to achieve.

Instead I propose another solution.
```php
set('writable_dirs', [
    'data/cache'
]);
set('writable_dirs_recursive', true);
``` 

The second parameter could be checked inside the `deploy:writable` task, and it would behave accordingly.

On second thoughts there's an issue with this though, that now all the `writable_dirs` will be rewritten in a recursive fashion, so I can't do something like the folowing:

```php
set('writable_dirs', [
    'data/*', // recursive
    'data/log', // non-recursive
]);
```

Maybe we should just check for the existence of a trailing "*"?

Any thoughts @elfet ?

**Comment by elfet** [comment]
Why do not do something like this?
```php
set('writable_dirs', ['data']);
```
Now every of your data is writeable. 
I think adding settings like `writable_dirs_recursive` will confuse users and complicate writable tasks. It's better to keep it as possible as simple(but not simpler). 

If you need to add write permissions recursively - override writable task:
```php
// deploy.php
task('writable', function () {
    run('chmod -R 777 {{writable_dir}}');
});
```

**Comment by ZeeCoder** [comment]
Fair points, this could be easily achieved through a custom task.

**Comment by Danielss89** [comment]
It could easily be ahcieved through a custom task, but i still think it is something that a lot would use. What about checking if a param is array or string, if string, just chmod, if array then look for the keys:
```
set('writable_dirs', ['data/cache', ['dir' => 'data/*', 'params' => '-R']]);
```

**Comment by ZeeCoder** [comment]
That would still conflict with the task's name.
"writable_dirs" makes the given *directories* writable.
It has nothing to do with the possible files inside them.

Another problem is that you are thinking with the `chmod` command, when in reality the "deploy:writable" task does more than that.
Please look at the code here: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L175

Even if it gets implemented, it has to be an other task imho.

**Comment by Danielss89** [comment]
ok
