### ISSUE TITLE
fail-support in YAML-recipes

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3230]
With [fail](https://deployer.org/docs/7.x/api#fail) one can specify which task should run on failure of a specific task, e.g.
https://github.com/deployphp/deployer/blob/ff3c33c0a47723378a5af4ee615f3466018dec93/recipe/common.php#L167-L169

When using the `deploy`-task there is already a fail-task defined `deploy:failed`, but when creating own tasks in YAML there is currently no way to execute something if a task failed. Therefore it would be good to have the `fail`-function also available in YAML.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3230">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3230/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3230/pledge.svg">
</picture>
</a>

**Comment by ulrichmathes** [comment]
Isn't it just simply 

```yaml
after:
    deploy:failed: deploy:unlock
```

**Comment by alexgit2k** [comment]
> Isn't it just simply
> 
> ```yaml
> after:
>     deploy:failed: deploy:unlock
> ```
> 
> untested - maybe `before` should be used 🤔

As said: When using the deploy-task there is already a fail-task defined deploy:failed, but when **creating own tasks in YAML** there is currently no way to execute something if a task failed.
