### ISSUE TITLE
Support both strings “1” and “true”

### ISSUE THREAD

**Issue by lazka** [deployphp/deployer#3235]
5de0b05ed4e0b1b changed the check to check for `true` instead of `1`, which means https://consoledonottrack.com/ no longer works

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3235">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3235/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3235/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I see, I think it will be better to support both 1 and true. 

What do you think @antonmedv?
