### ISSUE TITLE
Laravel recipe - testing and docs

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#324]
The laravel recipe should be prepared to deploy a version 5 application by default.
Just like the symfony recipe, which can deploy a smyfony3 app even though it's yet to be released.

If everything is tested it should also be documented on the site: https://github.com/deployphp/deployer.org/issues/12

**Comment by elfet** [comment]
Is it related to #304?

**Comment by ZeeCoder** [comment]
It is, actually. :)

**Comment by ZeeCoder** [comment]
It is done, documentation should follow sometime in the future: https://github.com/deployphp/deployer.org/issues/17
