### ISSUE TITLE
Remove sudo on deploy

### ISSUE THREAD

**Issue by zajca** [deployphp/deployer#325]
Hi,
I want to switch my projects on symfony from capyfony to deployer, but I run to problem with sudo command thing is on server there is no way that sudo will be available for deploy user, it's just not an option.

So when deployer setting permissions ``` sudo setfacl -R -m u:"www-data":rwX -m u:`whoami`:rwX app/cache app/logs ```

I get error because sudo can't be used, but this command is working perfectly fine on normal user, so why it's used? Can it be sudo forced off? During capyfony build there is no need for sudo.

**Comment by ZeeCoder** [comment]
Does the user you're ssh-ing in is also associated with the web server?
If so, there's no need for you to set up the permissions, and you can remove that task from your deployment process safely.

If it's not the case, then please share how did you set up permissions with Capifony, so that we may help.

**Comment by zajca** [comment]
Well I'm stupid. I just copy ```deploy:writable``` task and change $sudo variable to '' and it's work like charm. Sorry for this.

**Comment by ZeeCoder** [comment]
No problem

**Comment by kenjis** [comment]
It is configurable: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L15

Add below to your `deploy.php`
```
set('writable_use_sudo', false);
```

**Comment by ZeeCoder** [comment]
I think this is not documented on the site, am I wrong about this?

**Comment by kenjis** [comment]
You're right. It is missing.

**Comment by ZeeCoder** [comment]
Opened up an issue about this: https://github.com/deployphp/deployer.org/issues/16

**Comment by barryvdh** [comment]
Isn't the non-sudo behavior easier to understand? I always get errors about this..
