### ISSUE TITLE
Links still to deployer.phar instead of dep

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3257]
The changelog of https://github.com/deployphp/deployer/releases/tag/v7.0.0-rc.9 says:
> Phar renamed back to `dep `from `deployer.phar` + source code also available now.

However, assets since rc.9 and download-page still link use `deployer.phar`:
- https://github.com/deployphp/deployer/releases/tag/v7.0.0
- https://github.com/deployphp/deployer/releases/tag/v7.0.0-rc.9
- https://deployer.org/download

**Comment by antonmedv** [comment]
Dep only in composer package.
