### ISSUE TITLE
set a task to be exectued in multiple stages (select) 

### ISSUE THREAD

**Issue by danielzzz** [deployphp/deployer#3264]
- Deployer version: 7.0.0
- Deployment OS: ubuntu

hi, I am trying to migrate to 7.0.0 and in my file I have

```
->onRoles(['prod', 'dev'])
```

I've seen this is now set with labels:
```
->set('labels', ['stage'=>'dev'])
```

but how can I configure a task to be executed on multiple selected stages?

I tried different configuration of select():

```
->select('stage=prod', 'stage=dev', 'stage=demo')
or
task(....)
->select('stage=porod')
->select('stage=dev')
```

but I cannot get it to work...
thanks in advance, best
dan

**Comment by mautz-et-tong** [comment]
I have something like:
```
on(select('stage=develop,staging,release'), function ($host) {
    before('before:task', 'do:task');
});
```
This works for develop and staging so far^^

**Comment by antonmedv** [comment]
Will try to find some time to write a better doc about select and labels.

**Comment by danielzzz** [comment]
thanks @mautz-et-tong ! it helped!

**Comment by mautz-et-tong** [comment]
You're welcome, but I figure out that it is useless. `on(select('stage=develop,staging,release')` triggers every time even on 'stage' =>'prod'

**Comment by danielzzz** [comment]
is it? it works for me:
![image](https://user-images.githubusercontent.com/351916/186150144-696d7743-f0c7-443c-8a8f-3344d52aad3c.png)

```
task('demo', function () {
    writeln('demo task');
})->select('stage=demo');

task('test', function () {
    writeln('dev task');
})
->select('stage=dev,demo');
after('test', 'demo');

```

this might be related to this other issue when tasks are shown on the list (though not really executed) if select renders false.
https://github.com/deployphp/deployer/issues/3263

**Comment by antonmedv** [comment]
I think one aspect of how select works is misleading. 

If select contains host alias name, it will also be selected:

    select('stage=dev,demo');
    
Same as stage=dev and alias=demo.

**Comment by antonmedv** [comment]
Added documentation https://deployer.org/docs/7.x/selector
