### ISSUE TITLE
Upgrade from 6 to 7 -> Lack of documentation on common actions

### ISSUE THREAD

**Issue by tomvo** [deployphp/deployer#3283]
We're upgrading from 6 to 7 and running into quite a bit of things regarding changing the way the deploy works. Our deploy script is rather complex involving quite a lot of stages and hosts. 

The one thing at the moment I can not figure out is how to replace `onHosts`. There is no written doc on this. I want to limit my tasks to run on specific hosts only. And optionally for specific stages only.

For clarity, in our case, a host can have multiple stages and a stage can exist on multiple hosts.

**Comment by antonmedv** [comment]
Done! Added documentation https://deployer.org/docs/7.x/selector

**Comment by tomvo** [comment]
thanks @antonmedv !
