### ISSUE TITLE
Use sudo on cleanup

### ISSUE THREAD

**Issue by leandrogehlen** [deployphp/deployer#329]
When lost connection during deploy, and i repeat deploy routine then the following errors occurs:

```sh
 rm: cannot remove /usr/share/nginx/html/yii2-comercial/releases/2015060410

 0406/web/assets/7e1698fe/addon/fold/markdown-fold.js: Permission denied

 rm: cannot remove /usr/share/nginx/html/yii2-comercial/releases/2015060410

 0406/web/assets/7e1698fe/addon/fold/brace-fold.js: Permission denied
...
```

i think necessary to create the param `set('cleanup_use_sudo', true)`; 

i can make this PR.

**Comment by elfet** [comment]
If you deploy with same user, no problem will be.

**Comment by ZeeCoder** [comment]
Hmm, I don't quite get this one either, what happened exactly?
Tell us more detail about the server, and how you configured Deployer.

**Comment by leandrogehlen** [comment]
My server is `Debian GNU/Linux 8.0 (jessie)` and my deploy script is:

```php
require 'recipe/composer.php';

set('repository', 'git@github.com:mycompany/yii2-myrepos.git');

server('main', myserver.com.br')
    ->env('deploy_path', '/usr/share/nginx/html/yii2-myrepos')
    ->env('branch', '1.1.x')
    ->stage('prod')
    ->user('admin')
    ->pemFile('~/.ssh/key.pem');
 ```
This occurs when `rm` command does not was executed completely on `cleanup` task.
If use `sudo` the problem is solved

**Comment by ZhukV** [comment]
Use sudo for this operation is risky ;)
You should correct configure permissions on you server.

**Comment by leandrogehlen** [comment]
@ZhukV  The permissions are right, how i said, this occurrs when `rm` command fail

**Comment by ZhukV** [comment]
Imho, The error **Permission denied** indicate of fail access...

**Comment by leandrogehlen** [comment]
I believe there are no permission bigger than  chmod 777, and i used this (for test)
how i said, if occurs **ONLY** `rm` command fails and i try repeat deploy routine

**Comment by leandrogehlen** [comment]
I found the problem.
Who creates the `releases` folder is `admin` but who creates the `assets/*` is `www-data`.
This occurs because the application (yii2 framework) creates this folder,but  on demand.

**Comment by elfet** [comment]
You need set correct permissions. Try to install `setfacl` and do deploy again.

**Comment by leandrogehlen** [comment]
It will not work, because the subfolders into `assets` are created when a request page is executed

**Comment by ZhukV** [comment]
@elfet :+1: 

As solution (Apache): Create a group developer and add deployer user and apache user to this group.
As solution (Nginx + PHP-FPM): correct configure user for run phpfpm. It should equals for deployment user.

**Comment by leandrogehlen** [comment]
I think, that, permission configuration, is relevant to server administrator.
He should which permissions, will be used.

**Comment by leandrogehlen** [comment]
This issue was closed but th PR continues opned. What was the decision?

**Comment by elfet** [comment]
Can you say which PR? :)

**Comment by leandrogehlen** [comment]
PR #329

**Comment by leandrogehlen** [comment]
Please what was the decision?

**Comment by elfet** [comment]
Can you put your users in same group? I think this is problem?

**Comment by leandrogehlen** [comment]
Yes but i made pr #330 and it continues opened
