### ISSUE TITLE
add httpie options to fetch function

### ISSUE THREAD

**Issue by tombroucke** [deployphp/deployer#3292]
I have run into a timeout with fetch() a couple of times. Is it possible to add an options argument to the fetch() function? This would forward the options to the HTTPIE::setopt() method

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3292">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3292/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3292/pledge.svg">
</picture>
</a>

**Comment by boydbloemsma** [comment]
Can I pick this up?

**Comment by tombroucke** [comment]
I created a pull request: https://github.com/deployphp/deployer/pull/3719
