### ISSUE TITLE
Release name "xyz" already exists.

### ISSUE THREAD

**Issue by codekandis** [deployphp/deployer#3301]
- Deployer version: 7.0.2
- Deployment OS: Debian 11 x64 (bullseye)
- PHP: 8.1.9 (cli) (built: Aug 15 2022 09:47:52) (NTS)

In fact these are my tasks.

```php
task(
	'deploy',
	[
		'deploy:info',
		'deploy:prepare',
		'deploy:release',
		'deploy:update_code',
		'deploy:shared',
		'deploy:writable',
		'deploy:vendors',
		'deploy:clear_paths',
		'deploy:symlink',
		'deploy:unlock',
		'deploy:cleanup',
		'deploy:success'
	]
);
after( 'deploy:failed', 'deploy:unlock' );
```

In Deployer 7.0.1 I had no issue to deploy. But in 7.0.2 I got the following output on `deploy:release`.

```bash
task deploy:release
[production-release] /usr/bin/php8.1 /path/to/deployer.phar worker --port 33911 --task deploy:release --host production-release --file /path/to/receipt.php --decorated -vvv
[production-release] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/ssh-user@example.com' 'ssh-user@example.com' ': c39e0a5747a0b8ab43ea; bash -ls'
[production-release] run cd /path/to/target/dir && (if [ -h release ]; then echo +correct; fi)
[production-release] +correct
[production-release] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/ssh-user@example.com' 'ssh-user@example.com' ': 6c8bfaab6818d06a86a2; bash -ls'
[production-release] run cd /path/to/target/dir && (rm release)
[production-release] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/ssh-user@example.com' 'ssh-user@example.com' ': 0f2d1bbe6e91e72ee679; bash -ls'
[production-release] run cd /path/to/target/dir && (if [ -d releases/8 ]; then echo +correct; fi)
[production-release] +correct
[production-release] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/ssh-user@example.com' 'ssh-user@example.com' ': fb6cd6175b175aea4d11; bash -ls'
[production-release] run cd /path/to/target/dir && (if [ -d releases/8 ]; then echo +indeed; fi)
[production-release] +indeed
[production-release] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/ssh-user@example.com' 'ssh-user@example.com' ': c7c1e6ca57ba0b9f21c8; bash -ls'
[production-release] run cd /path/to/target/dir && (if [ -d releases/9 ]; then echo +right; fi)
[production-release]  Deployer\Exception\Exception  in release.php on line 115:
[production-release]
[production-release]   Release name "8" already exists.
[production-release]   Release name can be overridden via:
[production-release]   dep deploy -o release_name=9
[production-release]
[production-release] #0 [internal function]: Deployer\Importer\Importer::Deployer\{closure}()
[production-release] #1 phar:///path/to/deployer.phar/src/Task/Task.php(90): call_user_func(Object(Closure))
[production-release] #2 phar:///path/to/deployer.phar/src/Executor/Worker.php(38): Deployer\Task\Task->run(Object(Deployer\Task\Context))
[production-release] #3 phar:///path/to/deployer.phar/src/Command/WorkerCommand.php(52): Deployer\Executor\Worker->execute(Object(Deployer\Task\Task), Object(Deployer\Host\Host))
[production-release] #4 phar:///path/to/deployer.phar/vendor/symfony/console/Command/Command.php(298): Deployer\Command\WorkerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[production-release] #5 phar:///path/to/deployer.phar/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[production-release] #6 phar:///path/to/deployer.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Command\WorkerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[production-release] #7 phar:///path/to/deployer.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[production-release] #8 phar:///path/to/deployer.phar/src/Deployer.php(317): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[production-release] #9 phar:///path/to/deployer.phar/bin/dep(96): Deployer\Deployer::run('7.0.2', '/path/to...')
[production-release] #10 /path/to/deployer.phar(4): require('phar:///path/to...')
[production-release] #11 {main}
```

My guess: It came with 7.0.2 change `Keeps release folder after unsuccessful deploy.` There's some hazzle with the release folder determination.

**Comment by antonmedv** [comment]
I see. This is already a second report of this problem. https://github.com/deployphp/deployer/discussions/3298

So bug it is. Any volunteers to find it?)

**Comment by codekandis** [comment]
Maybe I can find it. I'll give it a try.

**Comment by Konafets** [comment]
The change responsible for the error might be in recipe/deploy/release.php:
https://github.com/deployphp/deployer/compare/v7.0.1...v7.0.2#diff-eed081aa2ab90dc717255f0ff86e507b9881ec754141dd4ef6762f140ba2fef4R106-R115

**Comment by codekandis** [comment]
Wht is the reason to use shell commands to test for e. g. existing symlinks or directories? Why do not use is_link() or is_dir()?

**Comment by antonmedv** [comment]
Because it’s executed on a host. Not locally.

**Comment by codekandis** [comment]
Ah yes, indeed. I forgot every command is executed via SSH.

**Comment by codekandis** [comment]
I did some digging first ...

- I migrated recently from deployer 6.x to 7.x ...
- I don't use deployer per project via composer but via shell execution as an installed script in my OS environment.
- In 7.1.x I ended up with the following task list

```php
task(
	'deploy',
	[
		'deploy:info',
		'deploy:prepare',
		'deploy:release',
		'deploy:update_code',
		'deploy:shared',
		'deploy:writable',
		'deploy:vendors',
		'deploy:clear_paths',
		'deploy:symlink',
		'deploy:unlock',
		'deploy:cleanup',
		'deploy:success'
	]
);
after( 'deploy:failed', 'deploy:unlock' );
```

This list mostly remained from the 6.x task list.

After my digging around I discovered `deploy:prepare` already executes some of the tasks in my list. This leads to redundancy and in fact to an existing release directory and in the end with the exception thrown as mentioned.

https://github.com/deployphp/deployer/blob/99a57a9035cfe0eeae5dba5befe5411ac0f3ac72/recipe/common.php#L137-L145

In fact the resolved list of my tasks would look like

```php
task(
	'deploy',
	[
		'deploy:info',
		'deploy:info',
		'deploy:setup',
		'deploy:lock',
		'deploy:release',
		'deploy:update_code',
		'deploy:shared',
		'deploy:writable',
		'deploy:release',
		'deploy:update_code',
		'deploy:shared',
		'deploy:writable',
		'deploy:vendors',
		'deploy:clear_paths',
		'deploy:symlink',
		'deploy:unlock',
		'deploy:cleanup',
		'deploy:success'
	]
);
after( 'deploy:failed', 'deploy:unlock' );
```

While I was migrating I didn't find any documentation about the existing tasks. I'd recommend to add a list of which tasks already exist with a description of what these tasks exactly do or what lists of tasks they combine (mark them as aliases).

So after my rea I now ended up with my tasks as follows

```php
task(
	'deploy',
	[
		'deploy:info',
		'deploy:setup',
		'deploy:lock',
		'deploy:release',
		'deploy:release',
		'deploy:update_code',
		'deploy:shared',
		'deploy:writable',
		'deploy:vendors',
		'deploy:clear_paths',
		'deploy:symlink',
		'deploy:unlock',
		'deploy:cleanup',
		'deploy:success'
	]
);
after( 'deploy:failed', 'deploy:unlock' );
```

Short and sweet:

In my case the exception thrown is a result of a non-obvious task redundancy due to migrating from deployer 6.x to deployer 7.1.x and 7.2.x.

**Comment by antonmedv** [comment]
So the problem is with:


		'deploy:prepare',
		'deploy:release',

Remove second deploy:release task.

**Comment by codekandis** [comment]
No, I won't. Because the task `deploy:prepare` isn't obvious as an alias of a group of tasks. AND it's not documented as far as I discovered due to my research in your official documentation.

To remove `deploy:prepare` and to insert `deploy:setup` and `deploy:lock` instead makes it more obvious to me which specific tasks will be executed in a line. And I'll check all the other tasks for a similar grouping.

**Comment by antonmedv** [comment]
From https://deployer.org/docs/7.x/cli#tree-command:
```
$ dep tree deploy
The task-tree for deploy:
└── deploy
    ├── deploy:prepare
    │   ├── deploy:info
    │   ├── deploy:setup
    │   ├── deploy:lock
    │   ├── deploy:release
    │   ├── deploy:update_code
    │   ├── build  // after deploy:update_code
    │   ├── deploy:shared
    │   └── deploy:writable
    ├── deploy:vendors
    ├── artisan:storage:link
    ├── artisan:config:cache
    ├── artisan:route:cache
    ├── artisan:view:cache
    ├── artisan:migrate
    └── deploy:publish
        ├── deploy:symlink
        ├── deploy:unlock
        ├── deploy:cleanup
        └── deploy:success
```

And from https://deployer.org/docs/7.x/recipe/common#deployprepare:


> ### deploy:prepare
> This task is group task which contains next tasks:
> [deploy:info](https://deployer.org/docs/7.x/recipe/deploy/info#deployinfo)
> [deploy:setup](https://deployer.org/docs/7.x/recipe/deploy/setup#deploysetup)
> [deploy:lock](https://deployer.org/docs/7.x/recipe/deploy/lock#deploylock)
> [deploy:release](https://deployer.org/docs/7.x/recipe/deploy/release#deployrelease)
> [deploy:update_code](https://deployer.org/docs/7.x/recipe/deploy/update_code#deployupdate_code)
> [deploy:shared](https://deployer.org/docs/7.x/recipe/deploy/shared#deployshared)
> [deploy:writable](https://deployer.org/docs/7.x/recipe/deploy/writable#deploywritable)

**Comment by codekandis** [comment]
Thank you very much.
