### ISSUE TITLE
Postgres can't be re-provisioned or skipped

### ISSUE THREAD

**Issue by wojciechczerniak** [deployphp/deployer#3320]
So far all provisioning recipes were able to skip provisioning if detected that they're already up to date. But not Postgres database. Once a user was created, it will fail and exit whole process.

```bash
root@vps:~# sudo -u postgres createuser deployer
could not change directory to "/root": Permission denied
createuser: error: creation of new role failed: ERROR:  role "deployer" already exists
```

IMO it would be useful having ability to re-run provisioning if for some reason it failed or I want to add more services to the server. I have to either fix it manually now or destroy the VPS to start from scratch.

- Deployer version: 7.0.2
- Deployment OS: Ubuntu 20 LTS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3320">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3320/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3320/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Sure. Also it will super cool to add test with reprovisoning.
