### ISSUE TITLE
Caddy provisioning will fail if gpg keyring file exists

### ISSUE THREAD

**Issue by wojciechczerniak** [deployphp/deployer#3321]
This line will fail:

https://github.com/deployphp/deployer/blob/6d759ef372af18c2a8ec48d4bf5282aee0133b64/recipe/provision.php#L87

if `/usr/share/keyrings/caddy-stable-archive-keyring.gpg` file exists. Remove it or skip this step when file is already there.

- Deployer version: 7.0.2
- Deployment OS: Ubuntu 20 LTS

**Comment by thomasnavarro** [comment]
I added these flags to the gpg command `--batch --yes`, it works since 😉

**Comment by antonmedv** [comment]
What about sending a PR?
