### ISSUE TITLE
Wrong version available to download through https://deployer.org/deployer.phar

### ISSUE THREAD

**Issue by llaville** [deployphp/deployer#3329]
While it was working with other previous versions 6.x, 5.x, ... The https://deployer.org/deployer.phar URL did not download anymore the most latest version.

Expected 7.0.2
Current 6.8.0

**Comment by antonmedv** [comment]
This is kinda by “design”. A lot of CIs expect it to be latest 6. I’ll add separate url for v7.

**Comment by llaville** [comment]
@antonmedv In this case we should got version 6.9.0 and not 6.8.0

**Comment by sandermarechal** [comment]
@antonmedv What is the separate v7 URL? The documentation does not list it. I do not want to install deployer as a dependency in my project. Deployer should execute composer, not the other way around IMHO.

**Comment by sandermarechal** [comment]
I found this link: https://github.com/deployphp/deployer/releases/latest/download/deployer.phar

Problem is that when deployer 8.x is released, that link will point to that new version. @antonmedv what is the stable v7 url that you said you added?

**Comment by DanielRuf** [comment]
I would be generally helpful, to mention the releases page for those, who need the phar files.

https://github.com/deployphp/deployer/releases/

See also https://github.com/deployphp/deployer/issues/2889#issuecomment-1893253843
