### ISSUE TITLE
After upgrading to 7.0: The "--parallel" option does not exist.

### ISSUE THREAD

**Issue by onokje** [deployphp/deployer#3331]
- Deployer version: 7.0.2
- Deployment OS: ubuntu

I upgraded from 6.8 to 7.0.2. I am using the --parallel option for several deployments. But after upgrading, those don't work anymore:

`The "--parallel" option does not exist.`

There is nothing in the upgrade document saying that this options is removed. How can i fix this?

**Comment by antonmedv** [comment]
Deployer v7 is parallel be default now. Will add it in update doc.

**Comment by onokje** [comment]
Awesome, thanks :)
