### ISSUE TITLE
Is {{release_path}} still the way to get the current release?

### ISSUE THREAD

**Issue by Azuka** [deployphp/deployer#3337]
- Deployer version: 7.0.2
- Deployment OS: OSX/Ubuntu (fails both locally and in ci)

```php
task('link:secrets', function () {
    run('ln -sfn ~/.secrets/.env {{release_path}}/system/.env.common');

    // Staging env
    if (in_array('staging', $stages)) {
        run('ln -sfn ~/.secrets/.env.staging {{release_path}}/system/.env');
    }
    // Production env
    if (in_array('production', $stages)) {
        run('ln -sfn ~/.secrets/.env.production {{release_path}}/system/.env');
    }

})->desc('Symlinks secret files.');

after('deploy:vendors', 'link:secrets');
```

I recently upgraded from deployer 6 to 7, and had a command that would symlink some env secrets for the current release, so that

- in the middle of a deploy to say, `releases/4`, this would symlink a file into `releases/4/.env`
- as a one-off, running `./vendor/bin/dep link:secrets stage=staging`, `{{release_path}}` would return the current release and link to it as well.

In both cases, I get the error: 

```
The "release_path" ({{deploy_path}}/release) does not exist.
```

What's the currently supported method to get the path to the working release? `{{release_name}}` for the second case returns `5` if the current release is `4`.

As of this writing, the implementation of `release_name` is:

```php
// The name of the release.
set('release_name', function () {
    return within('{{deploy_path}}', function () {
        $latest = run('cat .dep/latest_release || echo 0');
        return strval(intval($latest) + 1);
    });
});
```

I would prefer not to hack the internals in case something changes in future.

**Comment by antonmedv** [comment]
After `deploy:release` task is executed (deploy process) you can use [release_path](https://deployer.org/docs/7.x/recipe/deploy/release#release_path).

The `release_path` should point to `{{deploy_path}}/release` symlink. 

But Deployer also has a special param [release_or_current_path](https://deployer.org/docs/7.x/recipe/deploy/release#release_or_current_path).

The `release_or_current_path` can be used during deployment and as in one-off tasks. During deeply `release_or_current_path` points to `release` symlink. Otherwise to `current` symlink.

**Comment by Azuka** [comment]
Thanks for the quick reply. I'd really like to symlink secrets before completing the release so I don't catch clients trying to access the site during a release.

Another question: is there any way to detect if I'm in the middle of a release or not, assuming {{release_or_current_path}} doesn't work?

**Comment by antonmedv** [comment]
Easiest was to check if release exists is:

```php
$releaseExists = test('[ -h {{deploy_path}}/release ]');
```

**Comment by Azuka** [comment]
> The `release_or_current_path` can be used during deployment and as in one-off tasks. During deeply `release_or_current_path` points to `release` symlink. Otherwise to `current` symlink.

I just realized that means I can `readlink {{release_or_current_path}}`. I'll combine that with everything else and get it working.
