### ISSUE TITLE
og:image of the website

### ISSUE THREAD

**Issue by staabm** [deployphp/deployer#3339]
the og:image of the website has ~1.85MB filesize, which gets transferred on every mention in twitter/slack or any other tool which reads this image.

this image should have a smaller filesize.. its a waste of bandwidth and really bad for UX, seeing this image loading on a not-so-fast connection

https://deployer.org/img/ogimage@2x.png

![grafik](https://user-images.githubusercontent.com/120441/194822571-ff0622f8-46ac-408e-be99-7b89d259e237.png)

**Comment by Schrank** [comment]
@antonmedv I found a recommendation for 1200x600 this one is 1260 × 630:
![ogimage@2x](https://user-images.githubusercontent.com/379680/194827074-3d12112b-4477-42c4-b7ba-8837a5d469ee.jpg)

**Comment by antonmedv** [comment]
Ok, will rework og)

**Comment by antonmedv** [comment]
Fixed 
![38082166-554B-4387-A4EA-16CF6254B8A0](https://user-images.githubusercontent.com/141232/211356677-01210347-c854-447f-b61d-7f880f6fc5d5.jpeg)

**Comment by staabm** [comment]
thanks!
