### ISSUE TITLE
Call to undefined function Deployer\import() 

### ISSUE THREAD

**Issue by chrisc0** [deployphp/deployer#3345]
- Deployer version: 6.9.0
- Deployment OS: Ubuntu 22.04

I have this section in my deploy.php file:

// Hosts
set('http_user', 'www-data');
set('writable_use_sudo', true);
import('deployer-hosts.yaml');

However, when I try to run anything with deployer, I get this error message: 
                                                                                                                        
 [Error] Call to undefined function Deployer\import()                                                                   

 #0 phar:///usr/local/bin/deployer/src/Deployer.php(388): require()                                                     
 #1 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #2 phar:///usr/local/bin/deployer/src/Deployer.php(396): call_user_func()                                              
 #3 phar:///usr/local/bin/deployer/src/Deployer.php(322): Deployer\Deployer::loadRecipe()                               
 #4 phar:///usr/local/bin/deployer/bin/dep(136): Deployer\Deployer::run()                                               
 #5 /usr/local/bin/deployer(4): require('...')                                                                          
 #6 {main}                                                                                                              

Any ideas?

**Comment by Schrank** [comment]
Do you `require common.php`?

**Comment by Schrank** [comment]
But in theory should deployer.phar require the functions.php via composer.json and autoloader 🤔

**Comment by chrisc0** [comment]
I do this near the top "require 'recipe/yii.php';" but not "common.php".   Do I need to do that to?  It worked fine under deployer v5.  I install deployer globally, not with composer.

**Comment by chrisc0** [comment]
Never mind.  My fault.  I got my versions confused and had downloaded the wrong one.
