### ISSUE TITLE
Magento 2 shared file pub/index.php not working as expected

### ISSUE THREAD

**Issue by Aquive** [deployphp/deployer#3354]
- Deployer version: 7.0.2
- Deployment OS: debian

I added `pub/index.php` as a shared file among others. All others do work excecpt for this one. When I check it while the deploy is going on, I see the symlink is created, but when deploy is finished it is gone. Why is this? And how can I fix it?

```
namespace Deployer;

require_once 'recipe/magento2.php';

// Config

set('repository', 'repo.url');
set('static_content_locales', 'en_US nl_NL de_DE');
set('magento_themes', ['Client/default', 'Magento/luma', 'Magento/backend']);
add('shared_files', [
    '.htaccess',
    'app/etc/env.php',
    'pub/.htaccess',
    'pub/index.php'
]);
add('shared_dirs',[]);
add('writable_dirs', []);

// Hosts

// Staging server
host('staging url')
    ->set('labels', ['stage' => 'staging'])
    ->set('http_user', 'client')
    ->set('remote_user', 'client')
    ->set('port', '22')
    ->set('deploy_path', '/usr/www');

// Tasks

task('build', function () {
    cd('{{release_path}}');
});

after('deploy:failed', 'deploy:unlock');
```

**Comment by Aquive** [comment]
@antonmedv any ideas?

**Comment by peterjaap** [comment]
@Aquive why would you add `pub/index.php` to the shared files? That file is automatically copied from vendor to that location by composer becauase of the mapping in `magento/magento2-base` (see `vendor/magento/magento2-base/composer.json:488`).

**Comment by Aquive** [comment]
@peterjaap thanks for your answer! I guessed this was the problem already.

Yeah, I know. It's a weird one. Short answer: client insist on it. He wants to be able to put storeview specific things (like magerun code based on domains) in it. It is set up this way. Although moving it to its appropriate place would be better.

Would it be even possible? If not, we have to change the setup, so it adheres best practices.

**Comment by Aquive** [comment]
@peterjaap Don't tell me you didn't come across weird setups ;)

The problem is that it should symlink to the pub/index.php in the shared folder. But I could use the same tactic for it right? `rm pub/index.php && ln -s ../../shared/pub/index.php pub/index.php` from the top of my head.

Thanks for the tip.

**Comment by peterjaap** [comment]
@Aquive I have, that's why I know these tricks :rofl: 

But yes, same tactic, different command :)
