### ISSUE TITLE
Docker compose as deployment target (recipie)

### ISSUE THREAD

**Issue by acirulis** [deployphp/deployer#3362]
Hello,

I have a Symfony app which runs inside Docker containers on remote VPS with docker-compose script. I am currently going through Symfony recipe, and it seems that everything can be re-rewritten to support containers. For example, `set('bin/php', 'docker exec container_name php');` , etc. Other approach would be to forward SSH port and let deployer do its work directly inside container(s). 

Are there future plans for official container support? If not, which approach you would recommend following? I am also wondering if it would be possible to setup truly empty VPS, without docker containers already running.

Thanks!

**Comment by bgmastermind** [comment]
I've just attempted something similar, but with laravel. The port forwarding option for container ssh should be a working solution, but I did not want to go that way.  I couldn't get it working with the first option. Tried with bash -c , tried with exec -t tried creating custom task that executes before deploy, but it just hangs after connecting to the container. 
So a good reliable solution for containers would be great.

**Comment by antonmedv** [comment]
Well, i think this is beyond scope of deployer for now.

**Comment by Bilge** [comment]
If this isn't in scope, Deployer is waiting to die.

**Comment by antonmedv** [comment]
I’m working on a new recipe for docker-compose right now. Will be in future versions of Deployer.

**Comment by Bilge** [comment]
Will be interesting to see what you come up with. In the meantime, perhaps this issue should be reopened until you're done?

**Comment by jeykodev** [comment]
@antonmedv Do you have a rough schedule for us?

**Comment by antonmedv** [comment]
@jeykodev can't tell right now.
