### ISSUE TITLE
Array of tasks in after/before are reversed

### ISSUE THREAD

**Issue by erropix** [deployphp/deployer#3365]
I am not sure what the reason the tasks list is reversed on before/after hooks:

https://github.com/deployphp/deployer/blob/bc708bec860b50be558840adb5c6db3c733d369e/src/Importer/Importer.php#L239-L250

This makes no sense as we have to write the tasks in the opposite order of their execution.

**Comment by antonmedv** [comment]
Don’t remember) we can remove it. I guess.

**Comment by erropix** [comment]
I just found out it was added in v7 1d137ad0 but the commit description doesn't mention anything about the tasks bein reversed and this behavior is not documented either

**Comment by erropix** [comment]
@antonmedv any update on this?

**Comment by hwmaier** [comment]
I found this behaviour unexpected and a bit confusing. At least it should be documented, but I believe even better the order should be changed to what most people would expect top of the list first, bottom last.

**Comment by Schrank** [comment]
At you all: Feel free to provide a PR yourself, especially for so easy tasks like this.

Now 🤞 the CI is green :-)

**Comment by erropix** [comment]
@antonmedv I guess the YAML array order for me is different than what's shown in https://github.com/deployphp/deployer/issues/3431

Any idea what may cause this strange order difference?

**Comment by SimJoSt** [comment]
I can confirm, that the order is still an issue for me as well.
As a breaking change, it would probably need to go into a major release.

@antonmedv can you reopen this issue, so we can track this?
