### ISSUE TITLE
`deb completion` no supported shells

### ISSUE THREAD

**Issue by tom-knight** [deployphp/deployer#3366]
I have installed Deployer using the [installation instructions](https://deployer.org/docs/7.x/installation) to an existing Laravel project.

```
composer require --dev deployer/deployer
./vendor/bin/dep init
```

If I try to generate the bash completion file I get the following error:

```
./vendor/bin/dep completion bash
Detected shell "bash", which is not supported by Symfony shell completion (supported shells: "").
```

Looking at the [Symfony code](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Console/Command/DumpCompletionCommand.php) it's looking for 

```
__DIR__.'/../Resources/completion.*'
```

as the supported shells but can't find that.

I've tried running `dep` from different directories, with and without an alias but always with the same results.

The `completion.bash` file does exist:

```
$ ls vendor/symfony/console/Resources/completion.bash 
vendor/symfony/console/Resources/completion.bash
```

Also `artisan completion` does work as expected.

**Comment by brianfreytag** [comment]
I'm also having this issue. Is this an issue in Symfony or Deployer?

**Comment by antonmedv** [comment]
Is those files in phar as well? Maybe our build process is wrong?

**Comment by antonmedv** [comment]
What about 8

**Comment by kick-the-bucket** [comment]
`deployer.phar` in [v8.0.0-alpha.1](https://github.com/deployphp/deployer/releases/tag/v8.0.0-alpha.1) has the completion files inside it
