### ISSUE TITLE
Disable branch selection for host

### ISSUE THREAD

**Issue by jiexaspb** [deployphp/deployer#3370]
I have two hosts configured, one for production and one for testing:

```
host('test.mysite.com')
    ->set('remote_user', 'test')
    ->set('deploy_path', '/var/sites/test.mysite.com');

host('mysite.com')
    ->set('remote_user', 'production')
    ->set('deploy_path', '/var/sites/mysite.com');
```

When I need to deploy another branch to the test branch, I do this

dep deploy --branch newfeature

But I need to forbid choosing a branch for production, so as not to accidentally send test code there
How can I do that?

**Comment by antonmedv** [comment]
Set branch on prod to master.

**Comment by antonmedv** [comment]
host('test.mysite.com')
    ->set('remote_user', 'master')
