### ISSUE TITLE
Laravel recipe `artisan:migrate` task does not honor `default_timeout = null`

### ISSUE THREAD

**Issue by calebdw** [deployphp/deployer#3371]
- Deployer version: 7.0.2
- Deployment OS: Ubuntu 20

<details> 

<summary>deploy.php</summary>

```php
<?php

namespace Deployer;

require 'recipe/laravel.php';

set('default_timeout', null); // because of long-running migrations
set('shared_dirs', [
    'storage',
    'uploads',
]);

host('<host>')
    ->setLabels([
        'stage' => 'staging',
    ])
    ->setRemoteUser('<user>')
    ->setDeployPath('<path>');

task('deploy', [
    'deploy:prepare',
    'artisan:storage:link',
    'artisan:optimize:clear', // clear all caches
    'artisan:config:cache',
    'artisan:route:cache',
    'artisan:view:cache',
    'artisan:event:cache',
    'artisan:down',
    'artisan:migrate',
    'deploy:symlink',
    'artisan:up',
    'artisan:horizon:terminate',
    'deploy:unlock',
    'deploy:cleanup',
    'deploy:success',
]);

after('deploy:failed', 'deploy:unlock');
```

</details>

Hello, I recently upgraded to Deployer 7 and I just encountered a long-running migration that caused the deploy to fail after 300 seconds, despite `default_timeout` being set to `null`.

 This used to work in Deployer 6 so not too sure what's going on...

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3371">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3371/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3371/pledge.svg">
</picture>
</a>

**Comment by CalebDW** [comment]
Update:

Everything appears to be working correctly when `default_timeout` is set on the host level, not sure if this is the intended behaviour or not but it's not reflected in the docs from what I could tell...

The below code works:
```php
// ...
set('default_timeout', null); // does NOT work
set('shared_dirs', [
    'storage',
    'uploads',
]);

host('<host>')
    ->set('default_timeout', null); // works
    ->setLabels([
        'stage' => 'staging',
    ])
    ->setRemoteUser('<user>')
    ->setDeployPath('<path>');

// ...
```

**Comment by hashimaziz1** [comment]
How was this completed, as I've been getting a broken pipe for the last day or so for a long-running migration (large CSV file). How can I rule this out? `default_timeout` config option is set to 6000 but I get a `client_loop: send disconnect: Broken pipe` error after about 5 minutes of migrating, and the changing SSH/server configs doesn't seem to make a difference.
