### ISSUE TITLE
Symbolic link problems

### ISSUE THREAD

**Issue by kevinall05** [deployphp/deployer#3372]
- Deployer version: Deployer 7.0.2
- Deployment OS: Windows

Hi everyone,
I got a problem my tests of deployment.
At the release task, when Deployer want to make symbolic links, it stops and it says "ln: failed to create symbolic link 'essais/release': No such file or directory" and I don't understand why. In my releases, there is nothing in the folders that it creates at each deploy, is it possible that the problem came from there?

Thanks for your response

-----

require 'recipe/common.php';

set('repository', 'git@github.com:-------');
set('branch', 'main');

set('ssh_multiplexing', false);
set('keep_releases', 3);

add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

host('ip adress')
    ->set('remote_user', 'deployer')
    ->set('port', '2222')
    ->set('deploy_path', 'essais')
    ->set('release_path', 'release');

task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:clear_paths',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
    'deploy:symlink',
    'deploy:unlock',
    'deploy:cleanup',
]);

**Comment by patrickhoehn** [comment]
Hi @kevinall05, I have the same issue! I discovered that the symlinks do not point to the latest release anymore, tried deploy:symlink and got the same error. Did you manage to fix it?

**Comment by minkbear** [comment]
I have to face this problem with using mingw64 in windows server but readlink in https://github.com/deployphp/deployer/blob/0cf5d18591a87d265ba8c5ad6b18326049792b64/recipe/deploy/release.php#L61C22-L61C30 return empty.

**Comment by lartist** [comment]
Hi @patrickhoehn and @minkbear,

I managed to do it with the following code.

set(
    'bin/symlink',
    'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "{{deploy_path}}/symlink.ps1"'
);

This defines the correct way to create symlinks on windows. You should create a file (here symlink.ps1 in the deploy path) and add the following content.

/* ------- symlink.ps1 content

param(
    [string]$Target,
    [string]$Link
)

if (Test-Path $Link) {
    Remove-Item $Link -Force -Recurse
}

New-Item `
    -ItemType SymbolicLink `
-Path $Link `
    -Target $Target

---------------*/

It worked for me.
