### ISSUE TITLE
getting PHP version error, Still using COMPOSER_IGNORE_PLATFORM_REQS=1

### ISSUE THREAD

**Issue by dswtpvtltd** [deployphp/deployer#3398]
- Deployer version: 7
- Deployment OS: MacOs

I am using deployer for Mageto2 but I am getting php error. when I am trying to set ignore platform dependent php  version, still I am getting error. 
![Screenshot 2022-11-26 at 7 59 01 PM](https://user-images.githubusercontent.com/3082270/206225776-8280c3d8-dd80-4c4a-b611-c418c18fae6b.png)
![Screenshot 2022-11-26 at 7 58 21 PM](https://user-images.githubusercontent.com/3082270/206225858-2c891398-9d4c-4837-8e3b-2ffa35978f8e.png)
<img width="1150" alt="Screenshot 2022-12-07 at 9 20 51 PM" src="https://user-images.githubusercontent.com/3082270/206226274-efa0bd28-492f-4165-81ad-74abc0b955af.png">

      Please, provide a minimal reproducible example of deploy.php

**Comment by Schrank** [comment]
This looks like you are using PHP 8.1 but the Symfony version is not compatible with it? And your composer.json sets your PHP version to 7.0.3 and the modules expect at least 7.3 (while running 8.1)

**Comment by Schrank** [comment]
I guess removing the pinned version from your composer.json might fix your problem, but I don't know your environment, maybe you are running 7.0 on your production machine for some weird unreasonable reason (PHP 7.0 is out of support for years, insecure and shouldn't be used anymore ... but as always: know the rules before your break them, maybe it makes sense for you :-))
