### ISSUE TITLE
Problem with creating new argument / or option while calling dep deploy

### ISSUE THREAD

**Issue by kLkA** [deployphp/deployer#340]
Hi, I've looked into documentation code
```
argument('stage', InputArgument::OPTIONAL, 'Run tasks only on this server or group of servers.');
option('tag', null, InputOption::VALUE_OPTIONAL, 'Tag to deploy.');
```
tried insert 
```
option('migrate', null, InputOption::VALUE_OPTIONAL, 'descr');
```
into my deploy.php code and call
dep deploy --migrate=true
I've an exception about missing --migrate options
1) How to perform adding new option in console input?
2) How to access that option from deploy.php file?

**Comment by kenjis** [comment]
> I've an exception about missing --migrate options

What's your error message?

**Comment by kLkA** [comment]
Simple deployer's error about missing option, try to append --anyKey=test to your command and you'll see it

**Comment by kenjis** [comment]
I got the error:

~~~
$ php deployer.phar deploy --anyKey=test
                                         
  [RuntimeException]                     
  The "--anyKey" option does not exist.
~~~

But if I define option, I can't see it.

*deploy.php*
~~~php
<?php
require 'recipe/common.php';
option('migrate', null, Symfony\Component\Console\Input\InputOption::VALUE_OPTIONAL, 'descr');
task('test', function () {
    var_dump(input()->getOption('migrate'));
})->desc('Test.');
~~~

~~~
$ php deployer.phar test --migrate=xxx
  Executing task test
✔tring(3) "xxx"
~~~

**Comment by kLkA** [comment]
Thanks, that's why i asked a question how to properly perform it.
