### ISSUE TITLE
Symfony recipe with app-environment-file (wildcards) for shared files

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3414]
The Symfony recipe sets `.env.local` for `shared_files`: [recipe/symfony.php#L18-L20](https://github.com/deployphp/deployer/blob/master/recipe/symfony.php#L18-L20)
But Symfony also uses `.env.$APP_ENV.local` for uncommitted environment-specific overrides (see https://symfonycasts.com/screencast/symfony-fundamentals/environments#the-app-env-variable)

So actually it should be:
```
set('shared_files', [
    '.env.local',
    '.env.*.local',
]);
```
But wildcards are not supported for `shared_files`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3414">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3414/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3414/pledge.svg">
</picture>
</a>

**Comment by alexgit2k** [comment]
`glob( '.env.*.local' );` would return all files matching configuration-files (see https://www.php.net/manual/en/function.glob.php)

So in [recipe/deploy/shared.php](https://github.com/deployphp/deployer/blob/master/recipe/deploy/shared.php) `glob` could be used to expand wildcard patterns.

**Comment by Schrank** [comment]
Only if the file exists. Do you want to add them to git? Is this best practice?
If yes, you are right, then we can expand!

**Comment by alexgit2k** [comment]
I forgot that `glob` is not working at the remote host, so the wildcard-files have to be determined yet.
So instead of line 61 at [deploy/shared.php](https://github.com/deployphp/deployer/blob/master/recipe/deploy/shared.php#L61) the following should expand wildcards:

```php
    // Expand shared_files with wildcards
    $expanded_shared_files[] = [];
    foreach ($shared_files as $file) {
        if (str_contains($file, '*')) {
    	        $files = rtrim(run('cd {{release_path}} && ls $file'), PHP_EOL);
    	        $expanded_shared_files = array_merge( $expanded_shared_files, explode(PHP_EOL,$files) );
    	} else {
    		$expanded_shared_files[] = $file;
    	}
    }
    
    foreach ($expanded_shared_files as $file) {
```
