### ISSUE TITLE
Closure casted to array on nested structures for host->set()

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#3418]
- Deployer version: 7.0.2
- Deployment OS: Debian 11.3 

I observed that closure is casted to array on array nested structures but only on host/set().
For global/set() all is working as expected. 

Below a reproducible case. 

Testing deploy.php

```
<?php

namespace Deployer;

task('closure_test', function () {
    print_r(get('test_global'));
    print_r(get('test_local'));

});

set('test_global', [
        function () {
            return 'test value';
        }
    ]
);

host('host')
    ->set('test_local', [
            function () {
                return 'test value';
            }
        ]
    );
```
the command run
`dep closure_test`

the output is:

```
Array
(
    [0] => Closure Object
        (
        )

)
Array
(
    [0] => Array
        (
        )

)
```

but expected output would be:
```
Array
(
    [0] => Closure Object
        (
        )

)
Array
(
    [0] => Closure Object
        (
        )

)
```

**Comment by antonmedv** [comment]
Yes, the reason is what 
```php
host('host')
    ->set('test_local', [
            function () {
                return 'test value';
            }
        ]
    );
```
is done on worker and communicated to master process via HTTP request. 

So only serializable content can transfer (as JSON). I think we need to add some check (or documentation) about what kind of config can be added.  

Created a tracking issue at #3419
