### ISSUE TITLE
Overriding the shell of the localhost doesn't work

### ISSUE THREAD

**Issue by guvra** [deployphp/deployer#3423]
## Context

- Deployer version: 7.0.2
- Deployment OS: Alpine Linux

## Description

The function `runLocally` depends on bash to run the command.
Bash is not installed on Alpine Linux. 

I tried to override the default shell with the following code:

```php
localhost()
    ->setShell('sh -s');
```

But it doesn't work, the function `runLocally` still tries to use bash.

## Example

deploy.php example:

```php
<?php
namespace Deployer;

require 'recipe/common.php';

localhost()
    ->setShell('sh -s');

host('prod')
    ->setHostname('prod_hostname')
    ->setRemoteUser('myuser')
    ->setDeployPath('/var/www/html');

task('test:runLocally', function () {
    runLocally('echo test');
});
```

Command:

```
dep test:runLocally prod -v
```

Output:

```shell
task test:runLocally
[localhost] run echo test
[localhost] sh: bash: not found
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3423">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3423/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3423/pledge.svg">
</picture>
</a>

**Comment by guvra** [comment]
Additional note: using the 2nd arg of the `runLocally` function is not possible, because the core recipe of php deployer also uses this function, without specifying the argument.

**Comment by guvra** [comment]
> Should work to change the setting on host('prod') I guess

It only works if both the local and remote hosts use the same shell though.

I could install the `bash` package before deploying as a workaround.

**Comment by antonmedv** [comment]
I think we need some config to add. Maybe local_shell?
