### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#343]
Main feature to Deployer v3.1.0

**Comment by ZeeCoder** [comment]
Where will this be implemented exactly, and what will we store in it?

**Comment by elfet** [comment]
Creation of Deployer deps i think. Like StageStrategy and Server impl. All what as an interface i think.

Pimple?

**Comment by ZhukV** [comment]
Pimple :+1:

**Comment by ZeeCoder** [comment]
+1 for pimple.
Could we also store global configurations in pimple?
Is there a way to make a parameter protected?

**Comment by ZhukV** [comment]
In pimple we can not use parameters bag, and can not make protected services (parameters).

**Comment by ZeeCoder** [comment]
I think pretty much everything can be stored in pimple containers: https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php#L73

**Comment by gordalina** [comment]
+1 for Pimple, it's simple & straightforward. 
As far as I see it, there's no need for complex DI implementations (like Symfony's).

**Comment by AlexStansfield** [comment]
:+1: for pimple also.

Take a look at Cilex (https://github.com/Cilex/Cilex) if you like to see how pimple is combined well with Symfony console application.

**Comment by mavimo** [comment]
I already used some DIC for CLI projects, from my experience:

 * [Symfony DI](http://symfony.com/doc/current/components/dependency_injection/introduction.html) :+1: 
 * [Pimple](http://pimple.sensiolabs.org/) :-1: 

## Comparison

 * [Performance](http://www.sitepoint.com/php-dependency-injection-container-performance-benchmarks/)
 * [DI containers usage comparison](https://gist.github.com/mnapoli/6159681)

Pimple is faster (I'm not sure is critical issue here) but functionality are limited. On  Sf DI we can use YML config file to manage DI (and this should really useful on app maintenance and improvements).

**Comment by AlexStansfield** [comment]
@mavimo The performance article you link to isn't much use as Tom didn't actually review pimple as didn't realise you could use it as a DIC. He thought every instance it returned was the same which for V1.x is completely incorrect. For V2.x whilst that's what it does by default you can configure it to return you a new instance of your service each time you get it from the container.

If YML is important then there is a library for configuring Pimple with YML - https://github.com/gonzalo123/yml2pimple

**Comment by spotman** [comment]
Why not [PHP-DI](http://php-di.org/)?

**Comment by elfet** [comment]
Why?
