### ISSUE TITLE
Deployer 7.1 requires php >=8.1.0 when installed globally

### ISSUE THREAD

**Issue by onokje** [deployphp/deployer#3430]
- Deployer version:  7.1
- Deployment OS: alpine

I have this error in my pipeline when using the latest php deployer (I am installing globally):
`
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.16. in phar:///root/.composer/vendor/deployer/deployer/dep/vendor/composer/platform_check.php on line 24
`
It looks like there are some dependencies in composer.lock that require 8.1: `symfony/deprecation-contracts`, `symfony/string` and `symfony/service-contracts`. I am assuming this was not intentional? If it was, then It would be helpful to document it properly, and update the php version in composer.json to php 8.1.

**Comment by antonmedv** [comment]
Working on it.

**Comment by antonmedv** [comment]
Working on it.

**Comment by antonmedv** [comment]
Fixed.
