### ISSUE TITLE
Breaking before: order 

### ISSUE THREAD

**Issue by ulrichmathes** [deployphp/deployer#3431]
- Deployer version: 7.1.0
- Deployment OS: ubuntu

Before scripts where in order for deployer 7.0, with 7.1 the order get's reversed. This is a breaking change. None of the Changes in https://github.com/deployphp/deployer/releases/tag/v7.1.0 suggests that there is a change.

```
import:
  - recipe/common.php
  - contrib/rsync.php

before:
  deploy:update_code:
    - rsync:warmup
    - rsync

tasks:
  deploy:
    - deploy:prepare
    - deploy:publish
```

**Deployer 7.1**
```
vendor/bin/dep tree deploy
...
    │   ├── deploy:lock
    │   ├── deploy:release
    │   ├── rsync  // before deploy:update_code
    │   ├── rsync:warmup  // before deploy:update_code
    │   ├── deploy:update_code
    │   ├── deploy:shared
...
```

**Deployer 7.0.2**
```
vendor/bin/dep tree deploy
...
    │   ├── deploy:lock
    │   ├── deploy:release
    │   ├── rsync:warmup  // before deploy:update_code
    │   ├── rsync  // before deploy:update_code
    │   ├── deploy:update_code
    │   ├── deploy:shared
...
```

**Comment by antonmedv** [comment]
Fixed by https://github.com/deployphp/deployer/commit/a809e82459426b0b2a414f4f2707fd11ce856d84

Will release a new version.

**Comment by ulrichmathes** [comment]
Wow, that was a quick fix. Thank you so much.
