### ISSUE TITLE
v7.1.2 is not distributed as a phar

### ISSUE THREAD

**Issue by gjuric** [deployphp/deployer#3452]
- Deployer version: 7.1.2
- Deployment OS: n/a

v7.1.2 has a composer.json with a requires section and ``dep`` file missing from the root folder.

**Comment by antonmedv** [comment]
Looks like the release GitHub action is broken. Will try to do a couple of different releases to debug.

**Comment by antonmedv** [comment]
Should be fixed: https://github.com/deployphp/deployer/tree/v7.1.3

Don’t know what was the problem. Just recreating a new release fixed the issue.
