### ISSUE TITLE
Faster cloning by borrowing objects from existing clones

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#346]
Using git:
* "git clone --reference=<over there>" learned the "--dissociate"
   option to go with it; it borrows objects from the reference object
   store while cloning only to reduce network traffic and then
   dissociates the resulting clone from the reference by performing
   local copies of borrowed objects.

**Comment by johnny-bit** [comment]
Ooh!! I can do that! I did for my `local_common`! may I PR this? And can I use "git_cache" env for that?

**Comment by elfet** [comment]
Yes, sure. But it's better to detect git version and if git support it - use it.

**Comment by johnny-bit** [comment]
Hmmm... That *is* good idea... however there *are* some drawbacks to it... But OK, will add that to my `local_common` for check and then will pr `common` :)

**Comment by johnny-bit** [comment]
PR #352 fixes this :)

**Comment by johnny-bit** [comment]
So... #352 landed, then this issue can be closed, yes?
