### ISSUE TITLE
Release name "64" already exists.

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#3463]
- Deployer version: v7.1.3
- Deployment OS: Linux 4.4.0-19041-Microsoft

Without changing my deployment script, that has worked for years, deployment now, suddenly, fails every time with exactly the same error message outlined below.

```
Deployer\Exception\Exception  in release.php on line 108:

Release name "64" already exists.
Release name can be overridden via:
dep deploy -o release_name=66
```

**Comment by Bilge** [comment]
>ll releases

```
drwxrwsr-x+ 11 4.0K Jan  5  2022 199
drwxrwsr-x+ 11 4.0K Jan  8  2022 200
drwxrwsr-x+ 11 4.0K Jan  8  2022 201
drwxrwsr-x+ 11 4.0K Jan  9  2022 202
drwxrwsr-x+ 11 4.0K Jan 12  2022 203
drwxrwsr-x+ 11 4.0K Jan 10 18:26 54
drwxrwsr-x+ 11 4.0K Jan 11 10:59 55
drwxrwsr-x+ 11 4.0K Jan 11 11:46 56
drwxrwsr-x+ 11 4.0K Jan 13 11:02 57
drwxrwsr-x+ 11 4.0K Jan 13 13:22 58
drwxrwsr-x+ 11 4.0K Jan 13 16:25 59
drwxrwsr-x+ 11 4.0K Jan 24 14:09 60
drwxrwsr-x+ 11 4.0K Jan 24 23:24 61
drwxrwsr-x+ 11 4.0K Jan 25 23:09 62
drwxrwsr-x+ 11 4.0K Jan 26 02:01 63
drwxrwsr-x+ 10 4.0K Nov 10  2020 64
drwxrwsr-x+ 10 4.0K Nov 11  2020 65
drwxrwsr-x+ 11 4.0K Dec  9  2020 86
```

It seems that, at some point, Deployer hurt itself in its confusion and started renumbering using older, existing release numbers. At the same time, it stopped cleaning up older releases.

**Comment by dkoether** [comment]
Dear @Bilge,

please check in your deployment output if you call the task "deploy:release" multiple times. This would explain why the folder already exist. 

Otherwise please also check the counter of the last release number in file '{deploy_path}/.dep/latest_release' since you have a jump in your release folders and may the wrong number.

**Comment by antonmedv** [comment]
https://deployer.org/docs/7.x/UPGRADE#step-2-deploy

**Comment by Bilge** [comment]
I guess this can be closed since it's a _known issue_ introduced by upgrading, but it seems to me it still uses an incrementing release number, same as it always has, so I don't understand what the incompatibility issue is. In any case, there really should be a transparent migration path for existing users instead of having to do all those manual steps.

**Comment by antonmedv** [comment]
>  so I don't understand what the incompatibility issue is

Deployer v7 now uses a file to track releases and not rely on dirs in releases/ folder. 

> In any case, there really should be a transparent

Upgrade docs should cover this.

>  automatic migration path for existing users instead of having to do all those manual steps.

An automatic migration step can be implemented. But I don't have time to write and debug such code (so I decided to choose docs instead). Feel free to send a PR with the automation though :)
