### ISSUE TITLE
Add `remote` option to `update_code_strategy` to clone repository in release_path

### ISSUE THREAD

**Issue by jhhazelaar** [deployphp/deployer#3464]
Give deployer the option to have the remote repository in the release_path.

We use [Statamic](https://statamic.com) and in Statamic there's an option Git Automation, see documentation: https://statamic.dev/git-automation.

The default value of `update_code_strategy` is `archive`, but with the Git Automation we need a repository present in the `release_path` and with the option `clone` the repository is present but the origin is to a local mirror. But we need the remote origin.

Work around we now use is to set `update_code_strategy` to 'clone' add een extra remote and push to remote before a new deployment.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3464">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3464/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3464/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
What about adding remote after clone?

**Comment by jhhazelaar** [comment]
We can do that with every deployment, but we need to change the remote push in Statamic and add an action to the `deploy` action.

I think this option would be nice because there's no work around needed for deployer or Statamic. I'll wip up a fork and a PR and see if you like it or otherwise you can close it.

**Comment by antonmedv** [comment]
PR is ok 👍🏻

**Comment by jhhazelaar** [comment]
@antonmedv added a PR: https://github.com/deployphp/deployer/pull/3466 hoop you like it.

**Comment by alexflorea2** [comment]
This is something that I noticed moving from v6 also and feels like a big change that I did not found in the docs.

so bump for PR :)

**Comment by mwagena** [comment]
Made a new PR on this issue due to the wrong branch being made active after de update_code_strategy action. See: https://github.com/deployphp/deployer/pull/3540
