### ISSUE TITLE
Old releases are not deleted if colors is enabled for ls command

### ISSUE THREAD

**Issue by ocean90** [deployphp/deployer#3470]
- Deployer version: 7.1.3
- Deployment OS: macOS

I noticed that for a project the old releases were not deleted while `keep_releases` was set to 3. After some debugging I finally noticed that on the server we had `ls` aliased to `ls --color=always`. Because of this the `array_map()` in https://github.com/deployphp/deployer/blob/1bc90e84426059feb3a390283db6f2790e35d5a1/recipe/deploy/release.php#L39-L43 is producing an array with empty values:

```
array(32) {
  [0]=>
  string(4) ""
  [1]=>
  string(4) ""
  [2]=>
  string(4) ""
  [3]=>
  string(4) ""
  [4]=>
```

Before `array_map()` the output of `$ll` looks like:

<img width="230" alt="Bildschirm­foto 2023-01-30 um 17 17 14" src="https://user-images.githubusercontent.com/617637/215532463-1f006a64-dfb2-4cdf-b74a-030ca09cdac9.png">

As you can see the folder name is in color.

The current fix would be to remove the alias but I'm wondering if Deployer should prevent the colors by explicitly passing `--color=none` to `ls`?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3470">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3470/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3470/pledge.svg">
</picture>
</a>

**Comment by ocean90** [comment]
Looking at https://unix.stackexchange.com/questions/107371/how-to-turn-off-color-with-ls and it seems like there's also `-G` to enable colors on BSD but it's not clear what happens when `--color=none` is set. At least one macOS 13.2 it seems to work:

<img width="182" alt="Bildschirm­foto 2023-01-31 um 12 59 11" src="https://user-images.githubusercontent.com/617637/215753929-425f437b-dda1-4e77-8b30-018ecad6f45a.png">

Another option would be to use `\ls` which disables the alias or `command ls`.

<img width="223" alt="Bildschirm­foto 2023-01-31 um 13 00 00" src="https://user-images.githubusercontent.com/617637/215754089-ab5b2417-eb41-494e-bbdf-797c2e1e172e.png">

**Comment by antonmedv** [comment]
It's also possible to test if --color=none supported.
