### ISSUE TITLE
Native SSH support

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#348]
And also maybe upgrade of phpseclib fork.

**Comment by simonrjones** [comment]
Can I ask does this mean Deployer does not work with SSH public keys by default, e.g. using a public key to login via SSH with the identityFile() method?

If so, that is not clear from the documentation, but certainly doesn't appear to work when I try. 

If this is the case can I suggest some changes to the docs at http://deployer.org/docs/servers

**Comment by elfet** [comment]
Can you make PR to docs?

**Comment by simonrjones** [comment]
Just to confirm is using a public key to login via SSH not supported in Deployer without the ssh2 extension? It's still not clear to me!

**Comment by elfet** [comment]
phpseclib support this too.

**Comment by simonrjones** [comment]
OK.. it's not clear from your replies whether Deployer supports public key login to servers without installing the ssh2 extension?

If it can, looks like I'm doing something wrong since I can't get it working (I do not have ssh2 installed locally).

**Comment by elfet** [comment]
Wow. I'm closing this old issue. 1 year, 4 months, 26 days. I think this is longest time for any of deployer issues.
