### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by antiftw** [deployphp/deployer#3480]
Page at https://deployer.org/docs/hosts says:

Page Not Found

We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**Comment by Schrank** [comment]
Thanks for the info! How did you get there? Aka: Is the link broken or the page missing - for us to check :-)

**Comment by antiftw** [comment]
Ah right, my bad might have been an old link.

I got directed there from https://bolt.github.io/deployer/configuration.html, which is outside of your control.

**Comment by Schrank** [comment]
Happy to help!

Not sure you are looking for this:
https://github.com/deployphp/docs/blob/master/hosts.md
or 
https://github.com/deployphp/deployer/blob/master/docs/hosts.md

But in any case, here you go for 7.x and 6.x (version change on the top):
https://deployer.org/docs/7.x/hosts

**Comment by antiftw** [comment]
Ah cool even better. Made my day a lot easier :) Thanks!

Contacted the other dev about the broken link.

Have a nice weekend.
