### ISSUE TITLE
Error: Failed to open stream: No such file or directory when using third party recipe

### ISSUE THREAD

**Issue by loevgaard** [deployphp/deployer#3485]
- Deployer version: 7.1
- Deployment OS: OSX

```php
<?php
namespace Deployer;

require_once 'recipe/symfony.php';
require_once 'recipe/setono_dotenv.php';

...
```

My `composer.json` looks like this:
```json
{
    "license": "proprietary",
    "type": "project",
    "require": {
        "php": ">=8.1",
        "deployer/deployer": "^7.1",
        "setono/deployer-dotenv": "2.x-dev"
    },
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": false,
            "ergebnis/composer-normalize": true
        }
    }
}
```

I get this error:

```
➜  deployment git:(master) ✗ vendor/bin/dep deploy
 ErrorException  in deploy.php on line 10:

  require_once(recipe/setono_dotenv.php): Failed to open stream: No such file or directory
```

This worked in v6 and I suspect there has been some work in how the include path is used? What is way to allow me and others to create third party recipes nowadays?

Thanks for a great tool <3

**Comment by antonmedv** [comment]
This is an issue of setono/deployer-dotenv. Not deployer)

**Comment by loevgaard** [comment]
Hi, @antonmedv 

Thanks for your swift response. I might be wrong, but here is a reproducer of the problem as I see it: https://github.com/loevgaard/deployer-issue-3485.

As you can see the include path differs.

As mentioned it worked in v6 of Deployer and I have tried to search through the repository for changes that could affect this, but haven't been lucky enough to find it. Maybe you could guide me in the right direction, so I can make a PR? :)

**Comment by loevgaard** [comment]
Oh, just saw this issue: https://github.com/deployphp/deployer/issues/3293. This is the same issue.

**Comment by loevgaard** [comment]
I just tried to include the recipe directly like this: `require_once 'vendor/setono/deployer-dotenv/src/recipe/setono_dotenv.php';`

When it ran I got this error:

```
➜  deployment git:(master) ✗ vendor/bin/dep deploy
task deploy:info
[staging] info deploying HEAD
task deploy:setup
task deploy:lock
task deploy:release
task deploy:update_code
task dotenv:prepare
task deploy:shared
task deploy:writable
task deploy:vendors
task dotenv:generate
task dotenv:update
[staging]  Error  in setono_dotenv.php on line 98:
[staging]
[staging]   Class "Webmozart\Assert\Assert" not found
[staging]
ERROR: Task dotenv:update failed!
task deploy:failed
task deploy:unlock
```

My library requires `webmozart/assert` as you can see here: https://github.com/Setono/deployer-dotenv/blob/2.x/composer.json#L17, so I am leaning more and more towards that something is broken in the autoloading.

**Comment by loevgaard** [comment]
It must be these lines that are the culprit: https://github.com/deployphp/deployer/blob/master/bin/dep#L50-L54.

Is there a reason for this ordering? If the ordering was:

```php
$autoload = [
    __DIR__ . '/../../../autoload.php', // The dep located at "vendor/deployer/deployer/bin".
    __DIR__ . '/../vendor/autoload.php', // The dep located at "deployer.phar/bin" or in development.
    __DIR__ . '/../autoload.php', // The dep located at "vendor/bin".
];
```

it would load the correct autoloader.

**Comment by antonmedv** [comment]
Probably no reason. We can rearrange

**Comment by loevgaard** [comment]
@antonmedv: Added a PR that does just that: https://github.com/deployphp/deployer/pull/3488 :)

**Comment by loevgaard** [comment]
@antonmedv: It's impossible for me to migrate from v6 to v7 because of this issue and I guess for many others who have made their own recipe. I have tried with the PR, but it didn't build and I have no idea/knowledge about all the internals that go into actually testing it. Is it possible to pay you for fixing it? :)

**Comment by loevgaard** [comment]
Also this issue should be reopened, because it is definitely not fixed

**Comment by antonmedv** [comment]
You can use full path to the recipe:

```
require __DIR__ . './vendor/...';
```

**Comment by loevgaard** [comment]
Yes, but that would only work if the required recipes also use absolute requires. This is a pseudo solution and doesn't address the problem.

**Comment by loevgaard** [comment]
And I already tried your 'solution' here: https://github.com/deployphp/deployer/issues/3485#issuecomment-1428593813

**Comment by sylvainraye** [comment]
Hi, it's an issue for me too. I have a bunch of custom recipes and it's broken since v7.x cause of the autoload changes done in v7 as mentioned @loevgaard in the comment https://github.com/deployphp/deployer/issues/3485#issuecomment-1430307650

**Comment by sylvainraye** [comment]
Hi, my solution is to add in my deploy.php: `require $GLOBALS['_composer_autoload_path'];` after namespace declaration. As the dep binary is loading its own autoload included in its phar archive and not the one of the global composer where dep could be installed.

**Comment by loevgaard** [comment]
Summary (as per request of @antonmedv):

In v7 the autoloading inside Deployer has changed, which has the effect that third party recipes can't be loaded. A lot of fixes has been suggested, but doesn't work.

**Comment by antonmedv** [comment]
Duplicate of https://github.com/deployphp/deployer/issues/3605

**Comment by Smove** [comment]
For me, autoloading works as soon as i'm using dev-master. In every releases version, some autoload files get removed and thus its not working
