### ISSUE TITLE
Drop php@7.x support and update requirement

### ISSUE THREAD

**Issue by jhhazelaar** [deployphp/deployer#3494]
We needed to upgrade the requirements because of some conflicts. I made a PR to update the requirements and drop support of php@7.x to satisfy that requirement.

PR: https://github.com/deployphp/deployer/pull/3493

**Comment by antonmedv** [comment]
Are you using dev-master?

**Comment by jhhazelaar** [comment]
Yes is used dev-master and got conflicts with a Laravel applicatie. When I use de update dev-master in https://github.com/jhhazelaar/deployer it works.

**Comment by jhhazelaar** [comment]
If you want to drop de support van php@7.x, maybe we can also update the main of the Laravel test installation.

**Comment by antonmedv** [comment]
# Do NOT install `dev-master`

Install a specific tag version. THose tags are "bundled" and no dependencies are required there.

**Comment by jhhazelaar** [comment]
Oke, but the functionaliteit I need are not tagged yet. I'll wait for it to be tagged.

You can close this issue and pr if you like. Or keep it if you wan't to use it later.
