### ISSUE TITLE
parse does not work with :

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#3500]
- Deployer version: 7.1.4
- Deployment OS: mac OS

```
set('maxcluster:redis:prefix', 'fabi-testet');
parse('{{maxcluster:redis:prefix}}-cache');
```
ends in 

    {{maxcluster:redis:prefix}}-cache

instead of

    fabi-testet-cache

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3500">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3500/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3500/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Regexp change is needed)
