### ISSUE TITLE
Dependency on abandoned package

### ISSUE THREAD

**Issue by piotrekkr** [deployphp/deployer#351]
When installing deployer using composer I get:

```
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

**Comment by kenjis** [comment]
See https://github.com/deployphp/deployer/issues/259#issuecomment-111633652

**Comment by elfet** [comment]
Ref https://github.com/reactphp/http-client/issues/23

**Comment by johnny-bit** [comment]
So... Deployer depends on elfet/pure which in turns depends on react/react, which in turn depends on react/http-client which in turn depends on guzzle/parser... Fun.
