### ISSUE TITLE
Bugsnag Recipe not working due to API change

### ISSUE THREAD

**Issue by shakalandy** [deployphp/deployer#3518]
- Deployer Version: 7.2.0
- Deployment OS: Ubuntu 20.04 LTS

The Bugsnag API changed and the old API Endpoint is not reachable anymore:

```
[staging]  Deployer\Exception\HttpieException  in Httpie.php on line 186:
[staging]
[staging]   Failed to connect to notify.bugsnag.com port 443 after 4 ms: Couldn't connect to server
[staging]
ERROR: Task bugsnag:notify failed!
task deploy:failed
task deploy:unlock
❯ telnet notify.bugsnag.com 443
Trying ::...
telnet: connect to address ::: Connection refused
Trying 0.0.0.0...
telnet: connect to address 0.0.0.0: Connection refused
telnet: Unable to connect to remote host
``` 

The new Endpoint for the API is: https://build.bugsnag.com/

From what I can see the spec also changed, at least regarding source control and metadata: https://bugsnagbuildapi.docs.apiary.io/#reference/0/build/notify-of-a-build

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3518">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3518/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3518/pledge.svg">
</picture>
</a>

**Comment by Schrank** [comment]
Thanks for the issue, want to provide a PR for the fix? :-)
