### ISSUE TITLE
Lock and unlock releases

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#354]
We really need to implement this feature. 
- `deploy:release`  
  Then new release dir created, `LOCK` file created within it.  
  If prev release contains `LOCK` file, error throws.
- `deploy:symlink`  
  After symlink `LOCK` file deleted.
- `rollback`  
  Skip all release what contains `LOCK` file.
- `cleanup`  
  Delete all release what contains `LOCK` file (check if current not linked to it).

![](http://cdn.ebaumsworld.com/mediaFiles/picture/1989829/83031891.gif)

**Comment by johnny-bit** [comment]
So... `LOCK` file is basically saying "we're in process of deploying here"? I quite get the concept for release, symlink & rollback (rolling to last complete release) however I don't get cleanup... If release acted like You said, then cleanup would have to be run twice - once befor release and once normally. maybe it would be better to add tasks like semaphores? `acquire_lock` and `release_lock`?

**Comment by gordalina** [comment]
:+1:

**Comment by elfet** [comment]
acquire_lock and release_lock - :+1:

**Comment by Baldinof** [comment]
Is it necessary to have it on a per release basis ?

For my projects, I use these tasks, and it works good:
```php
env('lock_path', '{{deploy_path}}/deploy.lock');

task('deploy:lock', function() {
    $res = run('[ -f {{lock_path}} ] && echo Locked || echo OK');

    if (trim($res) === "Locked") {
        throw new RuntimeException("Deployement is locked.");
    }

    run('touch {{lock_path}}');
});

task('deploy:unlock', function() {
    $res = run('[ -f {{lock_path}} ] && echo Locked || echo OK');

    if (trim($res) === "Locked") {
        run('rm {{lock_path}}');
    }
});

after('deploy:prepare', 'deploy:lock');
after('deploy:symlink', 'deploy:unlock');
```

**Comment by elfet** [comment]
Done in v4!
