### ISSUE TITLE
Docs: missing information in "Upgrade from 6.x to 7.x"

### ISSUE THREAD

**Issue by TomaszGasior** [deployphp/deployer#3541]
This information in migration guide would make it much easier.

- Task definition as string is not supported anymore (like: `task('maintenance:disable', 'rm -f var/lock/maintenance.lock');`. When migrating you need to prepend new code with something like `cd('{{release_path}}');`.
- `.git` directory in project directory is not present by default, previously it was possible to use git commands in deployment process, now you need to switch `update_code_strategy` to `clone`.

**Comment by Schrank** [comment]
Thanks for the issue! Would you mind adding a PR? That would be awesome!

**Comment by TomaszGasior** [comment]
Created https://github.com/deployphp/deployer/pull/3546
