### ISSUE TITLE
Add commit message to `dep releases`

### ISSUE THREAD

**Issue by lukepass** [deployphp/deployer#3544]
Hello, is it possible to get the commit message to the `dep releases` command?

Something like this:

```
+---------------------+------example.org ------------+--------+-----------+----------------+
| Date (UTC)          | Release     | Author         | Target | Commit    | Message        |
+---------------------+-------------+----------------+--------+-----------+----------------+
| 2021-11-06 20:51:45 | 1           | Anton Medvedev | HEAD   | 34d24192e | First message  |
| 2021-11-06 21:00:50 | 2 (bad)     | Anton Medvedev | HEAD   | 392948a40 | Second message |
| 2021-11-06 23:19:20 | 3           | Anton Medvedev | HEAD   | a4057a36c | Third message  |
| 2021-11-06 23:24:30 | 4 (current) | Anton Medvedev | HEAD   | s3wa45ca6 | Fourth message |
| 2021-11-06 23:24:30 | 5           | Anton Medvedev | HEAD   | s3wa45ca6 | Fifth message  |
+---------------------+-------------+----------------+--------+-----------+----------------|
```

Thanks.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3544">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3544/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3544/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I'm not sure it will fit into one table)

**Comment by lukepass** [comment]
Maybe there could be one option such as `--long-format` or `--show-message` which will display it if needed? Thanks.
