### ISSUE TITLE
Magento 2: No themes are compiled if magento_themes is not set

### ISSUE THREAD

**Issue by mfickers** [deployphp/deployer#3549]
- Deployer version:  7.3

This PR #3326 changed the default behavior of the assets deployment step of the Magento 2 recipe. If `magento_themes` is empty, which is the default value, then no themes will be compiled at all.

[The documentation states](https://github.com/deployphp/deployer/blob/master/docs/recipe/magento2.md#magento_themes) that all themes should be compiled as the default behavior.

On version 7.2.1 and before, `setup:static-content:deploy` was called with $themesToCompile as an empty string, triggering the deployment of all themes:

 https://github.com/deployphp/deployer/blob/v7.2.1/recipe/magento2.php#L110-L117
```php
    $themesToCompile = '';
    if (count(get('magento_themes')) > 0) {
        foreach (get('magento_themes') as $theme) {
            $themesToCompile .= ' -t ' . $theme;
        }
    }

    run("{{bin/php}} {{bin/magento}} setup:static-content:deploy --content-version={{content_version}} {{static_content_locales}} $themesToCompile -j {{static_content_jobs}}"https://github.com/deployphp/deployer/commit/762a177ce1417ecc5e30dbf35d19c62734cb5b4e;
```

On version 7.3, the call to `setup:static-content:deploy` was moved inside the if-condition checking if `magento_themes` is not empty, leading to no themes to be compiled at all:

https://github.com/deployphp/deployer/blame/v7.3.0/recipe/magento2.php#L181-L190
```php
    $themesToCompile = '';
    if (get('split_static_deployment')) {
        invoke('magento:deploy:assets:adminhtml');
        invoke('magento:deploy:assets:frontend');
    } elseif (count(get('magento_themes')) > 0 ) {
        foreach (get('magento_themes') as $theme) {
            $themesToCompile .= ' -t ' . $theme;
        }
        run("{{bin/php}} {{release_or_current_path}}/bin/magento setup:static-content:deploy --content-version={{content_version}} {{static_deploy_options}} {{static_content_locales}} $themesToCompile -j {{static_content_jobs}}");
    }
```

**Comment by peterjaap** [comment]
Correct, as far as I can see this is the fix; https://github.com/deployphp/deployer/pull/3550

@renttek @sprankhub could you take a look too?

**Comment by peterjaap** [comment]
I guess that would make sense to keep it uniform, but Magento should already be running in production mode there, so shouldn't make a difference as far as I can see.
