### ISSUE TITLE
Task chain that requires 2+ remote servers

### ISSUE THREAD

**Issue by johnny-bit** [deployphp/deployer#355]
I have to write weird piece. Usually that would be 3 separate commands, but it would be great to be able to do in one:

1. Connect to server 1, issue command to create file on server 1
2. Dowload file locally (or upload to server2 directly if possible, then skip to point 4)
3. Connect & upload file downloaded to server 2
4. Issue command on server 2 to accept file

Reason for this: when developing long-running wordpress site (for example) it's great to have production database on staging, and vice versa - have changes applied on staging work on production witout lengtly introducing them.

Any suggestions for that?

**Comment by elfet** [comment]
Yes, try to use `onlyOn`. :wink: 
```php
task(...)->onlyOn('server 1');
task(...)->onlyOn('server 2');
task(...)->onlyOn('server 1');
```

**Comment by oanhnn** [comment]
@johnny-bit 
Are you haven't any other questions about @elfet 's suggestion?
I am closing thing issue but feel free to reopen if you think there needs to be more discussion.
