### ISSUE TITLE
Yii recipe is missing migrate

### ISSUE THREAD

**Issue by pappfer** [deployphp/deployer#3559]
I'm using Deployer v7 in a Yii2 application and the [yii recipe](https://deployer.org/docs/7.x/recipe/yii) seems to be missing a migrate task.
I added this to my deploy.php for now:

```
after('deploy:vendors', 'deploy:migrate');
task('deploy:migrate', function () {
    run('cd {{release_path}} && php yii migrate');
});
```

Shouldn't something like this be part of the recipe?

**Comment by antonmedv** [comment]
Yes, I think so. PR?
