### ISSUE TITLE
Namespace for functions

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#356]
Should Deployer use namespace for functions in `functions.php`?
To protect from overriding when installed via Composer with Laravel.
In recipe can be used in two ways:
```php
use function Deployer/task;
```
or
```php
namespace Deployer;
```
@deployphp/maintainer what do you think?

**Comment by kenjis** [comment]
`use function` can be used on PHP 5.6 or lator.

**Comment by gordalina** [comment]
If you use `use function` you'd have to import all functions (not only `task`). So i'd go for `namespace Deployer`.

Also, if this is to be implemented, i'd suggest in 4.0, per [semver](http://semver.org/) compliance. Lets not break API in minor updates.

**Comment by ZeeCoder** [comment]
I already wrote a couple of times how I'm a bit troubled by the "global" way Deployer sometimes handles things, so I'd back any solution.
On another note: I agree with @gordalina here, the idea is good, but it's hard to see whether it could be achieved in a non-BC-breaking fashion.

**Comment by gordalina** [comment]
@ZeeCoder I don't think it's achievable in a non-BC-breaking fashion, and I'm ok with that, **if and only if**, there's a proper versioning scheme (such as semver) and documentation for it.

**Comment by ZeeCoder** [comment]
My thoughts exactly

**Comment by elfet** [comment]
So you think go for v4.0?

**Comment by ZeeCoder** [comment]
For certain features, like this one, yes imho.

**Comment by elfet** [comment]
Well, lets release 4.0! Also i haму 100% awesome feature for this release. :fork_and_knife:  :fork_and_knife:   :fork_and_knife:   :fork_and_knife:

**Comment by gordalina** [comment]
Is there any other way to fix deployment of laravel apps?

**Comment by felipepodesta** [comment]
+1

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by marcosh** [comment]
The global nature of deployer functions clashes also with `hamcrest-php`.

I get the following error:

    PHP Fatal error:  Cannot redeclare set() 
    (previously declared in vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455)
    in vendor/deployer/deployer/src/functions.php on line 417

Definitely +1 for using a namespace in `functions.php`

**Comment by diimpp** [comment]
Same here

**Comment by JHGitty** [comment]
Need this as fast as possible for Symfony2 / Symfony3.

**Comment by JHGitty** [comment]
I think we need #471 to complete this issue.
