### ISSUE TITLE
Please add 7.3.1 to manifest

### ISSUE THREAD

**Issue by DowleyDeveloped** [deployphp/deployer#3562]
- Deployer version: 7.3.1
- Deployment OS: Ubuntu

Please add 7.3.1 version to [manifest.json](https://deployer.org/manifest.json).  Our deployment is looking for the latest release :)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3562">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3562/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3562/pledge.svg">
</picture>
</a>

**Comment by DowleyDeveloped** [comment]
Any update on this?

**Comment by ngrie** [comment]
I am aware that pushing issues on GitHub is not appreciated, but I am sure that this really small change would fix a lot of pipelines out there 😅 

I would do the pull request myself if that manifest file was to be found in a public repository.

**Comment by antonmedv** [comment]
Will update the manifest:)

**Comment by DowleyDeveloped** [comment]
@antonmedv Do you have an ETA for this? Sorry to nudge!

**Comment by antonmedv** [comment]
Let's do it this way. https://github.com/sponsors/antonmedv - if I collect $100 by the end of this day, will fix this bug after the work ;)

**Comment by tedsalmon** [comment]
Bump? 7.3.1 is still unavailable in the manifest file :(

**Comment by antonmedv** [comment]
Still not enough money to do the job. Sorry.

**Comment by tedsalmon** [comment]
> Still not enough money to do the job. Sorry.

Holding such a minor change hostage in exchange for money goes against the ethos of FOSS. While, I understand that we all need to make a living, I think this is the wrong way to go about it. Many other projects have found ways to monetize their work without resorting to gatekeeping changes, and I implore you to do the same.

**Comment by Schrank** [comment]
Hi!
There is no gate keeping, you can just fork it and do it yourself. You can have your own manifest and use that.

And it is not about holding hostage - we all work on things we want to and if the motivation is low, we don't. Therefore either you increase the motivation of @antonmedv or you need to learn living with it. It will surely happen one day.

**Comment by antonmedv** [comment]
@Schrank is right here. 😊 When my motivation is high, I do a lot of things. Currently my focus shifted to another FOSS project. And I still maintain Deployer. 

What need to be done for updating manifest:
- Recent release (BTW, thanks for everyone for lunch money, 75$ collected in one day, was enough to buy [this](https://www.lego.com/en-us/product/nasa-mars-rover-perseverance-42158) on discount) started automatic workflow.
- This workflow should update manifest.json itself.
- I can just go and add record into manifest, also the workflow need to be fixes.

**Comment by SimJoSt** [comment]
Just as a note for future explorers: The manifest at https://deployer.org/manifest.json now seems to contain the version `7.3.1`, `7.3.2`, `7.3.3` and `7.4.0`.
Thus, the issue is not just closed because of the move to discussions, but is actually completed.
