### ISSUE TITLE
Provision PHP 8.2 

### ISSUE THREAD

**Issue by rodrigodeananias** [deployphp/deployer#3568]
Is there a prevision to enable PHP 8.2  on provision?

**Comment by antonmedv** [comment]
set('php_version', ‘8.2’);

**Comment by rodrigodeananias** [comment]
I've tried, but failed.

**Comment by rodrigodeananias** [comment]
`Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php8.2-bcmath
E:
Couldn't find any package by glob 'php8.2-bcmath'
E: Couldn't find any package by regex 'php8.2-bcmath'
E: Unable to locate package php8.2-cli
E: Couldn't find any package by glob 'php8.2-cli'
E: Couldn't find any package by regex 'php8.2-cli'
E: Unable to locate package php8.2-curl
E: Couldn't find any package by glob 'php8.2-curl'
E: Couldn't find any package by regex 'php8.2-curl'
E: Unable to locate package php8.2-dev
E: Couldn't find any package by glob 'php8.2-dev'
E: Couldn't find any package by regex 'php8.2-dev'
E: Unable to locate package php8.2-fpm
E: Couldn't find any package by glob 'php8.2-fpm'
E: Couldn't find any package by regex 'php8.2-fpm'
E: Unable to locate package php8.2-gd
E: Couldn't find any package by glob 'php8.2-gd'
E: Couldn't find any package by regex 'php8.2-gd'
E: Unable to locate package php8.2-imap
E: Couldn't find any package by glob 'php8.2-imap'
E: Couldn't find any package by regex 'php8.2-imap'
E: Unable to locate package php8.2-intl
E: Couldn't find any package by glob 'php8.2-intl'
E: Couldn't find any package by regex 'php8.2-intl'
E: Unable to locate package php8.2-mbstring
E: Couldn't find any package by glob 'php8.2-mbstring'
E: Couldn't find any package by regex 'php8.2-mbstring'
E: Unable to locate package php8.2-mysql
E: Couldn't find any package by glob 'php8.2-mysql'
E: Couldn't find any package by regex 'php8.2-mysql'
E: Unable to locate package php8.2-pgsql
E: Couldn't find any package by glob 'php8.2-pgsql'
E: Couldn't find any package by regex 'php8.2-pgsql'
E: Unable to locate package php8.2-readline
E: Couldn't find any package by glob 'php8.2-readline'
E: Couldn't find any package by regex 'php8.2-readline'
E: Unable to locate package php8.2-soap
E: Couldn't find any package by glob 'php8.2-soap'
E: Couldn't find any package by regex 'php8.2-soap'
E: Unable to locate package php8.2-sqlite3
E: Couldn't find any package by glob 'php8.2-sqlite3'
E: Couldn't find any package by regex 'php8.2-sqlite3'
E: Unable to locate package php8.2-xml
E: Couldn't find any package by glob 'php8.2-xml'
E: Couldn't find any package by regex 'php8.2-xml'
E: Unable to locate package php8.2-zip
E: Couldn't find any package by glob 'php8.2-zip'
E: Couldn't find any package by regex 'php8.2-zip'`

**Comment by rodrigodeananias** [comment]
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php8.2-bcmath
E:
Couldn't find any package by glob 'php8.2-bcmath'
E: Couldn't find any package by regex 'php8.2-bcmath'
E: Unable to locate package php8.2-cli
E: Couldn't find any package by glob 'php8.2-cli'
E: Couldn't find any package by regex 'php8.2-cli'
E: Unable to locate package php8.2-curl
E: Couldn't find any package by glob 'php8.2-curl'
E: Couldn't find any package by regex 'php8.2-curl'
E: Unable to locate package php8.2-dev
E: Couldn't find any package by glob 'php8.2-dev'
E: Couldn't find any package by regex 'php8.2-dev'
E: Unable to locate package php8.2-fpm
E: Couldn't find any package by glob 'php8.2-fpm'
E: Couldn't find any package by regex 'php8.2-fpm'
E: Unable to locate package php8.2-gd
E: Couldn't find any package by glob 'php8.2-gd'
E: Couldn't find any package by regex 'php8.2-gd'
E: Unable to locate package php8.2-imap
E: Couldn't find any package by glob 'php8.2-imap'
E: Couldn't find any package by regex 'php8.2-imap'
E: Unable to locate package php8.2-intl
E: Couldn't find any package by glob 'php8.2-intl'
E: Couldn't find any package by regex 'php8.2-intl'
E: Unable to locate package php8.2-mbstring
E: Couldn't find any package by glob 'php8.2-mbstring'
E: Couldn't find any package by regex 'php8.2-mbstring'
E: Unable to locate package php8.2-mysql
E: Couldn't find any package by glob 'php8.2-mysql'
E: Couldn't find any package by regex 'php8.2-mysql'
E: Unable to locate package php8.2-pgsql
E: Couldn't find any package by glob 'php8.2-pgsql'
E: Couldn't find any package by regex 'php8.2-pgsql'
E: Unable to locate package php8.2-readline
E: Couldn't find any package by glob 'php8.2-readline'
E: Couldn't find any package by regex 'php8.2-readline'
E: Unable to locate package php8.2-soap
E: Couldn't find any package by glob 'php8.2-soap'
E: Couldn't find any package by regex 'php8.2-soap'
E: Unable to locate package php8.2-sqlite3
E: Couldn't find any package by glob 'php8.2-sqlite3'
E: Couldn't find any package by regex 'php8.2-sqlite3'
E: Unable to locate package php8.2-xml
E: Couldn't find any package by glob 'php8.2-xml'
E: Couldn't find any package by regex 'php8.2-xml'
E: Unable to locate package php8.2-zip
E: Couldn't find any package by glob 'php8.2-zip'
E: Couldn't find any package by regex 'php8.2-zip'

**Comment by rodrigodeananias** [comment]
I've found the problem, 8.2 it's not running on Ubuntu 22.04

**Comment by rodrigodeananias** [comment]
Thanks @antonmedv
