### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by gordalina** [deployphp/deployer#358]
Let's define a clear release process for deployer!

Here are some questions that were raised:

1. Avoid breaking BC in minor or patch releases
2. Introduce a UPGRADE file for end-users to see what was updated and how can they migrate their deploy scripts easily. This should contain NON BC-BREAKING changes for minor and BC-BREAKING changes in major version upgrade (3.x -> 3.x+1 and 3.x -> 4.0).
3. Introduce a CHANGELOG file for documenting patch releases. This can be done with a script that reads the `git log` output (this means that PR's should be [squashed](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) into one commit only).
4. Require PR's to have a matching documentation PR
5. Process to merge fixes for the lowest supported release (merge fixes to 3.0, merge new features to 3.1) when a fix is merged to 3.0, the 3.0 branch can be merged to 3.1.

Ping @deployphp/maintainer

**Comment by ZeeCoder** [comment]
:+1: for pretty much everything

**Comment by gordalina** [comment]
Just leaving here Symfony's BC Promise http://symfony.com/doc/current/contributing/code/bc.html
We should adopt something like this

**Comment by elfet** [comment]
@gordalina :+1: 
Can you write this to https://github.com/deployphp/deployer/blob/master/CONTRIBUTING.md

**Comment by lucasmichot** [comment]
:+1:

**Comment by lucasmichot** [comment]
For point 3, we can use of http://keepachangelog.com/ with http://changehub.io/cases/addapp/
