### ISSUE TITLE
Autoloading of third party recipes not working

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3605]
In v7 the autoloading inside Deployer has changed, which has the effect that third party recipes can't be loaded. A lot of fixes has been suggested, but doesn't work.

_Originally posted by @loevgaard in https://github.com/deployphp/deployer/issues/3485#issuecomment-1559273847_
            

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3605">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3605/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3605/pledge.svg">
</picture>
</a>

**Comment by sylvainraye** [comment]
Current workaround on deploy.php:

```
<?php

namespace Deployer;

require_once dirname(DEPLOYER_BIN) . '/../../autoload.php';
```

Fixed the issue for my own projects and recipes.

**Comment by Sven-TS** [comment]
Thank you, the workaround also works for me. Was looking for hours for a solution until I found this comment.
