### ISSUE TITLE
Throw exception on deploy:lock twice

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#3613]
I had a discussion with a user who had a failing deployment, because they added deploy:lock a second time, aber recipe/common.php did it already. We can throw an explicit exception for better development experience which explains THIS problem

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3613">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3613/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3613/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I think yes. We can save something in host to mark is a already locked in current deploy.
