### ISSUE TITLE
yarn recipe hard links rather than copy

### ISSUE THREAD

**Issue by stevenbrookes** [deployphp/deployer#3614]
Hi

Nice to see yarn now supported natively in deployer.  I've switched to using it instead of my own task definition.  I noticed it use cp -R to make a copy of the node modules.  This definitely speeds up the deployment, but doing cp -al instead, creating hard links rather than a copy is almost instant.  Seems to be working for me.

Would you like a patch ;)

Steve

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3614">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3614/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3614/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Nice idea 💡
