### ISSUE TITLE
additional settings in yaml config

### ISSUE THREAD

**Issue by asvechkar** [deployphp/deployer#3628]
- Deployer version: 7.3.1
- Deployment OS: ubuntu 22.04

In deploy.php I have next settings:
add('shared_files', ['.env']);
add('shared_dirs', ['vendor', 'node_modules']);
add('writable_dirs', ['bootstrap/cache', 'storage']);

How I can write this to deploy.yaml?

**Comment by antonmedv** [comment]
Currently not supported. Will work on adding support for this too.

**Comment by Schrank** [comment]
Agree, duplicate.
