### ISSUE TITLE
[Insight] The composer.lock is not up to date

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#363]
**[in composer.lock](https://github.com/deployphp/deployer/blob/3b271852214898ae5cf0f71e209954aadbfe86f8/composer.lock#L0)**

> The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

---------------------

Lets get platinum medal! =)

**Comment by ZeeCoder** [comment]
[Here you go](https://insight.sensiolabs.com/projects/69072898-df4a-4dee-ab05-c2ae83d6c469/analyses/347) :)

**Comment by elfet** [comment]
@ZeeCoder :cookie: :cookie: :cookie: Awesome!

**Comment by ZeeCoder** [comment]
:+1:
