### ISSUE TITLE
Images broken after deploying Statamic

### ISSUE THREAD

**Issue by Aquive** [deployphp/deployer#3632]
- Deployer version:  7.3.1

- Deployment OS: Ubuntu

When I deploy `dep deploy` Images on the site are broken (404). I need to manually do a "Clear all" in the control panel to make it work again, why is that?

```
<?php
namespace Deployer;

require 'recipe/statamic.php';

// Config

// We are using username and 'app password' to have write access without the need for an SSH key or agent
set('repository', '<url>');
set('update_code_strategy', 'clone');

add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Hosts
host('production')
    ->set('hostname', '<host>')
    ->set('remote_user', 'app')
    ->set('deploy_path', '~/production')
    ->set('writable_mode', 'chmod');

// Hooks

after('deploy:failed', 'deploy:unlock');

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3632">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3632/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3632/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I guess the same problem as in https://deployer.org/docs/7.x/avoid-php-fpm-reloading
