### ISSUE TITLE
Allow to continue parallel deployment if one host failed

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3671]
Hi !

I use deployer V7 with 10 hosts and parallel deployment is perfect !

However, yesterday I had a problem where one of the servers was down, and I discovered that if a single command fails for one host, ALL the deployment is canceled and every hosts stops at the step failed.

Is there a way to tell deployer to call the `fail()` callback for this host but continue normally for the others healthy hosts?

Thx for your help! :)

_Originally posted by @Tristan-MyAnaPro in https://github.com/deployphp/deployer/discussions/3668_

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3671">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3671/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3671/pledge.svg">
</picture>
</a>

**Comment by thyseus** [comment]
I like that idea but i want to point out that the *default* behavior should be to cancel the complete deployment process.
If one likes to implement a fallback, he should know that he is doing.

Having only 9 out of 10 nodes working but a green pipeline can be worse than a instant red pipeline with error notification :)
