### ISSUE TITLE
Support for writable_files like writable_dirs

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3678]
The [writable-recipie](https://deployer.org/docs/7.x/recipe/deploy/writable) allows to set the owner/group of directories. If also owner/group of files should be set, the workaround (except `run`) is to use `writable_recursive: true` and add the parent-directory to `writable_dirs`. But this changes the permissions of all files and directories within the specified directories. So a new option `writable_files` would be handy, which sets the owner/group only for the configured files.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3678">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3678/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3678/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I like the idea. Let's figure out on how can we refactor recipe.
