### ISSUE TITLE
[Symfony] database:migrate should only be executed once

### ISSUE THREAD

**Issue by Mika56** [deployphp/deployer#3687]
Because `database:migration` task alters the database, it should only be executed once, not by every host.

As such, `->once()` should be called when defining the task

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3687">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3687/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3687/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Well, it depends. 

You can do it by adding in your deploy.php:

```php
task('database:migration')->once();
```
