### ISSUE TITLE
Pass host definition from args

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3696]
Using selector/alias (last example from my initial post) still require to define hosts in `deploy.php`
But this is what I am trying to avoid.

_Originally posted by @Seb33300 in https://github.com/deployphp/deployer/issues/3692#issuecomment-1727956595_
            

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3696">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3696/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3696/pledge.svg">
</picture>
</a>

**Comment by Seb33300** [comment]
This could also be just a flag like `--auto-host` or any other name to automatically "register" unknow host to the list.

For instance, if `host('exemple.com')` is not in `deploy.php` and we try to do:
```bash
dep deploy exemple.com --auto-host -o branch=develop -o deploy_path=/path/www -o keep_releases=3 -vvv 
```

-> This should automatically call the `host('exemple.com')` method

**Comment by Seb33300** [comment]
For now, I bypassed that limitation by defining an environment variable in my CD pipeline and modifying my deploy.php as following:
``` php
host($_SERVER['my-variable']);
```
