### ISSUE TITLE
CLI hangs when calling task with incompatible host select

### ISSUE THREAD

**Issue by SimJoSt** [deployphp/deployer#3699]
- Deployer version: https://github.com/deployphp/deployer/releases/tag/v7.3.1
- Deployment OS: macOS

We noticed that tasks that have been restricted to specific hosts with `select()` cause issues when run directly via the cli without a compatible host.
For example, running the following command with the following task, will cause the cli to hang forever:
```bash
$ ./vendors/bin/dep single env=prod
```
```php
task('single', function(){
    echo 'single';
})->select('env=dev');
```

If the task that is restricted to a host is invoked from a group task, this issue doesn't occur:
```php
task('group', [
    'single'
]);

task('single', function(){
    echo 'single';
})->select('env=dev');
```
In this scenario, the cli ends the run without an issue.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3699">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3699/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3699/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Hmmm, intresting.
