### ISSUE TITLE
Comparison to Magallanes deploy tool

### ISSUE THREAD

**Issue by Mihailoff** [deployphp/deployer#37]
As many devs do, I'm searching for PHP replacement of Capistrano to be more consistent. Deployer seems pretty thin and clear. BTW there is another tool http://magephp.com/. So far one feature from it seems to me important: YAML configuration. Such language agnostic way makes life easier to non-php-dev users. I understand that Deployer API is very light to be used directly.

Also it's not documented how can be used different environment configs. In Magallanes it's more clear 

> .mage/config - the main general.yml configuration file is stored here.
> .mage/config/environments - the environments configuration files are here.
> .mage/logs - logs (if enabled) are saved there.
> .mage/tasks - and custom tasks are stored over here.

**Comment by elfet** [comment]
@Mihailoff great news! Now Deployer support server configuration via YANL files: http://deployer.org/docs/servers

And soon will be able to define entire `deploy.php` as `deploy.yml`.
