### ISSUE TITLE
ask function: Call to a member function getOutput()

### ISSUE THREAD

**Issue by puxiaokang** [deployphp/deployer#371]
Just for secure, I can't write host password in code. So I try ``ask`` function.

when I call ``ask`` or ``askHiddenResponse`` for ask password, the function throw this error:
```
Fatal error: Call to a member function getOutput() on a non-object in vendor/deployer/deployer/src/functions.php on line 511
```
*example:*
```
<?php
require 'recipe/symfony.php';
$password = askHiddenResponse("Host password: ");

server('prod', 'HOST', 22)
     ->user('USER')
     ->password($password);
```

If ``ask`` in ``task`` callback, It's success. but I can set server.password:
```
task('auth', function(){
    $password = askHiddenResponse("Host password: ");
    env('server.password', $password);
});
before('deploy', 'auth');

-- throw exception
The parameter `server.password` cannot be set, because `server` is protected.
```

**Comment by elfet** [comment]
You can specify password to `null`:
```php
server('prod', 'HOST', 22)
     ->user('USER')
     ->password(null);
```
And you will be asked for password.

@ZhukV can you add docs about this functionality?

**Comment by puxiaokang** [comment]
Thanks

**Comment by staabm** [comment]
is `ask` and friends not supposed to be run at the top level?
(as I ran into the same error as I dont invoke it within a task it seems).

if this is the case it would be great to throw a proper exception which tells the dev that the function/method he is trying to use requires a `Context` (which means needs to be called within a `task()`)

**Comment by elfet** [comment]
> if this is the case it would be great to throw a proper exception which tells the dev that the function/method he is trying to use requires a Context (which means needs to be called within a task())
This will be cool. Can you create PR with this?

**Comment by elfet** [comment]
> if this is the case it would be great to throw a proper exception which tells the dev that the function/method he is trying to use requires a Context (which means needs to be called within a task())

@staabm this will be cool. Can you create PR with this?

**Comment by staabm** [comment]
Will do
