### ISSUE TITLE
Missing docker image from documentation

### ISSUE THREAD

**Issue by esteban-serfe** [deployphp/deployer#3738]
I'm following the steps indicated here: https://deployer.org/docs/7.x/ci-cd#gitlab-cicd

But the docker image deployerphp/deployer:7 is not found ( see https://hub.docker.com/search?q=deployphp%2Fdeployer )

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3738">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3738/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3738/pledge.svg">
</picture>
</a>

**Comment by mfickers** [comment]
See #3118 for some suggestions of alternative images.

**Comment by Konafets** [comment]
As a workaround I installed Deployer globally via composer.
