### ISSUE TITLE
Use * wildcard in shared files

### ISSUE THREAD

**Issue by marcosh** [deployphp/deployer#374]
This would be a nice feature to have. For example in Zend Framework 2 you have a lot of local (meaning git ignored) configuration files. It would be nice to be able to share them using a wildcard like `*.local.php`.

I realize that this goes againts the fact that the actual implementation creates the declared shared files if they are not there. Using a wildcard like the above mentioned one would create an actual `*.local.php` file.

Maybe we could have some optional configuration setting to say that the shared files needs to be created or not, or we could just simply search the file name and avoid the creation of the file if we find a * wildcard.

What do you think?

**Comment by elfet** [comment]
This is a way of bugs %) 
Why you need this functionality?

**Comment by marcosh** [comment]
As I said in Zend Framework applications you could have a lot of configuration files, all ending in `.local.php`. I would like to avoid the need to modify my `deploy.php` file everytime I add a new configuration file. It would be easier if all the `*.local.php` files were automatically shared every time.

On the other hand, I would have to create my config files in the `shared` directory, but anyhow I would have to put some content into them even I created them automatically.

Why do you think it could generate bugs?

**Comment by hummer2k** [comment]
@marcosh maybe this will help: [environment-specific application config of zf2](http://framework.zend.com/manual/current/en/tutorials/config.advanced.html#environment-specific-application-configuration)

**Comment by tautelis** [comment]
Our team is also in need of this wildcard feature. I would like to contribute to have it.

**Comment by tforesti** [comment]
Hi, I think I need the same feature : I work on a multi-sites app and each site's admin can upload images for example. And these images are to be shared between releases.

Do you confirm that rigth now there is not feature which does this job and that this issue can does what I want ?

If yes do you have an idea on when this feature will be available ?

Thank you for your work.
