### ISSUE TITLE
Change releases_list to a space separated string in YAML

### ISSUE THREAD

**Issue by ronald2wing** [deployphp/deployer#3740]
Right now, the releases_list throws an error in YAML. It would be helpful to turn it into a string to use in string.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3740">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3740/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3740/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I didn't get it. In YAML?

**Comment by ronald2wing** [comment]
Code:
![Screenshot from 2023-12-05 20-56-28](https://github.com/deployphp/deployer/assets/16713673/e0943dab-c155-4f53-8f4b-85a9885057c7)
Error:
![Screenshot from 2023-12-05 20-56-05](https://github.com/deployphp/deployer/assets/16713673/8e057498-a511-4f2a-a57c-cfaff232cb93)
