### ISSUE TITLE
Current PHAR build does not fallback to deploy_path.

### ISSUE THREAD

**Issue by naquad** [deployphp/deployer#376]
I've downloaded recent `deployer.phar` and tried to migrate my projects. The problem I've experienced is that deployer doesn't change working directory to `deploy_path` one while documentation states it should. Setting undocumented variable `working_path` solved the issue, but I'm not sure it is a right solution. Rebuild the PHAR from master? Describe `working_path`?

**Comment by elfet** [comment]
`working_path` for `cd` and `run` functions. 
`deploy_path` for common.php recipe.

**Comment by elfet** [comment]
Please provide you deploy.php file/

**Comment by naquad** [comment]
http://deployer.org/docs/functions :
Quote:

```
run(string $command)
Runs a command on a remote server in the working path (server(...)->env('deploy_path', '/home/path')).
```

**Comment by naquad** [comment]
My deployer.php: https://gist.github.com/00e2e739dae4045ea809

**Comment by johnny-bit** [comment]
Wow, seems like Your code could benefit from migrating to 3.0 + using `deployphp/recipes` for new relic :smile: a lot of that is obsoleted by common.php + newrelic.php.
