### ISSUE TITLE
Allow variable for shared path

### ISSUE THREAD

**Issue by lfolco** [deployphp/deployer#3762]
Currently, in the `[shared.php](deploy:shared)` it gets the shared path as a child of the deploy path:

```
task('deploy:shared', function () {
    $sharedPath = "{{deploy_path}}/shared";
    ...
}
```

We have a multi-site setup where the `shared` directory is a sibling of our other sites. It would be great if we could specify that `sharedPath` variable in `deploy.php`.

Thanks!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3762">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3762/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3762/pledge.svg">
</picture>
</a>

**Comment by Schrank** [comment]
Hey @lfolco 👋 

Did you try to do it manually and run it though [parse()](https://deployer.org/docs/7.x/api#parse) ?

```
task('deploy:shared', function () {
    $sharedPath = parse("{{deploy_path}}/shared");
    ...
}
```

**Comment by lfolco** [comment]
Not sure I follow, in our setup our shared path does not reside within our deploy directory at all:

```
<root>/shared
-------site1
-------site2
<root>/site1
<root>/site2

So within the `deploy:shared` task, I would need to set the private variable `$sharedPath` (trying to avoid overriding the task if possible)

**Comment by Schrank** [comment]
NOW I get what you want. I assumed, that the shared path is a variable you could use like `{{shared_path}}` and somewhere is a `set('shared_path', function() {... })` - but this is not the case 😮 

I think this is something worth implementing 🤔 

Then you could just overwrite the set and do whatever you want.
