### ISSUE TITLE
Support Symfony V6

### ISSUE THREAD

**Issue by Sven-TS** [deployphp/deployer#3776]
Symfony's v6 LTS was released in November 2023 and we would like to upgrade our Symfony 5 projects to Symfony 6.

The deployer dependency currently blocks the update, because it requires some symfony packages in v5. Dependencies from composer.json:

```
"symfony/console": "^5.4.9",
"symfony/process": "^5",
"symfony/yaml": "^5"
```

If the symfony packages would be supported in v6 it would enable projects to move to symfony v6 and still using the deployer package.

**Comment by antonmedv** [comment]
It will not be blocked as Deployer dependencies are bundled: https://packagist.org/packages/deployer/deployer

**Comment by Sven-TS** [comment]
Thanks, my bad. Was working with an older version of Deployer and it was a conflict there. Fixed in the newer versions.
