### ISSUE TITLE
Strange filenames

### ISSUE THREAD

**Issue by agantelin** [deployphp/deployer#378]
After deploying my project I get plain file stucture (no subdirectories) and strange filenames instead of correct directory structure.
Directories names looks like:
i\1x\logos
i\2x\logos

Filenames looks like:
i\2x\logos\mk_logo.png
j\j-d295da88.js
s\s-d87a8841.css

It worked well with Deployer 2.0.2.
How can I fix it?

**Comment by ZeeCoder** [comment]
Hi!
A lot changed since v2.
Either you should use deployer v2.0.2, or you should update your configurations.

**Comment by agantelin** [comment]
I've updated my config.
I'am deploying from Windows 8.1 to Ubuntu 14.04 (if it is important).

Current deploy.php:

<?php 
    require 'recipe/common.php';

// CONFIG
    // local config
    define( 'project_name',                 'app_name' );
    define( 'local_path',                   'C:/path/to/build_production' );

    // production server config
    define( 'remote_production_host',       '111.222.333.444' );
    define( 'remote_production_port',       '12345' );
    define( 'remote_production_username',   'user' );
    define( 'remote_production_password',   'pass123' );
    define( 'remote_production_path',       '/var/www/app_name/public_html' );

// JOBS
    server('prod', remote_production_host, remote_production_port)
        ->user(remote_production_username)
        ->password(remote_production_password)
        ->env('deploy_path', remote_production_path)
        ->stage('production');

    task('upload_'.project_name, function () {
        upload(local_path, remote_production_path);
    })->desc('Uploading '.project_name);

    task(project_name, ['upload_'.project_name]);

**Comment by elfet** [comment]
Each. It's a bug with file names on Windows.  Need replace all `\` to `/`.
@deployphp/maintainer can anyone take care of this?
