### ISSUE TITLE
Handling of ProcessTimedOutException is unreliable

### ISSUE THREAD

**Issue by jimwins** [deployphp/deployer#3782]
The output of the `ps x | ...` command is not checked to see if a PID was actually retrieved. This can happen with a command that is long enough that the `$shellId` doesn't appear because it's only using `ps x` instead of `ps wwx`.

You could also eliminate the use of grep by making it: `ps wwx | awk '/$shellId/ && !/awk/ {print \$1; exit}'`

https://github.com/deployphp/deployer/blob/51e8e82c0726b0386d2989c42df003899d35af8a/src/Component/Ssh/Client.php#L96-L99

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3782">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3782/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3782/pledge.svg">
</picture>
</a>

**Comment by sebastiaanluca** [comment]
Running into this issue and took me a while to found the cause.

```
run ps x | grep 0654ffdedac0da1120a3 | grep -v grep | awk '{print $1}'
run kill -9 -
bash: line 1: kill: -: arguments must be process or job IDs
```

```
run("docker service update --force php");
```

**Comment by svycka** [comment]
I ran into this. Is this fixed?

**Comment by antonmedv** [comment]
Fixed in https://github.com/deployphp/deployer/releases/tag/v8.0.5
