### ISSUE TITLE
Error handling multiple cachetool options when cachetool variable is empty

### ISSUE THREAD

**Issue by daniDLL** [deployphp/deployer#3784]
- Deployer version: > 7.3.1
- Deployment OS: Debian Buster

By default the value of the "cachetool" variable is empty "", but with the latest changes since version 7.3.2 when including a for loop it does not check that the $option can be empty and therefore it tries to execute the opcache:reset with the --fcgi flag with an empty value "" which throws an exception:

`Unable to connect to FastCGI application: Invalid argument`

**Comment by gbobts** [comment]
Could this be fixed by #3742 ?
https://github.com/deployphp/deployer/commit/11cef7404e88e3467a7d476e780fdff469b9b38c#diff-3ff1b6689a573050ee941e9cf0474c9f96a4ff7697a386d9c1af6b320fc10ce6R75

**Comment by daniDLL** [comment]
Yes, with this change it would be solved, I close this issue, although as of today this change has not yet been tagged.

**Comment by antonmedv** [comment]
Yeap. Will release

**Comment by gbobts** [comment]
Hello @antonmedv could you communicate a release date ? do you need any help with reviewing or something?

**Comment by antonmedv** [comment]
Hey! I just got busy with other project. Will try to release today.

**Comment by antonmedv** [comment]
Hey! Just got busy with other project. Will try to release today.
