### ISSUE TITLE
Gitlab CI collapsible sections use unique section header name.

### ISSUE THREAD

**Issue by fliespl** [deployphp/deployer#3787]
Currently script uses unix timestamp ($start) as both start time + section name (same goes for section_end - using $start).

This causes collision within multiple tasks running in the same second cause it's used by gitlab for grouping.
```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$start}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$start}\r\e[0K");
```

I think better solution is to use slug of task name:

```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$slug}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$slug}\r\e[0K");
```

or to be more "unique" - combination of task name slug + startTime:

```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$slug}_{$start}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$slug}_{$start}\r\e[0K");
```

**Comment by mbrodala** [comment]
@antonmedv Can you make a new release with this change? I would like to test it but cannot apply it as change since `dep` is a Phar in releases.

**Comment by antonmedv** [comment]
Will do a release.

**Comment by mbrodala** [comment]
Unfortunately this still doesn't work well with tasks like this:

```php
desc('Clean up old local releases');
task('local:cleanup', function () {
    on(localhost(), function (): void {
        invoke('deploy:cleanup');
    });
})->once();
```

Our `deploy` task:

```php
task('deploy', [
    // ...
    'deploy:cleanup',
    'local:cleanup',
    // ...
]);
```

So strictly speaking the `deploy:cleanup` task is run twice but once for the remote host and once for the local host.

**Comment by mbrodala** [comment]
@antonmedv Would you accept an adjustment so that `Messenger:startTask()` and `::endTask()` also get the processed host? Then the section should be unique.

**Comment by antonmedv** [comment]
I think yes. I'm now in big refactoring so we can introduce those changes.
