### ISSUE TITLE
Shopware recipe

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#3799]
I'm currently trying the current shopware recipe and I think I'm missing something.

Three things I don't understand and would love to fix (therefore an issue an no discussion):

- The JS is build locally but not uploaded - isn't it?
- `composer install` is not called and uploaded

Am I missing something or is the recipe incomplete?

My current fix is to call composer install on the remote host and I ran theme:compile manually. If you explain to me how it is expected to work I'm happy to fix it - either the docs or the code :-)

cc @UlrichThomasGabor @peterjaap 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3799">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3799/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3799/pledge.svg">
</picture>
</a>

**Comment by UlrichThomasGabor** [comment]
My intention was to not build anything on the remote host. `composer install` is missing and could be added, but I'd call it locally for my use-case.

JS should be uploaded? Whole directory should be uploaded? `deploy:update_code` should do that

**Comment by Schrank** [comment]
Thanks for the quick answer! https://github.com/deployphp/deployer/blob/master/recipe/deploy/update_code.php doesn't contain any upload, maybe you are using https://github.com/deployphp/deployer/blob/master/contrib/rsync.php ?

**Comment by UlrichThomasGabor** [comment]
Ah, hm.

Yes, I have overwritten `'deploy:update_code'` to use [`upload()`](https://github.com/deployphp/deployer/blob/95acd35c2164ef03730cb7dd2c48172ef610f547/src/functions.php#L582). But this function seems to be not really in wide use.

Question is, what is the goal of this recipe.

I have mainly used it to build locally and push that onto a remote server. If this is the goal, then I guess update_code should be replaced with rsync or something like that, such that the recipe works without overwriting tasks.

Building on the remote server, I'd actually try to achieve with shopware build-ins? Especially with the growing support of composer, it seems to me that the board means are there to achieve that and a deployer recipe is not necessary?

**Comment by antonmedv** [comment]
> I have mainly used it to build locally and push that onto a remote server. If this is the goal, then I guess update_code should be replaced with rsync or something like that, such that the recipe works without overwriting tasks.

Yeap. Lets update the recipe.

**Comment by Schrank** [comment]
Will take care of it. Have a working prototype, except the theme is not used on production 🤪
