### ISSUE TITLE
contrib/rsync set('rsync_src', __DIR__); returns phar:///.../contrib/

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#3801]
- Deployer version: 7.3.3
- Deployment OS: MacOS

Using rsync.php with default parameter and deployer.phar returns unexpected result for __DIR__ - because the php file is inside a phar :-)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3801">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3801/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3801/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Is it possible to override __DIR__?

**Comment by Schrank** [comment]
It is. Technical all fine. IMHO a minor DX issue.
