### ISSUE TITLE
Incompatible declaration when using AWS SDK in deploy.php

### ISSUE THREAD

**Issue by seb-enovate** [deployphp/deployer#3807]
- Deployer version: 7.3.3

We are using the AWS SDK within our `deploy.php` file to fetch some data that we need for our deployments. However, since upgrading to more recent versions of the AWS SDK (version 3.303.4 in our case) we have been getting the following error when doing deploys (truncated for brevity):

```
PHP Fatal error:  Declaration of RingCentral\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string in phar:///root/.composer/vendor/deployer/deployer/dep/vendor/ringcentral/psr7/src/Request.php on line 63
PHP Stack trace:
PHP   1. {main}() /root/.composer/vendor/bin/dep:0
PHP   2. include() /root/.composer/vendor/bin/dep:119
PHP   3. require() /root/.composer/vendor/deployer/deployer/dep:4
PHP   4. Deployer\Deployer::run($version = '7.3.3', $deployFile = '/builds/clients/target-zero-booking-system/deploy.php') phar:///root/.composer/vendor/deployer/deployer/dep/bin/dep:96
...
```

I believe the issue is that the AWS SDK changed their version constraint of the `psr/http-message` package to allow either 1.x or 2.x in [this commit](https://github.com/aws/aws-sdk-php/commit/84d4539e72daf415e1d421dcaa0f76e607d1fd48#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R28).

Now Deployer's [version constraint for the same package](https://github.com/deployphp/deployer/blob/master/composer.json#L47) is `^1`, and I think this is allowing the package to jump to 2.x somehow.

Running the following command in my project that uses Deployer fixes the issue:

```sh
composer require "psr/http-message" "^1.1"
```

I also note that in the output of that composer command it says the following: 

```
  - Downgrading psr/http-message (2.0 => 1.1)
```

So I think that the `psr/http-message` version constraint in Deployer's `composer.json` needs to be updated to be more restrictive and prevent that package jumping to 2.x.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3807">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3807/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3807/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Do you ise Deployer at master?

**Comment by seb-enovate** [comment]
Hi Anton,

We are using version 7.3.3, if that is what you are asking?

Thanks

Seb

**Comment by antonmedv** [comment]
This is strange b/c deployed tagged version comes bunddled. No dependencies.

**Comment by seb-enovate** [comment]
Not sure if this is helpful but we are installing Deployer like this:

```sh
composer require "deployer/deployer" "^7.0.1"
```

And then installing the AWS SDK like this:

```sh
composer require "aws/aws-sdk-php"
```

**Comment by antonmedv** [comment]
@mtwalsh I guess you're using master branch. Try to switch a version tag.

**Comment by harmenjanssen** [comment]
I can confirm this is an issue. Running into it with Deployer `7.4.0` and AWS SDK `3.316.0`.

**Comment by Schrank** [comment]
Two approaches for solutions I have on my mind:
- have a seperate composer.json file for deployer (this is what we do, mainly, because we don't want composer to dictate our php version or dependency versions 🙈 )
- use deployer.phar file.

**Comment by Schrank** [comment]
Maybe that helps: https://andreas.heigl.org/2024/06/02/of-tools-and-dependencies/

**Comment by harmenjanssen** [comment]
> Maybe that helps: https://andreas.heigl.org/2024/06/02/of-tools-and-dependencies/

Hmm, that's an interesting philosophy. I was not aware that you could actually use multiple composer.json files.
Thanks for sharing!

**Comment by FrancescoASessa** [comment]
Hi, any update?

**Comment by antonmedv** [comment]
We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.

**Comment by antonmedv** [comment]
I think what we need to do is to vendor all symphony dependencies. Create a subject inside deploy rename all the namespaces. Delete all dependencies from composer

**Comment by antonmedv** [comment]
I started v8 in master branch! Now it is fully fixed.
