### ISSUE TITLE
Run function does not run functions from the deploy_path

### ISSUE THREAD

**Issue by antonydandrea** [deployphp/deployer#381]
In the documentation it says 
Runs a command on a remote server in the working path (server(...)->env('deploy_path', '/home/path')).

But when I run 'pwd', I found the working path was the home directory of the user. Either there is a bug or the documentation is wrong?

**Comment by ihsanudin** [comment]
all command run using ``cd {{release_path}} && [[comman]]``

**Comment by peterjaap** [comment]
This also happens when a command is run through a hook (after);

```php
after('elgentos:test', 'elgentos:test2');
```

```bash
➜  project git:(master) ✗ dep elgentos:test staging
➤ Executing task elgentos:test
/home/elgentos/project

✔ Ok
➤ Executing task elgentos:test_next
➤ Executing task elgentos:test_next
/home/elgentos
```

**Comment by elfet** [comment]
Will look close on it.

**Comment by elfet** [comment]
There was bug with `working_path`, indeed. But for now it's about 1.5 years since bug was discovered. And this become default behavior. So i'm thinking to save this behavior and update docs: `run` executes command in user home dir. If you want to change to `deploy_path` used `cd1 function:
```php
task('...', function () {
    cd('{{deploy_path}}');
    run('pwd');
});
```

**Comment by elfet** [comment]
Or use short syntax:
```php
task('hook', '
    cd {{deploy_path}};
    pwd;
');
```

**Comment by elfet** [comment]
👁 17dcad7b3b28e6455423e26baff13f036ddb62ab

**Comment by naquad** [comment]
This is a :man_facepalming: kind of behavior: every task now needs to `cd('{{deployment_path}}');`. It breaks DRY principle + it is error prone (recipe maintainer can forget to do it or forget to change it).

I've tried `before('deploy:*', 'a_hack:cd_to_deployment'');` and `->set('working_path', '/path/to/deployment')` both didn't work.

Usually project is residing in a single folder that is not user home directory and it makes sense to `cd {{deployment_path}}` for isolation and convenience. Documentation doesn't state that default directory is user home directory either.

Even if you don't want to change the default behavior it would be awesome if you would provide some workaround like optional setting `default_path` or similar setting to be used as a fallback in case if one needs to run all commands in given directory.

Thank you.

**Comment by antonmedv** [comment]
>  makes sense to cd {{deployment_path}} for isolation and convenience.

Maybe this will go to v5 (it still in beta). I don't like to cding to release path too. But i think what task should be without side effects as possible (cd in one mustn't effect working_path in another one)

> default_path or similar setting

Try this:
```php
set('working_path', '{{release_path}}');
```

If you can add this to docs (and more stuff what you this necessary about cding) will be really cool.

**Comment by naquad** [comment]
Working path didn't work :( https://github.com/deployphp/deployer/blob/master/src/Task/Task.php#L87

**Comment by antonmedv** [comment]
Yeah, this should be fixed.
