### ISSUE TITLE
Shopware recipe always updates all plugins

### ISSUE THREAD

**Issue by TimWuyts** [deployphp/deployer#3811]
I've noticed that the "sw:plugin:update:all" task for the Shopware recipe is always updating all plugins, not taking into account the "upgradeVersion" field correctly. Whenever this field is set to a null value, the update is still triggered.

https://github.com/deployphp/deployer/blob/a8a16c755ea5062510f6b519f0e63123a5abd1ea/recipe/shopware.php#L117

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3811">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3811/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3811/pledge.svg">
</picture>
</a>

**Comment by Schrank** [comment]
That sounds like a shopware problem to me and the command should be fixed in the core :-)

**Comment by UlrichThomasGabor** [comment]
Shopware has prepared a [shopware/deployment-helper](https://github.com/shopware/deployment-helper), which could render that custom code of the recipe obsolet, see [the demo code](https://gist.github.com/shyim/f6ca5ee0fc11462bb30edaf7d206edd1#file-deploy-php-L46) by @shyim.
