### ISSUE TITLE
manifest.json deprication

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3814]
Keeping manifest.json in sync with git and GH releases is too much toil. I have a plan to remove it with self-update command from Deployer. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3814">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3814/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3814/pledge.svg">
</picture>
</a>

**Comment by RemiHin** [comment]
Is this why my deployments are failing? Its trying to get the manifest, but its failing. The entire deployer.org website seems down (?)

**Comment by aristidesneto** [comment]
> Is this why my deployments are failing? Its trying to get the manifest, but its failing. The entire deployer.org website seems down (?)

Here same problem
