### ISSUE TITLE
deploy.php for laravel error

### ISSUE THREAD

**Issue by mani95lisa** [deployphp/deployer#382]
> Deployer 3.0.6 on mac

When I use this:
```php
require 'recipe/laravel.php';
server('prod1')
    ->user('root')
    ->env('deploy_path', '/var/www/deploy')
    ->env('branch', 'master')
    ->stage('production');
```
then run `dep deploy -p production` I got error `Unable to login with the provided credentials.  ` .

I find the server default use config file `~/.ssh/config` to auth from source code. I can use `ssh prod1` to login server. 

When I add `->configFile('~/.ssh/config')`, I got error ` You need to specify authentication method.  ` It's very strange.

So anybody know what's the problem, how can I fix it?

Thanks!

**Comment by mani95lisa** [comment]
Hello, anybody here? Is it a bug?

I'm not  clear how to debug or develop deployer, I want to help, is there any development intro?

Thanks!

**Comment by oanhnn** [comment]
Dear @mani95lisa,
Using config file for authentication only be supported by `ext-ssh2`.
Please try install `ext-ssh2` and add this line to `deplo.php` file:
```php
require 'recipe/laravel.php';
set('ssh_type','ext-ssh2'); // <-- add this line
server('prod1')
    ->user('root')
    ->env('deploy_path', '/var/www/deploy')
    ->env('branch', 'master')
    ->stage('production');
```
Otherwise, please try other authentication method.

**Comment by mani95lisa** [comment]
@oanhnn Thanks，I installed ssh2, and error gone, but new problem got.

```shell
dep deploy -p production -vvv
➤ Executing task deploy:prepare
⤷ on [prod]
```

Whatever I use `config` or `servers.yml` or `identityFile` method to deploy, I got above informations.
And progress is paused, no error or anything else.

```php
require 'vendor/autoload.php';
require 'vendor/deployer/deployer/recipe/laravel.php';

set('ssh_type', 'ext-ssh2');

$server = server('prod1')
    ->user('root')
    ->env('deploy_path', '/var/www/deploy')
    ->env('branch', 'master')
    ->stage('production');

set('repository', 'git@git.rsct.com:mani/rsct-backend.git');
```

Please have a look, thanks!
