### ISSUE TITLE
Add Nuxt JS deploy recipe

### ISSUE THREAD

**Issue by sts-ryan-holton** [deployphp/deployer#3823]
Hi, I'd like to be able to deploy a Nuxt JS project. Nuxt JS when generated as a static site dynamically figures out whether it needs to regenerate the project after each deployment by looking at some folders outside of Git. Since deployer creates a new release folder each time and does `npm run generate` from within, it effectively takes a long time on every deployment because it doesn't know about what's changed.

Can you create a recipe for this?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3823">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3823/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3823/pledge.svg">
</picture>
</a>

**Comment by sts-ryan-holton** [comment]
Is this something that might be implemented?

**Comment by Schrank** [comment]
Hi @sts-ryan-holton, thanks for opening this issue. I think this is something we might add as a contribution, but I guess it is nothing we want to implement and maintain, so feel free to PR a recipe and take care of it :-)
