### ISSUE TITLE
Deploy all hosts asynchronously rather than synchronously

### ISSUE THREAD

**Issue by sts-ryan-holton** [deployphp/deployer#3827]
I'm using the latest version of Deployer to deploy my Nuxt JS project to multiple ipv6 hosts. If I were to deploy one host individually, it wouldn't take no more than 5 minutes. But when defining multiple hosts, it seems that it deploys synchronously through each one, I'd like to be able to configure it to deploy to all at the same time because it takes over an hour right now, additionally, if something fails, then deployments to all hosts fail and are locked which is quite frustrating.

What are your thoughts?

This is my deployment hosts:

```php
host('a420:c3d3:ba97:c042:deff:8a15:fbfd:6276', 'c7b3:ea23:e29f:2564:8187:13aa:d2f3:bf36', 'ae7c:af20:e51d:1449:cc45:7e07:644f:33ba')
    ->set('branch', 'main')
    ->stage('all')
    ->set('repository', 'git@fudge:company/project)
    ->user('root')
    ->set('deploy_path', '/var/www/include-forms/fudge');
```

And I deploy running:

```bash
dep deploy all
``` 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3827">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3827/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3827/pledge.svg">
</picture>
</a>

**Comment by Schrank** [comment]
From the doc:
> Deployer runs a task in parallel on each host. This is why the output is mixed. We can limit it to run only on one host at a time.

This should be the default. Are you saying this doesn’t work for you?

can you check -vvv?

**Comment by sts-ryan-holton** [comment]
It seems to take a long time. 41 minutes to deploy to around 20 - 25 hosts

**Comment by Schrank** [comment]
Please try

    dep deploy all -vvv

then you see wether it works parallel or not.

**Comment by antonmedv** [comment]
> additionally, if something fails, then deployments to all hosts fail and are locked 

This is a feature of Deployer ʕっ•ᴥ•ʔっ

Deployer tried to keep all deployment hosts in sync (as Deployer does not know if it is save to deploy only to one host and allow other to fail).

This feature was requested a few times and I think it will be nice to add a simple API to configure deploy to run deploys not in sync.

Right now you can do:

 - Create a separate bash script to start each deploy to each host simultaneously: 

```bash
dep deploy host1 &
dep deploy host2 &
dep deploy host3 &
```

**Comment by sts-ryan-holton** [comment]
How do I know if parallel deploying is working with that flag?

**Comment by sts-ryan-holton** [comment]
@antonmedv It was working. Turned out I was looking at the wrong deployer version. Additionally though, linked to a newer Github issue. How can I deploy to one server in parallel model across many alias folders here:

```php
$sites = ['site1', 'site2'];

// Site: Fudge
foreach ($sites as $site) {
    host("ipv6/$site")
        ->set('labels', ['stage' => 'forms', 'site' => $site])
        ->set('repository', 'git@application-fudge:company/application-fudge')
        ->set('branch', 'feature/fudge_v2')
        ->set('remote_user', 'root')
        ->set('deploy_path', "/var/www/forms/fudge/$site");
}
```
