### ISSUE TITLE
automatic docs generation places Shopware docs link into all recipe docs

### ISSUE THREAD

**Issue by SimJoSt** [deployphp/deployer#3831]
Since https://github.com/deployphp/deployer/commit/d34b80f3f2b11d438a6fec3a9f5d7151d7190670 through https://github.com/deployphp/deployer/pull/3816 the automatic docs generation commit change the following line from 
```
  * [deploy:update_code](/docs/recipe/deploy/update_code.md#deployupdate_code) – Updates code
```
to
```
  * [deploy:update_code](/docs/recipe/shopware.md#deployupdate_code) – 
```
for all recipes, not just the Shopware one.

Here are some of the commits of the automatic docs generation that I observed this in:
- https://github.com/deployphp/deployer/commit/04c592686088f3437fa5d465e78a9c79109eff8d
- https://github.com/deployphp/deployer/commit/c859acec70718bb7c4590cddebd02cabbb976e28
- https://github.com/deployphp/deployer/commit/04c592686088f3437fa5d465e78a9c79109eff8d

I'm not sure why this is happening, as it does not occur when I run `bin/docsgen` on my local machine with the same commit.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3831">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3831/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3831/pledge.svg">
</picture>
</a>

**Comment by M-arcus** [comment]
I have posted it into the discussions https://github.com/deployphp/deployer/discussions/3918
