### ISSUE TITLE
`bin/docgen` expands curly braces, even if they are marked as code

### ISSUE THREAD

**Issue by SimJoSt** [deployphp/deployer#3832]
Syntax in recipe docs like this
```
`{{static_content_locales}}`
```
gets converted by `bin/docgen` to this for the docs
```
`[static_content_locales](/docs/recipe/magento2.md#static_content_locales)`
```

Maybe it could make sense to only expand curly braces, if they are not marked as code.
This is already the case, if text is part of a code block.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3832">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3832/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3832/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Makes sense.
