### ISSUE TITLE
kex_exchange_identification read: Conneciton reset by peer error

### ISSUE THREAD

**Issue by sts-ryan-holton** [deployphp/deployer#3848]
- Deployer version: ^7.4

- Deployment OS:

I'm trying to deploy to multiple folders at once on my single server. I'm experiencing when I run `deploy:unlock` intermittently:

```
[ip/site1]  error  in lock.php on line 21:
[ip/site1] run rm -f /var/www/forms/fudge/yesmoney/.dep/deploy.lock
[ip/site1] err kex_exchange_identification: read: Connection reset by peer
[ip/site1] err Connection reset by ip port 22
[ip/site1] exit code -1 (Unknown error)
```

I've tried a combination of:

```php
set('ssh_multiplexing', false);
```

and 

```php
set('ssh_multiplexing', true);
```

Additionally, I've allowed more SSH connections on my server. What am I missing?

My deploy.php file:

```php
<?php

namespace Deployer;

require 'recipe/common.php';
require 'contrib/npm.php';

require 'deploy/recipe/fudge-composer.php';
require 'deploy/recipe/fudge-nuxt.php';

// Project repository
set('repository', 'git@application-fudge:company/application-fudge.git');

// Shared files/dirs between deploys
add('shared_files', ['.env', 'brand-theme.scss']);

// Set number of releases to keep
set('keep_releases', 2);

// Timeout
set('default_timeout', 3600);

// Disable multiple SSH connections
set('ssh_multiplexing', false);

// Writable dirs by web server
set('allow_anonymous_stats', false);

$sites = ['site1', 'site2'];

foreach ($sites as $site) {
    host("2001:b98:301:1d00:250:56ff:fe8f:f50b/$site")
        ->set('labels', ['stage' => 'forms', 'site' => $site])
        ->set('repository', 'git@application-fudge:company/application-fudge')
        ->set('branch', 'feature/fudge_v2')
        ->set('remote_user', 'root')
        ->set('deploy_path', "/var/www/forms/fudge/$site");
}

after('deploy:update_code', 'npm:install');
after('npm:install', 'deploy:vendors');
after('deploy:writable', 'nuxt:generate');
after('deploy:failed', 'deploy:unlock');
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3848">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3848/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3848/pledge.svg">
</picture>
</a>

**Comment by haguiar-monsoon** [comment]
@sts-ryan-holton Same issue here. Do you solved it?

**Comment by haguiar-monsoon** [comment]
@sts-ryan-holton Just for your knowledge. I fixed the issue configuring `['-o UserKnownHostsFile=/dev/null']` in the ssh_arguments parameter.

**Comment by sts-ryan-holton** [comment]
Where abouts did you put that in the Deployer file? Could you provide an example?

**Comment by haguiar-monsoon** [comment]
@sts-ryan-holton 
`
host('127.0.0.1')->set('remote_user', 'user')->set('ssh_arguments', ['-o ProxyJump=usert@host', '-o StrictHostKeyChecking=no', '-o UserKnownHostsFile=/dev/null']`

**Comment by sts-ryan-holton** [comment]
This didn't work for me

**Comment by haguiar-monsoon** [comment]
@sts-ryan-holton I also added this config in the server that is doing the connection:

vim $HOME/.ssh/config

Host *
    StrictHostKeyChecking no
