### ISSUE TITLE
Hide progress bar

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3854]
### Discussed in https://github.com/deployphp/deployer/discussions/3853

<div type='discussions-op-text'>

<sup>Originally posted by **gponty** June 24, 2024</sup>
Hi,

Is it possible to hide progress bar ?
Because in github action it's ugly : 

![image](https://github.com/deployphp/deployer/assets/34276317/2e7f5544-e960-4dcf-9a86-1169338973f0)

ty</div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3854">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3854/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3854/pledge.svg">
</picture>
</a>

**Comment by sebastiaanluca** [comment]
It also prevents me from entering `yes` to accept the new host key 😬 

```
  ⠴  e type 'yes', 'no' or the fingerprint:   ⠹
  ⠇  e type 'yes', 'no' or the fingerprint:   ⠴
  ⠙  e type 'yes', 'no' or the fingerprint:   ⠇
  ⠸  e type 'yes', 'no' or the fingerprint:   ⠙
  ⠧  e type 'yes', 'no' or the fingerprint:   ⠼
  ⠋  e type 'yes', 'no' or the fingerprint:   ⠧
  ⠸  e type 'yes', 'no' or the fingerprint:   ⠋
  ⠦  e type 'yes', 'no' or the fingerprint:   ⠸
  ⠏  e type 'yes', 'no' or the fingerprint:   ⠦
  ⠹  e type 'yes', 'no' or the fingerprint:   ⠋
  ⠦  e type 'yes', 'no' or the fingerprint:   ⠸
  ⠇  e type 'yes', 'no' or the fingerprint:   ⠦
  ⠋  e type 'yes', 'no' or the fingerprint:   ⠏
  ⠸  e type 'yes', 'no' or the fingerprint:   ⠙
  ⠴  e type 'yes', 'no' or the fingerprint:   ⠸
  ⠧ se type 'yes', 'no' or the fingerprint:   ⠴
[host] Host key verification failed.
[host]  error  in setup.php on line 6:
[host] exit code -1 (Unknown error)
```

**Comment by antonmedv** [comment]
> It also prevents me from entering yes to accept the new host key 😬

Use accept-new
