### ISSUE TITLE
Every step/task throws `getsockname failed: Bad file descriptor` error

### ISSUE THREAD

**Issue by zigi05** [deployphp/deployer#3855]
- Deployer version: 7.4.0
- Deployment OS: Windows 10

Unable to deploy, every step/task throws the following error:
![image](https://github.com/deployphp/deployer/assets/10746393/8c5d0075-c4d5-43cc-8611-ef2226486af6)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3855">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3855/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3855/pledge.svg">
</picture>
</a>

**Comment by docmedicus-support** [comment]
We have exactly the same problem...

**Comment by zigi05** [comment]
@docmedicus-support I fixed it by disabling `ssh_multiplexing`

**Comment by docmedicus-support** [comment]
@zigi05 Thanks for your reply! Just found this fix in another thread as well. All working now...
