### ISSUE TITLE
I cannot init.

### ISSUE THREAD

**Issue by tkaneda** [deployphp/deployer#3868]
Hi, all.
I got latest version

```
$ curl -LO https://Deployer.org/Deployer.phar
$ sudo mv Deployer.phar /usr/local/bin/dep
```

and executed  init.

```
$ mkdir Deployer
$  cd Deployer
$ dep init
/usr/local/bin/dep: line 1: syntax error near unexpected token `newline'
/usr/local/bin/dep: line 1: `<!doctype html>'
```
Can I recover this ?

thanks.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3868">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3868/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3868/pledge.svg">
</picture>
</a>

**Comment by ozyab** [comment]
Your link for phar is wrong (https://deployer.org/docs/6.x/installation#download-phar-archive). 

Use this one `https://deployer.org/deployer.phar`

Furthermore, consider to use v7 instead of 6

**Comment by tkaneda** [comment]
Thanks.

I got from https://deployer.org/deployer.phar  and retry dep init.
I got error,  "Call to undefined function Deployer\Utility=posix_setsid()", 
so I install php-process extension and retry dep init.

I got deploy.php successfully.

Thanks. 
Regards.
