### ISSUE TITLE
Provisioning throws error on nodejs version

### ISSUE THREAD

**Issue by ricohumme** [deployphp/deployer#3884]
- Deployer version:  7.4.0
- Deployment OS: Ubuntu 24

Ign:9 https://deb.nodesource.com/node_16.x noble InRelease
Err:10 https://deb.nodesource.com/node_16.x noble Release
  404  Not Found [IP: 172.67.10.205 443]
Reading package lists...
E: The repository 'https://deb.nodesource.com/node_16.x noble Release' does not have a Release file.

I have also tried node_20.x, setup_20.x, node_22.x and setup_22.x with set('nodejs_version', 'XX'), non of which seem to work.
Does anyone have this issues or know of way to fix this

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3884">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3884/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3884/pledge.svg">
</picture>
</a>

**Comment by Glenf** [comment]
This issue happens because Nodesource has changed the distro naming. It's currently `nodistro` codename to allow compatibility to even larger set of distros.

From Nodesource repo (https://github.com/nodesource/distributions)
> Package Changes: DEB and RPM packages are now available under the nodistro codename. We no longer package the installer coupled to specific versions. This means you can install Node.js on almost any distro that meets the minimum requirements.
