### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by carlos-reynosa** [deployphp/deployer#3886]
Maybe the project should keep track of changes in a release through a changelog in source control:

https://keepachangelog.com/en/1.1.0/

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3886">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3886/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3886/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Actually I kept it for a long time before. It was a lot of work.

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/blob/6.x/CHANGELOG.md

**Comment by carlos-reynosa** [comment]
So what I do for other projects I work on is require developers to add to the changelog with their pull requests. They add to a future release section at the top. 

 When the time comes to make a new release I just move all the future release entries into a new entry for the current release being made:

Future Release
  - entry 1
  - entry 2

Version 1.0


Becomes 


Future Release 

Version 1.1
  - entry 1
  - entry 2
