### ISSUE TITLE
The authentication over the current SSH connection failed

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#391]
I installed deployer via composer.
I also installed herzult/php-ssh.

My previous deploy strategy was using capifony, with a key to login on the remote server.

My deploy.php:

```php
<?php

require 'recipe/symfony.php';
set('ssh_type', 'ext-ssh2');
server('stage1', 'full_address_of_my_server')
    ->user('my_user')
    ->stage('staging')
    ->env('deploy_path', '/home/my_user/test_deployer');
set('repository', 'git@bitbucket.org:company/repo.git');
```
When i try to execute ``bin/dep deploy:prepare staging`` I get the exception mentioned in the title (along with a strange message about POSIX compliance of my remote shell, that is a bash)

**Comment by elfet** [comment]
Look like bash does not available on your remove server. %)

**Comment by garak** [comment]
I'm not sure to understand... I can ssh on my remote server and bash is there.
On my remote server:
```bash
$ echo $0
-bash
```

**Comment by erickr** [comment]
I have the same issue, but are using a servers.yml file with the following settings:;
```
production:
  host: localhost
  user: test-prod
  identity_file: ~
  stage: production
  deploy_path: /home/test-prod/production
```

But also get the "  The authentication over the current SSH connection failed.  "
Also using ext-ssh2

Any ideas?

**Comment by oanhnn** [comment]
@erickr 
what is your `ext-ssh` version?
Are you try with `phpseclib`?

**Comment by erickr** [comment]
I'm using php5-ssh2 in debian jessie, 
Package: php5-ssh2                       
New: yes
State: installed
Automatically installed: no
Version: 0.12-3
Priority: extra
Section: php
Maintainer: Debian PHP PECL Maintainers <pkg-php-pecl@lists.alioth.debian.org>
Architecture: i386
Uncompressed Size: 151 k
Depends: phpapi-20131226, php5-common (>= 4.0.0), php5-common (<= 6.0.0), php-pear (>= 1.4.0), libc6 (>= 2.4), libssh2-1 (>= 1.2.9)
Breaks: libssh2-php (< 0.12-2)
Replaces: libssh2-php (< 0.12-2)
Description: Bindings for the libssh2 library
 Provides bindings to the functions of libssh2 which implements the SSH2 protocol.
Homepage: http://pecl.php.net/package/ssh2

I've tried with phpseclib as well, but it doest work either, that gives:
"Unable to login with the provided credentials."

Is it required to supply the path to the ssh keys or does it automatically check in ~/.ssh/ to find them?
Using commandline ssh works fine without any additional arguments, like: ssh test-prod@localhost for example.

**Comment by erickr** [comment]
It turned out I had added my dsa key to the authorized keys file of the target account, using an rsa key with set('ssh_type', 'ext-ssh2'); works correctly. Thanks!

**Comment by garak** [comment]
I'm using a dsa key also. What's wrong with it?

**Comment by erickr** [comment]
@garak that didnt work for me at least, switching to a rsa-key made it work instantly as long as ssh_type was set to ext-ssh2.

Did you try that?

**Comment by kenjis** [comment]
I don't know why DSA key does not work. But DSA key is 1024 bits. It is not secure today.

**Comment by garak** [comment]
Sorry, I double checked and ny key is ECDSA, not DSA. Any hint?

**Comment by erickr** [comment]
@garak at least phpseclib seems to not handle dsa-keys at all if I read the code right:
https://github.com/deployphp/deployer/blob/49bfff673ae49b95029831d2038b924c4cfccb43/src/Server/Remote/PhpSecLib.php#L58-L66

So try a rsa-key.

**Comment by garak** [comment]
@erickr you're right :disappointed: 
See also https://github.com/phpseclib/phpseclib/issues/216
