### ISSUE TITLE
Won't git clone from private repo but forwardAgent() connection is done.

### ISSUE THREAD

**Issue by agarb7** [deployphp/deployer#393]
I use:
server('ssss', '111.111.111.111')
    ->user('uuuu')
    ->forwardAgent();

Connect is done, and all tasks before `deploy:update_code` is done too.
On `deploy:update_code` raise exception:
```
  [RuntimeException]                          
  Permission denied (publickey).              
  fatal: The remote end hung up unexpectedly.
```
But if I manualy connect by `ssh uuuu@111.111.111.111` and exec `git clone -b master --depth 1 --recursive -q git@github.com:oooo/rrrr.git rrrr` - it working good.

I configured local(ubuntu) and server(debian7) in accordance with https://github.com/oanhnn/deployer-example/blob/master/docs/enable-feature-ssh-forward-agent.md (but in my server no sshd service, it's name ssh). This has no effect.

**Comment by elfet** [comment]
Which ssh implementation do you use? 
Try to use "deploy keys".

**Comment by agarb7** [comment]
I use phpseclib. But I aslo try ssh2_ext (clone latest master branch today) and it don't work too. (Little difference is it do not show exception explanation, just `[RuntimeException]` red recatangle. - May be this is small issue.)
I will try "deploy keys" a bit later.

**Comment by josemf** [comment]
Hi, same issue,

I'm pretty sure ssh agent forward is enabled in server. I've followed every step in https://github.com/oanhnn/deployer-example/blob/master/docs/enable-feature-ssh-forward-agent.md

And doing:
ssh josemf@xxx.xxx.xxx.xxx "git clone  --depth 1 --recursive -q git@bitbucket.org:vendor/project.git /var/local/apps/project/releases/20150729180636" 

Successfully clones the repository.

Ofc I don't have my private key in the server, so I know this comes for SSH Agent Forwarding.

Also:

> josemf@zeus:~/.ssh$ ssh -T git@bitbucket.org
> logged in as josemf.
>
> You can use git or hg to connect to Bitbucket. Shell access is disabled.

My deploy.php

> require 'recipe/composer.php';
>
> server('zeus', 'host', 22)
>    ->user('josemf')
>   ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'xxxxxxxxx')
>    ->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
>    ->stage('staging')
>    ->env('deploy_path', '/var/local/apps/project'); // Define the base path to deploy your project to.
>
> set('repository', 'git@bitbucket.org:vendor/project.git');

And the deploy log:

> ➤ Executing task deploy:prepare
> ⤷ on [zeus]
> Run: echo $0
> > bash
> >
> Run: if [ ! -d /var/local/apps/staging.rio-works.com ]; then echo ""; fi
> Run: cd /var/local/apps/staging.rio-works.com && if [ ! -d releases ]; then mkdir releases; fi
> Run: cd /var/local/apps/staging.rio-works.com && if [ ! -d shared ]; then mkdir shared; fi
> ⤶ done on [zeus]
> ✔ Ok
> ➤ Executing task deploy:release
> ⤷ on [zeus]
> Run: date +%Y%m%d%H%M%S
> > 20150729190535
> >
> Run: mkdir /var/local/apps/project/releases/20150729190535
> Run: cd /var/local/apps/project && if [ -h release ]; then rm release; fi
> Run: ln -s /var/local/apps/project/releases/20150729190535 /var/local/apps/project/release
> ⤶ done on [zeus]
> ✔ Ok
> ➤ Executing task deploy:update_code
> ⤷ on [zeus]
> Run: readlink /var/local/apps/project/release
> /var/local/apps/project/releases/20150729190535
> >
> Run: git clone  --depth 1 --recursive -q git@bitbucket.org:vendor/project.git /var/local/apps/project/releases/20150729190535 2>&1
>
>
>
>  [RuntimeException]
>  Permission denied (publickey).
>  fatal: Could not read from remote repository.
>  Please make sure you have the correct access rights
>  and the repository exists.
>
>
>
> Exception trace:

Well I think forwardAgent() function may not be working as expected. Or there's something broke with `phpseclib'.

deployer/phpseclib          v1.0.0 PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.

Thanks for you help!

**Comment by oanhnn** [comment]
I think `forwradAgent()` is working but in your agent has many keys and one or some keys has made this error. Please try add key to deploy keys and run below command before run deployer.
```
$ ssh-add -D
$ ssh-add /path/to/your_key
$ dep deploy dev -vvv
```

**Comment by josemf** [comment]
I've only one key on this computer, but followed your instructions anyway unfortunately with no success.

Do you have any other debug you want to try out? I could easily run some tests, or mess with `deployer´ or `phpseclib´ code if you would give me any guidance on that.

      System Version: OS X 10.9.5 (13F34)
      Kernel Version: Darwin 13.4.0

Thanks!

**Comment by agarb7** [comment]
In my case there is no solution still. I deleted all keys in remote, local, and github account and repos. I recreate key localy (ssh-keygen), add it to remote (ssh-copy-id uuuu@111.111.111.111), add it to only one needed repo to deploy keys section. When I try `dep deploy ssss`, i still get error:
```
  [RuntimeException]                          
  Permission denied (publickey).              
  fatal: The remote end hung up unexpectedly  
```
But `ssh uuuu@111.111.111.111 'git clone -b master --depth 1 --recursive -q git@github.com:oooo/rrrr.git rrrr'` works well.

Then i wrote task:
```php
task('show_keys', function () {
    writeln(run("sudo ssh-add -l"));
});
```
and set it before `deploy:update_code`, and got:
```
➤ Executing task show_keys
⤷ on [daikoku.ru]
Run: ssh-add -l
                                                             
  [RuntimeException]                                         
  Could not open a connection to your authentication agent.  
```                                                            
Forwarding does not happen. **It is bug?**

**Comment by agarb7** [comment]
*Local*: 
```
Kubuntu 14.10, PHP 5.6.11-1+deb.sury.org~utopic+1
Deployer 3.0.6 from composer
Deployer from repo master branch (with deployer/phpseclib and phpseclib/phpseclib)
```
*Remote*:
```
OpenSSH_6.7p1 Debian-5, OpenSSL 1.0.1k 8 Jan 2015
OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013
```

Agent forwarding does not work for me in above cases. There are people who have it work?

**Comment by elfet** [comment]
Did you enable agent forwarding feature?

**Comment by agarb7** [comment]
@elfet Yes)) I tried enable it in YAML format and by `forwardAgent()` method of `Builder`.
Please, show me a working configuration: os, deployer, php (with exts), sshd.

**Comment by josemf** [comment]
Would be interested in that, also. Thanks!

**Comment by oanhnn** [comment]
Here is my working configurations:
```
#####
# Local: Ubuntu 14.04
# OpenSSH_6.6.1p1 Ubuntu-2ubuntu2, OpenSSL 1.0.1f 6 Jan 2014
# PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
# file ~/.ssh/config on my PC
#####
Host github.com
  PreferredAuthentications publickey
  ForwardAgent yes
Host 192.168.1.3
  ForwardAgent yes
```
```
#####
# Remote: CentOS 6.5
# OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
# PHP 5.5.19 (cli) (built: Nov 16 2014 09:53:48)
# file /etc/ssh/sshd_config on my server
#####
Protocol 2

SyslogFacility AUTHPRIV

PubkeyAuthentication yes
AuthorizedKeysFile      .ssh/authorized_keys

PasswordAuthentication yes

ChallengeResponseAuthentication no

GSSAPIAuthentication yes
GSSAPICleanupCredentials yes

UsePAM yes

# Accept locale-related environment variables
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS

AllowAgentForwarding yes
X11Forwarding yes
ClientAliveInterval 120
ClientAliveCountMax 5

Subsystem       sftp    /usr/libexec/openssh/sftp-server
```

**Comment by vanquang9387** [comment]
I have the same problem as @agarb7 and @josemf 
Tried @oanhnn 's configuration but no luck.

ForwardAgent works with manual ssh (notice debug2: key: key/id_rsa (0x7f70d9d7ffc0)) :
>...
debug1: SSH2_MSG_SERVICE_ACCEPT received
**debug2: key: key/id_rsa (0x7f70d9d7ffc0)**
debug2: key: /home/quangnv/.ssh/identity ((nil))
debug2: key: /home/quangnv/.ssh/id_rsa ((nil))
debug2: key: /home/quangnv/.ssh/id_dsa ((nil))
debug2: key: /home/quangnv/.ssh/id_ecdsa ((nil))
...

but didn't work with deployer:
>...
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/quangnv/.ssh/identity ((nil))
debug2: key: /home/quangnv/.ssh/id_rsa ((nil))
debug2: key: /home/quangnv/.ssh/id_dsa ((nil))
debug2: key: /home/quangnv/.ssh/id_ecdsa ((nil))
...

Tried show_keys task as @agarb7 and got same output
>[RuntimeException]
Could not open a connection to your authentication agent.

**Comment by torinaki** [comment]
I have updated `phpseclib` till 2.0 version and have fixed agent forwarding according to:
https://github.com/phpseclib/phpseclib/blob/62fdd160e3ae2bb265a7e1f7c9426d552f55df47/tests/Functional/Net/SSH2AgentTest.php#L50
Now it works for me.

**Comment by vanquang9387** [comment]
Thanks @torinaki

**Comment by elfet** [comment]
Wow! Can you make PR with fixed phpseclib?

**Comment by AlexStansfield** [comment]
I think this has broken things for me.

I'm not using agent forwarding but pem files. Since phpseclib 2.0.0 was added in this PR when it does the git clone the directory is empty.

If i add deployer/phpseclib 1.0.0 back and remove phpseclib/phpseclib 2.0.0 everything is fine.

**Comment by josemf** [comment]
Thanks @torinaki! Works for me now.
