### ISSUE TITLE
Idea: Logs

### ISSUE THREAD

**Issue by Danielss89** [deployphp/deployer#394]
It would be nice if Deployer kept a log of each deployment. The logs should contain the same as -vvv outputs.

Option to enable/disable logging and choose a log directory.

WDYT?

**Comment by elfet** [comment]
Yes! This is cool feature. Must have!

**Comment by davidkudera** [comment]
:+1:

**Comment by erickr** [comment]
Is anyone doing this? 

Is there a preferred way of passing information between tasks? For example, lets say you use the hipchat recipe, and want to push the deploy log to a hipchat channel, and then later make another recipe collecting the git changelog between this and previous version, and you want to post that to hipchat as well.

**Comment by davidkudera** [comment]
What about using for example [saldaek/monolog](https://github.com/Seldaek/monolog)? Than everyone can configure where to put logs

**Comment by petermein** [comment]
+1

**Comment by elfet** [comment]
Monolog is a great idea!

**Comment by oisvidi** [comment]
If you use a DIC in v4 it would be nice if it was overwriteable before anything was run. So I could replace the container value "logger" with my own psr3 compatible logger. 

Which is monolog but might write to a different file or greylog. 

Would be nice if in my deploy.php I just set a bunch of container values, then the deployer app is run. 

dep cli sets up basic container, loads my deployer scripts which first runs common recipe then my deploy recipe then runs the app with container as a constructor parameter (as defined in the container).

**Comment by unclead** [comment]
why this issue was closed?
