### ISSUE TITLE
Rename symbolic link 'current' to another name

### ISSUE THREAD

**Issue by nntoan** [deployphp/deployer#395]
Hello,

As the title said, I want to rename symbolic link into another name, is that possible to do?

**Comment by elfet** [comment]
Copy `common.php` recipe and rename current to what you want)

**Comment by oanhnn** [comment]
@nntoan: Can i help me? I can support you by Vietnamese :smile:

**Comment by kenjis** [comment]
Why do you need to change?

**Comment by nntoan** [comment]
Anyone have any idea about this?

```php
PHP Fatal error:  require(): Failed opening required 'recipe/common.php' (include_path='phar:///usr/local/bin/dep/bin/../:phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib:.:/usr/local/Cellar/php56/5.6.10/lib/php') in /deploy.php on line 2
```

@kenjis : I want to controll everything.
