### ISSUE TITLE
New release updates are not actually visible in the browser - only older are

### ISSUE THREAD

**Issue by nicolamonaca** [deployphp/deployer#398]
Hi, whenever I try to "dep deploy [staging | production]" (both servers running on a DO droplet using Ubuntu 14.04 + Nginx + Laravel 5), the whole process seems to go fine and indeed it does, except for the fact that the updates in the new release are not visible in the browser. It correctly symlinks the "current" directory to the one just created: "2015xxxxxxxxxx", but I can not anyhow manage to see in the browser the updates contained in "2015xxxxxxxxxx".

I have "set('keep_releases', 5);" in my Deploy.php file and, in fact, if I deployed 4 more times, deployer would get rid of older directories and force the updates to appear in the browser, since then all 5 releases would have the updates I'd like to see.

Does anybody know if it's something related to deployer itself or to anything else? Did nobody experience such a strange behavior?

Following is my complete Deploy.php file: https://gist.github.com/nicolamonaca/8a0b53c77db9a80cd49a

**Comment by elfet** [comment]
Please run deployer with `-vvv` option.

**Comment by nicolamonaca** [comment]
$ dep deploy -vvv production
➤ Executing task deploy:prepare
⤷ on [production]
Run: echo $0
> bash
>
Run: if [ ! -d /var/www/sharewood ]; then echo ""; fi
Run: cd /var/www/sharewood && if [ ! -d releases ]; then mkdir releases; fi
Run: cd /var/www/sharewood && if [ ! -d shared ]; then mkdir shared; fi
⤶ done on [production]
✔ Ok
➤ Executing task deploy:release
⤷ on [production]
Run: date +%Y%m%d%H%M%S
> 20150720054545
>
Run: mkdir /var/www/sharewood/releases/20150720054545
Run: cd /var/www/sharewood && if [ -h release ]; then rm release; fi
Run: ln -s /var/www/sharewood/releases/20150720054545 /var/www/sharewood/release
⤶ done on [production]
✔ Ok
➤ Executing task deploy:update_code
⤷ on [production]
Run: readlink /var/www/sharewood/release
> /var/www/sharewood/releases/20150720054545
>
Run: git clone -b master --depth 1 --recursive -q git@bitbucket.org:nicolamonaca/sharewood-do.git /var/www/sharewood/releases/20150720054545 2>&1
⤶ done on [production]
✔ Ok
➤ Executing task deploy:vendors
⤷ on [production]
Run: if hash composer 2>/dev/null; then echo 'true'; fi
> true
>
Run: cd /var/www/sharewood/releases/20150720054545 &&  composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
> Loading composer repositories with package information
> Installing dependencies from lock file
>   - Installing symfony/finder (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/var-dumper (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing psr/log (1.0.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing maximebf/debugbar (v1.10.4)
>     Loading from cache
>     Extracting archive
>
>   - Installing vlucas/phpdotenv (v1.1.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/translation (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/security-core (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/routing (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/process (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/http-foundation (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/event-dispatcher (v2.7.2)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/debug (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/http-kernel (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/console (v2.6.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing swiftmailer/swiftmailer (v5.4.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing nikic/php-parser (v1.4.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing jakub-onderka/php-console-color (0.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing jakub-onderka/php-console-highlighter (v0.3.2)
>     Loading from cache
>     Extracting archive
>
>   - Installing dnoegel/php-xdg-base-dir (0.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing psy/psysh (v0.4.4)
>     Loading from cache
>     Extracting archive
>
>   - Installing nesbot/carbon (1.17.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing mtdowling/cron-expression (v1.0.4)
>     Loading from cache
>     Extracting archive
>
>   - Installing monolog/monolog (1.15.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing league/flysystem (1.0.9)
>     Loading from cache
>     Extracting archive
>
>   - Installing jeremeamia/superclosure (2.1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing ircmaxell/password-compat (v1.0.4)
>     Loading from cache
>     Extracting archive
>
>   - Installing doctrine/inflector (v1.0.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing danielstjules/stringy (1.9.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing symfony/filesystem (v2.7.2)
>     Loading from cache
>     Extracting archive
>
>   - Installing classpreloader/classpreloader (1.4.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing laravel/framework (v5.0.33)
>     Loading from cache
>     Extracting archive
>
>   - Installing barryvdh/laravel-debugbar (v2.0.5)
>     Loading from cache
>     Extracting archive
>
>   - Installing cartalyst/collections (v1.1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing react/promise (v2.2.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing guzzlehttp/streams (3.0.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing guzzlehttp/ringphp (1.1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing guzzlehttp/guzzle (5.3.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing cartalyst/stripe (v1.0.3)
>     Loading from cache
>     Extracting archive
>
>   - Installing cartalyst/stripe-laravel (v2.0.2)
>     Loading from cache
>     Extracting archive
>
>   - Installing cmgmyr/messenger (2.7)
>     Loading from cache
>     Extracting archive
>
>   - Installing mrclay/minify (2.2.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing graham-campbell/htmlmin (v3.1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing illuminate/html (v5.0.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing psr/http-message (1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing guzzlehttp/psr7 (1.1.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing intervention/image (2.3.1)
>     Loading from cache
>     Extracting archive
>
>   - Installing jenssegers/date (v2.0.21)
>     Loading from cache
>     Extracting archive
>
>   - Installing laracasts/utilities (2.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing stripe/stripe-php (v2.3.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing laravel/cashier (v5.0.7)
>     Loading from cache
>     Extracting archive
>
>   - Installing guzzle/guzzle (v3.9.3)
>     Loading from cache
>     Extracting archive
>
>   - Installing league/oauth1-client (1.5.0)
>     Loading from cache
>     Extracting archive
>
>   - Installing laravel/socialite (v2.0.8)
>     Loading from cache
>     Extracting archive
>
>   - Installing mcamara/laravel-localization (1.0.10)
>     Loading from cache
>     Extracting archive
>
>   - Installing league/glide (0.3.5)
>     Loading from cache
>     Extracting archive
>
>   - Installing spatie/laravel-glide (2.2.4)
>     Loading from cache
>     Extracting archive
>
> Generating optimized autoload files
> Warning: Ambiguous class resolution, "App\Http\Controllers\Admin\FeedbackOwnerController" was found in both "/var/www/sharewood/releases/20150720054545/app/Http/Controllers/Admin/FeedbackUserController.php" and "/var/www/sharewood/releases/20150720054545/app/Http/Controllers/Admin/FeedbackOwnerController.php", the first will be used.
> Generating optimized class loader
> Compiling common classes
>
⤶ done on [production]
✔ Ok
➤ Executing task deploy:shared
⤷ on [production]
Run: if [ -d $(echo /var/www/sharewood/releases/20150720054545/storage) ]; then rm -rf /var/www/sharewood/releases/20150720054545/storage; fi
Run: mkdir -p /var/www/sharewood/shared/storage
Run: mkdir -p `dirname /var/www/sharewood/releases/20150720054545/storage`
Run: ln -nfs /var/www/sharewood/shared/storage /var/www/sharewood/releases/20150720054545/storage
⤶ done on [production]
✔ Ok
➤ Executing task deploy:symlink
⤷ on [production]
Run: cd /var/www/sharewood && ln -sfn /var/www/sharewood/releases/20150720054545 current
Run: cd /var/www/sharewood && rm release
⤶ done on [production]
✔ Ok
➤ Executing task environment
⤷ on [production]
Run: cp /var/www/sharewood/shared/.env /var/www/sharewood/releases/20150720054545/.env
⤶ done on [production]
✔ Ok
➤ Executing task current:chown
⤷ on [production]
Run: chown monaghan:www-data /var/www/sharewood/current/*
⤶ done on [production]
✔ Ok
➤ Executing task composer
⤷ on [production]
Run: cd /var/www/sharewood/current; composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
>   - Installing symfony/yaml (v2.7.2)
>     Loading from cache
>
>   - Installing symfony/dom-crawler (v2.7.2)
>     Loading from cache
>
>   - Installing symfony/css-selector (v2.7.2)
>     Loading from cache
>
>   - Installing symfony/browser-kit (v2.7.2)
>     Loading from cache
>
>   - Installing sebastian/version (1.0.6)
>     Loading from cache
>
>   - Installing sebastian/global-state (1.0.0)
>     Loading from cache
>
>   - Installing sebastian/recursion-context (1.0.0)
>     Loading from cache
>
>   - Installing sebastian/exporter (1.2.0)
>     Loading from cache
>
>   - Installing sebastian/environment (1.2.2)
>     Loading from cache
>
>   - Installing sebastian/diff (1.3.0)
>     Loading from cache
>
>   - Installing sebastian/comparator (1.1.1)
>     Loading from cache
>
>   - Installing phpunit/php-text-template (1.2.1)
>     Loading from cache
>
>   - Installing doctrine/instantiator (1.0.5)
>     Loading from cache
>
>   - Installing phpunit/phpunit-mock-objects (2.3.5)
>     Loading from cache
>
>   - Installing phpunit/php-timer (1.0.6)
>     Loading from cache
>
>   - Installing phpunit/php-file-iterator (1.4.0)
>     Loading from cache
>
>   - Installing phpunit/php-token-stream (1.4.3)
>     Loading from cache
>
>   - Installing phpunit/php-code-coverage (2.1.8)
>     Loading from cache
>
>   - Installing phpdocumentor/reflection-docblock (2.0.4)
>     Loading from cache
>
>   - Installing phpspec/prophecy (v1.4.1)
>     Loading from cache
>
>   - Installing phpunit/phpunit (4.7.7)
>     Loading from cache
>
>   - Installing facebook/webdriver (1.0.1)
>     Loading from cache
>
>   - Installing codeception/codeception (2.1.1)
>     Loading from cache
>
>   - Installing phpspec/php-diff (v1.0.2)
>     Loading from cache
>
>   - Installing phpspec/phpspec (2.2.1)
>     Loading from cache
>
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
> phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
> phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
> phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
> facebook/webdriver suggests installing phpdocumentor/phpdocumentor (2.*)
> codeception/codeception suggests installing codeception/phpbuiltinserver (Extension to start and stop PHP built-in web server for your tests)
> codeception/codeception suggests installing codeception/specify (BDD-style code blocks)
> codeception/codeception suggests installing codeception/verify (BDD-style assertions)
> codeception/codeception suggests installing phpseclib/phpseclib (Extension required to use the SFTP option in the FTP Module.)
> phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 – Adds Nyan formatters)
> Generating autoload files
> Generating optimized class loader
> Compiling common classes
>
⤶ done on [production]
✔ Ok
➤ Executing task clean:views
⤷ on [production]
Run: cd /var/www/sharewood/shared/storage/framework/views; rm -f *
⤶ done on [production]
✔ Ok
➤ Executing task cleanup
⤷ on [production]
Run: ls /var/www/sharewood/releases
> 20150718212704
> 20150718212731
> 20150718220608
> 20150719131442
> 20150720054310
> 20150720054545
>
Run: rm -rf /var/www/sharewood/releases/20150718212704
Run: cd /var/www/sharewood && if [ -e release ]; then rm release; fi
Run: cd /var/www/sharewood && if [ -h release ]; then rm release; fi
⤶ done on [production]
✔ Ok
➤ Executing task optimize
⤷ on [production]
Run: cd /var/www/sharewood/current; php artisan optimize
> Generating optimized class loader
> Compiling common classes
>
⤶ done on [production]
✔ Ok
➤ Executing task success
Successfully deployed!
✔ Ok


I just deployed into production but still keep seeing the old version of the site.

**Comment by kenjis** [comment]
It seems good.
What about your config of web server? Document root is right?

By the way, you got one warning:
> Warning: Ambiguous class resolution, "App\Http\Controllers\Admin\FeedbackOwnerController" was found in both "/var/www/sharewood/releases/20150720054545/app/Http/Controllers/Admin/FeedbackUserController.php" and "/var/www/sharewood/releases/20150720054545/app/Http/Controllers/Admin/FeedbackOwnerController.php", the first will be used.
