### ISSUE TITLE
Create entire path to release in prepare?

### ISSUE THREAD

**Issue by AlexStansfield** [deployphp/deployer#402]
I noticed that I basically have to create the parent path up to the deployment path myself before deploying. Would it be bad to just add a ```-p``` to the mkdir command that creates the deployment path if it doesn't already exist?

**Comment by AlexStansfield** [comment]
Actually I just noticed that it in the latest master it doesn't actually create the deploy path directory either.

**Comment by elfet** [comment]
Can you make PR for this?

**Comment by AlexStansfield** [comment]
Sure thing. Have already made the code change as in deploying lots of things today to new environment. Will branch it and submit PR.

**Comment by elfet** [comment]
Cool, thanks!
