### ISSUE TITLE
Create a config file from template

### ISSUE THREAD

**Issue by erickr** [deployphp/deployer#405]
Is there a good way to create a config file from some of the settings from the servers.yml file and a template? Or any direction if anything like it has been done before?

**Comment by oanhnn** [comment]
@erickr 
You can use [configure recipe](https://github.com/deployphp/recipes/blob/master/docs/configure.md) from `deployphp/recipes`.
See an example in [here](https://github.com/oanhnn/deployer-example).
Good luck!

**Comment by elfet** [comment]
This is good idea! Add `dep init` command.

**Comment by erickr** [comment]
:+1: 
Great, cant see how I could have missed this!
