### ISSUE TITLE
Run command on different server

### ISSUE THREAD

**Issue by davidkudera** [deployphp/deployer#408]
Hi,

please, is it possible to somehow run command on different server? I have for example task `database:sync` which I run like this

```
$ dep database:sync test
```

I have two servers defined:
* `production`
* `test`

Now I would like to connect to `production`, create database dump, download it and then upload it to the test server.

If it is not possible (maybe yet :smile:), is there at least some workaround please?

Thank you

**Comment by davidkudera** [comment]
Ou.. I just found #355 so I'll try the suggested solution. Sorry if this is a duplicate

**Comment by davidkudera** [comment]
So I tried `onlyOn` method, but that will only run task if given server name (from command) is same

**Comment by elfet** [comment]
You can set dumping by onlyOn on prod server.

**Comment by oanhnn** [comment]
@davidkudera 
Can you try?
```php
task('database:dump', function(){
    // TODO: dump and download
})->onlyOn('production');

task('database:restore', function(){
    // TODO: upload and restore
})->onlyOn('test');

task('database:sync', [
     'database:dump',
     'database:restore',
]);

server('test', '192.168.1.2', 22)
    ->user('your_user')
    ->identityFile()
    ->stage(['dev'])
    ->env('deploy_path', '/var/www/apps/your_app')
    ->env('branch', 'master');

server('production', '192.168.1.3', 22)
    ->user('your_user')
    ->identityFile()
    ->stage(['dev'])
    ->env('deploy_path', '/var/www/apps/your_app')
    ->env('branch', 'master');
```
and run:
```
dep database:sync dev -vvv
```
Goodluck!

**Comment by davidkudera** [comment]
@oanhnn that's what I tried :wink: 

```php
task('database:dump', function(){
	write('DUMPING...');
})->onlyOn(['production']);

task('database:restore', function(){
	write('RESTORING...');
});

task('database:sync', [
	'database:dump',
	'database:restore',
]);
```

**output:**

```
✔ Executing task database:dump
➤ Executing task database:restore
RESTORING...✔ Ok
```

**Comment by oanhnn** [comment]
@davidkudera 
With your case, please try my script.
Your script missing `->onlyOn('test')` and settings server stage `dev`

**Comment by davidkudera** [comment]
@oanhnn I didn't noticed your stage setup, sorry...

So with that setup:

```php
localServer('production')
	->stage(['dev', 'david_work', 'test']);

localServer('test')
	->stage(['dev', 'test']);

localServer('david_work')
	->stage(['dev', 'david_work']);

task('database:dump', function() {
	write('DUMPING...');
})->onlyOn(['production']);

task('database:restore', function() {
	write('RESTORING...');
})->onlyOn(['test', 'david_work']);

task('database:sync', [
	'database:dump',
	'database:restore',
]);
```

I was able to run all tasks like I needed. The only problem is, that it looks quite difficult to just run some task on different server :wink:

**Comment by oanhnn** [comment]
I think it will be easy if you split it into 2 standalone works
Good luck

**Comment by oanhnn** [comment]
I am closing thing issue but feel free to reopen if you think there needs to be more discussion.

**Comment by davidkudera** [comment]
What do you think about some other option? Somehing like `runAt` for example.. Because now if I'll want to add another server, I'll have to update `production` configuration which btw seems little strange to me and `database:restore` task too.

And thats just one task. Later I'll have to add another similar task for downloading some uploaded files (like user's profile images, etc.).

**Comment by elfet** [comment]
`runAt` pretty much `onlyOn`.

**Comment by davidkudera** [comment]
@elfet Yeah, I know sorry.. But you know what I meant, right? :smiley:

**Comment by davidkudera** [comment]
I found another flaw. Every other task needs to have `onlyOn` options too, which is not so nice :disappointed: 

Also I can't reopen this issue (but maybe it's issue just for me....)

**Comment by elfet** [comment]
What do you mean? Can you show example?

**Comment by davidkudera** [comment]
Sure, I just added a new task `database:migrate` to `database:sync` for running doctrine migrations, but it throw an error for this command:

```
$ dep database:migrate test
```

I just forgot to set `onlyOn` on that new command, which is my mistake. Problem is that our old deployment (also written in deployer) has about 30 tasks and the new version which is written from scratch is much more complete... So you just have to think about it every time and if you'll forgot... Well.. I can lead to unexpected results or break something completely.

**Comment by elfet** [comment]
You need understand what task you running on which server. What you suggest to avoid this?

**Comment by davidkudera** [comment]
No no, I understand.. But lets see an example: 

You have many servers and one of them is `production`. Now you want to be able to download database from production to any other server at any time.

```php
localServer('production')
	->stage(['production', 'test1', 'test2', 'test3']);

localServer('test1')
	->stage(['test1']);

localServer('test2')
	->stage(['test2']);

localServer('test3')
	->stage(['test3']);
```

No you want to sync database at `test2`:

```
$ dep database:sync test2
```

And tasks are:

```php
task('database:dump', function() {
	write('DUMPING...');
})->onlyOn(['production']);

task('database:restore', function() {
	write('RESTORING...');
})->onlyOn(['test1', 'test2', 'test3', 'test4']);

task('database:migrate', function() {
	write('MIGRATING...');
});

task('database:sync', [
	'database:dump',
	'database:restore',
	'database:migrate',
]);
```

Now you want to add another task, which shouldn't run on production, so you'll set `onlyOn` (if you'll not forgot). Then you'll want to add another independent testing server = you have to update all of these tasks above with production server too (same for removing, updating, ...).

I suggest something like this:

```php
task('database:dump', function() {
	write('DUMPING...');
})->runOn('production'); // with better name of course

task('database:restore', function() {
	write('RESTORING...');
});

task('database:migrate', function() {
	write('MIGRATING...');
});
```

If I'll run `dep database:sync test2` and I'll not have any stages configured (I don't otherwise need them) it will run `database:dump` automatically and **always** on `production` server.

Also I could leave `onlyOn` configuration on `database:restore` task because I can watch myself to not run `dep database:restore` on `production`.

`onlyOn` is just some kind of filter, nothing more (I think). `runOn` on other hand starts task always on given server. No matter on which server or stage you actually started your tasks.

And finally adding new tasks or servers is simple again :wink:

**Comment by elfet** [comment]
I understand, but this is really complicate Deployer itself =) 
It's better to configure your scripts to avoid this problems.

**Comment by davidkudera** [comment]
Ok, I'll try it, thanks anyway

**Comment by davidkudera** [comment]
Sorry that I'm again reacting here... But it just seems impossible to do what I need.

In previous example when I'll run `dep database:migrate test2`, it will run on both `test2` and `production`, which is exactly what I don't want.

I just can't find any combination of server names, stages and onlyOn options to make it work

**Comment by davidkudera** [comment]
Ehm, what if I'll prepare a pull request and than you'll see? You know I'm trying so hard, because I really don't want to switch to some other tool (read worse tool). Also I don't think that it will complicate Deployer any more by looking at the code.

**Comment by oanhnn** [comment]
@davidkudera 
I think with your case, we can using:
```
task('database:dump', function() {
    write('DUMPING...');
})->onlyOn('production');

task('database:restore', function() {
    if ('production' == input()->hasArgument('stage')) {
    // or
    // if ('production' == env('server.name')) {
        return;
    }
    write('RESTORING...');
});
```

**Comment by davidkudera** [comment]
@oanhnn sure, I can, but it is not better than some combination of stages, servers and onlyOn options. Just imagine how the code will look like if more tasks have such otherwise useless code. Like I said, our deployment is pretty complicated and I just love the simplicity of docker - compare it with for example rocketeer...

Also I tried to use all of your suggestions, but really soon (just in minutes) I run across another problem. The bigist is that any developer can forgot to put such code in tasks and that can lead to really large problems. 

We can either make it little bit more dificult for developers with similar problem, or we can add new feature. So please, may I ask you to look at #413?
