### ISSUE TITLE
How to get current environment/stage

### ISSUE THREAD

**Issue by Danielss89** [deployphp/deployer#412]
Hi
I have a task which need to know the current environment/stage, the one i pass through the cli.
so `./vendor/bin/dep deploy dev` would give me `dev`.
I've looked through documentation but can't find any mention of this.

**Comment by oanhnn** [comment]
@Danielss89 
Can you try this code:
```
task('foo:bar', function() {
    // For arguments
    $stage = null;
    if (input()->hasArgument('stage')) {
        $stage = input()->getArgument('stage');
    }

    // For option
   $tag = null;
   if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
    }
}
```

**Comment by Danielss89** [comment]
Thx, that worked :)
Is it possible to deploy to more than one stage at the same time(in once cli command)?

**Comment by temp** [comment]
Somehow related - what is the preferred way to execute tasks only for some stages?
Do I have to check it inside the task, or is there something else I can do?

**Comment by elfet** [comment]
You can specify `onlyOn`.

**Comment by temp** [comment]
Hmm... I meant programmatically. I have a task (import database from production) which I only want to execute on stages test and staging.
It's set up as a before-task for database:migrate.
I'd like to execute this conditionally based on the stage...

**Comment by davidkudera** [comment]
@temp I think that I was trying to do something similar, but with no success.. See #408 issue and PR #413
