### ISSUE TITLE
Windows displays rubbish symbols in cmd

### ISSUE THREAD

**Issue by ju5tify** [deployphp/deployer#418]
The same in Powershell and in ConEmu.
Maybe it is better to display just plain text in Windows env
![2015-07-31 11_46_47-select administrator_ windows powershell](https://cloud.githubusercontent.com/assets/1333841/9003797/dbb1a9c2-3779-11e5-8b85-ad311fbad10b.png)
![2015-07-31 11_45_48-administrator_ c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/1333841/9003796/dbb1bb24-3779-11e5-9068-539d2dd7dbbb.png)
![2015-07-31 11_46_25-administrator_ powershell](https://cloud.githubusercontent.com/assets/1333841/9003798/dbb5af2c-3779-11e5-8ee9-b4c5a369a01a.png)

**Comment by elfet** [comment]
Eaahh. It is... I know... Can anyone with Windows make PR with just text instead of emoji and utf-8 (♻️)?

**Comment by nakashu** [comment]
why was this closed ? The issue is still present.

**Comment by elfet** [comment]
Yes, but still need to be fixed. Anyone want to contribute?

**Comment by nakashu** [comment]
I will probably get to it, during the holidays or sooner. But it is only one file Informer.php, that needs to be changed.

**Comment by ju5tify** [comment]
Can be temporary fixed with `chcp 65001` before running deployer
