### ISSUE TITLE
Using ssh-agent on Windows?

### ISSUE THREAD

**Issue by frutality** [deployphp/deployer#420]
Is it possible to use deployer with ssh-agent on Windows?

When I am connecting with `identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'MyStrongPassword')` it's ok. Deployment is successful.

But it's not secure to store MyStrongPassword here. I am trying to use `forwardAgent()` and all I get is:
```
Warning: fsockopen(): unable to connect to unix://C:/Users/8523~1/AppData/Local/Temp/ssh-lZz6mszVrxCO/agent.2700:0 (Unable to find the socket transport "unix" - did you forget to enable it when you configured PHP?) in path\to\vendor\deployer\phpseclib\phpseclib\System\SSH\Agent.php on line 97

Notice: Unable to connect to ssh-agent (Error 11073052: Unable to find the socket transport "unix" - did you forget to enable it when you configured PHP?) in path\to\vendor\deployer\phpseclib\phpseclib\System\SSH\Agent.php on line 99

[RuntimeException]
 Unable to login with the provided credentials.
```

I am using https://msysgit.github.io/ and ssh-agent works great. I just typing "ssh user@hostname" and connection is successful. 

Also I can use "pageant" agent (Putty). It works great too.

**Comment by elfet** [comment]
> Error 11073052: Unable to find the socket transport "unix" - did you forget to enable it when you configured PHP?

**Comment by frutality** [comment]
Couldn't find any information about unix sockets on Windows. 
1. Is it possible to use unix sockets on Windows? [I think answer is NO]
2. Is it possible to use another socket transport to connect to ssh-agent on Windows?

**Comment by vanquang9387** [comment]
I have exact same problem on Windows.

@frutality 
> When I am connecting with identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'MyStrongPassword') it's ok.

I even could not deploy with identityFile().
When using identityFile(), how could deployment server be authenticated by git server? Did you upload private key to deployment server?

**Comment by dima-stefantsov** [comment]
Why is this closed? I'm having same issue.
- using windows
- everything works with putty+pageant
- everything works with ssh+ssh-agent
- deployer doesn't work, same error as described above.

`stream_get_transports()` returns     

    string (3) "tcp"
    string (3) "udp"
    string (3) "ssl"
    string (5) "sslv3"
    string (5) "sslv2"
    string (3) "tls"
    string (7) "tlsv1.0"
    string (7) "tlsv1.1"
    string (7) "tlsv1.2"

How exactly do I "enable unix:// socket transport" in my php.ini in windows?

If unix:// transport is not available, maybe you could implement some other way of using ssh-agent (or pageant) - the way default utilites like ssh do it.

**Comment by oanhnn** [comment]
@dima-stefantsov this issue is out of date.
You can make a new issue if you have problem.
Please show me your enviroment.
Current i am using forward agent success on windows (git bash + ssh-agent).

**Comment by dima-stefantsov** [comment]
Hi @oanhnn, thanks for your reply.
With stream_get_transports() I have shown that I don't have unix:// transport available/installed. That is certainly the reason it fails for me.

I am using latest wamp on windows, php 5.6 or 7.0.8. Since it works for you, you must have unix:// transport. How do I get one?

**Comment by elfet** [comment]
Problem with ssh in php is what native extension ext-ssh for php does not support this, and pure php implementation of ssh (phpseclib) supports it only on unix-like systems. 

So here a few way to solve this issue:

* Implement forwardAgent in ext-ssh.
* Add windows support to phpseclib.
* Or add new ssh transport to deployer.

I'm going to do last one in next v4. But do not know then it will be done.

**Comment by elfet** [comment]
Reopened in #808
