### ISSUE TITLE
identifyFile() method does not work as expected

### ISSUE THREAD

**Issue by MatCottet** [deployphp/deployer#421]
Hi,

We try to use deployer for our projects.
But we have some trouble with the connection...
I use this config :
```
server('preprod', 'myserver.net', 22)
    ->user('user')
    ->identityFile()
    ->stage('pre-production')
    ->env('deploy_path', '/var/www/preprod')
    ->env('branch', 'master')
;
```

My coworker uses the same script, but it does not work for him.
```
 [RuntimeException]                              
  Unable to login with the provided credentials. 
```

So he tried to add forwardAgent() :
```
server('preprod', 'myserver.net', 22)
    ->user('user')
    ->identityFile()
    ->forwardAgent()
    ->stage('pre-production')
    ->env('deploy_path', '/var/www/preprod')
    ->env('branch', 'master')
;
```
It works for him but not for me...
So I moved the forwardAgent() :
```
server('preprod', 'myserver.net', 22)
    ->user('user')
    ->forwardAgent()
    ->identityFile()
    ->stage('pre-production')
    ->env('deploy_path', '/var/www/preprod')
    ->env('branch', 'master')
;
```
Works for me... But not for him... :'(

Someone has an idea?

**Comment by elfet** [comment]
Now `forwardAgent()` and `identityFile()` mutually exclusive due to phpseclib implementation. I'm working on new ssh agent for Deployer right now. 
Check if your id_rsa keys in same paths in `identityFile`.

**Comment by MatCottet** [comment]
Yes, our id_rsa keys are in same paths than `identityFile` parameter values.

**Comment by davefuentes** [comment]
Any update on this? We are having exact same issue. We found out that we having different versions of openssh. Can that be the issue? Is there any version supported or required?

I have: 
```
OpenSSH_6.9p1, LibreSSL 2.1.7. 
// No need to use ForwardAgent option
```
Member has: 
```
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011. 
// Needs ForwardAgent option.
```

Here's the server definition:
``` php
server('dev', 'dev.server.com', 22)
    ->user('root')
    ->env('deploy_path', '/var/www/html/')
    ->stage('dev')
    ->identityFile();
```

**Comment by elfet** [comment]
Try to use phpseclib ssh client instead. Or support Deployer 4 development which will have native ssh support.
