### ISSUE TITLE
function onerror($it, $that)

### ISSUE THREAD

**Issue by agarb7** [deployphp/deployer#422]
What about onerror function?

```php
/**
 * Call that task if specified task fails
 *
 * @param string $it
 * @param string $that
 */
function onerror($it, $that) 
{
    // ...
}
```

Usage example:
```php
onerror('deploy', 'rollback');
```

Currently I didn't find simple way to implement this in my recipe. 
I need it because my tasks references to previous release to check deploy ability. Bad release, that wasn't rollback, breaks this behavior.

**Comment by elfet** [comment]
I was thinks on this. And i think better solution is to implement Events in Deployer. This will be main feature in 4.0.
