### ISSUE TITLE
Deplyer with SVN

### ISSUE THREAD

**Issue by adamgajzlerowicz** [deployphp/deployer#427]
Hi guys,

I have used deplyer with my other git projects and I am loving the tool.

I am unable to find the documentation on how to set it up with SVN. Am I missing something?
I have tried in my deploy.php file:

require 'recipe/common.php';
server('ec2', 'server')
    ->user('user')
    ->pemFile('key.pem')
    ->env('deploy_path', '/var/www/website');
set('repository', 'http://user:password@x.x.x.x/repos/branches/development/');

... but no luck. Can you help please?

Many thanks!

**Comment by vanquang9387** [comment]
I think deployer currently does not support SVN and you have to override update_code task in recipe/common.php

**Comment by elfet** [comment]
You can override `update_code` task to checkout from svn.
