### ISSUE TITLE
npm install - when npm is building a module

### ISSUE THREAD

**Issue by lsv** [deployphp/deployer#430]
So I have a npm module browser-sync which is being made on the fly by npm.

Something like this

```
> make: Entering directory `/tmp/dep-npm-test/releases/20150818064438/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
>   CXX(target) Release/obj.target/validation/src/validation.o
>   SOLINK_MODULE(target) Release/obj.target/validation.node
>   SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
>   COPY Release/validation.node
> make: Leaving directory `/tmp/dep-npm-test/releases/20150818064438/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
```

Now this works perfect when using a local server, but when its a remote server, it doesnt work.

On the local, it looks like its generating error code lines (with a red > infront of each line)

I have made a repo which can be tested with
https://github.com/lsv/deploy-npm-test

**Comment by elfet** [comment]
Does your remove server have installed node and npm?

**Comment by lsv** [comment]
@elfet ofcourse, infact if I run npm install and node_modules/.bin/bower install directly on the server everything is fine.

**Comment by lsv** [comment]
Found the problem, though im not sure if its a NPM or deployer problem, but it seems that deployer thinks that NPM is printing errors (notice the red >'s) when it makes the module.

So npm install --silent --quiet (or -sq) added to the command it works fine.

**Comment by lsv** [comment]
The problem was that deployer stopped all task because deployer thinks npm was printing errors, so deployer stopped everything that npm was doing and just go to the next deployer task, which fails because npm wasnt finish making the .bin directory
