### ISSUE TITLE
How to make deploy:writable task skip files

### ISSUE THREAD

**Issue by vanquang9387** [deployphp/deployer#433]
Hi,
I have problem when run deploy:writable task without sudo (using setfacl).
My deploy.php:
```
...
set('shared_dirs', ['webroot/uploads']);
set('writable_dirs', ['webroot/uploads']);
...
```

* On first deploy: everything is OK, I have

dir/file | owner
------------ | -------------
webroot/uploads | deployer

* Later, files created:

dir/file | owner
------------ | -------------
webroot/uploads | deployer
webroot/uploads/image.jpg | apache

* On next deploy, setfacl failed
```
[RuntimeException]
  setfacl: webroot/uploads/image.jpg: Operation not permitted
```

I can not use sudo, how can I make writable task works on this case. In fact, I don't need to setfacl on files owned by apache, so skipping files is OK.

**Comment by elfet** [comment]
Does it work on some previous Deployer releases?

**Comment by vanquang9387** [comment]
I have tried with v3.0.6 only. But I think setfacl command in common recipe has not changed:
```
run("$sudo setfacl -R -m u:\"$httpUser\":rwX -m u:`whoami`:rwX $dirs");
run("$sudo setfacl -dR -m u:\"$httpUser\":rwX -m u:`whoami`:rwX $dirs");
```

**Comment by vanquang9387** [comment]
Excuse me, I have not found a solution for this. Is there anyone facing this problem?

**Comment by elfet** [comment]
Please show `-vvv` log. What is your http user?
How this command executes: `setfacl -R -m u:\"$httpUser\":rwX -m u:`whoami`:rwX $dirs`?

**Comment by vanquang9387** [comment]
@elfet apache is http user and this is the log for writable task:
```
➤ Executing task deploy:writable
⤷ on [local]
Run: ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
> apache
>
Run: cd /var/www/html/project/releases/20150821170801 && chmod 2>&1; true
> chmod: missing operand
> Try `chmod --help' for more information.
>
Run: cd /var/www/html/project/releases/20150821170801 && if hash setfacl 2>/dev/null; then echo 'true'; fi
> true
>
Run: cd /var/www/html/project/releases/20150821170801 &&  setfacl -R -m u:"apache":rwX -m u:`whoami`:rwX app/tmp app/webroot/advs app/webroot/data app/webroot/fonts app/webroot/images app/webroot/masks app/webroot/packs app/webroot/templates app/webroot/thumbs

  Unable to setup correct permissions for writable dirs.
  You need co configure sudo's sudoers files to don't prompt for password,
  or setup correct permissions manually.



  [RuntimeException]
  setfacl: app/webroot/images/1440144441_55d6dc39ce799.png: Operation not permitted
  setfacl: app/webroot/images/1440144423_main.png: Operation not permitted
  setfacl: app/webroot/images/1440144423.png: Operation not permitted
```

Files list:
```
$ ll current/app/webroot/images/
total 112
-rw-r--r--. 1 apache apache 34821 Aug 21 17:07 1440144423_main.png
-rw-r--r--. 1 apache apache 34821 Aug 21 17:07 1440144423.png
-rw-rw-r--+ 1 apache apache 34821 Aug 21 17:07 1440144441_55d6dc39ce799.png
```

**Comment by elfet** [comment]
Can you add deployer user to same group as apache?

**Comment by vanquang9387** [comment]
Added deployer user to apache group.
Deleted deploy dir and did some deployments again.
But that problem still exists.

**Comment by elfet** [comment]
Try to login as deployer on your server and figure out how to run this command properly. This is really depends on your config, and not Deployer code. Same code, same users works just right for me. 
Right way to do it, run command by your self on your server and figure out what is wrong. 
I can not telepathically run this command on your server :)
Iа you find out why this happens, and you know how to prevent other from this - it will be awesome! 100%.

**Comment by vanquang9387** [comment]
Yes, I don't think it's about Deployer code.
Will investigate on this. Thanks @elfet

**Comment by elfet** [comment]
Feel free to ask any questions.

**Comment by vanquang9387** [comment]
It seems to be the same with capifony https://github.com/everzet/capifony/issues/409
When not using `sudo`, `setfacl` should only run once ?
