### ISSUE TITLE
Using deployer server-side

### ISSUE THREAD

**Issue by dkisselev** [deployphp/deployer#440]
The documentation for deployer assumes that every deploying machine/user has SSH access into the production servers, which seems like a security gap to me (and in our case is a nuisance because we need to open firewall holes and user permissions for SSH access).

I'm wondering if anyone has any experiences to share about installing deployer server-side and triggering it remotely. That way there's only one possible config that deployer could run on and there are fewer gaps into production servers.

I see that the docs to talk about the ability to define a local server, but it feels a lot like a footnote and isn't really discussed anywhere, so maybe there are some good reasons to not do it.

**Comment by elfet** [comment]
Absolutely, you can deploy by github hook. Simple run `dep deploy` on deployment machine.

**Comment by zajca** [comment]
In my company we are using jenkins to run deploy. It's basically just have option on deploy start and simple case which runs deployer. Better integration would be great but it's serves well.
```
case "$Deployer" in
"deploy-prod1")
    dep deploy prod1 -vvv;
    ;;
"rollback-prod1")
    dep rollback prod1 -vvv;
    ;;

*)
    echo 'ERR';
    ;;
```
