### ISSUE TITLE
Add option to clear doctrine cache in symfony recipe

### ISSUE THREAD

**Issue by AlexStansfield** [deployphp/deployer#444]
Hey, just had one of my guys banging his head against this one for a couple of hours until we figured out the issue.

He'd made some significant changes in a Doctrine entity and composer was dying when it tries to warm the cache saying a field he'd removed didn't exist. Long story short, we'd forgotten we were using memcache for doctrine meta data caching. 

A simple ```php app/console doctrine:cache:clear-metadata``` sorted the problem out.

I wondered about whether it might be an idea to add an option for the symfony recipe to run this to save people having to add a custom task (I'm kinda bummed that cache:clear doesn't take care of it but oh well).

**Comment by elfet** [comment]
Cool! If you add this as optional task in new `doctrine.php` recipe, and add docs for it - it will be 100% awesome! Other can also bump into this error later, so this will fix it.

**Comment by AlexStansfield** [comment]
Will try to get it done this week. Sorry bit snowed under with work.

Cheers

**Comment by ihsanudin** [comment]
@AlexStansfield : If you use apc, you can't delete the cache using command

**Comment by AlexStansfield** [comment]
I'm aware, this would really be to just execute the ```php app/console doctrine:cache:clear-metadata``` anyone using apc would need to create their own solution as you basically have to do it through a web page.
