### ISSUE TITLE
ssh connection shut down prematurely

### ISSUE THREAD

**Issue by supermonster** [deployphp/deployer#445]
Here's my deployment log:

✔ Executing task deploy:prepare
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:symlink
  Executing task cleanup

Notice: Unable to open channel in phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3255

✔otice: Connection closed prematurely in phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3396
➤ Executing task success

This seems to be happening after several successful deployments. When I remove the releases dir on the server, it solves the problem, but as I do more and more deployments this problem always comes back.

**Comment by oanhnn** [comment]
Please show your version of Deployer, PHP and log from deploy command with debug option `-vvv`
