### ISSUE TITLE
Error on deploy:update_code

### ISSUE THREAD

**Issue by ricardobarantini** [deployphp/deployer#454]
I can do deploy with no problems but when I try to update my code with `deploy:update_code` I get this error:

```
[RuntimeException]                              
Unable to login with the provided credentials. 
```

My deployer version is 3.0.10

**Comment by oanhnn** [comment]
What provided credentials is you used?

**Comment by ricardobarantini** [comment]
SSH key for my private repo in Bitbucket.

**Comment by oanhnn** [comment]
This error is throw from [here](https://github.com/deployphp/deployer/blob/master/src/Server/Remote/PhpSecLib.php#L89)
It is you can't access to your server( not Bitbucket ).
Please check your credentials with native `ssh` command.

**Comment by ricardobarantini** [comment]
I can connect normally in my server by ssh.

**Comment by oanhnn** [comment]
It is maybe problem with key encryption algorithm, it is not support by [`phpseclib` 2.0](https://github.com/phpseclib/phpseclib/releases/tag/2.0.0).
Please try using forward agent to instead of this method.

**Comment by daFish** [comment]
This looks like a duplicate of #214.

**Comment by elfet** [comment]
We really need to implement native ssh client for Deployer 4.0. I can do it by myself, but it needs time....
