### ISSUE TITLE
OPCache invalidate 

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#457]
What about create a task for invalidating OPCache? 
I think this is will be killer feature! 
Take a look:
http://php.net/manual/ru/function.opcache-reset.php
http://ihaveabackup.net/2013/10/19/invalidating-the-opcache-in-php-5-5/

How want to implement this awesome stuff?

**Comment by daFish** [comment]
You could write a custom task to restart `php-fpm` after a successful deployment. This would achieve the same goal but not be viable on installations with high load.

**Comment by elfet** [comment]
Correct!
