### ISSUE TITLE
FTP support?

### ISSUE THREAD

**Issue by ejacky** [deployphp/deployer#458]
can this project support ftp ?

**Comment by elfet** [comment]
With FTP you can only upload and download files. You can not execute commands on remote server. 

You can run Deployer locally, and do not execute commands on remote server with `run`, and only describe tasks for local execution (FTP upload, rsync, etc). 

But main purpose on Deployer is to run on remote servers.

**Comment by ejacky** [comment]
thanks

**Comment by thyseus** [comment]
It is possible to use deployer in conjunction with https://github.com/dg/ftp-deployment .
Only drawback: you have 2 configuration files instead of one file.
I can live with this.
