### ISSUE TITLE
Add support of Phalcon Framework

### ISSUE THREAD

**Issue by dez-php** [deployphp/deployer#459]
I think many would be grateful, and I among them, if you add a recipe for Phalcon Framework

**Comment by ZeeCoder** [comment]
Could you outline the general steps of deploying a Phalcon app?

**Comment by elfet** [comment]
I think users will install Phalcon like this: https://docs.phalconphp.com/en/latest/reference/install.html#linux-solaris
After that `common.php` or `composer.php` will be good start.

**Comment by SananGuliev** [comment]
it is good idea add recipe for Phalcon.

**Comment by SananGuliev** [comment]
it is good idea add recipe for Phalcon. You can use this recipe

https://github.com/SananGuliev/deployer/tree/master/recipe
