### ISSUE TITLE
How to get arguments for server

### ISSUE THREAD

**Issue by lorenzoMarinelli** [deployphp/deployer#464]
Hi,
is it possible to do something like this:

server('prod', input()->getArgument('a'), input()->getArgument('b'))
      ->user(input()->getArgument('c'))
      ->password(input()->getArgument('d'))
      ->stage(input()->getArgument('e'))
      ->env(input()->getArgument('f'), input()->getArgument('g'));

When I try to do something similar I get this: "Fatal error: Call to a member function getInput() on a non-object in phar:///usr/local/bin/dep/src/functions.php on line 507"
input()->getArgument('g') only works inside tasks...

**Comment by ihsanudin** [comment]
What do you want to do? Get argument from input or?

**Comment by lorenzoMarinelli** [comment]
Yes, I want to get user, password, etc from user input...

**Comment by oanhnn** [comment]
@lorenzoMarinelli 
Sorry, `Deployer` not support your case. Please using different configure for different stages (servers).
```
$ dep deploy prod1
$ dep deploy prod2
```
