### ISSUE TITLE
Multiple stages in same server

### ISSUE THREAD

**Issue by spescina** [deployphp/deployer#465]
Hi. I have a setup where I have one server and staging/production stages on it.
I'd like to deploy the same app in these two environment. The only differences behind the two are a bunch of env vars like deploy path and git branch. Is it possible to manage this scenario? tnx.

**Comment by elfet** [comment]
yes! Absolute! Use env vars.

**Comment by spescina** [comment]
Please, can you go further? How can I use `master` branch on `myServer` for the `production` stage?

```
server('myServer', 'example.com', 22)
    ->stage('staging')
    ->env('branch', 'develop');
```

Tnx

**Comment by elfet** [comment]
```
server('myServer', 'example.com', 22)
    ->stage('production')
    ->env('branch', 'master');

server('myServer2', 'example.com', 22)
    ->stage('staging')
    ->env('branch', 'develop');
```
Like this?

**Comment by spescina** [comment]
So I have to define two servers... This is what I've already done so far, but I think this isn't the best way.

Something like that should be better in my opinion
```
server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser')
    ->stage('production')
        ->env('branch', 'master')
        ->env('deploy_path', 'var/www/production')
    ->stage('staging')
        ->env('branch', 'develop')
        ->env('deploy_path', 'var/www/staging');
```
Agree?

**Comment by JHGitty** [comment]
I agree to @spescina ; would be nice to see @ version 4.

**Comment by vanquang9387** [comment]
I think it will be confused when there are many servers in same stage (currently) and a server can act as many stages, too.

**Comment by spescina** [comment]
@vanquang9387 why?

I think this isn't so confusing.

```php
server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser')
    ->stage('production')
        ->env('branch', 'master')
        ->env('deploy_path', 'var/www/production')
    ->stage('staging')
        ->env('branch', 'develop')
        ->env('deploy_path', 'var/www/staging');

server('mySecondServer', 'example.com', 22)
    ->forwardAgent()
    ->user('mySecondUser')
    ->stage('production')
        ->env('branch', 'master')
        ->env('deploy_path', 'srv/www');
```

Isn't it?  
Deploy on **staging** goes on **myServer** `/var/www/staging`.
Deploy on **production** goes on **myServer** in `/var/www/production` and on **mySecondServer** in `/srv/www`.
Deploy on **myServer** goes on `/var/www/staging` and `/var/www/production`.
Deploy on **mySecondServer** goes on `/srv/www`.
Deploy on **myServer / production** goes on `/var/www/production`.

**Comment by vanquang9387** [comment]
>Deploy on staging goes on myServer /var/www/staging.
>Deploy on production goes on myServer in /var/www/production and on mySecondServer in /srv/www

Yes, we are deploying by stage.

>Deploy on myServer goes on /var/www/staging and /var/www/production.
>Deploy on mySecondServer goes on /srv/www.
>Deploy on myServer / production goes on /var/www/production.

Adding option to deploy by server (and stage) bings some more confusion.

In my opinion, it should be thought that "there are many servers in same stage". And I currently config servers of each stage to separated files:
- staging.php: server1, server2
- production: server2, server3

**Comment by oanhnn** [comment]
@spescina @JHGitty 
This way is shorter but it is confused more than current.
@deployphp/maintainer 
I think we should define env vars follow stage. 
After that, we add servers (host, port, user, ...) to stage.
Final, we allow deploy with stage only (not allow with server name).
It is very clean with users.

**Comment by vanquang9387** [comment]
>I think we should define env vars follow stage. 

This is not so good because env vars of same stage maybe different from server to server, such as: deploy_path, etc.

**Comment by spescina** [comment]
@vanquang9387 
> In my opinion, it should be thought that "there are many servers in same stage"

I disagree with this. It's personal, indeed, but in my day to day work I have one server and multiple stages on it, in early project days particularly. So, for me, it's rather confusing talking about multiple servers in one stage. In my use cases servers count is always less than stages count...

@oanhnn 
> And your code after reformat, it is not clean

Do you prefer this?
```php
$myServer = server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser');

$myServer->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', 'var/www/production');

$myServer->stage('staging')
    ->env('branch', 'develop')
    ->env('deploy_path', 'var/www/staging');
```
Same as before from code perspective but different when formatted.

**Comment by JHGitty** [comment]
Oh, hm.. I revert my opinion. Looks wrong after reformat.

**Comment by vanquang9387** [comment]
@spescina 
>It's personal, indeed, but in my day to day work I have one server and multiple stages on it, in early project days particularly.

Yes, I can understand. Sometimes, I also have a server acting as multiple stages on "early project days". But later, deploying by stage is more often.

```
$myServer = server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser');

$myServer->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', 'var/www/production');

$myServer->stage('staging')
    ->env('branch', 'develop')
    ->env('deploy_path', 'var/www/staging');
```
I don't know if this kind of chaining works as you expected.

**Comment by spescina** [comment]
So the goal would be:
I define servers and stages. Then I should be able to link them as I want.
If I have **one server** and **multiple stages** on it I should be able to write something like this
```php
$myServer = server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser');

stage('production')
    ->env('branch', 'master')

stage('staging')
    ->env('branch', 'develop');

// ------------------------------------

$myServer->stage('production')
    ->env('deploy_path', 'var/www/production');

$myServer->stage('staging')
    ->env('deploy_path', 'var/www/staging');
```
If I have **multiple servers** in the **same stage**  I should be able to write something like this
```php
$server1 = server('server1', 'example1.com', 22)
    ->forwardAgent()
    ->user('myFirstUser');

$server2 = server('server2', 'example2.com', 22)
    ->forwardAgent()
    ->user('mySecondUser');

stage('production')
    ->env('branch', 'master')

// ------------------------------------

$server1->stage('production')
    ->env('deploy_path', 'var/www/production');

$server2->stage('production')
    ->env('deploy_path', 'srv/www');
```
If I have **multiple servers** and **multple stages**  I should be able to write something like this
```php
$server1 = server('server1', 'example1.com', 22)
    ->forwardAgent()
    ->user('myFirstUser');

$server2 = server('server2', 'example2.com', 22)
    ->forwardAgent()
    ->user('mySecondUser');

stage('production')
    ->env('branch', 'master')

stage('staging')
    ->env('branch', 'develop');

// ------------------------------------

$server1->stage('production')
    ->env('deploy_path', 'var/www/production');

$server1->stage('staging')
    ->env('deploy_path', 'var/www/staging');

$server2->stage('production')
    ->env('deploy_path', 'srv/www');
```

Then I can deploy where exists the link behind a server and a stage

**Comment by elfet** [comment]
You can do all of this things right now. But you need to copy server.

**Comment by elfet** [comment]
```php
server('myServer', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser')
    ->stage('production')
        ->env('branch', 'master')
        ->env('deploy_path', 'var/www/production')

server('myServer2', 'example.com', 22)
    ->forwardAgent()
    ->user('myUser')
    ->stage('staging')
        ->env('branch', 'develop')
        ->env('deploy_path', 'var/www/staging');

server('mySecondServer', 'example.com', 22)
    ->forwardAgent()
    ->user('mySecondUser')
    ->stage('production')
        ->env('branch', 'master')
        ->env('deploy_path', 'srv/www');
```

**Comment by spescina** [comment]
@elfet
> You can do all of this things right now. But you need to copy server.

I know but I'd like to follow the DRY best practice. These copies confuse me... Why I have to redefine the server each time I add a stage on it? It's weird. I already know how to connect to that server.

But, we're talking about how deployer could be better or we're here just to fix bugs?

**Comment by irfan** [comment]
I totally agree @elfet.

its not about DRY principle @spescina. Think like this, you are separating all your config files depending to the stage in your framework, right? ZF/SF/Yii etc.. But some of them using same configuration like redis/memcache port etc.. But still you have to separate, because when you make any change it should not effect the other configuration.

At the end, those lines acts like configuration defination, it should be separated call.

**Comment by lucasmezencio** [comment]
@antonmedv so, I'm trying to do this:
```php
$homeDir = '/var/www/mysite.com';

host('myserver.com', 'myserver2.com', 'myserver3.com')
    ->stage('prod')
    ->user('crawler')
    ->port(22)
    ->identityFile('~/.ssh/key.pem')
    ->set('deploy_path', "{$homeDir}/prod")
;

host('myserver.com', 'myserver2.com', 'myserver3.com')
    ->stage('dev')
    ->user('crawler')
    ->port(22)
    ->identityFile('~/.ssh/key.pem')
    ->set('deploy_path', "{$homeDir}/dev")
;
```

But I'm getting this error:
```
[Error] Call to a member function stage() on array
```

What am I doing wrong?

**Comment by antonmedv** [comment]
Second call `host('myserver.com', 'myserver2.com', 'myserver3.com')` gives you already defined servers (array of them).

**Comment by lucasmezencio** [comment]
@antonmedv thanks for the explanation. Makes sense.
But then, how to set 2 stages for exactly the same servers list?

Sorry for bothering you, but I didn't understand.
Thanks!

**Comment by antonmedv** [comment]
On you can use host aliases. Or add different host names.

**Comment by antonmedv** [comment]
For now use host aliases, will be fixed in v7 only :( with `stage()` helper.
