### ISSUE TITLE
Deploying multiple repositories

### ISSUE THREAD

**Issue by spotman** [deployphp/deployer#466]
Hi there!

I have a project with directory structure like this:
- core
- public site
- private site

Each directory is independent repository with it's own deploying strategy. I want to deploy the whole project in one "dep deploy" command with cloning each repository to it's own subdirectory inside release path. Is it possible?

**Comment by elfet** [comment]
Yes.

**Comment by spotman** [comment]
@elfet thanks for quick response!
I was digging into deployer's internals and noticed that `deploy:update_code` (and other default functions) is using `cd {{release_path}}`, so there is no way to clone repository to `{{release_path}}/repo_path`. Am I missing something? Did you meant that it can be done via custom tasks?

**Comment by elfet** [comment]
Yes, via custom tasks.

**Comment by spotman** [comment]
Okay, thanks!
