### ISSUE TITLE
Question: Deploy in two servers at the same time

### ISSUE THREAD

**Issue by davefuentes** [deployphp/deployer#468]
I would like to deploy same repository content in two different environments, something like:
```
$ dep deploy prod dev
```
Is it possible? Sometimes when there are errors executing the script, the error mentions something about using -p for parallel:
```
deploy [-p|--parallel]
```

Can you elaborate on this?

**Comment by elfet** [comment]
You can combine them in one common stage.

**Comment by dzanfardino** [comment]
@antonmedv How? is there an example ?
