### ISSUE TITLE
Create a branch for version 4

### ISSUE THREAD

**Issue by JHGitty** [deployphp/deployer#469]
I think we should set the master branch to the branch for the newest development (currently version 4). The current master branch should be named "v3" or something like that.

Currently the master branch is version 3, right?

**Comment by elfet** [comment]
Yes!

**Comment by JHGitty** [comment]
We need this as fast as possible to add new features. :+1:

**Comment by mavimo** [comment]
:+1:

**Comment by elfet** [comment]
Done.
