### ISSUE TITLE
Recipe as class with Interface "Recipe"

### ISSUE THREAD

**Issue by JHGitty** [deployphp/deployer#470]
I think it would be good to have recipes as classes with interface "Recipe".

**Comment by elfet** [comment]
Hmm. May be as alternative syntax? We need simple API.

**Comment by JHGitty** [comment]
For namespaces we need to turn all functions into classes. That because I think it is good to have recipes  as class files.

You can would have two chooses:
a) Load a recipe (-> class file).
b) Do the commands directly (like the functions.php currently, just with a class around it).

**Comment by elfet** [comment]
What the interface?

**Comment by JHGitty** [comment]
```php
$deployer = new Deployer();
$deployer->useRecipt(new SymfonyRecipt());
$deployer->run();
```

Something like this would be nice.

**Comment by elfet** [comment]
? What the interface?
```php
interface Recipe {
  ???
}
```

**Comment by JHGitty** [comment]
The interface would needed to get all recipt information from the recipt object.

```$deployer->useRecipt``` will require one parameter of type ReciptInterface.

The interface could be something like this:
```php
interface ReciptInterface {

public function getHost();
public function getUser();
public function getEnv();

}
```

Another idea would be to have one function which returns an array with all data:
```php
interface ReciptInterface {

public function getRecipt();

}
```

**Comment by elfet** [comment]
First example it’s looks more like Server.
Second, obviously bad idea.

**Comment by JHGitty** [comment]
Yes, the second one is a bad idea. Just to write down all ways how you could do it. :+1:
