### ISSUE TITLE
Unset task?

### ISSUE THREAD

**Issue by lsv** [deployphp/deployer#472]
So if Im fx using the symfony recipe, and there is 1 task I dont want to be executed, is there any method to "unset" this task?

Actually it is the assetic task I dont want to run (I dont use assetic), so this task

```
task('deploy:assetic:dump', function () {

    run('php {{release_path}}/' . trim(get('bin_dir'), '/') . '/console assetic:dump --env={{env}} --no-debug');

})->desc('Dump assets');
```

I want to not run.

Ofcourse I could copy the whole symfony recipe and then removing this 1 task and use that instead - but it seems like over doing it.

**Comment by tmarly** [comment]
Hi Martin,

May be I'm wrong, but I don't think it's possible to remove a task.
However, you can override it with an empty function. For example:

`
task('deploy:assetic:dump', function () {});
`

This line must be set *after* 'require 'recipe/symfony.php'

++

**Comment by oanhnn** [comment]
Current `deployer` not support removing a task, but you can override a task as @tmarly 's comment.
```
task('deploy:assetic:dump', function () {})->setPrivate();
```

**Comment by elfet** [comment]
This is good idea! We need API for removing  tasks.

**Comment by patwebrussell** [comment]
2020 and still not done lol

**Comment by antonmedv** [comment]
@patwebrussell 2020 and some people not contributing, lol.

**Comment by patwebrussell** [comment]
It does not help that the topic was closed anyway hehe

**Comment by antonmedv** [comment]
I can disagree. Clearing issues is really helping me with prioritizing work. If somebody still interesting in this feature - open a discussion or send a PR.

**Comment by patwebrussell** [comment]
I my opinion we could probably do somathing like

task('deploy:assetic:dump')->unsetTask();

What's your toughts?

**Comment by antonmedv** [comment]
Maybe disable()?

**Comment by ThaDaVos** [comment]
Any progress on this? Currently wanting to disable some tasks from the laravel recipe as they are not available for lumen - as there is no lumen recipe

**Comment by ThaDaVos** [comment]
I've found a dirty way: `task('artisan:config:cache')->onStage(null);` -> just set a filter with value `null` disables the task
