### ISSUE TITLE
Feature idea: add a plugin system to deployer

### ISSUE THREAD

**Issue by mneuhaus** [deployphp/deployer#474]
Hey, i got an idea to enable a simple kind of Plugin system, especially useful for the packaged phar version of deployer.

The main idea consists of an additional command ```PluginCommand``` (open to suggestions about another name ;). This command would have several actions like "install, update, remove". These actions are basically only a "proxy" for ```composer [require|update|remove] foo/bar``` actions. That composer command gets executed in a global central location, for example under ```/Users/username/.deployer/``` on Mac. Additionally that path gets added to the include path, so that you can access those installed packages easily with a relative path.

**Example:**

install the existing [```deployphp/recipes```](https://github.com/deployphp/recipes) package as a plugin for deployer:

```
dep plugin install deployphp/recipes
```

this will install that package under ```/Users/username/.deployer/vendor/deployphp/recipes/```
The path ```/Users/username/.deployer/vendor``` is automatically added to the include path of deployer on every command, so you can have a ```deploy.php``` like this in a project: 

```php
<?php
require 'deployphp/recipes/recipes/slack.php';
...
```

This Plugin system would enable countless modular Packages to be created for different Frameworks/Hosts/etc without the need to add deployer as a dependency to the projects you're trying to deploy. 

If this is something that you guys would accept into deployer itself i'd be willing to create a proper pull-request for that :) I already did a rough prototype to test my idea, you can check it out here: 

[[WIP] add a plugin system](https://github.com/mneuhaus/deployer/commit/fd961f7ae74ae9fd87e55e9d43c1ea4033c90300)

**Comment by oanhnn** [comment]
Thank for your idea. I think this feature will be available in Deployer 4.x :+1:

**Comment by mneuhaus** [comment]
So, you guys are already Wirkung in this/something similar?
Has the 4.0 dev already started? If you linke i could pitch in in this :-)

**Comment by elfet** [comment]
I think we does not neeв another tool which will copy composer functionality.

**Comment by mneuhaus** [comment]
well, i don't really mean duplicate composer functionality, that command would only provide a simple facade to install packages in that global directory that deployer would take into account through the set_include_path.

if you don't like the idea of the plugin command itself, how about only including a central global directory, so you can manage those packages in that central directory "manually" with composer?

**Comment by elfet** [comment]
But you can do all this staff with composer right now! `--global` option.

**Comment by mneuhaus** [comment]
well, yea now i get what you mean ^^
you're absolutely right, i can install ```deployphp/recipes``` globally through:

```
composer global require deployphp/recipes
```

and then use that in my ```deploy.php``` by extending the include path: 

```
set_include_path(get_include_path() . PATH_SEPARATOR . getenv('HOME') . '/.composer/vendor/');
```

i guess than you can ignore this feature request, the only thing that could be neat to include would be to mention this possibility in the docs, and possible add that global composer path directly in deployer?
