### ISSUE TITLE
Better support for rollbacks

### ISSUE THREAD

**Issue by mkurzeja** [deployphp/deployer#475]
Hi,

I'm looking for a new deployment tool and deployer looks awesome - thanks for the great work you have done!

I have some concerns about rollbacks. 

*Sample scenario:*
The deployment process consists of several steps:
- prepare
- release
- update code
- assets
- database migrations
- restart cache

Now lets assume the last step 'restart cache' fails. Currently deployer would only remove the release directory but it should also revert the db migrations.

We could probably add a very simple mechanism to improve rollbacks, similar to the one in Capistrano.
There is a simple function that allows to add rollback closures. Then the rollback command executes all registered closures [LIFO].

What do you thin about it? Maybe you have some better ideas how to improve rollbacks?

**Comment by elfet** [comment]
Hi,

I'm planning to create functionality like this in Deployer v4. It will be using event system. 

But now i haven't mach time to work on Deployer v4.
