### ISSUE TITLE
Deployment fails on first run

### ISSUE THREAD

**Issue by alaczi** [deployphp/deployer#477]
with version 3.0.10 when the code checks the dir of the actual release symlink, the process crashes with a Runtime Exception as the release dir does not exist.

A workaround to create the symlink manually before trying the first deployment.

env('release_path', function () {
    return str_replace("\n", '', run("readlink {{deploy_path}}/release"));
});

**Comment by alaczi** [comment]
Ah, ok, I misinterpreted the command, I needed the deploy:release before the deploy:update_code.
The documentation really needs some update :D

**Comment by elfet** [comment]
Can you create PR for docs?
