### ISSUE TITLE
Laravel deployments

### ISSUE THREAD

**Issue by blsn** [deployphp/deployer#478]
On my Ubuntu VirtualBox I use the ‘laravel/homestead’ Vagrant box, can I use the 'deployer.org' solution to deploy my app on a remote server? because I saw in your website 'Laravel Recipe' status is: TODO.    

If yes, is there any tutorial for Laravel?

**Comment by kenjis** [comment]
deployer has Laravel recipe: https://github.com/deployphp/deployer/blob/master/recipe/laravel.php

**Comment by oanhnn** [comment]
@blsn Sorry by document on website is not update.

**Comment by elfet** [comment]
@deployphp/maintainer can any one update this? Really need help at this.

**Comment by pelletiermaxime** [comment]
That Laravel recipe has a few bugs, like a missing 'deploy:writable' task in the main deploy task and I disagree with the shared dirs. It's also lacking many features to run migrations, refresh the caches, etc. I will probably send a PR if nobody beats me to it.

**Comment by elfet** [comment]
Yes! Send PR. It is really cool!

**Comment by blsn** [comment]
I try to deploy a Laravel testing app using the following ```deploy.php``` link:
https://gist.github.com/GesJeremie/f8c59c097b67da29e30b

..but I get the following exception error:
```
vagrant@homestead:~/sites/test_app$ dep deploy prod
✔ Executing task deploy:prepare
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:vendors
✔ Executing task deploy:writable
✔ Executing task deploy:shared
✔ Executing task deploy:symlink
  Executing task assets

  [RuntimeException]
  bash: line 0: cd: /home/vagrant/deployer/releases/20151121013206/front: No such file or directory
```
debug mode:
```
:
:
➤ Executing task assets
⤷ on [prod]
Run: cd /home/vagrant/deployer/releases/20151121005601/front && npm install

  [RuntimeException]
  bash: line 0: cd: /home/vagrant/deployer/releases/20151121005601/front: No such file or directory
:
:
```
Any help would be appreciated.

**Comment by GesJeremie** [comment]
My deploy.php file fitted my project, I cleaned it just for you ;) https://gist.github.com/GesJeremie/f8c59c097b67da29e30b
