### ISSUE TITLE
Exception with ssh config file

### ISSUE THREAD

**Issue by obstschale** [deployphp/deployer#481]
Hi,

I read the deployer documentation and on the [Server Page](http://deployer.org/docs/servers) there it is mentioned that it is possible to use a SSH config file like:

```php
server(...)
    ->user('name')
    ->configFile('/path/to/file');
```

That sounds nice and I use it like:

```php
server('name', 'myserver.com')
	->user('user')
	->configFile('~/.ssh/config')
	->env('deploy_path', '~/html/example.com');
```

But when I execute my task an exception in [`Server/Remote/PhpSecLib.php:85`](https://github.com/deployphp/deployer/blob/master/src/Server/Remote/PhpSecLib.php#L85) is thrown:

```
 [RuntimeException]
  You need to specify authentication method.
```

I took a deeper look at deployers source code and found out that in [`PhpSecLib.php`](https://github.com/deployphp/deployer/blob/master/src/Server/Remote/PhpSecLib.php#L51-L86) the switch statement is used to decide how to connect to the server. The switch expression `$serverConfig->getAuthenticationMethod()` outputs for my situation the integer `2` like defined in [`Configuration.php`](https://github.com/deployphp/deployer/blob/master/src/Server/Configuration.php#L19-L23).

The interesting part is now: In this particular switch statement is no case for `AUTH_BY_CONFIG` defined. So, I'm not surprised anymore it is not working.

Can you please implement this case. Thank You.

**Comment by elfet** [comment]
Hi! 
Yes, it's true. PhpSecLib does not support this method for now. But it's really easy to implement. Any body can implement this? @obstschale I can't to implement myself it right now, i need to make money for living now)

**Comment by obstschale** [comment]
Hey @elfet - thx for your reply. No problem, get to it when you have time or I will take a look at it if I have time.

But please, don't document stuff which is not implemented yet. That is really annoying :smile:

**Comment by elfet** [comment]
Will be implemented in v.4

**Comment by rdohms** [comment]
So we cannot use "configFile" at all?
Not sure how this is closed, maybe it should be left open and assigned to a milestone?

**Comment by Azuka** [comment]
Hi. Has this been implemented yet?
