### ISSUE TITLE
Сustom php binary path

### ISSUE THREAD

**Issue by dmkuznetsov** [deployphp/deployer#484]
On some virtual hosting platforms for correct deploy we need to specify php binary.

For instance:

```bash
/opt/php54/bin/php composer.phar install
```

I suggest to create new environment var, for example "php_bin" with default value "php"

**Comment by elfet** [comment]
Why not using `alias php='/opt/php54/bin/php'`?

**Comment by dmkuznetsov** [comment]
Just "php" is busy with old version of php. 
I've tried to create .bashrc with alias, but It's not working for me.

**Comment by lbausch** [comment]
`.bashrc` is only taken into account for interactive shells.  You may check for `.profile` instead.

**Comment by elfet** [comment]
Then try `env('php', '/path/php')` and then use: `run('{{ php }} ...')`.

**Comment by dmkuznetsov** [comment]
@lbausch thanks! It's work!

@elfet I resolved my issue by overriding tasks ```deploy:vendors```, ```deploy:assetic:dump```, etc.

In generally yes, users can create alias and put in ```.profile```, but True-way is put this variable in configuration

**Comment by wesleywesley** [comment]
.bashrc does not work, .profile does not work, env('php', .. ) does not work. Exactly as @dmkuznetsov said, we need an environment variable to specify PHP version. Or a way to set the PATH variable and use it in all subsequent calls (better!)

**Comment by elfet** [comment]
Will be in Deployer v4. #586

**Comment by whyte624** [comment]
There is {{bin/php}} env variable now.
