### ISSUE TITLE
How to point to 'current/public' folder?

### ISSUE THREAD

**Issue by blsn** [deployphp/deployer#486]
I successfully deployed on the remote VPS.. and now I try to point the Apache default welcome page to `/path/to/project/CURRENT/public`.
I changed the file ‘000-default.conf’ in **sites-enabled**,
from:
`DocumentRoot /var/www/html`
to:
`DocumentRoot /var/www/html/current/public`
(http://stackoverflow.com/a/14966435/1315169),
but I get **server error** when I browse to the homepage.

my **deploy.php**:
``` php
require 'recipe/laravel.php';
server('prod', 'myipaddress', 2210)
    ->user('root')
    ->password('mypassword')
    ->stage('production')
    ->env('deploy_path', '/var/www/html');
set('repository', 'https://github.com/my/repo');
```
###### Please anybody can help me on how to point correctly to `current/public` folder.

**Comment by kenjis** [comment]
It seems your Apache config is something wrong. See your Apache error.log.

**Comment by blsn** [comment]
I did fresh installation, no errors found in the log file.
I get the Apache default welcome page if I don't change the default conf file above. 

Do you think that the way I perform it above in my question is correct?

**Comment by kenjis** [comment]
You need the folder `/var/www/html/releases/20151122161240/storage/logs` but you don't have it.

**Comment by blsn** [comment]
Thanks, I see what you mean, I'll try to fix it.

**Comment by elfet** [comment]
:+1:

**Comment by blsn** [comment]
I still cannot solve it... 
Git ignore the folder ```storage/logs``` when I try to add files to it.

Using the forcing command ```git add --force storage/logs``` the file ```laravel.log``` is now showing up on GitHub (```storage/logs/laravel.log```).

The command ```dep deploy prod``` is giving me 'successfully deployed' but the file is not created on the remote server, and I get the following error message (Apache error.log):

```
[Mon Nov 23 13:48:17.175385 2015] [:error] [pid 21486] [client 2400:cb00:29:1024::6ca2:f0b2:53773] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/releases/20151123183024/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/releases/20151123183024/bootstrap/cache/compiled.php:13301\nStack trace:\n#0 /var/www/html/releases/20151123183024/bootstrap/cache/compiled.php(13239): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/releases/20151123183024/bootstrap/cache/compiled.php(13002): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/releases/20151123183024/bootstrap/cache/compiled.php(13098): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#3 /var/www/html/releases/20151123183024/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(50): Monolog\\Logger->error(Object(UnexpectedValueException))\n#4 /var/www/html/releases/20151123183024/app/Exceptions/Handler.php(33): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueE in /var/www/html/releases/20151123183024/bootstrap/cache/compiled.php on line 13301

```

Any advice will be appreciated!

Notify: @kenjis
