### ISSUE TITLE
The writable_dirs task makes files also writable

### ISSUE THREAD

**Issue by Mihailoff** [deployphp/deployer#49]
https://github.com/elfet/deployer/blob/master/recipe/common.php#L138

I think there should be distinction like we have with ```shared_dirs``` / ```shared_files```.

Probably more intelligent way is to get rid of such difference and have only one ```shared``` option witch will able to guess is given argument a file or a directory.

```
set('shared', ['app/logs/', 'app/config/parameters.yml']);
set('writable', ['app/logs/', 'app/logs/*', 'app/public/whatever']);
```

Slash at the end treated as directory, file otherwise. Asterisk explicitly says that it is recursive.

**Comment by elfet** [comment]
Done.
