### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#490]
Can any body figure out why?

**Comment by MaartenStaa** [comment]
Seems like the [IP_REG_EXP](https://github.com/deployphp/deployer/blob/master/test/recipe/RemoteServerTest.php#L12) only accounts for IPv6. Maybe it should be something like `'#^(::1)|(127.0.0.1)$#'`?

**Comment by oanhnn** [comment]
Fixed with #501
