### ISSUE TITLE
 [RuntimeException] Too many arguments. - when define localServer

### ISSUE THREAD

**Issue by plusik** [deployphp/deployer#491]
Can you tell me what I am doing wrong? I do not understand

deploy.php
```
<?php

localServer('server1')
	->env('deploy_path', '/home/plus/sites_dev')
	->stage('local');



task('myDeploy', function () {

	// Your tasks code...
	run('if [ ! -d {{deploy_path}} ]; then mkdir -p {{deploy_path}}; fi');
	
})->desc('Deploy my site');
```

run this command:
```[bash]$ dep myDeploy server1```

output:
```

  [RuntimeException]
  Too many arguments.



myDeploy [-p|--parallel]

```

**Comment by kr1zmo** [comment]
I just had the same issue.

I solved this problem by adding a call to the `env( ... )` function on the server declaration.
I'm going to assume it's required?

```php
server( ... )
    ->env('deploy_path', '/your/project/path');
```

**Comment by elfet** [comment]
You need to specify options. See `common.php` recipe.

**Comment by plusik** [comment]
Thank you very much ^)

**Comment by pniederlag** [comment]
So basically there is a dependency/requirement to either:
- include recipes/common
- need  to specify some arguments

I'd seen a similar issue on gitter and it just took me a couple of hours to find out about this "obstacle" today. So it seems like a  common cause of troubles and failures as it's hard to spot.

**Comment by elfet** [comment]
What you suggest to do?

**Comment by pniederlag** [comment]
aim:
- make a default deployer.php without including any of the recipes more failure tolerant *or* provide a recipe that is really trimmed down to the most minimal effort to get deployer working.
("ping", "hello world", or "uptime")

rationale:
- recipe/common as the most simple recipe already provide a lot of tasks that migth not be useful in all cases (our use case: legacy projects)

ideas:
- move definition of "must have" arguments to some other place that is *always* included by default
- add some recipe/blank that is trimmed down to the real must have arguments
- improve documentation "getting started" and add a hint to this issue, or the essence of it ;)

Does any of this make sense to you? I could provide a PR for a recipe/blank and/or documentation if that is of any help.

Thx for getting back on this!
