### ISSUE TITLE
Deploying _really_ huge project.

### ISSUE THREAD

**Issue by IngwiePhoenix** [deployphp/deployer#493]
Currently, whenever I put out a new dev build of my [BIRD3](https://github.com/DragonsInn/BIRD3) project, I'd usually do

```
$ ssh user@server
$ cd /srv/bird3
$ screen -ls # Find the screen running the server
$ screen -r $SCREEN_ID
$> CTRL+C
$ git pull
$ npm start
```

... Manually. Since I use Gitlab and Github, I am definitively sure that this all could be automated in one way or another - at least, that the server is started and stopped by the deploy tool.

Thing is, I do not want to put my credentials at risk, yet still include my deployer file in my VCS. So, how do I best hide my password from VCS?

**Comment by elfet** [comment]
Define your deploy script in `deploy.php` and define servers with password/keys in `servers.yml` outside of repo: http://deployer.org/docs/servers (see *Servers list*)
