### ISSUE TITLE
how to use the arguments or options

### ISSUE THREAD

**Issue by tttlh** [deployphp/deployer#494]
can't find it in docs

**Comment by oanhnn** [comment]
You can find it in [here](http://deployer.org/docs/tasks)
Or using `bin/dep --help`
If you have any more question, you can join [gitter.im](https://gitter.im/deployphp/deployer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) to be supported

**Comment by elfet** [comment]
```
argument('stage', InputArgument::OPTIONAL, 'Run tasks only on this server or group of servers.');

option('tag', null, InputOption::VALUE_OPTIONAL, 'Tag to deploy.');
```

```
input()->getOption('tag');
```

**Comment by tttlh** [comment]
thanks.I didn't see the input function.
