### ISSUE TITLE
Password authentication and agent forwarding does not work at the same time

### ISSUE THREAD

**Issue by x3ro** [deployphp/deployer#498]
I ran into the situation where I couldn't authenticate on a server that uses password auth, but still needs agent forwarding to be enabled to clone the repository. In other words, the following will never try to authenticate with a password:

    server('some server', '192.168.1.55, 22)
        ->user('username')
        ->password("strongpassword")
        ->forwardAgent()

If this is a `wontfix` I think it should at least throw an error message when two incompatible authentication schemes are used at the same time :smile: 

PS: Deployer seems great so far. Thanks for making it :)

**Comment by oanhnn** [comment]
Currently, deployer only support only authentication method at the same time.
In your case, when call `->forwardAgent()`, authentication method is set to `Configuration::AUTH_BY_AGENT` and it wont using password method.

Now, you should use public key method and forward agent. Good luck!
