### ISSUE TITLE
Stream and display command output from server (e.g. tail of logs)?

### ISSUE THREAD

**Issue by seanw** [deployphp/deployer#502]
I want to write a task to stream and display live logs from a server along the lines of this:

task('logs', function () {
   run("tail -F -n 200 /usr/local/apache/logs/error_log");
});

Deployer seems to only show command output when the command finishes and if there was an error when I want this to display new log entries from stdout as they appear. Is there a standard way to make this work or even a quick hack for it like getting access to the SSH connection object and doing it myself? I had a look but the Server/Remote/PhpSecLib.php interface doesn't seem to give enough access to the output of the SSH command to do this.

**Comment by elfet** [comment]
As i know PhpSecLib and ssh2 extension does not provide this feature. I'm going to implement native ssh client in next release of Deployer. But now need to work at my other projects.

**Comment by ekandreas** [comment]
+1

**Comment by irfan** [comment]
I do not think deployer should do this. Watching apache logs is not a part of "deployment" process. The library should be able to show only the logs which is related to deployment. I mean, for me deployer is not server management tool.

To watch apache logs, you can define an alias to your .bashrc or .profile file like

alias prodlog='ssh user@production "tail -F -n 200 /usr/local/apache/logs/error_log"'
and just run prodlog command

**Comment by elfet** [comment]
Agree with @irfan

**Comment by seanw** [comment]
It's not so much for watching logs but when I do a deploy I want to do a quick manual check that the deploy didn't break anything and rollback if something went wrong. Forcing me to put the scripting somewhere else means I have to duplicate the scripting for connecting to servers which deployer takes the pain out of. The .bashrc approach also isn't great because it's not under source control and it's not shared between developers.

For comparison, Heroku's CLI tools has commands for deploying, viewing logs, rolling back and SSHing into servers and I find it greatly simplifies server management which is what I was hoping I could use deployer for.

**Comment by irfan** [comment]
Seems fair enough, I don't know what is the objective of Deployer. For me, these features that you mention might be another project which is using Deployer under the hood.

**Comment by elfet** [comment]
No watch in deployer.

**Comment by ged15** [comment]
@antonmedv what's the reason you've decided to never implement this? Output streaming would help when a script run on remote server outputs some data continuously during deploy.

**Comment by antonmedv** [comment]
@ged15 what do you mean by "outputs some data continuously during deploy"? Can you show an example?

**Comment by ged15** [comment]
One of our deployment scripts stops background processes just before switching the symlink. This script sends the stop command to the processes and waits for them to stop. While waiting, it continuously polls and streams output to the terminal like so:

```
 ** [out :: 10.10.20.10] Waiting 2s for some_worker (11482 on @DC1)...
 ** [out :: 10.10.20.10] Waiting 3s for some_worker (11482 on @DC1)...
 ** [out :: 10.10.20.10] Waiting 4s for some_worker (11482 on @DC1)...
 ** [out :: 10.10.20.10] Waiting 5s for some_worker (11482 on @DC1)...
 ** [out :: 10.10.20.10] Waiting 6s for some_worker (11482 on @DC1)...
 ** [out :: 10.10.20.10] Waiting 7s for some_worker (11482 on @DC1)...
...
```

Capistrano is able to output each line as it is output by the script and Deployr buffers the output until the script terminates and then outputs it all.

**Comment by antonmedv** [comment]
Okay, I think can implement this. PLease open an new issue and describe feature.

Btw, composer install outputs without buffering for me, and full log can be displayed.

**Comment by ged15** [comment]
@antonmedv my mistake, this works great for me too :) only blocker now is for me now is https://github.com/deployphp/deployer/issues/1419
