### ISSUE TITLE
Run other tasks in "task" function

### ISSUE THREAD

**Issue by qixiaobin** [deployphp/deployer#506]
It would be good to run other tasks in task definition, such as:
task("my_task", function(){
      run_task("deploy:prepare");
      run("something I want to do");
      run_task("deploy:release");
      run("another thing I want to do");
      ......
});

**Comment by oanhnn** [comment]
You can try:

```
task('task1', function(){
    run('something you want to do');
});
task('task2', function(){
    run('another thing I want to do');
});
task('my_task', [
    'deploy:prepare',
    'deploy:release',
]);
after('deploy:prepare', 'task1');
after('deploy:release', 'task2');
```
Good luck!
