### ISSUE TITLE
Set Branch on Deployer

### ISSUE THREAD

**Issue by brunofonseca** [deployphp/deployer#507]
Hello!
I am using the Deployer in my Laravel 5.1 project, and so far had no problem in configuration and application deployment. However, I like to know how to put a branch 'production' for when you deploy using it as standard. Currently when you deploy, you're using my development branch.

Grateful.

Bruno Fonseca.

**Comment by oanhnn** [comment]
You can use:
   server('dev-svr', '192.168.11.3', 22)
    -user('dev')
    ->env('branch', 'master');

I am using mobile, please see more in [here](https://github.com/oanhnn/deployer-example)
