### ISSUE TITLE
[RuntimeException] - Host key verification failed.                

### ISSUE THREAD

**Issue by brunofonseca** [deployphp/deployer#510]
Hi, 

I configured my deploy.php file with my information about the repository. However, when running the deployer it returns me this error below. What might be happening?

[RuntimeException]                                   
  Host key verification failed.                        
  fatal: Could not read from remote repository.        
  Please make sure you have the correct access rights  
  and the repository exists.

Thanks!

Bruno Fonseca

**Comment by oanhnn** [comment]
You try by your terminal and show result to here?
```
$ ssh -T deploy-user@hostname
```

**Comment by brunofonseca** [comment]
Hello!

The problem was because apparently my instance did not know the repository that I was trying to access, in other words, I had never accessed the repository and saved the git_cache.

In this case, I accessed remotely, and made a checkout of the repository without the deployer. It worked.

It would be interesting to add to a nearby feature the deployer this possibility if there is no git cache, the deployer request User and password. I do not know if you ever work that way and I do not know.

Grateful.

**Comment by oanhnn** [comment]
Yes. Deployer supported this feature.
If using password failure, you can try with public key or forward agent.
Goodluck!

**Comment by milesstewart88** [comment]
I'm still getting this issue! How do I fix it?

**Comment by jakenoble** [comment]
Try and log in using the same user using terminal, ensure it works using your key then retry, it crashes if any prompt appears when first logging in.

**Comment by milesstewart88** [comment]
@jakenoble nice one. I had created an ssh key for the wrong user duhhhhh! Thanks Jake
