### ISSUE TITLE
Cannot find composer or node commands

### ISSUE THREAD

**Issue by markbucknellcc** [deployphp/deployer#513]
Hi,

When the following line runs from deployer to my VPS:

run("cd {{release_path}}/app && npm install");

it tells me that npm is not installed, however when I run that command directly through my terminal window it works? I'm stumped!

**Comment by markbucknellcc** [comment]
I am also using the same user for SSH and Deployer

**Comment by oanhnn** [comment]
Your can try run `whereis npm` and show path to npm ?
After that, use it instead 'npm' command.
```
run("cd {{release_path}}/app && /usr/bin/npm install");
```

**Comment by markbucknellcc** [comment]
I've had a look into the issue and the problem is that the PATH for the deploy user isn't properly initialised when SSH ing into the server using PHPSecLib. 

SSH using Putty the path is:

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/deploy/bin:/home/deploy/bin 

SSH with deployer (PHPSecLib) the path is:

PATH=/usr/local/bin:/usr/bin

There are a couple of options to fix it. 

Firstly you can append "source /home/deploy/.bash_profile" to each of your deployer run() functions, which will find npm, node etc. e.g.

run('source /home/deploy/.bash_profile && npm');

Secondly, you could install bower, node, npm etc in the /usr/local/bin directory of the server and this would mean that the standard PATH would still find the binaries.

**Comment by oanhnn** [comment]
I think this problem are:
http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/#
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

**Comment by elfet** [comment]
I think we need same pages %)
