### ISSUE TITLE
symfony 3 recipe support

### ISSUE THREAD

**Issue by smithandre** [deployphp/deployer#514]
Seems like the symfony recipe doesn't support the symfony 3 directory structure yet. 
* console command moved to bin folder
* cache & logs moved to var folder. 

I guess the recipe just needs to be tweaked some more to accommodate these

**Comment by oanhnn** [comment]
Current, Deployer support symfony 2.x as default.
If you want switch to symfony 3.0, you can modify recipe follow http://deployer.org/docs/recipes
```
set('shared_dirs', ['var/logs']);
set('writable_dirs', ['var/cache', 'var/logs']);
set('bin_dir', 'bin');
set('var_dir', 'var');
after('deploy:vendors', 'database:migrate');
```

**Comment by pierredup** [comment]
IMO Deployer should support Symfony 3, it makes it easier to integrate with a project.
There is nowhere a cookbook or article to get Deployer to run with Symfony 3, so it might not be immediately clear for developers what they need to do.

Also Deployer already supports Drupal 7 & 8, Yii & Yii 2, so why not add support Symfony 3 as well?

I have created a simple PR (#515) to add a new recipe for Symfony 3

**Comment by oanhnn** [comment]
Current, Deployer supported Symfony 3.0, but it not default (because at that time, symfony 3.0 is not stable).
Please see docs before make issue.
http://deployer.org/docs/recipes
We can make it to dèault.

**Comment by pierredup** [comment]
Symfony 3 is stable for a couple of months now. But I don't think the Sf3 structure should be default, since it might take a while for all projects to upgrade to version 3.
That is why I suggest having a recipe for both version 2 and 3. That makes it the easiest for developers to get started with Sf3.
Not everyone will always read the docs

**Comment by oanhnn** [comment]
@elfet What are you think about making recipes with framework and version?

**Comment by elfet** [comment]
I think having framework+version (symfony,symfony3 recipe) bad idea. A lot of task will be same, as a lot of configs. But for now i do not see any other solution. Maybe have a config for version?

**Comment by pierredup** [comment]
> I think having framework+version (symfony,symfony3 recipe) bad idea. A lot of task will be same, as a lot of configs

But you do this for Drupal (7 & 8) and Yii (1 & 2)

**Comment by elfet** [comment]
Yes, maybe it's time for finding better solution. Or to keep adding version recipes. 

framework + version is simplest solution for now. Maybe live it as it?
