### ISSUE TITLE
Add composer global require

### ISSUE THREAD

**Issue by nadar** [deployphp/deployer#518]
As far as i could see, there is no possibility to include global composer plugins after downloading the composer.phar file (The only solution would be to write the whole composer tasks by myself)? If there is no possibility to set composer global requirments, a solution could be to split the `deploy:vendors`task in two tasks

1. task to download phar file
2. task to execute composer install.

This way the users could easy add a task after downloading the phar (1.) which contains the global definitions.

```
task('deploy:afterPharDownload', function () {
    run('php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"');
});
```

**Comment by oanhnn** [comment]
@nadar 
composer global install and global require package is running once time. I think you should create a custom task do it yourseft.
Thank you.
