### ISSUE TITLE
runLocally realtime output

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#520]
There was a heads up / update that provided runLocally with realtime output. How do I accomplish that without calling the tasks with a -vvv param?

**Comment by elfet** [comment]
Why you need this?

**Comment by ekandreas** [comment]
I'm loosing the env-settings between tasks. I solved it via setting the env every time in every task.

**Comment by ekandreas** [comment]
I'm running unit tests inside a Docker instance and need to see the ongoing output from the execution.

**Comment by acrozes** [comment]
Did you find a solution ? I have the same request ...

**Comment by dima-stefantsov** [comment]
Could we get real time output please?
Why do I need it? If tasks that I run take big amount of time, I want to know what's going on. Some of it may take days, no feedback is bad.

For reference, when I run things locally, real time output can be achieved with
```
use \Symfony\Component\Process\Process;
$process = new Process($command, $root, null, null, null);
$process->run(function($type, $buffer) {
    echo $buffer; // Realtime output!
});
```

**Comment by igloocube** [comment]
Use the tty option to achieve this:

```
task('phpunit', function() {
    runLocally('vendor/bin/phpunit', ['tty' => true]);
})
```
