### ISSUE TITLE
[Insight] Files should not be executable

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#521]
> Your project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files: 
- src/Type/Password.php

```bash
chmod a-x 'src/Type/Password.php'
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/69072898-df4a-4dee-ab05-c2ae83d6c469/analyses/407)_

**Comment by elfet** [comment]
How that's possible?

**Comment by oanhnn** [comment]
Yes. Sorry, it is tmp class. I am committed incorrect. I will removed it.

**Comment by elfet** [comment]
:+1:
