### ISSUE TITLE
localServer upload() doesn't work with directories

### ISSUE THREAD

**Issue by jorgeorpinel** [deployphp/deployer#524]
Example task:

``` php
task('deploy:upload', function() {
  upload(dirname(__FILE__), '{{release_path}}');
})->desc('Upload the entire current folder');
```

In this case (specifying 2 folders in `upload($local, $remote)`), `dep stage deploy:upload` outputs:

``` sh
PHP Warning: copy( ... failed to open stream: No such file or directory
```

for each file in $local recursively.

If only one is a folder, it outputs:

``` sh
PHP Warning: ... The second argument to copy() function cannot be a directory
```

and nothing is copied.

File in question is [src/Server/Local.php](https://github.com/deployphp/deployer/blob/master/src/Server/Local.php#L41-L44).

Works with regular `server()` definitions (non local).

**Comment by lsv** [comment]
Would it be an idea to change PHP copy command to something like

```
function recurse_copy($src,$dst) { 
    $dir = opendir($src); 
    @mkdir($dst); 
    while(false !== ( $file = readdir($dir)) ) { 
        if (( $file != '.' ) && ( $file != '..' )) { 
            if ( is_dir($src . '/' . $file) ) { 
                recurse_copy($src . '/' . $file,$dst . '/' . $file); 
            } 
            else { 
                copy($src . '/' . $file,$dst . '/' . $file); 
            } 
        } 
    } 
    closedir($dir); 
} 
```

Or maybe use [Symfony Filesystem component](http://symfony.com/doc/current/components/filesystem/introduction.html)?

**Comment by elfet** [comment]
File systems comp is ok,

**Comment by jorgeorpinel** [comment]
@lsv could be (:

@elfet if you say so (:
