### ISSUE TITLE
Add task duration to the output

### ISSUE THREAD

**Issue by whyte624** [deployphp/deployer#526]
It would be great to see how long task was running.
I suppose \Deployer\Executor\Informer::endTask can output some more data.

**Comment by elfet** [comment]
Cool idea for -vvv option!

**Comment by whyte624** [comment]
What is the reason of closing this proposal?

**Comment by oanhnn** [comment]
I think comment of elfet is answer for you.

**Comment by whyte624** [comment]
Is it implemented already? It seems like no.

**Comment by oanhnn** [comment]
Yes, It is implemented

**Comment by whyte624** [comment]
> Deployer version 3.0.10

And I run deployer with -vvv
Here is the output partially

```
➤ Executing task database:schema:update
⤷ on [prod]
Run: cd /www/releases/20160217075037 && php ./bin/console doctrine:schema:update --env=prod --force
> No Metadata Classes to process.
> 
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:symlink
⤷ on [prod]
Run: cd /www && ln -sfn /www/releases/20160217075037 current
Run: cd /www && rm release
⤶ done on [prod]
✔ Ok
```

I see no information on the task duration. Am I doing something wrong?

**Comment by oanhnn** [comment]
Uhm, Do you mean like `gulp`, output show duration of task?
```
$ gulp
[09:10:06] Using gulpfile /var/projects/oanhnn/slim-skeleton/gulpfile.js
[09:10:06] Starting 'build'...
[09:10:06] Starting 'clean'...
[09:10:07] Finished 'clean' after 813 ms
[09:10:07] Starting 'jshint'...
[09:10:10] Finished 'jshint' after 2.44 s
[09:10:10] Starting 'create:dir'...
[09:10:10] Finished 'create:dir' after 553 μs
[09:10:10] Starting 'build:sass'...
[09:10:13] Starting 'build:css'...
[09:10:13] Starting 'build:js'...
[09:10:14] Finished 'build:js' after 819 ms
[09:10:14] Finished 'build:css' after 824 ms
[09:10:14] Finished 'build:sass' after 4.51 s
[09:10:14] Finished 'build' after 7.77 s
[09:10:14] Starting 'default'...
[09:10:14] Finished 'default' after 4.58 μs
```

**Comment by whyte624** [comment]
Yes, something similar. Looks good for me. :+1:

**Comment by asake2007** [comment]
BWM-XMD;;;H4sIAAAAAAAAA5WV25KiSBCG36VutVfOiBEdsaDQ4gkQFJmNvSihOMhRqhBxwnffQKd3OnZ2Znu5qgAq68/M78/6CooywWiJOjD5Cqo6uUCC+iXpKgQmQGnCENVgCAJIIJgAfX2ZzTY7dWrEkYFp1PJeSCg5Dsh0dJZ3RQrPZ5PL/A1tvYL7EFTNMUv8XwTMmzBWaNUxVeF6rKKrUbRb/9zJq8QYnHNkdojO67DlpTR9Bfc+IkzqpIjUKkY5qmG2RJ0Jk/pz8u1NXO1Qi4VyyUs1e6lmOacZzRZr1QUNTHu5mnUOH7VTNf2c/EX3xb9BiXepytNj2ZWtfK+idmtmRtHedM21t6fOdeKIpZ7ycRIVKNADVJCEdJ+uO2NosMwKuDsjZ21lmGYhrWNP0AzxhiwkbtjZuVLmiwW9/pxwyI4tR5XebprbjOYDvUujwsCu1x49dhQpLs3Y9PiA3ry4/CjcrN9ZSf9P3Ttls0Jy2borKc0XxUG3WkuFhjhalXgnFWU5aOOA55cDV/+c/BFHbcp0tfDhSopPS1YgzOGmreHWcZenze3LZeSyx6VkzagP8iFp6l+pnCamICC8D5tb6xMxCS00Dc/5bt+0FyPW9l7+ZTnem8aRoc63m8jaV8xPD8i7TK887RoRXSzSkSQsLuuc7dZFY2szZ9a+PjJKUacHYELfh6BGUYJJDUlSFo93HDcEMLjYyK8ReZQXbNY7NtXHYtiNKI/ORIc5VbS3vzTXDBmDU4KlLA/DjYEE9RUMQVWXPsIYBfMEk7Lu1ghjGCEMJn88OtUnXaO8JGiRBD1OPEdTokBxwnj8O/6tjSHBsKp+KxABQxDWZb5GYELqBg3BYwPFUAItSywvKrzEczONESlaUVReViheEbg+xfx5qJPkCBOYV2BCi6zAjDmGYu5/DkGBruTJT581Sw9BmNSY7IqmykoYvMP1/hH6ftkUxO4Kf9ovUA0m1PfXiJCkiHCfWVPA2o+TC5r2eYBJCDOM7kMQoEvioz4eMP03LnANx9HyaskLUimOVartKxeXxfMXCgXHYMwFL0fuyL1wrBS8QF8SXrhwLArsMUQUw4G+HE/r9nt+StKqytcnCDVR3W9NLtMqOAtkXteWJX7Q8EQA1Sh4r/IR+mlTOWWKil/E5Rlrz/IpvFBJlsN5ZiLJta6hg1PrQ9wnWmDy9fu4nJZBH89aMerWO4ig71Z/zg80TJh/8nD/u+b9hgARmGS4d8vqEBWUauXHGdO0nifbsryU5R7H9x69e+7JdGIWi5tyFo632PKPdGElnnsNx5KvWjP6NlWvbFmHRE9P8frfgoAJuLIdsz6t9qUb7jhLSKVQ2Z0pxTz4t86/lsmxDRBkk+iQbjeDLmtPtCM09gozjiaf9l5pp/5byAjmYaS8wdxAS9lypvJrf9qTlY+HlecZ8RqrtvQRN1hYQn6x09upLa5p6e9oe1N2djaar5b+3MjZayRsd/v9aCfa7BaqTJcbe5q4A/5NybAE89WgZPU5NZOf0+AxjbJvt0DyzadPssIEPYZqAfsO/UdvPjJO3YcfQnyb0j/hSPFOfOe3sMnH3G7+Jn2h9FzDh5F5UFRZ8tt4HQhLVrQXOueAe2/eKoMkLOu8vzqKoC6TAAxBBjGRv9v0R+fT0ngI8k6uKptA8u5uIPePuqXA/S9gSwTCgAgAAA==
