### ISSUE TITLE
Multiple deploy scripts

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#531]
How do I separate deploy scripts in separate recipes?
In my case I'm using the "common" recipe. In that file there's a mandatory "stage" argument like so:
```
argument('stage', \Symfony\Component\Console\Input\InputArgument::OPTIONAL, 'Run tasks only on this server or group of servers.');
```

I'm also using deploy scripts to start and stop Docker containers. In these scripts I'm not interested in the "stage" argument and everything should run on the local environment. But still, my deploy.php needs the common recipe and forces the need of the stage argument.

It would be nice if the stage argument really was optional and not forced as now.

Or perhaps possible to create a file "docker.php" and use ``dep docker`` as command. When the "docker" command is missed in "deploy.php" then PHP-Deployer should look for tasks in "docker.php".

**Comment by elfet** [comment]
You can specify file for dep commend. `-f, --file[=FILE]`

**Comment by ekandreas** [comment]
Ok, to bad :-(

**Comment by ekandreas** [comment]
How come the InputArgument::OPTIONAL isn't optional?
