### ISSUE TITLE
Cann't save PATH env

### ISSUE THREAD

**Issue by sidz** [deployphp/deployer#538]
Hi.
I have a question:
why run command can't save PATH env between each other and how I can do this?

I need set PATH because I have a multiple version of PHP, and one project use php >=5.5.
```
run('PATH=/opt/phpbrew/php/php-5.6.17/bin:$PATH');
run('echo $PATH');
```
show me PATH env without PATH=/opt/phpbrew/php/php-5.6.17/bin
but when I run:
```
run('PATH=/opt/phpbrew/php/php-5.6.17/bin:$PATH' && echo $PATH);
```
I can see that my path there.

or maybe deployer have variable which can help me install path to php?

p.s. I review code, and I found that composer install command hardcoded.
maybe we can add env('php_path') or smth like this? 

I think, I can make a pull request if it will be needed

**Comment by elfet** [comment]
```
run('export PATH=/opt/phpbrew/php/php-5.6.17/bin:$PATH');
run('echo $PATH');
```

**Comment by wesleywesley** [comment]
i have the same issue, @elfet i tried your solution, it has no effect.

**Comment by elfet** [comment]
Add it into your `.bashrc`.

**Comment by sidz** [comment]
This is no a good option, what if I have a testing server with a different php? If I set in the .bashrc it will be global option for this user. But I want to set php version temporary or I need an option to set a php version for composer.

**Comment by elfet** [comment]
I think to configure php bin dir in env for Deployer v4.

**Comment by marvinhinz** [comment]
Is there a recommended way to do this? Even if php bin path is configurable, this config is not always honored. For example composer calling post install scripts "typo3cms cache:clean" which uses this header: #!/usr/bin/env php.

**Comment by akosglue** [comment]
@marvinhinz have you found any solution to this?
