### ISSUE TITLE
Symfony 2 users are shutdown from >3.0.0?

### ISSUE THREAD

**Issue by appeltaert** [deployphp/deployer#545]
Why not copy the old recipe to a new recipe called symfony2? I mean, 2.7/8 are supported to 2018/19.

**Comment by elfet** [comment]
Because a lot of people use Deployer. And this is BC.

**Comment by appeltaert** [comment]
Nevermind i found the culprit, it's assumed that assetic is used. I thought it might have been included by default starting 3.0 since i never use it, but its actually removed from the core package since 2.8.
I guess copying the default recipe to suit the needs is best after all.
