### ISSUE TITLE
Split downloading of composer.phar and installing project dependencies in deploy:vendors task

### ISSUE THREAD

**Issue by arogachev** [deployphp/deployer#548]
I suggest to split `deploy:vendors` task to two separate tasks:

- 1st will just download `composer.phar` file.
- 2nd will install project Composer packages.

The benefit of this is we can execute custom tasks after 1st one is completed, for example: installation / update of global packages.

Example with Yii2 framework - we need to install [Composer Asset Plugin](https://github.com/francoispluchino/composer-asset-plugin) *before* installing project packages:

```
composer global require "fxp/composer-asset-plugin:~1.1.1"
```

This is only needed on first installation, then we only need to update this plugin.

Skipping installation of this plugin leads to errors and application will not be working. Currently both Yii2 recipes ([basic](https://github.com/deployphp/deployer/blob/master/recipe/yii2-app-basic.php) and [advanced](https://github.com/deployphp/deployer/blob/master/recipe/yii2-app-advanced.php)) lack this, that means users have to install it separately on their own.

This is not limited to just Yii2 of course.

Writing custom task is not appropriate because there is no way to inject custom task now and we need duplicate code from `deploy:vendors`.

Related - https://github.com/deployphp/deployer/issues/518.

**Comment by nadar** [comment]
:+1:

**Comment by elfet** [comment]
I think this is cool thing to have. May be in next release 4.x.

**Comment by arogachev** [comment]
@elfet So what's the reason of closing in this case?

**Comment by elfet** [comment]
Because we found better solution: custom bin. Will be in next release.

**Comment by arogachev** [comment]
OK, this sounds more clear.
