### ISSUE TITLE
Call a task from another task

### ISSUE THREAD

**Issue by loranger** [deployphp/deployer#550]
Hello,

I'd like to being able to call a task from another one, but I can't find any way to achieve it.
I did search and found other people trying to do it too (#522, #506, #322) but the answers are workaround, not real solutions.

For example, I'd like to call a recipe task conditionnaly :

```php
task ('notify:slack', function () {
    if (env('slack')) {
        call('deploy:slack');
    }
});

after('deploy', 'notify:slack');
```

It would also be convient if we could use it with askConfirmation, for instance :

```php
task('composer:confirm', function(){
    if(askConfirmation('Do you need to update your dependencies ?', true)){
        call('deploy:vendors');
    }
});
```

An other way to achieve it would be to being able to get env variable from outside a task, but it seem tight binded to the context :

```php
$tasks = [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
];

if (env('slack')) {
    array_push($tasks, 'deploy:slack');
}

task('deploy', $tasks);
```

Please could you consider this feature request ?

**Comment by elfet** [comment]
Hi! This is common question. But according to Deployer structure this is does not possible (It will broke parallel deployment at all).
But there is a solution. `call('deploy:slack');` it's look like a function call and can be a function: `callDeploySlack();` whick can be called there it's needed.

```php
$subtask_1 = function () {...};
$subtask_2 = function () {...};

task('subtask_1', $subtask_1):
task('subtask_2', $subtask_2);

task ('task', function () {
    if ($condition) {
        $subtask_1();
    } else {
        $subtask_2();
    }
});
```

See more in #522.

**Comment by oanhnn** [comment]
@elfet What are you think about "Task may be object"?
It will be extended easily !

**Comment by elfet** [comment]
It's good thing, but i do not see how it will work with current "function" task. May be some cool feature for Deployer 4. (two types of tasks? func and object?)
Now Deployer offers [Task](https://github.com/deployphp/deployer/blob/master/src/Task/Task.php) class. May be it's should be abstract class? Or `TaskInterface` for Deployer 4?

**Comment by filippoth** [comment]
Thanks for the tool elfet, it's awesome.

I was also trying to achieve calling a task from a task, because I would like to add a confirmation before running a rsync. I ended up with an ugly solution which is calling the deployer with run Locally again :)

`task('deploy', function() {
    if (!askConfirmation('Are you sure? This will write to production')) {
        writeln('<comment>Aborted</comment>');
        return 0;
    } else {
        runLocally("dep rsync -vvv");
    }
});`

**Comment by elfet** [comment]
Calling task from another task does not implemented yet. I'll try to implement it if will have free time.
If you like tool you can support via patreon: https://www.patreon.com/deployer
