### ISSUE TITLE
Can you deploy a commit by its SHA hash?

### ISSUE THREAD

**Issue by seanw** [deployphp/deployer#552]
I made an attempt at doing this by setting the "tag" and "branch" variables but got this:

warning: Could not find remote branch 253d2d7d26e7c8da204326009ce45c514f928c45 to clone.
fatal: Remote branch 253d2d7d26e7c8da204326009ce45c514f928c45 not found in upstream origin

**Comment by sustmi** [comment]
I think it is not possible with the current `common` recipe.
You can override the default `deploy:update_code` adding this to your `deploy.php` to run:
`git clone $repository` (without shallow copy, in contrast to shallow clone in default task)
`git reset --hard $commit`

**Comment by oanhnn** [comment]
@seanw Sorry, current task `deploy:update_code` in `recipe/common` not support commit hash.
Please custom this task or create a branch for your commit hash.
