### ISSUE TITLE
Interactive dependency prompt for bower install 

### ISSUE THREAD

**Issue by monyiliev** [deployphp/deployer#553]
Hello, I am using a simple recipe to deploy on a staging server that requires a `bower install`. 

Everything runs smoothly until `bower` presents an interactive prompt to ask for a dependency version (in my case angular). If I run it on the server, I can select my choice, but with deployer it exits with 
```
 [RuntimeException]                                                                                       
  bower                                             ECONFLICT Unable to find suitable version for angular 
```  
Not sure if this is `phpseclib` related and if the completion of #348 will fix it or there is something I could do to get the interactive prompt work. 

All help and advice is highly appreciated.

Here's my task:
```php
/*
 * Run bower install
 */
task('deploy:bower_install', function () {
  cd('{{release_path}}');
  run('bower install');
})->desc('running bower install');
```
```
Deployer version 3.0.10
PHP 5.5.30
Bower 1.7.7
Deployment target: Ubuntu 14.04 LTS
```

Thanks.

**Comment by elfet** [comment]
Hi, 

Configure bower to not asking you about it :)
