### ISSUE TITLE
write() weird output on short strings

### ISSUE THREAD

**Issue by cronfy** [deployphp/deployer#555]
When write()/writeln() is used inside a task to print short string (1 or 2 chars), it gives weird output. Consider this `deploy.php`:

### example 

```php
<?php

localServer('test');

task('test', function() {
        writeln("b");
});
```

`dep test` would output:

```
$ dep test
➤ Executing task test
b[k
✔ Ok
```

Note these symbols after ```b```.

### example with use case

Use case is when you want to print some message in a task, separated from other output with newlines:

```php
task('test', function() {
        writeln("\n\n\nHello\n\n\n");
});
```

It prints some characters at the beginning:

```
$ dep test
➤ Executing task test
[k


Hello



✔ Ok
```

### info

```
$ dep -V
Deployer version master
```

I tried it in 2 environments:

1. FreeBSD 8.4, PHP 5.4.16
2. Linux Mint 17, PHP 5.5.9-1ubuntu4.14

**Comment by elfet** [comment]
Very strange bug. Try to run with -vvv option.

**Comment by cronfy** [comment]
with -vvv it's ok:

```
$ dep test -vvv
➤ Executing task test
⤷ on [test]
b
⤶ done on [test]
✔ Ok
```
