### ISSUE TITLE
Task may be a callable

### ISSUE THREAD

**Issue by oanhnn** [deployphp/deployer#557]
Task may be a callable
```
task('task1', function() {});
task('task2', 'functionname');
task('task3', 'NameSpace\\ClassName');
task('task4', new Object());
task('task5', [$object, 'methodName']);
```

**Comment by elfet** [comment]
Nice! way to solve task/object problem.

**Comment by oanhnn** [comment]
I implemented this feature in https://github.com/oanhnn/deployer/tree/feature-task-may-be-callable
Changed:
- Task may be defined from a callable
- Task group be defined by function `taskGroup`

**Comment by oanhnn** [comment]
I will add more test cases before make a PR. :smile:

**Comment by elfet** [comment]
Cool!.

**Comment by oanhnn** [comment]
Merged!
