### ISSUE TITLE
releases_list items are not checked to be a release

### ISSUE THREAD

**Issue by cronfy** [deployphp/deployer#558]
If any other files/directories appear in deploy_path/releases/ dir, deployer thinks it is a release without any check. It leads to problems with keep_releases: instead of releases deployer keeps other entries.

Live example:

```sh
deploy/releases$ ls -1
20160216103038
20160216105529
20160216105529.bak
20160216110130
runtime
```

`runtime` is a garbage from slightly misconfigured yii. `20160216105529.bak` is a manually created backup.

`dep cleanup` in this sutuation (assuming that keep_releases is 3) would remove last 2 releases, leaving only latest one along with `runtime` and `20160216105529.bak`:

```sh
20160216105529.bak
20160216110130
runtime
```

Thus current behaviour may lead to unwanted removal of releases. It can even remove all releases including current.

**Comment by elfet** [comment]
@deployphp/maintainer what you think?>

**Comment by oanhnn** [comment]
I am agree with @cronfy :+1:

**Comment by cronfy** [comment]
What about pull request I submitted? Is it ok or needs rework to be accepted?
