### ISSUE TITLE
There is no way to be send a notification if a deploy fails.

### ISSUE THREAD

**Issue by philbates35** [deployphp/deployer#564]
I'm hoping to have deployer sit on a dedicated build/deployment server, and have a deployment triggered by a git webhook.

If a deploy fails for whatever reason, I want to notify the team - e.g. via email, or Slack message. It would be nice to be able to do something like the following in `deploy.php`:
```
exceptionHandler(function($exception) {
    // E.g. Send message to Slack channel
});
```
I can't currently see a way in which I could do something like this as they are always handled by Deployer - there's no opportunity for me to even do a `try catch` in `deploy.php`.

I think this callback should happen every time an exception is thrown, regardless of whether it is non fatal or not, and leave it up to the develop to handle different type of exceptions, and decide whether they should notify for not fatal exceptions or not.

**Comment by clphillips** [comment]
This would be nice, but I'd take it a step further. We need the ability to step execution of subsequent tasks in some circumstances. For example, if checkout fails, no need to run composer, etc.

**Comment by elfet** [comment]
@philbates35 this will come in Deployer v4 with events system.

@clphillips you can throw an exception to stop execution.

**Comment by philbates35** [comment]
Good to hear thanks. :)

Is there a roadmap page of planned release dates in the future? I couldn't see one. Or is it just a case of "it's ready when it's ready"?

**Comment by elfet** [comment]
There is no roadmap, because it’s is created in free of work time. But you always can support development if it’s needed.

**Comment by philbates35** [comment]
Understand completely. :)

**Comment by devonblzx** [comment]
@elfet In regards to throwing an exception to stop execution, are there are plans for the ability to stop execution on only one server in multi-server execution?  For example, if a task fails on one server, that server stops and reports an error, but all other servers may finish the entire task group.

**Comment by elfet** [comment]
@devonblzx now we does have such feature. But it may interesting for Deployer v4. Some thing like deploy strategy.

**Comment by rlacerda83** [comment]
https://github.com/deployphp/deployer/pull/740
