### ISSUE TITLE
More useful exceptions and breaking execution

### ISSUE THREAD

**Issue by devonblzx** [deployphp/deployer#566]
So this is a two parter.  I'm not sure if this will be handled with v4.   However, when hitting RuntimeExceptions, I saw an opportunity to make better use of a thrown exception from a run() call.

For this, I created a TaskException which allows you to set/get the exit code, stderr, and stdout.

https://github.com/deployphp/deployer/compare/master...virtualcomplete:feature1/taskexception

This would allow you to do something like this within a task to better handle the exception.  As of right now, I didn't see any way that the exit code is exposed.

``` php
    try {
        run('sh exit1.sh');
    }
    catch (\Deployer\Exception\TaskException $e) {
        writeln("<error>Exit Code ".$e->getCode()." on ".env('server.name')."</error>");
        writeln("<error>Output: ".$e->getStdout()." on ".env('server.name')."</error>");
        writeln("<error>Stderr: ".$e->getStderr()." on ".env('server.name')."</error>");
    }
```

My current code only adds this to phpseclib, as I did not have the ssh2 library installed and I also saw that there is going to be native ssh2 support in v4.

**Breaking execution**

Another useful addition to this would be allowing you to break execution on the server within the task.  Allowing this server to fail, but any other server that does not receive this error can finish as planned.  I'm looking for inputs on this as I haven't had enough time to go through the classes yet to see how this works with parallel execution.

**Reasons why this is useful**

Allows users to deploy on servers regardless if one of many fails.  Allows users to make tasks that react to certain errors and even allow error correcting within the tasks.

Let me know your thoughts.

**Comment by elfet** [comment]
Well i think this will go to v4.1 or v5.

**Comment by devonblzx** [comment]
@elfet Awesome, let me know if you need any help with anything.

**Comment by elfet** [comment]
Done, see #1092
