### ISSUE TITLE
Adding session directory to symfony3 recipe

### ISSUE THREAD

**Issue by dfuhrmann** [deployphp/deployer#570]
Symfony 3 uses the directory var/sessions to store all sessions created. This directory is missing in der symfony3 recipe.

It should at least be added to the "writable_dirs" array. Additionally I think it should be also added to the "shared_dirs" array to ensure that the sessions are not destroyed during deployment.

Source that it should be writable:
http://symfony.com/doc/current/book/installation.html#checking-symfony-application-configuration-and-setup

**Comment by oanhnn** [comment]
Thank for your report!
