### ISSUE TITLE
Laravel application and shared folders

### ISSUE THREAD

**Issue by dexbarrett** [deployphp/deployer#572]
I'm trying out this library and everything seemed going well until I noticed some problems with the folders the Laravel framework needs to be writable. If I only set those folders as writable and not shared the permissions are set correctly, but if I set those folders as both writable and shared they won't get the writable permissions. I don't use the Laravel recipe but a custom file based on the majority of that recipe; I just added the **writable_dirs** task and some other things my app needs.

Am I missing something or why could this be happening? I could leave those folders as only writable but not shared, but that wouldn't be useful because shared folders are the main point of an atomic deployment.

Hope I explained myself. Thank you.

**Comment by philbates35** [comment]
I noticed this too. I found that the writable permission was being set correctly on the `storage` directory in each release (it appears in each release because `storage` isn't a shared directory, it's the subdirectories in the `storage` directory that are shared), but the writable permission wasn't being set on the subdirectories that were shared (`storage/app` etc).

**Comment by elfet** [comment]
Hi guys. Need to check if deploy:writeable task can make shared folders writable. May be this feature is missing.
@oanhnn can you check?

**Comment by oanhnn** [comment]
@dexbarrett @philbates35 
Please show a part of your `deploy.php` file. It may be help me to reproduce this issue.

**Comment by dexbarrett** [comment]
@oanhnn Sure. This is my deploy.php file. I'm testing it locally first, before testing on a VPS. 

    require_once 'recipe/common.php';

    //shared dirs
    set('shared_dirs', [
        'storage/app',
        'storage/framework/cache',
        'storage/framework/sessions',
        'storage/framework/views',
        'storage/logs',
        'public/images/book-covers',
        'public/images/book-photos/photos',
        'public/images/book-photos/thumbnails'
    ]);


    //writable dirs
    set('writable_dirs', [
    	'bootstrap/cache',
    	'storage',
    	'public/images/book-covers',
        'public/images/book-photos/photos',
        'public/images/book-photos/thumbnails'
    ]);

    //tasks

    task('migration', function() {
      run('php {{release_path}}/artisan migrate --force');
    })->desc('Artisan migrations');

    task('env_file', function() {
    	upload('/home/localuser/.librosjbenv', '{{release_path}}/.env');
    })->desc('Copy environment file');

    task('reload:apache', function() {
    	run('service apache2 reload');
    })->desc('Reload Apache Server');


    task('deploy', [
        'deploy:prepare',
        'deploy:release',
        'deploy:update_code',
        'deploy:vendors',
        'deploy:shared',
        'deploy:writable',
        'deploy:symlink',
        'env_file',
        'migration',
        'cleanup',
    ])->desc('Deploy your project');

    after('deploy', 'reload:apache');
    after('deploy', 'success');



    localServer('local')
    ->user('localuser')
    ->stage('local')
    ->env('deploy_path', '/var/www/librosjbprod');

    set('repository', 'repo_path');

**Comment by oanhnn** [comment]
@dexbarrett Thank for your `deploy.php` file
I think it may be one of the following cases:

1. You using `chmod` to set permissions writable, after that, `www-data` user (`apache` user) make log  and cache files with its ownership. If that, you need sudo to change permissions. This way is not recommaned.

2. When task `deploy:shared` run, it make symlinks. After that, task `deploy:writable` run, it only change permission of symlink. If that, you should change setting `shared_dirs` and `writable_dirs` . Eg.
   ```
   // Laravel shared dirs
   set('shared_dirs', ['storage', 'public/images', 'public/game', 'public/api']);
   // Laravel writable dirs
   set('writable_dirs', ['storage', 'bootstrap/cache']);
   ```

**Comment by oanhnn** [comment]
> give the write permissions to the folder the symlinks point to (in this case, the shared folder that Deployer creates)

Right
But in my server (using `setfacl`), it running with script:
```php
// Laravel shared dirs
set('shared_dirs', ['storage', 'public/images', 'public/game', 'public/api']);
// Laravel writable dirs
set('writable_dirs', ['storage', 'bootstrap/cache']);
```
I will debug this issue when i have more time.

**Comment by barryvdh** [comment]
Is this still an issue? I suggest to change the writeable/shared folders to shared entire `storage` and use a symlinked public storage folder, see #619
