### ISSUE TITLE
Symfony-cache is not writable if deployer runs on another user than the httpd 

### ISSUE THREAD

**Issue by nemoinho** [deployphp/deployer#575]
I installed and configured deployer on a clean new installation and use different users for deployment and httpd.

So the directories are owned by my deployment-user. Due to the recipe of symfony and symfony3 the cache should be writable for users of the same group but after the cache warmup the prod-directory looks like this (php_deployer is my deployment-user www-data is also in group php_deployer):

    drwxrwxrwx 3 php_deployer php_deployer 4096 Mar  8 00:11 .
    drwxr-xr-x 4 php_deployer php_deployer 4096 Mar  8 00:11 ..
    drwxr-xr-x 6 php_deployer php_deployer 4096 Mar  8 00:11 prod

But to run symfony it has to be 

    drwxrwxrwx 3 php_deployer php_deployer 4096 Mar  8 00:11 .
    drwxr-xr-x 4 php_deployer php_deployer 4096 Mar  8 00:11 ..
    drwxrwxr-x 6 php_deployer php_deployer 4096 Mar  8 00:11 prod

I created a workaround for this that looks like this:
    
    /**
     * Make cache writable again after warmup
     */
    task('deploy:make_cache_writable', function () {
        run("chmod -R g+w {{cache_dir}}");
    })->desc('Make cache writable again');
    
    after('deploy:cache:warmup', 'deploy:make_cache_writable');

**Comment by oanhnn** [comment]
:+1:  
This is great way to resolve this problem. But deploy user not always has group www-data.
I think it is a special case, you should write a blog or Wiki. We will insert link in document of Deployer.
What are you think? @elfet

**Comment by elfet** [comment]
Yes! I really want to create better docs, i think this is 50% success of open source libs.
I think about section with hot-to or faq.

**Comment by nemoinho** [comment]
I'm totally fine with that, but I have one appeal left. If you do so you should remove the lines [49-51](https://github.com/deployphp/deployer/blob/master/recipe/symfony.php#L49-L51) from the symfony-recipe because they are just confusing and have not really an effect.

**Comment by oanhnn** [comment]
Thank @nemoinho , I will check it.

**Comment by nemoinho** [comment]
After some research I found another possible reason for this behaviour. The deploy-task of the symfony-recipe has the wrong order in my opinion:
    
    /**
     * Main task
     */
    task('deploy', [
        'deploy:prepare',
        'deploy:release',
        'deploy:update_code',
        'deploy:create_cache_dir',
        'deploy:shared',
        'deploy:writable',
        'deploy:assets',
        'deploy:vendors',
        'deploy:assetic:dump',
        'deploy:cache:warmup',
        'deploy:symlink',
        'cleanup',
    ])->desc('Deploy your project');

The task `deploy:writable` should be called after the warmup because all previous tasks should always run with the privileges of the deploying user and after that the recipe-specific configuration should be set. In that case all the given functionality of the recipe can be used, and `set('writable_dirs', […])` works again as expected.

But the marked lines are still obsolete ;-)

**Comment by elfet** [comment]
Done.
