### ISSUE TITLE
Deploy from local machine

### ISSUE THREAD

**Issue by mehrdaad** [deployphp/deployer#578]
Sorry for creating a new issue but I've got a problem.
Right now for a project I'm using git locally but that's not on any site like github.  
I want to deploy my app directly from my machine to the vps.  
Is it possible to deploy my app from my local master branch to vps directly?
And if not how about deploying the whole directory to the vps?

**Comment by jakenoble** [comment]
Have you attempted to install git on your VPS?

`apt-get install git`

**Comment by mehrdaad** [comment]
@jakenoble yeah git is installed. What I don't figure out is how to deploy from my machine?  
What is configuration on deployment on my end?

**Comment by jakenoble** [comment]
What have you tried so far?

You start the deployment process from your local machine and it SSH's to your remote, uses git to download the code base and set up your app.

**Comment by mehrdaad** [comment]
``uses git to download the code base and set up your app.`` this is the problem.
The project is not on GitHub. so ``set('repository', 'git@github.com:org/app.git')`` is nonsense.
The whole project is on my local machine. could I describe my problem?

**Comment by jakenoble** [comment]
It doesn't need to be on github, just in a repo that Deployer supports.

If you're not using some sort of source control then you have bigger issues. Even if you're a lone developer like myself.

**Comment by mehrdaad** [comment]
@jakenoble let me say this way: my project is not on any online source control online like GitHub, bitbucket etc. But I'm using git locally. now I want to deploy my app from my machine to vps.  
That's all I need.

**Comment by jakenoble** [comment]
I do not think Deployer does this.

I think you need something else then or a custom solution, your case seems fairly niche.

**Comment by mehrdaad** [comment]
I don't think this is niche. There are many cases that a developer want to deploy to vps from local machine. Isn't it?

**Comment by sr972** [comment]
Already tried `set('repository', 'file:///<pathtoyourlocalgit/app.git')` or `set('repository', '/<pathtoyourlocalgit/app.git')` ?
Just a shot in the dark...

**Comment by jakenoble** [comment]
@sr972 I am fairly sure that will fail, its run from the remote VPS, so `file:///` will not exist.

**Comment by sr972** [comment]
Oh sure.. Checkout is going to proceed on remote not on local.. My fault...
But you can use `runLocally(string $command)` and checkout local and then rsync it to the vps.

**Comment by oanhnn** [comment]
@mehrdaad 
You can follow steps:
1. Make your local machine to git server, it is may be access from your remote machine
2. `set('repository', 'git@your-local-machine:org/app.git')`
3. run deployer

https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server
https://www.linux.com/learn/tutorials/824358-how-to-run-your-own-git-server

**Comment by elfet** [comment]
Or you can use this recipe: https://github.com/deployphp/recipes/blob/master/docs/rsync.md

**Comment by oisvidi** [comment]
Why not use bitbucket? Unlimited free private repos for teams up to 5 people. How git basically works is you have a repo on your machine and usually a master on a remote server. 
You push to that master repo, tag it and push tag, then use deployer to deploy to your webserver. 

Anything not in the master repo does not exist as far as any developers on your project are concerned.

**Comment by mehrdaad** [comment]
@oisvidi Din't know bitbucket was free for small teams.Tnx for telling! tnx

**Comment by vanquang9387** [comment]
@mehrdaad GitLab.com is also a very good choice.
https://about.gitlab.com/gitlab-com/

1. Unlimited repositories
2. Unlimited private collaborators
3. 10GB disk space per project (including Git LFS)
4. Unlimited total disk space
5. Completely free, no credit card required

**Comment by rogeriolino** [comment]
Hi @mehrdaad 

I was with same trouble and I fix it overriding the `deploy:update_code` task: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L173

```php
// skip git clone
task('deploy:update_code', function () {});
```

Then you can just copy the local directory to your deploy server via ssh.

**Comment by AlexeyPlodenko** [comment]
Otherwise try the following PHP script, that builds your project in a Docker container and then uploads it to your server https://github.com/AlexeyPlodenko/myDeploy

**Comment by AlexeyPlodenko** [comment]
@antonmedv Was the mentioned issue introduced in your script please? Because, that was the reason I have created my script.
