### ISSUE TITLE
Configurable bin file

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#586]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A
#538 
Allow user to specify there to look for php bin.

```php
env('php_bin', function () {
    return run('which php');
});
```

**Comment by oisvidi** [comment]
Support for reading composers bin-dir instead of writing it multiple places? https://getcomposer.org/doc/06-config.md#bin-dir

**Comment by nemoinho** [comment]
He meant PHP itself. I really like the idea, because than I can use deployer as well to deploy legacy code which may needs special php-versions.

**Comment by gperdomor** [comment]
@elfet i submit a PR to handle this issue :D

**Comment by elfet** [comment]
I see, need more time for testing.

**Comment by oanhnn** [comment]
@elfet I think we allow setting up all bin path like:
```
env('bin.php', function() {
   return run('which php');
});
env('bin.git', '/usr/local/git1.7/bin/git');
env('bin.composer', null); // for using local composer
```

Because in some cases, users using vagrant, they can mount software sources (like php, git, apache, ..) and build custom.

**Comment by elfet** [comment]
What about creating new mechanizm for bins? Like PATH or something?

**Comment by elfet** [comment]
`run('php ...');` Maybe some replace('php', '/...')?

**Comment by oanhnn** [comment]
What are you think a bout multi version php. Fix PATH is not good solution.

**Comment by oanhnn** [comment]
> run('php ...'); Maybe some replace('php', '/...')?
Users can custom like `env('bin.git', '/usr/local/git1.7/bin/git');`

**Comment by gperdomor** [comment]
I don't like the idea of modify the $PATH env. But i like to have a map of bin paths, with default values and configurable by server. For example, i have a <code>deploy.yml</code> file with the deploy configuration, with the map of bin executable shoul be something like this:

mmmmm having <code>env(bin.executable, path_to_executable)</code> sounds great... and can be configured by server. In my case i have a <code>deploy.yml</code> with this content:
<pre><code>timezone: America/Caracas

git:
  repository: url_to_repo.git
  branch: master

servers:
  prod:
    host: domain.com
    stage: production
    deploy_path: 'path/for/deploy'
    port: 22
    ssh_user: user
    password: password
    bin: # Alternative names: bins, exec, executables, paths?
        php: '/usr/local/bin/php'
        phpcli: '/usr/local/bin/php-cli' # For composer install (I need this), by default (if null) use the php path
        git: '/usr/local/bin/git'

  development:
    host: other_host
    stage: development
    deploy_path: 'path/for/deploy'
    port: 22
    ssh_user: user
    password: password
    bin:
        php: '/usr/bin/php'
        git: '/usr/bin/git'
        #php-cli is not configured so '/usr/bin/php' is used in composer install
</code></pre>

That file should be parsed in the <code>deploy.php</code> file

**Comment by nemoinho** [comment]
That's a great Idea to make all the executable configurable, but manipulating the $PATH only ends in rubbish and should be avoided in any way. And I would prefer the way oanhnn suggested.

**Comment by elfet** [comment]
@nemoinho take a look at #608
