### ISSUE TITLE
Output tasks durations

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#587]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

```
> done in [45s]
```

**Comment by nemoinho** [comment]
I think there is already a pull request which addresses this topic https://github.com/deployphp/deployer/pull/589 isn't it?

**Comment by elfet** [comment]
Hmmm, yes :)

**Comment by elfet** [comment]
Merged.
