### ISSUE TITLE
Task stuck in a loop ?

### ISSUE THREAD

**Issue by aschelch** [deployphp/deployer#591]
We are using a deployer task to reload our CakeResque workers using this code : 

```
task('resque', function () {
    run("cd {{deploy_path}}/web/app && ./Console/cake CakeResque.CakeResque stop -a");
    run("cd {{deploy_path}}/web/app && ./Console/cake CakeResque.CakeResque load");
})->desc('Redémarrage des workers Resque du client');
```

The first run() is ok but the second you stay stuck. Do you have any idea ? 
We tryed to spot the blocking line : https://github.com/wa0x6e/Cake-Resque/blob/master/src/Shell/CakeResqueShell.php#L765

When we execute these two lines directly on the server, it work like a charm.

Thanks in advance,

**Comment by oisvidi** [comment]
Shouldn't this be more like: 

`task('resque', function () {
    run("cd {{deploy_path}}/web/app && ./Console/cake CakeResque.CakeResque stop -a && ./Console/cake CakeResque.CakeResque load");
})->desc('Redémarrage des workers Resque du client');`

**Comment by elfet** [comment]
That is doing ./Console/cake CakeResque.CakeResque load?

**Comment by aschelch** [comment]
@oisvidi : I tried already but same issue

@elfet : When I do CTRL + C to stop the task and check, the workers started ! So I guess it do the work but do not return anyhing ? Is that make sense ?

**Comment by elfet** [comment]
try add `&`.

**Comment by oanhnn** [comment]
@aschelch In my project:
```php
/**
 * Clear cake_core_file_map in redis
 * Reload service
 */
task('deploy:end', function () {

    within('{{deploy_path}}/current', function () {
        // Stop resque workers
        run('./Console/cake CakeResque.CakeResque stop -a 1');
        $host   = env('redis.host');
        $port   = env('redis.port');
        $db     = env('redis.db');
        $prefix = env('app.prefix');
        // Clear cake_core_file_map in Redis
        run(sprintf('redis-cli -h %s -p %s -n %s --raw keys "%scake_core_file_map" | xargs redis-cli -h %s -p %s -n %s del', $host, $port, $db, $prefix, $host, $port, $db));
        // Clear app cache
        run('./Console/cake cache clear -f 1');

        // Start resque workers
        run('Console/cake CakeResque.CakeResque start -q send_email -n 5 >> /dev/null 2>&1 &');

        // Check status of serives
        sleep(5);
        run('Console/cake CakeResque.CakeResque stats');
    });
})->desc('Clear cache and restart services');
```

**Comment by elfet** [comment]
We need how-to pages.

**Comment by aschelch** [comment]
@elfet Adding `&` did not change.

@oanhnn  We added `>> /dev/null 2>&1 &` and it works ! 
I have one more question about your code. Why exactly did you delete the cake_core_file_map file ? 
I thing we may have the same issue with realpath ? 

Thanks

**Comment by oanhnn** [comment]
@aschelch In CakePHP v2.x, all paths of loaded files will saved in cache with key `<prefix>cake_core_file_map`. After your deploy, you may be need:
1. stop PHP-FPM, CakeResque, ...
2. clear cache in key `<prefix>cake_core_file_map`
3. start PHP-FPM, CakeResque, ...

If not do that, your app may be run with old code (See content of this cache key).

**Comment by oanhnn** [comment]
@aschelch I think this problem is when we run command start workers, it will fork to child progresses, and this workers will delay. If you not using background job (adding `&`) and using function `sleep()` to pause this progress, it will kill by this task finished.
:smile:

**Comment by aschelch** [comment]
@oanhnn Thanks a lot. You saved my day ;)
