### ISSUE TITLE
Failed to require deployer recipes

### ISSUE THREAD

**Issue by samuelecarpene** [deployphp/deployer#595]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.0.11 |
| Local Machine OS | Ubuntu 14.04 |
| Remote Machine OS | Ubuntu 14.04 |
### Content

Deployer fail to load recipe. Can you help me to solve?
### Steps to reproduce

1 Install deployer as described in documentation
2 create a file deploy.php
3 run "dep" command
### Content of `deploy.php`

<?php
require ('recipe/wordpress.php');
### Output log

PHP Fatal error:  require(): Failed opening required 'recipe/wordpress.php' (include_path='phar:///usr/local/bin/dep/bin/../:phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in /home/httpd/abc/www/deploy.php on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/dep:0
PHP   2. require() /usr/local/bin/dep:4
PHP   3. require() phar:///usr/local/bin/dep/bin/dep:58

**Comment by psren** [comment]
The same with composer template using the phar.

```
[Deployer\Initializer\Exception\ResourceNotFoundException]                                                                 
  Not found resource file "phar:///usr/local/bin/dep/src/Initializer/Template/../../Resources/templates/composer.php.dist".
```

**Comment by samuelecarpene** [comment]
Solved replacing require with require_once!
