### ISSUE TITLE
Automatically check for phar updates

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#596]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | v3.1.0 |
### Description

Implement checking for updates on `dep` command run. 

```
$ dep deploy
> There is a new version of Deployer: 3.0.12 (you are using 3.0.11)
```

What are you think?

**Comment by nemoinho** [comment]
Maybe the deployer should remind you to update the tool from time to time and may provide a self-update method like composer:

    $ composer update
    > Warning: This development build of composer is over 30 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.

**Comment by elfet** [comment]
Now deployer has `dep self-update`. I thinking of how to remind user to upgrade.
