### ISSUE TITLE
Is target server working directory cached?

### ISSUE THREAD

**Issue by markaduffy** [deployphp/deployer#598]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 3.0.11 |
| Local Machine OS | Ubuntu 14.04 |
| Remote Machine OS | Ubuntu 14.04 |

Whenever I deploy, for some reason its grabbing an old copy of the working directory. I tried doing a manual pull down to the target server and it works fine, but the deploy seems to be grabbing a working copy with untracked files. Is a cached copy of repo maybe stored somewhere on the target server? Ive deleted the deploy_path files multiple times, and get same result everytime.
### Content of `deploy.php`

<?php

require_once 'recipe/laravel.php';

//tasks

task('migration', function() {
  run('php {{release_path}}/artisan migrate --force');
})->desc('Artisan migrations');

task('hubot', function(){
    run('export SLACK_TOKEN= && echo "Just deployed code to example.com!" | slack-post --channel C0MXXXXX --username hubot chat.postMessage');
})->desc('Hubot told about deployment');

task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:symlink',
    'migration',
    'cleanup',
])->desc('Deploy your project');

after('deploy', 'success');

server('prod', 'xxx.xxx.xxx.xxx', 22)
    ->user('user')
    ->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
    ->stage('production')
    ->env('deploy_path', '/var/www/example.com'); // Define the base path to deploy your project to.

server('prod', 'xxx.xxx.xxx.xxx', 22)
    ->user('user')
    ->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
    ->stage('staging')
    ->env('deploy_path', '/var/www/staging.example.com'); // Define the base path to deploy your project to.

set('repository', 'git@github.com:organisation/repo.git');

**Comment by elfet** [comment]
Try to do it your self on server.

**Comment by MarnuLombard** [comment]
@elfet: please explain what you mean by "try do it yourself". Do what? 

Running into the same issue, though I suspect it's more apache/filesystem related than a deployer problem.

**Comment by elfet** [comment]
Please, provide output of `dep deply -vvv`.

**Comment by markaduffy** [comment]
I could pull the code down successfully from github on the server. No issues. Here is the verbose output. 

/home/me/dev/portal [git::master] [me@orion] [16:40]
> dep deploy prod -vvv
➤ Executing task deploy:prepare
⤷ on [prod]
Run: echo $0
> zsh
> 
Run: if [ ! -d /var/www/mysite.com ]; then mkdir -p /var/www/mysite.com; fi
Run: cd /var/www/mysite.com && if [ ! -d releases ]; then mkdir releases; fi
Run: cd /var/www/mysite.com && if [ ! -d shared ]; then mkdir shared; fi
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:release
⤷ on [prod]
Run: mkdir /var/www/mysite.com/releases/20160322204128
Run: cd /var/www/mysite.com && if [ -h release ]; then rm release; fi
Run: ln -s /var/www/mysite.com/releases/20160322204128 /var/www/mysite.com/release
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:update_code
⤷ on [prod]
Run: git version
> git version 1.9.1
> 
Run: ls /var/www/mysite.com/releases
> 20160322204128
> 
Run: readlink /var/www/mysite.com/release
> /var/www/mysite.com/releases/20160322204128
> 
Run: git clone  --depth 1 --recursive -q git@github.com:foundational-eb/portal.git /var/www/mysite.com/releases/20160322204128 2>&1
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:shared
⤷ on [prod]
Run: if [ -d $(echo /var/www/mysite.com/releases/20160322204128/storage/app) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/storage/app; fi
Run: mkdir -p /var/www/mysite.com/shared/storage/app
Run: mkdir -p `dirname /var/www/mysite.com/releases/20160322204128/storage/app`
Run: ln -nfs /var/www/mysite.com/shared/storage/app /var/www/mysite.com/releases/20160322204128/storage/app
Run: if [ -d $(echo /var/www/mysite.com/releases/20160322204128/storage/framework/cache) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/storage/framework/cache; fi
Run: mkdir -p /var/www/mysite.com/shared/storage/framework/cache
Run: mkdir -p `dirname /var/www/mysite.com/releases/20160322204128/storage/framework/cache`
Run: ln -nfs /var/www/mysite.com/shared/storage/framework/cache /var/www/mysite.com/releases/20160322204128/storage/framework/cache
Run: if [ -d $(echo /var/www/mysite.com/releases/20160322204128/storage/framework/sessions) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/storage/framework/sessions; fi
Run: mkdir -p /var/www/mysite.com/shared/storage/framework/sessions
Run: mkdir -p `dirname /var/www/mysite.com/releases/20160322204128/storage/framework/sessions`
Run: ln -nfs /var/www/mysite.com/shared/storage/framework/sessions /var/www/mysite.com/releases/20160322204128/storage/framework/sessions
Run: if [ -d $(echo /var/www/mysite.com/releases/20160322204128/storage/framework/views) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/storage/framework/views; fi
Run: mkdir -p /var/www/mysite.com/shared/storage/framework/views
Run: mkdir -p `dirname /var/www/mysite.com/releases/20160322204128/storage/framework/views`
Run: ln -nfs /var/www/mysite.com/shared/storage/framework/views /var/www/mysite.com/releases/20160322204128/storage/framework/views
Run: if [ -d $(echo /var/www/mysite.com/releases/20160322204128/storage/logs) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/storage/logs; fi
Run: mkdir -p /var/www/mysite.com/shared/storage/logs
Run: mkdir -p `dirname /var/www/mysite.com/releases/20160322204128/storage/logs`
Run: ln -nfs /var/www/mysite.com/shared/storage/logs /var/www/mysite.com/releases/20160322204128/storage/logs
Run: if [ -f $(echo /var/www/mysite.com/releases/20160322204128/.env) ]; then rm -rf /var/www/mysite.com/releases/20160322204128/.env; fi
Run: if [ ! -d $(echo /var/www/mysite.com/releases/20160322204128/.) ]; then mkdir -p /var/www/mysite.com/releases/20160322204128/.;fi
Run: mkdir -p /var/www/mysite.com/shared/.
Run: touch /var/www/mysite.com/shared/.env
Run: ln -nfs /var/www/mysite.com/shared/.env /var/www/mysite.com/releases/20160322204128/.env
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:writable
⤷ on [prod]
Run: ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
> www-data
> 
Run: cd /var/www/mysite.com/releases/20160322204128 && chmod 2>&1; true
> chmod: missing operand
> Try 'chmod --help' for more information.
> 
Run: cd /var/www/mysite.com/releases/20160322204128 && if hash setfacl 2>/dev/null; then echo 'true'; fi
Run: cd /var/www/mysite.com/releases/20160322204128 && sudo chmod 777 -R bootstrap/cache storage
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:vendors
⤷ on [prod]
Run: if hash composer 2>/dev/null; then echo 'true'; fi
> true
> 
Run: cd /var/www/mysite.com/releases/20160322204128 &&  composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
> Loading composer repositories with package information
> Installing dependencies from lock file
> Analyzed 101 packages to resolve dependencies
> Analyzed 188 rules to resolve dependencies
>   - Installing symfony/finder (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-mbstring (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/var-dumper (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psr/log (1.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing maximebf/debugbar (v1.11.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing vlucas/phpdotenv (v2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/translation (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/routing (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/process (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-util (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-php56 (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/http-foundation (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/event-dispatcher (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/debug (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/http-kernel (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/console (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing swiftmailer/swiftmailer (v5.4.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing nikic/php-parser (v2.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jakub-onderka/php-console-color (0.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jakub-onderka/php-console-highlighter (v0.3.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing dnoegel/php-xdg-base-dir (0.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psy/psysh (v0.6.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing paragonie/random_compat (1.1.6)
>     Loading from cache
>     Extracting archive
> 
>   - Installing nesbot/carbon (1.21.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing mtdowling/cron-expression (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing monolog/monolog (1.17.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing league/flysystem (1.0.16)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jeremeamia/superclosure (2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing doctrine/inflector (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing classpreloader/classpreloader (3.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing laravel/framework (v5.2.14)
>     Loading from cache
>     Extracting archive
> 
>   - Installing barryvdh/laravel-debugbar (v2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psr/http-message (1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/psr7 (1.2.3)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/promises (1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/guzzle (6.1.1)
>     Loading from cache
>     Extracting archive
> 
> Generating optimized autoload files
> > post-install-cmd: php artisan clear-compiled
> > post-install-cmd: php artisan optimize
> Generating optimized class loader
> 
⤶ done on [prod]
✔ Ok
➤ Executing task deploy:symlink
⤷ on [prod]
Run: cd /var/www/mysite.com && ln -sfn /var/www/mysite.com/releases/20160322204128 current
Run: cd /var/www/mysite.com && rm release
⤶ done on [prod]
✔ Ok
➤ Executing task migration
⤷ on [prod]
Run: php /var/www/mysite.com/releases/20160322204128/artisan migrate --force
> Nothing to migrate.
> 
⤶ done on [prod]
✔ Ok
➤ Executing task cleanup
⤷ on [prod]
Run: cd /var/www/mysite.com && if [ -e release ]; then rm release; fi
Run: cd /var/www/mysite.com && if [ -h release ]; then rm release; fi
⤶ done on [prod]
✔ Ok
➤ Executing task success
Successfully deployed!
✔ Ok

**Comment by elfet** [comment]
What happens if you try to do it your self:
```
git clone --depth 1 --recursive -q git@github.com:foundational-eb/portal.git /var/www/mysite.com/releases/20160322204128
```

**Comment by markaduffy** [comment]
it looks fine. "nothing to commit, working directory clean"

**Comment by elfet** [comment]
Try to add into `deploy.php` next line:
```php
env('git_cache', false);
```

**Comment by markaduffy** [comment]
DIdnt help.

home/me/dev/portal [git::master] [me@orion] [9:40]
> dep deploy staging -vvv
➤ Executing task deploy:prepare
⤷ on [staging]
Run: echo $0
> zsh
> 
Run: if [ ! -d /var/www/staging.mysite.com ]; then mkdir -p /var/www/staging.mysite.com; fi
Run: cd /var/www/staging.mysite.com && if [ ! -d releases ]; then mkdir releases; fi
Run: cd /var/www/staging.mysite.com && if [ ! -d shared ]; then mkdir shared; fi
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:release
⤷ on [staging]
Run: mkdir /var/www/staging.mysite.com/releases/20160323134106
Run: cd /var/www/staging.mysite.com && if [ -h release ]; then rm release; fi
Run: ln -s /var/www/staging.mysite.com/releases/20160323134106 /var/www/staging.mysite.com/release
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:update_code
⤷ on [staging]
Run: ls /var/www/staging.mysite.com/releases
> 20160323134106
> 
Run: readlink /var/www/staging.mysite.com/release
> /var/www/staging.mysite.com/releases/20160323134106
> 
Run: git clone  --depth 1 --recursive -q git@github.com:site-eb/portal.git /var/www/staging.mysite.com/releases/20160323134106 2>&1
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:shared
⤷ on [staging]
Run: if [ -d $(echo /var/www/staging.mysite.com/releases/20160323134106/storage/app) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/storage/app; fi
Run: mkdir -p /var/www/staging.mysite.com/shared/storage/app
Run: mkdir -p `dirname /var/www/staging.mysite.com/releases/20160323134106/storage/app`
Run: ln -nfs /var/www/staging.mysite.com/shared/storage/app /var/www/staging.mysite.com/releases/20160323134106/storage/app
Run: if [ -d $(echo /var/www/staging.mysite.com/releases/20160323134106/storage/framework/cache) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/storage/framework/cache; fi
Run: mkdir -p /var/www/staging.mysite.com/shared/storage/framework/cache
Run: mkdir -p `dirname /var/www/staging.mysite.com/releases/20160323134106/storage/framework/cache`
Run: ln -nfs /var/www/staging.mysite.com/shared/storage/framework/cache /var/www/staging.mysite.com/releases/20160323134106/storage/framework/cache
Run: if [ -d $(echo /var/www/staging.mysite.com/releases/20160323134106/storage/framework/sessions) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/storage/framework/sessions; fi
Run: mkdir -p /var/www/staging.mysite.com/shared/storage/framework/sessions
Run: mkdir -p `dirname /var/www/staging.mysite.com/releases/20160323134106/storage/framework/sessions`
Run: ln -nfs /var/www/staging.mysite.com/shared/storage/framework/sessions /var/www/staging.mysite.com/releases/20160323134106/storage/framework/sessions
Run: if [ -d $(echo /var/www/staging.mysite.com/releases/20160323134106/storage/framework/views) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/storage/framework/views; fi
Run: mkdir -p /var/www/staging.mysite.com/shared/storage/framework/views
Run: mkdir -p `dirname /var/www/staging.mysite.com/releases/20160323134106/storage/framework/views`
Run: ln -nfs /var/www/staging.mysite.com/shared/storage/framework/views /var/www/staging.mysite.com/releases/20160323134106/storage/framework/views
Run: if [ -d $(echo /var/www/staging.mysite.com/releases/20160323134106/storage/logs) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/storage/logs; fi
Run: mkdir -p /var/www/staging.mysite.com/shared/storage/logs
Run: mkdir -p `dirname /var/www/staging.mysite.com/releases/20160323134106/storage/logs`
Run: ln -nfs /var/www/staging.mysite.com/shared/storage/logs /var/www/staging.mysite.com/releases/20160323134106/storage/logs
Run: if [ -f $(echo /var/www/staging.mysite.com/releases/20160323134106/.env) ]; then rm -rf /var/www/staging.mysite.com/releases/20160323134106/.env; fi
Run: if [ ! -d $(echo /var/www/staging.mysite.com/releases/20160323134106/.) ]; then mkdir -p /var/www/staging.mysite.com/releases/20160323134106/.;fi
Run: mkdir -p /var/www/staging.mysite.com/shared/.
Run: touch /var/www/staging.mysite.com/shared/.env
Run: ln -nfs /var/www/staging.mysite.com/shared/.env /var/www/staging.mysite.com/releases/20160323134106/.env
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:writable
⤷ on [staging]
Run: ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
> www-data
> 
Run: cd /var/www/staging.mysite.com/releases/20160323134106 && chmod 2>&1; true
> chmod: missing operand
> Try 'chmod --help' for more information.
> 
Run: cd /var/www/staging.mysite.com/releases/20160323134106 && if hash setfacl 2>/dev/null; then echo 'true'; fi
Run: cd /var/www/staging.mysite.com/releases/20160323134106 && sudo chmod 777 -R bootstrap/cache storage
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:vendors
⤷ on [staging]
Run: if hash composer 2>/dev/null; then echo 'true'; fi
> true
> 
Run: cd /var/www/staging.mysite.com/releases/20160323134106 &&  composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
> Loading composer repositories with package information
> Installing dependencies from lock file
> Analyzed 101 packages to resolve dependencies
> Analyzed 188 rules to resolve dependencies
>   - Installing symfony/finder (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-mbstring (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/var-dumper (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psr/log (1.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing maximebf/debugbar (v1.11.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing vlucas/phpdotenv (v2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/translation (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/routing (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/process (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-util (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/polyfill-php56 (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/http-foundation (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/event-dispatcher (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/debug (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/http-kernel (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing symfony/console (v3.0.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing swiftmailer/swiftmailer (v5.4.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing nikic/php-parser (v2.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jakub-onderka/php-console-color (0.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jakub-onderka/php-console-highlighter (v0.3.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing dnoegel/php-xdg-base-dir (0.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psy/psysh (v0.6.1)
>     Loading from cache
>     Extracting archive
> 
>   - Installing paragonie/random_compat (1.1.6)
>     Loading from cache
>     Extracting archive
> 
>   - Installing nesbot/carbon (1.21.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing mtdowling/cron-expression (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing monolog/monolog (1.17.2)
>     Loading from cache
>     Extracting archive
> 
>   - Installing league/flysystem (1.0.16)
>     Loading from cache
>     Extracting archive
> 
>   - Installing jeremeamia/superclosure (2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing doctrine/inflector (v1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing classpreloader/classpreloader (3.0.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing laravel/framework (v5.2.14)
>     Loading from cache
>     Extracting archive
> 
>   - Installing barryvdh/laravel-debugbar (v2.2.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing psr/http-message (1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/psr7 (1.2.3)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/promises (1.1.0)
>     Loading from cache
>     Extracting archive
> 
>   - Installing guzzlehttp/guzzle (6.1.1)
>     Loading from cache
>     Extracting archive
> 
> Generating optimized autoload files
> > post-install-cmd: php artisan clear-compiled
> > post-install-cmd: php artisan optimize
> Generating optimized class loader
> 
⤶ done on [staging]
✔ Ok
➤ Executing task deploy:symlink
⤷ on [staging]
Run: cd /var/www/staging.mysite.com && ln -sfn /var/www/staging.mysite.com/releases/20160323134106 current
Run: cd /var/www/staging.mysite.com && rm release
⤶ done on [staging]
✔ Ok
➤ Executing task migration
⤷ on [staging]
Run: php /var/www/staging.mysite.com/releases/20160323134106/artisan migrate --force
> Nothing to migrate.
> 
⤶ done on [staging]
✔ Ok
➤ Executing task cleanup
⤷ on [staging]
Run: cd /var/www/staging.mysite.com && if [ -e release ]; then rm release; fi
Run: cd /var/www/staging.mysite.com && if [ -h release ]; then rm release; fi
⤶ done on [staging]
✔ Ok
➤ Executing task success
Successfully deployed!
✔ Ok

Still get following in /current/ 
Storage is in shared folder.

deleted:    storage/app/.gitignore
modified:   storage/debugbar/.gitignore
deleted:    storage/framework/cache/.gitignore
deleted:    storage/framework/sessions/.gitignore
deleted:    storage/framework/views/.gitignore
deleted:    storage/logs/.gitignore
Untracked files:
(use "git add ..." to include in what will be committed)

storage/app
storage/framework/cache
storage/framework/sessions
storage/framework/views
storage/logs
