### ISSUE TITLE
How do i deploy to server through another ssh server

### ISSUE THREAD

**Issue by chouex** [deployphp/deployer#601]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | OSX
| Remote Machine OS | Linux

### Description 
How do i deploy to server behind another server using ssh?

workstation->proxy(ssh)->target

**Comment by elfet** [comment]
You can login via ssh to proxy and run `dep deploy` there.

**Comment by jelte** [comment]
A simply way is to configure an alias in your `~/.ssh/config` file

```
Host <your_tunnel_name>
    HostName <hostname_of_target>
    ProxyCommand ssh <username_of_proxy>@<hostname_of_proxy> nc %h %p 2> /dev/null
    User <username_of_target>
```
than you'll be able to simply connect through
```
# ssh <your_tunnel_name>
```

Simple solution to tunneling, without needed "deployer".
also makes your life easier to connect to your production server :)

**Comment by chouex** [comment]
ssh tunneling seems to be the better solution while deployer not support tunneling yet.

**Comment by ryancastle** [comment]
This is working for me, after much failed experimentation with remote port forwarding.

`ssh -A -t deployment-proxy ssh -A -t deployment-target php deployer.phar deploy local`
