### ISSUE TITLE
Check that branch is clean, pushed, and what you expected before deploying

### ISSUE THREAD

**Issue by travisdoherty** [deployphp/deployer#602]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
My Deployer process is generally:
- checkout master
- merge in from development
- push
- run `vendor/bin/deploy`.

Sometimes I forget to push. Then I wait for the entire deploy process before I realize my branch is still dirty.

So I use a task like this to help me out:

```
/**
 * Start by checking that the current git branch is:
 * - master
 * - fully pushed
 */
task('deploy:checkgit', function() {
    if (trim($branch = `git rev-parse --abbrev-ref HEAD`) !== 'master') {
        writeln("<error>You should release from master, not $branch.</error>");
        exit(1);
    }

    // check that there are no modified files
    exec("git diff-index --quiet HEAD", $output, $exitCode);
    if ($exitCode) {
        writeln("<error>Branch is not clean, not starting a deploy process.</error>");
        exit(1);
    }

    // update remotes and check git status
    `git remote update`;
    $local = trim(`git rev-parse @`);
    $remote = trim(`git rev-parse @{u}`);

    if ($local !== $remote) {
        writeln("<error>Your `master` is not equal to `origin/master`, you should push first.</error>");
        exit(1);
    }

})->once()->desc('Check that git is clean.');
```

Would this be a useful feature to continue for anyone else?

**Comment by oanhnn** [comment]
This is a useful feature, but not it need be flexible. Eg:
- If deployment script and source code are different repos.
- Deploy from other machine, that is different with develop machine.

I think it better if you write a tutorial post on http://deployer.org .
What are you thing? @travisdoherty @elfet

**Comment by elfet** [comment]
There are a lot of different work flow. Co i think this must not go into common.php recipe. 
Best solution is to write article about how to get task like this. 
Here new repo for stuff like this: https://github.com/deployphp/how-to

**Comment by travisdoherty** [comment]
Thanks for the feedback! I'll stick this into the how-to repo.
