### ISSUE TITLE
Can't deploy from bitbucket

### ISSUE THREAD

**Issue by mehrdaad** [deployphp/deployer#603]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

I've setup my project in bitucket.  
I've also setup my computer ssh key and remote server ssh key in the bitbucket repo.  
I can also clone my repo in from remote server.  
### Output log

But when I run `dep deploy` I get error: 
`
  [RuntimeException]
  Host key verification failed.
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.
`
verbose output also is: 

```
➤ Executing task deploy:prepare
↳ on [production]
• done on [production]
✔ Ok [4s 651ms]
➤ Executing task deploy:release
↳ on [production]
• done on [production]
✔ Ok [1s 914ms]
➤ Executing task deploy:update_code
↳ on [production]


  [RuntimeException]
  Host key verification failed.
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.


Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at /home/vagrant/app/deploy/common.php:177
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:64
 require() at /usr/local/bin/dep:4

deploy [-p|--parallel]
```
### Content of `deploy.php`

I don't figure out what is the problem. My server configuration is: 

```
set('repository', 'git@bitbucket.org:username/projetct.git');
set('keep_releases', 3);
// Configure servers
server('production', 'x.x.x.x')
    ->user('root')
    ->password("password")
    ->env('deploy_path', '/var/www/temp');
```

I have required `laravel.php` from `deploy.php`  
and required `common.php` from `laravel.php`.
I've also removed some `set` commands like `shared_dir` in `common.php` because it was changed in `laravel.php`

Description went too long. sorry about that.

**Comment by oanhnn** [comment]
Please show your output with debug mode (add option `-vvv` when run deployer).
And i think you try:
```
$ ssh root@x.x.x.x 'git clone git@bitbucket.org:username/projetct.git /tmp/project'
```

**Comment by mehrdaad** [comment]
```
➤ Executing task deploy:prepare
↳ on [production]
> echo $0
< bash
<
> if [ ! -d /var/www/temp ]; then mkdir -p /var/www/temp; fi
> cd /var/www/temp && if [ ! -d releases ]; then mkdir releases; fi
> cd /var/www/temp && if [ ! -d shared ]; then mkdir shared; fi
• done on [production]
✔ Ok [4s 590ms]
➤ Executing task deploy:release
↳ on [production]
> mkdir /var/www/temp/releases/20160326101711
> cd /var/www/temp && if [ -h release ]; then rm release; fi
> ln -s /var/www/temp/releases/20160326101711 /var/www/temp/release
• done on [production]
✔ Ok [1s 864ms]
➤ Executing task deploy:update_code
↳ on [production]
> git version
< git version 1.9.1
<
> find /var/www/temp/releases -maxdepth 1 -mindepth 1 -type d
< /var/www/temp/releases/20160325200044
< /var/www/temp/releases/20160326101711
< /var/www/temp/releases/20160325200028
<
> readlink /var/www/temp/release
< /var/www/temp/releases/20160326101711
<
> git clone -b master --depth 1 --recursive -q git@bitbucket.org:mehrdaad/ashojash_web.git /var/www/temp/releases/20160326101711 2>&1


  [RuntimeException]
  Host key verification failed.
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.


Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at /home/vagrant/ashojash/deploy/common.php:177
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:64
 require() at /usr/local/bin/dep:4

deploy [-p|--parallel]
```

**Comment by oanhnn** [comment]
> I can clone my project manually in remote server via git clone

Your problem is ssh by password and git clone by key. When you ssh by deployer, your ssh agent may be not start and add your key. So that, i want you run below command:
```
$ ssh root@x.x.x.x 'git clone git@bitbucket.org:username/projetct.git /tmp/project'
```

**Comment by oanhnn** [comment]
Other option, you can switch to using private-public key or foward agent to ssh by deployer.

**Comment by mehrdaad** [comment]
@oanhnn do want me to run 
``` $ ssh root@x.x.x.x 'git clone git@bitbucket.org:username/projetct.git /tmp/project'```
on my remote server?
I've run that on the remote server and cloned the project.

> 

Other option, you can switch to using private-public key or foward agent to ssh by deployer.

Don't know so much about deployer. I would really appreciate if you could show me how to do that. Tnx

**Comment by mehrdaad** [comment]
>Your problem is ssh by password and git clone by key
@oanhnn when using deployer, directories are created so I conclude that ssh password for remote server is correct. 
But I don't know how to configure git clone key on my remote server or on deployer. Would you give a hint about it.Tnx

**Comment by oanhnn** [comment]
@mehrdaad Please run on your local machine (where you run deployer on).
Deployer document available on https://deployer.org

**Comment by mehrdaad** [comment]
@oanhnn I run ``dep deploy`` on vagrant. I'm also Bitbucket user.
I can run ```$ ssh root@x.x.x.x 'git clone git@bitbucket.org:username/projetct.git /tmp/project'```
on vagrant machine it clones the project and doesn't ask me any password. 
I've also added 3 deploy key to bitbucket : my remote server, my host machine, and my vagrant machine key.  
But again I get the same issue.
What should I do now?

**Comment by oanhnn** [comment]
@mehrdaad Are you using?

|Q|A|
|---|---|
|Local OS| Ubuntu OS 14.04 (Homestead)|
|Remote OS| Ubuntu OS 14.04|

**Comment by mehrdaad** [comment]
@oanhnn yeah that's right.

**Comment by mehrdaad** [comment]
@oanhnn you didn't provide any example? do you plan to?

**Comment by oanhnn** [comment]
@mehrdaad 
Please read https://github.com/oanhnn/deployer-example/blob/master/docs/run-deployer-on-homestead.md and star if it is useful

**Comment by oanhnn** [comment]
@elfet I want add this document to https://github.com/deployphp/how-to but i don't know construct of this repo. Please create first commit. :smile:

**Comment by elfet** [comment]
Okay, will create it today

**Comment by pabloworks** [comment]
I have this error:

[RuntimeException]
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.

Deploy stops in: Executing task deploy:update_code
Log:
/usr/bin/git clone -b homolog --depth 1 --recursive -q git@bitbucket.org:pabloworks/leilaobrasil.git /att/www/homolog/leilaobrasil/releases/20161116165527 2>&1

Any idea?

**Comment by oanhnn** [comment]
@pabloworks 
Can you show more info like template https://raw.githubusercontent.com/deployphp/deployer/master/.github/ISSUE_TEMPLATE.md
