### ISSUE TITLE
ability to change GIT executable path

### ISSUE THREAD

**Issue by mikk150** [deployphp/deployer#607]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

It would be nice if we could change GIT executable path OR modify $PATH variable (latter would be even better)

**Comment by oanhnn** [comment]
Please follow and discuss in #586

**Comment by oanhnn** [comment]
This will implement in v4.x.
