### ISSUE TITLE
Fork phar update lib

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#609]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
We need to fork https://github.com/kherge-abandoned/php-phar-update and related projects into deployer org. This projects does not supported any more. But we need to add support for Symfony 3.0 there.

Can any body take this?

**Comment by elfet** [comment]
@oanhnn what do you think?

**Comment by oanhnn** [comment]
:+1:  I am agree.

**Comment by oanhnn** [comment]
@elfet Is this feature implemented by commit 5fa083c072254784c8472d2e89603419102d665f ?

**Comment by elfet** [comment]
Yes :+1:
