### ISSUE TITLE
Composer install after post deploy

### ISSUE THREAD

**Issue by mehrdaad** [deployphp/deployer#610]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | 3
| Local Machine OS  | Vagrant homesatead
| Remote Machine OS | Ubuntu

Sorry but I'm going to ask 3 question in my issue,
First @elfet why did you change ``php`` to ``bin/php``? I was getting error running ``dep deploy`` on my homestead machine so I was made to change it again to ``php`` to get it working, any reason for ``bin/php``?

Second after repo clones to server, command ``/usr/local/bin/composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction`` which generates error: I put the log trace in verbose mode here:  

```
     [RuntimeException]
     Loading composer repositories with package information
     Installing dependencies from lock file
     Analyzed 121 packages to resolve dependencies
     Analyzed 259 rules to resolve dependencies
     - Installing artisaninweb/laravel-soap (0.2.5.10)
      Loading from cache
      Extracting archive
    - Installing caouecs/laravel4-lang (2.0.36)
      Loading from cache
      Extracting archive
    - Installing nikic/php-parser (v2.0.1)
      Loading from cache
      Extracting archive
      ...
      ...
      Generating optimized autoload files
       > post-install-cmd: php artisan clear-compiled
       Script php artisan clear-compiled handling the post-install-cmd event returned with an error

        [RuntimeException]
        Error Output:

         Exception trace:
          () at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:204
           Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/C
       omposer/EventDispatcher/EventDispatcher.php:94
       Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/s
  rc/Composer/Installer.php:332
       Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallComman
  d.php:134
        Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/co
  nsole/Command/Command.php:259
        Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symf
  ony/console/Application.php:844
        Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor
  /symfony/console/Application.php:192
   Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/
  Console/Application.php:166
   Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console
  /Application.php:123
   Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Co
  nsole/Application.php:99
   Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
   require() at /usr/local/bin/composer:25
  install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-c
  ustom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--
  optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]..
  .
```

Second question is about ``composer install`` command I don't know why I get error there?  
Third question: directory ``bootstrap/cache/`` is in my .gitignore file (I use laravel), when command 
```php artisan clear-compiled`` generates error. How you handle this error?
Tnx

**Comment by mehrdaad** [comment]
Don't know why knowbody has asked before my First and Second question, 
But I was able to solve seond question by adding:
```
run("cd {{release_path}}/bootstrap && mkdir cache");
```
in ``task('deploy:vendors',function(){});``

**Comment by mehrdaad** [comment]
@mehrdaad  I was getting num 2 and 3 error because I had included ``bootstrap/cache`` in my ``.gitignore`` file

**Comment by oanhnn** [comment]
@mehrdaad 
1. We change php to `{{bin/php}}` to allow custom path to php bin file. It is useful for someone.
2. Error is of `post-install-cmd`. You can ignore `post-install-cmd` by `composer.json` file or set environment variable `composer_options` (add option `--no-scripts`)
   ```php
   env('composer_options', 'install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction --no-scripts');
   ```
3. You should remove `/bootstrap/cache/` in `/.gitignore` file (in root directory of project). And add a `/bootstrap/cache/.gitignore` file with content:
   ```
   # /bootstrap/cache/.gitignore
   *
   !.gitignore
   ```

**Comment by oanhnn** [comment]
Please close this issue if no more question.
