### ISSUE TITLE
[Composer][Packagist] Composer packages aren't in sync

### ISSUE THREAD

**Issue by gperdomor** [deployphp/deployer#611]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Composer packages aren't in sync

**Comment by oanhnn** [comment]
@gperdomor Please show more information for reproduce bug.

**Comment by gperdomor** [comment]
@oanhnn  I'm using the version "4.x-dev", but running <code>composer update</code> i don't get the last version from repository, i need the changes introduced in #608...

**Comment by oanhnn** [comment]
@elfet Can your check synchronization in packgist site and follow this issue.

**Comment by elfet** [comment]
Will look at this.

**Comment by gperdomor** [comment]
Any progress here?

**Comment by elfet** [comment]
Updated, try now.

**Comment by gperdomor** [comment]
@elfet solved... Thank you :D
