### ISSUE TITLE
[Feature] Add writable users

### ISSUE THREAD

**Issue by gperdomor** [deployphp/deployer#612]
| Q | A |
| --- | --- |
| Issue Type | Feature |
| Deployer Version | 4 |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Please, add an option to set which users have write permissions in the <code>writable_dirs</code>.

Use case:
    - The web server user is 'UserA'
    - You deploy using 'userB' because is the only user with permissions to connect over ssh.
    - You have an FTP user 'UserC'.

With the current option, you can't set permission for UserC.

This options should be per server, so every server can use different users.

I also notice that deployer use:
<code>ps **aux** | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1</code>

And Symfony Docs use <code>ps **axo user,comm** | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1</code>

In my case, the first command (the deployer one) determine an incorrect user...

**Comment by oanhnn** [comment]
I think your case, you should custom task `deploy:writable` by yourself.
Default task of Deployer only cover common cases

**Comment by elfet** [comment]
Yes, this command was copied from symphony docs, if they updated it, so can we.

**Comment by gperdomor** [comment]
I will make a PR tonight to fix the command and other to introduce the writable users. I not agree whit @oanhnn, other deploy tool, like capistrano fore example use this feature. WDYT?

**Comment by oanhnn** [comment]
I think your pull request is good. But it only resolved a case. I don't want common tasks more complex.
We're thinking about solution using group for set writable permissions in version 4.x. It is better.

**Comment by elfet** [comment]
Done in v4.
