### ISSUE TITLE
Composer.phar problem with deployer common.php 3.2

### ISSUE THREAD

**Issue by arvatis** [deployphp/deployer#615]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.2
| Local Machine OS  | OSX
| Remote Machine OS | Linux

### Description 
When using deployer 3.2 the usage of composer.phar can be corrupt.

Would be necessary to add an {{release_path}}/composer.phar.
So it would look like this:
```
env('bin/composer', function () {
    if (commandExist('composer')) {
        $composer = run('which composer')->toString();
    }

    if (empty($composer)) {
        run("cd {{release_path}} && curl -sS https://getcomposer.org/installer | php");
        $composer = '{{bin/php}} {{release_path}}/composer.phar';
    }

    return $composer;
});
```

**Comment by elfet** [comment]
True. Can you make PR?

**Comment by arvatis** [comment]
Fixed: https://github.com/deployphp/deployer/pull/616

**Comment by arvatis** [comment]
Can you please add a v3.2.1 version ?
