### ISSUE TITLE
ability change $PATH variable

### ISSUE THREAD

**Issue by mikk150** [deployphp/deployer#618]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

ability change $PATH variable per server (#608 won't fix this issue) because we need to execute commands that execute other commands that are not in $PATH for some bizarre reason

**Comment by elfet** [comment]
Can you show an example?

**Comment by mikk150** [comment]
on deployer, 
$PATH = /usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/local/rvm/bin

on ssh
$PATH = /usr/local/rvm/gems/ruby-2.1.2@global/bin:/usr/local/rvm/rubies/ruby-2.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/pgsql/bin:/usr/local/mysql/bin:/usr/local/nodejs/bin:/usr/local/rvm/bin:/home/<classified>/bin

for some reason there is more directories in PATH when connecting via SSH and we need some directories to be in path when deploying(for compiling JS and CSS)
deployer own env() doesn't cut it, because you cannot inject it inside code(and even then it doesn't work, because we need ruby, and ruby needs it's binary path to be in $PATH)

**Comment by elfet** [comment]
What's why:
![](http://capistranorb.com/images/BashStartupFiles1.png)

**Comment by elfet** [comment]
So you need ruby only on one command? `export PATH=$PATH:/usr/local/foo && ?`

**Comment by mikk150** [comment]
yes, I did it
```php
 run('PATH={{path}} php5 {{release_path}}/yii asset ');
```

and on server
```php
->env('path', '$PATH:/usr/local/rvm/gems/ruby-2.1.2@global/bin:/usr/local/rvm/rubies/ruby-2.1.2/bin')
```

but it's quite cumblesome

**Comment by elfet** [comment]
What is your solution?

**Comment by RuslanZavacky** [comment]
@elfet @mikk150 is there a solution to make .bashrc to be executed? Doesn't seem that there is a solution.. and I am quite stuck with with mking node/npm work :(
