### ISSUE TITLE
Could not open input file: Error

### ISSUE THREAD

**Issue by bdensmore** [deployphp/deployer#620]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.2.1
| Local Machine OS  | Ubuntu 14.04
| Remote Machine OS | Ubuntu 14.04

### Description 
When trying to deploy, I'm getting the following error:

[RuntimeException]
  Could not open input file: /var/www/motivis-assets/releases/20160411210247/app/console

### Steps to reproduce

dep deploy production

### Content of `deploy.php`
```php
// All Deployer recipes are based on `recipe/common.php`.
require 'recipe/symfony.php';

// Define a server for deployment.
// Let's name it "prod" and use port 22.
server('ec2', '127.0.0.1')
    ->user('my_user')
    ->pemFile('cert.pem')
//     ->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
    ->stage('production')
    ->env('deploy_path', '/var/www/motivis-assets'); // Define the base path to deploy your project to.

// Specify the repository from which to download your project's code.
// The server needs to have git installed for this to work.
// If you're not using a forward agent, then the server has to be able to clone
// your project from this repository.
set('repository', 'git@github.com:myrepo/sass-automation.git');

// set('bin_dir', 'bin');

set('writable_dirs', ['build', 'stylesheets', 'app/cache', 'app/logs']);
// set('keep_releases', 5);

task('reload:php-fpm', function () {
    run('sudo /usr/sbin/service php5-fpm reload');
});

after('deploy', 'reload:php-fpm');
after('rollback', 'reload:php-fpm');
```

### Output log
➤ Executing task deploy:prepare
↳ on [ec2]
> echo $0
< bash
<
> if [ ! -d /var/www/motivis-assets ]; then mkdir -p /var/www/motivis-assets; fi
> if [ ! -L /var/www/motivis-assets/current ] && [ -d /var/www/motivis-assets/current ]; then echo true; fi
> cd /var/www/motivis-assets && if [ ! -d releases ]; then mkdir releases; fi
> cd /var/www/motivis-assets && if [ ! -d shared ]; then mkdir shared; fi
• done on [ec2]
✔ Ok [636ms]
➤ Executing task deploy:release
↳ on [ec2]
> mkdir /var/www/motivis-assets/releases/20160411210247
> cd /var/www/motivis-assets && if [ -h release ]; then rm release; fi
> ln -s /var/www/motivis-assets/releases/20160411210247 /var/www/motivis-assets/release
• done on [ec2]
✔ Ok [132ms]
➤ Executing task deploy:update_code
↳ on [ec2]
> which git
< /usr/bin/git
<
> git version
< git version 1.9.1
<
> find /var/www/motivis-assets/releases -maxdepth 1 -mindepth 1 -type d
< /var/www/motivis-assets/releases/20160411150157
< /var/www/motivis-assets/releases/20160411153740
< /var/www/motivis-assets/releases/20160411145817
< /var/www/motivis-assets/releases/20160411152923
< /var/www/motivis-assets/releases/20160411195709
< /var/www/motivis-assets/releases/20160411210247
< /var/www/motivis-assets/releases/20160411202618
< /var/www/motivis-assets/releases/20160411152641
< /var/www/motivis-assets/releases/20160411152530
< /var/www/motivis-assets/releases/20160411182134
< /var/www/motivis-assets/releases/20160411151155
< /var/www/motivis-assets/releases/20160411204455
< /var/www/motivis-assets/releases/20160411150353
< /var/www/motivis-assets/releases/20160411204639
< /var/www/motivis-assets/releases/20160411182630
< /var/www/motivis-assets/releases/20160411145847
< /var/www/motivis-assets/releases/20160411150044
<
> readlink /var/www/motivis-assets/release
< /var/www/motivis-assets/releases/20160411210247
<
> /usr/bin/git clone  --depth 1 --recursive -q git@github.com:motivislearning/sass-automation.git /var/www/motivis-assets/releases/20160411210247 2>&1
• done on [ec2]
✔ Ok [457ms]
➤ Executing task deploy:clear_controllers
↳ on [ec2]
> rm -f /var/www/motivis-assets/releases/20160411210247/web/app_*.php
> rm -f /var/www/motivis-assets/releases/20160411210247/web/config.php
• done on [ec2]
Ok [91ms]
➤ Executing task deploy:create_cache_dir
↳ on [ec2]
> if [ -d "/var/www/motivis-assets/releases/20160411210247/app/cache" ]; then rm -rf /var/www/motivis-assets/releases/20160411210247/app/cache; fi
> mkdir -p /var/www/motivis-assets/releases/20160411210247/app/cache
> chmod -R g+w /var/www/motivis-assets/releases/20160411210247/app/cache
• done on [ec2]
✔ Ok [184ms]
➤ Executing task deploy:shared
↳ on [ec2]
> if [ -d $(echo /var/www/motivis-assets/releases/20160411210247/app/logs) ]; then rm -rf /var/www/motivis-assets/releases/20160411210247/app/logs; fi
> mkdir -p /var/www/motivis-assets/shared/app/logs
> mkdir -p `dirname /var/www/motivis-assets/releases/20160411210247/app/logs`
> ln -nfs /var/www/motivis-assets/shared/app/logs /var/www/motivis-assets/releases/20160411210247/app/logs
> if [ -f $(echo /var/www/motivis-assets/releases/20160411210247/app/config/parameters.yml) ]; then rm -rf /var/www/motivis-assets/releases/20160411210247/app/config/parameters.yml;
 fi
> if [ ! -d $(echo /var/www/motivis-assets/releases/20160411210247/app/config) ]; then mkdir -p /var/www/motivis-assets/releases/20160411210247/app/config;fi
> mkdir -p /var/www/motivis-assets/shared/app/config
> touch /var/www/motivis-assets/shared/app/config/parameters.yml
> ln -nfs /var/www/motivis-assets/shared/app/config/parameters.yml /var/www/motivis-assets/releases/20160411210247/app/config/parameters.yml
• done on [ec2]
✔ Ok [542ms]
➤ Executing task deploy:assets
↳ on [ec2]
> find /var/www/motivis-assets/releases/20160411210247/web/css /var/www/motivis-assets/releases/20160411210247/web/images /var/www/motivis-assets/releases/20160411210247/web/js -exe
c touch -t 201604110902.49 {} ';' &> /dev/null || true
• done on [ec2]
✔ Ok [47ms]
➤ Executing task deploy:vendors
↳ on [ec2]
> if hash composer 2>/dev/null; then echo 'true'; fi
< true
<
> which composer
< /usr/local/bin/composer
> cd /var/www/motivis-assets/releases/20160411210247 && export SYMFONY_ENV=prod && /usr/local/bin/composer install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progre
ss --no-interaction
< Loading composer repositories with package information
< Installing dependencies from lock file
< Analyzed 93 packages to resolve dependencies
< Analyzed 179 rules to resolve dependencies
<   - Installing symfony/yaml (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/process (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/finder (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/polyfill-mbstring (v1.1.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/console (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing phpseclib/phpseclib (2.0.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/expression-language (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing psr/log (1.0.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing symfony/debug (v3.0.4)
<     Loading from cache
<     Extracting archive
<
<   - Installing evenement/evenement (v2.0.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/stream (v0.4.3)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/promise (v2.4.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/event-loop (v0.4.2)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/socket (v0.4.3)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/cache (v0.4.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/dns (v0.4.2)
<     Loading from cache
<     Extracting archive
<<   - Installing react/socket-client (v0.4.5)
<     Loading from cache
<     Extracting archive
<
<   - Installing psr/http-message (1.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing guzzlehttp/psr7 (1.2.3)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/http-client (v0.4.10)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/http (v0.4.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/child-process (v0.4.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing react/react (v0.4.2)
<     Loading from cache
<     Extracting archive
<
<   - Installing elfet/pure (v2.0.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing herrera-io/version (1.1.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing seld/jsonlint (1.4.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing justinrainbow/json-schema (1.6.1)
<     Loading from cache
<     Extracting archive
<
<   - Installing herrera-io/json (1.0.3)
<     Loading from cache
<     Extracting archive
<
<   - Installing herrera-io/phar-update (2.0.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing deployer/phar-update (v1.0.0)
<     Loading from cache
<     Extracting archive
<
<   - Installing deployer/deployer (v3.2.0)
<     Loading from cache
<     Extracting archive
<
< Generating optimized autoload files
<
• done on [ec2]
✔ Ok [1s 136ms]
➤ Executing task deploy:assetic:dump
↳ on [ec2]
> which php
< /usr/bin/php
<
> /usr/bin/php /var/www/motivis-assets/releases/20160411210247/app/console assetic:dump --env=prod --no-debug
  [RuntimeException]
  Could not open input file: /var/www/motivis-assets/releases/20160411210247/app/console
Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at phar:///usr/local/bin/dep/recipe/symfony.php:77
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4
deploy [-p|--parallel]

**Comment by oanhnn** [comment]
Are you checked file exist `/var/www/motivis-assets/releases/20160411210247/app/console`

**Comment by elfet** [comment]
What version of symfony?

**Comment by bdensmore** [comment]
This is what is in the composer.lock file

"symfony/console": "~2.6|~3.0",
"symfony/debug": "~2.6|~3.0",
"symfony/expression-language": "~2.6|~3.0"

**Comment by nemoinho** [comment]
Maybe you use the wrong symfony recipe because the given information about your symfony-installation allow also symfony 3.

Try `require 'recipe/symfony3.php';` (note the 3) instead of `require 'recipe/symfony.php';` at the beginning of your deploy.php

**Comment by bdensmore** [comment]
Thanks for the suggestion @nemoinho. While that didn't work, this did.

Adding set('bin_dir', '/vendor/symfony'); did work.

Things are deploying perfectly now.

Thanks everyone.
