### ISSUE TITLE
Environment's specific config

### ISSUE THREAD

**Issue by adriandmitroca** [deployphp/deployer#626]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

I am wondering if there is possibility (like in Capistrano) to separate Deployer's config for different environments - for example on a production server I'd like to have:
- set custom `php/bin` path (`onlyOn` method doesn't work with `env()`)
- disable `deploy:writable` task (lacks of sudo) (I would have to rewrite whole task just to specify `onlyOn` method)

In Capistrano I would just set this in config file for specific environment and everything would just works. What about here?

**Comment by oanhnn** [comment]
Can you try?
```php
server('svr1', 'xx.xx.xx.xx', 22)
    ->env('php/bin', '/usr/bin/php'); // set special environment variable

server('svr2', 'xx.xx.xx.xx', 22)
    ->env('php/bin', '/usr/local/php7/bin/php'); // set special environment variable

server('svr3', 'xx.xx.xx.xx', 22)
     ->env('branch', 'develop'); // don't set special environment variable, Deployer will use default environment variable 
```

**Comment by adriandmitroca** [comment]
Thanks! It works great. But sadly problem 2 still unresolved - about handling tasks depending on environments (let's say - different `deploy` strategy).

I could define `deploy:production` and `deploy:staging` tasks but then:
- I would duplicate myself
- Deployment would look like `dep deploy:production production`

**Comment by luke83** [comment]
`task($name, $body)` could be changed in `task($name, $body = null)` and return task reference when you call it without $body, so you can do:

```php
task('deploy:writable')->onlyOn(['dev', 'staging'] );

```

**Comment by adriandmitroca** [comment]
@luke83 

Sadly this solution doesn't work. Deployer immediately stops without any output even in debug mode.

**Comment by elfet** [comment]
```
task('deploy:writable')->onlyOn(['dev', 'staging']);
```
This does not supported. %)

**Comment by luke83** [comment]
@adriandmitroca @elfet it was a proposal, sorry for misunderstanding

**Comment by sourcerer-mike** [comment]
+1 I like to disallow some commands on the server too. Especially deploying on some server as they are meant for other things.

**Comment by diimpp** [comment]
Any updates on this?

I'm really dreading the day I will accidentally reload database in production :)

**Comment by antonmedv** [comment]
Not it's possible:
```js
task('deploy:writable')->onlyOn(['dev', 'staging']);
```

**Comment by ScreamingDev** [comment]
Oh okay, it's about whitelisting. The issue looked like people request for blacklisting. So I voted it up.
I guess I open a new one when I'm in such situation again.
