### ISSUE TITLE
Provide PHAR-file over HTTPS

### ISSUE THREAD

**Issue by dennisdegreef** [deployphp/deployer#627]
Please consider providing the `deployer.phar`-file over HTTPS.

Currently the recommended form of installation is:

```
$ curl -L http://deployer.org/deployer.phar -o deployer.phar
$ mv deployer.phar /usr/local/bin/dep
$ chmod +x /usr/local/bin/dep
```

While this command can be vulnerable to a MITM-attack.

If you can, I would love to see the deployer.org website to provide HTTPS (which is easy and free with the Let's Encrypt project).

Additionally, providing a checksumming hash or some form of signature would be greatly appreciated.

I currently cannot be certain that the pharchive I am downloading, is actually what you intended to provide.

Thanks!

**Comment by elfet** [comment]
Hi,

I'm really want to do this stuff. And https will be soon. 

But what best way to work with checksums? md5? PGP?

**Comment by tarjei** [comment]
Hi, any movement on this?

**Comment by elfet** [comment]
I have planned to add https on site. Also i planning to sign phar with PGP. 
But now i have a lot of work, so i don't know then i can come back on this issue. I hope it will be in next month.

**Comment by elfet** [comment]
Done! Now with https! 
https://deployer.org/download

**Comment by dennisdegreef** [comment]
Thanks a lot for this! I really appreciate it!

**Comment by elfet** [comment]
Took about 7 months(!) to do it)) Main problem — just don't have enough time. So i'm looking to sponsors. Created page at https://www.patreon.com/deployer
