### ISSUE TITLE
Symfony project. Not possible to preserve app_dev.php

### ISSUE THREAD

**Issue by murnieza** [deployphp/deployer#630]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

As seen at https://github.com/deployphp/deployer/blob/cd7ec689201105c3592175c1bc10106a205f807d/recipe/symfony.php#L110 it is not possible to override `deploy:clear_controllers` and keep some specific files. This can be useful in non-production environments. 

Is there a way to work around this? Maybe it makes sense to make this task public?

**Comment by elfet** [comment]
How are you trying to override task?

**Comment by murnieza** [comment]
Override works like for any other task. Sorry for false alarm :) 

BTW what is purpose of `->setPrivate()`?

**Comment by elfet** [comment]
To not display in console help.
