### ISSUE TITLE
Bug when running deploy:writeable

### ISSUE THREAD

**Issue by pemenang** [deployphp/deployer#631]
while trying to use deployer and while using `dep deploy -vvv dev` I noticed this error during `deploy:writeable`

### Output of `deploy:writeable`
```
➤ Executing task deploy:writable
↳ on [test_1]
> ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
< www-data
<
> cd /var/www/main_site/releases/20160419070428 && chmod 2>&1; true
< chmod: missing operand
< Try `chmod --help' for more information.
```

`ls -l` shows the latest release doesn't properly chmod

Using `common.php` and `magento.php` taken from `https://github.com/deployphp/deployer/blob/master/recipe/`

Deployer version: **3.2.1**
OS: **Debian Wheezy**

**Comment by oanhnn** [comment]
Look your issue not like a bug. See #492

**Comment by elfet** [comment]
We need to add comment right in bash to avoid this issue came again)
