### ISSUE TITLE
Create a release only if there any changes in project's VCS

### ISSUE THREAD

**Issue by 1allen** [deployphp/deployer#632]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Create a release only if there any changes in project's VCS.

**Comment by elfet** [comment]
I think if user ask to create release, it better to do it. 
This functionality your can create your self for you.

**Comment by 1allen** [comment]
Well, this behavior could be optional :)
Or even default along with fallback `--force` option — user still has choice.

In my case, I've considered deployer for some kind of continuous deployment (e.g. via cron) on certain automatically provisioned nodes — it's possibly not the best practice, but it's quite reliable.
Another case — accidental run of `deploy` task (e.g. by different users).

In both cases `rollback` task becomes quite less usable (you should run it twice or more until the changes are really reverted) or unusable at all (in case the number of releases [created without VCS changes] reaches the number `keep_releases` value).


I'll try my best to contribute this functionality, but I can't promise it due to lack of time :)
Thank you for this tool, it looks so tasty)

**Comment by dimoniet** [comment]
I think that this is a good feature, when there are no changes, give a warning that nothing is going to be deployed, and tell the user that he could deploy anyway putting the `--force` option

Let me check how to do this.

**Comment by elfet** [comment]
`dep deploy` should always create a new release. It's simpler. 

May be add another custom task for checking changes. Closing this issue.

**Comment by 1allen** [comment]
#1755 same-same mai? :-)
