### ISSUE TITLE
[RuntimeException] Without exception message

### ISSUE THREAD

**Issue by Rudolfff** [deployphp/deployer#637]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.2.1 |
| Local Machine OS | Ubuntu 14.04 |
| Remote Machine OS | Debian 7 |

I'm trying implement new deploy in my project but i'm stuck. when i run my deploy command

> dep deploy:update_code beta -vvv

then i have this exception

`➤ Executing task deploy:update_code
↳ on [main]

> cd /var/www/beta.domain.pl && which git
> < /usr/bin/git
> < 
> cd /var/www/beta.domain.pl && git version
> < git version 1.7.10.4
> < 
> cd /var/www/beta.domain.pl && find /var/www/beta.domain.pl/releases -maxdepth 1 -mindepth 1 -type d
> cd /var/www/beta.domain.pl && readlink /var/www/beta.domain.pl/release

  [RuntimeException]  

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at phar:///usr/local/bin/dep/recipe/common.php:146
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Server/Environment.php:101
 Deployer\Server\Environment->get() at phar:///usr/local/bin/dep/src/Server/Environment.php:175
 Deployer\Server\Environment->parseCallback() at n/a:n/a
 preg_replace_callback() at phar:///usr/local/bin/dep/src/Server/Environment.php:161
 Deployer\Server\Environment->parse() at phar:///usr/local/bin/dep/src/functions.php:285
 run() at phar:///usr/local/bin/dep/recipe/common.php:206
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

deploy:update_code [-p|--parallel]
`
this is my deploy.php file

`<?php
require 'recipe/common.php';

server('main', 'beta.domain.pl', 22)
    ->user('user')
    ->password('password')
    ->stage('beta')
    ->env('deploy_path', '/var/www/beta.domain.pl');

set('repository', 'https://bbuser@bitbucket.org/bbuser/beta.domain.pl.git');
set('keep_releases', 2);`

Any idea what's causing this error?

**Comment by oanhnn** [comment]
I see your issue is problem of command 
```
cd /var/www/beta.domain.pl && readlink /var/www/beta.domain.pl/release
```
Please run this command in your server (remote machine)

**Comment by Rudolfff** [comment]
This command doesn't return any error or another message when i execute it on my remote server.

**Comment by oanhnn** [comment]
Can you show full `deploy.php` file and output with `-vvv` mode?

**Comment by Rudolfff** [comment]
Both things are in my first post. This is my deploy.php at the moment.

**Comment by oanhnn** [comment]
Your first post is not enough. I need know task is run.

**Comment by Rudolfff** [comment]
In my opinion this is some issue on server layer. I checked line
`usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114`
```
    public function run($command)
    {
        $this->checkConnection();

        $result = $this->sftp->exec($command);

        if ($this->sftp->getExitStatus() !== 0) {
            $output = $this->sftp->getStdError() ?: $result;
            throw new \RuntimeException($output); //line 114
        }

        return $result;
    }
```

This exception is throw because in my cause ssh returns exit_code 1 (I've checked it via xdebug) after this command
`cd /var/www/beta.domain.pl && readlink /var/www/beta.domain.pl/release`
this is strange situation, because when i run this command directly via ssh terminal then works good.

**Comment by oanhnn** [comment]
> I see your issue is problem of command 
> ```
> cd /var/www/beta.domain.pl && readlink /var/www/beta.domain.pl/release
> ```
> Please run this command in your server (remote machine)

I known problem from your server. Exception is throw after run command 
```
cd /var/www/beta.domain.pl && readlink /var/www/beta.domain.pl/release
```

I want see you `deploy.php` file (excluded your secret) to reproduce it.

**Comment by Rudolfff** [comment]
My deploy file is very short. This is it:

```
<?php
require 'recipe/common.php';

server('main', 'beta.domain.pl', 22)
->user('user')
->password('password')
->stage('beta')
->env('deploy_path', '/var/www/beta.domain.pl');

set('repository', 'https://bbuser@bitbucket.org/bbuser/beta.domain.pl.git');
set('keep_releases', 2);
```

**Comment by oanhnn** [comment]
Were you define `deploy` task ? @@

**Comment by forestia-dev** [comment]
Hi guys,

Same issue for me

Deployer version: 3.2.1
The local machine: ubuntu 14.04
The remote machine: 

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

vagrant@homestead: $ dep deploy prod -vvv
➤ Executing task deploy:prepare
↳ on [prod]
> echo $0
< bash
< 
> if [ ! -d /usr/local/nginx/html/test ]; then mkdir -p /usr/local/nginx/html/test; fi
> if [ ! -L /usr/local/nginx/html/test/current ] && [ -d /usr/local/nginx/html/test/current ]; then echo true; fi
> cd /usr/local/nginx/html/test && if [ ! -d releases ]; then mkdir releases; fi
> cd /usr/local/nginx/html/test && if [ ! -d shared ]; then mkdir shared; fi
• done on [prod]
✔ Ok [1s 660ms]
➤ Executing task deploy:update_code
↳ on [prod]
> which git
< /usr/bin/git
< 
> git version
< git version 2.7.4
< 
> find /usr/local/nginx/html/test/releases -maxdepth 1 -mindepth 1 -type d
> readlink /usr/local/nginx/html/test/release

                      
  [RuntimeException]  
                      

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php:114
 Deployer\Server\Remote\PhpSecLib->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at phar:///usr/local/bin/dep/recipe/common.php:146
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Server/Environment.php:101
 Deployer\Server\Environment->get() at phar:///usr/local/bin/dep/src/Server/Environment.php:175
 Deployer\Server\Environment->parseCallback() at n/a:n/a
 preg_replace_callback() at phar:///usr/local/bin/dep/src/Server/Environment.php:161
 Deployer\Server\Environment->parse() at phar:///usr/local/bin/dep/src/functions.php:285
 run() at phar:///usr/local/bin/dep/recipe/common.php:206
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

deploy [-p|--parallel]

My deploy file:

<?php
require 'recipe/common.php';

server('prod', 'ec2-XX-XX-XX-XX.eu-west-1.compute.amazonaws.com')
    ->user('ec2-user')
    ->pemFile('~/.ssh/my.pem')
    ->env('deploy_path', '/usr/local/nginx/html/test')
    ->stage('master');

set('repository', 'git@github.com:forestia-dev/my-repo.git');
set('keep_releases', 2);

task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'cleanup'
]);

The result of the command on the remote doesn't output anything. 

Any ideas ?

**Comment by ricco24** [comment]
I get same error. Any progress, any suggestions?

Deployer version: 3.3.0
Deploying on local machine with Ubutntu 16.04.

```
// deploy.php
use Symfony\Component\Console\Input\InputArgument;

require getenv('HOME') . '/.composer/vendor/autoload.php';
require getenv('HOME') . '/.composer/vendor/deployer/deployer/recipe/common.php';

argument('version', InputArgument::OPTIONAL, 'Repository tag/branch');

serverList('servers.yml');
set('repository', 'xxx');
set('writable_dirs', ['cache', 'log']);
set('composer_command', '/usr/local/bin/composer');
set('keep_releases', 3);

task('task:composer', function() {
	run("cd {{release_path}} && composer install");
})->desc('Install composer');

task('deploy', [
	'deploy:prepare',
	'task:composer',
	'deploy:symlink',
	'cleanup',
])->desc('Deploy your project');
```

I tried deploy:vendors and now custom composer install task but both get me same error.

```
07:30:01   [Symfony\Component\Process\Exception\ProcessFailedException]            
07:30:01   The command "readlink /var/www/cloud/release" failed.                   
07:30:01   Exit Code: 1(General error)                                             
07:30:01   Working directory: /var/lib/jenkins/workspace/(deploy - staging) cloud  
07:30:01   Output:                                                                 
07:30:01   ================                                                        
07:30:01   Error Output:                                                           
07:30:01   ================   
```

**Comment by ricco24** [comment]
Ok seems like bad definition of default task. It is required use task "deploy:release" before any task using {{release_path}} is called.

So when i changed default task to:

```
task('deploy', [
	'deploy:prepare',
	'deploy:release',
	'deploy:vendors',
	'deploy:symlink',
	'cleanup',
])->desc('Deploy your project');
```

All works ok. Maybe some more specific error message has to be raised when this happens. But i think this issue can be closed.

**Comment by freesh** [comment]
I have the same Problem if i call deploy:init.

**Comment by psihius** [comment]
Same issue here, and I can't find any solutions on google ;|

Here is my deployer.php

> <?php
> require 'recipe/common.php';
> 
> set( 'ssh_type', 'ext-ssh2' );
> set( 'repository', 'git@bitbucket.org:xxxxxxx/yyyyyyyyy.git' );
> set( 'keep_releases', 5 );
> 
> set( 'shared_dirs', [
>   'storage/app',
>   'storage/framework/cache',
>   'storage/framework/sessions',
>   'storage/framework/views',
>   'storage/logs',
> ] );
> set( 'shared_files', [ '.env' ] );
> set( 'writeable_dirs', [ 'storage', 'vendor'] );
> 
> server( 'production', 'xxx.xxx.xxx.xxx', 22 )
>   ->user( 'bankservices' )
>   ->identityFile( '/vagrant/.ssh/id_rsa.pub', '/vagrant/.ssh/id_rsa' )
>   ->stage( 'production' )
>   ->env( 'deploy_path', '/home/bankservices' );
> 
> task( 'artisan:migrate', function ()
> {
>     run( 'cd {{release_path}} && php artisan migrate --force | tee last_migration' );
> } );
> 
> task( 'artisan:down', function ()
> {
>     run( 'cd {{release_path}} && php artisan down' );
> } );
> 
> task( 'artisan:cache-clear', function ()
> {
>     run( 'cd {{release_path}} && php artisan cache:clear' );
> } );
> 
> task( 'artisan:up', function ()
> {
>     run( 'cd {{release_path}} && php artisan up' );
> } );
> 
> task( 'artisan:queue-restart', function ()
> {
>     run( 'cd {{release_path}} && php artisan queue:restart' );
> } );
> 
> task( 'rollback', function ()
> {
>     $releases = env( 'releases_list' );
>     if (isset( $releases[ 1 ] ))
>     {
>         $current  = sprintf( '{{deploy_path}}/releases/%s', $releases[ 0 ] );
>         $previous = sprintf( '{{deploy_path}}/releases/%s', $releases[ 1 ] );
> 
>         // Enable maintenance mode
>         run( sprintf( 'cd "%s" && php artisan down', $current ) );
> 
>         // Rollback old migration if necessary
>         run( sprintf( 'cd "%s" && grep -i "Migrated" last_migration && php artisan migrate:rollback --force; true', $current ) ); // Need to return true or the script will balk
> 
>         // Symlink to old release.
>         run( sprintf( 'cd "{{deploy_path}}" && ln -nfs "%s" current', $previous ) );
> 
>         // Remove release
>         run( sprintf( 'rm -rf "%s"', $current ) );
>         if (isVerbose())
>         {
>             writeln( sprintf( 'Rollback to "%s" release was successful.', $releases[ 1 ] ) );
>         }
> 
>         run( sprintf( 'cd "%s" && php artisan up', $previous ) );
>     }
>     else
>     {
>         writeln( "<comment>No more releases you can revert to.</comment>" );
>     }
> 
> } )->desc( 'Roll back the last commit' );
> 
> task( 'deploy', [
>   'deploy:prepare',
>   'deploy:release',
>   'deploy:update_code',
>   'deploy:shared',
>   'deploy:writable',
>   'deploy:vendors',
>   'artisan:down',
>   'artisan:migrate',
>   'deploy:symlink',
>   'artisan:cache-clear',
>   'artisan:up',
>   'artisan:queue-restart',
>   'cleanup',
> ] )->desc( 'Deploy your project' );
> 
> 
> after( 'deploy', 'success' );

Here is what I get when I try to deploy

> vagrant@bankservices:/vagrant$ php dep -vvv deploy:update_code production
> ➤ Executing task deploy:update_code
> ↳ on [production]
> > cd /home/bankservices && which git
> < /usr/bin/git
> < 
> > cd /home/bankservices && /usr/bin/git version
> < git version 1.9.1
> < 
> > cd /home/bankservices && find /home/bankservices/releases -maxdepth 1 -mindepth 1 -type d
> < /home/bankservices/releases/20160929200901
> < /home/bankservices/releases/20160925132303
> < /home/bankservices/releases/20160925132020
> < /home/bankservices/releases/20160925133109
> < /home/bankservices/releases/20160925123101
> < 
> > cd /home/bankservices && readlink /home/bankservices/release
> 
>                       
>   [RuntimeException]  
>                       
> 
> Exception trace:
>  () at phar:///vagrant/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:32
>  Ssh\Exec->run() at phar:///vagrant/dep/src/Server/Remote/SshExtension.php:116
>  Deployer\Server\Remote\SshExtension->run() at phar:///vagrant/dep/src/functions.php:296
>  run() at phar:///vagrant/dep/recipe/common.php:148
>  {closure}() at n/a:n/a
>  call_user_func() at phar:///vagrant/dep/src/Server/Environment.php:101
>  Deployer\Server\Environment->get() at phar:///vagrant/dep/src/Server/Environment.php:175
>  Deployer\Server\Environment->parseCallback() at n/a:n/a
>  preg_replace_callback() at phar:///vagrant/dep/src/Server/Environment.php:161
>  Deployer\Server\Environment->parse() at phar:///vagrant/dep/src/functions.php:285
>  run() at phar:///vagrant/dep/recipe/common.php:208
>  {closure}() at n/a:n/a
>  call_user_func() at phar:///vagrant/dep/src/Task/Task.php:79
>  Deployer\Task\Task->run() at phar:///vagrant/dep/src/Executor/SeriesExecutor.php:43
>  Deployer\Executor\SeriesExecutor->run() at phar:///vagrant/dep/src/Console/TaskCommand.php:82
>  Deployer\Console\TaskCommand->execute() at phar:///vagrant/dep/vendor/symfony/console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at phar:///vagrant/dep/vendor/symfony/console/Application.php:791
>  Symfony\Component\Console\Application->doRunCommand() at phar:///vagrant/dep/vendor/symfony/console/Application.php:186
>  Symfony\Component\Console\Application->doRun() at phar:///vagrant/dep/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at phar:///vagrant/dep/src/Deployer.php:101
>  Deployer\Deployer->run() at phar:///vagrant/dep/bin/dep:63
>  require() at /vagrant/dep:4
> 
> deploy:update_code [-p|--parallel]
> 
> vagrant@bankservices:/vagrant$ php dep -V
> Deployer version 3.3.0

**Comment by psihius** [comment]
Okay, I know what happens. The issue is this command:
> cd /home/bankservices && readlink /home/bankservices/release
The release directory does not exist, because for some reason the previous guy used "current". So, either in previous versions of Deployer the release directory was called "current" or there was some way to define how the directory has to be called.
Right now the "release" dir name is hardcoded in the code like this:
```php
 /**
 * Return release path.
 */
env('release_path', function () {
    return str_replace("\n", '', run("readlink {{deploy_path}}/release"));
});
```

**Comment by elfet** [comment]
Good point. I think we need to clean this automatically.

**Comment by psihius** [comment]
Some better exception handling would help too. At least write something like "Command <cd /... && readlink /.....> failed due to exit status = 1" - a plain "RuntimeException" is equal to failing silently. I only got the idea to look at exit statuses after a few hours sifting through google and someone mentioning about command exit status.

**Comment by elfet** [comment]
Ok, will do it.

**Comment by psihius** [comment]
Leaving this for the people who will come here in search of the original issue.

I think this is the same issue that happened to the author of this issue, because when running "deploy:update_code" I had the same issue as the author, I just moved on to running "deploy:release".
In any case, before anything else, try running command bellow first - if it runs fine, then it is the issue of using the wrong command. But be aware, that that runs the full deployment process, that can be undesirable.
```
php dep deploy
```

**Comment by elfet** [comment]
Now deploy:release will clear release before deploy.

**Comment by udayakumaar** [comment]
I see some of you got the runtimexception without any message. It happens because the production server does not have git. If it is Ubuntu server, please use the below command:

sudo apt-get install git

Thanks.
