### ISSUE TITLE
2-factor authentication with google authenticator?

### ISSUE THREAD

**Issue by jdavidbakr** [deployphp/deployer#638]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | 3.2.1 |
| Local Machine OS | OSX |
| Remote Machine OS | Linux |
### Description

Because of PCI requirements we have to have 2-factor authentication on our servers.  We have chosen to use public key + google authenticator, but that means there is an exchange each time we log in to a server: the public key is first verified and then I am prompted to enter the google authenticator code to proceed.

I have been unable to figure out how to do this with deployer.  I tried using both identityFile() and password(null) in my server definition, but from what I can tell it looks like the password call replaces the identity file call in the config.  Due to the recent changes in PCI requirements this will likely become more commonplace that logging on to a production server will require a form of 2-factor authentication.  I am not sure whether having the password as a second authentication method would also resolve the issue of not being able to do google authenticator.
### Output log

```
➤ Executing task deploy:prepare


  [RuntimeException]                              
  Unable to login with the provided credentials.  


deploy [-p|--parallel]
```

**Comment by jdavidbakr** [comment]
Possible fix in pull request https://github.com/deployphp/deployer/pull/639

**Comment by oanhnn** [comment]
TODO: 
- [ ] Support this feature with ext-ssh
- [ ] Add unit test
