### ISSUE TITLE
Upgrade to PHPUnit 5.3

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#646]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.x

* [ ] Upgrade to PHPUnit 5.3

**Comment by oanhnn** [comment]
PHPUnit 5.4 require PHP 5.6+ and current it is beta

**Comment by elfet** [comment]
Then 5.3 :)

**Comment by oanhnn** [comment]
PHPUnit 5.0+ require PHP5.6+

**Comment by elfet** [comment]
Done!
