### ISSUE TITLE
Timeout error in phar.../SSH2.php on line 839

### ISSUE THREAD

**Issue by ottomen** [deployphp/deployer#647]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

Hi!

I have an error while deploying process.

"remote: PHP Notice:  Cannot connect to makebecool.pro:9090. Timeout error in phar:///etc/deploy/deployer.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 839
"
Here is the screenshot: http://prntscr.com/b0uy0y 

Deployment .php file is correct, according to the you manual.

This is temporary error. Sometimes it's happen, sometimes it's not.

**Comment by elfet** [comment]
Please, use https://github.com/deployphp/deployer/blob/master/.github/ISSUE_TEMPLATE.md
