### ISSUE TITLE
Question: Deployer on same machine being deployed to

### ISSUE THREAD

**Issue by Rexeh** [deployphp/deployer#648]
Maybe I'm one of the weird ones here, but I'm sure this requirement must exist for those who have small projects and maybe not a separate deployment | prod | uat server set.

When reading the documentation, it appeared that if I want to run

dep deploy from Server1, and also deploy to Server1, then I have to actually SSH back into the box for the same user using deployer, which seems a bit odd!

Let's say I have a **DeploymentUser**, this user controls the deploy.php and shared distributables from their ~ directory.

I login as this user, and run dep deploy staging.

The script then SSHes in as the same user I'm running the command as, and executes. It works great, but the SSHing into the same user makes it a bit dirty, all the same having to create a firewall rule to let the box SSH into itself :)

**User error, or feature request?**

**Comment by khromov** [comment]
@Rexeh The most common way to deploy is from your personal desktop machine. For example, I deploy all my projects from my laptop which runs Deployer locally. :)

**Comment by Rexeh** [comment]
@khromov hmm that might be one way to go, hadn't really thought about doing it that way as I wanted to have it auto deploy on server off TeamCity test runs completing successfully.

**Comment by khromov** [comment]
@Rexeh I see, that's a very valid use case! As you wrote yourself you can actually get it to connect locally without any major issue. Not sure if it's an edge case or a feature request. :)

**Comment by elfet** [comment]
localServer?

**Comment by Rexeh** [comment]
Nope, this is a remote server.

So using a remote server to issue the build command, which in turn deploys on the exact same server.

**Comment by elfet** [comment]
Can you explain what do you want to do?

**Comment by Rexeh** [comment]
Sure no problem.

I would expect to be able to define something along the lines of deploy to self.

Whether you define a user still and escalate to that user... I'd probably say that's a step too far.

So defining server as localhost, forget the username and password credentials and the script executes as executing user.

**Comment by elfet** [comment]
Well, it's what `localServer` do. :)

**Comment by Rexeh** [comment]
Hmm didn't see that in the documentation but will give it a go

**Comment by Rexeh** [comment]
@elfet worked great so will close this off. Many thanks
