### ISSUE TITLE
Timezone inconsistency might delete whole release folder being deployed

### ISSUE THREAD

**Issue by tchapi** [deployphp/deployer#649]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.2.1
| Local Machine OS  | Mac OS X El Capitan
| Remote Machine OS | Ubuntu 16.04 PHP 7

### Description 
When deploying to a remote server, the name of the release folder is determined with the `date()` function of the local machine.

If another user deploys to the same server with a machine that is not configured to use the same timezone, or any timezone at all, the folder name timestamps will not be consistent to *rsort*, which will trigger a wrong cleanup task and potentially delete the current release (being deployed).

The problem apparently lies in https://github.com/deployphp/deployer/blob/master/recipe/common.php#L38

### Steps to reproduce
Take two machines. One machine on which `php.ini` is the standard release file, and another where you added this line in `php.ini`:

    date.timezone = UTC

Deploy from the "standard release" machine, then deploy from the other : the current release folder will be deleted each time you try to release (see log below).

### Content of `deploy.php`
```php
<?php
require 'recipe/symfony.php';
server('[redacted', '[redacted', 22)
    ->user('deploy')
    ->identityFile('[redacted]')
    ->stage('production')
    ->env('deploy_path', '/var/www/[redacted]'); // Define the base path to deploy your project to.
set('repository', '[redacted]');
```

### Output log
```
✔ Ok [808ms]
➤ Executing task deploy:symlink
↳ on [redacted]
> cd /var/www/[redacted] && ln -sfn /var/www/[redacted]/releases/20160512184857 current
> cd /var/www/[redacted] && rm release
• done on [redacted]
✔ Ok [231ms]
➤ Executing task cleanup
↳ on [redacted]
> rm -rf /var/www/[redacted]/releases/20160512184857
```

**Comment by elfet** [comment]
Yes, it's a bug. I'm thinking to using UTC for releases.

**Comment by oanhnn** [comment]
@tchapi I fixed this bug with #656 , please confirm

**Comment by tchapi** [comment]
Ok thanks to you @coox and @oanhnn ! I will confirm asap

**Comment by peschee** [comment]
@tchapi Any updates?

**Comment by tchapi** [comment]
Sorry for the late response — to me it looks good !
