### ISSUE TITLE
[Bug?] I can not deploy a private repository, I get a [runtimeException] message. 

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#652]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | Deployer version 3.2.1
| Local Machine OS  | linux mint 17 with PHP 5.6.21-1+donate.sury.org~trusty+4 (cli) 
| Remote Machine OS | Debian 8 with PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33) 

### Description 
When I try to deploy a remote repository I get a  [RuntimeException]
This issues come from: https://github.com/deployphp/deployer/issues/651

### Steps to reproduce
I have configured my ~/.ssh/config file:
`
Host xx.xxx.xx.xx
 ForwardAgent yes
`

I add my file to forward with:
`ssh-add ~/.ssh/oskarcalvo`

I add PHP SSH2 extension to deploy.php file.
First I add the files to the project: `composer require deployer/deployer herzult/php-ssh`
Them I load the new options in deploy.php
```php
require 'vendor/autoload.php';
set('ssh_type', 'ext-ssh2');
```

I don't change nothing from my remote server because Debian 8 doesn't have the line #AllowAgentForwarding yes in her file /etc/ssh/sshd_config

### Content of `deploy.php`
```php
<?php
/*
 * This file has been generated automatically.
 * Please change the configuration for correct use deploy.
 */

require 'recipe/common.php';
require 'vendor/autoload.php';

// Set configurations
set('repository', 'git@domain.com:username/repository.git');
set('shared_files', ['drupal/sites/geem.t4dos.com/settings.php']);
set('shared_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('writable_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('repository', 'git@github.com:oskarcalvo/FSW-GEMM.git');
set('ssh_type', 'ext-ssh2');

// Configure servers
server('production', 'xx.xxx.xx.xx', 22)
    ->forwardAgent()
    ->user('deployer')
    ->password(null)
    ->forwardAgent()
    ->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', '/var/www/html/geem');
/*
server('beta', 'beta.domain.com')
    ->user('username')
    ->password()
    ->env('deploy_path', '/var/www/beta.domain.com');
*/

/**
 * Restart Apache2 on success deploy.
 */
task('apache:restart', function () {
    // Attention: The user must have rights for restart service
    // Attention: the command "sudo /bin/systemctl restart php-fpm.service" used only on CentOS system
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo service apache2 restart');
})->desc('Restart Apache2 service');

after('success', 'apache:restart');

/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');

after('deploy', 'success');
```

### Output log
*With enabled option for verbose output `-vvv`.*

`
oem FSW-GEMM (master) $ dep deploy production -vvv
➤ Executing task deploy:prepare
↳ on [production]
> echo $0
< bash
< 
> if [ ! -d /var/www/html/geem ]; then mkdir -p /var/www/html/geem; fi
> if [ ! -L /var/www/html/geem/current ] && [ -d /var/www/html/geem/current ]; then echo true; fi
> cd /var/www/html/geem && if [ ! -d releases ]; then mkdir releases; fi
> cd /var/www/html/geem && if [ ! -d shared ]; then mkdir shared; fi
• done on [production]
✔ Ok [2s 125ms]
➤ Executing task deploy:release
↳ on [production]
> mkdir /var/www/html/geem/releases/20160516193639
> cd /var/www/html/geem && if [ -h release ]; then rm release; fi
> ln -s /var/www/html/geem/releases/20160516193639 /var/www/html/geem/release
• done on [production]
✔ Ok [710ms]
➤ Executing task deploy:update_code
↳ on [production]
> which git
< /usr/bin/git
< 
> git version
< git version 2.1.4
< 
> find /var/www/html/geem/releases -maxdepth 1 -mindepth 1 -type d
< /var/www/html/geem/releases/20160516020306
< /var/www/html/geem/releases/20160516193639
< 
> readlink /var/www/html/geem/release
< /var/www/html/geem/releases/20160516193639
< 
> /usr/bin/git clone -b master --depth 1 --recursive -q git@github.com:oskarcalvo/FSW-GEMM.git /var/www/html/geem/releases/20160516193639 2>&1

                      
  [RuntimeException]  
                      

Exception trace:
 () at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:32
 Ssh\Exec->run() at phar:///usr/local/bin/dep/src/Server/Remote/SshExtension.php:116
 Deployer\Server\Remote\SshExtension->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at phar:///usr/local/bin/dep/recipe/common.php:206
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

deploy [-p|--parallel]

`

**Comment by oanhnn** [comment]
Please update you `deploy.php` file like:

```
<?php
require 'recipe/common.php';
// require 'vendor/autoload.php'; <== comment or remove

// Set configurations
set('repository', 'git@domain.com:username/repository.git');
set('shared_files', ['drupal/sites/geem.t4dos.com/settings.php']);
set('shared_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('writable_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('repository', 'git@github.com:oskarcalvo/FSW-GEMM.git');
set('ssh_type', 'ext-ssh2');

// Configure servers
server('production', 'xx.xxx.xx.xx', 22)
//    ->forwardAgent() <== comment or remove
    ->user('deployer')
//   ->password(null)   <== comment or remove
    ->forwardAgent()
    ->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', '/var/www/html/geem');

/**
 * Restart Apache2 on success deploy.
 */
task('apache:restart', function () {
    // Attention: The user must have rights for restart service
    // Attention: the command "sudo /bin/systemctl restart php-fpm.service" used only on CentOS system
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo service apache2 restart');
})->desc('Restart Apache2 service');

after('success', 'apache:restart');

/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');

after('deploy', 'success');

// Add test task
task('test', function() {
     run('ssh -vT git@github.com');
});
```

And run task `test`.

**Comment by oskarcalvo** [comment]
Thanks @oanhnn.
First I have try in my remote server this:
`
deployer .ssh $ ssh -T git@github.com
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Hi oskarcalvo! You've successfully authenticated, but GitHub does not provide shell access.
deployer .ssh $
`

Also I try:
`deployer .ssh $ ssh -vT git@github.com
OpenSSH_6.7p1 Debian-5+deb8u1, OpenSSL 1.0.1k 8 Jan 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to github.com [192.30.252.122] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/deployer/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u1
debug1: Remote protocol version 2.0, remote software version libssh-0.7.0
debug1: no match: libssh-0.7.0
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha2-256 none
debug1: kex: client->server aes128-ctr hmac-sha2-256 none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: RSA 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /home/deployer/.ssh/known_hosts:1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: oskarcalvo
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to github.com ([192.30.252.122]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: Requesting authentication agent forwarding.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
Hi oskarcalvo! You've successfully authenticated, but GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3328, received 1800 bytes, in 0.2 seconds
Bytes per second: sent 18851.8, received 10196.3
debug1: Exit status 1
`

So, I understand that the forward Agent works fine when I connect through ssh to the server.

When I run test task I get this:
`
oem FSW-GEMM (master) $ dep test production -vvv
➤ Executing task test
↳ on [production]
> cd /var/www/html/geem && ssh -vT git@github.com

                                                                                
  [RuntimeException]                                                            
  OpenSSH_6.7p1 Debian-5+deb8u1, OpenSSL 1.0.1k 8 Jan 2015                      
  debug1: Reading configuration data /etc/ssh/ssh_config                        
  debug1: /etc/ssh/ssh_config line 19: Applying options for *                   
  debug1: Connecting to github.com [192.30.252.122] port 22.                    
  debug1: Connection established.                                               
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_rsa type -1                      
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_rsa-cert type -1                 
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_dsa type -1                      
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_dsa-cert type -1                 
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_ecdsa type -1                    
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_ecdsa-cert type -1               
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_ed25519 type -1                  
  debug1: key_load_public: No such file or directory                            
  debug1: identity file /home/deployer/.ssh/id_ed25519-cert type -1             
  debug1: Enabling compatibility mode for protocol 2.0                          
  debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u1            
  debug1: Remote protocol version 2.0, remote software version libssh-0.7.0     
  debug1: no match: libssh-0.7.0                                                
  debug1: SSH2_MSG_KEXINIT sent                                                 
  debug1: SSH2_MSG_KEXINIT received                                             
  debug1: kex: server->client aes128-ctr hmac-sha2-256 none                     
  debug1: kex: client->server aes128-ctr hmac-sha2-256 none                     
  debug1: sending SSH2_MSG_KEX_ECDH_INIT                                        
  debug1: expecting SSH2_MSG_KEX_ECDH_REPLY                                     
  debug1: Server host key: RSA 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48  
  debug1: Host 'github.com' is known and matches the RSA host key.              
  debug1: Found key in /home/deployer/.ssh/known_hosts:1                        
  debug1: SSH2_MSG_NEWKEYS sent                                                 
  debug1: expecting SSH2_MSG_NEWKEYS                                            
  debug1: SSH2_MSG_NEWKEYS received                                             
  debug1: SSH2_MSG_SERVICE_REQUEST sent                                         
  debug1: SSH2_MSG_SERVICE_ACCEPT received                                      
  debug1: Authentications that can continue: publickey                          
  debug1: Next authentication method: publickey                                 
  debug1: Trying private key: /home/deployer/.ssh/id_rsa                        
  debug1: Trying private key: /home/deployer/.ssh/id_dsa                        
  debug1: Trying private key: /home/deployer/.ssh/id_ecdsa                      
  debug1: Trying private key: /home/deployer/.ssh/id_ed25519                    
  debug1: No more authentication methods to try.                                
  Permission denied (publickey).                                                
                                                                                

Exception trace:
 () at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:32
 Ssh\Exec->run() at phar:///usr/local/bin/dep/src/Server/Remote/SshExtension.php:116
 Deployer\Server\Remote\SshExtension->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at /home/oem/oskar/sources/geem/project/FSW-GEMM/deploy.php:63
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

test [-p|--parallel]

`

Thanks.

Oskar

**Comment by oanhnn** [comment]
I see you remote git@github.com by key
```
debug1: Offering RSA public key: oskarcalvo
```
But when using deployer, this key is not found?
Can you modify task test and run:
```
// Add test task #########################################################
task('test', function() {
     runLocally('ssh-add -l');
     run('ssh-add -l');
});
```

**Comment by oskarcalvo** [comment]
As I dit before.
Run it locally:
`oem FSW-GEMM (master) $ ssh-add -l
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskarcalvo (RSA)
1024 db:5c:2a:92:e9:08:38:90:c6:90:7d:81:6f:96:d5:c6 oem@oskar (DSA)
2048 95:55:af:fa:11:e3:68:09:1a:66:37:9f:5b:03:98:cb oscar.calvo@he-cocktail.com (RSA)
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskar@labo (RSA)
`

Run it in the remote server:
`
deployer ~ $ ssh-add -l
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskarcalvo (RSA)
1024 db:5c:2a:92:e9:08:38:90:c6:90:7d:81:6f:96:d5:c6 oem@oskar (DSA)
2048 95:55:af:fa:11:e3:68:09:1a:66:37:9f:5b:03:98:cb oscar.calvo@he-cocktail.com (RSA)
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskar@labo (RSA)
deployer ~ $ 
`

And run the test:

`
oem FSW-GEMM (master) $ dep test production -vvv
➤ Executing task test
↳ on [production]
Run locally: ssh-add -l
> 2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskarcalvo (RSA)
1024 db:5c:2a:92:e9:08:38:90:c6:90:7d:81:6f:96:d5:c6 oem@oskar (DSA)
2048 95:55:af:fa:11:e3:68:09:1a:66:37:9f:5b:03:98:cb oscar.calvo@he-cocktail.com (RSA)
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskar@labo (RSA)
> cd /var/www/html/geem && ssh-add -l

                                                             
  [RuntimeException]                                         
  Could not open a connection to your authentication agent.  
                                                             

Exception trace:
 () at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:32
 Ssh\Exec->run() at phar:///usr/local/bin/dep/src/Server/Remote/SshExtension.php:116
 Deployer\Server\Remote\SshExtension->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at /home/oem/oskar/sources/geem/project/FSW-GEMM/deploy.php:65
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

test [-p|--parallel]
`

**Comment by oskarcalvo** [comment]
I have add this to my deploy.php
```php
// Configure servers
server('production', '92.222.85.85', 22)
    //->forwardAgent()
    ->user('deployer')
    //->password(null)
    ->forwardAgent()
    ->identityFile('~/.ssh/oskarcalvo.pub', '~/.ssh/oskarcalvo', NULL)
    ->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', '/var/www/html/geem');
```

And when I run the test task I get these error message:

```
oem FSW-GEMM (master) $ dep test production -vvv
➤ Executing task test
↳ on [production]
Run locally: ssh-add -l
> 2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskarcalvo (RSA)
1024 db:5c:2a:92:e9:08:38:90:c6:90:7d:81:6f:96:d5:c6 oem@oskar (DSA)
2048 95:55:af:fa:11:e3:68:09:1a:66:37:9f:5b:03:98:cb oscar.calvo@he-cocktail.com (RSA)
2048 71:31:98:99:2f:80:fe:4b:f0:da:b1:99:cb:9c:e2:5b oskar@labo (RSA)
> cd /var/www/html/geem && ssh-add -l
[deployer@92.222.85.85] Password:
PHP Warning:  ssh2_auth_pubkey_file(): Authentication failed for deployer using public key: Username/PublicKey combination invalid in phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Authentication/PublicKeyFile.php on line 46

                                                              
  [RuntimeException]                                          
  The authentication over the current SSH connection failed.  
                                                              

Exception trace:
 () at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Session.php:167
 Ssh\Session->authenticate() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Session.php:140
 Ssh\Session->createResource() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/AbstractResourceHolder.php:25
 Ssh\AbstractResourceHolder->getResource() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Subsystem.php:39
 Ssh\Subsystem->getSessionResource() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:18
 Ssh\Exec->createResource() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/AbstractResourceHolder.php:25
 Ssh\AbstractResourceHolder->getResource() at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:24
 Ssh\Exec->run() at phar:///usr/local/bin/dep/src/Server/Remote/SshExtension.php:116
 Deployer\Server\Remote\SshExtension->run() at phar:///usr/local/bin/dep/src/functions.php:296
 run() at /home/oem/oskar/sources/geem/project/FSW-GEMM/deploy.php:66
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:63
 require() at /usr/local/bin/dep:4

test [-p|--parallel]

```

**Comment by oanhnn** [comment]
@oskarcalvo 
With issue about using `identityFile()`, it may be is a problem of key.
http://stackoverflow.com/questions/3407503/trying-to-connect-using-ssh2-auth-pubkey-file

I will research about problem using `forwardAgent()`

**Comment by oskarcalvo** [comment]
OK @oanhnn , I remove then  identifyFile() method.

I hope, we can fix my problem to deploy with private repository.


Oskar

**Comment by oskarcalvo** [comment]
It's working now. I think I don't change anything.

this is my last deploy.php
```php

<?php
/*
 * This file has been generated automatically.
 * Please change the configuration for correct use deploy.
 */

require 'recipe/common.php';
//require 'vendor/autoload.php';

// Set configurations
set('repository', 'git@github.com:oskarcalvo/xxx.git');
set('shared_files', ['drupal/sites/geem.t4dos.com/settings.php']);
set('shared_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('writable_dirs', ['drupal/sites/geem.t4dos.com/files']);
set('repository', 'git@github.com:oskarcalvo/FSW-GEMM.git');
set('ssh_type', 'ext-ssh2');

// Configure servers
server('production', '92.222.85.85', 22)
    //->forwardAgent()
    ->user('deployer')
    //->password(null)
    ->forwardAgent()
    //->identityFile('/home/oem/.ssh/oskarcalvo.pub', '/home/oem/.ssh/oskarcalvo', NULL)
    ->stage('production')
    ->env('branch', 'master')
    ->env('deploy_path', '/var/www/html/geem');
/*
server('beta', 'beta.domain.com')
    ->user('username')
    ->password()
    ->env('deploy_path', '/var/www/beta.domain.com');
*/

/**
 * Restart Apache2 on success deploy.
 */
task('apache:restart', function () {
    // Attention: The user must have rights for restart service
    // Attention: the command "sudo /bin/systemctl restart php-fpm.service" used only on CentOS system
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo service apache2 restart');
})->desc('Restart Apache2 service');

after('success', 'apache:restart');

/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');

after('deploy', 'success');

// Add test task #########################################################
task('test', function() {
    //run('ssh -vT git@github.com');
    runLocally('ssh-add -l');
    run('ssh-add -l');
}); 
```

Oskar
