### ISSUE TITLE
Setting file owner (chown)?

### ISSUE THREAD

**Issue by khromov** [deployphp/deployer#654]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

I noticed files are created under the account you use for authentication, but I need the files to have specific user/group, not same as SSH account. What is the best way to do this with Deployer?

**Comment by khromov** [comment]
If someone else gets stuck a quick workaround for this is to write a custom task, for example:

```php
task('deploy:owner', function () {
  run('chown -R www-data:www-data /var/www/site');
});
```

Something built-in would be nice though, it's a very common feature.

**Comment by oanhnn** [comment]
@khromov 
Thank you for your idea. It is good, but it can have use root privilege. We will think about it.

**Comment by elfet** [comment]
What about writable?

**Comment by khromov** [comment]
@elfet I assume that chmods the files to be writable? I'm currently deploying a WordPress project and it doesn't play nice if the files are not owned by the web server process... The workaround task I have works well so you can consider adding native chown-capabilities a feature request!

**Comment by elfet** [comment]
Solved with v4.

**Comment by dustingraham** [comment]
But, how was it solved? Looking through the docs, have not found it yet.

**Comment by antonmedv** [comment]
Use `run('chiwn ...')`
