### ISSUE TITLE
ssh key forwarding broken?

### ISSUE THREAD

**Issue by glaszig** [deployphp/deployer#659]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | v3.3.0 |
| Local Machine OS | Ubuntu 14.04.3 LTS `Linux vagrant-ubuntu-trusty-64 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` |
| Remote Machine OS | Ubuntu 14.04.3 LTS `Linux deploy-test 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` |
### Description

i have two vagrant boxes up and running. i log into one of them via `vagrant ssh vagrant-box-one` and have my ssh key forwarded so that `ssh -T git@github.com` returns the authenticated greeting from github.
from that vagrant box i'd like to deploy to the other vagrant box. to ensure my ssh key is forwarded to that second vagrant box i verified that the following works:

```
vagrant@vagrant-box-one$ ssh vagrant-box-two ssh -T git@github.com
vagrant@192.168.222.90's password:
Hi glaszig! You've successfully authenticated, but GitHub does not provide shell access.
```

all fine.

now i have a `deploy.php` with said vagrant box configured as a server.

``` php
server('vagrant-box-two', '192.168.222.90')
    ->user('vagrant')
    ->password('vagrant')
    ->env('deploy_path', '/var/www/');

task('test', function() {
     run('ssh -vT git@github.com');
});
```

when i do the following i expect the output from the manual command above but get:

```
bin/dep test vagrant-box-two -vvv
➤ Executing task test
↳ on [vagrant]
> cd /var/www && ssh -vT git@github.com


  [RuntimeException]
  OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
  debug1: Reading configuration data /etc/ssh/ssh_config
  debug1: /etc/ssh/ssh_config line 19: Applying options for *
  debug1: Connecting to github.com [192.30.252.131] port 22.
  debug1: Connection established.
  debug1: identity file /home/vagrant/.ssh/id_rsa type -1
  debug1: identity file /home/vagrant/.ssh/id_rsa-cert type -1
  debug1: identity file /home/vagrant/.ssh/id_dsa type -1
  debug1: identity file /home/vagrant/.ssh/id_dsa-cert type -1
  debug1: identity file /home/vagrant/.ssh/id_ecdsa type -1
  debug1: identity file /home/vagrant/.ssh/id_ecdsa-cert type -1
  debug1: identity file /home/vagrant/.ssh/id_ed25519 type -1
  debug1: identity file /home/vagrant/.ssh/id_ed25519-cert type -1
  debug1: Enabling compatibility mode for protocol 2.0
  debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
  debug1: Remote protocol version 2.0, remote software version libssh-0.7.0
  debug1: no match: libssh-0.7.0
  debug1: SSH2_MSG_KEXINIT sent
  debug1: SSH2_MSG_KEXINIT received
  debug1: kex: server->client aes128-ctr hmac-sha1 none
  debug1: kex: client->server aes128-ctr hmac-sha1 none
  debug1: sending SSH2_MSG_KEX_ECDH_INIT
  debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
  debug1: Server host key: RSA 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
  debug1: Host 'github.com' is known and matches the RSA host key.
  debug1: Found key in /home/vagrant/.ssh/known_hosts:1
  debug1: ssh_rsa_verify: signature correct
  debug1: SSH2_MSG_NEWKEYS sent
  debug1: expecting SSH2_MSG_NEWKEYS
  debug1: SSH2_MSG_NEWKEYS received
  debug1: Roaming not allowed by server
  debug1: SSH2_MSG_SERVICE_REQUEST sent
  debug1: SSH2_MSG_SERVICE_ACCEPT received
  debug1: Authentications that can continue: publickey
  debug1: Next authentication method: publickey
  debug1: Trying private key: /home/vagrant/.ssh/id_rsa
  debug1: Trying private key: /home/vagrant/.ssh/id_dsa
  debug1: Trying private key: /home/vagrant/.ssh/id_ecdsa
  debug1: Trying private key: /home/vagrant/.ssh/id_ed25519
  debug1: No more authentication methods to try.
  Permission denied (publickey).


Exception trace:
 () at /var/www/project/vendor/herzult/php-ssh/src/Ssh/Exec.php:32
 Ssh\Exec->run() at /var/www/project/vendor/deployer/deployer/src/Server/Remote/SshExtension.php:116
 Deployer\Server\Remote\SshExtension->run() at /var/www/project/vendor/deployer/deployer/src/functions.php:296
 run() at /var/www/project/deploy.php:62
 {closure}() at n/a:n/a
 call_user_func() at /var/www/project/vendor/deployer/deployer/src/Task/Task.php:79
 Deployer\Task\Task->run() at /var/www/project/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at /var/www/project/vendor/deployer/deployer/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /var/www/project/vendor/deployer/deployer/src/Deployer.php:101
 Deployer\Deployer->run() at /var/www/project/vendor/deployer/deployer/bin/dep:64

test [-p|--parallel]
```

after seeing it reads `/etc/ssh/ssh_config` i figured i just need to configure ssh to forward the keys in that file:

```
Host *
  ForwardAgent yes
```

...to no avail. still fails to forward my key.
### Expected Behavior

the ssh implementation is supposed to forward my local ssh key _through_ `vagrant-box-one` _to_ `vagrant-box-two` -- as it does when using ssh manually.
### Background

we have a vagrant dev box which developers use to develop one of our php apps.
we also use the same box to deploy from to our production systems so everybody using the box must be able to log into the box, forwarding their ssh key and having that key again forwarded to the production systems to `git clone` our app onto the production servers.

almost the same scenario applies for our ci setup: a vm runs the tests and deploys our app onto the production systems -- in the future via deployer, hopefully.

what am i doing wrong? is this broken? anybody knows a workaround?

**Comment by glaszig** [comment]
oh dear. this appears to be a long-standing problem related to #70, #232, #223, #80, #393 and others.

**Comment by elfet** [comment]
Yes, both implementation of ssh on php has problems agent forwarding. In next deployer version im planning to implement native ssh support.

**Comment by elfet** [comment]
Now has native ssh in v4.

**Comment by htmlauthor** [comment]
I am having exact same issue as #70 even if I am using version 4.0.2 any ideas on it?

**Comment by elfet** [comment]
Try to use deploy keys.

**Comment by htmlauthor** [comment]
I am using deployment key.

**Comment by elfet** [comment]
Try to use native ssh.

**Comment by htmlauthor** [comment]
Any pointers on how to do this?

**Comment by elfet** [comment]
https://deployer.org/docs/configuration

**Comment by htmlauthor** [comment]
My bad - I was using ssh key which was protected with passphrase. It's now working after changing key to the one which is not passphrase protected. 

It would still be nice to be able to use one which is protected, but now I am happy it is working.
