### ISSUE TITLE
Fatal error while declaring env-method

### ISSUE THREAD

**Issue by makallio85** [deployphp/deployer#669]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.3.0 |
| Local Machine OS | Win7 x64 |
| Remote Machine OS | N/A |
### Description

Fatal error: Cannot redeclare env() (previously declared in C:\xampp\htdocs\private-api\app_information_services\vendor\cakephp\cakephp\src\Core\functions.php
82) in C:\xampp\htdocs\private-api\app_information_services\vendor\deployer\deployer\src\functions.php on line 579
### Steps to reproduce

I just ran dep command and this shows up. It seems that cakephp has also env-method defined  ( https://github.com/cakephp/cakephp/blob/master/src/Core/functions.php#L182 )

Composer autoloader will cause cakephp functions.php to load.
### Content of `deploy.php`

``` php

require 'paths.php';
require ROOT . DS . 'vendor/deployer/deployer/recipe/composer.php';

try {
    $dotenv = new \Dotenv\Dotenv(ROOT);
    $dotenv->overload();
} catch (\Dotenv\Exception\InvalidPathException $e) {
    die($e);
}

server('test', getenv('TEST_SERVER_HOST'), 22)
    ->user(getenv('TEST_SERVER_USERNAME'))
    ->password(null)
    ->stage('test')
    ->env('deploy_path', getenv('TEST_SERVER_DEPLOY_PATH'));

server('production', getenv('PRODUCTION_SERVER_HOST'), 22)
    ->user(getenv('PRODUCTION_SERVER_USERNAME'))
    ->password(null)
    ->stage('production')
    ->env('deploy_path', getenv('PRODUCTION_SERVER_DEPLOY_PATH'));

set('repository', getenv('MY_REPO'));

task('reload:httpd', function () {
    run('sudo -S /sbin/service httpd reload');
});

after('deploy', 'reload:httpd');
after('rollback', 'reload:httpd');
```
### Output log

_With enabled option for verbose output `-vvv`._

No output available.

**Comment by oanhnn** [comment]
Your problem like #316 
It will be fixed in Deployer v4.x . But now, you can fix it with commit https://github.com/ceesvanegmond/deployer/commit/3ccbb2ce1a1d99d6c4f1fab9f1c3531a3e329e99
