### ISSUE TITLE
*.yml files are not used in deploy 3.x ?

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#673]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

Hello oanhnn, in your anwser  https://github.com/deployphp/deployer/issues/670#issuecomment-222036421  you comment the load of the *.yml file.
That means that in 3.x version we must use *.php files? Or it's only for my proposal of creation of dinamic values.

Thanks

Oskar

**Comment by elfet** [comment]
What is ylm?

**Comment by oskarcalvo** [comment]
Sorry , my mistake. I want to say  *.yml files

**Comment by oanhnn** [comment]
Yes. This is compare between using `.php` and `.yml` file:

Feature | Using php file | Using yaml file
--- | --- | ---
Simple | No (Like code) | Yes
Static environment value | Yes | Yes
Dynamic environment value | Yes | No

I like using php file, and each file is a statge :smile:
