### ISSUE TITLE
Getting current server username

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#674]
Issue Type: Question
Deployer Version: 3.3.0
Local Machine OS: OSX
Remote Machine OS: Ubuntu 14.04

How do I (in a deploy stage script) get the current username from the server config. Eg,
```php
runLocally('echo {user}');
```

I'm trying to compose a ssh command for fetching files from the remote server, eg,
```php
    runLocally('rsync --exclude .cache -re ssh {user}@{{server.host}}:{{deploy_path}}/shared/web/app/uploads web/app', 999);
```

And the dep command looks like the following:
```bash
dep pull production
```

**Comment by elfet** [comment]
`whoami`

**Comment by ekandreas** [comment]
Great! Thanks!
