### ISSUE TITLE
The revison option is never checked in deploy:update_code

### ISSUE THREAD

**Issue by Baltazardoung** [deployphp/deployer#675]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug,
| Deployer Version  | 3.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
The `revison` option (1fc4edc771fb660c90b8270a7ae2edaa05e92fcf)  pass to deployer script is never checked in `deploy:update_code` task because the `tag` InputOption object (`input()->hasOption('tag')`) always exists (with `null` default value).

### Content of `deploy.php`
```php
<?php
require 'recipe/common.php';

task('hasOption', function () {

    // See 1fc4edc771fb660c90b8270a7ae2edaa05e92fcf commit
    if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
    } elseif (input()->hasOption('revision')) {
        $revision = input()->getOption('revision');
    }

    $at = '';
    if (!empty($revision)) {
        $at = $revision;
    } else if (!empty($tag)) {
        $at = $tag;
    } elseif (!empty($branch)) {
        $at = $branch;
    }

    writeln("<info>The value is " . (empty($at)?'EMPTY':$at) . " when it should be " . input()->getOption('revision') . "</info>");
});

task('test', [
    'hasOption',
]);
```

### Output log
php deployer.phar test --revision=1fc4edc771fb660c90b8270a7ae2edaa05e92fcf -vvv
➤ Executing task hasOption
↳ on [localhost]
The value is EMPTY when it should be 1fc4edc771fb660c90b8270a7ae2edaa05e92fcf
• done on [localhost]
✔ Ok [1ms]

**Comment by oanhnn** [comment]
Thank for reporting bug.
It will fixed with #676

**Comment by Baltazardoung** [comment]
This bug should be also fixed in the 4.x branch, no ?

**Comment by oanhnn** [comment]
Yes. It wil be fixed in branch 4.x

**Comment by oanhnn** [comment]
I merged to 4.x
