### ISSUE TITLE
problem with stdin: is not a tty on deploy:shared

### ISSUE THREAD

**Issue by pniederlag** [deployphp/deployer#677]
| Q | A |
| --- | --- |
| Issue Type | Bug or Feature Request |
| Deployer Version | v3.3.0/master |
| Local Machine OS | ubuntu 12.04 LTS |
| Remote Machine OS | cPanel managed |
### Description

the deploy:shared task runs into an exception, while deploy:prepare just runs fine.

```
➤ Executing task deploy:shared
↳ on [default]
> if [ -d $(echo stdin: is not a tty/home/xxx/yyy-test/releases/20160531093028/Web/fileadmin) ]; then rm -rf stdin: is not a tty/home/xxx/yyy-test/releases/20160531093028/Web/fileadmin; fi
> mkdir -p /home/xxx/yyytest/shared/Web/fileadmin
> mkdir -p `dirname stdin: is not a tty/home/xxx/yyy-test/releases/20160531093028/Web/fileadmin`

[RuntimeException]                          
stdin: is not a tty                         
dirname: extra operand `is'                 
Try `dirname --help' for more information.  
mkdir: missing operand                      
Try `mkdir --help' for more information.    
```
### Background

The deploy:prepare task has a check for this problem
https://github.com/deployphp/deployer/blob/master/recipe/common.php#L111

As this check didn't trigger I added some debugs and found that for our environment the message has some extra bytes or for some other reason does not match the exact string comparison. For this reason I'd like to propose to change the default test for exact string matching into a less strict check.
### Open Qustions

Why does deploy:prepare work without any troubles (despite missing tty), while deploy:shared fails so bad (see above)
### Content of `deploy.php`  to demonstrate the problem

``` php
<?php
/**
* deployment description to test error condition  on stdin: is not a tty
**/
include 'vendor/deployer/deployer/recipe/common.php';
include 'vendor/deployphp/recipes/recipes/rsync.php';

server('default', getenv('DEPLOYER_HOST'), getenv('DEPLOYER_PORT'))
    ->user(getenv('DEPLOYER_USER'))
    ->env('deploy_path', getenv('DEPLOYER_DESTINATION'))
    ->identityFile();

task('test:bug_tty', function() {
    cd(''); // To run command as raw.
    $result = run('echo $0')->toString();
    if (preg_match('/stdin: is not a tty.*/', $result)) {
            throw new RuntimeException(
                "Looks like ssh inside another ssh.\n" .
                "Help: http://goo.gl/gsdLt9"
            );
        }
})->desc('debugging');
```

**Comment by elfet** [comment]
Hmmm, it's come from https://github.com/deployphp/deployer/commit/598773719e7b7fd0cb139b8246e16945a4143299

**Comment by elfet** [comment]
@pbudzon ping, can you explain a little bit your commit?

**Comment by elfet** [comment]
@pniederlag take a look at #249 #248

**Comment by pbudzon** [comment]
@elfet This was over a year ago... I'm guessing something changed inside Deployer in the meantime which aggravated this?

**Comment by claytonrcarter** [comment]
I ran into this issue trying to run `deploy:symlink` on a cPanel+jailshell system.  It seems to arise from the references to `{{release_path}}` and the usage of `readlink` to dereference it in the `common.php` recipe.

Personally, I was able to work around it by overriding the `env('release_path',...);` with my own:

Original (in `common.php` line `145`):
```
env('release_path', function () {
    return str_replace("\n", '', run("readlink {{deploy_path}}/release"));
});
```

My 'fix':
```
env('release_path', function () {
  $result = explode( "\n", run("readlink {{deploy_path}}/release"));
  $result = ( $result[0] != "stdin: is not a tty" ) ? $result[0] : $result[1];
  return str_replace("\n", '', $result);
});
```

Not sure if that's helpful, but FWIW, it works for me.  Thanks!

**Comment by claytonrcarter** [comment]
I should clarify that, in my case, all of the output from the shell commands had the `stdin ...` as the first line of output, but the rest of the output looked fine.  For example:
```
➤ Executing task deploy:prepare
↳ on [production]
> echo $0
< stdin: is not a tty
< jailshell
<
```
and
```
➤ Executing task deploy:symlink
↳ on [production]
> readlink /home/failbett/public_html/fbf-webapps/test/release
< stdin: is not a tty
< /home/failbett/public_html/fbf-webapps/test/releases/20160814121455
<
```

**Comment by elfet** [comment]
Solved in v4.

**Comment by maykino** [comment]
How do I upgrade to version 4? Doesn't seem to be out yet.

**Comment by elfet** [comment]
Will be released soon. You can now test master branch.

**Comment by elfet** [comment]
#910
