### ISSUE TITLE
Permissions on Remote Server

### ISSUE THREAD

**Issue by joshbrown** [deployphp/deployer#68]
Hey there!

I'm still trying to determine what permissions are needed on the remote server for using deployer?

The user I'm using is `fo`, and the user Nginx uses is the standard `www-data`. When everything deployed, checking the permissions it's `fo:fo`, but shouldn't it be `fo:www-data`? I've added the user `fo` to the `www-data` group. I just get a forbidden error when trying to access the site after deploying.

Any help is appreciated! Thanks!

**Comment by elfet** [comment]
Fixed. Now using `setfacl`.
