### ISSUE TITLE
PHP Notice:  Undefined variable: key_comment

### ISSUE THREAD

**Issue by gulios** [deployphp/deployer#681]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0

### Description 
*➤ Executing task deploy:prepare
PHP Notice:  Undefined variable: key_comment in phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib/System/SSH/Agent.php on line 180*

**Comment by oanhnn** [comment]
I think this is problem of `phpseclib`. You should report for `phpseclib` projects

**Comment by gulios** [comment]
strange because they changed it in head version https://github.com/phpseclib/phpseclib/blob/master/phpseclib/System/SSH/Agent.php
but in your composer it downloads older with that bug

```
$key->loadKey('ssh-rsa ' . base64_encode($key_blob) . ' ' . $key_comment);
```

**Comment by oanhnn** [comment]
Deployer using a stable version of phpseclib. But this change of phpseclib only exist on master branch and not include any stable version >= 2.0.
This problem will be resolved after phpseclib release a new version 2.x

**Comment by gulios** [comment]
Thx

**Comment by gulios** [comment]
ok, phpseclib released 
  - Installing phpseclib/phpseclib (2.0.2)

Can you upgrade deployer.phar ?

**Comment by oanhnn** [comment]
Close this issue. Please follow #712

**Comment by thiagolcks** [comment]
Hey guys, I'm still having this issue.

**Comment by elfet** [comment]
I'll try to upgrade phpseclib.
