### ISSUE TITLE
setfacl: illegal option -- R

### ISSUE THREAD

**Issue by uradvd85** [deployphp/deployer#683]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Remote Machine OS | Freebsd 9.1 |
### Description

root@work:/data/www/site/releases/20160603115438 # cd /data/www/site/releases/20160603115438 && sudo setfacl -R -m u:"uradvd85":rwX -m u:`whoami`:rwX wp-content/uploads
setfacl: illegal option -- R
usage: setfacl [-bdhkn] [-a position entries] [-m entries] [-M file] [-x entries] [-X file] [file ...]
root@work:/data/www/site/releases/20160603115438 #
### Output log

Executing task deploy:writable
↳ on [old]

> cd /data/www/site/releases/20160603115438 && chmod 2>&1; true
> < usage: chmod [-fhv] [-R [-H | -L | -P]] mode file ...
> <
> cd /data/www/site/releases/20160603115438 && if hash setfacl 2>/dev/null; then echo 'true'; fi
> < true
> <
> cd /data/www/site/releases/20160603115438 && sudo setfacl -R -m u:"uradvd85":rwX -m u:`whoami`:rwX wp-content/uploads

  Unable to setup correct permissions for writable dirs.
  You need to configure sudo's sudoers files to not prompt for password,
  or setup correct permissions manually.

  [RuntimeException]
  We trust you have received the usual lecture from the local System
  Administrator. It usually boils down to these three things:
      #1) Respect the privacy of others.
      #2) Think before you type.
      #3) With great power comes great responsibility.
  sudo: no tty present and no askpass program specified

**Comment by nemoinho** [comment]
`-R` and `--recursive` are not supported on a typical freebsd installation (see: [FreeBSD manpage for setfacl](https://www.freebsd.org/cgi/man.cgi?query=setfacl&sektion=1)).

But to make this clear this problem may occur on every non-GNU system (except OSX 😉), so this will also happens on Solaris and maybe other BSD's as well.

A possible simple workaround which also works on GNU systems and OSX could be this solution, but it may needs some more investigation:
    
    $ find DIRECTORY_PATH | xargs setfacl OPTIONS

**Comment by elfet** [comment]
> $ find DIRECTORY_PATH | xargs setfacl OPTIONS
Really need to test this. If some one can test it and create PR – ❤️

**Comment by elfet** [comment]
Solved in v4.
