### ISSUE TITLE
Parallel Deploy and Rollbacks

### ISSUE THREAD

**Issue by rlacerda83** [deployphp/deployer#689]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | N/A
| Local Machine OS  | Ubuntu
| Remote Machine OS | Red Hat

### Description 

Hello friends,

I wonder if the deployer meets my need.

I have two cases to deploy a production and other staging for testing.

My production environment has 3 servers and the staging has only one server.

How does the parallel deployment? It performs all commands on all machines? In the case of my deploy in production, would run composer and all tasks on all servers?

If so, it is not performative. Today we have a script that does to build the project locally, performs all tasks and then replicates only the code for all servers. You can do this with the deployer?

Another doubt that I was against the rollback.
The rollback deployer just change the symlink the current folder?
Does not perform migrations? You can send failure notifications?

My problem here is that if there is a failure in a server I need to give a complete rollback, including code and database. If not I have cases where I have a code out of sync with the database, and that's too bad ...

Thanks!

**Comment by elfet** [comment]
Now deployer does not track youк flow of migrations, you need to define your own tasks for that. Also by default deployer start build of all servers, but it can build it only on one server as well.

**Comment by unclead** [comment]
You can prepare new release localy and then use `rsync` to delivery new release to all servers. You can find `rsync` recipe here https://github.com/deployphp/recipes/blob/master/recipes/rsync.php

**Comment by rlacerda83** [comment]
Thank you @elfet and @unclead.
I will try rsync.

I did not understand what I should do with the migration in case of rollback. Can you explain a little better please?

Each server has its own database.

**Comment by unclead** [comment]
you can execute your own task for downgrade database after peroming default `rollback` task.
There is an example from doc: http://deployer.org/docs/examples
You can write the task .e.g. `rollback:db` and call it after rollback task
```
after('rollback', 'rollback:db');
```

**Comment by rlacerda83** [comment]
One more doubt!

Instead of doing the build locally, I need to do in just a remote server, and then replicate the build to other servers using rsync.

Does this work with the recipe of rsync? If not I can create a task to run the rsync commands manually.

Would be like this:
```
// servers prod1, prod2, prod3
// build only in prod1
task ('deploy', [
    'Deploy: prepare', // common recipe - runOnly in prod1
    'Deploy: release', // common recipe - runOnly in prod1
    'Deploy: update_code', // common recipe - runOnly in prod1
    'Deploy: vendors', // common recipe - runOnly in prod1
    'Deploy:bower', // common recipe - runOnly in prod1
    'Deploy:sync', // custom task only in prod1 to rsync from prod1 to prod2 and prod3
    'Deploy: symlink', // common recipe - all servers
    'Cleanup', // common recipe - all servers
])->desc('your Deploy project');
```
