### ISSUE TITLE
Impossible to call run or runLocally when using task()->once()

### ISSUE THREAD

**Issue by ahfeel** [deployphp/deployer#690]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.3.0 |
| Local Machine OS | OSX |
| Remote Machine OS | N/A |
### Description

When declaring a task to be executed locally and only once through the ->once() modified, it's impossible to call run() or runLocally() as it throws the following exception :

`Fatal error: Uncaught Error: Call to a member function parse() on null in phar:///Users/ahfeel/Work/instant-gaming/deployer.phar/src/functions.php:316`

Seems that env() returns null

**Comment by oanhnn** [comment]
Can you show more info?
Eg: an example task, deploy.php

**Comment by ahfeel** [comment]
Sure, here it is :

```
task('ig:notify_rollbar', function() {
    $ch = curl_init('https://api.rollbar.com/api/1/deploy/');
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query(['access_token' => 'XXXX', 'environment' => 'production', 'revision' => trim(runLocally('git log -n 1 --format="%h"')), 'local_username' => runLocally('whoami')]));
    curl_exec($ch);
})->once();
```

This doesn't work :)

**Comment by adamdude828** [comment]
I am getting the same problem. It appears that runlocally is attempting to parse the environment but it shouldn't if the task is only ran once. Would you be open to pull request to only parse the command if an environment is there, to catch this case where once is used?

```php
task('deploy:clone', function() {
    if (!input()->hasOption('tag')) {
        throw new \Exception("Must provide tag to build");
    }
    $repo = get("repository");
    runlocally("cd /tmp/ && git clone $repo ".get("folderName"));
    runlocaly("cd /tmp/".get("folderName")." && git checkout ".input()->getOption("tag"));
})->once();
```

**Comment by elfet** [comment]
Done!

**Comment by elfet** [comment]
```php
task('test', function () {
    runLocally('echo "{{repository}}";');
    writeln(get('repository'));
})->once();
```
