### ISSUE TITLE
deploy:symlink is not atomic.

### ISSUE THREAD

**Issue by huoding** [deployphp/deployer#691]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

source code:

```
task('deploy:release', function () {
    $releasePath = env()->parse("{{deploy_path}}/releases/{{release_name}}");
    $i = 0;
    while (run("if [ -d $releasePath ]; then echo 'true'; fi")->toBool()) {
        $releasePath .= '.' . ++$i;
    }
    run("mkdir $releasePath");
    run("cd {{deploy_path}} && if [ -h release ]; then rm release; fi");
    run("ln -s $releasePath {{deploy_path}}/release");
})->desc('Prepare release');
```

first rm symlink, then make symlink, so deploy:release is not atomic.

the right method: make a temp symlink, then 'mv -fT' symlink

**Comment by elfet** [comment]
First of all `mv -T` does not exist on some OS. 
Second of all this is just release, server must be configured to look at current symlink. Release link used only due deployment process.

**Comment by huoding** [comment]
deploy:symlink is not atomic, too:

```
/**
 * Create symlink to last release.
 */
task('deploy:symlink', function () {
    run("cd {{deploy_path}} && ln -sfn {{release_path}} current"); // Atomic override symlink.
    run("cd {{deploy_path}} && rm release"); // Remove release link.
})->desc('Creating symlink to release');
```

strace ln -sfn, show: first unlink, then symlink. not  atomic.

```
shell> strace ln -sfn releases/foo current
symlink("releases/foo", "current")      = -1 EEXIST (File exists)
unlink("current")                       = 0
symlink("releases/foo", "current")      = 0
```

**Comment by dnaber-de** [comment]
What would be a possible alternative, @huoding ?

**Comment by elfet** [comment]
Well we can add `mv -T` too. But it's not supported by a lot of systems and we need to add precheck.

```
$ strace mv -T z.new z
lstat64("z.new", {st_mode=S_IFLNK|0777, st_size=1, ...}) = 0
lstat64("z", {st_mode=S_IFLNK|0777, st_size=1, ...}) = 0
rename("z.new", "z") 
```

**Comment by elfet** [comment]
By the way, `deploy:release` can be not atomic, because it's only preparation stage. 
Atomic feature must be in `deploy:symlink`.

**Comment by elfet** [comment]
Done. Now, if it's possible, `deploy:symlink` will perform atomic switch.
