### ISSUE TITLE
Can be used deploy init to create the deploy.php file?

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#694]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 3.2 |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Question

Hello if you read the [Installation](http://deployer.org/docs/installation) and the [Getting started](http://deployer.org/docs/getting-started) pages you must create the deploy.php file by yourself

But there is an action "dep init" that create the file.

I don't know if the problem is that the documentation is old or dep init is  for another thing.

Thanks.

**Comment by oanhnn** [comment]
You can `dep init`.
Documents is not updated. Can you make a PR for document?

**Comment by oskarcalvo** [comment]
Hello oanhnn, I'm trying to undertstand the project to be able to make a good PR to update de documentation

**Comment by elfet** [comment]
@oskarcalvo it's will be cool :)
