### ISSUE TITLE
Not able to set timeout for run command

### ISSUE THREAD

**Issue by AlexKovalevych** [deployphp/deployer#697]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Would be nice to be able to manually set timeout for `run` (for the `Local.php` as well) similar to how its done for `runLocally`

**Comment by oanhnn** [comment]
This feature is implemented but it is out of date.
Can you make a PR?

**Comment by AlexKovalevych** [comment]
Yup, i'll work on it the next week
