### ISSUE TITLE
Allow to add callback to mustRun in Local server

### ISSUE THREAD

**Issue by AlexKovalevych** [deployphp/deployer#698]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Would be nice to allow to print command output immediately. (e.g. `mustRun` in `Local.php` allows to pass callback and print output while command is still running)

**Comment by elfet** [comment]
Done!
```php
task('test', "
    while :;
    do
    date;
    sleep 1;
    done
")->once();
```
