### ISSUE TITLE
Notice: SSH_AUTH_SOCK not found

### ISSUE THREAD

**Issue by fede91it** [deployphp/deployer#699]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Windows 10 x64
| Remote Machine OS | Linux serv01.esm1.siteground.biz 3.12.18-clouder0 #73 SMP Wed May 18 13:32:34 EEST 2016 x86_64

### Steps to reproduce
1. Run `dep current federicoliva`

### Content of `deploy.php`
```php
require 'recipe/symfony.php';

server('federicoliva', '77.104.141.222', 18765)
	->user('federic9')
    ->forwardAgent()
    ->stage('production')
    ->env('deploy_path', '~/public_html/deployer');
```

### Output log
```
➤ Executing task current
↳ on [federicoliva]
> cd ~/public_html/deployer && readlink ~/public_html/deployer/current

Notice: SSH_AUTH_SOCK not found in C:\Users\Federico\AppData\Roaming\Composer\vendor\phpseclib\phpseclib\phpseclib\System\SSH\Agent.php on line 130
```

What is wrong?

**Comment by oanhnn** [comment]
Can you check agent on your machine (Windows)?
I suggest you should use **git-bash** and run some commands before deploy.
```
$ eval `ssh-agent -s`
$ ssh-add /path/to/key
$ ssh-add -l
$ dep deploy prod -vvv
```

**Comment by fede91it** [comment]
At the command `ssh-add /path/tp/key` I get this output:

**Could not open a connection to your authentication agent.**

**Comment by oanhnn** [comment]
@fede91it 
Please run commands as my suggestion.
Your error is you haven't  authentication agent. And command
```
$ eval `ssh-agent -s`
```
to start a ssh agent. :smile:

**Comment by fede91it** [comment]
These special quotes... mmm... it works now :P

**Comment by oanhnn** [comment]
@fede91it 
Are you have any other question?

**Comment by fede91it** [comment]
No thanks, it works fine!
