### ISSUE TITLE
No compatible server to client encryption algorithms found

### ISSUE THREAD

**Issue by jmsche** [deployphp/deployer#7]
Got this error yesterday on my first try with deployer:

PHP Notice:  No compatible server to client encryption algorithms found in ...../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1127

I got it fixed by updating vendors and rebuilding PHAR archive.

Hope this can help :)

**Comment by ArjandeV** [comment]
@elfet I have the same issue, only I need to connect to my EC2 with a PEM file.. Any idea why it doesnt work?

**Comment by elfet** [comment]
Try to install ssh2 extension.
