### ISSUE TITLE
Problem reading Bitbucket private repository

### ISSUE THREAD

**Issue by glend** [deployphp/deployer#70]
I'm trying to deploy using a private Bitbucket repository. I've set Git access via SSH as instructed at Bitbucket https://confluence.atlassian.com/display/BITBUCKET/Set+up+SSH+for+Git

When I try to deploy it gives me:

```
[RuntimeException]                                   
Permission denied (publickey).                       
fatal: Could not read from remote repository.        
Please make sure you have the correct access rights  
and the repository exists.
```

Which means it connects succesfully to the server but it cannot access the remote repo. It's weird because I try to clone my repo manually and it works fine.

**Comment by timbofield** [comment]
I've got the same issue with a private bit bucket repo. Are SSH keys not being forwarded ?  This works fine with Capistrano.

**Comment by oanhnn** [comment]
I have same problem and my solution is `forward agent` feature. Please try it.
```php
server('dev-server', '192.168.1.2', 22)
    ->user('dev')
    ->forwardAgent()
    ->stage(['dev'])
    ->env('deploy_path', '/var/www/apps/dev')
    ->env('branch', 'develop')
;
```
And config your system support forward agent feature.

**Comment by willmcl** [comment]
I am having the same issue with bitbucket keys. I can run the git clone command that is run by deploy:update_code exactly when done manually. Anyone find any solutions?

**Comment by oanhnn** [comment]
Dear @willmcl,
Please show you native command on shell and error on using `deployer`.
