### ISSUE TITLE
deployer.org lacks an SSL certificate

### ISSUE THREAD

**Issue by iandunn** [deployphp/deployer#700]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Downloads of Deployer are hosted on deployed.org, but the site doesn't have an SSL certificate, making the downloads vulnerable to man-in-the-middle attacks, etc. That makes me leery of incorporating it into my projects.

Even a free certificate from [Let's Encrypt](https://letsencrypt.org/) or [StartSSL](https://startssl.com/) would be enough to verify the site's identity.

An alternative idea would be to [distribute releases via GitHub](https://help.github.com/articles/distributing-large-binaries/).

**Comment by iandunn** [comment]
Here's some additional discussions of best practices:

* http://www.phpdeveloper.org/news/22445
* http://fabien.potencier.org/article/73/signing-project-releases

**Comment by elfet** [comment]
Hi all! 🔥

[![2016-10-22 14 23 31](https://cloud.githubusercontent.com/assets/141232/19617768/622d7238-9863-11e6-870a-85ccbf2004c5.png)](https://www.ssllabs.com/ssltest/analyze.html?d=deployer.org)

Deployer now with **https** support! ❤️
