### ISSUE TITLE
Add timer to know how long the deployment took

### ISSUE THREAD

**Issue by geoffrey-brier** [deployphp/deployer#705]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question/Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Hi!

I'd like to know if I could implement some kind of timer to know how long the deployment took so that I can later include it in a slack notification.

If you're up for it, I'd like to have your opinion about how to do so. I was thinking about updating some tasks (from recipes/common.php) and adding new variables so that they can be accessed anywhere. Or maybe I could add new tasks to start/end a timer? I'm all ears :)

**Comment by oanhnn** [comment]
What do you think about 
```
➤ Executing task deploy:start
↳ on [test-svr]
> cd ~ && if [ ! -d /app/source ]; then mkdir -p /app/source; fi
• done on [test-svr]
✔ Ok [3s 824ms]
➤ Executing task deploy:prepare
↳ on [test-svr]
> echo $0
< bash
< 
> if [ ! -d /app/source ]; then mkdir -p /app/source; fi
> if [ ! -L /app/source/current ] && [ -d /app/source/current ]; then echo true; fi
> cd /app/source && if [ ! -d releases ]; then mkdir releases; fi
> cd /app/source && if [ ! -d shared ]; then mkdir shared; fi
• done on [test-svr]
✔ Ok [6s 483ms]
➤ Executing task deploy:release
↳ on [test-svr]
> if [ -d /app/source/releases/20160614010641 ]; then echo 'true'; fi
> mkdir /app/source/releases/20160614010641
> cd /app/source && if [ -h release ]; then rm release; fi
> ln -s /app/source/releases/20160614010641 /app/source/release
• done on [test-svr]
✔ Ok [2s 773ms]
```

Please try run with `-vvv` option and see output.

**Comment by geoffrey-brier** [comment]
@oanhnn Yes I saw the output with the `-vvv` option. Sadly you don't have access to the `Informer` in your tasks so you cannot get access to any timing information. On top of that there are no mechanism to get the overall deployment time.

Do you see what I mean?

**Comment by elfet** [comment]
In task?

**Comment by geoffrey-brier** [comment]
@elfet Yes

**Comment by elfet** [comment]
Use php.

**Comment by geoffrey-brier** [comment]
@elfet So you don't want the feature in deployer?

**Comment by elfet** [comment]
We cann’t  add all feature to deployer. In that case it’s really simple to implement it yourself.

**Comment by geoffrey-brier** [comment]
I understand, I'll close the issue then.
