### ISSUE TITLE
Is it possible to clone repository from https?

### ISSUE THREAD

**Issue by alexdevid** [deployphp/deployer#706]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.2
| Local Machine OS  | Any
| Remote Machine OS | Any

### Description 
Is it possible to clone repository from https?
If so, how to do this? I have to set password somewhere.

### Content of `deploy.php`
```php
<?php
require __DIR__ . '/vendor/deployer/deployer/recipe/symfony.php';

server('prod', 'example.com')
    ->user('user')
    ->password('password')
    ->env('deploy_path', '/path/to/deploy/dir/')
    ->stage('production');
set('repository', 'https://username@bitbucket.org/team/repo.git');
```

**Comment by oanhnn** [comment]
@alexdevid 
You can try:
```
git clone https://username:password@bitbucket.org/team/repo.git
```
But it is bad ideal :-1:
