### ISSUE TITLE
Max parallel child execution

### ISSUE THREAD

**Issue by TheRatG** [deployphp/deployer#708]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 3.3.0 |
| Local Machine OS | Linux homestead 3.19.0-25-generic #26~14.04.1-Ubuntu |
| Remote Machine OS | SMP Debian 3.2.60 |
### Description
- How to limit parallel execution child? I have to deploy some project on 12 instances, and faced with error like this *_Exception [RuntimeException] on [test.es] server Unable to login with the provided credentials. *_ from time to time during deploy process.
- Why **-p** option calls **tests**
### Steps to reproduce

Create big server list.
### Output log

```
Options:
  -p, --parallel         Run tests in parallel.
```

**Comment by elfet** [comment]
> Run tests in parallel.

A bug. :)

> Exception [RuntimeException] on [test.es] server Unable to login with the provided credentials

Is about problems with login.

**Comment by TheRatG** [comment]
>Is about problems with login.
But some remote operation work correctly, problem with login happened from time to time.
>How to limit parallel execution child?
There is no limit parameter?

**Comment by elfet** [comment]
Now you cannot limit. But it's good thing to have. We need some one who can implement it.

**Comment by elfet** [comment]
> Run tests in parallel.

Fixed.

I'm going to implement another option `--limit` for batching.
