### ISSUE TITLE
Connection works but hangs on first command with no errors

### ISSUE THREAD

**Issue by mrchimp** [deployphp/deployer#710]
| Q | A |
| --- | --- |
| Issue Type | Bug / Question |
| Deployer Version | 3.3.0 |
| Local Machine OS | Ubuntu 16.04 |
| Remote Machine OS | Debian 8.4 |
### Description

Commands don't appear to be running on the remote machine. Watching auth.log on the machine shows that Deployer _is_ connecting successfully but it hangs on the first command.

I'm aware that this could be a configuration issue but as far as I can tell the connection is good and as there is no further output or logs I'm finding it really hard to debug. I've used deployer on other machines/servers with basically the same configuration and had no issues. Hoping you can give me some pointers.
### Steps to reproduce

Use the deploy.php below and run `dep test prod -vvv`.
### Content of `deploy.php`

``` php
require 'recipe/laravel.php';

serverList('./servers.yml');

set('repository', 'https://github.com/mrchimp/chimpcom.git');

task('test', function() {
    run('mkdir /var/www/html/test');
    run('ls');
});
```
### Output log

```
➤ Executing task test
↳ on [prod]
> cd /var/www/html/website && mkdir /var/www/html/website/test
^C
```
### auth.log output

```
Jun 16 20:32:00 myhost sshd[22257]: Accepted publickey for mrchimp from x.x.x.x port 52971 ssh2: RSA xxxxxxxxxxxxxxxxxxxxxxxxx
Jun 16 20:32:00 myhost sshd[22257]: pam_unix(sshd:session): session opened for user mrchimp by (uid=0)
Jun 16 20:32:00 myhost systemd-logind[3176]: New session 420 of user mrchimp.
Jun 16 20:32:01 myhost sshd[22257]: pam_unix(sshd:session): session closed for user mrchimp
Jun 16 20:32:01 myhost systemd-logind[3176]: Removed session 420.
```

**Comment by oanhnn** [comment]
Is directory `/var/www/html/website` existed ?

**Comment by mrchimp** [comment]
Yes, it exists.

If I remove the `mkdir` command and only have the `ls` command, I get the same result.

**Comment by oanhnn** [comment]
I think error by directory `/var/www/html/website` not exist, and command `cd` failure.

**Comment by mrchimp** [comment]
It does exist. `ls` (without the `cd`) fails, too.
