### ISSUE TITLE
Ask for SSH key password only once for all servers

### ISSUE THREAD

**Issue by patrickreck** [deployphp/deployer#711]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | OSX
| Remote Machine OS | Windows

### Description 
I have a bunch of production servers which I am deploying to. However, I currently have to write the password for my SHH key once for every server, even though it's the same for every one of them. I would like to only write this once, but `askHiddenResponse()` is not available before declaring the servers.

How can I ask for the password just once?

### Content of `deploy.php`
```php
server('production1', 'x.x.x.x')
    ->user('deploy')
    ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', null)
    ->stage('production')
    ->env('deploy_path', 'C:/www');

server('production2', 'x.x.x.x')
    ->user('deploy')
    ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', null)
    ->stage('production')
    ->env('deploy_path', 'C:/www');
```

**Comment by oanhnn** [comment]
Currently Deployer don't support, but it can support in future.
I suggest using forward agent. You can add key only once and Deployer will authenticate with all server by forward agent.

**Comment by spidgorny** [comment]
Example:

> $ ssh-agent bash
> $ ssh-add ~/.ssh/aws.pem
Enter passphrase for ~/.ssh/aws.pem: ****
Identity added: ~/.ssh/aws.pem
> $ depp deploy

It will not ask for password anymore.
