### ISSUE TITLE
Magento2 Recepipe

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#713]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |

There is a Magento1 recipe, should we start working on Magento2?
- Works with Composer
- uses bin/magento binary file for commands
- needs to share files/folders

Flush cache

``` php
task('magento:cache:flush', function () {
    $output = run('{{bin/php}} {{deploy_path}}/current/bin/magento cache:flush');
    writeln('<info>' . $output . '</info>');
})->desc('Flush cache');
```

Generate static content

``` php
task('magento:static-content', function () {
    $output = run('{{bin/php}} {{deploy_path}}/current/bin/magento setup:static-content:deploy nl_NL');
    writeln('<info>' . $output . '</info>');
})->desc('Clear cache');
```

Needs a first-time install script, that copies the env.php/config.php? How do you usually handle that?

``` php
task('install', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'magento:install',
]);

env('magento_install_options',
'--db-host=localhost --db-name=magento --db-user=magento ' .
'--admin-firstname=Magento --admin-lastname=User --admin-email=admin@example.com ' .
'--admin-user=admin --admin-password=admin123 --language=nl_NL '.
'--currency=EUR --timezone=Europe/Amsterdam --cleanup-database '.
'--session-save=db --use-rewrites=1');

task('magento:install', function() {
    $confirm = askConfirmation('Are you sure? This will (re-)install Magento!');
    if (!$confirm) {
        writeln('<comment>Aborted</comment>');
        return 0;
    }
    $dbPass = ask('What is the DB password?','');
    $output = run('{{bin/php}} {{deploy_path}}/current/bin/magento setup:install --base-url=http://'.env('server.host').' --db-password="'. $dbPass.'" {{magento_install_options}}');
    writeln('<info>' . $output . '</info>');

  //Not sure what this should be exactly
   // run("cp {{release_path}}/app/etc/env.php {{deploy_path}}/shared/app/etc/env.php");
    // run("cp {{release_path}}/app/etc/config.php {{deploy_path}}/shared/app/etc/config.php");

});
```

Deploy

``` php
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'magento:static-content',
    'deploy:symlink',
    'deploy:writable',
    'cleanup',
    'magento:cache:flush',
]);
```

Other options:
- Enabe maintenance mode
- di:compile
- permissions
  .. ?

References:
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands.html
http://davidalger.com/development/magento/deploying-magento-2-using-capistrano/
https://github.com/davidalger/capistrano-magento2

**Comment by barryvdh** [comment]
This gives a good example of when to run commands:
https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/deploy.rake

And how the commands are run (Capinstrano/Ruby, but point should be clear)
https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake

**Comment by HOSTED-POWER** [comment]
Hi

Is there something working available already somewhere? Would interest me to test out :)

**Comment by elfet** [comment]
Can anybody create PR for Magento2?

**Comment by HOSTED-POWER** [comment]
Any update? Would be great to know :)

**Comment by elfet** [comment]
There is pending changes. You can fork pr and make this changes your self

**Comment by peterjaap** [comment]
I did a quick review @unailopez16 @barryvdh 

I don't think enabling all modules in the deployment recipe is a good idea - I might have a good reason (or a not so good reason) to disable an extension but still deploy the code.

Also, enabling/disabling maintenance mode during deployment isn't necessary when there is no database upgrade. I'd recommend moving this to an `askConfirmation` that defaults to true in silent mode.

You might also want to add an option to set a parameter in some config file for which theme and/or language to deploy the static content for. You're now deploying ALL static content, which takes a considerable amount of time for M2. When we're building a Dutch shop, I don't need to deploy other languages, so adding `nl_NL` to the static content deploy command considerably speeds things up. This goes for `--theme` as well.

**Comment by peterjaap** [comment]
Can this also be re-opened @elfet ?

**Comment by elfet** [comment]
@peterjaap can you create a new PR with your vision of magento2 deploy process. I think you have more knowledge as you have certificates.  😀

**Comment by peterjaap** [comment]
Will do that as soon as we're actually deploying our M2 project :)

**Comment by elfet** [comment]
Now Deployer 4.1.0 with M2 recipe!
