### ISSUE TITLE
Deploy tag

### ISSUE THREAD

**Issue by RicardoJ** [deployphp/deployer#715]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 3.3.0 or above. Possible at v4?
| Local Machine OS  | Darwin luna.local 15.4.0 Darwin Kernel Version 15.4.0
| Remote Machine OS | Linux apollo 4.4.0-24-generic 43-Ubuntu SMP

### Description 
When you are deploying you must have a option of generating a git tag in the repository with the current release name so you can easy track your latest deployment in your git environment.

**Comment by oanhnn** [comment]
@RicardoJ I think you should make a custom task for this feature.
Becasue, sometime, deployers want deploy a develop version for test of build CI. They will have many tag version is created by Deployer.

What are you thing if we will log deploy versions in to a file?

**Comment by RicardoJ** [comment]
After reading your motivation, I agree to the situation other deployers may have with CI. Thank you for the information.

√

**Comment by oanhnn** [comment]
@RicardoJ 
I see you implemented feature using deployer.lock file.
What are you thing if we will log deploy versions in to a file? Can you help us this feature?

**Comment by RicardoJ** [comment]
Yes, I'll add it in a PR.

**Comment by fnagel** [comment]
Any idea where to find the PR? Was not able to find something.

I'm using something like this for my symfony apps:

````
task('deploy:create_git_tag', function () {
    $git = get('bin/git');
    $env = get('symfony_env');
    $host = get('hostname');
    $branch = get('branch', 'unknown');
    $date = new \DateTime();

    $tag = $env . '-' . $date->format('Ymd-His');
    $message = 'Deployed branch ' . $branch . ' to ' . $env . ' environment on ' . $host;

    cd('{{release_path}}');

    run("$git config user.name 'Deployer'");
    run("$git config user.email 'git@deployer.vm'");
    run("$git tag -a $tag -m '" . $message . "' --force");
    run("$git push origin $tag --force");
})->desc('Create release tag');
````
