### ISSUE TITLE
Deploy from local git repo?

### ISSUE THREAD

**Issue by clytemnestra** [deployphp/deployer#716]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

I'm trying to deploy from a local git repo but I'm getting an error. Cloning from the project works just fine if I do it in another folder, `/home/user/project` is my git repo. I thought it could be a permission thing but I changed the owner to the user and gave 777, but still running in the error.
### Content of `deploy.php`

``` php
<?php

require 'recipe/symfony3.php';

// Set configurations
set('repository', "file:///home/user/project");
set('shared_files', ['app/config/parameters.yml']);
set('shared_dirs', ['app/logs']);
set('writable_dirs', ['app/cache', 'app/logs']);

// Configure servers
server('production', 'xxx.xxx.xxx.xxx')
    ->user('deploy')
    ->identityFile('/root/.ssh/id_rsa.pub','/root/.ssh/id_rsa','passphrase')
    ->env('deploy_path', '/var/www/html/project');

```
### Output log

I'm getting

```
  fatal: '/home/user/project' does not appear to be a git repository
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.
```

Does it need to be at public address? Can't I deploy from a local git repo?

**Comment by edbizarro** [comment]
set the repository env without de "file:///" part maybe?

**Comment by clytemnestra** [comment]
That won't work.

```
 [RuntimeException]
  fatal: repository 'home/user/project' does not exist
```

/home/user/project, /home/user/project/, /home/user/project/.git won't work either.

**Comment by x3ro** [comment]
@clytemnestra Is it possible that you missed one slash? I successfully deployed from a local repository using this:

    set('repository', 'file://' . getcwd() . '/test/repositories/submodules-test/.git');

**Comment by clytemnestra** [comment]
Pretty sure I had three slashes and it still didn't work.

**Comment by x3ro** [comment]
The error message you posted suggests otherwise :D

**Comment by clytemnestra** [comment]
I said in the first example the contents of `deploy.php` which include `file:///home/user/project`. That's a copy-paste.

**Comment by clytemnestra** [comment]
What's the reason for closing this if the issue is not solved?

**Comment by elfet** [comment]
I think this issue not related to deployer, as @x3ro successfully useв local repo.

**Comment by clytemnestra** [comment]
Yes, but I'm not sure about the properties of that repo. If there is something wrong that I'm doing I want to know what.

**Comment by x3ro** [comment]
If you're trying to deploy from a local repository, afaik you need to either have a bare repository or point deployer to the `.git` directory of your cloned repo (see above in my example).

**Comment by clytemnestra** [comment]
I tried all the possible combinations with and without file:///, adding slashes and .git at the end, nothing seemed to work. If I do it with a Github repo it works, but not with a local one.

**Comment by elfet** [comment]
What git command you are trying to run?

**Comment by clytemnestra** [comment]
Not running any git command, I'm running ``dep deploy``

**Comment by elfet** [comment]
Run command with `-vvv` option. Show full output.

**Comment by migueldemoura** [comment]
According to #578, you can't really do this easily :disappointed: .

Deployer is executed in the VPS, so the file:// approach will never work unless you add a custom task with `before(...)`, updating your git repo in the VPS itself. That way, you can use `set('repository', "file:///path/to/repo/in/vpn");` afterwards.

I just ended up moving the project to a private github repo.

**Comment by x3ro** [comment]
Hmm, my apologies to @clytemnestra. I believe I implied something that was true for me, but doesn't really make sense for most other people: I'm deploying __from__ the local machine, __to__ the local machine. 

Indeed, explained in #578, this is otherwise not easily possible. @elfet Would it make sense to check whether people use `file://` as the `repository`, and print a warning if they do?

**Comment by elfet** [comment]
Yes, i think warning is ok.

**Comment by clytemnestra** [comment]
Ah, from local to local was working for me, too.

**Comment by emobin** [comment]
your git command run on your remote servers, as your repository in your local system your remote server can not find your local system on the NET and this cause the problem. you need to use an online Repo or bring your system online to use your local repository. Even though its working on local 2 local because they see each other.
