### ISSUE TITLE
Fix Symfony recipe follow change of asset bundle

### ISSUE THREAD

**Issue by oanhnn** [deployphp/deployer#720]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

> Starting from Symfony 2.8, Assetic is no longer included by default in the Symfony Standard
> Edition. Refer to this article to learn how to install and enable Assetic in your Symfony application.

https://symfony.com/doc/current/cookbook/assetic/index.html
https://symfony.com/doc/current/cookbook/assetic/asset_management.html

**Comment by robfrawley** [comment]
Fixed in #688 already.
