### ISSUE TITLE
Is PATH from server not honored?

### ISSUE THREAD

**Issue by alomvar** [deployphp/deployer#722]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | OS X 10.11.5 (El Capitan)
| Remote Machine OS | GNU/Linux Debian 7 (Wheezy)

Multiple PHP versions are installed on the remote machine (on which I do not have root access to). The default (`/usr/bin/php`) is 5.4 which is provided by Debian. There are others, in example PHP 7 installed in `/usr/local/php70`.

To make PHP 7 the default in shell when logging in via SSH I created `.profile` and `.bash_profile` scripts which get executed on log in. Prepending `PATH` with `/usr/local/php70/bin` (complete shell script line: `PATH="/usr/local/php70/bin:$PATH"`) makes the PHP 7 binaries the default, as expected.

```
$ which php
/usr/local/php70/bin/php
```

I am using that exact same user for deployer. It appears that either the log in scripts are not executed or the `PATH` variable from the server side is ignored in that case. Executing the following task:

```
task('debug', function () {
    write(run('which php'));
    write(run('echo "$PATH"'));
    exit;
});
```

Results in:

```
➤ Executing task debug
/usr/bin/php
/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
$ 
```

I read in other issues about environment specific deployer configuration. But to me it appears more logical that different stages (testing, staging and production) should be as similar as possible and thus this is a target environment configuration issue. I still tried [overriding the binary](https://github.com/deployphp/deployer/blob/master/recipe/common.php#L51) via deployer environmental variable with:

```
env('bin/php', function () {
    return '/usr/local/php70/bin/php';
});
```

But sadly without success. How can I force Deployer to use a specific PHP binary on the server either by server side configuration or Deployer configuration?

**Comment by t33k** [comment]
Set env on stage level

`server('beta', 'x.x.x.x', 22)
    ->user('xxx')
    ->identityFile()
    ->stage('beta')
    ->env('bin/php', '/usr/local/bin/php5.6.6-cli')
`

I use it like that and its working.

**Comment by alomvar** [comment]
Thank you, that solved the problem.
