### ISSUE TITLE
Group Tasks don't respect onlyForStage() and onlyOn() settings

### ISSUE THREAD

**Issue by galoppi** [deployphp/deployer#723]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | master |
| Local Machine OS | Ubuntu 14.04 |
| Remote Machine OS | N/A |
### Description

If you define a group task and want to limit its execution to an explicit stage then the onlyForStage() setting doesn't have any effect and all subtasks are executed on each stage.
### Steps to reproduce

In the example below the task `send-team-message` is executed on each stage because it is
a group task that encapsulate the `deploy:slack` task. The `deploy:slack` itself doesn't have a onlyForStage() restriction.
The only workaround for this misbehaviour is to define the constraint for the subtask directly:

``` php
$deployer->tasks->get('deploy:slack')->onlyForStage(['stage']);
```
### Content of `deploy.php`

``` php
task('send-team-message',[
   'deploy:slack'])->onlyForStage('production');

task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'rsync:warmup',
    'rsync',
    'deploy:vendors',
    'deploy:shared',
    'compare_database',
    'clear_cache',
    'create_news',
    'deploy:symlink',
    'cleanup',
    'send-team-message'
])->desc('Deploying Project');
```

**Comment by tralafiti** [comment]
👍  Yeah, would love to see this changed / fixed, too

**Comment by elfet** [comment]
But what to do in this situation?

```php
task('send-team-message', [
   'deploy:slack'])->onlyForStage('production');

task('send-another-message', [
   'deploy:slack'])->onlyForStage('beta');

task('deploy', [
    'send-team-message',
    'send-another-message'
])->desc('Deploying Project');
```

**Comment by elfet** [comment]
Try to fix it in 4.x release.

**Comment by tralafiti** [comment]
In your example I would expect that `deploy:slack` is run on
* `beta` - via `send-team-message` group-task - when I trigger `deploy beta`
* and `production` - via `send-another-message` group-task - when I trigger `deploy production`

---
Also higher level definitions should overwrite lower ones. So in the case of
```
task('send-team-message', [
   'deploy:slack'])->onlyForStage('production');

task('deploy', [
    'send-team-message',
])->onlyForStage('beta')->desc('Deploying Project');
```
`beta` would overwrite `production`. Or what do you think?

**Comment by elfet** [comment]
I think we can use some sort of lazy algorithm.
```
deploy (filter: beta)
|_ send-team-message (filter: production)
   |_ deploy:slack (no filter)
```
In this case `deploy:slack` will never be executed.

**Comment by elfet** [comment]
It was difficult, but i made it!

![minimercury](https://cloud.githubusercontent.com/assets/141232/20236606/02bfd1e8-a8ed-11e6-9d27-b86d5421a314.jpg)
