### ISSUE TITLE
Deployer used in offline deploymeny

### ISSUE THREAD

**Issue by ely029** [deployphp/deployer#724]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question,
| Deployer Version  | N/A
| Local Machine OS  | Windows 7
| Remote Machine OS | Ubuntu 16.04 LTS

I am start studying the Deployer. My question is the deployer can use for offline deployment. I have a yii framework developed from windows and deployed to the ubuntu 16.04 LTS

**Comment by oanhnn** [comment]
You can found document from hhtps://deployer.org
Or getting start with steps:

1. Install Deployer
2. Make a deploy.php and require recipe for Yii framework
3. Change server config to correct with your enviroment
4. Run deploy command 

Any question, you can post here or http://deployer.org/discuss
Goodluck!
