### ISSUE TITLE
git archive rather than clone

### ISSUE THREAD

**Issue by talisman-innovations** [deployphp/deployer#729]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 3.3 |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

I've moved a number of my projects over to deployer recently and been very happy with how it works and the ease of migrating my projects.  One thing I've noticed though is that the size of the releases on the destination server has increased significantly compared to my previous deployment approach.  Taking a closer look I see that the main difference is that deployer uses git clone and my previous release script, which was hand crafted, used git archive.  Even though deployer uses a shallow clone, in my repo at least there's a lot of additional branch information that I don't need (or want really) deployed to the server running the application.

Before I recode the update_code step for my local deploy.php script, was there any specific reason to use clone rather than archive for the update_code step?  If not would you like a revised version of update_code using git archive?

Thanks and keep up the deploying!

Steve

**Comment by rlacerda83** [comment]
+1

**Comment by elfet** [comment]
What is pros and cons of archive vs clone? shallow clone is really fast, also allowing you to easy switch branches on staging servers for testing.

**Comment by talisman-innovations** [comment]
Well for the repo that I'm dealing with there is a size difference between a shallow clone and an archive.  360MB for the archive and 522MB for the clone.  This is then multiplied by the number of old versions that are kept.  For my deployments I never need to switch branches on the deployed systems so I don' get any advantage from the extra space.  

This particular repo is likely to have ever more branches and projects in it, so this gap will grow over time, leading to wasted space and possible slower deployments - although git archive isn't' super fast itself.

**Comment by elfet** [comment]
But deployer use `--depth 0` option. So size of archive and clone should be same. 

If you want using git archive simple override deploy:update_code recipe.

**Comment by talisman-innovations** [comment]
It seems to use --depth 1 based on my inspection of the code.  --depth 0 also seems to give an error from git.  

You are right I can override the deploy function so I'll give that a try and see if it improves things for me.  Thanks for the response.

**Comment by elfet** [comment]
--depth 1 is correct

**Comment by thiagolcks** [comment]
Hi, guys! An advantage of using `git archive` is that we can ignore some files and folders that shouldn't be on the production server (like tests) using *export-ignore* in the *.gitattributes* file. Thus the code could be smaller than using `git clone`.

The OWASP Quick Reference Guide says: "Remove test code or any functionality not intended for production, prior to deployment." Having `git archive` would solve this issue.

**Comment by antonmedv** [comment]
@thiagolcks that's try. You can do it simply as:
```js
task('deploy:update_code', function () {
    run('git archive --format=tar {{branch}} | (cd {{release_path}} && tar xf -)');
});
```

**Comment by thiagolcks** [comment]
thanks @antonmedv

**Comment by talisman-innovations** [comment]
My thanks too  @antonmedv.  Reduces the footprint per release from 650MB to 250MB on one of our systems.

**Comment by frakman1** [comment]
Are you sure you're not getting the footprint savings from the `tar` command and not the `git archive` command?

`git archive` has some advantages but I am not sure you are using them. `git clone` has a shallow option using `--depth 1` and also lets you include a single branch using `--single-branch`. The example above doesn't seem to use the files ignore feature.

The true value of using `git archive` is  when using it to get a single **folder** within the project. See example below:

```bash
git archive --remote=git@gitlab.com:<group>/<project>.git  <branch>:<folder>/ | tar xvf -
```

Note that in this example, `git archive` is not being used for packaging a release but rather to download and use some files locally.

**Comment by garak** [comment]
@frakman1 the value of using archive is that you can easily exclude every development-only file, just by using a `.gitattributes` file.
The only downside I can see is that you can't use it with an http/https repository.

In such case, you can replace suggested solution with this one:

```php
task('deploy:update_code', static function (): void {
    run('rm -rf tmp_repo && (git clone {{repository}} tmp_repo && cd tmp_repo && git archive --format=tar {{branch}}) | (cd {{release_path}} && tar xf -)');
});
```

**Comment by andyexeter** [comment]
Capistrano creates a `repo` directory within the deploy path which is a mirrored clone of the repo and uses `git archive` off of this to create releases. 

I've ported the method over to Deployer and there are a few benefits of this approach over performing a `git clone` for every release (even with caching enabled):

* Faster (The default `update_code` method takes 9s 294ms in my test repo, and 1s 769ms using `git archive` - this is a huge win. (the first deploy takes a while longer as it has to create the mirror)
* Less space used on disk. Currently every release contains a .git directory. Using this approach, there's only ever one clone
* More secure. Keeping .git directories outside of releases is considered good practice

This is the `update_code` task I have been testing with:

```
desc('Update code');
task('deploy:update_code', function () {
    $repository = get('repository');
    $branch = get('branch');
    $git = get('bin/git');
    $options = [
        'tty' => get('git_tty', false),
    ];

    $at = '';
    if (!empty($branch)) {
        $at = $branch;
    }

    // If option `tag` is set
    if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
        if (!empty($tag)) {
            $at = $tag;
        }
    }

    // If option `tag` is not set and option `revision` is set
    if (empty($tag) && input()->hasOption('revision')) {
        $revision = input()->getOption('revision');
    }

    if (!test('[ -d {{deploy_path}}/repo ]')) {
        run('mkdir -p {{deploy_path}}/repo');
    }

    if (!test('[ -f {{deploy_path}}/repo/HEAD ]')) {
        run("$git clone --mirror $repository {{deploy_path}}/repo 2>&1", $options);
    }

    run("cd {{deploy_path}}/repo && $git remote update 2>&1", $options);

    run("cd {{deploy_path}}/repo && $git archive $at | tar -x -f - -C {{release_path}} 2>&1", $options);

    if (!empty($revision)) {
        run("cd {{release_path}} && $git checkout $revision");
    }
});
```

@antonmedv is this something you'd consider a PR for?

**Comment by antonmedv** [comment]
Yes, maybe. Currently method git clone uses only one last commit, borrows  files from previous deployment, supports branches, tags, hashes. Let’s try to switch to archive and compare speed.

**Comment by antonmedv** [comment]
Well, looks like git archive has more restrictions, for example, you can not do this:
```
$ git archive --format=tar --remote=git@github.com:deployphp/deployer.git master)
Invalid command: 'git-upload-archive 'deployphp/deployer.git''
You appear to be using ssh to clone a git:// URL.
Make sure your core.gitProxy config option and the
GIT_PROXY_COMMAND environment variable are NOT set.
fatal: the remote end hung up unexpectedly
```

Let's leave git clone for now and write a better doc on how to switch to other methods. This is really simple.

**Comment by andyexeter** [comment]
`git archive --remote` uses a  remote repo to create the archive - what was the reason for trying this? The `update_code` task in my [previous comment](https://github.com/deployphp/deployer/issues/729#issuecomment-779977028) uses a local bare repo which is cloned once on the first deploy and which `git archive` is called on to create releases.

Essentially, it can be boiled down to the following:

1) If `{{deploy_path}}/repo` directory does not exist, create it
2) If `{{deploy_path}}/repo/HEAD` file does not exist, clone bare repo (with `git clone --mirror`)
3) Fetch updates with `git remote update`
4) Use `git archive` on the bare repo within {{deploy_path}}/repo to create the release in `{{release_path}}`

Steps 1 and 2 will usually only be run on the first deploy. Subsequent deploys will only need to run steps 3 and 4 and this is where the speed improvement comes into play.

**Comment by antonmedv** [comment]
I see. Let’s try to implement this and see if there is some speed improvements.

**Comment by antonmedv** [comment]
A few questions: what is the HEAD file is? How to deploy branch, tag and a revision in this case?

**Comment by andyexeter** [comment]
HEAD is just a file which always exists in a repo. Its only significance in this method is a way of finding out whether the repo has been cloned or not yet.

I did add branches, tags and revisions support to my method. I will paste it again here:

```
desc('Update code');
task('deploy:update_code', function () {
    $repository = get('repository');
    $branch = get('branch');
    $git = get('bin/git');
    $options = [
        'tty' => get('git_tty', false),
    ];

    $at = '';
    if (!empty($branch)) {
        $at = $branch;
    }

    // If option `tag` is set
    if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
        if (!empty($tag)) {
            $at = $tag;
        }
    }

    // If option `tag` is not set and option `revision` is set
    if (empty($tag)) {
        $revision = input()->getOption('revision');
        if (!empty($revision)) {
            $at = $revision;
        }
    }

    if (!test('[ -d {{deploy_path}}/repo ]')) {
        run('mkdir -p {{deploy_path}}/repo');
    }

    if (!test('[ -f {{deploy_path}}/repo/HEAD ]')) {
        run("$git clone --mirror $repository {{deploy_path}}/repo 2>&1", $options);
    }

    cd('{{deploy_path}}/repo');

    run("$git remote update 2>&1", $options);

    run("$git archive $at | tar -x -f - -C {{release_path}} 2>&1", $options);
});
```

**Comment by antonmedv** [comment]
Done in https://github.com/deployphp/deployer/pull/2461 🎉

Wow, it was A LOONG time since this issue was created: `now - 29 Jul 2016 = 4 years, 7 months, 14 days ago`.
