### ISSUE TITLE
upload directory which is not under version control

### ISSUE THREAD

**Issue by lbausch** [deployphp/deployer#732]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Debian testing
| Remote Machine OS | Debian 8.5

### Description 
I'm trying to upload a directory via `upload()` which is not under version control because it's excluded via an entry in .gitignore.
Deployer uses `->ignoreVCS(true)` when finding files - can this be changed in any way?

**Comment by elfet** [comment]
http://api.symfony.com/2.3/Symfony/Component/Finder/Finder.html#method_ignoreVCS
Like `.git` dir.

**Comment by lbausch** [comment]
So do I have to implement my own upload() function?

**Comment by elfet** [comment]
If you want upload `.git` forlder - yes. But it's easy, because you can take and upload function as example.

**Comment by lbausch** [comment]
Alright - thanks! :)
