### ISSUE TITLE
Symfony recipe on multiple environments

### ISSUE THREAD

**Issue by hoffereka** [deployphp/deployer#733]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Is it possible somehow to execute symfony recipe's tasks on multiple environments?
We have 3 envs (www_live, admin_live, api_live) and all of them needs cache warmup,
writable dirs, etc...

**Comment by oanhnn** [comment]
Please show more about your case?

**Comment by hoffereka** [comment]
What should I do, I cannot upload the whole project. We have an API, admin and a public site, with the same schema and entities, but for example different authentication system, different templates, different yml configs. We handled this situation that we created a couple of environments, web, api, admin, etc... and when we deploy our symfony project, we warmup all environments' cache, shared files, etc...

**Comment by oanhnn** [comment]
Are all your site included a symfony projects?
If true that, please do this flow:

### 1. make `deploy.php` file
```
require 'recipe/symfony.php'; // or symfony 3

// Your config for project

server('prod', '123.123.123.123', 22)
    ->user('deployer')
    ->forwardAgent()
    ->stage('www_live')
    ->env('deploy_path', '/path/to/deploy_path')
    ->env('env', 'www_live')
;

server('prod', '123.123.123.123', 22)
    ->user('deployer')
    ->forwardAgent()
    ->stage('admin_live')
    ->env('deploy_path', '/path/to/deploy_path')
    ->env('env', 'admin_live')
;

server('prod', '123.123.123.123', 22)
    ->user('deployer')
    ->forwardAgent()
    ->stage('api_live')
    ->env('deploy_path', '/path/to/deploy_path')
    ->env('env', 'api_live')
;
```
### 2. Run deploy
```
$ dep deploy www_live
$ deploy:assetic:dump admin_live
$ dep deploy:cache:warmup admin_live
$ dep database:migrate admin_live
$ deploy:assetic:dump api_live
$ dep deploy:cache:warmup api_live
$ dep database:migrate api_live
```

> ### There may be some difference with your actual project

**Comment by hoffereka** [comment]
Good idea, thanks!
