### ISSUE TITLE
deployer in CI-process with jenkins

### ISSUE THREAD

**Issue by kitingChris** [deployphp/deployer#735]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I want to include deployer directly in my CI process. 

I want it to be triggered by jenkins and also want to get every output returned for surveillance purpose.

I realized the only suitable output that I may get is with Verbosity Level Debug.
This is because I want to use QA tools like lint, phpcs, phpunit and so on but with them executed locally the output is always either error (see other issue #734 ) or hidden without setting verbosity level to max.

So my question: HOW should I use deployer within a CI process?

**Comment by oanhnn** [comment]
Two ways for implement your case:

## One
Setting up CI run QA tools before run Deployer.
Travis script (Sorry, i not use jenkins). 
```
language: php

php:
- 5.5
- 5.6
- 7.0
- hhvm

sudo: false

addons:
  mariadb: '10.1'

before_install:
- composer self-update

install:
- composer install
- composer require satooshi/php-coveralls '~1.0'
- composer require deployer/deployer

before_script:
- composer run-script post-create-project-cmd
- mysql -u root -e 'CREATE DATABASE IF NOT EXISTS testdb;'

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
- php vender/bin/dep deploy staging -vvv

```
## Two
Run  deploy to Deployer before QA tools
Travis script. 
```
language: php

php:
- 5.5
- 5.6
- 7.0
- hhvm

sudo: false

addons:
  mariadb: '10.1'

before_install:
- composer self-update

install:
- composer install
- composer require deployer/deployer

script:
- php vender/bin/dep deploy staging -vvv

after_script:
- php vender/bin/dep qa_test staging -vvv
```

With way 2, you need make `qa_test` task.
```
task('qa_test', function () {
    within('{{deploy_path}}/current', function() {
        run('php vendor/bin/phpcs');
        run('php vendor/bin/phpunit');
    });
});
```

## Your error
About your error #734 , It is your command not return code equal 0 (QA tool check has error, fail, ...).
I think it isn't bug of Deployer.

**Comment by kitingChris** [comment]
Maybe not a bug indeed. But would be great if deployer could give some options to handle those in a better way. 
I would propose a more specific exception that could be catched and handled instead of a runtime exception :)

**Comment by oanhnn** [comment]
"Why not return code 0 when error?"
I think you ask author of **phpunit** or **phpcs** , ... or fix your code to pass all test.
With me, i run **phpunit** and **phpcs** on locally and only deploy when it pass all test.
So that, i not has exception like you.
