### ISSUE TITLE
Добавить метод ~writable~ для одного файла

### ISSUE THREAD

**Issue by tebaly** [deployphp/deployer#736]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | 3
| Local Machine OS  | linux
| Remote Machine OS | linux

Может есть смысл добавить метод типа `writable($fileName)` для одного файла (recipe/common.php)? Сейчас при деплое единичный файл лога не имеет прав на запись от www-data

**Comment by tebaly** [comment]
Возможно что типа такого

`````
task('deploy:writable', function() {
    $httpUser = get('http_user');
    $files = join(' ', get('writable_files'));
    cd('{{release_path}}');
    run("chown $httpUser $files");
});
`````

Применение
`````
set('writable_files', [
    'path/to/file'
]);
`````

**Comment by oanhnn** [comment]
A lot of frameworks, writable directories is shared between `http_user` and `cli_user`.
I think `chown` like your PR will has problems with `cli_user`. Eg:
```
$ artisan cache:clear
```
