### ISSUE TITLE
Enh: Set color of output / remote output via deploy.php config.

### ISSUE THREAD

**Issue by davidjeddy** [deployphp/deployer#741]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | ^3.0
| Local Machine OS  | OSX
| Remote Machine OS | CentOS

### Description 
Setting output color via configuration, something along the lines of
```
set('output', '#FFFFFF');
set('output_highlight', '#FFFFFF');
set('output_alert', '#FFFFFF');
```
then for remote output
```
set('remote_output', '#FFFFFF');
set('remote_output_hightlight', '#FFFFFF');
set('remote_output_alert', '#FFFFFF');
```

The values used for coloring matter not; hex, predefined string, unicode colors, etc.

**Comment by elfet** [comment]
You can not set any hex color in console. We use **symfony/console** component for coloring.

**Comment by davidjeddy** [comment]
The hex color codes were examples; TTY color codes would be fine as well; even plain text would be ok.
