### ISSUE TITLE
Code completion for PHPStorm

### ISSUE THREAD

**Issue by greatwitenorth** [deployphp/deployer#742]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Is it possible to have code completion in PHPStorm for deployer when it's installed globally (not via composer)? Since the require path is relative to the phar being executed, right now PHPStorm can't find the content of `recipe/symfony.php`

**Comment by greatwitenorth** [comment]
I got this working by renaming ```/usr/local/bin/dep``` to ```/usr/local/bin/depployer.phar``` (since PHPStorm will only index files with .phar ending. I then made a symbolic link for convenience back to ```dep```

```
mv /usr/local/bin/dep /usr/local/bin/deployer.phar
ln -s /usr/local/bin/deployer.phar /usr/local/bin/dep
```

Then in PHPStorm I added ```/usr/local/bin``` to my include path under PHPStorm -> Preferences -> Language & Frameworks -> PHP

**Comment by elfet** [comment]
Nice solution! I think this must go to docs.

**Comment by greatwitenorth** [comment]
One thing that's not perfect about this method is that it still doesn't autocomplete the require path for ```recipe/symfony.php```. Not sure if there's a way to accomplish this in PHPStorm.

**Comment by elfet** [comment]
Done.
