### ISSUE TITLE
running multiple tasks

### ISSUE THREAD

**Issue by kalvish21** [deployphp/deployer#744]
I know you can run multiple tasks by listing them all under one task. Is there a way to do it in command line? I like this feature as it allows us to run particular tasks for particular use cases (without always having to "group" them).

**Comment by elfet** [comment]
There no such functionality right now. All because of **dep** command structure:
```
dep [task] [server/stage] [user specified options, ...]
```

But i think we can add an extend point to 4.x branch to add this functionality.

**Comment by kalvish21** [comment]
How can I do the user specified options? I did not find that anywhere in tutorials.

**Comment by elfet** [comment]
Please, use group tasking.
