### ISSUE TITLE
Drop PHP 5.5 support.

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#745]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 4.x |
### Description

What about dropping PHP 5.5 support on deploy machine?
PHPUnit 5.4 does not support it anyway.

**Comment by t33k** [comment]
Ubuntu 14.04 LTS (up to 2019) will use php 5.5.
So if you are not going to use any special feature of php 5.6 then I would suggest to stay 5.5 compatibile as long as possible.

**Comment by sr972** [comment]
Against dropping the support for 5.5 by now. Reason like @t33k told, to many 14.04LTS machines :(

**Comment by elfet** [comment]
Okay, but what to do with phpunit then?

**Comment by oanhnn** [comment]
+1 for php5.5+

**Comment by rlacerda83** [comment]
If possible, keep the compatibility with PHP 5.5.
The version of phpunit compatible with PHP 5.5 does not satisfy you?

**Comment by davidjeddy** [comment]
To be reasonable, any language based library should support all version of the language being supported by the publishing body. In the case of PHP that means everything supported via http://php.net/. According the support pages 5.5 has reached EOL; even for security updates. 

This all is of course for 'active' and 'new' changes for deploy (or any library). If it works with 5.5, cool, but it should not be an active focus, it will just the contributors back.*

Ref: http://php.net/supported-versions.php

* All words here are opinion only and should be consumed as such.

**Comment by mablae** [comment]
I dont see an reason in keeping support for a version that has reached EOL like @davidjeddy points out.

**Comment by t33k** [comment]
Maybe better to start with question what special features of php 5.6 we want to use in Deployer 4 to drop support for php 5.5? If this will be only changing array() to [] and few other minor changes that brings nothing special then IMO better to keep as wide as possible.

**Comment by mablae** [comment]
@t33k Agree. These are new features in v5.6: http://php.net/manual/en/migration56.new-features.php

Short Array Notation was introduced in v5.4 already IMHO.

**Comment by davidjeddy** [comment]
@t33k for deployer v4 why not aim for PHP7.x, it's released and stable.

**Comment by t33k** [comment]
@davidjeddy 
If possible then we should aim also for php7 but it all depends on amount of work needed to support such wide set of php versions. I suppose the worse will be hell of third party libraries dependency.

After thinking - in the end if we drop php 5.5 in v4 I would not cry much becase there is always working v3 for php 5.5.

**Comment by oanhnn** [comment]
I think Deployer 4 should still support PHP 5.5 and require (dev mode only) PHPUnit ~4.8|~5.4

**Comment by elfet** [comment]
> ~4.8|~5.4

Use different api.

**Comment by elfet** [comment]
Or we can simple do not run tests on php 5.5 in CI.

**Comment by elfet** [comment]
Again, for php 5.5 there is Deployer v3, Deployer v4 can be for 5.6 and 7.

**Comment by elfet** [comment]
php.net: Current Stable PHP 5.6.24

http://php.net/supported-versions.php

So php do not support it any more. So can do we too.

But you will be able to run on php 5.5, only difference no php5.5 in travis-ci.

**Comment by oanhnn** [comment]
I think travis-ci should care all cases.
So that, I am agree with ideal "php 5.5 there is Deployer v3, Deployer v4 can be for 5.6 and 7."

**Comment by elfet** [comment]
👍🏻

**Comment by davidjeddy** [comment]
This conversation leads me to believe deployer needs a support roadmap. IE how long will each major version be support, how long are `critical` issues resolved after that, then when is the major version dropped. Then co-ordinate the supported major/minor version of PHP that fall within it. Love it or hate it Ubuntu has a very simple to understand way of dealing with this exact issue. OR assign a deployer major/minor version to each major/minor of php. That way deployer could be tied in with composer for version constraining.

deployer v3 => php 5.x
deployer >=v4.5 => php >=7.5
deployer v5 => php 8.x


As for testing: Every commit, every branch, every option, every time.
