### ISSUE TITLE
Integrate recipes repository in main master

### ISSUE THREAD

**Issue by mablae** [deployphp/deployer#746]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | 3 |
| Local Machine OS | Linux |
| Remote Machine OS | Linux |

I dont understand why there is this external `recipes` repository. I think all possible integrations should be available in main tool without any extra effort. This should also include the phar. 

What is the reason to keep "some" recipes out of the main tool, where as others are included by default? 

Makes no sense.

**Comment by mablae** [comment]
Has anyone an opionion on this? Maybe I am just overlooking the benefits this separation brings?

**Comment by elfet** [comment]
Hi,

I was created to speed up development. Two different maintainers work on separate projects. 
Now as you can see a lot of recipes for popular projects already bundled with deployer.

**Comment by oanhnn** [comment]
@mablae In `recipes ` repository, it can require some packages, tool but `deployer` not require. If two repository are merged, `Deployer` will be complex and bulky.

**Comment by barryvdh** [comment]
It would be useful it the recipes were included by default, so we don't have to require a package in the main composer.json. So perhaps require the recipes from inside the main repo and make them available for usage with the CLI, but keep development seperate?

**Comment by antonmedv** [comment]
I was thinking completely in other way: separate recipes. So you will get only stuff you need.
