### ISSUE TITLE
Error callback function

### ISSUE THREAD

**Issue by silence44** [deployphp/deployer#747]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

_Sometimes during deploy I got errors. I would like to send to slack that smth is broken and need to be fixed. So I suggest to create the error callback function with provided exception to handle errors._

**Comment by elfet** [comment]
Yes. I't will be in 4.x for sure.

**Comment by elfet** [comment]
Done in v4.
