### ISSUE TITLE
A question about the new 3.x

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#748]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Hello, I have updated from 2.x to 3.x and the deploy.php file doesn't work, I'd like to know if there is an example file for the new 3.x version.

Thanks

Oskar

**Comment by oanhnn** [comment]
@oskarcalvo You can see my example [oanhnn/deployer-example](https://github.com/oanhnn/deployer-example).
We are working with version 4 and It be released soon

**Comment by oskarcalvo** [comment]
Thanks @oanhnn ,
