### ISSUE TITLE
Super verbose output with color fragments although --no-ansi switch active.

### ISSUE THREAD

**Issue by kitingChris** [deployphp/deployer#749]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.3.0 |
| Local Machine OS | Linux |
| Remote Machine OS | Linux |
### Description

Not sure if this is intended but I want to get in my jenkins log only the clean output of all commands. 
The first second levels of verbosity do not use the color-format codes with --no-ansi but the third level does.
### Output log

```
+ dep deploy integration -vvv --no-ansi
➤ Executing task quality-assurance:run-lint
↳ on [integration]
> which php
[1;30m< /usr/bin/php[0m
[1;30m< [0m
```

**Comment by elfet** [comment]
I think we can add better support for `--no-ansi` in next version of deployer v4.

**Comment by elfet** [comment]
Done!
