### ISSUE TITLE
Can we use deploy as componant and not phar ?

### ISSUE THREAD

**Issue by Kleinast** [deployphp/deployer#750]
| Q | A |
| --- | --- |
| Issue Type | Question, Feature |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Hi,
I would like create a web-based app build with a full stack symfony. Is there a way to use directly deployer as a symfony componant and not call deploy.phar script from my symfony web app ?

Thx

**Comment by elfet** [comment]
Now deployer does not contain web app.

**Comment by Kleinast** [comment]
Ok but, if I install a symfony full stack, require deployer as dependency of a project for user deployer classes directly without out pass by dep command, is it possible ? is it hard ?

**Comment by elfet** [comment]
You can do it. Of cause.
