### ISSUE TITLE
Add ability to merge with set, rather than overwrite

### ISSUE THREAD

**Issue by garygreen** [deployphp/deployer#752]
When using `set('shared_dirs', ['my_custom_dir']);` it would be nice to have the ability to merge with the existing values, rather than overwrite.

At the moment I have to do `set('shared_dirs', array_merge(get('shared_dirs'), ['my_custom_dir']))`. which seems messy and adds a lot of bloat to my deploy file.

Maybe a `merge('shared_dirs', ['my_custom_dir'])` option for the collection?

**Comment by elfet** [comment]
I think creating another function for merging is bad — there is already to match functions.

What about this?

```php
$shared = get('shared_dirs');
array_push($shared, 'new', 'shared');
set('shared_dirs',  $shared);
```

**Comment by garygreen** [comment]
Too verbose for me. It's pretty common to want to add additional writable dirs, shared dirs, etc rather than simply replacing the existing ones the recipe defines? Surprised a function for merging data doesn't exist...

**Comment by elfet** [comment]
I think we can add some api function for what.

**Comment by oanhnn** [comment]
@garygreen @elfet 
What are you think about case:
```
// recipe abc
set('shared_dirs', ['foo', 'bar']);
```
And in `deploy.php` file, i only want share `bar` and `baz` directory.
Are we need a function to this case?
I think make a new function, new API is simple but it isn't need.
This make deployer will be complex. Especially when the document is unclear!

**Comment by garygreen** [comment]
@oanhnn 

> i only want to share `bar` and `baz` directory

Your last example does exactly that. I'm not sure what point your making?

**Comment by elfet** [comment]
What about this name instead of `merge`?

```php
add('shared_dirs', ['path/to/dir']);
```
```

**Comment by elfet** [comment]
Or more fun way:

```php
set('shared_dirs', function ($dirs) {
    $dirs[] = 'path/to/dir';
    return $dirs;
});
```

**Comment by garygreen** [comment]
I like `add` that sounds good. The closure function is pretty cool but can't see myself using it tbh.

**Comment by elfet** [comment]
Done in v4 with `add`.
