### ISSUE TITLE
[RuntimeException] mkdir: cannot create directory ‘releases’: Permission denied "deployer"

### ISSUE THREAD

**Issue by gopalindians** [deployphp/deployer#754]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | 3.0 |
| Local Machine OS | Ubuntu 15 |
| Remote Machine OS | Ubuntu 14 |
### Description

Unable to deploy the App from local folder to server through deployer 

it returns.
[RuntimeException] mkdir: cannot create directory ‘releases’: Permission denied "deployer"
### Content of `deploy.php`

``` php

declare(strict_types = 1);


require 'recipe/laravel.php';


define('HOST', '120.0.0.1');
define('USER_NAME', '***********');
define('PASSWORD', '**********');


// Laravel shared dirs
set('shared_dirs', [
    'storage/app',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'storage/logs',
]);

// Laravel 5 shared file
set('shared_files', ['.env']);

// Laravel writable dirs
set('writable_dirs', ['storage', 'vendor']);

server('prod', HOST, 22)
    ->user(USER_NAME)
    ->password(PASSWORD)
    ->forwardAgent()
    ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', '*****')
    ->stage('production')
    ->env('deploy_path', '/var/www/html');


task('reload:php-fpm', function () {
    run('sudo /usr/sbin/service php-fpm reload');
});

after('deploy', 'reload:php-fpm');
after('rollback', 'reload:php-fpm');
```
### Output log

_With enabled option for verbose output `-vvv`._

➤ Executing task deploy:prepare
↳ on [prod]

> echo $0
> < bash
> < 
> if [ ! -d /var/www/html ]; then mkdir -p /var/www/html; fi
> if [ ! -L /var/www/html/current ] && [ -d /var/www/html/current ]; then echo true; fi
> cd /var/www/html && if [ ! -d releases ]; then mkdir releases; fi

  [RuntimeException]  
  mkdir: cannot create directory ‘releases’: Permission denied  

Exception trace:
 () at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/Server/Remote/PhpSecLib.php:124
 Deployer\Server\Remote\PhpSecLib->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/functions.php:296
 run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/recipe/common.php:138
 {closure}() at n/a:n/a
 call_user_func() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/Task/Task.php:79
 Deployer\Task\Task->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/Executor/SeriesExecutor.php:43
 Deployer\Executor\SeriesExecutor->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/Console/TaskCommand.php:82
 Deployer\Console\TaskCommand->execute() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/src/Deployer.php:101
 Deployer\Deployer->run() at phar:///mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar/bin/dep:63
 require() at /mnt/hgfs/E/xampp/htdocs/Laraval/deployer.phar:4

deploy [-p|--parallel]

**Comment by elfet** [comment]
Check what your user has access to write in deploy path.
