### ISSUE TITLE
Deploying under different (root) user

### ISSUE THREAD

**Issue by JSpock** [deployphp/deployer#755]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

On production server I have user "produser" and it is in sudoers. Webapp directory is /www/application and owner of it is root (root:root). When I try to deploy there I got permission problem (cant create directories etc). 
Is there any possibility to switch user before deploy? I cannot change permissions of application dir and I can not get root password

**Comment by oanhnn** [comment]
I think with your case, you should deploy to other directory and make a symlink point to it.

**Comment by elfet** [comment]
Use `server(...)->user('root')`

**Comment by JSpock** [comment]
> Use server(...)->user('root')

I can't because I dont have root user password. Yes, it is kinda tricky situation and I cant figure out how to get deployer work for it. Another way is to rewrite common recipe and add sudo before every command (maybe it could be feature?)

**Comment by oanhnn** [comment]
@JSpock 
Can you try with `deploy_path`  different `/www/application` :smile: 
```
task('deploy:link', function () {
    run("cd /www/application && sudo ln -sfn {{current}} current");
});
after('deploy:symlink', 'deploy:link');
```

**Comment by JSpock** [comment]
@oanhnn That was my first idea too, but unfortunately, it is not an option. Files must also be root:root. So main question is, how it is possible to run switch user before deploy on remote machine

**Comment by kkrieger85** [comment]
I face the same/similar problem:

- Login to our server as root 
- Deployment as www-data

So first step after login to server has to be to change user.

My first idea was to rewrite `deploy:prepare` and add command to change user after login:

```
/**
 * Preparing server for deployment.
 */
task('deploy:prepare', function () {
    \Deployer\Task\Context::get()->getServer()->connect();
```

```
/**
 * Preparing server for deployment.
 */
task('deploy:prepare', function () {
    \Deployer\Task\Context::get()->getServer()->connect();
    run('sudo su www-data');   
```

Ref: recipe/common.php:104

**Comment by elfet** [comment]
Please, use sudo for switching users.

**Comment by kkrieger85** [comment]
That's not the solution.

Have a look at: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L104

There is no chance to switch user there between login to server and creating deploy_path

**Comment by kkrieger85** [comment]
To fix rights I use 

```php
task('fix-rights', function () {
    #runs as root
    run('chown -R 33:33 {{deploy_path}}');
});

after('cleanup', 'fix-rights');
```

**Comment by elfet** [comment]
What's good solution.
