### ISSUE TITLE
Run task with variables.

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#756]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Hello, I'd like to know if there is anyway to run a task and pass a  variable through the console.

Mi idea is:

```
task('drush: clear_cache', function () {
    run('sudo /usr/bin/drush  clear cache --var1');
});
```

And run in this way
`dep dev drush:clear_cache --var1=all`

Thanks

Oskar

**Comment by JSpock** [comment]
Check http://deployer.org/docs/tasks section "Using input options"

**Comment by elfet** [comment]
Up you can use options and arguments, check docs.
