### ISSUE TITLE
Where can be store new variables?

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#757]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

Following the example of @oanhnn the best place to to store new variables is:
app.php.tpl
dep.php
servers.yml

Thanks

Oskar

**Comment by elfet** [comment]
What is you question?

**Comment by oskarcalvo** [comment]
What is the best file to store the new variables?

**Comment by elfet** [comment]
I do not understand your question.

**Comment by oskarcalvo** [comment]
If I need  to store some variables, for example the token of cron, to be able to run task in Drupal.

**Comment by oanhnn** [comment]
@oskarcalvo 
- app.php.tpl
- deploy.php
- servers.yml

All files can save your variable. With me,

- app.php.tpl => template for config application, this is changed follow framework
- deploy.php => script deploy for application, this is changed follow framework (used recipe) and application's spec
- servers.yml => save server, stage information, enviroment variable for application. This is changed follow application
