### ISSUE TITLE
There is any way to add variables to the task?

### ISSUE THREAD

**Issue by oskarcalvo** [deployphp/deployer#758]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

I'd like to know it there is any way to make this idea:

```

task('drush:clear_cache', function() {
    run('/usr/bin/drush cc --vars1');
}); 


```

And this to run the comand:

`dep stagin drush:clear_cache --vars=all`

thanks.

Oskar

**Comment by oanhnn** [comment]
Please check document, using `option()` or `argument()` function
