### ISSUE TITLE
Error when I issued php vendor/bin/dep

### ISSUE THREAD

**Issue by SHMorton** [deployphp/deployer#759]
| Q 
| ----------------- | ---
| Issue Type        | Bug, Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Windows 10
| Remote Machine OS | N/A

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
Re: Error when I issued php vendor/bin/dep
Versions: Deployer 3.3.0, PHP 7.0.10 (FastCGI on Windows 10 IIS), Symfony 3, Windows 10.
Result:
dir=$(d=${0%[/\\]*}; cd "$d"; cd "../deployer/deployer/bin" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/dep" "$@"

### Content of `deploy.php`
```php
CONTENT
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by oanhnn** [comment]
Please more information about your issue.

**Comment by SHMorton** [comment]
1. I placed the phar file into my C:\PHP folder.
2. From my project root folder, with Symfony 3 already installed, I ran the command, composer require deployer/deployer:~3.3.0, which appeared to work and made the expected entries in the vendor folder.
3. From my project root folder I ran the command, php vendor/bin/dep, and received the long error message (starting with dir=$(d=${0%[/\]*};...) pasted into my issue pane above.

**Comment by cariba** [comment]
Hey mate, this might help you:
on a windows machine, go to your symfony project root and just type in directly:
.\vendor\bin\dep deploy staging
where "staging" is just an example. use one of your server definitions instead.
hope this helps!

**Comment by mittus** [comment]
@cariba thank's, it's help for me!

Then I will add "C:\www\vendor\bin" to the path, and now can start dep in cmd.
