### ISSUE TITLE
previously declared functions (conflicts)

### ISSUE THREAD

**Issue by tobz-nz** [deployphp/deployer#762]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0 (all versions?)
| Local Machine OS  | os x 10.11
| Remote Machine OS | N/A

### Description 
fatal errors with some global functions conflicting with other packages.

### Steps to reproduce
install deployer globally, run `dep` with `laravel/valet` also installed globally
or run `dep` with locally installed a laravel app (or anything with `hamcrest/hamcrest-php` installed)

### Output log
installed globally along with `laravel/valet`:
```
Fatal error: Cannot redeclare output() (previously declared in /Users/username/.composer/vendor/laravel/valet/cli/includes/helpers.php:39) in /Users/username/.composer/vendor/deployer/deployer/src/functions.php on line 520
```
or installed locally with `hamcrest/hamcrest-php` installed (via something else, not sure what.. just part of Laravel maybe?)

```
Fatal error: Cannot redeclare set() (previously declared in /Users/username/Code/codecomp/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /Users/username/Code/codecomp/vendor/deployer/deployer/src/functions.php on line 420
```

To fix it I guess use namespaced global functions?
Will PR if I get a chance - deadlines though :(

**Comment by tobz-nz** [comment]
..confirmed it can be fixed by either wrapping all the global function definitions in:
```
namespace Deployer {
   // functions
}
```
then importing all functions in `deploy.php` e.g. `Deployer\task();`

This would be a breaking change though.
Version 4.0?

**Comment by oanhnn** [comment]
This issue is discussed in other issues.
In version 4.x will be fix with function namspace.
With version 3.x, you should using `deployer.phar` file to deploy.

**Comment by ibasaw** [comment]
i'm on 4.x-dev, and got this fatal error:

    PHP Fatal error:  Cannot redeclare set() (previously declared in /var/www/sources/xxx/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /var/www/sources/xxx/vendor/deployer/deployer/src/functions.php on line 420
