### ISSUE TITLE
Potential Bug with using option('...') in combination with -p flag.

### ISSUE THREAD

**Issue by dustingraham** [deployphp/deployer#763]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.3.0 |
| Local Machine OS | Centos 7 |
| Remote Machine OS | Centos 7 |
### Description

When I add an option, then use that option, and combine it with -p it seems to silently die.
### Steps to reproduce
1. Add `option('dry-run', null, null, 'Use rsync --dry-run.');`
2. Use two or more servers.
3. Run `dep test dev --dry-run -p -vvv`
4. Observe it lists...
   
   ➤ Executing task test
   ↳ on [server1]
   ↳ on [server2]

But never gets past that step.

Thoughts?

**Comment by dustingraham** [comment]
After further testing, it appears that when setting -p it automatically sets the option to 1. Could be related.

**Comment by dustingraham** [comment]
Ah, I think this is the problem:

https://github.com/deployphp/deployer/blob/master/src/Executor/ParallelExecutor.php#L201

This looks like it's force adding my options, but I'm using flags, so there are no values provided.

My hack-around is to use InputOption::VALUE_REQUIRED with a default value of 0, and then call --dry-run=1 to enable it.

This bug should be fixed so userland can create flags like -r or --dry-run without requiring values. Sorry I don't know how to fix it.

**Comment by elfet** [comment]
We need to separately collect valueless options and pass it through. I'll fix it.

**Comment by elfet** [comment]
I made it! Done in v4!
