### ISSUE TITLE
Options and arguments not working

### ISSUE THREAD

**Issue by kalvish21** [deployphp/deployer#764]
I have the following code:

    argument('nogulp', InputArgument::OPTIONAL, 'Skip gulp install.');

    task('gulp', function () {
        $nogulp = input()->hasArgument('nogulp') && input()->getArgument('nogulp') != null;
        if (!empty($nogulp)) {
            echo 'Skipping gulp ...';
        } else {
            echo 'Running gulp ...';
            cd("/home/ubuntu/mycode");
            if (env('nogulp') == 0) {
                run("gulp");
                run("gulp assemble");
            }
            run("gulp asset");
        }
    })->desc('Run gulp tasks when required');

The purpose is to skip gulp tasks when not required. However, it always runs. I did it from the documentation here:

http://deployer.org/docs/tasks

Is there something im missing?

**Comment by dustingraham** [comment]
What's your command you're running? Are you trying to make it work on parallel? There's a bug for parrallel with no parameters. Try dep gulp production -p --nogulp=1

**Comment by kalvish21** [comment]
Thanks!
