### ISSUE TITLE
chmod doesn't work on bsd targets

### ISSUE THREAD

**Issue by torvitas** [deployphp/deployer#765]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3
| Local Machine OS  | debian
| Remote Machine OS | FreeBSD

### Description 
chmod doesn't work on bsd based systems since the ordering of parameters is wrong

**Comment by elfet** [comment]
What is correct order?

**Comment by torvitas** [comment]
https://www.gnu.org/software/coreutils/manual/html_node/chmod-invocation.html#chmod-invocation
