### ISSUE TITLE
Enable deep clone via env()

### ISSUE THREAD

**Issue by dmecke** [deployphp/deployer#772]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Deployer currently does a shallow clone of the repository when git_cache is `false`. Maybe it would be a good idea to make the depth of the clone configurable (or disable the shallow clone) via `env()`.

In my concrete use case I need to do some git magic at the end of the deployment to send an email with all included commits of that deployment. To be able to do so, I need a deep clone of the repository.

**Comment by elfet** [comment]
I think you can override task `deploy:update_code` for that.

**Comment by dmecke** [comment]
I thought about that, but that method is pretty long and I dislike overriding it just for changing that single parameter. Also, as the deep clone is already switchable (indirectly through git_cache), I thought it might be a good idea to be able to directly switch it on or off.

**Comment by qtsd** [comment]
You can also create a task which run `git fetch --unshallow`

**Comment by dmecke** [comment]
Thanks @qtsd, I did not know about that `--unshallow` option.
