### ISSUE TITLE
PHP Fatal error:  Cannot redeclare set()

### ISSUE THREAD

**Issue by asvechkar** [deployphp/deployer#775]
php vendor/bin/dep

PHP Fatal error:  Cannot redeclare set() (previously declared in /Users/aleksey/Projects/portalapp_app/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /Users/aleksey/Projects/portalapp_app/vendor/deployer/deployer/src/functions.php on line 420
PHP Stack trace:
PHP   1. {main}() /Users/aleksey/Projects/portalapp_app/vendor/deployer/deployer/bin/dep:0

Fatal error: Cannot redeclare set() (previously declared in /Users/aleksey/Projects/portalapp_app/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /Users/aleksey/Projects/portalapp_app/vendor/deployer/deployer/src/functions.php on line 420

Call Stack:
    0.0002     365728   1. {main}() /Users/aleksey/Projects/portalapp_app/vendor/deployer/deployer/bin/dep:0

**Comment by elfet** [comment]
Please read https://github.com/deployphp/deployer/blob/master/CONTRIBUTING.md

**Comment by oanhnn** [comment]
Thank you for report.
This is conflict function `set()` between **hamcrest/hamcrest-php** and **deployer/deployer**.
It was reported and resloved in version 4.x
