### ISSUE TITLE
Easier task definition

### ISSUE THREAD

**Issue by sourcerer-mike** [deployphp/deployer#776]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | master |
| Local Machine OS | Ubuntu |
| Remote Machine OS | Ubuntu |
### Description

To define a new task you can use the `task` function
which allows an array of other tasks to be executed.
Unfortunately every task needs to be defined as a function even if it is one command.
Those tasks need to be a string too instead of the closure.
Please give us a simpler interface.
### Suggestion

```
// execute one command
task('pull', 'bin/foo bar:baz');

// execute other tasks and one command
task('foo', [
  'bar',
  'bin/baz',
]);

// allow closures in tasks
task('bar', [
  'baz',
  function () { localRun('dmc'); },
  'qux',
  'bin/qux',
]);
```

Today I configure deployer with a "pull" command to get the DB and some other files from remote
or staging.
This ends in a lot of source which could be only a few lines as most of the commands are already there or just one line.
Instead I need to put it in plenty functions to server the `task` function.
I hope this will be rewritten some day.

**Comment by elfet** [comment]
Hi, 

Nice suggestion, but this will be conflicting with group def:
```php
task('foo', [
  'bar',
  'bin/baz',
]);
```

**Comment by sourcerer-mike** [comment]
I don't think so. It needs a strategy pattern that check if a single entry is a task. If not then it is a command.
Or it gets a prefix like `#`, `./` or similar to separate commands from tasks.

**Comment by elfet** [comment]
Done! 
```php
task('test', "
    while :;
    do
    date;
    sleep 1;
    done
")->once();
```

**Comment by sourcerer-mike** [comment]
Whoa. Is there any documentation? I don't understand the solution.

**Comment by elfet** [comment]
Documentation will be later, roadmap is here https://www.patreon.com/deployer
Now you can simple do this:
```php
task('bash', 'echo "command";');
```
