### ISSUE TITLE
Measuring tasks execution time

### ISSUE THREAD

**Issue by gulios** [deployphp/deployer#777]
| Q | A |
| --- | --- |
| Issue Type | Question, Feature Request |
| Deployer Version | 3.3 |
| Local Machine OS | OSX |
| Remote Machine OS | Debian |
### Description

I just want to measure execution time of each task defined in recipe and store it e.g in syslog.
example:  user | task_name | server | execution_time

In verbose mode i see times in output but how to catch these data while processing recipe?

Thank you.

**Comment by elfet** [comment]
Hi, what you want to measure?

**Comment by gulios** [comment]
We have large amount of servers and some of tasks in recipes take a lot of time to finish(git, builders, compressors etc) so that's why i want to store all tasks's execution times in  DB(syslog) for statistics usage.

ex:

user | deploy:prepare | 2s | server | timestamp
user | deploy:release  | 3s | server | timestamp
user | deploy:update_code  | 40s | server | timestamp
user | builder  | 30s | server | timestamp
etc...

**Comment by pluseg** [comment]
@elfet Anton, maybe it'd be more convenient to add profiling feature in verbose mode? Or as optional parameter `--profile`?

**Comment by elfet** [comment]
Yes this is good solution `---profile` option. Need to figure out how it will be combined with coming logging feature.
What open formats of profile is there?

**Comment by barryvdh** [comment]
Composer also use the `--profile` flag, which enables debugging mode on it's IO instance. That simply prepends the memory usage and time before the actual message, in all writes.

**Comment by barryvdh** [comment]
See https://github.com/composer/composer/blob/86c887b5e4455222b0728ab4c8a6a932c06c075d/src/Composer/IO/ConsoleIO.php#L151-L157

**Comment by joelpittet** [comment]
I was thinking this would be nice, so I could focus my efforts on what is the slowest operation instead of eyeballing it!  Is it my `rsync` or `composer` or `git clone` tasks that are taking their sweet time.  Knowing how long each one took could allow me to focus my attention a bit better to the main culprit.

**Comment by antonmedv** [comment]
Done!
```
dep deploy --profile profile.tsv
```

**Comment by grappler** [comment]
@antonmedv I can't find where this feature has been implemented. What is the `profile.tsv` used for?

**Comment by antonmedv** [comment]
For getting a time of execution.

**Comment by grappler** [comment]
Ok, is `profile.tsv` an empty file? While using version `6.8` and running `dep deploy staging --branch=master --profile` I get the following error: `The "--profile" option does not exist.`

**Comment by antonmedv** [comment]
This option was added in deployer v7
