### ISSUE TITLE
ask not working / PHP Fatal error:  Call to a member function getOutput()

### ISSUE THREAD

**Issue by mstaack** [deployphp/deployer#778]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  |  3.3.0
| Local Machine OS  | Ubuntu 14.04 LTS

### Description 
Ask not working at all

### Steps to reproduce
ask variable and echo it out.

### Content of `deploy.php`
```php
<?php

$branch = ask('branch?','master');

writeln($branch);
```

### Output log
```
└> dep -vvv       
PHP Fatal error:  Call to a member function getOutput() on boolean in phar:///usr/local/bin/dep/src/functions.php on line 519

Fatal error: Call to a member function getOutput() on boolean in phar:///usr/local/bin/dep/src/functions.php on line 519

```

**Comment by rlacerda83** [comment]
$branch->getOutput() ?

**Comment by mstaack** [comment]
```
<?php

require 'recipe/common.php';

$branch = ask('branch?', 'master');

writeln($branch->getOutput());

```

gives the same 
`PHP Fatal error:  Call to a member function getOutput() on boolean`

PHP 5.6

**Comment by elfet** [comment]
http://symfony.com/doc/current/components/console.html
