### ISSUE TITLE
Deployment of subtree

### ISSUE THREAD

**Issue by andrewtch** [deployphp/deployer#780]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Sometimes, it's better to work with monolithic repositories and use subtree splits. Is there a standard way that will allow to clone only subpart of the repo? The options might also be filter-branch and sparse checkouts.

**Comment by oanhnn** [comment]
Yes, current Deployer haven't this feature. 
You can customize update code task for this feature.
