### ISSUE TITLE
Returned true not updated after deployment

### ISSUE THREAD

**Issue by mehrdaad** [deployphp/deployer#781]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Question,   
| Deployer Version  | 3.1.2
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

I'm facing a very confusing circumstance. I can deploy my code successfully to remote machine.  
I can confirm that current symlink is pointing to latest release which I've pushed and the code is updated.  
The problem is that when I access my app through browser I can confirm that not only the front end hasn't changed yet but the back-end is pointing to previous version.  
The funny thing is that after a time of 5-10min the code is updated to latest version.  
Any insights of why I'm facing this issue?

**Comment by pdbreen** [comment]
Reload php-fpm (or apache depending on your server config) after the symlink is swapped.

**Comment by mehrdaad** [comment]
I'm on Nginx. how can I reload php-fpm?

**Comment by pdbreen** [comment]
One example is in the LaravelTemplate that's generated:  https://github.com/deployphp/deployer/blob/master/src/Initializer/Template/LaravelTemplate.php

My task def is near identical:

```
task('php-fpm:restart', function () {
    $output = run('sudo /sbin/service php-fpm restart');
    writeln('<info>' . $output . '</info>');
})->desc('Restart PHP-FPM service');
```

**Comment by mehrdaad** [comment]
I ran ``sudo /sbin/service php-fpm restart`` manually on Ubuntu server which returned ``-bash: /sbin/sevice: No such file or directory``  
but running `` service php5-fpm restart`` solved the problem.  

Just a small question: Will laravel app be able to serve while the php5-fpm is restarting?

**Comment by pdbreen** [comment]
If you use restart, there will be an extremely small outage (microseconds in my case, which is fine for me).  You can try using `service php5-fpm reload` instead.

**Comment by mehrdaad** [comment]
solved the problem. appreciated!  
Can I change ``service php5-fpm restart`` with ``service php5-fpm reload`` without any additional configuration?

**Comment by oanhnn** [comment]
Yes. I think ok.

**Comment by mehrdaad** [comment]
@pdbreen appreciated
