### ISSUE TITLE
Pointing symbolic link 'current' to a subfolder of the release

### ISSUE THREAD

**Issue by tbreuss** [deployphp/deployer#785]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question, Feature Request
| Deployer Version  | 3.3.0
| Local Machine OS  | Mac OS X
| Remote Machine OS | Linux

I couldn't find any information about if it's possible to point the symlink 'current' to a subfolder of the release folder.

Instead of pointing to a release folder like:
/www/deployer/releases/20160921222059

It would be useful to point to a subfolder of the release folder like:
/www/deployer/releases/20160921222059/web
/www/deployer/releases/20160921222059/public_html/
/www/deployer/releases/20160921222059/public/

The use case is that many frameworks are suggesting a folder structure, where the public folder is called "web", "public_html" or "public". Therefore on the remote server this folder is located within the deployer release folder.

In case of Yii2 basic app the folder structure looks like:

...
assets
commands
controllers
views
web (--> this is the public web server folder)
widgets
...

**Comment by t33k** [comment]
Why cant you simply point vhost to this folder like
DocumentRoot /var/www/yii.example.com/current/web

**Comment by tbreuss** [comment]
Thanks... and of course. This was a stupid one.
