### ISSUE TITLE
Deploying on shared hosting and serving from the webroot

### ISSUE THREAD

**Issue by migueldemoura** [deployphp/deployer#793]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Ubuntu 16.04 x64
| Remote Machine OS | Debian 8.5 x64

### Description 
How do I deploy a Symfony 3 app on shared hosting why deployer?

Here's my directory structure:
```
~
└─── current (symlink pointing to the lastest release)
│
└─── releases/
│   │  
│   └─── 20160925202156/
│   └─── 20160925202156/
│   
└─── shared/
│   
└─── web/ (web root)
```

This is what it looks like after my deploy script. Now, how do I use the contents of `current` and serve the app from the webroot this way?

I used to copy my whole project to the home folder with my project's web folder overriding the hosting web folder, which would obviously work.

I know how to do this with a Virtual Host, but without access to that I have no clue.

I tried using this:

```
Options +FollowSymLinks

RewriteEngine On
RewriteRule (.*) ../current/web/$1 [L]
```

but it didn't work.

**Comment by oanhnn** [comment]
Can you try make a symlink named `web` point to release directory like `current`.

```
/**
 * Create symlink to last release.
 */
task('deploy:custom_webroot', function () {
    run("cd {{deploy_path}} && ln -sfn {{release_path}}/web web");
});
```

**Comment by migueldemoura** [comment]
Didn't try that, thought I couldn't mess the the web dir itself - turns out I can.

With the symlink to the web dir I get 403's. 

Any ideas? I am trying to get the server logs, but it is ending up to be rather difficult.

**Comment by elfet** [comment]
It's something your hosting specified. Try to contact your host support.

**Comment by migueldemoura** [comment]
If anyone experiences a similar problem, here are my conclusions:

The 403's were down to the owner/group of the webroot dir being changed when creating the symlink. Asking the sysadmin to chown it fixed it.

Then I started having 500's due to the fact that execution of scripts outside the webroot wasn't allowed, causing the web/app.php require to outside web/ to fail.

It should be noted that you also need a `</Directive>` or equivalent applied to the folder containing the symlinked webroot with the option FollowSymLinks for Apache to follow it properly.
