### ISSUE TITLE
Redefine Symfony parameters

### ISSUE THREAD

**Issue by aurelien-w** [deployphp/deployer#796]
| Q | A |
| --- | --- |
| Issue Type | Question |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

I'd use "deployer" to redefine the parameters of Symfony (parameters.yml) during deployment. For that I would like to use the environment variables: SYMFONY__PARAMETER. But I do not know how to do with "deployer"?

`->env('SYMFONY_PARAMETER', 'value');` ?

`->env('env_vars', 'SYMFONY_PARAMETER=value');` ?

For now nothing works...
I use nginx.

```
<?php
require 'recipe/symfony3.php';

set('repository', '****');
set('shared_files', ['app/config/parameters.yml']);

server('preprod', '*******')
    ->user('archi')
    ->identityFile()
    ->env('deploy_path', '/var/www/html');

task('php-fpm:restart', function () {
    run('sudo systemctl restart php7.0-fpm');
})->desc('Restart PHP-FPM service');

task('deploy:owner', function () {
    run('sudo chown -R archi:www-data /var/www/html');
});

after('deploy:writable', 'deploy:owner');
after('success', 'php-fpm:restart');
```

Thanks !

**Comment by pluseg** [comment]
@aurelien-w Note that env() function doesn't set params in OS environment. Check method set() here: https://github.com/deployphp/deployer/blob/master/src/Server/Environment.php. You can write new function that sets it properly (http://unix.stackexchange.com/questions/21598/how-do-i-set-a-user-environment-variable-permanently-not-session).

**Comment by elfet** [comment]
Better docs needed for this.
