### ISSUE TITLE
git_cache support for git < 2.3

### ISSUE THREAD

**Issue by qtsd** [deployphp/deployer#798]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |

git_cache is only available when git > 2.3 because of the `--dissociate` option.

According to this [stackoverflow thread](http://stackoverflow.com/questions/2248228/how-to-detach-alternates-after-git-clone-reference) `--dissociate` just runs `git repack -a -d` and `rm .git/objects/info/alternates` (also visible in the official git repo)

Could I purpose a PR to dissociate manually when git < 2.3 ?

**Comment by elfet** [comment]
I think this is unnecessary complication. If people wants use _git_cache_, they can install new git. 
Implementing this feature cause a possible bugs also, so i think it's better to not implement it right now.
