### ISSUE TITLE
Forwarding agent 

### ISSUE THREAD

**Issue by jekill** [deployphp/deployer#80]
In my case I have different ssh keys on my deploy host and my git repository. For that I use "forward_agent" option in ruby lib "net-ssh". 

I have researched that and unfortunately found that libssh2 and therefore "pecl_ssh2" don't support forwarding agent. Only it prevents me to use "deployer" in my projects.

@elfet Do you have any ideas how to bypass it?

**Comment by charlieWasp** [comment]
Was this issue solved somehow? :)

**Comment by elfet** [comment]
Will be if i will implement native ssh agent.
