### ISSUE TITLE
Getting Permission Error

### ISSUE THREAD

**Issue by ovaiskhan11** [deployphp/deployer#800]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Windows 10
| Remote Machine OS | N/A

### Description 
I have created a folder .ssh/id_rsa in my directory D:/home/Abdul Ovais
Now directory looks like: D:/home/Abdul Ovais/.ssh/id_rsa
and also added id_rsa.pub file in .ssh folder which is D:/home/Abdul Ovais/.ssh/id_rsa.pub

but when I am trying to run command on Cygwin terminal it shows me permission error 

### Content of `deploy.php`
<?php
require 'deployer/recipe/opencart.php'; 
set('default_stage', 'staging');

// Define a server for deployment.
server('staging', '13.80.69.133')
    ->user('dev1') // Defind SSH username
    //->password('') // Define SSH user's password
	->identityFile('(D:/home/Abdul Ovais/.ssh/id_rsa.pub', 'D:/home/Abdul Ovais/.ssh/id_rsa', 'pass phrase')
    ->stage('staging') // Define stage name
    ->env('deploy_path', '/var/www/abdulovais.com'); // Define the base path to deploy your project to.

// Specify the repository from which to download your project's code.
set('repository', 'https://ovaiskhan@bitbucket.org/abdulovais/ok-web-app.git');
?>

### Output log
Abdul Ovais@DESKTOP-31UBAGF /xampp/htdocs/abdulovais
$ dep deploy:staging
➤ Executing task deploy:staging
Deploying...
Upload file catalog/controller/api/product.php to /var/www/abdulovais.com/catalog/controller/api/product.php

Warning: file_get_contents(D:/home/Abdul Ovais/.ssh/id_rsa): failed to open stream: Permission denied in phar://D:/usr/local/bin/dep/src/Server/Remote/PhpSecLib.php on line 62

  [RuntimeException]
  Unable to login with the provided credentials.
deploy:staging [-p|--parallel]

PHP Warning:  file_get_contents(D:/home/Abdul Ovais/.ssh/id_rsa): failed to open stream: Permission denied in phar://D:/usr/local/bin/dep/src/Server/Remote/PhpSecLib.php on line 62

**Comment by oanhnn** [comment]
This is error about read your key file. Please fix permission of path to file.
