### ISSUE TITLE
exit code

### ISSUE THREAD

**Issue by gulios** [deployphp/deployer#810]
| Q | A |
| --- | --- |
| Issue Type | Bug, Feature Request |
| Deployer Version | 3.3.0 |
| Local Machine OS | macOs |
| Remote Machine OS | Debian |
### Description

In Informer class there is taskError() method.
Unfortunately it returns only write output without exit code, so it's not possible to handle it.
I know that we can parse string for 'Some errors occurred!' but better way would be return exit(255) or pass code from output source/server.

Thx
### Output log

✘ Some errors occurred!

**Comment by elfet** [comment]
Error code correct:
```
dep deploy:lock; echo $?;
✔ Executing task deploy:lock
0
```

```
dep deploy:lock; echo $?;
➤ Executing task deploy:lock


  [RuntimeException]
  Deploy locked.
  Run deploy:unlock command to unlock.


deploy:lock [-p|--parallel]

1
```

> ✘ Some errors occurred!

Only for `NonFatalException`, so 0 exit code is correct.
