### ISSUE TITLE
Releases cleanup and rollback is dangerous

### ISSUE THREAD

**Issue by dima-stefantsov** [deployphp/deployer#814]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | latest |
| Local Machine OS | Windows |
| Remote Machine OS | Ubuntu |
### Description

_There may be situation where rollback will not work, where deployer will remove all good releases._
### Steps to reproduce
1. Keep 5 releases.
2. Deploy a good release.
3. Try to deploy but fail in process many times in a row, lets say 5 times.
4. Successfully deploy, but realize something went wrong (previous failures was for a reason, something bad is happening to code)
5. Try to rollback.
6. Fail.

Because unsuccessful deploys on **step 3** created many new folders in /releases/, and your cleanup logic just thinks in numbers. It has counted 5, removed the rest. Including the only good release folder that was working until latest deploy.

Effectively, while I said to keep 5 releases, deployer have kept 0 releases, removed even the latest /current/

Should be easy to fix, but is very important to be able to trust Deployer.

**Comment by elfet** [comment]
I think we need solution here. May be to do not allow to deploy if where was bad/not finished deploy.

**Comment by qtsd** [comment]
A task called after `deploy:prepare` and before `rollback`.
Which just check if symlink *release* exists, and then rm the link and its target.

This will keep only the last failed release (to debug it), and delete it when deploy works again or when rolling back.

**Comment by elfet** [comment]
Good solution.

**Comment by qtsd** [comment]
Perhaps better to have a function instead of a task, to avoid change all recipes (and keep the fix for people who have custom ones) ?
What do you prefer ?

**Comment by elfet** [comment]
i think it's better to create separate task which you can include to youк custom deploy.

**Comment by pdbreen** [comment]
You could also fail deploy:release (or deploy:prepare) if release symlink already exists.  This would alert that paste deploy failed and the repair task that you are talking about adding needs to be run once failure is understood.

**Comment by qtsd** [comment]
I think is better to clean automatically.
If it's ok, I can purpose a PR.

**Comment by elfet** [comment]
Well, i do not know what is best: automatically or manually. In automatically mode it's simple to redeploy. But in manually you can find out why deploy fails.

**Comment by qtsd** [comment]
In both cases you will have to find why deploy fails.
The only difference is that when a deploy fails, you will not be able to re-deploy until running the cleaning task by yourself.
I think it's waste of time because when a deploy fails, you know about it.
So when you re-deploy it's to test a fix or to deploy with a fixed recipe.

**Comment by elfet** [comment]
Done!
