### ISSUE TITLE
Problem with HTML files missing - Symfony2

### ISSUE THREAD

**Issue by pzaj2** [deployphp/deployer#818]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0
| Local Machine OS  | CentOS 7
| Remote Machine OS | CentOS 7

### Description 
*The HTML file that is included in repository is not being fetched / is being removed when deploying. Cloning the repository manually does clone the file*

### Steps to reproduce
*Create git repository with .html file somewhere in the structure*

### Content of `deploy.php`
```php
require 'recipe/symfony.php';

server('vm_dev', 'XXXX', 24)    
    ;

set('repository', 'XXXX');
```

### Output log
*Here everything is fine, it's successfully deployed*

**Comment by elfet** [comment]
Works for me.

**Comment by oanhnn** [comment]
I think you should check web server config (NGINX, apache, ...)

**Comment by pzaj2** [comment]
Well, it was overwritten (the whole directory was) by component installing assets using custom scripts! Problem fixed.
