### ISSUE TITLE
Cannot redeclare set() function

### ISSUE THREAD

**Issue by aambrozkiewicz** [deployphp/deployer#820]
Seems like deployer/src/functions.php are colliding with Laravel functions like set(), env() and probably other.

`Fatal error: Cannot redeclare set() (previously declared in /Users/aleksander/php/proj/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /Users/aleksander/php/proj/vendor/deployer/deployer/src/functions.php on line 420`

**Comment by elfet** [comment]
Yes, this bug already known, will be fixed in v4, now you can use phar archive.
