### ISSUE TITLE
A directory which is declared both "writeable" and "shared" is not fully writeable

### ISSUE THREAD

**Issue by k-solnushkin** [deployphp/deployer#822]
| Q | A |
| --- | --- |
| Issue Type | Bug |
| Deployer Version | 3.3.0 |
| Local Machine OS | Ubuntu 16.04.1 LTS |
| Remote Machine OS | Ubuntu 16.04.1 LTS |
### Description

With the Laravel recipe, the "storage" directory is rightfully moved to "shared" from under "releases", but access rights for "storage" are not set properly: everything inside "storage" should be web-server-writeable, but it is not.

The task "deploy:writable" works in directory "releases"; it sets access rights for the directory "storage" such that the web server can write into it, but the catch is that files under "storage" are also shared files, and for example "storage/logs" is a symlink pointing to "shared".

Here is what "man chmod" says: _"In contrast, chmod ignores symbolic links encountered during recursive directory traversals."_ Hence access rights for "storage/{app,logs}" are not properly set since they are symlinks.

This is a bug, because a Laravel application deployed this way will not work out of the box until permissions are fixed manually.
### Steps to reproduce

After deployment, permissions for "framework" are set properly (here, it's world-writeable, hence also web-server-writeable):

```
deploy@ubuntu:$ ll -d current/storage/framework/
drwxrwxrwx 2 deploy deploy 4096 Oct 26 15:31 current/storage/framework//
```

However, permissions for "logs" are **not** set properly:

```
deploy@ubuntu:$ ll -d current/storage/logs/
drwxrwxr-x 2 deploy deploy 4096 Oct 26 15:31 current/storage/logs//
```

The Laravel application cannot even write its logs to report about the problem.

My preferred manual workaround:

```
$ sudo chgrp -R www-data shared
```

This makes the directory owned by group "www-data" under which Nginx runs, hence making it writeable for Nginx.
### Content of `deploy.php`

Relevant section of `deploy.php` that lists 'storage' as both a shared directory and a writeable directory:

``` php
set('shared_files', ['.env']);
set('shared_dirs', [
    'storage/app',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'storage/logs',
]);
set('writable_dirs', ['bootstrap/cache', 'storage']);
```
### Output log

```
➤ Executing task deploy:writable
↳ on [production]
> ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
< www-data
<
> cd /home/deploy/example.com/releases/20161026153107 && chmod 2>&1; true
< chmod: missing operand
< Try 'chmod --help' for more information.
<
> cd /home/deploy/example.com/releases/20161026153107 && if hash setfacl 2>/dev/null; then echo 'true'; fi
> cd /home/deploy/example.com/releases/20161026153107 && sudo chmod 777 -R bootstrap/cache storage
• done on [production]
✔ Ok [190ms]
```

**Comment by elfet** [comment]
I think using ACL is more configurable and suitable for a most users. Using `chgrp` may broke a lot of workflow where user hierarchy not configured properly.

**Comment by elfet** [comment]
Fixed in v4.
