### ISSUE TITLE
Allow keeping all deployed releases

### ISSUE THREAD

**Issue by k-solnushkin** [deployphp/deployer#824]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | 3.3.0 |
| Local Machine OS | Ubuntu 16.04.1 LTS |
| Remote Machine OS | Ubuntu 16.04.1 LTS |
### Description

There is no way to specify to keep all releases that have ever been deployed. I would like to specify `set('keep_releases', -1)` so that old releases are not purged. Currently, to achieve the same effect, I would either need to specify a large number such as 1000000 or to redefine the "cleanup" task, which makes little sense.

Keeping all releases allows to compare a new version of the web application to an arbitrary older version.

**Comment by elfet** [comment]
I think it's possible to add this functionality.

**Comment by elfet** [comment]
Done in v4!

**Comment by k-solnushkin** [comment]
Dear Anton,

Allow me to express my deep gratitude for the way you handle community feedback, and for promptly closing this issue (#824) as well as #823 and #822.

Thanks for keeping up the good work!

I wish all of the community to have amazing experience with the new v4.0 release of Deployer.

**Comment by elfet** [comment]
Thanks a lot!
