### ISSUE TITLE
Add git tags to names of "release" directories

### ISSUE THREAD

**Issue by k-solnushkin** [deployphp/deployer#825]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | 3.3.0 |
| Local Machine OS | Ubuntu 16.04.1 LTS |
| Remote Machine OS | Ubuntu 16.04.1 LTS |
### Description

git tags are often used for deployments in continuous delivery workflow, but with Deployer there is no way to know which directory under `releases` corresponds to which git tag deployed. The directory name for a release could consist of not just a timestamp but also include a trailing tag name, such as `...-<tag>`, if a tag was specified via `--tag` command line option.

This will allow to quickly distinguish which version is deployed in which directory.

**Comment by elfet** [comment]
I think this can be easily achieved with rewriting release naming.
