### ISSUE TITLE
Deployer conflicts with Hamcrest PHP implementation

### ISSUE THREAD

**Issue by d70rr3s** [deployphp/deployer#826]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0
| Local Machine OS  | Ubuntu 15.10
| Remote Machine OS | N/A

### Description 
Deployer conflicts with Hamcrest PHP implmentation as both define a [**set()** ](https://github.com/hamcrest/hamcrest-php/blob/master/hamcrest/Hamcrest.php#L452)

### Steps to reproduce
Add deployer/deployer and mockery/mockery (use hamcrest-php as dep) as project deps using Composer.

### Content of `deploy.php`
```php
-
```

### Output log
```console
PHP Fatal error:  Cannot redeclare set() (previously declared in /home/dtorresr/MEGAsync/projects/m21_radio_web/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:455) in /home/dtorresr/MEGAsync/projects/m21_radio_web/vendor/deployer/deployer/src/functions.php on line 420
```

**Comment by elfet** [comment]
This will be fixed in next release on Deployer v4.
