### ISSUE TITLE
Separate authentication from configuration in `serverList()`

### ISSUE THREAD

**Issue by dnaber-de** [deployphp/deployer#832]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 3.3.0
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Currently the `serverList` function reads in all server configuration as well as authentication parameter. In order to allow different authentication options across all project contributors I provided a `servers.yml.dist` that is under version control and acts as a template. Any contributor can make a local copy `servers.yml` which is ignored by VCS and preferred by the `deploy.php` script. However, this has a mayor drawback. If something changes in the `servers.yml.dist` it has to be distributed to all possible local copies manually. Therefore I separated in two files: `server-config.yml` and `server-authentication.yml.dist`. The last one can be overwritten locally.

The use case is, that SSH-Configuration and Key-Setups typically differ across developer's machines. Maybe this would be a nice core feature.

Here's an example:

`server-configuration.yml`
```
servername:
  host: hostname.tld
  port: 22
  user: myuser
  deploy_path: /var/www
  branch: master
  stage: testing
  bin/php: "php_cli"
```

```
servername:
  identity_file:
    public_key: ~/.ssh/id_rsa.pub
    private_key: ~/.ssh/id_rsa
```

This is the updated `serverList` function, that handles two configuration files:
```
/**
 * @see serverList()
 */
function deployServers( $serverFile, $authFile ) {

	$serverList = Yaml::parse(
		file_get_contents( $serverFile )
	);
	$authList = Yaml::parse(
		file_get_contents( $authFile )
	);

	foreach ( (array) $serverList as $name => $config ) {
		try {
			if ( ! is_array( $config ) ) {
				throw new \RuntimeException();
			}

			$serverConfig = new DotArray( $config );
			if ( isset( $authList[ $name ] ) && is_array( $authList[ $name ] ) ) {
				$authConfig = new DotArray( $authList[ $name ] );
			} else {
				$authConfig = $serverConfig;
			}

			if ( $serverConfig->hasKey( 'local' ) ) {
				$builder = localServer( $name );
			} else {
				$builder = $serverConfig->hasKey( 'port' )
					? server( $name, $serverConfig[ 'host' ], $serverConfig[ 'port' ] )
					: server(
						$name, $serverConfig[ 'host' ]
					);
			}

			unset( $serverConfig[ 'local' ] );
			unset( $serverConfig[ 'host' ] );
			unset( $serverConfig[ 'port' ] );

			if ( $authConfig->hasKey( 'identity_file' ) ) {
				if ( $authConfig[ 'identity_file' ] === NULL ) {
					$builder->identityFile();
				} else {
					$builder->identityFile(
						$authConfig[ 'identity_file.public_key' ],
						$authConfig[ 'identity_file.private_key' ],
						$authConfig[ 'identity_file.password' ]
					);
				}

				unset( $authConfig[ 'identity_file' ] );
			}

			if ( $authConfig->hasKey( 'identity_config' ) ) {
				if ( $authConfig[ 'identity_config' ] === NULL ) {
					$builder->configFile();
				} else {
					$builder->configFile( $authConfig[ 'identity_config' ] );
				}
				unset( $authConfig[ 'identity_config' ] );
			}

			if ( $authConfig->hasKey( 'forward_agent' ) ) {
				$builder->forwardAgent();
				unset( $authConfig[ 'forward_agent' ] );
			}

			foreach ( [ 'password', 'pem_file' ] as $key ) {
				if ( $authConfig->hasKey( $key ) ) {
					$method = lcfirst( str_replace( ' ', '', ucwords( str_replace( '_', ' ', $key ) ) ) );
					$builder->$method( $authConfig[ $key ] );
					unset( $authConfig[ $key ] );
				}
			}
			if ( $serverConfig->hasKey( 'user' ) ) {
				$builder->user( $serverConfig[ 'user' ] );
				unset( $serverConfig[ 'user' ] );
			}
			if ( $serverConfig->hasKey( 'stage' ) ) {
				$builder->stage( $serverConfig[ 'stage' ] );
				unset( $serverConfig[ 'stage' ] );
			}

			// Everything else are env vars.
			foreach ( $serverConfig->toArray() as $key => $value ) {
				$builder->env( $key, $value );
			}
		} catch ( \RuntimeException $e ) {
			throw new \RuntimeException( "Error in parsing `$serverFile` file." );
		}
	}
}
```

**Comment by elfet** [comment]
You can use ssh keys for that.

**Comment by dnaber-de** [comment]
Use ssh-keys for what?

**Comment by elfet** [comment]
For authentication.

**Comment by dnaber-de** [comment]
Of course I can. In fact we use SSH-Keys for that but every developer on a different way. Some define various keys in `~/.ssh/config` others not. So there's no uniform way on how we use keys and how we name it. That's why I separate the authentication part from the server configuration part.

**Comment by t33k** [comment]
I have similar problem. 

Some devs working on one project uses "->identityFile()" and other uses "->forwardAgent()". 
We did put ->identityFile() as default into deploy.php but then other devs must change his deploy.php to activate ->forwardAgent().

deploy.php is in git so this is not good solution at all.

So having separate file with connection settings only that could be out of git is good idea IMO. 
However I am not using yml for configuration.

**Comment by elfet** [comment]
I think we can create something for v4.1.

**Comment by dnaber-de** [comment]
Any update on this?

**Comment by antonmedv** [comment]
Yes, there is complete solution for it in v5. Now you can have only definitions of hosts in inventory file `hosts.yml` and credentials in `~/.ssh/config`

**Comment by dnaber-de** [comment]
I'm not sure but there's typically no `~/.ssh/config` on Windows, isn't it?

**Comment by antonmedv** [comment]
you can use configFile method

**Comment by dnaber-de** [comment]
Not on Windows

**Comment by antonmedv** [comment]
On windows too. `host(...)->configFile(...)`

**Comment by dnaber-de** [comment]
What SSH client on Windows supports the config file syntax of Linux SSH client?

**Comment by antonmedv** [comment]
It's openssh.

**Comment by dnaber-de** [comment]
Didn't know that there's also a Windows version. Thanks for your patience.

**Comment by antonmedv** [comment]
Just add `host(...)->configFile('C:/.../ssh_config')`. Or i recommend you to use bash on windows: https://msdn.microsoft.com/en-us/commandline/wsl/about
