### ISSUE TITLE
Too many arguments, expected arguments "command".

### ISSUE THREAD

**Issue by skipyT** [deployphp/deployer#833]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 3.3.0
| Local Machine OS  | Ubuntu 16.04 php7
| Remote Machine OS | Ubunu 16.04 php7

### Description 
When trying to call dep command with stage argument I am getting an error.
Adding a new optional argument in TaskCommand::configure with:
$this->addArgument('stage', InputArgument::OPTIONAL, null);
resolves the issue. I will create a pull request for this.

### Steps to reproduce
Call dep my_task stagename
Error:
[Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".

### Output log
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".       
                                                          

Exception trace:
 () at /deployer/vendor/symfony/console/Input/ArgvInput.php:184
 Symfony\Component\Console\Input\ArgvInput->parseArgument() at /deployer/vendor/symfony/console/Input/ArgvInput.php:88
 Symfony\Component\Console\Input\ArgvInput->parse() at /deployer/vendor/symfony/console/Input/Input.php:62
 Symfony\Component\Console\Input\Input->bind() at /deployer/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /deployer/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at /deployer/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /deployer/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /deployer/vendor/deployer/deployer/src/Deployer.php:101
 Deployer\Deployer->run() at /deployer/vendor/deployer/deployer/bin/dep:64

my_task [-p|--parallel]

**Comment by skipyT** [comment]
I found that we can add arguments form deploy.php with argument(...). 

Closing this issue.

**Comment by xdemoor** [comment]
https://deployer.org/docs/servers

In "Stages" section:

_And then you call command dep [task] [server or stage], it will be executed only on specified stage servers._

When I did that, I have this error too. How to run a 'dep deploy dev' where dev is the stage of a server ?
Can't find the answer in the documentation...
