### ISSUE TITLE
[POLL] New default release name

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#840]
I'm thinking to move to more readable release name format:
```
releases/2016_11_05_08:49:20
```

Instead of 
```
releases/20161105084920
```

What @deployphp/maintainer are you think? 
Perhaps, it will not work on Windows.

Also there is another approach of using incremental releases name:
```
...
releases/255
releases/256
```

[Vote for new release name in v4](https://twitter.com/antonmedv/status/794825642957078528)

**Comment by t33k** [comment]
What about one more option to vote? :)
20161105_084920

**Comment by ivangretsky** [comment]
Please keep windows compatibility a priority.

**Comment by elfet** [comment]
Will keep. v4 comes with native ssh support.

**Comment by elfet** [comment]
Also looks like what incremental dir name a winning.

**Comment by elfet** [comment]
New v4 will come with incremental naming 🏆
