### ISSUE TITLE
Package/tarball deployment

### ISSUE THREAD

**Issue by jover** [deployphp/deployer#841]
Would be nice (IMHO even necessary) to deploy a package (tarball) instead of checking out the code from a repository.
See [Capistrano Tarball](https://github.com/aq1018/capistrano-tarball) deploy procedure for inspiration.

Nowadays, a lot of code has to be compiled before it's deployed to one or more servers.
For example, you don't want to compile SASS on your production servers...

So assembling/compiling the code locally, or on a build server should happen first (using Deployer) and then package it to sent it as a tarball to the servers (and of course extract it).

**Comment by elfet** [comment]
Hi, you can do this by implementing it using `task` by your self. Default `common.php` is used for building on production instead, and this is more suitable for more people. 

For example it's allow you to build release in beta and in prod versions.

PS It will be cool if come one implements this recipe with tarball for deploy. I can create repo in org on github.
