### ISSUE TITLE
Cant connect to Jelastic

### ISSUE THREAD

**Issue by earlcherry** [deployphp/deployer#842]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.3.0
| Local Machine OS  | Ubuntu 16.06 / Windows 10
| Remote Machine OS | CentOS Linux release 7.2.1511

`server('prod', 'gate.mirhost.cloud', 3022)`
       ` ->user('xxx')`
       ` ->env('deploy_path', '/var/www/webroot/')`
        `->identityFile('/home/xxx/.ssh/id_rsa.pub', '/home/xxx/.ssh/id_rsa')`
        `->stage('production');`
`set('default_stage', 'production');`

Hello. Deployer cant connect to Jelastic server with this keys, but from cli connect successful. Deployer return "Unable to login with the provided credentials". What im doing wrong?

**Comment by elfet** [comment]
Try run ssh-add before in console.

**Comment by earlcherry** [comment]
same problem

**Comment by earlcherry** [comment]
Executing task deploy:prepare

Notice: Expected SSH_FXP_VERSION in phar://C:/Soft/Dev/Server/OpenServer/modules/php/PHP-7-x64/deployer.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 473


  [RuntimeException]
  Unable to login with the provided credentials.


deploy [-p|--parallel]

**Comment by earlcherry** [comment]
solve the problem. In jelastic you must set not only username. Correct is nodeid-userid like 123456-1234. Now how i can connect from Windows? In linux i use ssh-add, in windows i try add key to peagent but its dont work. And sorry for stupid question, but why need use both keys in identityFile function, id_rsa and id_rsa.pub? Private key not enough?

**Comment by elfet** [comment]
ext-ssh requires it https://github.com/deployphp/deployer/blob/master/src/Server/Remote/SshExtension.php#L74
