### ISSUE TITLE
Clean up .git folder after release

### ISSUE THREAD

**Issue by andrewtch** [deployphp/deployer#844]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Currently, deployer leaves .git folder intact. It should clear it automatically.

**Comment by elfet** [comment]
True.

**Comment by andrewtch** [comment]
To be precise deployer should clean SVN / HG and other folders, leaving no artifacts. Any idea where to hook this behavior? In "update code"?

**Comment by elfet** [comment]
You can setup `clear_paths` for that. Can you create PR?

**Comment by andrewtch** [comment]
Should I add it to https://github.com/deployphp/deployer/blob/master/recipe/common.php#L237 ?

Btw, any plans to support anything but git?

**Comment by elfet** [comment]
No, to clean_paths.

Yes, later in v4.1.

**Comment by elfet** [comment]
You can achieve this by `deploy:clean` task.

```php
set('clear_paths', [
    '.git'
]);
```

But note in this case git cache will not work and on next deploy will be downloaded full release.

**Comment by renatomefi** [comment]
Just an update, the task it currently called: `deploy:clear_paths`
