### ISSUE TITLE
Deployment info file

### ISSUE THREAD

**Issue by andrewtch** [deployphp/deployer#845]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Create releases.txt file and add info about who and when deployed what.

**Comment by pluseg** [comment]
@elfet I think it's possible to use `.dep/releases` file for that. What do you think?

**Comment by elfet** [comment]
I think to use web-based client to display deployment logs. And now i'm working on this feature hard.
