### ISSUE TITLE
Command to execute arbitrary command on remote host

### ISSUE THREAD

**Issue by andrewtch** [deployphp/deployer#846]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Like capistrano / symfony symfony:console command, respecting prod env and --no-debug

**Comment by dima-stefantsov** [comment]
I think you already can do that, using custom argument. dep mycommandexecutor --mycommand="echo $PATH", something like that.

**Comment by elfet** [comment]
Hi, i'm thinking to add something like this.

**Comment by elfet** [comment]
I think better to have command to connect to server: `dep ssh production`, that way, than implementing terminal in plain php.

**Comment by elfet** [comment]
And `ssh` command will ship in v5 🙂
