### ISSUE TITLE
Local deployments?

### ISSUE THREAD

**Issue by ColmMcBarron** [deployphp/deployer#849]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Have local deployment options been removed?

This recipe is not in source control, maybe there is a different way to do it?
https://deployer.org/recipes/local

Thanks

**Comment by ikappas** [comment]
You need to use https://github.com/deployphp/recipes

**Comment by elfet** [comment]
Use can use `localServer`.
