### ISSUE TITLE
Conditional before and after

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#851]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Allow before and after tasks to run conditionally. 

I have prepared two different reference implementations

In https://github.com/ikappas/deployer/tree/feature/conditional-scenario-1 the definition is:
```
$enabled = true;
after('some:task:a', 'other:task:a', $enabled);
before('some:task:b', 'other:task:b', function(){
 // 
});
```

In https://github.com/ikappas/deployer/tree/feature/conditional-scenario-2 the definition is:
```
$enabled = true;
after('some:task', 'other:task')->when($enabled);

before('some:task', 'other:task')->when(function() {
   // Do your stuff and return a boolean value.
});

$disabled = true;
after('some:task', 'other:task')->unless($disabled);

before('some:task', 'other:task')->unless(function() {
   // Do your stuff and return a boolean value.
});

```

### References
https://github.com/ikappas/deployer/tree/feature/conditional-scenario-1
https://github.com/ikappas/deployer/tree/feature/conditional-scenario-2

**Comment by elfet** [comment]
I think this is unnecessary complications.  You can simple do it using if within task.

**Comment by ikappas** [comment]
@elfet 

There is an issue using a simple if. The task **seems** to run allways as reported to the console which is misleading.
```bash
$ dep 'db:pull' staging
> db:backup:local
> db:push
...
```


Consider the following example and how concise it looks and acts.

### Code on a composer library under vendor/some/package/recipes/db.php
```php
// Boolean to determine whether the database should be backed up or not.
// Override this to enable backups.
set('backup_db', false);

desc('Pull the database from the remote server');
task('db:pull', [...]);

task('db:backup:local', ...)->setPrivate();

// Run the following task **only** if user has overridden the 'backup_db' option.
before('db:pull', 'db:backup:local')->when(function(){ return get('backup_db'); });

```

### Code on project deploy.php
```php
require_once 'recipe/common.php';
require_once 'vendor/some/package/recipes/db.php';

// enable database backups before pull/push operators
set('backup_db', true);

```
### Output with default `backup_db` false value.
```bash
$ dep 'db:pull' staging
> db:push
...
```

### Output with `backup_db` set to true in deploy.php
```bash
$ dep 'db:pull' staging
> db:backup:local
> db:push
...
```

Btw, Capistrano provides this functionality using if/unless. 

```ruby
namespace :db do
  namespace :backup do

    desc "Backup the local database"
    task :local do
      run_locally do
        ...
      end
    end

    before :push, 'backup:remote' if :backup_db # <-- This is how it's used

  end
end
```

**Comment by ikappas** [comment]
I found another issue while using a simple if:

consider the previous example but with `db:backup:local` as public

```php
// Boolean to determine whether the database should be backed up or not on push/pull operations.
// Override this to enable backups on push/pull.
set('backup_db_on_push_pull', false);

desc('Pull the database from the remote server');
task('db:pull', function(){
    // database pull magic here
});

task('db:backup:local', function() {
    if (get('backup_db_on_push_pull')) {
        // database backup magic here
    }
});

before('db:pull', 'db:backup:local');
```
### Expected Behaviour
- When `dep db:pull staging` is run it doesn't execute `db:backup:local`.
- When `dep db:backup:local` is run it executes the backup task.

### Actual Behaviour
- When `dep db:pull staging` is run it doesn't execute `db:backup:local`
- When `dep db:backup:local` ***seems to run but never executes the backup task!***

### Notes
Using a simple if statement tightly couples the two tasks and there is no easy solution around it.

**Comment by elfet** [comment]
I was thinking about implementing this feature, and i think best way it to have API like this:
```php
if(get('backup_db_on_push_pull')) {
     before('db:pull', 'db:backup:local');
}
```

But it will require PHP source parsing which i do not like. May be there is another solution for this: server roles. 

If @ikappas you can describe a little more about why you need this, it will help.

**Comment by ikappas** [comment]
@elfet
In your example the if(get('backup_db_on_push_pull')) is evaluated before the tasks actually run. This means that `backup_db_on_push_pull` must be manipulated prior to these lines of code.

This probably works from an end-user standpoint but from a library standpoint where you want to provide the `backup_db_on_push_pull` option to enable this functionality it will not work because your library will always be included before any user code.

Instead consider the following :
```
before('db:pull', 'db:backup:local')->when(function(){ return get('backup_db_on_push_pull'); });
```
The conditional statement (when/unless) is evaluated when tasks are actually run thus giving the opportunity to the user to override the `backup_db_on_push_pull` option as they please.

(See the two reference implementations under references in the description.)

**Comment by elfet** [comment]
What about allowing users to swift on/off plugins functionaloty by adding after/before hooks in those deploy.php files?

**Comment by antonmedv** [comment]
#1140

**Comment by antonmedv** [comment]
See #1140
