### ISSUE TITLE
Introduce a desc function

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#852]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Add a desc function, similar to capistrano, that allows to add a description to the subsequent task definition.
```
desc('Flush rewrite rules');
task('wp:rewrite:flush', function () {
    within('release_path', function() {
        run('{{bin/wp}} rewrite flush {{wp_cli_args}}')
    });
});
```

### References
https://github.com/ikappas/deployer/tree/feature/desc-function

**Comment by oanhnn** [comment]
You can use:
```
task('wp:rewrite:flush', function () {
    within('release_path', function() {
        run('{{bin/wp}} rewrite flush {{wp_cli_args}}')
    });
})->desc('Flush rewrite rules');
```

**Comment by elfet** [comment]
I thinking of it. And i like how it looks.

**Comment by elfet** [comment]
Done: https://github.com/deployphp/deployer/blob/0d37f55460f3c351c3e4e4341765c47ae4d63933/src/functions.php#L122
