### ISSUE TITLE
Stage branch setting in configuration is ignored

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#858]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | master
| Local Machine OS  | Mac OS 10.12.1
| Remote Machine OS | N/A

### Description 
When executing `dep deploy` the branch setting set for a stage is overridden by a null which 
results in always deploying on master branch.

### Explanation
This happens because in common.php:161 a branch option is initialized with null value.
```php
option('branch', null, InputOption::VALUE_OPTIONAL, 'Branch to deploy.');
```

And in task `deploy:update_code` the following code is broken because branch is always overridden with a null value.
```
$branch = get('branch');
...
// If option `branch` is set.
if (input()->hasOption('branch')) {
    $branch = input()->getOption('branch'); // This value is null always.
}
```

**Comment by ikappas** [comment]
Please note that this issue may also affect tag and revision options that are configured similarly.

**Comment by ikappas** [comment]
@elfet This happens on latest `master`

**Comment by elfet** [comment]
Fixed. Also recheck tag and revision. Now all good.
