### ISSUE TITLE
🚀🚀🚀🚀  Deployer v4 ready to release! [BETA TESTERS WANTED]

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#860]
Deployer v4 milestone are closed 🕶 . There a lot of features and refactoring. I'm think now we are ready to release it. But before it will be cool if it was tested.

## Beta Testers Wanted!

Please, test master branch and phar archive too (to create phar archive run `php ./build` command).

ping @deployphp/maintainer

**Comment by TheRatG** [comment]
Hello, I successfully integrated master deployer to  one of my project, which is using symfony3 recipe. Also I'm planning update deployer in another 2 or 3 projects. Thanks a lot.

**Comment by elfet** [comment]
Cool! If everething will be okay, let me know. Thanks!

**Comment by elfet** [comment]
Released!
