### ISSUE TITLE
Forward Composer Auth For Private Repositories

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#861]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Short Description 
Add an option to forward composer auth (similar to forward agent) to the remote servers in order to access private repositories.

### Description
Using composer private repositories via Satis or Toran Proxy does not work unless `forward agent` is used. However, these repositories are cloned instead of downloaded which is slow.
```bash
[staging] <   - Installing example/package (1.0)
[staging] <     Downloading
[staging] <     Failed to download example/package from dist: The 'https://packages.example.com/packages/composer/dist/archive.zip?project_id=212&ref=1.0' URL required authentication.
[staging] < You must be using the interactive console to authenticate
[staging] <     Now trying to download from source
[staging] <   - Installing example/package (1.0)
[staging] <     Cloning 738e67d11e33b924bac17eddcccc2a0dfaef3bd
```
This can be mitigated by forwarding composer auth to the deployment server using COMPOSER_AUTH environment variable.

### Reference Capistrano Code
```ruby
def composer_home
  if ENV['COMPOSER_HOME']
    ENV['COMPOSER_HOME']
  elsif (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    raise 'The APPDATA or COMPOSER_HOME environment variable must be set for composer to run correctly' unless ENV['APPDATA']
    File.join(ENV['APPDATA'].gsub("\\", '/'), 'Composer')
  else
    raise 'The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly' unless ENV['HOME']
    File.join(ENV['HOME'].gsub("\\", '/'), '.composer')
  end
end

def composer_auth_json
  File.realpath(File.join(composer_home, 'auth.json'))
end

if ENV['COMPOSER_AUTH']
  fetch(:default_env).merge!({
    composer_auth: JSON.minify(ENV['COMPOSER_AUTH']).gsub('"', '\"')
  })
elsif File.file?(composer_auth_json)
  fetch(:default_env).merge!({
    composer_auth: JSON.minify(File.read(composer_auth_json)).gsub('"', '\"')
  })
end
```

### References
- https://getcomposer.org/doc/articles/http-basic-authentication.md
- https://getcomposer.org/doc/03-cli.md#composer-auth

**Comment by ikappas** [comment]
@elfet Have a look at https://github.com/ikappas/deployer/tree/feature/forward-composer-auth for possible implementation 😄

**Comment by elfet** [comment]
Can you make PR?

**Comment by peterjaap** [comment]
+1

**Comment by syssi** [comment]
I would be happy about a solution for this use case. Especially the Gitlab Package Registry can be accessed via HTTPS/AuthToken only.

**Comment by antonmedv** [comment]
How it’s used?

**Comment by syssi** [comment]
You can have a private package repository. It will be added by

```
composer config repositories.<group_id> composer https://gitlab.example.com/api/v4/group/<group_id>/-/packages/composer/
```

If it's not public the URL isn't accessible without basic authentication. A so called "personal access token" (username: ___token___, password: <token>) or your username & password is required to access the repository:

```
composer config gitlab-token.gitlab.com <personal_access_token>
```

At the CI/CD pipeline and locally it's pretty easy to access the package registry. I would like to give "deployer" / the deploying host access to this package repository. The commands above creates a `auth.json` at the project root or globally at the composer home. I would like to forward this authorization (file/environment variale) to the remote host.

**Comment by antonmedv** [comment]
Just upload auth.json to remote host.

**Comment by syssi** [comment]
Good point. I will give it a try! :-)
