### ISSUE TITLE
Remove Self-Update Command When Installed via Composer

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#862]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
The self-update command should not be available when deployer is installed as a composer package.

### Steps to reproduce

- install deployer as a composer package.
- run ./vendor/bin/dep
- in the list shows `self-update` as a command

**Comment by elfet** [comment]
Does it really needed? 😃 
Also what to do in this situation:
* user install deployer with composer,
* user download phar,
* user run phar in project with deployer installed via composer,
* deployer detects it, and run local deployer source from vendor dir.

**Comment by ikappas** [comment]
Hehe it is certainly not critical! 😄 
Well why not hide it after `deployer detects it`?

**Comment by elfet** [comment]
What to do if user want to update phar then?

**Comment by ikappas** [comment]
I am not familiar with the current implementation and how deployer detects it.

I think that the logic should be:
- When deployer is run via ./vendor/bin/deployer then the command should be hidden. 
- When deployer is run via phar(local/global) then the command should be available.

Composer for example handles it in this manner. If you run composer from phar the selfupdate/self-update command is available but when run via ./vendor/bin/composer you can see that it is not.

Also I've noticed that you have a dependency on 'deployer/phar-update' that could probably be removed when deployer is installed via composer.

**Comment by elfet** [comment]
Now deployer does not detect at all.

**Comment by ikappas** [comment]
Check this out:
https://github.com/composer/composer/blob/master/src/Composer/Console/Application.php#L384

**Comment by elfet** [comment]
Done ;)
