### ISSUE TITLE
Background process

### ISSUE THREAD

**Issue by ekandreas** [deployphp/deployer#867]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4
| Local Machine OS  | OSX
| Remote Machine OS | Ubuntu 16

### Description 
How do I start a local background process from php-deployer?
In this case I need to ensure that Selenium is started before running tests.

This snippet inside a task will get stucked on the java part... 
```
    $output = runLocally('ls selenium.jar');
    if($output!='selenium.jar') {
        runLocally('wget https://goo.gl/Lyo36k -O selenium.jar');
    }
    runLocally('java -jar selenium.jar &');
    runLocally('phpunit tests');
```

**Comment by elfet** [comment]
Try to use something like nohup.

**Comment by MasonFI** [comment]
Can you post nohup example how it should work?

I have this script called start-email-create.sh:
export CI_ENV=demo && nohup php /var/www/xxx/current/codeigniter/public/index.php tasks EmailCreate >> /var/log/php-cli/demo/email-create/$(date +"%Y%m%d").log 2>&1 &
echo $! > /root/tasks/demo/email-create.pid

When I run this from cli, it works fine. When I start it from deployer like this:
desc('Start email message creation and sending');
task('messaging:start-email-messaging', function () {
	run('/root/tasks/demo/start-email-create.sh');
});

It will start the task, but it does not return anything, so Deployer will get timed out.
The EmailCreate function is just infinite while loop that creates messages with fixed intervals.

Can Deployer somehow skip the return value of that .sh script and move on to the next task?

**Comment by antonmedv** [comment]
run('
   export CI_ENV=demo && nohup php /var/www/xxx/current/codeigniter/public/index.php tasks EmailCreate >> /var/log/php-cli/demo/email-create/$(date +"%Y%m%d").log 2>&1 &
echo $! > /root/tasks/demo/email-create.pid
');

**Comment by MasonFI** [comment]
Thanks!

**Comment by MasonFI** [comment]
I dont know if its a Deployer problem, but I'll ask it here anyways: for some reason deployer hangs on even with that change above when deploying to production, but demo and dev environments are working properly. Difference is, that dev and demo are deployed locally to the dev server, production is done to external server. Any tips how to debug this?

**Comment by antonmedv** [comment]
Try disable multi staging. Add do add `-vvv` option.

**Comment by MasonFI** [comment]
Thanks. Did not work, -vvv doesn't show anything interesting.. well maybe I'll try to run those scripts from Jenkins pipeline after Deployer.

**Comment by johandouma** [comment]
I'm having the same issue I think, deployer just seems to hang and nothing happens. @MasonFI did you ever resolve this issue? I know it's been a while though.

**Comment by MasonFI** [comment]
No I didnt resolve the issue, sorry.

ke 17. heinäk. 2019 klo 10.04 Johan Douma <notifications@github.com<mailto:notifications@github.com>> kirjoitti:

I'm having the same issue I think, deployer just seems to hang and nothing happens. @MasonFI<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMasonFI&data=02%7C01%7C%7Cdfab57de660c4c6c796408d70a84f2eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636989438440476824&sdata=LZGIqdiLy03hlwZC%2FspDUoKvkMKhSNmoEu1n1iCMgZI%3D&reserved=0> did you ever resolve this issue? I know it's been a while though.

**Comment by bohehe** [comment]
Have you solved this issue? I got the same timeout problem when I'm  running
`nohup java -jar build/libs/xxxxx.war > /dev/null 2>&1 &`. The deployer return no outputs, but the process is hanged and finally I got a timeout error.

**Comment by bohehe** [comment]
I solved my problem:
I was using
`task('deploy:rollback', function() {
    run('cd {{deploy_path}}/current && java -jar build/libs/xxxx.war > /dev/null 2>&1 &');
});`

to solve the timeout issue,  I use the absolute path, 
`java -jar {{release_path}}/build/libs/tmail_bu-0.0.1.war > /dev/null 2>&1 &`
It seems the & character has some bug on function run().
BTW, 
`run('cd {{deploy_path}}/current && java -jar build/libs/xxxx.war > /dev/null 2>&1 & && echo "done"');`
will return an syntax error because of "&&"
Hope this will help you.

**Comment by MasonFI** [comment]
Sorry, I couldn't solve this problem.

pe 22. toukok. 2020 klo 6.43 Good Hunter <notifications@github.com>
kirjoitti:

**Comment by addgod** [comment]
The problem here is that deployer ssh into the the machine, and then when it is done, it disconnects. Any task that are run by that user in the jobs list ( and that is what & in the end does ) will be closed. You need to add a diswon after then it should work.

```
run('cd {{deploy_path}} && java -jar build/libs/xxxx.war > /dev/null 2>&1 & disown');
```

**Comment by SimansDev** [comment]
> The problem here is that deployer ssh into the the machine, and then when it is done, it disconnects. Any task that are run by that user in the jobs list ( and that is what & in the end does ) will be closed. You need to add a diswon after then it should work.
> 
> ```
> run('cd {{deploy_path}} && java -jar build/libs/xxxx.war > /dev/null 2>&1 & disown');
> ```
Hello from 2024. 
I hoped this one would work for me, but it doesn't. The command was placed in the background, but the deployer is still waiting for the command to be finished.
