### ISSUE TITLE
Specific Version Download Links

### ISSUE THREAD

**Issue by anthonysomerset** [deployphp/deployer#868]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I want to write a homebrew-php formula for deployer so that people can manage the install via homebrew (mainly so we can avoid warnings about binaries co-existing in same directory)

part of the formula is a sha256 hash check to verify the downloaded file before install - obviously it would be impossible to verify this with the generic download link url as it may change at anytime

Please can you consider providing specific version links in addition to the quick install link so that homebrew downloads won't immediately break when you release an update, i don't think we need to maintain all versions but current and previous should be adequate

**Comment by anthonysomerset** [comment]
Closing as i didn't see https://deployer.org/download before

**Comment by elfet** [comment]
There is also https://deployer.org/manifest.json
