### ISSUE TITLE
clear_paths deletes relative to release_path and not to deploy_path

### ISSUE THREAD

**Issue by t33k** [deployphp/deployer#869]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0
| Local Machine OS  | OSX
| Remote Machine OS | Debian

### Description 
In Deployer 3.3 the clear_path was relative from deploy_path.
In Deployer 4.0 the clear_path is relative from release_path.

In comment of set('clear_paths', []); there is still  // Relative path from deploy_path
Is it bug or change of clear_paths behaviour?

**Comment by elfet** [comment]
It's a change of behavior. Neet to update docs.
