### ISSUE TITLE
keep_release wrong counting and wrong folder remove

### ISSUE THREAD

**Issue by t33k** [deployphp/deployer#870]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0
| Local Machine OS  | OSX
| Remote Machine OS | Debian

### Description 
If I set:
set('keep_releases', 3);

then there is four release folders and additionally every second deploy the wrong folder is removed. 

For example:
1) in releases folder there are 3,4,5,6 folders
2) I do deploy
3) in release folder there is now 3,5,6,7 folders
4) I do deploy 
5) in release folder there is now 5,6,7,8 folders
4) I do deploy
5) in release folder there is now 5,7,8,9 folders

**Comment by elfet** [comment]
Counting is wrong, will fix it. But sorting based on mtime, so if you touch something in old release - order are about to change.

**Comment by elfet** [comment]
I think solution is only to sort alphabetically using sort php func.
