### ISSUE TITLE
Overwriting the init task currently not possible. Is this intentional?

### ISSUE THREAD

**Issue by x3ro** [deployphp/deployer#872]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | master
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Currently, in the [Deployer class](https://github.com/deployphp/deployer/blob/master/src/Deployer.php#L171), the `init` task is non-overwritable since it is added before after the `addConsoleCommands`. Since I'm building a custom `deployer.phar` bundled with custom recipes, it'd be very useful to be able to provide a custom `init` command as well, without having to modify the Deployer source.

Is there a reason for adding the `init` command this what that I'm not seeing? Thanks for your time!

**Comment by elfet** [comment]
Done. Please check master branch.
