### ISSUE TITLE
DotArray Syntax in Deployer 4.0.0 not supported anymore?

### ISSUE THREAD

**Issue by tinogo** [deployphp/deployer#873]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.0
| Local Machine OS  | Gitlab CI Docker Container (Debian)
| Remote Machine OS | Ubuntu 14.04

### Description 
I've just updated from Deployer version 3.3.0 to version 4.0.0 and I have a question regarding the DotArray Syntax.
In my deploy scripts I was using `env('server.host')` to obtain the defined server hostname.
I've changed it to `get('server.host')` for Deployer 4.0.0, but now I'm getting the following error message:
```
Configuration parameter `server.host` does not exists. 
```

So, the question is: How can I obtain the server host via the environment variables with Deployer 4.0.0?

**Comment by t33k** [comment]
I can confirm with env('server.name') . My quick fix was: 
get('server')['name'];

**Comment by elfet** [comment]
DotArray was deprecated in Deployer 4, but i think we can return some of it functionality back to Collection class.  So it will be possible to use dot notation. Btw @t33k solution correct.

**Comment by mootari** [comment]
@elfet There's a difference between deprecating and completely removing a feature. :)

**Comment by tinogo** [comment]
@t33k: Thank you for the hint. `get('server')['host']` did the trick for me. :)
@elfet: Although @mootari ist right, Deployer 4.0.0 was/is a major release, so removing features or breaking the API isn't a problem imo.
But it would have helped a lot to mention in the UPGRADE.md, that the DotArray syntax isn't supported anymore.

**Comment by mootari** [comment]
@tinogo: I'm totally fine with feature removal / changes, too. I merely wanted to point out that "deprecated" doesn't mean "removed" and might cause confusion if used that way.

**Comment by elfet** [comment]
Returned part of functionality back. Please, check master branch.

**Comment by elfet** [comment]
Fixed.

**Comment by pniederlag** [comment]
not working in v4.0.2 for me using serverList('servers.yml') and dep staging.foo

I do get:

    [RuntimeException]                           
      Stage or server `staging.foo` was not found.

Dumping 

    $deployer = Deployer::get();
    var_dump($deployer->servers);

I can see 'staging.foo' does exist.

From reading the code the error is logic. In Collection the DotArray is implemented by exploding the lookup key and searching for some nested values. However I do see that in ServersCollection::collection the key is just used "as is" with the dot.

Changing private to protected for  ::collection in Collection() and overriding get() and  has()  in ServerColleciton does fix the problem for me. PR to follow.

**Comment by pniederlag** [comment]
Created PR https://github.com/deployphp/deployer/pull/913
