### ISSUE TITLE
First deploy deletes storage folder on laravel recipe.

### ISSUE THREAD

**Issue by henriquebremenkanp** [deployphp/deployer#875]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0
| Local Machine OS  | macOS Sierra PHP7
| Remote Machine OS | ubuntu 16.04 PHP7

#### Expected behavior
At first deploy, deployer should copy or move the contents of `storage` from the release to `shared/storage`.
#### Actual behavior
Deployer creates an empty `storage` folder and deletes/overwrites (idk) the `storage` folder we cloned.

#### Why is this a problem
1. Laravel blade stores cached files on `storage/framework/views`. If it does not exist, it raises an error.
2. Laravel default session driver (file) stores files on `storage/framework/sessions`, which also does not exist and raises an error.
3. Laravel default cache driver (file) stores files on `storage/framework/cache`, which also does not exist and raises an error.
4. We're missing the folder we usually want to symlink (`storage/app/public` to `public/storage`) as part of the default deploy.

The last folder we delete but it's not big deal is `storage/logs` because it creates itself when the first log entry appears. 

#### Create a new laravel project
composer create-project --prefer-dist laravel/laravel laravel
cd laravel

#### Init deployer
composer require deployer/deployer
vendor/bin/dep init
Chose 1 for Laravel recipe

#### Init git
git init
git add .
git commit -m "init"
git remote add origin git@github.com:you/repo.git
git push -u origin master

### Content of `deploy.php`
It is the default generated by `dep init`, just change the `set('repository', '')`, and server info to match valid settings.
```php
<?php
namespace Deployer;
require 'recipe/laravel.php';

// Configuration

set('repository', 'git@domain.com:username/repository.git');
add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Servers

server('production', 'domain.com')
    ->user('username')
    ->identityFile()
    ->set('deploy_path', '/var/www/domain.com');


// Tasks

desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
after('deploy:symlink', 'php-fpm:restart');

```

### Output log

✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:shared
✔ Executing task deploy:vendors
✔ Executing task deploy:writable
✔ Executing task deploy:symlink
✔ Executing task deploy:unlock
✔ Executing task cleanup
➤ Executing task artisan:cache:clear
Cache cleared successfully.
✔ Ok
➤ Executing task artisan:config:cache
Configuration cache cleared!
Configuration cached successfully!
✔ Ok
✔ Executing task success
Successfully deployed!

**Comment by elfet** [comment]
Fixed.

**Comment by pdbreen** [comment]
See also #896
