### ISSUE TITLE
[SF_RECIPE] Add conditional statement for composer options

### ISSUE THREAD

**Issue by rmasclef** [deployphp/deployer#878]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.0
| Local Machine OS  | Debian Jessie (8.6)
| Remote Machine OS | Debian Jessie (8.6)

### Description 
At this time, `composer_options` is automatically skipping dev dependencies with the `--no-dev` option.

When talking about `development` environments, I think that a lot of developers likes to have the `devDependencies` downloaded on the environment (for example to have the symfony debug toolbar ...).

At this time, if a developer wants this feature, he can override the `composer_options` in his deploy file like below :
```php
{...}

//Define composer option to add the dev dependancies when the dev environment is set
set(
    'composer_options',
    '{{composer_action}} --verbose --prefer-dist --no-interaction --optimize-autoloader'.
    get('env') !== 'dev' ? '--no-dev' : ''
);

{...}
```

The idea is to automatically add the composer dev dependencies to the project if the environment is set to a defined value ('dev', 'qualif', 'staging' ... to be defined).

Or we can imagine an option call `dev_environments`where the user define the environments where he wants dev dependencies to be deployed :)

**Comment by elfet** [comment]
What about overriding *composer_options* for that stage?
```php
server('beta', ...)
    ->stage('beta')
    ->set('composer_options', ' --verbose --prefer-dist --no-interaction --optimize-autoloader');
```

**Comment by rmasclef** [comment]
It will work, but if you have many stages in which you want to have dev dep, you will have to add this line of code for each of them ...

**Comment by elfet** [comment]
What about this?
```php
$composerOptions = 'composer_options', ' --verbose --prefer-dist --no-interaction --optimize-autoloader';

server('beta', ...)
    ->stage('beta')
    ->set($composerOptions);
```

**Comment by rmasclef** [comment]
Same answer, you still have a to had a `set($composerOptions)` to each environment you want to have the composer dev deps ...

_I think you forgot [] or array() to wrap the content of $composerOptions but I understood you._

**Comment by elfet** [comment]
I think its possible to create some think like stage files. I'll try to do it next version.
