### ISSUE TITLE
Parameter freezing step

### ISSUE THREAD

**Issue by player259** [deployphp/deployer#879]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
In case of strange environment parameters behavior (like #871) there should be declared parameter freezing step
Such unpredictable parameter evaluation can appear on task skipping or specific execution order
I'd suggest to use two-step deployment with preparing and execution as symfony container does (container compilation)
Symfony uses FrozenParameterBag (DependencyInjection component) to store parameters in runtime
And Deployer already has a part of described feature, Deployer::get()->config service, where parameters are defined before the real execution.

Other parameters, as "releases_list", should not be cached or freezed at all
After "cleanup", "deploy:release" tasks or other custom tasks, which do manipulations in releases folder, value of "releases_list" should be evaluated again

So parameter subsystem should became more transparent, predictive and determinate
By the way, i agreed with deprecating env()

And it will be great to use Config component to store servers.yml structure definition
Symfony\Component\Config\Definition\Processor
Symfony\Component\Config\Definition\Builder\TreeBuilder

**Comment by elfet** [comment]
It will be cool if "releases_list" did not freezes. What about some parameter?
```php
set('releases_list`, function () {
}, true); // true - not freeze
```

Or some method for recalling callback?

```php
fetch('releases_list'); // Recall callback and update config param.
```

**Comment by player259** [comment]
As some parameters are defined in third-party recipes, developer should not know how they are working.
Developer can miss the moment when parameter should be fetched again, or don't know that parameters were affected by his actions.
So, first solution seems more meanful.

**Comment by elfet** [comment]
Or maybe something like:
```php
factory('releases_list', ...);
```

**Comment by player259** [comment]
Yes, functions should stay small and simple. Another function to implement another behavior is the way to go.
But if you introduce factory() as runtime-evaluated parameter, set() should become once-evaluated non-runtime parameter, as opposite to factory(). And the expected way is on-the-start evaluation, just before the tasks.
I think it will be more clear for developers to have parameter initialization step. If keep thing as-is, it will be ambiguous and uncertain. In some cases there will be no difference what to use - factory() or set(), and this is not good.

**Comment by elfet** [comment]
I think freeze all parameters before every task is unproductive. It's slow down deployment process. 
Now is more like lazy evaluating params, which is familiar to many programmers. So, i think we don't need freezing step.

**Comment by player259** [comment]
Freeze parameters for the environment, not before every task.
"bin/git" will not be changed during deployment. Same thing for "release_name" and "release_path". They should be evaluated once. Their values depend on environment itself, but not previous task results. So you can freeze them on the start.

**Comment by elfet** [comment]
But what if user run task what does not required "release_name" or "release_path"?

**Comment by elfet** [comment]
After a lot of thinking I came out with idea what parameter freezing step not acceptable for current deployer implementation and recipes. Now there are lot of other task and flows in which freezing all parameters unnecessary, and declaring for each task what parameters are needed is a complicating. I think leave current implementation as is. Maybe do a little refactoring. Current implementation is simple and clear - think of it as lazy evaluation.

Things what maybe needed:
* Refactor `deploy:release` task, update `releases_list` correctly.
* Implement `refetch` fund which will be updating cache and return actual results.
* Add more configuration options for variables as `'no_cache' => true` and so on.
