### ISSUE TITLE
[SF_RECIPE] prevent removal of app_dev file for dev environment

### ISSUE THREAD

**Issue by rmasclef** [deployphp/deployer#880]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.0
| Local Machine OS  | Debian Jessie (8.6)
| Remote Machine OS | Debian Jessie (8.6)

### Description 

At this time, `deploy:clear_controllers` task automatically removes  `app_dev.php` file.

When talking about `development` environments, I think that a lot of developers likes to have access to the `app_dev.php` front controller in order to have the symfony errors displayed.

At this time, if a developer wants this feature for a server config having `dev` in the `env` variable, he can override the `deploy:clear_controllers` task in his deploy file like below :

### Content of `deploy.php`
```php
{...}

/**
 * @override deploy:clear_controllers
 * prevent removal of app_dev.php file for dev environment
 */
task('deploy:clear_controllers', function () {
    if (get('env') !== 'dev') {
        run('rm -f {{release_path}}/web/app_*.php');
    }
    run('rm -f {{release_path}}/web/config.php');
})->setPrivate();

{...}
```

The idea is to automatically prevent the removal of the app_*.php file if the environment is set to a defined value ('dev', 'qualif', 'staging' ... to be defined).

Or we can imagine an option call dev_environments where the user define the environments where he wants app_dev.php file to be deployed :)

**Comment by elfet** [comment]
I think it can be setup to clean_path config.

**Comment by rmasclef** [comment]
Do you mean `clear_paths` config or do you mean creating a new clean_path conf to handle this feature ?

**Comment by elfet** [comment]
Yes, `clear_path`.

**Comment by rmasclef** [comment]
Well in that case it won't work for sure :)

In fact, the `clear_paths` conf is only used on `deploy:clean` which is the last task to be called (so it is called **after** the `deploy:clear_controller` which is called right after `deploy:update_code`).

### Content of `common.php` line 514 to 522
```PHP
desc('Cleaning up files and/or directories');
task('deploy:clean', function () {
    $paths = get('clear_paths');
    $sudo  = get('clear_use_sudo') ? 'sudo' : '';

    foreach ($paths as $path) {
        run("$sudo rm -rf {{release_path}}/$path");
    }
});
```

### Content of `symfony.php` line 119 to 150
```PHP
/**
 * Remove app_dev.php files
 */
task('deploy:clear_controllers', function () {
    run('rm -f {{release_path}}/web/app_*.php');
    run('rm -f {{release_path}}/web/config.php');
})->setPrivate();

// Run after code is checked out
after('deploy:update_code', 'deploy:clear_controllers');

/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:create_cache_dir',
    'deploy:shared',
    'deploy:assets',
    'deploy:vendors',
    'deploy:assets:install',
    'deploy:assetic:dump',
    'deploy:cache:warmup',
    'deploy:writable',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])->desc('Deploy your project');
```

**Comment by rmasclef** [comment]
By the way, you've done a really great job on this app !! Congratulation :+1: :+1: :+1:

**Comment by elfet** [comment]
I think maybe to drop `deploy:clear_controllers` at all?

**Comment by rmasclef** [comment]
Nope, this task is useful for production environnement :)

**Comment by elfet** [comment]
Now you can override clear_path for your dev env.
```php
server('dev', ...)
    ->set('clear_path', []);
```

**Comment by rmasclef** [comment]
Great :+1:

**Comment by elfet** [comment]
Yes, tommorow
