### ISSUE TITLE
identity_file.public_key parameter not found

### ISSUE THREAD

**Issue by player259** [deployphp/deployer#881]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4
| Local Machine OS  | Ubuntu 15.10
| Remote Machine OS | Debian 8

### Description 
identity_file parameter not working as expected
Old config produces an error
```
Fatal error: Uncaught exception 'RuntimeException' with message 'Error processing servers: prod
Object `identity_file.public_key` does not exist in Collection.' in .../vendor/deployer/deployer/src/Bootstrap/BootstrapByConfigFile.php:161
```

This issue caused deprecating DotArray
Documentation
```
identity_file:
    public_key:  /path/to/public.key
    private_key: /path/to/private.key
    password:    optional-password-for-private-key-or-null
```
What actually works
```
identity_file: something-non-empty
identity_file.public_key:  /path/to/public.key
identity_file.private_key: /path/to/private.key
identity_file.password:    optional-password-for-private-key-or-null
```

Another bit of pain, that error message is hidden
vendor/deployer/deployer/src/Bootstrap/BootstrapByConfigFile.php line 160
```
} catch (\RuntimeException $e) {
    throw new \RuntimeException("Error processing servers: ".$name);
}
```
Please, remove try/catch block from BootstrapByConfigFile::parseConfig, ::initServers and ::initClusters
I think there should be more practical way to notify which server/cluster was failured, instead of supressing native exceptions

**Comment by elfet** [comment]
Try, will fix it.

**Comment by elfet** [comment]
Duplicate #873

**Comment by elfet** [comment]
Fixed, please check master branch.
