### ISSUE TITLE
Deprecated env() vs get()

### ISSUE THREAD

**Issue by baldurpan** [deployphp/deployer#882]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4
| Local Machine OS  | OS X 10.11.6
| Remote Machine OS | Debian

### Description 
I was just updating to version 4.0 from version 3.3 and noticed that the env() function has been deprecated. How can I now check which stage server (defined using setup()) is being used inside tasks?
In version 3.3 I was able to check like this:
```php
task('mytask', function(){

	if (env('server.host') == 'myawesome.server.com') {
		// Do something
	} else {
		// Do something else
	}

});
```

Now this doesn't work anymore and get('server.host') just returns an error:

*[RuntimeException]
  Configuration parameter `server.host` does not exists*

**Comment by elfet** [comment]
This is a bug, and will be fixed soon. Now you can use `get('server')['host']`.
Duplicate #873
