### ISSUE TITLE
Return process return code on "run" and "runLocally" so we can determine if the command completed successfully

### ISSUE THREAD

**Issue by infoeon** [deployphp/deployer#883]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
When calling the "run" or "runLocally" function it only returns the output of the command, not the return code or exit code.   The deploy should halt immediately if a process does not complete successfully  or we should be allowed to take different actions dependent on the return value.

**Comment by elfet** [comment]
Deployer will throw exception.
