### ISSUE TITLE
ssh_type has to be set before loading server list

### ISSUE THREAD

**Issue by NiR-** [deployphp/deployer#884]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0

Filled in as a question, since I'm not sure if `native` lacks some documentation or if there's some room for improvement.

### Description 
`ssh_type` has to be set **before** loading any server list or it is ignored and the default `phpseclib` is used.

### Content of `deploy.php`
```php
serverList('app/config/servers.yml');
set('ssh_type', 'native');
```

### Output log

```
$ bin/dep deploy:restart_workers preprod -vvv
➤ Executing task deploy:reload_workers
[preprod] > cd /home/user/my/website.fr && (sudo /usr/local/bin/supervisorctl restart my_worker)
PHP Notice:  Cannot connect to preprod-website:22. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/knplabs/projets/website/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1011
                                                  
  [RuntimeException]                              
  Unable to login with the provided credentials.
```

**Comment by elfet** [comment]
Yes, now ssh_type has to be set before loading server list. I think we need to update docs. Can you make PR?
