### ISSUE TITLE
SFTP support

### ISSUE THREAD

**Issue by tjbp** [deployphp/deployer#887]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Deployer doesn't appear to support SFTP. Sadly we're not always granted SSH access to servers we need to deploy to, and it's not immediately obvious in the docs that SSH access is required. Short of actually adding support, perhaps the Requirements section of the readme could include "SSH access" to save some of us the 15 minutes fishing around in Deployer's code to see what's possible? Happy to create a PR.

**Comment by elfet** [comment]
You can you upload/download function wich requires only sftp.
