### ISSUE TITLE
Call to undefined method Deployer\Server\Builder::set()

### ISSUE THREAD

**Issue by jdavidbakr** [deployphp/deployer#888]
The documentation refers to being able to call ->set() on a server but it throws an error.  (I tried version 4.0 but the set() function doesn't even appear to work there, I'm guessing the online docs are for 3.x)

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 3.3.0
| Local Machine OS  | OSX 10.12.1
| Remote Machine OS | Amazon Linux

### Description 
*If you're reporting a bug, please include following information*

### Steps to reproduce
server(...)
  ->set(...)

### Content of `deploy.php`
```php
set('seed',false);

server('live', '[redacted]', 22)
    ->user($user)
    ->identityFileAndPassword(null)
    ->stage('production')
    ->env('branch', 'develop')
    ->env('deploy_path', '/var/www/html/live');

server('beta', '[redacted]', 22)
    ->user($user)
    ->identityFileAndPassword(null)
    ->stage('production')
    ->env('branch', 'develop')
    ->env('deploy_path', '/var/www/html/beta');

server('sandbox', '[redacted]',22)
    ->set('seed',true)
    ->user($user)
    ->identityFile()
    ->stage('staging')
    ->env('branch','develop')
    ->env('deploy_path','/var/www/html/sandbox');

```

### Output log
PHP Fatal error:  Call to undefined method Deployer\Server\Builder::set() in /Users/jonb/Documents/Projects/move-3/deploy-script.php on line 25

**Comment by elfet** [comment]
It,s for 4. Will leave link to old docs on site.

**Comment by Hypnocrit** [comment]
This still seems to be a problem.  Not sure what to do about it.  The documentation for the project seems to be very out of date.  Following exactly the documentation to deploy 4.1 does not work; similar errors.    Trying it on 3.3 yields other problems.

**Comment by elfet** [comment]
I'm going to improve docs for sure.

**Comment by khromov** [comment]
Having same issue, is the documentation still out of date? 😢

**Comment by elfet** [comment]
Now docs sync with latest release 4.3.0.

**Comment by jdavidbakr** [comment]
I finally figured out  why this was happening to me - I had upgraded an existing deployer v3 to v4.  v4 is namespaced, so you must include the namespace in the deploy.php file (see the example).  I had completely overlooked this, once I added this I was able to start using v4.
