### ISSUE TITLE
Why artisan:migration are not done for Laravel? Despite the fact that it is present in laravel.fp?

### ISSUE THREAD

**Issue by kruteev** [deployphp/deployer#890]
Why artisan:migration are not done for Laravel? Despite the fact that it is present in laravel.fp?

**Comment by elfet** [comment]
`dep artisan:migrate`?

https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L54

**Comment by kruteev** [comment]
Separately prescribe? Is it possible to automate at deploy?

**Comment by elfet** [comment]
```php
after('deploy:update_code', 'artisan:migrate');
```

**Comment by kruteev** [comment]
Just right! And if you do rollback migration rollback will happen?

**Comment by elfet** [comment]
Only if you add it same way. Dealing with migrations may be tricky and everyone need to understand when and what you about to migrate.
