### ISSUE TITLE
Error when using Deployer with Laravel Valet

### ISSUE THREAD

**Issue by RicardoRamirezR** [deployphp/deployer#897]
I'm using [Laravel Valet](https://github.com/laravel/valet), I just tried to run ```dep deploy``` and got:
```bash
Fatal error: Cannot redeclare output() (previously declared in
~/.composer/vendor/laravel/valet/cli/includes/helpers.php:39) in
~/.composer/vendor/deployer/deployer/src/functions.php on line 520
```
What should I do?

**Comment by henriquebremenkanp** [comment]
Can you give us the steps to reproduce this error?
I guess you are globally requiring both valet and deployer?

**Comment by RicardoRamirezR** [comment]
Just global require both.

**Comment by henriquebremenkanp** [comment]
This is a known problem with composer global requires, they can conflict and it is still an unsolved issue. It is not unique to valet and deployer.

I would suggest you use the phar installation method.
https://github.com/deployphp/deployer/blob/master/README.md#installation

**Comment by RicardoRamirezR** [comment]
Yep, that worked form me, thank you.
