### ISSUE TITLE
Add a deploy:rollback for failing deploys

### ISSUE THREAD

**Issue by iDuuck** [deployphp/deployer#899]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.0.1
| Local Machine OS  | OS X
| Remote Machine OS | Ubuntu

### Description 
When deploying but something goes wrong, the deployment is locked and you cannot deploy until running `dep deploy:unlock` manually. What about unlocking automatically in an `deploy:rollback` task?

**Comment by iDuuck** [comment]
Or, just checked and an rollback task is already defined, but with another meaning. Would be also good to just add another hook on the `deploy:fail`  task to do `deploy:unlock` afterwards.

**Comment by elfet** [comment]
You can do it like this: 
```php
after('deploy:failed', 'deploy:unlock');
```

**Comment by iDuuck** [comment]
I know. But this is a feature request. Why not add this as a default?

**Comment by elfet** [comment]
Maybe it's should be by default. Need to think more on it.
