### ISSUE TITLE
Artisan optimize

### ISSUE THREAD

**Issue by rzb** [deployphp/deployer#900]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.1
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

Is there any reason not to include `artisan optimize` in the laravel recipe? I can easily do it on my own, just wondering.

Thanks.

**Comment by elfet** [comment]
I think it's better to include it by default. Can you make PR?
