### ISSUE TITLE
Rollback symlinks incorrectly every other rollback

### ISSUE THREAD

**Issue by kirkdocker** [deployphp/deployer#903]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0.1
| Local Machine OS  | Windows (git bash)
| Remote Machine OS | Ubuntu (vagrant)

### Description 
Performing multiple rollbacks causes the **current** symlink to not link correctly on every second rollback.

![deployer-rollback](https://cloud.githubusercontent.com/assets/9040251/20621380/2c26379e-b2f6-11e6-9f9d-68b6f14a626f.jpg)

### Steps to reproduce
Deploy application multiple times. Then perform a rollback. 

After each rollback, perform a **ls -al** on the destination server, app directory. The 'current' symlink fails on every other rollback. It links to the directory **3** for example, instead of **releases/3**. But on the next rollback it will link correctly.

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/laravel.php';

// Configuration

set('repository', 'git@git.SITE.com:kirk.docker/status-page.git');

server('vagrant', '127.0.0.1', '2222')
    ->user('vagrant')
    ->password('vagrant')
    ->set('deploy_path', '/var/www/local-status.SITE.com');
```

### Output log
```
$ dep rollback -vvv
Ô×ñ Executing task rollback
[vagrant] > cd /var/www/local-status.SITE.com && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (cd releases && ls -t -d */)
[vagrant] < 5/
[vagrant] < 4/
[vagrant] < 3/
[vagrant] < 2/
[vagrant] < 1/
[vagrant] > cd /var/www/local-status.SITE.com && (if [ -f .dep/releases ]; then echo "true"; fi)
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (tail -n 10 .dep/releases)
[vagrant] < 20161123143722,1
[vagrant] < 20161123144037,1
[vagrant] < 20161123144633,1
[vagrant] < 20161123144955,2
[vagrant] < 20161123151343,2
[vagrant] < 20161124165527,3
[vagrant] < 20161124165542,4
[vagrant] < 20161124165555,5
[vagrant] > cd /var/www/local-status.SITE.com && (if [[ "$(man ln)" =~ "--relative" ]]; then echo "true"; fi)
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (cd /var/www/local-status.SITE.com && ln -nfs --relative /var/www/local-status.SITE.com/releases/4 current)
[vagrant] > cd /var/www/local-status.SITE.com && (rm -rf /var/www/local-status.SITE.com/releases/5)
Rollback to `4` release was successful.
ÔÇó done on [vagrant]
Ô£ö Ok [518ms]

KirkD@HRT-PC07 MINGW64 /c/xampp/htdocs/status-page (deployment)
$ dep rollback -vvv
Ô×ñ Executing task rollback
[vagrant] > cd /var/www/local-status.SITE.com && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (cd releases && ls -t -d */)
[vagrant] < 4/
[vagrant] < 3/
[vagrant] < 2/
[vagrant] < 1/
[vagrant] > cd /var/www/local-status.SITE.com && (if [ -f .dep/releases ]; then echo "true"; fi)
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (tail -n 10 .dep/releases)
[vagrant] < 20161123143722,1
[vagrant] < 20161123144037,1
[vagrant] < 20161123144633,1
[vagrant] < 20161123144955,2
[vagrant] < 20161123151343,2
[vagrant] < 20161124165527,3
[vagrant] < 20161124165542,4
[vagrant] < 20161124165555,5
[vagrant] > cd /var/www/local-status.SITE.com && (if [[ "$(man ln)" =~ "--relative" ]]; then echo "true"; fi)
[vagrant] < true
[vagrant] > cd /var/www/local-status.SITE.com && (cd /var/www/local-status.SITE.com && ln -nfs --relative /var/www/local-status.SITE.com/releases/3 current)
[vagrant] > cd /var/www/local-status.SITE.com && (rm -rf /var/www/local-status.SITE.com/releases/4)
Rollback to `3` release was successful.
ÔÇó done on [vagrant]
Ô£ö Ok [545ms]
```

I've diffed the output and each rollback produces essentially identical info. Does this happen to anyone else, or is it something to do with my config?

**Comment by elfet** [comment]
Can't reproduce it locally. Can you debug it a little more? Please, add output of `releases_list` inside this task.

**Comment by kirkdocker** [comment]
I'm not entirely sure what you mean, so I did the following: (note that version numbers will be different than original post):

```php
desc('Get releases_list');
task('releases_list', function(){
    print_r(get('releases_list'));
});
```
I get the following output:

```dep releases_list local
Ô×ñ Executing task releases_list
Array
(
    [0] => 4
    [1] => 3
    [2] => 2
    [3] => 1.1
Ô£ö
```

Let me know  if you meant something else.

Thank you.

**Comment by elfet** [comment]
Hmmm, difficult to say. Maybe you can repeat all steps with this task to reproduce error?

**Comment by kirkdocker** [comment]
I've narrowed it down a bit. If I run the following code directly on the server this causes the 'flipping' behavior. 

`cd /var/www/local-status.SITE.com && (cd /var/www/local-status.SITE.com && ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 current)`

And if I narrow it down further to this part, the issue still happens:

`ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 current`

Those commands were taken directly from the debug output of the rollback command.

Results:

```
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ls -al
total 20
drwxrwxr-x 5 vagrant vagrant 4096 Nov 25 14:28 .
drwxr-xr-x 4 vagrant vagrant 4096 Nov 25 12:08 ..
lrwxrwxrwx 1 vagrant vagrant   12 Nov 25 14:28 current -> releases/1.1
drwxrwxr-x 2 vagrant vagrant 4096 Nov 25 14:10 .dep
drwxrwxr-x 4 vagrant vagrant 4096 Nov 25 14:22 releases
drwxrwxr-x 3 vagrant vagrant 4096 Nov 25 12:08 shared
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 current
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ls -al
total 20
drwxrwxr-x 5 vagrant vagrant 4096 Nov 25 14:28 .
drwxr-xr-x 4 vagrant vagrant 4096 Nov 25 12:08 ..
lrwxrwxrwx 1 vagrant vagrant    3 Nov 25 14:28 current -> 1.1
drwxrwxr-x 2 vagrant vagrant 4096 Nov 25 14:10 .dep
drwxrwxr-x 4 vagrant vagrant 4096 Nov 25 14:22 releases
drwxrwxr-x 3 vagrant vagrant 4096 Nov 25 12:08 shared
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 current
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ls -al
total 20
drwxrwxr-x 5 vagrant vagrant 4096 Nov 25 14:28 .
drwxr-xr-x 4 vagrant vagrant 4096 Nov 25 12:08 ..
lrwxrwxrwx 1 vagrant vagrant   12 Nov 25 14:28 current -> releases/1.1
drwxrwxr-x 2 vagrant vagrant 4096 Nov 25 14:10 .dep
drwxrwxr-x 4 vagrant vagrant 4096 Nov 25 14:22 releases
drwxrwxr-x 3 vagrant vagrant 4096 Nov 25 12:08 shared
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 current
vagrant@vagrant-ubuntu-trusty-64:/var/www/local-status.SITE.com$ ls -al
total 20
drwxrwxr-x 5 vagrant vagrant 4096 Nov 25 14:30 .
drwxr-xr-x 4 vagrant vagrant 4096 Nov 25 12:08 ..
lrwxrwxrwx 1 vagrant vagrant    3 Nov 25 14:30 current -> 1.1
drwxrwxr-x 2 vagrant vagrant 4096 Nov 25 14:10 .dep
drwxrwxr-x 4 vagrant vagrant 4096 Nov 25 14:22 releases
drwxrwxr-x 3 vagrant vagrant 4096 Nov 25 12:08 shared
```

So I guess it's an OS thing? I've no idea why this is happening. Any ideas?

Thanks

**Comment by elfet** [comment]
I think it maybe a `--relative` option. Please, try with `set('use_relative_symlink', false);`.

**Comment by kirkdocker** [comment]
Removing `--relative` fixes the issue on the command line.

I've just tried using deployer and this works correctly now as well.

Thanks for your help 👍

**Comment by elfet** [comment]
So it's bug then `--relative` is on. Will fix it.

**Comment by jordisala1991** [comment]
@kirkdocker can you try using this?

`ln -nfs --relative /var/www/local-status.SITE.com/releases/1.1 /var/www/local-status.SITE.com/current`

I tried to reproduce your issue but it was impossible to me using xenial-64. But when you do a release, a similar symlink is created, and that works for you right?

**Comment by kirkdocker** [comment]
@jordisala1991 Good catch with that one. 

`set('use_relative_symlink', false);`

fixed the issue for me.

Cheers.

**Comment by stz184** [comment]
Beware that -r is a GNUism, i.e. non POSIX so won't work in the OP case as the standard OS X ln command is BSD based.
Also, Ubuntu 14.04.5 LTS is still using coreutils 8.21-1ubuntu5.4
So, I am not sure how good idea is --relative option to be default one.

**Comment by elfet** [comment]
@stz184 deployer detect is system supports relative symlinks and then use it. Otherwise use in without this option.
