### ISSUE TITLE
Uncaught Error: Call to undefined function localServer()

### ISSUE THREAD

**Issue by acrozes** [deployphp/deployer#905]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0.1 or 4.0.2
| Local Machine OS  | Windows
| Remote Machine OS | N/A

$ php deployer.phar self-update

Fatal error: Uncaught Error: Call to undefined function localServer() in .\deploy.php:16
Stack trace:
#0 phar://./deployer.phar/bin/dep(106): require()
#1 .\deployer.phar(4): require('phar://...')
#2 {main}
  thrown in .\deploy.php on line 16

Same error with:
$ php deployer.phar -v
$ php deployer.phar --version

**Comment by elfet** [comment]
Add `namespace Deployer;` to `deploy.php`.
