### ISSUE TITLE
Authentication for Private Git Repos?

### ISSUE THREAD

**Issue by khoanguyen96** [deployphp/deployer#906]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question/Feature Request
| Deployer Version  | Latest?
| Local Machine OS  | Windows 7
| Remote Machine OS | Ubuntu

I was looking through documentation, but I can't find any way to specify a SSH key or username and password for a repository? I was trying to use the Laravel recipe if that helps.

**Comment by elfet** [comment]
You can use deployment keys for that: https://developer.github.com/guides/managing-deploy-keys/

**Comment by khoanguyen96** [comment]
Oh great! Thanks.. but how would I go about adding the deployment key to my deploy.php? I've looked through the deployer documentation, and haven't found anything..?

Sorry, if this is extremely simple...

**Comment by elfet** [comment]
If you usng deployment keys you need to do it only once. Another approach is using agent forwarding.

**Comment by khoanguyen96** [comment]
Thank you I got it!
