### ISSUE TITLE
`Release path does not found.` - even though release directory gets created.

### ISSUE THREAD

**Issue by jofrysutanto** [deployphp/deployer#909]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | Mac OS
| Remote Machine OS | Linux

### Description 

Going through the code, it suppose to continue when (`if [ -h ~/xxx.com/release ]; then echo 'true'; fi`):

```
    $releaseExists = run("if [ -h {{deploy_path}}/release ]; then echo 'true'; fi")->toBool();
    if (!$releaseExists) {
        throw new \RuntimeException(
            "Release path does not found.\n" .
            "Run deploy:release to create new release."
        );
    }
```

My console says it's returning true, but it still triggers the RuntimeException.

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/common.php';

// Configuration

set('repository', 'git@domain.com:username/repository.git');
set('shared_files', []);
set('shared_dirs', []);
set('writable_dirs', []);

// Servers

server('staging', 'xxx.com.au')
    ->user('xxx')
    ->password('xxx')
    ->set('deploy_path', 'xxx.com.au');


// Tasks

desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
after('deploy:symlink', 'php-fpm:restart');

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

after('deploy', 'success');
```

### Output log
...
• done on [staging]
✔ Ok [19s 488ms]
➤ Executing task deploy:update_code
[staging] > which git
[staging] < stdin: is not a tty
[staging] < /usr/bin/git
[staging] > stdin: is not a tty
/usr/bin/git version
[staging] < stdin: is not a tty
[staging] < bash: stdin:: command not found
[staging] < git version 1.7.1
[staging] > if [ -h ~/xxx.com/release ]; then echo 'true'; fi
[staging] < stdin: is not a tty
[staging] < true
➤ Executing task deploy:failed
• done on [staging]
✔ Ok [0ms]

  [RuntimeException]
  Release path does not found.
  Run deploy:release to create new release.

Exception trace:
 () at phar:///usr/local/bin/dep/recipe/deploy/release.php:83
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Server/Environment.php:126
 Deployer\Server\Environment->get() at phar:///usr/local/bin/dep/src/Server/Environment.php:176
 Deployer\Server\Environment->parseCallback() at n/a:n/a
 preg_replace_callback() at phar:///usr/local/bin/dep/src/Server/Environment.php:162
 Deployer\Server\Environment->parse() at phar:///usr/local/bin/dep/src/functions.php:676
 Deployer\parse() at phar:///usr/local/bin/dep/src/functions.php:286
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/update_code.php:59
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:91
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:79
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:186
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:110
 require() at /usr/local/bin/dep:4

**Comment by elfet** [comment]
It is because of `stdin: is not a tty`.
http://unix.stackexchange.com/questions/48527/ssh-inside-ssh-fails-with-stdin-is-not-a-tty

**Comment by jofrysutanto** [comment]
Doh! Thanks. Will dig around for the solution, cheers.

**Comment by elfet** [comment]
#910
