### ISSUE TITLE
Task "copy_dirs" deletes directories during the first deployment

### ISSUE THREAD

**Issue by sardoj** [deployphp/deployer#914]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.x
| Local Machine OS  | Ubuntu 14.04
| Remote Machine OS | Ubuntu 14.04

### Description 
During the first deployment, the task "copy_dirs" deletes directories.

### Content of `deploy.php`
```// Configuration
set('repository', '************');
set('shared_files', []);
set('shared_dirs', ['upload']);
set('writable_dirs', []);
set('copy_dirs', ['data']);
set('clear_paths', []);
set('keep_releases', 3);

// Servers
serverList('servers.yml');

//Deploy
desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:copy_dirs',
    'deploy:shared',
    'deploy:writable',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);
```

### Output log
[site] > if [ -d $(echo /var/www/html/site/releases/1/data) ]; then rm -rf /var/www/html/site/**releases/1**/data; fi

[site] > if [ -d $(echo /var/www/html/site/current/data) ]; then cp -rpf /var/www/html/site/current/data /var/www/html/site/**releases/1**/data; fi

**Comment by elfet** [comment]
Fixed b37e7351a27bf3fee64ce02e2d00981f417f575e
