### ISSUE TITLE
laravel migrate show error release path does not found

### ISSUE THREAD

**Issue by nyrf** [deployphp/deployer#920]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0.2
| Local Machine OS  | OS X 10.12.1
| Remote Machine OS | ubuntu 14.04

### Description 
After deploy, run `dep artisan:migrate`

### Output log
*  [RuntimeException]
  Release path does not found.
  Run deploy:release to create new release.*

**Comment by elfet** [comment]
This task can be called only during deployment process:
```php
before('deploy:symlink', 'artisan:migrate');
```
Maybe it's should be able to run it separately.  @deployphp/maintainer ?

**Comment by nyrf** [comment]
@elfet It works, thanks.
