### ISSUE TITLE
Wordpress recipe should include wp-content/uploads as shared folder?

### ISSUE THREAD

**Issue by craigharman** [deployphp/deployer#926]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Can I suggest that the wordpress recipe creates the wp-content/uploads folder as a shared/writable folder by default? I would assume best practice would be to not have this committed in source control and it is easier to remove (by putting in a blank shared_files setting) than it is to add (having to rewrite the entire recipe).

**Comment by elfet** [comment]
What about adding this?
```php
add('shared_dirs', ['wp-content/uploads']);
```

**Comment by craigharman** [comment]
I tried that, but the Wordpress recipe doesn't run the deploy:writable or deploy:shared tasks so it didn't work. I recreated the recipe as follows:

set('shared_dirs', ['wp-content/uploads']); 
set('writable_dirs'. ['wp-content/uploads']); 

task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
])->desc('Deploy your project');
