### ISSUE TITLE
Mercurial support?

### ISSUE THREAD

**Issue by curious-jim** [deployphp/deployer#928]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | master
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Is there a way to use it with Mercurial(hg) repo?

repository is mandatory in configuration, and it only accepts git, as I can see, but what to do, if I don't use git?

**Comment by elfet** [comment]
I have plans to add support for other vcs.

**Comment by pluseg** [comment]
@curious-jim What kind of branching do you use? Common branches or bookmarks?

**Comment by curious-jim** [comment]
I use common branches

**Comment by elfet** [comment]
I think we can come in form of recipe, or plugin.

**Comment by pluseg** [comment]
@elfet Mercurial is DVCS as git and have almost same API: `pull`, `push`, `clone`, `merge`, `branch`, `hg update` equals `git checkout`. So I guess that it'd better just create VcsInterface and GitVcs, MercurialVcs, etc. Also we can define concrete vcs type by `repository` env parameter. What do you think about it?

**Comment by elfet** [comment]
@pluseg nice idea, let me think about it a while. PS. interesting how this done in capistrano and ansible.

**Comment by bolechen** [comment]
+1

**Comment by curious-jim** [comment]
any news?

**Comment by antonmedv** [comment]
Now you can override `deploy:update_code` with you own strategy: 

```php
task('deploy:update_code', function () {
    run('hg clone {{repository}} {{release_path}}');
});
```

**Comment by curious-jim** [comment]
Tested, working great. Thanks
