### ISSUE TITLE
Why  deployer/phar-update as dependency?

### ISSUE THREAD

**Issue by ceesvanegmond** [deployphp/deployer#929]
| Q                 | A
| ----------------- | ---
| Issue Type        |Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Mac Sierra
| Remote Machine OS | Ubuntu 16

### Description 
Just a question, why is deployer/phar-update a dependency of this specific project? For instance when using a other framework than Symfony, you might not need phar-update. 

Is there an specific reason for this?

**Comment by elfet** [comment]
It's used only when deployer is a phar.

**Comment by ceesvanegmond** [comment]
But why is it a 'requirement'? I think it needs to be an suggestion instead of a require. Don't you think? In this case, I got installation errors, because of an interfering package  ```justinrainbow/json-schema``` because this is used by ```herrera-io/json``` which is ultimatly used by ```deployer/phar-update```.

Don't you think it's better to suggest instead of require this ```phar-update``` package? It is optional though.

**Comment by elfet** [comment]
Yes, i think it's better to move it to suggests. Will do it in next release. For now you can use phar version.
