### ISSUE TITLE
executing dep deploy failed

### ISSUE THREAD

**Issue by iserifith** [deployphp/deployer#930]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | N/A
| Local Machine OS  debian 8
| Remote Machine OS | debian 8

### Description 
*If you're reporting a bug, please include following information*

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/laravel.php';

// Configuration
set('repository', 'git@github.com:iserifith/monash-main.git');

add('shared_files', []);
add('shared_dirs', []);

add('writable_dirs', []);

// Servers

server('localhost', 'http://144.xxx.xx.255/')
    ->user('serah')
    ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'mypass')
    ->set('deploy_path', '/var/www/lar');


// Tasks

desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
after('deploy:symlink', 'php-fpm:restart');
```

### Output log
*With enabled option for verbose output `-vvv`.*
Shell on your server is not POSIX-compliant. Please change to sh, bash or similar.  
  Usually, you can change your shell to bash by running: chsh -s /bin/bash            
✔                                                                                     ➤ Executing task deploy:failed

                                                  
  [RuntimeException]                              
  Unable to login with the provided credentials. 

Am i missing something here?

**Comment by elfet** [comment]
> Unable to login with the provided credentials.

**Comment by iserifith** [comment]
i assume its this right `>identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', 'mypass'` ? 
does those file already there or i need to create it? sorry for the dumb questions

**Comment by elfet** [comment]
Try login to server with ssh.

**Comment by mathbr** [comment]
Please reduce the host to its name (or IP address in your case), there should not be a scheme here.

**Comment by premkritin** [comment]
how this issue was resolved?
