### ISSUE TITLE
Optional SSH agent forwarding

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#932]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | v4.0.2
| Local Machine OS  | Ubuntu Trusty
| Remote Machine OS | Ubuntu Trusty

### Description 

I'd like to ask how I could make SSH agent forwarding optional.

Background: we usually run our deployments from our CI which sets up an SSH agent for SSH connections. For this we need to invoke `server(...)->forwardAgent()`. However, we also want to be able to perform deployments from developer machines in some cases where there is no SSH agent. If we keep the forwarding we'll get the following error:

```
Notice: SSH_AUTH_SOCK not found in /.../phpseclib/phpseclib/phpseclib/System/SSH/Agent.php on line 130
```

Which makes sense since no SSH agent was set up.

With the current fluid interface for server configuration there is no way to enable SSH agent forwarding optionally, e.g. by checking if the environment variable `SSH_AUTH_SOCK` is non-empty. Having a way to achieve this would be useful.

An alternative approach would be checking `SSH_AUTH_SOCK` within `forwardAgent()` and skipping the configuration change if it is empty. This way the previously set authentication method (password, identity file, etc.) will be used instead.

**Comment by elfet** [comment]
What about this?
```php
$prod = server(...);

if (!$_ENV['CI']) {
    $prod->forwardAgent();
}
```

**Comment by mbrodala** [comment]
Yes, I thought about this but it's not a perfect solution since I need to do this for every server and it derives from the fluid interface for server configuration. I'll work with something like this for now:

```php
use Deployer\Server\Configuration;
use Deployer\Server\ServerInterface;
use Deployer\Task\Context;

desc('Activate SSH agent forwarding if possible');
task('config:ssh:agent', function() {
  if (empty(getenv('SSH_AUTH_SOCK'))) {
    return;
  }

  /** @var ServerInterface */
  $server = Context::get()->getServer();
  /** @var Configuration */
  $config = $server->getConfiguration();
  $config->setAuthenticationMethod(Configuration::AUTH_BY_AGENT);
});
```

Now I can simply add the `config:ssh:agent` task to my `deploy` task group and don't have worry about this anymore.

Do you see a potential issue with this solution in some scenarios?

**Comment by elfet** [comment]
It depends on you.

**Comment by mbrodala** [comment]
Nice one. ;-)

OK, I'll close this one since the task solution works for me.

**Comment by mbrodala** [comment]
This can be fixed also by switching to `native_ssh` for `ssh_type`, see #980

**Comment by elfet** [comment]
Also can be configured via .ssh/config for native ssh.
