### ISSUE TITLE
Clone from local repository

### ISSUE THREAD

**Issue by SliceOfLife** [deployphp/deployer#936]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | Deployer version 4.0.2
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Content of `deploy.php`
```php
set('repository', '/Users/user/work/project/.git');
```

### Output log
  [RuntimeException]                                                      
  fatal: repository '/Users/user/Sites/torrents/www/.git' does not exist 

I want to clone files from local repository, but I can't do this, because git command run on remote server.

**Comment by elfet** [comment]
You can't do this, because git command run on remote server.

**Comment by SliceOfLife** [comment]
Yes, I can't do this, because git command run on remote server.

**Comment by SliceOfLife** [comment]
But I want do this!
