### ISSUE TITLE
deploying on same server but different deploy path

### ISSUE THREAD

**Issue by jainabhishek14** [deployphp/deployer#938]
| Q  | A
| ----------------- | ---
| Issue Type      | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

### Description 
I have to deploy a project on different path on a single server. But following error occurs
`[RuntimeException]                                      
  Configuration parameter deploy_path does not exists.`

### Steps to reproduce

`dep -v deploy_review`
### Content of `deploy.php`
```php
namespace Deployer;
require 'recipe/yii.php';

date_default_timezone_set('Etc/UTC');
// Configuration
set('ssh_type','phpdeclib');
set('repository', xxxxxxxxx@xxxxxxx:xxxxxxxxx.git);
set('keep_releases', 10);
add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Tasks
task('deploy_review', [
    'deploy:setreview',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:config',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'current',
    'success',
])->desc('Deploy your project');


task('deploy_staging', [
    'deploy:setstaging',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:config',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'current',
    'success',
])->desc('Deploy your project');

task('deploy_production', [
    'deploy:setproduction',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:config',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'current',
    'success',
])->desc('Deploy your project');


task('deploy:setstaging',function () {
   //set('default_stage', 'staging');
    $server = server('abcde','domain.com')
            ->forwardAgent()
            ->user('root')
            ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa',null)
            ->stage('staging')
            ->set('deploy_path', '/deploy_path/');
});

task('deploy:setreview',function () {
    set('default_stage', 'review');
    server('abcde','domain.com')
            ->forwardAgent()
            ->user('root')
            ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa',null)
	    ->set('deploy_path', '/path_for_review/')
	    ->stage('review');
	    
});

task('deploy:setproduction',function () {
    set('default_stage', 'production');
    server('abcde','domain.com')
            ->forwardAgent()
            ->user('root')
            ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa',null)->stage('production')->set('deploy_path', '/path_for_production/');
});


task('deploy:config',function () {
    writeln('<info>Deploying...</info>');
    $deployPath = get('deploy_path');
    $releasePath = get('release_path');
    run("mkdir {$releasePath}/ipuser/assets");
    run("chown -R www-data:www-data {$releasePath}/ipuser/assets");
    run("chown -R www-data:www-data {$releasePath}/ipuser/protected/runtime");
    run("mkdir {$releasePath}/ipadmin/assets");
    run("chown -R www-data:www-data {$releasePath}/ipadmin/assets");
    run("chown -R www-data:www-data {$releasePath}/ipadmin/protected/runtime");
});
```

### Output log
*With enabled option for verbose output `-vvv`.*
➤ Executing task deploy:setreview
• done on [localhost]
✔ Ok [1ms]
➤ Executing task deploy:prepare
[localhost] > echo $0
[localhost] < sh

                                                          
  [RuntimeException]                                      
  Configuration parameter `deploy_path` does not exists.  
                                                          

Exception trace:
 () at phar:///usr/local/bin/dep/src/Server/Environment.php:132
 Deployer\Server\Environment->get() at phar:///usr/local/bin/dep/src/Server/Environment.php:176
 Deployer\Server\Environment->parseCallback() at n/a:n/a
 preg_replace_callback() at phar:///usr/local/bin/dep/src/Server/Environment.php:162
 Deployer\Server\Environment->parse() at phar:///usr/local/bin/dep/src/functions.php:676
 Deployer\parse() at phar:///usr/local/bin/dep/src/functions.php:286
 Deployer\run() at phar:///usr/local/bin/dep/recipe/deploy/prepare.php:34
 Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:91
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:79
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:186
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:110
 require() at /usr/local/bin/dep:4

**Comment by elfet** [comment]
Configure  2 `server`s.

**Comment by jainabhishek14** [comment]
already configured different servers in deploy:setstaging, deploy:setreview, deploy:setproduction tasks

**Comment by elfet** [comment]
Configure them on first level. Not in tasks.

**Comment by jainabhishek14** [comment]
how can i configure multiple servers at first level and use them in tasks?

**Comment by elfet** [comment]
`dep task server`
