### ISSUE TITLE
Unable to Upload file to server using Deployer.

### ISSUE THREAD

**Issue by ahmedkhan847** [deployphp/deployer#939]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Debian
| Remote Machine OS | Debian

### Description 
I am trying to upload a single file from my local Debian DigitalOcean server to remote DigitalOcean server. It shows me message, that upload is done but I wasn't able to find the file on server. I am testing it on Cloudways.

### Steps to reproduce
`php vendor/bin/dep deploy`
### Content of `deploy.php`
```php
<?php
namespace Deployer;
require "vendor/autoload.php";

set('default_stage', 'production');
server('production', '')
    ->user('')
    ->password('')
    ->set('deploy_path', '/home/master/applications/ptansjptmq/public_html/deployit')	
    ->stage('production');

task('deploy', function () {
$deployPath = get('deploy_path');
     upload("composer.json", "{$deployPath}/");
        
}); 
```

### Output log
*With enabled option for verbose output `-vvv`.*
➤ Executing task deploy
Upload file composer.json to /home/master/applications/ptansjptmq/public_html/deployit/
✔ Ok

**Comment by elfet** [comment]
Do you run on `php vendor/bin/dep deploy` on your "local Debian DigitalOcean"?

**Comment by ahmedkhan847** [comment]
Yes I have done that too.

**Comment by elfet** [comment]
Need more info. Uploads works for me and for a lot of other people too.

**Comment by ahmedkhan847** [comment]
Which type of information? I have attached full output and my code. Server in which I am trying to upload file doesn't allow me root  access.

**Comment by elfet** [comment]
I try upload file from my local Debian to Debian at DigitalOcean and everything works fine.

**Comment by ahmedkhan847** [comment]
can you help me figure out why it is not working for me?

**Comment by pdbreen** [comment]
You may have commented out in initial report for privacy, but your server() declaration has no host set which would deploy the file locally I believe.  So, check on local host for /home/master/... If found, review server declaration for proper config.

**Comment by ahmedkhan847** [comment]
@pdbreen I haven't added my Server IP and its credentials here.
