### ISSUE TITLE
Using GPG signatures

### ISSUE THREAD

**Issue by oanhnn** [deployphp/deployer#940]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Using GPG signatures for release.
And support install with [PHIVE](https://phar.io/)

Ref:
https://akrabat.com/using-phive-to-manage-phpunit/

**Comment by elfet** [comment]
Phive now in really development stage. There is no docs about installation or adding own phar. 

But adding GPG signatures is a good idea. Now we have only SHA1, and i'm looking forwart to adding GPG to releases.

**Comment by elfet** [comment]
What to sign with GPG? tag or phar archive?

**Comment by antonmedv** [comment]
No need for this right now. There is sha1 anyway. Maybe will return to this later.

**Comment by thomasweinert** [comment]
Please reconsider. Phive is not yet 1.0, but it works quite well and it simplifies the tools management a lot. Basically you end up with:

```
git checkout someproject.git
cd someproject
phive install
tools/dep target
```

No need to know which tools in which version the project needs any more. Unlike composer it avoids conflicts between the tool and project classes. It will verify the signatures of each tool before installing.

What you would need to do:

1. Sign the phar (I suggest adding a task for that to the project :-) )
`gpg -u john@example.com --detach-sign --output deployer.phar.asc deployer.phar`
2. Upload the phar to 
`https://deployer.org/deployer.phar.asc`

This would allow to install the phar using 
`phive install https://deployer.org/deployer.phar`

Optionally, add the phar and the signature to the GitHub release. Phive can use the GitHub 
as a repository for released versions. It simplifies the installation to:

`phive install deployphp/deployer`

**Comment by antonmedv** [comment]
Ok, will reconsider it. Also did you know what we have distributed version of deployer? 
https://packagist.org/packages/deployer/dist

**Comment by antonmedv** [comment]
Digged a little bit GPG signing. Really complicated and how do you verify public keys? :) 
Even if GPG adds more security, how many deployer’s users are into that stuff? 
Can we rely on https and sha1(can be updated) signing?

**Comment by aaa2000** [comment]
I am also interested to use Phive to install deployer

Maybe this article https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd can help you.
