### ISSUE TITLE
Deploy From Dev Machine's Local Git Repo

### ISSUE THREAD

**Issue by thomaskonrad** [deployphp/deployer#943]
Hi,

instead of checking out a Git repo on the remote machine, I'd like to [archive](https://git-scm.com/docs/git-archive) a specific branch or tag on my dev machine and then deploy it on the server (upload it from my dev machine). The thing is that my web server does not have access to my internal Git repository, so there is no way for me to let the remote server check out the code itself.

Is this possible with Deployer right now? I did not find any corresponding configuration directives.

Thank you
Thomas

**Comment by elfet** [comment]
Take a look at https://deployer.org/recipes/local

**Comment by fnagel** [comment]
@antonmedv Has this recipe been renamed? Link is dead.
