### ISSUE TITLE
Deploy Specific Git Tag (Instead Of Branch)

### ISSUE THREAD

**Issue by thomaskonrad** [deployphp/deployer#944]
Hi,

is it possible to deploy a specific Git _tag_ instead of a _branch_? I usually tag stable releases with a Git tag and then continue working on the same branch, so the latest commit on that branch might not be stable any more.

Thanks
Thomas

**Comment by elfet** [comment]
`--revision` option. I think we need better docs here. @thomaskonrad can you make PR to docs?

**Comment by pluseg** [comment]
@elfet Sent PR to docs, please review.

**Comment by elfet** [comment]
Merged.
