### ISSUE TITLE
variable collision from deploy.php

### ISSUE THREAD

**Issue by glensc** [deployphp/deployer#951]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | v4.0.2
| Local Machine OS  | Linux
| Remote Machine OS | N/A

### Description 

deployer entrypoint [bin/dep](https://github.com/deployphp/deployer/blob/v4.0.2/bin/dep) should protect itself from variable and function collisions.

at least it must not rely on any variable after reading user `deploy.php`:
- [bin/dep:107](https://github.com/deployphp/deployer/blob/v4.0.2/bin/dep#L107)

also shouldn't expose it's internals to user `deploy.php` either.

i suggest to move everything to a class under `Deployer` namespace.

### Content of `deploy.php`
```php
<?php
$deployer = null;
```

### Output log
*With enabled option for verbose output `-vvv`.*

```
$ deployer.phar -vvv
PHP Fatal error:  Call to a member function run() on null in phar:///home/glen/deployer.phar/bin/dep on line 110

$ ./vendor/bin/dep -vvv
PHP Fatal error:  Call to a member function run() on null in /home/glen/vendor/deployer/deployer/bin/dep on line 111
```

**Comment by elfet** [comment]
So it's only $deployer var is out there? What about renaming to $__deployer__?
Or just use Deployer::get()->run();

**Comment by glensc** [comment]
yes, for now `$deployer` may be overwritten by user code. but in the future there may be more. also the second point that user code should not access internal variables.
