### ISSUE TITLE
Reconfigure tasks

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#954]
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | 4.0.2
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

It would be useful if there was an API to reconfigure existing tasks. Right now if one wants to e.g. limit execution of a task from a recipe to a limited set of servers, one has to do something like this:

```php
desc('Limit foo task to selected servers');
task('config:foo:bar', function() {
  $deployer = Deployer::get();
  $task = $deployer->tasks->get('foo:bar');
  $task->onlyOn([
    'server1',
    'server2',
  ]);
});
before('foo:bar', 'config:foo:bar');
```

I could imagine an API like this instead:

```php
task('foo:bar')->onlyOn([
  'server1',
  'server2',
]);
```

(Same goes for all other methods of the `Task` class.)

This would mean that the `$body` of `task()` would become optional. If called with only the task name, the `Task` object would be returned if present.

What do you think?

**Comment by elfet** [comment]
I think reconfiguring tasks on runtime is bad idea. Why you need it for?

**Comment by mbrodala** [comment]
I gave an example above: a task bundled with a recipe should only be executed for a selected list of servers (or stages). To be specific its a task which should clear the PHP opcode cache and that doesn't work on all of our servers. Thus we limit the task to the servers where it works. Yes, the original issue is the broken servers but sometimes we don't have a choice and thus try to work with it as good as possible.

And yes, I understand that reconfiguring tasks at runtime can have bad side effects.

Do you have another idea how we could solve our (and similar) issues?

**Comment by elfet** [comment]
I think API like this `task('foo:bar')` is okay. Need to think a little bit more about corner cases.

Also did you try this?

```php
task('foo:bar:part', ['foo:bar'])->onlyOn([
  'server1',
  'server2',
]);
```

Using group tasks for this?

**Comment by mbrodala** [comment]
Your suggestion sounds useful and would at least reduce the visual overhead, I'll try that.

**Comment by elfet** [comment]
I will add this solution to docs later.

**Comment by mbrodala** [comment]
@elfet I just notice that this is not possible actually since group tasks [cannot be configured like this](https://github.com/deployphp/deployer/blob/d2cbc89da3b51963767aeaa5dbd3f92992ddbd25/src/Task/GroupTask.php#L49).

Do you think it would be possible to allow this for group tasks? Otherwise I'd have to stick to my original attempt, unless task reconfiguration is added.

**Comment by elfet** [comment]
@mbrodala can you describe when you want to configure tasks? At what point and based on what data?

**Comment by mbrodala** [comment]
@elfet I think I made this clear by now. ;-) We have some tasks (e.g. PHP Opcache reset) which are included from recipes but should only run on a few selected servers since e.g. reset does not work on the other servers.

**Comment by elfet** [comment]
Ok, so this kind of API will be usable here:
```php
task('deploy:opcache')->onlyOn([
  'server1',
  'server2',
]);
```

**Comment by mbrodala** [comment]
Yeah, that's my suggestion. I can add a PR if you think this could go in.

**Comment by elfet** [comment]
Yes, i think lest give it a try)

**Comment by pluseg** [comment]
@elfet @mbrodala guys, I guess the issue can be closed, doesn't it?

**Comment by elfet** [comment]
True

**Comment by torinaki** [comment]
```
task('deploy:opcache')->onlyOn([
  'server1',
  'server2',
]);
```
got following error:
```
PHP Warning:  Missing argument 2 for Deployer\task(), called in 
```

**Comment by mbrodala** [comment]
@torinaki There is no release of Deployer which includes [this change](https://github.com/deployphp/deployer/commit/c37237da8853cb23934e8cbb93441f6e026037f5) yet.

**Comment by torinaki** [comment]
@mbrodala but offical documentation already contains this changes:
![image](https://cloud.githubusercontent.com/assets/1269372/23355964/c6daaea8-fce0-11e6-8b3c-6560e932a65c.png)
https://deployer.org/docs/tasks

**Comment by mbrodala** [comment]
Yeah, because there is only one branch (`master`) in that repository. @elfet Maybe this should be changed?

**Comment by elfet** [comment]
Yes, i really wan't to do something with this, maybe have two branches, published and master.
