### ISSUE TITLE
Zero downtime?

### ISSUE THREAD

**Issue by dmarklund** [deployphp/deployer#959]
Is a new deployment made with zero downtime?

**Comment by elfet** [comment]
Yes, deployer use atomic symlink switching.

**Comment by dmarklund** [comment]
Fantastic!

**Comment by elfet** [comment]
🍪

**Comment by philixxx** [comment]
And about the data migration ? 
Data migration take time and it has been launched before the symlink switching. 
An user can use the "older code" with the new database model right ?

**Comment by elfet** [comment]
@philixxx database migration always tricky one. And you have to plan your own migration strategy. Basically migrations should not bring breaking changes, so old code will work. If you change you database with some BC you should turn on some maintaince mode or split it into a few smaller what will be easy to apply.
