### ISSUE TITLE
Using Deployer on Windows

### ISSUE THREAD

**Issue by fede91it** [deployphp/deployer#960]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0.2
| Local Machine OS  | Windows 10 LTSB x64
| Remote Machine OS | Linux

### Description 

The *deploy_path* folder esists but at it's inside no files or folders was created after run `dep deploy`. 

### Steps to reproduce

1. Executed `dep init -t Laravel`
2. Changed *repository* setting,.
3. Added *ssh_type* setting to native (the only that works on Windows)
4. Updated *server* details and used *forwardAgent*
5. Run `dep deploy -vvv`

### Content of `deploy.php`
```php
<?php
namespace Deployer;
require 'recipe/laravel.php';

// Configuration

set('repository', 'git@bitbucket.org:fede91it/thejuicesqueezer-laravel.git');
set('ssh_type', 'native');

add('shared_files', []);
add('shared_dirs', []);

add('writable_dirs', []);

// Servers

server('production', '77.104.141.250', 18765)
    ->user('thejuice')
    ->set('deploy_path', '~/public_html/_deployer')
    ->forwardAgent();

// Tasks

desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
after('deploy:symlink', 'php-fpm:restart');
```

### Output log

```
Ô×ñ Executing task deploy:prepare
[production] > echo $0
[production] < bash
[production] > if [ ! -d ~/public_html/_deployer ]; then mkdir -p ~/public_html/_deployer; fi
[production] > if [ ! -L ~/public_html/_deployer/current ] && [ -d ~/public_html/_deployer/current ]; then echo true; fi
[production] > cd ~/public_html/_deployer && if [ ! -d .dep ]; then mkdir .dep; fi
[production] > cd ~/public_html/_deployer && if [ ! -d releases ]; then mkdir releases; fi
[production] > cd ~/public_html/_deployer && if [ ! -d shared ]; then mkdir shared; fi
ÔÇó done on [production]
Ô£ö Ok [6s 50ms]
Ô×ñ Executing task deploy:lock
[production] > if [ -f ~/public_html/_deployer/.dep/deploy.lock ]; then echo 'true'; fi
[production] > touch ~/public_html/_deployer/.dep/deploy.lock
Ô×ñ Executing task deploy:failed
ÔÇó done on [production]
Ô£ö Ok [0ms]


  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "ssh -A -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p "18765" "thejuice@77.104.141.250" "touch ~/public_html/_deployer/.dep/deploy.lock"" failed.
  Exit Code: 1(General error)
  Working directory: D:\Progetti\laravel-thejuicesqueezer
  Output:
  ================
  Error Output:
  ================
  touch: cannot touch `/home/thejuice/public_html/_deployer/.dep/deploy.lock': No such file or directory


Exception trace:
 () at D:\Progetti\laravel-thejuicesqueezer\vendor\symfony\process\Process.php:232
 Symfony\Component\Process\Process->mustRun() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\Server\Remote\NativeSsh.php:74
 Deployer\Server\Remote\NativeSsh->run() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\functions.php:310
 Deployer\run() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\recipe\deploy\lock.php:20
 Deployer\{closure}() at n/a:n/a
 call_user_func() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\Task\Task.php:91
 Deployer\Task\Task->run() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\Executor\SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\Console\TaskCommand.php:79
 Deployer\Console\TaskCommand->execute() at D:\Progetti\laravel-thejuicesqueezer\vendor\symfony\console\Command\Command.php:261
 Symfony\Component\Console\Command\Command->run() at D:\Progetti\laravel-thejuicesqueezer\vendor\symfony\console\Application.php:817
 Symfony\Component\Console\Application->doRunCommand() at D:\Progetti\laravel-thejuicesqueezer\vendor\symfony\console\Application.php:185
 Symfony\Component\Console\Application->doRun() at D:\Progetti\laravel-thejuicesqueezer\vendor\symfony\console\Application.php:116
 Symfony\Component\Console\Application->run() at D:\Progetti\laravel-thejuicesqueezer\vendor\deployer\deployer\src\Deployer.php:186
 Deployer\Deployer->run() at C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\bin\dep:111

deploy [-p|--parallel]
```

**Comment by elfet** [comment]
Try replace `set('deploy_path', '/home/thejuice/public_html/_deployer')` with `set('deploy_path', '~/public_html/_deployer')` full path

**Comment by fede91it** [comment]
Same issue

**Comment by elfet** [comment]
Check what /home/thejuice/public_html/_deployer/.dep exists.

**Comment by fede91it** [comment]
Doesn't exists, but if I create by myself I get an error on dep deploy

**Comment by elfet** [comment]
But `~/public_html/_deployer` was created? Try run all same commands manually from ssh (from log)

**Comment by fede91it** [comment]
Running commands one-by-one works and .dep folder was created and deploy.lock is correctly touched. So via dep deploy the commands seems to be executed in a dry running

**Comment by elfet** [comment]
Try switch ssh_type to native.

**Comment by fede91it** [comment]
I already use native ssh_type, look at deploy.php

**Comment by picks44** [comment]
I have the same issue [#925](https://github.com/deployphp/deployer/issues/925) but it was closed without any support. Hopefully you'll be luckier.

**Comment by elfet** [comment]
Will try to run it on windows. How do you install php where?

**Comment by fede91it** [comment]
The simpler way is to download XAMPP and you have PHP ready to use.

**Comment by fede91it** [comment]
Any news?

**Comment by elfet** [comment]
Now dont have time, will try to end of week

**Comment by pluseg** [comment]
@fede91it Hi Federico! Do you still face the issue? Can you run `touch ~/public_html/_deployer/.dep/deploy.lock` manually as `thejuice` user?

**Comment by picks44** [comment]
@fede91it how do you make deployer.phar executable as "dep" on Windows ?

**Comment by elfet** [comment]
@picks44 `php deployer.phar`

**Comment by picks44** [comment]
@elfet yes, this is what I do to execute Deployer so far, but I wanted to know if there xas a way to "shortcut" this as "dep" like on a Linux machine.

**Comment by picks44** [comment]
Anyway I have the same issue, seems like Deployer is not creating anything on the production server when executing `php dep deploy -vvv`.

**Comment by siklr** [comment]
@picks44 I'm experiencing the same issue, and it seems like this might be due to a poor usage of touch, as it's not designed to create directories on its own. In my case, if I try and run touch /home/<user>/.dep/deploy.lock on the server, I'm greeted by an error saying no such file or directory.

**Comment by FredoVelcro** [comment]
Hello,
Same issue, same env, .dep/ dir is not created on the server...

**Comment by antonmedv** [comment]
Now, it's should be fixed.

**Comment by FredoVelcro** [comment]
i confirm : fixed !

**Comment by Vin57** [comment]
For me, this was because i made a `deploy:lock` before `deploy:prepare`.

You have to `prepare`, before doing any `lock`.

Just as : 

```
task('release', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release'
   ...
]);
```
