### ISSUE TITLE
Require single server

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#965]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 

Is it possible to require a single server for tasks? Background: I'm currently creating tasks to pull/push user data from/to remote servers and by nature these should only be executed against a single server. For example pulling the database from all configured servers into the local database does not make sense.

### Steps to reproduce

- Execute `bin/dep pull` (pulls from all servers to local)
- Execute `bin/dep pull <stage>` (pulls from multiple servers of `<stage>` to local)

In both of these cases multiple servers are processed whereas only one should be allowed.

**Comment by mbrodala** [comment]
For the case nothing was passed I can work around this through a bogus [default stage](https://github.com/deployphp/deployer/commit/03f344ad364d5b1176f9afbaa272dd60ae29af6b):

```php
set('default_stage', 'please pass a server or stage name');
```

**Comment by elfet** [comment]
Sorry, don't understand what you are trying to do.

**Comment by mbrodala** [comment]
I guess it's not easy to follow so here we go with a `deploy.php`:

```php
desc('Imports the database from a remote server');
task('db:pull', function() {});

server('foo')->stage('qux');
server('bar')->stage('qux');
```

If I do `dep db:pull` or `dep db:pull qux` now, the task `db:pull` is executed against both `foo` and `bar`. Thus it first downloads and imports the database from `foo` and right afterwards does the same with `bar`. However, the task `db:pull` is only meant to be ran against a single server which cannot be enforced ATM.

**Comment by elfet** [comment]
```php
task('db:pull', function() {})
    ->onlyOn('foo');
```

**Comment by mbrodala** [comment]
@elfet Yes, that works if I know the names of servers beforehand, but not if I provide my task as recipe. The user should be able to execute the `db:pull` task against any server, even if more servers are added later.

**Comment by elfet** [comment]
So `db:pull` should be run on one server, but you do not know which? The first one?

**Comment by mbrodala** [comment]
Correct, it could be any of the servers, the user decides here.

**Comment by elfet** [comment]
|Server 1|Server 2|Server 3|
|--------|--------|---------|
| db:pull |             |               |
|             | task 2   |              |
|             |             |    task 2  |

**Comment by elfet** [comment]
Something like this:
```php
task('db:pull', function() {})
    ->onlyOnce();
```

**Comment by mbrodala** [comment]
Yes, something like this or:

```php
task('db:pull', function() {})
  ->single();
```

This would be similar to `->once()` but instead of running on local it would check if there are currently multiple servers and fail with an exception in this case. I can add a PR to add this to the `SeriesExecutor` and `ParallelExecutor` if you like this idea.

**Comment by elfet** [comment]
It will be cool. But you think it's ok to throw exception?

**Comment by mbrodala** [comment]
I don't like throwing too many exceptions but I don't see a different solution in this case. And besides we'd need to first iterate all possible tasks to check if there is one with the `single` flag. It would not make sense running some tasks on multiple servers only to fail when encountering one task with this flag.

Let me think this through a for bit.

**Comment by elfet** [comment]
@mbrodala i'm closing this for now. Will wait your PR.
