### ISSUE TITLE
 Call to a member function getOutput() on boolean in phar:///usr/local/bin/dep/src/functions.php

### ISSUE THREAD

**Issue by shaynekasai** [deployphp/deployer#967]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.1.0
| Local Machine OS  | OSX
| Remote Machine OS | N/A

### Description 
Calling 
`ask('hello?', 'hihi');`

Getting
PHP Fatal error:  Call to a member function getOutput() on boolean in phar:///usr/local/bin/dep/src/functions.php on line 625

Fatal error: Call to a member function getOutput() on boolean in phar:///usr/local/bin/dep/src/functions.php on line 625

Also composer require symfony/console but result is the same

**Comment by elfet** [comment]
Everything working ok:
```php
<?php
namespace Deployer;

task('list', function () {
    $a = ask('hello?', 'hihi');
    writeln($a);
});
```

```
$ dep
➤ Executing task list
hello? [hihi] j
j
✔ Ok
```
