### ISSUE TITLE
Suggest package instituteweb/deployer-scripts

### ISSUE THREAD

**Issue by ArminVieweg** [deployphp/deployer#968]
Hi,
I've created, based on Deployer and its tasks, a package with a reimplementation of the tasks.

**Their major benefit:** They work on Unix as well as on Windows.

To achieve this I've used league/flysystem and combined it with Deployer configuration.

Additionally, I've split building and deploying tasks, so you can run build tasks locally (or on dedicated deployment server) and keep the requirements of installed services on remotes low.

SSH is required, as well as PHP, composer and an unzip binary.

You find complete README and link to repo on packagist: https://packagist.org/packages/instituteweb/deployer-scripts

I would like to know your thoughts about my approach and maybe this is also useful for other users :)

Thanks,
Armin

**Comment by elfet** [comment]
Hi, this is awesome! A grate work, i think we can adopt something from this.

**Comment by pniederlag** [comment]
Armin, cool stuff. Thx for sharing!

**Comment by elfet** [comment]
I think it will be cool to have some sort of awesome-deployer lists.
