### ISSUE TITLE
POSIX Requirement

### ISSUE THREAD

**Issue by houstona** [deployphp/deployer#969]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Unix
| Remote Machine OS | Docker php:5.6

### Description 
I am trying to deploy in a gitlab setup using .gitlab-ci.yml but am unable to due to the requirement for POSIX is there anywhere around that?

This happens every time I try to deploy:

`Shell on your server is not POSIX-compliant. Please change to sh, bash or similar.  
  Usually, you can change your shell to bash by running: chsh -s /bin/bash`

#### Deploy.php
`<?php
namespace Deployer;
require 'recipe/common.php';
// Configuration

set('repository', 'git@github.com:example/deployer.git');
set('shared_files', [
	'web/.htaccess',
	'.env'
]);
set('shared_dirs', [
	'web/app/uploads'
]);
set('writable_dirs', [
	'web/app/uploads'
]);
set('application_name', 'deployer');
// Servers

server('staging', 'example.com', '1234')
    ->user('user')
    ->password('password')
    ->set('deploy_path', '/var/www/{{application_name}}/staging')
    ->set('branch','develop')
    ->set('stage', 'staging');

// Tasks

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

after('deploy', 'success');`

**Comment by elfet** [comment]
How did you run dep?

**Comment by houstona** [comment]
I ran `php deployer.phar deploy staging` through the gitlab ci using docker.

**Comment by sas05** [comment]
I also have same problem

**Comment by elfet** [comment]
Try run `ssh echo $0` in gitlab ci using docker. Whats output?

**Comment by houstona** [comment]
This is what happens when I do that.

> Warning: Identity file .......... not accessible: No such file or directory.
> ssh: Could not resolve hostname echo: Name or service not known

**Comment by elfet** [comment]
I think error is:

> Warning: Identity file .......... not accessible: No such file or directory.
> ssh: Could not resolve hostname echo: Name or service not known

**Comment by houstona** [comment]
It appears that GitLab can't run in an interactive shell since all jobs have to be automated. Is there a way to run this in a non-interactive shell?

**Comment by houstona** [comment]
I actually found the problem. Deployer wasn't getting the variables I was setting in GitLab and was failing authentication to the server. Passing the variable in directly resolved the issue. Just need to figure out how come its not accepting the gitlab variables. How would I get environment variables?

**Comment by elfet** [comment]
What is your GitLab CI config? In php you can get env variables by `getenv()`

**Comment by houstona** [comment]
I am using hidden variables and was trying to use get() to get the environment variables. I am using getenv() now and it is working fine. The error was confusing though maybe look into error handling when there is an empty or no password?

**Comment by elfet** [comment]
empty or no password for that?
Please, show your gitlab ci config.

**Comment by houstona** [comment]
`stages:
    - deploy
before_script:
    - curl -LO https://deployer.org/deployer.phar
    - mv deployer.phar /usr/local/bin/dep
    - chmod +x /usr/local/bin/dep
    - dep self-update
Deploy to staging:
  stage: deploy
  script:
    - dep deploy:unlock staging 
    - dep deploy staging --revision=$CI_BUILD_REF -v
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - develop
Deploy to production:
  stage: deploy
  script:
    - dep deploy:unlock production 
    - dep deploy production --revision=$CI_BUILD_REF -v
  environment:
    name: production
    url: https://example.com
  only:
    - master
  when: manual`

**Comment by elfet** [comment]
You can omit `dep self-update` as `https://deployer.org/deployer.phar` already contain latest version.

**Comment by houstona** [comment]
Yeah, that is just left over from when I was trying different ways of deploying to try and resolve the problem.
