### ISSUE TITLE
Is there a way to check what stage is set in a task?

### ISSUE THREAD

**Issue by khoanguyen96** [deployphp/deployer#970]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Windows 7
| Remote Machine OS | CentOS 7

### Description 
Was just wondering if there was a way to check what stage was set when deploying, as I'm using a task that seeds the database, but depending on the stage set, it would have to correctly seed the right data.

Thanks!

**Comment by unclead** [comment]
stages are available through `env` and use can use it as below

```
    if (isTesting()) {
        set('keep_releases', 1);
    } else {
        set('keep_releases', 10);
    }
```

```
function isTesting()
{
    $stages = env('stages');
    return reset($stages) === 'testing';
}
```

**Comment by mbrodala** [comment]
Notice that you should use `get('stages')` instead, `env()` is gone in 4.x.

**Comment by khoanguyen96** [comment]
Thank you! I've got it working.

**Comment by klefix** [comment]
But why does `input()->hasArgument('stage')` return `true` while `input()->getArgument('stage')` returns `NULL` ?
Altogether while `var_dump(get('stages'));` returns an array with one entry containing the stage i'm curently deploying to...

**Comment by elfet** [comment]
@klefix looks like a bug. Also i think it will be cool get better API for `get('stages')` (maybe return all stages instead of only one)
