### ISSUE TITLE
Add command init to emulator

### ISSUE THREAD

**Issue by oanhnn** [deployphp/deployer#972]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Add command `dep init` to emulator in homepage of deployer (https://deployer.org)

**Comment by elfet** [comment]
It will be tricky to emulate dialogs in js. Do you really think somebody will type this in emulator?

**Comment by oanhnn** [comment]
Yes. I think it is very intuitive example about a CLI tool

**Comment by elfet** [comment]
@oanhnn can you do it? 😄

**Comment by elfet** [comment]
Well, i have no time for creating this in emulator. Anybody can PR to https://github.com/deployphp/deployer.org
