### ISSUE TITLE
use the ssh-config-file with the actual ssh cmd

### ISSUE THREAD

**Issue by mwr** [deployphp/deployer#979]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | master
| Local Machine OS  | ---
| Remote Machine OS | ---

### Description 
One can provide the server config with a configFile like this:
`$production->configFile('path/to/file');`

In the first place I assumed this file would then be used with the actual ssh command.
But as it turns out is just used to gather some information out of it.

So is there a reason why this is not done?

See here:
https://github.com/deployphp/deployer/blob/master/src/Server/Remote/NativeSsh.php#L51

In my local dev environment I added `-i path/to/file` in the above mentioned class and it worked out well.

**Comment by elfet** [comment]
Config file is used only for getting config about servers.

**Comment by mwr** [comment]
Thanks @elfet for your fast response.
OK, that's what I figured. But is there something preventing us from adding the possibility to use the ssh-config file in the command?
If not I would be happy to create a pull request to add that feature.

**Comment by elfet** [comment]
You want to *not to use* config file?

**Comment by elfet** [comment]
There actually a research #980 from me, i'm going to improve whole ssh system at deployer.

**Comment by mwr** [comment]
I want to use the native ssh implementaion and use the config file as a parameter.
Right now the config file is only used to fetch information.
I want to use it for the actual connection.
Thus adding the possibility to use all the features we have available in the native ssh command like ProxyCommand etc.

Like this:
```
    /**
     * {@inheritdoc}
     */
    public function run($command)
    {
        $serverConfig = $this->getConfiguration();
        $sshOptions = [
            '-A',
            '-q',
            '-i __PATH_TO_SSH_CONFIG_FILE__',
            '-o UserKnownHostsFile=/dev/null',
            '-o StrictHostKeyChecking=no'
        ];
```

And I like the approach of using native ssh :)

**Comment by elfet** [comment]
@mwr i will implement this. All `$sshOptions` should be configurable.

**Comment by mwr** [comment]
@elfet looking forward to that. Will be a great addition.

**Comment by elfet** [comment]
#980

**Comment by pluseg** [comment]
@elfet please close the ticket as it's done.
