### ISSUE TITLE
One release late

### ISSUE THREAD

**Issue by ArnaudTarroux** [deployphp/deployer#982]
Hi,

When I release it seems has a release late.. If I deploy the current folder has the good symlink to realeases/<release_id> But the code executed continue to be this of the prev release, if I execut
`php bin/console cache:clear -e prod`
 to clear the cache, the cache is cleared but the code executed is always the one of the prev release.
If I remove all folders of releases directory except the last one, everything is cool, the code executed is the good one...

Anybody have the same problem ?
I use the Symfony3 recipe.

Thanks :)

**Comment by pdbreen** [comment]
Sounds like php opcode cache isn't being refreshed.  Are you reloading php-fpm or apache / nginx?

**Comment by ArnaudTarroux** [comment]
@pdbreen No I don't reload php or Nginx, I will try for the next deploy. 
Thanks :)

**Comment by ArnaudTarroux** [comment]
This is the solution to this problem ! I reload php-fpm after each deploy.
Thanks @pdbreen :)
