### ISSUE TITLE
Local deployment on production server

### ISSUE THREAD

**Issue by pet1330** [deployphp/deployer#983]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description
Is there any reason Deployer shouldn't be hosted on the production server?

For example, if I have one server which hosts the production site under example.com and a staging site under staging.example.com, is there anything wrong with having a webhook start the deploy script automatically? So having [Travis](https://travis-ci.org) call:

> `example.com/deploy?stage=production&token=supersecretdeploymentkey`

on a successful build to begin the deployment. I have seen that there is a [recipe for local deployment](https://deployer.org/recipes/local), but all the documentation seems to suggest this is for building the app locally and copying it to the production server when using shared hosting or for testing on a development machine.

**Comment by elfet** [comment]
Yes, this is fully possible. Deploy strategy depends on your needs, it can be local build, build server, or build on production server. Last one is most common and most simple for a lot of projects, so this is default behavior. But it's **really** easy to customize it and do your own strategy: there is a common tasks, hooks, and a lot of configurations.
