### ISSUE TITLE
Add previous_release variable

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#991]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | next

### Description 
Implement `previous_release` variable. It should be pointing at previous release path.
Next should be implemented:
* [ ] Correct working on first deploy (cold start)
* [ ] Throw exception on non-deploy context 
* [ ] Documentation

### Links
[Example in deploy:copy_dirs task](https://github.com/deployphp/deployer/blob/master/recipe/deploy/copy_dirs.php#L15)

**Comment by pluseg** [comment]
@elfet Where should `previous_release` variable point to? On last successful build or any last?

**Comment by elfet** [comment]
In deploy context on last release, in non-deploy context on second to last release.

**Comment by antonmedv** [comment]
Done a7f54ac65e89465d43c6b4b61e6db9f32ec3c23d
