### ISSUE TITLE
Не может найти класс

### ISSUE THREAD

**Issue by vtvz** [deployphp/deployer#992]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.0
| Local Machine OS  | Ubuntu 14.04 php5.6
| Remote Machine OS | The same

### Description 
```
$ dep init
PHP Fatal error:  Class 'Deployer\Component\PharUpdate\Console\Helper' not found in phar:///usr/local/bin/dep/src/Console/Application.php on line 68
```

### Steps to reproduce
Установил так:

```
curl -LO https://deployer.org/deployer.phar
mv deployer.phar /usr/local/bin/dep
chmod +x /usr/local/bin/dep
```

### Content of `deploy.php`
```php
нет
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by elfet** [comment]
Fixed.

**Comment by vtvz** [comment]
Здорово. Оперативненько)

**Comment by tchapi** [comment]
Hi, can you tag a release with this fix ?

**Comment by tchapi** [comment]
PS — I don't see which commit fixes this. It seems to be https://github.com/deployphp/deployer/commit/b76b25ded6cb28392f3ce47b55eee61e922e15f6 that provoked this bug, since phar-update moved to dev requirements

**Comment by elfet** [comment]
@tchapi its only effects phar build

**Comment by elfet** [comment]
@tchapi yeah, there was a bug. Fixed and tagged new release.

**Comment by tchapi** [comment]
Superb, thank you !
