### ISSUE TITLE
deployer/phar-update

### ISSUE THREAD

**Issue by ENM1989** [deployphp/deployer#993]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2

### Description 
*The deployer/phar-update requirement needs to be in the require section, not in require-dev, because it is used in the console application class.*

### Steps to reproduce
Set Deployer 4.2 as a composer requirement.
Run deploy.

### Content of `deploy.php`
```php
PHP Fatal error:  Uncaught Error: Class 'Deployer\Component\PharUpdate\Console\Helper' not found in /vendor/deployer/deployer/src/Console/Application.php:68
Stack trace:
#0 /vendor/symfony/console/Application.php(83): Deployer\Console\Application->getDefaultHelperSet()
#1 /vendor/deployer/deployer/bin/dep(100): Symfony\Component\Console\Application->__construct('Deployer', 'v4.2.0')
#2 {main}
  thrown in /vendor/deployer/deployer/src/Console/Application.php on line 68
```

### Output log
*With enabled option for verbose output `-vvv`.*

**Comment by elfet** [comment]
Fixed it with another approach: a2ddd5a058d5a412b300cffab8ba6e333dfaeea5

**Comment by elfet** [comment]
Tagged release.

**Comment by ENM1989** [comment]
Thanks for fixing.
