### ISSUE TITLE
deploy file or dir mappings

### ISSUE THREAD

**Issue by sourcerer-mike** [deployphp/deployer#999]
### Description 

Add the posibility to symlinks files around.
You want that when an application needs symlinks from around the machine or other places within the repo.

Or is it possible yet?

### Content of `deploy.php`
```php
set('mapped_files', [
	'lib/.htaccess.prod' => 'srv/www/.htaccess',
	'/usr/bin/false' => '/srv/www/.yomama',
]);

after('deploy:shared', 'deploy:mappings');
task('deploy:mappings', function () {
	foreach ( get('mapped_files') as $from => $to ) {
		run("cd {{release_path}} && {{bin/symlink}} " . $from . " " . $to );
	}
});
```

Hint: People might come up with some recursion like modman does it ;)

**Comment by elfet** [comment]
Your example is solution. This is how its done.

**Comment by sourcerer-mike** [comment]
Your reply is a stub. This is a feature request.

**Comment by elfet** [comment]
I think this task is really simple to implement youself and everybody already using something like this if needed. But adding this to common recipe will requre a docs, and tests. New functionality like this brings unnecessary complications and new api for a simple symlink function. So i, as maintainer, have right to reject this feature request. Sorry about that.
